### ISSUE TITLE
Destroying `google_container_node_pool` fails because instance group persists

### ISSUE THREAD

**Issue by hawksight** [terraform-providers/terraform-provider-google#1000]
Destroying `google_container_node_pool` fails because instance groups persist. They are resized from counts of 1 to counts of 0. But the instance groups are not actually removed.

This breaks the removal of other resources subsequently. As the node pool creation created they instance groups, it should remove them upon deletion.

### Terraform Version
```
Terraform v0.11.2
+ provider.google v1.5.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- google_container_node_pool

### Terraform Configuration Files
```hcl
resource "google_container_node_pool" "pools" {
  count         = "${var.POOL_COUNT}"

  name          = "${var.CLUSTER_VPC}-np-${count.index + 1}"
  cluster       = "${var.CLUSTER_NAME}"
  zone          = "${var.CLUSTER_ZONE}"
  node_count    = "${var.CLUSTER_COUNT}"

  node_config {
    machine_type     = "${var.NODE_MACHINE}"
    disk_size_gb     = "${var.NODE_DISK_SIZE}"
    local_ssd_count  = "${var.NODE_SSD}"
    service_account  = "${var.NODE_ACCOUNT}"
    image_type       = "${var.NODE_IMAGE}"
    oauth_scopes = [
      "compute-rw",
      "storage-ro",
      "logging-write",
      "monitoring",
    ]
    labels {
      sopost_env     = "${var.META_ENV}"
      region         = "${var.META_REGION}"
      gcloud_project = "${var.META_PROJECT}"
      zone           = "${var.CLUSTER_ZONE}"
    }
    tags             = [
      "${var.META_REGION}",
      "${var.CLUSTER_NAME}",
      "${var.CLUSTER_SUB}"
    ]
  }

  depends_on = ["google_container_cluster.cluster"]
}

```

### Debug Output
N/A - didn't have anyrthing set at the time. Will follow up when I can test a basic setup.

### Panic Output
N/A (not sure what this is? just the error output? - If so, see Actual Behaviour)

### Expected Behavior
Expected terraform to destroy a node pool completely - including the instance groups which it created when the node pool is created.

### Actual Behavior
The instance groups resize from a count of '1' to '0' but are not destroyed themselves.

Terraform then errors stating that it cannot  delete the node pool's:
```
module.cluster.google_container_node_pool.pools: Still destroying... (ID: us-central1-a/k8s-du/vpc-du-np-1, 7m0s elapsed)
module.cluster.google_container_node_pool.pools: Still destroying... (ID: us-central1-a/k8s-du/vpc-du-np-1, 7m10s elapsed)
Error: Error applying plan:

1 error(s) occurred:

* module.cluster.google_container_node_pool.pools (destroy): 1 error(s) occurred:

* google_container_node_pool.pools: Error waiting for deleting GKE NodePool:
	(1) Google Compute Engine: The instance_template resource 'projects/xxxxx/global/instanceTemplates/gke-k8s-du-vpc-du-np-1-58da7e47' is already being used by 'projects/xxxxx/zones/us-central1-b/instanceGroupManagers/gke-k8s-du-vpc-du-np-1-58da7e47-grp'
	(2) Google Compute Engine: The instance_template resource 'projects/xxxxxx/global/instanceTemplates/gke-k8s-du-vpc-du-np-1-7955b73e' is already being used by 'projects/xxxxx/zones/us-central1-a/instanceGroupManagers/gke-k8s-du-vpc-du-np-1-7955b73e-grp'
	(3) Google Compute Engine: The instance_template resource 'projects/xxxxx/global/instanceTemplates/gke-k8s-du-vpc-du-np-1-4afbbb9b' is already being used by 'projects/xxxxx/zones/us-central1-c/instanceGroupManagers/gke-k8s-du-vpc-du-np-1-4afbbb9b-grp'
```

The node pool appears gone in the GKE cluster via the console. However the instance groups remain when looking under Compute -> Instance Groups on the gcloud console.

`terraform state list` shows the node pool as deleted. However the instance groups being there will stop the deletion of other resources, such as the subnet and VPC in which they reside.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Main.tf with: `google_container_cluster` and  `google_container_node_pool`. Specify a `depends_on` for the node pool, on the container cluster.
2. `terraform plan`
3. `terraform apply`
4. `terraform plan -destroy -out plan` - should work just fine
5. `terraform apply plan` - Will attempt to delete node pool but will only resize down to 0.

### Temp solution
Manually remove the instance groups, plan destroy and apply again.

### Important Factoids
My code is modularised so node pool, and container cluster are in the module (along with firewall) - which is fairly normal. Nothing extraordinary about it.

### References
I discovered this when attempting to resolve another issue i raised: #831

**Comment by danawillow** [comment]
Hmm, I'm having trouble reproducing this. What does your configuration look like for `google_container_cluster`?

Here's the config I tried testing this with:
```
provider "google" {}

resource "google_compute_network" "network" {
  name                    = "is-1000"
  auto_create_subnetworks = "false"
}

resource "google_compute_subnetwork" "subnet" {
  name          = "is-1000"
  ip_cidr_range = "10.0.0.0/16"
  network       = "${google_compute_network.network.self_link}"
  region        = "us-central1"
}

resource "google_container_cluster" "cluster" {
  name               = "is-1000"
  zone               = "us-central1-a"
  initial_node_count = 1
  network            = "${google_compute_network.network.name}"
  subnetwork         = "${google_compute_subnetwork.subnet.name}"
}

resource "google_container_node_pool" "np" {
  name       = "is-1000"
  cluster    = "${google_container_cluster.cluster.name}"
  zone       = "us-central1-a"
  node_count = 1
}
```
Then I tried removing the node pool, which succeeded.

**Comment by hawksight** [comment]
sorry I haven't had time to drop a copy of my config in but I can reproduce consistently with the following [gist](https://gist.github.com/hawksight/5b442cdc33ba00ca638af861dc0a7d74)

Sorry for all the vars, its my own module, so to make it easier, this is the dev config I use to build with it. The output should be a cluster with 1 additional nodepool, - 6 nodes in total:
```hcl
module "cluster" {
  source          = "../terraform-modules/gcloud-k8s"

  META_PROJECT    = "${var.G_PROJECT}"
  META_REGION     = "${var.G_REGION}"
  META_ENV        = "dev"

  CLUSTER_VPC     = "${module.network.VPC_NAME}"
  CLUSTER_SUB     = "${module.network.SUB_NAME[0]}"
  CLUSTER_NAME    = "k8s-du"

  CLUSTER_ZONE    = "us-central1-a"
  CLUSTER_ZONES   = ["us-central1-b", "us-central1-c"]
  CLUSTER_VERSION = "1.7.11-gke.1"

  NODE_MACHINE    = "g1-small"
  FW_PORTS        = ["80", "443"]
  POOL_COUNT      = "1"
}
```

The actual node pool resource does go away, although It always errors out. I then have to go and delete the instance groups which by that time have gone to 0 nodes, but the instance group still exists.

It's possible the issue might have something to do with either:
* the fact its a multi zone cluster, hence multiple instance groups?
* or that I am using a count on the `google_container_node_pool` resource?

**Comment by danawillow** [comment]
Weird, I used your updated config and I'm still not getting an error.

Paging @rosbo / @paddycarver / @ndmckinley , either of you want to give this a try and see if you can get a repro?

**Comment by hawksight** [comment]
Apologies for a long silence but I think this can be closed now. 

I no longer seem to be able to reproduce this as I have been building / tearing down a dev cluster and have no had the error appear.
Checked in compute and the instance groups are removed appropriately. So in this case It may have just been something on the google end perhaps.

**Comment by paddycarver** [comment]
Hm. Weird. I'll take a closed issue, though! Let us know if it resurfaces. :) Thanks for chiming back in!

**Comment by cepefernando** [comment]
Seeing the very same issue on my end, the node pool is resized from counts of 1 to counts of 0. But the instance groups are not actually removed.

`
* module.google_k8s.google_compute_subnetwork.primary (destroy): 1 error(s) occurred:

* google_compute_subnetwork.primary: Error deleting subnetwork: googleapi: Error 400: The subnetwork resource 'projects/xxx/regions/europe-west4/subnetworks/vid-primary' is already being used by 'projects/xxx/zones/europe-west4-b/instanceGroupManagers/gke-vid-primary-autoscaling-9a8b5c67-grp', resourceInUseByAnotherResource

`

My `google_container_node_pool` is as follows: 
`resource "google_container_node_pool" "primary_autoscaling" {
  name = "primary-autoscaling"

  cluster = "${google_container_cluster.primary.name}"

  # NOTE: Do NOT use node_count in combination with autoscaling
  autoscaling {
    max_node_count = "${var.autoscalable_cluster_max_size}"
    min_node_count = "${var.autoscalable_cluster_min_size}"
  }

  node_config {
    labels          = "${var.labels}"
    machine_type    = "${var.machine_type}"
    oauth_scopes    = "${var.oauth_scopes}"
    service_account = "${google_service_account.k8s_node.email}"
    tags            = "${concat(list("autoscale"), local.tags)}"
  }
}`

I have to manually remove the template in order to continue with the `destroy`

**Comment by danawillow** [comment]
@cepefernando are you trying to delete only the node pool, or the node pool and the cluster? Would you mind sharing the config for `google_container_cluster.primary`, as well as the output from `terraform plan` and debug logs (https://www.terraform.io/docs/internals/debugging.html)

**Comment by cepefernando** [comment]
Thanks for your reply @danawillow , I'm trying to delete the node pool and the cluster, here is the config for the `google_container_cluster.primary`:

`resource "google_container_cluster" "primary" {
  name                     = "${var.name}"
  project                  = "${var.project}"

  depends_on               = [
    "google_project_iam_binding.compute_network_users",
    "google_project_iam_binding.container_admins",
    "google_project_iam_binding.container_cluster_admins",
    "google_project_iam_binding.container_viewers",
    "google_project_iam_binding.dns_admins",
    "google_storage_bucket_iam_binding.image_store_admins",
    "google_storage_bucket_iam_binding.image_store_readers",
  ]

  network                  = "${google_compute_network.primary.name}"
  subnetwork               = "${google_compute_subnetwork.primary.*.name[0]}"

  # NOTE: Not using `region` as it is still in Beta as of 2018-04-14
  zone                     = "${var.zone}"
  additional_zones         = "${var.additional_zones}"

  enable_legacy_abac       = false

  node_pool = [{
    name = "default-pool"
    node_count= 0
  }]

  remove_default_node_pool = false
  # Client Management
  master_auth {
    username = "${var.gke_username}"
    password = "${var.gke_password}"
  }

  # WARN: Beta feature, but there is no other documented way to create a
  # cluster without external IP's and since we only get 8 external IP's within
  # the default quota, we'll have to make due.
  private_cluster          = true

  cluster_ipv4_cidr        = "${var.cluster_ipv4_cidr}"
  master_ipv4_cidr_block   = "${var.master_ipv4_cidr}"

  ip_allocation_policy {
    cluster_secondary_range_name  = "${var.name}-primary-pod-range"
    services_secondary_range_name = "${var.name}-primary-service-range"
  }

  master_authorized_networks_config = {
    cidr_blocks = [
      {
        "cidr_block" = "0.0.0.0/0",
        "display_name" = "All"
      }
    ]
  }

  lifecycle {
    ignore_changes = ["node_pool"]
  }
}
`

**Comment by danawillow** [comment]
Thanks! Let me know when you have plan output and debug logs ready and I'll take a look.
