### ISSUE TITLE
ignore_changes on node_config doesn't seem to work

### ISSUE THREAD

**Issue by Stono** [terraform-providers/terraform-provider-google#1002]
I have the following on my google_container_cluster
```
  lifecycle {
    ignore_changes = ["initial_node_count", "network_policy", "node_config"]
  }
```

But as you can see, it's trying to rebuild:
```
      node_config.0.disk_size_gb:                                              "200" => "100" (forces new resource)
      node_config.0.image_type:                                                "COS" => <computed>
      node_config.0.labels.%:                                                  "1" => "0" (forces new resource)
      node_config.0.labels.purpose:                                            "default" => "" (forces new resource)
```

**Comment by Stono** [comment]
Ahhh, 
I've figured this out.

There was another resource which is not included in my `ignore_changes` block, which was causing the rebuild.  I actually think we could improve this by only showing `(forces new resource)` for things which are actually causing the change (ie if they're in the ignore block, they shouldn't show that message).

**Comment by danawillow** [comment]
Closing this since it appears solved. If you have suggestions on Terraform things that aren't google-specific, feel free to file an issue at github.com/hashicorp/terraform!
