### ISSUE TITLE
Error importing google_compute_network/google_compute_subnetwork when project not set in provider

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-google#1006]
I don't have `project` set in my `google` provider (either explicitly or implicitly via environment variable) and want to import networks and subnets via `terraform import`:
```
terraform import google_compute_network.net net-xxxxxx
google_compute_network.net: Importing from ID "net-xxxxxx"...
google_compute_network.net: Import complete!
  Imported google_compute_network (ID: net-xxxxxx)
google_compute_network.net: Refreshing state... (ID: net-xxxxxx)

Error: google_compute_network.net (import id: net-xxxxxx): 1 error(s) occurred:

* import google_compute_network.net result: net-xxxxxx: google_compute_network.net: project: required field is not set
```
```
terraform import google_compute_subnetwork.subnet us-east4/subnet-xxxxxx
google_compute_subnetwork.subnet: Importing from ID "us-east4/subnet-xxxxxx"...
google_compute_subnetwork.subnet: Import complete!
  Imported google_compute_subnetwork (ID: us-east4/subnet-xxxxxx)
google_compute_subnetwork.subnet: Refreshing state... (ID: us-east4/subnet-xxxxxx)

Error: google_compute_subnetwork.subnet (import id: us-east4/subnet-xxxxxx): 1 error(s) occurred:

* import google_compute_subnetwork.subnet result: us-east4/subnet-xxxxxx: google_compute_subnetwork.subnet: project: required field is not set
```

**Comment by ewbankkit** [comment]
It's the calls to `getProject` [here](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_network.go#L139) and [here](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_subnetwork.go#L191) that return the error.

Will need to add an additional, optional part to the ID specified to `terraform import` that is the project ID to handle this case.

**Comment by ewbankkit** [comment]
The better solution seems to be to set the `GOOGLE_PROJECT` or equivalent environment variable before running `terraform import`:
```
GOOGLE_PROJECT=abcd1234 terraform import google_compute_network.net net-xxxxxx
GOOGLE_PROJECT=abcd1234 terraform import google_compute_subnetwork.subnet us-east4/subnet-xxxxxx
```

**Comment by tdmalone** [comment]
@ewbankkit Thanks - the above workaround was helpful. This might be worth reopening though, because this should be added to the docs: https://www.terraform.io/docs/providers/google/r/compute_network.html#import
