### ISSUE TITLE
Route resource's priority parameter should be optional

### ISSUE THREAD

**Issue by jphalip** [terraform-providers/terraform-provider-google#1009]
### Terraform Version
+ Terraform v0.11.2
+ provider.google v1.5.0

### Affected Resource(s)

- google_compute_route

### Debug Output

```
Error: google_compute_route.my_route: "priority": required field is not set
```

### Expected Behavior
The route priority should be optional and default to 1000, similarly to the "gcloud" command [counterpart](https://cloud.google.com/sdk/gcloud/reference/compute/routes/create).

### Actual Behavior
The route resource requires you to provide a priority.

**Comment by albertomurillo** [comment]
I just faced this. Will you work on a PR?
