### ISSUE TITLE
google_compute_route fails to create on first run

### ISSUE THREAD

**Issue by albertomurillo** [terraform-providers/terraform-provider-google#1010]
`google_compute_route` creation fails on first run when a custom `google_compute_subnetwork` is defined

### Terraform Version
```➜  terraform git:(master) ✗ terraform version
Terraform v0.11.2
+ provider.google v1.5.0
```

### Affected Resource(s)
- google_compute_route

### Terraform Configuration Files
```hcl
provider "google" {
  credentials = "${file("../account.json")}"
  project     = "${var.project_id}"
  region      = "${var.region}"
}

resource "google_compute_network" "default" {
  name                    = "kubernetes-the-hard-way"
  auto_create_subnetworks = "false"
}

resource "google_compute_subnetwork" "default" {
  name          = "kubernetes"
  ip_cidr_range = "10.240.0.0/24"
  network       = "${google_compute_network.default.self_link}"
}

resource "google_compute_route" "default" {
  name        = "kubernetes-route-10-200-0-0-24"
  dest_range  = "10.200.0.0/24"
  network     = "${google_compute_network.default.self_link}"
  next_hop_ip = "10.240.0.20"
  priority    = 1000
}
```

### Debug Output
https://gist.github.com/albertomurillo/25fe037da7d66f04476a3a300538592e

### Expected Behavior
All resources created

### Actual Behavior
1. `google_compute_network` is created
2. `google_compute_subnetwork` creation starts
3. `google_compute_route` creation starts before `google_compute_subnetwork` finishes
4.  `google_compute_route` fails
5. `google_compute_subnetwork` succeeds

### Steps to Reproduce
1. `terraform apply`

### References

**Comment by danawillow** [comment]
Hey @albertomurillo, you're going to want to use depends_on for this: https://www.terraform.io/docs/configuration/resources.html#explicit-dependencies. I'm going to go ahead and close this issue since if I'm understanding the problem correctly it's WAI, but thanks for the report!
