### ISSUE TITLE
Lack of functionality for google_compute_network_peering connecting multiple projects

### ISSUE THREAD

**Issue by JanisOrlovs** [terraform-providers/terraform-provider-google#1036]
Hi there,

Terraform module google_compute_network_peering is missing options to connect networks located in different projects. 

For example:

need to connect project-a and project-b, but there are no such module options.

**Comment by emilymye** [comment]
The `network`/`peer_network` fields ([docs](https://www.terraform.io/docs/providers/google/r/compute_network_peering.html)) accept self-links with the project defined, i.e. 
```
data "google_compute_network" "networkA" {
  name = "defaultA"
  project = "projectA"
}

data "google_compute_network" "networkB" {
  name = "defaultB"
  project = "projectB"
}

resource "google_compute_network_peering" "peeringAB" {
  name = "peeringAB"
  network = "${google_compute_network.networkA.self_link}" 
  peer_network =  "${google_compute_network.networkB.self_link}"
}

resource "google_compute_network_peering" "peeringBA" {
  name = "peeringBA"
  network = "${google_compute_network.networkB.self_link}"
  peer_network =  "${google_compute_network.networkA.self_link}"
}

...
```
would connect networkA in project A to networkB in project B. The `self_link`s look like `https://www.googleapis.com/compute/v1/projects/projectA/global/networks/defaultA`, so there is a project associated with the network that Terraform will use. 

Is that what you meant by connecting networks in different projects? Or is it that this option isn't working for you as expected?

**Comment by JanisOrlovs** [comment]
Hello,
Thanks, I'm marking this as closed.
