### ISSUE TITLE
Add support for managing Build Triggers in Container Builder

### ISSUE THREAD

**Issue by eik3** [terraform-providers/terraform-provider-google#1039]
It would be nice if we could manage Build Triggers with Terraform.
There's an [REST API for that](https://cloud.google.com/container-builder/docs/api/reference/rest/v1/projects.triggers).

**Comment by justinholmes** [comment]
I've started work on this, currently it creates a build trigger.

**Comment by justinholmes** [comment]
Delete and updating working as well.

**Comment by justinholmes** [comment]
Initial version https://gist.github.com/justinholmes/af62356ebd485e4b63e1e3153baef392

**Comment by justinholmes** [comment]
Will sort out a PR once unit tests are done.

**Comment by mathyourlife-fitbit** [comment]
Is there a branch/fork somewhere with the work in progress on this, or just the gist?

**Comment by mathyourlife-fitbit** [comment]
#1357 not as fully featured as your gist, @justinholmes , but possibly a place to start.

**Comment by edevil** [comment]
Is this stalled?

**Comment by naseemkullah** [comment]
@mathyourlife-fitbit @justinholmes 

Hello, are we able to `terraform import` cloud build triggers as well?

Also can we create cloud build triggers for GitHub repos? My understanding is that it only works with GCP's Cloud Source Repos.. I'm looking for a way to use TF to create build triggers for private GitHub repos.

Many thanks in advance.

**Comment by rileykarson** [comment]
It looks like container builder was an old name for Cloud Build; we have support for build triggers and have for a while; I'm closing this out.
