### ISSUE TITLE
Problem with the 'port' in the google_compute_backend_service

### ISSUE THREAD

**Issue by meverone** [terraform-providers/terraform-provider-google#1043]
## Terraform Version
Terraform v0.11.3

## Terraform Configuration Files

```
data "null_data_source" "vars" {
  inputs = {
    port_name = "${var.prefix}-${var.port}"
  }
}

resource "google_compute_https_health_check" "default" {
  name = "${data.null_data_source.vars.outputs.port_name}"
  request_path = "/_healthcheck.html"
  port = "${var.port}"
}

resource "google_compute_backend_service" "default" {
  name = "${data.null_data_source.vars.outputs.full_name}"
  description = ""
  port_name = "${data.null_data_source.vars.outputs.port_name}"
  protocol = "HTTPS"
  timeout_sec = 1200
  enable_cdn = "${var.enable_cdn}"
  connection_draining_timeout_sec = 0

  backend {
    group = "${var.backends[0]}"
  }

  backend {
    group = "${var.backends[1]}"
  }

  backend {
    group = "${var.backends[2]}"
  }

  backend {
    group = "${var.backends[3]}"
  }

  health_checks = [
    "${google_compute_https_health_check.default.self_link}"]
}
```

Hi, 

I'm having a problem with proper configuring my https target proxy namely, I'm not able to forward traffic to the specific backend (which base on ports).
The code above let's say work correctly because it creates named port in instance groups from what I saw in the console - which is weird because I'm not defining it (I only set the name). But it is not setting `port` in back-end service when it's configuring backends.

PS
I know that `port` attribute is deprecated in favor of `port_name`.

## Expected behavior 

Backends should have set port from `named port` service

**Comment by danawillow** [comment]
Hey @meverone, I'm having a bit of trouble understanding what the issue you're having is. Are you getting an error message? Or is it that you expected the resource to have a certain property which isn't getting set? Or are you expecting the resource not to have a certain property but it is being set? Or something else?

**Comment by meverone** [comment]
Hey,
I would like to have the ability to set port for backends e.g. 
```
resource "google_compute_backend_service" "default" {
  name = "${data.null_data_source.vars.outputs.full_name}"
  description = ""
  port_name = "${data.null_data_source.vars.outputs.port_name}"
  protocol = "HTTPS"
  timeout_sec = 1200
  enable_cdn = "${var.enable_cdn}"
  connection_draining_timeout_sec = 0

  backend {
    group = "${var.backends[0]}"
    port = 3000
  }
  ...
}
```

**Comment by danawillow** [comment]
Hey @meverone, `port` isn't a property of a backend though, it's a property of the backend service as a whole: https://cloud.google.com/compute/docs/reference/rest/v1/backendServices

**Comment by meverone** [comment]
But from what I checked, there is no possibility to set `port` in BackendService.
Only `named_port` is created somehow, but after that, I have to set manually the port for BackendService.

**Comment by danawillow** [comment]
I see. What's preventing you from using `port_name`?

**Comment by meverone** [comment]
In this case, I would have to modify `google_compute_instance_group` (in my case, I have to "dynamically" generate terraform file) but I wanted to avoid this.
or might be there is another way to set port?

**Comment by danawillow** [comment]
The `google_compute_instance_group` resource only supports named ports, so every port that's in there has a name associated with it that you could use for the `port_name` field.

**Comment by meverone** [comment]
Hey,

Sorry, I totally forgot about this ticket.
I solved this in a different way. You can close this ticket.

**Comment by danawillow** [comment]
Ok, glad to hear you were able to figure something out!

**Comment by jayhding** [comment]
@meverone hi, could you describe more how you solved this issue? Thanks
