### ISSUE TITLE
google_compute_disk: Hot-remove of the root disk is not supported

### ISSUE THREAD

**Issue by nodesocket** [terraform-providers/terraform-provider-google#1048]
Building a `google_compute_disk` from a snapshot:

```tf
resource "google_compute_disk" "blog" {
    name = "blog"
    zone = "us-central1-a"
    snapshot = "blog-2018-02-05-2"
    type = "pd-ssd"
    size = 10
}
```

I updated the snapshot manually and bumped the snapshot, but now when trying to run `terraform apply` it is erroring with:

```
* google_compute_disk.blog: Hot-remove of the root disk is not supported.
```

Ideas?

**Comment by ndmckinley** [comment]
Can you post the output of `terraform plan`?  If it's trying to destroy and recreate the disk, that would explain it - you'd need to shut down the instance first.  That kind of cross-resource update dependency can't be modeled by Terraform, to the best of my knowledge.

**Comment by nodesocket** [comment]
@ndmckinley should Terraform just destroy the disk and recreate it from the new snapshot?

**Comment by paddycarver** [comment]
Unfortunately, I don't know that even that would be allowed--from my understanding, a boot disk, once attached to a resource, cannot be unattached or deleted until the instance is deleted or stopped.

**Comment by ndmckinley** [comment]
As it stands, I think `terraform apply` is giving you the correct error, because GCE does not allow this without taking down the instance.  You can work around this by making a destroy/create change to the instance, like changing the name, which will destroy and recreate in the right order.

**Comment by nodesocket** [comment]
Ok makes sense. I'll close this issue.
