### ISSUE TITLE
google_compute_disk not available causes google_compute_instance_template to fail in later apply

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#1052]
First apply fails in "not have enough resources"
```
$ terraform apply
...
google_compute_disk.i_docker.0: The zone 'projects/my-project/zones/europe-west3-a' does not have enough resources available to fulfill the request.  Try a different zone, or try again later.
```

Then the second apply fails because the disk was not created:
```
$ terraform apply
...
* google_compute_instance_template.i: 1 error(s) occurred:

* google_compute_instance_template.i[2]: index 2 out of range for list google_compute_disk.i_docker.*.name (max 2) in:

${google_compute_disk.i_docker.*.name[count.index]}
```

had to `terraform state rm "google_compute_disk.i_docker[0]"` it to get apply working again

**Comment by danawillow** [comment]
Hey @matti, I'd need to see your config to know what's going on. Mind sharing it?

**Comment by matti** [comment]
Sorry, can't really share any config that would be of any help: This only triggers when you get the "The zone 'projects/my-project/zones/europe-west3-a' does not have enough resources available to fulfill the request.  Try a different zone, or try again later." so it's also hard to run without running in a loop for days or so. I've seen this twice during the last two weeks and I've been running terraform apply/destroy ~30 times a day.

**Comment by danawillow** [comment]
Sure, but in order to help debug the issue, I need to know what your .tf file looks like, what the output of terraform plan looks like, etc. Right now it doesn't look like anything google-specific: that error looks to be because you're trying to access a disk that doesn't exist (maybe you're supposed to have the same number of instance templates and disks and after the first apply you don't?) Otherwise I'm not sure what you'd like us to do with this report.

**Comment by matti** [comment]
Umm, yes the latter error is not google-specific, but if you have a look at the first error that comes from the Google API:

```
google_compute_disk.i_docker.0: The zone 'projects/my-project/zones/europe-west3-a' does not have enough resources available to fulfill the request.  Try a different zone, or try again later.
```

This is what makes the disk not exist in the next apply - so in the event when the google cloud runs out of disks (!) then the state for `google_compute_disk` is stored as it would exist.
