### ISSUE TITLE
Request: Support creating BigQuery table definitions.

### ISSUE THREAD

**Issue by hden** [terraform-providers/terraform-provider-google#1055]
Support creating BigQuery table definitions i.e. tables with external data sources.
https://cloud.google.com/bigquery/external-table-definition

### Affected Resource(s)
- google_bigquery_table

**Comment by rickard-von-essen** [comment]
See GoogleCloudPlatform/magic-modules#1466

**Comment by allanlegalstart** [comment]
should be fixed by https://github.com/terraform-providers/terraform-provider-google/pull/3602 :)

**Comment by megan07** [comment]
Thanks @hden for opening this issue. It's been closed with #3602 and has been released.
