### ISSUE TITLE
Allow specifying accelerators in cluster node_config

### ISSUE THREAD

**Issue by kmontag** [terraform-providers/terraform-provider-google#1067]
Beta support for GPUs on Kubernetes clusters has been released: https://cloud.google.com/kubernetes-engine/docs/concepts/gpus

It looks like they can be added via REST API using the `accelerators` field in a node pool configuration, e.g. (when creating a cluster):

```
POST https://container.googleapis.com/v1/projects/foo/zones/us-west1-a/clusters
{
  "cluster": {
    "name": "gpu-test",
    "zone": "us-west1-a",
    "nodePools": [
      {
        "name": "default-pool",
        "initialNodeCount": 1,
        "config": {
          // ...
          "accelerators": [
            {
              "acceleratorCount": 1,
              "acceleratorType": "nvidia-tesla-k80"
            }
          ]
        },
        // ...
      }
    ],
    // ...
  }
}
```

Would be great if this could be supported in the `node_config` block for `google_container_cluster` / `google_container_node_pool`.

Thanks!

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.11.3
+ provider.google v1.5.0
```

### Affected Resource(s)
- google_container_cluster
- google_container_node_pool

**Comment by dhague** [comment]
I have the same requirement - currently hacking on the code for it, unless someone else has already started work on this?

**Comment by ndmckinley** [comment]
That's great!  Tag me in the PR and I'll expedite the review.

**Comment by dhague** [comment]
Almost done with this - in case anyone is desperate for it, the code [here](https://github.com/dhague/terraform-provider-google/commit/9af59a1d0f95dcb7c4034bc147d25d7b18f50b43) works, I just need to tweak the tests to pass (so caveat emptor!). I'm on vacation for a long weekend, so I expect to finish this on Tuesday.

**Comment by thomasjungblut** [comment]
I can also pick this up if there's anything urgent, synced with Darren yesterday on what's missing.
