### ISSUE TITLE
terraform force-unlock explodes in ParseInt

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#1072]
Not sure if this is this provider issue or not:

Terraform v0.11.3

backend with gcs
```
terraform {
  backend "gcs" {
    bucket = "my-terraform" 
    prefix = "kontena_platform"
  }
}
```

lock goes stale..
```
Error: Error locking state: Error acquiring the state lock: writing "gs://my-terraform/kontena_platform/dolan.tflock" failed: googleapi: Error 412: Precondition Failed, conditionNotMet
Lock Info:
  ID:        c0f204fa-5887-e159-04f8-329a90cb072a
  Path:
  Operation: OperationTypeApply
  Who:       mpa@mx.local
  Version:   0.11.3
  Created:   2018-02-11 17:33:29.330612 +0000 UTC
  Info:
``
..force-unlock  doesn't work
```
$ terraform force-unlock -force c0f204fa-5887-e159-04f8-329a90cb072a
Failed to unlock state: strconv.ParseInt: parsing "c0f204fa-5887-e159-04f8-329a90cb072a": invalid syntax
```

**Comment by danawillow** [comment]
Hey @matti, the gcs backend is part of Terraform core- you'll want to file an issue at https://github.com/hashicorp/terraform instead. I'll go ahead and close this one- good luck!

**Comment by matti** [comment]
https://github.com/hashicorp/terraform/issues/17328

**Comment by matti** [comment]
(fixed in there)
