### ISSUE TITLE
metadata startup-script for google_compute_instance broken after 1.4.0

### ISSUE THREAD

**Issue by mytran** [terraform-providers/terraform-provider-google#1079]
In my google_compute_instance resource, I have a metadata block with startup script defined instead of the **metadata_startup_script** argument because I do not want the VM to get recreated when it changes.
ie
```
  metadata = {
    startup-script = "MYSCRIPT"
  }
```

This works fine for me on 1.4.0 but both 1.5.0 and 1.60, it keeps on thinking that I have **metadata_startup_script** set when I run terraform plan and tries to destroy it.
```
      metadata.startup-script:  "" => "MYSCRIPT"
      metadata_startup_script:  "MYSCRIPT" => "" (forces new resource)
```

Looking through the source, I believe this line added for import support broke this:
https://github.com/terraform-providers/terraform-provider-google/blob/e1323489baa0e70e135fbecf18675e8bd89ccfc1/google/resource_compute_instance.go#L785

**Comment by ndmckinley** [comment]
I agree that that's broken and that you've found the reason - we'll need a diff-suppress for diffs specifically adding something to metadata.startup-script and removing that exact thing from metadata_startup_script.  I'll look into it.

**Comment by ndmckinley** [comment]
Ah, bummer, I've misunderstood diff suppress.  :-1: I'll figure out another solution.

**Comment by ndmckinley** [comment]
That PR will fix it going forward, but for your existing instances you'll need to either do state munging to get the state to reflect the config, or a full `terraform destroy` / `terraform apply`.  I can't figure a way around that, unfortunately.

**Comment by gwoo** [comment]
`terraform state rm ADDRESS...` worked for me.
