### ISSUE TITLE
Feature request: Add the ability to retrieve a data source based on its self_link

### ISSUE THREAD

**Issue by jphalip** [terraform-providers/terraform-provider-google#1082]
Most data sources require multiple parameters (most often the resource's name, project and region). In cases where one already has a resource's self_link, it'd be great if one could simply pass that as the unique parameter to retrieve the data source.

If you agree that this would be a good idea, I'd be happy to provide a patch.

**Comment by ndmckinley** [comment]
Sounds pretty reasonable to me!  You'll probably want to make sure to use `ConflictsWith` so that only one of `name` (or other identifier) and `self_link` can be used, but that's the only thing I can see being an issue.

**Comment by rileykarson** [comment]
This is something we support on a few datasources now (such as https://www.terraform.io/docs/providers/google/d/datasource_compute_instance.html#argument-reference), and as we add new datasources I'd imagine we'll continue to support. If you have any specific datasources missing `self_link` inputs, please feel free to file issues!
