### ISSUE TITLE
Creating a storage bucket require Compute API

### ISSUE THREAD

**Issue by rolandkool** [terraform-providers/terraform-provider-google#1089]
Hi,

With the latest terraform google provider version (1.6.0) it is required to enable the Compute API in order to create a bucket. This doesn't seem right.
With version 1.5.0 or older, this is not needed.

### Terraform Version
terraform 0.11.3
terraform-google-provider 1.6.0

### Affected Resource(s)
- google_storage_bucket

### Terraform Configuration Files
```hcl
resource "google_storage_bucket" "myproject-testbucket" {
  name          = "myproject-testbucket"
  project       = "myproject"
  location      = "EUROPE-WEST1"
  storage_class = "REGIONAL"
  force_destroy = false

  labels = {
    opex = "myteam"
  }

  versioning = {
    enabled = false
  }

}
```
A service account with only bucket admin permissions is used to create the bucket.

### Debug Output
google_storage_bucket.myproject-testbucket: googleapi: Error 403: Access Not Configured. Compute Engine API has not been used in project 1234567679 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=1234567679 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured

### Expected Behavior
Bucket should have been created. The Storage APIs are enabled (by us), but Compute API is not.

### Actual Behavior
Creation failed with error: Access Not Configured. Compute Engine API has not been used 

### Steps to Reproduce
1. Install version 1.6.0 of terraform google provider
2. use hcl example and configure a google provider with credentials
3. run terraforma apply

**Comment by ndmckinley** [comment]
That's correct - this is necessary to make imports workable.

https://github.com/terraform-providers/terraform-provider-google/commit/7b54aa854028843471fd68d67452a01ee2af4f4e#diff-b93d962cfcd3c90fba7b47c0240bd1fc

Does it cause you substantial problems?

**Comment by wmuizelaar** [comment]
Well, if we for example have a project with only storage-buckets, the Compute Engine API is not needed to be enabled. But with this change, we need to enable it. Which also automatically creates networking, firewall-rules, etc, etc. Which feels like a total overkill for just being able to manage buckets.

So, it's not a substantial problem, but it feels a bit weird to need it suddenly.

Is the import really needing these compute API calls? Maybe there is another way to work around the issue with them not being workable?

**Comment by ndmckinley** [comment]
The API calls to get the project name from a bucket are in Compute, for some reason.  It's unfortunate - but without the Compute API calls, we can only import buckets in the provider default project.  Agreed that it's a bit weird to need it suddenly, but if it helps at all, in reality you needed it all along and we were skipping it by mistake.  :)

If it's a sizable issue for you, like enabling Compute Engine on these bucket-only projects will break your workflow, and you need me to provide a way to disable it, let me know - but it does have to stay in there for most people.

**Comment by rolandkool** [comment]
@ndmckinley thanks for your feedback.
For us, it works so far without Compute API, even the importing. Our setup is such that we only manage resources within one project with one terraform run, so managing buckets in different clouds from one terraform is not something we do. I understand that this is the use case for having the Compute API enabled?

Buckets themselves don't require Compute API either, so it's only for terraform that it needs to be enabled. In our case, we would like to not enable this API if not strictly necessary. So it would be nice if terraform could check for scenarios where this API is needed and only fail if that is the case and in other scenarios keep working without it.
Is that something you would like to consider adding in?

Thanks,

Roland

**Comment by ndmckinley** [comment]
Got it. I'll take a look, then, and try to keep that API call out of `Read`.

**Comment by rolandkool** [comment]
Thanks for the change!

**Comment by drigz** [comment]
This might be a silly question, but am I correct in saying that `google_storage_bucket` requires either `project = "..."` or `depends_on = ["google_project_service.compute"]` (or the corresponding `google_project_services` resource)?

The [docs](https://www.terraform.io/docs/providers/google/r/storage_bucket.html) don't mention the dependency on the Compute API - should this be mentioned there?

**Comment by ndmckinley** [comment]
There is only a dependency on the compute API in the event of imports, as of #1125, so you shouldn't need a `depends_on`.

I can add that to the import section of the docs, sure!

**Comment by ndmckinley** [comment]
https://github.com/terraform-providers/terraform-provider-google/pull/1641 will add that phrasing.

**Comment by drigz** [comment]
@ndmckinley I was running into the 403 error on project creation (I believe with provider v1.14). The resource was defined as below, and adding `depends_on = ["google_project_service.compute"]` seemed to resolve the issue.

```
resource "google_storage_bucket" "robot" {
  name     = "${var.id}-robot"
  location = "${var.region}"
  storage_class = "REGIONAL"
  force_destroy = "true"
}
```

My understanding from #1125 is that the Compute API was required at creation because the resource doesn't specify `project` - is that correct? (in hindsight, maybe specifying `project` would be the more efficient resolution)

**Comment by ndmckinley** [comment]
Oh, shoot, I suppose that's true as well.  If you intend to use the default provider project, we can't tell the difference between that and "bucket is currently being imported" while in the read method, so we have to require the compute API for both cases.
