### ISSUE TITLE
google_compute_disk: Support short names for snapshots in other projects

### ISSUE THREAD

**Issue by waldiTM** [terraform-providers/terraform-provider-google#1099]
### Terraform Version
```
Terraform v0.11.3
+ provider.google v1.6.0
```

### Affected Resource(s)
- google_compute_disk

### Terraform Configuration Files
```hcl
resource "google_compute_disk" "syncproxy" {
  name = "${var.prefix_syncproxy}-data"
  zone = "${var.zone_syncproxy}"
  snapshot = "debian-infra/snapshot"
}
```

### Feature request
Google Cloud compute support creating disks from snapshots in other projects ([API doku](https://cloud.google.com/compute/docs/reference/rest/v1/disks/insert), see part about `resource.sourceSnapshot`).

Please support some short form for such an snapshots like `$project/$name`.

**Comment by yhuang** [comment]
Just wanted to confirm that currently it is not possible to use a snapshot from one project to create a compute disk in another with the current Terraform provider, based on this error I am seeing:

{code}
* google_compute_disk.snapshot_boot_disk: Error loading snapshot 'projects/preprod-tax-admin/global/snapshots/forcesalt001-201808231445': googleapi: Error 400: Invalid value 'projects/preprod-tax-admin/global/snapshots/forcesalt001-201808231445'. Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?', invalidParameter
{code}

The provider seems to assume the snapshot is in the same project as where the compute disk would be, and that is why it is insisting on the short name; yet, as waldiTM had pointed out, current documentation suggests that the capability should be there:

https://cloud.google.com/compute/docs/images/sharing-images-across-projects

```
You can share access to images, disks, and snapshots using the following IAM roles or permissions...
```

https://www.terraform.io/docs/providers/google/r/compute_disk.html

```
snapshot - (Optional) The source snapshot used to create this disk. You can provide this as a partial or full URL to the resource. For example, the following are valid values:

https://www.googleapis.com/compute/v1/projects/project/global/snapshots/snapshot
projects/project/global/snapshots/snapshot
global/snapshots/snapshot
snapshot
```

**Comment by paddycarver** [comment]
I've investigated this, and it looks like using the `https://` version of the snapshot will work, but `projects/project/global/snapshots/snapshot` and `global/snapshots/snapshot` will not. I believe.

So a temporary workaround is to use the full `https://` version. This is something we should fix in the generated code that handles snapshots, however, to match what our documentation says we support.

**Comment by madsonic** [comment]
perhaps we can drop a note in the docs while this gets fixed? I ran into this problem and couldn't really find this bug from google until i dig through the bugs list
