### ISSUE TITLE
Updating tags leads to instance restart

### ISSUE THREAD

**Issue by migibert** [terraform-providers/terraform-provider-google#1108]
Hi there,

Since we updated provider to v1.6.0, we observe that managing tags with terraform has unexpected behavior.
Changing a tag now leads to an error (although the tags are correctly added / removed), asking us to set allow_stopping_for_update to true. When we set this flag, changing tags lead to restart our instances.
If we force google provider version to 1.5.0, everything works as expected.

### Terraform Version
Terraform v0.11.3
+ provider.google v1.6.0

### Affected Resource(s)
- google_compute_instance

### Terraform Configuration Files
```hcl
resource "google_compute_instance" "foo" {
  name         = "foo"
  machine_type = "n1-standard-1"
  zone         = "${var.region_zone_eu}"
  tags         = ["foo", "bar"]

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }

  network_interface {
    network = "default"
    access_config {
      # Ephemeral IP
    }
  }

  service_account {
    email = "${google_service_account.foo.email}"
    scopes = []
  }
}
```

### Debug Output
Error: Error applying plan:
1 error(s) occurred:
* google_compute_instance.foo: 1 error(s) occurred:
* google_compute_instance.foo: Changing the machine_type, min_cpu_platform, or service_account on an instance requires stopping it. To acknowledge this, please set allow_stopping_for_update = true in your config.

### Expected Behavior
Changing a tag should not trigger an error or try to restart instance

### Actual Behavior
If I do not set allow_stopping_for_update = true, an error occurs but tag is correctly added.
If I set allow_stopping_for_update = true, there is no error, the tag are correctly added but my instance is restarted.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Add or remove a tag
3. `terraform apply`

### Important Factoids
It did work as expected in v1.5.0

### References
- #1005

**Comment by danawillow** [comment]
All right, as far as I can tell this is caused by an issue in Terraform core. Filed https://github.com/hashicorp/terraform/issues/17411, let's hope it's an easy fix :)

**Comment by migibert** [comment]
Oh thank you for analysis and bug report, I did not think that could be related to terraform core! I'll keep an eye on this issue!

**Comment by danawillow** [comment]
No worries, I definitely wouldn't have expected that either :)
