### ISSUE TITLE
google_compute_target_pool.instances should be a set

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#1109]
`data.google_compute_instance_group.group.instances` return URLs that are accepted by the `google_compute_target_pool` (docs: "They can be given as URLs, or in the form of "zone/name".) but once applied, the URLs will always cause resource to be modified because apparently `zone/name` is really expected.

**Comment by danawillow** [comment]
Hey @matti, can you paste in the config you're using that's encountering this error? I just tried to reproduce it and didn't have any problems. Here's the config I used:

```
resource "google_compute_instance" "test" {
  name         = "test"
  machine_type = "n1-standard-1"
  zone         = "us-central1-a"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-8"
    }
  }

  network_interface {
    network = "default"

    access_config {
      // Ephemeral IP
    }
  }
}

resource "google_compute_instance_group" "test" {
  name = "terraform-test"
  zone = "us-central1-a"

  instances = [
    "${google_compute_instance.test.self_link}",
  ]
}

data "google_compute_instance_group" "all" {
  name = "${google_compute_instance_group.test.name}"
  zone = "us-central1-a"
}

resource "google_compute_target_pool" "default" {
  name = "instance-pool"

  instances = ["${data.google_compute_instance_group.all.instances}"]
}
```

**Comment by matti** [comment]
Made a repro here: https://github.com/matti/repro-terraform-provider-google-issue-1109

**Comment by matti** [comment]
Opened #1123 that would make the approach I'm using here unnecessary

**Comment by matti** [comment]
^-- #1123 is closed, but the bug still triggers with my example

**Comment by danawillow** [comment]
Ah ok, I see what's happening. The "zone/name" is completely a red herring here. The actual issue is that the order of the instances within the target pool changed. See this part here:
```
instances.0: "europe-west1-c/test-2-mp5w" => "https://www.googleapis.com/compute/v1/projects/ag-dolan/zones/europe-west1-b/instances/test-1-pxj8"
  instances.1: "europe-west1-d/test-3-xv25" => "https://www.googleapis.com/compute/v1/projects/ag-dolan/zones/europe-west1-c/instances/test-2-mp5w"
  instances.2: "europe-west1-b/test-1-pxj8" => "https://www.googleapis.com/compute/v1/projects/ag-dolan/zones/europe-west1-d/instances/test-3-xv25"

```
Your config has them in the order "1, 2, 3", but the API is returning them in the order "2, 3, 1", causing the diff. We should probably make that field into a set since the order doesn't matter.

I'm going to go ahead and change the title of this issue in case someone else ends up picking it up before I get a chance to, hope that's all right.

**Comment by matti** [comment]
oh, right. makes sense now!

**Comment by paddycarver** [comment]
As this is a list -> set change, I'm going to flag it as a potentially backwards incompatible change (which means it may need to be held for the next major release), but will evaluate the solution to see if we can get it in in a minor or patch release.

**Comment by chrisst** [comment]
As of 2.0 instances will be a set and ordering will be unimportant.
