### ISSUE TITLE
google_compute_backend_service to have backends from list setter

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#1112]
Currently it's not possible to have a dynamic number of backends because the backends need to be given as blocks:

```
resource "google_compute_backend_service" "all" {
  name        = "backends"

  backend {
    group = "${module.statefuls.instance_groups[0]}"
  }

  backend {
    group = "${module.statefuls.instance_groups[1]}"
  }

  backend {
    group = "${module.statefuls.instance_groups[2]}"
  }
}
```

Something like
```
backends = []
```
would be great

**Comment by nmavor** [comment]
look as some code was done on the terraform side 
https://github.com/hashicorp/terraform/pull/11059

**Comment by webervin** [comment]
Please note that upstream-issue is closed without merge, so this one needs to be triaged again

**Comment by danawillow** [comment]
I believe this can be accomplished natively in terraform 0.12 now with dynamic blocks: https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks. Closing this since I think that's a cleaner solution than changing the provider.
