### ISSUE TITLE
Support for target_pools in google_compute_instance_group 

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#1123]
In regional instance group manager there is an option to automatically add instances to target pools https://www.terraform.io/docs/providers/google/r/compute_region_instance_group_manager.html#target_pools

If zonal instance group manager (https://www.terraform.io/docs/providers/google/r/compute_instance_group_manager.html) would support this also then hacks like the one failing in https://github.com/terraform-providers/terraform-provider-google/issues/1109 wouldn't be needed

**Comment by danawillow** [comment]
I'm seeing https://www.terraform.io/docs/providers/google/r/compute_instance_group_manager.html#target_pools. Is that what you're looking for or something different?

**Comment by matti** [comment]
Huh - okay I missed that. Thanks!
