### ISSUE TITLE
Resource `google_container_engine` Enforcing Un-necessary Check

### ISSUE THREAD

**Issue by kylegoch** [terraform-providers/terraform-provider-google#1132]
The `google_container_cluster` resource is enforcing an unnecessary check to make sure the CIDR is valid for `cluster_ipv4_cidr` https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_container_cluster.go#L141 however the API actually accepts values other than CIDRs (https://github.com/terraform-providers/terraform-provider-google/blob/master/vendor/google.golang.org/api/container/v1/container-gen.go#L338).

**Comment by ndmckinley** [comment]
Hi, sorry, I see the documentation string:

```
        // ClusterIpv4Cidr: The IP address range of the container pods in this
	// cluster,
	// in
	// [CIDR](http://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing)
	//
	// notation (e.g. `10.96.0.0/14`). Leave blank to have
	// one automatically chosen or specify a `/14` block in `10.0.0.0/8`.
```

Meaning that the only valid values are CIDRs or blank, right?
