### ISSUE TITLE
google_container_cluster crash

### ISSUE THREAD

**Issue by allistera** [terraform-providers/terraform-provider-google#1136]
Hi there,

Getting a terraform crash when attempting to create a Kubernetes container cluster using the standard example.

Details under.

Thanks

### Terraform Version

Terraform v0.11.3
+ provider.google v1.6.0

### Affected Resource(s)

google_container_cluster

### Terraform Configuration Files

Using example from https://www.terraform.io/docs/providers/google/r/container_cluster.html

```hcl
provider "google" {
  project     = "masked"
  region      = "europe-west1"
}

resource "google_container_cluster" "primary" {
  name               = "allister"
  zone               = "us-central1-a"
  initial_node_count = 3

  additional_zones = [
    "us-central1-b",
    "us-central1-c",
  ]

  master_auth {
    username = "masked"
    password = "masked"
  }

  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]

    labels {
      foo = "bar"
    }

    tags = ["foo", "bar"]
  }
}

# The following outputs allow authentication and connectivity to the GKE Cluster.
output "client_certificate" {
  value = "${google_container_cluster.primary.master_auth.0.client_certificate}"
}

output "client_key" {
  value = "${google_container_cluster.primary.master_auth.0.client_key}"
}

output "cluster_ca_certificate" {
  value = "${google_container_cluster.primary.master_auth.0.cluster_ca_certificate}"
}
```

### Debug Output

https://gist.github.com/allistera/528a49ff950f12219e7957d70aab9b47

### Expected Behavior

Kubernetes Cluster created, outputs returned.

### Actual Behavior

Kubernetes Cluster created, terraform crash.

### Steps to Reproduce

1. `terraform apply`

**Comment by ndmckinley** [comment]
Hey there!

Sorry for your trouble ... but when I do the same thing from head, I get the outputs specified.  I see the same thing from v1.6.0.  My best guess is that the URL which came back didn't match the instance group manager URL for whatever reason, and we should report that error instead of crashing.

**Comment by allistera** [comment]
Awesome thanks Nathan!
