### ISSUE TITLE
[Feature Request] Data source google_storage_bucket_object

### ISSUE THREAD

**Issue by Farhie** [terraform-providers/terraform-provider-google#1157]
Hello,

Feature request for being able to get an object as a data source.

As part of our CloudFunction deployment we have a pipeline that syncs a CloudFunction zip to a Google Cloud Storage Bucket. We did consider making our Terraform pipeline a downstream dependency of the package step of our Cloud Functions. However, this proved to be clunky. 

We would like to be able to get the object within the Terraform apply. I am envisioning this would work something like:

```hcl
data "google_storage_bucket_object" "cloudfunction_archive" {
  bucket = "cloudfunctions"
  name = "function.zip"
}

// fields intentionally omitted
resource "google_cloudfunctions_function" "test_cloudfunction_function" {
  name = "${var.environment}-test-cloud-function"
  source_archive_bucket = "test-bucket"
  source_archive_object = "${data.google_storage_bucket_object.cloudfunction_archive}"
}
```

**Comment by rameshvenk** [comment]
+1 for this as well. We are trying to figure out if a object within a storage bucket exists, but currently there seems to be no way to do that within the provider. This would help us greatly in our consul deployments

**Comment by morgante** [comment]
It is possible to do this today doing a combination of google_storage_object_signed_url data provider and http.

```
locals {
  credentials_file_path = "${path.module}/sa-key.json"
}

provider "google" {
  credentials = "${file(local.credentials_file_path)}"
}

data "google_storage_object_signed_url" "secret_file" {
  bucket      = "gcp-fnd-stored-secret"
  path        = "test.txt"
  credentials = "${local.credentials_file_path}"
}

data "http" "remote_secret" {
  url = "${data.google_storage_object_signed_url.secret_file.signed_url}"
}

output "file_data" {
  value = "${data.http.remote_secret.body}"
}
```

**Comment by bbrouwer** [comment]
This method doesn't work when using application default credentials for my user account. It apparently needs to be a service account. I am trying to use my own user account to download an encrypted secret, and then decrypt it using KMS and finally use that credential to configure the google provider for all other resources. I was hopeful when I saw that this had its own credential property, but it still doesn't help if I want those credentials to be my own.

**Comment by chrisst** [comment]
fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/1050
