### ISSUE TITLE
Creating GKE cluster without initial_node_count

### ISSUE THREAD

**Issue by pbzdyl** [terraform-providers/terraform-provider-google#1163]
### Terraform Version
Terraform v0.11.3
+ provider.google v1.6.0

### Affected Resource
- `google_container_cluster`

### Terraform Configuration Files
```hcl
variable "test_cluster_name" { default = "test2" }
variable "test_cluster_machine_type" { default = "n1-standard-1" }
variable "test_cluster_disk_size_gb" { default = 10 }
variable "test_cluster_min_nodes" { default = 1 }
variable "test_cluster_max_nodes" { default = 16 }
variable "test_cluster_auto_repair" { default = true }
variable "test_cluster_dashboard_disabled" { default = true }
variable "test_cluster_master_version" { default = "1.9.3-gke.0" }
variable "test_cluster_node_version" { default = "1.9.3-gke.0" }
variable "test_cluster_oauth_scopes" {
  type = "list"
  default = [
    "https://www.googleapis.com/auth/devstorage.read_only",
    "https://www.googleapis.com/auth/logging.write",
    "https://www.googleapis.com/auth/monitoring",
    "https://www.googleapis.com/auth/servicecontrol",
    "https://www.googleapis.com/auth/service.management.readonly",
    "https://www.googleapis.com/auth/trace.append"
  ]
}

resource "random_id" "test_gke_username" {
  byte_length = "${var.password_length}"
}

resource "random_id" "test_gke_password" {
  byte_length = "${var.password_length}"
}

resource "google_container_cluster" "test" {
  name               = "${var.test_cluster_name}"
  zone               = "${var.zone}"
  min_master_version = "${var.test_cluster_master_version}"
  node_version       = "${var.test_cluster_node_version}"

  master_auth {
    username = "${random_id.test_gke_username.b64}"
    password = "${random_id.test_gke_username.b64}"
  }

  addons_config {
    kubernetes_dashboard {
      disabled = "${var.test_cluster_dashboard_disabled}"
    }
  }

  node_pool = [
    {
      name = "default-pool"
      node_config {
        machine_type       = "${var.test_cluster_machine_type}"
        disk_size_gb       = "${var.test_cluster_disk_size_gb}"
        oauth_scopes = "${var.test_cluster_oauth_scopes}"
      }
      autoscaling {
        min_node_count = "${var.test_cluster_min_nodes}"
        max_node_count = "${var.test_cluster_max_nodes}"
      }
      management {
        auto_repair = "${var.test_cluster_auto_repair}"
      }
    }
  ]
}
```

### Expected Behavior
With the configuration above - notice that it doesn't specify `initial_node_count` in the embedded `node_pool` - a new cluster with a node pool of size 1 is created.

### Actual Behavior
A node pool with size 0 is created:
<img width="467" alt="screen shot 2018-03-07 at 20 56 16" src="https://user-images.githubusercontent.com/57622/37116983-21ce84ca-2250-11e8-89c8-fc16e41b879f.png">

The cluster is not auto-resized above size 0 even if non kube-system pods are deployed:
<img width="481" alt="screen shot 2018-03-07 at 20 55 57" src="https://user-images.githubusercontent.com/57622/37117817-9a14fb06-2252-11e8-85c6-061e4d5eaf25.png">

### Steps to Reproduce
`terraform apply` the config included above

### Workaround
I can fix the issue by specifying `initial_node_count = 1` explicitly.
But according to [`google_container_cluster` docs `initial_node_count` is deprecated and `node_count` should be used instead](https://www.terraform.io/docs/providers/google/r/container_cluster.html#initial_node_count). Unfortunately, I cannot use `node_count` with autoscaling configuration as `node_count` always sets the cluster size to `node_count` value when the actual size has been modified by autoscaler - thus usage of autoscaling and `node_count` is mutually exclusive.

I am concerned that support for `initial_node_count` will be dropped and it won't be possible to workaround the issue I have (cluster created with size 0) just by specifying `initial_node_count`.

**Comment by pbzdyl** [comment]
According to [GKE API reference initialNodeCount](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters.nodePools#NodePool) is mandatory thus I think it shouldn't be deprecated in terraform-provider-google. It's value has to be within auto-scaling range.

If it's not present in tf configuration and auto-scaling is used then it could be defaulted to [`min_node_count`](https://www.terraform.io/docs/providers/google/r/container_node_pool.html#min_node_count).

**Comment by wmuizelaar** [comment]
I guess this is related to https://github.com/terraform-providers/terraform-provider-google/issues/844
