### ISSUE TITLE
Failure to create resilient background functions (i.e. retry on failure)

### ISSUE THREAD

**Issue by Farhie** [terraform-providers/terraform-provider-google#1164]
Hello,

We are triggering CloudFunctions upon new messages being inserted in to a PubSub topic. The team spent time investigating why the CloudFunctions were not being re-invoked upon failure. Turns out we can't configure the `retry on failure` property of Background CloudFunctions. Can a retry upon failure parameter be added to `google_cloudfunctions_function`. Or are we missing something in the current setup?

**Comment by stevehayes** [comment]
Hey Ninjas!

My team is also experiencing this same issue and it is a blocker for us. Is there anything we can do to escalate or expedite this enhancement? I didn't find anything in the docs the indicated we had misconfigured anything. HALP!

**Comment by rosbo** [comment]
Hi stevehayes@,

We always welcome contributions from the community, if you feel like taking a stab at it, I can review your PR promptly if you tag me on it.

More info here: https://github.com/terraform-providers/terraform-provider-google/blob/master/README.md#developing-the-provider
