### ISSUE TITLE
Provider project not used in google_container_cluster

### ISSUE THREAD

**Issue by psalaberria002** [terraform-providers/terraform-provider-google#1166]
### Terraform Version
Terraform v0.11.3
+ provider.google v1.6.0

### Affected Resource(s)
Please list the resources as a list, for example:
- google_container_cluster

Other resources get the project from the provider configuration.

### Terraform Configuration Files
```hcl
provider "google" {
  credentials = "${file("~/.config/gcloud/xxx.json")}"
  region = "${var.region}"
  version = "~> 1.6"
  project = "${data.terraform_remote_state.project.project_id}"
}

resource "google_container_cluster" "primary" {
  #project = "${data.terraform_remote_state.project.project_id}"
  name = "primary"
  zone = "${var.zone}"
  network = "${var.network_self_link}"

  enable_legacy_abac = false

  addons_config {
    kubernetes_dashboard {
      disabled = true
    }
  }

  network_policy {
    enabled = true
  }
}
```

### Expected Behavior
If project is not provided in google_container_cluster, the provider project is used.
https://www.terraform.io/docs/providers/google/r/container_cluster.html#project

### Actual Behavior
Provider project is not used.

## Additional information
I created a Google Cloud project with a service account for Terraform. That's where I store the remote states. The cluster is going to be created in a different project.

Error 403: Google Kubernetes Engine API has not been used in project xxx-terraform

**Comment by psalaberria002** [comment]
Enabling the Kubernetes API in the Terraform project fixed the issue. Is this the expected behavior?

**Comment by rosbo** [comment]
I also find this behavior surprising. My team filed an issue to the IAM team about it a little while ago. Not much we can do on the Terraform side to fix this.

Thanks for reporting and I am sorry that you wasted time on this...
