### ISSUE TITLE
Add support for regional GKE clusters in google_container_cluster

### ISSUE THREAD

**Issue by ashish-amarnath** [terraform-providers/terraform-provider-google#1170]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.2 and upwards
+ provider.google

### Affected Resource(s)
Please list the resources as a list, for example:
- google_container_cluster

### Expected Behavior
This is a feature request to add support for Regional GKE clusters on creating/updating a container cluster.

### References
This document describes what needs to be done
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters

**Comment by danawillow** [comment]
Unassigning myself because @ashish-amarnath mentioned in slack they were planning on implementing this.

**Comment by Stono** [comment]
@ashish-amarnath do we know when this is coming?  As regional clusters are now beta it'd be awesome to make use of them.

**Comment by ashish-amarnath** [comment]
@Stono I don't have an ETA at the moment. Based on our plans this might be a couple of weeks away.
I'll keep this issue updated.

**Comment by ashish-amarnath** [comment]
@danawillow I was able to put together an initial set of changes for this. I've opened a WIP PR at https://github.com/terraform-providers/terraform-provider-google/pull/1181 hoping to get some initial feedback on the approach.

**Comment by wmuizelaar** [comment]
I guess this is doubling with https://github.com/terraform-providers/terraform-provider-google/issues/829 ?

**Comment by danawillow** [comment]
Fixed in #1181

**Comment by Stono** [comment]
Eeek exciting.
Do you have a rough feeling for 1.9 release date?

**Comment by danawillow** [comment]
@Stono released it today!

**Comment by Stono** [comment]
Rock star!  I'll give it a go later
