### ISSUE TITLE
`google_sql_user` id is not necessarily unique

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#1184]
We store the IDs as "instance/name", but users with the same instance/name pair can exist with different hosts.

As far as I can tell, there are no user-visible effects of this. However, it does make our import tests flaky because they expect that IDs are unique. I also wouldn't be surprised if other parts of Terraform assume that IDs are unique as well.

Sample failure:
```
--- FAIL: TestAccSqlUser_firstGen (97.04s)
	testing.go:513: Step 2 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

		(map[string]string) (len=1) {
		 (string) (len=4) "host": (string) (len=9) "gmail.com"
		}


		(map[string]string) (len=1) {
		 (string) (len=4) "host": (string) (len=10) "google.com"
		}

FAIL
```
In this test, the "expected" is what's wrong because both users in the test have the same id.

**Comment by rileykarson** [comment]
This is stored as name/host/instance now.
