### ISSUE TITLE
terraform apply throws Error 409: alreadyExists when re-creating google_kms_key_ring

### ISSUE THREAD

**Issue by pwhn** [terraform-providers/terraform-provider-google#1214]
### Terraform Version
```
Terraform v0.11.4
+ provider.google v1.7.0
```

### Affected Resource(s)
- google_kms_key_ring

### Terraform Configuration Files
```hcl
variable project_id {
  type = "string"
  default = ""
}

provider "google" {
  project = "${var.project_id}"
  credentials = "account.json"
}

resource "google_kms_key_ring" "my_key_ring" {
  project   = "${var.project_id}"
  name      = "my-key-ring"
  location  = "europe"
}

resource "google_kms_crypto_key" "my_crypto_key" {
  name     = "my-crypto-key"
  key_ring = "${google_kms_key_ring.my_key_ring.id}"
}
```

### Expected Behavior
GCP resources `google_kms_key_ring` and `google_kms_crypto_key` can't be deleted. This is by design. But if they already exist, terraform should skip their creation and not break the deployment.

### Actual Behavior
When resource `google_kms_key_ring` already exists, calling `terraform apply` throws the Error 409: alreadyExists, which breaks the deployment:  
```
google_kms_key_ring.my_key_ring: Error creating KeyRing: googleapi: Error 409: KeyRing projects/my-project/locations/europe/keyRings/my-key-ring already exists., alreadyExists
```

### Steps to Reproduce
1. `terraform apply` <- google_kms_key_ring does not exist yet, command succeeds
2. `terraform destroy`
3. `terraform apply` <- this is where terraform throws Error 409: alreadyExists.

**Comment by pwhn** [comment]
Looks like this has already been raised in https://github.com/terraform-providers/terraform-provider-google/pull/518#issuecomment-365080711 and answered in https://github.com/terraform-providers/terraform-provider-google/pull/518#issuecomment-365093782.

And the answer is to import `google_kms_key_ring` before calling `terraform apply`, https://www.terraform.io/docs/providers/google/r/google_kms_key_ring.html#import.

**Comment by todd-dsm** [comment]
A [helper script](https://gist.github.com/todd-dsm/cbcabec1926ee39223ae6d8551da8c91) for those who _also_ diddled with this way too long.

Is this not best solved with data source, like everything we need to discover along the way?
