### ISSUE TITLE
It should be possible to change the description of a google_dns_managed_zone even if it's not empty?

### ISSUE THREAD

**Issue by jstephenson** [terraform-providers/terraform-provider-google#1215]
### Terraform Version
```
Terraform v0.11.4
+ provider.google v1.7.0
```

### Affected Resource(s)
- google_dns_managed_zone

### Terraform Configuration Files
**From**
```hcl
resource "google_dns_managed_zone" "example_com" {
  name = "example-com"
  dns_name = "example.com.
  description = ""
}
```
**To**
```hcl
resource "google_dns_managed_zone" "example_com" {
  name = "example-com"
  dns_name = "example.com.
  description = "My new description."
}
```

### Expected Behavior
I would have thought it'd do what's necessary to recreate the resource, including emptying it as necessary?

### Actual Behavior
`Error deleting DNS ManagedZone: googleapi: Error 400: The resource named 'example-com' cannot be deleted because it is not empty, containerNotEmpty`

### Steps to Reproduce
Where the zone `example-com` already exists with a blank description.
1. `terraform import google_dns_managed_zone.example_com example-com`
2. `terraform apply`

### Important Factoids
This represents the particular case I ran in to, but I suspect creating the resource with Terraform from the start and then altering the description does the same – haven't yet tried this.

This appears to be the case whether or not Terraform manages the record sets which are causing the zone to be not-empty.

**Comment by danawillow** [comment]
Hey @jstephenson, thanks for the report!

I think the `description` part here is a bit of a red-herring. It sounds like what you want is that deleting a `google_dns_managed_zone` from Terraform empties its record sets as well, right? We can make that happen, but first I want to check on the use case. If you manage both your managed zone and your record sets with Terraform and interpolate them correctly, then destroying the managed zone should also destroy the record sets. For example, our tests have this case (don't worry about the '%s's, you get the point):
```
	resource "google_dns_managed_zone" "parent-zone" {
		name = "%s"
		dns_name = "%s.hashicorptest.com."
		description = "Test Description"
	}
	resource "google_dns_record_set" "foobar" {
		managed_zone = "${google_dns_managed_zone.parent-zone.name}"
		name = "%s.hashicorptest.com."
		type = "NS"
		rrdatas = ["ns.hashicorp.services.", "ns2.hashicorp.services."]
		ttl = %d
	}
```
Because the record set references the managed zone, changing the description on the zone would do the following in this order:
1. Delete the record set
2. Delete the managed zone
3. Recreate the managed zone
4. Recreate the record set

Does that work for your use case?

**Comment by jstephenson** [comment]
@danawillow Yes indeed – the more general form of this issue would suggest that it should be possible to change any attribute of a Cloud DNS resource and have the provider figure out how to apply it successfully, whatever steps that might reasonably require. Habits of a lifetime cause me to open every bug with a specific, reproducible use-case!

Your proposed flow does indeed work for me thank you – it was a bit frustrating having to go through each zone in the Cloud Console and manually empty them before I could apply my changes!

**Comment by danawillow** [comment]
Glad to hear it worked!

**Comment by kim0** [comment]
Hey @danawillow 

I just hit this same problem. But my use-case is different. I'm using TF to create the zones, then I'm launching gke cluster. In GKE, I use [external-dns](https://github.com/kubernetes-incubator/external-dns) to create public DNS entries for the services dynamically. Now, I changed my domain name, and was expecting TF to delete the old zone and create a new empty one, but it failed bec the zone is not empty. I suppose that's a good security measure to avoid deleting DNS records, but perhaps it should have some kind of "recursive: True" setting that deletes all records under the zone?

**Comment by danawillow** [comment]
@kim0, I'm not totally sure I understand what you're getting at. Can you file a new issue about it? If you provide a sample configuration, what you expected to happen, and what actually happened, that'll help. Thanks!

**Comment by kim0** [comment]
@danawillow .. Sorry for not being clear enough. I suppose I was looking for a parameter like [force_destroy](https://www.terraform.io/docs/providers/aws/r/route53_zone.html#force_destroy) but for Google's DNS. Thanks
