### ISSUE TITLE
[enhancement] Add SSL Policy support to Target HTTPS Proxies

### ISSUE THREAD

**Issue by nickjacques** [terraform-providers/terraform-provider-google#1229]
Now that [SSL Policies](https://cloud.google.com/compute/docs/load-balancing/ssl-policies) have [been released](https://cloudplatform.googleblog.com/2018/02/announcing-SSL-policies-for-HTTPS-and-SSL-proxy-load-balancers.html), let's add SSL Policy support to Target HTTPS Proxies.

Parent issue for creating SSL Policy resources is #1228.

**Comment by rosbo** [comment]
This feature was added in #1466 and release in 1.13.0
