### ISSUE TITLE
[enhancement] Add SSL Policy support to Target SSL Proxies

### ISSUE THREAD

**Issue by nickjacques** [terraform-providers/terraform-provider-google#1230]
Now that [SSL Policies](https://cloud.google.com/compute/docs/load-balancing/ssl-policies) have [been released](https://cloudplatform.googleblog.com/2018/02/announcing-SSL-policies-for-HTTPS-and-SSL-proxy-load-balancers.html), let's add SSL Policy support to Target SSL Proxies.

Parent issue for creating SSL Policy resources is #1228.

**Comment by rosbo** [comment]
Note to implementer, the change should be similar to the one for the https proxy:
https://github.com/GoogleCloudPlatform/magic-modules/pull/151/files
