### ISSUE TITLE
[enhancement] Add support for log-based metrics

### ISSUE THREAD

**Issue by endemics** [terraform-providers/terraform-provider-google#1236]
Hi,

We are planning to use [log-based metrics](https://cloud.google.com/logging/docs/logs-based-metrics/) to create counter metrics from application logs or google cloud API logs (such as reported errors for Cloud KMS Decrypt calls), and unless mistaken this is not yet supported in terraform.

I believe such terraform resource would be using the API detailed in https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.metrics

### Terraform Version

```
terraform v0.11.4
provider.google v1.8.0
```

### Expected Behavior

Be able to create at least simple log-based metric counters that would look something like:
```
resource "google_logging_project_metric" "kms-metric" {
  name        = "kms-logs-error-metric"
  description = "Number of KMS decryption error"
  filter      = "resource.type=\"cloudkms_cryptokey\" logName=\"projects/${var.google_project_id}/logs/cloudaudit.googleapis.com%2Fdata_access\" protoPayload.status.message: \"denied\""
}
```

**Comment by cblecker** [comment]
I would also love to see this.

**Comment by shotarohorai** [comment]
Is anyone already working on this issue?
@danawillow

**Comment by luckysamadhiya** [comment]
@danawillow any update on log-based  metrics support in terrafrom ?

**Comment by luckysamadhiya** [comment]
@danawillow just wanna confirm again , any update on log-based metrics support in terraform ?

**Comment by danawillow** [comment]
@chrisst do you know?

(I'm actually on a break from Terraform at the moment, so I'm afraid tagging me in issues isn't going to be much help)

**Comment by chrisst** [comment]
No updates at this point :( I'll add it to my queue though when I get some time.

**Comment by kiroiskim** [comment]
Waiting for any updates.

**Comment by kiroiskim** [comment]
Hello @chrisst, do we have any update on this enhancement support? :)

**Comment by kiroiskim** [comment]
Hello @chrisst, thanks for checking on this lately. I see a pull request is pending approval on the magic modules repository. Will the update be pushed in this repository once approved? Looking forward to have it soonest.

**Comment by chrisst** [comment]
Yes, Magic Modules is a code generator that we use to build the Terraform Provider Google code base. Once that PR is ready it will generate PR's into all the downstream code bases including this and https://github.com/terraform-providers/terraform-provider-google-beta/

**Comment by kiroiskim** [comment]
That's good to know @chrisst. Looks like I have to wait for this update. Adding labels via terraform would also be great. :)

**Comment by git4raj** [comment]
We would like to have the ability to create the metric through Terraform. Currently, we validated by creating the manually / sdk and the log based alert policy through Terraform. Please notify when available..
Thanks,
Raj
