### ISSUE TITLE
Support GKE cluster labels for google_container_cluster

### ISSUE THREAD

**Issue by natalysheinin** [terraform-providers/terraform-provider-google#1238]
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- `google_container_cluster`
Currently a provisioner needs to be created to do this operation for us. This is an important feature because once its included in the cluster configuration, we would need to recreate every cluster since cluster label creation/modification causes a cluster recreate. Better to have sooner than later if possible.

### Important Factoids
Not to be confused with labels for `node_config` which get applied to nodepools rather than clusters.

### References
https://cloud.google.com/kubernetes-engine/docs/how-to/creating-managing-labels

**Comment by natalysheinin** [comment]
@danawillow is this being considered for any future release?

**Comment by danawillow** [comment]
It's definitely something we'd like to add, no ETA that I can report currently though.

**Comment by KaylaEcker** [comment]
I'm working on this!

**Comment by danawillow** [comment]
In progress PR: https://github.com/terraform-providers/terraform-provider-google/pull/1663

**Comment by paddycarver** [comment]
#1663 has been merged, this should go out with 1.16.0.
