### ISSUE TITLE
GCE managed group instances' IPs as output

### ISSUE THREAD

**Issue by jgoclawski** [terraform-providers/terraform-provider-google#1246]
Hi there,

### Terraform Version
Terraform v0.11.3
+ provider.google v1.6.0

### Affected Resource(s)
- google_compute_region_instance_group_manager
- google_compute_instance

### Terraform Configuration Files
```hcl
resource "google_compute_region_instance_group_manager" "default" {
  name               = "${var.name_prefix}-instance-group"
  base_instance_name = "${var.name_prefix}"
  instance_template  = "${google_compute_instance_template.default.self_link}"
  region             = "${var.region}"
  target_pools       = ["${google_compute_target_pool.default.self_link}"]
  target_size        = "${var.instance_count}"
}
```

### Expected Behavior
I would like to be able to discover managed instances IPs via Terraform and expose them as an output.
Use case:
Step 1 - create managed instances with Terraform
Step 2 - run code deploy on them, using Jenkins. Jenkins gets IPs from Terraform's output and uses SSH to connect with them.

Another use case:
Step 1 - create managed instances with Terraform
Step 2 - add instances' IPs to "authorized_networks" on "google_sql_database_instance" resource.

Right now in step 2, we're using gcloud command to discover IPs.

Something like this is possible with AWS, using "aws_instance" data source or "aws_instances" data source.
For GCP, there is no "google_compute_instance" data source. There is however "google_compute_region_instance_group" data source, but it doesn't expose IPs as an attribute.

**Comment by paddycarver** [comment]
I'm going to close this out, as we've released the compute instance data source, so people should be able to string this together by themselves, if they really want to. I'm weakly against adding documentation/an example on how to do it, because I think it's behaviour that should be discouraged. If anyone feels strongly it should be documented, feel free to chime in, and we can reopen the issue.
