### ISSUE TITLE
Feature request: support datastore entities

### ISSUE THREAD

**Issue by PepperTeasdale** [terraform-providers/terraform-provider-google#1253]
### Terraform Version
0.11.5

We need to configure google datastore in multiple environments and we were hoping to use terraform to manage it. Unfortunately for now we can just create manually or write ad hoc scripts. Would love to see this resource supported :)

**Comment by morgante** [comment]
@mhuxtable App engine creation was recently added to the google_project resource: https://www.terraform.io/docs/providers/google/r/google_project.html#app_engine

**Comment by ndmckinley** [comment]
Anyone who's interested, could you elaborate on what would be useful to add?  It would be especially helpful to get the set of gcloud commands you're currently using to work around the lack of terraform support.

**Comment by PepperTeasdale** [comment]
Apologies, I'm not remember the context from when I brought this up and I'm no longer working on the project that was using this...  Happy to close if no one else has a request for this feature anymore.

**Comment by ndmckinley** [comment]
I'll tag it stale - we'll close it in a few weeks if no one else chimes in.  :)

**Comment by morgante** [comment]
Unfortunately datastore doesn't have much of a public API, but if anyone is interested we have abstracted the current gcloud commands into a Terraform module: https://github.com/terraform-google-modules/terraform-google-cloud-datastore

Once a public API is released, we'll replace the commands with proper resources.

**Comment by johnroach** [comment]
I would love this to be a part of Terraform. Would love to manage all my cloud resources in a single place rather than needing to create datastore resource from a different tool

**Comment by morgante** [comment]
@johnroach Can you share the specific gcloud commands you're hoping to replace w/ Terraform?

**Comment by johnroach** [comment]
@morgante I see what you mean now. I was thinking in terms of GCP Console work that needed to be done.

**Comment by morgante** [comment]
@johnroach No problem, please *do* check out this module and let us know if there's anything missing there: https://github.com/terraform-google-modules/terraform-google-cloud-datastore
