### ISSUE TITLE
Multiple zones in container_node_pool

### ISSUE THREAD

**Issue by temujin9** [terraform-providers/terraform-provider-google#1257]
### Affected Resource(s)
Please list the resources as a list, for example:
- google_container_node_pool

### Terraform Configuration Files
```hcl
resource "google_container_cluster" "primary" {
  name               = "core-kubernetes"
  project            = "greenfield-guild"
  zone               = "us-west1-a"

  initial_node_count = 1
  node_pool {
    name = "default-pool"
  }

  additional_zones = [
    "us-west1-b",
    "us-west1-c",
  ]
}

resource "google_container_node_pool" "us-west1-a" {
  zone       = "us-west1-a"
  cluster    = "${google_container_cluster.primary.name}"
  node_count = 1
}

resource "google_container_node_pool" "us-west1-b" {
  zone       = "us-west1-b"
  cluster    = "${google_container_cluster.primary.name}"
  node_count = 1
}

resource "google_container_node_pool" "us-west1-c" {
  zone       = "us-west1-c"
  cluster    = "${google_container_cluster.primary.name}"
  node_count = 1
}
```

Some details elided: ask if they might matter.

### Debug Output
https://gist.github.com/temujin9/cca208b29cc032f79960a2b1e680ea68

### Expected Behavior
I am expecting to be able to create a pool or collection of pools which cross regional boundaries, like I can with the default pool created by google_container_cluster.

### Actual Behavior
It bombed out, complaining of not having a cluster in that region.

### Steps to Reproduce
1. Add google_container_cluster stanza
1. `terraform apply`
1. Add google_container_node_pools stanza
1. `terraform apply`

**Comment by emilymye** [comment]
My understanding is that multizone clusters automatically replicate node pools you create in the primary cluster zone for the other zones (see [docs](https://cloud.google.com/kubernetes-engine/docs/concepts/multi-zone-and-regional-clusters#multi-zone)), and that you can't explicitly create or control the node pool for these additional zones.

**Comment by temujin9** [comment]
That was it exactly. Thank you!
