### ISSUE TITLE
Add support for DNSSEC in dns_managed_zone

### ISSUE THREAD

**Issue by rosbo** [terraform-providers/terraform-provider-google#1265]
Affected resources:

* dns_managed_zone

Context:
https://cloud.google.com/dns/api/v1beta2/managedZones#resource

This feature is in beta.

**Comment by alwaysastudent** [comment]
+1

**Comment by MarcFundenberger** [comment]
+1

**Comment by jiridoko** [comment]
+1
Is there an ETA on this?

**Comment by jmdots** [comment]
Here's another link that might help: https://cloud.google.com/dns/docs/dnssec-advanced#subdelegation

**Comment by jdpleiness** [comment]
+1

**Comment by FoxBoxsnet** [comment]
+1

**Comment by Lord-Y** [comment]
+1

**Comment by Lawouach** [comment]
Friendly ping on this one too :)

**Comment by paddycarver** [comment]
This was added in #3677 and released in version 2.8.0 of the provider.
