### ISSUE TITLE
terraform crash when creating google_sql_database_instance

### ISSUE THREAD

**Issue by theothermike** [terraform-providers/terraform-provider-google#1267]
using terraform-provider-google checked out and built on 3/28/2018 13:00:00 EST

### Terraform Version
Terraform v0.11.5

### Affected Resource(s)
- google_sql_database_instance

### Terraform Configuration Files
```hcl
resource "google_sql_database_instance" "cloudsqldb" {
  name             = "${var.environment_name}-${var.client}-db-${var.region}"
  region           = "${var.region}"
  database_version = "${var.database_version}"

  settings {
    tier               = "${var.machine_type}"
    maintenance_window = {}
  }
}

resource "google_sql_database" "primary_db" {
  instance = "${google_sql_database_instance.cloudsqldb.name}"
  name     = "${var.db_name}"
}

resource "google_sql_user" "primary_db_user" {
  host     = "%"
  instance = "${google_sql_database_instance.cloudsqldb.name}"
  name     = "${var.db_username}"

  #password = "${var.db_password != "" ? var.db_password : "changeme"}"
}
tfvars:
  environment_name = "staging"
  project          = "my-project"
  region           = "europe-west1"
  zone             = "europe-west1-c"
  machine_type     = "db-n1-standard-4"
  db_name          = "db"
  db_username      = "db_staging"
  db_password      = "changeme"
```

### Debug Output
https://gist.github.com/theothermike/3e78aa38815c944b567f336a288e4e89

### Panic Output
https://gist.github.com/theothermike/3e78aa38815c944b567f336a288e4e89

### Expected Behavior
Not crash.  I ran same configs last week with 0.11.3 against another environment and current terraform-provider-google git (as of 3/18/2018) and it worked

### Actual Behavior
crash

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
the output contains references to a lot of other HCL we use to define the rest of the infra.   I've scrubbed the tfvars gist links of client identifying data

### References

**Comment by theothermike** [comment]
updated gist link with crash.log:  https://gist.github.com/theothermike/3e78aa38815c944b567f336a288e4e89

**Comment by blackjid** [comment]
Hi, I having a similar error

```
Error: Error applying plan:

1 error(s) occurred:

* module.apps_mysql.google_sql_database_instance.main: 1 error(s) occurred:

* google_sql_database_instance.main: unexpected EOF
```

**Comment by theothermike** [comment]
still happening on 0.11.7 w 1.12 of provider.  

"panic: interface conversion: interface {} is nil not map[string]interface {}"
