### ISSUE TITLE
Terraform fails to find existing kubernetes cluster with same name when removed from state

### ISSUE THREAD

**Issue by tanner-bruce** [terraform-providers/terraform-provider-google#1268]
### Terraform Version
```
Terraform v0.11.5
+ provider.google v1.5.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Affected Resource(s)
`google_container_cluster`

### Terraform Configuration Files
```hcl
resource "google_container_cluster" "primary" {
  name               = "mycluster"
  zone               = "${var.zone}"
  network            = "${var.network}"
  subnetwork            = "${var.network}"
  initial_node_count = 1

  min_master_version = "${data.google_container_engine_versions.central1a.latest_master_version}"

  master_auth {
    username = "${file("data/secrets/k8s/cluster_user")}"
    password = "${file("data/secrets/k8s/cluster_pass")}"
  }

  enable_legacy_abac = false

  node_config {
    preemptible  = false
    machine_type = "n1-standard-4"

    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]
    tags = "${var.tags}"
  }
}
```
### Expected Behavior

Terraform sees that cluster already exists

### Actual Behavior

Terraform does not see that the cluster exists during plan and fails during apply

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -out=plan`
2. `terraform apply plan`

**Comment by sl1pm4t** [comment]
This is the expected behaviour of Terraform.
You can use `terraform import` to bring the cluster resource back into the state file, then Terraform knows the cluster exists and won't try to create on the next run.
e.g.
`terraform import google_container_cluster.mycluster us-east1-a/my-cluster`
