### ISSUE TITLE
google_container_cluster with custom service account is unable to pull from gcr.io

### ISSUE THREAD

**Issue by theothermike** [terraform-providers/terraform-provider-google#1273]
### Terraform Version
0.11.5
1.8.0 of provider plugin

### Affected Resource(s)
google_container_cluster

### Terraform Configuration Files
```hcl
resource "google_container_cluster" "primary_cluster" {
  name                              = "${var.environment_name}-${var.client}-kubernetes01-${var.region}"
  zone                              = "${var.zone}"
  logging_service                   = "none"
  monitoring_service                = "none"
  network                           = "${var.network}"
  initial_node_count                = "${var.node_count}"
  enable_legacy_abac                = false

  node_config {
    disk_size_gb    = "${var.disk_size}"
    machine_type    = "${var.machine_type}"
    service_account = "${var.service_account}@${var.project}.iam.gserviceaccount.com"
    tags            = ["kubernetes", "${var.environment_name}"]
  }

  min_master_version = "${var.kubernetes_version}"
  node_version       = "${var.kubernetes_version}"
}```

using 1.9.6.gke.1 (latest)

### Debug Output
n/a

### Panic Output
n/a 

### Expected Behavior
When creating a k8s cluster using google_container_cluster and specifying a custom Service Account, the cluster is unable to pull from the private gcr.io repo (in same project as, even though the service account was entitled with read access to the underlying storage bucket.

### Actual Behavior
unable to pull from private gcr.io container registry.  I verified this by creating the cluster by hand using the GUI with the same specs and service account, afterwards it was able to pull the image properly

### Steps to Reproduce
1. `terraform apply`

### Important Factoids

### References

**Comment by emilymye** [comment]
Hi @theothermike, can you post your debug logs? (running `export TF_LOG="DEBUG"` before `terraform apply`). I don't have a lot of experience with the container registries but will try to debug.

**Comment by ndmckinley** [comment]
Ping - can you send along the debug logs for this issue?

**Comment by rosbo** [comment]
Does your custom service account `${var.service_account}@${var.project}.iam.gserviceaccount.com` have read access to the storage bucket storing the images in gcr.io?

**Comment by theothermike** [comment]
Yes, the service account has read access (i even gave it project editor access, just in case).     Creating the Cluster by hand using the GUI, with the custom service account, it works perfect as expected (which I just did on a new cluster I had created using the Terraform provider, and ran into the same problem)

Given that I've run into this problem twice, both using the Terraform provider, it should be easy for you to reproduce on your end with the conditions I stated (custom service account defined in the terraform config).

**Comment by theothermike** [comment]
Do you have a secure way for me to provide you the debug logs?  Can i email them to you directly?  there is a lot of GCP specific output with secrets and client specific info, that I would rather not provide in a public bug ticket

**Comment by emilymye** [comment]
@theothermike I sent you an update over email but as mentioned, it might be related to node_config .oauth_scopes

**Comment by watiko** [comment]
I checked GCP Console's REST output then I realized that required scope is `["https://www.googleapis.com/auth/cloud-platform"]`.

```
node_config {
  machine_type    = "${var.machine_type}"
  service_account = "${var.service_account}@${var.project}.iam.gserviceaccount.com"
  oauth_scopes    = ["https://www.googleapis.com/auth/cloud-platform"]
}
```

**Comment by danawillow** [comment]
@theothermike, can this issue be closed? Have you tried adding the cloud-platform scope like in @watiko's comment?

**Comment by theothermike** [comment]
@danawillow I'm testing this today, will confirm and close this if it works

**Comment by theothermike** [comment]
confirmed, this works with the oauth scopes as described
