### ISSUE TITLE
Support advanced routing in `google_compute_router`

### ISSUE THREAD

**Issue by vincepri** [terraform-providers/terraform-provider-google#1278]
BGP Peers now support `CUSTOM` advertise mode, which is documented [here](https://cloud.google.com/compute/docs/reference/rest/v1/routers/insert). 

Custom mode allows to set `advertisedGroups` and `advertisedIpRanges` which are really useful when connecting to external providers and to allow route summarization.

**Comment by morgante** [comment]
Isn't this supported already? https://www.terraform.io/docs/providers/google/r/compute_router.html#advertised_ip_ranges

**Comment by danawillow** [comment]
Added in #1723
