### ISSUE TITLE
Retrying on 503 errors?

### ISSUE THREAD

**Issue by andyshinn** [terraform-providers/terraform-provider-google#1283]
I am trying to run `terraform plan -detailed-exitcode` periodically as a CI job to detect when workspaces diverge. But I am noticing a lot of HTTP 503 errors that fail the job. I am wondering if these should be retried and this is considered a bug?

I am also noting that the 503 errors always seem to happen on `google_sql_user`:

```
* google_sql_user.myname: google_sql_user.myname: Error reading SQL User "myname" in instance "database-9368152c": googleapi: Error 503: Service temporarily unavailable., serverException
```

### Terraform Version
```
$ terraform -v
Terraform v0.11.5
+ provider.google v1.6.0
+ provider.ns1 v1.0.0
+ provider.random v1.1.0
+ provider.zerotier (unversioned)
```

### Affected Resource(s)
- google_sql_user

### Terraform Configuration Files
```hcl
resource "google_sql_database_instance" "master" {
  name             = "mydbname"
  database_version = "MYSQL_5_7"
  region           = "us-east1"

  settings {
    tier             = "db-n1-standard-2"
    disk_size        = 100
    replication_type = "SYNCHRONOUS"

    backup_configuration {
      binary_log_enabled = true
      enabled            = true
    }

    database_flags {
      name  = "group_concat_max_len"
      value = "1000000"
    }

    database_flags {
      name  = "sql_mode"
      value = "TRADITIONAL"
    }

    database_flags {
      name  = "log_bin_trust_function_creators"
      value = "on"
    }
  }
}

resource "google_sql_user" "myname" {
  name     = "myname"
  instance = "${google_sql_database_instance.master.name}"
  host     = "%"
  password = "us3rp4ss"
}
```

### Debug Output
None yet. Will provide if useful.

### Panic Output
None.

### Expected Behavior
Multiple plans a day do not fail with HTTP 503 errors.

### Actual Behavior
Multiple plans (on a 30 minute interval) fails with HTTP 503s.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Run `terraform plan -detailed-exitcode` on a 30 minute job.

### Important Factoids
Running on a GCE instance so it shouldn't necessarily be local network related.

### References
None.

**Comment by rosbo** [comment]
@danawillow Did you reach out to the Google Cloud SQL team about these 503? I remember you looked into it because this is causing flakiness for our acceptance tests.

**Comment by rosbo** [comment]
With the work in #1212, we will be retrying on 503. Thanks

**Comment by francisd** [comment]
This is still an issue with v1.18 provider.  We have a 5 GCP Postgres DB, and the likelihood of failure increases as it randomly 503 a different each time.  

```
* module.jinx-production.google_sql_database.jinx: 1 error(s) occurred:

* module.jinx-production.google_sql_database.jinx: google_sql_database.jinx: Error reading SQL Database "jinx" in instance "jinx": googleapi: Error 503: Service temporarily unavailable., serverException

* module.julius-production.google_sql_database.julius: 1 error(s) occurred:

* module.julius-production.google_sql_database.julius: google_sql_database.julius: Error reading SQL Database "julius" in instance "julius": googleapi: Error 503: Service temporarily unavailable., serverException
```

Can the retries be increased from 3 with a exponential backoff period as it always looks to be intermittent with different DB instances.  We'd rather wait a few extra minutes than wait for an entire terraform plan to run again.  Thanks

**Comment by danawillow** [comment]
Looks like that's for the `google_sql_database` resource, which is a different one. #2055 is an open issue for that.
