### ISSUE TITLE
Support for gcp bucket transfers

### ISSUE THREAD

**Issue by markfra** [terraform-providers/terraform-provider-google#1286]
Hi,

Currently it's not possible to create a bucket-transfer in combination terraform.
We would like to use transfers for various reasons, but mainly for automated backups.

### Terraform Version
0.11.1

### Affected Resource(s)
Please list the resources as a list, for example:
- resource_storage_bucket_transfer

### Expected Behavior

We would like to define transfers as a resource, for example:

    resource "google_storage_bucket_transfer" "transfer" {
      bucket = "your-bucket-name"
      jobspec = { spec }
    }

**Comment by rosbo** [comment]
Hi @markfra,

Can you add a bit more details about your use case please? Which feature are you referring too? The resource you are listing above does not exist but you are talking about supporting import for it...

Thank you

**Comment by lloydcotten** [comment]
+1 for this feature.  No so sure about the resource example in the OP, since a transfer consists of just one transfer job, not a list.  But yes would love to be able to configure this via terraform.

**Comment by markfra** [comment]
@lloydcotten you are correct. Within GCP its 1 spec per job. so it should not be a list (updated the example).

**Comment by mrsimo** [comment]
Yes please! We'd like to use this too, if possible!

**Comment by Kiraco** [comment]
Any news if this will be implemented? :)

**Comment by larsha** [comment]
Same here, would be awesome to get this in so we can create scheduled transfers as we create new buckets 👍

**Comment by akramhussein** [comment]
I've created a PR #2164 that builds upon @ReneKroon's work with the amendments suggested by @rosbo.

**Comment by akramhussein** [comment]
I'm still working to complete this PR - believe I'm very close to having it done. 
Current progress can be seen [here](https://github.com/zoe/terraform-provider-google)

**Comment by rileykarson** [comment]
Support has been added by @akramhussein in https://github.com/GoogleCloudPlatform/magic-modules/pull/1069 and this feature will be released in `2.0.0` 🎉
