### ISSUE TITLE
Reuse the same GOOGLE_FOLDER for our data source acceptance tests.

### ISSUE THREAD

**Issue by rosbo** [terraform-providers/terraform-provider-google#1295]
To avoid creating/deleting a bunch of folders, our tests for the google_folder and the google_active_folder datasource should reuse the same folder.

**Comment by rileykarson** [comment]
While it's not _ideal_ that we create/destroy a lot of folders, unless it becomes an issue for some reason I'm inclined to say we don't need to bother with doing this. Closing out- if anyone sees this and feels strongly that we should do this, feel free to reopen/refile.
