### ISSUE TITLE
node_pools don't support regional clusters

### ISSUE THREAD

**Issue by Stono** [terraform-providers/terraform-provider-google#1300]
Hey, 
We're trying to rebuild our clusters using the new regional clusters added in 1.9.0, however we use `google_container_node_pool` to add custom pools to our cluster.

The node pools however do not work against regional clusters:

```
Error: Error applying plan:

1 error(s) occurred:

* module.kubernetes.google_container_node_pool.custom-pool: 1 error(s) occurred:

* google_container_node_pool.custom-pool: Error creating NodePool: googleapi: Error 400: v1 API cannot be used to access GKE regional clusters. See https://goo.gl/uHKp3k for more information., badRequest
```

**Proposal**
I think the [google_container_node_pool](https://www.terraform.io/docs/providers/google/r/container_node_pool.html) resource should be changed with:

  - A region parameter added which has the description of "The location of the kubernetes regional master, for use with regional clusters"
  - The zone parameter description changed to "The location of the kubernetes zonal master, for use with zonal clusters"
  - The parameters should be mutually exclusive, with zone using the existing code process and region using the newer v1beta1 api which handles regional clusters (https://cloud.google.com/kubernetes-engine/docs/reference/api-organization#beta)

Associated issue: https://github.com/terraform-providers/terraform-provider-google/issues/829
Associated PR for master regional clusters: https://github.com/terraform-providers/terraform-provider-google/pull/1181

**Comment by Stono** [comment]
@danawillow :-) I tried!

**Comment by darrenhaken** [comment]
I'll take this up @Stono

**Comment by Stono** [comment]
Thank you oh random stranger @darrenhaken who definitely doesn't work in my office :)

**Comment by morgante** [comment]
I'm also encountering this bug.

**Comment by Stono** [comment]
This works now so closing the issue :-) ta
