### ISSUE TITLE
What IAM permissions do I need to give a role for developing the provider?

### ISSUE THREAD

**Issue by darrenhaken** [terraform-providers/terraform-provider-google#1306]
I've picked up #1300 which is my first Google provider contrib but I've tried to run one of the tests and I receive this error:

```
* google_container_cluster.cluster: googleapi: Error 403: Google Compute Engine: Required 'compute.networks.get' permission for 'projects/sandbox/global/networks/default', forbidden
```

Can anyone offer advice on what IAM permissions I'd need?

We have been using TF for a while and not seen this issue before.

**Comment by Stono** [comment]
@danawillow any chance you can help @darrenhaken and I resolve this so we can work on https://github.com/terraform-providers/terraform-provider-google/issues/1300 ? 

It seems extremely strange as we've created a brand new project and created a service account with the following IAM roles:

  - Compute Admin
  - Compute Instance Admin (v1)
  - Compute Network Admin
  - Kubernetes Engine Admin
  - Editor
  - Owner

And we're still seeing this.  I feel like the 403 is a red herring and something else is actually wrong in the way we're setting credentials.

@darrenhaken can you please post the output from the test run with TF_LOG=DEBUG

**Comment by Stono** [comment]
I think we may have got to the bottom of this... will update soon!

**Comment by danawillow** [comment]
@darrenhaken @Stono any updates? You're right that I can't really tell what's going on without debug logs. I'm also inclined to agree that the 403 is likely a red herring, but I'd double check to make sure you're using the service account you think you are (it should say in the debug logs how you're authenticating)

**Comment by Stono** [comment]
Closing this issue in favour of #1313 which highlights the issue was due to a bad IAM policy caused by race conditions in TF

**Comment by darrenhaken** [comment]
Closed

**Comment by bluemalkin** [comment]
Hi - I'm hitting this issue but despite reading the related issues I cannot figure out the fix.

I have the latest terraform and my service account has owner permission on the project with the shared VPC.
Am I missing something ?

Thanks

**Comment by danawillow** [comment]
Hey @bluemalkin, can you file a separate issue and fill out the issue template (including debug logs)? Thanks!

**Comment by bluemalkin** [comment]
@danawillow sure #1711
