### ISSUE TITLE
Add create timeout support for google_compute_snapshot

### ISSUE THREAD

**Issue by techwolf359** [terraform-providers/terraform-provider-google#1307]
Hello!

I'm trying to use google_compute_snapshot to take a snapshot of a source disk before creating a new disk from the just-created snapshot. Here's the basics:

```
resource "google_compute_snapshot" "mysql-data-snapshot" {
  count       = "1"
  name        = "mysql-data-snapshot-${lookup(var.instances, 0)}"
  source_disk = "mysql-data-${lookup(var.instances, 0)}"
  zone        = "${var.region_zone_pri}"
}

resource "google_compute_disk" "mysql-data-disk" {
  count = "${var.size}"
  name  = "mysql-data-${lookup(var.instances, count.index)}"
  type  = "${var.disk_type}"
  zone  = "${count.index == 0 ? var.region_zone_pri : (count.index == 1 ? var.region_zone_sec : var.region_zone_ter)}"
  size  = "${var.data_disk_size}"
  snapshot = "${count.index == 1 ? google_compute_snapshot.mysql-data-snapshot.self_link : ""}"
  # depends_on = [ "google_compute_snapshot.mysql-data-snapshot" ]

  lifecycle {
    ignore_changes = ["snapshot"]
    prevent_destroy = true
  }

}
```

Running apply, I get:

> * google_compute_snapshot.mysql-data-snapshot: Error waiting for Creating Snapshot: timeout while waiting for state to become 'DONE' (last state: 'RUNNING', timeout: 4m0s)

I tried to add this to give us more time to create the snapshot:

```
  timeouts {
    create = "60m"
  }
```

That results in an error:

> * module.dbserver.module.dbserver1.google_compute_snapshot.mysql-data-snapshot: [ERR] Error decoding timeout: Timeout Key (create) is not supported

I think adding create timeout support to the google_compute_snapshot would allow it the time to complete, and continue on with the creation I'm looking for.

**Comment by catsby** [comment]
Hey all – the `timeout` is a feature that each resource must opt-in to, meaning a developer must add support for it where it's useful / reasonable. 

For anyone looking to take a stab at it, AWS DB Instance implements time-outs for create, update, and delete

- https://github.com/terraform-providers/terraform-provider-aws/blob/2d4e976d2c149f049ebb3348d91d8bcc9c6654b5/aws/resource_aws_db_instance.go

**Comment by ndmckinley** [comment]
I can add a timeout to that resource, sure.
