### ISSUE TITLE
Make org_id optional when creating a new project

### ISSUE THREAD

**Issue by ubschmidt2** [terraform-providers/terraform-provider-google#131]
### Terraform Version
Terraform v0.10.0-dev (9706042ddd51b85a46e23356536a1d812efa5a38+CHANGES)

### Affected Resource(s)
- google_project

### Terraform Configuration Files
```hcl
provider "google" {
  region  = "us-central1"
}

resource "google_project" "project" {
  name            = "stschmidt-tf-021"
  project_id      = "stschmidt-tf-021"
}
```

### Debug Output
https://gist.github.com/ubschmidt2/91ef1af6ae9587b21f3bdbe1c9d38713

### Expected Behavior
Should successfully create the GCP project.

### Actual Behavior
```
1 error(s) occurred:

* google_project.project: "org_id": required field is not set
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
The organization is optional in the underlying Resource Manager API. Also, the GCloud CLI doesn't required an organization (example: `gcloud projects create stschmidt-tf-021)`.

### References
- https://cloud.google.com/resource-manager/reference/rest/v1/projects#Project
- https://cloud.google.com/sdk/gcloud/reference/projects/create

**Comment by danisla** [comment]
Can we close this since TF cannot create projects without parent using a service account?

**Comment by ubschmidt2** [comment]
@danisla: This change benefits human users that do not have an org. It allows them to use Terraform for project creation, too.
