### ISSUE TITLE
Multiple race condition issues in google_project and google_project_services

### ISSUE THREAD

**Issue by Stono** [terraform-providers/terraform-provider-google#1313]
Hi, 
We were recently working on https://github.com/terraform-providers/terraform-provider-google/issues/1300 and were experiencing 403 errors when using our new "test" project. 

This led us to raising https://github.com/terraform-providers/terraform-provider-google/issues/1306 for support however, upon further investigation it seems like the "test" project was being created with an incorrect IAM policy; one in which the compute engine API service accounts had no permissions.

There was also another problem highlighted during the project creation and that was a race condition on creating buckets on a new project.

**The Sequence (Part 1: Bucket)**

We have the following code in a module called `standard_project`.  
```
resource "google_project" "project" {
  name            = "${var.name}"
  project_id      = "${var.name}"
  billing_account = "${var.billing_account_id}"
  folder_id       = "${var.folder}"
}

locals {
  standard_apis = [
    "containerregistry.googleapis.com",
    "pubsub.googleapis.com",
    "compute.googleapis.com",
    "servicemanagement.googleapis.com",
    "dns.googleapis.com",
    "deploymentmanager.googleapis.com",
    "replicapool.googleapis.com",
    "replicapoolupdater.googleapis.com",
    "resourceviews.googleapis.com",
    "monitoring.googleapis.com",
    "logging.googleapis.com",
    "container.googleapis.com",
    "storage-api.googleapis.com"
  ]
}

resource "google_project_services" "enabled-apis" {
  project = "${google_project.project.project_id}"
  services = "${concat(local.standard_apis, var.additional_apis)}"
  disable_on_destroy = "true"
}

resource "google_storage_bucket" "terraform-bucket" {
  name     = "terraform-${google_project.project.name}"
  project  = "${google_project.project.project_id}"
  force_destroy = false
  location = "EU"
}
```

And we invoke it like so:

```
module "project-delivery-platform-broken-tf" {
  source = "./modules/basic-project"
  name = "at-delivery-platform-broken-tf"
  billing_account_id = "${local.billing_account_id}"
  folder = "${google_folder.delivery-engineering.name}"
}

resource "google_project_iam_policy" "iam-delivery-platform-broken-tf" {
  project     = "${module.project-delivery-platform-broken-tf.project_id}"
  policy_data = "${data.google_iam_policy.delivery-platform-broken-tf-policy.policy_data}"
}

data "google_iam_policy" "delivery-platform-broken-tf-policy" {
  binding {
    role = "roles/editor"
    members = [
      "domain:autotrader.co.uk"
    ]
  }
}
```

The first time you run this code, you'll see this error:
 `* google_storage_bucket.terraform-bucket: googleapi: Error 403: The project to be billed has not configured billing., accountDisabled`.  

If you then wait a second, and re-run the plan you will see that the bucket, and the IAM policy remain:
```
  ~ google_project_iam_policy.iam-delivery-platform-broken-tf
      policy_data:   "{\"bindings\":[{\"members\":[\"serviceAccount:service-473114872189@container-engine-robot.iam.gserviceaccount.com\"],\"role\":\"roles/container.serviceAgent\"},{\"members\":[\"domain:autotrader.co.uk\",\"serviceAccount:473114872189-compute@developer.gserviceaccount.com\",\"serviceAccount:473114872189@cloudservices.gserviceaccount.com\",\"serviceAccount:service-473114872189@containerregistry.iam.gserviceaccount.com\"],\"role\":\"roles/editor\"}]}" => "{\"bindings\":[{\"members\":[\"domain:autotrader.co.uk\"],\"role\":\"roles/editor\"}]}"

  + module.project-delivery-platform-broken-tf.google_storage_bucket.terraform-bucket
      id:            <computed>
      force_destroy: "false"
      location:      "EU"
      name:          "terraform-at-delivery-platform-broken-tf"
      project:       "at-delivery-platform-broken-tf"
      self_link:     <computed>
      storage_class: "STANDARD"
      url:           <computed>
```

At this point, you can run the apply again and the bucket will be successfully created.

**Perceived issue**:  Billing takes a moment to be correctly configured to the project, the `google_project` resource needs to be a bit more intelligent as to waiting for the project to be `ready`.

**The Sequence (Part 2: IAM Policy)**

The IAM policy at this point also gets created **however** the compute service account, and kubernetes service accounts which are added as part of the `enabled_apis` above have been removed, and the project is left in a non-working state.

Now, the interesting part here is if you did all this again without the `google_project_iam_policy` and `google_iam_policy` blocks, created the project and then after successful project creation - added those blocks back and run it again, it works.  It appears as if the `google_iam_policy` data block reads the existing policy and amends your values to it (thus including the service accounts) so this needs to be done AFTER the enabled_apis.

**Perceived issue**:  The `google_iam_policy` is computed and stores the "current state" of the IAM policy prior to the enabled_apis being run.  Enabling an api which modifies the IAM policy after the `google_iam_policy` block has been run will end up with a race condition.

**Logs**
I have captured debug logs for this entire; multi-run process and can provide them to you by email!

Thanks
Karl

**Comment by ndmckinley** [comment]
Hi there!

Part 1: the API for enabling billing is marked as synchronous in the Cloud Platform docs, but if you're seeing some kind of propagation delay, I'll see what we can do about that.  Probably just have to add in a write-read loop instead of the simple write we've got now.  Sorry for the inconvenience!

---

Part 2: Definitely confusing!  `foo_iam_policy` is a very blunt instrument and there are lots of ways that using it can go wrong.  In almost all cases we recommend you use `foo_iam_members` or `foo_iam_binding` instead, because this is just one of many ways that its behavior is unintuitive.

However, I'm inclined to argue that the behavior is _correct_, despite being confusing - you've got a config which applies a blanket IAM policy, and in parallel it performs an operation with the side effect of modifying that policy, which is a race condition.  Put another way, from my perspective this race condition is in the config there, and not in the provider, which generally does not try to protect you from race conditions of this sort when they'd require external locks, synchronization, or global operation ordering.

Does that explanation seem sensible?  If you think something should be done in the provider, what kind of behavior are you looking for?

**Comment by Stono** [comment]
Hey,
Thanks for the response.
I think you're right and there is a strange situation where google_iam_policy manages an entire policy but there are other providers, such as enabled_apis which result in that IAM policy being modified outside of terraform state....

Will think about it more, I'm half inclined to suggest not permitting the use of certain providers in the same project when they're known to conflict?

**Comment by ndmckinley** [comment]
>Will think about it more, I'm half inclined to suggest not permitting the use of certain resources in the same project when they're known to conflict?

I like the thought, but unfortunately I don't think it's something we have the ability to do - I'm not aware of any terraform provider hooks where you can operate on the whole plan graph.

>As for the bucket, I added a local-exec with a sleep 10 on the project resource for now!
I'll try and get around to adding that loop soon, but glad you found something that works in the meantime.  :)

**Comment by Stono** [comment]
Cheers for fixing the fixable part of this @ndmckinley - we switched our IAM policy control to "member" resources for the other one as suggested.
