### ISSUE TITLE
Rolling upgrade - max_unavailable_fixed is not being set to 0

### ISSUE THREAD

**Issue by shaharmor** [terraform-providers/terraform-provider-google#1314]
Hi,

### Terraform Version
Terraform v0.11.6

### Affected Resource(s)
- google_compute_instance_group_manager

### Terraform Configuration Files
```hcl
resource "google_compute_instance_group_manager" "router" {
  update_strategy    = "ROLLING_UPDATE"

  rolling_update_policy {
    type                  = "PROACTIVE"
    minimal_action        = "REPLACE"
    max_surge_fixed       = 1
    max_unavailable_fixed = 0
    min_ready_sec         = 120
  }
}
```

### Debug Output
I can't copy the debug output as it includes some stuff that we prefer not to share, but in the logs I see that the response from GCE is
```
2018-04-10T12:22:31.590+0300 [DEBUG] plugin.terraform-provider-google_v1.9.0_x4:   "maxUnavailable": {
2018-04-10T12:22:31.590+0300 [DEBUG] plugin.terraform-provider-google_v1.9.0_x4:    "calculated": 1
2018-04-10T12:22:31.590+0300 [DEBUG] plugin.terraform-provider-google_v1.9.0_x4:   },
```
While it should be:
```
{
 "maxUnavailble": {
  "fixed": 0,
  "calculated": 0
 }
}
```

### Expected Behavior
The correct max unavailable value be set when using 0 as the value.

### Actual Behavior
If the value is 0, it is not being set.

### Steps to Reproduce
1. `terraform apply`

### References
This should have been fixed here:
- https://github.com/terraform-providers/terraform-provider-google/pull/1260/files
But its still not working.

I think that its not possible to set the `MaxUnavailable` value to 0 from the API, according to https://cloud.google.com/compute/docs/reference/rest/beta/instanceGroupManagers/update

> resource.updatePolicy.maxUnavailable.fixed | numberSpecifies a fixed number of VM instances. This must be a positive integer.

**Comment by ndmckinley** [comment]
It's correct that it's not possible to set `MaxUnavailable` to 0.  If you could set that, you'd be asking for a rolling update without taking any instances down, which of course can't be done.

Since that's not possible, what behavior would you expect to see here?  The existing behavior takes an approach I'm inclined to like, and the only alternative I can suggest is for terraform to present you with an error since the config is invalid.

**Comment by shaharmor** [comment]
> It's correct that it's not possible to set MaxUnavailable to 0. If you could set that, you'd be asking for a rolling update without taking any instances down, which of course can't be done.

This is incorrect. In the UI you can set MaxUnavailable when manually running a rolling update.
You can only set it to 0 if you set MaxSurge to a positive number, in which case a new server will be added before one is removed, always keeping your number of servers at the configured minimum.

**Comment by ndmckinley** [comment]
Aha, I see.  The API docs and the other docs disagree, and the behavior of the UI matches the other docs... since the UI uses the same API we do, I bet if we just sent along a `maxSurge: 1` / `maxUnavailable: 0` it would work, even though the docs say it shouldn't...  :)  Let me test that.

**Comment by ndmckinley** [comment]
Okay, looking at the code it seems that we already do.  I see that you can't share your debug output, but can you copy the `PUT` request we send to initiate the update?

**Comment by shaharmor** [comment]
Hm.. seems to be working now. I think I had to modify it to something other than 0 and then change back while in version 1.9
