### ISSUE TITLE
Feature request: Cloud Armor

### ISSUE THREAD

**Issue by bdronneau** [terraform-providers/terraform-provider-google#1315]
Hi,

Thanks to provide GCP in Terraform. I am currently looking forward to use Cloud Armor and stop having IPs list in nginx. 
For now, it's only a beta product, but maybe someone is already looking to integrate it.
There is no trace of armor in [google api go client](https://github.com/google/google-api-go-client/), so for now I've to wait before give a try develop something on this subject.

### References
- https://cloud.google.com/armor/

**Comment by danawillow** [comment]
Hey @bdronneau, we have Cloud Armor support via the security policy resource: https://www.terraform.io/docs/providers/google/r/compute_security_policy.html, which can also be referenced from backend services: https://www.terraform.io/docs/providers/google/r/compute_backend_service.html#security_policy. Did you have any other functionality in mind for Cloud Armor support?

**Comment by bdronneau** [comment]
Hi @danawillow ,
I've missed this part, and it contains all I need to bootstrap Cloud Armor.
Many thank.
