### ISSUE TITLE
allow_stopping_for_update causes wrong ephemeral IP state

### ISSUE THREAD

**Issue by andyshinn** [terraform-providers/terraform-provider-google#1317]
Not quite sure if this is considered a bug but definitely caused some confusion for us.

When resetting an instance it will retain its ephemeral IP. However, when stopping / starting and instance with an ephemeral IP address, it will get a new IP. The `allow_stopping_for_update` means that `network_interface.0.access_config.0.assigned_nat_ip` will be out of sync.

### Terraform Version
```
$ terraform -v
Terraform v0.11.5
+ provider.google v1.8.0
+ provider.ns1 v1.0.0
+ provider.random v1.1.0
+ provider.zerotier (unversioned)
```

### Affected Resource(s)
- google_compute_instance

### Expected Behavior
When changing a parameter that requires `allow_stopping_for_update`, the change should also update `network_interface.0.access_config.0.assigned_nat_ip`.

### Actual Behavior
The `network_interface.0.access_config.0.assigned_nat_ip` output of the instance is incorrect after changing scope (which causes an instance to be stopped and then started).

### Steps to Reproduce
1. Create a `google_compute_instance` with ephemeral IP and `allow_stopping_for_update` set to `true`.
1. Compare `network_interface.0.access_config.0.assigned_nat_ip` and the actual ephemeral IP (which should be in sync).
1. Change the instance scopes (which will cause the instance to stop and start).
1. Compare `network_interface.0.access_config.0.assigned_nat_ip` and the actual ephemeral IP (now different).

### Important Factoids
May not necessarily be a bug. In our case it made sense to taint the resource and recreate it (so that other resources depending on the IP were updated). If this is the case maybe pointing this out in docs makes sense.

**Comment by ndmckinley** [comment]
I agree with you that it might not be a bug - or, at least, in my opinion, it's not a provider bug.  The state does actually get updated - if you set an output for `network_interface.0.access_config.0.assigned_nat_ip` you'll see the new value there.  I've just tested with an instance (swapping instance size).  A second `terraform apply` should propagate those changes, but if it doesn't then that's probably an upstream issue.

In another sense, this is one of the caveats of `allow_stopping_for_update` - unless you explicitly set the address by reserving one with the `google_compute_address` resource, the IP is going to change on unrelated updates.

What do you think?

**Comment by ndmckinley** [comment]
I'm going to close this issue since I believe I've answered it, but don't let that dissuade you from reopening the issue if you think there's more here.

**Comment by andyshinn** [comment]
I guess the state _is_ updated. I was more concerned that other dependents of `network_interface.0.access_config.0.assigned_nat_ip` did not get updated (I was thinking that `allow_stopping_for_update` could somehow signal that it was changed so dependents would know). But if this isn't something really part of Terraform (I'm guessing it has to be a full delete / create) then probably not worth getting into.

**Comment by ndmckinley** [comment]
Yeah, that's a tough one - since Terraform only executes the things it knows about at plan time, and `allow_stopping_for_update` doesn't signal that the IP address may be updated, the downstream resources can't know about that change during plan time.  Running `apply` twice is the best thing I can suggest.  Have you tried that?  Does it work for you?

**Comment by andyshinn** [comment]
Yes, that does work. It was just not apparent at first. We're just going to work to try and avoid using `allow_stopping_for_update` as it has a more predictive result.
