### ISSUE TITLE
Add support for folders

### ISSUE THREAD

**Issue by ubschmidt2** [terraform-providers/terraform-provider-google#132]
### Terraform Version
Terraform v0.10.0-dev (9706042ddd51b85a46e23356536a1d812efa5a38+CHANGES)

### Affected Resource(s)
- google_project

### References
- https://cloud.google.com/resource-manager/docs/creating-managing-folders
- https://cloud.google.com/resource-manager/reference/rest/v2beta1/folders

**Comment by danawillow** [comment]
This is blocked on https://github.com/terraform-providers/terraform-provider-google/issues/93, but is absolutely on our radar.

**Comment by rileykarson** [comment]
Looking at https://cloud.google.com/resource-manager/docs/creating-managing-folders, it looks like this has entered GA.

**Comment by ubschmidt2** [comment]
Identified use cases:

- affecting the existing resource type "google_project":
  - create a new GCP project in a given existing GCP folder.
    (Implementation note: I'd suggest to add a "folder_id" attribute to "google_project". This should only require a minor change to the call to v1/projects/create. If "folder_id" is set, then parent ResourceId.type="folder".)
  - move a TF-managed GCP project between folders and between org node and folder.
    (Implementation note: This should be just a matter of updating the project with the appropriate parent ResourceId.)
- for configuring GCP folders:
  - create a new GCP folder (+destroy)
    (Implementation note: uses the resource-manager v2/folders API. New TF resource type "google_folder".)
  - move a TF-managed GCP folder into a given existing GCP folder or to the org node.
    (Implementation note: see the v2/folders/move API.)
  - configure the IAM policy of a GCP folder.
    (Implementation note: This looks very similar to what already exists for "google_project". However, since IAM policies can be set on many different resource types, it might make sense to revisit the current approach, maybe it can be generalized a bit so that it works for other resource types, too.)
  - configure constraints on a GCP folder.
    (Implementation note: Constraints can be set on the org node, folder(s), and the project, thus need a solution that works (or could be extended to work) for all levels.)

**Comment by rosbo** [comment]
I created 4 new issues to track the different use cases we identified to make it easier to track progress.

This task will be kept open until all children issues are resolved.

#411 is being tackled by @ubschmidt2 & @srivasta
#412 is being tackled by @rosbo
I (@rosbo) will probably take over #413 once I am done with #412.

#414 is up for grab. I might take it if I have the bandwidth once I am done with #412 and #413

cc/ @danawillow
