### ISSUE TITLE
name_prefix must be resurrected 

### ISSUE THREAD

**Issue by shamil** [terraform-providers/terraform-provider-google#1326]
Hi,

I understand that it was decided to remove `name_prefix` to avoid complexity of the provider's code. I was totally agree with the decision. **BUT!** After I started migrating to `random_id` resource, it became my worst nightmare. 

Adding keepers made my `terraform` code unmanageable. It is error prone, most of the time you can't get your keepers right and need to focus on this little thing like random prefix instead of focusing on the logic of the resources and provisioning.

My keepers sometimes are bigger than the resource itself. This is just too much non-relevant, unneeded, and mostly duplicated code all over the places. I don't know how to express the headache, really.

This comment https://github.com/terraform-providers/terraform-provider-google/issues/1054#issuecomment-380672270 from @negz is a classic example...

btw,  having `name_prefix` just for `google_compute_instance_template` will do our life much brighter, because this is the most used resource IMO and requires `lifecycle { create_before_destroy = true }` to work properly.

Not sure this will convince you, but I had to try.
Please, please reconsider.

**Comment by shamil** [comment]
Hi @paddycarver 

Sorry if you got the impression that I fill like you don't care. This was not my intention. The reason that I expressed the way I did, is that from my experience for larger projects such as `terraform`, usually once something merged it is really hard to convince maintainers/core committers to roll back something. Most of the time they are right by not rolling back and if something merged it passed multiple approvements and/or discussions. So convincing that is a challenge.

I really glad that I was wrong, I appreciate your care and fast response. Thanks a lot!

**Comment by tholcman** [comment]
It complicates things with `google_container_node_pool` in exactly same way as with template. We can workaround this by creating multiple pools with copy-paste, chaning name and params and then removing old pool, but using `lifecycle { create_before_destroy = true }` looks to me as more terraform-way of doing things.

So what are these "... things that would make the user experience better" behind it? Is it worth of it?

**Comment by mborst** [comment]
I don't know if this is the right place to put this, but it seems like this is the most recent discussion about name `name_prefix` deprecation/undeprecation and I think it is basically an analogous problem. Here it goes:

We use Let's Encrypt certificates for TLS, among others we feed them into `google_compute_ssl_certificate` resources. We have set `google_compute_ssl_certificate` to `create_before_destroy = true` to not have any outages while updating the certificates, which happens regularly because of the short lifetime of these certificates. Since migrating these `google_compute_ssl_certificate` resources away from `name_prefix`, when needing to update the certificate, we run into errors because the name of the certificate does not change, but a certificate with that name already exists.

Now, the question for me is should we just use the `keepers` pattern because it is only the `certificate` parameter that needs to be added and if we read the `certificate` through the random provider, everything will be fine or, because I figure this is a pretty common use case, should this also be handled within terraform instead, e.g. via undeprecation of `name_prefix` for `google_compute_ssl_certificate`?

**Comment by danawillow** [comment]
Maybe? It would be easier for me to understand your use case with a sample config and terraform plan output :)

**Comment by mborst** [comment]
Sorry, I don't have the output anymore (I know, stupid me). It happened when trying to renew the certificate. Terraform complains that the certificate it tries to create (before destroying the old one) already exists, i.e. something along the lines of`[...]/web-static-lb-cert123456789012345678901234567 already exists`, I think with status code 409. So my assumption was that the certificate renewal does not trigger a new name, and thus the conflict.

Here's the code:
```
module "letsencrypt_certificate" {
  source = "../../modules/letsencrypt-certificate"

  server_url            = "${var.letsencrypt_server_url}"
  email_address         = "${var.letsencrypt_account_email_address}"
  common_name           = "${var.domain}"
  dns_challenge_project = "${var.dns_challenge_project}"
  account_key_pem       = "${var.letsencrypt_account_key_pem}"
}

resource "google_compute_ssl_certificate" "main" {
  name        = "${random_id.ssl_certificate_name.dec}"
  project     = "${var.project}"
  private_key = "${module.letsencrypt_certificate.private_key_pem}"
  certificate = "${module.letsencrypt_certificate.certificate_pem}"

  lifecycle = {
    create_before_destroy = true
  }
}

resource "random_id" "ssl_certificate_name" {
  byte_length = 11
  prefix      = "${var.name}-lb-cert"
}
```

**Comment by mborst** [comment]
Ok, I found a way to reproduce the error by setting the minimum required days of TTL for the certificate to a value that forces recreation.
Here's the apply output:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:


-/+ google_compute_ssl_certificate.main (new resource required)
      id:                 "web-get-lb-cert15427085947765536661679668" => <computed> (forces new resource)
      certificate:        <sensitive> => <sensitive> (forces new resource)
      certificate_id:     "2504813478887950532" => <computed>
      name:               "web-get-lb-cert15427085947765536661679668" => "web-get-lb-cert15427085947765536661679668"
      name_prefix:        "" => <computed>
      private_key:        <sensitive> => <sensitive> (attribute changed)
      project:            "my-project" => "my-project"
      self_link:          "https://www.googleapis.com/compute/v1/projects/my-project/global/sslCertificates/web-get-lb-cert15427085947765536661679668" => <computed>

  ~ google_compute_target_https_proxy.main
      ssl_certificates.#: "1" => <computed>


  ~ acme_certificate.main
      certificate_pem:    "-----BEGIN CERTIFICATE-----\n***" => <computed>
      min_days_remaining: "21" => "91"


Plan: 1 to add, 2 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

acme_certificate.main: Modifying... (***)
  certificate_pem:    "-----BEGIN CERTIFICATE-----\n***" => "<computed>"
  min_days_remaining: "21" => "91"
acme_certificate.main: Modifications complete after 2s (***)
google_compute_ssl_certificate.main: Creating...
  certificate:    "<sensitive>" => "<sensitive>"
  certificate_id: "" => "<computed>"
  name:           "" => "web-get-lb-cert15427085947765536661679668"
  name_prefix:    "" => "<computed>"
  private_key:    "<sensitive>" => "<sensitive>"
  project:        "" => "my-project"
  self_link:      "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* google_compute_ssl_certificate.main: 1 error(s) occurred:

* google_compute_ssl_certificate.main: Error creating ssl certificate: googleapi: Error 409: The resource 'projects/my-project/global/sslCertificates/web-get-lb-cert15427085947765536661679668' already exists, alreadyExists

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

I also tried the keepers way like so:

```
keepers = {
  certificate = "${letsencrypt_certificate.certificate_pem}"
}
```

This led to one successful run with a new cert, but on the second run, I got the error described here: https://github.com/terraform-providers/terraform-provider-random/issues/21

**Comment by paddycarver** [comment]
Looking through my notes for this, it looks like we intended to undeprecate this for SSL certificates, for the same reason it made sense for instance_templates, but I think I let it fall through the gaps.

@danawillow, any objection to me just opening a PR to remove the deprecation for SSL certificates, on the grounds that the most common case has a requirement for randomness in the name, and no use cases are opened up by removing name_prefix?

**Comment by danawillow** [comment]
Did we? I don't remember. I think that's fine, go for it 👍 

Just to correct you a teeny bit:
> no use cases are opened up by removing name_prefix?

Anything that's not a part of the REST API makes code generation more difficult. We can do custom code now so it's not a big deal, it just means stuff that has to be maintained separately.

**Comment by paddycarver** [comment]
Opened #1622, which should take care of this. The deprecation message for ssl_certificate resources can be safely ignored, and will go away in the next release of the provider. Sorry for the confusion, everyone!

**Comment by mborst** [comment]
Thanks a lot!

**Comment by vincentbesanceney** [comment]
Looks I'm a bit late on this one, but as @tholcman said, for `google_container_node_pool` resource, it really complicates things. Unless I missed something on how to do it right, we need to add keepers for every parameter that triggers a ForceNew action. A real pain that `name_prefix` handled nicely.

I noticed it's been removed on the 2.0.0 branch, could we bring it back?
