### ISSUE TITLE
[feature request] - Set instance Public DNS PTR Record

### ISSUE THREAD

**Issue by ducksauz** [terraform-providers/terraform-provider-google#1333]
### Terraform Version
0.11.7

### Affected Resource(s)
- google_compute_instance

While this isn't a process that is 100% automate-able, as you have to go to the google webmaster console to claim the name with a TXT record first, it would be helpful if I could set the Public DNS PTR Record for an instance via Terraform.

https://cloud.google.com/compute/docs/instances/create-ptr-record

**Comment by ndmckinley** [comment]
Making good progress on this, but the lack of automatability is making it hard to test.  :)  I'll keep at it!
