### ISSUE TITLE
Question: GCEProvider - acceleratorCount 

### ISSUE THREAD

**Issue by bradserbu** [terraform-providers/terraform-provider-google#1334]
Hi,

**I would like to know how you configure a GPU attachment using terraform and the GCE provider.**

The property on the GCE configuration is "acceleratorCount".  I saw there is logic that seems to support the mapping of this property in the in the "helpers" file in the project.  

_Can someone please explain how to leverage this by providing a sample terraform script to provision an instance with a GPU attached?_

Sincerely,
Brad Serbu

**Comment by danawillow** [comment]
Hey @bradserbu, here's the test case we use for this: https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_instance_test.go#L2495

and here are the docs for the field: https://www.terraform.io/docs/providers/google/r/compute_instance.html#guest_accelerator (you might have to ctrl/cmd-f for the fields it contains).

Does that work? If so I can add another example to that docs page if you think it would be worthwhile.

**Comment by ndmckinley** [comment]
I think Dana has answered the question, so I'm going to close the issue - but please don't let that dissuade you from reopening if you'd like anything more on this.
