### ISSUE TITLE
Panic error with google_sql_database_instance's timeouts option.

### ISSUE THREAD

**Issue by polc** [terraform-providers/terraform-provider-google#1335]
### Terraform Version
Terraform v0.11.7                                                                                                                                                                             
+ provider.google v1.9.0                                                                                                                                                                      
+ provider.kubernetes v1.1.0                                                                                                                                                                  
+ provider.random v1.2.0                                                                                                                                                                      

### Affected Resource(s)
- google_sql_database_instance

### Terraform Configuration Files
```hcl
resource "google_sql_database_instance" "master" {
  name   = "${random_id.instance.keepers.name}-${random_id.instance.hex}"
  database_version = "POSTGRES_9_6"
  region = "${var.region}"

  settings {
    tier = "db-f1-micro"
  }

  timeouts {
    create = 20
  }
}
```
### Panic Output
https://gist.github.com/polc/46cdd70693e9e54cee46b41473229abf

### References
I tried the new `timeouts` option (https://github.com/terraform-providers/terraform-provider-google/pull/1288).

### Important note
it's working if I put a string instead of a int in `timeouts.create`.

**Comment by genevieve** [comment]
I think you should write
```
  timeouts {
    create = "20m"
  }
```

**Comment by polc** [comment]
OK thanks!
