### ISSUE TITLE
Empty binding members for google_project_iam_policy result in continually changing plan

### ISSUE THREAD

**Issue by chrisboulton** [terraform-providers/terraform-provider-google#1338]
### Terraform Version

Terraform v0.11.7
+ provider.google v1.9.0

### Affected Resource(s)

- google_project_iam_policy

### Terraform Configuration Files
```hcl
variable "id" {
  default = "XXXXX"
}

variable "owners" {
  default = ["user:user@example.com"]
}

variable "viewers" {
  default = []
}

data "google_iam_policy" "policy" {
  binding {
    role    = "roles/owner"
    members = ["${var.owners}"]
  }

  binding {
    role    = "roles/viewer"
    members = ["${var.viewers}"]
  }
}

resource "google_project_iam_policy" "project" {
  project     = "${var.id}"
  policy_data = "${data.google_iam_policy.policy.policy_data}"
  authoritative = true
}
```

This is actually all encapsulated within a generic module I have for managing GCP projects with Terraform. Sometimes I don't necessarily have any one that might be considered a viewer, so the member list might be empty. It'd be nice to be able to have behaviour exist where if the list of members is empty, the Terraform provider didn't even attempt to add it to to the payload.

(I'm not aware of any other way I could workaround this where the binding wouldn't be generated if the members list was empty, apart from generating my policies outside the module, specific to each project, and then passing them in - which I'd like to try avoid)

### Terraform Output

(Should provide enough valuable information as a debug log would provide)

```
  ~ google_project_iam_policy.project
      policy_data: "{\"bindings\":[{\"members\":[\"user:user@example.com\"],\"role\":\"roles/owner\"}]}" => "{\"bindings\":[{\"role\":\"roles/viewer\"},{\"members\":[\"user:user@example.com\"],\"role\":\"roles/owner\"}]}"
```

### Expected Behavior

No resources should have changed.

### Actual Behavior

The Terraform GCP provider is generating an empty binding without any members for `roles/viewer`, as can be seen in the output above. This means that on each plan/apply, the difference of what's returned from the GCP API and what's submitted do not match up, because GCP is obviously not storing the binding with no members.

### Steps to Reproduce

1. Take Terraform code above, substitute in own variables
2. Run `terraform apply` to apply
3. Run `terraform plan` and observe differences reported

**Comment by ndmckinley** [comment]
Interesting! Thanks for the report, let's see what we can do.

**Comment by ndmckinley** [comment]
Aha, I see what's happened here.  You're seeing a permanent diff because the state you're requesting _cannot_ be the state retrieved by `terraform refresh`, and your suggestion is that we avoid reporting diffs of this kind.  I wonder if that's possible - I'll take a look.

**Comment by chrisboulton** [comment]
Yup - purely because the list of members is empty. I'm suggesting that in this case, we don't attempt to generate that binding in the resulting policy.
