### ISSUE TITLE
Add VPC flow logs support for google_compute_subnetwork

### ISSUE THREAD

**Issue by ellipticasec** [terraform-providers/terraform-provider-google#1364]
Hi,

I would like to get VPC flow logs support in subnet (currently in beta).

### Terraform Version
```
Terraform v0.11.7
+ provider.google v1.10.0
```
### Affected Resource(s)
- google_compute_subnetwork

**Comment by paddycarver** [comment]
I just opened a PR to support this: #1385

**Comment by danawillow** [comment]
Merged in https://github.com/terraform-providers/terraform-provider-google/pull/1385
