### ISSUE TITLE
Support disabling Basic Auth on google_container_cluster

### ISSUE THREAD

**Issue by ellipticasec** [terraform-providers/terraform-provider-google#1367]
Hi,

### Terraform Version
```
Terraform v0.11.7
+ provider.google v1.10.0
```

### Affected Resource(s)
- google_container_cluster

### Expected Behavior
When using `gcloud` or Console, I can disable Basic Auth and Client Cert auth when creating my cluster. I always want to use `gcloud container cluster get-credentials` when doing `kubectl`, so those are useless.  Also, this means that my `tfstate` contains sensitive key material.

### Actual Behavior
Support disabling `master_auth`

**Comment by plasticine** [comment]
@ellipticasec You can disable `master_auth` by setting both `username` & `password` to an empty string.

```
master_auth = {
    username = ""
    password = ""
}
```

**Comment by ellipticasec** [comment]
Thanks @plasticine that worked.

Now I will close and re-open to support not issuing Client Key / Cert.
