### ISSUE TITLE
Project IAM Bindings with automatically created service accounts

### ISSUE THREAD

**Issue by mattdodge** [terraform-providers/terraform-provider-google#1369]
**Terraform Version**: 0.11.3
**Google Provider Version**: 1.6

**Affected Resource(s)**
- `gcp_project_iam_binding`
- `google_service_account`

I am wondering if there is a way to use the `gcp_project_iam_binding` resources when your project has service accounts that use those roles that were automatically created by GCP. I am trying to manage all of my IAM roles/resources with terraform. However, because of the fact that `gcp_project_iam_binding` is authoritative for an entire role, I cannot figure out how to use that when automatically created service accounts also have that role.

For example, if I want to define two users to be editors I would expect to do something like this:
```hcl
resource "google_project_iam_binding" "editors" {
  project = "my-project"
  role    = "roles/editor"
  members = [
    "user:email1@domain.com",
    "user:email2@domain.com"
  ]
}
```

I can apply that and it works ok the first time. However, the next time I go to run an apply the plan comes up with changes since there are other service accounts that have the role of `roles/editor`. Specifically, the plan will show this:
```
  ~ module.iam.google_project_iam_binding.editors
      members.#:              "3" => "2"
      members.#####:          "user:email1@domain.com" => "user:email1@domain.com"
      members.#####:          "user:email2@domain.com" => "user:email2@domain.com"
      members.#####:          "serviceAccount:service-#####@containerregistry.iam.gserviceaccount.com" => ""
```

I would even be ok setting up service account resources and including them (although that's a bit annoying since they get auto created by GCP services) but because the domain of the service account emails is custom I can't do that either.

Is there any way to do this or am I stuck using the non-authoritative `google_project_iam_member` resource?

**Comment by morgante** [comment]
The service account's email is based on the project ID, so it should be straightforward to compute. For example:

```
locals {
  project_number = "${google_project.my_project.number}"
  project_id     = "${google_project.my_project.project_id}"
}

resource "google_project_iam_binding" "editors" {
  project = "${local.project_id}"
  role    = "roles/editor"

  members = [
    "serviceAccount:${format("service-%s@containerregistry.iam.gserviceaccount.com", local.project_number)}",
    "serviceAccount:${format("%s@cloudservices.gserviceaccount.com", local.project_number)}",
  ]
}
```

**Comment by mattdodge** [comment]
Ah that's true. I was thinking of using the actual `google_service_account` terraform resource, where you can't change the service account domain name. But I suppose I could just put them in the members list directly too, duh. Is this the recommended way to do this?

**Comment by morgante** [comment]
Yes, that's definitely my recommendation. It wouldn't make sense to put these in as a Terraform resource anyways - you don't actually control those service accounts, so if you wanted to (for example) delete them you wouldn't be able to.

**Comment by mattdodge** [comment]
Ok great, I think that will work as a solution for me. Going to go ahead and close this but if there are other ideas feel free to leave them here. Thanks a lot @morgante!
