### ISSUE TITLE
google_sql_database_instance removal making tfstate mismatched

### ISSUE THREAD

**Issue by bmwcmw** [terraform-providers/terraform-provider-google#1370]
Hi,

The scenario happens when we want to renaming old_instance and old_user to new_instance and new_user.

### Terraform Version
```
Terraform v0.11.6
+ provider.google v1.9.0
```

### Affected Resource(s)
- google_sql_database_instance
- google_sql_user

### Terraform Configuration Files
```hcl

resource "google_sql_database_instance" "new_instance" {
  name             = "new_instance"
  provider         = "google"
  region           = "${var.region_eu}"
  database_version = "MYSQL_5_7"

  settings {
    tier = "db-n1-standard-1"

    disk_autoresize = true

    backup_configuration {
      enabled    = true
      start_time = "02:00"
    }

    ip_configuration {
      authorized_networks = {
      }
    }

    database_flags = {
      name  = "max_allowed_packet"
      value = 8000000
    }
  }
}

resource "google_sql_user" "new_user" {
  name     = "root"
  password = "123456"
  instance = "${google_sql_database_instance.new_instance.name}"
  host     = "%"
}
```

### Debug Output
First terraform apply
```
...
google_sql_database_instance.new_instance: Creation complete after 3m47s (ID: new_instance)

Error: Error applying plan:

1 error(s) occurred:

* google_sql_user.users (destroy): 1 error(s) occurred:

* google_sql_user.users: Error, failed to deleteuser root in instance old_instance: googleapi: Error 403: Operation failed because another operation was already in progress., operationInProgress

```
then for the second terraform apply or terraform plan :
```
Error: Error refreshing state: 1 error(s) occurred:

* google_sql_user.users: 1 error(s) occurred:

* google_sql_user.users: google_sql_user.old_user: Error reading SQL User "root" in instance "old_instance": googleapi: Error 409: The instance or operation is not in an appropriate state to handle the request., invalidState
```

### Expected Behavior
When terraform removes an sql instance, it should systematically remove the associated users and update tfstate correctly.

### Actual Behavior
When terraform removed the old_instance, it'll not find old_user anymore and returns the first error, but it doesn't remove old_user from tfstate. 

Then if we launch apply or plan again, we'll always see the second error.

Old_user associated to old_instance is still in tfstate. We have to remove it manually.
```
"google_sql_user.old_user": {
"type": "google_sql_user",
"depends_on": [
"google_sql_database_instance.old_instance"
],
...
"meta": {
"schema_version": "1"
},
"tainted": false
},
"deposed": [],
"provider": "provider.google"
}
```

### Steps to Reproduce
1. `terraform apply`
2. `terraform apply` or `terraform plan`

### Important Factoids
Running with cloud mysql v2

**Comment by paddycarver** [comment]
Sorry for the issue! Looking at what you're describing, it _looks_ like Terraform is trying to remove the user, but can't because an operation is already in progress (I'm not 100% on what that is, but my guess would be deleting the instance?). So the delete fails, so Terraform _assumes_ the user still exists. That is borne out by the second error you're seeing, which is saying that we can't read a list of the users.

It feels like a lot of the debugging for this issue is going to depend on the exact order things are actually happening in. Would it be possible for you to turn [debugging on](https://www.terraform.io/docs/internals/debugging.html) and put the log in here? (Just make sure to sanitize it!)

**Comment by bmwcmw** [comment]
Hi paddycarver,

Thanks for your reply.

Yesterday I've upgraded terraform to 0.11.7 + google cloud provider 1.10.0. Then by replaying the same operations in another gcloud project, I only having sometimes Error 403 operationInProgress.

I haven't found related lines in last release note but it seems the issue has been fixed somehow. I'll close the ticket now and come back when it occurs again.
