### ISSUE TITLE
google_container_cluster taint triggers new instance

### ISSUE THREAD

**Issue by hprotzek** [terraform-providers/terraform-provider-google#1371]
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- google_container_cluster

### Terraform Configuration Files
```hcl
resource "google_container_cluster" "cluster" {
  name = "${var.cluster_name}"
  network = "${data.terraform_remote_state.networking.network_name}"
  subnetwork = "${data.terraform_remote_state.networking.k8s_subnetwork_name}"
  min_master_version = "${var.min_master_version}"

  node_pool {
    name = "default-pool"
    node_count = 3

    autoscaling {
      min_node_count = 3
      max_node_count = 6
    }

    node_config {
      image_type = "UBUNTU"
      disk_size_gb = "100"
      machine_type = "n1-standard-2"

      oauth_scopes = [
        "https://www.googleapis.com/auth/compute",
        "https://www.googleapis.com/auth/devstorage.read_only",
        "https://www.googleapis.com/auth/logging.write",
        "https://www.googleapis.com/auth/monitoring",
      ]

      tags = [
        "${var.k8s_node_tag}",
        "default-pool"]
    }
  }

  node_pool {
    name = "worker-pool"
    node_count = 2

    autoscaling {
      min_node_count = 2
      max_node_count = 10
    }

    node_config {
      image_type = "UBUNTU"
      disk_size_gb = "100"
      machine_type = "n1-standard-8"

      oauth_scopes = [
        "https://www.googleapis.com/auth/compute",
        "https://www.googleapis.com/auth/devstorage.read_only",
        "https://www.googleapis.com/auth/logging.write",
        "https://www.googleapis.com/auth/monitoring",
      ]

      tags = [
        "${var.k8s_node_tag}",
        "worker-pool"]

      taint {
        key = "dedicated"
        value = "worker"
        effect = "PREFER_NO_SCHEDULE"
      }

      preemptible = true
    }
  }

  master_auth {
    username = "${var.k8s_user}"
    password = "${random_string.k8s_pass.result}"
  }

  maintenance_policy {
    daily_maintenance_window {
      start_time = "03:00"
    }
  }

  provisioner "local-exec" {
    command = <<EOT
      gcloud container clusters get-credentials ${var.cluster_name} --zone ${google_container_cluster.halfpipe.zone}
      kubectl create serviceaccount tiller --namespace kube-system
      kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
      helm init --service-account tiller --wait
EOT
  }
}
```
### Expected Behavior
Updating existing GKE cluster without modifying anything, shouldn't trigger a destroy. 

### Actual Behavior
Seems the taint config block wasn't stored during creation and now triggers a destroy.
```
node_pool.1.node_config.0.taint.#:                          "0" => "1" (forces new resource)
node_pool.1.node_config.0.taint.0.effect:                   "" => "PREFER_NO_SCHEDULE" (forces new resource)
node_pool.1.node_config.0.taint.0.key:                      "" => "dedicated" (forces new resource)
node_pool.1.node_config.0.taint.0.value:                    "" => "worker" (forces new resource)
```

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

**Comment by paddycarver** [comment]
What change do you make that triggers the update? Or is this the change, in which case, what config did you start with? Any help you can provide so we can get a reproduction would be greatly appreciated.

**Comment by hprotzek** [comment]
I didn't change anything, the first `terraform apply` creates the cluster and the second `terraform apply` reports the changes and forces a destroy.

**Comment by hprotzek** [comment]
Found the problem. If the `node_config` is wrapped in a `node_pool` then `taint` got ignored. If `node_config` is used directly in the `google_container_cluster` resource , then the taint settings are working.

**Comment by danawillow** [comment]
Hey @hprotzek, I'm giving this a try but I can't reproduce it with your example. What version of the google provider are you using? Would you mind posting debug logs (run `TF_LOG=DEBUG terraform apply` and put the output into a gist)?

**Comment by etikouirt** [comment]
Same thing with `image_type` for example. If you change it after the first `terraform apply` you get a deletion/creation from the `terraform plan`. This feature is designed on GCP side since you're able to do It on the web UI.

![screenshot from 2018-06-25 18-33-55](https://user-images.githubusercontent.com/14345524/41863333-b3d5e708-78a6-11e8-9ea5-db446ea76f26.png)

The call seems to be done with a POST to `https://console.cloud.google.com/m/operations?organizationId=<orgId>&operationType=cloud-console.container.updateCluster&pid=<envName>` with  **desiredNodePoolImageType** set to "COS" in the params.

Should I open an other issue ?

**Comment by danawillow** [comment]
Yes please!

**Comment by danawillow** [comment]
@hprotzek, are you still seeing this issue? If so, have you been able to get debug logs?

**Comment by hprotzek** [comment]
@danawillow Seems to be fixed with version:
Terraform v0.11.7
+ provider.google v1.16.2

Thanks :-)
