### ISSUE TITLE
[google_pubsub_subscription] Requires push_config that API defines as optional

### ISSUE THREAD

**Issue by icflournoy** [terraform-providers/terraform-provider-google#1389]
I'm writing TF plans to cover some existing infrastructure and have run into an issue where the `google_pubsub_subscription` resource requires a push config. The Google API indicates this is optional.

https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions#resource-subscription
> An empty pushConfig signifies that the subscriber will pull and ack messages using API methods.

### Terraform Version
```
Terraform v0.11.7
+ provider.google v1.10.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Affected Resource(s)
- google_pubsub_subscription

### Terraform Configuration Files
```hcl
resource "google_pubsub_subscription" "test-subscription" {
    name = "test-subscription"

    ack_deadline_seconds = "600"
}
```

### Gcloud output from existing resource
```
$ gcloud pubsub subscriptions list
---
ackDeadlineSeconds: 600
messageRetentionDuration: 604800s
name: projects/test-project/subscriptions/test-subscription
pushConfig: {}
topic: projects/test-project/topics/test-topic
```

### Expected Behavior
I expect to create a resource without specifying a pushConfig

### Actual Behavior
```
$ terraform plan

Error: google_pubsub_subscription.test-subscription: "topic": required field is not set
```

### Steps to Reproduce
1. Create a PubSub topic
2. Use a `google_pubsub_subscription` resource to try to subscribe to the topic (without a `push_config` block)

**Comment by emilymye** [comment]
That log looks like it says "topic" is missing from the subscription resource - you probably need to add `topic = "projects/test-project/topics/test-topic" ` (or some interpolate-y equivalent) to your subscription.

**Comment by icflournoy** [comment]
Ah, yup when I was sanitizing the Terraform code to post here I removed that part and didn't catch that the error changed.

I was trying to initialize an empty push_config block like
```hcl
push_config {}
```
which is why Terraform was throwing a required error.

In reading the docs closed I see that push_config is optional, but the parameters within are required, which makes sense why I was seeing the error with the empty push_config.
