### ISSUE TITLE
host parameter needed in cloud_sql_user resource whereas documented as optional 

### ISSUE THREAD

**Issue by egouraud-claranet** [terraform-providers/terraform-provider-google#1394]
Hi there,

### Terraform Version
0.10.8
terraform google provider version : 1.6.0

### Affected Resource(s)
google_sql_user

### configuration example
```
resource "google_sql_database_instance" "myinstance" {
  name    = "myinstance"
  project = "myproject"
  region  = "europe-west1"
  database_version = "POSTGRES_9_6"
  }
}

resource "google_sql_user" "myuser" {
  name = "myuser"
  instance = "myinstance"
  project = "myproject"
  password = "mypassword"
}
```
### Expected Behavior
creation of a google_sql_user resource  with a 2nd generation instance

### Actual Behavior
`Error: google_sql_user.myuser: "host": required field is not set`

### Steps to Reproduce
just declare a google_sql_user without the host parameter

### Important Factoids
The documentation says that for second generation cloud sql servers host is not needed (Optional) 

### References
https://www.terraform.io/docs/providers/google/r/sql_user.html#host

**Comment by emilymye** [comment]
Hi @egouraud-claranet, is this your full config? It seems like the required `settings` value is missing from `google_sql_database_instance`. Can you tell what tier your database_instance is using? i.e. "DO" 

Otherwise, I'll probably need the debug logs (run with export TF_LOG=DEBUG) on the apply to figure out what's wrong, since host is optional in the user schema.

**Comment by egouraud-claranet** [comment]
hi @emilymye , 
sorry for the incomplete configuration, i just focused on the user resource, and put a partial instance configuration to show that i use a 2nd generation instance (db-f1-micro to answer to your question)

the fail appears at the terraform plan

cheers,
Emmanuel

**Comment by egouraud-claranet** [comment]
ok @emilymye , 
i got it
the parameter was required on 1.6.0 version of google provider, it is optional since 1.7.0

sorry for the noise
