### ISSUE TITLE
Add support to attach an ssl_policy to target_https_proxy

### ISSUE THREAD

**Issue by mumblez** [terraform-providers/terraform-provider-google#1399]
### Terraform Version
Terraform v0.11.7
+ provider.google v1.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_ssl_policy
- google_compute_target_https_proxy

### Expected Behavior
No option listed @ https://www.terraform.io/docs/providers/google/r/compute_target_https_proxy.html to attach the ssl_policy

Maybe it's yet to be implemented?
I tried `ssl_policy` and `ssl_policies` but terraform complains invalid field

### Steps to Reproduce
1. Create an ssl_policy
2. Try attaching to target_https_proxy

**Comment by paddycarver** [comment]
The [docs](https://cloud.google.com/compute/docs/load-balancing/ssl-policies) for the feature. It [looks](https://cloudplatform.googleblog.com/2018/02/announcing-SSL-policies-for-HTTPS-and-SSL-proxy-load-balancers.html) like it was introduced in late February.

At the moment, we don't seem to have support for this, but I see no reason we couldn't add it.

**Comment by rosbo** [comment]
I will be adding this feature in the next couple of days. The https proxy resource will be autogenerated and will support this field.

**Comment by rosbo** [comment]
This feature will be available in the next release. Thank you
