### ISSUE TITLE
Support for passing schema text file to schema param in 'google_bigquery_table' resource 

### ISSUE THREAD

**Issue by kpr6** [terraform-providers/terraform-provider-google#140]
Hi there,
### Terraform Version
Terraform v0.9.8
### Affected Resource(s)
- google_bigquery_table

### Terraform Configuration Files
```hcl
resource "google_bigquery_table" "default" {
  dataset_id = "${google_bigquery_dataset.default.dataset_id}"
  table_id   = "${var.tableName}"
  time_partitioning {
    type = "DAY"
  }
  labels {
    env = "default"
  }
  schema = "${file("CUSTOMER_CDW_schema.json")}"
}

```

### Expected Behavior
Accepting schema.txt file for table schema creation

### Actual Behavior
google_bigquery_table.default: "schema" contains an invalid JSON: invalid character 'D' looking for beginning of value

**Comment by danawillow** [comment]
Hey @kpr6, your issue report still has a lot of the template defaults, and it's hard to tell what you've typed vs what is part of the template. Would you mind explaining your issue a bit further? A sample terraform config would be great.

**Comment by kpr6** [comment]
I've updated the post.
To extend further, resource "google_bigquery_table" accepts schema file in "json" format only while creating a table. So, I was asking whether it would be possible for it to accept schema file in ".txt" format as well @danawillow

**Comment by danawillow** [comment]
Is "txt" a standard format? We need something we can consistently parse in order to fill in the schema part of the Bigquery API (see https://cloud.google.com/bigquery/docs/reference/rest/v2/tables). The extension of the file doesn't matter, but we already have functions for parsing json (marshal and unmarshal)- I don't know of any other formats that have similar functions that are already written.

**Comment by ndmckinley** [comment]
Closing this issue due to lack of response - if you would still like this done, please let us know what format you're wanting to have added!  An example snippet would be handy, too.  We'd be happy to take a look.  :)
