### ISSUE TITLE
Importing Load-Balancer Resources Fails When Service Account from A Different Project

### ISSUE THREAD

**Issue by loffelmacher** [terraform-providers/terraform-provider-google#1400]
## Terraform Version
```
$ terraform -v
Terraform v0.11.7
```

## Affected Resources
- `google_compute_url_map`
- `google_compute_target_http_proxy`
- `google_compute_target_https_proxy`
- `google_compute_backend_bucket`
- `google_compute_backend_service`
- `google_compute_global_forwarding_rule`
- `google_compute_global_address`

## Expected Behavior
While using `terraform import` I should be able to use a service-account from 
any GCP project to authenticate, so long as it has sufficient org-level permissions. 

## Actual Behavior
The `import` functionality, at least when used with load-balancer components, 
required me to create a new service account in the same GCP project. 

I have project rsl-foo with any of the resources listed above, and I have 
a second project rsl-bar, where I created a service account. I gave the rsl-bar 
broad org-level rights. It works for creating anything in GCP, but fails to 
import things.

## Steps to Reproduce
Create two projects, the service account, and some load-balancer components in 
Google Cloud to `terraform import`. Then run an import like: `terraform import google_compute_url_map.rsl_um rsl-um`.

**Comment by paddycarver** [comment]
This issue was raised following a discussion on the GCP slack, and my conclusion was the same.

**Comment by rileykarson** [comment]
Many of these resources properly support import cross-project now; if anyone encounters any issues though, please file bugs for the specific resource!
