### ISSUE TITLE
<Feature Request> Logging exclusions resource

### ISSUE THREAD

**Issue by PepperTeasdale** [terraform-providers/terraform-provider-google#1404]
Hello!

Just curious if adding something like a `google_logging_exclusion` resource was on the roadmap for this project. This would be very helpful to have codified and easily applicable to every environment. Currently, this would look like writing an ad hoc script using their API, [as described here](https://cloud.google.com/logging/docs/exclusions). Keeping it with our terraform code would be awesome, especially with the upcoming consumption-based pricing for the stackdriver service.

Thanks!

**Comment by paddycarver** [comment]
It looks like #990 is open as a PR to add that.

**Comment by PepperTeasdale** [comment]
Oh excellent! Thanks for referencing. Watching that PR now :)
