### ISSUE TITLE
GCP Netblock Data Source

### ISSUE THREAD

**Issue by jacobleonw** [terraform-providers/terraform-provider-google#1416]
Hi,

It would be good if there was an IP range data source in the Google provider like [Cloudflare's](https://www.terraform.io/docs/providers/cloudflare/d/ip_ranges.html)

**Comment by rosbo** [comment]
Would this data source meet your needs?
https://www.terraform.io/docs/providers/google/d/datasource_compute_lb_ip_ranges.html

**Comment by jacobleonw** [comment]
According to [the link on that page](https://cloud.google.com/compute/docs/load-balancing/health-checks#health_check_source_ips_and_firewall_rules), this only covers 
* 209.85.152.0/22
* 209.85.204.0/22
* 35.191.0.0/16

I'm ultimately trying to lockdown SSH access to an instance from Google Cloud Shell, and according to what I've read on the internet, it can use any IP from `_cloud-netblocks.googleusercontent.com`.

I understand the security implications of opening up SSH to the GCP netblock, but I still think it would be a good feature to have instead of having to manually gather the source IPs.

For now, I will look at using a workaround of dynamically updating firewall rules via `gcloud` cli

**Comment by morgante** [comment]
@rosbo Do you think this is a good idea? I know it would be useful for some other customers, even in cases where they're configuring other clouds via Terraform as well (in a multi-cloud environment).
