### ISSUE TITLE
Allow setting folder_id on google_project to ""

### ISSUE THREAD

**Issue by morgante** [terraform-providers/terraform-provider-google#1419]
### Terraform Version
```
Terraform v0.11.7
+ provider.external v1.0.0
+ provider.google (unversioned)
+ provider.http v1.0.1
```

### Affected Resource(s)
- google_project

### Terraform Configuration Files
```hcl
locals {
  organization_id = "816421441114"
  folder_id       = ""
}
resource "google_project" "test_project" {
  name       = "My Project"
  project_id = "gcp-fnd-test-project-folder"
  org_id     = "${local.organization_id}"
  folder_id  = "${local.folder_id}"
}


```

### Expected Behavior
Setting folder_id to "" should have the same behavior as leaving it off entirely.

### Actual Behavior
The only way to successfully execute this is to leave folder_id off entirely (and create at org level) or leave off org_id (and create at folder level). This has to be hard-coded in the HCL, making variable creation impossible.

The key code is here: https://github.com/terraform-providers/terraform-provider-google/blob/42b07b30e618d3ceabdd6d36f8a13656f137f528/google/resource_google_project.go#L53-L64

### Important Factoids
This is critical to being able to dynamically only set the folder ID based on variables or parameters.

**Comment by sethvargo** [comment]
This is happening because of the use of `conflicts_with` in the schema, which is doing validation on the presence of keys instead of presence of keys _with_values_. If we move that validation into the resource-level, this becomes possible at the expense of more code to maintain.

**Comment by rosbo** [comment]
I opened an issue against Terraform core a few months ago about this.

The answer I got was that HCL2 will introduce a proper concept of `unset` and `null`. 

For more details, here is the issue I opened:
https://github.com/hashicorp/terraform/issues/16575

Given that we would lose plan-time validation, I suggest we wait until HCL2.

What do you think?

**Comment by morgante** [comment]
I'm not convinced that we benefit much from plan-time validation, to be honest. In fact, I would suggest we don't need it at all and could instead switch on a single value (whether folder_id is set or not). I think if folder_id is specified, the desired behavior (being in that folder) is clear, even if org_id is also specified.

**Comment by sethvargo** [comment]
I tend to agree with @morgante that the trade-off leans toward giving customers power of extensibility in the short term

**Comment by rosbo** [comment]
Alright, you convinced me. I will open a PR soon to fix this.
