### ISSUE TITLE
Google provider v1.11.0 introduces 32-bit integer conversion overflow

### ISSUE THREAD

**Issue by derwei** [terraform-providers/terraform-provider-google#1426]
We ran into a problem using the 32-bit binary of Terraform and google provider v1.11.0

```
plugin.terraform-provider-google_v1.11.0_x4: panic: Error reading level state: strconv.ParseInt: parsing "1369852711444692407": value out of range
```

We have worked around this by using the 64-bit binary of Terraform.

### Terraform Version
Terraform v0.11.7
+ provider.google v1.11.0
+ provider.tls v1.1.0

### Affected Resource(s)
- google_compute_target_http_proxy
- google_compute_target_https_proxy

### Panic Output
https://gist.github.com/derwei/157d9c7beb81298a41e70af5c1d699fe

### Expected Behavior
terraform actions should have succeeded

### Actual Behavior
terraform apply, destroy, refresh will crash.

### Steps to Reproduce
Use a 32-bit terraform client to perform actions on a google_compute_target_http_proxy.

**Comment by rosbo** [comment]
Thanks for reporting. I have a PR out to fix this and we will do a release quickly once it is in. Stay tuned!

**Comment by rosbo** [comment]
1.12 has been released and include a fix for this bug. Sorry for the trouble.
