### ISSUE TITLE
Add support to configure lien on project

### ISSUE THREAD

**Issue by cbeckhashicorp** [terraform-providers/terraform-provider-google#1435]
GCP has added the ability to protect projects from accidental deletion using liens. Request support be added to provider for configuration of liens with Terraform.

https://cloud.google.com/resource-manager/docs/project-liens

**Comment by ndmckinley** [comment]
This is obviously a good idea.  :)  In progress.

**Comment by paddycarver** [comment]
I believe this has shipped. I'm going to close the issue out, but if it's still a problem, feel free to comment and we can reopen.
