### ISSUE TITLE
google_compute_address assumes EXTERNAL address_type for imported resources.

### ISSUE THREAD

**Issue by alfred-tio-ck** [terraform-providers/terraform-provider-google#1438]
### Executive Summary

According to the docs at https://www.terraform.io/docs/providers/google/r/compute_address.html, all fields except name are optional.

However, when importing an existing internal static IP reservation, the EXTERNAL address_type is assumed and enforced upon subsequent terraform executions, despite being an optional field.

### Terraform Version
Terraform v0.11.7
+ provider.google v1.10.0
+ provider.template v1.0.0

### Affected Resource(s)
- google_compute_address

### Debug Output
https://gist.github.com/alfred-tio-ck/046f15383b5adc24cf19bcda840d5d59

### Expected Behavior
Based on the docs, the desired result should be no change to the above imported resource.

### Actual Behavior
In the above debug output, terraform assumes and attempts to convert the imported internal IP reservation into an external IP reservation. 

### Steps to Reproduce
1. Create an internal IP address reservation via gcloud. For example:

```gcloud compute addresses create test-internal-address --addresses 10.137.41.2 --project test-project --region us-central1 --subnet projects/shared-vpc-host-project/regions/us-central1/subnetworks/us-central1-10-137-40-0-22```

2. Define the resource in a .tf file, for example:

```
resource "google_compute_address" "test_internal_address" {
  name         = "test-internal-address"
}
```

3. Import the resource, for example:

```terraform import google_compute_address.test_internal_address projects/test-project/regions/us-central1/addresses/test-internal-address```

4. Perform terraform plan and/or apply. Output pasted on the gist above.

**Comment by rosbo** [comment]
Hi @alfred-tio-ck,

The default value for `address_type` is `EXTERNAL`.

You must update your resource in the .tf file to match this:
```hcl
resource "google_compute_address" "test_internal_address" {
  name         = "test-internal-address"
  address_type = "INTERNAL"
}
```

Let me know if you are still having troubled after doing this change and I will reopen the issue.

Thank you
