### ISSUE TITLE
google_compute_backend_service only supports ONE health check

### ISSUE THREAD

**Issue by jwgoh** [terraform-providers/terraform-provider-google#144]
### Terraform Version
v0.9.6

### Affected Resource(s)
- google_compute_backend_service

Argument reference `health_checks` is a bit misleading because only on health check is supported

Also the document mentions the below:

> health_checks - (Required) Specifies a list of HTTP health check objects for checking the health of the backend service.

EDIT: I can open a PR to update the doc

**Comment by stack72** [comment]
Closed via #145
