### ISSUE TITLE
google_compute_backend_service \ list group into backend

### ISSUE THREAD

**Issue by caminale** [terraform-providers/terraform-provider-google#1457]
Hi there,
I tried to insert a list of backends that serve my BackendService and I want to automated all my terraform with inputs.  
If I change the number of group-instance, I have to change my code to add this one into my backend-service.
this one works but it's not automatic :

  ``` tf
   backend {
    group = "${google_compute_instance_group.cockroach_crew.0.self_link}"
  }
  backend {
    group = "${google_compute_instance_group.cockroach_crew.1.self_link}"
  }
  backend {
    group = "${google_compute_instance_group.cockroach_crew.2.self_link}"
  }
```

So I want to automize it and I tried to make template_file to shape my backends list:
I have list of backends in this shape : 
```json
{
  group="https://www.googleapis.com/compute/v1/projects/cockroach-gce/zones/europe-west2-a/instanceGroups/terraform-cockroach-crew1"
},{
  group="https://www.googleapis.com/compute/v1/projects/cockroach-gce/zones/europe-west3-a/instanceGroups/terraform-cockroach-crew2"
},{
  group="https://www.googleapis.com/compute/v1/projects/cockroach-gce/zones/europe-west1-b/instanceGroups/terraform-cockroach-crew3"
}
```
and when I insert it, into my backend-service like this : 
```tf
  backend = ["${data.template_file.service_json.rendered}"]
```
I have an error : 
```
*module.instance-cockroach.google_compute_backend_service.cockroach-service: backend.0: expected object, got string
```
I spent time to solve this issue to find another method but I didn't succeed.
If someone have already done this, please tell how you succeed !! :)

**Comment by ndmckinley** [comment]
It looks like you've tried to provide a string representation of your json as an entry in the backend list.  This won't work - terraform doesn't parse strings into HCL in the way that would be required for this to work.  You need a solution that automatically adds
```
backend {
  group = "${google_compute_instance_group.cockroach_crew.NUMBER.self_link}"
}
```

Where `NUMBER` takes on every value from `0 - ${google_compute_instance_group.cockroach_crew.count}`.  I'm not sure HCL can represent this.  If you really need to automate it, you could try using the JSON syntax for your whole file.

https://www.terraform.io/docs/configuration/syntax.html#json-syntax

**Comment by ndmckinley** [comment]
Sounds great!  Please comment again if you have any trouble - happy to try and help.  I'm going to close this now, since we prefer not to have open-ended issues like this stay open indefinitely, but happy to help if that doesn't work for you.
