### ISSUE TITLE
`plan` thinks that persistent disk can be made smaller

### ISSUE THREAD

**Issue by borekb** [terraform-providers/terraform-provider-google#1458]
### Terraform Version

```
$ terraform -v
Terraform v0.11.7
+ provider.google v1.10.0
```

### Affected Resource(s)

- google_compute_disk

### Description

I tried making a persistent disk size smaller:

```
resource "google_compute_disk" "backup_server_data" {
  name = "backup-server-data"
  type = "pd-ssd"
  size = "${var.backup_server_data_disk_size}"    # 35 -> 30
}
```

Google Cloud doesn't support that ([docs](https://cloud.google.com/compute/docs/disks/add-persistent-disk): "You can only resize a persistent disk to increase its size. You cannot reduce the size of a persistent disk.") but `terraform plan` was happy with the change:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ google_compute_disk.backup_server_data
      size: "35" => "30"


Plan: 0 to add, 1 to change, 0 to destroy.
```

`apply` failed as expected:

```
$ terraform apply
google_compute_disk.backup_server_data: Modifying... (ID: backup-server-data)
  size: "35" => "30"

Error: Error applying plan:

1 error(s) occurred:

* google_compute_disk.backup_server_data: 1 error(s) occurred:

* google_compute_disk.backup_server_data: Error resizing disk: googleapi: Error 400: Invalid value for field 'sizeGb': '30'. New disk size '30' must be larger than existing size '35'., invalid
```

Is it technically possible for a TF provider to be smart about the actual values and in this case, probably throw an error at the `plan` time already?

(Note: this situation probably doesn't have a good solution as throwing away a persistent disk and creating a new one is probably not what the user wants, unless data migration is planned carefully.)

**Comment by rosbo** [comment]
This is similar to the `ip_cidr_range` for subnetwork. You can expand the range but not shrink it. To support this, we used the `CustomizeDiff` function:
https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_subnetwork.go#L127

**Comment by ndmckinley** [comment]
Ah, cool, that's an easy one, then.  :)
