### ISSUE TITLE
Could `region` be optional for `google_sql_database_instance`?

### ISSUE THREAD

**Issue by borekb** [terraform-providers/terraform-provider-google#1459]
### Terraform Version

```
$ terraform -v
Terraform v0.11.7
+ provider.google v1.10.0
```

### Affected Resource(s)

- google_sql_database_instance

### Description

For all of my resources, `region` is inferred from a provider section which looks like this:

```
provider "google" {
  project = "${var.project_id}"
  region  = "europe-west1"
  zone    = "europe-west1-b"
}
```

So for example, I can do this:

```
resource "google_compute_address" "my_address" {
  name   = "my-address"
}
```

instead of:

```
resource "google_compute_address" "my_address" {
  name   = "my-address"
  region = "europe-west1"
}
```

One major exception seems to `google_sql_database_instance` which requires `region` and I'm wondering why. Is it because of the legacy first-generation instance regions that did not necessarily match GCE regions? Does this still apply to second generation that I am using?

Thanks.

**Comment by ndmckinley** [comment]
Interesting point.  Investigating!  Thanks for the report.

**Comment by ndmckinley** [comment]
After some quick investigation, that's almost definitely why.  I don't mind changing it, as long as there's a big call-out in the docs that says that this is a pitfall.  I'm also not changing `region` from "Required" to "Optional", because almost everyone should set `region` in their config.

**Comment by borekb** [comment]
Sounds great, thanks for such a quick response!
