### ISSUE TITLE
No support for Automated Windows Password generation

### ISSUE THREAD

**Issue by discentem** [terraform-providers/terraform-provider-google#1472]
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance

terraform-google-provider does not have support for https://cloud.google.com/compute/docs/instances/windows/automate-pw-generation as far as I can tell. Having the equivalent of https://github.com/terraform-providers/terraform-provider-aws/pull/2219 for this provider would be great for automated provisioning workflows.

Here is an full, working example of automate-pw-generation in golang: https://github.com/GoogleCloudPlatform/compute-image-windows/pull/139/files. it would just need to be modified/integrated into this provider.

**Comment by discentem** [comment]
This example could be helpful as reference for integrating support for this feature https://github.com/GoogleCloudPlatform/compute-image-windows/pull/139/files

**Comment by morgante** [comment]
I'm not sure if this should be its own resource.

Instead, I think with the addition of #1578 you'd be able to do this all within your Terraform config.

**Comment by discentem** [comment]
Thanks for the comment @morgante. I was assuming it could be part of the compute_instance provider, but I definitely could be wrong. 

Am I able to generate these bits just with already existing terraform functions? https://github.com/GoogleCloudPlatform/compute-image-windows/blob/master/examples/windows_auth_go_sample.go#L59-L71

**Comment by KbLev** [comment]
Any updates on this?

@morgante do you have a sample code on how to do this?

**Comment by morgante** [comment]
@KbLev Unfortunately I don't think it's currently possible because #1578 is still open.

**Comment by haf-afa** [comment]
@morgante What about the suggestion of @discentem - using the PKI infra to extract the password rather than "screen scraping" the password from the output of the serial port?

**Comment by haf** [comment]
Do we have some sample code to do this available now that #1578 is closed @morgante ?

**Comment by morgante** [comment]
I don't have the Terraform code, but you should be able to do the equivalent of https://github.com/GoogleCloudPlatform/compute-image-windows/pull/139/files using the new data source.
