### ISSUE TITLE
Support Custom Machine types in google_container_node_pool

### ISSUE THREAD

**Issue by drubin** [terraform-providers/terraform-provider-google#1473]
I am trying to move away from manually configuring my node_pools in the GUI/CLI and I would like to manage them but currently, I make use of custom machine types in my node pools so this makes it hard.

### Terraform Version
Terraform v0.11.5
+ provider.google v1.12.0
+ provider.random v1.2.0

### Affected Resource(s)
- google_container_node_pool

### Terraform Configuration Files
```hcl
# no config
```

### Debug Output
na

### Panic Output
na

### Expected Behavior
I should be allowed to specify custom machine types in node_config

### Actual Behavior
There doesn't seem to be a param so I am limited to the built-in machine types.

### Steps to Reproduce
na

### Important Factoids
na
### References
- https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type 
- https://www.terraform.io/docs/providers/google/r/container_cluster.html#node_config 

I hope this is the correct way to report this? Since it isn't really a bug I am not sure what other debugging info I could include.

**Comment by emilymye** [comment]
I strongly suspect that using "machine_type=custom-NUMBER_OF_CPUS-AMOUNT_OF_MEMORY" in your config will work (see formats for API examples from https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type#creating_the_instance for example). I will have to get back to you after I test this, but feel free to try this :)

**Comment by drubin** [comment]
@emilymye Ah I see now what you mean. That is hidden away in the API section of the google docs. I wonder if it would make more sense to highlight this in the terraform docs?

As someone that has used the CLI and the console it isn't exactly transparent that `gcloud compute instances create example-instance --custom-cpu 4 --custom-memory 5` maps to this magic value. `machine_type=custom-NUMBER_OF_CPUS-AMOUNT_OF_MEMORY`

I will give it a try in the morning, but I think you are right this should just work.

**Comment by drubin** [comment]
Thank you @emilymye
