### ISSUE TITLE
Cloud IoT Core: Support multiple Pub/Sub topics

### ISSUE THREAD

**Issue by sdouche** [terraform-providers/terraform-provider-google#1493]
According to the [documentation](https://cloud.google.com/iot/docs/how-tos/devices), A Cloud IoT Core device registry supports multiple Pub/Sub topics:

> If you select only one Cloud Pub/Sub topic, all device telemetry (the event data sent from devices to 
> the cloud) will be published to that topic. You can specify multiple topics in order to publish separate 
> streams of data from a device. Each topic maps to a subfolder specified in either the MQTT topic path 
> or the HTTP request when the data is published.

### Terraform Version
```
$ terraform version
Terraform v0.11.7
+ provider.google v1.12.0
```
### Affected Resource(s)
- google_cloudiot_registry

### Expected Behavior
Be able to use multiple topics for a device registry.

**Comment by reapp3r** [comment]
This means supporting event_notification_config as an array of entries, and each entry can have not just the "pubsub_topic_name" value but also the "subfolder_matches" value, as per the [API](https://cloud.google.com/iot/docs/reference/cloudiot/rest/v1/projects.locations.registries#EventNotificationConfig)

**Comment by danawillow** [comment]
Some context for whoever ends up getting to this: Migrating the field to become an array would be a breaking change, and thus can only happen in a major release. However, just adding the ability to have multiple topics (but not with subfolder_matches) can be done in a non-breaking fashion. For whatever reason, this field was implemented as a map, so we'd want to update the code to ignore the keys entirely and treat it as an array of values. It would lead to some weirdish configs, but it at least would enable the feature to be added without breaking existing users.

**Comment by hobochild** [comment]
@danawillow What about adding a new field `telemetry_notification_config` with the proposed changes and deprecating `event_notification_config` in the next major release?

**Comment by danawillow** [comment]
Perhaps! I'm not thinking super hard about this particular issue right now, but I'll add it to our 3.0.0 milestone so we don't forget about it when we start thinking about breaking changes for that.

**Comment by rileykarson** [comment]
Done in https://github.com/GoogleCloudPlatform/magic-modules/pull/2390 + another PR
