### ISSUE TITLE
Clout IoT: ability to add devices

### ISSUE THREAD

**Issue by sdouche** [terraform-providers/terraform-provider-google#1495]
The module can create registries but not handle devices.

### Terraform Version
```
$ terraform version
Terraform v0.11.7
+ provider.google v1.12.0
```

### Affected Resource(s)
google_cloudiot_registry

### Expected Behavior
Be able to create devices with these arguments:

- id
- device communication
- public key format (rs, es, rs_x509, es_x509)
- public key expiration
- device metadata

**Comment by sdouche** [comment]
Hi @emilymye. You right, it is this API. I stupidly copy/paste the name of fields on the screen, communication is the `Blocked` field in the API.

**Comment by sungchun12** [comment]
Are there any updates to this enhancement?

**Comment by ferrarimarco** [comment]
Now that https://github.com/GoogleCloudPlatform/magic-modules/pull/3357 is merged, I can start having a look at this.

**Comment by ferrarimarco** [comment]
FYI: the work to support this resource is here: https://github.com/GoogleCloudPlatform/magic-modules/pull/3637
