### ISSUE TITLE
Error message for long project name is unclear

### ISSUE THREAD

**Issue by morgante** [terraform-providers/terraform-provider-google#1498]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- google_project

### Terraform Configuration Files
```hcl
resource "google_project" "long_project" {
  name       = "long-project-id-is-longer-than-it-should-be"
  project_id = "long-project-id-is-longer-than-it-should-be"
  org_id     = "${var.organization_id}"
}
```

### Expected Behavior
I get some sort of error that explains my project ID is too long, ideally before the API request is even made.

### Actual Behavior
When I run apply, I get this unhelpful error:
```
* google_project.long_project: Error creating project long-project-id-is-longer-than-it-should-be (long-project-id-is-longer-than-it-should-be): googleapi: Error 400: Request contains an invalid argument., badRequest.
```

**Comment by danawillow** [comment]
Fixed in #1519
