### ISSUE TITLE
Label support for topics and subscriptions

### ISSUE THREAD

**Issue by shinzui** [terraform-providers/terraform-provider-google#1500]
Is it possible to add label support to pubsub [topics](https://www.terraform.io/docs/providers/google/r/pubsub_topic.html) and [subscriptions](https://www.terraform.io/docs/providers/google/r/pubsub_subscription.html)?

**Comment by rolandkool** [comment]
+1

**Comment by rosbo** [comment]
The Pub/Sub Topics and Subscriptions API don't have support for labels:
https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/create
https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.topics#Topic

There is no options to set them in the UI either. 

Feel free to reopen if I am mistaken.

Thank you

**Comment by rosbo** [comment]
It looks like these labels are a no-op.

```sh
gcloud beta pubsub topics create test-label --labels=foo=bar # No errors at creation, it seems like it is working
gcloud beta pubsub topics describe MY_NEW_TOPIC # No signs of the labels
gcloud beta pubsub topics list --filter="labels.foo:*" # Listed 0 items.
```

I will look at the gcloud code and report back.

**Comment by rolandkool** [comment]
Hi @rosbo , any news on this topic?

**Comment by rosbo** [comment]
@danawillow did the pubsub team get back to you about their plans for each of these versions?

**Comment by danawillow** [comment]
Yeah, there's context on the bug you filed :)

Basically, we should wait until they're in v1.

**Comment by Starefossen** [comment]
Sooo.. labels are now supported in v1 right? https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.topics
