### ISSUE TITLE
Custom route advertisement feature for Cloud routers

### ISSUE THREAD

**Issue by davispolly** [terraform-providers/terraform-provider-google#1501]
Currently, cloud routers support custom route advertisements(https://cloud.google.com/router/docs/how-to/advertising-overview) and this feature is not yet supported by the google_compute_router resource. It would be great if this supported as I have few customers who are actively using it.

**Comment by AndreyK-git** [comment]
+1

**Comment by glassrye** [comment]
I would also like this feature

**Comment by danawillow** [comment]
Fixed in #1723
