### ISSUE TITLE
rolling_update_policy in regional_group_manager's seems buggy

### ISSUE THREAD

**Issue by apenney** [terraform-providers/terraform-provider-google#1506]
### Terraform Version
Terraform v0.11.7
+ provider.google v1.12.0

### Affected Resource(s)
- google_compute_region_instance_group_manager

I tried enabling rolling_update_policy in two different modules.  Both didn't work for different reasons.

#### Bastion

Our bastion module makes a single instance.  I added:

```
  update_strategy    = "ROLLING_UPDATE"

  rolling_update_policy {
    type                  = "PROACTIVE"
    minimal_action        = "REPLACE"
    max_surge_fixed       = 1
    max_unavailable_fixed = 0
    min_ready_sec         = 30
  }
```

When I checked via the console I saw the settings were:

```
Update mode
Proactive
Maximum surge
0 instances (fixed)
Maximum unavailable
3 instances (fixed)
Minimum wait time
0 seconds
```

Which is obviously completely different.  Despite this every terraform run seemed not to change it or want to change it.

#### Vault Cluster

My vault cluster makes 3 nodes, and I used:

```
  rolling_update_policy {
    type                  = "PROACTIVE"
    minimal_action        = "REPLACE"
    max_surge_fixed       = "${length(data.google_compute_zones.available.names)}"
    max_unavailable_fixed = 0
    min_ready_sec         = 30
  }
```

In this case it simply remained in as:

```
Update mode
Opportunistic
```

I tried a variety of settings, changing surge/unavailable, tweaking min_ready_sec, etc, but I could never get it to actually do anything and it certainly wasn't replacing instances.  I'm not really sure how to debug further or what I could do to get you useful information, but I'm willing to be guided into the right direction!

**Comment by emilymye** [comment]
Hi @apenney! It would be very helpful if you could run with env variable `TF_LOG=DEBUG` and give us  the debug logs output for some example configs where you are changing/adding rolling update. If you can give us the debug logs and the configs you are using, we can probably help more.

**Comment by danawillow** [comment]
Actually, I think this is WAI. @apenney, when you were running the update, were you also changing the instance template?

**Comment by apenney** [comment]
I was, I was definitely updating the image it was deploying as well!

**Comment by danawillow** [comment]
Hm, ok then. When you get the chance, feel free to send over the config and debug logs (and plan output, just to be safe) and I'll take another look :)

**Comment by bpineau** [comment]
[plan.txt](https://github.com/terraform-providers/terraform-provider-google/files/2173766/plan.txt)
[main.tf.txt](https://github.com/terraform-providers/terraform-provider-google/files/2173769/main.tf.txt)

I see the same issue.
Attached my plan and tf code (not sure how to privately provide the whole debug logs ?)

The debug logs reveal the following warning :
`Update policy type was set to OPPORTUNISTIC. Please use regionInstanceGroupManager.update() to preserve the policy.`

Before the update shown in the attached plan (replacing the AMI -> the instance template), my instanceGrouManager is as such:
```
$ gcloud beta --project mycompany-myapp-staging compute instance-groups  managed \
       describe --region europe-west3  myapp
...
targetSize: 3
updatePolicy:
  maxSurge:
    calculated: 3
    fixed: 3
  maxUnavailable:
    calculated: 0
    fixed: 0
  minReadySec: 60
  minimalAction: REPLACE
  type: PROACTIVE
versions:
- instanceTemplate: https://www.googleapis.com/compute/beta/projects/mycompany-myapp-staging/global/instanceTemplates/myapp-server-20180708121229080500000001
  targetSize:
    calculated: 3
```

The relevant debug logs section showing the `PROACTIVE` type being ignored for `OPPORTUNISTIC`:
```
[DEBUG]: ---[ REQUEST ]---------------------------------------
[DEBUG]: POST /compute/beta/projects/mycompany-myapp-staging/regions/europe-west3/instanceGroupManagers/myapp-server/setInstanceTemplate?alt=json HTTP/1.1
....
[DEBUG]: ---[ RESPONSE ]--------------------------------------
...
[DEBUG]: {
[DEBUG]:  "kind": "compute#operation",
[DEBUG]:  "id": "5523112436329067114",
[DEBUG]:  "name": "operation-1531055237182-5707c938b3230-0c84f6f0-de2a6549",
[DEBUG]:  "operationType": "compute.instanceGroupManagers.setInstanceTemplate",
[DEBUG]:  "targetLink": "https://www.googleapis.com/compute/beta/projects/mycompany-myapp-staging/regions/europe-west3/instanceGroupManagers/myapp-server",
[DEBUG]:  "targetId": "7672965652139827113",
[DEBUG]:  "status": "PENDING",
[DEBUG]:  "user": "someone@mycompany.com",
[DEBUG]:  "progress": 0,
[DEBUG]:  "insertTime": "2018-07-08T06:07:17.652-07:00",
[DEBUG]:  "warnings": [
[DEBUG]:   {
[DEBUG]:    "code": "FIELD_VALUE_OVERRIDEN",
[DEBUG]:    "message": "Update policy type was set to OPPORTUNISTIC. Please use regionInstanceGroupManager.update() to preserve the policy."
[DEBUG]:   }
...
[DEBUG]: ---[ REQUEST ]---------------------------------------
[DEBUG]: PATCH /compute/beta/projects/mycompany-myapp-staging/regions/europe-west3/instanceGroupManagers/myapp-server?alt=json HTTP/1.1
....
```

Could be that we're using the [PATCH API](https://cloud.google.com/compute/docs/reference/rest/beta/instanceGroupManagers/patch)
while we would be expected to use PUT to trigger an [instanceGroupManagers.update](https://cloud.google.com/compute/docs/reference/rest/beta/instanceGroupManagers/update) ?

**Comment by bpineau** [comment]
Yes I confirm the following modification triggers the update as expected:
```
diff --git a/google/resource_compute_instance_group_manager.go b/google/resource_compute_instance_group_manager.go
index c06840e..68021cb 100644
--- a/google/resource_compute_instance_group_manager.go
+++ b/google/resource_compute_instance_group_manager.go
@@ -499,7 +499,7 @@ func performUpdate(config *Config, id string, updateStrategy string, rollingUpda
                        Versions:     versions,
                }

-               op, err := config.clientComputeBeta.InstanceGroupManagers.Patch(project, zone, id, manager).Do()
+               op, err := config.clientComputeBeta.InstanceGroupManagers.Update(project, zone, id, manager).Do()
                if err != nil {
                        return fmt.Errorf("Error updating managed group instances: %s", err)
                }
```

I'll follow up with a pull request (this time, keeping the Patch() call before Update(), to respect the "force overwrite rolling-update policy like gcloud and GCP UI does").

**Comment by paddycarver** [comment]
So something weird is going on; #1742 should have fixed this, but when it's applied, reading the instance group no longer returns any information about the update strategy. Which could be a problem with our code, or could be a weird backend thing I'll have to go through an issue with Google to get resolved. Either way, we can't release #1742 until we get it resolved, unfortunately. :(

I'll keep working on this, and hopefully we can get a #1742-equivalent fix in soon.

**Comment by chasebolt** [comment]
First off, thanks for maintaining this provider! It is super helpful :heart: 

I am running into this issue as well where `google_compute_region_instance_group_manager` isn't respecting the `update_strategy` and `rolling_update_policy` attributes. Is there anything else that would be helpful to provide for this issue?

**Comment by paddycarver** [comment]
Hi @chasebolt, thanks for the friendly nudge, this had slipped off my radar.

I've opened #1969 to fix this for `compute_instance_group_manager`. We'll need to make similar changes to `compute_region_instance_group_manager`, but I had to do some shady black magic to make this work, so I want to wait and see where we land on that one before I duplicate the approach in the regional resource.

Sorry for the delay on this. Hopefully we can get it patched up soon.

**Comment by chasebolt** [comment]
Not a problem at all - I appreciate the ping back. I'll follow that PR that looks like you already have some work going on.

Thanks!

**Comment by paddycarver** [comment]
Just a heads up, there's an open proposal about this in #1971. I'll update with even more information this week.

**Comment by SpencerSharkey** [comment]
Is there any further update on this? This behavior remains broken in the latest 1.19.1, or is the current recommendation to use beta if this functionality is required?

**Comment by paddycarver** [comment]
1.19.0 introduced a split in this:

* update_strategy can be set to NONE, ROLLING_UPDATE, REPLACE, or RESTART. REPLACE and RESTART are aliases, and RESTART is deprecated. ROLLING_UPDATE is also deprecated. So honestly, use NONE or REPLACE. NONE does nothing. REPLACE goes through each instance in the group and tells the IGM to replace it, one at a time. This is also entirely deprecated in google-beta.
* update_policy can be used in the google-beta provider. This uses the `versions` field to deploy multiple instance templates and roll an update between them. This is the future behaviour, and the behaviour (I believe) GCP recommends using, but it is worth noting it is still in beta. I believe it'll make its way to GA eventually, at which point we'll probably deprecate update_strategy and recommend everyone use update_policy, but I don't know when that point will actually be.

I can't recommend anything specifically for your infrastructure, because I don't know what you need or what your beta risk tolerance is. If you can stomach the risk of a beta API, I think the beta provider's update_policy and version combination is a more intuitive and better solution, and is likely to be the main/only solution when it comes to GA. If you can't stomach the risk of a beta API, update_strategy = REPLACE is a reasonably close approximation of the behaviour for the most common case (I want to slowly roll out a new template without taking my entire instance group offline). update_strategy = NONE is basically for "please don't touch it, just change the instance template associated with the group and do nothing else, I'll take care of it myself".

**Comment by paddycarver** [comment]
Oops, this is regional. That complicates matters only because I don't think we have an update_policy value of RESTART for regional instance group managers. We probably could, if people needed it, but I'm hesitant to implement it if there's no demand, because it's custom Terraform behaviour and not API-defined behaviour, which always makes me hesitant and squeamish.

**Comment by rileykarson** [comment]
@paddycarver this is resolved in `google-beta` right?

**Comment by paddycarver** [comment]
This should be. If anyone is experiencing issues with (regional) instance group managers, I'd love an issue.
