### ISSUE TITLE
PEM parse asn1 error on terraform apply

### ISSUE THREAD

**Issue by jpza** [terraform-providers/terraform-provider-google#1520]
Hi there,

I have an issue where trying to create a simple cluster is resulting in a PEM error. I've read other issues that say this error indicates that the resource has an incorrect configuration but I have checked the documentation thoroughly and my config seems simple and well-formed. 

### Terraform Version
$ terraform -v                                                                                                                                                                                            [16:09:39]
Terraform v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- google_container_cluster

### Terraform Configuration Files
```hcl
resource "google_container_cluster" "redaced" {
  name               = "redaced-cluster"
  zone               = "us-central1-f"
  initial_node_count = 3
  network            = "faketv-network"
}
```

### Debug Output
https://gist.github.com/jpza/b2632aa218563458bb1941ab0f1c070d

### Expected Behavior
Apply should have worked

### Actual Behavior
I got the error: 
```
* google_container_cluster.redaced: Post https://container.googleapis.com/v1/projects/faketv-dev/zones/us-central1-f/clusters?alt=json: private key should be a PEM or plain PKSC1 or PKCS8; parse error: asn1: syntax error: sequence truncated
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by danawillow** [comment]
Hey @jpza, that sounds like potentially a credentials issue. How did you download your credentials file? Are you able to provision other resources in TF?

**Comment by jpza** [comment]
Credentials are gathered as suggested on the provider docs: "Contents of the JSON file used to describe your account credentials, downloaded from Google Cloud Console."

```
GOOGLE_APPLICATION_CREDENTIALS=/Users/myuser/.tfcreds/tfadmin-dev.json
GOOGLE_PROJECT=faketv-dev
```

/Users/myuser/.tfcreds/tfadmin-dev.json has a valid service-account key

I'm not able to provision anything. I just tested. Everything throws this PEM error

**Comment by jpza** [comment]
Just realized my problem. I was setting the wrong env var. Should have been setting `GOOGLE_CLOUD_KEYFILE_JSON`
