### ISSUE TITLE
`google_sql_user` always wants to recreate (not populating tfstate)

### ISSUE THREAD

**Issue by abevoelker** [terraform-providers/terraform-provider-google#1526]
### Terraform Version
Terraform v0.11.7
+ provider.google v1.12.0
+ provider.random v1.3.1

### Affected Resource(s)
- google_sql_user

### Terraform Configuration Files
```hcl
resource "google_project_service" "sqladmin" {
  project = "${var.project}"
  service = "sqladmin.googleapis.com"
}

resource "random_string" "db_password" {
  length = 16
  special = true
}

resource "google_sql_database_instance" "webapp" {
  depends_on = ["google_project_service.sqladmin"]
  name = "webapp-instance"
  database_version = "POSTGRES_9_6"
  region = "us-central1"

  settings {
    tier = "db-f1-micro"
  }
}

resource "google_sql_user" "cloudsqlproxy" {
  name     = "proxyuser"
  host     = "cloudsqlproxy~%"
  instance = "${google_sql_database_instance.webapp.name}"
  password = "${random_string.db_password.result}"
}
```

### Debug Output
https://gist.github.com/abevoelker/6b650dcd6b639388e6f11b9bf139e370

### Panic Output
N/A

### Expected Behavior
The user should be added to the Cloud SQL database instance, and subsequent `terraform plan` executions should show that nothing remains to be done

### Actual Behavior
The user is added to the Cloud SQL database, however subsequent `terraform plan` executions show that the user needs to be added every time:

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
...
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + google_sql_user.cloudsqlproxy
      id:       <computed>
      host:     "cloudsqlproxy~%"
      instance: "webapp-instance"
      name:     "proxyuser"
      password: <sensitive>
      project:  <computed>


Plan: 1 to add, 0 to change, 0 to destroy.
```

Re-executing the plan works without error ("Apply complete! Resources: 1 added, 0 changed, 0 destroyed." every time), so I guess the Google Cloud API overwrites the user in-place?

I looked inside my `terraform.tfstate` file and grepped for "google_sql_user" however didn't find anything, so it seems to me that tfstate is not being populated correctly with the created user.

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

### Important Factoids
Just in case the `random_string` resource or funky "cloudsqlproxy~%" hostname had something to do with it, I also tried this simpler HCL:

```hcl
resource "google_sql_user" "cloudsqlproxy" {
  name     = "proxyuser"
  host     = "foo"
  instance = "${google_sql_database_instance.webapp.name}"
  password = "password"
}
```

However it made no difference - the issue still persisted.

### References
~~I searched for "google_sql_user" and "tfstate" however no open issues seem relevant. At least I imagine #1184 (google_sql_user IDs not unique) isn't due to tfstate not even getting populated.~~

edit: On second look this may be related to #1057 and #623

**Comment by abevoelker** [comment]
I just added some outputs that reference `google_sql_user.cloudsqlproxy`:

```hcl
output "database_username" {
  sensitive = true
  value     = "${google_sql_user.cloudsqlproxy.name}"
}

output "database_password" {
  sensitive = true
  value     = "${google_sql_user.cloudsqlproxy.password}"
}
```

Which suddenly causes `terraform apply` to error out:

```console
$ terraform apply /tmp/plan
google_sql_user.cloudsqlproxy: Creating...
  host:     "" => "cloudsqlproxy~%"
  instance: "" => "webapp-instance"
  name:     "" => "proxyuser"
  password: "<sensitive>" => "<sensitive>"
  project:  "" => "<computed>"
google_sql_user.cloudsqlproxy: Still creating... (10s elapsed)
google_sql_user.cloudsqlproxy: Creation complete after 13s

Error: Error applying plan:

2 error(s) occurred:

* output.database_password: Resource 'google_sql_user.cloudsqlproxy' does not have attribute 'password' for variable 'google_sql_user.cloudsqlproxy.password'
* output.database_username: Resource 'google_sql_user.cloudsqlproxy' does not have attribute 'name' for variable 'google_sql_user.cloudsqlproxy.name'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

However if I do a `terraform refresh` right after, the outputs do show up, although it seems to ignore the `sensitive` option:

```console
$ terraform refresh
random_string.db_password: Refreshing state... (ID: d8l]AoZr>6$t*ccS)
...

Outputs:

database_password = d8l]AoZr>6$t*ccS
database_username = proxyuser
```

**Comment by danawillow** [comment]
Thanks for providing the debug logs!

So, right now you're creating a postgres db instance and then assigning a user to that instance. Postgres users don't have hosts, so the API is ignoring the host you set for it (ideally it would error instead- I'll ask around and see if I can get that changed). When we try to read back the list of users to match it with the one in your config, we're not seeing a match because the hosts aren't the same (the API is returning an empty host), so Terraform assumes the user has been deleted and removes it from state.

The simple solution for you is to just not set a host. I'll update the docs to make it more clear that hosts aren't a thing in postgres, and see if I can get the Cloud SQL team to give an error message when we try to create a user with one.

**Comment by abevoelker** [comment]
Thanks for that explanation - I should've read the other issue(s) closer (my bad). I was getting hung up on the Cloud SQL Proxy user creation instructions I was using which do seem to specify a hostname, but I must've been looking at the MySQL-specific instructions as the [Postgres-specific page](https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#3_create_the_proxy_user) does say that hostname doesn't matter. Thanks again!
