### ISSUE TITLE
master version "1.10.2-gke.1" is unsupported.

### ISSUE THREAD

**Issue by moxli** [terraform-providers/terraform-provider-google#1539]
### Terraform Version

Terraform v0.11.7
+ provider.google v1.13.0

### Affected Resource(s)
- google_container_cluster

### Terraform Configuration Files
```hcl
provider "google" {
  project = "maximilian-dorner-testing"
  region  = "europe-west3"
}

resource "google_project_services" "services" {
  project = "maximilian-dorner-testing"

  services = [
    "iam.googleapis.com",
    "bigquery-json.googleapis.com",
    "oslogin.googleapis.com",
    "containerregistry.googleapis.com",
    "pubsub.googleapis.com",
    "compute.googleapis.com",
    "servicemanagement.googleapis.com",
    "deploymentmanager.googleapis.com",
    "replicapool.googleapis.com",
    "replicapoolupdater.googleapis.com",
    "resourceviews.googleapis.com",
    "container.googleapis.com",
    "storage-api.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "sql-component.googleapis.com",
    "sqladmin.googleapis.com",
  ]
}

resource "google_container_cluster" "primary" {
  name               = "marcellus-wallace"
  zone               = "europe-west3-a"
  initial_node_count = 1
  min_master_version = "1.10.2-gke.1"

  additional_zones = [
    "us-central1-b",
    "us-central1-c",
  ]

  master_auth {
    username = "mr.yoda"
    password = "supersecretpassworddddd"
  }

  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]

    labels {
      foo = "bar"
    }

    tags = ["foo", "bar"]
  }
}

# The following outputs allow authentication and connectivity to the GKE Cluster.
output "client_certificate" {
  value = "${google_container_cluster.primary.master_auth.0.client_certificate}"
}
output "client_key" {
  value = "${google_container_cluster.primary.master_auth.0.client_key}"
}

output "cluster_ca_certificate" {
  value = "${google_container_cluster.primary.master_auth.0.cluster_ca_certificate}"
}
```

### Debug Output
https://gist.github.com/6110ef5127b1cad9f9fdb143521e5ccd

### Panic Output
n/a

### Expected Behavior
Terraform creates a new GKE cluster with the master version 1.10.2-gke.1.

### Actual Behavior
The google API says the version is unsupported.

### Steps to Reproduce
terraform init
terraform apply

### Important Factoids
**I have successfully created multiple clusters with version 1.10.2-gke.1 in last couple days.** Today it stopped working in my dev enviroment so I recreated it using the template from terraform.io and it the error message still shows up.
If I use the version 1.9.7-gke.1 it works.

The used version is the latest GKE release available: https://cloud.google.com/kubernetes-engine/release-notes

### References
n/a

**Comment by rgardam** [comment]
Hi. 
I was also hitting this silly bug today. It might be that gke has published a new version and not updated their docs

I found that I was able to deploy the `1.10.2` version without the `-gke.1` at the end 

During this time I found that terraform was flip flopping between 1.10.2 and 1.10.2-gke.3

`node_version:                                                            "1.10.2-gke.3" => "1.10.2"`

setting it to  ` 1.10.2-gke.3` seems to have fixed the issue

**Comment by moxli** [comment]
Thanks for you reply! 
I was not aware that Google doesnt update their google cloud docs right away. -> Nothing regarding gke-2 & gke-3

**Comment by kim-liedtke** [comment]
FYI:
in order to find out the supported versions, you can always execute: `gcloud container get-server-config --zone [COMPUTE-ZONE]`
See [https://cloud.google.com/kubernetes-engine/versioning-and-upgrades](https://cloud.google.com/kubernetes-engine/versioning-and-upgrades) for further information.

**Comment by rgardam** [comment]
Yeah, during the time that this issue was an issue the gke version page was out of date.
