### ISSUE TITLE
google_storage_bucket location variable case 

### ISSUE THREAD

**Issue by jwgoh** [terraform-providers/terraform-provider-google#154]
### Terraform Version
v0.9.6

### Affected Resource(s)
Please list the resources as a list, for example:
- `google_storage_bucket`

```
resource "google_storage_bucket" "server-storage" {
  name = "tf-server-bucket"
  location = "asia-southeast1"
  storage_class = "REGIONAL"
}
```

If you specify the location of the `google_storage_bucket` in lowercase, the resource gets provisioned without any error. But if you do `terraform plan` after, Terraform tries to recreate a new resource because location should be in uppercase.

![screen shot 2017-06-22 at 3 20 49 pm](https://user-images.githubusercontent.com/6704206/27421813-8dc7f8fe-575e-11e7-8d89-9bb5baf89601.png)

**Comment by rileykarson** [comment]
Duplicates #115 & fixed in #117. The fix should ship in our next release.
