### ISSUE TITLE
Support Stackdriver-Kubernetes

### ISSUE THREAD

**Issue by kim0** [terraform-providers/terraform-provider-google#1541]
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- google_container_cluster

### Expected Behavior
I am able to create a GKE cluster with the new stackdriver-kubernetes mode monitoring as detailed [here](https://cloud.google.com/monitoring/kubernetes-engine/installing#creating_the_cluster)

### Actual Behavior
I tried to create a new GKE cluster and set `logging_service = "logging.googleapis.com/kubernetes"` but that was not accepted as a valid value

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create new GKE cluster with Terraform
1. Set `logging_service = "logging.googleapis.com/kubernetes"`

**Comment by danawillow** [comment]
Fixed in #1589.
