### ISSUE TITLE
google_compute_forwarding_rule ip_address as link (instead of the IP address) never converges

### ISSUE THREAD

**Issue by chrisboulton** [terraform-providers/terraform-provider-google#1543]
According to the GCP docs, I can supply the link to an IP address when I'm creating an internal forward rule. Terraform lets me do this. This will result in a static IP reservation showing up in the network I create the address in, and shows it linked back to the backend service:

<img width="639" alt="screen shot 2018-05-27 at 2 06 43 am" src="https://user-images.githubusercontent.com/98472/40584273-e77bb724-6152-11e8-8eea-8ff471e6a011.png">

(Normally when you just pass a plain IP address, this association doesn't seem to be created - which to me seems like a bug with the API in general...)

### Terraform Version

```
Terraform v0.11.7
+ provider.google v1.13.0
```

### Affected Resource(s)

- google_compute_forwarding_rule

### Terraform Configuration Files

(Assumes the default network with auto mode networking)

```hcl
resource "google_compute_address" "ip" {
  name         = "test-ip"
  region       = "us-east1"
  address_type = "INTERNAL"
}

data "google_compute_region_instance_group" "group" {
  name   = "instance-group-1"
  region = "us-east1"
}

resource "google_compute_health_check" "hc" {
  name = "hc"

  tcp_health_check {
    port = "80"
  }
}

resource "google_compute_region_backend_service" "svc" {
  name          = "my-backend-service"
  region        = "us-east1"
  health_checks = ["${google_compute_health_check.hc.self_link}"]
  protocol      = "TCP"

  backend {
    group = "${data.google_compute_region_instance_group.group.self_link}"
  }
}

resource "google_compute_forwarding_rule" "fr" {
  name                  = "my-forwarding-rule"
  load_balancing_scheme = "INTERNAL"
  ports                 = ["80"]
  network               = "default"
  region                = "us-east1"
  backend_service       = "${google_compute_region_backend_service.svc.self_link}"
  ip_address            = "${google_compute_address.ip.self_link}"
}

```

### Debug Output

First run applying: https://gist.github.com/chrisboulton/afd6c52fc2e64740eba76231bfb1ffdc#file-first-apply

Second run planning: https://gist.github.com/chrisboulton/afd6c52fc2e64740eba76231bfb1ffdc#file-second-plan

### Expected Behavior

Terraform should be fully converged and should show no changes.

### Actual Behavior

I guess because the GCP API is returning the IP address instead of the link, the comparison here fails and on each apply the forwarding rule will be recreated.

**Comment by Chupaka** [comment]
For now one may use `ip_address            = "${google_compute_address.ip.address}"`.

Works fine for us for a long time already.

**Comment by rosbo** [comment]
Terraform has the ability to suppress a diff for a field, this feature is called `DiffSuppressFunc`. For instance, we suppress a diff between "my-network" and "http://[...]/projects/xxx/global/networks/my-network" for a `network` field. 

However, in that case, we would need to know the ip address associated with the address self_link in order to suppress the diff. `DiffSuppressFunc` cannot make network calls so it is not possible to achieve. The solution to this problem is to use `ip_address = "${google_compute_address.ip.address}"` like @Chupaka mentioned above.

Thank you
