### ISSUE TITLE
Support configuration of Memorystore Redis

### ISSUE THREAD

**Issue by pdecat** [terraform-providers/terraform-provider-google#1547]
#1485 added support for the creation of Memorystore Redis instances but left apart the `redis_configs` block which allows to configure `maxmemory-policy` and `notify-keyspace-events` parameters.

https://cloud.google.com/memorystore/docs/redis/reference/rest/v1beta1/projects.locations.instances#Instance.FIELDS.redis_configs

### Terraform Version

```
# terraform version
Terraform v0.11.7
+ provider.external v1.0.0
+ provider.google v1.13.0
+ provider.template v1.0.0
```

### Affected Resource(s)

- google_redis_instance

### Terraform Configuration Files

```hcl
resource "google_redis_instance" "test" {
  name           = "test"
  memory_size_gb = 1

  # NOT IMPLEMENTED YET
  redis_configs {
    maxmemory_policy = "allkeys-lru"
    notify_keyspace_events = "KEA"
  }
}
```

### Expected Behavior

I'd expect the `redis_configs` block to be supported.

### Actual Behavior

The `redis_configs` block to be supported.

**Comment by king601** [comment]
Oh man, thanks for submitting this issue. I had spent an hour attempting to see if there had been some magical way to do it that hadn't been documented. 

Sidenote: couple other things I tried when trying to create the changes: metadata, redis_configs, redisConfigs, redis_configurations.

Sadly, I have no experience in Go and it looks above me for implementing this right now, so I have to just give my thanks in advance for anyone who picks this up.

**Comment by edevil** [comment]
PR is #1706
