### ISSUE TITLE
stackdriver metric filter based autoscaling

### ISSUE THREAD

**Issue by neilmock** [terraform-providers/terraform-provider-google#1560]
We currently provision our autoscale infra via gcloud CLI but would love to convert this to our existing Terraform stack if possible.  I did not see a way in the docs, so wanted to make sure we weren't missing anything.

gcloud beta compute instance-groups managed set-autoscaling <name> \
 --zone="${ZONE}" --project="${GCLOUD_PROJECT}" \
    --update-stackdriver-metric=pubsub.googleapis.com/subscription/num_undelivered_messages \
    --stackdriver-metric-filter="resource.type = pubsub_subscription AND resource.label.subscription_id = <subscription_id>" \
    --stackdriver-metric-single-instance-assignment=240

Thanks!

**Comment by steadysupply** [comment]
I'd like to cheer for this issue as well.

**Comment by steadysupply** [comment]
Ref: https://github.com/terraform-providers/terraform-provider-google/issues/1044

**Comment by craigwatson** [comment]
+1 from me, this should be considered.

**Comment by paddycarver** [comment]
This looks like it has been implemented on https://www.terraform.io/docs/providers/google/r/compute_autoscaler.html, so I'm going to close it out.
