### ISSUE TITLE
Feature Request: support instance templates in the google_compute_instance provider

### ISSUE THREAD

**Issue by abdelsource** [terraform-providers/terraform-provider-google#1582]
GCP Supports creating instances from instance templates

https://cloud.google.com/compute/docs/instances/create-vm-from-instance-template

It would be nice if Terraform could offer the same support by providing a template name to the google_compute_instance provider.

**Comment by abdelsource** [comment]
Hi Vincent,

That would work but it defeats the purpose of creating a VM from a VM template.

Creating an instance group manager with Terraform and setting the size to 1 creating more overhead, as there will be a need to create a HealthCheck...

Can't we just add the instance_template option to google_compute_instance provider ?

**Comment by rosbo** [comment]
Hi,

If you only need one VM, why not simply using `google_compute_instance`?

> Can't we just add the instance_template option to google_compute_instance provider ?

If we add an instance_template field, there is a few design decisions we need to take. For instance:

* Should the instance be updated if the instance template has been changed?
* Should we support overriding field in `google_compute_instance`?
* and so on.

**Comment by morgante** [comment]
One thing to note is that there is actually an API endpoint for using an instance template: https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert#sourceInstanceTemplate

**Comment by rosbo** [comment]
Good to know. Given that the Cloud API supports it, I am much more inclined to add support for this feature.

Thanks @morgante for the pointer.

**Comment by paddycarver** [comment]
(I'm inclined to add support, too, but would still be really interested in hearing about use cases vs `google_compute_instance`, just so we can understand the impetus here and understand how people are actually using it/what problem it's solving.)

**Comment by abdelsource** [comment]
Hi,

One use case i have is providing a team of people the ability to use a template created by an other team (Ops create and maintain templates that dev teams can re-use to spin up instances without having to care much about the config...)

**Comment by rosbo** [comment]
Thanks for sharing this use case. I can see more clearly the value of adding this feature now.
