### ISSUE TITLE
Feature Request: Support for IP address - Network Tier

### ISSUE THREAD

**Issue by koalalorenzo** [terraform-providers/terraform-provider-google#1583]
### Terraform Version
```
Terraform v0.11.7
+ provider.azurerm v1.6.0
+ provider.cloudflare v1.0.0
+ provider.google v1.12.0
+ provider.null v1.0.0
+ provider.random v1.2.0
```

### Expected Behavior
I would like to be able to create IP addresses via terraform

### Actual Behavior
It seems not possible, I have checked very quickly and it seems that there is no issue about this. (Plz, link it if there is an active discussion about it, that I was not able to find)

**Comment by koalalorenzo** [comment]
Use case: I am *MANUALLY* forced to create IP addresses on the console, and inserting the value manually before deploying any kubernetes clusters. These IP addresses are used automagically by kubernetes services.

**Comment by morgante** [comment]
What do you need which the google_compute_address resource doesn't provide? https://www.terraform.io/docs/providers/google/r/compute_address.html

**Comment by koalalorenzo** [comment]
The tier: standard vs Premium

**Comment by morgante** [comment]
Okay, to clarify that means this the feature request here is to add support for the "networkTier" field to the `compute_address` and `compute_global_address` resources.

**Comment by koalalorenzo** [comment]
Yes, Thank you. Sorry!

**Comment by rosbo** [comment]
Support has been added for `address`, `forwarding_rule`, `instance` and `instance_template` in #1530.

`global_address` and `global_forwarding` are resources generated by [Magic Modules](https://github.com/GoogleCloudPlatform/magic-modules). Magic Modules doesn't support beta resources yet but should real soon.

**Comment by chrisst** [comment]
`network_tier` is currently supported by `compute_address`.

Unfortunately it looks like GCP doesn't support `network_tier` on global addresses right now, see https://cloud.google.com/network-tiers/docs/using-network-service-tiers#creating_forwarding_rules.

Currently the [rest API documentation](https://cloud.google.com/compute/docs/reference/rest/v1/globalAddresses) says it does support it, but I've opened up an internal bug to fix that documentation so it should be updated soon.

Feel free to re-open if there is something else I am missing on the terraform side.
