### ISSUE TITLE
Cloud Composer resource

### ISSUE THREAD

**Issue by davispolly** [terraform-providers/terraform-provider-google#1588]
Cloud composer(https://cloud.google.com/composer/) which is Beta, currently does not have a terraform resource and few customers that I work with are requesting for it, so that they can provision it as IAAC.

**Comment by lawrenae** [comment]
Is anyone taking a crack at this? I'd be interested in helping, and otherwise creating a PR for it. Thoughts?

**Comment by danawillow** [comment]
Hey @lawrenae, at this point we're mostly trying to do new resource types with Magic Modules (https://github.com/GoogleCloudPlatform/magic-modules), that way we don't have to do extra work to add or review something that we know is going to be replaced soon.

If this is a thing you absolutely need right now and it's super important, I'd review a PR for it, but if you can wait a bit, it's on my list of resources to do soon (likely within the next two weeks-ish).

**Comment by lawrenae** [comment]
oh cool -- no worries. Thanks for the update!

**Comment by paddycarver** [comment]
Assigned to modular-magician, as we're going to be generating this one in the near future, and so PRs are probably gently discouraged. If it's important to get it in ASAP and you're happy to open a PR, though, feel free to shout in this issue and we'll see about switching tack.

**Comment by chaitanyaks** [comment]
resource "null_resource" "composer" {
  provisioner "local-exec" {
    command = "gcloud beta composer environments create ${var.env-name}  --location us-east1 --disk-size 20GB   --zone us-east1-b  --machine-type n1-standard-1  --node-count 3 --labels env=beta"
  }
}

**Comment by tdszyman** [comment]
Just noting that Cloud Composer is no longer in Beta -- it's been in GA for a few weeks now. This is definitely something I wish was available in TF

**Comment by michaelsmithhx** [comment]
We also have a Composer + Terraform requirement so +1 for this feature

**Comment by nickithewatt** [comment]
@danawillow @emilymye Is there any update on when this feature may be implemented? If this Magic Modules implementation is some way off, are you open to a PR via the more traditional route? Thanks!

**Comment by emilymye** [comment]
@nickithewatt working on this feature, expect a PR shortly :)

**Comment by nickithewatt** [comment]
Fantastic, thanks @emilymye

**Comment by alan-ma-umg** [comment]
@emilymye thanks so much for getting the PR for composer. Just checking do we have the TF for Composer PR ready?
