### ISSUE TITLE
Configuring google_container_cluster Alias IPs without explicit secondary ranges?

### ISSUE THREAD

**Issue by reidab** [terraform-providers/terraform-provider-google#1597]
Looking at [Google's docs for GKE Alias IPs](https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips#secondary_ranges) it seems there are various levels of control possible for secondary IP ranges:

1. [Creating a cluster with Alias IPs](https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips#create): Enable IP aliases and let GKE manage both the cluster IPs and the secondary IP blocks automatically
2. [Creating a cluster with specific IP ranges](https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips#example_specific_ranges): Set the cluster IP ranges manually and let GKE manage the secondary IP blocks automatically
3. [Creating a cluster with existing secondary ranges](https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips#example_existing_ranges): Explicitly set the named secondary ranges

I'd prefer to let GKE handle all the IP range allocation, but it seems that the Terraform provider currently requires named secondary ranges. Is this necessary?

Specifying an empty block for `ip_allocation_policy` passes the plan phase but fails to apply with:

```
* google_container_cluster.primary: clusters using IP aliases must specify secondary ranges
```

### Terraform Version

Terraform v0.11.7
+ provider.google v1.13.0

### Affected Resource(s)

- google_container_cluster

**Comment by shinzui** [comment]
Is this something that's going to be fixed soon? I need Alias IPs to use memorystore, but I would like to avoid managing a network and subnetwork for my kubernetes pods and services.

**Comment by geekflyer** [comment]
@danawillow @rosbo  @paddycarver @ndmckinley 

Could you please prioritize supporting this feature soon? Alias IP enabled clusters is GA and apparently the recommended way to create GKE clusters these days. It's unfortunate that the terraform provider only supports it halfway. Currently we have to always create clusters via gcloud first and then import them into terraform because of this issue...

**Comment by danawillow** [comment]
Hey all, can I confirm for you that what you want from an API perspective would be to be able to set all the non-deprecated fields listed in https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.IPAllocationPolicy? If we continue to not allow setting `useIpAliases` explicitly, would that be all right or do you need the ability to set that to false at any point?

**Comment by danawillow** [comment]
Yup! Basically, if you set anything in the `ip_allocation_policy` block, `useIpAliases` would be set to true (this is the current behavior).
