### ISSUE TITLE
Specify region in Dataflow job

### ISSUE THREAD

**Issue by svenschwermer** [terraform-providers/terraform-provider-google#1600]
### Terraform Version
Current, see documentation: https://www.terraform.io/docs/providers/google/r/dataflow_job.html

### Affected Resource(s)
- google_dataflow_job

### Expected Behavior
I expect to be able to specify the region.

### Actual Behavior
I cannot specify the region.

### References
https://cloud.google.com/dataflow/docs/concepts/regional-endpoints

**Comment by IslamAzab** [comment]
same here, is there any update about this?

**Comment by paddycarver** [comment]
Not yet! Sorry, we have a limited number of maintainers, and a lot of work to do, so sometime enhancements can take a moment to get to. We do accept PRs, however!

**Comment by migibert** [comment]
Working on it, I expect a PR to be ready on the middle of the next week.
