### ISSUE TITLE
Google TF provider should not attempt decreasing Cloud SQL instance disk size

### ISSUE THREAD

**Issue by czka** [terraform-providers/terraform-provider-google#1612]
```
$ terraform version
Terraform v0.11.7
+ provider.google v1.10.0
```
As of now, TF returns an error that it failed to apply disk size reduction on a Cloud SQL instance. But Google TF provider should not even attempt decreasing Cloud SQL instance disk size, as such operation is not supported by Google.

**Comment by paddycarver** [comment]
For maintainers: I think we can accomplish this with a `CustomizeDiff` function that rejects the plan if it involves the disk size decreasing.

**Comment by ndmckinley** [comment]
That function already exists on `google_compute_disk`'s `size` attribute, too, so that's a good sign.

**Comment by ndmckinley** [comment]
Why don't I just throw that together?  PR soon, unless something goes wrong.
