### ISSUE TITLE
Support updating a dns_managed_zone

### ISSUE THREAD

**Issue by benjamin-maynard** [terraform-providers/terraform-provider-google#1615]
### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.22.0
+ provider.digitalocean v0.1.3
+ provider.dme v0.1.0
+ provider.github v1.1.0
+ provider.google v1.13.0
+ provider.powerdns v0.1.0
```

### Affected Resource(s)
- google_dns_managed_zone

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
**INITIAL:**
```
resource "google_dns_managed_zone" "benmaynard-co-uk" {
  name        = "benmaynard-co-uk"
  dns_name    = "benmaynard.co.uk."
  description = "bnemaynard.co.uk DNS Zone - Managed by Terraform"
}
```
**CHANGED:** (Note description change, correcting spelling error)
```
resource "google_dns_managed_zone" "benmaynard-co-uk" {
  name        = "benmaynard-co-uk"
  dns_name    = "benmaynard.co.uk."
  description = "benmaynard.co.uk DNS Zone - Managed by Terraform"
}
```
### Debug Output
```
-/+ google_dns_managed_zone.benmaynard-co-uk (new resource required)
      id:                                      "benmaynard-co-uk" => <computed> (forces new resource)
      description:                             "bnemaynard.co.uk DNS Zone - Managed by Terraform" => "benmaynard.co.uk DNS Zone - Managed by Terraform" (forces new resource)
      dns_name:                                "benmaynard.co.uk." => "benmaynard.co.uk."
      name:                                    "benmaynard-co-uk" => "benmaynard-co-uk"
      name_servers.#:                          "4" => <computed>
      project:                                 "maynard-networks" => <computed>
```

### Expected Behavior
Terraform updates the Managed Zone description without recreating the resource.

### Actual Behavior
Terraform attempts to recreate the resource.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create Managed Zone with a description
2. Apply Terraform Configuration
3. Change Managed Zone Description
4. Re-apply Terraform

### Important Factoids
N/A

### References
N/A

**Comment by rosbo** [comment]
Hi, 

The v1 API for Cloud DNS doesn't support update. However, the new beta API does.

I updated your issue title slightly to reflect this.

Note to future implementer:
* Use the new patch method in the beta API to update a zone's description: https://cloud.google.com/dns/api/v1beta2/managedZones/patch

**Comment by benjamin-maynard** [comment]
Thanks for the quick response! Look forward to it being implemented.
