### ISSUE TITLE
google_compute_network trying to delete and recreate based on description change

### ISSUE THREAD

**Issue by danielcompton** [terraform-providers/terraform-provider-google#1619]
### Terraform Version
Terraform v0.11.7
GCP Provider version: 1.9.0

### Affected Resource(s)
- google_compute_network

### Terraform Configuration Files

Was:

```hcl
resource "google_compute_network" "default" {
  name                    = "default"
  auto_create_subnetworks = "true"
}
```

Fixed version:

```
resource "google_compute_network" "default" {
  name                    = "default"
  description             = "Default network for the project"
  auto_create_subnetworks = "true"
  routing_mode            = "REGIONAL"
}
```

### Debug Output

N/A

### Description

I went to run `terraform plan` and saw an alarming change suggested: deleting and recreating the `google_compute_network` resource. 

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ google_compute_network.default (new resource required)
      id:                      "default" => <computed> (forces new resource)
      auto_create_subnetworks: "true" => "true"
      description:             "Default network for the project" => "" (forces new resource)
      gateway_ipv4:            "" => <computed>
      name:                    "default" => "default"
      project:                 "myapp" => <computed>
      routing_mode:            "REGIONAL" => "REGIONAL"
      self_link:               "https://www.googleapis.com/compute/v1/projects/myapp/global/networks/default" => <computed>


Plan: 1 to add, 0 to change, 1 to destroy.
```

Eventually I found that if I added a `description` (and possibly `routing_mode`?), the diff went away. I think I was previously on the 1.5.0 GCP provider before running this.

I've fixed the issue now, so I don't have a current reproduction.

**Comment by paddycarver** [comment]
I can't see any changes to that resource between 1.5.0 and 1.9.0... Is it possible that GCP's API changed and either started returning a default description for the the default network if none was set, or changed the description on the default network?

**Comment by danielcompton** [comment]
The only change that I could see affecting this in the time frame since I last ran terraform plan would be https://github.com/terraform-providers/terraform-provider-google/commit/49191c5d910e4238341f69d9b9af6f4de59a0ad2#diff-b67258c305086a2fbba2d2fdd2672769.

**Comment by paddycarver** [comment]
Hmm, yeah, that can't lead to this. I'm going to have to stick with the unsatisfying (sorry!) answer that the upstream API changed its behaviour, which means there's really nothing we can do here. I'm sorry for the unsatisfying resolution, I wish there was something else I could offer. I'm going to close this out, but if anyone can get a reproduction, I'd love to see it, just to confirm that the change came from upstream.
