### ISSUE TITLE
google_sql_database_instance: dynamic authorized_networks

### ISSUE THREAD

**Issue by Chupaka** [terraform-providers/terraform-provider-google#1644]
### Affected Resource(s)
- google_sql_database_instance

### Terraform Configuration Files
We're allowing access to Postgres Cloud SQL instance only from our backend servers. If the number of servers is constant, one may use code like
```hcl
resource "google_sql_database_instance" "postgres" {
  settings {
    ip_configuration {
      authorized_networks = [
        {
          value = "${google_compute_instance.backend.0.network_interface.0.access_config.0.assigned_nat_ip}"
        },
        {
          value = "${google_compute_instance.backend.1.network_interface.0.access_config.0.assigned_nat_ip}"
        },
      ]
    }
  }
}
```

But looks like currently there's no way to create list of maps from dynamic list of strings via interpolation functions. There's a feature request opened in terraform that can manage those situations (https://github.com/hashicorp/terraform/issues/7034), but it's far from finishing.

Can we have some kind of logic in google-provider so that if it sees **authorized_networks {value=list}** it automatically creates necessary list of maps? Then the above task would look like
```hcl
resource "google_sql_database_instance" "postgres" {
  settings {
    ip_configuration {
      authorized_networks {
        value = "${google_compute_instance.backend.*.network_interface.0.access_config.0.assigned_nat_ip}"
      }
    }
  }
}
```

**Comment by danawillow** [comment]
Unfortunately, that just isn't possible at the moment given the way that Terraform internals work. Each schema element has a fixed type, so for `authorized_networks` it's a set, and for `value` it's a string.

Hypothetically we could add a new field that accomplishes what you're asking for, but then we have two fields that mean the same thing and that requires some upkeep.

However, there are some changes coming up in Terraform core 0.12 that will likely make what you're hoping for easier. If it's all right, I'd like to hold off on doing anything about this particular issue until it comes out and then we can re-evaluate. Tagging @paddycarver in case there's anything he'd like to add about it as well :)

**Comment by Chupaka** [comment]
Any details about 0.12 changes so we can evaluate them now?

**Comment by paddycarver** [comment]
Unfortunately, we can't say too much about future Terraform releases, as the details are always subject to change until the release actually happens. :( I believe this exact use case is being kept in mind, however. Unfortunately, I think the best we can do at the moment is reevaluate when 0.12 ships.

**Comment by Chupaka** [comment]
Well, we were able to make it work in current version. Here's the workaround:

```hcl
data "null_data_source" "auth_netw_postgres_allowed_1" {
  count = "${length(google_compute_instance.apps.*.self_link)}"

  inputs = {
    name  = "apps-${count.index + 1}"
    value = "${element(google_compute_instance.apps.*.network_interface.0.access_config.0.assigned_nat_ip, count.index)}"
  }
}

data "null_data_source" "auth_netw_postgres_allowed_2" {
  count = 2

  inputs = {
    name  = "onprem-${count.index + 1}"
    value = "${element(list("192.168.1.2", "192.168.2.3"), count.index)}"
  }
}

resource "google_sql_database_instance" "postgres" {
  settings {
    ip_configuration {
      authorized_networks = [
        "${data.null_data_source.auth_netw_postgres_allowed_1.*.outputs}",
        "${data.null_data_source.auth_netw_postgres_allowed_2.*.outputs}",
      ]
    }
  }
}
```

Is it worth to make an example in **google_sql_database_instance** [documentation](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html)?

**Comment by danawillow** [comment]
Sure! Feel free to send a PR over :)

**Comment by Chupaka** [comment]
Yup, done :) https://github.com/terraform-providers/terraform-provider-google/pull/1741

I believe we can close this issue: this 'workaround' is good working solution for current version of Terraform.

**Comment by Chupaka** [comment]
Bright future is coming: https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each

Closing the issue hoping my pull request will be merged some day :)
