### ISSUE TITLE
Constant modified resource with subnetwork and cluster

### ISSUE THREAD

**Issue by Stono** [terraform-providers/terraform-provider-google#1648]
Hey, 
We have the following subnet block:

```
  resource "google_compute_subnetwork" "vpc_subnet" {
    name          = "${var.prefix}"
    network       = "${var.network}"
    project       = "${var.network_project}"
    region        = "${var.region}"
    ip_cidr_range = "${var.node_cidr_range}"
    private_ip_google_access = true
    secondary_ip_range = {
      range_name = "${var.prefix}-pods"
      ip_cidr_range = "${var.pod_cidr_range}"
    }
    secondary_ip_range = {
      range_name = "${var.prefix}-services"
      ip_cidr_range = "${var.service_cidr_range}"
    }
  }
```

Which is then used in our `google_container_cluster.cluster`:

```
subnetwork = "${google_compute_subnetwork.vpc_subnet.name}"
```

But with **every** terraform run we see this:

```
  ~ module.kubernetes.google_container_cluster.cluster
      subnetwork:         "projects/at-delivery-platform-dev/regions/europe-west4/subnetworks/delivery-platform" => "delivery-platform"
```

So it looks like the state that is being stored for `subnet` on the `container_cluster` is the full path

**Comment by danawillow** [comment]
sigh... another #988 issue. I assume you're using `lifecycle.ignore_changes` on the cluster, right? You might be able to get around that by using `remove_default_node_pool`, and then this problem will go away. (I know it doesn't seem related, but trust me on this one.)

Going to close this one out in favor of that and the other ones that are still open whose numbers I don't have memorized, take a look at the linked issue in hashicorp/terraform for a very detailed explanation of what's going on.

If I'm wrong and you aren't using `lifecycle.ignore_changes`, let me know and I'll reopen this :)

**Comment by Stono** [comment]
Hey @danawillow 

FYI, our cluster has:
```
  lifecycle {
    ignore_changes = ["initial_node_count", "node_config", "addons_config.0.horizontal_pod_autoscaling", "node_version"]
  }
``` 

We also have set `remove_default_node_pool = true`

I worked around this by setting a fqdn style path for the subnetwork on the cluster:

```
subnetwork = "projects/${var.network_project}/regions/${var.region}/subnetworks/${google_compute_subnetwork.vpc_subnet.name}"
```
