### ISSUE TITLE
Unable to set pod_security_policy_config to 0

### ISSUE THREAD

**Issue by Stono** [terraform-providers/terraform-provider-google#1667]
Hey, 
We set pod_security_policy_config to 1 recently, but then decided to put it back to 0, but we now get this in every single plan (the apply works, but seems to never actually be set).

```
  ~ module.kubernetes.google_container_cluster.cluster
      pod_security_policy_config.#: "1" => "0"
```

Any ideas?

**Comment by emilymye** [comment]
This is actually saying that the number of config items read is 1, vs your config, which probably has the pod_security_policy_config block removed. Since the default (i.e. what we read from GKE), 

```
pod_security_policy_config {
  enabled = false
}
```
is not in your config, it's causing a diff. We'll go ahead and suppress that.
