### ISSUE TITLE
Google API Rate Limit Issue

### ISSUE THREAD

**Issue by Stewart-Smith-CK** [terraform-providers/terraform-provider-google#1704]
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
Multiple resources under the google provider.

### Terraform Configuration Files
Directory structure:
base:
   - project1
       - system1
          - main.tf
          - variables.tf
          - terraform-setup.tf
       - system2
          - main.tf
          - variables.tf
          - terraform-setup.tf
   - project2
       - system3
          - main.tf
          - variables.tf
          - terraform-setup.tf
       - system4
          - main.tf
          - variables.tf
          - terraform-setup.tf
   - project3
       - system5
          - main.tf
          - variables.tf
          - terraform-setup.tf
       - system6
          - main.tf
          - variables.tf
          - terraform-setup.tf
       - system7
          - main.tf
          - variables.tf
          - terraform-setup.tf
       - system8
          - main.tf
          - variables.tf
          - terraform-setup.tf
```hcl

```

### Debug Output
```
* google_project_service.cloudbuild_api: googleapi: Error 429: Insufficient tokens for quota 'servicemanagement.googleapis.com/default_requests' and limit 'DefaultRequestsPerMinutePerProject' of service 'servicemanagement.googleapis.com' for consumer 'project_number:1'., rateLimitExceeded
* google_project_service.servicemanagement_api: 1 error(s) occurred:
```

### Panic Output
N/A - Did not produce a crash log

### Expected Behavior
Should have passed through the code without failure, all code deploys individually.

### Actual Behavior
When running a templated "terraform apply" to 45+ different folders all at once we run into an issue with Google's API limiting the requests per second on terraform

### Steps to Reproduce
terraform plan or terraform apply

### Important Factoids
Running terragrunt to group terraform apply's for a top level directory with 45+ sub directories with their own main.tf & variables.tf files inside deploying 45+ different pieces of infrastructure. Roughly deploying 500+ machines in one go.

We found a potential solution to the issue is utilizing Service Usage API instead of Service Management API, however we spent a lot of time investigating this due to the inconsistent errors we got from Terraform itself - adding to the error log to suggest using the other API service would be ideal.

Benefits over using Service Usage vs Service Management:
The rate limiting separates reads (2/second) and writes (.5/second) as opposed to being 2 QPS across both reads and writes.

### References
N/A

**Comment by danawillow** [comment]
Hey @Stewart-Smith-CK, which version of the google provider are you using? We've been using the service usage API since v1.13.0: https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#1130-may-24-2018

**Comment by rileykarson** [comment]
Closing due to age/lack of response. Feel free to reopen the issue or file a new one if this is still a problem!
