### ISSUE TITLE
google_container_cluster: inline node_pool w/autoscaling deploys broken clusters

### ISSUE THREAD

**Issue by rvandegrift** [terraform-providers/terraform-provider-google#1708]
If a `google_container_cluster` only has autoscaling inline `node_pool`s, then the result is a broken cluster.  GCP never deploys any instances: the system pods cannot be launched, which seems to prevent autoscaling from ever launching anything.

I'm surprised Google accepts the config - gcloud always requires that `--min-nodes=1` (or greater).  But terraform doesn't permit the analogous config: `initial_node_count` cannot be specified along with an inline `node_pool`.

### Terraform Version
```
$ terraform -v
Terraform v0.11.7
+ provider.google v1.15.0
```

### Affected Resource(s)
- google_container_cluster

### Terraform Configuration Files
```hclresource "google_container_cluster" "zonal1" {
  name = "zonal1"
  zone = "us-central1-a"

  node_pool {

    autoscaling {
      min_node_count = 1
      max_node_count = 2
    }

    node_config {
      machine_type = "n1-standard-1"
      disk_size_gb = 30
      preemptible = true

      oauth_scopes = [
	"https://www.googleapis.com/auth/compute",
	"https://www.googleapis.com/auth/devstorage.read_only",
	"https://www.googleapis.com/auth/logging.write",
	"https://www.googleapis.com/auth/monitoring",
      ]
    }
  }
}

```

**Comment by brunoban** [comment]
Ran into that as well. A really weird scenario. 😕

**Comment by rileykarson** [comment]
I think this has been fixed on the inline resource regardless, but our recommendation is also to use the separate resource where https://www.terraform.io/docs/providers/google/r/container_node_pool.html#initial_node_count is possible.
