### ISSUE TITLE
google_container_cluster: network_policy_config defaults to disabled

### ISSUE THREAD

**Issue by rvandegrift** [terraform-providers/terraform-provider-google#1709]
The docs at [1] imply that network_policy_config defaults to enabled and can be disabled.  In fact, it's the opposite.

[1] https://www.terraform.io/docs/providers/google/r/container_cluster.html#network_policy_config

### Terraform Version
```
$ terraform -v
Terraform v0.11.7
+ provider.google v1.15.0
```

**Comment by rileykarson** [comment]
Reading over the live docs now, this should be clear as we provide an example of setting disabled to true.

**Comment by rvandegrift** [comment]
Heh, you were tripped up just like I was. :)  By default, network policy is *disabled* but the docs misleadingly imply that it defaults to enabled.

Will open a PR on the docs that show the precise issue.
