### ISSUE TITLE
google_container_node_pool: derive zone/region from provider

### ISSUE THREAD

**Issue by anurag** [terraform-providers/terraform-provider-google#1714]
### Terraform Version
Terraform v0.11.7
+ provider.google v1.15.0

### Affected Resource(s)
- google_container_node_pool

### Expected Behavior
`google_container_node_pool` should behave like `google_container_cluster` when it comes to specifying `region` or `zone`. Terraform creates a regional cluster when the provider has a region without a zone, and a zonal cluster when the provider has both a region and a zone.

For node pools, the docs [here]( https://www.terraform.io/docs/providers/google/r/container_node_pool.html#argument-reference) state:
> Note: You must be provide region for regional clusters and zone for zonal clusters

This seems to be by design, because https://github.com/terraform-providers/terraform-provider-google/blob/master/google/regional_utils.go#L15 is used by the node pool resource to get the location.

This issue prevents reuse of node_pool modules in both regional and zonal clusters.

**Comment by anurag** [comment]
There is a workaround: you can specify both zone and region in the node_pool definition and explicitly set one of them to empty depending on the type of node pool you're setting up.

**Comment by rileykarson** [comment]
Both are retrieved from the provider now.
