### ISSUE TITLE
Terraform does not create the plan based on the dependency tree

### ISSUE THREAD

**Issue by funkydorian** [terraform-providers/terraform-provider-google#1716]
### Terraform Version
Terraform v0.11.7
+ provider.google v1.14.0

### Affected Resource(s)
Please list the resources as a list, for example:
- google_coontainer_cluster
- google_compute_network

### Terraform Configuration Files
```hcl
//Create VPC
resource "google_compute_network" "vpc" {
  name                    = "${var.test-vpc}"
  auto_create_subnetworks = "false"
}

//Create subnet
resource "google_compute_subnetwork" "subnet" {
  name          = "${var.test-subnet}"
  ip_cidr_range = "${var.subnet_cidr}"
  network       = "${var.test-vpc}"
  depends_on    = ["google_compute_network.vpc"]
  region        = "${var.region}"
}

resource "google_container_cluster" "test-k8s" {
  name                = "${var.gke_cluster_name}"
  zone                = "europe-west2-a"
  initial_node_count  = "${var.gke_initial_node_count}"
  node_version        = "${var.gke_node_version}"
  min_master_version  = "${var.gke_min_master_version}"
  depends_on          = ["google_compute_subnetwork.subnet"]
  network             = "${google_compute_network.vpc.name}"
  subnetwork          = "${google_compute_subnetwork.subnet.name}"

additional_zones = [
    "europe-west2-b",
    "europe-west2-c",
]

  node_config {
    machine_type = "${var.gke_machine_type}"
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]

    labels {
      service = "gke"
    }

    tags = ["env", "test"]
  }

}
```

tfvars:
```hcl
#------- Environment -------
env = "temp"

#------- Credentials -------
credentials        = "account.json"
project            = "temp-sr"
region             = "europe-west2"

#----- VPC -----
test-vpc        = "test-vpc-dev"
test-subnet     = "test-subnet-dev"
subnet_cidr        = "10.157.0.0/16"

#------- GKE -------
gke_machine_type        = "n1-highmem-4"
gke_node_version        = "1.9.6-gke.1"
gke_min_master_version  = "1.9.6-gke.1"
gke_initial_node_count  = 1
gke_cluster_name        = "temp-dev"


```
### Debug Output
https://gist.github.com/funkydorian/bae456dd789a8835507d28d1ac989ca4

### Expected Behavior
Terraform should first destroy the GKE and after delete the subnet and recreate all again

### Actual Behavior
The plan does not have GKE even if the dependencies are defined

### Steps to Reproduce
1. `terraform apply`

**Comment by paddycarver** [comment]
What change are you making to prompt a diff when running `terraform apply`?

**Comment by henrylawson** [comment]
I have attempted to replicate your issue and was unable to, using the config that you have provided - making minor adjustments to run in my environment.

For Steps to Reproduce, I did a `apply` then a `destroy`, as I assume you are seeing this error on `destroy`, after the resources are created?

The error you have shared in your gist suggests that there is still a resource attached the subnet while Terraform is trying to destroy it. Is it possible you have another cluster running on the subnet that was not created by this Terraform or is perhaps managed by a separate Terraform project?

If Terraform has created the resource, it should be able to infer dependencies and destroy them in the correct order. You can check that the dependencies are correct by reviewing [`terraform graph`](https://www.terraform.io/docs/commands/graph.html)
