### ISSUE TITLE
Request: Google Site Verification API

### ISSUE THREAD

**Issue by steveh** [terraform-providers/terraform-provider-google#1724]
Similar to [aws_ses_domain_identity_verification](https://www.terraform.io/docs/providers/aws/r/ses_domain_identity_verification.html), it would be wonderful to be able to automatically pull the required information from the Google API to programmatically create DNS records, using the Terraform DNS provider of your choice.

[API documentation](https://developers.google.com/site-verification/)
[Go client library stub](https://github.com/google/google-api-go-client/blob/master/siteverification/v1/siteverification-gen.go)

I don't know enough Go to determine if this is enough to be useful.

Suggested systax:

```hcl
resource "google_site_verification" "example" {
  domain = "example.com"
}

resource "aws_route53_record" "txt_example" {
  zone_id = "${aws_route53_zone.example.zone_id}"
  name    = "${google_site_verification.example.txt_name}" // will be `example.com`
  type    = "TXT"
  ttl     = "600"
  records = ["${google_site_verification.example.txt_record}"] // will be something like `google-site-verification=9fHJM07vph3qSP6RZjg2dqxc98-f5RU58ZNs0Z1FH18`
}

resource "aws_route53_record" "cname_example" {
  zone_id = "${aws_route53_zone.example.zone_id}"
  name    = "${google_site_verification.example.cname_name}" // will be something like `ltwez2m3gppg.example.com`
  type    = "CNAME"
  ttl     = "600"
  records = ["${google_site_verification.example.cname_record}"] // will be something like `gv-anvl25u3um2rva.dv.googlehosted.com`
}
```

**Comment by paddycarver** [comment]
Hi there! Thanks for the feature request. I think this would be a wonderful feature to add, but sadly, don't think in belongs in this specific provider. Looking at the authentication, this isn't _technically_ a Google Cloud API, as far as I can tell, and uses a different auth scheme. So I think this would make a great addition to a provider, but probably falls outside the scope of this provider. I'm going to close this out, but feel free to comment if you have any questions or concerns or think I misunderstood something.
