### ISSUE TITLE
Configuring google_container_cluster without Alias IPs in a shared network

### ISSUE THREAD

**Issue by tmeulensteen** [terraform-providers/terraform-provider-google#1725]
Hi,

When creating a google_container_cluster it seems like setting IP aliasses is mandatory when using a shared network. But creating a container cluster via the console does seems to work without IP aliasses within a shared network.

### Terraform Version
Terraform v0.11.7
+ provider.google v1.15.0

### Affected Resource(s)
Please list the resources as a list, for example:
- google_container_cluster

### Terraform Configuration Files
```hcl
resource "google_container_cluster" "primary" {
  name               = "${var.cluster_name}"
  description        = "example k8s cluster"
  zone               = "${var.gcp_zone}"
  initial_node_count = "${var.initial_node_count}"
  master_auth {
    username = "${var.master_username}"
    password = "${var.master_password}"
  }
  node_config {
    machine_type = "${var.node_machine_type}"
    disk_size_gb = "${var.node_disk_size}"
    preemptible = "${var.node_preemptible}"
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]
  }
}
```

### Expected Behavior
The creation of the desired resource

### Actual Behavior
Error: Error applying plan:

1 error(s) occurred:

* google_container_cluster.primary: 1 error(s) occurred:

* google_container_cluster.primary: googleapi: Error 400: using a shared network is only supported with IP aliases., badRequest

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by danawillow** [comment]
Hey @tmeulensteen, the documentation at https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-shared-vpc specifically says:
> Clusters that use Shared VPC cannot use legacy networks and must have Alias IPs enabled.

The error message you pasted in came from GCP itself (you can tell because it says googleapi), so there isn't really anything we can do on our end. If you'd like the ability to configure clusters using shared vpc without alias ips, I'd recommend filing an issue at http://issuetracker.google.com.

In the meantime though, I'm going to close this issue. If I've misunderstood, please let me know and I'd be happy to reopen :)

**Comment by tmeulensteen** [comment]
Hi @danawillow 

The problem at my end, is that I'm not using a shared VPC but deploy the google_container_cluster  within a 'normal' default VPC. Therefore AliasIP should not be mandatory.

**Comment by danawillow** [comment]
Oh ok, when you said a "shared network" I was reading that as "shared vpc". Can you explain what a shared network is? I'm not familiar with that term.

**Comment by tmeulensteen** [comment]
I've updated my original post to make the issue somewhat clearer. It's creating a google_container_cluster within a VPC (a non shared VPC).

**Comment by danawillow** [comment]
Is the configuration you posted still the correct one? I don't see anything in it referencing a network. If it is, would you mind sharing debug logs? https://www.terraform.io/docs/internals/debugging.html

**Comment by tmeulensteen** [comment]
The configuration is still the correct one. That is the only thing that is in the script at the moment.

**Comment by danawillow** [comment]
Interesting! Were you able to get debug logs?

**Comment by tmeulensteen** [comment]
[terraform.log](https://github.com/terraform-providers/terraform-provider-google/files/2265392/terraform.log)

see the debuglog attached

**Comment by danawillow** [comment]
Thanks! I took a look, and I don't have a great idea what's going on. A few questions though that might help me:
* How do you set the project on the cluster? Are you using a `provider "google"` block or environment variables? 
* Is the service account that's running terraform coming from the same project that you're trying to create the cluster in?

In the meantime, if you explicitly set `network` to the full self link of the one you want, that should make the problem go away.
