### ISSUE TITLE
Plan after apply requests changes due to additional OAuth scopes on existing resources

### ISSUE THREAD

**Issue by mkrull** [terraform-providers/terraform-provider-google#1726]
When explicitly setting the allowed oauth scopes on node pools without also including
- https://www.googleapis.com/auth/monitoring
- https://www.googleapis.com/auth/logging.write

`terraform plan` will require changes because the node pools have the above scopes while the planned ones should not.

### Terraform Version
Terraform v0.11.7
+ provider.google v1.15.0

### Affected Resource(s)
- google_container_node_pool
- google_container_cluster

### Terraform Configuration Files
```hcl
resource "google_container_node_pool" "monkeypool" {
  name       = "monkey-pool"
  zone       = "${var.region}"
  project    = "${var.project}"
  cluster    = "${google_container_cluster.cluster.name}"
  node_count = 3

  node_config = {
    preemptible = true
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/servicecontrol",
      "https://www.googleapis.com/auth/service.management.readonly"
    ]
    machine_type = "n1-standard-1"
  }
}

resource "google_container_cluster" "cluster" {
  name               = "${var.cluster_name}"
  zone               = "${var.region}"
  project            = "${var.project}"
  initial_node_count = 3
  min_master_version = "1.10.4-gke.2"
  node_version       = "1.10.4-gke.2"

  node_config {
      oauth_scopes = [
        "https://www.googleapis.com/auth/compute",
        "https://www.googleapis.com/auth/devstorage.read_only",
        "https://www.googleapis.com/auth/servicecontrol",
        "https://www.googleapis.com/auth/service.management.readonly",
        "https://www.googleapis.com/auth/ndev.clouddns.readwrite"
      ]
      machine_type = "n1-standard-1"
  }
}
```

### Expected Behavior
After apply, plan should not require changes.

### Actual Behavior
The oauth scopes are different. Two additional scopes are present on the machines of the node pools.
- https://www.googleapis.com/auth/monitoring
- https://www.googleapis.com/auth/logging.write

### Steps to Reproduce
Apply any cluster or node pool configuration with an explicit list of oauth scopes without Stackdriver oauth scopes. Run plan after apply.

**Comment by paddycarver** [comment]
It sounds like GKE requires the monitoring and logging.write scopes to be present on node pools, which wouldn't surprise me in the slightest. Are you expecting that Terraform should remove the scopes, or just silently ignore them?

**Comment by mkrull** [comment]
I have no strict opinion on how this should be handled. My first guess would be to silently ignore them but then again I don't know enough about why those are added and if they are even removable to judge that.

**Comment by paddycarver** [comment]
If you happen to have the [debug logs](https://www.terraform.io/docs/internals/debugging.html) available, I can verify, but I'm pretty sure we're _already_ trying to remove them, and the API is either ignoring us or undoing the change behind us. But I can't say for certain without seeing debug logs.

Assuming that is the case, however, I'm not sure silently ignoring the change is an ideal solution here. I think documenting it may be closer to Terraform's spirit of "I will make things match the config you specify" than just ignoring the change. But I'll circle up with the other maintainers and get their opinions on the matter, too.

**Comment by rileykarson** [comment]
The docs appear to have since been updated (https://www.terraform.io/docs/providers/google/r/container_cluster.html#oauth_scopes).
