### ISSUE TITLE
debian-9 should be used instead of debian-8 in tests and docs

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#1729]
debian-8 has reached its [end-of-life](https://www.debian.org/security/2018/dsa-4205). It probably won't break anything if we keep things as-is, but since these are examples that our users might use, we should try to keep them more realistic.

**Comment by paddycarver** [comment]
I've started tackling this, and switching from hardcoded image names to the compute_image data source in our tests, to prevent future breaks when images are deprecated. Just commenting to claim this so we don't duplicate effort.
