### ISSUE TITLE
google_storage_bucket can't create/update tags with merge syntax

### ISSUE THREAD

**Issue by victor5114** [terraform-providers/terraform-provider-google#1743]
### Terraform Version
Terraform v0.11.7
+ provider.google v1.15.0

### Affected Resource(s)
- google_storage_bucket

### Terraform Configuration Files
variables.tf
```hcl
variable "labels" {
  type = "map"
  default = {
    "Customer" = "xxxx"
    "Project_Name" = "xxxx"
    "Creator" = "xxxx"
    "Project_Code" = "xxxx"
    "Billing" = "xxxx"
  }
}
```

storage_bucket.tf
```hcl
locals {
  common_labels {
    "Customer"      = "${var.labels["Customer"]}"
    "Project_Name"  = "${var.labels["Project_Name"]}"
    "Creator"       = "${var.labels["Creator"]}"
    "Project_Code"  = "${var.labels["Project_Code"]}"
    "Billing"       = "${var.labels["Billing"]}"
  }
}

resource "google_storage_bucket" "landing_area_data" {
  name          = "landing_area_data"
  location      = "${var.location}"
  project       = "xxxx"
  storage_class = "REGIONAL"

  labels = "${merge(
    local.common_labels,
    map("name", "landing_area_data")
    )}"

  # labels {
  #   name = "landing_area_data_2"
  # }
}
```

### Debug Output
https://gist.github.com/victor5114/31c51808c0aa0f66cf4f0dbe32ed543c

### Panic Output
None

### Expected Behavior
Create/Update the appropriate labels

### Actual Behavior
Raise a 400 bad request error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
I'd like to reuse local blocks to tag resources with "labels" attribute. It seems to work fine unless I replace ```labels {}``` by the ```labels = {merge()}``` syntax (See Stackoverflow post below)
`terraform plan` gives the correct new labels to create/update but I get an error from the google API.

### References
- https://stackoverflow.com/questions/47973324/how-to-use-locals-in-terraform-to-repeat-and-merge-blocks

**Comment by rileykarson** [comment]
Closing as outdated with Terraform 0.12 changing how functions / lists work considerably.
