### ISSUE TITLE
Timeout creating/destroying regional GKE cluster

### ISSUE THREAD

**Issue by danisla** [terraform-providers/terraform-provider-google#1744]
Creating a regional cluster takes much longer than a standard zonal cluster. I have an [automated CI test](https://concourse-tf.gcp.solutions/teams/main/pipelines/tf-nat-gw-regression/jobs/run-example-gke-regional) that fails most of the time because it takes more than 10m to create or destroy a regional cluster. 
In my experience, it typically takes between 9-15m to complete this operation. The timeout is 10m. 

Terraform: v0.11.7
Google Provider: v1.15

**Comment by paddycarver** [comment]
From my investigations, it looks like `container_cluster` supports [user-specified timeouts](https://www.terraform.io/docs/configuration/resources.html#timeouts). While we certainly could bump the built-in timeouts, that gives us no way to distinguish between regional and zonal resources. Is there a problem with just setting a custom timeout on the resource if it's timing out for you?

**Comment by danisla** [comment]
Thanks, Paddy, the user-specified timeout seems to fix my problem for now. 

It would still be nice if the resource defaults didn't require additional timeout tweaking when we already know that regional clusters take much longer to destroy.
