### ISSUE TITLE
terraform.io google_compute_disk documentation is formatted incorrectly

### ISSUE THREAD

**Issue by nilium** [terraform-providers/terraform-provider-google#1749]
The google_compute_disk documentation formatting on terraform.io is formatted incorrectly, resulting in the documentation page running list items into paragraphs. This can be observed at <https://www.terraform.io/docs/providers/google/r/compute_disk.html> and affects argument formatting starting with:

> ` * image` - (Optional) The image from which to initialize this disk.

And ending at:

> In addition to the arguments listed above, the following computed attributes are exported:

This doesn't appear to be an issue with the markdown, just the terraform.io HTML produced from it. Not sure if this should be tracked on here, [terraform-website](https://github.com/hashicorp/terraform-website), or another related project. Happy to close and move it as needed.

----

Quick screenshot to help spot this if needed:

![screen shot 2018-07-09 at 4 29 01 pm](https://user-images.githubusercontent.com/44962/42481068-4efc7e2e-8395-11e8-90b9-2e7fb99bba49.png)

**Comment by ndmckinley** [comment]
Thanks!  It should be fixed in #1746.  Let me double check that.

**Comment by ndmckinley** [comment]
![working_disk_page](https://user-images.githubusercontent.com/605324/42481418-25e42ddc-8397-11e8-95d4-70c27b7f9e2a.png)

Yep, this will be fixed when that gets pushed.  Thanks for the report!

**Comment by nilium** [comment]
Awesome! I'll keep an eye on that and close this once it's merged. Thanks!
