### ISSUE TITLE
google_compute_instance - Invalid value for field 'resource.networkInterfaces[0]'

### ISSUE THREAD

**Issue by tealtail** [terraform-providers/terraform-provider-google#175]
I think my usage follows what I've seen in documentation, but when connecting a nat gateway instance to the network, `terraform apply` fails.

---

### Terraform Version
```
› terraform -v
Terraform v0.9.11
```
### Affected Resource(s)
- google_compute_instance
- google_compute_network

### Terraform Configuration Files
```hcl
resource "google_compute_network" "default" {
  name                    = "devops-network"
  auto_create_subnetworks = "false"
}

resource "google_compute_instance" "nat_gateway_1" {
  depends_on = [
    "google_compute_network.default",
  ]

  name         = "devops-network-nat-1"
  machine_type = "n1-standard-1"
  zone         = "us-east1-b"

  can_ip_forward = true

  disk {
    image = "debian-cloud/debian-8"
  }

  network_interface {
    network = "${google_compute_network.default.name}"
  }

  metadata_startup_script = <<EOF
  #!/bin/bash
  sudo sysctl -w net.ipv4.ip_forward=1
  sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf > /dev/null
  sudo apt-get install iptables-persistent
  EOF
}
```

### Debug Output
```
* google_compute_instance.nat_gateway_1: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode network, invalid
```

### Expected Behavior
Expected resource to be created

### Actual Behavior
`terraform apply` failed

### Steps to Reproduce
1. `terraform apply`

**Comment by tealtail** [comment]
Closing. There are also some subnetwork resources being created. Using them in the `network_interface` block worked.

**Comment by viharikrishna** [comment]
Hello
I'm getting similar error "* google_compute_instance.linux-virtualmachine: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].subnetwork': 'projects/viharisnewtest/regions/us-central1/subnetworks/{{us-central1-10-129-2-64-27}}'. The referenced subnetwork resource cannot be found., invalid"

network_interface {
    subnetwork     = "projects/{{viharisnewtest}}/regions/{{us-central1}}/subnetworks/{{us-central1-10-129-2-64-27}}"
  }

Note - This is a shared VPC environment. 
Is my format incorrect?
