### ISSUE TITLE
google_service_account_iam_policy not working as expected

### ISSUE THREAD

**Issue by tsadoklevi** [terraform-providers/terraform-provider-google#1751]
### Terraform Version
Terraform v0.11.7
- provider.google v1.15.0
- provider.random v1.3.1

### Affected Resource(s)
google_service_account_iam_policy

### Terraform Configuration Files
```hcl

resource "google_service_account" "default" {
    account_id   = "${var.account_id}"
    display_name = "${var.display_name}"
}
data "google_iam_policy" "default" {
    binding {
        role = "${var.role}"
        members = ["serviceAccount:${google_service_account.default.email}"]
    }
}
resource "google_service_account_iam_policy" "default" {
    # service_account_id  = "${google_service_account.default.account_id}"
    service_account_id  = "${google_service_account.default.email}"
    policy_data         = "${data.google_iam_policy.default.policy_data}"
}

output "iam_policy_etag" {
    value       = "${google_service_account_iam_policy.default.etag}"
    description = "The etag of the service acccount's IAM policy."
}
```

### Debug Output
```bash

Error: Error applying plan:
2 error(s) occurred:
* module.service_account_for_storage.output.iam_policy_etag: Resource 'google_service_account_iam_policy.default' not found for variable 'google_service_account_iam_policy.default.etag'

* module.service_account_for_storage.google_service_account_iam_policy.default: "service_account_id" ("malta-prod-storage-sa@[GCP_PROJECT_ID].gserviceaccount.com") doesn't match regexp "projects/(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))/serviceAccounts/((?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))@appspot.gserviceaccount.com|[0-9]{1,20}-compute@developer.gserviceaccount.com|[a-z](?:[-a-z0-9]{4,28}[a-z0-9])@[-a-z0-9\\.]{1,63}\\.iam\\.gserviceaccount\\.com$)"

```

### Expected Behavior
Service account IAM policy should be created

### Actual Behavior
Service account IAM policy is not created

**Comment by paddycarver** [comment]
In `google_service_account_iam_policy` use `${google_service_account.default.self_link}` not `${google_service_account.default.email}` for `service_account_id`.

Arguably, we should probably support both, or at least have a better error for a common case like that.

**Comment by tsadoklevi** [comment]
@paddycarver thank you. 

I've tried it and here's what I got:

```bash
Error: Error running plan: 1 error(s) occurred:
* module.service_account_for_storage.google_service_account_iam_policy.default: 1 error(s) occurred:
* module.service_account_for_storage.google_service_account_iam_policy.default: Resource 'google_service_account.default' does not have attribute 'self_link' for variable 'google_service_account.default.self_link
```

Also, when I use 

```hcl
service_account_id  = "projects/${data.google_client_config.default.project}/serviceAccounts/${google_service_account.default.email}"
```

I get

```bash
Error: Error applying plan: 1 error(s) occurred:
* module.service_account_for_storage.google_service_account_iam_policy.default: 1 error(s) occurred:
* google_service_account_iam_policy.default: Error setting IAM policy for service account 'projects/anakatech/serviceAccounts/maltatsadok@anakatech.iam.gserviceaccount.com': googleapi: Error 400: Role roles/storage.objectViewer is not supported for this resource., badRequest
```

And when I use - 

```hcl
 service_account_id  = "${google_service_account.default.email}"
```
I get - 
```bash
Error: Error running plan: 1 error(s) occurred:
* module.service_account_for_storage.google_service_account_iam_policy.default: "service_account_id" ("[ACCOUNT_ID]@[GCP_PROJECT_ID].iam.gserviceaccount.com") doesn't match regexp "projects/(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))/serviceAccounts/((?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))@appspot.gserviceaccount.com|[0-9]{1,20}-compute@developer.gserviceaccount.com|[a-z](?:[-a-z0-9]{4,28}[a-z0-9])@[-a-z0-9\\.]{1,63}\\.iam\\.gserviceaccount\\.com$)"
```

**Comment by paddycarver** [comment]
That's what I get for not checking the docs before replying. Sorry about that! You want `.name`, not `.self_link`.

**Comment by tsadoklevi** [comment]
@paddycarver thank you again. 

Actually I think that the docs are wrong - 

In [google_service_account_key](https://www.terraform.io/docs/providers/google/d/datasource_google_service_account_key.html) the `service_account_id` is defined as using `.email` or unique id - 

> service_account_id - (Required) The Service account id of the Key Pair. This can be a string in the format {ACCOUNT} or projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT}, where {ACCOUNT} is the **email address** or **unique id** of the service account. If the {ACCOUNT} syntax is used, the project will be inferred from the account.

But, in the "Example Usage" section above it none of the above is used and instead the `service_account_id` is set using `.name`

```bash
data "google_service_account" "myaccount" {
  account_id = "myaccount"
}

data "google_service_account_key" "mykey" {
  service_account_id = "${data.google_service_account.myaccount.name}"
  public_key_type = "TYPE_X509_PEM_FILE"
}

output "mykey_public_key" {
  value = "${data.google_service_account_key.mykey.public_key}"
}
```

Moreover, in [IAM policy for service account
](https://www.terraform.io/docs/providers/google/r/google_service_account_iam.html#service_account_id) the `service_account_id` is defined as - 

> service_account_id - (Required) The service account id to apply policy to.

and all the examples use - 

```bash
service_account_id = "your-service-account-id"
```
IMHO when someone reads `service_account_id` s/he infers `account_id` and not '.unique_id` or '.email' and surely not `.name`. 

I hope that the good people at behind Terraform would fix the docs and moreover fix the kind of value used in `service_account_id` so it would use `account_id`.

**Comment by tsadoklevi** [comment]
Adding to the comment above I should note that I haven't been able to add `roles/storage.objectViewer` role to the above mentioned service account. Using this - 

```hcl
resource "google_service_account" "default" {
    account_id   = "${var.account_id}"
    display_name = "${var.display_name}"
}
data "google_iam_policy" "default" {
    binding {
        role = "roles/storage.objectViewer"
        members = ["serviceAccount:${google_service_account.default.email}"]
    }
}
resource "google_service_account_iam_policy" "default" {
    service_account_id  = "${google_service_account.default.name}"
    policy_data         = "${data.google_iam_policy.default.policy_data}"
}
```

... I received `Error 400: Role roles/storage.objectViewer is not supported for this resource`:

```bash
* module.service_account_for_storage.google_service_account_iam_policy.default: 1 error(s) occurred:
* google_service_account_iam_policy.default: Error setting IAM policy for service account 'projects/[PROJECT_ID]/serviceAccounts/[ACCOUNT_ID]@[PROJECT_ID].iam.gserviceaccount.com': googleapi: Error 400: Role roles/storage.objectViewer is not supported for this resource., badRequest
* google_container_node_pool.default: 1 error(s) occurred:
```

On the other hand I could add `roles/storage.objectViewer` role for a specified bucket using 

```hcl
resource "google_storage_bucket_iam_member" "member" {
    bucket          = "${google_storage_bucket.terraform_state.name}"
    role            = "roles/storage.objectViewer"
    member          = "serviceAccount:${module.service_account_for_storage.email}"
}
```

Any insights?

**Comment by walterdolce** [comment]
Hi @tsadoklevi, I suggest you resort to using the `google_project_iam_member` or `google_project_iam_binding` as suggested here: [#1225 (comment)](https://github.com/terraform-providers/terraform-provider-google/issues/1225#issuecomment-385809325)

I suspect all the `google_service_account_iam_*` resources are currently either broken and/or incomplete. Or maybe they're not. But they are definitely confusing.


https://github.com/terraform-providers/terraform-provider-google/issues/

**Comment by tsadoklevi** [comment]
Hi @walterdolce - thank you for you comments. 

I used `google_project_iam_binding` resource as follows and It worked - 
```bash
resource "google_service_account" "cloudsql-sa" {
    account_id   = "cloudsql-sa"
}
resource "google_project_iam_binding" "cloudsql-sa-cloudsql-admin-role" {
    role    = "roles/cloudsql.admin"
    members = [
        "serviceAccount:${google_service_account.cloudsql-sa.email}"
    ]
}
```
This is equivalent to -
```bash
export PROJECT_ID=$(gcloud config list --format 'value(core.project)')
export SA_EMAIL= $(google_service_account.cloudsql-sa.email)
export ROLE="roles/cloudsql.admin"

gcloud projects add-iam-policy-binding $PROJECT_ID --member serviceAccount:$SA_EMAIL --role $ROLE
```
But as commented in #1225 the "side effect" of using this resource is that upon `terraform destroy` **I lost all the members that were previously added to the role (!)**

So, the right resource for adding a service account (or other types of members) is `google_project_iam_member`, as follows - 

```bash
resource "google_service_account" "cloudsql-sa" {
    account_id   = "cloudsql-sa"
}
resource "google_project_iam_member" "cloudsql-sa-cloudsql-admin-role" {
    role    = "roles/cloudsql.admin"
    member = "serviceAccount:${google_service_account.cloudsql-sa.email}"
}
```

**Comment by paddycarver** [comment]
More information on the iam resources possible for the project is available at https://www.terraform.io/docs/providers/google/r/google_project_iam.html. We're always happy to field suggestions on how to improve this to make it clearer.

In this case, the original problem (https://github.com/terraform-providers/terraform-provider-google/issues/1751#issuecomment-404410121) is because the service_account_iam_policy is to determine who is allowed to use the service account, and what permissions they have on it (https://cloud.google.com/iam/docs/service-accounts#service_account_permissions), so you can't set the storage.objectViewer permission on it, because that's not a permission that makes sense in that context. You wanted to use the google_project_iam_member/google_project_iam_policy/google_project_iam_binding resource with the service account being the member, and storage.objectViewer being the role.

It looks like we got to a solution, however, so I'm going to close this out. Feel free to comment if you feel there's more to do here.
