### ISSUE TITLE
Terraform crash on google_container_cluster

### ISSUE THREAD

**Issue by wmuizelaar** [terraform-providers/terraform-provider-google#1767]
### Terraform Version
```
Terraform v0.11.7
+ provider.google v1.16.0
+ provider.local v1.1.0
```

### Affected Resource(s)
- google_container_cluster

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "google" {
  credentials = "${file("/etc/gcp/gke-manager")}"
  project     = "bolcom-frieps6"
  region      = "europe-west4"
}

resource "google_container_cluster" "bolcom-sbx-89s" {
  name               = "bolcom-sbx-89s"
  region             = "europe-west4"
  project            = "bolcom-frieps6"
  min_master_version = "1.10.4-gke.2"
  enable_legacy_abac = false
  network            = "bolcom-sbx"
  subnetwork         = "bolcom-sbx-europe-west4"


  master_auth {
    username =""
    password =""
  }

  addons_config {
    http_load_balancing {
      disabled = false
    }
    horizontal_pod_autoscaling {
      disabled = false
    }
    kubernetes_dashboard {
      disabled = true
    }
    network_policy_config {
      disabled = false
    }
  }

  network_policy {
    provider = "CALICO"
    enabled = true
  }

  pod_security_policy_config {
    enabled = true
  }

  maintenance_policy {
    daily_maintenance_window {
      start_time = "02:00"
    }
  }

  ip_allocation_policy {
    cluster_secondary_range_name = "bolcom-sbx-89s-pods"
    services_secondary_range_name = "bolcom-sbx-89s-services"
  }

  master_ipv4_cidr_block = "172.16.0.16/28"
  private_cluster        = true

  master_authorized_networks_config {
    cidr_blocks = [
      { cidr_block = "91.195.1.40/30", display_name = "office" },
      { cidr_block = "185.14.171.68/32", display_name = "shd-gcp-jump-001" },
      { cidr_block = "185.14.168.100/30", display_name = "vpn-005-006-007-008" },
    ]
  }

  node_pool {
    name       = "internal"
    initial_node_count = 1

    autoscaling {
      min_node_count = 1
      max_node_count = 5
    }

    management {
      auto_repair = true
      auto_upgrade = true
    }
    node_config {
      preemptible = true
      disk_size_gb = 500
      machine_type = "n1-standard-1"
      service_account = "bolcom-sbx-89s-sa@bolcom-frieps6.iam.gserviceaccount.com"
      tags = ["bolcom-sbx-89s-internal"]

      labels {
        bol-environment = "sbx",
        bol-opex = "teamprovisioning",
        bol-status = "operational",
      }

      workload_metadata_config {
        node_metadata = "SECURE"
      }
    }
  }
}
resource "local_file" "master_bolcom-sbx-89s_ip_fact" {
  content = "bol_kubernetes_instance_bolcom-sbx-89s_master_ip=${google_container_cluster.bolcom-sbx-89s.endpoint}"
  filename = "/data/bolcom-frieps6/puppet-executor-data/var/facts.d/kubernetes_instance_bolcom-sbx-89s_master_ip.txt"
}

resource "local_file" "master_bolcom-sbx-89s_cluster_ca" {
  content="${base64decode(google_container_cluster.bolcom-sbx-89s.master_auth.0.cluster_ca_certificate)}"
  filename = "/data/bolcom-frieps6/puppet-executor-data/kubernetes_clusters/bolcom-sbx-89s/cluster.ca"
}

resource "local_file" "cluster_bolcom-sbx-89s_additional_zones_fact" {
  content = "bol_kubernetes_instance_bolcom-sbx-89s_additional_zones=${jsonencode(google_container_cluster.bolcom-sbx-89s.additional_zones)}"
  filename = "/data/bolcom-frieps6/puppet-executor-data/var/facts.d/kubernetes_instance_bolcom-sbx-89s_additional_zones.txt"
}
```

### Panic Output
See https://gist.github.com/wmuizelaar/8fdddb7e42aac6eade2800308d530fed

### Expected Behavior
The defined cluster would have been kept intact and unchanged

### Actual Behavior
Terraform crashed, and the state got screwed up.

### Steps to Reproduce
1. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1663

**Comment by paddycarver** [comment]
Did this happen when you ran `terraform plan` or `terraform apply` after upgrading, with no changes? From what I can tell, the crash occurred when trying to update a cluster when `resource_labels` had changed, but I'm not seeing `resource_labels` in your config. Do you have any information about the events leading up to this crash that could help us understand the scope of the impact here?

(That being said, it looks like a straightforward crash, though I'm scratching my head as to why our tests didn't catch it. I'll be able to find out more in the morning.)

**Comment by wmuizelaar** [comment]
I tried directly a `terraform apply` after upgrading, with no changes. 

We -do- set resource labels on our cluster though, but that's done outside of terraform, with `gcloud`,  maybe it's that what's causing the crash?

**Comment by paddycarver** [comment]
That sounds plausible and would fit my understanding of the code in question. Thanks for the info, I see I path forward on how to reproduce and fix this, and the only question I have left is if it warrants a patch release to fix it. I'll talk with the other maintainers as soon as they come online in the morning. In the meantime, `lifecycle.ignore_changes["resource_labels"]` will prevent the error, I believe.

Sorry for the breakage :(

**Comment by paddycarver** [comment]
We'll be issuing a patch release for this soon.
