### ISSUE TITLE
Secondary ranges on subnetwork resource keep changing with each terraform run

### ISSUE THREAD

**Issue by rolandkool** [terraform-providers/terraform-provider-google#1770]
Hi,

### Terraform Version
Terraform 0.11.7
Google Provider 0.15.0

### Affected Resource(s)
- google_compute_subnetwork

### Terraform Configuration Files
```hcl
resource "google_compute_network" "rklenv-network" {
  name = "rklenv-network"
  project = "bolcom-rklenv"

  auto_create_subnetworks = false
}
resource "google_compute_subnetwork" "bolcom-rklenv-subnetwork" {
  name    = "bolcom-rklenv-subnetwork"
  project = "bolcom-rklenv"
  network = "${google_compute_network.rklenv-network.self_link}"
  region  = "europe-west4"

  private_ip_google_access = true
  ip_cidr_range            = "10.35.0.0/22"
  enable_flow_logs         = "false"

  secondary_ip_range {
    range_name = "bolcom-rklenv-pods"
    ip_cidr_range = "10.34.0.0/16"
  }
  secondary_ip_range {
    range_name = "bolcom-rklenv-pods-test"
    ip_cidr_range = "10.35.8.0/22"
  }
  secondary_ip_range {
    range_name = "bolcom-rklenv-services"
    ip_cidr_range = "10.35.4.0/22"
  }
  secondary_ip_range {
    range_name = "bolcom-rklenv-services-test"
    ip_cidr_range = "10.35.16.0/22"
  }
}

```

### Expected Behavior
Create network + subnetwork + ip ranges on first run. On second run, nothing changes.

### Actual Behavior
In our case, it seems that the order in which the ranges are created by terraform doesn't match the order in the file. This results in terraform keep changing the ranges. It may change 2 or 3, depending on the ordering. But each time, it makes the same change.
In our terraform file, we sort on range_name.

### Steps to Reproduce
Apply the above HCL example and run terraform to make the changes. Then rerun to see if it changes the subnetworks. Good chance it does.

**Comment by Chupaka** [comment]
@rolandkool, so, where's the log of your second run?

**Comment by rolandkool** [comment]
Sorry, here's the output when you rerun terraform (same on each subsequent run):

>  google_compute_network.rklenv-network: Refreshing state... (ID: rklenv-network)
google_compute_subnetwork.bolcom-rklenv-subnetwork: Refreshing state... (ID: europe-west4/bolcom-rklenv-subnetwork)

> An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

> Terraform will perform the following actions:

>  ~ google_compute_subnetwork.bolcom-rklenv-subnetwork
      secondary_ip_range.2.ip_cidr_range: "10.35.16.0/22" => "10.35.8.0/22"
      secondary_ip_range.2.range_name:    "bolcom-rklenv-services-test" => "bolcom-rklenv-pods-test"
      secondary_ip_range.3.ip_cidr_range: "10.35.8.0/22" => "10.35.16.0/22"
      secondary_ip_range.3.range_name:    "bolcom-rklenv-pods-test" => "bolcom-rklenv-services-test"


> Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by sethvargo** [comment]
I think we need to update magic-modules to sort values after composing the slice. We are iterating over a map (which is undefined ordering) which is causing this constant diff. @danawillow @rosbo

**Comment by ndmckinley** [comment]
Bummer!  Are you on `0.16.2`?  That patch release contained our fix for this issue.

**Comment by karlkfi** [comment]
upgrading to 1.16.2 fixed the issue. thanks!

**Comment by ndmckinley** [comment]
Glad to hear that!

**Comment by sethvargo** [comment]
Just cross-reffing here: https://github.com/GoogleCloudPlatform/magic-modules/commit/882606c7612d5c4e2bdafe4c43831accc651eb1f
