### ISSUE TITLE
New Resource Request: Filestore

### ISSUE THREAD

**Issue by Chupaka** [terraform-providers/terraform-provider-google#1774]
Hi there,

Cloud Filestore is in Beta now, can we have it in Terraform, please? :)

https://cloud.google.com/filestore/
https://cloud.google.com/filestore/docs/reference/rest/

**Comment by rolandkool** [comment]
+1

**Comment by TFaga** [comment]
+1 as well. I'd like to take a crack at this and make a PR, if still available and possible.

**Comment by danawillow** [comment]
Hey @TFaga, we're generally trying to have new resources these days be generated by [Magic Modules](https://github.com/GoogleCloudPlatform/magic-modules). If you're interested in submitting a PR there, you're more than welcome to! Otherwise, unless it's an urgent business need, it makes our (the terraform-provider-google maintainers) lives easier if we can avoid new handwritten resources.

**Comment by Chupaka** [comment]
Is there any progress on this?.. @TFaga

**Comment by danawillow** [comment]
I think @ndmckinley is also planning on looking at this.

**Comment by ndmckinley** [comment]
I am!  :)  It'll be the next thing I work on.

**Comment by Chupaka** [comment]
@ndmckinley sorry for bothering you, but is there any ETA?..

**Comment by ndmckinley** [comment]
Hi!  I'm about to head out on a 2 week vacation, unfortunately, so it likely won't be until early September.

**Comment by ryancurrah** [comment]
@ndmckinley woot have a good vacay! Looking forward to filestore in tf

**Comment by rojopolis** [comment]
> Hi! I'm about to head out on a 2 week vacation, unfortunately, so it likely won't be until early September.

We're pushing the limit of what could be considered early in September.  Is there any progress to report?

**Comment by ndmckinley** [comment]
:)  Unfortunately, Filestore still isn't available in the golang SDK - that's the last step.  Everything else _ought_ to work once that comes out.

**Comment by rojopolis** [comment]
Thanks @ndmckinley.  I put [this module](https://registry.terraform.io/modules/rojopolis/filestore/google/0.1.0) together until we can get a proper resource type.

**Comment by ndmckinley** [comment]
I am _impressed_.  I promise I'm working on it on my end, but your module should earn some kind of "best workaround" award.  :)

**Comment by ndmckinley** [comment]
Great news, the SDK came together and I'll be back to getting this out the door very soon.

**Comment by ndmckinley** [comment]
Hooray!  This will be in the next release.  :)
