### ISSUE TITLE
Add support for regional persistent disks

### ISSUE THREAD

**Issue by rolandkool** [terraform-providers/terraform-provider-google#1776]
`google_compute_disks` can now also be regional in stead of bound to a zone. Would it possible to add support for this feature?

https://cloud.google.com/compute/docs/disks/#repds

**Comment by Chupaka** [comment]
Search first :) Regional disks are on their way: https://github.com/terraform-providers/terraform-provider-google/pull/1753

**Comment by paddycarver** [comment]
#1755 is open and looks like it will land soon, so hopefully this will be done shortly.

**Comment by rolandkool** [comment]
Thanks! I did do a search first but obviously missed that ticket :(

**Comment by paddycarver** [comment]
No worries, it happens. :)

**Comment by danawillow** [comment]
Fixed in #1755!
