### ISSUE TITLE
Feature: google_compute_vpc_network_peer

### ISSUE THREAD

**Issue by mtohmaz** [terraform-providers/terraform-provider-google#178]
Anyone know when/if Terraform will support creating [VPC network peers](https://cloud.google.com/compute/docs/peering-networks)? I know it's a Beta feature in GCP, but it's a very simple solution in connecting separate networks either inside or outside GCP.

**Comment by danawillow** [comment]
Thanks for the FR, @mtohmaz! No timeline right now, but I'm going to link this to https://github.com/terraform-providers/terraform-provider-google/issues/93 so we can easily keep track of all the beta FRs.

**Comment by danawillow** [comment]
Still no timeline, but this is in GA now: https://cloud.google.com/compute/docs/reference/latest/networks/addPeering

**Comment by rosbo** [comment]
Hi Mahmoud, I added a new resource named `google_compute_network_peering` to support this new feature. The code has been committed and will be release soon in the next version of the Terraform Google provider.

Here is an example usage:
```hcl
resource "google_compute_network_peering" "peering1" {
  name = "peering1"
  network = "${google_compute_network.default.self_link}"
  peer_network = "${google_compute_network.other.self_link}"
}

resource "google_compute_network_peering" "peering2" {
  name = "peering2"
  network = "${google_compute_network.other.self_link}"
  peer_network = "${google_compute_network.default.self_link}"
}

resource "google_compute_network" "default" {
  name                    = "foobar"
  auto_create_subnetworks = "false"
}

resource "google_compute_network" "other" {
  name                    = "other"
  auto_create_subnetworks = "false"
}
```
