### ISSUE TITLE
network of google_container_cluster resource constantly changing

### ISSUE THREAD

**Issue by drubin** [terraform-providers/terraform-provider-google#1792]
No matter the value i put for `network` field iit never udpates to the 

`projects/xxxxxxx/global/networks/default` its either `default` or `https://www.googleapis.com/compute/v1/projects/xxxxxxx/global/networks/default`

### Terraform Version
Terraform v0.11.7
+ provider.google v1.16.2
+ provider.random v1.3.1

### Affected Resource(s)
- google_container_cluster

### Terraform Configuration Files
```hcl
# Original configuration with out default network
resource "google_container_cluster" "first" {
project = "${google_project.project.id}"
.... 
}

data "google_compute_network" "default" {
  project = "${google_project.project.project_id}"
  name    = "default"
}

resource "google_container_cluster" "second" {
project = "${google_project.project.id}"
...
network = "${data.google_compute_network.default.self_link}" 
...
}
```

### Debug Output

```
  ~ google_container_cluster.first
      network: "projects/infra-a-xxxx/global/networks/default" => "default"

  ~ google_container_cluster.second
      network: "projects/infra-b-xxxx/global/networks/default" => "https://www.googleapis.com/compute/v1/projects/infra-b-xxxx/global/networks/default"
```

### Panic Output
NA

### Expected Behavior
I would expect to not have terraform (try) change my network for my GKE cluster on every single run. It should either update the state or fail, or have migrated my data correctly.

### Actual Behavior
No matter if I use the `name` or `self_link` as documented if the source is a data `data "google_compute_network" ` it seems to constantly try to change the default. 

I suspect I could do some string replace values to remove `https://www.googleapis.com/compute/v1/` but that seems nasty and from the code, I read it should already handle this case.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. Create cluster with the first configuration without network (older version of terraform)
1. Upgrade terraform
1. Start seeing constant network change request

### Important Factoids
I think this GKE cluster was created with a version of 0.10.x terraform, which I later upgraded to 0.11. Nothing breaks or fails to apply it just constantly tries to make this change.

### References
Na

**Comment by danawillow** [comment]
@drubin, are you by any chance using lifecycle.ignore_changes somewhere in that cluster block? If so, this is a known bug in TF core that hasn't been fixed yet. There's more discussion/information in #988 and its linked issues.

Because this sounds suspiciously similar to those other issues, I'm going to close this out as a duplicate, but do let me know if I'm wrong and I'll investigate!

**Comment by drubin** [comment]
@danawillow Yes, I have an ignore_lifecycle changes on our node_pool. (It feels wrong to have node_pools managed from inside the cluster as any change forces a destroy)

Great I will keep an eye on that issue, gave it a quick read seems like you have been struggling with this for MONTHS. Hopefully 0.12 fixes this its super annoying and confuses everyone when they see this change.

Is there maybe a hack I can do by manually editing my state file to remove this constant change?

Linking to the original upstream bug so it's easy to find. https://github.com/hashicorp/terraform/issues/18209

**Comment by danawillow** [comment]
Yeah, so one quickish fix would be to remove the default node pool using `remove_default_node_pool = true` (or whatever it's called, I'm doing this from memory). That would eliminate the need for the lifecycle ignore changes.

The other thing that might work would be to edit your config (as opposed to your state) to specify the network in the `"projects/infra-a-xxxx/global/networks/default"` format.
