### ISSUE TITLE
Ability to get the region configured in the provider (equivalent of the aws_region data source)

### ISSUE THREAD

**Issue by walterdolce** [terraform-providers/terraform-provider-google#1800]
Hi there, this is a feature request (or bug, depending on how you want to look at it :)

### Terraform Version
```
Terraform v0.11.7
+ provider.google v1.16.2
```

### Affected Resource(s)
N/A

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
There should be a way to reference the region configured in the provider in other resources, so that people don't have to specify/maintain/remember a `${var.region}` to achieve this.

### Actual Behavior
There isn't such functionality.

### Steps to Reproduce
N/A

### Important Factoids
N/A

### References
The AWS provider provides such functionality: https://www.terraform.io/docs/providers/aws/d/region.html

**Comment by danawillow** [comment]
Hey @walterdolce, I think https://www.terraform.io/docs/providers/google/d/datasource_client_config.html is what you're looking for. Does that look about right to you?

**Comment by walterdolce** [comment]
Hi @danawillow, I didn't see that data resource! Thanks! 

So the `data.google_client_config.current.region` value would come from the provider regardless on how it's setup? (i.e. whether set via `GOOGLE_REGION`, or `GCLOUD_REGION`, or `CLOUDSDK_COMPUTE_REGION`, or explicitly on the provider - in that order?)

**Comment by walterdolce** [comment]
I didn't know it existed. I even PR'd it :) - #1804

**Comment by danawillow** [comment]
Yup, if you take a look at the code, it was implemented in the same way as in your PR: https://github.com/terraform-providers/terraform-provider-google/blob/master/google/data_source_google_client_config.go

In terms of precedence, a region set explicitly on the provider will come first, and then environment variables in the order GOOGLE_REGION, GCLOUD_REGION, CLOUDSDK_COMPUTE_REGION.

**Comment by walterdolce** [comment]
Ha! Thanks a lot for clarifying that for me. I will close the PR and this issue unless you guys would like to keep it for some reason?
