### ISSUE TITLE
Support for OS Login?

### ISSUE THREAD

**Issue by ctindel** [terraform-providers/terraform-provider-google#1815]
I ran across this forum post:

https://groups.google.com/forum/#!topic/terraform-tool/z8VOIegiAE4

And I was wondering, has this been added yet?  I looked through the docs and didn't see anything but wasn't sure.

**Comment by ndmckinley** [comment]
Not yet!  Thanks for opening the issue.  :)

**Comment by ducksauz** [comment]
Did some messing around today. I don't think any specific support is actually required.

Step 1: Enable oslogin API for your project

```
resource "google_project_services" "project" {
  project = "${var.project-id}"
  services   = [
    "iam.googleapis.com",
    "compute.googleapis.com",
    "oslogin.googleapis.com",
    "cloudmonitoring.googleapis.com"
  ]
}
```

Step 2: Set enable-oslogin metadata on your instances
```
resource "google_compute_instance" "foo-instance" {
  name         = "foo-dev"
  machine_type = "f1-micro"
  zone         = "${var.region-us}-a"
[SNIP]
  metadata {
    enable-oslogin = "TRUE"
  }
}
```

Step 3: Add appropriate IAM binding to the project
```
resource "google_project_iam_binding" "os-login-admin-users" {
  role = "roles/compute.osAdminLogin"

  members = [
    "user:bofh@example.com",
    "group:sysadmins@example.com",
  ]
}
```

Do those things and it should work. It did for me.

**Comment by ndmckinley** [comment]
Oh, excellent.  :)  I'll go ahead and close the issue.
