### ISSUE TITLE
How do I do a cloud-init configuration?

### ISSUE THREAD

**Issue by ctindel** [terraform-providers/terraform-provider-google#1816]
Trying to port a project over from the AWS provider, where I would just give the template_cloudinit_config rendered into a user_data variable, but there is no user_data variable in google_compute_instance and google is not helping me here.

**Comment by ctindel** [comment]
Just in case someone wanders along later, it needs to be in "user-data" (not "user_data") part of the metadata:

```
resource "google_compute_instance" "instance" {
  metadata {
    user-data = "${data.template_cloudinit_config.instance_user_data.rendered}"
  }
}
```

**Comment by ndmckinley** [comment]
Opened a PR showing how to do it in GCP!  Closing this issue, since it's not pending any investigation on our end.
