### ISSUE TITLE
Google project services, always marked for change

### ISSUE THREAD

**Issue by pmyjavec** [terraform-providers/terraform-provider-google#1818]
### Terraform Version

`0.11.7`

### Affected Resource(s)

- google_project_services

### Terraform Configuration Files
```hcl
resource "google_project_services" "project" {
  project = "${google_project.main.number}"

  services = [
    "iam.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "container.googleapis.com",
    "containerregistry.googleapis.com",
  ]
}
```

### Expected Behavior

Terraform should act in an idempotent and not make any changes to the list of enabled services for my project. 

### Actual Behavior

When running Terraform with the above configuration against my project, TF seems seem to be confused about which services are enabled and will continuously try to enable services and (disable?) services, see the following [plans](https://gist.github.com/pmyjavec/adc8f23a4ff3702ea35cfe9b2d951690).

Here is a [diff](https://gist.github.com/pmyjavec/e256953822572e1a718e7f6510d52559) of the two resources in the state file.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

No

### References

N/A

**Comment by ndmckinley** [comment]
I'm sorry for the inconvenience, but that's working as intended.  That's the issue that's meant to be called out by the note on the documentation page: https://www.terraform.io/docs/providers/google/r/google_project_services.html.  I'd be more than happy to modify the note if there's something else you'd like to see there.

To summarize, `google_project_services` is supposed to be a list of *all* services available on the project, and is only useful for very particular use cases where you can control which services wind up enabled.  You almost certainly want to use a series of `google_project_service` resources instead.

There's a proposal in #1814 to modify the way this resource works which we haven't decided about yet - if we take that up, the resulting resource might be a better call than a series of `google_project_service` resources.

**Comment by pmyjavec** [comment]
Hello Nathan,

Thanks for getting back to me. I think it would be more clear to say something like:

“A list of all available services available should be provided and each service you would like to enable or disable should be set individually”

Something to that effect?

I read the current note and the only limitation I read was that I can’t use it in conjunction with “google_project_service” , which I wasn’t and I still had the problem, hence filing the bug.

Cheers

**Comment by ndmckinley** [comment]
That does seem clearer!  I'll make a change like that.

**Comment by pmyjavec** [comment]
Excellent, appreciate it and thank you ! :)
