### ISSUE TITLE
google_compute_shared_vpc_host_project support to enable Kubernetes engine

### ISSUE THREAD

**Issue by aman-wolde-ck** [terraform-providers/terraform-provider-google#1819]
The resource for attaching a service project to a host project does not allow you to set the option to enable Kubernetes Engine access. This can be accomplished on GCP console.

### Affected Resource(s)
- google_compute_shared_vpc_service_project

### Terraform Configuration Files
```hcl
resource "google_compute_shared_vpc_service_project" "project" {
  host_project    = "${google_project.shared_vpc.project_id}"
  service_project = "${google_project.project.project_id}"

  depends_on = [
    "google_compute_shared_vpc_host_project.host_project",
  ]
}
```

**Comment by ndmckinley** [comment]
Oh, cool.  There's a lot of steps there, but I think we can make that work.  These are the gcloud commands we'll need to emulate: https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-shared-vpc#enabling_shared_vpc_and_granting_roles

**Comment by ndmckinley** [comment]
Oh, hey, we can make it work just by granting `compute.SubnetworkUser` to the two relevant service accounts for k8s.  No problem.  I say we just add a list of subnetworks, call it `k8s_access_subnets` or something like that, and add those iam roles to the right service accounts for every subnet in the list.  I'll see what I can do.

**Comment by ndmckinley** [comment]
@morgante had some concerns on the linked PR - we'll get that sorted!  :)  Chime in there if you have an opinion.

**Comment by ndmckinley** [comment]
FWIW I'm inclined to agree with @morgante that this introduces some potential for confusion - If your use case is hard to cover with the existing mechanism, please say so here or on the PR.  Unless you or someone else has an opinion, I'll probably close the PR and the issue in about a week.  :)  Happy to change my mind, though!

Best,
Nathan
