### ISSUE TITLE
resource_google_project app_engine expects list instead of map

### ISSUE THREAD

**Issue by ryanckoch** [terraform-providers/terraform-provider-google#1821]
The new app_engine block in the google_project resource expects a list with a max length of 1 rather than a map. https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_google_project.go#L95

Is there a specific reason for this? This makes it rather difficult to modularize it and have decent outputs if some of your resources enable app_engine and others don't. You also have to so some other hackery to pass a empty list if variable not declared... would be much easier to pass empty map.

### Affected Resource(s)
- google_project

### References
- https://github.com/terraform-google-modules/terraform-google-project-factory/pull/4

**Comment by ndmckinley** [comment]
Hm, the list (nested object, really) is what makes sense to me.  What would you expect as the keys and values in the map, given that Terraform maps can only be string->string?

https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L125
