### ISSUE TITLE
Node IP Address for GKE

### ISSUE THREAD

**Issue by maganuk** [terraform-providers/terraform-provider-google#1824]
Is there any way to get external IP Addresses for the GKE Nodes from a node_pool or a cluster? I want to assign these to the firewall rules in a RDS Database and Azure SQL Database. Alternatively, why is there no data source for a compute instance? Since I can acquire the compute instance name from the cluster, I could use this to get to the network ip.

**Comment by morgante** [comment]
@maganuk By design, GKE nodes are meant to be mostly ephemeral so I'd discourage directly whitelisting the instances themselves. Instead you could whitelist the subnet that the GKE cluster is launched in.
