### ISSUE TITLE
Custom app_engine feature_settings in google_project requires two applys

### ISSUE THREAD

**Issue by ryanckoch** [terraform-providers/terraform-provider-google#1826]
In order to set custom feature settings in the new google_project app_engine block requires two `terraform apply`s. This is not optimal.

### Affected Resource(s)
- google_project

### Terraform Configuration Files
```hcl
locals {
  credentials_file_path = "./sa-key.json"
}

provider "google" {
  credentials = "${file(local.credentials_file_path)}"
}

resource "google_project" "project" {
  name            = "testproject"
  project_id      = "testproject-11399"
  org_id          = "############"
  billing_account = "######-######-######"

  app_engine = [
    {
      location_id = "us-east1"

      feature_settings = [
        {
          split_health_checks = false
        },
      ]
    },
  ]
}

```

### Expected Behavior
All app_engine settings configured in one `terraform apply`

### Actual Behavior
Requires two passes of `terraform apply` to get everything set properly

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Set feature_settings in app_engine block
2. `terraform apply`
3. `terraform plan` to see additional work needed
4. `terraform apply`
See gist for full output: https://gist.github.com/ryanckoch/ab3e3780071f1fb6f8616402890e0af4

**Comment by ndmckinley** [comment]
Well, that's not great!  I'll see if I can get that added to our unit tests so we don't continue to regress.  Thanks!

**Comment by ndmckinley** [comment]
Very strange, but yes, I see the error right there.  What version of the Google provider are you using?  I can't repro in `0.16.2`.

**Comment by ryanckoch** [comment]
Hmmm

```
➜  issue-1826 terraform --version
Terraform v0.11.7
+ provider.google (unversioned)

Your version of Terraform is out of date! The latest version
is 0.11.8. You can update by downloading from www.terraform.io/downloads.html
```

```
➜  issue-1826 bash -c "cd ${GOPATH}/src/github.com/DeviaVir/terraform-provider-gsuite && git rev-parse HEAD"
1ece8af5a8acc4aac3639652bd602eddb63ad7f4
```

**Comment by ndmckinley** [comment]
Sorry, it's terraform-provider-google, not terraform-provider-gsuite.  :(

**Comment by ryanckoch** [comment]
Bah... Sorry... I clearly need a nap
```
➜  issue-1826 bash -c "cd ${GOPATH}/src/github.com/terraform-providers/terraform-provider-google && git rev-parse HEAD"
f3fa40caf2bbc303dcca23ae15eabc1dc5716067
```

**Comment by rileykarson** [comment]
This field was removed and split out into a separate resource; see https://www.terraform.io/docs/providers/google/version_2_upgrade.html#app_engine-has-been-removed
