### ISSUE TITLE
google_sql_database_instance not working anymore

### ISSUE THREAD

**Issue by tmeulensteen** [terraform-providers/terraform-provider-google#1838]
Hi,

Creating a google_sql_database_instance does not seem to work anymore. A few weeks ago this was working fine, but today it isn't

### Terraform Version
Terraform v0.11.7
+ provider.google v1.16.0

### Affected Resource(s)
Please list the resources as a list, for example:
- google_sql_database_instance

### Terraform Configuration Files
```hcl
resource "google_sql_database_instance" "master" {
  name = "test-postgresql-instance"
  database_version = "POSTGRES_9_6"
  region = "europe-west1"
  settings {
    tier = "db-f1-micro",
    ip_configuration {
      authorized_networks {
        name = "AuthNetworkName",
        value = "xxxxx"
      }
    }
    availability_type = "ZONAL"
  }
}
```

### Debug Output
Error: Error applying plan:

1 error(s) occurred:

* google_sql_database_instance.master: 1 error(s) occurred:

* google_sql_database_instance.master: Error, failed to create instance test-postgresql-instance: googleapi: Error 400: Invalid parameter: instance name (ProjectID:test-postgresql-instance).., invalid

### Expected Behavior
The SQL resource will be created.

### Actual Behavior
The resource creation crashed on a invalid name parameter.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by Chupaka** [comment]
Did you try to change "test-postgresql-instance" to something else?

`name` - (Optional, Computed) The name of the instance. If the name is left blank, Terraform will randomly generate one when the instance is first created. **This is done because after a name is used, it cannot be reused for up to one week.**

**Comment by tmeulensteen** [comment]
Even when omitting the name parameter, the creation of a new sql resource fails


* google_sql_database_instance.test-postgresql-instance: Error, failed to create instance terraform-20180802111627675300000001: googleapi: Error 400: Invalid parameter: instance name (projectid:terraform-20180802111627675300000001).., invalid

**Comment by Chupaka** [comment]
Well, at least the following config deployed normally for me:

```
resource "google_sql_database_instance" "master" {
  database_version = "POSTGRES_9_6"
  region = "europe-west1"
  settings {
    tier = "db-f1-micro",
    availability_type = "ZONAL"
  }
}
```

```
google_sql_database_instance.master: Creation complete after 7m2s (ID: terraform-20180802114232832400000001)
```

```
$ terraform -v
Terraform v0.11.7
+ provider.google v1.16.2
```

**Comment by tmeulensteen** [comment]
When using the same settings

`resource "google_sql_database_instance" "master" {
  database_version = "POSTGRES_9_6"
  region = "europe-west1"
  settings {
    tier = "db-f1-micro",
    availability_type = "ZONAL"
  }
}`

Even when using the latest provider
`$ ./terraform -v
Terraform v0.11.7
+ provider.google v1.16.2`

I still get this error.
`Error: Error applying plan:

1 error(s) occurred:

* google_sql_database_instance.mastertwo: 1 error(s) occurred:

* google_sql_database_instance.mastertwo: Error, failed to create instance terraform-20180806141315831200000001: googleapi: Error 400: Invalid parameter: instance name (CI-Environment:terraform-20180806141315831200000001).., invalid

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.`

**Comment by Chupaka** [comment]
What templates?.. For me, it seems like something is adding project name and colon ("projectid:") before the generated "terraform-nnnnn" part of name...

**Comment by ndmckinley** [comment]
Yes, the problem is likely with your Terraform environment - on a clean install you wouldn't likely be seeing this.  If you could please post the full template, I'd be happy to try and see where the problem is coming from.
