### ISSUE TITLE
Setting automatic_restart to false does not work

### ISSUE THREAD

**Issue by piyushk** [terraform-providers/terraform-provider-google#1839]
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- google_compute_instance

### Terraform Configuration Files
```hcl
  scheduling {
    automatic_restart = false
    on_host_maintenance = "TERMINATE"
  }
```

### Expected Behavior
When the host went down for maintenance, the instance terminated and restarted. We need the instances to terminate and stay terminated should that happen. GCP should display "Automatic restart: Off"

### Actual Behavior
The instance should have terminated on host maintenance. GCP displays "Automatic restart: On (recommended)"

**Comment by ndmckinley** [comment]
Sorry about that!  I'm trying to build a repro case now.

**Comment by piyushk** [comment]
`terraform-provider-google_v1.8.0_x4`

I'll need some time to generate an example from my config. I'll try and post it shortly.

**Comment by ndmckinley** [comment]
Oh, that's very far out of date, I have no trouble at all believing you had trouble there!  :)  I can even imagine what the problem must have been.  We try not to make breaking changes, I hope the upgrade isn't too much of a struggle.

**Comment by ndmckinley** [comment]
Confirmed - the issue is present in `1.8.0` but not in `1.16.2`.  Please upgrade.  :)

**Comment by piyushk** [comment]
Thanks for confirming @ndmckinley. I've confirmed that this error does not exist in 1.16.2 as well. I didn't realize that the providers needed to be updated separately.
