### ISSUE TITLE
Error bringing up Terraform database instances

### ISSUE THREAD

**Issue by snalvi** [terraform-providers/terraform-provider-google#1841]
Hi there,

I've run into this issue multiple times now where Terraform fails to bring up the infrastructure appropriately on an GCP. We're trying to bring up multiple database instances, and it fails about ~50% of the time. Looking around online it says it's a GCP API timing issue, that sometimes you just need to wait, but it seems odd that the issue keeps cropping up without any real reason or solid reproducibility (eg. it fails ).

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- google_sql_database_instance
- google_sql_database.<database-name>

(Database name is trying to connect to Database instance)

### Terraform Configuration Files
```hcl
resource "google_sql_database_instance" "instance-db" {
  name = "${local.prefix}"
  database_version = "POSTGRES_9_6"
  region = "${var.region}"

  settings {
    tier = "db-f1-micro"
    ip_configuration {
      authorized_networks = [ {
        name = "${local.prefix}-nat"
        value = "${google_compute_instance.nat-instance.network_interface.0.access_config.0.assigned_nat_ip}"
      }]
    }
  }
}

resource "google_sql_database" "database-name" {
  name      = "custom-name"
  instance  = "${google_sql_database_instance.instance-db.name}"
}
```

### Expected Behavior
All instances come up appropriately

### Actual Behavior
Error: 
```
Error: Error applying plan:

2 error(s) occurred:
* google_sql_database.credhub-db: 1 error(s) occurred:
* google_sql_database.credhub-db: Error, failure waiting for insertion of <dabase> into <deployment>:
* google_sql_database.uaa-db: 1 error(s) occurred:
* google_sql_database.uaa-db: Error, failure waiting for insertion of uaa into <deployment>:
```

### Steps to Reproduce
`terraform apply`

**Comment by Chupaka** [comment]
And where's the full log?

Isn't it creation timeout error? What if you increase it on the resource?

```
  timeouts {
    create = "60m"
    delete = "2h"
  }
```

**Comment by ndmckinley** [comment]
This seems like a timeout issue, yes.  Did @Chupaka's timeout block help?

**Comment by pivotal-saman-alvi** [comment]
Yes, the timeout block solved the problem. Thanks @Chupaka !

**Comment by g0blin79** [comment]
Have the same problem and "timeouts" setting does not resolve for me.

This is the snapshot of my config.tf

```
[...]

// Define SQL instances
resource "google_sql_database_instance" "production-postgres" {
  name = "production-postgres"
  database_version = "POSTGRES_9_6"
  region = "europe-west3"

  settings {
    # Second-generation instance tiers are based on the machine
    # type. See argument reference below.
    tier = "db-custom-2-7680"

    backup_configuration {
    	enabled = true
    	start_time = "00:00"
    }
  }

  timeouts {
    create = "60m"
  }
}

// Define Database
resource "google_sql_database" "testdb" {
  name      = "testdb"
  instance  = "${google_sql_database_instance.production-postgres.name}"
  charset   = "latin1"
  collation = "latin1_swedish_ci"
}

[...]
```

This is the error:

```
Error: Error applying plan:

1 error(s) occurred:

* google_sql_database.testdb: 1 error(s) occurred:

* google_sql_database.testdb: Error, failure waiting for insertion of testdb into production-postgres:
```

**Comment by ndmckinley** [comment]
@g0blin79 - you've added the timeout block to the database instance, but it's the database which needs it (`testdb` instead of `production-postgres`).

**Comment by g0blin79** [comment]
> you've added the timeout block to the database instance, but it's the database which needs it

Yes I'll try. I added to the database instance because in terraform official documentation this setting seems to be available only for database instance (https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#timeouts)

and not available for database

https://cloud.google.com/sql/docs/mysql/admin-api/v1beta4/databases
https://www.terraform.io/docs/providers/google/r/sql_database.html

But I'll try

**Comment by g0blin79** [comment]
Tried without success.
This is my configuration updated.

```
[...]

// Define SQL instances
resource "google_sql_database_instance" "production-postgres" {
  name = "production-postgres"
  database_version = "POSTGRES_9_6"
  region = "europe-west3"

  settings {
    # Second-generation instance tiers are based on the machine
    # type. See argument reference below.
    tier = "db-custom-2-7680"

    backup_configuration {
    	enabled = true
    	start_time = "00:00"
    }
  }
}

// Define Database
resource "google_sql_database" "testdb" {
  name      = "testdb"
  instance  = "${google_sql_database_instance.production-postgres.name}"
  charset   = "latin1"
  collation = "latin1_swedish_ci"

  timeouts {
    create = "60m"
  }
}

[...]
```

This the resulted error

```
Error: Error applying plan:

1 error(s) occurred:

* google_sql_database.testdb: 1 error(s) occurred:

* google_sql_database.testdb: Error, failure waiting for insertion of testdb into production-postgres:
```

Maybe there is something wrong?

**Comment by sereeth** [comment]
@g0blin79 I'm having the same issue, this is a bug somewhere in TF or its a Google API issue.  New issue here: https://github.com/terraform-providers/terraform-provider-google/issues/2055
