### ISSUE TITLE
Unable to deploy google cloud resources via https proxy

### ISSUE THREAD

**Issue by tflowcamdev** [terraform-providers/terraform-provider-google#1847]
Apologies if there's an issue already for this, but I wasn't able to find one.

I'm trying to deploy google cloud resources behind a firewall, and need to use an https proxy for connections outbound.  This is generally possible with most providers by setting the HTTPS_PROXY environment variable.  It seems that go generally supports this out of the box with net/http with the default client/transport.

However, when trying to deploy google cloud resources, it's not working for me - Can support for this be added?

I'm using an envioronment variable like this:

HTTPS_PROXY=http://myuser:mypasword@10.10.10.20:3128

### Terraform Version
Terraform v0.11.2
+ provider.google v1.16.0

(We've had the same issue with terraform v.11.3 too)

### Affected Resource(s)
- google_compute_instance

Haven't gotten far enough to test other resources, but think this is a general issue with the provider reaching out via proxy.

Relevant part of the output is as follows:

2018-08-07T18:19:44.534Z [DEBUG] plugin.terraform-provider-google_v1.16.0_x4: 2018/08/07 18:19:44 [DEBUG] Loading zone: us-central1-a
2018-08-07T18:19:44.534Z [DEBUG] plugin.terraform-provider-google_v1.16.0_x4: 2018/08/07 18:19:44 [DEBUG] Google API Request Details:
2018-08-07T18:19:44.534Z [DEBUG] plugin.terraform-provider-google_v1.16.0_x4: ---[ REQUEST ]---------------------------------------
2018-08-07T18:19:44.534Z [DEBUG] plugin.terraform-provider-google_v1.16.0_x4: GET /compute/v1/projects/oceanic-guard-191815/zones/us-central1-a?alt=json HTTP/1.1
2018-08-07T18:19:44.534Z [DEBUG] plugin.terraform-provider-google_v1.16.0_x4: Host: www.googleapis.com
2018-08-07T18:19:44.534Z [DEBUG] plugin.terraform-provider-google_v1.16.0_x4: User-Agent: google-api-go-client/0.5 Terraform/0.11.7 (+https://www.terraform.io)
2018-08-07T18:19:44.534Z [DEBUG] plugin.terraform-provider-google_v1.16.0_x4: Accept-Encoding: gzip
2018-08-07T18:19:44.534Z [DEBUG] plugin.terraform-provider-google_v1.16.0_x4:
2018-08-07T18:19:44.534Z [DEBUG] plugin.terraform-provider-google_v1.16.0_x4:
2018-08-07T18:19:44.534Z [DEBUG] plugin.terraform-provider-google_v1.16.0_x4: -----------------------------------------------------
2018/08/07 18:19:44 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* google_compute_instance.default: Error loading zone 'us-central1-a': Get https://www.googleapis.com/compute/v1/projects/oceanic-guard-191815/zones/us-central1-a?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: Service Unavailable
2018/08/07 18:19:44 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* google_compute_instance.default: Error loading zone 'us-central1-a': Get https://www.googleapis.com/compute/v1/projects/oceanic-guard-191815/zones/us-central1-a?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: Service Unavailable

2018/08/07 18:19:44 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error applying plan:

1 error(s) occurred:

* google_compute_instance.default: 1 error(s) occurred:

* google_compute_instance.default: Error loading zone 'us-central1-a': Get https://www.googleapis.com/compute/v1/projects/oceanic-guard-191815/zones/us-central1-a?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: Service Unavailable

### Actual Behavior
Terraform failed to deploy

### Steps to Reproduce
1. `terraform apply`

**Comment by danawillow** [comment]
Interesting! @tflowcamdev, do you have an example provider that you know works with this? I just poked around the aws provider code for a sec and didn't see anything specific regarding proxies, but it's possible I just didn't look hard enough.

**Comment by danawillow** [comment]
Thanks, that's super helpful! I'll get right on it.

**Comment by danawillow** [comment]
All right, I took a look at this and as far as I can tell, this provider _is_ using the default http client: if you follow the code down, it ends up getting set to `http.DefaultClient` [here](https://github.com/terraform-providers/terraform-provider-google/blob/master/vendor/golang.org/x/oauth2/internal/transport.go#L33). I'm not really sure why it's not picking up the proxy settings, but I'm not confident there's anything else I can do on our end.

**Comment by paddycarver** [comment]
This is related to #2109, I think, though they're reporting it's service-specific?

**Comment by tflowcamdev** [comment]
@danawillow hey thanks so much - I have retested by getting the latest provider and it is working for me.

I'm not sure exactly where this started working - but it does look good now - sorry for wasting your time here.

**Comment by jawlitkp** [comment]
this is still occurring for me.
