### ISSUE TITLE
Please support Node 8 runtime for Cloud Functions

### ISSUE THREAD

**Issue by kaifresh** [terraform-providers/terraform-provider-google#1857]
This is a feature request to support Node 8 runtimes for Cloud Functions. This was recently introduced here: https://cloud.google.com/functions/docs/concepts/exec#runtimes

Thanks

**Comment by kulkarnisu** [comment]
+1, especially Python support would be appreciated

**Comment by geekflyer** [comment]
on that occasion please also add support passing environment variables: https://cloud.google.com/functions/docs/env-var

**Comment by yevgen87** [comment]
Fix is here https://github.com/terraform-providers/terraform-provider-google/issues/2062

Added nojejs6, nodejs8, python37 runtimes.

**Comment by srossross** [comment]
> Any idea when this will get released?

from #2062, or can you tell me how to apply this patch to terraform?

**Comment by Chrisjw42** [comment]
The list of runtimes above are not included in the doco, it's probably worth adding them there, since the specific strings would be easy to get wrong.
