### ISSUE TITLE
google_compute_instance.network_interface.*.alias_ip_range assert error - max 1 array element permitted

### ISSUE THREAD

**Issue by rsawer** [terraform-providers/terraform-provider-google#1858]
### Terraform Version
+ Terraform version: 0.11.7  41e50bd32a8825a84535e353c3674af8ce799161
+ provider.google v1.16.2

### Affected Resource(s)
- google_compute_instance

### Terraform Configuration Files

resource "google_compute_instance" "instance1" {
    name                    = "instance1"
    machine_type            = "n1-standard-1"
    zone                    = "europe-west1-c"
    allow_stopping_for_update = true
        boot_disk {
        initialize_params {
            image           = "someimage"
            type            = "pd-standard"
            size            = "30"
        }
    }
      network_interface {
        subnetwork          = "net-0-sub-1" 
        subnetwork_project  = "someproject"
        address             = "172.27.1.11"
        alias_ip_range = [
            {
                "ip_cidr_range" = "172.27.1.12/32"
            },
            {
                "ip_cidr_range" = "172.27.1.13/32"
            }
        ]
    }

}

### Debug Output
018/08/10 13:57:48 [ERROR] root.module: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [network_interface.0.alias_ip_range: attribute supports 1 item maximum, config has 2 declared]
2018/08/10 13:57:48 [ERROR] root.module: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [network_interface.0.alias_ip_range: attribute supports 1 item maximum, config has 2 declared]

### Expected Behavior
There is a possibility to add couple of ip alias ranges from gcloud console 
Rest equivalent:
 "networkInterfaces": [
    {
      "aliasIpRanges": [
        {
          "ipCidrRange": "172.27.1.12/32"
        },
        {
          "ipCidrRange": "172.27.1.13/32"
        }
      ],
      "fingerprint": "00000=",
      "kind": "compute#networkInterface",
      "name": "nic0",
      "network": "somenetwork",
      "networkIP": "172.27.1.11",
      "subnetwork": "some subnetwork"
    }
  ],

Tfstate after importing existing resource with two ip alias ranges:
"network_interface.0.alias_ip_range.0.ip_cidr_range": "172.27.1.12/32",
"network_interface.0.alias_ip_range.0.subnetwork_range_name": "",
"network_interface.0.alias_ip_range.1.ip_cidr_range": "172.27.1.13/32",
"network_interface.0.alias_ip_range.1.subnetwork_range_name": "",

### Actual Behavior
Error: module.module.google_compute_instance.instance1: network_interface.0.alias_ip_range: attribute supports 1 item maximum, config has 2 declared

### Steps to Reproduce
1. Add following alias ip range block inside ntwork_interface block:
        alias_ip_range = [
            {
                "ip_cidr_range" = "172.27.1.12/32"
            },
            {
                "ip_cidr_range" = "172.27.1.13/32"
            }
        ]
2. Terraform apply

**Comment by croteaub** [comment]
Seeing the same behavior with the cloudsql resource as well:

Error: google_sql_database_instance.master: settings.0.backup_configuration: attribute supports 1 item maximum, config has 2 declared

resource "google_sql_database_instance" "master" {
  count            = "${var.create}"
  name             = "${var.name}"
  master_instance_name = "${var.name}"
  project          = "${var.project}"
  region           = "${var.region}"
  database_version = "${var.database_version_create}"

  settings {
    tier                        = "${var.db_machine_type}"
    activation_policy           = "${var.activation_policy}"
    availability_type           = "${var.availability_type}"
    authorized_gae_applications = ["${var.authorized_gae_applications}"]
    disk_autoresize             = "${var.disk_autoresize}"
    backup_configuration        = ["${var.backup_configuration}"]
    location_preference          = ["${var.location_preference}"]
    maintenance_window          = ["${var.maintenance_window}"]
    disk_size                   = "${var.disk_size}"
    disk_type                   = "${var.disk_type}"
    pricing_plan                = "${var.pricing_plan}"
    replication_type            = "${var.replication_type}"
    backup_configuration {
      binary_log_enabled = "true"
      enabled = "true"
      start_time= "03:00"
    }
/*
IP configuration is used for whitelisting.  Must use an External IP, can not be private.
IP configuration is not required when using the Cloud SQL proxy side car
    ip_configuration = [{
      authorized_networks = [{
        name = "${var.authorized_networks_name}"
        value = "172.26.0.0/16"
      }]
      require_ssl = "${var.require_ssl}"
    }]
*/
  }

  replica_configuration = ["${var.replica_configuration}"]
}

**Comment by ndmckinley** [comment]
@croteaub: please file a separate issue for Cloud SQL - these are going to have to be fixed individually and it will be easier to track them separately.

**Comment by croteaub** [comment]
Will do
