### ISSUE TITLE
google_compute_instance documentation error

### ISSUE THREAD

**Issue by steven-edgar** [terraform-providers/terraform-provider-google#1864]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance
- google_storage_bucket

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

- google_compute_instance  - Documentation

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
n/a

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

n/a

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

n/a

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

There is an error in the documentation for the google_compute_instance resource, attached_disk block, device_name argument
https://www.terraform.io/docs/providers/google/r/compute_instance.html#device_name-1
This is described as:

device_name - (Optional) Name with which the attached disk will be accessible under /dev/disk/by-id/

Whilst it's not spelled out in the Google cloud API docs for attached disk, it is spelled out in the similar disks[] section in https://cloud.google.com/compute/docs/reference/rest/v1/instances, that the name given here will be presented in the provisioned VM as /dev/disk/by-id/google-{{ device_name }}, and therefore that doc should read

device_name - (Optional) Name with which the attached disk will be accessible under /dev/disk/by-id/google-{{ device_name }}

Having recently provisioned several VMs on GCP using this terraform module and with the attached_disk.device_name set, I can verify that this is correct.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by ndmckinley** [comment]
Thank you, that's helpful, let me tweak that.
