### ISSUE TITLE
Precondition failed for billing account = bad error

### ISSUE THREAD

**Issue by morgante** [terraform-providers/terraform-provider-google#1892]
### Affected Resource(s)
- google_project

### Expected Behavior
When I create a project and attempt to associate billing, if my billing account doesn't have sufficient quota I should get a "precondition failed error" which references that my quota is exhausted.

### Actual Behavior
The error is "precondition failed" but doesn't specify what the failed precondition is.

### Steps to Reproduce
Attempt to create a new project on a billing account (via Terraform) which doesn't have any quota left.

**Comment by ndmckinley** [comment]
Does the error that comes back from the GCP API contain enough information to know that the error is related to exhausted quota?

**Comment by morgante** [comment]
@ndmckinley I don't currently have a billing account with insufficient quota, but I *do* know that gcloud is able to return a verbose error in this case (similar to #1903). Not quite sure how gcloud knows that.

**Comment by mattlawnz** [comment]
yes it does, here is the error:

```ERROR: (gcloud.beta.billing.projects.link) FAILED_PRECONDITION: Precondition check failed.
- '@type': type.googleapis.com/google.rpc.QuotaFailure
  violations:
  - description: 'Cloud billing quota exceeded: https://support.google.com/code/contact/billing_quota_increase'
    subject: billingAccounts/REDACTED```

**Comment by emilymye** [comment]
It looks like the API now returns a proper error message, so I'm going to close this and related issues.
