### ISSUE TITLE
Documentation: typo in google_resource_manager_lien

### ISSUE THREAD

**Issue by howardburgess** [terraform-providers/terraform-provider-google#1897]
Issue https://github.com/terraform-providers/terraform-provider-google/issues/1435 requested Terraform support for [Google project liens](https://cloud.google.com/resource-manager/docs/project-liens), which was added in https://github.com/terraform-providers/terraform-provider-google/pull/1484.

The resource was added in the `google` provider [v1.16.2](https://github.com/terraform-providers/terraform-provider-google/releases/tag/v1.16.2) as `google_resource_manager_lien` but the documentation uses the resource name `google_resourcemanager_lien`, leading to Terraform complaining if the documentation is followed:

    Error: google_resourcemanager_lien.lien: Provider doesn't support resource:
    google_resourcemanager_lien

The documentation needs updating to use the implemented resource name.

Terraform version: v0.11.7
Resource affected: `google_resource_manager_lien` v1.16.2

**Comment by ndmckinley** [comment]
Good news!  It's just a typo in some manually written code which gets merged into the autogenerated stuff.  :)  Took only a second to fix - PR will be generated soon.

**Comment by howardburgess** [comment]
Good to hear. Thanks @ndmckinley :)
