### ISSUE TITLE
data.google_dns_managed_zone prompts an "read" update always

### ISSUE THREAD

**Issue by ramyala** [terraform-providers/terraform-provider-google#1902]
### Terraform Version

Terraform v0.11.8
+ provider.aws v1.32.0
+ provider.github v1.2.1
+ provider.google v1.16.2
+ provider.helm (unversioned)
+ provider.kubernetes v1.2.0
+ provider.local v1.1.0
+ provider.random v2.0.0
+ provider.template v1.0.0
+ provider.tls v1.2.0

### Affected Resource(s)
- google_dns_managed_zone

### Terraform Configuration Files
```hcl
resource "google_project_service" "dns" {
  service = "dns.googleapis.com"
}
data "google_dns_managed_zone" "my_zone" {
  name    = "${local.dns_zone}"
  project = "${var.root_project}"

  depends_on = ["google_project_service.dns"]
}
```

### Debug Output

``` 
$ tf apply
...
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
 <= read (data resources)

Terraform will perform the following actions:

 <= data.google_dns_managed_zone.my_zone
      id:             <computed>
      description:    <computed>
      dns_name:       <computed>
      name:           "my-zone"
      name_servers.#: <computed>
      project:        "root-project"

```

### Expected Behavior

We shouldn't be prompted once the data is read and no changes were detected subsequently. The behavior should be in-line with other data objects.

### Actual Behavior

`tf apply` always prompts to read from `data.google_dns_managed_zone.my_zone`. Thus as a side-effect any dependency on attributes from this data object will be asked to update/recreate.

**Comment by emilymye** [comment]
@ramyala Thanks for submitting this issue! I believe this is a side effect of how `depends_on` works for data sources in Terraform core. See https://github.com/hashicorp/terraform/issues/11806. Unfortunately, that means I don't have an easy answer other than to remove the dependency on the project service object. If you have any other questions, please let me know!
