### ISSUE TITLE
google_service_account_key googleapi: Error 400: Invalid JSON payload received. Unknown name "publicKeyType"

### ISSUE THREAD

**Issue by Place1** [terraform-providers/terraform-provider-google#1909]
Hi

I'm trying to use terraform to get the `google_service_account_key` for the `google_compute_default_service_account` but when I'm getting the following error message `googleapi: Error 400: Invalid JSON payload received. Unknown name "publicKeyType"` when I `terraform apply`.

### Terraform Version
```
Terraform v0.11.8
+ provider.google v1.14.0
+ provider.kubernetes v1.2.0
+ provider.random v2.0.0
```

### Affected Resource(s)
- google_service_account_key

### Terraform Configuration Files
```hcl
data "google_compute_default_service_account" "default" {}

data "google_service_account_key" "key" {
  service_account_id = "${data.google_compute_default_service_account.default.email}"
  public_key_type    = "TYPE_X509_PEM_FILE"
}

resource "kubernetes_secret" "cloudsql_credentials" {
  type = "Opaque"

  metadata {
    name = "cloudsql-instance-credentials"
  }

  data {
    credentials.json = "${base64decode(data.google_service_account_key.key.private_key)}"
  }
}
```

### Debug Output
```
Error: Error refreshing state: 1 error(s) occurred:

* module.production_kubernetes_cluster.data.google_service_account_key.key: 1 error(s) occurred:

* module.production_kubernetes_cluster.data.google_service_account_key.key: data.google_service_account_key.key: Error reading Service Account Key "projects/-/serviceAccounts/<redacted>-compute@developer.gserviceaccount.com": googleapi: Error 400: Invalid JSON payload received. Unknown name "publicKeyType": Cannot bind query parameter. Field 'publicKeyType' could not be found inrequest message., badRequest
```

### Expected Behavior
The `google_service_account_key` should be fetched so that the `.private_key` can be accessed

### Actual Behavior
JSON error

### Steps to Reproduce
1. `terraform apply`

**Comment by Chupaka** [comment]
Can you repeat it with current version (provider.google v1.16.2)?

**Comment by emilymye** [comment]
I'm pretty sure something is wrong with this data source. Shouldn't service account public keys be referred to by specific key id, not an overall service account? I'll look into this.
