### ISSUE TITLE
adding enableLogging to resourceComputeFirewall()

### ISSUE THREAD

**Issue by gkuchta** [terraform-providers/terraform-provider-google#1914]
Hi!

Are there plans for adding `enableLogging` to the `resourceComputeFirewall()` magic module? I know that feature's only available in v0 beta, so I'm curious about plans. I'd opened a PR to include support for it pre-magic module (https://github.com/terraform-providers/terraform-provider-google/pull/1908), but I believe that's now deprecated code. Talk about bad timing on my part!

Cheers,

Garrett

**Comment by emilymye** [comment]
Yup, #1907 just made this a magic-modules-generated resource. It shouldn't be too hard to add this field so I'll go ahead and do it. It's probably fine to close out your other PR, and I'll probably do so if you approve :) Sorry for the extra work!

**Comment by gkuchta** [comment]
@emilymye awesome and thank you! I've closed out my PR, and I'll keep my eyes on the release notes. Cheers :)
