### ISSUE TITLE
FeatureRequest: Add ability to create node pool with preemptible machines.

### ISSUE THREAD

**Issue by lfshr** [terraform-providers/terraform-provider-google#1918]
The ability to create node pools with preemptible machines is currently available via the console. This should be (eventually) reflected in the terraform provider.

### Affected Resource(s)
Please list the resources as a list, for example:
- google_container_cluster
- google_container_node_pool

### Terraform Configuration Files
```hcl
provider "google" {
  project = "project-name"
  region  = "europe-west2"
}

resource "google_container_cluster" "test-cluster" {
  name = "gce-test-cluster"
  zone = "europe-west2-a"
  
  node_pool {
    name               = "default-pool"
    initial_node_count = 3
    preemptible = true
  }
}
```

### Expected Behavior
A cluster should be created with a node_pool that has preemptible machines.

### Important Factoids
This is currently not available via the Google GO SDK. I'm not 100% sure where the issue should go above terraform to get this included. Any help would be appreciated.

**Comment by Chupaka** [comment]
If you cannot do it via gcloud or API - Terraform has nothing to do here.

**Comment by lfshr** [comment]
See OP
> This is currently not available via the Google GO SDK. I'm not 100% sure where the issue should go above terraform to get this included. Any help would be appreciated.

This is here more for "remind me later" purposes, and to try and get the ball rolling on Google's side.

**Comment by danawillow** [comment]
It's in the API here: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig.

**Comment by danawillow** [comment]
Also, here's a fun trick: if you go into the console and try to create a resource, a lot of times there's a link for "Equivalent REST"- that's a great way to figure out how to call something using the API.

**Comment by lfshr** [comment]
Hi @danawillow thanks for the response.

The NodeConfig preemptible flag is already implemented in terraform. The NodePool preemptible flag isn't. You can't specify a NodeConfig block alongside a NodePool block :(

**Comment by lfshr** [comment]
Currently on the console you can spin up a cluster with a NodePool that creates preemptible machines.

**Comment by danawillow** [comment]
Sure you can! https://www.terraform.io/docs/providers/google/r/container_node_pool.html#node_config

**Comment by lfshr** [comment]
I tried this today before opening this. Either Terraform doesn't allow it or the API doesn't allow it. I can confirm tomorrow.

**Comment by lfshr** [comment]
Never mind, I am indeed stupid. Supply the node_config block inside the node_pool block rather than alongside it.

```
provider "google" {
  project = "<project-name>"
  region  = "europe-west2"
}

resource "google_container_cluster" "test-cluster" {
  name = "gce-test-cluster"
  zone = "europe-west2-a"

  node_pool {
    name               = "default-pool"
    initial_node_count = 3

    node_config {
      preemptible = true
    }
  }
}

```
