### ISSUE TITLE
Incorrect zones for google_compute_autoscaler in tfstate

### ISSUE THREAD

**Issue by pst** [terraform-providers/terraform-provider-google#192]
### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- google_compute_autoscaler

### Terraform Configuration Files
https://gist.github.com/pst/aed987feba7b9514a9887783ce975028

### Debug Output
 1. First successful `terraform apply`:
     https://gist.github.com/pst/5d096cd8d720a83b23d81c4e09516aeb
 1. `terraform show` with incorrect state:
     https://gist.github.com/pst/35a110ec5249ad69b6bb7b39ebff812f
 1. `terraform plan` (forcing new autoscaler resources):
      https://gist.github.com/pst/9ab7340f185342fa4106db641faa5596
 1. Second `terraform apply` that fails (not all that interesting because the plan is already wrong):
      https://gist.github.com/pst/00d1839fc5c1e1cc3915d4feb5919c06

### Expected Behavior
Applying above hcl, terraform creates the resources. Re-applying the unchanged hcl, does not change the resources.

### Actual Behavior
Applying above hcl, terraform correctly creates the resources on GCP. Most importantly the `google_compute_instance_group_manager` and `google_compute_autoscaler` resources are correctly distributed across the three zones specified.

However, the `terraform.ftstate` file and `terraform show` claim all `google_compute_autoscaler` resources are in a single zone (see [autoscaler.1](https://gist.github.com/pst/35a110ec5249ad69b6bb7b39ebff812f#file-tf_debug_show_after_first_apply-log-L47) and [autoscaler.2](https://gist.github.com/pst/35a110ec5249ad69b6bb7b39ebff812f#file-tf_debug_show_after_first_apply-log-L62)). Hence a `terraform plan` and `terraform apply` try to assign the correct zone which forces a new resource (see [plan output](https://gist.github.com/pst/9ab7340f185342fa4106db641faa5596#file-tf_debug_plan_after_first_apply-log-L4707:L4730)). This then also fails with a `Error 400` from the API. Optimally the internal state should correctly reflect the reality on GCP and not try to recreate the the resources when the hcl is applied again.

### Steps to Reproduce
 1. `terraform apply`
 1. `terraform show`  # not required to reproduce, just for clarification
 1. `terraform plan`  # not required to reproduce, just for clarification
 1. `terraform apply`

**Comment by rileykarson** [comment]
Hi @pst!

It looks like we scan every `zone` in the `region` when reading autoscalers, in order to accommodate `Import`. GCP allows multiple autoscalers with the same name to exist as long as they have different zones, and as a result we are reading the same one each time; we'll need to update `google_compute_autoscaler` to check if a `zone` is checked in config/state, and use that instead when possible.

In the meantime, you should be able to work around it by appending a the `count.index` to the end of your autoscaler's names so they are all unique within the region, going from;

```hcl
  name   = "auto-scaler"
```

to

```hcl
  name   = "auto-scaler${count.index}"
```

**Comment by pst** [comment]
Thanks for the explanation @rileykarson. The workaround is also fine for me.
