### ISSUE TITLE
Terraform crashes with google provider built from master

### ISSUE THREAD

**Issue by rolandkool** [terraform-providers/terraform-provider-google#1920]
Hi there,

When I build the terraform provider from the master branch and run it against my GKE cluster it crashes. See attached crash.log.
[crash.log](https://github.com/terraform-providers/terraform-provider-google/files/2309595/crash.log)

The exact same .tf file works just fine with 1.16.

**Comment by antoncohen** [comment]
It looks like v1.17.0 got cut from master an hour ago (8 hours after this bug report). v1.17.0 crashes.

**Comment by jgrabenstein** [comment]
Confirming that I see the same issue as @rolandkool with v1.17.0 of the google provider module (`unexpected EOF` with a GKE cluster). Works successfully with v1.16.2

**Comment by ajcrowe** [comment]
Yeah I'm seeing this, specifically when planning is readying the state for a GKE cluster.

**Comment by danawillow** [comment]
Gah, sorry about that all. Fix is out for review now.
