### ISSUE TITLE
Support import for Runtime Config resources

### ISSUE THREAD

**Issue by zombiezen** [terraform-providers/terraform-provider-google#1928]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.11.8
+ provider.google v1.16.2
```

### Affected Resource(s)
- google_runtimeconfig_config
- google_runtimeconfig_variable

### Terraform Configuration Files

```hcl
provider "google" {
  version = "~> 1.15"
}

resource "google_runtimeconfig_config" "default" {
  name = "foo"
}

resource "google_runtimeconfig_variable" "default" {
  name   = "bar"
  parent = "${google_runtimeconfig_config.default}"
  text   = "baz"
}
```

### Expected Behavior

`terraform import google_runtimeconfig_config.default projects/myproject/configs/foo` would import the resource (and similarly for the variable).

### Actual Behavior

The resources are not importable.

### Steps to Reproduce
1. `terraform import google_runtimeconfig_config.default projects/myproject/configs/foo`

**Comment by migibert** [comment]
I'm on it!
