### ISSUE TITLE
Adding a new access_config block to existing instance forces resource re-creation

### ISSUE THREAD

**Issue by diegolima** [terraform-providers/terraform-provider-google#1948]
Hello!

Trying to modify an existing instance that was created having only an internal IP address (and thus no access_config block) to add an external IP afterwards results in terraform wanting to re-create the instance. When using the GCP control panel I'm able to attach an IP address to an existing instance without having to re-create it.

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- google_compute_instance

### Debug Output
```
network_interface.#:                                 "1" => "1"
network_interface.0.access_config.#:                 "0" => "1" (forces new resource)
```

### Expected Behavior
A new access_config block is added to the running instance

### Actual Behavior
Terraform destroys the instance and creates a new one with an external IP address

### Steps to Reproduce
1. `terraform apply`

**Comment by Chupaka** [comment]
Hi. What version of Google Provider plugin?

**Comment by paddycarver** [comment]
In addition, if you could provide [debug logs](https://www.terraform.io/docs/internals/debugging.html), that would be super helpful.

**Comment by Chupaka** [comment]
"If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed." (c) New Issue Template

1.12 is way too old. Have you checked with 1.17?

**Comment by rileykarson** [comment]
This looks like it was resolved a while ago; if you find that's not the case with a newer provider version, please feel free to file a new issue!
