### ISSUE TITLE
google_cloudbuild_trigger should support disabled option

### ISSUE THREAD

**Issue by anshulpatel25** [terraform-providers/terraform-provider-google#1952]
Hello,

`google_cloudbuild_trigger` should support `disabled` option upon trigger creation.

### Terraform Version
```
Terraform v0.11.8
```

### Affected Resource(s)
- google_cloudbuild_trigger

### Terraform Configuration Files
```hcl
provider "google" {
    project = "my-awesome-project"
}

resource "google_cloudbuild_trigger" "trigger" {
    trigger_template {
        branch_name = "master"
        repo_name = "my-awesome-repo"
    }
    build {
        step {
            name = "ubuntu"
            args = "echo Hello World"
        }
    }

    disabled = true
}
```

### Expected Behavior
`disabled` should be supported.

### Actual Behavior

```
Error: google_cloudbuild_trigger.trigger: : invalid or unknown key: disabled
```

### Steps to Reproduce
`terraform plan`

**Comment by rileykarson** [comment]
Done in https://github.com/terraform-providers/terraform-provider-google/pull/2790. This should land in `2.0.0`.
