### ISSUE TITLE
google_compute_vpn_tunnel is always recreated.

### ISSUE THREAD

**Issue by kedare** [terraform-providers/terraform-provider-google#1963]
### Terraform Version
```
Terraform v0.11.8
+ provider.google v1.17.1
```

### Affected Resource(s)
- google_compute_vpn_tunnel

### Terraform Configuration Files
```hcl
resource "google_compute_vpn_tunnel" "gc-euw1-infra-to-hq-1" {
  name          = "gc-infra-to-hq-1"
  peer_ip       = "${var.hq-vpn-ip}"
  shared_secret = "${var.hq-vpn-psk}"
  router        = "${google_compute_router.gc-euw1-infra-router.self_link}"
  ike_version   = 1

  target_vpn_gateway = "${google_compute_vpn_gateway.gc-euw1-infra-vpngw-1.self_link}"
}

resource "google_compute_vpn_tunnel" "gc-euw1-infra-to-hq-2" {
  name          = "gc-infra-to-hq-2"
  peer_ip       = "${var.hq-vpn-ip}"
  shared_secret = "${var.hq-vpn-psk}"
  router        = "${google_compute_router.gc-euw1-infra-router.self_link}"
  ike_version   = 1

  target_vpn_gateway = "${google_compute_vpn_gateway.gc-euw1-infra-vpngw-2.self_link}"
}
```

### Debug Output
https://gist.github.com/kedare/b4220314458d0e18507345e46871cd97

### Panic Output
No panic

### Expected Behavior
Desired state would match

### Actual Behavior
A difference is detected on the state, even after applying the changes, it still doesn't match when running it right after applying it.
When checking with a `terraform state show` of the tunnel, it does match the desired state.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Nothing special, the whole Google Cloud project is managed by Terraform, no external changes are allowed.

### References
Nothing

**Comment by paddycarver** [comment]
This looks like a bug in our resource definition in Magic Modules--I believe we need to set the router field to diffsuppress using `compareSelfLinkOrResourceName`.
