### ISSUE TITLE
ContainerAnalysis API will be enabled on every apply (even when its enabled)

### ISSUE THREAD

**Issue by rtoma** [terraform-providers/terraform-provider-google#1964]
Hi there,

### Terraform Version
```
Terraform v0.11.8
+ provider.google v1.17.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- google_project_services

### Terraform Configuration Files
```hcl
resource "google_project_services" "some-project" {
  project  = "some-project"
  services = [
    "cloudbuild.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "containeranalysis.googleapis.com",                        # <----
    "containerregistry.googleapis.com",
    "logging.googleapis.com",
    "monitoring.googleapis.com",
    "pubsub.googleapis.com",
    "servicemanagement.googleapis.com",
    "storage-api.googleapis.com",
    "storage-component.googleapis.com",
  ]
}
```

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
Enable the API only if its disabled.

### Actual Behavior
The API is being enabled on every apply run even though its already enabled.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
```
# terraform refresh
google_project_services.some-project: Refreshing state... (ID: some-project)

# terraform apply -auto-approve
google_project_services.some-project: Refreshing state... (ID: some-project)
google_project_services.some-project: Modifying... (ID: some-project)
  services.#:          "9" => "10"
  services.1109577435: "cloudbuild.googleapis.com" => "cloudbuild.googleapis.com"
  services.133405307:  "storage-component.googleapis.com" => "storage-component.googleapis.com"
  services.1712537408: "containerregistry.googleapis.com" => "containerregistry.googleapis.com"
  services.2117420113: "pubsub.googleapis.com" => "pubsub.googleapis.com"
  services.2254174451: "" => "containeranalysis.googleapis.com"            # <----
  services.2471815660: "servicemanagement.googleapis.com" => "servicemanagement.googleapis.com"
  services.3237295688: "monitoring.googleapis.com" => "monitoring.googleapis.com"
  services.3355193353: "logging.googleapis.com" => "logging.googleapis.com"
  services.3644083179: "cloudresourcemanager.googleapis.com" => "cloudresourcemanager.googleapis.com"
  services.3875785048: "storage-api.googleapis.com" => "storage-api.googleapis.com"
google_project_services.some-project: Modifications complete after 2s (ID: some-project)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Important Factoids
n/a

### References
The containeranalysis API is part of an ignore list added in https://github.com/terraform-providers/terraform-provider-google/commit/d03f802be20c4a19c8bf6f1c2945cff0c06676d7#diff-99440dd2bc1d1e0f9d7fc3be16bdc37dR37 - maybe the reasons for adding it, are not valid anymore?

**Comment by paddycarver** [comment]
The ignore list is populated with services that can't be manipulated from Terraform--if you remove it from your config, is it not enabled for you by default?

**Comment by rtoma** [comment]
Hi Paddy,

No, its not enabled by default. Maybe things have changed?

What I have seen: when you enable the Container Registry API the Container Analysis API is not automatically enabled. The Container Analysis API needs to be explicitly enabled, which will only work if you've whitelisted your account by joining https://groups.google.com/forum/#!forum/containeranalysis-users. Disabling the API does not seem to work (or may take a very long time).

Feel like removing the API from the ignorelist? Looking forward to your ideas.

**Comment by rtoma** [comment]
@paddycarver any additional information I can provide? If you approve I can submit a PR to remove that one line.

**Comment by danawillow** [comment]
Container Analysis is enabled automatically if you enable the Binary Authorization API. What's your use case for using it independently?

**Comment by rtoma** [comment]
Hi Dana, I did not know that. Thanks.

To answer your question: we'd like to enable the API's we use and nothing more. We use Container Analysis for its vulnerability scanning feature. Binary Authorization we do not use yet. That's why we want to control the Analysis API.

**Comment by danawillow** [comment]
Hmm, thanks! I'll follow up inside of Google and see if I can find anything out.
