### ISSUE TITLE
google_project_service does not wait for API to be enabled

### ISSUE THREAD

**Issue by aaron-trout** [terraform-providers/terraform-provider-google#1965]
Terraform is not waiting for Kubernetes API to be enabled before continuing. In my case, I am trying to create a project, enable the container API with the `google_project_service` resource *AND* create a GKE cluster all in a single `terraform apply`. It seems like the step for enabling the Kubernetes API does not wait until it has finished and causes the cluster creation to fail. 
### Terraform Version
```
Terraform v0.11.8
+ provider.google v1.17.1
```

### Affected Resource(s)

- google_project_service

### Terraform Configuration Files
```hcl
resource "google_project_service" "gke-api" {
  project = "${google_project.banana.id}"
  service = "container.googleapis.com"
}

resource "google_container_cluster" "my-cluster" {
  ...
  ...
}
```

### Expected Behavior
GKE API gets enabled, terraform waits for it to be ready and then continues to perform further actions.

### Actual Behavior
Makes an API call to enable the API but does not wait until complete. Terraform apply fails, but if I just wait a few minutes and then run it again it works because the GKE API is now properly enabled.

```
google_project_service.gke-api: Creating...
  disable_on_destroy: "" => "true"
  project:            "" => "my-project"
  service:            "" => "container.googleapis.com"
google_project_service.gke-api: Still creating... (10s elapsed)
google_project_service.gke-api: Creation complete after 13s (ID: nm-control-plane-orange/container.googleapis.com)

Error: Error applying plan:

1 error(s) occurred:

* google_container_cluster.my-cluster: 1 error(s) occurred:

* google_container_cluster.my-cluster: googleapi: Error 403: EXTERNAL: Kubernetes Engine API is not enabled for this project. Please ensure it is enabled in Google Cloud Console and try again: visit https://console.cloud.google.com/apis/api/container.googleapis.com/overview?project=my-cluster to do so., forbidden
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Easiest way to reproduce is make a brand new project and try to create a GKE cluster. Make sure you don't click on kubernetes engine in the web console because this will enable the API!

**Comment by paddycarver** [comment]
Do you have a [debug log](https://www.terraform.io/docs/internals/debugging.html) for this?

The reason I ask is because [we are](https://github.com/terraform-providers/terraform-provider-google/blob/v1.17.1/google/resource_google_project_services.go#L281-L286) waiting for a service to confirm it's enabled before we move on, and so it's very bizarre that this is happening, and seems to point to an upstream bug. But before I say it's an upstream problem, I want to verify the code is actually running the way we think it is.

**Comment by Chupaka** [comment]
Don't we need some `depends_on = ["google_project_service.gke-api"]` on `my-cluster` resource?..

**Comment by aaron-trout** [comment]
@paddycarver ok so I tried to make a standalone terraform file to reproduce this and ran it this morning with debug logs...... it worked 😠 

I am also using shared VPC in my actual config, maybe that has something to do with it? I'll have to do some more digging and get back to you...

**Comment by aaron-trout** [comment]
Closing this, think it was a red herring and I've not had it happen again even when deleting and recreating everything.
