### ISSUE TITLE
google_compute_vpn_tunnel doesn't support the selection of routing options

### ISSUE THREAD

**Issue by mazzy89** [terraform-providers/terraform-provider-google#1966]
The resource `google_compute_vpn_tunnel` doesn't support the selection of the routing options. Why is not possible to choice wether option is dynamic, route or policy based?

### Terraform Version
Terraform v0.11.8

### Affected Resource(s)
- google_compute_vpn_tunnel

**Comment by paddycarver** [comment]
I'm sorry, I can't seem to find any docs that talk about the features you're talking about. Can you link me to some documentation for what you're looking for?

**Comment by paddycarver** [comment]
I'm not an expert in the domain, but I believe these options are already supported, and implicitly chosen based on which fields you populate.

For dynamic, you'd want to populate the [`router`](https://www.terraform.io/docs/providers/google/r/compute_vpn_tunnel.html#router) field.

For route based, I believe you'd want to populate the [`remote_traffic_selector`](https://www.terraform.io/docs/providers/google/r/compute_vpn_tunnel.html#remote_traffic_selector) field.

For policy based, I believe you'd want to populate the [`remote_traffic_selector`](https://www.terraform.io/docs/providers/google/r/compute_vpn_tunnel.html#remote_traffic_selector) field _and_ the [`local_traffic_selector`](https://www.terraform.io/docs/providers/google/r/compute_vpn_tunnel.html#local_traffic_selector) field.

**Comment by mazzy89** [comment]
I'll try that and I'll let you know.

**Comment by mazzy89** [comment]
Unfortunately by using the following resource doesn't create the expected result:

```
resource "google_compute_vpn_tunnel" "this" {
  project = "${var.project}"

  name = "${var.vpn_name}"

  ike_version   = "1"
  peer_ip       = "${var.vpn_gateway}"
  shared_secret = "${var.shared_secret}"

  target_vpn_gateway = "${google_compute_vpn_gateway.this.self_link}"

  remote_traffic_selector = ["10.60.0.0/16"]

  depends_on = [
    "google_compute_forwarding_rule.this",
  ]
}
```

The VPN is created with `policy-based` routing option

**Comment by mazzy89** [comment]
Closing this issue because it is possible to have as routing options `Route based`. It is enough to define `remote_traffic_selector ` and `local_traffic_selector ` as `[0.0.0.0/0]` and then create a `google_compute_route` resource
