### ISSUE TITLE
Proposal: deprecate managed instance groups' instance_template field in favor of versions

### ISSUE THREAD

**Issue by paddycarver** [terraform-providers/terraform-provider-google#1971]
Right now, we have an `instance_template` field on `google_compute_instance_group_manager`, to specify the template you want to use with the instance group.

However, we also have a `version` sub-block that allows for canary deploys, and more.

It would be fine to have both of them, except the IGM API fills in a default `version` if you don't specify one, meaning we need to make the blocks optional and computed. Which limits our ability to do things like detect drift, and complicates the code for rolling deploys significantly.

This issue is meant as a way to just gather feedback and hear opinions on whether we should deprecate the `instance_template` field, and guide everyone over to using `version` for 2.0.0 of the provider.

I'd love to hear more feedback from other maintainers, as well as from users.

[EDIT] Versions are a beta feature. This is predicated on them achieving GA status prior to 2.0.0; I don't want to push everyone towards a beta API if we can avoid it. So assume for the moment this will only happen if the changes make it to GA in time.

**Comment by migibert** [comment]
When I added version support, I chose to keep template because of backward compatibility but I am pretty sure we should only support versions as soon as it becomes GA.
It would unify the way we manage instances and let user learn only one way to work with Managed Instance Groups without regarding if the use case is canary release, A/B testing or rolling release.

**Comment by rileykarson** [comment]
It looks like the [Updating Managed Instance Groups documentation](https://cloud.google.com/compute/docs/instance-groups/updating-managed-instance-groups#relationship_between_versions_and_instancetemplate_properties_for_a_managed_instance_group) suggests migrating to use `version` as well. At first glance, I'm in support of moving Terraform entirely over as soon as that becomes an option for us. I'd like it if we provided examples in the docs for a few common use cases as well.

**Comment by paddycarver** [comment]
So our current plan for this is that we're going to have the GA version of the provider use instance_template and update_strategy, and a new beta provider will use versions and rolling_update_policy. instance_template and update_strategy will be unsupported on the beta provider, and versions and rolling_update_policy will be deprecated on the GA provider. Because they never worked as intended _anyways_, we'll leave them as they are until 2.0.0, when the fields will be removed and the overall code simplified.
