### ISSUE TITLE
google_cloudbuild_trigger can't add Dockerfile Directory Path

### ISSUE THREAD

**Issue by 35blaze** [terraform-providers/terraform-provider-google#1978]
I want to build a Trigger using a Dockerfile but when I define the Dockerfile Direcotry Path it's not applied to the Trigger Configuration and Terraform gives no error message.

### Terraform Version
`Terraform v0.11.8`

### Affected Resource
- google_cloudbuild_trigger
`trigger_template block`: `dir` - (Optional) Directory, relative to the source root, in which to run the build. This must be a relative path. If a step's dir is specified and is an absolute path, this value is ignored for that step's execution.

### Terraform Configuration Files
```hcl
resource "google_cloudbuild_trigger" "build_trigger" {
  project     = "${var.project_id}"

  trigger_template {
    branch_name = "master"
    project     = "${var.project_id}"
    repo_name   = "${var.repo}"
    dir         = "${var.dockerfile_dir}"
  }

  build {
    images = ["${var.image_prefix}${var.image_name}:latest"]

    step {
      name = "gcr.io/cloud-builders/docker"
      args = "build -t ${var.image_prefix}${var.image_name}:latest -f Dockerfile ."
    }
  }
}
```

### Debug Output
Cloud Build Trigger fails.

### Expected Behavior
The Dockerfile Directory Path should be added to the Trigger Configuration. Docker command should be:
```hcl
cd docker/folderA/folderB/ && docker build \
    -t eu.gcr.io/repo/image_name:latest \
    -f Dockerfile \
    .
```

### Actual Behavior
The Dockerfile Directory Path stays empty in the Trigger Configuration and `terraform apply` runs without errors. Docker command is:
```hcl
docker build \
    -t eu.gcr.io/repo/image_name:latest \
    -f Dockerfile \
    .
```

### Steps to Reproduce
1. `terraform apply`
2. Perform `Trigger run`

**Comment by danawillow** [comment]
Hey @35blaze, debug output in this case means output from debug logs as described at https://www.terraform.io/docs/internals/debugging.html. Mind forwarding those along in a gist? That would be a big help.

**Comment by rileykarson** [comment]
Closing due to age and lack of response- feel free to reopen if you're still encountering this.
