### ISSUE TITLE
 project_id validator is too restrictive: rejects domain-scoped or long project IDs.

### ISSUE THREAD

**Issue by diekmann** [terraform-providers/terraform-provider-google#1986]
### Terraform Version
 * Independent of Terraform version, I'm using v0.11.6 right now.
 * terraform-provider-google >= 1.13.0

### Affected Resource(s)
- google_project

### Terraform Configuration Files
```hcl
resource "google_project" "my_test_project" {
  project_id      = "example.com:foobar-terraform-test-foo"
  name            = "foobar-terraform-test-foo"
}

```

### Expected Behavior
Terraform accepts the `project_id` without any trouble.

### Actual Behavior
Terraform refuses to load the config with my `project_id`:
```
Error: google_project.my_test_project: "example.com:foobar-terraform-test-foo" project_id must be 6 to 30 with lowercase letters, digits, hyphens and start with a letter. Trailing hyphens are prohibited.
```

This breaks existing configurations which use a domain-scoped project IDs or very long project IDs.

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
terraform-provider-google introduces in 1.13.0 "project: Added name and project_id plan-time validations".

The regex is
`ProjectIDRegex   = "^[a-z][a-z0-9-]{4,28}[a-z0-9]$"`.
This regex did not change since 1.13.0 and is still the same in the current [github HEAD](https://github.com/terraform-providers/terraform-provider-google/blob/7e82a982e403b0cb0fa82c232ed5cf90af60b933/google/validation.go#L54).

### References
Related change which fixes a similar issue: [Allow other forms of project names to be matched.](https://github.com/terraform-providers/terraform-provider-google/pull/1865).

Probably we should get rid of `var ProjectIDRegex` completely and only use `const ProjectRegex` (defined in the same file) everywhere? In the code we have, `ProjectRegex` is the project ID and not the project name.

**Comment by danawillow** [comment]
This will be fixed by #1878
