### ISSUE TITLE
New data source : google_compute_instance

### ISSUE THREAD

**Issue by tpoindessous** [terraform-providers/terraform-provider-google#1989]
Hi 

I can't find how to access informations (internal IP for example) about a compute instance.

I don't know if I'm not looking in the right direction or if a google_compute_instance datasource is missing.

Thanks in advance !

**Comment by danawillow** [comment]
This is already in progress in #1906

**Comment by tpoindessous** [comment]
Thanks !


Le jeu. 6 sept. 2018 à 00:37, Dana Hoffman <notifications@github.com> a
écrit :

**Comment by paddycarver** [comment]
#1906 was merged, so I'm going to close this out now.
