### ISSUE TITLE
IPv6 connection to container.googleapis.com being preferred even when IPv6 not available on local network

### ISSUE THREAD

**Issue by magic7s** [terraform-providers/terraform-provider-google#2000]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.8
+ provider.aws v1.31.0
+ provider.google v1.16.2
+ provider.http v1.0.1
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0

### Affected Resource(s)

resource "google_container_cluster"

### Terraform Configuration Files
default

### Debug Output
```
Error: Error refreshing state: 1 error(s) occurred:

* google_container_cluster.primary: 1 error(s) occurred:

* google_container_cluster.primary: google_container_cluster.primary: Error reading Container Cluster "gke-hybrid-cloud": Get https://container.googleapis.com/v1beta1/projects/k8s-hybrid-cloud/locations/us-west1-a/clusters/gke-hybrid-cloud?alt=json: dial tcp [2800:3f0:4001:80a::200a]:443: connect: no route to host

```
### Expected Behavior

Use IPv4 when IPv6 not enabled.

### Actual Behavior

Attempts to connect to container.googleapis.com via AAAA IPv6 address.

### Steps to Reproduce

Issue to appearing at random. Using https://test-ipv6.com I can see that my DNS server supports IPv6, but my local network does not. 

Might reproduce:
1. ensure DNS can resolve ipv6 address `dig container.googleapis.com aaaa`
2. Disable ipv6 on local network (mac: `networksetup -setv6off Wi-Fi`)
3. `terraform plan`

**Comment by danawillow** [comment]
This doesn't seem to me like something we can really correct on our end, though I could be wrong. We connect to GKE by using the client libraries that GCP gives us, so that's likely where the fix would need to be made. If you have debug logs though (https://www.terraform.io/docs/internals/debugging.html), that would help give information that we could provide to that team for debugging.

**Comment by rileykarson** [comment]
Closing this as there's not really anything we can do in the provider.

If you're encountering this still, please feel free to file again. We may be able to do something with debug logs provided, but without those it's unlikely that we'll be able to reproduce this to even attempt a fix.
