### ISSUE TITLE
A google_project_iam_binding resource with an empty members list should be stored in state

### ISSUE THREAD

**Issue by sudoforge** [terraform-providers/terraform-provider-google#2007]
Summary:

I periodically need to add a project-level binding for users, which is later removed. To facilitate doing this easily, I keep a `google_project_iam_binding` resource around and simply add/remove IAM users from the `members` list as needed.

When the `members` list has at least one item, the resource is persisted in state and the upstream API handles it appropriately. When the `members` list is empty, however, the binding is deleted by the upstream API (as expected), and the resource is removed from Terraform's state (not expected). This causes each subsequent plan/apply to attempt to create the resource - causing Terraform to submit the API request, which in turn is treated as a no-op by GCP, which in turn results in nothing being saved to Terraform's state and causing this whole endless-cycle-of-creation-on-every-plan-or-apply.

### Terraform Version

```
λ terraform -v
Terraform v0.11.8
+ provider.google v1.16.0
```

### Affected Resource(s)

- google_project_iam_binding

### Terraform Configuration Files

I've included the relevant code below.

```hcl
resource "google_project_iam_binding" "role__container_developer" {
  role = "roles/container.developer"

  members = [
    # AN EMPTY LIST
  ]
}
```

### Debug Output

There's nothing particularly useful shown in the debug log, and lots of private information to redact, so I'm choosing not to include this publicly. If it is needed in order to determine the issue, I can provide it privately.

### Expected Behavior

Given the above resource block, the expected behavior is... well, nothing. Terraform shouldn't do anything with that resource block, since a) it does not exist in state, so we don't need to remove anything from upstream; and b) upstream performs a no-op when this request is submitted.

I suppose this gets tricky when a user has a valid binding in their GCP project and creates the Terraform resource for the first time without importing it. The expected behavior may be to clear out the GCP project's binding, which a no-op would obviously not do.

Perhaps the proper solution here is to store the resource with the empty `members` list in Terraform's state, so that it can be tracked appropriately.

### Actual Behavior

```
λ gcp projects get-iam-policy myproject --format=json | jq -r '.bindings[] | select(.role | contains("container.developer")) | .members[]'
(no ouput)


λ tf state show module.myproject.google_project_iam_binding.role__container_developer
(no output)


λ tf plan -target module.myproject.google_project_iam_binding.role__container_developer
Acquiring state lock. This may take a few moments...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + module.myproject.google_project_iam_binding.role__container_developer
      id:   <computed>
      etag: <computed>
      role: "roles/container.developer"


Plan: 1 to add, 0 to change, 0 to destroy.


λ tf apply -auto-approve
<output redacted for brevity>


λ tf state show module.myproject.google_project_iam_binding.role__container_developer
(no output)


λ tf plan -target module.myproject.google_project_iam_binding.role__container_developer
Acquiring state lock. This may take a few moments...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + module.myproject.google_project_iam_binding.role__container_developer
      id:   <computed>
      etag: <computed>
      role: "roles/container.developer"


Plan: 1 to add, 0 to change, 0 to destroy.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. With the above resource block, run `terraform apply`.
2. View the output. Type `yes` and perform the apply. Note that the resource is "created" successfully.
3. Check out the bug/issue:
    3.1. Run `terraform state {resource_path}` and note that there is nothing stored in state.
    3.2. Run `terraform plan` or `terraform apply` and note that Terraform wants to create the resource again.

### Important Factoids

N/A

### References

N/A

**Comment by evralston** [comment]
The same behavior exists with empty `members` list for `google_storage_bucket_iam_binding`, so the solution probably needs to be duplicated to all the various policy/binding/member resources.

**Comment by paddycarver** [comment]
We use a code-level abstraction to share code amongst all of them, so any solution we implement will be mirrored across all of them. :)
