### ISSUE TITLE
Recreation of subnetwork fails

### ISSUE THREAD

**Issue by dbadola** [terraform-providers/terraform-provider-google#2011]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

terraform -v
Terraform v0.11.8
+ provider.google v1.17.1

### Affected Resource(s)

google_compute_subnetwork

### Terraform Configuration Files

```tf
provider "google" {
  credentials = "${var.credentials}"
  project     = "${var.project-id}"
  region      = "${var.region}"
}

resource "google_compute_network" "gcp-vpc" {
  name                    = "${var.vpc-name}"
  auto_create_subnetworks = "false"
  routing_mode = "REGIONAL"
}

resource "google_compute_subnetwork" "subnetwork-southeast-2" {
   name          = "${var.subnetwork-southeast1}"
   ip_cidr_range = "${var.vpc-cidr}"
   region        = "${var.region}"
   network       = "${google_compute_network.gcp-vpc.id}"
}
```

### Panic Output

```
Terraform will perform the following actions:

  - google_compute_subnetwork.subnetwork-southeast-1

  + google_compute_subnetwork.subnetwork-southeast-2
      id:                   <computed>
      creation_timestamp:   <computed>
      fingerprint:          <computed>
      gateway_address:      <computed>
      ip_cidr_range:        "192.168.0.0/24"
      name:                 "subnetwork-southeast1"
      network:              "gcp-vpc"
      project:              <computed>
      region:               "asia-southeast1"
      secondary_ip_range.#: <computed>
      self_link:            <computed>


Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_compute_subnetwork.subnetwork-southeast-1: Destroying... (ID: asia-southeast1/subnetwork-southeast1)
google_compute_subnetwork.subnetwork-southeast-2: Creating...
  creation_timestamp:   "" => "<computed>"
  fingerprint:          "" => "<computed>"
  gateway_address:      "" => "<computed>"
  ip_cidr_range:        "" => "192.168.0.0/24"
  name:                 "" => "subnetwork-southeast1"
  network:              "" => "gcp-vpc"
  project:              "" => "<computed>"
  region:               "" => "asia-southeast1"
  secondary_ip_range.#: "" => "<computed>"
  self_link:            "" => "<computed>"
google_compute_subnetwork.subnetwork-southeast-1: Still destroying... (ID: asia-southeast1/subnetwork-southeast1, 10s elapsed)
google_compute_subnetwork.subnetwork-southeast-1: Still destroying... (ID: asia-southeast1/subnetwork-southeast1, 20s elapsed)
google_compute_subnetwork.subnetwork-southeast-1: Destruction complete after 26s

Error: Error applying plan:

1 error(s) occurred:

* google_compute_subnetwork.subnetwork-southeast-2: 1 error(s) occurred:

* google_compute_subnetwork.subnetwork-southeast-2: Error creating Subnetwork: googleapi: Error 409: The resource 'projects/core-1-190918/regions/asia-southeast1/subnetworks/subnetwork-southeast1' already exists, alreadyExists

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
### Expected Behavior

I have created a subnetwork "subnetwork-southeast-1"  in side the vpc  once created I tried to change subnetwork to  "subnetwork-southeast-2". So it should delete the existing subnetwork "subnetwork-southeast-1" and create the new one  "subnetwork-southeast-2" without any error

### Actual Behavior

In Actual, It's deleting the  "subnetwork-southeast-1" but not able to create "subnetwork-southeast-2" as gives bellow error

" google_compute_subnetwork.subnetwork-southeast-2: Error creating Subnetwork: googleapi: Error 409: The resource 'projects/core-1-190918/regions/asia-southeast1/subnetworks/subnetwork-southeast1' already exists, alreadyExists"

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ndmckinley** [comment]
This will work if you change the `name` of the new subnetwork, but as-is, you're asking for a delete and immediate recreation of what GCP thinks of as an identical resource.  This won't work, unfortunately - it's a limitation of the GCP networking APIs.  Does changing the `name` of the resource meet your needs?

**Comment by dbadola** [comment]
@ndmckinley  Sorry But i don't understand your reply.  Let me explain my need.

Let's say we have deployed a subnetwork with "subnet1" name.  Now the requirement is to change the name to "new-subnet1" name normally this will delete the subnetwork and recreate the subnetwork with "new-subnet1" name

Changing the name only will result in above error

**Comment by Chupaka** [comment]
```
  + google_compute_subnetwork.subnetwork-southeast-2
      <...>
      name:                 "subnetwork-southeast1"
```
Looks like you're not changing the name, it's still "southeast1"

**Comment by dbadola** [comment]
@Chupaka  sorry for the confusion I am talking about "google_compute_subnetwork" name.

not the subnetwork name


  - google_compute_subnetwork.**subnetwork-southeast-1**

  + google_compute_subnetwork.**subnetwork-southeast-2**
      id:                   <computed>
      creation_timestamp:   <computed>
      fingerprint:          <computed>
      gateway_address:      <computed>
      ip_cidr_range:        "192.168.0.0/24"
      name:                 "subnetwork-southeast1"

**Comment by Chupaka** [comment]
Then @ndmckinley already answered: change the name of subnetwork, not the name of terraform resource.

**Comment by ndmckinley** [comment]
Yep, GCP doesn't know anything about the terraform resource name - as far as GCP is concerned you are destroying and recreating the exact same resource, which it doesn't support.  I'm going to go ahead and close the issue since `terraform state mv` accomplishes your objective.
