### ISSUE TITLE
Add encryption configuration block to google_bigquery_table to support CMEK

### ISSUE THREAD

**Issue by jasper-smith** [terraform-providers/terraform-provider-google#2014]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for specifying table encryption configuration to support creating tables encrypted using customer managed encryption keys ([CMEK](https://cloud.google.com/bigquery/docs/customer-managed-encryption))

### New or Affected Resource(s)

* google_bigquery_table

### Potential Terraform Configuration

```tf
resource "google_bigquery_table" "default" {
  dataset_id = "${google_bigquery_dataset.default.dataset_id}"
  table_id   = "bar"

  time_partitioning {
    type = "DAY"
  }

  labels {
    env = "default"
  }

  schema = "${file("schema.json")}"

  encryption_config {
     kms_key_name = "projects/[PROJECT_ID]/locations/[LOCATION]/keyRings/[KEYRING]/cryptoKeys/[KEY]"
  }
}
```

**Comment by ndmckinley** [comment]
I've been working on this, but there's some kind of issue with bigquery tables and org policies when it comes to making this work.  I'm investigating.

**Comment by ndmckinley** [comment]
Cool, they're going to fix the issue internally.  In the meantime, a retry loop solves our issue.

**Comment by frankfarrell** [comment]
Hi, this would be really useful. Has there been any progress made on it?

**Comment by MartinNowak** [comment]
A workaround that was feasible to me was to set [`default_encryption_configuration`](https://www.terraform.io/docs/providers/google/r/bigquery_dataset.html#default_encryption_configuration) on the dataset-level.

**Comment by anubbhavm** [comment]
Hi, just checking if there's been any progress on this?
