### ISSUE TITLE
GKE cluster should support auto-repair management

### ISSUE THREAD

**Issue by ramyala** [terraform-providers/terraform-provider-google#2025]
### Terraform Version
v0.11.8

### Affected Resource(s)
Please list the resources as a list, for example:
- google_container_cluster

There is no way to configure `auto-repair` for default node pools which go along the google_container_cluster. This option is available on GKE and also under management policy for google_container_node_pool.

**Comment by rileykarson** [comment]
This is possible, but not while using the default `node_config` block for the default node pool. If you configure the default node pool and then interact with it using a `google_container_node_pool` resource, this will work. The same is true of the GKE API.

Using the default node pool with Terraform isn't recommended. Instead, using https://www.terraform.io/docs/providers/google/r/container_cluster.html#remove_default_node_pool and creating explicit `google_container_node_pool` is recommended.
