### ISSUE TITLE
Add disk labels to google_compute_instance_template

### ISSUE THREAD

**Issue by andyhky** [terraform-providers/terraform-provider-google#2026]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.7
    provider.google v1.17.1

### Description

Requesting that google_compute_instance_template gets supports for disk labels. Support is present in the Compute API  already.

### New or Affected Resource(s)

* google_compute_instance_template

### Potential Terraform Configuration
https://www.terraform.io/docs/providers/google/r/compute_instance_template.html

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_instance_template" "foo" {
  name_prefix        = "foo"
  ###....
  disk { 
  	boot = true
  	auto_delete = true
  	labels = {
	    cost-center = "marketing",
	    env = "production"
	}
  }
###...
}

```

### References

* https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates/insert
(properties.disks[].initializeParams.labels)

**Comment by marcboudreau** [comment]
I've created a PR (#3766) to address this issue.

**Comment by chrisst** [comment]
fixed by https://github.com/terraform-providers/terraform-provider-google/pull/3766
