### ISSUE TITLE
Add network field to google_cloudfunction_function

### ISSUE THREAD

**Issue by rojopolis** [terraform-providers/terraform-provider-google#2033]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Old title: Add arguments for google_cloudfunction_function resource

The google_cloudfunction_function resource is missing several important arguments that are available in the API:
* ~~runtime~~ https://github.com/terraform-providers/terraform-provider-google/issues/1857
* ~~environmentVariables~~ #1830 
* network

### New or Affected Resource(s)

* google_cloudfunction_function

### Potential Terraform Configuration

```tf
resource "google_cloudfunctions_function" "function" {
  name                  = "function-test"
  description           = "My function"
  available_memory_mb   = 128
  source_archive_bucket = "${google_storage_bucket.bucket.name}"
  source_archive_object = "${google_storage_bucket_object.archive.name}"
  trigger_http          = true
  timeout               = 60
  entry_point           = "helloGET"
  labels {
    my-label = "my-label-value"
  }
  runtime = "python3.7"
  environment_variables {
    MY_VAR_1 = value
    MY_VAR_2 = different_value
  }
  network = "${google_compute_network.my-network.self_link"}"
}
```

### References

* https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions

**Comment by rileykarson** [comment]
`runtime` was added as part of https://github.com/terraform-providers/terraform-provider-google/issues/1857. I'm editing the issue body to reflect that, + editing the title to only mention `network`.

**Comment by megan07** [comment]
Hi @rojopolis !

Thank you for opening this issue.  As noted in the API docs for Cloud Functions, the `network` field will be replaced by `vpcConnector`.  I believe this has already happened, as I am unable to set the `network` field using the console, the API, or gcloud.  `vpcConnector` has been added in #4189 .  Would you be able to take a look and see if that works for you?
Since this functionality appears to be supported I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!
