### ISSUE TITLE
Add `force_destroy` field for BigQuery dataset

### ISSUE THREAD

**Issue by ocervell** [terraform-providers/terraform-provider-google#2050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, we have to write our own custom script to essentially empty bigquery tables before deleting the dataset.

The shell script looks like:
```
PROJECT_ID=$1
DATASET_NAME=$2
for i in $(bq ls $PROJECT_ID:$DATASET_NAME | sed 1,2d | awk "{print \$1}");
do
  bq rm -ft $PROJECT_ID:$DATASET_NAME.$i;
done
```

and the resource definition:

```
# BigQuery dataset
resource "google_bigquery_dataset" "dataset" {
  count      = "${local.destination_type == "bigquery" ? 1 : 0}"
  dataset_id = "${local.destination_name}"
  project    = "${local.destination_project}"

  # Delete all tables in dataset on destroy.
  # This is required because a dataset cannot be deleted if it contains any data.
  provisioner "local-exec" {
    when    = "destroy"
    command = "sh ${path.module}/scripts/delete-bq-tables.sh ${local.destination_project} ${local.destination_name}"
  }

  depends_on = [
    "google_project_service.enable_destination_api",
  ]
}
```

Similarly to the `google_storage_bucket` resource, we should have a `force_destroy` flag that we can set to delete all tables on destroy.

### New or Affected Resource(s)

* google_bigquery_dataset

### Potential Terraform Configuration

```tf
resource "google_bigquery_dataset" "dataset" {
  dataset_id = "${var.dataset_id}"
  project    = "${var.project_id}"
  force_destroy = true
}
```

**Comment by rileykarson** [comment]
Fixed by https://github.com/terraform-providers/terraform-provider-google/pull/2986, `delete_contents_on_destroy` is available in `2.0.0`.
