### ISSUE TITLE
Replace examples using element() syntax with [] syntax

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#2056]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Reported internally: "If you use element() for resources using the count meta-parameter and change the count, ALL instances of that resource may be modified instead of just the instances added or removed. Use [] indexing instead. I didn't realize this would happen, and there are a few places in the Google provider documentation that use element() unnecessarily, eg https://www.terraform.io/docs/providers/google/r/sql_database_instance.html"

**Comment by paddycarver** [comment]
:ship: :rocket: :writing_hand: :memo: :tada: :sparkles:

(I can't find any instances of this with a quick grep, so I'm gonna say we did it.)
