### ISSUE TITLE
Support setting metadata for Dataproc cluster nodes

### ISSUE THREAD

**Issue by qvallance** [terraform-providers/terraform-provider-google#2058]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Most Dataproc [initialization action scripts](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions) leverage metadata keys to allow users to set variables.  An example from the [datalab.sh](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/datalab/datalab.sh) initialization action script, to install additional spark packages:
`readonly SPARK_PACKAGES="$(/usr/share/google/get_metadata_value attributes/spark-packages || true)"` 

### New or Affected Resource(s)

* google_dataproc_cluster

### Potential Terraform Configuration

```tf
    cluster_config {
        master_config {
            num_instances     = 1
            machine_type      = "n1-standard-1"
            metadata {
              foo = "bar"
           }
        }
        worker_config {
            num_instances     = 2
            machine_type      = "n1-standard-1"
            metadata {
              foo = "bar"
           }
        }
```

**Comment by paddycarver** [comment]
I believe this has been implemented and shipped, so I'm going to close this issue out. If you still are having trouble with this, please feel free to open a new issue.
