### ISSUE TITLE
Data source for IP ranges of Google APIs and services (_spf.google.com)

### ISSUE THREAD

**Issue by qvallance** [terraform-providers/terraform-provider-google#2059]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There is an existing data source ([`google_netblock_ip_ranges`](https://www.terraform.io/docs/providers/google/d/datasource_google_netblock_ip_ranges.html)) for looking up the Compute Engine IP ranges ([`_cloud-netblocks.googleusercontent.com`](https://cloud.google.com/compute/docs/faq#where_can_i_find_product_name_short_ip_ranges)). 
  Would like to either update this data source or add a new one to lookup the public IP ranges used for Google APIs and services, including *.googleapis.com and gcr.io ([`_spf.google.com`](https://cloud.google.com/vpc/docs/configure-private-google-access#dns_resolution)).

This would address the following use-case:
1. VMs only have private IP addresses
2. BGP default route to on-prem VPN gateway
3. Private Google Access is enabled for VPC
4. Need to create custom routes to direct traffic for Google APIs and services to the [`default internet gateway`](https://cloud.google.com/vpc/docs/routes#routingpacketsinternet)

### New or Affected Resource(s)

* `google_service_ip_ranges` (new)
or
* `google_netblock_ip_ranges` (update)

### Potential Terraform Configuration

```tf
data "google_service_ip_ranges" "default" {}

resource "google_compute_route" "google_services" {
  count       = "${length(data.google_netblock_ip_ranges.default.cidr_blocks_ipv4)}
  name        = "google-services-${count.index}"
  dest_range  = "${data.google_netblock_ip_ranges.default.cidr_blocks_ipv4[count.index]}"
  network     = "vpc-net"
  next_hop_gateway = "default-internet-gateway"
  priority    = 100
}
```

or 

```tf
data "google_netblock_ip_ranges" "services" {
  netblocks = "services"  # options: services, compute
}

resource "google_compute_route" "google_services" {
  count       = "${length(data.google_netblock_ip_ranges.services.cidr_blocks_ipv4)}
  name        = "google-services-${count.index}"
  dest_range  = "${data.google_netblock_ip_ranges.services.cidr_blocks_ipv4[count.index]}"
  network     = "vpc-net"
  next_hop_gateway = "default-internet-gateway"
  priority    = 100
}
```

**Comment by megan07** [comment]
Thanks @qvallance for opening this issue. It's been closed with #4121 and will be released shortly.
