### ISSUE TITLE
Add runtime support to cloud functions (patch is attached)

### ISSUE THREAD

**Issue by yevgen87** [terraform-providers/terraform-provider-google#2062]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform version
Terraform v0.11.7
provider.google v1.17.1

### New or Affected Resource(s)

[runtime.patch.zip](https://github.com/terraform-providers/terraform-provider-google/files/2385902/runtime.patch.zip)

* google_cloudfunctions_function

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_cloudfunctions_function" "function" {
  name                  = "function-test"
  description           = "My function"
  available_memory_mb   = 128
  source_archive_bucket = "${google_storage_bucket.bucket.name}"
  source_archive_object = "${google_storage_bucket_object.archive.name}"
  trigger_http          = true
  timeout               = 60
  runtime               = "python37"
  entry_point           = "helloGET"
  labels {
    my-label = "my-label-value"
  }
}

```
### References

* https://cloud.google.com/functions/docs/concepts/exec

**Comment by frankcash** [comment]
please lgtm ❤️

**Comment by srossross** [comment]
Any idea when this will get released?

**Comment by shaunwarman** [comment]
This doesn't seem to be available in `provider "google-beta" {}` either.

**Comment by rileykarson** [comment]
Hey @shaunwarman  & @srossross!

Support was added in https://github.com/terraform-providers/terraform-provider-google/pull/2340 and will appear in our next release, `2.0.0`. Unfortunately, we don't have a date for when we're going to make that release - our intention is to release in lockstep with Terraform 0.12 (well, likely with the beta), and I don't believe we have a date on that yet. @paddycarver may be able to provide a little more guidance than me.

@srossross: Per your question in #1857, you could clone the `2.0.0` branch (this branch is our effective `master` until the release) of this repo / the beta repo and run `make build` to build a local copy of the provider, and [run that copy locally](https://github.com/terraform-providers/terraform-provider-google/blob/2.0.0/.github/CONTRIBUTING.md#running-a-local-copy-of-the-provider). I wouldn't necessarily advise this, especially for anything but local development - the `2.0.0` branch is under active development and could be broken in unexpected ways + we have made a _lot_ of breaking changes that change how some resources work.

**Comment by rileykarson** [comment]
Also, I'm going to close out this issue based on #2340. If you have other questions, please don't hesitate to ask them here though!

**Comment by paddycarver** [comment]
Just wanted to jump in to say that there is no official release date for 0.12 beta1 yet, which is when we intend to release 2.0.0. Also wanted to say that plan could change as we get more information. :)
