### ISSUE TITLE
A node-pool taint with '/' is not accepted.

### ISSUE THREAD

**Issue by ghost** [terraform-providers/terraform-provider-google#2063]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.8
+ provider.google v1.17.1
+ provider.kubernetes v1.2.0

### Affected Resource(s)

* google_container_node_pool/node_config
* google_container_cluster/node_config

### Terraform Configuration Files

```
resource "google_container_node_pool" "np" {
  name       = "preemptible-pods"
  zone       = "${var.zone}"
  cluster    = "${local.cluster_id}"
  node_count = 1

  node_config {
    preemptible  = true
    machine_type = "${var.machine_type}"

    oauth_scopes = [
      "compute-rw",
      "storage-ro",
      "logging-write",
      "monitoring",
    ]

    labels {
      preemptible = "true"
    }

    taint {
      key = "cloud.google.com/gke-preemptible"
      value = "true"
      effect = "NO_SCHEDULE"
    }
  }
}

```

### Debug Output

* google_container_node_pool.np: error creating NodePool: googleapi: Error 400: Invalid field 'cluster.node_config.taints.key': "cloud.google.com/gke-preemptible". It must begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between., badRequest

### Expected Behavior

Terraform should create a node pool with the taint "cloud.google.com/gke-preemptible".

### Actual Behavior

terraform can't create a node pool with the requested taint. String validation excludes '/', even though it's a legal character in GKE taints.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by paddycarver** [comment]
That error indicates it's an API error, not a Terraform error. If that's a valid Kubernetes taint, but not a valid GKE taint, I think that may be an upstream issue. Are you able to use that node taint with gcloud or the API?

**Comment by apersson-sylog** [comment]
It's a valid GKE taint, I can set it using kubectl on my GKE cluster.

It's documented by Google here: https://cloud.google.com/kubernetes-engine/docs/how-to/preemptible-vms

**Comment by amq** [comment]
It's a valid taint, yet `gcloud beta container node-pools create` doesn't accept it.

**Comment by rileykarson** [comment]
It appears that the upstream API now works as intended, I was able to set this taint on a node pool.
