### ISSUE TITLE
Add instances network tag in google_container_cluster output  

### ISSUE THREAD

**Issue by tpoindessous** [terraform-providers/terraform-provider-google#2070]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We use nat-gateway and GKE cluster. Nat-gateway needs to get the network tag which is added to GKE nodes. For the moment, we use a shell script to get this value.

It would be great if this value can be added in google_container_cluster output (and google_container_node_pool ?). 

### New or Affected Resource(s)

* google_container_cluster

**Comment by tpoindessous** [comment]
For the record : alternative way to do this : add specific network tags to google_container_cluster (node_config -> tags)

**Comment by rileykarson** [comment]
I'd suggest attaching network tags to the node pool with https://www.terraform.io/docs/providers/google/r/container_cluster.html#tags instead of picking up any that are automatically applied; that way, even if default tags are changed your infrastructure will continue to work as expected.
