### ISSUE TITLE
Update API for cloud functions (add event type configuration)

### ISSUE THREAD

**Issue by yevgen87** [terraform-providers/terraform-provider-google#2080]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform version
Terraform v0.11.8
provider.google v1.18.0

### Description
When cloud function is created with trigger_bucket option, Event Type is not configurable and set to outdated 'Object Change (legacy)'.

Here is the corresponding code (google/resource_cloudfunctions_function.go):
```go
                function.EventTrigger = &cloudfunctions.EventTrigger{
                        EventType: "providers/cloud.storage/eventTypes/object.change",
                        // Must be like projects/PROJECT_ID/buckets/NAME
                        // Bucket must be in same project as function
                        Resource: fmt.Sprintf("projects/%s/buckets/%s", project, v.(string)),
                }
```

Supported trigger type values are:
* google.storage.object.finalize
* google.storage.object.delete
* google.storage.object.archive
* google.storage.object.metadataUpdate

### New or Affected Resource(s)

* google_cloudfunctions_function

### References

* https://cloud.google.com/functions/docs/calling/storage

**Comment by danawillow** [comment]
`trigger_bucket` has been removed and replaced with `event_trigger`, which adds this configuration (https://github.com/terraform-providers/terraform-provider-google/pull/2158): https://www.terraform.io/docs/providers/google/version_2_upgrade.html#resource-google_cloudfunctions_function
