### ISSUE TITLE
Order of google_bigquery_dataset.access should be ignored

### ISSUE THREAD

**Issue by tmshn** [terraform-providers/terraform-provider-google#2093]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.11.7
```

### Affected Resource(s)

* google_bigquery_dataset

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "my_log" {
  dataset_id = "my_log"

  access = [
    {
      role          = "WRITER"
      special_group = "projectWriters"
    },
    {
      role          = "OWNER"
      special_group = "projectOwners"
    },
    {
      role          = "READER"
      special_group = "projectReaders"
    },
    {
      role          = "WRITER"
      user_by_email = "${var.logging_sink_writers["mylog"]}"
    },
  ]
}
```

### Expected Behavior

`terraform plan` after `terraform apply` should produce an empty plan.

### Actual Behavior

Diff on `access` argument persists forever.

### Steps to Reproduce

1. `terraform apply`
1. `terraform plan`

### References

* #1931: The resource is introduced here
* #1692, #1525: The solution in case of storage bucket. Can be fixed similarly.

**Comment by tmshn** [comment]
I'd be happy to work on this if I had time, but unfortunately currently too busy for extra oss work...so just leave the issue. If no one work on this until October, I may do this for my October Fest work.

**Comment by ocervell** [comment]
As a workaround, you might want to look into [this](https://github.com/terraform-google-modules/terraform-google-log-export)

**Comment by tmshn** [comment]
Thank you @chrisst for the work! ❤️

**Comment by pmjacinto** [comment]
Thank you @chrisst !!

Any idea when this will be released? (i.e. will there be a 1.21.0 / 1.20.1 release, of do we need to wait for the 2.0.0 release ?)

**Comment by chrisst** [comment]
@pmjacinto - That's a great question. This change will be part of the 2.0 release as it's a little too coupled to other changes to be able to pull it into a 1.21 branch at this point. However we're working right now to figure out if/when we can ship 2.0.0 but I'm hopeful it will be weeks (not months).
