### ISSUE TITLE
Feauture Request: Postgres Schemas/Postgres Provider Integration

### ISSUE THREAD

**Issue by olib963** [terraform-providers/terraform-provider-google#2094]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be good to be able to manage postgres schemas and permissions as part of terraform. This is already possible by using the [Postgres Provider](https://www.terraform.io/docs/providers/postgresql/index.html) however there is no way to directly connect the provider and the provider will fail if it cannot connect to Postgres which means that the `google_sql_database_instance` will have to have been created before adding this provider with a `cloud_sql_proxy` running alongside `terraform` to provide the connection.

I am happy to attempt to work on this myself with guidance on the best approach.

### New or Affected Resource(s)

Either (Preferred)

- `google_sql_postgres_schema` a new resource that creates a schema and can be linked to `google_sql_user`s for permissions.

Or

- `google_sql_database_instance` & Postgres provider both changed to allow a connection 

### Potential Terraform Configuration

```tf
# Postgres Database
resource "google_sql_database_instance" "master" {
  name = "my-instance"
  database_version = "POSTGRES_9_6"
  region = "us-central1"

  settings {
    tier = "db-f1-micro"
  }
}

resource "google_sql_database" "my_db" {
  name     = "my_db"
  instance = "${google_sql_database_instance.master.name}"
}

# Users
resource "google_sql_user" "admin-user" {
  instance = "${google_sql_database_instance.master.name}"
  name     = "admin"
  password = "password1"
}

resource "google_sql_user" "service-user" {
  instance = "${google_sql_database_instance.master.name}"
  name     = "my-service"
  password = "password2"
}

resource "google_sql_user" "readonly-user" {
  instance = "${google_sql_database_instance.master.name}"
  name     = "reader"
  password = "password3"
}

# Schema
resource "google_sql_postgres_schema" "my_schema" {
  name           = "my_schema"
  fail_if_exists = false
  # Give all permissions to the owner
  owner          = "${google_sql_user.service-user.name}"

  # Grant usage to read only user
  policy {
    usage = true
    user  = "${google_sql_user.readonly-user.name}"
  }

  # Grant all to schema to admin
  policy {
    all   = true
    user  = "${google_sql_user.admin-user.name}"
  }
}
```

### Current Issue with Postgres Provider

This is an pseudo-example terraform configuration using the Postgres Provider, however it would not currently work.

```tf
# Postgres Database
resource "google_sql_database_instance" "master" {
  name = "my-instance"
  database_version = "POSTGRES_9_6"
  region = "us-central1"

  settings {
    tier = "db-f1-micro"
  }
}

resource "google_sql_database" "my_db" {
  name     = "my_db"
  instance = "${google_sql_database_instance.master.name}"
}

resource "google_sql_user" "terraform-user" {
  instance = "${module.persistence.postgres_db_name}"
  name     = "terraform"
  password = "terraformPass"
}

# Null resource to run cloud proxy (I have not tried anything like this myself, I have just created the sql database then later added the postgres provider and run the cloud proxy separately)
resource "null_resource" "proxy" {
  provisioner "local-exec" {
    # Get and run the cloud proxy
    command = "wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy && cloud_sql_proxy && cloud_sql_proxy -instances=${google_sql_database_instance.master.connection_name}=tcp:5432"
  }
}

# Postgres Provider
provider "postgresql" {
  count    = 0
  version  = "~> 0.1"
  host     = "127.0.0.1" # Connect to cloud proxy locally
  port     = 5432
  database = "${google_sql_database.my_db.name}"

  username = "${google_sql_user.terraform-user.name}"
  password = "${google_sql_user.terraform-user.password}"

  sslmode = "disable"
}

#Users
resource "google_sql_user" "admin-user" {
  instance = "${google_sql_database_instance.master.name}"
  name     = "admin"
  password = "password1"
}

resource "google_sql_user" "service-user" {
  instance = "${google_sql_database_instance.master.name}"
  name     = "my-service"
  password = "password2"
}

resource "google_sql_user" "readonly-user" {
  instance = "${google_sql_database_instance.master.name}"
  name     = "reader"
  password = "password3"
}

# Schema
resource "postgresql_schema" "my_schema" {
  name          = "my_schema"
  if_not_exists = true
  owner         = "${google_sql_user.service-user.name}"

  policy {
    usage = true
    role  = "${google_sql_user.readonly-user.name}"
  }

  policy {
    create_with_grant = true
    usage_with_grant  = true
    role              = "${google_sql_user.admin-user.name}"
  }
}
```

**Comment by paddycarver** [comment]
My offhand thoughts on this are that I'm deeply uncomfortable trying to replicate the Postgres provider's behaviour here, and would much rather investigate if any work needs to be done on our end to facilitate using the two providers together.

**Comment by paddycarver** [comment]
I'm going to close this out, as the change requested is really better suited to the Postgres provider.
