### ISSUE TITLE
Support for providing etag for subnet iam binding

### ISSUE THREAD

**Issue by kenthua** [terraform-providers/terraform-provider-google#2108]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
The ability to support etag for [google_compute_subnetwork_iam_binding](https://www.terraform.io/docs/providers/google/r/compute_subnetwork_iam.html#google_compute_subnetwork_iam_binding-1).  

The [policy](https://cloud.google.com/iam/reference/rest/v1/Policy) has the option to add an etag reference, however the "etag" field is not supported.  

If no etag is provided when attempting to create the policy binding:
```
google_compute_subnetwork_iam_binding.subnet: Error applying IAM policy for Compute Subnetwork project_id/us-west1/gke-subnet: Error setting IAM policy for Compute Subnetwork project_id/us-west1/gke-subnet: googleapi: Error 503: Code: '-6150088471201793618', backendError
```

[Retrieving](https://www.terraform.io/docs/providers/google/r/compute_subnetwork_iam.html#etag) an etag is possible as an output, but I'm not sure how I would apply in the creation of a policy.

Is there another way to apply this that I am missing?  In the reference I noted a workaround by applying the role as a project iam binding, but ideally want to apply it to only the subnet iam policy?

### New or Affected Resource(s)

* google_compute_subnetwork_iam_binding

### Potential Terraform Configuration

```
resource "google_compute_subnetwork_iam_binding" "subnet" {
  project = "${var.host_project}"
  subnetwork = "${var.subnetwork}"
  role       = "roles/compute.networkUser"

  members = [
    "serviceAccount:${data.google_project.service_project.number}@cloudservices.gserviceaccount.com",
    "serviceAccount:service-${data.google_project.service_project.number}@container-engine-robot.iam.gserviceaccount.com"
  ]

  etag = ??? <computed??>
  depends_on = ["google_compute_subnetwork.subnet0"]
}
```

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

This is a workaround https://github.com/terraform-providers/terraform-provider-google/issues/1711

The reason for this is to automate [gke shared vpc](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-shared-vpc#enabling_shared_vpc_and_granting_roles).

* #0000

**Comment by paddycarver** [comment]
I think I'm a little confused here. Because `etag` is a concurrency control tool, it's only really interesting for the underlying provider, so we abstract it away. We set `etag` on each request, as part of a read-modify-write loop that all IAM resources go through. Allowing users to set it would not really do much except break Terraform, because users can't know the order resources will apply in, and so can't predict what the etag will be when resources apply.

Do you happen to have any [debug logs](https://www.terraform.io/docs/internals/debugging.html) for that 503 error? A 503 error shouldn't indicate anything wrong with the request, but indicates something wrong with the upstream service--in this case, IAM. Is this an error you get consistently?

**Comment by morgante** [comment]
@kenthua I recommend not using the `google_compute_subnetwork_iam_binding` resource as it will attempt to wipe out any other users who are not specified in Terraform (including essential Google services).

**Comment by kenthua** [comment]
So I switched over to `google_compute_subnetwork_iam_member` per @morgante 's suggestion.  It seems to error out, with a similar 503 issue.  I have a dependency on the subnet being created prior to running adding a new member to the role.

```
java.util.concurrent.ExecutionException: com.google.net.rpc3.client.RpcClientException: \u003ceye3 title='/IAMInternal.SetPolicy, ABORTED'/\u003e /IAMInternal.SetPolicy [APPLICATION_ERROR(10)] There were concurrent policy changes. Please retry the whole read-modify-write with exponential backoff.
```

So it errors out, but if I run terraform apply again, it goes through without issue.  Seems like there needs to be an additional wait or delay needed?

**Comment by morgante** [comment]
@kenthua Can you share your Terraform config to be sure the dependency is being properly captured?

**Comment by kenthua** [comment]
https://github.com/kenthua/gke/blob/master/terraform/private-cluster-shared-vpc/network.tf#L39

**Comment by rileykarson** [comment]
Hey @kenthua! Are you still experiencing this?

It's a common (and unfortunate) error for networking and load balancing resources to return 503's when a project id is mistyped. Can you confirm that your value is correct?

**Comment by emilymye** [comment]
Since this issue hasn't been updated by non-Googlers since 2018, I'm going to go ahead and close it. If anyone is still experiencing this issue, please feel free to reopen!
