### ISSUE TITLE
Add support to associate a vlan_attachment to a router-interface

### ISSUE THREAD

**Issue by netturpin** [terraform-providers/terraform-provider-google#2116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Based on [GCP documentation](https://cloud.google.com/interconnect/docs/how-to/dedicated/creating-vlan-attachments), there are 4 steps to get a complete setup :
 1 Request a Partner/Dedicated Interconect (out of scope as mention in [issue #1140](https://github.com/terraform-providers/terraform-provider-google/issues/1140#issue-301475403) )
2. Create a vlan attachment (solved with #1569)
3. Associate a vlan attachment with a cloud router by creating a router interface linked to the vlan attachment
4. Setup a BGP session between the Cloud router and the on-prem router.

My understanding is, now that we are able to create vlan attachment in terraform, we need the ability to specify them when we create a router_interface. I feel this should be done in [google_compute_router_interface object](https://www.terraform.io/docs/providers/google/r/compute_router_interface.html) but I may be wrong,

The BGP session setup should be already functional with the [compute_router_peer object](https://www.terraform.io/docs/providers/google/r/compute_router_peer.html).

### New or Affected Resource(s)

* google_compute_router_interface
### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_router_interface" "foobar" {
  name       = "interface-1"
  router     = "router-1"
  region     = "us-central1"
  ip_range   = "169.254.1.1/30"
  vlan_attachment = "attachment-1"
}

```

### References

* #1140

**Comment by morgante** [comment]
Along with this, the "cloudRouterIpAddress" field needs to be exposed as an output from an interconnect attachment: https://cloud.google.com/compute/docs/reference/rest/v1/interconnectAttachments/get

**Comment by morgante** [comment]
@tysen Have we also addressed [this comment](https://github.com/terraform-providers/terraform-provider-google/issues/2116#issuecomment-487176261) as well?

**Comment by tysen** [comment]
Sure have.
