### ISSUE TITLE
Feature Request: Create GPU instances

### ISSUE THREAD

**Issue by strin** [terraform-providers/terraform-provider-google#212]
Hi there, 

Would there be support for managing GPU instances?

There is `--accelerator` flag in Google Cloud Compute. And it is supported by the V1 Go API.

Thanks

**Comment by ubschmidt2** [comment]
API: https://cloud.google.com/compute/docs/reference/beta/instances/setMachineResources

Depends on #93.

**Comment by rileykarson** [comment]
Linking to #311
