### ISSUE TITLE
google_container_cluster/google_container_node_pool creates empty node pool

### ISSUE THREAD

**Issue by trickleup** [terraform-providers/terraform-provider-google#2126]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.8
+ provider.google v1.18.0
```

### Affected Resource(s)

google_container_cluster
google_container_node_pool

### Terraform Configuration Files

```tf
variable "GCP_PROJECT" {}
variable "CLUSTER_NAME" {}

resource "google_container_node_pool" "primary-pool" {
  project = "${var.GCP_PROJECT}"
  name    = "primary-pool"
  region  = "us-west1"
  cluster = "${google_container_cluster.primary.name}"

  autoscaling {
    min_node_count = 1
    max_node_count = 5
  }

  management {
    auto_repair  = true
    auto_upgrade = true
  }

  node_config {
    machine_type = "n1-standard-1"
    image_type   = "COS"
    disk_type    = "pd-standard"
    disk_size_gb = "100"

    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
      "https://www.googleapis.com/auth/servicecontrol",
      "https://www.googleapis.com/auth/service.management.readonly",
      "https://www.googleapis.com/auth/trace.append",
    ]
  }
}

resource "google_container_cluster" "primary" {
  project            = "${var.GCP_PROJECT}"
  name               = "${var.CLUSTER_NAME}"
  region             = "us-west1"
  min_master_version = "1.10.7-gke.2"

  logging_service    = "logging.googleapis.com/kubernetes"
  monitoring_service = "monitoring.googleapis.com/kubernetes"

  network    = "REDACTED"
  subnetwork = "REDACTED"

  ip_allocation_policy {
    cluster_secondary_range_name  = "REDACTED"
    services_secondary_range_name = "REDACTED"
  }

  remove_default_node_pool = true

  node_pool {
    name = "default-pool"
  }

  addons_config {
    http_load_balancing {
      disabled = false
    }

    horizontal_pod_autoscaling {
      disabled = false
    }

    kubernetes_dashboard {
      disabled = false
    }
  }

  lifecycle {
    create_before_destroy = true
    prevent_destroy       = true
    ignore_changes        = ["node_pool"]
  }

  timeouts {
    create = "60m"
    update = "20m"
    delete = "20m"
  }
}

```

### Expected Behavior

I would expect a regional GKE cluster to be created, with no default node pool, and one, regional, auto-scaled, "primary" node pool with one instance in each zone, totaling 3 nodes.

### Actual Behavior

The apply succeeded (no errors from terraform). 
- The GKE cluster was created (as expected)
- No default node pool (as expected)
- A primary node pool created (as expected)
- The primary node pool contains no nodes and all pods are unschedulable (not expected)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by leejones** [comment]
I ran into this also and solved it by setting `initial_node_count = 1` in the node pool.

I think what's happening is that GKE's cluster autoscaling [depends on some/all of system pods running](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler#minimum_and_maximum_node_pool_size), so a cluster with no nodes (and therefore no system pods) cannot scale itself up.

**Comment by trickleup** [comment]
Thanks @leejones!

> so a cluster with no nodes (and therefore no system pods) cannot scale itself up

I'm not sure this is the case. I was able to add an autoscaling nodepool from the google console with the same configuration, to the same cluster, and this pool immediately scaled up to the minimum instance, and was able to schedule pods.

According to the suggestion, I tried to set `initial_node_count` in the cluster config, but this conflicts with the node_pool block:

```
google_container_cluster.primary: googleapi: Error 400: It's invalid to specify both cluster.initial_node_count and a node pool. Please only provide a node pool
``` 

So I set the initial_node_count = 1 in the node_pool block, and removed the `remove_default_node_pool` flag. I was able to run this, but with the same result - a default, non-autoscaling node pool, and an additional, autoscaling node pool, with zero instances.

To debug further, I moved the whole node pool configuration to the `node_pool` object of the cluster configuration, and instead of defining another node pool, just tried to configure the default node pool as auto scaling. This does not work either, same thing happens, the pool does not spin up the minimum capacity. So it seems maybe that this issue is not related to default vs non-default pools, but a more general issue with autoscaling node pools.

If anyone knows a workaround, let me know! What I want to achieve is to spin up a gke cluster with one autoscaling node pool (default or non-default), and I want to do this with one `terraform apply` run.

**Comment by leejones** [comment]
Sorry for the trouble @trickleup! I remember having some similar difficulties. It looks like my suggestion above was based on my poor memory and was incomplete. I reviewed my configuration and realized that I'm defining `initial_node_count` in both the cluster and the node pool config. Here's a slimmed down version of the configuration that has recently worked well for me:

```hcl
resource "google_container_cluster" "cluster" {
  # For regional GKE clusters, "additional_zones" in Terraform is actually the
  # complete list of zones used by the cluster (master nodes and worker nodes).
  additional_zones = "${var.gke_cluster_zones}"

  # The Google Cloud API requires that initial_node_count be greater than 0
  # when the cluster is created. We congiure Terraform to remove the default
  # node pool so the initial_node_count is somewhat irrelevant after that pool
  # is removed. However, the initial_node_count setting must remain unchanged
  # or Terraform will want to recreate the cluster.
  initial_node_count = 1

  name    = "${var.gke_cluster_name}"
  network = "${var.network}"

  region = "${var.gke_cluster_region}"

  remove_default_node_pool = true
}

resource "google_container_node_pool" "general-purpose" {
  autoscaling {
    max_node_count = "${var.gke_max_node_count}"
    min_node_count = "${var.gke_min_node_count}"
  }

  cluster = "${google_container_cluster.cluster.name}"

  initial_node_count = 1

  name = "general-purpose"

  node_config {
    disk_size_gb = "${var.gke_disk_size_gb}"
    image_type   = "${var.gke_image_type}"
    machine_type = "${var.gke_machine_type}"

    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.full_control",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
      "https://www.googleapis.com/auth/ndev.clouddns.readwrite",
    ]
  }

  region = "${var.gke_cluster_region}"
}
```

This configuration does the following:

* creates a cluster with the default node pool removed
* creates a node pool with a single node in each zone initially and autoscaling enabled

I hope that's helpful!

**Comment by yob** [comment]
These issues looks similar: #1160, #1708

**Comment by kish3007** [comment]
@leejones the above terraform you provided didn't work in my case. If i create gke_cluster and node pool in one terraform , only cluster creation part works fine and node pool creation part fails with `cluster not found error`, so I feel the issue still exists. Here is my terraform looks like:
`resource "google_container_cluster" "gke-cluster" {
  name = "gke-${terraform.workspace}-cluster-${var.region}"
  description = "GKE devops cluster"
  zone = "${var.region}-a"
  
  initial_node_count = 1
  
  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]

    labels {
      env = "${var.gke_label}"
    }

    machine_type = "${var.gke_node_machine_type}"
    tags         = ["gke-node"]
  }
}

resource "google_container_node_pool" "dev" {
  name       = "dev-pool"
  zone       = "${var.region}-a"
  cluster    = "gke-${terraform.workspace}-cluster-${var.region}"

  initial_node_count = 1

  management {
    auto_repair  = true
    auto_upgrade = true
  }

  autoscaling {
    min_node_count = "${var.gke_min_nodes}"
    max_node_count = "${var.gke_max_nodes}"
  }
}`

**Comment by rileykarson** [comment]
Superseded by https://github.com/terraform-providers/terraform-provider-google/issues/1708
