### ISSUE TITLE
cos-cloud absent

### ISSUE THREAD

**Issue by zdevi** [terraform-providers/terraform-provider-google#2145]
Hi,
I'm havin trouble to pull cos-stable google's image. It looks you did not add cos-cloud public repo in the code. I can't access cos-stable-xxx which is on this repo.

**Comment by Chupaka** [comment]
What is this issue about? (O_o)

**Comment by zdevi** [comment]
When i try to use google's cos-stable image with terraform (Container Optimized OS) which is a public google image, it sais it doesn't find it. I tried with the commande 'gcloud compute image list' and i could see it, but terraform doesn't :

`:~/Desktop/terraform-provider-google$ gcloud compute images list|grep cos
cos-69-10895-71-0                                     cos-cloud          cos-69-lts                                    READY
cos-beta-70-11021-29-0                                cos-cloud          cos-beta                                      READY
cos-dev-71-11104-0-0                                  cos-cloud          cos-dev                                       READY
cos-stable-65-10323-104-0                             cos-cloud                                                        READY
cos-stable-68-10718-106-0                             cos-cloud          cos-stable                                    READY
cos-stable-69-10895-71-0                              cos-cloud          cos-stable                                    READY`

**Comment by Chupaka** [comment]
I still can't see your "doesn't". Where's Terraform config, where's Terraform log?

**Comment by zdevi** [comment]
* google_compute_instance_template.app: 1 error(s) occurred:

* google_compute_instance_template.app: Error resolving image name 'cos-stable-69-10895-71-0': Could not find image or family cos-stable-69-10895-71-0

2018-10-01T18:04:46.535+0200 [DEBUG] plugin.terraform-provider-google_v1.18.0_x4: ---[ REQUEST ]---------------------------------------
2018-10-01T18:04:46.535+0200 [DEBUG] plugin.terraform-provider-google_v1.18.0_x4: GET /compute/v1/projects/setjemesian-terraform-admin/global/images/family/cos-stable-69-10895-71-0?alt=json HTTP/1.1
2018-10-01T18:04:46.703+0200 [DEBUG] plugin.terraform-provider-google_v1.18.0_x4:   "message": "The resource 'projects/setjemesian-terraform-admin/global/images/family/cos-stable-69-10895-71-0' was not found"

**Comment by zdevi** [comment]
I've been able to pull the image by specifying the repo : source_image = "cos-cloud/cos-stable-69-10895-71-0"
