### ISSUE TITLE
Missing Attributes reference section on doc page for google_organization_iam_custom_role

### ISSUE THREAD

**Issue by BrunoReboul** [terraform-providers/terraform-provider-google#2146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* https://www.terraform.io/docs/providers/google/r/google_organization_iam_custom_role.html
* https://www.terraform.io/docs/providers/google/r/google_project_iam_custom_role.html

### Potential Terraform Configuration

```tf
# Missing Attributes reference section on the two doc pages for google_organization_iam_custom_role and google_project_iam_custom_role
# Should document the returned ID of the created custom role formatted as [projects|organizations]/{parent-name}/roles/{role-name}
```

### References

* #0000

**Comment by paddycarver** [comment]
Looks like this got fixed. Please open a new issue if you're still missing information. Thanks!
