### ISSUE TITLE
Master version "1.9.7-gke.5" is unsupported., badRequest

### ISSUE THREAD

**Issue by ensonic** [terraform-providers/terraform-provider-google#2149]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.7

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "foo" {
  name = "foo"
  zone = "${var.zone}"
  min_master_version = "1.9.7-gke.5"
  enable_legacy_abac = true
  depends_on = ["google_project_service.container"]
  ...
```

### Debug Output

https://gist.github.com/ensonic/05440feef1efd8e0a29c76001909677d

### Expected Behavior

Install some newer version. If there is trouble parsing the version, give a helpful error.

### Actual Behavior

Fails with a not helpful error. If I remove the 'min_master_version' it will run fine and actually create a good version.

### Steps to Reproduce

1. `terraform apply`

### References

* #1539 has a similar error

**Comment by tmegow** [comment]
Since yesterday 11/12, I am also experiencing this symptom when trying to create `1.11.2-gke.15` gke clusters.

I get `Error 400: Master version "1.11.2-gke.15" is unsupported., badRequest`, despite this being a supported version, having worked previously, and still working via the web console.

> validMasterVersions:
> - 1.11.2-gke.15

https://i.imgur.com/Vow9w7o.png

**Comment by rileykarson** [comment]
Using the following config, I successfully created a cluster:

```hcl
resource "google_container_cluster" "primary" {
  name               = "marcellus-wallace"
  zone               = "us-central1-a"
  initial_node_count = 1
  min_master_version = "1.11.2-gke.15"

  additional_zones = [
    "us-central1-b",
    "us-central1-c",
  ]

  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]

    labels {
      foo = "bar"
    }

    tags = ["foo", "bar"]
  }
}
```

My suspicion is that this is one of two things;

* A transient issue upstream, in which case there isn't much we can do from our side unfortunately.
* I'm not sure that every master version is supported in every zone; it looks like we're able to [query the API for valid versions by `zone`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/ServerConfig). 
	* Can you confirm the `zone` you used in the Cloud Console and your Terraform config match?

If the zones match and you're still seeing this issue, please post a config that you're experiencing the issue with so I can try to reproduce on my end!

**Comment by tmegow** [comment]
Thank you for your help! 
Using your bare-bones config, i was successfully able to create a  `1.11.2-gke.15` cluster in `us-east4-c` (the zone i'm working in). Below I have shared a config which is responds with `Error 400: Master version "1.11.2-gke.15" is unsupported., badRequest`. Perhaps I have added some other breaking config option.

I have redacted some sensitive info; I hope you can test `master_authorized_networks_config` with other values.

```
$ gcloud container get-server-config --zone us-east4-c
Fetching server config for us-east4-c
defaultClusterVersion: 1.9.7-gke.7
defaultImageType: COS
validImageTypes:
- UBUNTU
- COS_CONTAINERD
- COS
validMasterVersions:
- 1.11.2-gke.15
```


```
# Get k8s versions available on GKE
data "google_container_engine_versions" "gke_version" {
  zone = "us-east4-c"
}

resource "google_container_node_pool" "fruit-leather-generic" {
  name       = "fruit-leather-generic"
  region       = "us-east4"
  cluster       = "${google_container_cluster.fruit-leather.name}"
  node_count = 1

  node_config {
    machine_type = "n1-standard-2"

    image_type = "COS"

    oauth_scopes = [
      "compute-rw",
      "storage-ro",
      "logging-write",
      "monitoring",
    ]
  }
}


resource "google_container_node_pool" "fruit-leather-mongodb" {
  name       = "fruit-leather-mongodb"
  region       = "us-east4"
  cluster       = "${google_container_cluster.fruit-leather.name}"
  node_count = 1

  node_config {
    machine_type = "n1-standard-2"

    image_type = "UBUNTU"

    oauth_scopes = [
      "compute-rw",
      "storage-ro",
      "logging-write",
      "monitoring",
    ]
  }
}

resource "google_container_cluster" "fruit-leather" {
  provider              = "google-beta"
  name               = "fruit-leather"
  region               = "us-east4"

  min_master_version = "${data.google_container_engine_versions.gke_version.latest_master_version}"
  node_version = "${data.google_container_engine_versions.gke_version.latest_master_version}"

  master_auth {
    username = ""
    password = ""
    client_certificate_config {
    issue_client_certificate = true
  }
  }

  node_pool {
      name = "default-pool"
  }

  master_authorized_networks_config {
    cidr_blocks = [
    { display_name = "xx", cidr_block   = "x.x.x.x/28" },
    { display_name = "xx", cidr_block   = "x.x.x.x/32" },
    ]
  }

  network_policy {
    enabled  = true
    provider = "CALICO"
  }

  addons_config {
    network_policy_config {
      disabled = false
    }

    kubernetes_dashboard {
      disabled = true
    }
  }
}
```

**Comment by tmegow** [comment]
I may have uncovered the issue. I am trying to use regional GKE clusters and maybe the `1.11` version needs to be the same in all zones within the region.
`us-east4-a` has `1.11.2-gke.15`
`us-east4-b` has `1.11.2-gke.18`
`us-east4-c` has `1.11.2-gke.15`
🤔

**Comment by rileykarson** [comment]
Ah! I was just about to start writing up my response - I'd noticed the same thing. It turns out, the versions supported in a `region` and its corresponding `zone`s are not necessarily the same. I sent a PR out to clarify this in the docs.


Here's a working config after I cut down some fields off the one you provided. You can set a `region` for the `google_container_engine_versions` datasource instead of `zone`, and this should work as expected:

```hcl
provider "google-beta" {
}

data "google_container_engine_versions" "gke_version" {
  provider = "google-beta"
  region   = "us-east4"
}

output "versions" {
  value = "${data.google_container_engine_versions.gke_version.valid_master_versions}"
}

resource "google_container_cluster" "fruit-leather" {
  provider = "google-beta"
  name     = "fruit-leather"
  region   = "us-east4"

  min_master_version = "${data.google_container_engine_versions.gke_version.latest_master_version}"
  node_version       = "${data.google_container_engine_versions.gke_version.latest_node_version}"

  node_pool {
    name = "default-pool"
  }
}
```

**Comment by tmegow** [comment]
TIL the distinction between regional and zonal supported versions. Your suggested config works great, thank you!
