### ISSUE TITLE
google_container_cluster beta private_cluster feature is deprecated

### ISSUE THREAD

**Issue by idsvandermolen** [terraform-providers/terraform-provider-google#2163]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

According to Google SDK `gcloud`docs the beta feature flag `--private-cluster` is deprecated and split into two new flags: `--enable-private-nodes` and `--enable-private-endpoint`.
The feature to enable private nodes currently exists in `google_container_cluster` terraform resource, but probably the feature to enable private endpoint could be implemented also.
Fragment of `gcloud` help:
```
     Private Clusters

       --enable-private-endpoint
          Cluster is managed using the private IP address of the master API
          endpoint.

       --enable-private-nodes
          Cluster is created with no public IP addresses on the cluster nodes.

       --master-ipv4-cidr=MASTER_IPV4_CIDR
          IPv4 CIDR range to use for the master network. This should be a /28
          and should be used in conjunction with the --enable-private-nodes
          flag.

       --private-cluster
          (DEPRECATED) Cluster is created with no public IP addresses on the
          cluster nodes.

          The --private-cluster flag is deprecated and will be removed in a
          future release. Use --enable-private-nodes instead.
```
Current (deprecated) syntax:
```tf
resource "google_container_cluster" "mycluster" {
  private_cluster = true
}
```

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_container_cluster" "mycluster" {
  enable_private_nodes    = true
  enable_private_endpoint = true
}
```

### References

* #1250

**Comment by ewbankkit** [comment]
It looks like the new [`PrivateClusterConfig`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.PrivateClusterConfig) structure returns both public and private master endpoints. How about adding them both to the resource's returned attributes?

**Comment by paddycarver** [comment]
This has been merged in to the google-beta provider. It'll be in the next release. :)

**Comment by mkozjak** [comment]
@paddycarver: Should this work with the latest provider-google-beta?

Getting ```Error: google_container_cluster.primary: : invalid or unknown key: private_cluster_config```.

Currently having lock.json, terraform-provider-google-beta_v1.19.0_x4 and terraform-provider-google_v1.19.0_x4 in .terraform/plugins/darwin_amd64...

**Comment by ewbankkit** [comment]
@mkozjak Make sure you specify the `google-beta` provider in the `google_container_cluster` resource - See [here](https://www.terraform.io/docs/providers/google/provider_versions.html).

**Comment by mkozjak** [comment]
@ewbankkit: That was it. The docs link was wrong so I failed to see that one. Thank you very much!
