### ISSUE TITLE
Align vendored revisions of google.golang.org/api/...

### ISSUE THREAD

**Issue by alexsomesan** [terraform-providers/terraform-provider-google#2165]
Hi there,

### Terraform Version
Terraform v0.11.8

### Affected Resource(s)
None. This is a Go build build issue.

Currently , the Google provider vendors packages of `google.golang.org/api/...` at different Git commit IDs for each service API. While this is permitted by certain vendoring tools like `govendor`, it is neither reproducible with just packages in GOPATH nor more importantly is it compatible with Go modules as introduced in Go 1.11.x. Because Go modules only allow specifying versions at a module level and for non-module-native projects like `google.golang.org/api/...` the module boundary is considered the entire repository, it is not possible to express different versions for each sub-package in a `go.mod` file.

As a maintainer of the Kubernetes provider, I am running into this issue because the K8S provider vendors the Google provider as a test dependency for its acceptance tests. This is blocking the migration of both providers to Go modules.

### Expected Behavior
All vendored packages under `google.golang.org/api/...` are aligned at the same commit IDs.

### Actual Behavior
Most packages of `google.golang.org/api/...` are vendored at different commit IDs.

### Important Factoids
Only a single line of code seems to need to be adapted in order to bump `google.golang.org/api/...` to latest tip of master.
As I don't have enough context on this provider, I'm not able to assess the validity of this change. Nevertheless, this following change seems to be enough to get the provider to build and pass tests after updating vendored `google.golang.org/api/...`.

```diff
index 4ff1ab72..bc79aa9b 100644
--- a/google/resource_sql_user.go
+++ b/google/resource_sql_user.go
@@ -171,7 +171,7 @@ func resourceSqlUserUpdate(d *schema.ResourceData, meta interface{}) error {

                mutexKV.Lock(instanceMutexKey(project, instance))
                defer mutexKV.Unlock(instanceMutexKey(project, instance))
-               op, err := config.clientSqlAdmin.Users.Update(project, instance, host, name,
+               op, err := config.clientSqlAdmin.Users.Update(project, instance, name,
                        user).Do()

                if err != nil {
```

### References
Branch with proposed changes to alleviate this issue.
https://github.com/alexsomesan/terraform-provider-google/commits/update-google-api

**Comment by alexsomesan** [comment]
I forgot to mention this was briefly discussed with @paddycarver on Slack.

**Comment by alexsomesan** [comment]
Thanks a lot for resolving this!

**Comment by paddycarver** [comment]
This still needs the code change coming from GoogleCloudPlatform/magic-modules#640 to make its way downstream to us before the code will build, just a heads up. Currently that's blocked on some legal stuff.
