### ISSUE TITLE
App Engine recreated with resource "google_app_engine_application"

### ISSUE THREAD

**Issue by mkozjak** [terraform-providers/terraform-provider-google#2175]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.8
+ provider.google v1.19.0 (manually built, copied and named to .terraform/plugins)

### Affected Resource(s)

* google_project
* google_app_engine_application

### Terraform Configuration Files

main.tf
```tf
terraform {
	required_version = ">= 0.11.8"
}

// Configure the Google Cloud provider
provider "google" {
	project = "test-dev"
	region = "europe-west3"
	version = "~> 1.18"
}

// Create a project
resource "google_project" "test-dev" {
	name = "test-dev"
	project_id = "test-dev"
	org_id = "${var.org_id}"
	billing_account = "${var.billing_account}"
}
```

app_engine.tf
```tf
resource "google_app_engine_application" "test-dev" {
	project = "${google_project.test-dev.project_id}"
	location_id = "europe-west3"
}
```

### Debug Output

https://gist.github.com/7940003399787e5e521db648630c9b05

### Expected Behavior

Terraform should recognize App Engine already exists and skip recreating it.

### Actual Behavior

Terraform tries to create an App Engine, but fails with "googleapi: Error 409: This application already exists and cannot be re-created., alreadyExists".
Btw, Terraform doesn't look at $GOPATH/bin for new providers.

### Steps to Reproduce

Create your GCP project and App Engine via GCP Console.

1. `terraform init`
2. `terraform import google_project.test-dev test-dev`
3. `terraform plan`
4. `terraform apply`

### References

* #2147 
* #2118

**Comment by danawillow** [comment]
Hi @mkozjak, most of our resources don't let you use a "create" action when the resource already exists. Importing it into your state should work. I'm happy to entertain an argument about why app engine should behave differently than the rest, if you have one.

**Comment by mkozjak** [comment]
@danawillow Hi! Not sure if I reported okay, but I did import everything before trying plan/apply:

```2. terraform import google_project.test-dev test-dev```

So, I have created a project and an app engine initially without using terraform. Later on went with importing and trying apply. The rest is in the debug log.

**Comment by paddycarver** [comment]
@mkozjak Have you tried `terraform import google_app_engine_application.test-dev test-dev`?

**Comment by mkozjak** [comment]
@paddycarver Oh yes, sorry, I haven't tried that one. For some reason I thought it would pull everthing if i did just `terraform import google_project.test-dev test-dev`. Thanks!
