### ISSUE TITLE
google_project keeps wanting to update app_engine

### ISSUE THREAD

**Issue by bluemalkin** [terraform-providers/terraform-provider-google#2188]
### Terraform Version
```
terraform -v
Terraform v0.11.8
+ provider.google v1.19.0
```

### Affected Resource(s)

* google_project

### Terraform Configuration Files

```
resource "google_project" "foo" {
  name = "foo"
}
```

### Debug Output

```
  ~ update in-place

Terraform will perform the following actions:

  ~ google_project.foo
      app_engine.#: "" => <computed>
```

This apply keeps wanting to happen all the time and won't go away.

### Actual Behavior

https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#1190-october-08-2018 mentions that app_engine is deprecated. 

I do not use app engine on my project. 

I've tried setting `app_engine = []` but then I get the deprecated warning.

The CHANGELOG.md should have documentation on how to fix this.

**Comment by danawillow** [comment]
Hi @bluemalkin, I think I know how to fix this, but I'm not 100% sure that the issue you've found is the one I'm going to be fixing. If you could provide us with debug logs, that would help me know for sure.
