### ISSUE TITLE
google_container_node_pool - transitioning from beta features to GA provider wants to re-create resource 

### ISSUE THREAD

**Issue by bluemalkin** [terraform-providers/terraform-provider-google#2189]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
```
terraform -v
Terraform v0.11.8
+ provider.google v1.19.0
```

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

```
resource "google_container_cluster" "regional" {
  name   = "marcellus-wallace"
  region = "us-central1"
}

resource "google_container_node_pool" "regional-np" {
  name       = "my-node-pool"
  region     = "us-central1"
  cluster    = "${google_container_cluster.primary.name}"
  node_count = 1
}
```

### Debug Output

```
-/+ google_container_node_pool.regional-np (new resource required)
      id:                                    "australia-southeast1/xxx/regional-np" => <computed> (forces new resource)
```

### Expected Behavior

As per https://www.terraform.io/docs/providers/google/provider_versions.html#converting-resources-between-versions 
going from beta to GA google provider coming off version `1.18.0`, removing the `region` attribute should not require any changes to infrastructure.

### Actual Behavior

The google_container_node_pool wants to be re-created.

Is there a way to update existing states to be compliant with the GA provider, without needing to explicitly use the `google-beta` provider ?

**Comment by paddycarver** [comment]
Can you share your full config and plan output? It looks like they got accidentally cut off there.

**Comment by danawillow** [comment]
Hi @bluemalkin, I'm not really sure what you're trying to do here. It sounds like you're trying to use a beta feature (regional clusters) in the GA provider, which is something we're explicitly not going to be allowing in the future. Your options are to use the google-beta provider (which still has this functionality), or to use a zonal cluster. GKE does not provide a way to convert between a regional cluster and a zonal one, so we unfortunately can't offer that for you.

**Comment by bluemalkin** [comment]
Thanks for the clarification!
