### ISSUE TITLE
Storing the password of the google_sql_user as encrypted text.

### ISSUE THREAD

**Issue by dwardu89** [terraform-providers/terraform-provider-google#2190]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When a google_sql_user is created, a password will be created. However when it is stored in the state file, the password will be stored as plain text. This is not secure when storing data at rest.

### New or Affected Resource(s)

* google_sql_user

### Potential Terraform Configuration

```
resource "google_sql_user" "tf" {
  name     = "terraform"
  instance = "db_instance_name"
  host     = "%"
  password = ""
  pgp_key = "" // Either a base-64 encoded PGP public key, or a keybase username in the form keybase:some_person_that_exists.
}
```

### References

The idea has been taken from https://www.terraform.io/docs/providers/aws/r/iam_access_key.html

**Comment by paddycarver** [comment]
Oops, sorry, wrong button click.

**Comment by dwardu89** [comment]
Yes understood, however when you think about it. What would happen if the storage account is compromised? Another form of security would be to store the password encrypted with a `pgp_key`, will let you encrypt it by client as well as at rest.
It's used with access key id's which will encode the data on another level.

**Comment by paddycarver** [comment]
Unfortunately, this would come with a significant cost. What's in the state file is what is able to be interpolated, so removing the user's password from the state file means people can't use it with the MySQL or PostgreSQL or even Vault provider. hashicorp/terraform#516 has more history on this conversation, which has been ongoing for a while.

**Comment by paddycarver** [comment]
I think the Vault provider will have the same issue, if I understand correctly. To interpolate from the Vault provider, the secret has to be set in state.

The real solution for this will likely come from a Terraform core change, but I have no insight into what that will look like or a timeline.

**Comment by joestump** [comment]
The preexisting pattern is to expose a `pgp_key` variable and to use [`encryption`](https://github.com/hashicorp/terraform/blob/master/helper/encryption/encryption.go) helper. Basically, if `pgp_key` is set, TF encrypts what's stored in state and leaves it to the end user to decrypt and marshal as necessary. If `pgp_key` is _not_ set, the unencrypted value is stored in state.

I don't see any reason not to leverage this pattern for similar use cases. It gives us the best of both worlds.

**Comment by paddycarver** [comment]
The preexisting pattern is only applied in a small handful of places across some of our most active providers. The number of drawbacks, the UX, and the whackamole nature of the fix meant when I surveyed our internal team of maintainers, the consensus was that it wasn't a pattern we were comfortable supporting, and we'd prefer to leverage a core solution rather than implementing partial support now.

**Comment by paddycarver** [comment]
Hi there! In accordance with [Terraform's guidance](https://www.terraform.io/docs/extend/best-practices/sensitive-state.html#don-39-t-encrypt-state) on best practices for providers, we're not going to implement this. The suggested workaround is to use an [enhanced remote backend](https://www.terraform.io/docs/backends/types/index.html), which should meet most security needs.

If an enhanced remote backend can't solve this issue for someone's use case, the recommended path forward is to weigh in on the [upstream issue](https://github.com/hashicorp/terraform/issues/516) about this with your use case and requirements.
