### ISSUE TITLE
google_project_iam_member don't accept a list

### ISSUE THREAD

**Issue by Jean-Mercier** [terraform-providers/terraform-provider-google#2195]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.7
+ provider.google v1.18.0

### Affected Resource(s)

* google_project_iam_member

### Terraform Configuration Files

```
resource "google_project_iam_member" "project-iam" {
  project = "my-project"
  role    = "roles/editor"

#it's fail with members or member :
members = [
  "user:toto@example.fr",
  "user:tata@example.fr",
]

}

```

### Expected Behavior
As the documentation said we can pass a list of members to this ressource and create iam policy
https://www.terraform.io/docs/providers/google/r/google_project_iam.html#member-members

### Actual Behavior

When i make the plan : 
with "members"
Error: google_project_iam_member.project-iam: : invalid or unknown key: members

with "member"
Error: google_project_iam_member.project-iam: member must be a single value, not a list

### Steps to Reproduce
terraform plan

1. `terraform apply`

### References

* #0000

**Comment by danawillow** [comment]
Hey @Jean-Mercier, if you want a list you should use the `google_project_iam_binding` resource. Take a look at the examples on that page, and let me know if you still have questions!
