### ISSUE TITLE
Clearing google_container_cluster.master_authorized_networks_config errors out

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-google#2198]
Removing a `google_container_cluster` resource's `master_authorized_networks_config` attribute from Terraform code and running `terraform apply`:

```console
$ terraform apply
google_container_cluster.cluster: Refreshing state... (ID: xxxxxxxx)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ google_container_cluster.cluster
      master_authorized_networks_config.#: "1" => "0"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_container_cluster.cluster: Modifying... (ID: xxxxxxxx)
  master_authorized_networks_config.#: "1" => "0"

Error: Error applying plan:

1 error(s) occurred:

* google_container_cluster.cluster: 1 error(s) occurred:

* google_container_cluster.cluster: googleapi: Error 400: Must specify a field to update., badRequest
```

**Comment by ewbankkit** [comment]
It looks like `expandMasterAuthorizedNetworksConfig` called from [here](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_container_cluster.go#L832-L835) shouldn't return `nil` but instead
```go
&containerBeta.MasterAuthorizedNetworksConfig{
		Enabled: false,
}
```

**Comment by ewbankkit** [comment]
Same error in `terraform-provider-google-beta`.

**Comment by ewbankkit** [comment]
I also think that [this line](https://github.com/terraform-providers/terraform-provider-google/blob/99c8a17a3e882efe60063905f91986fe93ff7ce5/google/resource_container_cluster.go#L1644) should change to

```go
if c == nil || !c.Enabled
```

else if I remove all the `master_authorized_networks_config` lines from the state file and run `terraform plan`:

```console
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

google_container_cluster.cluster: Refreshing state... (ID: xxxxxxxx)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ google_container_cluster.cluster
      master_authorized_networks_config.#:               "1" => "0"
      master_authorized_networks_config.0.cidr_blocks.#: "" => <computed>


Plan: 0 to add, 1 to change, 0 to destroy.
``` 

and I get the same error.

**Comment by gburiola** [comment]
I played around with the `masterAuthorizedNetworksConfig` setting via the console and then looked at the API calls that were made on stackdriver and these are the payloads the update expect for all possible combinations:

### DISABLE

notice how you have to specify an empty dict `{}` and not `enabled:  false` to disable it

```
   update: {
    desiredMasterAuthorizedNetworksConfig: {}
   }
```

### ENABLE with empty list of cidrBlocks

```
   update: {
    desiredMasterAuthorizedNetworksConfig: {
     enabled:  true      
    }
   }
```

### ENABLE and specify cidrBlock

```
   update: {
    desiredMasterAuthorizedNetworksConfig: {
     cidrBlocks: [
      0: {
       cidrBlock:  "8.8.8.8/32"        
       displayName:  "test"        
      }
     ]
     enabled:  true      
    }
   }
```

**Comment by chap-dr** [comment]
Trying to get nodes private, but master public (while we work on getting ci system on a known set of cidrs) But even tho the docs says master_authorized_networks_config (optional) it gets enabled. 

Leaving it empty throws "missing field 400 error" during apply. 
Leaving the section out of the config entirely just enabled it but with no cidrs added.

**Comment by oswalya** [comment]
Hey,

Are there any updates on this? We are currently struggling exactly with this issue. When doing a plan:

```hcl
~ module.k8s.google_container_cluster.cluster
      master_authorized_networks_config.#:                        "1" => "0"
```

And trying afterwards an apply:

```sh
* google_container_cluster.cluster: 1 error(s) occurred:

* google_container_cluster.cluster: googleapi: Error 400: Must specify a field to update., badRequest
```

Currently this behaviour would mean to delete and recreate a lot of productive clusters. Anyone found a suitable workaround without recreation? Or better any chance of getting this fixed?

**Comment by oswalya** [comment]
This issue might be solved by a PR I just opened at the magic modules:
https://github.com/GoogleCloudPlatform/magic-modules/pull/2308

Fingers crossed. Further I think this bug is also related / the same as https://github.com/terraform-providers/terraform-provider-google/issues/3098

**Comment by megan07** [comment]
Thanks @ewbankkit for opening this issue. It's been closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/2312 and will be released shortly.
