### ISSUE TITLE
google_monitoring_alert_policy: Provider doesn't support resource

### ISSUE THREAD

**Issue by naftulikay** [terraform-providers/terraform-provider-google#2211]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
$ terraform version
Terraform v0.11.8
+ provider.archive v1.1.0
+ provider.google v1.18.0
+ provider.null v1.0.0
```

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_monitoring_alert_policy" "default" {
  display_name = "Custom Metric Test"
  combiner = "OR"
  conditions = [{
    display_name = "Default Condition"
    condition_threshold {
      filter = "metric.type=\"custom.googleapis.com/sample_metric\""
      duration = "30s"
      threshold_value = "0"
      comparison = "COMPARISON_GT"
      aggregations = [{
        alignment_period = "60s"
        per_series_aligner = "ALIGN_RATE"
      }]
    }
  }]

  notification_channels = []
}
```

### Debug Output

```
Error: google_monitoring_alert_policy.default: Provider doesn't support resource: google_monitoring_alert_policy
```

### Panic Output

N/A

### Expected Behavior

[As per the documentation, the resource should exist in the provider.](https://www.terraform.io/docs/providers/google/r/monitoring_alert_policy.html)

### Actual Behavior

The error message above is emitted.

### Steps to Reproduce

1. Follow [the example provided for the resource](https://www.terraform.io/docs/providers/google/r/monitoring_alert_policy.html).
1. `terraform apply`

### Important Factoids

Nope, very generic setup.

### References

N/A.

Searching doesn't reveal anything.

**Comment by naftulikay** [comment]
This was because of an old provider version, hence this is my fault.

However, there doesn't seem to be a clear way from the CLI to upgrade a provider. I forced an upgrade by manually removing a file in `.terraform/plugins`.

**Comment by rileykarson** [comment]
Hey @naftulikay!

We include a [short section in the provider docs]https://github.com/terraform-providers/terraform-provider-google#upgrading-the-provider) on how to upgrade your provider to the latest version, and the [provider versions section of the Terraform website](https://www.terraform.io/docs/configuration/providers.html#provider-versions) has a detailed guide on provider versions.

Please let us know if you feel there's a better way we could surface this information to you!
