### ISSUE TITLE
Encryption of Disk (Boot Disk ,Attached Disk and Local Disk) ,is that supported via Cryptographic Keys or KMS in GCP ,via Terraform .At API level it's simple but at Terraform level I was not able to achieve .

### ISSUE THREAD

**Issue by NG-GCP-USER** [terraform-providers/terraform-provider-google#2234]
We have KMS keys in GCP which I am not able to use for disk encryption using Terraform code .Is there a support for using disk encryption with KMS .In Yaml and python it was simple .

What only I can find is useful it seemed for my KMS encryption was https://www.terraform.io/docs/providers/google/d/google_kms_secret.html .But it didn't work .Is there some simple way that can be shared .

Finally I did it use the option with disk_encryption_key_raw attribute  ,but it doesn't seem much secure .

**Comment by chrisst** [comment]
KMS support has been added to disks and compute templates:
