### ISSUE TITLE
automatic_restart false in scheduling/google_compute_instance_template forces new resource

### ISSUE THREAD

**Issue by dgolja** [terraform-providers/terraform-provider-google#224]
Hi there,

If in `google_compute_instance_template` you define `scheduling` block `automatic_restart` = `false`, terraform will always recreate the resource trying to update `automatic_restart` field to `true`.

### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- google_compute_instance_template

### Terraform Configuration Files
```hcl
...
resource "google_compute_instance_template" "instance_template" {
  name_prefix = "dgolja-instance-template-tf-bug-"

  region = "${var.region}"

  lifecycle {
    create_before_destroy = true
  }

  machine_type         = "n1-standard-1"
  can_ip_forward       = false

  scheduling {
    automatic_restart   = false
    on_host_maintenance = "MIGRATE"
  }

  network_interface {
    network = "default"
  }

  disk {
    source_image = "projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20170619a"
    disk_type    = "pd-ssd"
    auto_delete  = true
    boot         = true
  }

  service_account {
    scopes = ["userinfo-email"]
  }
}
...

```

### Debug Output
https://gist.github.com/dgolja/1c80d16db90d9bbea5fa1cce21d9f8f9

### Expected Behavior
Since there is no change terraform shouldn't recreate the resource.

### Actual Behavior
Keep updating the resource, however the new resource is the same.

### Steps to Reproduce
1. `terraform apply`

**Comment by dgolja** [comment]
Workaround for this bug is to use a deprecated parameter `automatic_restart` and set it to `false`. 

https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_instance_template.go#L134-L140

**Comment by selmanj** [comment]
Thanks for reporting, hopefully #248 fixes this for you.
