### ISSUE TITLE
Support for Google Cloud Router & Cloud NAT

### ISSUE THREAD

**Issue by KieranP** [terraform-providers/terraform-provider-google#2249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCP just introduced a new Cloud NAT. - https://cloud.google.com/nat/docs/overview

Would be nice to have support for it in Terraform along with all our other resources we already have.

### New or Affected Resource(s)

* google_cloud_router
* google_cloud_nat

### Potential Terraform Configuration

```tf
resource "google_cloud_router" "primary" {
  name = "primary-router"
  network = google_compute_network.default.name
  region = "asia-east1"
}

resource "google_cloud_nat" "primary" {
  name = "primary-nat"
  network = google_compute_network.default.name
  region = "asia-east1"
  router = google_cloud_router.primary.name

  nat_mapping {
    source = "both" // or "primary" / "secondary"
    ip_address = google_compute_address.nat.address // omit to have ip be automatic
  }

  settings {
    min_ports = 64
    
    timeouts {
      udp = 30
      tcp_established = 1200
      tcp_transitory = 30
      icmp = 30
    }
  }
}
```

### References

https://cloud.google.com/nat/docs/overview

**Comment by paddycarver** [comment]
Looking at https://cloud.google.com/nat/docs/apis#rest_api, it looks like all the operations are meant to be performed on the Router API resource, so it may make more sense to have this be a sub-block within Router. Maybe. It could be a candidate for fine-grained resourcehood.

**Comment by KieranP** [comment]
@paddycarver Yup, the sample terraform script was designed based on the currently google UI, but under the hood, I suspect they are just making one API request. Either way, being able to import/configure the cloud NATs in terraform would be great.

**Comment by akoenig** [comment]
Just stumbled upon this one while terraforming private Kubernetes clusters (in isolated VPCs). In this case the Kubernetes nodes needs outbound connectivity for fetching container images. I created a Cloud NAT manually and everything works as expected then.

The possibility to integrate that into my terraform workflow as well would be superb. Looking forward to see that resource in the `google-beta` provider 😊

**Comment by drebes** [comment]
@akoenig,  if all your container images are hosted on gcr.io, you can fetch them with [Private Google Access](https://cloud.google.com/vpc/docs/configure-private-google-access), which is free.

**Comment by akoenig** [comment]
@drebes Yap, I know that. The setup uses images from other registries like quay.io (e.g. `nginx-Ingress`, etc. Unfortunately, this is not an option, but thanks for mentioning it. 🙂

**Comment by ndmckinley** [comment]
This should be done within the month of November, folks, and released as soon after completion as is feasible.  :)  Thanks for your patience.

**Comment by danawillow** [comment]
Merged in https://github.com/terraform-providers/terraform-provider-google-beta/pull/161.

**Comment by zhhuta** [comment]
I've download google-beta plugin and still get error
```google_compute_router_nat.cloud-nat: Provider doesn't support resource: google_compute_router_nat```

**Comment by ndmckinley** [comment]
Router NAT isn't in `1.19`, which was released in early october.  It'll be in `1.20`, to be released soon.

**Comment by Phylu** [comment]
In the meantime, you will need to compile the plug-in yourself and put it in .terraform/plugins/YOUR_ARCHITECTURE/ for so that it gets used.

**Comment by zhhuta** [comment]
thanks for advice

**Comment by paddycarver** [comment]
Just a heads up that 1.20.0 has been released. 🎉
