### ISSUE TITLE
Add filter to metric block of google_compute_region_autoscaler and google_compute_autoscaler

### ISSUE THREAD

**Issue by lchastel** [terraform-providers/terraform-provider-google#2255]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Some Stackdrivers metrics have labels which allows to filter the values.

For instance : agent.googleapis.com/memory/percent_used has the label "state" that contains the type of memory (buffered, cached, free, slab, used)
(Have a look to https://cloud.google.com/monitoring/api/metrics_agent for labels)

Those metrics could be used in autoscaler of instance group.

I have a case on which is need the autoscaled the instance group according to used memory.
But as I could not specify the filter, I'm not able to make is work correctly. 
I always have a value at 100% even if real value is 10%.
I checked in Stackdriver, the metric agent.googleapis.com/memory/percent_used  shows 6 values ... one by label.

The change need to be made in google_compute_region_autoscaler and google_compute_autoscaler
In block "metric" of block "autoscaling_policy", the field filter need to be added.

### New or Affected Resource(s)

* google_compute_autoscaler
* google_compute_region_autoscaler 

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_region_autoscaler" "foobar" {
  name   = "my-region-autoscaler"
  region = "us-central1"
  target = "${google_compute_region_instance_group_manager.foobar.self_link}"

  autoscaling_policy = {
    max_replicas    = 5
    min_replicas    = 1
    cooldown_period = 60
     metric = {
      name = "agent.googleapis.com/memory/percent_used"
      target = 80
      type = "GAUGE"
      filter = "metric.label.state=\"used\""   <=== Here is the modified line in TF
    }
...
```

### References

https://cloud.google.com/monitoring/api/metrics_agent

**Comment by paddycarver** [comment]
This looks like it has been added and released, so I'm going to close this issue out.
