### ISSUE TITLE
Mapping Private IP to Compute Node

### ISSUE THREAD

**Issue by Na-Sathish** [terraform-providers/terraform-provider-google#2262]
Hi @danawillow,
Yeah, I tried with below code also giving the same error,
```
resource "google_compute_address" "static" {
  name = "${var.kafka_private_ip_name}"
  subnetwork = "${var.subnet_self_link}"
  address_type = "INTERNAL"
  region = "asia-south1" 
}  
network_interface {
    subnetwork = "${var.subnet_self_link}"
    access_config {
      nat_ip = "${google_compute_address.static.address}"
    }
}
```
**Error:** 
* google_compute_instance.virtual_instance: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].accessConfigs[0].natIP': '10.11.0.2'. The specified external IP address '10.11.0.2' was not found in region 'asia-south1'., invalid

Terraform Info after Creating `google_compute_address` :
```
network_interface.#:                                 "" => "1"
network_interface.0.access_config.#:                 "" => "1"
network_interface.0.access_config.0.assigned_nat_ip: "" => "<computed>"
network_interface.0.access_config.0.nat_ip:          "" => "10.11.0.2"
network_interface.0.access_config.0.network_tier:    "" => "<computed>"
network_interface.0.address:                         "" => "<computed>"
network_interface.0.name:                            "" => "<computed>"
network_interface.0.network_ip:                      "" => "<computed>"
network_interface.0.subnetwork:                      "" => "projects/test-project/regions/asia-south1/subnetworks/test-subnet"
network_interface.0.subnetwork_project:              "" => "<computed>"
```

_Originally posted by @Na-Sathish in https://github.com/terraform-providers/terraform-provider-google/issues/435#issuecomment-430103563_

**Comment by Chupaka** [comment]
`nat_ip` is for external addresses, you're trying to assign internal address to it.

**Comment by dev-auto-voonik** [comment]
@Chupaka ,
          Yes. I am trying to assign the internal address to compute engine and also i found the solution for that using `network_ip`.

```
resource "google_compute_address" "static" {
  name = "${var.kafka_private_ip_name}"
  subnetwork = "${var.subnet_self_link}"
  address_type = "INTERNAL"
  region = "asia-south1" 
}  
network_interface {
    subnetwork = "${var.subnet_self_link}"
    network_ip = "${google_compute_address.static.address}"
    access_config {}
}
```

**Comment by Chupaka** [comment]
Yep, that's how it should be done.

**Comment by emilymye** [comment]
Apologies, I don't have much context for this. Can you give me a brief summary? 

Alternatively, it looks like you may have found a solution. If so, please let me know if I can close this issue.

**Comment by dev-auto-voonik** [comment]
@emilymye. Sure, You can close this issue.
