### ISSUE TITLE
Add support for network endpoint groups

### ISSUE THREAD

**Issue by morgante** [terraform-providers/terraform-provider-google#2263]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We should add support for creating and managing network endpoint groups via Terraform.

REST API: https://cloud.google.com/compute/docs/reference/rest/beta/networkEndpointGroups/

### New or Affected Resource(s)

* google_compute_network_endpoint_group
* google_compute_network_endpoint

### Potential Terraform Configuration

```tf
google_compute_network_endpoint_group "mine" {
  name = "my-neg"
  description = "new-neg"
  network = "${google_compute_network.mine.selfLink}"
  subnetwork = "${google_compute_subnetwork.mysubnet.selfLink}"
  defaultPort = "90"
}

google_compute_network_endpoint "vm1" {
  endpoint_group = "${google_compute_network_endpoint_group.mine.id}"
  instance = "${google_compute_instance.mine.name}"
  port = "100"
  ipAddress = "192.167.3.10"
}
```

**Comment by josiahp** [comment]
This has been assigned to "modular-magician" for a few months yet but has yet to be autogenerated (I assume that means using the REST API to dynamically generate some terraform implementation?) Is there something I could do to help? I'm using network endpoint groups currently and I'd really like to manage them with terraform.

**Comment by danawillow** [comment]
Hey @josiahp, sorry that it's taking so long! The code is all ready to go, but there's an issue with the API itself that I'm waiting to get fixed. Once the holidays are over, I'll ping that team again to see if they have an ETA.

**Comment by boxrick** [comment]
@danawillow Hello! Did this ever get fixed?

**Comment by danawillow** [comment]
The issue with the API got fixed, but I haven't finished the resource yet. I'm taking a break from Terraform until late April, and I have it on my plate for when I get back.

**Comment by mvanholsteijn** [comment]
@danawillow when do you get back?

**Comment by bukzor** [comment]
@danawillow is there a work-in-progress branch that we can toy with?

**Comment by danawillow** [comment]
Sure- https://github.com/danawillow/magic-modules/commit/25fe50d193f9d1a0183bce35e2c93965ccc8db50. It'll need to be rebased on master, and there may have been changes to what gets put in the terraform.yaml file or the example, but you can go from there. https://github.com/GoogleCloudPlatform/magic-modules has more information on how to generate Terraform code with Magic Modules.

**Comment by danawillow** [comment]
@emilymye this can be closed now, right?

**Comment by danawillow** [comment]
Pretty sure there's nothing left to do here, but feel free to open if I'm mistaken.
