### ISSUE TITLE
Add support for configuring the message retention duration of PubSub subscriptions

### ISSUE THREAD

**Issue by pdecat** [terraform-providers/terraform-provider-google#2264]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please add support for [configuring the *message retention duration* of PubSub subscriptions](https://cloud.google.com/sdk/gcloud/reference/beta/pubsub/subscriptions/create#--message-retention-duration).

Also, PubSub [subscriptions can now be updated](https://cloud.google.com/sdk/gcloud/reference/beta/pubsub/subscriptions/update).
Edit: update was implemented as part of https://github.com/GoogleCloudPlatform/magic-modules/pull/1088

### New or Affected Resource(s)

* `google_pubsub_subscription`

### Potential Terraform Configuration

```tf
resource "google_pubsub_topic" "mytopic" {
  name = "mytopic"
}

resource "google_pubsub_subscription" "mytopic-subscription" {
  name  = "mytopic-subscription"
  topic = "${google_pubsub_topic.mytopic.name}"

  ack_deadline_seconds = "600"

  #NOTE: not implemented yet
  message_retention_duration = "48h"
}
```

### References

* https://cloud.google.com/sdk/gcloud/reference/beta/pubsub/subscriptions/create#--message-retention-duration
* https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/create#body.request_body.FIELDS.message_retention_duration

* https://cloud.google.com/sdk/gcloud/reference/beta/pubsub/subscriptions/update
* https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/patch

**Comment by pdecat** [comment]
This was apparently graduated to GA as part of the replay feature release (there's no longer any mention of alpha or beta on this field).

https://cloud.google.com/pubsub/docs/replay-overview

https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/create#body.request_body.FIELDS.message_retention_duration

https://cloud.google.com/sdk/gcloud/reference/pubsub/subscriptions/create#--message-retention-duration

@rileykarson, now that [Pubsub resources are magic-modules generated](https://github.com/GoogleCloudPlatform/magic-modules/pull/1088), do you think support for this could be implemented?

**Comment by pdecat** [comment]
Thanks @rileykarson! :tada:

**Comment by aaron-lane** [comment]
@rileykarson: Thanks for implementing this!

It appears [not to have been released with v2.2.0](https://github.com/terraform-providers/terraform-provider-google/blob/v2.2.0/google/resource_pubsub_topic.go#L41-L60). Is it targeted for v2.3.0 now?

**Comment by pdecat** [comment]
It was released in 2.2.0, I'm already using it.

**Comment by rileykarson** [comment]
@aaron-lane: It's a part of `google_pubsub_subscription`, not `google_pubsub_topic`: https://github.com/terraform-providers/terraform-provider-google/blob/v2.2.0/google/resource_pubsub_subscription.go#L69

**Comment by aaron-lane** [comment]
Some day, I'll learn to read things. Thank you!
