### ISSUE TITLE
support for google-managed ssl certificates

### ISSUE THREAD

**Issue by mblakele** [terraform-providers/terraform-provider-google#2267]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Today, `google_compute_ssl_certificate` requires a user-managed certificate and private key. According to https://cloud.google.com/load-balancing/docs/ssl-certificates#certificate-types GCP also supports google-managed certificates. It would be useful if this provider supported google-managed certs, for cases where users don't want to manage their own certs.

### New or Affected Resource(s)

* google_compute_ssl_certificate

### Potential Terraform Configuration

Google-managed certs would be generated by omitting the certificate and private key, but supplying a list of domains. Here's an excerpt from the gcloud docs:

```
    gcloud beta compute ssl-certificates create NAME
        (--domains=DOMAIN,[DOMAIN,...]
          | --certificate=LOCAL_FILE_PATH --private-key=LOCAL_FILE_PATH)
        [--description=DESCRIPTION] [GCLOUD_WIDE_FLAG ...]

DESCRIPTION
    (BETA) gcloud beta compute ssl-certificates create is used to create SSL
    certificates which can be used to configure a target HTTPS proxy. An SSL
    certificate consists of a certificate and private key. The private key is
    encrypted before it is stored.

    You can create either a managed or a self-managed SslCertificate. A managed
    SslCertificate will be provisioned and renewed for you, when you specify
    the --domains flag. A self-managed certificate is created by passing the
    certificate obtained from Certificate Authority through --certificate and
    --private-key flags.
```

Here's the first example from the current tf docs, modified to be a google-managed cert.

```tf
resource "google_compute_ssl_certificate" "default" {
  name_prefix = "my-certificate-"
  description = "a description"
  domains = ["mydomain.org", "www.mydomain.org"]

  lifecycle {
    create_before_destroy = true
  }
}
```

### References

* https://cloud.google.com/load-balancing/docs/ssl-certificates#certificate-types

**Comment by ndmckinley** [comment]
I am making pretty good progress on this, but continuing it depends on https://github.com/GoogleCloudPlatform/magic-modules/pull/640.  :)

**Comment by jamielennox** [comment]
Can the short term version of this be a data_ source for SSL certificates? To avoid secrets in state this is the sort of thing that we might reference anyway - and it would appear this will work with managed certs?

**Comment by WeetA34** [comment]
hi
any news?

**Comment by ndmckinley** [comment]
Hi there!  As the new overrides system is done, this is unblocked.  Just gotta find the hours in the day.  :)  I see it's widely requested, so rest assured, it's a priority!

**Comment by cemo** [comment]
@ndmckinley is there any progress on this? We are desperately need it.

**Comment by ndmckinley** [comment]
No updates right now, I'm afraid.  But since the 2.0.0 release went out this morning, there are a lot more hours in the day to devote to this sort of thing, for what that's worth.

**Comment by WeetA34** [comment]
Hi

Until Google releases the official support of managed certificates, i created a magic-modules patch to be able to use them with google-cloud-beta terraform provider.

I didn't propose it as Pull Request because i'm not a magic-modules expert and i just modify the products/compute/api.yaml and products/compute/terraform.yaml for my needs.

**Warning !! Don't compile ga google cloud terraform provider with this magic-modules patch. Don't use this custom google-cloud-beta provider for creating standard static certificates. Just it for managed certificates.**

FYI, i added the following attributes:
- managed
- managed.domains[]
- managed.status
- managed.domainStatus
- selfManaged
- selfManaged.certificate
- selfManaged.privateKey
- type
- subjectAlternativeNames[]
- expireTime

As you don't provide certificate and private_key when you use managed certificates, i had to set certificate and private_key as output attribute. That's why i warned to not using it for standard static certificates.

[magic-modules_managed_certs.patch.txt](https://github.com/terraform-providers/terraform-provider-google/files/2869865/magic-modules_managed_certs.patch.txt)

```
provider "google-beta" {
  region      = "${var.region}"
  project     = "${var.project}"
  credentials = "${var.credentials}"
  zone        = "${var.zone}"
}

resource "google_compute_ssl_certificate" "default" {
  provider = "google-beta"
  name     = "ssl_cert"
  type     = "MANAGED"
  managed  = {
    domains = [
      "myhost.mydomain.tld"
    ]
  }
}

resource "google_compute_global_address" "default" {
  name = "default_address"
}

resource "google_dns_record_set" "default" {
  name = "myhost.mydomain.tld."
  type = "A"
  ttl  = "300"

  managed_zone = "dns-zone-name"

  rrdatas = [
    "${google_compute_global_address.default.address}"
  ]
}
```

More information regarding magic-modules: https://github.com/GoogleCloudPlatform/magic-modules

**Comment by WeetA34** [comment]
Just after resource creation
```
$ gcloud beta compute ssl-certificates list
NAME                 TYPE     CREATION_TIMESTAMP             EXPIRE_TIME  MANAGED_STATUS
<ssl_cert_name>  MANAGED  2019-02-15T01:50:40.587-08:00               PROVISIONING
    <fqdn>: PROVISIONING
```

After automatic DNS validation (done every ... minute(s))
```
$ gcloud beta compute ssl-certificates list
NAME                 TYPE     CREATION_TIMESTAMP             EXPIRE_TIME                    MANAGED_STATUS
<ssl_cert_name>  MANAGED  2019-02-15T01:50:40.587-08:00  2019-05-16T02:00:27.000-07:00  ACTIVE
    <fqdn>: ACTIVE
```

**Comment by WeetA34** [comment]
terraform show sample
```
google_compute_ssl_certificate.default:
  id = ssl-cert-name
  certificate = -----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----

  certificate_id = 0123456789012345678
  creation_timestamp = 2019-02-15T01:50:40.587-08:00
  description =
  expire_time = 2019-05-16T02:00:27.000-07:00
  managed.# = 1
  managed.0.domain_status.% = 1
  managed.0.domain_status.myhost.mydomain.tld = ACTIVE
  managed.0.domains.# = 1
  managed.0.domains.0 = myhost.mydomain.tld
  managed.0.status = ACTIVE
  name = ssl-cert-name
  private_key =
  project = gcp-project
  self_link = https://www.googleapis.com/compute/v1/projects/gcp-project/global/sslCertificates/ssl-cert-name
  self_managed.# = 0
  subject_alternative_names.# = 1
  subject_alternative_names.0 = myhost.mydomain.tld
  type = MANAGED
```

**Comment by WeetA34** [comment]
From GCP beta APi doc (https://cloud.google.com/compute/docs/reference/rest/beta/sslCertificates/insert),
status should be an enum with the following values:
- PENDING
- RUNNING
- DONE

For now, i've only seen PROVISIONING and ACTIVE 😄

**Comment by ndmckinley** [comment]
Made progress on this one - it's out for an initial review.  https://github.com/GoogleCloudPlatform/magic-modules/pull/1420.

**Comment by ndmckinley** [comment]
This will be in the next release of Terraform.  It's beta-provider-only for the moment.

**Comment by jaceq** [comment]
This is already released in google-beta 2.1.0 (and I already use it).

**Comment by rileykarson** [comment]
Ah yup, looks like we missed out on closing this out when we added the feature.

**Comment by thnee** [comment]
How was this implemented and documented? The docs for `google_compute_ssl_certificate` still says that `certificate` and `private_key` are required. Correct me if I am wrong, but when reading [this documentation](https://www.terraform.io/docs/providers/google/provider_versions.html) I would assume to find the result of this issue documented on [this page](https://www.terraform.io/docs/providers/google/r/compute_ssl_certificate.html), yes?

**Comment by ndmckinley** [comment]
Those docs are here - https://www.terraform.io/docs/providers/google/r/compute_managed_ssl_certificate.html.  They aren't linked in the sidebar, sorry - working on that!

**Comment by thnee** [comment]
It seems that the `type` argument is not correctly documented. It says that there is a choice between `SELF_MANAGED` or `MANAGED`, but the code only accepts `MANAGED` as a choice. It seems to me that it does not make much sense to have a `type` attribute at all for this resource? Sorry for commenting this on a closed issue, let me know if I should report it somewhere else.

**Comment by ndmckinley** [comment]
Ah, that is an oversight - I'll update that.

**Comment by ndmckinley** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/1502
