### ISSUE TITLE
Support Private IP for google_sql_database_instance resource

### ISSUE THREAD

**Issue by nabadger** [terraform-providers/terraform-provider-google#2273]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The WebUI at console.cloud.google.com introduces a Beta feature to lets you specify private IP connectivity (on 2nd generation instances).

We noticed that when provisioning the instance through the terraform module there is no such option, and our read-only slaves are replicating via the public-ip.

We would like the private-ip option to be available in terrform - the reduced latency / increased-reliability we would get from having master/slave replication take place only in the google network would be a great benefit.

### New or Affected Resource(s)

* google_sql_database_instance

### Potential Terraform Configuration

```tf
resource "google_sql_database_instance" "master" {
  name              = "db name"
  project           = "my project"
  region            = "${var.region}"

  settings {
    tier            = "${var.tier}"
     ...
    ip_configuration {
      require_ssl  = false
      ipv4_enabled = true
      private_ip_enabled = true
      public_ip_enabled = false
    }
```

### References

* https://cloud.google.com/sql/docs/mysql/private-ip

**Comment by pdecat** [comment]
Same as https://github.com/terraform-providers/terraform-provider-google/issues/2127 ?

**Comment by nabadger** [comment]
@pdecat yeah, this looks like a duplicate.

**Comment by chrisst** [comment]
Closing as duplicate. Let me know if you imagined something different than #2127
