### ISSUE TITLE
auto_create_routes false no longer supported for google_compute_network_peering

### ISSUE THREAD

**Issue by bluemalkin** [terraform-providers/terraform-provider-google#2281]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.8
+ provider.google v1.18.0
```

### Affected Resource(s)

* google_compute_network_peering

### Terraform Configuration Files

```
resource "google_compute_network_peering" "net-prd-0" {
  name               = "net-prd-0"
  auto_create_routes = "false"
  network            = "${google_compute_network.default.self_link}"
  peer_network       = "${data.google_compute_network.net-prd-0.self_link}"
}
```

### Debug Output

```
* google_compute_network_peering.net-prd-0: Error adding network peering: googleapi: Error 400: Only full mesh configuration across peered networks is supported currently (autoCreateRoutes must be set to true in the API request)., badRequest
```

### Expected Behavior

Create the peering connection without setting up the routes

### Actual Behavior

Peering creation fails when auto_create_routes is set to false. It looks like it's no longer supported. Is there a workaround ? 

I also noticed that even if I setup routes manually, there does not seem to be an option to select peering as the next hop according to the resource docs at https://www.terraform.io/docs/providers/google/r/compute_route.html

**Comment by emilymye** [comment]
Hi @bluemalkin! I think currently manual routes are not implemented in GCP, so the API just only accepts `autoCreateRoutes = true` for network peering and routes `nextHopNetwork` is output only. This isn't reflected in the documentation, but it's how the API behaves. @ndmckinley to confirm?

I'm reluctant to enforce validation or removal of this field in Terraform, in case this feature is actually being released soon (see disclaimer). If we can get them to formally change the documentation or if some new feature gets announced, we'll change Terraform then to match, but I would rather not formalize TF behavior based off the undocumented request behavior. We can at least add a warning in the TF docs in case people run into it?

**Disclaimer**: This is just a personal assumption about why the API behaves differently than documentated behavior. As someone who works at Google, I do not actually know whether this feature is being implemeted and couldn't relay such knowledge if I had it :P If you really need this, we can certainly reach out to the corresponding GCP team to see if they have public plans to implement this feature.
