### ISSUE TITLE
google_container_cluster regional clusters are GA and not beta anymore

### ISSUE THREAD

**Issue by idsvandermolen** [terraform-providers/terraform-provider-google#2286]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.8
+ provider.google v1.19.1

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
provider "google" {}

resource "google_container_cluster" "primary" {
  name   = "primary"
  region = "europe-west4"
}
```

### Expected Behavior
`terraform validate` should not complain

### Actual Behavior
`terraform validate` complains about `region` being a beta / deprecated:
```
Warning: google_container_cluster.primary: "region": [DEPRECATED] This field is in beta and will be removed from this provider. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.
```

### Steps to Reproduce

1. create file with terraform config
1. `terraform init`
1. `terraform validate`

### Important Factoids
Terraform docs 
https://www.terraform.io/docs/providers/google/r/container_cluster.html#region also mark `region` as beta, however Regional Clusters have been GA since June: https://cloud.google.com/blog/products/gcp/regional-clusters-in-google-kubernetes-engine-are-now-generally-available

**Comment by danawillow** [comment]
Neat! Probably yes, but I'd check the PR that added the deprecation warning just to make sure it didn't do anything else.

**Comment by smaslennikov** [comment]
The docs [still](https://www.terraform.io/docs/providers/google/r/container_node_pool.html#argument-reference) specify `region` as a beta attribute.

`google_container_node_pool` is also affected by the same issue, is that intended?

**Comment by ndmckinley** [comment]
It's on `master`, but I don't think it's present in any of our releases yet.  Github doesn't seem to think so.  That would explain the docs situation.
