### ISSUE TITLE
Support for "Requester Pays" for GCS buckets

### ISSUE THREAD

**Issue by skinnykini** [terraform-providers/terraform-provider-google#2332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Provide Terraform support for enabling/disabling Requester Pays feature on GCS buckets. API details - https://cloud.google.com/storage/docs/json_api/v1/buckets

### New or Affected Resource(s)

* google_storage_bucket

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by lawrenae** [comment]
Is there an issue if I start working up a PR for this? Is someone else already in progress?

**Comment by lawrenae** [comment]
PR  #2402 opened for this
