### ISSUE TITLE
GKE: min_master_version is empty

### ISSUE THREAD

**Issue by paolomainardi** [terraform-providers/terraform-provider-google#2348]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
terraform --version
Terraform v0.11.10
+ provider.google v1.19.1
```

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf

variable "k8s_version" {
  default = "1.10.7-gke.6"
}

resource "google_container_cluster" "primary" {
  name               = "gke-cluster"
  description        = ""
  zone               = "europe-west1-b"
  enable_legacy_abac = false
  min_master_version = "${var.k8s_version}"

  master_auth {
    username = "admin"
    password = "admin"
  }

  maintenance_policy {
    daily_maintenance_window {
      start_time = "03:00"
    }
  }

  addons_config {
    kubernetes_dashboard {
      disabled = true
    }
  }
}
```

### Debug Output

```
Terraform will perform the following actions:

  ~ google_container_cluster.primary
      min_master_version: "" => "1.10.7-gke.6"

  ~ google_container_node_pool.default-pool
      version:            "1.10.7-gke.2" => "1.10.7-gke.6"

  ~ google_container_node_pool.default-pool-n4
      version:            "1.10.7-gke.2" => "1.10.7-gke.6"

  ~ google_container_node_pool.gitlab-ci-build-preemptible
      version:            "1.10.7-gke.2" => "1.10.7-gke.6"
```

### Expected Behavior

The `min_master_version` should not be empty as it is already on `1.10.7-gke.6`

### Actual Behavior

The `min_master_version` is showed as empty.

### Steps to Reproduce

1. Create the cluster manually
2. Import the cluster with `terraform import`

**Comment by danawillow** [comment]
Hey @paolomainardi, I'm going to go ahead and mark this as blocked by upstream terraform.

When a resource is imported, the code only has access to the id that it was imported with and not any information that was in the config. This means that at import time, we can't see the min_master_version that you set in your config. And although we could potentially set it based on the version upstream, we would have to do that in the read function (which isn't import specific), which would defeat the purpose of the field in the first place (see #577)

**Comment by paolomainardi** [comment]
Ok thanks a lot for the explanation @danawillow 
My only concern now is what will happen at the next run, because the master is already on "1.10.7-gke.6" version.

**Comment by danawillow** [comment]
From just looking at the code, I don't think anything will happen. If you want to be extra sure though, you could spin up a small test cluster and import it and see what happens on the next run.

**Comment by rileykarson** [comment]
This is reconciled to the best of the provider's current ability by documenting the behaviour at https://www.terraform.io/docs/providers/google/r/container_cluster.html#min_master_version-1.
