### ISSUE TITLE
Non-idempotent resources on default values/different formats

### ISSUE THREAD

**Issue by johnsonj** [terraform-providers/terraform-provider-google#235]
### Terraform Version
0.9.11

### Affected Resource(s)
- google_compute_firewall
- google_compute_target_pool
- google_compute_forwarding_rule

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
Repro snippet. `>>>` means I had to add the line to prevent it from being recreated, `<<<` means I had to remove the line. 
```hcl
resource "google_compute_firewall" "jumpbox-external" {
  name        = "${var.env_name}-jumpbox-external"
  network     = "${google_compute_network.pcf-network.name}"
  target_tags = ["${var.env_name}-jumpbox-external"]

  allow {
    protocol = "icmp"
  }

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }

>>>  source_ranges = ["0.0.0.0/0"]
}

resource "google_compute_target_pool" "cf-ws" {
  name = "${var.env_name}-cf-ws"

  health_checks = [
    "${google_compute_http_health_check.cf-public.name}",
  ]

>>>  session_affinity = "NONE"
}


resource "google_compute_forwarding_rule" "cf-ws-https" {
  name        = "${var.env_name}-cf-ws-https"
  target      = "${google_compute_target_pool.cf-ws.self_link}"
<<<  port_range  = "443"
>>>  port_range  = "443-443"
  ip_protocol = "TCP"
  ip_address  = "${google_compute_address.cf-ws.address}"
}
```

### Expected Behavior
Resources should not re-create or need to be modified

### Actual Behavior
Every `terraform apply` would cause the resources to re-create or be updated

### Steps to Reproduce
1. `terraform deploy`
2. `terraform apply`

### Important Factoids
There shouldn't be. This doesn't seem like a new bug, I've been seeing this in our [bosh docs](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/bosh/main.tf#L70) for a while.

**Comment by danawillow** [comment]
Hmm, I'm having trouble reproducing this. Here's my full tf config that I'm using. I did an apply and then a plan and the plan showed no changes. What am I missing?

```hcl
variable "env_name" {
  default = "test"
}

resource "google_compute_firewall" "jumpbox-external" {
  name        = "${var.env_name}-jumpbox-external"
  network     = "${google_compute_network.pcf-network.name}"
  target_tags = ["${var.env_name}-jumpbox-external"]

  allow {
    protocol = "icmp"
  }

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }
}

resource "google_compute_network" "pcf-network" {
  name                    = "test-jeff-network"
  auto_create_subnetworks = "true"
}

resource "google_compute_target_pool" "cf-ws" {
  name = "${var.env_name}-cf-ws"

  health_checks = [
    "${google_compute_http_health_check.cf-public.name}",
  ]
}

resource "google_compute_http_health_check" "cf-public" {
  name         = "test-health-check"
  request_path = "/health_check"

  timeout_sec        = 1
  check_interval_sec = 1
}

resource "google_compute_forwarding_rule" "cf-ws-https" {
  name        = "${var.env_name}-cf-ws-https"
  target      = "${google_compute_target_pool.cf-ws.self_link}"
  port_range  = "443"
  ip_protocol = "TCP"
  ip_address  = "${google_compute_address.cf-ws.address}"
}

resource "google_compute_address" "cf-ws" {
  name = "test-jeff-address"
}
```

**Comment by johnsonj** [comment]
Maybe the small repro is problematic? Your config looks right.

Here's where I yanked the code from: [terraforming-gcp](https://github.com/pivotal-cf/terraforming-gcp)

**Comment by danawillow** [comment]
@johnsonj is this still happening?

**Comment by johnsonj** [comment]
I'll re-open if I notice it again, thanks!
