### ISSUE TITLE
[Feature Request] Add support for GuestOsFeatures

### ISSUE THREAD

**Issue by ldevulder** [terraform-providers/terraform-provider-google#2366]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We use Terraform in our company to provision VM on GCP and we would like to use the MULTI_IP_SUBNET feature provided by the '--guest-os-features' option. But we were not able to use it with terraform-provider-google, it seems to be an unavailable option.

Supporting GuestOsFeatures could be very useful to add other features like UEFI_COMPATIBLE or VIRTIO_SCSI_MULTIQUEUE through Terraform.

More information about GuestOsFeatures available [here](https://cloud.google.com/compute/docs/images/create-delete-deprecate-private-images#guest-os-features).

### New or Affected Resource(s)

* google_compute_image

### Potential Terraform Configuration

```tf
resource "google_compute_image" "bootable-image" {
  name = "my-custom-image"
  guest_os_features = [ "MULTI_IP_SUBNET", "SECURE_BOOT" ]
}
```

**Comment by hsehic** [comment]
this approach should be very useful if you want to have virtual IP RA in your cluster on GCP
