### ISSUE TITLE
Add resources for Cloud Task Queues

### ISSUE THREAD

**Issue by zombiezen** [terraform-providers/terraform-provider-google#2367]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

[Google Cloud Tasks](https://cloud.google.com/tasks/) is a service that provides task queues for App Engine apps. Unlike App Engine task queues, they are managed through a REST API. Ideally, these could be provisioned using Terraform.

### New or Affected Resource(s)

* google_task_locations
* google_task_queue

### Potential Terraform Configuration

```tf
data "google_task_locations" "all" {
  project = "my-project"
}

resource "google_task_queue" "foo" {
  parent = "projects/my-project/locations/${data.google_task_locations.locations[0]}"
  name = "foo"
  rateLimits = ...
  retryConfig = ...
  appEngineRouting = ...
}
```

### References

- [REST API](https://cloud.google.com/tasks/docs/reference/rest/)
- [gRPC API](https://cloud.google.com/tasks/docs/reference/rpc/google.cloud.tasks.v2beta3)

**Comment by mccall114** [comment]
I've started a local branch for this, just need to write tests. Never contributed to this repo before -- do I need permission to push my branch?

**Comment by rileykarson** [comment]
If you fork the repo (for example, I forked to https://github.com/rileykarson/terraform-provider-google) and push your branch there, you can make a pull request against the repo.

**Comment by JasperWoo** [comment]
What's the status of development for this feature?

**Comment by rambleraptor** [comment]
Hello! I can take a look at this.

**Comment by rileykarson** [comment]
Hey @mccall114! A member of my team (@rambleraptor above) was interested in picking up this feature. If you've got substantial work staged on the feature, please let me know so that both of you don't repeat too much of the same work!

**Comment by mccall114** [comment]
Hey @rileykarson & @rambleraptor. I got a lot of the functionality working in [this branch](https://github.com/mccall114/terraform-provider-google/tree/issue-2367-cloud-task-queue-resources) of my fork. I didn't get around to finishing the tests, so feel free to pick up from where I left off or do your own thing.

**Comment by kdp8791** [comment]
Hi @mccall114 / @rambleraptor, any updates on when the Cloud Tasks changes will be available for use? Thank you!

**Comment by slevenick** [comment]
This was fixed via https://github.com/GoogleCloudPlatform/magic-modules/pull/2662

and will be available soon
