### ISSUE TITLE
Error creating IAM binding into a pubsub topic right after creating pubsub topic.

### ISSUE THREAD

**Issue by wisoot** [terraform-providers/terraform-provider-google#2384]
Hi,

I encounter the issue when I created a pubsub topic then right away created an iam for the topic, then terraform throw error saying the topic is not found. However, if I run apply again, it will work.

Seem like when I'm trying to bind publisher IAM into the topic right after the topic has been created, there is not enough time between them to allow Topic to be able to get provisioned properly before binding step happen.

I've tried to look for the same issue but I couldn't find anything. If this issue has been reported please direct me to the ticket.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

v0.11.8

### Affected Resource(s)

* google_pubsub

### Terraform Configuration Files

```tf
resource "google_pubsub_topic" "topic" {
  name = "segment.test.topic"
}

resource "google_pubsub_topic_iam_binding" "pubsub_topic_iam" {
  topic = "segment.test.topic"
  role = "roles/pubsub.publisher"
  members = ["user:pubsub@segment-integrations.iam.gserviceaccount.com"]
}
```

### Debug Output

```
Error: Error applying plan:

1 error(s) occurred:

* google_pubsub_topic_iam_binding.pubsub_topic_iam: 1 error(s) occurred:

* google_pubsub_topic_iam_binding.pubsub_topic_iam: Error retrieving IAM policy for pubsub topic "projects/[project_name]/topics/segment.test.topic": googleapi: Error 404: Resource not found (resource=segment.test.topic)., notFound

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Expected Behavior

* Google pubsub topic was created
* Publisher was added into the topic

### Actual Behavior

* Google pubsub topic was created
* Publisher was not added into the topic

### Steps to Reproduce

1. `terraform apply`

**Comment by Chupaka** [comment]
You're trying to create them simultaneously. You need some sort of dependency. For example,
topic = "${google_pubsub_topic.topic.name}"

**Comment by wisoot** [comment]
That make sense. Thank you so much for your answer.

**Comment by wyardley** [comment]
This is true, but normally, Terraform should be able to figure these out properly without an explicit dependency. I opened #2765, which describes the exact same issue.

**Comment by Chupaka** [comment]
Please close #2765 for exactly the same reason :)
