### ISSUE TITLE
Add (beta) support for Node Auto-Provisioning on GKE clusters

### ISSUE THREAD

**Issue by wmuizelaar** [terraform-providers/terraform-provider-google#2388]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
The new Node Autoprovisioning feature is released in beta for GKE clusters. I would like the provider to support it, so the limits and boundaries of the feature can be set. See https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning for details.

Automatically provisioning nodes based on usage request would help the administration of nodepools enormously. 

There is also an option where existing nodepools can be marked as auto-provisioned (and then deleteable) or new nodepools can be altered to be specifically managed. This combined with the terraform support for defining nodepools can become interesting, since probably nodepools that are auto-created should be ignored by terraform, and vice versa. 

### New or Affected Resource(s)

* google_container_cluster
* google_container_nodepool

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "clustername" {
  provider           = "google-beta"
  name               = "clustername"
  region             = "europe-west4"
  project            = "projectname"
  min_master_version = "1.10.7-gke.6"
  enable_legacy_abac = false
  network            = "networkname"
  subnetwork         = "subnetworkname"

  resource_labels {
    foo = "bar"
    state = "stable"
  }


  master_auth {
    username = ""
    password = ""
  }

  addons_config {
    http_load_balancing {
      disabled = false
    }
    horizontal_pod_autoscaling {
      disabled = false
    }
    kubernetes_dashboard {
      disabled = true
    }
    network_policy_config {
      disabled = false
    }
  }

  network_policy {
    provider = "CALICO"
    enabled = true
  }

  pod_security_policy_config {
    enabled = true
  }

  maintenance_policy {
    daily_maintenance_window {
      start_time = "02:00"
    }
  }

  ip_allocation_policy {
    cluster_secondary_range_name = "range-pods"
    services_secondary_range_name = "range-services"
  }

  private_cluster_config {
    enable_private_nodes = "true"
    master_ipv4_cidr_block = "172.16.0.16/28"
  }

  master_authorized_networks_config {
    cidr_blocks = [
      { cidr_block = "1.2.3.4/24", display_name = "range1" },
    ]
  }

  autoprovisioning_config {
    max-cpu = 16
    max-memory = 64
    max-accelerator [
      { type = "nvidia-tesla-k80", count = 4}
    ]
  }

  lifecycle {
    ignore_changes = ["node_pool"]
  }
  initial_node_count = 1
  remove_default_node_pool = true

}

```

See the `autoprovisioning_config` block for the actual example.

**Comment by ndmckinley** [comment]
Sure thing, I'll see what I can do.

**Comment by ndmckinley** [comment]
I've got this running through code generation right now - however, unless you're a member of the `1.11.2` EAP, it seems that your k8s master is not going to support node autoscaling yet.  Are you a member of that EAP?  If so, I can try to get myself access to it and do some further testing before releasing it.  Otherwise, I intend to keep it unreleased until `1.11.2` becomes publicly available.

**Comment by wmuizelaar** [comment]
I'm not a member of the EAP, but have access to 1.11.2-gke.9 - it became available publicly a couple of days ago.

**Comment by ndmckinley** [comment]
Fantastic!  I'll go revise our tests and get this out and available.  Thanks!

**Comment by rvlzzr** [comment]
Any update/timeline on this?

**Comment by rileykarson** [comment]
Hey @rvlzzr! We don't have a specific timeline, but looking at the [beta downstream](https://github.com/terraform-providers/terraform-provider-google-beta/pull/93) of the [Magic Modules PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/694), we're waiting on the ability to test this.

**Comment by ndmckinley** [comment]
Hey @rvlzzr - @rileykarson is totally right, I'm struggling to test this due to a quirk of the GCP SDK.  We'll get there, though!  :)

**Comment by ndmckinley** [comment]
Got it mostly together!  This should get merged soon.
