### ISSUE TITLE
Newly created bigtable cluster wants to recreate on every apply

### ISSUE THREAD

**Issue by wyardley** [terraform-providers/terraform-provider-google#2400]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.11.10
+ provider.google v1.19.1
+ provider.null v1.0.0
```

### Affected Resource(s)
* google_bigtable_instance

### Terraform Configuration Files
```tf
resource "google_bigtable_instance" "instance" {
  name = "foo"

  cluster {
    cluster_id   = "foo"
    zone         = "${local.zone}"
    num_nodes    = 1
    storage_type = "SSD"
  }
}
```

### Debug Output
I can gist this to you and send you the link on GCP Slack in #terraform if it's needed.

### Expected Behavior
Nothing

### Actual Behavior
```
Terraform will perform the following actions:

  ~ google_bigtable_instance.instance
      cluster.1044552912.cluster_id:       "" => "foo"
      cluster.1044552912.num_nodes:        "" => "1"
      cluster.1044552912.storage_type:     "" => "SSD"
      cluster.1044552912.zone:             "" => "us-central1-a"
      cluster.3016384818.cluster_id:       "foo" => ""
      cluster.3016384818.num_nodes:        "0" => "0"
      cluster.3016384818.storage_type:     "SSD" => ""
      cluster.3016384818.zone:             "us-central1-a" => "us-central1-a"
```

Also, if I let it make those changes, the next run gives me:
```
* google_bigtable_instance.instance: google_bigtable_instance.instance: Error retrieving cluster "": rpc error: code = InvalidArgument desc = When parsing 'projects/xxx/instances/user-data-1/clusters/' : Cluster name expected in the form 'projects/<project_id>/instances/<instance_id>/clusters/<cluster_id>'.
```
### Steps to Reproduce

1. `terraform apply`

It seems as if the cluster ID is changing under the hood. I can repro this just by deleting and re-creating the cluster. This is especially annoying since I also can't import this resource still (#932)

**Comment by rileykarson** [comment]
Terraform won't let `num_nodes` of `1` being specified anymore which had a weird and unexpected behaviour. For completeness, `num_nodes` must be set to 3 or higher for a `PRODUCTION` instance, and must be left unset for `DEVELOPMENT` instances.

The weird behaviour being encountered here was that a `PRODUCTION` instance with a `num_nodes` of `1` didn't fail in the API as expected, but instead created a `DEVELOPMENT` instance. They don't *have* a `num_nodes`, leading to the diff from `0` in state (based on reading the API) and `1` as specified in config.
