### ISSUE TITLE
wrong docs in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ensonic** [terraform-providers/terraform-provider-google#2403]
The docs tell what env-vars to set, but some apparently need to be set to a specific value:

```
-- FAIL: TestAccComputeRegionBackendService_withBackendAndUpdate (0.00s)
    provider_test.go:91: One of GOOGLE_REGION, GCLOUD_REGION, CLOUDSDK_COMPUTE_REGION must be set to us-central1 for acceptance tests
--- FAIL: TestAccComputeTargetTcpProxy_TargetTcpProxyBasicExample (0.01s)
    provider_test.go:91: One of GOOGLE_REGION, GCLOUD_REGION, CLOUDSDK_COMPUTE_REGION must be set to us-central1 for acceptance tests
```

here `GOOGLE_REGION=us-central1` is required.

Other variables like GOOGLE_ORG are not obvious to what values they should be set.

Finally I'd expect to see what command I should use to run all tests (just `make testacc`?)

**Comment by ndmckinley** [comment]
Thanks for calling that out!  I'm on it.  :)

**Comment by ensonic** [comment]
Thanks!
