### ISSUE TITLE
resource google_compute_project_metadata doesn't support import

### ISSUE THREAD

**Issue by tmessinis** [terraform-providers/terraform-provider-google#2414]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

---

Importing project metadata is not supported. Is there any plan to add import support for this resource? Additionally this information is not included in the documentation for the resource: https://www.terraform.io/docs/providers/google/r/compute_project_metadata.html

### Terraform Version
Terraform v0.11.10

### Affected Resource(s)

* google_compute_project_metadata

### Debug Output
```
terraform import module.<module name>.google_compute_project_metadata.project common_metadata
module.<module name>.google_compute_project_metadata.project: Importing from ID "common_metadata"...

Error: module.<module name>.google_compute_project_metadata.project (import id: common_metadata): import module.<module name>.google_compute_project_metadata.project (id: common_metadata): resource google_compute_project_metadata doesn't support import
```

### Expected Behavior
Terraform imports the project metadata.

### Actual Behavior
Terraform fails with the following error `resource google_compute_project_metadata doesn't support import`

### Steps to Reproduce

1. `terraform import module.<module name>.google_compute_project_metadata.project common_metadata`

**Comment by ndmckinley** [comment]
Fixed in both beta and ga providers.

**Comment by smaslennikov** [comment]
@ndmckinley I'm also hitting this issue, running:
- Terraform v0.11.11
- provider.google v1.19.1

Initially I hit this on terraform 0.11.10, since then I've updated to 0.11.11 and rerun `terraform init`. Are there any other steps needed to get the updated GA version?

**Comment by rileykarson** [comment]
Hey @smaslennikov!

Sorry for the confusion here- adding `import` support for this resource meant we had to make a breaking change that's part of our `2.0.0` release. We expected to release it sooner than we have, so while it works on `master`@HEAD, it hasn't appeared in a release and it won't until `2.0.0`, even if there are more `1.X` series releases before then.

**Comment by smaslennikov** [comment]
@rileykarson Thanks for the explanation! I'll be awaiting the 2.0.0 release then. Cheers!
