### ISSUE TITLE
Cloud Composer image_version input 

### ISSUE THREAD

**Issue by michyliao** [terraform-providers/terraform-provider-google#2429]
I am trying to create a composer instance with a specific image_version `composer-1.3.0-airflow-1.10.0` , but the parameter is not set and getting this error when I do a terraform plan

`Error: module.composer.google_composer_environment.ds_services_composer: "config.0.software_config.0.image_version": this field cannot be set`

Can this parameter get added to the resource when we want to deploy a certain version of composer/airflow?

**Comment by memosstilvi** [comment]
I would like to give this a shot, if there is no one else working on this atm.

**Comment by memosstilvi** [comment]
Would be nice to add support for the Python version as well.

**Comment by danawillow** [comment]
Added in https://github.com/terraform-providers/terraform-provider-google-beta/pull/174
