### ISSUE TITLE
Travis doesn't run on terraform-google-provider-beta

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#2437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

https://github.com/terraform-providers/terraform-provider-google-beta has no Travis runs; I'm assuming @paddycarver needs to set this up, so I'm assigning him.

**Comment by paddycarver** [comment]
I've clicked the button to activate the build! I think this is good now, let me know if it's not and I'll dig some more.
