### ISSUE TITLE
google_compute_attached_disk doesn't work on regional persistent disks

### ISSUE THREAD

**Issue by mcclunge** [terraform-providers/terraform-provider-google#2441]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_attached_disk

### Expected Behavior

Be able to attach a regional persistent disk using google_compute_attached_disk 

### Actual Behavior

google_compute_attached_disk tries attaching a disk in the same zone as the instance it's trying to attach to.
Ex:
projects/{project-name}/zones/{zone-name}/disks/{disk-name}
Instead of:
projects/{project-name}/regions/{region}/disks/{disk-name}"

**Comment by chrisst** [comment]
Will be fixed in 2.0.0
