### ISSUE TITLE
Feature request: IPV6 Loadbalancing support

### ISSUE THREAD

**Issue by renchap** [terraform-providers/terraform-provider-google#245]
Overview: https://cloud.google.com/compute/docs/load-balancing/ipv6

This will require changes to `google_compute_address` and `google_compute_global_forwarding_rule ` with a new `ipVersion` attribute.

**Comment by rileykarson** [comment]
Linking to #93 since it looks like `ipVersion` is in Beta for each.

**Comment by rileykarson** [comment]
Closed with #250 and #265.

**Comment by renchap** [comment]
@rileykarson this feature is now in GA, should I create a separate ticket to support it?
https://cloudplatform.googleblog.com/2017/09/announcing-ipv6-global-load-balancing-ga.html

**Comment by rosbo** [comment]
@renchap I created a new ticket tracking this work. #445. Thank you
