### ISSUE TITLE
Layout issue in Composer Environment website

### ISSUE THREAD

**Issue by juliosueiras** [terraform-providers/terraform-provider-google#2465]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* google_composer_environment

### Expected Behavior

Proper Layout on the docs

### Actual Behavior

<img width="1280" alt="screen shot 2018-11-13 at 2 08 22 pm" src="https://user-images.githubusercontent.com/3680302/48436903-ec6f1100-e74d-11e8-9095-6cb14ec035b5.png">

### Steps to Reproduce

1 go to https://www.terraform.io/docs/providers/google/r/composer_environment.html

**Comment by rileykarson** [comment]
Thanks for the report @juliosueiras!

This was fixed at HEAD with https://github.com/terraform-providers/terraform-provider-google/pull/2299, so I'm going to close this out. If the bad formatting is a major blocker for you please let us know, and we'll look at cutting a website release.

**Comment by juliosueiras** [comment]
Thats fine, and thanks =)
