### ISSUE TITLE
google_container_cluster - unable to set beta logging/monitoring on existing cluster

### ISSUE THREAD

**Issue by bluemalkin** [terraform-providers/terraform-provider-google#2472]
### Terraform Version
```
Terraform v0.11.10
+ provider.google v1.19.1
+ provider.google-beta v1.19.0
```
### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```
resource "google_container_cluster" "gke-0" {
  provider = "google-beta"
.....
  logging_service    = "logging.googleapis.com/kubernetes"
  monitoring_service = "monitoring.googleapis.com/kubernetes"
}
```

### Debug Output

```
Terraform will perform the following actions:

  ~ google_container_cluster.gke-0
      logging_service:    "logging.googleapis.com" => "logging.googleapis.com/kubernetes"
      monitoring_service: "monitoring.googleapis.com" => "monitoring.googleapis.com/kubernetes"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_container_cluster.gke-0: Modifying... (ID: ops-stg-gke-0)
  logging_service:    "logging.googleapis.com" => "logging.googleapis.com/kubernetes"
  monitoring_service: "monitoring.googleapis.com" => "monitoring.googleapis.com/kubernetes"

Error: Error applying plan:

1 error(s) occurred:

* google_container_cluster.gke-0: 1 error(s) occurred:

* google_container_cluster.gke-0: googleapi: Error 400: "logging.googleapis.com/kubernetes" and "monitoring.googleapis.com/kubernetes" can only be set together (was "" and "monitoring.googleapis.com/kubernetes")., badRequest
```
### Expected Behavior

On an existing cluster the monitoring and logging to be changed to beta.

### Actual Behavior

Unable to apply. Instead I had to edit the cluster manually in the console and tick beta then save.

Sub-sequent terraform plan detected no changes.

**Comment by jurschel** [comment]
I have found that if you take the /kubernetes off that it will actually work but it won't do both at the same time.  It takes 2 runs for it to apply both for some reason.  Has anybody else experienced the same issue?

**Comment by danawillow** [comment]
Looks like we need to change from using [setLogging](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters/setLogging) to [update](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters/update)

**Comment by bryanlarsen** [comment]
The fix was merged 7 days ago; provider.google v1.20 was released 5 days ago.   Was the fix not included in 1.20 or am I doing something else wrong?

**Comment by jurschel** [comment]
My recent deployments aren't experiencing the problem so from my perspective it looks fixed.  What providers are you using?

**Comment by bryanlarsen** [comment]
* provider.aws: version = "~> 1.52"
* provider.google: version = "~> 1.20"
* provider.google-beta: version = "~> 1.20"
* provider.kubernetes: version = "~> 1.4"
* provider.local: version = "~> 1.1"

After I manually switched the cluster to beta monitoring Terraform did notice the change and stop trying to apply it (and thus stopped giving an error applying the change)
