### ISSUE TITLE
google_compute_image: The resource '(a public-readable image tar)' of type 'Google Cloud Storage object' was not found.

### ISSUE THREAD

**Issue by haokanga** [terraform-providers/terraform-provider-google#2477]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

`Terraform v0.11.10`

### Affected Resource(s)

* google_compute_image

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug) then please include both the
# version of the config before the change, and the version of the config after the change.
provider google {
  region = "${var.region}"
}

resource "google_compute_image" "my-gcp-image" {
  name    = "${var.google_compute_image_name}"
  project = "${var.project}"

  raw_disk {
    source = "${var.google_compute_image_source}"
  }

  # Increase the timeouts for the operations on the image
  timeouts {
    create = "15m"
    update = "15m"
    delete = "15m"
  }
}
```

### Debug Output

https://gist.github.com/haokanga/aabad7775a49b37b9883d2d0c3f589e3

--->

### Expected Behavior

A image should be created. This terraform template worked, **until Nov 12, 2018.** 

### Actual Behavior

Failed to create the image with the error message.

`google_compute_image: The resource '(a public-readable image tar)' of type 'Google Cloud Storage object' was not found.`

### Steps to Reproduce

1. `terraform apply`

**Comment by rileykarson** [comment]
Hey @haokanga!

Did you update your Terraform or Google provider version within the last few days, or since the last execution?

Also, can you verify that the image you're trying to read is still available at the address you've specified? Looking at the diff, I'm seeing the error `EXTERNAL_RESOURCE_NOT_FOUND`.

**Comment by haokanga** [comment]
Hi @rileykarson , we investigated more. This should be an error on GCP side, not Terraform.

<img width="742" alt="gcp-image-not-found" src="https://user-images.githubusercontent.com/14087400/48508122-b9934e80-e81b-11e8-86b5-334f88840606.png">

**Comment by rileykarson** [comment]
Weird! I've tried to reproduce and am unable. I'll look into filing a bug for this tomorrow.

**Comment by rileykarson** [comment]
Hopefully this has been resolved- I'm unable to reproduce now. Please reopen / file a new issue if you're still experiencing this!

**Comment by haokanga** [comment]
Thank you @rileykarson, I have confirmed with GCP and this is not an issue on the Terraform side.
