### ISSUE TITLE
Add support for GCS bucket retention policies

### ISSUE THREAD

**Issue by mikeraimondi** [terraform-providers/terraform-provider-google#2481]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCS allows retention policies to be configured for a bucket. As this is part of the bucket's overall configuration, managing the policies in Terraform seems to make the most sense.

### New or Affected Resource(s)

* google_storage_bucket

### References

* [Bucket API](https://cloud.google.com/storage/docs/json_api/v1/buckets)
* [Policy locks](https://cloud.google.com/storage/docs/json_api/v1/buckets/lockRetentionPolicy)

**Comment by itaimalek** [comment]
Hi,
is there an ETA for this?

**Comment by megan07** [comment]
Thanks @mikeraimondi for opening this issue. It's been closed with #4044 and will be released shortly.
