### ISSUE TITLE
name_prefix reincarnation for google_container_node_pool

### ISSUE THREAD

**Issue by vincentbesanceney** [terraform-providers/terraform-provider-google#2486]
Further to #1326, could you reconsider and revert #2356? Unless I missed something, using `random_id` instead of `name_prefix` for `google_container_node_pool` makes it a real pain in exactly the same way as for `google_compute_instance_template` or `google_compute_ssl_certificate`.

Would be very grateful!

**Comment by paddycarver** [comment]
It's something we're actively discussing amongst the maintainers and trying to come to a decision on still, unfortunately. This is definitely an area where we've noted the pain and need to do _something_, we just want to make sure we explore our options and think things through before we commit to which specific action we'll take.

We should have more information on this in the near future.

**Comment by danawillow** [comment]
Update: this is happening. @paddycarver, this is assigned to you- are you working on it or do you want me to?

**Comment by paddycarver** [comment]
I'll take it on.

**Comment by paddycarver** [comment]
This has been merged as GoogleCloudPlatform/magic-modules#1335.
