### ISSUE TITLE
Address should be an (optional) input value for global address

### ISSUE THREAD

**Issue by Phylu** [terraform-providers/terraform-provider-google#2489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently it is possible to create a global address pool using terraform. However the actual IP addresses are allocated by GCP and cannot be chosen by the user despite the API allows this.

### New or Affected Resource(s)

* google_compute_global_address

### Potential Terraform Configuration

```tf
resource "google_compute_global_address" "private_ip_alloc" {
  name          = "private_ip_alloc"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  address = "10.100.0.0"
  network       = "${google_compute_network.vpc.self_link}"
}
```

The address should be changed from an autogenerated value to a value which may be set optionally.

### References

* https://cloud.google.com/compute/docs/reference/rest/beta/globalAddresses/insert

**Comment by danawillow** [comment]
Fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/1014.
