### ISSUE TITLE
Problem when setting external users as owners of organization owned projects

### ISSUE THREAD

**Issue by gburiola** [terraform-providers/terraform-provider-google#2514]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```$ terraform -v
Terraform v0.11.10
```

### Affected Resource(s)

* google provider v1.19.1
* google_project_iam_member

### Description

We manage projects in multiple different GCP organisation domains and when we try to define an external user as owner it fails.

```
Terraform will perform the following actions:

  + google_project_iam_member.owner_user_domaincom
      id:     <computed>
      etag:   <computed>
      member: "user:user@domain.com"
      role:   "roles/owner"


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_project_iam_member.owner_user_domaincom: Creating...
  etag:   "" => "<computed>"
  member: "" => "user:user@domain.com"
  role:   "" => "roles/owner"

Error: Error applying plan:

1 error(s) occurred:

* google_project_iam_member.owner_user_domaincom: 1 error(s) occurred:

* google_project_iam_member.owner_user_domaincom: Error applying IAM policy for project "myproject": 
  Error setting IAM policy for project "myproject": googleapi: 
  Error 400: Request contains an invalid argument., badRequest
```

debug logs show the following:

```
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest",
        "debugInfo": "detail: \"[ORIGINAL ERROR] generic::invalid_argument: \u003ceye3 title=\\'INVALID_ARGUMENT\\'/\u003e generic::INVALID_ARGUMENT: External users must be invited to be owners of organization owned projects.\\ncom.google.developers.metadata.api.modules.projectservice.iam.IamPolicyException: \u003ceye3 title=\\'INVALID_ARGUMENT\\'/\u003e generic::INVALID_ARGUMENT: \u003ceye3 title=\\'INVALID_ARGUMENT\\'/\u003e generic::INVALID_ARGUMENT: External users must be invited to be owners of organization owned projects. [google.rpc.error_details_ext] { details { type_url: \\\"type.googleapis.com/google.cloudresourcemanager.v1.ProjectIamPolicyError\\\" value: \\\"\\\\010d\\\\022\\\\026user:USER@DOMAIN.COM\\\\032\\\\013roles/owner\\\" } }\"\n"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

```
External users must be invited to be owners of organization owned projects
```

Project `myproject` is part of GCP organization `foo.com` but the user that I'm trying to configure as owner `user@domain.com` is from a different domain.

Using any other role other than `owner` works fine

If I assign the `owner` role to user `user@domain.com` via the web console, it works and then I see the following:

![screenshot 2018-11-22 at 14 24 03](https://user-images.githubusercontent.com/6121373/48911125-d3f7a880-ee69-11e8-8414-2433a1d63efd.png)

Looking at the `setIamPolicies` API call done via the webconsole, I see that it actually defined the role as `roles/resourcemanager.projectOwnerInvitee` and not `roles/owner`

Once the user clicks on the invitation email, then the role is changed to `roles/owner`

### Suggestion

My suggestion is that terraform replicates the same behaviour as the UI

- if `google_project_iam_member.role = roles/owner` and member domain is different from organization domain
-- then call API `setIamPolicies` with role = `roles/resourcemanager.projectOwnerInvitee`
-- else call API `setIamPolicies` with role = `roles/owner`

**Comment by Chupaka** [comment]
AFAIR, docs say you must use UI for this kind of action. You cannot do it via API.

**Comment by ndmckinley** [comment]
I believe that @Chupaka is right - I do not think that that action will send the invitation email - but even if it were possible to do via the API, we try to avoid having this sort of, I'll call it "project logic", in Terraform.  I don't think we'll take this on.
