### ISSUE TITLE
resource labels overridden on update when other labels specified (dataproc_cluster) 

### ISSUE THREAD

**Issue by edward2a** [terraform-providers/terraform-provider-google#2518]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

0.11.10

### Affected Resource(s)

google_dataproc_cluster

### Terraform Configuration Files

https://github.com/edward2a/terraform-google-dataproc/tree/bugger

### Debug Output

```
google_dataproc_cluster.this: Refreshing state... (ID: dpc-test)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ google_dataproc_cluster.this
      labels.%:                          "4" => "1"
      labels.goog-dataproc-cluster-name: "dpc-test" => ""
      labels.goog-dataproc-cluster-uuid: "8b298802-8ee6-4f74-89f0-4daae4c34a52" => ""
      labels.goog-dataproc-location:     "europe-west2" => ""


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
```

### Panic Output

N/A

### Expected Behavior

Resource specific labels should be merged with user declared labels when any label (even an empty map) is declared.
An error should be raised if user declares a resource specific label (block override).

### Actual Behavior

On execution of `terraform apply`, the plan proposes to remove the resource specific labels, leaving only customer defined labels.

### Steps to Reproduce

1. pull code from https://github.com/edward2a/terraform-google-dataproc/tree/bugger
2. create a vars.json file to test the module:
```
{"cluster_name":"dpc-test",
  "project_id":"<project_id>",
  "region_name":"europe-west2",
  "subnetwork":"<target-subnet>",
  "zone":"europe-west2-a",
  "image_version": "1.3.16-deb9",
  "labels":{"hello":"world"}
}
```
3. create a .tf file with the google provider configuration
4. terraform apply -var-file vars.json
5. terraform apply -var-file vars.json

### Important Factoids

None.

**Comment by ndmckinley** [comment]
Hm.  My initial inclination is to call this working-as-intended, but I'm not sure yet.  Can you explain to me where the other labels, for instance, `goog-dataproc-cluster-uuid`, came from?

**Comment by edward2a** [comment]
Hi Nathan, I believe it is actually working-as-intended as you mention.
The labels are added by dataproc itself as part of the cluster creation.
Given this is the behaviour of the service, I believe those labels should be either ignored or merged into the state to avoid removal on cluster updates.

**Comment by mzaheer** [comment]
Just wanted to see if there was any update to this issue? I am running into the exact same problem. Terraform is looking to remove google generated labels that were added at cluster creation time.

**Comment by Matthew-Wroblewski** [comment]
I'm working with someone who is experiencing a similar problem. The Dataproc cluster UUID label is being stripped after terraform apply.  The lack of a UUID label is preventing Stackdriver from monitoring the CPU utilization of the cluster.

**Comment by edwardmedia** [comment]
@edward2a @Matthew-Wroblewski Is this still an issue with you? I am not able to repro it with provider **v3.16.0**. Below is the `plan` and the `apply` result. I am closing this issue based on the result. Please feel free if you still see this is an issue. Thanks

```
  # google_dataproc_cluster.dataproc-cluster will be updated in-place
  ~ resource "google_dataproc_cluster" "dataproc-cluster" {
      ~ labels  = {
          ~ "foo"                        = "bar" -> "bar-1"
          - "goog-dataproc-cluster-name" = "issue-2518" -> null
          - "goog-dataproc-cluster-uuid" = "0e3af1fe-eb68-40be-92be-20a4abd377b7" -> null
          - "goog-dataproc-location"     = "europe-west1" -> null
          + "xyz"                        = "xyz"
        }
       
resource "google_dataproc_cluster" "dataproc-cluster" {
    labels  = {
        "foo"                        = "bar-1"
        "goog-dataproc-cluster-name" = "issue-2518"
        "goog-dataproc-cluster-uuid" = "0e3af1fe-eb68-40be-92be-20a4abd377b7"
        "goog-dataproc-location"     = "europe-west1"
        "xyz"                        = "xyz"
```
