### ISSUE TITLE
Enable Custom Images in DataProc

### ISSUE THREAD

**Issue by paul-opsguru** [terraform-providers/terraform-provider-google#2536]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Often, it's useful to pre-bake DataProc images in order to make provisioning faster (instead of installing packages and 3rd party jars on each cluster provisioning). 
The full procedure is described here: https://cloud.google.com/dataproc/docs/guides/dataproc-images
Would be useful to have the ability to pass a pre-baked image URI to the google_dataproc_cluster resource as part of 'cluster_config' block.

### New or Affected Resource(s)

google_dataproc_cluster

### Potential Terraform Configuration

```tf
 cluster_config {
        # Override or set some custom properties
        software_config {
            image_uri       = "https://www.googleapis.com/compute/v1/projects/project-id/global/images/custom-image-name"
        }
    }
```

### References

https://cloud.google.com/dataproc/docs/guides/dataproc-images
https://cloud.google.com/compute/docs/images#custom_images

**Comment by ndmckinley** [comment]
Looks sensible to me.  https://cloud.google.com/dataproc/docs/reference/rest/v1beta2/projects.regions.clusters#Cluster points to https://cloud.google.com/dataproc/docs/reference/rest/v1beta2/ClusterConfig#InstanceGroupConfig, so it's in the API... let's see how much trouble it'd be to get that in there.  :)

**Comment by ndmckinley** [comment]
I'll let that percolate through CI, and see if it works as easily as I hope it did.  :)
