### ISSUE TITLE
Backport creating BigTable column families to master branch

### ISSUE THREAD

**Issue by nvtkaszpir** [terraform-providers/terraform-provider-google#2537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I see that #1576  - which allows to create bigtable column families - was merged into branch v2.0.0. Yet release of 2.0.0 may be quite far in the future ;)

Is it possible to backport this functionality to master branch? 

### New or Affected Resource(s)

* google_bigtable_table

### Potential Terraform Configuration

```tf
resource "google_bigtable_table" "table" {
  name          = "test"
  instance_name = "${google_bigtable_instance.instance.name}"
   column_family {
    family = "test-first"
  }
   column_family {
    family = "test-second"
  }
}
```

### References

* #1576

**Comment by ndmckinley** [comment]
We'll do what we can.  :)

We know people are also excited about cloud NAT, which is in the final stage of review - when that comes out, if 0.12 (and hence 2.0.0) appears to be a ways away, we'll try to figure something out.  :)  I'm going to go ahead and close this since it's not actionable right now ... but know we're going to give it our best shot.
