### ISSUE TITLE
Documentation for kubernetes versioning in the Google Container Cluster module docs

### ISSUE THREAD

**Issue by jclarksnps** [terraform-providers/terraform-provider-google#2538]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Could we please add documentation within the google container cluster documentation for min_master_version and node_version for how google does versioning for Kubernetes.  There is quite a bit more to it than just putting a version in there, they allow for wildcarding, latest etc.

Module docs: https://www.terraform.io/docs/providers/google/r/container_cluster.html

Official google k8s version documentation: https://cloud.google.com/kubernetes-engine/versioning-and-upgrades

**Comment by ndmckinley** [comment]
Does the proposed change in https://github.com/GoogleCloudPlatform/magic-modules/pull/965 address your concern?
