### ISSUE TITLE
Labeling Resources

### ISSUE THREAD

**Issue by noizo** [terraform-providers/terraform-provider-google#254]
Hi.

Google has changed something with labeling instances recently.
https://cloud.google.com/compute/docs/labeling-resources

I've been using labeling this way before:

```
 resource "google_compute_instance" "name" {
  tags         = ["${var.name}", "no-ip", "postgres"]
```

It worked fine, but now it applies only to Tags, and not Labels.
There are no docs in terraform covering Labeling on Google provider, so i think this future is missing.

**Comment by rileykarson** [comment]
Hi @noizo!

Labels and Tags were decoupled as of [May 01, 2017](https://cloud.google.com/compute/docs/release-notes#may012017). We have an ongoing issue tracking general labels support at #17, and work on supporting them across resources is in progress. For `google_compute_instance` specifically, labels support landed in #150 and was part of release `0.1.2` on July 20th.

This isn't currently reflected on the website documentation, and I don't expect it will be until Terraform `0.10` releases. In the meantime, you can view the [documentation](https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/r/compute_instance.html.markdown) in the source repo, with the disclaimer that it's tracking `HEAD` and not the `0.1.2` release.

If you're interested in other resources, feel free to file issues or comment on #17! We generally prioritise adding support to resources that have specific demand when adding general support for a feature like this.
