### ISSUE TITLE
google_folder resource ID attribute incorrectly includes "folders/"

### ISSUE THREAD

**Issue by mikeraimondi** [terraform-providers/terraform-provider-google#2542]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.10
provider.google v1.19.1

### Affected Resource(s)

* google_folder

### Terraform Configuration Files

```tf
resource "google_folder" "foo" {
  display_name = "foo"
  parent       = "folders/123456789"
}

output "folder_id" {
  value = "${google_folder.foo.id}"
}
```

### Expected Behavior

```
Outputs:

folder_id = 987654321
```

### Actual Behavior

```
Outputs:

folder_id = folders/987654321
```

### Steps to Reproduce

See above

### Important Factoids

This doesn't seem to occur with the google_folder data source. It's ID correctly excludes "folders/"

**Comment by ndmckinley** [comment]
`id` isn't one of the documented fields of `google_folder` - the value of `id` should be considered "unspecified", in that we don't state anything about what its value is.  `name` is one of the documented fields, but `name` is correctly documented as including `folders/`.  https://www.terraform.io/docs/providers/google/r/google_folder.html

You may be able to get the value you want using https://www.terraform.io/docs/configuration/interpolation.html#split-delim-string-.
