### ISSUE TITLE
Provider fails on trying to update with an empty body

### ISSUE THREAD

**Issue by pratikmallya** [terraform-providers/terraform-provider-google#2544]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
 ➜ terraform -v
Terraform v0.11.10
+ provider.google v1.18.0
```

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
TODO
```

### Debug Output

https://gist.github.com/pratikmallya/e2ccb486d32f166f06b4fcd76f80644a

### Expected Behavior

Terraform apply shouldn't have caused a failure. Terraform provider shouldn't have tried to update when there is nothing to update, since that causes failure

### Actual Behavior

Terraform apply fails because GCP api returns a 400 when an update request is made with an empty body.

### Steps to Reproduce

TODO

**Comment by pratikmallya** [comment]
Will get in a minimal reproducible example soon; just wanted to file this now

**Comment by ndmckinley** [comment]
We will need the example to make progress on this bug.  Please update when you're ready to provide one.  We're also going to need more debug logs, ideally - it'd be great if you could include the detected diff.

**Comment by rileykarson** [comment]
Closing as outdated, `1.18.0` was a while ago and this resource has changed a fair bit since then. If you can repro this on a recent release, feel free to comment / open a new issue!
