### ISSUE TITLE
Cloud SQL: fails to change require_ssl setting from true -> false

### ISSUE THREAD

**Issue by rvandegrift** [terraform-providers/terraform-provider-google#2552]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.10
+ provider.google v1.19.1

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

First config:
```tf
resource "google_sql_database_instance" "db" {
  name = "db"
  database_version = "MYSQL_5_7"
  region = "us-central1"

  settings {
    tier = "db-f1-micro"
    disk_type = "PD_HDD"

    ip_configuration {
      require_ssl = true
    }
  }
}
```

Second config:
```tf
resource "google_sql_database_instance" "db" {
  name = "db"
  database_version = "MYSQL_5_7"
  region = "us-central1"

  settings {
    tier = "db-f1-micro"
    disk_type = "PD_HDD"

    ip_configuration {
      require_ssl = false
    }
  }
}
```

### Expected Behavior

Terraform should change the `requilreSsl` setting from `true` to `false`.

### Actual Behavior

No changes are made, even though the correct change appears in the plan.  Terraform thinks it has succeeded.

### Steps to Reproduce

1. `terraform apply` the first config
2. `terraform apply` the second config

### Debug Output

https://gist.github.com/rvandegrift/e29f15b7934b463805318b3ace09f187

**Comment by GeneralAardvark** [comment]
:+1:
