### ISSUE TITLE
How to assign private ip to cloudsql with terraform??

### ISSUE THREAD

**Issue by hrlimaye** [terraform-providers/terraform-provider-google#2561]
Hello

GCP:Terraform

I have created VM having access from my public ip only so it will act as jump box and created cloud-sql that will be accessible from jump-box only.
Issue i am facing is I am not able to assign private ip to cloud-sql as i dont see any option in terraform for google_sql_database_instance.
I am able to do it from console.

**Comment by Chupaka** [comment]
https://github.com/terraform-providers/terraform-provider-google/issues/2127#issuecomment-443070824

**Comment by danawillow** [comment]
Closing in favor of #2127
