### ISSUE TITLE
Allow importing google_sql_user cross-projects

### ISSUE THREAD

**Issue by vdamianchicon** [terraform-providers/terraform-provider-google#2563]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.10
+ provider.google v1.19.1
+ provider.google-beta v1.19.0

### Affected Resource(s)

* google_sql_user

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug) then please include both the
# version of the config before the change, and the version of the config after the change.
```

### Expected Behavior

resource "google_sql_user" "data-user" {
project = "${local.project_id}"
}
terraform import google_sql_user.data-user <instance>/<dbname>/data-user
google_sql_user.data-user: Importing from ID "<instance>/<dbname>/data-user"...
google_sql_user.data-user: Import complete!

### Actual Behavior

resource "google_sql_user" "data-user" {
project = "${local.project_id}"
}
terraform import google_sql_user.data-user <instance>/<dbname>/data-user
google_sql_user.data-user: Importing from ID "<instance>/<dbname>/data-user"...
google_sql_user.data-user: Import complete!
Imported google_sql_user (ID: <instance>/<dbname>/data-user)
google_sql_user.data-user: Refreshing state... (ID: <instance>/<dbname>/data-user)

Error: google_sql_user.data-user (import id: <instance>/<dbname>/data-user): 1 error(s) occurred:

import google_sql_user.data-user result: <instance>/<dbname>/data-user: google_sql_user.data-user: project: required field is not set

### Steps to Reproduce

1. `terraform import google_sql_user.data-user <instance>/<dbname>/data-user`
2.  `<instance> = <project_id> = <project_name>`

### References

* https://www.terraform.io/docs/providers/google/r/sql_user.html#project

**Comment by sarneaud** [comment]
> google_sql_user.data-user: project: required field is not set

The project should be supplied by the provider when you create the resource, but this reminds me of another bug where importing didn't work properly.  Does the same workaround help?

https://github.com/terraform-providers/terraform-provider-google/issues/1846#issuecomment-411248401

**Comment by vdamianchicon** [comment]
Yes I have a provider that supply the project. Will check the other bug work around and see if it works on my case

provider "google-beta" {
  region      = "${local.gcp_region}"
  project     = "${local.project_id}"
  version     = "~> 1.0"
}

**Comment by vdamianchicon** [comment]
ooops

**Comment by vdamianchicon** [comment]
[#1846 (comment)](https://github.com/terraform-providers/terraform-provider-google/issues/1846#issuecomment-411248401) 
Seem relevant in my case because <instance> = <project_id> = <project_name>
how will I apply the work around in my case?

**Comment by sarneaud** [comment]
Have you tried this?

```
GOOGLE_PROJECT=<project_name> terraform import google_sql_user.data-user <instance>/<dbname>/data-user
```

(I.e., just specifying the `GOOGLE_PROJECT` when importing.)

**Comment by paddycarver** [comment]
I think we need to update the import logic for that resource to provide a cross-project import option. Sorry for the oversight!

**Comment by vdamianchicon** [comment]
I will try the workaround:
`GOOGLE_PROJECT=<project_name> terraform import google_sql_user.data-user <instance>/<dbname>/data-user`
