### ISSUE TITLE
Add support for Cloud Scheduler

### ISSUE THREAD

**Issue by maryamhanifpour** [terraform-providers/terraform-provider-google#2571]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please add support for Cloud Scheduler: https://cloud.google.com/scheduler/

### New or Affected Resource(s)

* google_cloud_scheduler_job

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_cloud_scheduler_job" "foo" {
  name = "foo"
  description = "my job"
  schedule = "30 12 * * *"
  timezone = "America/New_York"
  retry_config {
    retry_count = 4
    max_retry_duration = 60
    min_backoff_duration = 5
    max_backoff_duration = 30
    max_doublings = 3
  }
  pubsub_target {
    topic_name = "projects/myproject/topics/mytopic"
    data = "my message payload"
    attributes = {
      mykey = "myvalue"
    }
  }
  # or
  app_engine_http_target {
    http_method = "POST"
    app_engine_routing {
      service = "web"
      version = "prod"
      instance = "my-instance-001"
    }
    relative_uri = "/my/path"
    headers = {
      My-Header = "my value"
    }
    body = "my body"
  }
  # or
  http_target {
    uri = "https://www.example.com/my/endpoint"
    http_method = "POST"
    headers = {
      My-Header = "my value"
    }
    body = "my body"
  }
}
```

### References

* #0000

**Comment by paddycarver** [comment]
Updated the issue with a bit more detail. Sounds like a nice thing to add, though!

**Comment by g-harel** [comment]
Hey, I'd like to give this issue a try if that would be helpful. If you think it might be too involved as a first issue please let me know!

Since [Cloud Scheduler](https://cloud.google.com/scheduler) is in beta, it looks like I should plan on opening a PR in the [google-beta](https://github.com/terraform-providers/terraform-provider-google-beta) provider repo?

**Comment by davidharrisonlb** [comment]
I'd be really keen to offer some assistance on this issue too

**Comment by g-harel** [comment]
Per [this page](https://www.terraform.io/docs/providers/google/provider_versions.html), I'll fork off of the `beta` repo.

@davidharrisonlb I'll be working [here](https://github.com/g-harel/terraform-provider-google-beta/tree/cloud-scheduler) (on the `cloud-scheduler` branch). We can talk over email if that works for you! 

gabrielj.harel@gmail.com

**Comment by davidharrisonlb** [comment]
Hey @g-harel I've done some work on your branch and need to push it up, or I can fork your branch and PR my changes? email is below for adding me as a contributor

david.harrison@ladbiblegroup.com

**Comment by paddycarver** [comment]
Hey y'all, as per [the contributing guide](https://github.com/terraform-providers/terraform-provider-google/blob/2.0.0/.github/CONTRIBUTING.md#autogenerated-resources) we're actually doing all our development in the [magic modules](https://github.com/GoogleCloudPlatform/magic-modules) repo now, so PRs against that would be preferred. That doesn't mean the resource needs to be generated, just that we're going to have to make the changes there, so it's easier if the PR happens against that, instead. :)

**Comment by rileykarson** [comment]
Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/1102
