### ISSUE TITLE
Terraform Enterprise Service Account question

### ISSUE THREAD

**Issue by elvin159** [terraform-providers/terraform-provider-google#2609]
I have a terraform enterprise workspace configured to go to a specific service project. project-A. The terraform enterprise workspace credentials is using a gcp service account that is created on project-B. When using a terraform logging resource (stackdriver API enablement on project-A) i get a permission denied to project-B because the API is not enabled on project-B nor do we have an iam policy binding for that service account. 

This pattern of having the service account on project-B and deploying compute instances to a different service project works perfectly fine. IF I reconfigure the workspace credentials to a service account that is created on project-A AND i enable the API for logging on project-A and correctly bind that service account to the proper role. The terraform workspace applies perfectly fine. no problems.

Can someone explain to me why this is happening? I've got an explanation from hashicorp that this is a common pattern for some terraform resources for gcp, what i want to know is which terraform resources exhibit this pattern and which do not. We want to know if we should enable APIs on a single place (project-A) using service accounts created in project-B or if we should manage API enable/disabe on each individual service project.

---
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by morgante** [comment]
Generally speaking, to deploy resources in Project A using a service account from Project B, you need to ensure that:

1. The API is active on Project A *and* Project B (this isn't always required, but it's simpler to do so across the board)
2. The Service Account is granted the appropriate role on project B (ex. Compute Admin or Editor).

**Comment by elvin159** [comment]
@morgante thank you for this insight.
