### ISSUE TITLE
`google_sql_database_instance`: unable to set `maintenance_window.hour` to 0

### ISSUE THREAD

**Issue by sergei-ivanov** [terraform-providers/terraform-provider-google#2610]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.10
+ provider.google v1.19.1
```

### Affected Resource(s)

* `google_sql_database_instance`

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "mysql" {
  count            = "${var.database_count}"
  name             = "${format("%s-%02d", "dev", count.index + 1)}"
  project          = "${var.project}"
  database_version = "MYSQL_5_7"
  region           = "europe-west1"

  settings {
    tier            = "db-n1-highmem-2"
    disk_autoresize = true
    disk_size       = "20"
    disk_type       = "PD_SSD"

    ip_configuration {
      require_ssl  = false
      ipv4_enabled = true
    }

    backup_configuration {
      binary_log_enabled = true
      enabled            = true
      start_time         = "00:00"
    }

    maintenance_window {
      day          = "7"
      hour         = "1" # <--- change this from 1 to 0 to reproduce
      update_track = "stable"
    }
  }
}
```

### Debug Output

https://gist.github.com/sergei-ivanov/03a1c2e15d4bb77fb01729876a35b291

The important bit is this part of the PUT request:

```
2018-12-07T19:23:45.268Z [DEBUG] plugin.terraform-provider-google_v1.19.1_x4:   "maintenanceWindow": {
2018-12-07T19:23:45.268Z [DEBUG] plugin.terraform-provider-google_v1.19.1_x4:    "day": 7,
2018-12-07T19:23:45.268Z [DEBUG] plugin.terraform-provider-google_v1.19.1_x4:    "updateTrack": "canary"
2018-12-07T19:23:45.268Z [DEBUG] plugin.terraform-provider-google_v1.19.1_x4:   },
```

It looks like when `hour = "0"` it is not passed down to the API.

### Panic Output

N/A

### Expected Behavior

Maintenance schedule for Cloud MySQL instance should be updated to happen on Sunday between 00:00 and 01:00 UTC.

### Actual Behavior

An error is reported from the API:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.main.google_sql_database_instance.mysql
      settings.0.maintenance_window.0.hour: "1" => "0"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.main.google_sql_database_instance.mysql: Modifying... (ID: dev-01)
  settings.0.maintenance_window.0.hour: "1" => "0"

Error: Error applying plan:

1 error(s) occurred:

* module.main.google_sql_database_instance.mysql: 1 error(s) occurred:

* google_sql_database_instance.mysql: Error, failed to update instance dev-01: googleapi: Error 400: Invalid request: Invalid maintenance window. Hour of day is unspecified., invalid

```

### Steps to Reproduce

1. Change `settings.maintenance_window.hour` from `1` to `0`
2. `terraform apply`

The same problem occurs when provisioning a fresh MySQL instance, if the value for the `hour` was initially set to `0`.

### Important Factoids

N/A

### References

N/A

**Comment by sergei-ivanov** [comment]
I had a closer look at the provider code (in particular, at `expandMaintenanceWindow` function), and I could not see anything suspicious going on there. Then I decided to dig a bit deeper, and I think I know where the problem is. If you look [at the definition](https://github.com/googleapis/google-api-go-client/blob/master/sqladmin/v1beta4/sqladmin-gen.go#L1765) of the `Hour` field in Google SQL Admin API, it has a `json:"hour,omitempty"` annotation, which, as I understand it from reading [this](https://golang.org/pkg/encoding/json/#Marshal), will ignore zero value for JSON serialisation.
So perhaps we need to raise a bug against the API instead. Can anyone from Terraform team confirm my findings please?

**Comment by danawillow** [comment]
Every field in the client library is like this- we use `ForceSendFields` to send zero values. I'll prepare a PR.
