### ISSUE TITLE
Add InstanceType to Bigtable

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#263]
Apparently the go client library now supports InstanceType, so we can probably add it to our Bigtable resource.

https://github.com/GoogleCloudPlatform/google-cloud-go/commit/7a4ba9f439fbc50061834a4063b57cf7222ba83f

cc @rileykarson

**Comment by dasch** [comment]
This is critical to setting up developer projects, :+1: 💯

**Comment by rileykarson** [comment]
Closed with #313.
