### ISSUE TITLE
Support configuring GKE resource usage metering

### ISSUE THREAD

**Issue by davidxia** [terraform-providers/terraform-provider-google#2644]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GKE supports [resource usage metering](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-usage-metering) right now. It'd be great if Terraform supported configuring this option as well. Otherwise, we have to [manually enable or disable it](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-usage-metering#enable-usage-metering). Manually configuring it means it's prone to human error and isn't declarative or versioned.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "primary" {
  resource_usage_bigquery_dataset <name of BigQuery dataset>
}
```

Not specifying `resource_usage_bigquery_dataset` means it's disabled.

### References

None

**Comment by ndmckinley** [comment]
Can do, as long as it's featured in the API... but I can't find any evidence that it is.  Looks `gcloud` exclusive according to the docs here: https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-usage-metering.  I'll keep looking.

**Comment by ndmckinley** [comment]
Aha, yes:
>You cannot currently enable usage metering using the Google Cloud Platform Console.

So it's `gcloud`-exclusive - if you want it in Terraform, for now you'll need to use provisioners or null resources which shell out to gcloud to set it up.  Tagging as `upstream` for reconsideration later.

**Comment by ndmckinley** [comment]
Well!  It's not in the docs, but if you add `"resourceUsageExportConfig": {"bigqueryDestination": {"datasetId": "some-dataset"}}` at top level under the "cluster" block during the create call, then it does seem to work.  :)

**Comment by davidxia** [comment]
@ndmckinley Thanks. I'm having trouble getting that to work though. Could you give an example?

**Comment by ndmckinley** [comment]
Ah, I didn't write that clearly!  That's a note for the eventual implementation, it won't be doable right now in config.

**Comment by krmayankk** [comment]
It would be good to get this prioritized.  This is a knob we want to turn on as we create gke clusters using terraform.

**Comment by manuelfelipe** [comment]
hey @ndmckinley / @rileykarson  have a PR for this in https://github.com/GoogleCloudPlatform/magic-modules/pull/1742 - any chance you guys can take a look? 

the workaround for us right now to have this enabled as part of our gke cluster module(s) is to use a `local-exec` provisioner to run the gcloud command to update the cluster once created but it is painfully slow (avg 18min to update) compare to when you create the cluster with this already enabled

**Comment by rileykarson** [comment]
Thanks @manuelfelipe! It looks like nobody got to it last week, but I'll prod someone to review it if it's left untouched for a couple more days.

**Comment by rileykarson** [comment]
Assigning to @hashibot to mark that @manuelfelipe is working on this.
