### ISSUE TITLE
Big Table Application Profile

### ISSUE THREAD

**Issue by michyliao** [terraform-providers/terraform-provider-google#2659]
Hi,

I was wondering if there is an option to include application profile for big table replicated instances? 

Thanks!

**Comment by ndmckinley** [comment]
Anything that comes from the API, or anything that's doable with a single resource from the API, is available for inclusion.  I'll go research the API and see whether this is in there!  :)

**Comment by ndmckinley** [comment]
Aha, yes, that would be a new resource, like so:
https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances.appProfiles.  We could create that.  We'll prioritize it based on :+1:s, like other resource creation requests.  :)  Looks pretty standard, so it seems like a great fit for magic modules.

**Comment by megan07** [comment]
Thanks @michyliao for opening this issue. It's been closed with #4126 and will be released shortly.
