### ISSUE TITLE
KMS calls fail if service enabled on the same apply

### ISSUE THREAD

**Issue by jalseth** [terraform-providers/terraform-provider-google#2673]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.10
provider.google v1.20.0

### Affected Resource(s)

google_app_engine_application

### Terraform Configuration Files

project.tf
```tf
variable "project_id" {}
variable "region" {}

provider "google" { region = "${var.region}" }

resource "google_project_services" "project" {
    project  = "${var.project_id}"
    services = [
        "sql-component.googleapis.com",
        "appengine.googleapis.com",
        "appengineflex.googleapis.com",
        "iam.googleapis.com",
        "iap.googleapis.com",
        "admin.googleapis.com",
        "cloudkms.googleapis.com",
        "oslogin.googleapis.com",
        "storage-component.googleapis.com",
        "cloudbuild.googleapis.com",
        "bigquery-json.googleapis.com",
        "containerregistry.googleapis.com",
        "pubsub.googleapis.com",
        "compute.googleapis.com",
        "deploymentmanager.googleapis.com",
        "monitoring.googleapis.com",
        "logging.googleapis.com",
        "replicapool.googleapis.com",
        "replicapoolupdater.googleapis.com",
        "iamcredentials.googleapis.com",
        "container.googleapis.com",
        "storage-api.googleapis.com",
        "resourceviews.googleapis.com"
    ]
}
```

appengine.tf
```tf
resource "google_app_engine_application" "app" {
    project     = "${var.project_id}"
    location_id = "${var.region}"
}
```

iam.tf
```tf
data "google_iam_policy" "iap_users" {
    binding {
        role = "roles/iap.httpsResourceAccessor"
        members = [
            "user:james@PROJECT.com",
        ]
    }
}

resource "google_project_iam_policy" "iap_policy" {
    project     = "${var.project_id}"
    policy_data = "${data.google_iam_policy.iap_users.policy_data}"
}
```

kms.tf
```tf
resource "google_kms_key_ring" "PROJECT_key_ring" {
    name     = "PROJECT-key-ring"
    project  = "${var.project_id}"
    location = "${var.region}"
}

resource "google_kms_crypto_key" "PROJECT_crypto_key" {
    name            = "PROJECT-crypto-key"
    key_ring        = "${google_kms_key_ring.PROJECT_key_ring.self_link}"
    rotation_period = "100000s"
}

resource "google_kms_key_ring_iam_binding" "PROJECT_mgmt_key_ring_iam" {
    key_ring_id = "${var.project_id}/${var.region}/${google_kms_key_ring.PROJECT_key_ring.name}"
    role        = "roles/cloudkms.cryptoKeyEncrypter"
    members = [
        "user:james@PROJECT.com"
    ]
}

resource "google_kms_crypto_key_iam_binding" "PROJECT_mgmt_key_iam" {
    crypto_key_id = "${var.project_id}/${var.region}/${google_kms_key_ring.PROJECT_key_ring.name}/${google_kms_crypto_key.PROJECT_crypto_key.name}"
    role          = "roles/cloudkms.cryptoKeyEncrypter"
    members = [
        "user:james@PROJECT.com"
    ]
}
```

### Debug Output

Debug logs for the first and second `terraform apply` commands: https://gist.github.com/jalseth/86b5392991ed7e3809a71c8b481a4c9e

### Expected Behavior

`terraform apply` succeeds on the first try, then I am able to deploy my application with `gcloud app deploy`. 

### Actual Behavior

The first `terraform apply` fails as the KMS API has been activated too recently for the KMS changes to be made. This is a separate issue that should be fixed, but not the one I am most concerned about.

Running `terraform apply` again succeeds and all the resources are created. However, attempting to deploy my application with `gcloud app deploy` fails with `(gcloud.app.deploy) FAILED_PRECONDITION: service account "PROJECT_NUMERIC_ID@cloudbuild.gserviceaccount.com" has insufficient permission to execute the build on project "PROJECT_ID"`. 

### Steps to Reproduce

1. Create new GCP project
2. Set Terraform variables
3. `terraform init`
4. `terraform apply` (fails - only applies partially)
5. `terraform apply` (succeeds)
6. `gcloud app deploy` (fails)

### Important Factoids

* This issue only appears to happen with both `iam.tf` and `kms.tf` are in use, if I move either of them to another folder before running `terraform apply` the `gcloud app deploy` is successful.
* It is not clear to me if the root cause of the issue is in the Terraform provider, or a bug in `gcloud`.

**Comment by paddycarver** [comment]
Have you tried using a [different level of IAM](https://www.terraform.io/docs/providers/google/r/google_project_iam.html), like a member or binding?

I believe you're overwriting your entire project IAM policy, which would lock out the Google-created service accounts.

**Comment by jalseth** [comment]
That was it, thank you. It does still take two `terraform apply`s though.

**Comment by paddycarver** [comment]
I think that may be a duplicate behaviour of #2129. Does that sound right to you? Services not being enabled when they say they are?

I think we may be able to do some retry in the KMS logic, if we're not already.

**Comment by jalseth** [comment]
It appears similar. I tried adding a 30s delay as a work-around as suggested in that issue, but it did not resolve the error in my case. Here's the debug log: [kms_issue.log](https://github.com/terraform-providers/terraform-provider-google/files/2681907/kms_issue.log)

**Comment by paddycarver** [comment]
If you go to https://console.cloud.google.com/home/dashboard?project=404235738678, does it redirect you to https://console.cloud.google.com/home/dashboard?project=tf-bug-008 ?

**Comment by jalseth** [comment]
Yes, it does. And I can verify the cloudkms API was enabled successfully.

**Comment by paddycarver** [comment]
Oh, now that I look at the log, I see what's going on here.

You need a dependency on your services call within the kms resources, or Terraform will try to parallelize them. Adding a `depends_on` to the `google_kms_key_ring` resource like so should sort you out:

```tf
resource "google_kms_key_ring" "PROJECT_key_ring" {
    name     = "PROJECT-key-ring"
    project  = "${var.project_id}"
    location = "${var.region}"
    depends_on = ["google_project_services.services"]
}
```

**Comment by paddycarver** [comment]
Are you leaving out the `${}` in the `depends_on` field? Those aren't included in depends_on: https://www.terraform.io/docs/configuration/resources.html#explicit-dependencies

**Comment by jalseth** [comment]
My mistake, I'm used to adding the `${}` everywhere else. Thank you for the prompt help.

**Comment by paddycarver** [comment]
Glad it got resolved! Sorry for the confusion.
