### ISSUE TITLE
Support SourceRepository for CloudFunctions

### ISSUE THREAD

**Issue by pratikmallya** [terraform-providers/terraform-provider-google#2685]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, the only way to specify the source of a respository seems to be to use a GCS bucket. Cloud Functions do support [Google Source Repositories](https://cloud.google.com/source-repositories/) as a source for code and that parameter would be nice to have

### New or Affected Resource(s)

* google_cloudfunctions_function 

### Potential Terraform Configuration

```tf
resource "google_sourcerepo_repository" "cf_trigger" {
  name = "trigger"
}

resource "google_cloudfunctions_function" "cf_trigger" {
...
sourceRepo = "${google_sourcerepo_repository.cf_trigger.url}"
}
```

**Comment by rileykarson** [comment]
Support was added in https://github.com/terraform-providers/terraform-provider-google/pull/2650, this will appear in `2.0.0`.
