### ISSUE TITLE
Support for sole-tenant node in GCP

### ISSUE THREAD

**Issue by donwichurano** [terraform-providers/terraform-provider-google#2700]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCP currently supports sole-tenant nodes. It'd be nice if terraform supported assigning sole-tenant nodes to creating compute instance.

### New or Affected Resource(s)

* google_compute_instance
* google_compute_soletenant_node_group
* google_compute_soletenant_node_template

### Potential Terraform Configuration

```
resource "google_compute_instance" "instance" {
    node_config {
       node = "node-name"
       node_affinity  = {
            key = "value"
       }
    }
}
```

### References

https://cloud.google.com/compute/docs/nodes/create-nodes

**Comment by epollum** [comment]
bump
