### ISSUE TITLE
Add `check_id` output attribute to `google_monitoring_uptime_check_config`

### ISSUE THREAD

**Issue by sergei-ivanov** [terraform-providers/terraform-provider-google#2702]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

`google_monitoring_uptime_check_config` resource exports name, in the format of `projects/<project>/uptimeChecks/<check_id>`, but condition filters in `google_monitoring_alert_policy` resource seem to require just the `check_id`. Therefore I am having to strip the `projects/<project>/uptimeChecks/` prefix using `replace()` function with a regexp. Please see the example below.

Would it be possible to export just the `check_id` as a separate attribute?

### New or Affected Resource(s)

* `google_monitoring_uptime_check_config`

### Potential Terraform Configuration

```tf
resource "google_monitoring_uptime_check_config" "test" {

  project      = "${var.project}"
  display_name = "Test"
  timeout      = "10s"
  period       = "150s"

  http_check = {
    path    = "/actuator/health"
    port    = "8443"
    use_ssl = true
  }

  monitored_resource {
    type = "uptime_url"

    labels = {
      project_id = "${var.project}"
      host       = "${google_compute_instance.test.network_interface.0.access_config.0.nat_ip}"
    }
  }

  selected_regions = [
    "EUROPE",
    "USA",
  ]
}

resource "google_monitoring_alert_policy" "test" {

  display_name = "Test"
  enabled      = true
  combiner     = "OR"

  conditions = [
    {
      display_name = "Uptime Health Check on ${google_monitoring_uptime_check_config.test.display_name}"

      condition_threshold {
        filter = "${format(
                    "metric.type=\"%s\" resource.type=\"%s\" metric.label.\"check_id\"=\"%s\"",
                    "monitoring.googleapis.com/uptime_check/check_passed",
                    google_monitoring_uptime_check_config.test.monitored_resource.0.type,
                    replace(google_monitoring_uptime_check_config.test.name, "/^.*\\//", ""))
                  }"
#
# I'd like to be able to use something like
#   google_monitoring_uptime_check_config.test.check_id
# instead of using the replace() function to strip prefix off the name.
#
# Passing full `google_monitoring_uptime_check_config.test.name` as `check_id`
# is not rejected by the API, but does result in a non-working condition,
# because the uptime check is not matched by the filter.
#

        duration        = "300s"
        comparison      = "COMPARISON_GT"
        threshold_value = "1"

        trigger {
          count = "1"
        }

        aggregations = [
          {
            alignment_period     = "1200s"
            per_series_aligner   = "ALIGN_NEXT_OLDER"
            cross_series_reducer = "REDUCE_COUNT_FALSE"

            group_by_fields = [
              "resource.*",
            ]
          },
        ]
      }
    },
  ]
}
```

### References

* #1044

**Comment by alexburlton** [comment]
I've experienced this same issue, although I've worked around it using the inbuilt basename function which you may find nicer:

`basename(google_monitoring_uptime_check_config.test.id)`

**Comment by sergei-ivanov** [comment]
@alexburlton that really worked nicely, and the config looks less ugly now. Hopefully the associated pull request will be merged soon (many thanks @chrisst !).
