### ISSUE TITLE
Domain joining of VM created in GCP is not supported .

### ISSUE THREAD

**Issue by angey** [terraform-providers/terraform-provider-google#2711]
Domain joining of VM created in GCP is not supported . This is the case for both windows and Non-windows VMs . So as of now the only solution is running script and then joining the VM to AD . 

But while looking at other provider like Azure they have it possible via Terraform function itself -https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples/vm-joined-to-active-directory 

This feature will help enterprise migration easy for Infra servers and will have less script to mange  .

**Comment by emilymye** [comment]
I'm not very familiar with this operation so I'm not sure exactly what you are requesting. It seems this is more a deploy step operation that would need to be some `remote-exec` call to provision a Windows GCP instance. Are you asking for an example of how to do this with GCP?

**Comment by angey** [comment]
Thanks Emily for response here . Yes, if you can help me with  the remote-exec example that works well with GCP that will do my job Windows/Linux . In short I need to Domain Join the VM to my DC server ,this should run some command like  run "realm join ad.example.com -U user" . The user ID and password can be fetched dynamically from HashiCorpVault or some secure place.

**Comment by paddycarver** [comment]
Hi! It looks like you're trying to do provisioning steps. Unfortunately, this isn't the best place to get that kind of help--you probably want one of the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google).
