### ISSUE TITLE
google_compute_forwarding_rule "all" value is missing for the ports field

### ISSUE THREAD

**Issue by HugoPuntos** [terraform-providers/terraform-provider-google#2766]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

For a regional TCP load balancer, it's not possible to set the ports value to all (cf https://www.terraform.io/docs/providers/google/r/compute_forwarding_rule.html#ports) as it can be done in GCP:

![screenshot 2018-12-28 at 11 16 40](https://user-images.githubusercontent.com/5734735/50512419-137d6a00-0a92-11e9-8a92-fb80afe130b9.png)

### New or Affected Resource(s)

* google_compute_forwarding_rule

### Potential Terraform Configuration

```tf
ports = ["ALL"]
```

### References

* #0000

**Comment by rileykarson** [comment]
Just to confirm, have you tried using `ALL` in a configuration? Looking at our code briefly, I don't see a reason it wouldn't work offhand. I think this is a case of our documentation not covering every option explicitly.

**Comment by HugoPuntos** [comment]
Yes, I have tried the syntax with `ALL` but Terraform throws the following exception:

```
Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.ports[0]': 'ALL'. Not an integer: 'ALL'., invalid
```

**Comment by rileykarson** [comment]
Thanks for trying that out! I suspect the Console is mapping "ALL" to
something else in that case. Are you able to omit `ports` entirely? Looking
at the gcloud docs for the field it states:

> If not specified for regional forwarding rules, all ports are matched.

**Comment by HugoPuntos** [comment]
I've already tried this solution and the port is mandatory in case of a TCP LB:
```
 Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.ports[0]': ''. Forwarding rules with backend services must specify at least one port., invalid
```

**Comment by rileykarson** [comment]
Ah! Got it- there's a Beta field called `allPorts` in the API that's present in Get and Insert calls but isn't documented as part of the resource.

**Comment by rileykarson** [comment]
Done! This should work on `google-beta` in `2.0.0` by specifying `all_ports` and leaving `port`/`port_range` blank.
