### ISSUE TITLE
Google Service Account Key Project

### ISSUE THREAD

**Issue by benfdking** [terraform-providers/terraform-provider-google#2788]
### Terraform Version

```
Terraform v0.11.11
+ provider.google v1.20.0
+ provider.random v2.0.0
```

### Terraform Configuration Files

main.tf
```hcl
provider "google" {
  version = "~> 1.20"
}

module "development" {
  source = "module/"
  project_prefix = "development"
}

output "development_project_name" {
  value = "${module.development.project_name}"
}
```

module/main.tf
```hcl
resource "google_project" "project" {
  name = "${random_id.random.hex}"
  project_id = "${random_id.random.hex}"
}

resource "random_id" "random" {
  prefix = "${var.project_prefix}"
  byte_length = "8"
}

resource "google_service_account" "vault_account" {
  account_id = "vault-account"
  display_name = "vault-account"
  project = "${google_project.project.project_id}"
}

resource "google_service_account_key" "vault_account_key" {
  service_account_id = "${google_service_account.vault_account.account_id}"
}

resource "google_project_iam_binding" "vault_service_account_binding" {
  role = "roles/editor"
  project = "${google_project.project.project_id}"

  members = [
    "serviceAccount:${google_service_account.vault_account.email}",
  ]
}
```

module/output.tf
```hcl
output "project_name" {
  value = "${google_project.project.name}"
}
```

module/variables.tf
```hcl
variable "project_prefix" {
  type = "string"
  description = "prefix for the project name"
}
```

### Crash Output

```
Error: Error applying plan:

1 error(s) occurred:

* module.development.google_service_account_key.vault_account_key: 1 error(s) occurred:

* google_service_account_key.vault_account_key: project: required field is not set

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Expected Behavior

When receiving the error, I expected to be able to just add the project to the resource and it to generate. 

The change was 

```hcl
resource "google_service_account" "vault_account" {
  account_id = "vault-account"
  display_name = "vault-account"
  project = "${google_project.project.project_id}"
}
```

### Actual Behavior

I got the error 

```
Error: module.development.google_service_account_key.vault_account_key: : invalid or unknown key: project
```

### Steps to Reproduce

```
terraform init
terraform apply
```

**Comment by Chupaka** [comment]
So, you're changing google_service_account.vault_account, but error about unknown key appears in google_service_account_key.vault_account_key?

**Comment by ksbeking** [comment]
Yes, I get the "crash output" with the supplied config. The "error" occurs when I change the `google_service_account_key.vault_account_key` 

from 
```hcl
resource "google_service_account_key" "vault_account_key" {
  service_account_id = "${google_service_account.vault_account.account_id}"
}
```

to 
```hcl
resource "google_service_account" "vault_account" {
  account_id = "vault-account"
  display_name = "vault-account"
  project = "${google_project.project.project_id}"
}
```

Copying this, I just realised that one of them has the `display_name`. I am sorry I made an error copying the version, that didn't seem to affect anything though.

**Comment by ksbeking** [comment]
No, I am being an idiot, you just add the line into the service account key. 

```
project = "${google_project.project.project_id}"
```

I am trying to create projects and return root credentials for that project.

**Comment by Chupaka** [comment]
So did you try previous versions? Like
```
provider "google" {
  version = "1.19"
}
```

**Comment by ksbeking** [comment]
Yep, I have tried with 1.19. Does not work either. I have used the workaround you linked to which did work. Thank you for that. Just feels bizarre that I need a new provider for one element, the service account key.

**Comment by emilymye** [comment]
Sorry for the confusion! The service account resource was implemented to expect service account id to contain the project. You should use the service account name (instead of `account_id`) as it has format `projects/my-project/serviceAccounts/vault-account@...`. 

i.e. the resource should be:

```
resource "google_service_account_key" "vault_account_key" {
  service_account_id = "${google_service_account.vault_account.name}"
}
```

We only try to determine project at provider-level if this service account id is not project-qualified, which is where we run into this issue. 

Unfortunately we didn't enforce the optional project field when either of these resources were submitted (both are handwritten). We can probably go ahead and add them just to make things less confusing.

**Comment by benfdking** [comment]
Thank you @emilymye. No need to apologise. Given the following documentation, I guess I deserve a significant part of the blame. 

```
service_account_id - (Required) The Service account id of the Key Pair. This can be a string in the format {ACCOUNT} or projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT}, where {ACCOUNT} is the email address or unique id of the service account. If the {ACCOUNT} syntax is used, the project will be inferred from the account.
```
