### ISSUE TITLE
google_monitoring_alert_policy documentation field 'invalid or unknown key'

### ISSUE THREAD

**Issue by ubergeek42** [terraform-providers/terraform-provider-google#2791]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.11.11
+ provider.cloudflare v1.4.0
+ provider.google v1.20.0
+ provider.google-beta v1.20.0
+ provider.newrelic v1.0.1
+ provider.null v1.0.0
+ provider.pagerduty v1.2.1
+ provider.template v1.0.0
```

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_monitoring_alert_policy" "container_memory_usage" {
  display_name          = "Container Memory Usage"
  combiner              = "OR"
  enabled               = true
  notification_channels = "${var.notification_channels}"

  documentation {
    content   = "some text"
    mime_type = "text/markdown"
  }

  conditions = [
    {
      display_name = "Container Memory Limit > 90% for 5m"

      condition_threshold {
        duration        = "300s"
        comparison      = "COMPARISON_GT"
        threshold_value = "0.9"
        filter          = "metric.type=\"kubernetes.io/container/memory/limit_utilization\" resource.type=\"k8s_container\""

        aggregations = [
          {
            alignment_period     = "60s"
            cross_series_reducer = ""
            per_series_aligner   = "ALIGN_MEAN"
            group_by_fields      = []
          },
        ]
      }
    },
  ]
}


```

### Expected Behavior

The documentation field of the alert policy should have been updated.

### Actual Behavior

Terraform threw an error message:
```
Error: snip.google_monitoring_alert_policy.container_memory_usage: : invalid or unknown key: documentation
```

### Steps to Reproduce

Create an alert policy with a documentation field.

### Important Factoids

I see that the code for this was merged into the provider 2.0 branch, but it's showing on the main website as being a field I can use: https://www.terraform.io/docs/providers/google/r/monitoring_alert_policy.html (search for `documentation`). So either the published documentation is wrong and should be corrected/changed; or the fix that adds the documentation key should be released.

### References

* #2523

**Comment by Chupaka** [comment]
According to the docs you mentioned, `documentation` is a key of `aggregation` block. Have you tried to nest it?

```
resource "google_monitoring_alert_policy" "container_memory_usage" {
  conditions = [
    {
      condition_threshold {
        aggregations = [
          {
            documentation {
              content   = "some text"
              mime_type = "text/markdown"
            }
          },
        ]
      }
    },
  ]
}
```

**Comment by chrisst** [comment]
Oh dear, it looks like the documentation for `documentation` made it into the 1.20 release but the code did not. What you have in your config is fixed in master and will be fixed as of our next release.

**Comment by ubergeek42** [comment]
@chrisst thanks for the information. Do you know if the next release be 2.x? or 1.21?(and will this fix be in both?)

**Comment by chrisst** [comment]
We plan on releasing 2.0, but the release process isn't completely in my hands. But any release should have support for `documentation`

**Comment by chrisst** [comment]
Well I failed to get the document updates in, but now the functionality is live with 2.0.0 so closing this.
