### ISSUE TITLE
"subnetwork project does not match" with shared VPC in another project

### ISSUE THREAD

**Issue by wmgroot** [terraform-providers/terraform-provider-google#2802]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.11
+ provider.google v1.20.0
```

### Affected Resource(s)

* google_compute_subnetwork
* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_compute_subnetwork" "kube-subnetwork" {
  name = "kube-subnetwork"
  project = "project1"
  ip_cidr_range = "10.X.X.X/22"
  region = "us-central1"
  network = "shared-vpc-network"

  secondary_ip_range = [
    {
      range_name = "kube-pods-range"
      ip_cidr_range = "10.X.X.X/18"
    },
    {
      range_name = "kube-services-range"
      ip_cidr_range = "10.X.X.X/20"
    }
  ]
}

resource "google_container_cluster" "primary" {
  project = "project2"

  name = "kube-cluster"
  zone = "us-central1-f"

  network = "https://www.googleapis.com/compute/v1/projects/project1/global/networks/shared-vpc-network"
  subnetwork = "${google_compute_subnetwork.kube-subnetwork.name}"
  # subnetwork = "https://www.googleapis.com/compute/v1/projects/project1/regions/us-central1/subnetworks/kube-subnetwork"  # using the selfLink allows me to correctly create the cluster

  ip_allocation_policy {
    cluster_secondary_range_name = "${google_compute_subnetwork.kube-subnetwork.secondary_ip_range.0.range_name}"
    services_secondary_range_name = "${google_compute_subnetwork.kube-subnetwork.secondary_ip_range.1.range_name}"
  }

  initial_node_count = 1
}
```

### Debug Output

https://gist.github.com/wmgroot/7291ea66c56febc5b8d118df3ca30c2c

### Expected Behavior

My GKE cluster should be created using a subnetwork that exists on a shared VPC network from another project.

### Actual Behavior

I receive an error that the project for the subnetwork does not match the project of the network, although the subnetwork is created correctly on the VPC network from the other project.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I am able to create the GKE cluster successfully if I use the full selfLink of the subnetwork. See the commented line in my Terraform config above.

In my case, the name of my shared VPC network is the same as the project where I'm trying to deploy my GKE cluster (in my example, "shared-vpc-network" == "project2"). Not sure if this is relevant to this issue.

**Comment by Chupaka** [comment]
What if you replace `kube-subnetwork.name` with `kube-subnetwork.self_link`?

**Comment by chrisst** [comment]
I'm pretty sure that when you don't define the full link as in your comment, you're getting a reference to just the `name` of the subnetwork at which point we're trying to infer the `project` from your `provider` block.

Can you confirm which project is set in your `provider` block? Also if you reproduce the error again with `TF_LOG=DEBUG` and add the output I'll be able to tell which project is getting sent with the payload.

Finally @Chupaka 's suggestion is a good work around, using the `self_link` should use a fully built reference to the subnetwork with the project defined.

**Comment by chrisst** [comment]
Unfortunately I don't think it's possible get this to work using just the reference to the `name`. Terraform doesn't support accessing fields on other resources at plan time, so we need to try and infer the correct `project`. We start with checking the `subnetwork` value to see if it's got the project as part of a fully qualified link and if not we fall back to the provider default (this is the behavior for all GCP resources).

It is impossible to know which is the 'correct' project between `google_container_cluster.primary.project` and `google_compute_subnetwork.kube-subnetwork.project` and the provider, because any of the 3 could be right. However given that the self_link is working I don't see this as needing to be resolved. Let me know if you understand differently.

**Comment by wmgroot** [comment]
Thanks for looking into this. In my case, the provider project is set to "project1". The only resource using "project2" is the `google_container_cluster` resource referencing the network and subnetwork, so it appears to be falling back to the cluster `project`, instead of the explicit `project` defined in the referenced `google_compute_subnetwork`, or the `project` defined in the current provider.

My provider block:
```
provider "google" {
  version = "~> 1.20"
  project = "project1"
  region = "us-central1"
  zone = "us-central1-f"
}
```

I think it would be convenient to users if the project value was pulled from `google_compute_subnetwork.kube-subnetwork.project` when comparing the projects of the network and subnetwork. Is there a time when `project` is not present for a `google_compute_subnetwork`?

I completely agree this is a super low priority inconvenience, I'm sure you have much more important fixes and features to work through. I'm content using `self_link`.

Thanks for working on an awesome tool!
