### ISSUE TITLE
Unable to Create Public Cluster with `private_cluster_config` block, even when `enable_private_endpoint = enable_private_nodes = false`

### ISSUE THREAD

**Issue by Jberlinsky** [terraform-providers/terraform-provider-google#2820]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* google_container_cluster

### Problem Statement

At present, due to shortcomings in the current version of Terraform and the implementation of `private_cluster_config` in this provider, it is not possible to specify a `private_cluster_config` block without making the cluster private. This prevents the development of wrapper modules without adding significant complexity to their implementation.

This issue was uncovered while developing [terraform-google-kubernetes-engine](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/51#pullrequestreview-189438122). In building out this module, we wish to allow users to specify whether their cluster should be public or private. However, due to the implementation at the provider level, it is not possible to do so -- since blocks can not be specified to resources in a modular manner, that resource is preordained to be private or not. Although the provider currently allows `private_cluster_config.enable_private_endpoint` and `private_cluster_config.enable_private_nodes` to both be `false`, `private_cluster_config. master_ipv4_cidr_block` is [required to be a valid CIDR](https://github.com/terraform-providers/terraform-provider-google/blob/91a513ab832f35673720f5f5902e1f6f34841169/google/resource_container_cluster.go#L571).

### Suggested Change(s)

It seems reasonable to allow an empty string (or some other control string) to be passed here, which the backing Golang code would interpret as an instruction to disregard the `master_ipv4_cidr_block` argument when populating the `google_container_cluster` resource.

**Comment by rileykarson** [comment]
I think this issue has to do with limitations in how modules can be configured! Since fields can't be excluded, the only nil-like behaviour we can have pre-0.12 is to set the empty string as the value.

Our validation means that we don't allow that- the value has to be a valid CIDR- so it's impossible to conditionally create a private cluster.

**Comment by emilymye** [comment]
Oh, I see! Alright, I'll go ahead and maybe add a customize diff then.

**Comment by Jberlinsky** [comment]
@emilymye Sorry for the delay. Do you still need something more specific from me?

**Comment by rileykarson** [comment]
Assigning this issue to myself since I'm also interested in having it fixed, I'll probably end up making the change by `2.0.0` / `2.0.1`.
