### ISSUE TITLE
Rendered documentation is misformatted

### ISSUE THREAD

**Issue by maguro** [terraform-providers/terraform-provider-google#2834]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

Documentation is misformatted:

https://www.terraform.io/docs/providers/google/r/composer_environment.html

**Comment by rileykarson** [comment]
Fixed with https://github.com/terraform-providers/terraform-provider-google/pull/2299 - this should be fixed with the next release.
