### ISSUE TITLE
google_monitoring_notification_channel: subsequent runs throw errors for slack and pagerduty

### ISSUE THREAD

**Issue by dodizzle** [terraform-providers/terraform-provider-google#2839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.11
+ provider.google v1.20.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.vault v1.4.1

### Affected Resource(s)
google_monitoring_notification_channel

### Terraform Configuration Files

```tf
resource "google_monitoring_notification_channel" "pagerduty" {
  display_name = "Pagerduty"
  type         = "pagerduty"

  labels = {
    service_key = "SECRET"
  }
}

resource "google_monitoring_notification_channel" "slack" {
  display_name = "Slack"
  type         = "slack"

  labels = {
    auth_token   = "SECRET"
    channel_name = "monitoring"
  }
}
```

### Debug Output
https://gist.github.com/dodizzle/e364a070c6a3f0e727a37f4878d50263

### Expected Behavior

After the pagerduty and slack notification channels have been created subsequent runs for terraform apply should not fail.

### Actual Behavior

2 errors occur.
1. For pagerduty it requires you to use a label named service_name.
2. For slack it requires you to use a label named owner.
Neither of these labels are required when listing the channel-descriptors.
ie. gcloud alpha monitoring channel-descriptors list

### Steps to Reproduce
Use the above tf config and run terraform apply followed by a second terraform apply

### References
https://cloud.google.com/monitoring/alerts/using-channels-api
https://www.terraform.io/docs/providers/google/r/monitoring_notification_channel.html
* #0000

**Comment by emilymye** [comment]
@dodizzle Hi! I'm working on getting the label diff fixed, but I can't seem to trigger the other errors through either Terraform or directly using the API/curl. It could be that they fixed it on the API side but for now I'm just going to fix the labels issue and wait and see if the other errors come up again.
