### ISSUE TITLE
Question: No data source for KMS key/ring?

### ISSUE THREAD

**Issue by kierachell** [terraform-providers/terraform-provider-google#2847]
Google Cloud Platform does not support destruction of KMS keys/rings. There exists a data source for a `kms_secret` with a bit of a hack for getting it, but (as mentioned in https://github.com/terraform-providers/terraform-provider-google/issues/1214; and https://github.com/terraform-providers/terraform-provider-google/issues/518 mentions importing key/ring every single time: not a fun workflow) it looks like it would make more sense to have KMS keys and rings a data source (instead of having to reimport them each time).

Is there a special reason why `data` source for KMS key/ring is not implemented? (I make a PR for one but wanted to ask first.)

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by emilymye** [comment]
It's true that we don't have them! If you do contribute them, please do so via https://github.com/GoogleCloudPlatform/magic-modules, where we have starting putting new code for Terraform in order to generate multiple versions of the provider and to autogenerate resources.

**Comment by chrisst** [comment]
Available at https://www.terraform.io/docs/providers/google/d/google_kms_crypto_key.html and https://www.terraform.io/docs/providers/google/d/google_kms_key_ring.html
