### ISSUE TITLE
Setting boot disk size on preemptable dataproc nodes forces recreate when number of preemptable instances is 0

### ISSUE THREAD

**Issue by schaffino** [terraform-providers/terraform-provider-google#2861]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.7
+ provider.google v1.19.0

### Affected Resource(s)

google_dataproc_cluster

### Terraform Configuration Files

```tf
resource "google_dataproc_cluster" "dataproc-cluster" {

  name   = "test"
  region = "europe-west1"

  cluster_config {

    gce_cluster_config {
      zone = "europe-west1-d"
    }

    master_config {
      num_instances = "1"
      machine_type  = "n1-standard-4"
      disk_config {
        boot_disk_size_gb = "500"
      }
    }

    worker_config {
      num_instances = "2"
      machine_type  = "n1-standard-4"

      disk_config {
        boot_disk_size_gb = "500"
      }
    }

    preemptible_worker_config {
     num_instances     = "0"
      disk_config {
        boot_disk_size_gb = "500"
      }
    }
  }
}
```

### Expected Behavior

The terraform apply operation should return successfully without altering infrastructure

### Actual Behavior

The cluster is destroyed and recreated

Plan shows  

cluster_config.0.preemptible_worker_config.0.disk_config.0.boot_disk_size_gb: "" => "500" (forces new resource)

### Steps to Reproduce

Run terraform apply twice in a row with the given config

### Important Factoids

If the cluster has 1 or more preemptable instances then the problem does not occur. If the cluster is created with 1 or more preemptable instances but is scaled down to 0 instances outside terraform the problem will occur on the next run.

**Comment by edwardmedia** [comment]
Using above code, I can repro the issue. my provider is v3.16.0
