### ISSUE TITLE
dataproc_cluster using global looks for subnetwork of worker nodes in global region

### ISSUE THREAD

**Issue by bantonj** [terraform-providers/terraform-provider-google#2863]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
v0.11.7
google provider: v1.20.0

### Affected Resource(s)
- dataproc_cluster

### Terraform Configuration Files
```hcl
resource "google_dataproc_cluster" "dataproc_cluster" {
  name   = "dm-qa-cluster-01"
  region = "global"

  cluster_config {
    staging_bucket = "dm-qa-cluster-01-staging"

    master_config {
      num_instances = 1
      machine_type  = "n1-standard-2"

      disk_config {
        boot_disk_type    = "pd-ssd"
        boot_disk_size_gb = 500
      }
    }

    worker_config {
      num_instances = 1
      machine_type  = "n1-standard-2"

      disk_config {
        boot_disk_size_gb = 500
        num_local_ssds    = 0
      }
    }

    preemptible_worker_config {
      num_instances = 0
    }

    gce_cluster_config {
      zone             = "us-west1-a"
      subnetwork       = "qa-dmxleo-private-us-west1"
      internal_ip_only = true
    }
  }
}
```

### Debug Output
https://gist.github.com/bantonj/23fcc751e999e97f7a85fb55e5400d30

### Panic Output
NOPE

### Expected Behavior
Terraform should have set "subnetworkUri": "projects/qa-dmxleo/regions/**us-west1**/subnetworks/qa-dmxleo-private-us-west1" based on the zone of the gce_cluster_config. 

### Actual Behavior
Instead it used the region from the parent, global. "subnetworkUri": "projects/qa-dmxleo/regions/**global**/subnetworks/qa-dmxleo-private-us-west1". Maybe requiring the self_link to avoid this?

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
NOPE

### References
NOPE

**Comment by edwardmedia** [comment]
@bantonj yes, I was using the data source of the subnet for the config and the resources were created successfully. Below is the HCL I was using to test. Based on the result I got, I am closing the issue. Please feel free to reopen it if this is still an issue with you. Thanks
```tf
resource "google_dataproc_cluster" "dataproc_cluster" {
  name   = "dm-qa-cluster-01"
  region = "global"

  cluster_config {
    staging_bucket = "coolbucket-dev"

    master_config {
      num_instances = 1
      machine_type  = "n1-standard-2"

      disk_config {
        boot_disk_type    = "pd-ssd"
        boot_disk_size_gb = 500
      }
    }

    worker_config {
      num_instances = 2
      machine_type  = "n1-standard-2"

      disk_config {
        boot_disk_size_gb = 500
        num_local_ssds    = 0
      }
    }

    preemptible_worker_config {
      num_instances = 0
    }

    gce_cluster_config {
      zone             = "us-west1-a"
      subnetwork       = data.google_compute_subnetwork.my-subnetwork.name
      internal_ip_only = false
    }
  }
}

data "google_compute_subnetwork" "my-subnetwork" {
  name   = "defauult"
  region = "us-east1"
}
```
