### ISSUE TITLE
Add ignore_changes to google_compute_ssl_certificate

### ISSUE THREAD

**Issue by lagerstrom** [terraform-providers/terraform-provider-google#2867]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In resource google_compute_ssl_certificate there is the lifecycle map. For the moment it only accepts create_before_destroy as one of the keys. I would be really useful if we could have the ignore_changes field as well. For example when you have updated the SSL certificates manually and don't want to add the old ones that are checked-in in the terraform repo again. One example could look like this 

### New or Affected Resource(s)

I am using provider.google v1.20.0 and it doesn't work for me.

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_ssl_certificate" "default" {
  name_prefix = "certificates-"
  description = "The certificates for the enivronment"

  private_key = "${file("certs/privkey1.pem")}"
  certificate = "${file("certs/fullchain1.pem")}"

  lifecycle {
    ignore_changes = [
      "ssl_certificates",
      "*"
    ]
  }
}

```

### References

* #0000

**Comment by Chupaka** [comment]
So, how it "doesn't work"? Where's the problem log?

**Comment by lagerstrom** [comment]
@Chupaka Ah look at that, I just didn't understand that it should have been in the google_compute_target_https_proxy. Changed that and now it works as I want it to. We can close this request :) Thank you for your help :+1:
