### ISSUE TITLE
Data source "region instance group" attribute size cannot be referenced by a count for iterative route creation in Google Cloud.

### ISSUE THREAD

**Issue by Red--** [terraform-providers/terraform-provider-google#2873]
Per this terraform page (https://www.terraform.io/docs/providers/google/d/datasource_compute_region_instance_group.html), I should be able to reference the size attribute to get the number of running instances from the regional instance group data source.

Example

resource "google_compute_route" "backbone_network_to_prod_supernet" {
  count = "${data.google_compute_region_instance_group.[group_name].size}"
  .... more settings ...
}

This results in an error:  

* module.[project-name].google_compute_route.backbone_network_to_prod_supernet: google_compute_route.backbone_network_to_prod_supernet: value of 'count' cannot be computed

I have tried iterating over the length of the list of instances, referencing the size, and other methods, to no avail.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug) then please include both the
# version of the config before the change, and the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Red--** [comment]
NOTE:  I can call the region instance group in the Google API Explorer and it returns the "size" count of the same group I am trying to reference within my terraform script. This tells me that it does exist, there is just an issue with how Terraform is pulling the information from Google's APIs.

**Comment by rileykarson** [comment]
Unfortunately, there's nothing we can do in the provider to fix this. Duplicates https://github.com/hashicorp/terraform/issues/12570.
