### ISSUE TITLE
API and documentation for google-beta provider incomplete or inconsistent

### ISSUE THREAD

**Issue by rvaidya** [terraform-providers/terraform-provider-google#2880]
Filing here since google-beta doesn't have an issue tracker.

Is the google-beta provider ready to be used with a stable API? The documentation link from the github repo is a 404 (https://www.terraform.io/docs/providers/google-beta/), and there are differences in configuration between google and google-beta that are not documented

Example: https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_instance_group_manager.go vs https://github.com/terraform-providers/terraform-provider-google-beta/blob/master/google-beta/resource_compute_instance_group_manager.go

In beta, "version" is required and has completely replaced a standalone "instance_template" and "rolling_update_policy" is just "update_policy"

If the beta provider is not ready, I think the deprecation warnings for beta features should be removed until it is.

**Comment by rileykarson** [comment]
@paddycarver: Assigning you to fix/redirect the link in the `google-beta` repo

**Comment by rvaidya** [comment]
Can you add the note about "version" and "update_policy" (and anything else we need to be aware of) to https://www.terraform.io/docs/providers/google/provider_versions.html

This is the first place I looked for migrating to google-beta.  Since the "Converting resources between versions" section is so short, it almost makes it seem like changing provider="google" to provider="google-beta" and back again is all you need if you're not using beta fields

**Comment by paddycarver** [comment]
This has been deployed, terraform.io/docs/provider/google-beta now redirects to terraform.io/docs/provider/google.
