### ISSUE TITLE
google_container_cluster.ip_allocation_policy could use a field to enable google private access

### ISSUE THREAD

**Issue by david-wb** [terraform-providers/terraform-provider-google#2885]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `ip_allocation_policy` field has a helpful option `create_subnetwork` to create the cluster subnet automatically. The problem for me is that the auto-created subnet does not have google private access enabled. Some of my workloads require this (such as google ESP). To workaround this, I had to define a custom subnet with private access enabled. It would be nice if that could be handled automatically. 

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_container_cluster" "cluster" {
  ...

  ip_allocation_policy {
    create_subnetwork            = true
    enable_google_private_access = true
  }

  ...
}
```

**Comment by paddycarver** [comment]
As `create_subnetwork` was removed in 3.0.0, I'm going to close this out, with the recommendation being the same as the `create_subnetwork` removal recommendation: create a subnetwork explicitly. If this doesn't work for your use case, please feel free to open a new issue. Thanks!
