### ISSUE TITLE
google_compute_router docs state BGP optional, but plan fails stating its mandatory

### ISSUE THREAD

**Issue by steven-edgar** [terraform-providers/terraform-provider-google#2886]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.7

Google Terraform Provider 1.15

### Affected Resource(s)

* google_compute_router

### Terraform Configuration Files

```tf
resource "google_compute_router" "router-on-prem-1" {
            network = "vpc_network_1"
            description = "Router back to on-prem networks"
            depends_no = [ "google_network.vpc_network_1" ]
}

```

### Expected Behavior

Compute router resource created

### Actual Behavior

Following string on stderr

Error: google_compute_router.router-on-prem: "bgp": required field is not set

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I presume this is a documentation error, which lists the "bgp" argument as optional, as the GCP Web console requires the BGP ASN to be provided when provisioning a router. 

### References

* #0000

**Comment by rileykarson** [comment]
I'm not able to reproduce on `2.0.0`; I have a config where the field is unset.
