### ISSUE TITLE
Period field in google_monitoring_uptime_check_config.http cannot be updated

### ISSUE THREAD

**Issue by jaceq** [terraform-providers/terraform-provider-google#2887]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

terraform -v
Terraform v0.11.11
+ provider.external v1.0.0
+ provider.google v1.20.0
+ provider.kubernetes v1.5.0
+ provider.null v1.0.0
+ provider.random v2.0.0

### Affected Resource(s)

google_monitoring_uptime_check_config.http

### Debug Output
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ google_monitoring_uptime_check_config.http
      period: "60s" => "300s"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_monitoring_uptime_check_config.http: Modifying... (ID: projects/XXX/uptimeCheckConfigs/http-uptime-check-1547634101)
  period: "60s" => "300s"

Error: Error applying plan:

1 error(s) occurred:

* google_monitoring_uptime_check_config.http: 1 error(s) occurred:

* google_monitoring_uptime_check_config.http: Error updating UptimeCheckConfig "projects/XXX/uptimeCheckConfigs/http-uptime-check-1547634101": googleapi: Error 400: Cannot change the period

```

### Expected Behavior

If period field cannot be updated, TF should destroy / create resource

### Actual Behavior
TF tries to perform in-place update while API refuses to do so

### Steps to Reproduce

Create a http check google_monitoring_uptime_check_config.http and then try to modify 'period' field.

**Comment by Chupaka** [comment]
Please read the doc carefully:

>Currently, the only supported values are 60s (1 minute), 300s (5 minutes), 600s (10 minutes), and 900s (15 minutes). Optional, defaults to 300s.

**Comment by jaceq** [comment]
@Chupaka  Yes, I also tried with 60s -> 300s and that gives same error. Will update original description

**Comment by sergei-ivanov** [comment]
Duplicates #2703
