### ISSUE TITLE
CoreOS/COS Images use "user-data" instead of "startup-script" metadata

### ISSUE THREAD

**Issue by ghost** [terraform-providers/terraform-provider-google#2896]
Based on the issue mentioned here: https://github.com/coreos/ignition/issues/654

Running CoreOS or COS images on compute instances is a bit tricky at the moment since `metadata_startup_script` is essentially useless for them. It is also unclear what format those scripts should be (yml vs bash vs ignition?). There's no mention of `user-data` in the terraform docs.

Here are just some of the "what looks like relevant docs" that did not really clarify the situation:

- https://cloud.google.com/container-optimized-os/docs/how-to/run-container-instance
- https://www.terraform.io/docs/providers/google/r/compute_instance.html
- https://coreos.com/os/docs/latest/booting-on-google-compute-engine.html

Not sure if really a bug or a feature request but:
Would it make sense to add a `metadata_user_data` argument to `compute_instance` for images that rely on `user-data`? Since right now one is required to hack in a `user-data` metadata key to have the same functionality as `metadata_startup_script`?

This works with COS/CoreOS but it's hard to tell what kind of file format to pass there:

```
  metadata = {
    user-data               = "${file("etcd_startup.ign")}"
  }
 ```

This does not work

```
  metadata_startup_script = "${data.template_file.etcd_node-startup.rendered}"
```

SO, the request is:

- Change `metadata_startup_script` to supply `user_data` as well depending on the image?
- Remove it for clarity?
- Add `metadata_user_data`?
- Provide "verified working" examples. 

---

Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by danawillow** [comment]
Revisiting: add docs on the difference between metadata and metadata_startup_script
