### ISSUE TITLE
Add data source to encrypt data with KMS key

### ISSUE THREAD

**Issue by zombiezen** [terraform-providers/terraform-provider-google#2898]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I'd like to have the inverse of the `google_kms_secret` data source, which allows for decrypting cipher text. My use case is storing an encrypted value in a Runtime Configurator config.

### New or Affected Resource(s)

Perhaps something like: `google_kms_ciphertext`?

### Potential Terraform Configuration

```tf
data "google_kms_ciphertext" "myencryptedconfig" {
  crypto_key = "${google_kms_crypto_key.my_crypto_key.id}"
  plaintext = "hello world"
}

resource "google_runtimeconfig_config" "myconfig" {
  name = "myconfig"
}

resource "google_runtimeconfig_variable" "myvar" {
  name = "myvar"
  parent = "${google_runtimeconfig_config.myconfig.name}"
  project = "${google_runtimeconfig_config.myconfig.project}"
  value = "${base64encode(data.google_kms_ciphertext.myencryptedconfig.ciphertext)}"
}
```

**Comment by megan07** [comment]
Thanks @zombiezen for opening this issue. It has been added with https://github.com/GoogleCloudPlatform/magic-modules/pull/2135 and was released in 2.14.0 release.
