### ISSUE TITLE
Add Unmanaged Instances group

### ISSUE THREAD

**Issue by andelhie** [terraform-providers/terraform-provider-google#2913]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Right now there really no way with managed region instance group to get just the instance name just the instance URL.  So one way around it in the GCP console is to use unmanaged instance group.

This would then let me add unmanaged instance to a LB.

### New or Affected Resource(s)

* google_compute_unmanaged_instance_group

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
 resource "google_compute_instance_group_unmanaged" "unmanaged" {
  name = "unmanaged"
  description = "something here about being unmanaged group"
  region = "us-east1"
  instances = ["${var.google_compute.instancename.*.self_link}",]
}
```

### References

https://cloud.google.com/compute/docs/instance-groups/creating-groups-of-unmanaged-instances

* #0000

**Comment by ndmckinley** [comment]
>Right now there really no way with managed region instance group to get just the instance name just the instance URL.

I'd add that the last element of the URL, from the final slash to the end of the string, is the `name`, if that helps.

**Comment by ndmckinley** [comment]
https://www.terraform.io/docs/configuration/interpolation.html#basename-path- should do that for you, right?

**Comment by andelhie** [comment]
That may do it did not think about using that one.

**Comment by andelhie** [comment]
This did work but I have to crap this as I can get the host name but not the IP of the instance in an instance region group manager.  With out the IP ansible will not be able to ssh over to the nodes.

**Comment by rambleraptor** [comment]
Hello! I do some Ansible work for Google Cloud.

You'll want to ssh into a random instance using `gcloud compute ssh` or upload SSH keys to the GCP [metadata server](https://console.cloud.google.com/compute/metadata/sshKeys). If you use `gcloud compute ssh`, a pair of public/private keys will be created under `~/.ssh/google_compute_engine[.pub]`. 

Once you've done that, you can use those keys with Ansible.
