### ISSUE TITLE
Instance with inline boot_disk and initialize_params breaks on type pd-ssd

### ISSUE THREAD

**Issue by nodesocket** [terraform-providers/terraform-provider-google#292]
### Terraform Version
`v0.10.0`

### Affected Resource(s)
`google_compute_instance`

### Terraform Configuration Files
```
variable "zones" {
    type = "list"
    default = [
        "us-west1-a",
        "us-west1-b",
        "us-west1-c"
    ]
    description = "The zones to provision into"
}

resource "google_compute_instance" "rethinkdb" {
    count = 3
    name  = "rethinkdb${count.index + 1}"
    machine_type = "f1-micro"
    zone = "${element(var.zones, count.index)}"

    tags = ["rethinkdb"]

    boot_disk {
        initialize_params {
            image = "rethinkdb-ubuntu-1604-lts"
            type  = "pd-ssd"
            size = 10
        }
        auto_delete = true
    }

    network_interface {
        network = "default"
        access_config {
            # ephemeral external ip address
        }
    }

    scheduling {
        preemptible = false
        on_host_maintenance = "MIGRATE"
        automatic_restart = true
    }
}
```

### Expected Behavior
This should create instances with each having a 10GB SSD boot disk using the image `rethinkdb-ubuntu-1604-lts`.

### Actual Behavior
* google_compute_instance.node.0: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.disks[0].initializeParams.diskType': 'pd-ssd'. The URL is malformed., invalid

**Comment by rileykarson** [comment]
Thanks for the report @nodesocket!

We didn't catch this issue before our last provider release, but #275 appears to have fixed it and added a test so we can prevent something similar happening in the future. If this bug happens again after the next Google provider release, feel free to re-open the issue.

**Comment by nodesocket** [comment]
@rileykarson does #275 also fix https://github.com/terraform-providers/terraform-provider-google/issues/218#issuecomment-320117936?

**Comment by rileykarson** [comment]
I don't believe so; that will need to be made as a separate change.

**Comment by nodesocket** [comment]
@rileykarson any idea when this fix will ship? Also, what is the process of updating a Terraform plugin? Is it just `terraform init` again?

**Comment by rosbo** [comment]
We should a new version of the google provider in a week or so.

Yes, terraform init will fetch the latest google gcp provider.
