### ISSUE TITLE
google_compute_router_nat wants to recreate resources even though nothing has changed

### ISSUE THREAD

**Issue by bantonj** [terraform-providers/terraform-provider-google#2928]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

v0.11.7
google provider: v1.20.0

### Affected Resource(s)

* google_compute_router_nat

### Terraform Configuration Files

```
resource "google_compute_router" "router-asia-southeast1" {
  name    = "router-asia-southeast1"
  region  = "asia-southeast1"
  network = "staging-dmxleo"
}

resource "google_compute_router_nat" "nat-asia-southeast1" {
  name                               = "nat-asia-southeast1"
  router                             = "${google_compute_router.router-asia-southeast1.name}"
  region                             = "asia-southeast1"
  nat_ip_allocate_option             = "AUTO_ONLY"
  source_subnetwork_ip_ranges_to_nat = "LIST_OF_SUBNETWORKS"

  subnetwork {
    name = "${google_compute_subnetwork.staging-dmxleo-private-asia-southeast1.self_link}"
  }
}
```

### Debug Output

https://gist.github.com/bantonj/461cfe40e186c3510b3a16896fe96b5a
### Expected Behavior

When running apply no changes should be made.

### Actual Behavior

Terraform wants to make changes because of some subnetwork related changes that it didn't take note of, or GCP changed later.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply` again

### References

* #0000

**Comment by Chupaka** [comment]
I can't find Plan in your debug output for some reason... And the answer is in the plan

**Comment by bantonj** [comment]
Sorry about that, I updated the gist with the full output.

**Comment by ndmckinley** [comment]
The workaround here is to set `subnetwork.source_ip_ranges_to_nat` to `[LIST_OF_SUBNETWORKS]`, but that's something we can do in code.

**Comment by ndmckinley** [comment]
Oh, never mind, it seems like we have actually added the `Required` tag to that field - in the next release it will be required.  In the meantime, the correct approach is to set that value.
