### ISSUE TITLE
Mismatch between docs and stable provider around CloudSQL private instances

### ISSUE THREAD

**Issue by smaslennikov** [terraform-providers/terraform-provider-google#2937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
$ terraform version
Terraform v0.11.11
+ provider.google v1.19.1
```

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "master" {
  name = "${var.name}"
  database_version = "POSTGRES_9_6"
  region = "${var.region}"

  settings {
    tier = "${var.tier}"
    disk_size = "${var.disk_size}"
    disk_autoresize = true

    database_flags {
      name = "temp_file_limit"
      value = "2147483647"
    }

    ip_configuration {
      require_ssl = true
      private_network = "${var.private_network_self_link}"
    }
  }
}
```

### Debug Output

```
Error: module.cloudsql.google_sql_database_instance.master: settings.0.ip_configuration.0: invalid or unknown key: private_network
```

### Expected Behavior

According to [docs](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#private-ip-instance), this is valid syntax. It's expected that the CloudSQL instance comes up with a private IP.

### Actual Behavior

Terraform does not validate the code.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

According to https://github.com/terraform-providers/terraform-provider-google/issues/2127 , it seems the provider won't actually support this until v2.0.0. Since the docs are present, however, one would expect support to be present in a stable version as well.

**Comment by rileykarson** [comment]
It looks like you're on `1.19.1`, and the feature was added in `1.20.0`; https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#1200-december-14-2018

Sorry for the confusion around versions- we expected at the time that `2.0.0` would be the next release, but ended up making release `1.20.0`. If this doesn't work after upgrading, feel free to comment on this issue and we'll reopen it.

**Comment by smaslennikov** [comment]
@rileykarson Ah, thank you, that makes a whole lot of sense. Things are working now, and I don't have to build the provider to use it. 

Cheers!
