### ISSUE TITLE
Add support for PARTNER Interconnect VLAN attachments

### ISSUE THREAD

**Issue by goobysnack** [terraform-providers/terraform-provider-google#2942]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The current feature set for the resource "google_compute_interconnect_attachment" doesn't allow for "partner interconnect", which requires keys "type" and "edgeAvailabilityDomain" from the api.  It also requires that the key interconnect to have a set field, which should be left out of the gcloud command or api call.

### New or Affected Resource(s)

resource "google_compute_interconnect_attachment"

### Potential Terraform Configuration
```tf
resource "google_compute_interconnect_attachment" "foobar" {
  project      = "${google_project.project.id}"
  region       = "${var.region}"
  name         = "${var.vlan_foobar}"
  type         = "PARTNER"
  router       = "${google_compute_router.router_foobar.name}"
  edgeAvailabilityDomain = "AVAILABILITY_DOMAIN_1"
}
```

### References

https://www.terraform.io/docs/providers/google/r/compute_interconnect_attachment.html
https://cloud.google.com/sdk/gcloud/reference/compute/interconnects/create
https://cloud.google.com/compute/docs/reference/rest/v1/interconnectAttachments/insert

**Comment by cblecker** [comment]
@ndmckinley 👋  It looks like you were working on this resource recently.. is exposing the additional API fields to create a partner interconnect complicated? I'd have a look at it myself, but I haven't done much with the Magic Modules stuff.

**Comment by danawillow** [comment]
Added in https://github.com/GoogleCloudPlatform/magic-modules/pull/1323.
