### ISSUE TITLE
GKE support for fuzzy version

### ISSUE THREAD

**Issue by apetitbois** [terraform-providers/terraform-provider-google#2949]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google keeps on bumping revision of available gke cluster version.
Their API supports a fuzzy logic to determine which version you want to build as seen in that [link](https://cloud.google.com/kubernetes-engine/versioning-and-upgrades#specifying_cluster_version)

Today, we want to be able to build consistently our cluster with the same major/minor versions of kube.
For example, I'd like to be able to specify building 1.11.6 and not 1.11.6-gke.5 which may or may not supported in a couple of days and break my pipelines.

### New or Affected Resource(s)

google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "controlPlane" {
    name               = "${var.cluster_name}"
    region             = "${var.cluster_region}"

    min_master_version = "1.11.5-gke.5"
[...]
}
```

```tf
resource "google_container_cluster" "controlPlane115" {
    name               = "${var.cluster_name}"
    region             = "${var.cluster_region}"

    min_master_version = "1.11.5"
[...]
}

resource "google_container_cluster" "controlPlaneLatest" {
    name               = "${var.cluster_name}"
    region             = "${var.cluster_region}"

    min_master_version = "latest"
[...]
}
```

### References

https://cloud.google.com/kubernetes-engine/versioning-and-upgrades#specifying_cluster_version

**Comment by petervandenabeele** [comment]
Just to make sure, is this not _already_ working for `min_master_version`?

`min_master_version = "1.11.6"` works for me. I changed it from the `1.11.N-gke.M` style like 2 months ago.

For node version, I do keep the "1.11.6-gke.2" style.

**Comment by apetitbois** [comment]
You are correct, I was mistaken and the error message was indeed coming from my node pool and not from my control plane.

I'll close this issue as I'm now buliding my nodepools with version = "{....controlPlane.master_version}"
