### ISSUE TITLE
google_compute_zones behavior different (empty) with Beta provider

### ISSUE THREAD

**Issue by clebio** [terraform-providers/terraform-provider-google#2955]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

# Summary 

When using the `google-beta` provider, the data source `google_compute_zones` returns an empty list.

### Terraform Version

```
$ terraform --version
Terraform v0.11.11
+ provider.google v1.20.0
+ provider.google-beta v1.20.0
```

### Affected Resource(s)

* google_compute_zones

### Terraform Configuration Files

Works as expected (provided you `export TF_VAR_project=$(gcloud config list project --flatten core.project --format json| jq '.[]' -r)` )
```tf
variable "region" {
  default = "us-central1"
}

variable "project" {
  description = "GCP project ID"
}

provider "google" {
  project = "${var.project}"
  region  = "${var.region}"
}

data "google_compute_zones" "available" {}

output "zones" {
  value = "${data.google_compute_zones.available.names}"
}
```

#### output
```sh
$ terraform apply
data.google_compute_zones.available: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

zones = [
    us-central1-a,
    us-central1-b,
    us-central1-c,
    us-central1-f
]
```

### Expected Behavior

The beta provider should also return a valid list of zones. For comparison,
```sh

$ gcloud compute zones list  --filter=region=us-central1
NAME           REGION       STATUS  NEXT_MAINTENANCE  TURNDOWN_DATE
us-central1-c  us-central1  UP
us-central1-a  us-central1  UP
us-central1-f  us-central1  UP
us-central1-b  us-central1  UP
```
versus
```sh
$ gcloud beta compute zones list  --filter=region=us-central1
NAME           REGION       STATUS  NEXT_MAINTENANCE  TURNDOWN_DATE
us-central1-c  us-central1  UP
us-central1-a  us-central1  UP
us-central1-f  us-central1  UP
us-central1-b  us-central1  UP
```

#### Beta provider version

 Change only the provider in the above Terraform (to `google-beta`):
```tf
provider "google-beta" {
  project = "${var.project}"
  region  = "${var.region}"
}
```

#### Output
```sh
$ terraform apply
data.google_compute_zones.available: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

zones = []
```

### Steps to Reproduce

0. Use terraform code above.
1. `terraform apply`

**Comment by rileykarson** [comment]
Hey @clebio!

This is one of the weird cases of the `google-beta` provider; even though you've only defined a `google-beta` block, Terraform still thinks it should use `google` for the datasource. See https://www.terraform.io/docs/providers/google/provider_versions.html#using-the-google-beta-provider

You can add `provider = "google-beta"` and the correct provider will be associated with the datasource.
