### ISSUE TITLE
Creating a GKE cluster with large disk space timeout with API error

### ISSUE THREAD

**Issue by michyliao** [terraform-providers/terraform-provider-google#2960]
Hi all,

I am creating a GKE cluster with diskspace of 15TB. When we try to create a cluster with large nodes - the resizing takes time, but the cluster will eventually time out due to health check of nodes with the following error:

`Error waiting for creating GKE cluster: All cluster resources were brought up, but the cluster API is reporting that: only 0 nodes out of 3 have registered; cluster may be unhealthy.`

This is because the nodes are not available yet due to it resizing from the default to 15TB. I have waited until all the nodes were done resizing but the cluster configuration is still in error mode and won't connect to the nodes. This errors out in terraform and we won't be able to keep the configuration. This is probably on both GCP and Terraform side as well. I've also tried the timeout configuration - but by default create is at 30mins, but it errors around 16mins. 

Currently we create a cluster with default values and resize it manually, but we would like to have it all in the configurations since nodes can go down any moment! Let me know if we are missing any configurations on our side with terraform or not! 

Thanks

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

**Comment by rileykarson** [comment]
Hey @michyliao!

Out of curiosity, does configuring this work from the Cloud Console / `gcloud`? As well, if you start this in Terraform and wait a while (but before the error is returned) what does the Console show on the cluster? It may have an updated warning/error that Terraform doesn't display.

**Comment by michyliao** [comment]
Hey @rileykarson 

I've only ran it through terraform, and terraform errors out, same with console. I will give gcloud a try.

**Comment by rileykarson** [comment]
Thanks @michyliao! The most interesting piece of information is probably what the Console shows while the creation is in progress; it may have an error that the other clients (Terraform and `gcloud`) can't display.

**Comment by rileykarson** [comment]
Thanks for your diligence @michyliao!

Since we're getting the same error across multiple clients, this seems like a GKE-side error. Can you file an issue in the [GKE issue tracker](https://issuetracker.google.com/issues/new?component=187077&template=1162666)? (Also, if you don't mind linking that issue here so I can track it as well.)

**Comment by michyliao** [comment]
@rileykarson 

Submitted the ticket! https://issuetracker.google.com/issues/123635831

**Comment by rileykarson** [comment]
Great! Looks like this has been resolved using a new Kubernetes version. Can you attempt this with that version?

**Comment by michyliao** [comment]
@rileykarson 

I was able to create a GKE with 15TB with the latest version!
