### ISSUE TITLE
Creating a google_container_cluster without the optional node_config block crash Terraform

### ISSUE THREAD

**Issue by rosbo** [terraform-providers/terraform-provider-google#297]
Hi there,

### Terraform Version
0.10.0
### Affected Resource(s)

- google_container_cluster

### Terraform Configuration Files
```hcl
resource "google_container_cluster" "c1" {
  name = "test-cluster"
  zone = "us-central1-a"
  initial_node_count = 1
}
```

### Panic Output
[crash.log](https://gist.github.com/rosbo/ec7c3f3ba960d8125c87e389ad1e097b)

It fails because `*container.NodeConfig` is nil when reading from GCP api. The following block should handle the nil case:
```go
func flattenClusterNodeConfig(c *container.NodeConfig) []map[string]interface{} {
	config := []map[string]interface{}{
		{
			"machine_type":    c.MachineType,
			"disk_size_gb":    c.DiskSizeGb,
			"local_ssd_count": c.LocalSsdCount,
			"service_account": c.ServiceAccount,
			"metadata":        c.Metadata,
			"image_type":      c.ImageType,
			"labels":          c.Labels,
			"tags":            c.Tags,
		},
	}

	if len(c.OauthScopes) > 0 {
		config[0]["oauth_scopes"] = c.OauthScopes
	}

	return config
}
```

### Expected Behavior
Not crash especially since the `node_config` is actually Optional.

### Actual Behavior
Crashed.

### Steps to Reproduce
1. `terraform apply`
2. Delete node pools from the UI
3. Run terraform `apply` or `plan` and it crashes.

**Comment by danawillow** [comment]
Hmm, I can't reproduce this. Do you have a sample config that applies successfully but sends back a nil `NodeConfig`? I tried the one you posted but I got the error ` Error 400: cluster.initial_node_count must be greater than zero., badRequest`. If I add an `initial_node_count` then it applies successfully but also sends back a `NodeConfig`.

**Comment by rosbo** [comment]
I have been able to repro. I updated the steps in the original issue description.

I have a fix. I will open a PR in a few minutes.

**Comment by rosbo** [comment]
I opened a PR to fix the issue.
