### ISSUE TITLE
google_compute_instance datasource: cannot create using self_link field

### ISSUE THREAD

**Issue by gillesgagniard** [terraform-providers/terraform-provider-google#2972]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.11
+ provider.google v1.20.0

### Affected Resource(s)

* google_compute_instance datasource

### Terraform Configuration Files

```tf
data "google_compute_instance_group" "all_nodes" {
  self_link = "${google_container_cluster.my_gke.instance_group_urls[0]}"
}

data "google_compute_instance" "my_node" {
  self_link = "${data.google_compute_instance_group.all_nodes.instances[0]}"
}
```

### Expected Behavior

I should be able to initialize a `google_compute_instance` datasource from a self_link, for instance from one retrieved  from a google_compute_instance_group. I shouldn't have to pass the name/zone fields.

BTW, this is the documented behaviour: https://www.terraform.io/docs/providers/google/d/datasource_compute_instance.html

### Actual Behavior

I get the following output:

Error: data.google_compute_instance.my_node: "name": required field is not set

Error: data.google_compute_instance.my_node: "self_link": this field cannot be set

### Steps to Reproduce

1. `terraform apply`

**Comment by rileykarson** [comment]
Fixed by https://github.com/terraform-providers/terraform-provider-google/pull/2874, this is coming in `2.0.0`.
