### ISSUE TITLE
Resource id format for google_container_node_pool is too restrictive

### ISSUE THREAD

**Issue by rosbo** [terraform-providers/terraform-provider-google#298]
Hi there,

The id for `google_container_node_pool` is its `name`. However, you can have two distinct node pool with the same name as long as they are in different clusters.

### Terraform Version
0.10.0

### Affected Resource(s)

- google_container_node_pool

### Terraform Configuration Files

This creates two `google_container_node_pool` with the same name in two different `google_container_cluster`. This is valid. The name only has to be unique inside a given zone.

```hcl
resource "google_container_cluster" "cluster1" {
  name = "tf-cluster-nodepool1"
  zone = "us-central1-a"
  initial_node_count = 2

  master_auth {
    username = "mr.yoda"
    password = "adoy.rm"
  }

  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]
  }
}

resource "google_container_cluster" "cluster2" {
  name = "tf-cluster-nodepool2"
  zone = "us-central1-a"
  initial_node_count = 2

  master_auth {
    username = "mr.yoda"
    password = "adoy.rm"
  }

  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]
  }
}

resource "google_container_node_pool" "pool1" {
  name = "my-pool"
  zone = "${google_container_cluster.cluster1.zone}"
  cluster = "${google_container_cluster.cluster1.name}"
  initial_node_count = 1
}

resource "google_container_node_pool" "pool2" {
  name = "my-pool"
  zone = "${google_container_cluster.cluster2.zone}"
  cluster = "${google_container_cluster.cluster2.name}"
  initial_node_count = 1
}
```

### Debug Output

```
  + google_container_node_pool.pool1
      cluster:            "tf-cluster-nodepool1"
      initial_node_count: "1"
      name:               "my-pool"
      node_config.#:      "<computed>"
      zone:               "us-central1-a"
```

### Expected Behavior
No Diff, the node pools exist!

### Actual Behavior
It shows a diff because the first node pool who gets created is overwritten in the state by the second node pool because they have the same id (remember id == name).

### Steps to Reproduce

1. `terraform apply`

**Comment by drebes** [comment]
``google_compute_router_interface`` and ``google_compute_router`` have a similar relationship to ``google_container_node_pool`` and ``google_container_cluster`` (the first is a sub-resource of the second). The way we set the Id there is in the form {region}/{cluster}/{interface}, which is also how the interface gets imported. We may use the same model here.

**Comment by danawillow** [comment]
Fyi it's possible that this resource will be going away- check out #285, would love a dissenting opinion if you have one :)
