### ISSUE TITLE
Open in Cloud Shell destroys your Cloud Shell Instance

### ISSUE THREAD

**Issue by darnold-harness** [terraform-providers/terraform-provider-google#2990]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Panic Output
This is my own personal Panic Output... "What The F***!? Where are my files!?"

### Expected Behavior
Does not delete all of the files in your Google Cloud Shell. As per the README with in the cloud shell,
``` 
Your 5GB home directory will persist across sessions, but the VM is ephemeral and will be reset
approximately 20 minutes after your session ends. No system-wide change will persist beyond that.
```
My files should have been left intact.

### Actual Behavior
My files were all deleted.

### Steps to Reproduce
Create some files in a cloud shell instance, then click the fancy new "Open in Cloud Shell" link in the Terraform docs.

**Comment by rileykarson** [comment]
Right! So this is a little unintuitive but your files are still present. When normally using Cloud Shell, you have a persistent home directory that is carried across sessions, and this is almost always true. The Open in Cloud Shell links we include in our docs use a custom image, and when you're using a custom image you're given an ephemeral home environment.

There isn't a _great_ way to switch between the ephemeral home and your persistent home again in a short period of time, but waiting ~20 minutes for the ephemeral home to time out and launching a new Cloud Shell session will use your persistent home again.

**Comment by rileykarson** [comment]
They're deleted when closed, as the session is temporary; pulling the message on session launch:

>This session will run the temporary Cloud Shell environment gcr.io/graphite-cloud-shell-images/terraform:latest with a temporary home directory that will be deleted on session end. This environment is officially maintained by Google.

Would you have expected different behaviour? Our intended use case for the feature is highly temporary, single-use environments that are cleaned up by the end of the session.

**Comment by darnold-harness** [comment]
Ah, right on. If it's documented, then it should be expected. I guess I
just didnt see it. Thanks for your help!
