### ISSUE TITLE
Data resource `google_compute_zones` does not properly inherit `project` from provider in parent module

### ISSUE THREAD

**Issue by sudomann** [terraform-providers/terraform-provider-google#2991]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.11
+ provider.google v1.20.0

### Affected Resource(s)

* google_compute_zones

### Terraform Configuration Files

https://github.com/sudomann/tf-sample-01

### Debug Output

https://gist.github.com/sudomann/b65adbad7fc1f12859130459d2911da6

### Expected Behavior
Terraform successfully plans infrastructure

### Actual Behavior
Fails due to `data.google_compute_zones.available: project: required field is not set`

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Important Factoids

None come to mind

**Comment by chrisst** [comment]
I'm pretty sure your issue is that you have defined the google provider block twice here: https://github.com/sudomann/tf-sample-01/blob/master/gcp/main.tf#L1-L9 and you're picking up the instance that doesn't have project defined on it. 

I suggest that you define it a single time in your config, or add `project = "my-project-name" ` to both definitions.

**Comment by sudomann** [comment]
@chrisst Aw man you are right; I was using multiple provider syntax which I guess is intended for aws.
