### ISSUE TITLE
Add disk labels to google_compute_instance

### ISSUE THREAD

**Issue by safirh** [terraform-providers/terraform-provider-google#2995]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Requesting that google_compute_instance gets supports for disk labels. Support is present in the Compute API already.

### New or Affected Resource(s)

* google_compute_instance

### Potential Terraform Configuration

https://www.terraform.io/docs/providers/google/r/compute_instance.html

```tf
resource "google_compute_instance" "default" {
   name         = "test"
   machine_type = "n1-standard-1"
   zone         = "us-central1-a"
   
   boot_disk {
      initialize_params {
         image = "debian-cloud/debian-9"
         labels = {
            env = "production"
         }
      }
  }
}
```

### References

https://cloud.google.com/compute/docs/reference/rest/v1/instances/attachDisk

**Comment by chrisst** [comment]
similar to https://github.com/terraform-providers/terraform-provider-google/issues/2026

**Comment by marcboudreau** [comment]
I've created a PR (#3766) to address this issue.

**Comment by paddycarver** [comment]
It looks like this issue was addressed in a PR, merged, and released, so I'm going to close the issue out. If there's still work to be done here, feel free to open a new issue. Thanks!
