### ISSUE TITLE
google_compute_instance_group.group.0: diffs didn't match during apply.

### ISSUE THREAD

**Issue by billyfoss** [terraform-providers/terraform-provider-google#3015]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.11
+ provider.google v1.20.0

### Affected Resource(s)

* google_compute_instance_group

### Terraform Configuration Files

Recreation code available at:
https://github.com/billyfoss/terraform-gcp-diff-recreate

### Panic Output

No panic

### Expected Behavior

Expected a new instance to get created and the instance group to be updated to include the new instance.  I also expected the description change to be ignored. 

### Actual Behavior

I received an error message. 

````
Error: Error applying plan:

2 error(s) occurred:

* google_compute_instance_group.group[0]: google_compute_instance_group.group.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.11
    Resource ID: google_compute_instance_group.group.0
    Mismatch reason: attribute mismatch: instances.#
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"instances.3594147435":*terraform.ResourceAttrDiff{Old:"",
New:"FORCE_UPDATE", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "instances.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* google_compute_instance_group.group[1]: google_compute_instance_group.group.1: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.11
    Resource ID: google_compute_instance_group.group.1
    Mismatch reason: attribute mismatch: instances.#
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"instances.3594147435":*terraform.ResourceAttrDiff{Old:"",
New:"FORCE_UPDATE", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "instances.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
````

### Steps to Reproduce

1. Setup a default GCP project (or use an existing)
2. Place the service account json in the same directory
3. Update the terraform.tfvars to reflect the project name and credential file name
4. Create the initial set of resources 
  ````
  terraform init
  terraform plan
  terraform apply
  ````
5. Update the instance.tf to change the 2 places with DEBUG: and run again to update the resources

  ````
  terraform plan
  TF_DEBUG=trace  terraform apply
  ````
6. Review the trace output
7. NOTE: if you run terraform apply again, the process will be successful.

### Important Factoids

None

### References
Possibly:  https://github.com/hashicorp/terraform/issues/18802
* #18802

**Comment by edwardmedia** [comment]
@billyfoss  The version of your provider is pretty old. Could you please upgrade your provider and let me know if this is still an issue? Thank you

**Comment by edwardmedia** [comment]
@billyfoss I don't see your reply. Is there anything more I can assist?

**Comment by edwardmedia** [comment]
@billyfoss it seems your instances are in different zones. If this is what you want to do,  you might want to look into  **google_compute_region_instance_group_manager** instead. **google_compute_instance_group** works for a single zone. I am closing this issue. Please feel free to reopen it if you need further assistance.
