### ISSUE TITLE
extended memory doesn't work in google_compute_instance

### ISSUE THREAD

**Issue by james-oppel-exa** [terraform-providers/terraform-provider-google#3021]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.11

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "saas" {
  name = "${var.role}"
  machine_type = "${lookup(var.machine-type, var.product-type)}"
  zone = "${var.zone}"
  boot_disk {
    initialize_params {
      size = 240
      image = "${var.image}"
      type = "pd-ssd"
    }
  }
  network_interface {
    subnetwork = "${var.subnet}"
    network_ip = "${google_compute_address.saas-int-ip.address}"
    access_config {
      nat_ip = "${google_compute_address.saas-ext-ip.address}"
    }
  }
  can_ip_forward = true
  tags = [
    "${replace("${var.role}", "/(-master|-\\d{1,})|/", "")}"
  ]
  lifecycle {
    ignore_changes = ["attached_disk"]
  }
}

variable "zone" {}
variable "network" {}
variable "subnet" {}
variable "image" {}
variable "region" {}
variable "cidr-prefix" {}
variable "managed-zone-name" {}
variable "managed-zone-dns-name" {}
variable "role" {} # One of `dl-master`, `dl-worker`, `aa-master`, `aa-worker`.
variable "final-octet" {} # Final octet of the SaaS component being provisioned. i.e. 10.0.1.(*)

variable "product-type" {}
variable "machine-type" {
  type = "map"
  default = {
    # GCP requires memory to be a multiple of 256MiB (1024MiB/1GiB).
    "ex2000" = "custom-16-131072"
    "ex3000" = "custom-16-131072" 
    "ex4000" = "custom-40-262144" 
    "dl-master" = "custom-24-159744"
    "aa-worker" = "custom-16-131072"
  }
}
```

### Expected Behavior
I am trying to provision an instance of 16vCPUs and 128GB/mem. In the [docs](https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type), it is specified that you need to define the machine type with a `--custom-extensions` flag. In the [terraform docs](https://www.terraform.io/docs/providers/google/r/compute_instance.html), it says to achieve this, just specify a machine of type `custom-<cpu>-<mem>.

### Actual Behavior
When specifying an extended memory type of custom machine, TF returns a 400:

```
* module.dl-worker-0.google_compute_instance.saas: 1 error(s) occurred:

* google_compute_instance.saas: Error loading machine type: googleapi: Error 400: Invalid resource usage: 'Memory size for a 16 vCPU instance must be between 14848MiB and 106496MiB, while 131072MiB was provided.'., invalidResourceUsage
* module.ir.google_compute_instance.saas: 1 error(s) occurred:

* google_compute_instance.saas: Error loading machine type: googleapi: Error 400: Invalid resource usage: 'Memory size for a 16 vCPU instance must be between 14848MiB and 106496MiB, while 131072MiB was provided.'., invalidResourceUsage
```

### Steps to Reproduce
0. Create a google_compute_instance resource of type "custom-16-131072"
1. `terraform apply`

* #0000

**Comment by emilymye** [comment]
From the docs:

> Memory must be between 0.9 GB per vCPU, up to 6.5 GB per vCPU.

So I don't think 16 vCPUs can't have more than 105 GB :(

**Comment by Chupaka** [comment]
@emilymye, the same doc says: "With extended memory, you can add additional memory to a machine type with no limitations per vCPU."

**Comment by james-oppel-exa** [comment]
@emilymye Thanks for the reply. As @Chupaka has clarified, it does indeed state in the GCP docs that you _can_ achieve this:

```
Adding extended memory to a machine type
By default, a custom machine can have up to 6.5 GB of memory per vCPU. However, this might not be enough memory for your workload. At an additional cost, you can get more memory per vCPU beyond the 6.5 GB limit. This is referred to as extended memory.

With extended memory, you can add additional memory to a machine type with no limitations per vCPU.
```
You can also, according to the docs, achieve this programmatically via Gcloud: 

`gcloud compute instances create example-instance --custom-cpu 2 --custom-memory 15 --custom-extensions`
 
And indeed, in the TF docs, it says that you can achieve this by simply specifying a _custom-vcpus-mem_ machine_type:
```
To create a machine with a custom type (such as extended memory), format the value like custom-VCPUS-MEM_IN_MB like custom-6-20480 for 6 vCPU and 20GB of RAM.
```

So, I would expect the provider to handle the logic and implement this according to the code I submitted in the original report. I have provisioned this machine type manually many times before, it isn't a limitation with GCP.

Thanks!

**Comment by emilymye** [comment]
Oh, I see! When I [originally encountered this issue](https://github.com/terraform-providers/terraform-provider-google/issues/1473)), I wasn't aware of extended memory, so I didn't document it in the Terraform docs. It looks like the format for extended memory has to be `custom-[NUMBER_OF_CPUS]-[AMOUNT_OF_MEMORY]-ext`, so can you try with the `-ext` suffix?

**Comment by james-oppel-exa** [comment]
Confirmed that this works.

Thanks for your help!

**Comment by Chupaka** [comment]
@james-oppel-exa, sorry for the off-topic... Is the price of "16 vCPU + 128 GB" the same as "18 vCPU + 128 GB"? Looks like "Extended memory" is kind of "We reserve vCPUs for you to meet the limit of 6,5 GB per CPU, but you can't use those vCPUs"... Where am I wrong?

**Comment by james-oppel-exa** [comment]
@Chupaka On the GCP pricing calculator, I see a 18-125-ext (calculator doesn't resolve further than 5GiB memory increments) costing USD $734/month. a 20-125 configuration is USD $1,483/month. I've seen what approximates these pricing forecasts in production, although with variance depending on regions, etc.

I'm not sure how they manage the resources at the hypervisor level, but it seems to make a significant impact on costs.

**Comment by james-oppel-exa** [comment]
My original post, I used the calculator wrong. 

So it would actually need to be 20vCPUs / 128GiB to be able to achieve the memory without have to extend.

According to Google's pricing calculator, `custom-16-128-extended` = `750.95 per 1 month` and `custom-20-128` = `756.91 per 1 month`, so the difference seems to be negligible.  

Thanks for the pointer; I wasn't thinking that Google just reserves the necessary vCPUs and charges you for them anyway. There's no point in foregoing the resources, since there doesn't seem to be a meaningful cost-saving associated with it. 

I'm going to confirm with our organizational GCP partner to see if there's any unexpected conditions which should be taken into account. If there is, I'll get back to you.

**Comment by Chupaka** [comment]
@james-oppel-exa
Did you have a response from Google? Is this correct that there's no meaning in Extended Memory?

**Comment by james-oppel-exa** [comment]
@Chupaka There's no real meaningful difference in pricing. There is a few dollars per month difference, and at a large scale, it can be a meaningful amount, but generally user experience (presumed better performance due to the additional vCPUs) is more important than a few dollars per month per VM. Make me wonder why Google offers this in the first place...
