### ISSUE TITLE
depends_on not working for Metadata

### ISSUE THREAD

**Issue by dgarstang** [terraform-providers/terraform-provider-google#3029]
### Terraform Version

```
Terraform v0.11.11
+ provider.google v1.20.0
```

### Affected Resource(s)

google_compute_instance
google_compute_project_metadata

### Terraform Configuration Files

```
resource "google_compute_project_metadata" "project_metadata" {
  project = "${element(var.projects, count.index)}"
  metadata {
    "ssh-keys" = "gadmin:${file("files/id_gcp_infra.pub")}"
    "serial-port-enable" = 1
  }
}

resource "google_compute_instance" "bastion_hosts" {
  count        = "${length(var.bastion_subnets)}"
  name         = "${lookup(var.bastion_subnets[count.index], "name")}"
  machine_type = "${var.bastion_machine_type}"
  zone         = "${lookup(var.bastion_subnets[count.index], "zone")}"
  project      = "${lookup(var.bastion_subnets[count.index], "project")}"
  tags         = ["bastion"]
  boot_disk {
    initialize_params {
      image = "ubuntu-1804-bionic-v20190204"
      size  = "16"
    }
  }
  network_interface {
    subnetwork         = "${lookup(var.bastion_subnets[count.index], "subnet")}"
    subnetwork_project = "${lookup(var.bastion_subnets[count.index], "project")}"
    access_config {
    }
  }
  connection {
    user    = "gadmin"
    agent   = true
    timeout = "2m"
  }
  provisioner "remote-exec" {
    connection {
      type     = "ssh"
      user     = "gadmin"
    }
    inline = [
      "echo Hello > /tmp/foo"
    ]
  }
  depends_on = [
    "google_compute_network.infra_compute_network",
    "google_compute_subnetwork.infra_public_subnetwork",
    "google_compute_project_metadata.project_metadata"
  ]
}
```

### Debug Output

```
* google_compute_instance.bastion_hosts[5]: timeout - last error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* google_compute_instance.bastion_hosts[3]: timeout - last error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* google_compute_instance.bastion_hosts[4]: timeout - last error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
* google_compute_instance.bastion_hosts[2]: timeout - last error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

### Expected Behavior

The metadata containing the ssh public key should have been populated before the bastion hosts were created. Verified that the ssh keys are not in the metadata with the GCP console. The depends_on clearly depends on google_compute_project_metadata.project_metadata. 

### Actual Behavior

Metadata with ssh public keys not populated before bastion hosts were started, and attempt at sshing in to run provisioner failed.

### Steps to Reproduce

1. `terraform apply`

**Comment by joestump** [comment]
I'd look into using [`cloud-init`](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#configure-instances-ssh-keys) with [`template_cloudinit_config`](https://www.terraform.io/docs/providers/template/d/cloudinit_config.html) and passing it in as `user-data` in the `metadata` parameter.

**Comment by dgarstang** [comment]
I'd rather not do that. This would mean passing the metadata on a per VM basis which is harder to maintain than at the project level. It also means that something which would be managed at the project level has to be combined with whatever VM specific things need to be done, also making it less manageable.

**Comment by edwardmedia** [comment]
@dgarstang Is this still an issue with you? The version of your provider is pretty old. Can you try with the latest version? To verify your issue, I was using below code to build two resources. It seemed the metadata was available and one piece of data was successfully written to the file `data.txt` on the VM. Can you let us if this is still an issue?
```
resource "google_compute_project_metadata" "default" {
  metadata = {
    foo  = "bar"
    fizz = "buzz"
    "13" = "42"
  }
}
resource "google_compute_instance" "default" {
  name         = "test"
  machine_type = "n1-standard-1"
  zone         = "us-central1-a"
  tags = ["foo", "bar"]
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
  // Local SSD disk
  scratch_disk {
    interface = "SCSI"
  }
  network_interface {
    network = "default"
    access_config {
      // Ephemeral IP
    }
  }
  metadata = {
    foo = "bar"
  }
  metadata_startup_script = "curl http://metadata.google.internal/computeMetadata/v1/project/attributes/fizz -H 'Metadata-Flavor: Google' > /tmp/data.txt"
  service_account {
    scopes = ["userinfo-email", "compute-ro", "storage-ro"]
  }
}
```

**Comment by edwardmedia** [comment]
@dgarstang I don't see your reply. Is there anything more I can assist?

**Comment by edwardmedia** [comment]
@dgarstang because I can't repro, I am closing the issue. Please feel free to reopen it if this is still an issue with you. Thanks
