### ISSUE TITLE
google_kms_crypto_key does not support asymmetric (like ECDSA) keys

### ISSUE THREAD

**Issue by fproulx-eoscanada** [terraform-providers/terraform-provider-google#3039]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.11
+ provider.google v2.0.0
```

### Affected Resource(s)

* `google_kms_crypto_key`

### Terraform Configuration Files

```tf
resource "google_kms_crypto_key" "some-key" {
  name            = "default"
  key_ring        = "${google_kms_key_ring.some-keyring.self_link}"
  version_template {
		algorithm =        "EC_SIGN_P256_SHA256"
		protection_level = "SOFTWARE"
	}

  lifecycle {
    prevent_destroy = true
  }
}
```

### Debug Output

```
* google_kms_crypto_key.some-key: Error creating CryptoKey: googleapi: Error 400: The algorithm EC_SIGN_P256_SHA256 is not valid for CryptoKeys with purpose ENCRYPT_DECRYPT., badRequest
```

### Expected Behavior

Asymetric keys should be supported

### Actual Behavior

Only symmetric keys are supported 

The value is hardcoded
https://github.com/terraform-providers/terraform-provider-google-beta/blob/d88182e26117a556a43a53c4c59aa06bc57d30bc/google-beta/resource_kms_crypto_key.go#L110

### Steps to Reproduce

1. `terraform apply`

**Comment by filippo91** [comment]
Hi, I'm interested in working on this issue.
