### ISSUE TITLE
Cloud Spanner instance with short name cannot create/update

### ISSUE THREAD

**Issue by tjun** [terraform-providers/terraform-provider-google#3041]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.11
+ provider.google v2.0.0
```
### Affected Resource(s)

* google_spanner_instance

### Terraform Configuration Files

```tf
resource "google_spanner_instance" "foo1" {
  project      = "${module.merpay-shared-spanner-jp.gcp_project_id}"
  config       = "regional-asia-northeast1"
  display_name = "foo1"
  name         = "foo1"
  num_nodes    = 3
}
```

### Expected Behavior

It worked on previous terraform-google-provider version: `1.20.0`

### Actual Behavior

Got error:
```
Error: google_spanner_instance.foo1: "name" ("foo1") doesn't match regexp "^(?:[a-z](?:[-_a-z0-9]{4,28}[a-z0-9])?)$"
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Create a spanner instance with short or log name will get the same errror.

### References

Spanner document: https://cloud.google.com/spanner/quotas

It says 
> Instance ID length limit: 2 to 64 characters

The regexp is not correct:
https://github.com/terraform-providers/terraform-provider-google/blob/738bdb9aacbc29c3ccd0ed05824b64203581ebdb/google/resource_spanner_instance.go#L64

* #0000

**Comment by emilymye** [comment]
There seems to be conflicting documentation - the [REST docs](https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances/create) say 2-30 and the name when creating through the UI is actually enforced to be 30 characters or less, but I just verified that you can still create one via API with id  > 30 characters. Fun! We'll talk to the team to get the docs and/or validation fixed, and fix our regexp.
