### ISSUE TITLE
Support lists in advertised_ip_ranges block of google_compute_router

### ISSUE THREAD

**Issue by allandrick** [terraform-providers/terraform-provider-google#3053]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In https://github.com/terraform-providers/terraform-provider-google/pull/1723 support for advertised_ip_ranges in google_compute_router was added.  The format for each range is a block including a single range and a description.

The documentation describes this element as a list, but in reality, it isn't a list, rather, multiple occurrences of a block.

We often create Terraform modules to simplify the consumption of such resources and solutions (e.g.: VPN with BGP and N advertised ranges), however, currently there is no way to pass in a list and conditionally add multiple advertised_ip_ranges blocks.

Would it be possible to make advertised_ip_ranges contain optional lists instead string vars so that we can create multiple advertised_ip_ranges on a single advertised_ip_ranges block within the resource?

### New or Affected Resource(s)

* google_compute_router

### Potential Terraform Configuration

```tf
resource "google_compute_router" "cloud-router" {
  name    = "${var.name}"
  project = "${var.gcp_project}"
  region  = "${var.gcp_region}"
  network = "${var.network}"

  bgp {
    asn = "${var.asn}"
    advertise_mode = "${var.advertise_mode}"
    advertised_groups = ["${var.advertised_groups}"]
    advertised_ip_ranges {
      ranges = [
        "${split(",", var.advertised_ip_ranges)}"
      ]
      descriptions = [
        "${split(",", var.advertised_ip_range_descriptions)}"
      ]
    }
  }
}
```

### References

* https://github.com/terraform-providers/terraform-provider-google/pull/1723

**Comment by paddycarver** [comment]
I think we could do this, but with 0.12 imminent and the [Dynamic Nested Blocks](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each#dynamic-nested-blocks) it enables, I think I'd prefer to wait for that feature.

**Comment by danawillow** [comment]
Closing in favor of a 0.12-native solution.
