### ISSUE TITLE
Add support for scheduled snapshots for persistent disk

### ISSUE THREAD

**Issue by Chupaka** [terraform-providers/terraform-provider-google#3062]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Scheduled snapshots feature is promoted to beta now, so it worth adding to google-beta provider :)
https://cloud.google.com/compute/docs/disks/scheduled-snapshots

**Comment by emilymye** [comment]
For reference, this would entail adding resource policies as a resource: https://cloud.google.com/compute/docs/reference/rest/beta/resourcePolicies/

**Comment by Lirt** [comment]
Hey,

I've encountered some permission problems with the scheduled snapshot resource policy. I am not sure if this is a bug in TF, but here it is:

1. Created resource policy:
```yaml
resource "google_compute_resource_policy" "XYZ-snapshot-schedule" {
  name        = "XYZ-snapshot-schedule"
  provider    = "google-beta"
  project     = "project1"
  region      = "us-central1"

  snapshot_schedule_policy {
    schedule {
      daily_schedule {
        days_in_cycle = 1
        start_time    = "02:00"
      }
    }
    retention_policy {
      max_retention_days    = 7
      on_source_disk_delete = "APPLY_RETENTION_POLICY"
    }
    snapshot_properties {
      labels = {
        app      = "XYZ"
      }
    }
  }
}
```

2. Attached it manually to disk.
3. Apply worked fine, but now when I hit plan again I have this error: 

```bash
Error: Error reading ComputeResourcePolicy "XYZ-snapshot-schedule": googleapi: Error 403: Required 'compute.resourcePolicies.get' permission for 'projects/<PROJECT_NAME>/regions/us-central1/resourcePolicies/<XYZ>-snapshot-schedule', forbidden.
```

4. Terraform user has these rights - Compute Viewer, Project Viewer, Role Viewer, Service Account User, Storage Admin

Compute Viewer should be enough for permission `compute.resourcePolicies.get` (https://cloud.google.com/iam/docs/understanding-roles).

**Comment by tysen** [comment]
Hi @Lirt, I attempted to repro this using admin credentials and `terraform plan` did not fail in the way you observed. Is it possible for you to try with more permissions?

**Comment by Lirt** [comment]
I solved it, issue was I didn't have specified `google-beta` provider explicitly. Anyway, thank you for reproducing @tysen.
