### ISSUE TITLE
google_container_cluster does not import remove_default_node_pool correctly

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#3064]
after importing a:

```
resource "google_container_cluster" "cluster" {
  ...
  remove_default_node_pool = true
}
```

I get this in plan:
```
  ~ google_container_cluster.cluster
      remove_default_node_pool: "" => "true"
```

which fails because the default-pool has already been removed

**Comment by matti** [comment]
added
```

  lifecycle {
    ignore_changes = "remove_default_node_pool"
  }
```

**Comment by emilymye** [comment]
Interesting - I'm not sure what the best thing to do is here for setting this value on import. Should we attempt to set it based on the presence of `nodePools/default-pool`? Thoughts @rileykarson?

**Comment by rileykarson** [comment]
That seems sensible to me, we could set it to false if `GET` succeeds and false otherwise; that way, the existing update logic we have that removes the default node pool when you go from false -> true will remove it on the next apply.
