### ISSUE TITLE
Fine-grained audit config for projects isn't documented

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#3066]
See https://github.com/GoogleCloudPlatform/magic-modules/pull/1094

**Comment by yhuang** [comment]
@rileykarson @ndmckinley : Thank you for getting this feature to work on the project level.  Are there plans to extend the support to organization level?

**Comment by rileykarson** [comment]
Assuming the API supports it, it's just a matter of plumbing it through! If you don't mind filing issues for each level we're missing & you're interested in.

**Comment by yhuang** [comment]
Users would definitely be interested in getting this capability at the org-level, so we would not need to keep setting it for each project:

https://github.com/terraform-providers/terraform-provider-google/issues/3202

Thank you.
