### ISSUE TITLE
Documentation: variable rolling_update_policy is missing

### ISSUE THREAD

**Issue by dingxiangfei2009** [terraform-providers/terraform-provider-google#3072]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* `google_compute_instance_group_manager`

### Expected Behavior

According to https://github.com/GoogleCloudPlatform/terraform-google-managed-instance-group/blob/fd61badc86ad3080b84b91949bed21b50ce698a5/main.tf#L85, there is a variable called `rolling_update_policy` in resource type `google_compute_instance_group_manager`.

### Actual Behavior

However, as of 18 Feb 2019, https://www.terraform.io/docs/providers/google/r/compute_instance_group_manager.html does not specify the variable.

### Steps to Reproduce

1. Compare https://www.terraform.io/docs/providers/google/r/compute_instance_group_manager.html and 
https://github.com/GoogleCloudPlatform/terraform-google-managed-instance-group/blob/fd61badc86ad3080b84b91949bed21b50ce698a5/main.tf

**Comment by rileykarson** [comment]
That module is built for an older version of the provider and hasn't been updated yet; we recently released `2.0.0` where that field was renamed. See this section of the upgrade guide for context: https://www.terraform.io/docs/providers/google/version_2_upgrade.html#resource-google_compute_instance_group_manager

We're unable to display multiple versions of docs on the website; see [the checked in documentation @ `1.20.0`](https://github.com/terraform-providers/terraform-provider-google/blob/104bbbe70e6d4c9a713afb9c1adc512f85f5857d/website/docs/r/compute_instance_group_manager.html.markdown) and the field is present with it's original name.
