### ISSUE TITLE
Add Support Optional Components Configuration in Dataproc Beta Provider

### ISSUE THREAD

**Issue by d20tech** [terraform-providers/terraform-provider-google#3075]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The beta release of Google Cloud Dataproc allows users to specify optional components that will be installed on a cluster at startup time. This property is specified on the SoftwareConfig element of the clusters.create command as described here: https://cloud.google.com/dataproc/docs/reference/rest/v1beta2/ClusterConfig#Component

Terraform does not expose this property in its `software_config` element, thus clusters can not be created using this feature.

### New or Affected Resource(s)

* google_dataproc_cluster

### Potential Terraform Configuration

```tf
resource "google_dataproc_cluster" "mycluster" {
    # ... 
    software_config {
        optional_components = [ "ANACONDA", "JUPYTER" ]
    }
}
```

### References

* https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/optional-components

**Comment by megan07** [comment]
Thanks @d20tech for opening this issue. It's been closed with #4073 and will be released shortly.
