### ISSUE TITLE
google_compute_instance_from_template ignores values defined in template

### ISSUE THREAD

**Issue by conorgil** [terraform-providers/terraform-provider-google#3076]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.11.11
+ provider.google v2.0.0
```

### Affected Resource(s)

* google_compute_instance_template
* google_compute_instance_from_template

### Terraform Configuration Files

Config with the bug:
```tf
provider "google" {
  version = "~> 2.0"

  credentials = ""
  project     = ""
  region      = "us-west1"
}

resource "google_compute_instance_template" "default" {
  name_prefix  = "instance-template-"
  machine_type = "n1-standard-1"
  region       = "us-west1"

  disk {
    source_image = "ubuntu-1804-lts"
    disk_size_gb = 40
  }

  network_interface {
    network       = "default"
    access_config = {}
  }

  scheduling {
    preemptible       = true
    automatic_restart = false
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "google_compute_instance_from_template" "test" {
  name                     = "instance-from-template"
  zone                     = "us-west1-a"
  source_instance_template = "${google_compute_instance_template.default.self_link}"
}

```

Config without the bug (duplicates the `scheduling` block in the `google_compute_instance_from_template` resource):
```tf
provider "google" {
  version = "~> 2.0"

  credentials = ""
  project     = ""
  region      = "us-west1"
}

resource "google_compute_instance_template" "default" {
  name_prefix  = "instance-template-"
  machine_type = "n1-standard-1"
  region       = "us-west1"

  disk {
    source_image = "ubuntu-1804-lts"
    disk_size_gb = 40
  }

  network_interface {
    network       = "default"
    access_config = {}
  }

  scheduling {
    preemptible       = true
    automatic_restart = false
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "google_compute_instance_from_template" "test" {
  name                     = "instance-from-template"
  zone                     = "us-west1-a"
  source_instance_template = "${google_compute_instance_template.default.self_link}"

  scheduling {
    preemptible       = true
    automatic_restart = false
  }
}

```

### Debug Output

See [gist](https://gist.github.com/conorgil/61161ad0b5e276343338fa1cde6e4640).

Notice that the request to create the template successfully returns on [L55](https://gist.github.com/conorgil/61161ad0b5e276343338fa1cde6e4640#file-terraform-debug-output-L55) and correctly sets `scheduling.preemptible = true` and `scheduling.automatic_restart = false`. Also, the request to retrieve the template on [L155](https://gist.github.com/conorgil/61161ad0b5e276343338fa1cde6e4640#file-terraform-debug-output-L155) returns the correct values in the `scheduling` block.

Then, the request to create the instance (presumably using the template) uses the incorrect values for the `scheduling` block on [L192](https://gist.github.com/conorgil/61161ad0b5e276343338fa1cde6e4640#file-terraform-debug-output-L192). It looks like it completely ignores the values in the template and uses defaults for creating an instance.

### Expected Behavior

The instance created should have used the `scheduling` options defined in the template.

### Actual Behavior

The Request to create the instance did not use the `scheduling` options defined in the template and instead used the default for creating an instance. Specifically, it should have set `scheduling.automatic_restart = false` because that is defined in the template, but it defaulted to use `scheduling.automatic_restart = true`, which conflicts with `scheduling.preemptible = true`.

### Steps to Reproduce

Use the config above that has the bug:
1. `terraform apply`
and you will see the error

Use the config above that uses the work around of duplicating the `scheduling` block in the `google_compute_instance_from_template` resource and see that it runs without error.

**Comment by billyfoss** [comment]
I ran into this as well.  Duplicating the scheduling block in each instance from template worked around the issue, but it was confusing to not have the automatic_restart updated from the template.

**Comment by BastienM** [comment]
Just ran into the same error a few minutes ago.

Took me a bit of time to figure out that the `scheduling` block is indeed overridden in `google_compute_instance_template` no matter what.

**Comment by edwardmedia** [comment]
@conorgil we just have had a fix for a similar issue https://github.com/terraform-providers/terraform-provider-google/issues/6050. Can you help verify if this works for you after the fix is released?

**Comment by conorgil** [comment]
@edwardmedia Great to see this get fixed! Unfortunately, I have not been working with Terraform recently and I do not have time to help test.

**Comment by edwardmedia** [comment]
@conorgil Please feel free to reopen it if you still see this is an issue. Thank you
