### ISSUE TITLE
google_container_cluster istio_config not actually supported

### ISSUE THREAD

**Issue by krishicks** [terraform-providers/terraform-provider-google#3092]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

Hi, I tried using the `istio_config` addon for a `google_container_cluster` and couldn't get it to work. I had originally created the cluster with the google provider at version 0.15.0. Because the istio support is beta, I ended up going down the google-beta provider path, but that didn't seem to work, either. The only references to `istio_config` I found in this repository are in documentation.

### Terraform Version

v0.11.11

### terraform-provider-google Version

google-beta ~~0.20.0~~ 1.20
google ~~0.15.0~~ 1.15

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "main" {
  provider           = "google-beta"

  name               = "<redacted>"
  project            = "<redacted>"
  cluster_ipv4_cidr  = "10.116.0.0/14"
  enable_legacy_abac = true
  network            = "projects/<redacted>/global/networks/default"
  initial_node_count = 3

  addons_config {
    istio_config {
      disabled = false
    }
  }
}
```

### Debug Output

Relevant debug output:

```
2019/02/20 13:35:23 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [addons_config.0: invalid or unknown key: istio_config]
2019/02/20 13:35:23 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [addons_config.0: invalid or unknown key: istio_config]
```

### Expected Behavior

The cluster gets configured with the istio addon.

### Actual Behavior

Terraform returns an error.

### Steps to Reproduce

I did this on an existing cluster that I wanted to add `istio_config` to. In doing so I:
1. Add the google-beta provider
1. Reconfigure the resource with the `google-beta` provider, per [the docs](https://www.terraform.io/docs/providers/google/provider_versions.html#converting-resources-between-versions)
1. `terraform apply`
1. See the above error

### Important Factoids

I did this on an existing cluster that I wanted to add `istio_config` to. The original cluster was made with 0.15.0 of the normal google provider.

**Comment by rileykarson** [comment]
Can you re-confirm your Google provider versions? Neither of those are valid provider versions. I'd expect you mean `1.15.0` for the `google` provider and one of `1.20.0` or `2.0.0` for `google-beta`?

**Comment by krishicks** [comment]
Ah, sorry, I was going on memory there. It's 1.15 for `google` and 1.20 for `google-beta`.

**Comment by rileykarson** [comment]
That feature was added in `2.0.0`, so you'll need to upgrade your version of `google-beta` in that case. See this massive changelog; https://github.com/terraform-providers/terraform-provider-google-beta/blob/master/CHANGELOG.md#200-february-12-2019

Let me know if it doesn't work after upgrading.

**Comment by krishicks** [comment]
Got it. I swear I searched for `istio` on that page but I must have had a typo. Thanks!
