### ISSUE TITLE
Kubeconfig generation for google_container_cluster 

### ISSUE THREAD

**Issue by PavanDevops** [terraform-providers/terraform-provider-google#3097]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I have been observed that Azure resource azurerm_kubernetes_cluster is generating Kubeconfig as kube_config_raw.

Would be great helpful to get the same mechanism with certificate keys for GKE google_container_cluster also.

### New or Affected Resource(s)

* google_XXXXX
google_container_cluster

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by pdecat** [comment]
Hi, that's already possible, have a look at:

- https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/test-infra/gke/kubeconfig-template.yaml
- https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/test-infra/gke/main.tf

**Comment by danawillow** [comment]
Closing this due to https://github.com/terraform-providers/terraform-provider-google/issues/3097#issuecomment-465921011 claiming it can already be done, but please feel free to comment and reopen if I misunderstood.
