### ISSUE TITLE
Removing the master_authorized_networks_config block on private clusters fails.

### ISSUE THREAD

**Issue by moxli** [terraform-providers/terraform-provider-google#3098]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.11
+ provider.google v1.20.0

### Affected Resource(s)

google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "cluster" {

  name = "${var.name}"
  project = "${var.project}"
  zone = "${var.zone}"
  min_master_version = "${var.min_master_version}"
  remove_default_node_pool = true

  node_pool {
      name = "default-pool"
  }

  master_auth {
    username = "admin"
    password = "${var.password}"
  }

  additional_zones   = "${var.additional_zones}"

  maintenance_policy {
    daily_maintenance_window {
      start_time = "${var.maintenance_start_time}"
    }
  }

  master_authorized_networks_config {
    cidr_blocks {
      cidr_block = "x.x.x.x/32"
      display_name = "net1"
    }
    cidr_blocks {
      cidr_block = "x.x.x.x/32"
      display_name = "net2"
    }
    cidr_blocks {
      cidr_block = "x.x.x.x/32"
      display_name = "net3"
    }
    cidr_blocks {
      cidr_block = "x.x.x.x/32"
      display_name = "net4"
    }
  }

  private_cluster_config {
    enable_private_endpoint = false
    enable_private_nodes = true
    master_ipv4_cidr_block = "${var.master_ipv4_cidr_block}"
  }

  ip_allocation_policy {
    create_subnetwork = true
    subnetwork_name = "${var.name}-subnetwork"
  }

  "lifecycle" = {
    "ignore_changes" = ["node_pool"]
  }
}
```

### Debug Output

If you think this is required please let me know. This should be fairly easy to reproduce. 

### Expected Behavior

I have this private Kubernetes cluster setup with private nodes and a public master endpoint.
I have added authorized networks for our office IPs. Unfortunately this prevents users to connect to the cluster with Google Cloud shell.

I have removed the "master_authorized_networks_config" block from the config and ran apply.

Each authorized network should be removed and master_authorized_networks_config should be set to "0".

### Actual Behavior

The following error occurs:

Error: Error applying plan:
```
1 error(s) occurred:

* module.fsl.module.cluster.google_container_cluster.cluster: 1 error(s) occurred:

* google_container_cluster.cluster: googleapi: Error 400: Must specify a field to update., badRequest
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Chupaka** [comment]
DId you check with provider.google v2.0.0?

**Comment by moxli** [comment]
No I have not managed to upgrade to v2 yet.
It seems like the master_authorized_networks_config is enabled by default with the following config.
```tf
  private_cluster_config {
    enable_private_endpoint = false
    enable_private_nodes = true
    master_ipv4_cidr_block = "${var.master_ipv4_cidr_block}"
  }
```

You can go ahead and disable it via the Google Console but I was not able to reflect that in my terraform code.
Right now I just added the following:

```tf
  master_authorized_networks_config {
    cidr_blocks {
      cidr_block = "0.0.0.0/0"
      display_name = "Public"
    }
  }
```

This brings back a publicly accessible endpoint.

**Comment by hugoShaka** [comment]
This issue can be reproduced with `terraform-provider-google_v2.3.0_x4`.

**Comment by mike-marcacci** [comment]
I can reproduce this on `terraform-provider-google_v2.12.0_x4`.

**Comment by oswalya** [comment]
This issue might be solved by a PR I just opened at the magic modules:
https://github.com/GoogleCloudPlatform/magic-modules/pull/2308

Fingers crossed. Further I think this bug is also related / the same as https://github.com/terraform-providers/terraform-provider-google/issues/2198
