### ISSUE TITLE
Slow plans since upgrade to v2.0.0

### ISSUE THREAD

**Issue by Stono** [terraform-providers/terraform-provider-google#3101]
Hi, 
We're seeing slow plans / hangs (around 5 mins) on terraform since upgrading to v2.0.0 of the provider, specifically on this resource:

```
null_resource.wait-for-k8s-master: Refreshing state... (ID: 7869720648393322930)
```

Which is:
```
resource "null_resource" "wait-for-k8s-master" {
  triggers {
    core_pool_id   = "${google_container_node_pool.core-20181128.id}"
  }

  depends_on = [
    "google_container_node_pool.core-20181128"
  ]

  provisioner "local-exec" {
    command = "${path.module}/wait_for_ready.sh ${google_container_cluster.cluster.name} ${var.project} ${google_container_cluster.cluster.zone} ${null_resource.install-helm.triggers.helm_version}"
    when    = "create"
  }
}
```

Any ideas?

**Comment by paddycarver** [comment]
Unfortunately, without [debug logs](https://www.terraform.io/docs/configuration/environment-variables.html), we're not going to be able to help much :/ Even then, there's a lot going on here--null resources, provisioners, a shell script... I'm happy to take a look, but I can't even be sure this is related to 2.0.0 changes :/

**Comment by Stono** [comment]
Yes valid point and apologies for not providing them, they're just very
verbose and contain a lot of info about our infra.

Could you possibly reach out via email or slack and I can provide them?

**Comment by paddycarver** [comment]
Of course, feel free to send them my way. I'm paddy at hashicorp.

**Comment by Stono** [comment]
Really annoyingly I've come in today and it's not doing it.  Yesterday it was doing it with *every* plan, but I didn't save the logs.

I'll close this issue for now but reopen/reach out to you if it returns!

**Comment by paddycarver** [comment]
Glad to hear it's resolved!
