### ISSUE TITLE
Problem in getting ip numbers of instances from instance manager

### ISSUE THREAD

**Issue by eakarsu** [terraform-providers/terraform-provider-google#3104]
We are trying to achive similar thing mentioned here
https://github.com/terraform-providers/terraform-provider-google/issues/1246
 
We are trying to get ip numbers of instances from instance manager. Then update/create and DNS  record wirth those ip numbers  as below. Are reaching to instances but not ip numbers in below.
Can you help up?
 
resource "google_compute_instance_group_manager" "node-manager" {
  name = "${var.env}-manager"
  target_size = "${var.node_instance_count}"
  base_instance_name = "${var.env}"
  instance_template = "${google_compute_instance_template.node-template.self_link}"
  update_strategy = "NONE"
  zone = "${var.zone}"
  wait_for_instances = true

  named_port {
    name = "${var.port_name}"
    port = "${var.port_number}"
  }
}

data "google_compute_instance_group" "all" {
  self_link = "${google_compute_instance_group_manager.node-manager.instance_group}"
}

data "google_compute_instance" "all" {
  count="${length(data.google_compute_instance_group.all.instances)}"
  self_link="${data.google_compute_instance_group.all.instances[count.index]}"
}

data "google_compute_instance" "second" {
  count="${length(data.google_compute_instance_group.all.instances)}"
  self_link="${data.google_compute_instance_group.all.instances[count.index]}"
}

locals {
  instances = "${data.google_compute_instance_group.all.instances}"
  networks = "${data.google_compute_instance.second.network_interface}"
}

resource "google_dns_managed_zone" "dev" {
  name = "dev-example"
  dns_name = "example.com."
  description = "Example Dev DNS Managed Zone"
}

resource "google_dns_record_set" "default" {
  count="${length(local.instances)}"
  name = "zkdev1.${google_dns_managed_zone.dev.dns_name}"
  type = "A"
  ttl = "604800"

  managed_zone = "${google_dns_managed_zone.dev.name}"

  rrdatas = [
    "${element(local.networks.network_ip, count.index)}"]
    }
 

---

Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by paddycarver** [comment]
As [mentioned](https://github.com/terraform-providers/terraform-provider-google/issues/1246#issuecomment-417419732) in #1246 this is almost certainly not something you want to do. Mixing control planes like this will not end well.

I'm not sure what you mean by "Are reaching to instances but not ip numbers in below." Can you post output or [debug logs](https://www.terraform.io/docs/configuration/environment-variables.html)?

**Comment by eakarsu** [comment]
Thanks for reply

(base) eakarsu-57ce22:zk eakarsu$ terraform apply
google_compute_firewall.node-server: Refreshing state... (ID: zk-server-fw)
data.template_file.node_instance_templatefile: Refreshing state...
google_compute_instance_template.node-template: Refreshing state... (ID: search-zk-dev-template)
google_compute_instance_group_manager.node-manager: Refreshing state... (ID: search-sandbox-214814/us-east1-b/search-zk-dev-manager)
data.google_compute_instance_group.all: Refreshing state...
data.google_compute_instance.all[2]: Refreshing state...
data.google_compute_instance.all[0]: Refreshing state...
data.google_compute_instance.all[1]: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + module.instance-template-wodns.google_dns_managed_zone.dev
      id:             <computed>
      description:    "Example Dev DNS Managed Zone"
      dns_name:       "aneeshabraham.com."
      name:           "dev-example"
      name_servers.#: <computed>
      project:        <computed>

  + module.instance-template-wodns.google_dns_record_set.default[0]
      id:             <computed>
      managed_zone:   "dev-example"
      name:           "zkdev1.aneeshabraham.com."
      project:        <computed>
      rrdatas.#:      "1"
      rrdatas.0:      "https://www.googleapis.com/compute/v1/projects/search-sandbox-214814/zones/us-east1-b/instances/search-zk-dev-z14g"
      ttl:            "604800"
      type:           "A"

  + module.instance-template-wodns.google_dns_record_set.default[1]
      id:             <computed>
      managed_zone:   "dev-example"
      name:           "zkdev1.aneeshabraham.com."
      project:        <computed>
      rrdatas.#:      "1"
      rrdatas.0:      "https://www.googleapis.com/compute/v1/projects/search-sandbox-214814/zones/us-east1-b/instances/search-zk-dev-p7cm"
      ttl:            "604800"
      type:           "A"

  + module.instance-template-wodns.google_dns_record_set.default[2]
      id:             <computed>
      managed_zone:   "dev-example"
      name:           "zkdev1.aneeshabraham.com."
      project:        <computed>
      rrdatas.#:      "1"
      rrdatas.0:      "https://www.googleapis.com/compute/v1/projects/search-sandbox-214814/zones/us-east1-b/instances/search-zk-dev-78xm"
      ttl:            "604800"
      type:           "A"


Plan: 4 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:


resource "google_compute_instance_group_manager" "node-manager" {
  name = "${var.env}-manager"
  target_size = "${var.node_instance_count}"
  base_instance_name = "${var.env}"
  instance_template = "${google_compute_instance_template.node-template.self_link}"
  update_strategy = "NONE"
  zone = "${var.zone}"
  wait_for_instances = true

  named_port {
    name = "${var.port_name}"
    port = "${var.port_number}"
  }
}


data "google_compute_instance_group" "all" {
  self_link = "${google_compute_instance_group_manager.node-manager.instance_group}"
}



data "google_compute_instance" "all" {
  count="${length(data.google_compute_instance_group.all.instances)}"
  self_link="${data.google_compute_instance_group.all.instances[count.index]}"
}


/*
data "google_compute_instance" "second" {
  count="${length(data.google_compute_instance_group.all.instances)}"
  self_link="${data.google_compute_instance.all.network_interface}"
}
*/

locals {
  instances = "${data.google_compute_instance_group.all.instances}"
  //networks = "${data.google_compute_instance.second.name}"
}




resource "google_dns_managed_zone" "dev" {
  name = "dev-example"
  dns_name = "example.com."
  description = "Example Dev DNS Managed Zone"
}

resource "google_dns_record_set" "default" {
  count="${length(local.instances)}"
  name = "zkdev1.${google_dns_managed_zone.dev.dns_name}"
  type = "A"
  ttl = "604800"

  managed_zone = "${google_dns_managed_zone.dev.name}"

  rrdatas = [
    //"${element(local.networks, count.index)}"]
    "${element(local.instances, count.index)}"]
  //network_ip
}

**Comment by eakarsu** [comment]
My target goal is to get ip numbers of instances  instance manager have created.
data.google_compute_instance.all is getting map to a actual instances. But I need to get ip numbers (network_interface.0.network_ip) from each instance. I don't know to get it. You may help me on this.
I appreciate your help

data "google_compute_instance_group" "all" {
self_link = "${google_compute_instance_group_manager.node-manager.instance_group}"
}

data "google_compute_instance" "all" {
count="${length(data.google_compute_instance_group.all.instances)}"
self_link="${data.google_compute_instance_group.all.instances[count.index]}"
}


data "google_compute_instance" "second" {
count="${length(data.google_compute_instance_group.all.instances)}"
self_link="${data.google_compute_instance.all.network_interface}"
}

**Comment by sjmiller609** [comment]
```
data "google_compute_instance" "sample_instance" {
  self_link = tolist(data.google_compute_instance_group.sample_instance_group.instances)[0]
}
```
For the data source on the instance, I needed to use type conversion in order for the index to work.

**Comment by rileykarson** [comment]
Closing as a non-provider issue. We don't really encourage accessing specific managed instances by IP because they can be recreated by GCP at will, but configuration is the problem here and not really anything in the provider.

**Comment by robins35** [comment]
I need this as well. I am spinning up multiple instances with a group manager and a template, I am using a null_resource to run an ansible playbook on each of them. How am I supposed to know the IPs of the instances that are spun up when 1) I can't explicitly define them, google defines them, and 2) terraform won't even let me know what the IPs are?

It doesn't matter if google changes the IPs in the future, when I am building the instances, I need to be able to run a playbook on them. Since there isn't an explicit "google_compute_instance" being defined, I have no other way to grab the IP addresses. Unless I'm supposed to somehow shell out of terraform and use a gcloud command.
