### ISSUE TITLE
Build dependencies between google_project_service resources and resources which rely on the API being enabled

### ISSUE THREAD

**Issue by rsalmond** [terraform-providers/terraform-provider-google#3105]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Presently there is no dependency relationship between the `google_project_service` resource and any resource which relies on the service being enabled. For example, the code below produces the dependency graph in the screenshot.

```
resource "google_kms_key_ring" "my_key_ring" {
  name     = "my-key-ring"
  location = "us-central1"
}

resource "google_project_service" "project" {
  service = "cloudkms.googleapis.com"
}
```
![image](https://user-images.githubusercontent.com/4367945/53194033-b43e6080-35cf-11e9-925e-7dd1f496e87b.png)

Due to this, it is possible to execute a `terraform destroy` only to face failures because the API required to delete the KMS keyring has already been disabled.

By inspecting the services named in the `google_project_service` (or `google_project_services`) resources and associating them with other `google_*` resources in the graph it should be possible to infer this relationship and execute operations in the correct order.

### New or Affected Resource(s)

* google_project_service

**Comment by rileykarson** [comment]
Terraform core establishes dependency relationships based on the interpolations used in your config and the `depends_on` attributed and this isn't an issue we can solve in the provider. As such, I'm going to close this out- there's no action we can take.

`depends_on` might work? eg:

```hcl
resource "google_kms_key_ring" "my_key_ring" {
  name     = "my-key-ring"
  location = "us-central1"
  depends_on = ["google_project_service.project"]
}

resource "google_project_service" "project" {
  service = "cloudkms.googleapis.com"
}
```

**Comment by rsalmond** [comment]
>this isn't an issue we can solve in the provider

@rileykarson are you suggesting I should open an issue against Terraform core? This feels like a very Google specific issue.

WRT to `depends_on`, it seems to me that if we can ask users to manually infer the relationship we should also be able to dynamically add the `depends_on` field.

**Comment by rileykarson** [comment]
Terraform providers are unable to dynamically build a dependency graph; the _only_ way to build one is with interpolations / manually defining `depends_on`. My apologies for the confusion- that's why you would need to file an issue against Terraform core.

**Comment by rsalmond** [comment]
Ah I understand, thank you!
