### ISSUE TITLE
Specify CIDR block sizes for GKE cluster subnets

### ISSUE THREAD

**Issue by abstrctn** [terraform-providers/terraform-provider-google#3108]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When creating a new GKE container cluster, you can request that a new subnetwork should be created, however the new subnet defaults to a size of `/22`. Google's API allows for specifying larger or smaller ranges, but this is not exposed in Terraform.

While you can already customize the size of a new subnetwork by creating a `google_compute_subnetwork` resource (and then reference that new subnetwork in the `google_container_cluster` definition), there the subnetwork address must be explicitly defined with a precise range, meaning you can no longer rely on GCP to assign you an unused block. This is particularly useful when creating clusters within shared projects.

Additionally, it could be useful to loosen the [conflict configuration](https://github.com/terraform-providers/terraform-provider-google/blob/b2f501754ff141c4d66b78cea5677de8ddbffa9e/google/resource_container_cluster.go#L490) between the `create_subnetwork` and existing `services_ipv4_cidr_block` / `cluster_ipv4_cidr_block` options, since the underlying API lets you specify all three values as long as they are block sizes and not full addresses.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

A `node_ipv4_cidr_block` could be added to the `ip_allocation_policy` block, to keep configuration in sync with the [underlying API call to GCP](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#ipallocationpolicy).

```tf
resource "google_container_cluster" "name" {
  ip_allocation_policy {
    node_ipv4_cidr_block = "/27"
    create_subnetwork = true
  }
```

### References

* #1921

**Comment by ndmckinley** [comment]
Thanks for the report!  I'm looking into this - seems doable!
