### ISSUE TITLE
Add versioned support and Beta features to google_compute_instance

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#311]
We can now support `v0beta` features in addition to `v1`; there are a few outstanding issues for `v0beta` features for `google_compute_instance`. It will need to be converted to a versioned resource, and then support for those fields added. This issue is to track that change & those features.

**Comment by rosbo** [comment]
The gpu support, ip aliasing and minimal cpu platform beta features have been added to `google_compute_instance`.
