### ISSUE TITLE
Adding two or more labels on a project results in an Error: 400

### ISSUE THREAD

**Issue by gosseljl** [terraform-providers/terraform-provider-google#3111]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

 terraform -v
Terraform v0.11.11
+ provider.google v2.0.0
+ provider.random v2.0.0

### Affected Resource(s)

* google_project

### Terraform Configuration Files

```tf

main.tf:

provider "google" {
  region = "us-east1"
  zone   = "us-east1-c"
}

module "project" {
  source = "modules/projects"

  project_name    = "my-project"
  environment     = "test"
  org_id          = "${var.org_id}"
  owner           = "System"
  billing_account = "${var.billing_account}"
  team            = "Admin"
}

modules/project/project.tf:

variable "org_id" {}
variable "billing_account" {}
variable "environment" {}
variable "owner" {}
variable "project_name" {}
variable "team" {}

resource "google_project" "project" {
  name            = "${var.project_name}-${var.environment}"
  project_id      = "${var.project_name}-${var.environment}"
  billing_account = "${var.billing_account}"

  labels {
    env  = "${var.environment}"
    team = "${var.team}"
  }
}
```

### Expected Behavior

The project should have two labels applied.  A single label works fine.

### Actual Behavior

Error: Error applying plan:

1 error(s) occurred:

* module.project.google_project.project: 1 error(s) occurred:

* google_project.project: error creating project my-project-test (my-project-test): googleapi: Error 400: field [labels] has issue [invalid project label], badRequest. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission

### Steps to Reproduce

1. `terraform apply` with the above test boiled down test case.

**Comment by ndmckinley** [comment]
Your problem is that your specific test values are invalid.  In particular, your team name is `Admin`.

>Keys and values can contain only lowercase letters, numeric characters, underscores, and dashes. All characters must use UTF-8 encoding, and international characters are allowed.

No uppercase letters allowed.  :)

You can fix this easily by using [lower](https://www.terraform.io/docs/configuration/interpolation.html#lower-string-).
