### ISSUE TITLE
BigQuery Dataset permission

### ISSUE THREAD

**Issue by ToogiiB** [terraform-providers/terraform-provider-google#3112]
We can grant access to service accounts on dataset manually in UI. But it is not available in Terraform.
https://www.terraform.io/docs/providers/google/r/bigquery_dataset.html
Even though it is not mentioned in [here]( https://cloud.google.com/bigquery/docs/dataset-access-controls#bigquery-update-dataset-access-bqweb), it is already supported by Google BigQuery. 
Please advise if you can add this or it is already available.

**Comment by ndmckinley** [comment]
Does the

```hcl
resource "google_bigquery_dataset" "default"
  ...
  access {
     ...
     user_by_email: "service-account@example.com"
  }
  ...
}
```

work for you?  Comment if that's not what you're looking for, and I'll reopen.

https://www.terraform.io/docs/providers/google/r/bigquery_dataset.html#access
