### ISSUE TITLE
The google_compute_url_map fails with '"path_matcher.0.name": required field is not set or 'path_matcher: should be a list'

### ISSUE THREAD

**Issue by movergan** [terraform-providers/terraform-provider-google#3113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.11
+ provider.google v2.0.0
+ provider.null v2.0.0

### Affected Resource(s)

"google_compute_url_map"

### Terraform Configuration Files

```tf
resource "null_resource" "path_matcher" {
  count = "${length(var.host_rule)}"
  triggers {
    name = "${lookup(var.host_rule[count.index], "path_matcher")}"
    default_service = "${module.gce-lb-https.backend_services[count.index]}"
  }

}

resource "google_compute_url_map" "url-map" {
  // note that this is the name of the load balancer
  name            = "${var.name}"
  default_service = "${module.gce-lb-https.backend_services[0]}"


  host_rule = "${var.host_rule}"

  path_matcher = "${null_resource.path_matcher.*.triggers}"

}
```

state for the Null resource is:
```
                "null_resource.path_matcher.0": {
                    "type": "null_resource",
                    "depends_on": [
                        "module.gce-lb-https"
                    ],
                    "primary": {
                        "id": "8829969477972640304",
                        "attributes": {
                            "id": "8829969477972640304",
                            "triggers.%": "2",
                            "triggers.default_service": "https://www.googleapis.com/compute/v1/projects/project-name/global/backendServices/d001-loadbalancer-backend-0",
                            "triggers.name": "backend-0"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.null"
                },
                "null_resource.path_matcher.1": {
                    "type": "null_resource",
                    "depends_on": [
                        "module.gce-lb-https"
                    ],
                    "primary": {
                        "id": "6616983559536597915",
                        "attributes": {
                            "id": "6616983559536597915",
                            "triggers.%": "2",
                            "triggers.default_service": "https://www.googleapis.com/compute/v1/projects/project-name/global/backendServices/d001-loadbalancer-backend-1",
                            "triggers.name": "backend-1"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.null"
                }
```

### Expected Behavior

path_matcher should not fail when list is given.

### Actual Behavior
With:
```tf
path_matcher = "${null_resource.path_matcher.*.triggers}"
```
The error:
```
Error: module.d001-loadbalancer.google_compute_url_map.url-map: path_matcher: should be a list
```

With known W/A:
```
path_matcher = ["${null_resource.path_matcher.*.triggers}"]
```

The error is:
```
Error: module.d001-loadbalancer.google_compute_url_map.url-map: "path_matcher.0.default_service": required field is not set

Error: module.d001-loadbalancer.google_compute_url_map.url-map: "path_matcher.0.name": required field is not set
```
### Steps to Reproduce

1. With the configuration above run `terraform plan`

### Important Factoids
I am trying to build a TF module based on Google LB module, In order to do that I need to generate path_matcher dynamically. I am trying to use null_resource as a workaround here. 
### References

* #0000

**Comment by ndmckinley** [comment]
This seems to be an issue with your terraform configuration, not with the google provider.

Splats and lists interact in complex ways, to say the least.  It seems like you're trying to get a list of lists of objects out of your null provisioner.  There's no guidance in the terraform docs on how to do that, but here's what I usually do in similar situations: make an output, rather than a `google_compute_url_map` - and modify your splat until the output value looks right to you.  Then paste that into the resource and see if it works.  If it doesn't work, come back and comment on this bug with the output that looks correct to you, and the error message from the resource.

There may genuinely be no way to do this in HCL1 - in that case, I recommend refiling this bug on Terraform core.
