### ISSUE TITLE
cloud_build_trigger "build" argument is not optional

### ISSUE THREAD

**Issue by rsalmond** [terraform-providers/terraform-provider-google#3122]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
 terraform -v
Terraform v0.11.11
+ provider.google v2.0.0
```
### Affected Resource(s)

* cloud_build_trigger

### Terraform Configuration Files

```tf
resource "google_cloudbuild_trigger" "test" {
  description = "Test trigger"

  trigger_template {
    repo_name = "my-repo"
  }
}
```

### Debug Output

https://gist.github.com/rsalmond/83387d407d6712cc597aae1b7f923431

### Expected Behavior

I would expect that the docs would not have suggested that the `build` parameter was optional, or since it can be provided as an empty object then the provider would default to `"build": {}` when none is provided.

### Actual Behavior

```
Error: Error applying plan:

1 error(s) occurred:

* google_cloudbuild_trigger.test: 1 error(s) occurred:

* google_cloudbuild_trigger.test: Error creating Trigger: googleapi: Error 400: Request contains an invalid argument.
```

I have also suggested to google that this is a misleading error message given the nature of the problem.

### Steps to Reproduce

1. `terraform apply`

**Comment by rileykarson** [comment]
Hey @rsalmond!

The `build` attribute is optional for this resource; you can see in [the example in the docs](https://www.terraform.io/docs/providers/google/r/cloud_build_trigger.html#example-usage-cloudbuild-trigger-filename) that none is provided. I suspect that the API requires one of several fields including `build` to be set, and returns an error if none are.

There isn't much to be done in the provider about this- but if you can find a comprehensive guide to configuration from the API I'll gladly update the docs on our side.

**Comment by rsalmond** [comment]
@rileykarson I thought the exact same thing myself, which is why I opened a support case and had them confirm that the build object is required. 

You can confirm it [here](https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.triggers/create) by replicating the payload present in the debug output. 

Incidentally, `branchName` appears to also be required when a `triggerTemplate` is provided, but I have not confirmed it with google. There is a [detailed API guide](https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.triggers#BuildTrigger) but it rather unhelpfully does not appear to suggest which fields are required and which are optional.

**Comment by SavageDoxed** [comment]
Thanks for closing the ticket :)

**Comment by rileykarson** [comment]
Ah, looking over the REST docs you linked, one of `build` or `filename` is required; I'll update our documentation to reflect that.

**Comment by rsalmond** [comment]
👍  thanks!

**Comment by rsalmond** [comment]
Ah yeah I was bumping into the combination of missing params. 

```
resource "google_cloudbuild_trigger" "test" {
  description = "Test trigger"

  trigger_template {
    repo_name = "my-repo"
  }

  filename = "somefile.yaml"
}
```

This _also_ fails but not because a build is not present, it's because the branch name is not present in the trigger template. Might want to mark that one as required as well.
