### ISSUE TITLE
Export "default" internal/external IP addresses for compute instances

### ISSUE THREAD

**Issue by apparentlymart** [terraform-providers/terraform-provider-google#3126]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Terraform 0.12 no longer has the feature of allowing providers to pre-populate certain arguments of the `connection` block, instead requiring the user to explicitly set all of the arguments, using `self.foo` references where appropriate. This change is in line with our "explicit is better than implicit" philosophy; there's more detail on the rationale behind this [in the draft upgrade guide](https://github.com/hashicorp/terraform/blob/da4862e3f79701c80a3feb01c3f7d57facb37c19/website/upgrade-guides/0-12.html.markdown#default-settings-in-connection-blocks).

The IP address selection behavior for the Google Cloud compute resource types was pretty complicated, so as currently implemented the upgrade tool will generate the following approximation of that logic as a Terraform expression:

```hcl
  host = coalesce(
    concat(
      # Prefer any available NAT IP address
      flatten([
        for ni in self.network_interface : [
          for ac in ni.access_config : ac.nat_ip
        ]
      ]),
      # Otherwise, use the first available LAN IP address
      [
        for ni in self.network_interface : ni.network_ip
      ],
    )...
  )
```

This current implementation should work, and we could ship with it if needed, but I wanted to suggest an alternative path that might be more intuitive to users if it would be possible to implement before the first provider release that supports Terraform v0.12.0.

I think the main distinction users often care about when setting `host` is whether to use a publicly-accessible IP address or a privately-accessible IP address. The right answer here depends on how their surrounding environment is set up, and so Terraform and providers generally cannot guess which is the best choice without more global knowledge, and so we invite users to select a suitable address themselves when assigning to the `host` argument.

As far as I can tell, the selection of a default IP address is currently used only in [the call to `SetConnInfo`](https://github.com/terraform-providers/terraform-provider-google/blob/1319ddd86de649e62984da8a31ca5643c4ef1787/google/resource_compute_instance.go#L782-L794), and always prefers the external IP address if one is available. The candidates for this selection don't seem to be exported as attributes, so if a user wants to override to prefer the private one, they'd need to write out a more complex expression to do so.

I'd like to propose exporting two new attributes with names like `default_network_ip` and `default_nat_ip` that would be assigned the values of `internalIP` and `externalIP` respectively, and then we can simplify the generated `host` expression to this:

```hcl
  host = coalesce(self.default_nat_ip, self.default_network_ip)
```

...which should hopefully be clearer to users and easier to simplify to the specific IP address type they want if they know they _never_ want to use `default_nat_ip` for some reason.

Since the upgrade tool must work with the first version of the provider that supports v0.12.0, getting this benefit in the upgrade tool unfortunately requires some tight coordination to get this in before that release and then update the upgrade tool before core v0.12.0 final. I don't think it would be the end of the world if we didn't make this and shipped with the more-complex expression above, but I think it'd be nice if it were possible to coordinate these changes so we can smooth out the UX for upgraders a little more.

### New or Affected Resource(s)

* google_compute_instance

**Comment by rileykarson** [comment]
I don't imagine we'll cut a feature release between now & our first 0.12 release given that we just released `2.1.0`. Unfortunately, I think we're stuck with the bulky expression.

Regardless, thanks for the heads up!
