### ISSUE TITLE
Failed updates to google_monitoring_uptime_check_config 

### ISSUE THREAD

**Issue by alexburlton** [terraform-providers/terraform-provider-google#3132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.11
+ provider.google v2.0.0
+ provider.google-beta v2.0.0

### Affected Resource(s)

* google_monitoring_uptime_check_config.http

### Terraform Configuration Files

Create an initial uptime check like the following:

```tf
resource "google_monitoring_uptime_check_config" "my_check" {
  display_name = "A Check"
  timeout = "10s"
  period = "60"

  http_check {
    port = 443
    use_ssl = true
  }

  monitored_resource {
    type = "uptime_url"
    labels = {
      host = "HOST_ONE"
      project_id = "id"
    }
  }
}
```

Apply it, amend the host within the monitored resource and try to apply it again.

### Debug Output

* google_monitoring_uptime_check_config.my_check: 1 error(s) occurred:

* google_monitoring_uptime_check_config.my_check: Error updating UptimeCheckConfig "projects/blah": googleapi: Error 400: Cannot update the resource of a config

### Expected Behavior

Resources should have been destroyed and re-created

### Actual Behavior

TF tries to perform in-place update while API refuses to do so

### Steps to Reproduce

Create a http check google_monitoring_uptime_check_config.http and then try to modify 'host' field within the monitored_resource

### References

Pretty much identical problem to #2703, but for the host rather than the period.

**Comment by ndmckinley** [comment]
@chrisst - looks like some changes to stackdriver concurrency stuff!  Here and #3133.
