### ISSUE TITLE
google_storage_bucket encryption -block should allow empty default_kms_key_name

### ISSUE THREAD

**Issue by autero1** [terraform-providers/terraform-provider-google#3134]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description 
When creating a `google_storage_bucket` and passing empty string in`encryption` `default_kms_key_name`, `terraform` crashes.

```
* google_storage_bucket.website: unexpected EOF
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
To allow writing more re-usable code, empty string should be treated as `no value` and default Google Provided Encryption used. See `terraform` configuration below as example.

### New or Affected Resource(s)

* google_storage_bucket

### Potential Terraform Configuration

```tf
resource "google_storage_bucket" "website" {
  ...
  encryption {
    default_kms_key_name = "${var.website_kms_key_name}"
  }
  ...
}
```

### References

* #0000

**Comment by ndmckinley** [comment]
Yeah, that sounds right to me.  Let's see what I can do about that!
