### ISSUE TITLE
Improve documentation around monitoring_notification_channel

### ISSUE THREAD

**Issue by alexburlton** [terraform-providers/terraform-provider-google#3150]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The [documentation for gcloud notifcation channels](https://www.terraform.io/docs/providers/google/r/monitoring_notification_channel.htmll) would really benefit from providing more examples, or at least more guidance on how to find things out yourself.

I've tried to set up a slack notification channel, and the first snag I came up against was knowing what fields to populate in my tf setup. I ended up finding this manually by running the gcloud command:

`gcloud alpha monitoring channel-descriptors describe projects/<My Project>/notificationChannelDescriptors/slack`

That's got me as far as:

```tf
resource "google_monitoring_notification_channel" "basic" {
  display_name = "My slack notifications"
  type = "slack"
  labels = {
    auth_token = "????????"
    channel_name = "#notification-channel"
  }
}
```

However, I'm still currently mystified as to how I'm meant to populate the auth_token field. When you manually set up one of these channels, you go through an OAuth flow in order to allow gcloud to have read/write access to your slack channel. Obviously an auth_token gets generated as part of this, but I can't see where it's exposed in either slack or google cloud. If it's part of the terraform API, there must be an intended way for this to be used. If not, it should be documented that slack channels are not supported by terraform.

### New or Affected Resource(s)

* monitoring_notification_channel

**Comment by brunoban** [comment]
The way I did it was create the token inside Slack, with an app and a Bot User OAuth Access Token, then just using the token as a the auth token variable. It works, but there is a small problem.

I don't know if I'm doing something wrong, but I have the auth token defined as a variable, and every time I plan anything, Terraform thinks the auth token changed and tries to recreate the resource. I have the notification as a module, but even declaring it as a simple resource the result is the same.

```
  ~ module.staging_notifications.google_monitoring_notification_channel.notification_channel
      labels.auth_token: "***************************************************7bob" => "xoxo-123123123-123123123-1231231231231231237bob"
```
Values were modified, of course.

Am I doing something wrong or is this a bug?

**Comment by aguromanodg** [comment]
I am having issues with this as well, so help is appreciated.

**Comment by chrisst** [comment]
The monitoring API has been set up in a very flexible way which allows them to set up new channels and required fields without needing to create new api endpoints or new objects. However this flexibility makes it a bit more difficult to use each of the notification channels. For each of the labels per channel types I would look at https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.notificationChannelDescriptors/list in the api explorer. But for the contents of each channel's labels I would set up the channel through the UI and import into Terraform. I've added both of these suggestions to the documentation in the linked PR which will hopefully reduce the learning curve.

In terms of adding examples: Given the flexibility of this feature we are unable to provide examples for each notification type to actually cover all the permutations. Also our documentation won't be updated if the stackdriver team adds or modifies existing channels. The UI and official documentation is in lock step with the product team and will always be the most up to date.

For these reasons we won't be adding examples to the official documentation. If you think there is a situation that has significant complexity to get working we would welcome a PR to the `examples` directory or a blog post.
