### ISSUE TITLE
GCP network creation fails due to eventual consistency of google_project_service API

### ISSUE THREAD

**Issue by likwid** [terraform-providers/terraform-provider-google#3151]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.11
+ provider.google v2.1.0

### Affected Resource(s)

* google_project_service
* google_compute_network

### Terraform Configuration Files

main.tf
```tf
resource "google_project" "current" {
  name            = "${var.project_name}"
  project_id      = "${var.project_name}"
  billing_account = "${var.billing_account}"
  org_id          = "${var.organization_id}"
}

resource "google_project_service" "api_services" {
  project            = "${google_project.current.project_id}"
  count              = "${length(var.api_services)}"
  service            = "${element(var.api_services, count.index)}"
  disable_on_destroy = false
}

resource "google_project_iam_member" "members" {
  project = "${google_project.current.project_id}"
  count   = "${length(var.members)}"
  role    = "${lookup(var.members[count.index], "role")}"
  member  = "${lookup(var.members[count.index], "name")}"
}

resource "google_compute_network" "current" {
  project                 = "${google_project.current.project_id}"
  name                    = "${var.network_name}"
  auto_create_subnetworks = "true"
}
```

vars.tf
```tf
variable project_name {}
variable "billing_account" {}
variable "organization_id" {}

variable api_services {
  default = [
    "compute.googleapis.com",
    "cloudkms.googleapis.com",
    "container.googleapis.com",
    "iam.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "dns.googleapis.com",
    "cloudfunctions.googleapis.com",
    "serviceusage.googleapis.com",
  ]
}

variable "default_region" {
  default = "us-central1"
}

variable "default_zone" {
  default = "us-central1-f"
}

variable members {
  default = [
    {
      name = "user:[redacted]"
      role = "roles/owner"
    },
  ]
}

variable network_name {
  default = "example-net"
}

provider "google" {
  region = "${var.default_region}"
  zone   = "${var.default_zone}"
}
```

### Debug Output

https://gist.github.com/likwid/16ae8f6cbed7c227a8e0c595098cf108

### Panic Output

N/A

### Expected Behavior

The google network should be created

### Actual Behavior

```
Error: Error applying plan:

1 error(s) occurred:

* google_compute_network.current: 1 error(s) occurred:

* google_compute_network.current: Error creating network: googleapi: Error 403: Project 718911275328 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=718911275328 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I am authenticating to gcloud using my user account via `gcloud auth application-default login`

### References

* #2129 
* #1789

**Comment by likwid** [comment]
For posterity, I did end up finding a solution to my problem based on the advice from #2129 and #1789 that I will put here.

The problem seems to be that the google_project_service GCP API returns success before the APIs have actually been enabled. The graph for this looks like: 
`[Create Project] -> [Enable Services] -> [Create Network]`

The `google_project_service` resource seems to return before APIs are actually enabled, and this causes the `google_compute_network` resource creation to fail.

I was able to insert a null_resource into the graph, and make that null resource depend on `google_project_service` and additionally use a `local-exec` provisioner to sleep for 30 seconds. This seems to avoid the problem.

Here is the solution:

```
resource "google_project" "current" {
  name            = "${var.project_name}"
  project_id      = "${var.project_name}"
  billing_account = "${var.billing_account}"
  org_id          = "${var.organization_id}"
}

resource "google_project_service" "api_services" {
  project            = "${google_project.current.project_id}"
  count              = "${length(var.api_services)}"
  service            = "${element(var.api_services, count.index)}"
  disable_on_destroy = false
}

resource "google_project_iam_member" "members" {
  project = "${google_project.current.project_id}"
  count   = "${length(var.members)}"
  role    = "${lookup(var.members[count.index], "role")}"
  member  = "${lookup(var.members[count.index], "name")}"
}

resource "null_resource" "waiter" {
  # Changes to any instance of the cluster requires re-provisioning
  triggers {
    project_services_ids = "${join(",", google_project_service.api_services.*.id)}"
  }

  depends_on = ["google_project_service.api_services"]

  provisioner "local-exec" {
    command = "sleep 30"
  }
}

resource "google_compute_network" "current" {
  project                 = "${google_project.current.project_id}"
  name                    = "${var.network_name}"
  auto_create_subnetworks = "true"

  depends_on = ["null_resource.waiter"]
}
```

**Comment by jaceq** [comment]
I also had to add a dummy sleep after enabling APIs... honestly I find that quite poor :(

**Comment by venkykuberan** [comment]
Closing this one as another issue - https://github.com/terraform-providers/terraform-provider-google/issues/5649 is being tracked for the same problem
