### ISSUE TITLE
Enhancement: diff suppression for security_policy rules

### ISSUE THREAD

**Issue by nickjacques** [terraform-providers/terraform-provider-google#3152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Provider version: `google@2.0`

When using [`google_compute_security_policy`](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_security_policy.go) objects and updating the rules in that policy, Terraform plan/apply actions generate diffs that include rules that do not change. For example, this rule does not change but it is listed in the diff (values are redacted):

```
rule.1234567.action:                                    "allow" => "allow"
      rule.1234567.description:                               "My Test Rule 1" => "My Test Rule 1"
      rule.1234567.match.#:                                   "1" => "1"
      rule.1234567.match.0.config.#:                          "1" => "1"
      rule.1234567.match.0.config.0.src_ip_ranges.#:          "3" => "3"
      rule.1234567.match.0.config.0.src_ip_ranges.9999999:    "1.1.1.1/32" => "1.1.1.1/32"
      rule.1234567.match.0.config.0.src_ip_ranges.8888888:    "2.2.2.2/32" => "2.2.2.2/32"
      rule.1234567.match.0.config.0.src_ip_ranges.7777777:    "3.3.3.3/32" => "3.3.3.3/32"
      rule.1234567.match.0.versioned_expr:                    "SRC_IPS_V1" => "SRC_IPS_V1"
      rule.1234567.preview:                                   "false" => "false"
      rule.1234567.priority:                                  "105" => "105"
```

I would expect that this particular rule diff to be suppressed, since the values do not change. In a situation where I am adding or removing a rule, the output makes sense:

```
rule.0000000.action:                                    "" => "allow"
      rule.0000000.description:                               "" => "My Test Rule 2"
      rule.0000000.match.#:                                   "0" => "1"
      rule.0000000.match.0.config.#:                          "0" => "1"
      rule.0000000.match.0.config.0.src_ip_ranges.#:          "0" => "5"
      rule.0000000.match.0.config.0.src_ip_ranges.99999:      "" => "1.1.1.1/24"
      rule.0000000.match.0.config.0.src_ip_ranges.88888:      "" => "2.2.2.2/24"
      rule.0000000.match.0.config.0.src_ip_ranges.77777:      "" => "3.3.3.3/24"
      rule.0000000.match.0.config.0.src_ip_ranges.66666:      "" => "4.4.4.4/24"
      rule.0000000.match.0.config.0.src_ip_ranges.55555:      "" => "5.5.5.5/24"
      rule.0000000.match.0.versioned_expr:                    "" => "SRC_IPS_V1"
      rule.0000000.preview:                                   "" => ""
      rule.0000000.priority:                                  "" => "100"
```

Suppressing diffs of rules that do not change would greatly increase the readability and usability of plan/apply output. 

### New or Affected Resource(s)

* [`google_compute_security_policy`](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_security_policy.go)

### Potential Terraform Configuration

N/A, would apply to any configuration in which security policy rules remain the same - ideally, rules that do not change do not generate a diff in plan/apply actions. 

### References

* No references/issues that I am aware of

**Comment by rileykarson** [comment]
This is Terraform core behaviour unfortunately, and we can't do anything about it in the provider; hopefully `0.12` will make the diffs in this situation slightly more intuitive.
