### ISSUE TITLE
Sensitive content in google_storage_bucket_object

### ISSUE THREAD

**Issue by rcoy-v** [terraform-providers/terraform-provider-google#3153]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

`google_storage_bucket_object` always prints the contents of the bucket object during plan/apply. This is unwanted when trying to create an object that contains sensitive information. I would like to be able to provide generated content string to this resource, and not have it printed in terminal. 

### New or Affected Resource(s)

google_storage_bucket_object

### Potential Terraform Configuration
A new property like `sensitive_content`, which is marked as sensitive in the provider.

```tf
resource "google_storage_bucket_object" "sensitive" {
  name               = "sensitive-object"
  bucket             = "my-bucket"
  sensitive_content  = "generated content not printed during apply" # new property
}
```

**Comment by rileykarson** [comment]
Fixed by @rcoy-v in https://github.com/GoogleCloudPlatform/magic-modules/pull/1470
