### ISSUE TITLE
google_compute_instance.myinstance: Error creating instance: googleapi: Error 503: Code: '5565A2157AA41.A2D664D.AD06091F', backendError

### ISSUE THREAD

**Issue by gdubicki** [terraform-providers/terraform-provider-google#316]
### Terraform Version

Terraform v0.10.0

### Affected Resource(s)

google_compute_instance

### Terraform Configuration Files
```hcl
resource "google_compute_instance" "myinstance" {
  count = "${var.myinstance_count}"

  name         = "${format("myinstance%02d", count.index + 1)}"
  machine_type = "custom-1-4096"
  zone         = "${lookup(var.zones, count.index)}"
  tags         = ["no-ip"]

  depends_on = [
    "google_compute_disk.myinstance-data-disk",
  ]

  lifecycle {
    ignore_changes = ["metadata_startup_script", "create_timeout", "disk", "machine_type"]
  }

  boot_disk {
    initialize_params {
      image = "projects/myproject/global/images/family/common"
    }
  }

  attached_disk {
    source      = "${element(google_compute_disk.myinstance-data-disk.*.name, count.index)}"
    device_name = "myinstance-opt"
  }

  network_interface {
    network = "${google_compute_network.myproject2.name}"
  }

  metadata {
    puppet_master      = "${var.puppetmaster}"
    puppet_environment = "${var.puppet_environment}"
  }

  metadata_startup_script = "${file("../common/scripts/bootstrap.sh")}"
}
```

### Debug Output

https://gist.github.com/gdubicki/51e286128513c61a09c7cbd348166d28

### Expected Behavior

Instance should be created.

### Actual Behavior

Instance was not created.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I have just switched to a new service account that I use for terraform in this project. But this new SA does work and it succesfully created a disk and changes tags of existing instances in this project on previous apply run.

Also I am using a shared image here from a different project, but it also did work, although this IS the first usage of this image in this particular project.

Finally this was one of the first applies in this project after the upgrade to 0.10.0 from 0.9.x line.

**Comment by gdubicki** [comment]
...and it also was the first time I tried to use the new style disk resources. After I switched back to the old style:

```hcl
  disk {
    image = "projects/myproject/global/images/family/common"
  }

  disk {
    disk = "${element(google_compute_disk.myinstance-data-disk.*.name, count.index)}"
    device_name = "myinstance-opt"
    auto_delete = 0
  }
```

...`terraform apply` passed!

**Comment by rileykarson** [comment]
Hi @gdubicki!

When moving from `disk` to `attached_disk`, it looks like we changed from the `disk` field which takes a name to the `source` field, which takes a self link. You can update

```hcl
    source      = "${element(google_compute_disk.myinstance-data-disk.*.name, count.index)}"
```

to

```hcl
    source      = "${element(google_compute_disk.myinstance-data-disk.*.self_link, count.index)}"
```

and it should work; I tested with a smaller repro, and it worked for me:

```hcl
resource "google_compute_disk" "disk" {
	count = "3"
	name = "${format("tf-disk-%02d", count.index + 1)}"
	zone = "us-central1-a"
}

resource "google_compute_instance" "instance" {
  count = "3"

  name         = "${format("tf-instance-%02d", count.index + 1)}"
  machine_type = "f1-micro"
  zone         = "us-central1-a"

  boot_disk {
    initialize_params {
      image = "debian-8-jessie-v20170523"
    }
  }

  attached_disk {
    source      = "${element(google_compute_disk.disk.*.name, count.index)}"
  }

  network_interface {
    network = "default"
  }
}
```

Getting a `503` back here that doesn't describe the actual issue isn't great, so I'm going to leave this issue open to track a better behaviour here.

**Comment by jim-raney-physiq** [comment]
Seconded, I banged my head against this for a bit until I found this.  A better error message would be a good idea.

**Comment by rileykarson** [comment]
Closing this as outdated because the upgrade path isn't really a consideration anymore; we've had two major versions since then.
