### ISSUE TITLE
Private DNS support not fully merged

### ISSUE THREAD

**Issue by maxlip** [terraform-providers/terraform-provider-google#3165]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

$ terraform -v
Terraform v0.11.11
+ provider.google v2.1.0
+ provider.google-beta v2.1.0

### Affected Resource(s)

google_dns_managed_zone

### Terraform Configuration Files

```tf
provider "google-beta" {
  project = "myproject"
}
resource "google_dns_managed_zone" "private-zone" {
  name = "private-zone"
  dns_name = "private.example.com."
  description = "Example private DNS zone"
  visibility = "private"

  private_visibility_config {
    networks {
      network_url =  "${google_compute_network.network-1.self_link}"
    }
  }

  forwarding_config {
    target_name_servers {
      ipv4_address = "2.3.4.5"
    }
  }

}
resource "google_compute_network" "network-1" {
  name = "network-1"
  auto_create_subnetworks = false
}
```

### Debug Output

N/A - doesn't get that far.

### Expected Behavior

Private forwarding zone should have been created.

### Actual Behavior

Terraform can't make it past plan phase due to not taking the private zone-specific keys:

$terraform plan
Error: google_dns_managed_zone.private-zone: : invalid or unknown key: forwarding_config
Error: google_dns_managed_zone.private-zone: : invalid or unknown key: private_visibility_config
Error: google_dns_managed_zone.private-zone: : invalid or unknown key: visibility

### Steps to Reproduce

1. Put down the config above, anything leveraging the keys "forwarding_config", "private_visibility_config", or "visibility"
2. Run `terraform plan`

### Important Factoids

I see a lot of yes/no discussion around when/how to merge this feature, but the net result *appears* to be that it was merged mid-Feb and supposed to be in v2.1 release.

### References

Magic-Modules PR to enable this feature appears to be https://github.com/GoogleCloudPlatform/magic-modules/pull/981
However, there does not appear to be a corresponding merged PR within the beta project. 

Perhaps the docs were mistakenly released since it was decided not not to release https://github.com/terraform-providers/terraform-provider-google-beta/pull/403?

**Comment by rileykarson** [comment]
Hey @maxlip!

Support was added in `2.1.0`. Try adding `provider = "google-beta` to the resource; unfortunately you need to explicitly add it to each and every resource even with a provider block defined. See [the using `google-beta` docs](https://www.terraform.io/docs/providers/google/provider_versions.html#using-the-google-beta-provider) for reference.

**Comment by maxlip** [comment]
Yes, thanks for the education. My mistake!
