### ISSUE TITLE
no timeouts are set on http.Client used in GCP API calls

### ISSUE THREAD

**Issue by mattnworb** [terraform-providers/terraform-provider-google#3168]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Since https://github.com/terraform-providers/terraform-provider-google/issues/3127 was closed because of a PR linked to it I wanted to recreate [this comment](https://github.com/terraform-providers/terraform-provider-google/issues/3127#issuecomment-468375316) as its own issue.

We've seen cases where attempts in to create a `google_container_cluster` via Terraform fail due to a connection or HTTP timeout in the polling requests that the terraform-provider-google make to check on the status of the operation to create the GKE cluster. In some cases we have seen a hanging HTTP request to `
GET /v1beta1/projects/PROJECT/locations/us-central1/operations/operation-...` take 15 minutes before being aborted and stopping the rest of the Terraform operation.

The PR linked to #3127 will allow for HTTP request errors to GCP to be retried, but if it was possible to configure the `http.Client` instance used in `google/config.go`, or if defaults were specified, then the hanging requests could be retried much sooner than after N minutes.

 If I am understanding correctly, the `http.Client` used by `google.golang.org/api/container/v1beta1`, `google.golang.org/api/container/v1`, and in calls (from terraform-provider-google like `w.Service.Projects.Locations.Operations.Get(name).Do()` all use the `http.Client` created by `google/config.go` and would therefore use its `Timeout` value.

https://github.com/terraform-providers/terraform-provider-google/blob/77c086de1c533e1ad4ea23a153d4266775c9ab2d/google/config.go#L115-L148

**Comment by rileykarson** [comment]
Wasn't it given a `30s` timeout in that PR? https://github.com/GoogleCloudPlatform/magic-modules/pull/1451/files#diff-2bc1b7a5d9b143d897a6d05b87b58356R132

**Comment by mattnworb** [comment]
@rileykarson yes looks like I misread that PR 😄 thanks for the quick correction!
