### ISSUE TITLE
Refresh fails with google_compute_attached_disk when manually deleted

### ISSUE THREAD

**Issue by timwsuqld** [terraform-providers/terraform-provider-google#3172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

$ terraform -v
Terraform v0.11.11
+ provider.google v1.19.0

### Affected Resource(s)

* google_compute_attached_disk

### Terraform Configuration Files
Using config similar to #2098 
```tf
# Extra disk
resource "google_compute_disk" "extra_disk" {
  count = "${var.server_extra_disks_count}"
  name  = "${lookup(var.server_extra_disks[count.index], "NAME")}"
  size  = "${lookup(var.server_extra_disks[count.index], "SIZE")}"
}

resource "google_compute_attached_disk" "extra_disks_attachments" {
  count       = "${var.server_extra_disks_count}"
  disk        = "${element(google_compute_disk.extra_disk.*.self_link, count.index)}"
  instance    = "${element(google_compute_instance.instance.*.self_link, 0)}"
  device_name = "${lookup(var.server_extra_disks[count.index], "NAME")}"
  depends_on = ["google_compute_instance.instance"]
}
```
### Debug Output

Debug log at https://gist.github.com/timwsuqld/b637d24d8020d3e87ced184600d53aba (with some of the irrelevant stuff removed, otherwise the log was more than twice the size)
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

google_compute_disk.boot_disk: Refreshing state... (ID: suq-gce-backups-1)
data.terraform_remote_state.suqld_core_state: Refreshing state...
google_compute_disk.extra_disk: Refreshing state... (ID: borg-repository)
google_compute_instance.instance: Refreshing state... (ID: suq-gce-backups-1)
google_compute_attached_disk.extra_disks_attachments: Refreshing state... (ID: suq-gce-backups-1:borg-repository)

Error: Error refreshing state: 1 error(s) occurred:

* module.suq-gce-backups-1.google_compute_attached_disk.extra_disks_attachments: 1 error(s) occurred:

* module.suq-gce-backups-1.google_compute_attached_disk.extra_disks_attachments: google_compute_attached_disk.extra_disks_attachments: googleapi: Error 404: The resource 'projects/suqld-cloud/zones/australia-southeast1-b/instances/suq-gce-backups-1' was not found, notFound
```

### Expected Behavior

Terraform should detect that the previously created google_compute_attached_disk is no longer present, and should then plan to recreate it

### Actual Behavior

It errored because a previously created google_compute_attached_disk was deleted
```
Error: Error refreshing state: 1 error(s) occurred:

2019-03-04T15:22:17.251+1000 [DEBUG] plugin.terraform-provider-google_v1.19.0_x4: 2019/03/04 15:22:17 [ERR] plugin: plugin server: accept unix /tmp/plugin672211442: use of closed network connection
* module.suq-gce-backups-1.google_compute_attached_disk.extra_disks_attachments: 1 error(s) occurred:

* module.suq-gce-backups-1.google_compute_attached_disk.extra_disks_attachments: google_compute_attached_disk.extra_disks_attachments: googleapi: Error 404: The resource 'projects/suqld-cloud/zones/australia-southeast1-b/instances/suq-gce-backups-1' was not found, notFound

```

### Steps to Reproduce

1. `terraform apply` to create the extra attached disks
2. Manually delete the VM and disks (just deleting the VM was enough to cause this)
3. Attempt `terraform refresh`

### References

* #2098 

If you want, I can try and recreate this with a simple SLS that can be reproduced easily, but that'll have to wait a day or so.

**Comment by timwsuqld** [comment]
I also realised that the google-provider version was out of date. I've retested and it's still an issue.
```
$ terraform -v
Terraform v0.11.11
+ provider.google v2.1.0
```

**Comment by timwsuqld** [comment]
And running `terraform state rm module.suq-gce-backups-1.google_compute_attached_disk.extra_disks_attachments` was enough for me to get operating again

So it's that resource that is the problem (I think)

**Comment by timwsuqld** [comment]
@rileykarson Thanks for that. I assume the next release of the Google provider will have that applied then?

**Comment by rileykarson** [comment]
Yep! This should be present in `2.2.0`.
