### ISSUE TITLE
google_container_cluster ignores cluster_ipv4_cidr to define custom Pod CIDR

### ISSUE THREAD

**Issue by afritzler** [terraform-providers/terraform-provider-google#3190]
### Community Note

* This issue currently occurs in the zone `europe-west1-b`.
* Setting the attribute `cluster_ipv4_cidr` doesn't seem to have any effect on the created cluster. The cluster pod cidr is always reverted to `10.44.0.0/14`.

### Terraform Version

```
Terraform v0.11.3
+ provider.google v2.1.0
+ provider.google-beta v2.1.0
+ provider.local v1.1.0
+ provider.template v2.1.0
```

### Affected Resource(s)

* google_container_cluster

### Expected Behavior

The Pod CIDR as provided via `cluster_ipv4_cidr` should be the actual Pod CIDR of the created cluster.

### Actual Behavior

The cluster Pod CIDR is always defaulted to `10.44.0.0/14`.

**Comment by rileykarson** [comment]
Hey @afritzler!

Are you able to include a sample config + debug logs? I suspect that what's happened is that some configuration causes GKE to ignore the `cluster_ipv4_cidr` value sent and use a different one instead- so this will be a matter of fussing out which that it.

**Comment by afritzler** [comment]
Hi and thanks for the quick response!

So the thing is - I changed now the region from `europe-west1` to `europe-west4` and it worked! Any valid CIDR range is accepted. Retried the setup in `west1` ... same problem again.

I can assemble an example we are running here and will come back to you tomorrow.

**Comment by ronenfreeman2** [comment]
I have the same issue:

`terraform apply`

```
google_container_cluster.gke_cluster: Creating...
  ...
  cluster_ipv4_cidr:                                                       "" => "10.0.0.0/14"
  ...
```

`terraform plan`
```
-/+ google_container_cluster.gke_cluster (new resource required)
  ...
      cluster_ipv4_cidr:                                              "10.52.0.0/14" => "10.0.0.0/14" (forces new resource)
  ...
```

The state file shows that `cluster_ipv4_cidr` was initially set to `10.52.0.0/14` ignoring `google_container_cluster.gke_cluster.cluster_ipv4_cidr`

**Comment by rileykarson** [comment]
I haven't been able to reproduce this. It is possible that the API failed silently before? I got an error testing just now if a subnetwork overlapped with the range inside my network that I'd chosen. I'm going to close this out, but if anyone can provide config + debug logs that would be a big help.
