### ISSUE TITLE
vertical pod autoscaling beta feature for google_container_cluster

### ISSUE THREAD

**Issue by mattnworb** [terraform-providers/terraform-provider-google#3200]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

[Vertical pod autoscaling](https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling) is available in beta now in GKE. Can support for it be added to `terraform-provider-google-beta` as well?

### New or Affected Resource(s)

* google_container_cluster

### References

* https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling

**Comment by deenski** [comment]
100% down to help implement this. I could use a little guidance, but would love to get this going.

**Comment by deenski** [comment]
Looking deeper into this, this feature should already either be enabled, or is very close to working. Looking at the v1beta1/container-gen.go and v1beta1/container-api.json ... Everything is in place for this to work. I don't really know where/how to update the resource definition, but will gladly do so if needed to get this feature working with the beta provider.

**Comment by mattnworb** [comment]
@deenski I believe the place to update (or at least one of them) would be https://github.com/GoogleCloudPlatform/magic-modules

**Comment by rileykarson** [comment]
@mattnworb is correct! MM is probably the best place to change this, specifically to https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/resources/resource_container_cluster.go.erb

https://github.com/terraform-providers/terraform-provider-google-beta/commit/d1bf585724cd9854c2476302efa5ebdfedfc580a is a good template, since that change added a similar field; https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/resources/resource_container_cluster.go.erb#L299-L309 shows what we do to omit beta fields from the GA provider for handwritten resources like GKE cluster. This field can probably be omitted entirely, since it's be an entirely new field.

**Comment by deenski** [comment]
Thank you both for the guidance. I have a lot on my plate, but I think I get the gist of it. Unfortunately I don't have Ruby installed, so that will take a little time to set up, and I have some deliverables to get out before the weekend. But I'll try to submit a PR to magic-modules by Monday.

**Comment by deenski** [comment]
Not sure if I'll be able to fulfill this by Monday after all. Putting out a few fires at the moment. Please feel free to take this on. Happy to help however I can, but I doubt I have the time soon to devote my focus to this.

**Comment by rileykarson** [comment]
No problem! I'll leave this issue assigned to HashiBot to indicate a community member is looking into it, and if one of the maintainers is looking to add this before you get to it they'll reach out to make sure we don't duplicate work.

**Comment by aluis-ac** [comment]
Hello, 

Is there any estimation to "Vertical pod autoscaling" be implemented on terraform? Thanks!

**Comment by chrisst** [comment]
Added in https://github.com/terraform-providers/terraform-provider-google-beta/pull/749 and will be available in the next release.

**Comment by ellisio** [comment]
@chrisst I stumbled across this as I'm currently working with HPA, and found VPA in the k8s docs. Kind of wild this is a feature being added the same day I'm researching it 🤘 Any chance I could get a date on when the next beta build will be released, or can you link me to a roadmap of some sort so I can set a reminder to circle back on this feature? Much appreciated in advance for any help.

**Comment by aluis-ac** [comment]
Looks like it's done, thanks a lot guys!

**Comment by chrisst** [comment]
ℹ️ We've been setting a goal for ourselves of shipping new versions of the provider roughly every two weeks. So if a feature is merged it should be available within a couple weeks. Feel free to take a glance at the [changelog](https://github.com/terraform-providers/terraform-provider-google-beta/blob/master/CHANGELOG.md) for more details!

**Comment by rileykarson** [comment]
Even better, we've documented some details about our releases at https://www.terraform.io/docs/providers/google/index.html#releases now.
