### ISSUE TITLE
Extend fine-grained IAM Audit Config setting to the organization level

### ISSUE THREAD

**Issue by yhuang** [terraform-providers/terraform-provider-google#3202]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please extend the capability to set fine-grained IAM Audit Config on the project level to the organization level.  

### Potential Terraform Configuration

The resource declaration can look something like this:

```
resource "google_organization_iam_audit_config" "serviceusage" {
  organization = "${local.org_id}"
  service = "serviceusage.googleapis.com}"

  audit_log_config {
     "log_type" = "DATA_READ",
  }

  audit_log_config {
    "log_type" = "DATA_WRITE",
  }

  audit_log_config {
    "log_type" = "ADMIN_READ",
  }
}
```

### References

https://github.com/GoogleCloudPlatform/magic-modules/pull/1094

**Comment by chrisst** [comment]
This was added in https://github.com/GoogleCloudPlatform/magic-modules/pull/2741
