### ISSUE TITLE
App Engine domain mapping

### ISSUE THREAD

**Issue by JeanDaniel-Fischer** [terraform-providers/terraform-provider-google#3204]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Hi, 
could you add support for App Engine application domain mapping ?
It would help when we configure new project and need to bind severals custom domains to it. 
If it helps, I am referencing this API (in the python lib) https://developers.google.com/resources/api-libraries/documentation/appengine/v1/python/latest/appengine_v1.apps.domainMappings.html.

### New or Affected Resource(s)

* google_appengine_domain_mapping

### Potential Terraform Configuration

```tf
resource "google_appengine_domain_mapping" "mydomain" {
  certificate_id = "mycertificateid"
  domain = "my.domain.name"
  project = "myproject"
}
```

### References

Did not find any.

**Comment by ncjones** [comment]
I would like to see an example of how to create a valid Cloud DNS record set that uses a custom app engine domain.

**Comment by LondonAppDev** [comment]
Is it currently not possible to map a custom domain to an App Engine instance using Terraform? I've not been able to find anything in the docs.
