### ISSUE TITLE
Numeric account_id causing regexp error.

### ISSUE THREAD

**Issue by kolaworld** [terraform-providers/terraform-provider-google#3212]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.12
+ provider.google v2.0.0
+ provider.kubernetes v1.5.1

### Affected Resource(s)

* google_service_account

### Terraform Configuration Files

```tf
data "google_service_account" "svc_acct" {
  account_id = "12345678900"
  project = "my-project"
}
```

### Debug Output
After running `terraform plan`, I get the below error:
```
Error: module.my_module.data.google_service_account.svc_acct: "account_id" ("12345678900") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"
```
### Expected Behavior
Terraform should be able to process an account_id with only numeric values.

### Actual Behavior
Terraform gave back a regexr error because account_id was only numeric values.

### Steps to Reproduce

1. `terraform plan` with above data.

**Comment by chrisst** [comment]
Service accounts can't be created with an all numeric id. Trying to create on through the UI will throw a similar error:
```
Service account ID must start with a lower case letter, followed by one or more lower case alphanumerical characters that can be separated by hyphens.

```
