### ISSUE TITLE
Some import formats for compute routers don't work

### ISSUE THREAD

**Issue by rolandkool** [terraform-providers/terraform-provider-google#3213]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Provider 1.90

### Affected Resource(s)

* google_compute_router

### Issue

When trying to import a google_compute_router using format `projects/project/regions/region/routers/name` or `project/region/name` the import fails with:

> Error reading ComputeRouter "projects/myproject": googleapi: Error 400: Invalid value for field 'region': 'projects'. Unknown region., invalid

Only format `name` or `region/name` seems to work. If other formats are supported it is a bug, otherwise the documentation needs to be updated to not suggest these formats.

**Comment by Chupaka** [comment]
Could you check this with actual provider version (2.1.0)?

**Comment by chrisst** [comment]
You are correct that `project/region/name` is broken, but the fully qualified import appears to be working.
