### ISSUE TITLE
Specifying disk type in the initialParams of disk fails

### ISSUE THREAD

**Issue by kamaltherocky** [terraform-providers/terraform-provider-google#322]
when you specify the disk type as pd-standard, it fails with invalid or malformed URL error. if the disk type is not specified then it works with the default.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

$ terraform -v                                                                                           
Terraform v0.10.0

### Affected Resource(s)
"google_compute_instance"

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
resource "google_compute_instance" "consul-server-master" {
  name         = "consul-server-master"
  machine_type = "n1-standard-2"
  zone         = "us-central1-a"

  tags = ["consul-server"]

  boot_disk {
    initialize_params {
      size = "30"
      type = "pd-standard"
      image = "ubuntu-1404-docker-latest"
    }
  }

  network_interface {
    subnetwork = "subnet01"
    subnetwork_project = "network01"
  }

}

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

Error applying plan:

1 error(s) occurred:

* module.consul.google_compute_instance.consul-server-master: 1 error(s) occurred:

* google_compute_instance.consul-server-master: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.disks[0].initializeParams.diskType': 'pd-standard'. The URL is malformed., invalid

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Compute instance should be created with a boot disk of type Standard-PD

### Actual Behavior
It failed with error that the disk type is invalid or malformed url for 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

 `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by rileykarson** [comment]
Thanks for the report @kamaltherocky!

It looks like we have a fix upcoming in the next release done in #275; I'm going to close this out for now, but if you encounter the error again in the future feel free to reopen this issue!
