### ISSUE TITLE
Importing google_storage_bucket resource requires Compute Engine API

### ISSUE THREAD

**Issue by marcin-kolda** [terraform-providers/terraform-provider-google#3222]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.11
+ provider.google v2.1.0

### Affected Resource(s)

* google_storage_bucket

### Terraform Configuration Files

```tf
resource "google_storage_bucket" "gcs_bucket" {
  name = "random-name-bucket-djgieovmgjbuaj"
  project = "my_project"
}
```

### Debug Output

https://gist.github.com/marcin-kolda/e0d67c01b9751a4d652f24fa47b26d8d

### Expected Behavior

Bucket should be imported successfully. As described in [documentation](https://www.terraform.io/docs/providers/google/r/storage_bucket.html), Compute Engine API doesn't need to be enabled if it explicitly set project on the bucket resource.

If you still need to map project id to project number I would suggest switching to [project.get](https://cloud.google.com/resource-manager/reference/rest/v1/projects/get) method. Enabling Compute Engine API has some drawbacks like creating default compute service account with Editor IAM role.

### Actual Behavior

Command failed because Compute Engine API is disabled. 

### Steps to Reproduce

1. `terraform import google_storage_bucket.gcs_bucket random-name-bucket-djgieovmgjbuaj`

### References

* #1089
* #1125
* #2792

**Comment by chrisst** [comment]
I've tried to cover all the permutations of using storage bucket that I'm aware. @marcin-kolda can take a look at the linked PR description and confirm that I haven't missed a scenario you care about?

**Comment by marcin-kolda** [comment]
Hi @chrisst, scenarios look good to me. Thanks for quick fix 👍
