### ISSUE TITLE
google_container_cluster issue_client_certificate always false if created with min_master_version = 1.12.X

### ISSUE THREAD

**Issue by rbounds** [terraform-providers/terraform-provider-google#3240]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.10
+ provider.google v2.2.0
+ provider.google-beta v2.2.0

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "primary" {
  name   = "my-gke-cluster"
  region = "us-central1"
  provider = "google-beta"

  min_master_version = "1.12.5-gke.10"
  remove_default_node_pool = true
  initial_node_count = 1
  master_auth {
    client_certificate_config {
      issue_client_certificate = true
    }
  }
}
```

### Expected Behavior
`master_auth.0.client_certificate_config.0.issue_client_certificate` should set to true
`terraform plan` should have no changes. 

### Actual Behavior
master_auth.0.client_certificate_config.0.issue_client_certificate remains false
`terraform plan` forces new `google_container_cluster` resource

### Steps to Reproduce
1. `terraform apply` a `google_container_cluster` resource with `master_auth.0.client_certificate_config.0.issue_client_certificate = "true" ` and `min_master_version = "1.12.5-gke.10"`
2. terraform plan.

**Comment by BrendanThompson** [comment]
I was seeing similar behaviour, but as of yesterday its now creating new certificates for every apply. Meaning, that when I make minor changes to TF it destroys the cluster and creates it again although it errors on destroy.

**Comment by mattnworb** [comment]
In 1.12, client certificates are now disabled by default https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster

**Comment by petervandenabeele** [comment]
FWIW (may be trivial in hindsight), I was able to do a work-around with adding:

```
+    client_certificate_config {
+      issue_client_certificate = false
+    }
```
to the `google-container-cluster` definition. For specific reasons, I am stuck on an old version of the google provisioner.

```
$ terraform version
Terraform v0.11.13
+ provider.google v1.20.0  ## OLD VERSION
+ provider.kubernetes v1.5.2
+ provider.null v1.0.0
+ provider.template v1.0.0
```

In my experience, this issue:
* only impacted a _fresh_  1.12.5-gke.5 cluster that I made this morning
* did _not_ impact older clusters that I had upgraded through the GCP User Interface from 1.11.7-gke.12 to 1.12.5-gke.5, but had not recreated.

**Comment by rileykarson** [comment]
This is pretty similar to https://github.com/terraform-providers/terraform-provider-google/issues/3369, so I'm going to consolidate them both there.
