### ISSUE TITLE
client-side encryption not working in cli; works fine when coded

### ISSUE THREAD

**Issue by mikosa** [terraform-providers/terraform-provider-google#3242]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

I am trying to do client-side encryption of the state file.
using TERRAFORM_VERSION=0.11.13

if I use command line to add the encryption key, it does not encrypt:
terraform init --backend-config="encryption_key=8eEmpoOYZ66QgAW6sKdsOXWeksdX0XW3kmmpmhczfBk="

Using same srcript, if I add the encryption in the terraform code like so it works fine:
  terraform  {
  backend "gcs" {
    bucket = "terraform"
    prefix  = "state/file"
    credentials = "account.json"
    encryption_key ="8eEmpoOYZ66QgAW6sKdsOXWeksdX0XW3kmmpmhczfBk="
    }
  }

### Expected Behavior

using the cli to add encryption key should have encrypted the gcs backend with client-side encryption.

### Actual Behavior

when using the cli method to add encryption key, backend file in gcs is not encrypted with client-side encryption.

* #0000

**Comment by emilymye** [comment]
This is a bug against upstream terraform, please file it against https://github.com/hashicorp/terraform
