### ISSUE TITLE
google_storage_bucket: changing storage_class forces new resource

### ISSUE THREAD

**Issue by Chupaka** [terraform-providers/terraform-provider-google#3247]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.11
+ provider.cloudflare v1.12.0
+ provider.google v2.2.0

### Affected Resource(s)

* google_storage_bucket

### Terraform Configuration Files

```tf
resource "google_storage_bucket" "bucket" {
  name          = "some-bucket-name"
  storage_class = "COLDLINE" # then change it to "NEARLINE"
}
```

### Expected Behavior

Default storage class is changed from COLDLINE to NEARLINE.

### Actual Behavior

```
Terraform will perform the following actions:

-/+ google_storage_bucket.bucket (new resource required)
<snip>
      storage_class:     "COLDLINE" => "NEARLINE" (forces new resource)
<snip>

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2. Change storage_class
3. `terraform plan`

### Important Factoids

When I change Default storage class manually via Console, `terraform plan` says `No changes. Infrastructure is up-to-date.`

**Comment by emilymye** [comment]
Looks like it's not supported through PATCH (which is what we use to update buckets) but it is through update? Interesting, I'll take a look.
