### ISSUE TITLE
google_container_cluster fails while master is upgrading on regional cluster

### ISSUE THREAD

**Issue by ctrox** [terraform-providers/terraform-provider-google#3249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

0.11.13
google 2.2.0

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
data "google_container_cluster" "primary" {
  name   = "demo"
  region = "us-central1"
}

output "endpoint" {
  host = "${data.google_container_cluster.primary.endpoint}"
}
```

### Expected Behavior

I would expect the data source to work even if a cluster is upgrading as regional cluster have master HA and the kubernetes API is responding.

### Actual Behavior

```
* data.google_container_cluster.primary: data.google_container_cluster.primary: Error reading Container Cluster "demo": Cluster "demo" has status "RECONCILING" with message ""
```

### Steps to Reproduce

1. Run `terraform apply` to create a cluster with >6 nodes
2. Run `terraform apply` again and it will fail while refreshing the state

### Important Factoids

This is especially painful when creating a cluster with more than 6 nodes as it goes into a `RECONCILING` state for over 10 minutes just after reporting `RUNNING` for a few seconds. I'm trying to deploy some resources on the cluster after the initial creation but this fails at getting `data.google_container_cluster.primary.endpoint`, even though the kubernetes API is responding and I would be able to deploy resources on it. Also when creating a cluster in terratest, the destroy step will fail because the state refresh fails.

It might be that the GKE API is at fault here because it reports the cluster to be `RUNNING` for a few seconds before it goes back into the `RECONCILING` state but also assuming that the control plane is HA, we should be able to do things with it.

**Comment by emilymye** [comment]
It [looks](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_container_cluster.go#L827) like currently we return an error (retriable) if the cluster isn't in `RUNNING` state. 

I'm not exactly sure what the the best way to handle this is. I don't know enough about the `RECONCILING` state to say we can guarantee the values returned during this state wouldn't cause a diff later on when it switches back to `RUNNING`.

**Comment by ctrox** [comment]
Yeah I have seen that too. I guess the safest solution for now would be to just be able to configure the retry timeout so we can wait a bit longer for the cluster to settle.
But it would be interesting to know why GKE takes so long when setting up >6 nodes (just what I observed in my limited testing) and why it goes to `RUNNING` for a minute in between. The only thing I could find on the subject was this: 
> Because we are creating a cluster of 6 nodes, the cluster may go into a 'RECONCILING' status as the control plane's instance size may be increased.
Source: https://github.com/GoogleCloudPlatform/gke-stateful-applications-demo#deployment-steps

**Comment by rileykarson** [comment]
The explicit check for `RUNNING` that failed this was removed a while ago, and there's currently a check for `ERROR` or `DEGRADED` that will cause the read to bail out. That's going away in https://github.com/GoogleCloudPlatform/magic-modules/pull/3115, but I'm optimistically going to close this out early since the original error wouldn't happen anymore.
