### ISSUE TITLE
BigQuery: Adding new column to table crashes terraform

### ISSUE THREAD

**Issue by rameshvenk** [terraform-providers/terraform-provider-google#326]
### Terraform Version
`Terraform v0.10.0`

### Affected Resource(s)
Please list the resources as a list, for example:
- google_bigquery_table

### Terraform Configuration Files
```hcl
provider "google" {
        project = "kohls-bigdata-sandbox"
        region  = "us-central1"
}

resource "google_bigquery_table" "test_t" {
        dataset_id = "tkmaikc"
        table_id   = "test_t"
        labels {
                env = "dev"
        }
        schema = "${file("test_t.json")}"
}
```

### Panic Output
https://gist.github.com/rameshvenk/06b06921b0dfee8e0be0276ffdd00db2#file-crash-log

### Expected Behavior
The columns should have been added to the existing table

### Actual Behavior
Terraform crashed with a panic as shown in the gist above

### Steps to Reproduce

1.  Create a file called `test_t.json` with the contents below
```hcl
[
    {
        "mode": "nullable",
        "name": "state",
        "type": "string"
    }
]
```
2. Run `terraform apply`
3. Next create a file called `test_t_add_cols.json` with the contents below
```hcl
[
    {
        "mode": "nullable",
        "name": "kind",
        "type": "string"
    },
    {
        "mode": "required",
        "name": "fullName",
        "type": "string"
    }
]
```
4. Change in the terraform .tf file change the `schema` filename to `test_t_add_cols.json`
5. Run `terraform apply`.
6. Terraform crashes.

**Comment by rameshvenk** [comment]
I had a typo in the `test_t_add_cols.json`. The correct file looks like this (changed required to nullable)

```hcl
[
    {
        "mode": "nullable",
        "name": "kind",
        "type": "string"
    },
    {
        "mode": "nullable",
        "name": "fullName",
        "type": "string"
    }
]
```

**Comment by danawillow** [comment]
This panic should be fixed by #209- let us know if it still persists after the next release!

**Comment by rameshvenk** [comment]
Hi, I downloaded terraform 0.10.2 (I was running 0.10.0 previously) and this issue still persists. I can upload the crash.log if required.

**Comment by danawillow** [comment]
No need- it's not the overall Terraform release that gets this change, but the one for the provider itself (see https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/ for more information). The google provider hasn't had a release since the change was submitted.
