### ISSUE TITLE
google_container_cluster apply is not idempotent with master_ipv4_cidr_block 

### ISSUE THREAD

**Issue by clebio** [terraform-providers/terraform-provider-google#3260]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```sh
$ terraform version
Terraform v0.11.13
+ provider.google v2.2.0
```

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
variable "region" {
  default = "us-central1"
}

variable "project" {}

provider "google" {
  project = "${var.project}"
  region  = "${var.region}"
}

resource "google_container_cluster" "main" {
  name               = "repro"
  region             = "${var.region}"
  initial_node_count = 1

  private_cluster_config {
    enable_private_endpoint = false
    master_ipv4_cidr_block  = "172.16.0.0/28"
    enable_private_nodes    = false
  }
```

#### Additional info on configurations

Leaving `master_ipv4_cidr_block` works fine (no replacement on second plan/apply):

```tf
  private_cluster_config {
    enable_private_endpoint = false
    enable_private_nodes    = false
  }
```

Setting `enable_private_nodes = true` also does not induce a replacement:

```tf
  private_cluster_config {
    enable_private_endpoint = false
    master_ipv4_cidr_block  = "172.16.0.0/28"
    enable_private_nodes    = true
  }

  ip_allocation_policy {}
```

  Though that seems to produce a _change_ on subsequent plan:

```sh
  ~ google_container_cluster.main
      master_authorized_networks_config.#: "1" => "0"
```

### Expected Behavior

An `apply` followed by another `apply` or `plan` should not cause replacement of the cluster.

### Actual Behavior

A second apply replaces the cluster.

### Steps to Reproduce

1. `terraform apply -auto-approve`
1. `terrraform plan`

The apply succeeds cleanly, but the plan shows replacement of the cluster due to `private_cluster_config.0.master_ipv4_cidr_block`

```sh
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

google_container_cluster.main: Refreshing state... (ID: repro)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ google_container_cluster.main (new resource required)
      id:                                              "repro" => <computed> (forces new resource)
      additional_zones.#:                              "1" => "1"
      additional_zones.114014501:                      "us-central1-b" => "us-central1-b"
      addons_config.#:                                 "1" => <computed>
      cluster_autoscaling.#:                           "0" => <computed>
      cluster_ipv4_cidr:                               "10.32.0.0/14" => <computed>
      enable_binary_authorization:                     "" => <computed>
      enable_kubernetes_alpha:                         "false" => "false"
      enable_legacy_abac:                              "false" => "false"
      enable_tpu:                                      "" => <computed>
      endpoint:                                        "35.224.48.131" => <computed>
      initial_node_count:                              "1" => "1"
      instance_group_urls.#:                           "0" => <computed>
      ip_allocation_policy.#:                          "0" => <computed>
      logging_service:                                 "logging.googleapis.com" => <computed>
      master_auth.#:                                   "1" => <computed>
      master_ipv4_cidr_block:                          "" => <computed>
      master_version:                                  "1.11.7-gke.4" => <computed>
      monitoring_service:                              "monitoring.googleapis.com" => <computed>
      name:                                            "repro" => "repro"
      network:                                         "projects/throwaway/global/networks/default" => "default"
      network_policy.#:                                "1" => <computed>
      node_config.#:                                   "0" => <computed>
      node_pool.#:                                     "0" => <computed>
      node_version:                                    "1.11.7-gke.4" => <computed>
      private_cluster:                                 "" => <computed>
      private_cluster_config.0.master_ipv4_cidr_block: "" => "172.16.0.0/28" (forces new resource)
      private_cluster_config.0.private_endpoint:       "" => <computed>
      private_cluster_config.0.public_endpoint:        "" => <computed>
      project:                                         "throwaway" => <computed>
      region:                                          "us-central1" => "us-central1"
      remove_default_node_pool:                        "true" => "true"
      zone:                                            "us-central1" => <computed>

Plan: 1 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------
```

### References

* #2231
* #3098

**Comment by emilymye** [comment]
Hmm, I believe that if enable_private_nodes is false, master ipv4 cidr is ignored by the API and a config block is not returned, hence the permadiff. We could try to add validation so that doesn't happen and make sure the master_authorized_networks_config is computed from API if not given, but there's not a great way for us to validate blocks based on specific values of the block. 

It looks like gcloud actually rejects config as specified (enable_private_nodes = false, master ipv4 cider range supplied), so we wouldn't support the above config in any case. Is there a reason you need to use that config?

**Comment by clebio** [comment]
The broader problem here is that I would like to support both options for `enable_private_nodes` (and possibly also for `enable_private_endpoint`), in a module. But if I have to conditionally include the `master_ipv4_cidr_block` attribute in order to do so, I have to make multiple cluster resource definitions, `count` on `var.enable_private_nodes == true ?`, and then `coalescelist` in the module outputs. There's other attributes which also can only be conditionally specified (e.g. `region` versus `zone`), so now my module has something like eight different possible `google_container_cluster` resources, one of which is conditionally applied based on some horrendous `count = "${var.enable_private_nodes && var.zonal && ... == true ? 1 : 0}"`.

**Comment by emilymye** [comment]
We recently made it so master_ipv4_cidr_block can be set to an empty value (i.e. ""). Would that solve your issue? Or am I misunderstanding?

**Comment by clebio** [comment]
Hmm, I wasn't aware of that. I will test again with, say, `master_ipv4_cidr_block    = "${var.private_nodes ? "172.16.0.0/28" : ""}"` when I get a few mintues.

**Comment by clebio** [comment]
Using 

```
variable "private_nodes" {
  default = true
}

resource "google_container_cluster" "main" {
  name               = "repro"
  region             = "${var.region}"
  initial_node_count = 1

  private_cluster_config {
    enable_private_endpoint = false
    master_ipv4_cidr_block  = "${var.private_nodes ? "172.16.0.0/28" : "" }"
    enable_private_nodes    = "${var.private_nodes}"
  }

  ip_allocation_policy {}
}
```

I get a (non-destructive) change on second `apply`:

```
Terraform will perform the following actions:

  ~ google_container_cluster.main
      master_authorized_networks_config.#: "1" => "0"```

Setting `private_nodes=false` seems to work as well, with no change on second apply. So I guess that works alright.

**Comment by emilymye** [comment]
So, after looking at it closer, it seems that when you have enable_private_nodes = true/master_ipv4_cidr_block set, the master_authorized_networks_config should exist and be in config, as the API creates it (just with no cidr_blocks/external access set up). I'm not sure what the best way to fix this is, since the potential fix (to make it computed) would technically not be valid under TF 0.12, so we're trying to figure out how to do it. The workaround for now might be to just have an empty `master_authorized_networks_config {}` if `master_ipv4_cidr_block` isn't empty.

**Comment by clebio** [comment]
Just to clarify, having an empty block like `master_authorized_networks_config {} ` is not ideal, since then we are back to the conditional resource counting shenanigans that I mentioned earlier. If I could specify that block completely in either case (when `enable_private_nodes` is either true or false), that works, but having to do 

```master_authorized_networks_config {}```
In one case and 
```
  master_authorized_networks_config {
    cidr_blocks {
      cidr_block   = "${var.ingress_cidr}"
    }
  }
```
in the other case is not a great work around.

I don't know without testing again (and can't tell from the docs) whether providing the latter version in *both* cases is possible. I appreciate your help on this, in the meantime!

**Comment by clebio** [comment]
Ok, using 
```
  master_authorized_networks_config {
    cidr_blocks {
      cidr_block   = "127.0.0.1/32"
    }
  }
``` 
seems to work fine for both values of `enable_private_nodes`. Thanks!
