### ISSUE TITLE
google_compute_url_map is not working when we use interpolation

### ISSUE THREAD

**Issue by selatamil** [terraform-providers/terraform-provider-google#3261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)
google_compute_url_map

### Terraform Configuration Files

path_matcher = [ {
    name            = "allpaths"
    default_service = "${module.lb.backend_services[0]}"
     path_rule = [ {
      paths   = ["/login"]
      service = "${module.lb.backend_services[0]}"
    }
   ]

  } ]

### Panic Output
I'm getting error while creating google_compute_url_map as below

Error: module.lb.google_compute_url_map.default: "path_matcher.0.default_service": required field is not set
Error: module.lb.google_compute_url_map.default: "path_matcher.0.name": required field is not set

### Expected Behavior

 below output block iis giving getting uri "https://www.googleapis.com/compute/v1/projects/id/global/backendServices/lb-backend-0" properly

output "backend" {
  value = "${module.lb.backend_services[0]}"
 }

### Actual Behavior

While applying below with manually feeded dervice uri it completes without any issues, but when I use  service = "${module.lb.backend_services[0]}", it's giving the error mentioned as panic output section
  
  
path_matcher = [ {
    name            = "allpaths"
    default_service = "https://www.googleapis.com/compute/v1/projects/id/global/backendServices/lb-backend-0"
     path_rule = [ {
      paths   = ["/login"]
      service = "https://www.googleapis.com/compute/v1/projects/id/global/backendServices/lb-backend-0"
    }
   ]

  } ]

  My module looks like:

resource "google_compute_url_map" "default" {
  project         = "${var.project_id}"
  name          = "${var.name}-url-map"
  default_service = "${google_compute_backend_service.default.0.self_link}"
  host_rule       = "${var.host_rule}"
  path_matcher    = ["${var.path_matcher}"]
}

variable "host_rule" {
  type        = "list"
  default     = []
}

variable "path_matcher" {
  type        = "map"
  default     = {}
}

**Comment by Chupaka** [comment]
Shouldn't the value be something like `"${module.lb.backend_services.*.self_link[0]}"`?

**Comment by selatamil** [comment]
@Chupaka  My module output is defined as below, so using "${module.lb.backend_services.*.self_link[0]}" in configuration will fail

output "backend_services" {
  value       = "${google_compute_backend_service.default.*.self_link}"
}

**Comment by selatamil** [comment]
@Chupaka  Any update please???

**Comment by emilymye** [comment]
@selatamil sorry for the delay. It is a little hard to debug without more information so it would be super helpful if you could provide
- Debug logs (run with TF_LOG=DEBUG)
- The exact modules or output you are getting from the various modules (i.e. `module.lb`)
