### ISSUE TITLE
Failed to parse key file ssh: unsupported key type "PRIVATE KEY"

### ISSUE THREAD

**Issue by zffocussss** [terraform-providers/terraform-provider-google#3263]
Hi there:
            I am using terrform to manage my resources on GCP.when creating vm instances ,and connection using private_key,it shows error
Failed to parse key file ssh: unsupported key type "PRIVATE KEY"

configuration block

 connection {
      agent = true
      type = "ssh"
      user = "username"
      private_key = "${file("~/.ssh/google_compute_engine2")}"
    }

terraform -v
Terraform v0.11.11
+ provider.google v1.20.0
+ provider.tls v1.2.0

**Comment by zffocussss** [comment]
I got this private key from Compute Engine default service account of GCP.

**Comment by emilymye** [comment]
@zffocussss I'm not sure how helpful I can be since this error is being returned by the Terraform core resource for `connection`. It looks like your private SSH key is invalid - may I ask how you are generating it? i.e did you use  ssh-keygen, gcloud, download it from the console? What steps did you take specifically?

It looks like it's at least trying to be a valid pkcs8 PEM ssh key. If it's not a error with the key format, I'm not sure why Terraform is returning this error and you might have to file an error against Terraform proper.

**Comment by zffocussss** [comment]
> @zffocussss I'm not sure how helpful I can be since this error is being returned by the Terraform core resource for `connection`. It looks like your private SSH key is invalid - may I ask how you are generating it? i.e did you use ssh-keygen, gcloud, download it from the console? What steps did you take specifically?
> 
> It looks like it's at least trying to be a valid pkcs8 PEM ssh key. If it's not a error with the key format, I'm not sure why Terraform is returning this error and you might have to file an error against Terraform proper.

I downloaded the private key from my service account.I extracted it from the json file.

**Comment by emilymye** [comment]
The service account JSON key, like the one you download from IAM? I don't think that's an SSH key in private key. Can you be more explicit about the way you are downloading the key? I.e. what page on the console, what buttons are you clicking.

Also, are you certain this is an valid ssh key you can use with your created VM?  i.e. can you just test this without Terraform by using that as your private .ssh key and attempting to login to the instance created. Did you use Terraform or gcloud to create/set the public ssh key on the VM instance in metadata?

**Comment by zffocussss** [comment]
> The service account JSON key, like the one you download from IAM? I don't think that's an SSH key in private key. Can you be more explicit about the way you are downloading the key? I.e. what page on the console, what buttons are you clicking.
> 
> Also, are you certain this is an valid ssh key you can use with your created VM? i.e. can you just test this without Terraform by using that as your private .ssh key and attempting to login to the instance created. Did you use Terraform or gcloud to create/set the public ssh key on the VM instance in metadata?

Hi emily.thanks finally,I set my local public key at ssh key in page "metadata",it works now.the private key from the service account json file should not be able to connect instances.
