### ISSUE TITLE
google_cloudfunctions_function resource does not allow underscores in `name`

### ISSUE THREAD

**Issue by tataranovich** [terraform-providers/terraform-provider-google#3264]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.11
+ provider.google v2.2.0

Your version of Terraform is out of date! The latest version
is 0.11.13. You can update by downloading from www.terraform.io/downloads.html
```

### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files

```tf
provider "google" {
  version = "~> 2.2"
  project = "${var.gcp_project}"
  region  = "${var.gcp_region}"
}

variable "gcp_project" {}

variable "gcp_region" {}

resource "google_cloudfunctions_function" "test_function" {
  name = "test_function"
}
```

### Expected Behavior

Should be created GCP CloudFunction with name `test_function`.

### Actual Behavior

Terraform fail to validate config
```
Error: google_cloudfunctions_function.test_function: "name" can only contain letters, numbers and hyphens
```

### Steps to Reproduce

1. `terraform validate`

### References

According to Google [docs](https://cloud.google.com/functions/docs/deploying/filesystem#deploy_using_the_gcloud_tool) function name name can only contain letters, numbers, underscores, and hyphens.

**Comment by emilymye** [comment]
Closing as fixed
