### ISSUE TITLE
google_storage_bucket_object content won-t display diff anymore

### ISSUE THREAD

**Issue by pgrangelgo** [terraform-providers/terraform-provider-google#3274]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
#> terraform -version
Terraform v0.11.13
+ provider.google v2.2.0
+ provider.google-beta v2.2.0
```

### Affected Resource(s)

* google_storage_bucket_object

### Expected Behavior

When changing the content of a google_storage_bucket_object, terraform should display the diff between previous content and the new content it wants to change. 

### Actual Behavior

Content is considered sensitive and nothing is displayed. No way to figure out what we are about to change.

This is related to this merge-request: https://github.com/GoogleCloudPlatform/magic-modules/pull/1470

### Steps to Reproduce

Change the content of a google_storage_bucket_object and apply terraform.

### References

https://github.com/GoogleCloudPlatform/magic-modules/pull/1470

https://github.com/terraform-providers/terraform-provider-google/commit/a3f794685eb152f5e17d42e404dc41d349dbbef2

**Comment by emilymye** [comment]
You can define an output for your bucket to display the raw content in the bucket. We can try to document this better on our end, but does this work for your use case? Or are you looking for something else?

There is more context in the comments of https://github.com/GoogleCloudPlatform/magic-modules/pull/1470 for why we went with sensitive `content` instead of having a separate `sensitive_content` field.

**Comment by pgrangelgo** [comment]
Hi @emilymye and thank you for answering so fast.

I did read https://github.com/GoogleCloudPlatform/magic-modules/pull/1470 but did not find any explanation of why it has been changed that way, except a comment from @rileykarson suggesting to do so.

I red the suggestion about adding an output to display the content of the bucket.

When I run `terraform plan` I need to see the difference between what is currently in the bucket and what terraform is about to put in the bucket. This was straightforward with terraform-provider-google 2.1.0 but is not displayed anymore with 2.2.0 due to this _sensitive_ parameter.

I am not that fluent with terraform output so I am still looking but I did not find a way, using _output_, to make `terraform plan` display the difference between what is currently in the bucket and what it will put in the bucket after that.

I came accross https://github.com/hashicorp/terraform/issues/18472 but it is open for quite a long time so I doubt it can help me.

**Comment by emilymye** [comment]
You can use `terraform output` to show the before state, and you have the output state from your config. The diff in `terraform plan` isn't necessarily the most straightforward diff in any case, so I guess I'm not sure why exactly this diff needs to show on terraform plan.

**Comment by pgrangelgo** [comment]
When we prepare for a change, we run a terraform plan and generate a plan file. This way, we ensure that what we will apply is the exact changes planned at the time of the plan.

I understand the workaround you are suggesting but this would force us to split the plan phase in two steps: first implement custom code to display the diff of every content we are about to change (which is not that trivial actually); second run plan and store the plan file.

This is *really* inferior to what we had with version 2.1.0 of google provider :cry:

**Comment by emilymye** [comment]
It's unlikely that we'll switch the behavior back to what it was, since many more users were interested in having sensitive contents. We probably won't have time to work on an alternative that works both for specifically making plan diffs nice with only a terraform plan and allow for sensitive content right now.

**Comment by saez0pub** [comment]
Hello,

I'm one of the not many more users not interrested of sensitive contents and It would have be more tolerant to have an optionnal parameter.
