### ISSUE TITLE
unable to overwrite externally changed instance metadata due to cached fingerprint

### ISSUE THREAD

**Issue by webervin** [terraform-providers/terraform-provider-google#3275]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

15:37 $ terraform -v
Terraform v0.11.13
+ provider.google v2.0.0

### Affected Resource(s)

google_compute_instance.ca_server

### Terraform Configuration Files

```tf
resource "google_compute_instance" "default" {
  name = "test"
  machine_type = "n1-standard-1"
  zone = "us-central1-a"


  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }

  network_interface {
    subnetwork = "${var.sub_network_name}"
  }
}
```

### Expected Behavior

Terraform is able to overwrite instance metadata that was changed externally

### Actual Behavior

```
* google_compute_instance.default: Error updating metadata: googleapi: Error 412: Supplied fingerprint does not match current metadata fingerprint., conditionNotMet
```

### Steps to Reproduce

- terraform apply
- use google cloud console, edit instance and enable access to serial ports
- actually connect to instance serial port  (to generate and upload your temporary key to instance) 
- terraform apply (this detects metadata change and suggests to remove data changed externally. 

```

  ~ google_compute_instance.default
      metadata.%:                  "2" => "0"
      metadata.serial-port-enable: "true" => ""
      metadata.ssh-keys:           "FILTERED:ssh-rsa .......google-ssh {\"userName\":\"FILTERED\",\"expireOn\":\"2019-03-19T13:57:59+0000\"}\nFILTERED:ecdsa-sha2-nistp256 .........= google-ssh {\"userName\":\"FILTERED\",\"expireOn\":\"2019-03-19T13:57:56+0000\"}\n" => ""


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_compute_instance.default: Modifying... (ID: test)
  metadata.%:                  "2" => "0"
  metadata.serial-port-enable: "true" => ""
  metadata.ssh-keys:           "FILTERED:ssh-rsa ....... google-ssh {\"userName\":\"FILTERED\",\"expireOn\":\"2019-03-19T13:57:59+0000\"}\nFILTERED:ecdsa-sha2-nistp256 ...........= google-ssh {\"userName\":\"FILTERED\",\"expireOn\":\"2019-03-19T13:57:56+0000\"}\n" => ""
Error: Error applying plan:

1 error(s) occurred:

* google_compute_instance.default: 1 error(s) occurred:

* google_compute_instance.default: Error updating metadata: googleapi: Error 412: Supplied fingerprint does not match current metadata fingerprint., conditionNotMet

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```
### Important Factoids
OS Login  is not enabled on project / instance, so keys are managed through metadata.

### References

* #0000

**Comment by emilymye** [comment]
Can you still reproduce this error? I originally had reproduced it (somewhat alarming, the tentative fix PR i have open is setting a field that should already be set to that value) but now it's working fine without my fix? I'm wondering if it's related to eventual consistency with the metadata server. If you do get an error, can you try applying and then reapplying after a break?

**Comment by rileykarson** [comment]
One thing I've found is that I believe the metadata fingerprint is shared at the _project_ level by all instances and the project, and not just the individual instance level. So regardless of whether we've read the correct value or not, we can encounter race conditions forcing us to retry several times if multiple metadatas are edited in parallel.

**Comment by webervin** [comment]
still happens, was reproduced using both google and google-beta provider

```
10:12 $ terraform -v 
Terraform v0.11.13
+ provider.google v2.0.0
+ provider.google-beta v2.2.0
```

possible contributing factor: I use  bucket to store state:

```
terraform {
  backend "gcs" {
    bucket = "unique-name-of-bucket-with-rw-access"
    prefix = "terraform/state"
  }
}

```

**Comment by marcusramberg** [comment]
I've also reproduced this today.
```
$ terraform -v
Terraform v0.11.13
+ provider.google v2.3.0
````
