### ISSUE TITLE
Missing Set on access attribute in google_bigquery_dataset

### ISSUE THREAD

**Issue by ondrejklucka** [terraform-providers/terraform-provider-google#3276]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We try to build dynamic `access` inline blocks for `google_bigquery_dataset` resource. 

```tf
resource "google_bigquery_dataset" "dataset" {
  ...
  access = {
    role = "OWNER"
    special_group = "projectOwners"
  }

  access = {
    role = "READER"
    group_by_email = "xyz@abc.com"
  }
  ...
}
```

We expect Terraform's `for_each` feature to resolve this issue, but it won't be out until later releases of 0.12, therefore we need to solve it differently in the meantime. Our hope was to assign an array of maps directly to access argument:

```tf
resource "google_bigquery_dataset" "dataset" {
  ...
  access = [
    {
      role = "OWNER"
      special_group = "projectOwners"
    },
    {
      role = "READER"
      group_by_email = "xyz@abc.com"
    }
  ]
}
```

As per documentation (https://www.terraform.io/docs/providers/google/r/bigquery_dataset.html):

```
access - (Optional) An array of objects that define dataset access for one or more entities. Structure is documented below.
```

However, the resource definition above results in:

```sh
Error: variable "access" should be type map, got list
```

We dug in the `resource_bigquery_dataset.go` code a bit and it looks like **access argument is missing Set method** on L184 - https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_bigquery_dataset.go#L184.

Admittedly a different provider, but such assignment works fine for `aws_elb` resource, according to https://github.com/hashicorp/terraform/issues/14037#issuecomment-361202716. The only difference between `listeners` in `aws_elb` and `access` in `google_bigquery_dataset` is the Set method.

**Would it be possible to add Set method to `access` attribute of `google_bigquery_dataset`?**

### New or Affected Resource(s)

* google_bigquery_dataset

### Potential Terraform Configuration

```tf
resource "google_bigquery_dataset" "dataset" {
  ...
  access = [
    {
      role = "OWNER"
      special_group = "projectOwners"
    },
    {
      role = "READER"
      group_by_email = "xyz@abc.com"
    }
  ]
}
```

### References
No known issues or pull requests.

**Comment by emilymye** [comment]
I don't believe the issue is actually that TypeSet is missing, since if schema.Set is nil, it just defaults to a HashSchema function which isn't functionally different than how the aws_elb [Set function](https://github.com/terraform-providers/terraform-provider-aws/blob/eb7fd230dc6d1a0f9b0cc771d1d343487fc5b604/aws/resource_aws_elb.go#L821-L832) works. 

Also, I just tried the following two configs and they both created fine:
```
// Inlined
resource "google_bigquery_dataset" "default" {
  dataset_id                  = "foo"
  friendly_name               = "test"
  description                 = "This is a test description"
  location                    = "US"
  default_table_expiration_ms = 3600000

  labels = {
    env = "default"
  }

 access = [
    {
      role   = "READER"
      special_group = "allAuthenticatedUsers"
    },
    {
      role = "OWNER",
      user_by_email = "myuser@myproj.iam.gserviceaccount.com",
    }
  ]
}
```
and 

```
// Using Variable
resource "google_bigquery_dataset" "default" {
  dataset_id                  = "foo"
  friendly_name               = "test"
  description                 = "This is a test description"
  location                    = "US"
  default_table_expiration_ms = 3600000

  labels = {
    env = "default"
  }

  access = "${var.access_blocks}"
}

variable "access_blocks" {
  type = "list"
  default = [
    {
      role   = "READER"
      special_group = "allAuthenticatedUsers"
    },
    {
      role = "OWNER",
      user_by_email = "myuser@myproject.iam.gserviceaccount.com",
    }
  ]
}
```

I assume this is something specific to passing the list in as a var - what exactly is your config for the list variable? i.e. did you set a `type`/`default` on the variable.

Lastly, and possible very important: even if you end up using this pattern, it's very much not what the Terraform core/HCL creators intended to be valid behavior (as described in the AWS issue you linked) and is very likely to change or be rejected by 0.12 so I wouldn't rely on it. I'm guessing it's only a work around until you get `foreach`, but just FYI.

**Comment by ondrejklucka** [comment]
Thank you, Emily. 
It works as you described. We'll be using this approach till 0.12.
