### ISSUE TITLE
Can we get a new release 0.1.3?

### ISSUE THREAD

**Issue by nodesocket** [terraform-providers/terraform-provider-google#328]
Terraform **v0.10.1** was just released. Hoping to get some patches and fixes (https://github.com/terraform-providers/terraform-provider-google/issues/292) pushed.

**Comment by danawillow** [comment]
Just released! We were planning on one for this week anyway :)

**Comment by nodesocket** [comment]
Thanks @danawillow

**Comment by nodesocket** [comment]
@danawillow did this update? It is not clear.

```
iMac ➜  terraform git:(master) terraform init
Downloading modules...
Get: file:///Users/justin/Sites/elastic-byte-ops/terraform/modules/node

Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.google: version = "~> 0.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by danawillow** [comment]
I don't work on core so I don't have a good sense of the messages- feel free to file an issue there that it should say what got downloaded. In the meantime, I would just try adding something that's new in the new version and seeing if `terraform plan` complains :)

**Comment by nodesocket** [comment]
What is the expected behavior? I was under the impression that `terraform init` would fetch new version of providers.

**Comment by apparentlymart** [comment]
Hi @nodesocket!

If you already had a version of the provider installed, `terraform init` won't upgrade it unless you specifically run `terraform init -upgrade` to indicate that you want to potentially replace your existing version. `init` is conservative by default because `init` is used for a number of different purposes, such as switching backends or installing modules, and we thought it would be suprising/annoying if it were impossible to do those actions without implicitly upgrading installed providers.

**Comment by nodesocket** [comment]
@apparentlymart yah I just noticed in fact, I did not upgrade providers after all:

```
MacBook-Pro ➜  darwin_amd64 git:(master) ✗ ll
total 65232
-rwxr-xr-x@ 1 justin  staff    82B Aug 17 16:29 lock.json
-rwxr-xr-x@ 1 justin  staff    32M Aug  3 16:43 terraform-provider-google_v0.1.2_x4
```

Running `terraform init -upgrade` worked though. Perhaps adding each plugin and version to `terraform version` would be helpful.

```
MacBook-Pro ➜  terraform git:(master) ✗ terraform --version
Terraform v0.10.2
    terraform-provider-google v0.1.2

````
