### ISSUE TITLE
Change default value of is_live is not set if lifecycle_rule.condition is set in google_storage_bucket

### ISSUE THREAD

**Issue by sho-abe** [terraform-providers/terraform-provider-google#3286]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, setting `lifecycle_rule` property without `lifecycle_rule.condition.is_live` of `google_storage_bucket` implicitly sets `is_live = false`.
If `is_live = false` is set, only archived objects are effected to lifecycle_rule, so live objects have no effect. However, in the Storage API, when is_live is not set, it affects both live object and archive object. 
When setting up with Terraform, I think that terraform should not set is_live neither true or false unless the user explicitly declares is_live. 

### New or Affected Resource(s)

* google_storage_bucket

### Potential Terraform Configuration

```tf
resource "google_storage_bucket" "test-is-live" {
  project       = "my-project-id"
  name          = "my-project-id-is-live"
  storage_class = "REGIONAL"
  location      = "us-central1"

  lifecycle_rule {
    action {
      type = "Delete"
    }

    condition {
      age = 10
    }
  }
}

```

### References

* https://www.terraform.io/docs/providers/google/r/storage_bucket.html
* https://cloud.google.com/storage/docs/json_api/v1/buckets

**Comment by emilymye** [comment]
Ah, this is an issue with a) storage API using a boolean to represent a three-state value and b)  how booleans are converted from config to Go to google go client Go. Rather than deal with some really bad conversion logic, we were thinking of deprecating `is_live` in favor of a "with_state" enum with  values `"", "LIVE", "ARCHIVED"`. We'll go ahead and put that in but please let us know if you have any questions.

**Comment by sho-abe** [comment]
@emilymye Thank you! This enhancement seems to be effective from version `2.4.0`.

**Comment by pdecat** [comment]
This change apparently did not make it to the 2.4.0 release notes.
