### ISSUE TITLE
Improve Test Sweepers

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#3288]
Sweepers don't cover a lot of newer products, and we have a lot of leftover ones in existing ones like networking. We should improve them so we can be more confident in our tests.

**Comment by danawillow** [comment]
Putting this as XL since it touches a bunch of resources. @c2thorn, if you want to divide this into smaller issues once you've done the first one and have a better sense of the scope, feel free!

**Comment by rileykarson** [comment]
Keeping open for @c2thorn to split this into a few smaller issues
