### ISSUE TITLE
Error when importing disable GCB trigger

### ISSUE THREAD

**Issue by rysteboe** [terraform-providers/terraform-provider-google#3299]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.13
+ provider.google v2.2.0

### Affected Resource(s)

* google_cloudbuild_trigger

### Terraform Configuration Files

```tf
provider "google" {
  project = "kaggle-cicd"
  region  = "us-east1"
  zone    = "us-east1-d"
}

terraform {
  backend "gcs" {
    project = "kaggle-cicd"
    region  = "us"
    bucket  = "kaggle-terraform-backend"
    prefix  = "kaggleazure/cloud-builds"
  }
}

resource "google_cloudbuild_trigger" "databundle-worker-gcp" {
  project     = "kaggle-cicd"
  description = "gcp-databundle-worker"
  disabled    = "true"
  filename    = "Kaggle.Services.Databundle.Worker/cicd/cloudbuild.yaml"

  trigger_template {
    project_id  = "kaggle-cicd"
    repo_name = "github-kaggle-kaggleazure"
    branch_name = "^ci$"
  }

  included_files = [
    "Kaggle.Services.Datasets/**",
    "Kaggle.Services.Databundle/**",
    "Kaggle.Services.Databundle.Worker/**"
  ]
}
```

### Debug Output

Not the full output because I was having trouble getting xclip working when sshing with the Chrome extension.  Let me know if you need the full output and I'll work that out.

### Expected Behavior

Trigger should have been imported to the GCS backend.

### Actual Behavior

Not imported, got an error instead.

### Steps to Reproduce

Create a GCB trigger, disable it, and then try to import it.

### Important Factoids

Doing this with my own user credentials.  I have owner on the project and have successfully imported other triggers.

### References

* #0000

**Comment by emilymye** [comment]
What was the error you got?

**Comment by rysteboe** [comment]
Sorry, lost track of this over the weekend.  Can't believe I forgot the actual output.  

```
google_cloudbuild_trigger.search-proxy: Importing from ID "1d6c22de-a7cc-4030-9328-501ea013aa20"...
google_cloudbuild_trigger.search-proxy: Import complete!
  Imported google_cloudbuild_trigger (ID: kaggle-cicd/1d6c22de-a7cc-4030-9328-501ea013aa20)
google_cloudbuild_trigger.search-proxy: Refreshing state... (ID: kaggle-cicd/1d6c22de-a7cc-4030-9328-501ea013aa20)

Error: google_cloudbuild_trigger.search-proxy (import id: 1d6c22de-a7cc-4030-9328-501ea013aa20): 1 error(s) occurred:

* import google_cloudbuild_trigger.search-proxy result: kaggle-cicd/1d6c22de-a7cc-4030-9328-501ea013aa20: google_cloudbuild_trigger.search-proxy: Error reading Trigger: disabled: '' expected type 'string', got unconvertible type 'bool'
```
