### ISSUE TITLE
Support for managing Google Cloud Firestore indexes

### ISSUE THREAD

**Issue by thepooley** [terraform-providers/terraform-provider-google#3305]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

A Google Cloud customer wants to manage their Firestore (native) DB indexes declaratively.  Previously they accomplished this with Datastore using yaml config files using the CLI; however, the (beta) Firestore CLI doesn't seem to support this (while the Firestore API does.)  Is it possible to add support for managing Firestore indexes via Terraform?

### New or Affected Resource(s)

Doesn't appear to be a Firestore resource yet.

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

https://cloud.google.com/firestore/docs/concepts/index-overview

* #0000

**Comment by ncjones** [comment]
We're using Cloud Datastore and have the same need. I'm not sure if it counts as a separate issue as these products are pretty similar.

**Comment by danawillow** [comment]
Added in https://github.com/GoogleCloudPlatform/magic-modules/pull/1682
