### ISSUE TITLE
Automatic Credentails for a Windows VM

### ISSUE THREAD

**Issue by KbLev** [terraform-providers/terraform-provider-google#3308]
### Terraform Version

Terraform v0.11.7
### Affected Resource(s)

Please list the resources as a list, for example:

    * google_compute_instance

Trying to create a vanilla Windows Server 2016 and a set of credentials with it but can't find a working sample on the internet. I understand I should be poking around the metadata parameters.

Tried a workaround using **gcloud** but doesn't work very well because once the credentials are created Terraform will try to destroy the machine as it doesn't match the tfstate.

**Comment by Chupaka** [comment]
Any details?

**Comment by emilymye** [comment]
What type of credentials you are trying to create/use - are these GCP credentials for terraform to use, credentials you want to set using terraform?

**Comment by KbLev** [comment]
The local admin credentials on the VM that you can use to RDP/WinRM.

**Comment by danawillow** [comment]
Closing as duplicate, see https://github.com/terraform-providers/terraform-provider-google/issues/1472 and https://github.com/terraform-providers/terraform-provider-google/issues/1578
