### ISSUE TITLE
Update google_container_cluster with ETCD encryption and verticalPodAutoscaling

### ISSUE THREAD

**Issue by mrjfox** [terraform-providers/terraform-provider-google#3315]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please update google_container_cluster to support the following GKE features

```
"databaseEncryption": {
  "state": "ENCRYPTED"
},
"verticalPodAutoscaling": {
  "enabled": true
}
```
### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```
resource "google_container_cluster" "gke-cluster" {
  database_encryption {
    encrypted = true
    kms-id  = "kms-id-bla"
  }
 vertical_pod_autoscaling = true
}
```

### References

Api Reference
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.zones.clusters

**Comment by danawillow** [comment]
To make my life a bit easier, I'm going to close this out as finished (yay!) and leave https://github.com/terraform-providers/terraform-provider-google/issues/3200 as the vertical pod autoscaling FR
