### ISSUE TITLE
Region support in google_compute_autoscaler

### ISSUE THREAD

**Issue by timurshevekhman** [terraform-providers/terraform-provider-google#332]
GCP supports setting autoscaler to operate on either region or zone. Currently, google_compute_autoscaler only supports zone arguement. Adding region argument would allow us to properly use Regional Instance Groups Manager #45

**Comment by mattes** [comment]
dup of https://github.com/terraform-providers/terraform-provider-google/issues/45

**Comment by rosbo** [comment]
Closing in favor of #45
