### ISSUE TITLE
Misleading example in google_service_acount docs

### ISSUE THREAD

**Issue by conorgil** [terraform-providers/terraform-provider-google#3329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
The example in the documentation for the `google_service_account` resource is misleading. It says:

> This snippet creates a service account, then gives it objectViewer permission in a project.

which sounds like a useful example of how to create a Service Account (SA) and then actually do something with it, but the example doesn't actually have anything to do with permissions:

```
resource "google_service_account" "object_viewer" {
  account_id   = "object-viewer"
  display_name = "Object viewer"
}
```

The example is misleading because the SA created has a name of `object-viewer`, but the example doesn't actually show creating any resources related to permissions. Simply naming the SA in a certain way doesn't automatically give it permissions. I found this very confusing while getting up to speed with terraform in GCP 

It looks like commit https://github.com/terraform-providers/terraform-provider-google/commit/6f742d2aaaecff49fecc1fc46dc87f7b759f68b6#diff-e3310653c30c4ff89f4cb148a343b625 removed the other useful resources in the example and accidentally forgot to update the example description.

I think the example description should remain unchanged and we should add back the deleted resources to make the example more realistic and useful.

There has been some discussion about the scope of examples in https://github.com/terraform-providers/terraform-provider-google/pull/3239, but this is another example of where I think the examples can be improved to be more useful/actionable.

Thoughts?

### New or Affected Resource(s)

* [google_service_account](https://www.terraform.io/docs/providers/google/r/google_service_account.html#example-usage)

**Comment by venkykuberan** [comment]
@conorgil example has been fixed for [google_service_account](https://www.terraform.io/docs/providers/google/r/google_service_account.html), hence closing the issue.
