### ISSUE TITLE
google_dataflow_job "id" attribute missing from documentation

### ISSUE THREAD

**Issue by Tfmenard** [terraform-providers/terraform-provider-google#3334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
The dataflow job "id" attribute is missing from the official documentation.
However, the attribute is accessible 
See official documentation [here ](https://www.terraform.io/docs/providers/google/r/dataflow_job.html) and example successful usage below.

### Affected Resource(s)

* google_dataflow_job

### Terraform Configuration Files

```tf
# outputs.tf
output "df_job_id" {
  description = "The unique Id of the newly created Dataflow job"
  value = "${google_dataflow_job.dataflow_job.id}"
}
```

**Comment by rileykarson** [comment]
Hey @Tfmenard!

We explicitly don't document the `id` value so that we can change it at will. On most resources this is a useless value, or a documented field provides the same information. Is that not the case for this resource?

**Comment by Tfmenard** [comment]
Well in my case, having the job's id is useful for checking a particular job's state after a google_dataflow_job resource is deployed. So it's useful for monitoring jobs.

I understand your motivations in not documenting the `id` attribute, but I think it would be very inconvenient for a user if you were to change the `id` value to not be the job's id. Since for this resource there are no other documented field that refers to the job's id, the user would loose the capability of retrieving the job's id.
So would it be possible to add a new documented field for the job's id ?

**Comment by venkykuberan** [comment]
This issue is outdated as we made a decision to add `id` attribute to all the resources and data sources and work is in progress. Hence closing this issue.
