### ISSUE TITLE
Spanner database with DDL recreated after import

### ISSUE THREAD

**Issue by rolandkool** [terraform-providers/terraform-provider-google#3335]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Provider 2.1

### Affected Resource(s)

* google_spanner_database

### Expected Behavior

Terraform should recreate the state before it got lost, including the DDL information.

### Actual Behavior

After an import, terraform detects a change in DDL and recreates your database.

### Steps to Reproduce

1. Take the example spanner database from https://www.terraform.io/docs/providers/google/r/spanner_database.html
2. Create the instance and database by doing an apply
3. Delete the terraform state file
4. Run an import
5. Run apply again

### References

* https://github.com/terraform-providers/terraform-provider-google/issues/2082

**Comment by Chupaka** [comment]
Looks like your attachment with the log is lost.

**Comment by rileykarson** [comment]
This is expected behaviour unfortunately; Terraform has no way of recovering what the `ddl`/`extraStatements` provided at creation time were, so you'll see a diff. This is an unintuitive interaction, and isn't a great behaviour- but these kind of creation-only fields aren't able to be represented well by the Terraform provider SDK.
