### ISSUE TITLE
Google SQL private IP -> sql_database_instance example documentation doesn't work

### ISSUE THREAD

**Issue by primehaxor** [terraform-providers/terraform-provider-google#3342]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.13

### Affected Resource(s)

* provider.google v2.3.0

### Terraform Configuration Files

```tf
resource "google_compute_network" "private_network" {
    name       = "private-network"
}

resource "google_compute_global_address" "private_ip_address" {
    name          = "private-ip-address"
    purpose       = "VPC_PEERING"
    address_type = "INTERNAL"
    prefix_length = 16
    network       = "${google_compute_network.private_network.self_link}"
}

resource "google_service_networking_connection" "private_vpc_connection" {
    network       = "${google_compute_network.private_network.self_link}"
    service       = "servicenetworking.googleapis.com"
    reserved_peering_ranges = ["${google_compute_global_address.private_ip_address.name}"]
}
```

### Expected Behavior

Setup the private network and PEER_VPC to attach into SQL Instance, I've also tried to use the google-beta provider

### Actual Behavior
```
Error: google_compute_global_address.private_ip_address: : invalid or unknown key: network
Error: google_compute_global_address.private_ip_address: : invalid or unknown key: prefix_length
Error: google_compute_global_address.private_ip_address: : invalid or unknown key: purpose
Error: google_service_networking_connection.private_vpc_connection: Provider doesn't support resource: google_service_networking_connection
```

### Steps to Reproduce
1. Use the configuration below
```
resource "google_compute_network" "private_network" {
    name       = "private-network"
}

resource "google_compute_global_address" "private_ip_address" {
    name          = "private-ip-address"
    purpose       = "VPC_PEERING"
    address_type = "INTERNAL"
    prefix_length = 16
    network       = "${google_compute_network.private_network.self_link}"
}

resource "google_service_networking_connection" "private_vpc_connection" {
    network       = "${google_compute_network.private_network.self_link}"
    service       = "servicenetworking.googleapis.com"
    reserved_peering_ranges = ["${google_compute_global_address.private_ip_address.name}"]
}
```

2. then `terraform plan`

### References
https://www.terraform.io/docs/providers/google/r/sql_database_instance.html

* #0000

**Comment by rileykarson** [comment]
When using the `google-beta` provider did you explicitly set `provider = "google-beta"` on each resource? Per https://www.terraform.io/docs/providers/google/provider_versions.html#using-the-google-beta-provider, it's necessary unfortunately.

**Comment by primehaxor** [comment]
No, I've just replaced in the provider definition in providers.tf

**Comment by rileykarson** [comment]
Ah! As mentioned in those docs, you'll need to explicitly specify the provider. Unfortunately, Terraform implicitly uses the `google` provider if you don't, even with only `google-beta` defined.

**Comment by XANi** [comment]
@rileykarson would be nice if examples actually stated that they need the beta provider, for example [this one](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#private-ip-instance) will flat out not work and there is no indication that the beta provider needs to be selected for it

**Comment by rileykarson** [comment]
Yep! That's what https://github.com/GoogleCloudPlatform/magic-modules/pull/1611/files fixes. Some examples are also already live that do that eg; https://www.terraform.io/docs/providers/google/r/compute_autoscaler.html#example-usage-autoscaler-beta
