### ISSUE TITLE
Terraform doesn't wait till the end of dataflow job drain 

### ISSUE THREAD

**Issue by mykolakovnir** [terraform-providers/terraform-provider-google#3355]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.13
+ provider.google v2.3.0
+ provider.random v2.1.0

### Affected Resource(s)

* google_dataflow_job

### Terraform Configuration Files

```tf
variable "gcp_project_name" {
}

variable "region" {
  default = "us-west1"
}

provider "google" {
  project = "${var.gcp_project_name}"
  region  = "${var.region}"
}

data "google_compute_zones" "available" {}

resource "random_id" "id" {
  byte_length = 8
}

resource "google_storage_bucket" "big_data_job_gcs" {
  project       = "${var.gcp_project_name}"
  name          = "gcs-${random_id.id.hex}"
  force_destroy = true
}

resource "google_pubsub_topic" "big_data_job_input_topic" {
  name    = "input-topic-${random_id.id.hex}"
  project = "${var.gcp_project_name}"
}

resource "google_dataflow_job" "big_data_job" {
  name              = "dataflow-job"
  project           = "${var.gcp_project_name}"
  zone              = "${data.google_compute_zones.available.names[0]}"
  template_gcs_path = "gs://dataflow-templates/2019-03-15-00/Cloud_PubSub_to_GCS_Text"
  temp_gcs_location = "${google_storage_bucket.big_data_job_gcs.url}/temp/"
  on_delete         = "drain"

  parameters = {
    inputTopic           = "${google_pubsub_topic.big_data_job_input_topic.id}"
    outputDirectory      = "${google_storage_bucket.big_data_job_gcs.url}/output/"
    outputFilenamePrefix = "prefix-"
    outputFilenameSuffix = ".txt"
  }
}
```

### Expected Behavior

According to current documentation terraform should wait till the end dataflow job drain. And current job should be successfully recreated in case of `terraform taint` and following `terraform apply`  

[Link to doc](https://www.terraform.io/docs/providers/google/r/dataflow_job.html#note-on-quot-destroy-quot-quot-apply-quot-)

### Actual Behavior

Terraform fails with an error
```
Error: Error applying plan:

1 error(s) occurred:

* google_dataflow_job.big_data_job: 1 error(s) occurred:

* google_dataflow_job.big_data_job: googleapi: Error 409: (aad1b1a43fdfac17): The workflow could not be created. Causes: (93f206e63a7a46bb): There is already an active job named dataflow-job. If you want to  submit a second job, try again by setting a different name., alreadyExists
```

### Steps to Reproduce

Use file above and run
1. `terraform apply`
2. `terraform taint google_dataflow_job.big_data_job`
3. `terraform apply`

**Comment by emilymye** [comment]
Huh! For some reason we have JOB_STATE_DRAINING and JOB_STATE_CANCELLING as terminal states when they probably shouldn't be. Testing a fix PR!

**Comment by mykolakovnir** [comment]
Thanks @emilymye !
