### ISSUE TITLE
Stackdriver Monitoring Custom Metric

### ISSUE THREAD

**Issue by ocervell** [terraform-providers/terraform-provider-google#3360]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Need a resource to create custom metrics through Stackdriver Monitoring API. 
API Documentation for custom metrics is available [here](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors/create).

### New or Affected Resource(s)

* `google_monitoring_metric_descriptor`

### Potential Terraform Configuration

```tf
resource "google_monitoring_metric_descriptor" {
  project_id="project_test_123"
  description="Daily sales records from all branch stores."
  display_name="daily sales"
  type="custom.googleapis.com/stores/daily_sales"
  metric_kind="GAUGE"
  value_type="DOUBLE"
  unit="{USD}"
  labels=[
    {
      key="store_id",
      value_type="STRING",
      description="The ID of the store."
    }
  ]
}
```

* #0000

**Comment by rileykarson** [comment]
Hey @ocervell! We weren't able to get this working up to our standards with Terraform due to issues with the underlying API, so we're not currently interested in adding this resource. That said, we'll leave this open to track interest in the feature.

**Comment by ocervell** [comment]
@rileykarson Could you expand a little on what issues in particular the underlying API has ? Is it the lack of an `update` method ?

**Comment by chrisst** [comment]
@ocervell IIRC there were a few issues with the underlying API that our code generator didn't handle well yet, such as lack of Operation objects for an async request and non standard HTTP codes. Additionally I got guidance from the API team that API descriptors should be automatically created for most scenarios and that custom metric descriptors should be exceptional. So at the time I chose to focus on getting alert policy and the other monitoring resources out over this one.

**Comment by rebelthor** [comment]
We're also interested in this since we want to have a full automated setup of our infrastructure, which also includes alerts. Since some metrics are only populated after everything is set up, we need to define these custom metrics prior to creating the alert policies, otherwise, it fails.

**Comment by agadelshin** [comment]
One year later I'd like to raise discussion again:

1. does stackdriver API still have this problems?
1. if it does, how can we motivate stackdriver team to fix it?

**Comment by tishen25** [comment]
Started working on this
