### ISSUE TITLE
Terraform Cannot Refresh State on Cloud SQL and Instance Template

### ISSUE THREAD

**Issue by jalseth** [terraform-providers/terraform-provider-google#3362]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.13
+ provider.google v2.3.0
+ provider.google-beta v2.3.0
+ provider.random v2.1.0
```

### Affected Resource(s)

* google_sql_database_instance
* google_compute_instance_template

### Terraform Configuration Files

For brevity in the issue, I have only included the configs for the two items throwing errors

compute.tf
```tf
resource "google_compute_autoscaler" "project_autoscaler" {
  name = "project-autoscaler"
  project = "${data.google_project.project.project_id}"
  zone = "${var.region}-a"
  target = "${google_compute_instance_group_manager.project_igm.self_link}"

  autoscaling_policy {
    max_replicas = 3
    min_replicas = 2
    cooldown_period = 120
    cpu_utilization {
      target = 0.5
    }
  }
}

resource "google_compute_instance_template" "base_instance_template" {
  name = "base-instance-template"
  machine_type = "${var.instance_size}"
  can_ip_forward = false
  project = "${data.google_project.project.project_id}"

  disk {
    source_image = "${data.google_compute_image.base_image.self_link}"
  }

  network_interface {
    subnetwork = "${google_compute_subnetwork.project_subnetwork.self_link}"
  }

  service_account {
    scopes = ["userinfo-email", "compute-ro", "storage-ro"]
  }
}

resource "google_compute_instance_group_manager" "project_igm" {
  name = "project-igm"
  project = "${data.google_project.project.project_id}"
  provider = "google-beta"
  base_instance_name = "project"

  version {
    instance_template = "${google_compute_instance_template.base_instance_template.self_link}"
    name = "primary"
  }

  auto_healing_policies {
    health_check = "${google_compute_https_health_check.project_health_check.self_link}"
    initial_delay_sec = 300
  }

  target_pools = ["${google_compute_target_pool.project_target_pool.self_link}"]
}

resource "google_compute_target_pool" "project_target_pool" {
  depends_on = ["google_project_services.project_services"]
  name = "project-target-pool"
  project = "${data.google_project.project.project_id}"
  region = "${var.region}"
}

data "google_compute_image" "base_image" {
  depends_on = ["google_project_services.project_services"]
  family = "ubuntu-minimal-1804-lts"
  project = "ubuntu-os-cloud"
}

resource "google_compute_https_health_check" "project_health_check" {
  depends_on = ["google_project_services.project_services"]
  name = "project-health-check"
  port = 443
  timeout_sec = 2
  check_interval_sec = 15
  project = "${data.google_project.project.project_id}"
}

resource "google_compute_project_metadata_item" "enable_oslogin" {
  project = "${data.google_project.project.project_id}"
  depends_on = ["google_project_services.project_services"]
  key = "enable-oslogin"
  value = "TRUE"
}

```

sql.tf
```tf
resource "google_sql_database_instance" "mysql" {
  depends_on = ["google_service_networking_connection.project_vpc_connection"]
  name = "project-mysql-master"
  database_version = "MYSQL_5_7"
  region = "${var.region}"
  project = "${data.google_project.project.project_id}"
  settings {
    tier = "${var.db_tier}"
    ip_configuration {
      ipv4_enabled = "false"
      private_network = "${google_compute_network.project_network.self_link}"
      require_ssl = "false"
    }
    maintenance_window {
      day = "${var.db_maintenance_day}"
      hour = "${var.db_maintenance_hour}"
      update_track = "stable"
    }
    backup_configuration {
      enabled = "true"
      binary_log_enabled = "true"
    }
  }
}

resource "random_string" "project_server_db_pass" {
  length = 32
  special = true
  upper = true
  lower = true
}

resource "google_sql_user" "project_server" {
  name = "project-server"
  instance = "${google_sql_database_instance.mysql.name}"
  host = "%"
  password = "${random_string.project_server_db_pass.result}"
  project = "${data.google_project.project.project_id}"
}

resource "google_sql_database" "project_server_db" {
  name = "project-server-db"
  instance = "${google_sql_database_instance.mysql.name}"
  project = "${data.google_project.project.project_id}"
}
```

### Debug Output

With `TF_LOG=TRACE` set: https://gist.githubusercontent.com/jalseth/7c833fda69aeed4da1a167d5c8aaf977/raw/ad11f74f1f5fa2c85cfd91d0194ce49d4c88466d/tf_plan_error_20190402.log

### Panic Output

N/A

### Expected Behavior

Able to refresh state with `terraform plan`.

### Actual Behavior

Terraform fails with error `google_sql_database_instance.mysql: unexpected EOF`. This does not happen on the initial creation of the resources in GCP, but on subsequent `plan` and `apply` commands.

### Steps to Reproduce

1. `terraform apply` (success)
2. `terraform plan`

### Important Factoids

Authenticating as user account that is the owner of the project.

### References

* Same error as in #1930

**Comment by rileykarson** [comment]
Would it be possible for you to attach debug-level logs? Judging from what I can see, there's an error reading the Terraform config / state before the provider sees it, but I can be more confident with the full output.

**Comment by jalseth** [comment]
Here you go. I do not have an SQL instance in this log as I disabled it for quicker testing, but the error still occurs with the instance template resource.

https://gist.github.com/jalseth/f47afc7ecdc7b740f45669cf8e77f77c

**Comment by jalseth** [comment]
Any update on this? It is prevent us from moving a project into production.

**Comment by rileykarson** [comment]
Sorry! I didn't see anything that indicates what's causing Terraform to fail out here, and taking another look now I still don't. The error we're getting is one we often get when _something else_ has failed.

**Comment by jalseth** [comment]
Did you attempt to repro the issue?

 If something else other than the Google provider is failing I need to know what specifically is failing so I can pursue that further.
