### ISSUE TITLE
Add time series per-group metric scaling to googler_compute_autoscaler

### ISSUE THREAD

**Issue by Dylnuge** [terraform-providers/terraform-provider-google#3365]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Metric based autoscaling on `google_compute_autoscalers` supports doing scaling based on a utilization target through the `target` and `type` fields (https://www.terraform.io/docs/providers/google/r/compute_autoscaler.html#metric). This appears to be a ["time series per instance" metric-based scaling rule](https://cloud.google.com/compute/docs/autoscaler/scaling-stackdriver-monitoring-metrics#per_instance_metrics). 

The autoscaler API also supports doing metric-based scaling on [groups of instances](https://cloud.google.com/compute/docs/autoscaler/scaling-stackdriver-monitoring-metrics#per_group_metrics), either using a utilization target or using a single instance assignment which spins up a new instance for every X units of the provided metric.

Adding support for these features in Terraform would be greatly appreciated. We're using single instance assignment scaling in particular to run clusters which react to Cloud Pub/Sub topics based on the number of unacknowledged messages in the subscription, spinning up more instances if the backlog grows and spinning down instances when the backlog is small or empty. This feature has been incredibly valuable for us and I'm sure there's other use cases.

### New or Affected Resource(s)

* `google_compute_autoscaler`

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_autoscaler" "autoscaler" {
  # Metric filter autoscaling is in beta
  provider = "google-beta"
  name = "autoscaler"
  zone = "${var.zone}"
  target = "${google_compute_instance_group_manager.mytemplate.self_link}"

  autoscaling_policy {
    min_replicas = 0
    max_replicas = 100
    cooldown_period = 60

    metric {
      name = "pubsub.googleapis.com/subscription/num_undelivered_messages"
      filter = "resource.label.subscription_id = \"my-subscriber\""
      single_instance_assignment = 50
    }
  }
```

### References

* GCloud API Docs for per-group metrics: https://cloud.google.com/compute/docs/autoscaler/scaling-stackdriver-monitoring-metrics#per_group_metrics

**Comment by rileykarson** [comment]
This should be added in our next release, `2.4.0`.
