### ISSUE TITLE
google_compute_network_peering: import/export custom routes

### ISSUE THREAD

**Issue by leg100** [terraform-providers/terraform-provider-google#3394]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

`google_compute_network_peering` is missing beta features, in particular:

(from `gcloud beta compute networks peerings create --help`)

```
     --export-custom-routes
        If set, the network will export custom routes to peer network. Use
        --no-export-custom-routes to disable it.

     --import-custom-routes
        If set, the network will import custom routes from peer network. Use
        --no-import-custom-routes to disable it.
```

### New or Affected Resource(s)

* google_compute_network_peering

### Potential Terraform Configuration

```tf
resource "google_compute_network_peering" "peering" {
  provider = "google-beta"
  name         = "peering"
  network      = "${var.source_net}",
  peer_network = "${var.dest_net}",
  export_custom_routes = "true"
  import_custom_routes = "true"
}
```
Both parameters should default to `false` if omitted.

### References

* #0000

**Comment by marcohelmerich** [comment]
I created a pull request in the magic modules repositry, but may need some help with testing.
https://github.com/GoogleCloudPlatform/magic-modules/pull/1695

**Comment by nesl247** [comment]
It looks like that PR was merged in. Not being familiar with terraform, what has to happen next?

**Comment by rileykarson** [comment]
Looks like this made it into `2.8.0`: https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#280-june-04-2019

We missed adding the docs though, unfortunately. I filed https://github.com/terraform-providers/terraform-provider-google/issues/4097 to track that, I'm going to close this issue out since the actual feature has been added.
