### ISSUE TITLE
Add SecurityGroups to google_container_cluster

### ISSUE THREAD

**Issue by marrau** [terraform-providers/terraform-provider-google#3407]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
*BETA-FEATURE*

I would like to use the groups from Google Cloud Identity inside a GKE to handle RBAC-based permission control.
For this to work the GKE needs to be setup with a flag "security-group". (see referenced documentation)

### Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster"
  location = "us-central1"

 security_group = "gke-security-groups@yourdomain.com"

 [...]
}

```

### References

* https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#groups-create-cluster
* https://godoc.org/google.golang.org/api/container/v1beta1

**Comment by marrau** [comment]
I like the potential terraform configuration in #3440 as it sticks more to the actual google api (and so is better to be autogenerated)

**Comment by marrau** [comment]
@alexey-medvedchikov Thank you. That looks great.

**Comment by rileykarson** [comment]
Closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/1715
