### ISSUE TITLE
google_container_node_pool name validation 

### ISSUE THREAD

**Issue by mattnworb** [terraform-providers/terraform-provider-google#3411]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Attempting to create a `google_container_node_pool` with a `name` containing hyphens returns an error at `terraform apply` time from GKE like:

```
[2019-04-08T19:06:02.776Z] * google_container_node_pool.32_by_1_pool: error creating NodePool: googleapi: Error 400: Invalid value for field "node_pool.name": "32-by-1-pool". Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,38}[a-z0-9])?)' (only alphanumerics and '-' allowed, must start with a letter and end with an alphanumeric, and must be no longer than 40 characters)., badRequest
```

While this is understandable on the GKE API side, it has bitten us more than a few times that the Terraform provider does not validate the name, as we have our Terraform code in a Git repo and do `terraform plan` in each CI/review build to validate both that a plan can be built and that it looks sane.

It would help save time if the Terraform provider for google_container_node_pool could validate the `name` against the same regex as the GKE API does when the resource is actually created.

### New or Affected Resource(s)

* google_container_node_pool

**Comment by emilymye** [comment]
As a note - the hyphens are allowed, it's that the name doesn't start with a letter

**Comment by mattnworb** [comment]
Looks like I copied an error from one of few times we have had this problem but then referred to a different occurrence of it in the writeup here. 

Thanks for the context, I suspected that is why the provider does not try to validate these today. It’s unfortunate there is not a way to “dry-run” the configuration against the API so that validation problems can be caught at plan-generation time without having to duplicate logic around what is a valid name in both the API and the terraform provider.

**Comment by emilymye** [comment]
While some APIs will document how they validate the names, it looks like GKE API docs don't show a validation. However, because GKE is rather abrupt and swift while making changes, I suspect even they don't want to document how they validate things because it changes too often.
