### ISSUE TITLE
Unable to set node_pool metadata when using module

### ISSUE THREAD

**Issue by rajatvig** [terraform-providers/terraform-provider-google#3415]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.13
+ provider.google v2.3.0
+ provider.google-beta v2.3.0

### Affected Resource(s)

google.container_node_pool

### Steps to Reproduce
When creating GKE clusters using a module, unable to set metadata on the node pool. Terraform fails completely even at init time.
This works well not using a module but directly using the resource.

### Error Message
```
Error: Error loading modules: module gke-cluster: Error loading .terraform/modules/03d35b347d697fc2fb267b2747dfc6a5/nodepools.tf: Error reading config for google_container_node_pool[pools]: At 39:14: root.node_config[0].metadata: unknown type for string *ast.ObjectType
```

**Comment by emilymye** [comment]
Without knowledge of how the module is set up or debug logs, I'm not sure we can provide much help. It sounds like the actual provider resource is working fine, so the module is the issue. I'm not sure which module you are using, but it might be better to debug with the module owner (or yourself if you are the module creator)

**Comment by rajatvig** [comment]
Yes, it was a mistake on my end. Had a metadata block that I was setting before. Sorry.
