### ISSUE TITLE
google_storage_bucket should validate fields

### ISSUE THREAD

**Issue by tonglil** [terraform-providers/terraform-provider-google#3420]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The resource when validating passes, but fails on apply because the field has specific requirements.

This breaks automation and requires approvals and etc again through the pipeline, delaying changes.

### New or Affected Resource(s)

* google_storage_bucket

### Potential Terraform Configuration

```tf
resource "google_storage_bucket" "bucket-name" {
  name          = "bucket-name"
  location      = "US"
  storage_class = "MULTI_REGIONAL"

  labels {
    repo   = "user/org"
    key = "value"
  }
}
```

When `terraform validate` everything passes:

```
Terraform will perform the following actions:

  + google_storage_bucket.bucket-name
      id:                 <computed>
      force_destroy:      "false"
      labels.%:           "2"
      labels.repo:        "user/org"
      labels.key:         "value"
      location:           "US"
      name:               "bucket-name"
      project:            <computed>
      self_link:          <computed>
      storage_class:      "MULTI_REGIONAL"
      url:                <computed>
```

But fails when `terraform apply`:

```
google_storage_bucket.bucket-name: Creating...
  force_destroy: "" => "false"
  labels.%:      "" => "2"
  labels.repo:        "user/org"
  labels.key:         "value"
  location:      "" => "US"
  name:          "" => "bucket-name"
  project:       "" => "<computed>"
  self_link:     "" => "<computed>"
  storage_class: "" => "MULTI_REGIONAL"
  url:           "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* google_storage_bucket.bucket-name: 1 error(s) occurred:

* google_storage_bucket.bucket-name: googleapi: Error 400: Invalid argument, invalid
```

Turns out:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/3250776/55988919-f2641200-5c59-11e9-9a4d-df47cb70bd5d.png">

**Comment by emilymye** [comment]
We are generally moving away from validation on fields such as names or similar, as underlying APIs have a habit of changing it on us and making our maintanence burden higher. Also, based on your config, if you're using "bucket-name" as a name, it is valid under the screenshotted restrictions. It might be that it is probably already taken since GCS bucket names must be globally unique. That is something we can't check as simple validation.

**Comment by tonglil** [comment]
Darn, the actual validation field that failed is the `labels.repo` field (as GCP labels apparently don't support `/`).

I feel like that field (resource labels) are fairly widespread across GCP resources that it would be a widely encompassing and valuable validation to perform.

**Comment by Chupaka** [comment]
@emilymye, just a thought: issue warnings but not errors on local validation.
