### ISSUE TITLE
istio_config cannot use in google provider version 2.3

### ISSUE THREAD

**Issue by thakerng** [terraform-providers/terraform-provider-google#3428]
I got this message when run `terraform apply`

```
Error: google_container_cluster.k8s_cluster: addons_config.0: invalid or unknown key: istio_config
```

Could you check istio_config is actually support for this version

`terraform version`

```
Terraform v0.11.13
+ provider.google v2.3.0
+ provider.google-beta v2.3.0
```

**Comment by Chupaka** [comment]
As you didn't provide your config, check that you are actually using beta provider for that resource.

**Comment by emilymye** [comment]
As @Chupaka mentioned, please make sure you have `provider "google-beta"` at the top of your cluster config. It appears to be in 2.3.0 beta provider: https://github.com/terraform-providers/terraform-provider-google-beta/blob/v2.3.0/google-beta/resource_container_cluster.go#L203

**Comment by thakerng** [comment]
Thank you 

It's work now
provider must be defined in `google_container_cluster` as well
Previously, There is only `provider "google-beta"` at top

```
provider "google-beta" {
  version     = "2.3.0"
  ...
}

resource "google_container_cluster" "primary" {
  provider = "google-beta"
  ...
}
```
