### ISSUE TITLE
writer_identity member value changes on apply

### ISSUE THREAD

**Issue by Nornode** [terraform-providers/terraform-provider-google#3456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.11
+ provider.google v2.4.0
+ provider.random v2.1.1

### Affected Resource(s)

resource "google_project_iam_binding"

### Terraform Configuration Files

```
resource "google_project_iam_binding" "billing-log-writer" {
    count                   = "${var.enable_log_billing}"
    role                    = "roles/storage.objectCreator"
    members                 = [
                            "${google_logging_billing_account_sink.billing-sink.writer_identity}",
        ]
}
```

### Expected Behavior

Applying my template twice (without any changes) would check but not find any changes.

### Actual Behavior
On applying 
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.logging_organization.google_project_iam_binding.billing-log-writer
      members.1440093022: "serviceAccount:o707520668752-816394@gcp-sa-logging.iam.gserviceaccount.com" => ""
      members.1695557587: "" => "serviceAccount:b010bd5-fa3ae5-5cb88c-220492@gcp-sa-logging.iam.gserviceaccount.com"
```

* #0000

**Comment by emilymye** [comment]
Can you add debug logs? i.e. run with `TF_LOG="DEBUG"`? I'm having trouble recreating this issue.

**Comment by Nornode** [comment]
Sorry for a long delay.
here's a [TF_LOG](https://gist.github.com/Nornode/8a4242f252f775802ae5ebcb28d61ef9)
The log collected a full:

> terraform apply
waited a few seconds to then run the same 

> terraform apply 
again.

I also applied the suggested changes.

**Comment by TryTryAgain** [comment]
@Nornode did you ever find a solution for this?

**Comment by Nornode** [comment]
No, I don't think so. 
I ended up changing several things to remove the obstacle.
