### ISSUE TITLE
Can't make rotation_period optional in google_kms_crypto_key

### ISSUE THREAD

**Issue by wyardley** [terraform-providers/terraform-provider-google#3467]
### Terraform Version
Terraform v0.11.13

### Affected Resource(s)
Please list the resources as a list, for example:
- google_kms_crypto_key

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "google_kms_crypto_key" "default_crypto_key" {
  count           = "${length(var.keys)}"
  name            = "${lookup(var.keys[count.index], "name", "")}" ## or "0"

  key_ring        = "${google_kms_key_ring.default_key_ring.self_link}"
  rotation_period =  "${lookup(var.keys[count.index], "rotation_period", "")}"
}
```
```hcl
module "gcp_kms_keyring" {
  source              = "../../modules/gcp_kms_keyring"
  name                = "foo"
  keys                = [
    {
      name = "foo"
    }
  ]
  location            = "global"
}
```

### Expected Behavior
What should have happened?
I know the focus is on 0.12 development, but.......
And since pre 0.12 tf doesn't have an undef / null, when a default is '0' or "", it doesn't seem to be possible to set a parameter or use defaults / ternary operator to make this parameter optional.

### Actual Behavior
What actually happened?
```
Error: module.gcp_kms_keyring.google_kms_crypto_key.default_crypto_key[0]: Invalid rotation period format: 
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by emilymye** [comment]
Overeager validation - fixing to allow for empty string!
