### ISSUE TITLE
can a iam member be given multiple roles one time?

### ISSUE THREAD

**Issue by zffocussss** [terraform-providers/terraform-provider-google#3478]
I am using "google_project_iam_member"

resource "google_project_iam_member" "project" {
  project = "your-project-id"
  role    = "roles/editor"
  member  = "user:jane@example.com"
}
if I have multiple members,roles.How can I define them.
resource "google_project_iam_member" "project" {
  project = "your-project-id"
  role    = "roles/1","roles/2","roles/3"
  member  = "user:a","user:b","user:c"
}

**Comment by rileykarson** [comment]
Hey @zffocussss!

`google_project_iam_member` is used to define a single user:role pairing. You can define multiple `google_project_iam_member` blocks to attach multiple roles to a single user, or multiple users to a single role.

Alternatively, if you have a single role with multiple members, you could use [`google_project_iam_binding`](https://www.terraform.io/docs/providers/google/r/google_project_iam.html#google_project_iam_binding-1) with the caveat that Terraform will remove the role from any users not present in that config.

As well, a great place for these kinds of questions is the #terraform channel in the [GCP Community Slack](https://gcp-slack.appspot.com/).

**Comment by zffocussss** [comment]
It is not convenient to manage multiple roles and members.by the way.What is "project id"?

**Comment by rileykarson** [comment]
A project id is a unique id for a project; sometimes it's the same as the display name, but at other times it's different (generally with numbers appended). See [the docs on identifying projects](https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects).

**Comment by zffocussss** [comment]
thanks
