### ISSUE TITLE
Cloud Identity Group resources

### ISSUE THREAD

**Issue by rrey** [terraform-providers/terraform-provider-google#3479]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I have a customer with an Active Directory (in Azure) and we are initiating a project in GCP.
We created an Organization and Google Engineers advised us to configue the provisioning of Cloud Identity with Azure AD. We did this and we now can use the AD user to connect to GCP.

The group management needs to be made at Cloud Identity level, and we were unable to find resources for cloud identity in the google provider.

Since the API exists, would it be possible to create the Terraform resources and datasources allowing to manage cloud identity ?

### New or Affected Resource(s)

* google_cloud_identity_group

### Potential Terraform Configuration

```tf
resource "google_cloud_identity_group" "admin" {
    name = "admin-group"
    displayName = "Admin Group"
}

resource "google_cloud_identity_group" "sub_group" {
    name = "non-admin-group"
    displayName = "Non-Admin Group"
    parent = "groups/${google_cloud_identity_group.admin.id}"
}
```

### References

Cloud Identity API doc: https://cloud.google.com/identity/docs/reference/rest/

**Comment by rrey** [comment]
Hello there, any feedback please ?

**Comment by rrey** [comment]
Hi @megan07 !

We don't have access to Cloud Search and we are only using Cloud Identity at this time.
We created all the Groups manually in Cloud Identity, having a terraform provider would allow us to 
automate all this !!

**Comment by danawillow** [comment]
Removing the waiting-response label so this doesn't get lost in automation, but if anyone who is subscribed to this could answer @megan07's question, that would help give us the information we need to get this prioritized.

**Comment by wchamber** [comment]
It looks like the Cloud Identiy Group API has beta support for Google Groups in addition to the Identity Groups that need an identity source. There's still some dependency on a GSuite integration, but it looks like GCP is building out functionality here. Labels on groups seem like a new feature not present in the GSuite Admin SDK.

https://cloud.google.com/identity/docs/how-to/groups#manage_google_groups_beta

**Comment by benv666** [comment]
Note sure if this should be a new ticket instead, but the datasources (as mentioned in the issue description) still seem to be unimplemented.
Since we're using an external AD group sync we would like to iterate over the members of existing groups, but since they are not managed in terraform it would be great to have datasources to get a list of groups and their members.
