### ISSUE TITLE
session affinity no longer set on backend services

### ISSUE THREAD

**Issue by thecodeassassin** [terraform-providers/terraform-provider-google#348]
### Terraform Version
v0.10.2

### Affected Resource(s)
google_compute_backend_service

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
esource "google_compute_backend_service" "legacy" {

    name = "legacy-backend-${var.environment}"
    description = "Legacy backend service"
    port_name = "http"
    protocol = "HTTP"
    timeout_sec = 120
    session_affinity = "GENERATED_COOKIE"

    depends_on = ["google_compute_instance_group_manager.legacy"]

    backend {
        group = "${google_compute_instance_group_manager.legacy.instance_group}"
    }

    backend {
        group = "${google_compute_instance_group_manager.legacy-fallback.instance_group}"
    }

    health_checks = ["${google_compute_http_health_check.legacy.self_link}"]
}
```

### Debug Output
https://gist.github.com/thecodeassassin/ebf4df4769fe38d6febf1529e014b2ee

### Expected Behavior
Should create a backend service that has the session affinity set. 

### Actual Behavior
What actually happened?

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I think it broke after upgrading from 0.9.x to 0.10.x.

**Comment by thecodeassassin** [comment]
It seems to be a UI problem on Google Cloud's side. issue can be closed i guess.

**Comment by thecodeassassin** [comment]
I was wrong, it seems that it's not setting the session affinity correctly when updating.

**Comment by selmanj** [comment]
Was able to reproduce. Whenever a backend_service is updated, session_affinity is reset to NONE (and a subsequent terraform apply notices this and corrects it).

A quick glance at the code seems to suggest the problem is that the update code is written to only set options that have changed, which then results in session_affinity having a default value.

**Comment by selmanj** [comment]
While attempting to fix this, I uncovered an inconsistency with how connection draining default values are set in the GCP API. Filed a bug upstream.
