### ISSUE TITLE
Dialogflow Support

### ISSUE THREAD

**Issue by beeme1mr** [terraform-providers/terraform-provider-google#3487]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for Dialogflow agent configuration. This could be used to manage the agent configuration, entities, and intents.

### New or Affected Resource(s)

* google_dialogflow_agent
* google_dialogflow_entity
* google_dialogflow_intent

### References

[Dialogflow API](https://cloud.google.com/dialogflow-enterprise/docs/reference/rest/v2-overview)

**Comment by rodush** [comment]
Hi @danawillow!
I hope you had a good vacation? :-) (I have seen the status in your github profile)
Do you know by any chance if there is any progress about this?
Digging around, I found out that the recommended (official?) way to add new resources or manage existing ones is with the Magic Modules.
I wonder, shall I spend time learning its DSL to add support for the Agent (Entity and Intents) and create a PR, or maybe the work is already in progress? 
Thanks for the update!

**Comment by danawillow** [comment]
Hi @rodush, that's indeed correct. I'm not aware of anyone on our side having started working on this yet, so you're welcome to pick it up! Check out the magic modules [README](https://github.com/GoogleCloudPlatform/magic-modules) and [codelab](https://codelabs.developers.google.com/codelabs/magic-modules/index.html#0) if you'd like to give it a try.

**Comment by c2thorn** [comment]
There are [a lot of potential responses](https://cloud.google.com/dialogflow/docs/reference/rest/v2/projects.agent.intents#Message) for Dialogflow Intents. Text and Custom Payload responses are available in the Default platform, so I plan to implement those for now. Feel free to request additional response types in separate issues so we can determine their demand.

**Comment by rangerscience** [comment]
Are there any plans to add fulfillment/webhook configuration to this provider? How would I go about properly requesting / implementing that?

(As nice as it'd be to have intents, responses, etc configurable in TF, the webhook stuff would actually interact with the rest of what TF is typically used for, right?)

**Comment by c2thorn** [comment]
Hey @rangerscience, additional Dialogflow features are best filed as separate issues as this one is a bit overloaded. This will help us keep track of the different Dialogflow features and their demand.

**Comment by rangerscience** [comment]
Added! Thanks @c2thorn
