### ISSUE TITLE
google_monitoring_alert_policy: labels not working

### ISSUE THREAD

**Issue by wilkmaia** [terraform-providers/terraform-provider-google#3493]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.13 (latest)

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_monitoring_notification_channel" "email" {
  display_name = "Sample Email"
  type         = "email"

  labels = {
    email_address = "sample@email.com"
  }
}

resource "google_monitoring_alert_policy" "alert" {
  display_name = "alert-policy"
  combiner     = "OR"

  enabled = true

  notification_channels = ["${google_monitoring_notification_channel.email.name}"]

  conditions = [
    {
      display_name = "Origin Unhealthy"

      condition_threshold {
        filter     = "metric.type=\"monitoring.googleapis.com/uptime_check/check_passed\" AND resource.type=\"uptime_url\" AND metric.label.check_id=\"origin\""
        duration   = "300s"
        comparison = "COMPARISON_GT"

        threshold_value = 2

        aggregations = [
          {
            alignment_period     = "300s"
            per_series_aligner   = "ALIGN_NEXT_OLDER"
            cross_series_reducer = "REDUCE_COUNT_FALSE"
          },
        ]
      }
    },
  ]

  labels = [
    "{ \"Key1\": \"Value1\"}",
    "{ \"Key2\": \"Value2\"}",
  ]
}
```

### Debug Output

https://gist.github.com/wilkmaia/bfd4793810bb2dde49de0b50be35b21b

### Expected Behavior

Successful execution.

### Actual Behavior

Error on GCP api call. The error is caused because GCP's AlertPolicy API has no `labels` field. The field name is `userLabels`.

Error is at https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_monitoring_alert_policy.go#L345. Replacing that with `obj["userLabels"]` should be enough. Or maybe renaming the `labels` prop to `user_labels`.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

* AlertPolicy API - https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies#AlertPolicy

**Comment by slevenick** [comment]
This is fixed with https://github.com/terraform-providers/terraform-provider-google/pull/3494

The field is renamed to `user_labels` to match the API. This will be available with the next release

**Comment by wilkmaia** [comment]
Thanks for fixing it, @slevenick. Should I close the issue?
