### ISSUE TITLE
CloudSQL HA Failover private network not the same as master

### ISSUE THREAD

**Issue by ellisio** [terraform-providers/terraform-provider-google#3495]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.13
+ provider.google v2.5.1
+ provider.google-beta v2.5.1
+ provider.random v2.1.1
```

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

https://gist.github.com/ellisio/935d1e697dc3aac7902482c8518049c2

### Debug Output

https://gist.github.com/ellisio/dc04593662416d925ef6fd065ff2cbb3

### Expected Behavior

`google_sql_database_instance.failover` should be created using both public and private networking.

### Actual Behavior

```
Error: Error applying plan:

1 error(s) occurred:

* google_sql_database_instance.failover: 1 error(s) occurred:

* google_sql_database_instance.failover: Error, failed to create instance arcadia-apps-andrew-failover: googleapi: Error 400: Invalid request: Replica should have the same network as the master: projects/arcadia-apps-238517/global/networks/arcadia-apps-andrew vs https://www.googleapis.com/compute/v1/projects/arcadia-apps-238517/global/networks/arcadia-apps-andrew., invalid
```

### Steps to Reproduce

1. `terraform apply`

**Comment by ellisio** [comment]
This was fixed by creating the `master` resource using the following:

```
locals {
  sql_private_network = "projects/${local.project}/global/networks/${google_compute_network.network.name}"
}

resource "google_sql_database_instance" "master" {
  // ...
  
  settings {
    // ...

    ip_configuration {
      require_ssl     = false
      ipv4_enabled    = true
      private_network = "${local.sql_private_network}"
    }
  }

  // ...
}
```

Then creating the `failover` with the exact same configuration. It appears `"${google_compute_network.network.self_link}"` returns a FQDN URL, instead of `projects/%s/global/networks/%s`, which is expected by the failover configuration.

Possible fixes?

1) Do not strip off the FQDN from `private_network` of `failover` if the `master` instance returns a `private_network` with it included.
2) Strip off the FQDN when creating the `master` instance.

If you manually create a Cloud SQL Cluster in HA, with a private IP, you'll notice the `Associated networking` block on the instance dashboard will _not_ have the FQDN prefix.

**Comment by venkykuberan** [comment]
@ellisio It looks to me this issue is fixed in the later versions, as i am able to create both master/fail over without any errors. Hence i am closing this ticket. Please reopen if you still see the issue on your end.
