### ISSUE TITLE
Cloudsql private private_ip not being added

### ISSUE THREAD

**Issue by TAvardit** [terraform-providers/terraform-provider-google#3504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.11
+ provider.google v1.20.0
+ provider.google-beta v2.5.1

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_compute_global_address" "cloudsql_private_ip_address" {
  provider      = "google-beta"
  name          = "cloudsql-private-ip-address"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  network       = "${google_compute_network.k8s.self_link}"
}

resource "google_service_networking_connection" "private_vpc_connection" {
  provider                = "google-beta"
  network                 = "${google_compute_network.k8s.self_link}"
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = ["${google_compute_global_address.cloudsql_private_ip_address.name}"]
}


# Cloudsql instance

resource "google_sql_database_instance" "test" {
  name             = "test"
  database_version = "POSTGRES_9_6"
  project          = "${var.project}"
  region           = "${var.region}"

  depends_on = ["google_service_networking_connection.private_vpc_connection"]

  settings {
    tier              = "db-custom-1-3840"
    availability_type = "ZONAL"
    disk_size         = "10"
    disk_autoresize   = "true"

    backup_configuration {
      enabled            = "false"
      binary_log_enabled = "false"
    }

    ip_configuration {
      ipv4_enabled    = "true"
      require_ssl     = "false"
      private_network = "${google_compute_network.k8s.self_link}"
    }
  }
}
```

### Actual Behavior
Allocated IP range, VPC peering and Cloudsql are created but there is no actual private IP set to the cloudsql instance , you have to activate it manually. Reapplying the Terraform just tries to reapply the following line but mnothing change on the cloudsql instance.
```tf
Terraform will perform the following actions:

  ~ google_sql_database_instance.test
      settings.0.ip_configuration.0.private_network: "" => "https://www.googleapis.com/compute/v1/projects/playground-XXXXXX/global/networks/test"
```
Enabling cloudsql private ip manually on the instance is working and the info of the private ip is added to the Terraform resource in the next `apply`.

### Steps to Reproduce

1. Have a cloudsql instance without `private)ip` set.
1. `terraform apply` on adding `privatte_ip` by using the code from `Terraform Configuration Files` above.
1. Check the cloudsql instance for `private_ip` configuration.

### References

*

**Comment by venkykuberan** [comment]
@TAvardit, apologies for the delay in response. Somehow this issue fell through the cracks.  If you are still facing the issues, please refer the updated docs [here](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html).

Please let us know if the docs didn't help to fix your issue.

**Comment by TAvardit** [comment]
@venkykuberan  We applied this change to all our instances and activated private ip configuration manually on the instance to have it working. Unfortunately, I don't have any instance that doesn't have it already configured and that I could test with it.

**Comment by venkykuberan** [comment]
Thank you @TAvardit, I will close this issue then. Please open a new one incase if you happened to hit the same issue.
