### ISSUE TITLE
Terraform autoscaling for gcp

### ISSUE THREAD

**Issue by hitesh1907nayyar** [terraform-providers/terraform-provider-google#3508]
Hi,

I need to know as how can we enable auto scaling forkubernetes on gcp in terraform ?

Presently I am using this script for creation of gcp on kubernetes:

provider "google" {
  
  region = "${var.gcp_region}"
  zone    = "${var.gcp_zone}"
}

resource "google_compute_route" "gcp_route" {
  name        = "${var.customer-name}-network-route"
  project     = "${var.gcp_project}"
  dest_range  = "0.0.0.0/0"
  network     = "${google_compute_network.gcp_vpc.name}"
  next_hop_gateway = "default-internet-gateway"
}

resource "google_compute_network" "gcp_vpc" {
  name                    = "${var.customer-name}-network"
  project                 = "${var.gcp_project}"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "gcp_subnet" {
  name                     = "${var.customer-name}-subnetwork"
  region                  = "${var.gcp_region}"
  project                 = "${var.gcp_project}"
  ip_cidr_range            = "10.127.0.0/20"
  network                  = "${google_compute_network.gcp_vpc.name}"
  private_ip_google_access = true
}

resource "google_container_node_pool" "kubernetes-cluster-node-pool" {
  name       = "${var.customer-name}-${var.gcp_cluster-name}-nodes"
  project    = "${var.gcp_project}"
  cluster    = "${google_container_cluster.kubernetes-cluster.name}"
  location   = "${var.gcp_zone}"
  node_count = "${var.gcp_min_size}"

  node_config {
    machine_type = "${var.gcp_instance-type}"
    
    oauth_scopes = [
      "compute-rw",
      "storage-full",
      "pubsub",
      "logging-write",
      "service-control",
      "service-management",
      "monitoring",
    ]

    labels {
      for = "ReferenceArchitecture"
    }

    tags = ["softwarization", "${var.customer-name}"]
  }

  autoscaling {
    min_node_count = "${var.gcp_desired_capacity}"
    max_node_count = "${var.gcp_max_size}"
  }

  management {
    auto_repair  = true
    auto_upgrade = true
  }
}

resource "google_container_cluster" "kubernetes-cluster" {
  name               = "${var.customer-name}-${var.gcp_cluster-name}"
  project            = "${var.gcp_project}"
  location           = "${var.gcp_zone}"
  remove_default_node_pool = true
  initial_node_count = 1
  
  network            = "${google_compute_network.gcp_vpc.name}"
  subnetwork         = "${google_compute_subnetwork.gcp_subnet.name}"

  enable_legacy_abac = true
  
  node_locations = [
    "${var.gcp_add_zone}",
  ]
}

**Comment by hitesh1907nayyar** [comment]
Any update please on this ?

**Comment by Chupaka** [comment]
```
autoscaling {
min_node_count = "${var.gcp_desired_capacity}"
max_node_count = "${var.gcp_max_size}"
}
```

According to this, you have autoscaling enabled. What's the question?

**Comment by hitesh1907nayyar** [comment]
> ```
> autoscaling {
> min_node_count = "${var.gcp_desired_capacity}"
> max_node_count = "${var.gcp_max_size}"
> }
> ```
> 
> According to this, you have autoscaling enabled. What's the question?

Problem is the nodes are not scaling consistently. When the load is increased sometimes the nodes scales up and sometimes not. When they dont scale then the request keeps on getting failed.  Can you let me know as how the above problem can be resolved. Also is there any metric like if cpu > 60% then node spoons up ?

**Comment by acondrat** [comment]
@hitesh1907nayyar you enabled cluster autoscaler but it does not care about CPU usage. It would only scale the cluster when there are insufficient resources to run your workloads. Please see https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler for details.

My guess is that you need to combine cluster autoscaler with the horizontal pod autoscaler to achieve CPU based scaling - https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by hitesh1907nayyar** [comment]
Ok @acondrat . I have a follow up question. How does the nodes scale down. There has been instances where load was increased and nodes increased say from 2 to 4. But aftersometime when the load reduced to 0 still the nodes were 4. I get notification in dashboard that low resource request but still nodes in gcp does not scale down. What could be the reason for the same ?

**Comment by acondrat** [comment]
Again, cluster autoscaler has nothing to do with CPU load.

For the scale down, I think you'll find the answer in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-scale-down-work . There are a couple of conditions for a node to "qualify" for a scale down.

**Comment by hitesh1907nayyar** [comment]
Hi @acondrat 
Thanks for the reply. So google already have auto-cluster installed on when terraform script is run with autoscaling option. Link that you shared- https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler  does not have any gcp kubernetes option.

**Comment by danawillow** [comment]
Closing this since it seems to be more about k8s in general rather than this terraform provider; feel free to reopen if I'm wrong.
