### ISSUE TITLE
GCP kubernetes version update via terraform

### ISSUE THREAD

**Issue by hitesh1907nayyar** [terraform-providers/terraform-provider-google#3509]
Hi,

I need to update kubernetes version that is installed via terraform. Presently it installs version - 1.11.8-gke.6. I need to get this updated to 1.12.7-gke.7. Can somebody please help

**Comment by rileykarson** [comment]
You can update the `min_master_version` of the cluster, and Terraform will upgrade the cluster if it's greater than the current master version.

Questions like this are a good fit for the [Google Cloud Platform Community Slack](https://gcp-slack.appspot.com/), specifically the #terraform channel. Several maintainers, myself included, hang out in that channel as well as many community members who use Terraform.
