### ISSUE TITLE
MySQL Database Instance with Private Network VPC IP only suddenly gets recreated and fails 

### ISSUE THREAD

**Issue by Starefossen** [terraform-providers/terraform-provider-google#3519]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.13
+ provider.google v2.5.1
+ provider.helm v0.9.1
+ provider.kubernetes v1.6.2
+ provider.local v1.2.1
+ provider.random v2.1.1
```

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_compute_network" "net" {
  name             = "my-network"
}

resource "google_sql_database_instance" "db" {
  name             = "my-db"
  database_version = "MYSQL_5_7"
  region           = "eu-north1"

  settings {
    tier = "db-f1-micro"

    ip_configuration {
      private_network = "${google_compute_network.net.self_link}"
    }
  }
}
```

### Apply Output

```
google_sql_database_instance.db: Modifying... (ID: my-db)
  settings.#:                                    "1" => "1"
  settings.0.activation_policy:                  "ALWAYS" => "<computed>"
  settings.0.availability_type:                  "" => "<computed>"
  settings.0.backup_configuration.#:             "1" => "<computed>"
  settings.0.crash_safe_replication:             "false" => "<computed>"
  settings.0.disk_autoresize:                    "true" => "true"
  settings.0.disk_size:                          "10" => "<computed>"
  settings.0.disk_type:                          "PD_SSD" => "<computed>"
  settings.0.ip_configuration.#:                 "1" => "1"
  settings.0.ip_configuration.0.ipv4_enabled:    "false" => "<computed>"
  settings.0.ip_configuration.0.private_network: "projects/my-project/global/networks/my-net" => "https://www.googleapis.com/compute/v1/projects/my-project/global/networks/my-apps"
  settings.0.location_preference.#:              "1" => "<computed>"
  settings.0.pricing_plan:                       "PER_USE" => "PER_USE"
  settings.0.replication_type:                   "SYNCHRONOUS" => "SYNCHRONOUS"
  settings.0.tier:                               "db-f1-micro" => "db-f1-micro"
  settings.0.version:                            "1" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* google_sql_database_instance.db: 1 error(s) occurred:

* google_sql_database_instance.: Error, failed to update instance settings for : googleapi: Error 400: Missing parameter: Settings version., required
```

### Expected Behavior

As per documentation this is how the private network should be configured so the expection is that this should work fine. 

### Actual Behavior

The instance is created but the second time you run `terraform apply` terraform says the `private_network` name had changed and tries to alter it inline and fails. 

### Steps to Reproduce

1. `terraform apply`
1. `terraform apply` <= this will fail

### Important Factoids

As a workaround, replacng the `https://www.googleapis.com/compute/v1/` part of the VPC network self_link seams to solve the problem.

```
  settings {
    …
    ip_configuration {
      private_network = "${replace("${google_compute_network.net.self_link}", "https://www.googleapis.com/compute/v1/", "")}"
    }
  }
```

### References

* #0000

**Comment by rileykarson** [comment]
Hey @Starefossen!

Out of curiousity, have you used `lifecycle.ignore_changes` on the resource? This is likely an occurrence of https://github.com/hashicorp/terraform/issues/18209

Past that, if you haven't, are you able to provide debug logs or a full repro config? It doesn't look like the config provided matches the values in your apply output.

**Comment by rileykarson** [comment]
Closing as stale, please file again if you encounter this.
