### ISSUE TITLE
filestore resource GA

### ISSUE THREAD

**Issue by elvin159** [terraform-providers/terraform-provider-google#3520]
i see in the documentation the filestore resource is in beta for terraform. GCP has GA'd the filestore service as of april 8. Is there a timeline to know when this resource will be GA'd?

https://www.terraform.io/docs/providers/google/r/filestore_instance.html

**Comment by rileykarson** [comment]
Ah- we weren't aware that it went GA. Sent https://github.com/GoogleCloudPlatform/magic-modules/pull/1701, which should fix this by our next release.
