### ISSUE TITLE
More fine-grained control over Composer GKE Cluster

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [terraform-providers/terraform-provider-google#3526]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_composer_environment

### Potential Terraform Configuration

```resource "google_composer_environment" "composer-environment" {
  provider = "google-beta"
  name = "${var.composer_environment_name}"
  region = "${var.composer_region}"
  project = "${var.project_id}"
  config {
    node_count = 3

    node_config {
      zone = "${var.composer_zone}"
      machine_type = "n1-standard-1"

      network = "${var.composer_network_self_link}"
      subnetwork =  "${google_compute_subnetwork.compose-subnet.self_link}"

    #  service_account = "${google_service_account.composer-role.name}"
    }

    software_config {
      airflow_config_overrides = {
        core-load_example = "True"
      }

      image_version = "composer-1.5.2-airflow-1.10.1"
      python_version = "2"

      pypi_packages = {
        #numpy = ""
        #scipy = "==1.1.0"
      }

      env_variables = {
        JANUS_SUBNETWORK = "${google_compute_subnetwork.compose-subnet.network}"
      }
    }
  }

 # depends_on = ["google_project_iam_member.composer-worker"]
}
```

The GKE composer cluster has the following properties we'd like to control for the cluster to be privateas described in https://cloud.google.com/composer/docs/how-to/managing/configuring-private-ip.
The composer can't be modified to be public.  

### References

* #0000

**Comment by mikhail-khodorovskiy** [comment]
@emilymye - still WIP but here is the diff with my fork for the private composer environment to work against v1beta1 version of the composer API for the google-beta provider: https://github.com/terraform-providers/terraform-provider-google-beta/compare/master...cambiahealth:adding-private-composer

**Comment by tysen** [comment]
Fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/1999
