### ISSUE TITLE
Allowing one hostname in multiple host_rules in google_compute_url_map

### ISSUE THREAD

**Issue by sageecute** [terraform-providers/terraform-provider-google#3537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This issue is with regards to the google_compute_url_map resource.

When we try to add the same domain to multiple host rules in terraform, it gives us a host conflict error. 
Suppose there a few common paths that need to be used by all the domains and they point to the same backend, then the current terraform resource configuration cannot fulfil the use case.

```
host_rule {
    hosts        = ["foo.bar.com"]
    path_matcher = "foobarpaths"
  }

  path_matcher {
    name            = "foobarpaths"
    default_service = "projects/${var.project_id}/global/backendServices/${var.default_backend}"
  }

  host_rule {
    hosts        = ["foo.bar.com", "zoo.bar.com"]
    path_matcher = "commonpaths"
  }

  path_matcher {

      name = "commonpaths"
      default_service = "projects/${var.project_id}/global/backendServices/${var.default_backend_service}"

      path_rule {
      paths   = ["${var.common_path}"]
      service = "projects/${var.project_id}/global/backendBuckets/${var.backend_bucket}"
    }
  }
```
Here we have foo.bar.com and zoo.bar.com pointing to the same backend bucket. But I am not able to create this resource. 

I get the following error

```
* google_compute_url_map.gclb-url-map: Error, failed to update Url Map gclb: googleapi: Error 400: Invalid value for field 'resource': '{  "id": "6204789751202287586",  "creationTimestamp": "2019-04-30T04:27:09.897-07:00",  "name": "gcl...'. Host rules conflict, invalid
```

The alternative will be to create a path for every hostname. 
The problem with this approach is that the urlmap rules are limited to 50. So if I try to do so I will run out of paths.

```
host_rule {
    hosts        = ["foo.bar.com"]
    path_matcher = "foobarpaths"
  }

  path_matcher {
    name            = "foobarpaths"
    default_service = "projects/${var.project_id}/global/backendServices/${var.default_backend_foobar}"

   path_rule {
      paths   = ["${var.common_path}"]
      service = "projects/${var.project_id}/global/backendBuckets/${var.backend_bucket}"
    }
  }

  host_rule {
    hosts        = ["zoo.bar.com"]
    path_matcher = "zoobarpaths"
  }

  path_matcher {

      name = "zoobarpaths"
      default_service = "projects/${var.project_id}/global/backendServices/${var.default_backend_zoobar}"

      path_rule {
      paths   = ["${var.common_path}"]
      service = "projects/${var.project_id}/global/backendBuckets/${var.backend_bucket}"
    }
  }
```

### Potential Terraform Configuration

There should be a provision to add multiple hosts. The same is allowed when we try to do it at the loadbalancer level from the user interface

```tf



```

### References

* #0000

**Comment by Chupaka** [comment]
This looks like API-generated error which cannot be worked around by Terraform. Can you create desired configuration manually?

**Comment by sageecute** [comment]
Yes I can create the desired configuration manually from the UI.

**Comment by rileykarson** [comment]
I believe this is a limitation of the underlying API. When I create the following with the API:

![image](https://user-images.githubusercontent.com/2080520/58647386-50a58c80-82bc-11e9-8852-c4beab609c42.png)

It maps to the following:

```js
{
 "kind": "compute#urlMap",
 "id": "8716881058519171037",
 "creationTimestamp": "2019-05-30T09:13:38.258-07:00",
 "name": "hello",
 "selfLink": "https://www.googleapis.com/compute/v1/projects/graphite-test-rileykarson/global/urlMaps/hello",
 "hostRules": [
  {
   "hosts": [
    "google.com"
   ],
   "pathMatcher": "path-matcher-1"
  },
  {
   "hosts": [
    "rileykarson.com"
   ],
   "pathMatcher": "path-matcher-2"
  },
  {
   "hosts": [
    "facebook.com"
   ],
   "pathMatcher": "path-matcher-3"
  }
 ],
 "pathMatchers": [
  {
   "name": "path-matcher-1",
   "defaultService": "https://www.googleapis.com/compute/v1/projects/graphite-test-rileykarson/global/backendServices/backend-service",
   "pathRules": [
    {
     "service": "https://www.googleapis.com/compute/v1/projects/graphite-test-rileykarson/global/backendServices/backend-service",
     "paths": [
      "/images/*"
     ]
    },
    {
     "service": "https://www.googleapis.com/compute/v1/projects/graphite-test-rileykarson/global/backendServices/backend-service",
     "paths": [
      "/memes/*"
     ]
    }
   ]
  },
  {
   "name": "path-matcher-2",
   "defaultService": "https://www.googleapis.com/compute/v1/projects/graphite-test-rileykarson/global/backendServices/backend-service",
   "pathRules": [
    {
     "service": "https://www.googleapis.com/compute/v1/projects/graphite-test-rileykarson/global/backendServices/backend-service",
     "paths": [
      "/h/*"
     ]
    },
    {
     "service": "https://www.googleapis.com/compute/v1/projects/graphite-test-rileykarson/global/backendServices/backend-service",
     "paths": [
      "/images/*"
     ]
    }
   ]
  },
  {
   "name": "path-matcher-3",
   "defaultService": "https://www.googleapis.com/compute/v1/projects/graphite-test-rileykarson/global/backendServices/backend-service",
   "pathRules": [
    {
     "service": "https://www.googleapis.com/compute/v1/projects/graphite-test-rileykarson/global/backendServices/backend-service",
     "paths": [
      "/memes/*"
     ]
    }
   ]
  }
 ],
 "defaultService": "https://www.googleapis.com/compute/v1/projects/graphite-test-rileykarson/global/backendServices/backend-service",
 "fingerprint": "wBxr8kUA8pc="
}

```

Each host maps to a single path matcher, containing a path rule per path.

In fact, it turns out the UI doesn't even preserve what I entered. It flattens my config out to the following:

![image](https://user-images.githubusercontent.com/2080520/58647545-abd77f00-82bc-11e9-927c-e6814c686310.png)

---

While it would be a better user experience, I'm not sure that adding resource-specific logic to Terraform to allow specifying the resource like the UI does is appropriate; the time spent adding that functionality could be better spent on API features we don't cover yet. Regardless, I'll leave this issue open in case there's community interest or any points I've missed.

**Comment by paddycarver** [comment]
This has gone a while without any response, and it sounds like this is an upstream limitation in the API, so I'm going to close this out. If you feel this is in error, please feel free to open a new issue.
