### ISSUE TITLE
Feature request: Labels support for Global Forwarding Rule

### ISSUE THREAD

**Issue by evandbrown** [terraform-providers/terraform-provider-google#354]
Hey folks!

Labels landed in alpha for Global Forwarding Rule (GFW). The API is at https://developers.google.com/apis-explorer/#search/globalforwardingrule/m/compute/alpha/compute.globalForwardingRules.insert

Here's the use-case: I'm building a tool to automate the creation, revocation, and renewal of Let's Encrypt/acme certificates for GFWs. I would love to label global forwarding rules that should have certs, something like:

```
labels: {
  "domain": "a.example.com",
  "expires": "2017-08-24T16:22:42Z"
}
```

This would be super neat because I wouldn't need to store information about which GFWs need certs in a separate database. The GFW List and Get APIs become the database. Cool!

Thanks for considering!

**Comment by selmanj** [comment]
Looks like there's a beta API as well. Relates to #17
