### ISSUE TITLE
Terraform Import failing for GCP Service accounts

### ISSUE THREAD

**Issue by thxmike** [terraform-providers/terraform-provider-google#3545]
Terraform Version

Terraform version: 0.11.13 

Terraform Configuration Files

resource "google_service_account" "terraform-iam" {
  account_id   = "projects/gsuite-api-service/serviceAccounts/terraform-iam-service@test-gsuite-api-229318.iam.gserviceaccount.com"
  email = "terraform-iam-service@test-gsuite-api-229318.iam.gserviceaccount.com"
  display_name = "terraform.iam.service"
  project = "gsuite-api-service"
}

Debug Output

https://gist.github.com/thxmike/71dbb1093f8f7bb590377b2a1af94e26
Crash Output
Expected Behavior

terraform import google_service_account.terraform-iam terraform-iam-service
should produce a state file or state data
Actual Behavior
In response to the answer provided in #3542, we did attempt this but keep getting a different error
Error: google_service_account.terraform-iam: "account_id" ("projects/gsuite-api-service/serviceAccounts/terraform-iam-service@test-gsuite-api-229318.iam.gserviceaccount.com") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"

Updated configure provided here

Steps to Reproduce
terraform import google_service_account.terraform-iam terraform-iam-service
Additional Context
References

**Comment by rileykarson** [comment]
Closing in favour of #3542, issues are still available to comment on after being closed; if this doesn't end up being config, #3542 will be opened.
