### ISSUE TITLE
Error:400  on folder import

### ISSUE THREAD

**Issue by thxmike** [terraform-providers/terraform-provider-google#3549]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.13
+ provider.google v2.5.1

### Affected Resource(s)

google_folder

### Terraform Configuration Files

```tf

resource "google_folder" "global-security" {
  display_name = "global-security"
  parent     = "organizations/493595111382"
}
```

### Debug Output
https://gist.github.com/thxmike/ced2b3824257eb343ca94de17bcf9959
### Expected Behavior

Imported folder into state with
terraform import google_folder.global-security "global-security"

### Actual Behavior
import google_folder.global-security result: folders/global-security: google_folder.global-security: Error reading folders/global-security: googleapi: Error 400: Request contains an invalid argument., badRequest

### Steps to Reproduce
run terraform import google_folder.global-security "global-security"

1. `terraform apply`

### References

* #0000

**Comment by thxmike** [comment]
After some digging, this appears to be coming from the google api.  I tried it on the api explorer and got the same results
https://cloud.google.com/resource-manager/reference/rest/v2/folders/get?apix_params=%7B%22name%22%3A%22folders%2Fcorp%22%7D

**Comment by rileykarson** [comment]
Hey @thxmike! Per https://www.terraform.io/docs/providers/google/r/google_folder.html#import, the folder id required is the numeric folder number and not the folder's user-facing display name. You can find that # beside the display name in the Cloud Console while browsing your organization.
