### ISSUE TITLE
Lifecycle ignore_changes = "disk" doesn't work on disks for Compute instances

### ISSUE THREAD

**Issue by beenanner** [terraform-providers/terraform-provider-google#355]
Quick check if this is a known issue if not I can add the additional details to reproduce, but I'm unable to apply the ignore_changes to a compute instances that has additional disks attached via RexRay(https://github.com/codedellemc/rexray).

**Comment by beenanner** [comment]
I've also tried adding all the new ones.

```
lifecycle {
      ignore_changes = ["boot_disk", "scratch_disk", "attached_disk", "disk"]
  }
```

**Comment by beenanner** [comment]
Output shows expected 1 disk since it was booted with only the boot_disk. :-)
```

Error refreshing state: 1 error(s) occurred:

* google_compute_instance.worker: 1 error(s) occurred:

* google_compute_instance.worker[0]: google_compute_instance.worker.0: Expected 1 disks, API returned 9
```

**Comment by danawillow** [comment]
Everything about attached disks is currently in flux, but I'll look into seeing if I can remove that check.

**Comment by beenanner** [comment]
Thanks @danawillow that would help out my use-case. Regardless awesome job on all the recent stuff, loving it! :-)

**Comment by dkazhdan** [comment]
Sorry i am being confused, would that mean that  ignore_changes =volume wont work for rexray attached volumes then? much appreciated

**Comment by beenanner** [comment]
@dkazhdan I dont think it's specific to rexray its any externally attached disks not defined within terraform. Rexray was just my specific use case. :-)
