### ISSUE TITLE
CloudFunctions support location euw2

### ISSUE THREAD

**Issue by perriea** [terraform-providers/terraform-provider-google#3554]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for CloudFunctions `europe-west2` and other missing regions on the provider.
No prob to import the function in the state but impossible to apply.
Thank you for your work !

### New or Affected Resource(s)

* google_cloudfunctions_function

```
Terraform v0.11.13
+ provider.archive v1.2.2
+ provider.google v2.5.1
+ provider.google-beta v2.5.1
```

Apply: 😢 
```tf
terraform apply
data.archive_file.function-cluster-creation-infos: Refreshing state...
data.terraform_remote_state.storage: Refreshing state...
data.terraform_remote_state.pubsub: Refreshing state...
data.terraform_remote_state.iam: Refreshing state...

Error: Error running plan: 1 error(s) occurred:

* module.func-infos-deploy-cluster.google_cloudfunctions_function.function: expected region to be one of [us-central1 us-east1 europe-west1 asia-northeast1], got europe-west2
```

Import: 👌 
```tf
terraform import module.func-infos-deploy-cluster.google_cloudfunctions_function.function ****/europe-west2/func-infos-cluster-deployment-labs
module.func-infos-deploy-cluster.google_cloudfunctions_function.function: Importing from ID "****/europe-west2/func-infos-cluster-deployment-labs"...
module.func-infos-deploy-cluster.google_cloudfunctions_function.function: Import complete!
  Imported google_cloudfunctions_function (ID: ****/europe-west2/func-infos-cluster-deployment-labs)
module.func-infos-deploy-cluster.google_cloudfunctions_function.function: Refreshing state... (ID: ****/europe-west2/func-infos-cluster-deployment-labs)

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

### References

* https://cloud.google.com/functions/docs/locations

**Comment by rileykarson** [comment]
Fixed by https://github.com/terraform-providers/terraform-provider-google/pull/3530 in `2.6.0`
