### ISSUE TITLE
GCP Composer add file to generated bucket

### ISSUE THREAD

**Issue by michyliao** [terraform-providers/terraform-provider-google#3559]
Hi all, I was wondering with the GCP provider on the composer resource, is there a way for us to import files to the dag buckets that get created by composer? ie.
`gcloud composer environments storage data import file.txt`

Or will i need to somehow extract the composer bucket name and import via `google_storage_bucket_object`. Just reading through the terraform docs on composer - i dont see any output value for buckets

Thanks!

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by chrisst** [comment]
@michyliao have you looked at `config.dag_gcs_prefix` already?
