### ISSUE TITLE
BigQuery Dataset - invalid or unknown key: access

### ISSUE THREAD

**Issue by wilkinsjle** [terraform-providers/terraform-provider-google#3573]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.13
+ provider.google v1.17.1

(running in Docker)

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "default" {
  dataset_id                  = "foo"
  friendly_name               = "test"
  description                 = "This is a test description"
  location                    = "EU"
  default_table_expiration_ms = 3600000

  labels = {
    env = "default"
  }

  access {
    role   = "READER"
    domain = "example.com"
  }
  access {
    role           = "WRITER"
    group_by_email = "writers@example.com"
  }
}
```

### Details
When I write Terraform to create a Big Query Dataset, the key `access` is invalid or unknown according to Terraform's `vaidate` function.

Above is an example `.tf` file, that is taken straight from the docs here: https://www.terraform.io/docs/providers/google/r/bigquery_dataset.html

Even validating this example `.tf` from the docs produces the same following message: 
```
Error: google_bigquery_dataset.default: : invalid or unknown key: access
```

Could it be that the docs are out of date, or perhaps is it the validator that has a bug? Is `access` a valid key in Terraform when creating BQ Datasets?

**Comment by Chupaka** [comment]
Could it be that your provider plugin is out of date? v1.17.1 is quite old. We have v2.5.1 already :)

**Comment by rileykarson** [comment]
Specifically, `access` was added in `1.18.0`; https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#1180-september-17-2018. If you upgrade your provider version this field should be available!

**Comment by wilkinsjle** [comment]
Thanks team!
