### ISSUE TITLE
Error reading billing accounts: googleapi: Error 500: Internal error encountered

### ISSUE THREAD

**Issue by mark-00** [terraform-providers/terraform-provider-google#3574]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

2019/05/06 18:27:17 [INFO] Terraform version: 0.12.0 beta2
2019/05/06 18:27:17 [INFO] Go runtime version: go1.11.5
+ provider.google v2.5.1

### Affected Resource(s)

google_project
google_billing_account

#### main.tf ####

```tf
module "myProject-test1" {
  source = "./modules/uz_google_project"
  name   = "test1"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test2" {
  source = "./modules/uz_google_project"
  name   = "test2"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test3" {
  source = "./modules/uz_google_project"
  name   = "test3"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test4" {
  source = "./modules/uz_google_project"
  name   = "test4"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test5" {
  source = "./modules/uz_google_project"
  name   = "test5"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test6" {
  source = "./modules/uz_google_project"
  name   = "test6"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test7" {
  source = "./modules/uz_google_project"
  name   = "test7"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test8" {
  source = "./modules/uz_google_project"
  name   = "test8"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test9" {
  source = "./modules/uz_google_project"
  name   = "test9"
  folder      = "folders/xxxxxxxx"
}
```

#### modules/uz_goole_project/main.tf ####
```tf
resource "google_project" "myProject" {
  name = var.name
  project_id = var.name
  folder_id  = var.folder
  billing_account = "${data.google_billing_account.myBillingAccount.id}"
}

data "google_billing_account" "myBillingAccount" {
  display_name = "xxxxxxxxxxxxxxx"
  open         = true
}
```

### Expected Behavior

plan should be created

### Actual Behavior

Half of the time there is no problem
Half of the time it gives an error   Error reading billing accounts: googleapi: Error 500: Internal error encountered.

Error: Error reading billing accounts: googleapi: Error 500: Internal error encountered., backendError

  on modules/uz_google_project/main.tf line 9, in data "google_billing_account" "myBillingAccount":
   9: data "google_billing_account" "myBillingAccount" {

### Steps to Reproduce

repeatedly execute the statement below. 10 times, 100 times, ...
 
rm terraform.tfstate terraform.tfstate.backup myplan.out ;terraform init; terraform plan -out myplan.out -no-color

about half of the time it gives an error. 

### Important Factoids

The higher the number of projects defined in `main.tf` the more likely the error occurs.

### References

* #0000

**Comment by mark-00** [comment]
setting -parallelism=5 solves  the issue

**Comment by chrisst** [comment]
It looks like you have exposed a bug in the billing account api. I recommend that you file a bug directly against the billing account apis at https://cloud.google.com/support/docs/issue-trackers. If you are able to reproduce without Terraform (using curl or a script) it will likely help them figure out the issue sooner. Otherwise you will probably want to provide them with timestamps when the error happened and turning on the Terraform debug log should provide those. To obtain the debug output, see the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html)
