### ISSUE TITLE
Error 400: applying alert policy with denominator_filter and labels reducer

### ISSUE THREAD

**Issue by gudzenkov** [terraform-providers/terraform-provider-google#3575]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.13
+ provider.google v1.20.0
+ provider.google-beta v2.5.1
+ provider.null v2.1.0
+ provider.random v2.1.0
+ provider.template v2.1.0

the same error reproduced with both google v1.20 and google-beta v2.5.1

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```
  terraform {
    required_version = "= 0.11.13"
    backend "gcs" {
      bucket  = "tf-state-xxxx"
      prefix  = "terraform/state/stackdriver/development"
      project = "tf-state-xxxx"
    }
  }

resource "google_monitoring_alert_policy" "api_quota" {
  provider = "google-beta"
  display_name = "API quota"
  enabled = "true"
  combiner = "OR"
  notification_channels = []
  conditions = [{
    display_name = "The limit utilization for each quota_metric"
    condition_threshold {
      filter             = "metric.type=\"serviceruntime.googleapis.com/quota/allocation/usage\" resource.type=\"consumer_quota\""
      denominator_filter = "metric.type=\"serviceruntime.googleapis.com/quota/limit\"            resource.type=\"consumer_quota\""
      duration = "300s"
      comparison = "COMPARISON_GT"
      threshold_value = "0.6"
      denominator_aggregations {
        alignment_period = "60s"
        per_series_aligner   = "ALIGN_MEAN"
        cross_series_reducer = "REDUCE_MIN"
        group_by_fields = ["project", "metric.labels.quota_metric"]
      }
      aggregations {
        alignment_period = "60s"
        per_series_aligner   = "ALIGN_MEAN"
        cross_series_reducer = "REDUCE_MIN"
        group_by_fields = ["project", "metric.labels.quota_metric"]
      }
    }
  }]
}

```

### Debug Output
https://gist.githubusercontent.com/gudzenkov/844433fd3427f965601ee2baff0a2cd7/raw/cda83cca42725b5c812145b83bf9e2e5015cb971/tf_debug_google_monitoring_alert_policy.log

### Expected Behavior

Metric `quota/limit`  is having labels `quota_metric` and `limit_name`
Metric `quota/allocation/usage` is having single label `quota_metric`
Setting `group_by_fields = ["project", "metric.labels.quota_metric"]` for both nominator and denominator should make labels match.

> Fields not specified in groupByFields are aggregated away.

There should be NO label `limit_name` for `quota/limit` metric after aggregation.

### Actual Behavior

```
* google_monitoring_alert_policy.api_test: Error creating AlertPolicy: googleapi: Error 400: Label 'limit_name' is in the denominator but not in the numerator.
```

### Steps to Reproduce

1. `terraform plan`
```
Plan: 1 to add, 0 to change, 0 to destroy.
```
2. `terraform apply`
```
google_monitoring_alert_policy.api_quota: Creating...
Error: Error applying plan:
* google_monitoring_alert_policy.api_test: Error creating AlertPolicy: googleapi: Error 400: Label 'limit_name' is in the denominator but not in the numerator.
```

**Comment by chrisst** [comment]
This is an error from the upstream API and not from Terraform. Based on your config Terraform appears to be sending the values I would expect in the payload of the POST body. I recommend that you file this bug against the stackdriver monitoring API instead: https://cloud.google.com/support/docs/issue-trackers.

I was also able to reproduce this error by [hitting the API directly](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies/create?apix=true&apix_params=%7B"name"%3A"projects%2Fproject-id"%2C"resource"%3A%7B"combiner"%3A"OR"%2C"conditions"%3A%5B%7B"conditionThreshold"%3A%7B"aggregations"%3A%5B%7B"alignmentPeriod"%3A"60s"%2C"crossSeriesReducer"%3A"REDUCE_MIN"%2C"groupByFields"%3A%5B"project"%2C"metric.labels.quota_metric"%5D%2C"perSeriesAligner"%3A"ALIGN_MEAN"%7D%5D%2C"comparison"%3A"COMPARISON_GT"%2C"denominatorAggregations"%3A%5B%7B"alignmentPeriod"%3A"60s"%2C"crossSeriesReducer"%3A"REDUCE_MIN"%2C"groupByFields"%3A%5B"project"%2C"metric.labels.quota_metric"%5D%2C"perSeriesAligner"%3A"ALIGN_MEAN"%7D%5D%2C"denominatorFilter"%3A"metric.type%3D%5C"serviceruntime.googleapis.com%2Fquota%2Flimit%5C"%20%20%20%20%20%20%20%20%20%20%20%20resource.type%3D%5C"consumer_quota%5C""%2C"duration"%3A"300s"%2C"filter"%3A"metric.type%3D%5C"serviceruntime.googleapis.com%2Fquota%2Fallocation%2Fusage%5C"%20resource.type%3D%5C"consumer_quota%5C""%2C"thresholdValue"%3A0.6%7D%2C"displayName"%3A"The%20limit%20utilization%20for%20each%20quota_metric"%7D%5D%2C"displayName"%3A"API%20quota"%2C"documentation"%3Anull%2C"enabled"%3Atrue%7D%7D). Including this on the bug report to stackdriver should help them identify the issue faster.
