### ISSUE TITLE
google_compute_firewall can I get a working example of enable_logging showing the allowed/expected values

### ISSUE THREAD

**Issue by 0xa08ab242** [terraform-providers/terraform-provider-google#3592]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Expected Behavior

refer to documentation for the allowable values for adding enable_logging parameter to a gcp firewall config using terraform-provider-google-beta

### Actual Behavior

allowable values do not exist as you can see in this except from the documentation:
"enable_logging - (Optional, Beta) This field denotes whether to enable logging for a particular firewall rule. If logging is enabled, logs will be exported to Stackdriver."

...so I started by trying a boolean value, then tried variations of that using quotes, braces, brackets, etc. and all failed.   At this point, I feel like either I don't know how to search the Internet, nobody else has ever had a problem with this because it is too obvious, or nobody else has tried to use this feature.

**Comment by chrisst** [comment]
You can try searching Github for other people using the resource:
https://github.com/search?q=google_compute_firewall++enable_logging+filename%3A*.tf&type=Code

All booleans in Terraform can be specified with just `true` or `false`. See https://www.terraform.io/docs/configuration-0-11/variables.html#booleans for more.

If this doesn't answer your question, please provide a snippet of your config that isn't working.

**Comment by 0xa08ab242** [comment]
@chrisst thanks for trying to help me search better, but the results of that search were not quite enough for me to see the answer to my problem.  For context, I was working off of error messages in circleci telling me that the value for enable_logging was invalid.  This is why I focused on having a valid working example or official documentation stating that this parameter was a boolean.  As I had stated in my original question, I had tried using the boolean value, and it still failed.
Where I had fallen into a trap was a bit of output just before the error message in circleci showing terraform initializing using both provider.google and provider.google-beta.  I made the mistaken assumption that the provider definition I needed was made elsewhere.
The short and simple answer that I needed to hear was:
For every GCP firewall rule where you want to enable logging via terraform, you have to call out the google-beta provider in that rule's configuration:
`provider = "google-beta"`
`enable_logging = true`
