### ISSUE TITLE
Terraform VMware TFstate file stores passwords in plain text.

### ISSUE THREAD

**Issue by TeeJuan** [terraform-providers/terraform-provider-google#3616]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Hi Guys, i recently started deploying VMs with Terraform and i noticed that it stores passwords in plain text. do you have any work arounds for this ? 
your help is highly appreciated in this regard.

thank you

**Comment by emilymye** [comment]
In general, that's a limitation of Terraform state (see [sensitive data in Terraform](https://www.terraform.io/docs/state/sensitive-data.html) and longstanding [issue](https://github.com/hashicorp/terraform/issues/516) against main Terraform). Options generally are to use remote state and to use [input variables](https://www.terraform.io/docs/configuration/variables.html) without defaults, [environment variables](https://www.terraform.io/docs/commands/environment-variables.html), or even HashiCorp Vault to manage your secrets.

**Comment by emilymye** [comment]
I'm going to ahead and close this issue but please feel free to re-open if there's anything you wanted to ask!
