### ISSUE TITLE
Service Account IAM role assignment

### ISSUE THREAD

**Issue by derekschauland** [terraform-providers/terraform-provider-google#3618]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.13
+ provider.google v2.6.0
+ provider.google-beta v2.6.0

### Affected Resource(s)
IAM Roles added to Service Accounts

### Terraform Configuration Files

resource "google_project_iam_binding" "stackdriver_iam_logswriter"{
  project = "${var.gcp_project_name}"
  role = "roles/logging.logwriter"
  members = [
    "serviceAccount:${local.curent_proj_number}@developer.gserviceaccount.com"
  ]
}

```tf
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug) then please include both the
# version of the config before the change, and the version of the config after the change.
```

### Expected Behavior

Terraform should apply the IAM Roles to a service account for a new gce instance without error

### Actual Behavior

Terraform throws an error about a bad request, but the IAM settings/roles get applied anyhow.

 google_project_iam_binding.stackdriver_iam_logswriter: Error applying IAM policy for project "terraform-testing-project": Error setting IAM policy for project "terraform-testing-project": googleapi: Error 400: Role roles/logging.logwriter is not supported for this resource., badRequest

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by emilymye** [comment]
Do you mind giving us:

- The same run with debug logs (i.e. `TF_LOG="DEBUG" terraform apply`)
- The before and after policy on the actual GCP resource (i.e. verified through the API, not using Terraform)

I'll verify if GCP actually adds the role to a GCE policy but returns an error - if so, that's an upstream error.

**Comment by derekschauland** [comment]
What is the best way to hit the API for verification? The resources being used are net new, there is no resource before... 

I wonder if there are project permissions controlling what is there already... I am trying to provide permissions for logging.logswriter and monitoring.metricwriter.  

[tf-logs.txt](https://github.com/terraform-providers/terraform-provider-google/files/3174256/tf-logs.txt)
A TF_log debug is attached for an apply for net new vm

**Comment by emilymye** [comment]
Interesting. Those permissions should be settable on the project. It's a little hard to read the debug logs - do you mind either only running with your `google_project` and `google_project_iam_binding` config only? Alternatively, if you post your config, I can attempt to recreate the issue on my end.

**Comment by derekschauland** [comment]
I’ll get just the iam policy bits posted tomorrow

I think the project service account is being set/ used for these roles... which might make them set once use many (terraform builds of vms happen in a test project )

Just weird that it would error if things work after- unless the error is more a “I’m already done with this” than failing because it can’t add roles

Derek

Sent from my iPhone

On May 13, 2019, at 4:38 PM, emily <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting. Those permissions should be settable on the project. It's a little hard to read the debug logs - do you mind either only running with your google_project and google_project_iam_binding config only? Alternatively, if you post your config, I can attempt to recreate the issue on my end.

**Comment by derekschauland** [comment]
[tf-logs_apply.txt](https://github.com/terraform-providers/terraform-provider-google/files/3177626/tf-logs_apply.txt)

The log for the iam_binding log file is attached

**Comment by emilymye** [comment]
Hmm. So, the error here (I think) is that you're using logwriter instead of logWriter. I can't recreate the situation where it still sets the binding, so maybe that was just left over from previous runs? 

I just did the following:
1. `terraform apply` with following config
```
resource "google_project_iam_member" "test" {
  project = "my-project"
  role = "roles/logging.logwriter"
  member = "serviceAccount:${data.google_compute_default_service_account.default.email}"
}
```
and got the error you got and no change to my project bindings. 

When I changed to:
```
resource "google_project_iam_member" "test" {
  project = "my-project"
  role = "roles/logging.logWriter"
  member = "serviceAccount:${data.google_compute_default_service_account.default.email}"
}
```
it worked fine. 

So, I'm not able to recreate the bindings silently changing despite the error, but using logWriter and metricWriter should fix the top-level error.

**Comment by derekschauland** [comment]
I think that will work - Ive got some other things to work out, am working to get block-project-ssh-keys working as needed - need TF to put the public keys for service account(s) on the vm and havent mastered that yet, but I think these should be set

thanks for your help
Derek
