### ISSUE TITLE
HA option in google_compute_vpn_gateway

### ISSUE THREAD

**Issue by selslack** [terraform-providers/terraform-provider-google#3625]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCP supports Cloud VPN HA configuration: https://cloud.google.com/vpn/docs/concepts/topologies#configurations_that_support_9999_availability. 

When using Terraform's `google_compute_vpn_gateway`, there's no option to create such gateway.

Since IPs are allocated automatically with this option enabled, the resource should have an output of newly allocated IPs.

### New or Affected Resource(s)

* google_compute_vpn_gateway

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

**Comment by selslack** [comment]
I've found this (for reference): https://github.com/GoogleCloudPlatform/magic-modules/pull/1760.

**Comment by slevenick** [comment]
Hey @selslack 

As you found in that Magic Modules PR I'm currently working on generating a new `google_compute_ha_vpn_gateway` resource for the HA VPN Gateway. 

This option is preferred because the API that supports the HA VPN Gateway is separate from the one that supports Target VPN Gateway (which is what the current `google_compute_vpn_gateway` supports)

I'll leave this issue open until we support the HA functionality

**Comment by slevenick** [comment]
Important note: the HA VPN Gateway resource is currently in beta, so this feature will be first made available in https://github.com/terraform-providers/terraform-provider-google-beta

**Comment by slevenick** [comment]
This is available via the `google_compute_ha_vpn_gateway` resource introduced in https://github.com/GoogleCloudPlatform/magic-modules/pull/1760

Currently this is only available in the beta provider.

**Comment by tobiaskohlbau** [comment]
Hello,

as far as I could read there exists no option to create a external vpn gateway with ha mode from the `terraform-provider-google-beta`. Are there any plans to support this beta feature as well?
