### ISSUE TITLE
google_compute_instance data struct doesn't support splat operator

### ISSUE THREAD

**Issue by smaslennikov** [terraform-providers/terraform-provider-google#3638]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.13
+ provider.google v2.1.0
+ provider.google-beta v2.2.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* `data.google_compute_instance`

### Terraform Configuration Files

```tf
...
resource "google_compute_region_instance_group_manager" "default" {
  name               = "${var.name}-mig"
  instance_template  = "${google_compute_instance_template.default.self_link}"
  base_instance_name = "${var.name}"
  region             = "${var.region}"
  target_size        = 2

  distribution_policy_zones = ["${data.google_compute_zones.available.names}"]
}

data "google_compute_region_instance_group" "default" {
  self_link = "${google_compute_region_instance_group_manager.default.instance_group}"
}

data "google_compute_instance" "default" {
  count = "${data.google_compute_region_instance_group.default.instances.size}"

  self_link = "${data.google_compute_region_instance_group.default.instances.*.instance[count.index]}"
}
...
```

### Debug Output

```
* module.pizza.data.google_compute_instance.default[0]: At column 73, line 1: invalid index operation into non-indexable type: TypeString in: ${data.google_compute_region_instance_group.default.instances.*.instance[count.index]}
```

### Expected Behavior

Data structures should be created, each representing an instance in the MIG.

### Actual Behavior

The splat (`*`) operator seems to be ineffective and `terraform plan` breaks.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This bug frustratingly prevents generating DNS records for MIGs. Several other tickets in this repository mention that this way is possible, while stating it's an antipattern. While I agree that it's an antipattern, it is sometimes needed and simply doesn't work.

### References

* https://github.com/terraform-providers/terraform-provider-google/issues/2915https://github.com/terraform-providers/terraform-provider-google/issues/3638

**Comment by emilymye** [comment]
I'm pretty sure this is a limitation of the splat operator, specifically with nested output-only fields (which is exactly what a data source is for) and would be an issue to bring up with Terraform core. However, I believe the official stance will probably be "use 0.12 which has a better splat". :/ 

We as providers sadly don't have control over how the splat operator works. I'm not sure if you could work around using something like the built-in `element` or `lookup` functions. We've typically pointed people to issues like https://github.com/hashicorp/terraform/issues/17048 where people have tried to find alternatives.

**Comment by smaslennikov** [comment]
@emilymye As terraform 0.12 isn't yet stable, that's not an option for me nor my clients. Thank you nonetheless, I'll continue following the issue you linked.
