### ISSUE TITLE
Support for http/2 in google_compute_health_check

### ISSUE THREAD

**Issue by tonnihult** [terraform-providers/terraform-provider-google#3641]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We would like to have support for HTTP2 in the resource google_compute_health_check and this is supported using gcloud beta.
 
```
$ gcloud beta compute health-checks create http2 http2-basic-check --port 443
Created [https://www.googleapis.com/compute/beta/projects/removed-project-name/global/healthChecks/http2-basic-check].
NAME               PROTOCOL
http2-basic-check  HTTP2
$ gcloud beta compute backend-services create test-service --protocol HTTP2 --health-checks http2-basic-check --global
Created [https://www.googleapis.com/compute/beta/projects/removed-project-name/global/backendServices/test-service].
NAME           BACKENDS  PROTOCOL
test-service            HTTP2
```

### New or Affected Resource(s)

* google_compute_health_check

### Potential Terraform Configuration

When creating the http2 health check via gcloud beta or through the google cloud console we see that the options are the same for the setups using https or http/2 as protocols. Example configuration is as below with default values added.

```tf
resource "google_compute_health_check" "http2-health-check" {
 name = "http2-health-check"

 timeout_sec        = 1
 check_interval_sec = 1

 http2_health_check {
   port = "443"
   host = ""
   request_path = "/"
   response = ""
   proxy_header = "NONE"
 }
}
```

**Comment by emilymye** [comment]
added in https://github.com/terraform-providers/terraform-provider-google/pull/3631
