### ISSUE TITLE
reserve static internal ip address

### ISSUE THREAD

**Issue by jberglund-BSFT** [terraform-providers/terraform-provider-google#366]
I would like the ability to reserve a static internal ip address as described here 
https://cloud.google.com/compute/docs/ip-addresses/reserve-static-internal-ip-address

**Comment by paddycarver** [comment]
This looks like it can be achieved just by adding a couple fields to the `google_compute_address` resource and making sure it supports beta APIs.

**Comment by CGavrila** [comment]
Is there any news on this one?

**Comment by elliottsam** [comment]
I have added PR #525 That I am using that adds this functionality

**Comment by rosbo** [comment]
Fixed by #594
