### ISSUE TITLE
Document workaround for #3369 in recommended usage examples for google_container_cluster

### ISSUE THREAD

**Issue by ejschoen** [terraform-providers/terraform-provider-google#3672]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I've spent a week trying to stop my system from trying to recreate its cluster on unrelated changes, or after timeout failures while provisioning the system.  This involved trying many different examples from published tutorials on the web, as well as searching through issues on this Github and looking for relevant questions on stackoverflow.  I reduced the problem to its simplest form, by trying to manage a cluster using exactly the recommended usage for [google_container_cluster](https://www.terraform.io/docs/providers/google/r/container_cluster.html).

Eventually, I stumbled across #3369, which was the root cause of my problem.  

The problem is that Terraform behavior is described by authors using many different terms: idempotent, change, recreate, etc.  It's very hard to find all relevant mentions of Terraform recreating a resource (like a cluster) by Google searching.

Until provider 3.0.0 can be released with fixes to the lifecycle issues, it might make sense to document the workarounds mentioned in that issue in the recommended usage documentation.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster"
  location = "us-central1-f"

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true
  initial_node_count = 1

  # Setting an empty username and password explicitly disables basic auth
  master_auth {
    username = ""
    password = ""
  }
  # Workaround for issue 3369.
  lifecycle {
    ignore_changes = ["master_auth", "network"]
  }
}

```

### References

* #3369

**Comment by danawillow** [comment]
@rileykarson, passing this to you since you have the most context on the issue
