### ISSUE TITLE
ip_allocation_policy false forces new resource 

### ISSUE THREAD

**Issue by brettcurtis** [terraform-providers/terraform-provider-google#3682]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
v0.11.8

### Affected Resource(s)
google_container_cluster

### Terraform Configuration Files
```tf
resource "google_container_cluster" "k8s_cluster" {
  provider = "google-beta"
  name     = "k8s-cluster-${var.region}"
  project  = "${google_project.k8s_project.project_id}"
  location   = "${var.region}"

  min_master_version = "${var.kubernetes_version}"
  network            = "default"
  subnetwork         = "default"
  node_version       = "${var.kubernetes_version}"
  logging_service    = "${var.kubernetes_logging_service}"
  monitoring_service = "${var.kubernetes_monitoring_service}"

  ip_allocation_policy {
    use_ip_aliases = false
  }

  addons_config {
    istio_config {
      disabled = false
    }
  }

  node_pool {
    name = "default-pool"

    node_config {
      machine_type = "${var.machine_type}"

      oauth_scopes = [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/compute",
        "https://www.googleapis.com/auth/devstorage.read_write",
        "https://www.googleapis.com/auth/logging.write",
        "https://www.googleapis.com/auth/monitoring",
      ]
    }

    initial_node_count = "${var.node_count}"

    autoscaling {
      min_node_count = "${var.min_node_count}"
      max_node_count = "${var.max_node_count}"
    }

    management {
      auto_repair  = "true"
      auto_upgrade = "false"
    }
  }

  timeouts {
    update = "20m"
  }

  depends_on = ["google_project_service.k8s_service"]
}
```
### Expected Behavior

If the cluster has ip aliasing disabled already this should not rebuild the resource

### Actual Behavior
```
      ip_allocation_policy.#:                               "0" => "1" (forces new resource)
      ip_allocation_policy.0.cluster_ipv4_cidr_block:       "" => <computed>
      ip_allocation_policy.0.cluster_secondary_range_name:  "" => <computed>
      ip_allocation_policy.0.node_ipv4_cidr_block:          "" => <computed>
      ip_allocation_policy.0.services_ipv4_cidr_block:      "" => <computed>
      ip_allocation_policy.0.services_secondary_range_name: "" => <computed>
      ip_allocation_policy.0.use_ip_aliases:                "" => "false" (forces new resource)
```
### References
Seems similar to this:
* #3230

**Comment by danawillow** [comment]
Hi @brettcurtis, I just ran the config you posted (or at least, a pretty similar one) and everything created as expected and it didn't show any changes on apply. Did you mean to post a before and after config?

**Comment by brettcurtis** [comment]
So the use case is that I already used terraform to create a cluster
without the ip aliasing stuff. Now I go and add the alias stuff but with
false and it wants to rebuild. If that's not clear I can give better
details back in the office tomorrow.

The reason I want to do this is because I have a git submodule multiple
teams consume with this code in it. Some teams need the ip aliasing and
others don't. So I don't want to impact those teams that do not need it.
I'd just pass a variable for true or false.

**Comment by rileykarson** [comment]
@danawillow see https://googlecloud-community.slack.com/archives/C1VNJ4EG7/p1558452175022700 for context
