### ISSUE TITLE
Support google_compute_instance import

### ISSUE THREAD

**Issue by nikoren** [terraform-providers/terraform-provider-google#369]
The initial idea was to try to update the configuration for google compute disks:
`disk` ==> `boot_disk`/`attached_disk` as required in version 10  to prevent all the deprecation errors, however this action involves destroying disk and the instance and then re-provision them. 

To avoid re-provisioning I thought we can manually remove all the resources from the state and re-import them on by one with the new configuration. Unfortunately importing `google_compute_instance` is currently not supported. I think we will stay with deprecation warnings and wait until this issue is resolve to update our config . 

### Terraform Version
Terraform v0.10.2

### Affected Resource(s)
- google_compute_instance

### Terraform Configuration Files
```hcl
resource "google_compute_instance" "compute-recommendation" {
  count = "${var.gce_recommendation_compute_count}"
  name = "${var.environment}-${var.client}-compute-recommendation-${count.index}"
  machine_type = "${var.gce_recommendation_compute_machine_type}"
  zone = "${var.gce_region}-b"
  tags = ["compute-recommendation"]

  boot_disk {
    source = "${element(google_compute_disk.compute-recommendation-disk.*.name, count.index)}"
  }
  network_interface {
    network = "${var.environment}"
    access_config {
      nat_ip =  "${element(google_compute_address.compute-recommendation-static-ips.*.address, count.index)}"
    }
  }
  metadata {
    sshKeys = "${var.gce_ssh_user}:${file("${var.gce_ssh_pub_key_file}")}"
  }
  service_account {
    scopes = "${var.service_account_scopes}"
  }
}
```

### Debug Output
https://gist.github.com/nikoren/887544482ab7597789b36b08a021a3af

### Expected Behavior
Compute instance should be imported

### Actual Behavior
Get error 

```
Error importing: 1 error(s) occurred:

* module.dev-tst-environment.google_compute_instance.compute-recommendation (import id: 49023364572610319): import module.dev-tst-environment.google_compute_instance.compute-recommendation (id: 49023364572610319): resource google_compute_instance doesn't support import
```
### Steps to Reproduce
1. create `gce_compute_instance` 
2. remove instance from state `terraform state rm gce_compute_instance.name`
3. Try to import the instance `terraform import google_compute_instance.compute-recommendation ${instance_id}`

**Comment by rosbo** [comment]
Related to #182 which is to add import support for all compute resources.

**Comment by danawillow** [comment]
Also related to #329 which does a migration to the new fields to avoid the destroy/create you noticed.

**Comment by nikoren** [comment]
Thanks for finding time to look into this issue,
@danawillow do you have any rough estimate for when this PR is going to be ready to merge?

**Comment by danawillow** [comment]
Hopefully within the next week or two, but it's hard to know.

**Comment by orkunkaraduman** [comment]
We are waiting this feature for a month...

**Comment by galdor** [comment]
Is there any news for this feature ?

**Comment by lkr2des** [comment]
I guess this open issue is related to what I am noticing as well, 

I am on 

$ terraform --version
Terraform v0.11.1
+ provider.google v1.1.0

and trying to do,

$ terraform import google_compute_instance.ac01 ac01
google_compute_instance.ac01: Importing from ID "ac01"...
Error importing: 1 error(s) occurred:

* google_compute_instance.ac01 (import id: ac01): import google_compute_instance.ac01 (id: ac01): resource google_compute_instance doesn't support import


Logs...
2017/12/17 11:36:08 [ERROR] root: eval: *terraform.EvalImportState, err: import google_compute_instance.ac01 (id: ac01): resource google_compute_instance doesn't support import
2017/12/17 11:36:08 [ERROR] root: eval: *terraform.EvalSequence, err: import google_compute_instance.ac01 (id: ac01): resource google_compute_instance doesn't support import

**Comment by rosbo** [comment]
@lkr2des You are correct. This error message shows up because the feature is not supported yet.

It won't be possible to import the metadata field correctly without a breaking change but I can still support import for all the other field. After the import, it will show a diff for the metadata field but since metadata supports update, it shouldn't be a big deal.

I suggest we do it in 2 parts:
1. Support import w/o the metadata field now.
2. Wait for v2 to do a breaking change allowing proper import support for the metadata.
