### ISSUE TITLE
Redis creation fails if provider region is actually zone

### ISSUE THREAD

**Issue by atmatthewat** [terraform-providers/terraform-provider-google#3690]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.14
+ provider.google v2.6.0

### Affected Resource(s)

* google_redis_instance.redis-cache

### Terraform Configuration Files

```tf
provider "google" {
  credentials = "${file("./creds/serviceaccount.json")}"
  project     = "scanradio-241321"
  region      = "us-west1-b"
}

resource "google_redis_instance" "redis-cache" {
  name           = "scanradio-redis"
  tier           = "BASIC"
  memory_size_gb = 1

  location_id    = "us-west1-b"

  redis_version     = "REDIS_3_2"

  redis_configs = {
    maxmemory-policy = "allkeys-lru"
  }
}
```

### Expected Behavior

Should have created the instance.

### Actual Behavior

google_redis_instance.redis-cache: Creating...
  alternative_location_id:        "" => "<computed>"
  create_time:                    "" => "<computed>"
  current_location_id:            "" => "<computed>"
  host:                           "" => "<computed>"
  location_id:                    "" => "us-west1-b"
  memory_size_gb:                 "" => "1"
  name:                           "" => "scanradio-redis"
  port:                           "" => "<computed>"
  project:                        "" => "<computed>"
  redis_configs.%:                "" => "1"
  redis_configs.maxmemory-policy: "" => "allkeys-lru"
  redis_version:                  "" => "REDIS_3_2"
  region:                         "" => "<computed>"
  reserved_ip_range:              "" => "<computed>"
  tier:                           "" => "BASIC"

Error: Error applying plan:

1 error occurred:
	* google_redis_instance.redis-cache: 1 error occurred:
	* google_redis_instance.redis-cache: Error creating Instance: googleapi: Error 403: Location us-west1-b is not found or access is unauthorized.

### Steps to Reproduce

1. `terraform apply`
2. Fails as per above with cryptic error
3. Change region in provider from "us-west1-b" to "us-west1"
4. Succeeds

### References

* #0000

**Comment by atmatthewat** [comment]
Note that every other thing that I've used so far (GKE, SQL, Cloud Storage) has been perfectly happy with the region field being a full zone name in the provider definition. Didn't trip anything up until Redis.

**Comment by rileykarson** [comment]
Hey @atmatthewat! GKE is a unique resource, and can actually be created in a `zone` or a `region`. That said, can you share the SQL config you were able to use? We'd expect a failure as you've experienced with Redis, but SQL succeeding would be surprising.

**Comment by venkykuberan** [comment]
@atmatthewat Do you still need help on this issue or shall i go head and close it ?

**Comment by venkykuberan** [comment]
I am closing this one, please reopen if needed
