### ISSUE TITLE
Unable to Deploy Database Instances

### ISSUE THREAD

**Issue by cofonseca** [terraform-providers/terraform-provider-google#3697]
Hello. I'm attempting to deploy a sql_database_instance for both MySQL and PostgreSQL, but they both fail with the following error:

> Error waiting for Create Instance: Failed to create subnetwork. Please create Service Networking connection with service 'servicenetworking.googleapis.com' from consumer project '1234567890' network 'vpc' again.

Here's an example of my PostgreSQL config:
```
resource "random_id" "id" {
    byte_length = 4
    prefix      = "${var.database_name}-"
}
resource "google_sql_database_instance" "postgresql" {
    database_version = "POSTGRES_11"
    region = "${var.region}"
    project = "${var.project_id}"
    name = "${random_id.id.hex}"
    settings {
        tier = "db-f1-micro"
        activation_policy = "ALWAYS"
        availability_type = "REGIONAL"
        replication_type = "SYNCHRONOUS"
        maintenance_window {
            day = 7
            hour = 3
            update_track = "stable"
        }
        ip_configuration {
            ipv4_enabled = "false"
            private_network = "${var.vpc}"
        }
        location_preference {
            zone = "${var.zone}"
        }
    }
}
```
My MySQL config looks almost identical. I use Terraform to manage all infrastructure in this environment, including the VPC that I'm trying to attach to, so nothing was created by hand. I have not had this issue in the past. Thoughts?

**Comment by danawillow** [comment]
Hi @cofonseca, take a look at the private ip example for sql databases: https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#private-ip-instance. You'll also need to add a `google_service_networking_connection` resource, as the error message suggests.

Hope that helps! Also, though we do answer usage questions in the issue tracker, we don't particularly love doing so- we'd rather keep it to bugs and feature requests. There are a list of community resources at https://github.com/terraform-providers/terraform-provider-google/issues/new?template=question.md that make the maintainers' lives easier :)
