### ISSUE TITLE
google_logging_metric resource doesn't allow counter metrics

### ISSUE THREAD

**Issue by amatas** [terraform-providers/terraform-provider-google#3698]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.12

### Affected Resource(s)

* google_logging_metric

### Terraform Configuration Files

```tf
resource "google_logging_metric" "logging_metric" {
  name   = "my-metric"
  filter = "resource.type=gce_instance AND logName:\"logs/syslog\""

  project = "${var.project_id}"

  metric_descriptor {
    labels {
      key         = "my-label"
      value_type  = "STRING"
      description = "This is my label"
    }
  }

  label_extractors = {
    "my-label" = "REGEXP_EXTRACT(jsonPayload.someField, \"before ([0-9]+) after\")"
  }
}
```

### Debug Output

```
Error: google_logging_metric.logging_metric: "metric_descriptor.0.metric_kind": required field is not set                                                   
Error: google_logging_metric.logging_metric: "metric_descriptor.0.value_type": required field is not set  
```

### Expected Behavior

A `counter metric` is created, as it is documented here:
https://cloud.google.com/logging/docs/logs-based-metrics/counter-metrics

### Actual Behavior

The actual resource requires the fields `value_type` and `metrics_kind` which seems that are not required in the case of `counter metric`.

### Steps to Reproduce

1. `terraform apply`

### References

* https://www.terraform.io/docs/providers/google/r/logging_metric.html#value_type
* https://cloud.google.com/logging/docs/logs-based-metrics/#counter-metric
* https://cloud.google.com/logging/docs/logs-based-metrics/counter-metrics

**Comment by l15k4** [comment]
Imho the `Counter` metric that you see in UI results into `DELTA` metric Kind ...

**Comment by rileykarson** [comment]
Tagging as enhancement because this seems more like new functionality than a bug.

**Comment by stepanstipl** [comment]
I was able to create "Counter" metric by setting `metric_kind = "DELTA"` and `value_type = "INT64"`. (Also the label and it's descriptor have to be changed to `my_label`, it appears that `-` is not allowed.)

So the final resource definition that worked:
```hcl
resource "google_logging_metric" "logging_metric" {
  name   = "my-metric"
  filter = "resource.type=gce_instance AND logName:\"logs/syslog\""

  project = "my-project"

  metric_descriptor {

    metric_kind = "DELTA"
    value_type = "INT64"

    labels {
      key         = "my_label"
      value_type  = "STRING"
      description = "This is my label"
    }
  }

  label_extractors = {
    "my_label" = "REGEXP_EXTRACT(jsonPayload.someField, \"before ([0-9]+) after\")"
  }
}
```

And created "Counter" metric:

<img width="1197" alt="Screenshot 2019-05-30 at 13 07 25" src="https://user-images.githubusercontent.com/3027227/58631913-e69cdf80-82db-11e9-99ad-fe89e14f6cc2.png">

Perhaps this could use some clarification in the docs?
