### ISSUE TITLE
CloudSQL - Replicating from an external server

### ISSUE THREAD

**Issue by akira28** [terraform-providers/terraform-provider-google#3704]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Right now is impossible to create an external master replication as described here:
https://cloud.google.com/sql/docs/mysql/replication/replication-from-external
Specifically this command is not replicable in Terraform:
```
gcloud beta sql instances create [SOURCE_REPRESENTATION_NAME] \
    --region=[REGION] --database-version=[MYSQL_VERSION] \
    --source-ip-address=[SOURCE_IP] --source-port=[SOURCE_PORT]
```

### New or Affected Resource(s)

* google_sql_database_instance

### Potential Terraform Configuration

```tf
resource "google_sql_database_instance" "external-origin" {
  count            = "1"
  name             = "external-origin"
  project          = "project_name"
  region           = "eu-west"
  database_version = "MYSQL_5_7"
  
  settings {
    source_ip_address = "123.123.123.123"
    source_port = "3306"
  }
}
```

**Comment by danawillow** [comment]
Clearing the milestone to propose adding it to sprint 7 in our planning meeting, as per https://github.com/terraform-providers/terraform-provider-google/issues/5620#issuecomment-589799193
