### ISSUE TITLE
Support Shared VPC/XPN in GCE

### ISSUE THREAD

**Issue by ebonydad** [terraform-providers/terraform-provider-google#372]
### Terraform Version

v0.10.2

### Expected Behavior

To be able to create, provision, deprovision Shared VPC/XPN via Terraform:

### Documentation:

https://cloud.google.com/compute/docs/shared-vpc/provisioning-shared-vpc

### SDK:

https://cloud.google.com/sdk/gcloud/reference/compute/xpn/

### Actual Behavior

No command sets are currently in Terraform.

**Comment by paddycarver** [comment]
I _think_ this may already be supported. Does https://www.terraform.io/docs/providers/google/r/compute_instance.html#subnetwork_project do what you're looking for? Could you help me understand better if it doesn't fit your needs? Sorry, I'm not overly familiar with XPN.

**Comment by danawillow** [comment]
@paddycarver, we have support for using XPN but not for provisioning it. @rosbo and I are working on adding support for that now so I'm going to go ahead and unassign you from this :)

**Comment by danawillow** [comment]
Fixed in #396.
