### ISSUE TITLE
google_compute_instance - errors with subnets when creating after upgrade to Terraform 12

### ISSUE THREAD

**Issue by melonger** [terraform-providers/terraform-provider-google#3727]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.0
+ provider.google v2.7.0
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "default" {
  count = var.serverinfo["count"]

  depends_on = [
    data.template_file.instance_user_data,
    google_compute_address.int-ip,
    google_compute_address.ext-ip,
  ]

  name         = "${var.servername}${count.index}"
  machine_type = var.serverinfo["size"]
  zone         = element(data.google_compute_zones.available.names, count.index)
  tags         = split(",", var.serverinfo["tags"])

  labels = {
    environment = var.env
    costcenter  = lower(var.tags["costcenter"])
  }

  service_account {
    ## Email needs to bind to the KMS service account
    email  = var.crypto_email
    scopes = split(",", var.serverinfo["roles"])
  }

  metadata = {
    sshKeys = "${var.os_user}:${var.ssh_public_key}"
  }

  allow_stopping_for_update = true

  metadata_startup_script = "${data.template_file.instance_user_data.rendered}"

  boot_disk {
    initialize_params {
      image = var.serverinfo["image"]
      size  = var.serverinfo["disk_size"]
    }
  }

  network_interface {
    network_ip = element(google_compute_address.int-ip.*.address, count.index)
    subnetwork = google_compute_address.int-ip[count.index].subnetwork
    access_config {
      nat_ip = element(google_compute_address.ext-ip.*.address, count.index)
    }
  }
}
```

### Panic Output

Error: Provider produced inconsistent final plan

When expanding the plan for
module.blah.google_compute_instance.default[0] to include new values
learned so far during apply, provider "google" produced an invalid new value
for .network_interface[0].subnetwork: was cty.StringVal("blah-internal"), but
now
cty.StringVal("https://www.googleapis.com/compute/v1/projects/gcp-blah/regions/us-central1/subnetworks/blah-internal").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Expected Behavior

It runs at first attempt

### Actual Behavior

It fails the first attempt, ctrl+c, fails with the above error, run the command a second time, and it works without issue. 

### Steps to Reproduce

1. `terraform apply --var-file=../varfiles/blah.tfvars`

### Important Factoids

This worked before the upgrade to TF12

**Comment by melonger** [comment]
Any update on this? It's a pretty critical bug when I can't get a seamless run of Terraform. If I have to run it a second time, every time, Terraform 12 becomes a useless upgrade for GCP.

**Comment by kyrogue** [comment]
Happening to me also, when referencing a subnetwork/network in the network interface block of the google_compute_instance resource, despite the subnetwork already existing in GCP, a first run always results in `Error: Error creating instance: googleapi: Error 400: The resource 'projects/*/regions/*/subnetworks/myproject-subnetwork' is not ready, resourceNotReady`
Only when i run terraform a second time does it apply seamlessly.

**Comment by tysen** [comment]
@melonger I was able to reproduce this but I was also able to prevent it. Is your `google_compute_address` referencing its `subnetwork` by its name (e.g. `subnetwork = google_compute_subnetwork.foo[count.index].name`)? Your stated error occurs when I try that, but not when I reference the subnetwork by its `self_link`.

@kyrogue Are you stating `depends_on` or referencing the terraform resource (e.g. subnetwork = google_compute_subnetwork.foo.self_link), or just using the name of the subnetwork?

**Comment by tysen** [comment]
@melonger Terraform 0.12 introduced some new validation that fails when the config changes between plan and apply. In this case the address subnetwork starts as the short form (in the config) but is replaced with the fully qualified URI after creation. Then the instance refs the address subnetwork again and sees a diff and the run fails. The solutions are to use the fully qualified URI from the start, or to create a local variable with the short form (the var won't change between plan and apply) that both the address and instance ref.

We'll see about the feasibility of changing this behavior in Terraform core, but no promises there.
