### ISSUE TITLE
Improve google_iam_policy diff formatting 

### ISSUE THREAD

**Issue by marcin-kolda** [terraform-providers/terraform-provider-google#3728]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Terraform 0.12 has improved JSON diff formatting, but it's still far from being usable. As discussed in hashicorp/terraform#21473 Terraform JSON diff renderer is not aware of GCP IAM policy specifics, e.g. if elements are ordered or not.

Because GCP IAM API reorders bindings, current IAM policy diff contains duplicates or adds and removes the same bindings.

It would be great if `google_iam_policy` would have schema for IAM policy, so that it could be properly rendered as list of unordered bindings. In such case IAM diff would be much more readable.

### Affected Resource

* google_iam_policy

### Terraform Configuration

Below is shown just one of the examples, where one IAM binding is duplicated.

```tf
resource "google_project_iam_policy" "gcp_project" {
  project = "gcp-project-id"
  policy_data = "${data.google_iam_policy.gcp_project_policy.policy_data}"
}

data "google_iam_policy" "gcp_project_policy" {
  binding {
    role = "roles/owner"
    members = [
      "user:name.surname@example.com"
    ]
  }
}
```

#### Plan Output

```
  # google_project_iam_policy.gcp_project will be updated in-place
  ~ resource "google_project_iam_policy" "gcp_project" {
        etag        = "BwWJ37ny6K4="
        id          = "gcp-project-id"
      ~ policy_data = jsonencode(
          ~ {
              ~ bindings = [
                  ~ {
                        members = [
                            "user:name.surname@example.com",
                        ]
                      ~ role    = "roles/bigquery.metadataViewer" -> "roles/owner"
                    },
                    {
                        members = [
                            "user:name.surname@example.com",
                        ]
                        role    = "roles/owner"
                    },
                  - {
                      - members = [
                          - "user:name.surname@example.com",
                        ]
                      - role    = "roles/viewer"
                    },
                ]
            }
        )
        project     = "gcp-project-id"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

#### Expected Behavior
Terraform diff should show that `roles/bigquery.metadataViewer` and `roles/viewer` IAM roles will be removed.

#### Actual Behavior
Terraform diff shows that `roles/bigquery.metadataViewer` will be changed to `roles/owner` despite the latter role already existing in the diff. In GCP you can't have duplicated bindings for the same users and resources. 

#### Steps to Reproduce
1. Requires setting up GCP project
1. `terraform apply` on GCP project
1. Grant yourself `roles/bigquery.metadataViewer` and `roles/viewer` IAM roles
1. Run `terraform plan`

### References

* hashicorp/terraform#21473
* #2903

**Comment by pdecat** [comment]
Wouldn't a `DiffSuppressFunc` function be able to sort the IAM bindings by role and then their members alphabetically just like what's read from the API before comparing the values?

**Comment by marcin-kolda** [comment]
If Google provider would sort IAM bindings in both `google_iam_policy` and IAM response before returning it to diff renderer that would be great.

**Comment by pdecat** [comment]
The IAM response is already returning the bindings sorted by their role name.

I've submitted #3855 that sorts the IAM policy bindings returned by the datasource and it greatly improves the diff.
