### ISSUE TITLE
Missing monitoring-read scope.

### ISSUE THREAD

**Issue by wiktor2200** [terraform-providers/terraform-provider-google#3736]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
There is missing google_scope: `monitoring-read`

This scope can be useful in read-only monitoring cases.
https://www.googleapis.com/auth/monitoring.read it exists, so it can be used.
More info: https://developers.google.com/identity/protocols/googlescopes#monitoringv3

### New or Affected Resource(s)

* google_service_scope

**Comment by wiktor2200** [comment]
https://github.com/terraform-providers/terraform-provider-google/pull/2813/

**Comment by paddycarver** [comment]
This has been merged and released, so I'm going to close this issue out. If this is not actually resolved, my apologies for the error, please feel free to open a new issue.
