### ISSUE TITLE
It's very unobvious what id to provide to `import google_compute_address`

### ISSUE THREAD

**Issue by gdubicki** [terraform-providers/terraform-provider-google#374]
### Terraform Version
Terraform v.0.10.3

### Affected Resource(s)
- google_compute_address

### Terraform Configuration Files
Doesn't matter.

### Debug Output
Doesn't matter?

### Expected Behavior

Terraform should provide a helpful example of google_compute_address ID that you have to provide for importing - that it's just a name of the address, not for example the long numeric id that you get with `gcloud compute addresses describe <name>`...

~It should also tell you that if the address is in other region than the default for your project, then you have to prepend it to the address region like "<region>.<name>"~

Update: actually you can't use this syntax, you need to temporarily change region in your provider... Thanks @selmanj !

### Actual Behavior
I got only the unfriendly error message: `Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?'`

### Steps to Reproduce
`terraform import google_compute_address.<some_name> <some_name>` if the address is in other region than the default for your project

### Important Factoids
Information at https://www.terraform.io/docs/providers/google/r/compute_address.html#import is not helpful at all.

**Comment by selmanj** [comment]
Note that the real problem here is that there's no way to specify the region during import; it defaults to what region you have set in your provider.

I think for regional resources, we might need to encode the region in the id if we want to be able to import them.

**Comment by gdubicki** [comment]
It looks like my compute address was not actually imported. It was in europe-west1, my default regions was us-central1, I changed it to europe-west1 temporarily and got successful output, but on the next `terraform plan` it wants to create this address again.. Should I file a separate ticket for this issue?

**Comment by rosbo** [comment]
No need to file an extra issue. I will make sure the import works properly when adding the region to the import id.

**Comment by selmanj** [comment]
Additionally, note that when using the workaround of setting your region on the provider before importing, the 'region' field is not set in the state file and will cause terraform to try to create the resource when you change it back (as mentioned by @gdubicki). Adding the proper value for 'region' to the state file fixes the issue.

I think once @rosbo adds region to the import id, this additional pain point won't occur.

**Comment by rosbo** [comment]
@gdubicki I improved the import functionality for compute_address. It should now support import from a region or project different from the default ones set. The fix will be part of our next release.

Thanks
