### ISSUE TITLE
google_container_cluster does not implement database_config as specified in documentation

### ISSUE THREAD

**Issue by thisnick** [terraform-providers/terraform-provider-google#3743]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.13
+ provider.google v2.7.0
+ provider.google-beta v2.3.0
+ provider.kubernetes v1.6.2
+ provider.local v1.2.2
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

`google_container_cluster`

### Terraform Configuration Files

```tf
resource "google_container_cluster" "test" {
  provider = "google-beta"

  project     = "${var.project}"
  name        = "${var.env}-${var.location}-${var.name}"
  location    = "${var.location}"
  description = "${var.env_long} GKE Cluster for ${var.env}-${var.location}-${var.name}"
  network     = "${var.network}"
  subnetwork  = "${var.subnetwork}"


  database_encryption {
    state = "${var.use_database_encryption_key ? "ENCRYPTED" : "DECRYPTED"}"
    key_name = "${var.use_database_encryption_key ? "" : google_kms_crypto_key.container_key.self_link}"
  }
}

```

### Debug Output
Too long...

### Panic Output

N/A

### Expected Behavior

Terraform implements `database_encryption` as described in [official documentation](https://www.terraform.io/docs/providers/google/r/container_cluster.html#database_encryption).

### Actual Behavior

Terraform complains `database_encyrption` is not supported:
```
Error: module.gke_tools_cluster-1.google_container_cluster.test: : invalid or unknown key: database_encryption
```

### Steps to Reproduce

Use the terraform file above and run `terraform plan` or `terraform apply`

### Important Factoids

No

### References

N/A

**Comment by rileykarson** [comment]
We have passing test including this feature: https://github.com/terraform-providers/terraform-provider-google-beta/blob/master/google-beta/resource_container_cluster_test.go#L3333-L3362

Is it possible that your module is using the `google` provider instead of `google-beta` somehow? Debug logs are a big help in cases like this, and they can be attached using https://gist.github.com/ if they're too long.

**Comment by thisnick** [comment]
I think for some reason my `beta` is locked at 2.3.0. I will try to upgrade it.
