### ISSUE TITLE
How to output attributes of instances from terraform.tfstate?

### ISSUE THREAD

**Issue by ameyaptk** [terraform-providers/terraform-provider-google#3754]
I'm executing a GCP module to create a service-account. 

> main.tf

 ```

    resource "google_service_account" "gsvc_account" {
      account_id   = "xxx"
      display_name = ""
      project = "proj-yyy"
    }
    output "account_id" {
      value = "${google_service_account.gsvc_account.account_id}"
    }

```

Once the account is created, a `terraform.tfstate` file is created containing all details of the account. 

> terraform.tfstate

```

    {
      "version": 4,
      "terraform_version": "0.12.0",
      "serial": 3,
      "lineage": "aaaa-bbbb-cccc",
      "outputs": {
        "xxx": {
          "value": "xxx",
          "type": "string"
        }
      },
      "resources": [
        {
          "module": "module.gsvc_tf",
          "mode": "managed",
          "type": "google_service_account",
          "name": "gsvc_account",
          "provider": "provider.google",
          "instances": [
            {
              "schema_version": 0,
              "attributes": {
                "account_id": "xxx",
                "display_name": "",
                "email": "xxx@yyy.com",
                "id": "projects/proj-yyy/serviceAccounts/xxx@yyy.com",
                "name": "projects/proj-yyy/serviceAccounts/xxx@yyy.com",
                "policy_data": null,
                "project": "proj-xxx",
                "unique_id": "10891885"
              }
            }
          ]
        }
      ]
    }


```

As you can see above, in the module, I'm outputing the `account_id` input variable. Is there a way to output the `attributes` viz. `id`, `name` etc. so that they can be accessed by another module? The `attributes` are computed after the resource is created.

**Comment by rileykarson** [comment]
`name` can be outputted by the module, similar to any other field. This would need to be done in the module, and isn't something that can be resolved from the provider.

**Comment by ameyaptk** [comment]
Perfect! That worked. Thanks! Is there a way to see which attributes can be 'outputed' and which can't?

**Comment by ameyaptk** [comment]
Nvm. Found it in provider documentation- https://www.terraform.io/docs/providers/google/r/google_service_account.html
