### ISSUE TITLE
google_cloud_scheduler_job requires App Engine application even while using http_target

### ISSUE THREAD

**Issue by caquino** [terraform-providers/terraform-provider-google#3758]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.0
+ provider.google v2.7.0
+ provider.google-beta v2.7.0
```

### Affected Resource(s)

* google_cloud_scheduler_job

### Terraform Configuration Files

```tf
provider "google" {
  project = "XXXXX"
  region  = "us-central1"
}

resource "google_cloud_scheduler_job" "updater" {
  name        = "test-updater"
  description = "test-updater"
  schedule    = "*/8 * * * *"
  time_zone   = "GMT"

  http_target {
    http_method = "GET"
    uri         = "https://www.google.com/"
  }
}

```

### Debug Output

https://gist.github.com/caquino/b189ee394e08bd1cf4df6c9cd9aa5f2c

### Panic Output
Not applicable

### Expected Behavior

The job scheduler with an HTTP target should have been provisioned.

### Actual Behavior

The job scheduler error message points out for an error related to an App Engine scheduler, even with the scheduler having an http_target.
```
Error: Error creating Job: googleapi: Error 404: The project xxxx does not contain an App Engine application. Please visit https://console.developers.google.com/appengine?project=xxxx to to add an App Engine application.
```

After additional tests, I was able to make it work when setting the timezone to "Etc/UTC", so it appears it's an error related to a wrong timezone, but sadly the error is not clear about it.

### Steps to Reproduce

1. Save the terraform configuration attached to this ticket to a file
2. Add the extra provider block
3. `terraform apply`

### Important Factoids

Not applicable

### References

Not applicable

**Comment by rileykarson** [comment]
I submitted a documentation fix that will close this out, this is a restriction of the API. See https://cloud.google.com/scheduler/docs/#supported_regions.

You can use https://www.terraform.io/docs/providers/google/r/app_engine_application.html to create an App Engine app in your project.

**Comment by caquino** [comment]
@rileykarson actually just changing my timezone to a correct one and it worked. Sadly the error message was not that helpful.

**Comment by rileykarson** [comment]
Huh! I have no explanation for that one. I'll leave this open to track adding the docs mirroring upstream in the provider.
