### ISSUE TITLE
Google Compute Forwarding Rule : invalid or unknown key: all_ports

### ISSUE THREAD

**Issue by Abrams88** [terraform-providers/terraform-provider-google#3764]
I am facing an issue when I am trying to configure a

> google_compute_forwarding_rule

specifying as

> all_ports = true

When I am executing a

> terraform plan

I receive the following error message:

> invalid or unknown key: all_ports

My Tf version and provider version are:
Terraform v0.11.13

provider.google v2.0.0

I tried with different google provider versions, like 1.19.0 and 2.1.0 but the same issue.
Furthermore, I have specified as protocol type and load balancer scheme as below:

```
  ip_protocol           = "TCP"
  load_balancing_scheme = "INTERNAL" 
```
Any suggestions what I am doing wrong and why this key is not recognised?
I am pretty sure that I dont have any typos error.

**Comment by chrisst** [comment]
`all_ports` was added in version `2.3.0` of the GA provider, previously to this it was a `beta` only field.
See the changelog for more details https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#230-march-26-2019

**Comment by Abrams88** [comment]
Good morning @chrisst , 
Many thanks for that. It worked! that was the issue, I changed to 2.3.0 version and I dont receive any error. 
Many thanks for your help!.
