### ISSUE TITLE
Missing auth method on backend which is on provider

### ISSUE THREAD

**Issue by gtmtech** [terraform-providers/terraform-provider-google#3806]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

terraform 0.11.13

### Affected Resource(s)

State files in gcs backend

### Description

Google provider supports access_token which is perfect for those of us who really dont like using long-lived keys for anything due to security risks associated-  see: `https://www.terraform.io/docs/providers/google/provider_reference.html`, `access_token` field. 

Perfect! We can use this for service-account generated temporary access tokens e.g. for 20 minutes to an hour, and no permanent keys are stored anywhere.

But `backend` `gcs` does not support this method. See `https://www.terraform.io/docs/backends/types/gcs.html#configuration-variables` - so we're back to using application-default-credentials = long-lived keys again

Can the backend support the good practice that provider supports too please?

### References

* https://www.terraform.io/docs/providers/google/provider_reference.html
* https://www.terraform.io/docs/backends/types/gcs.html#configuration-variables

**Comment by emilymye** [comment]
Closing as duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/3821
