### ISSUE TITLE
Migrating from 2.4.0 / terraform 0.11 to 2.5+ / terraform 0.12

### ISSUE THREAD

**Issue by fproulx-eoscanada** [terraform-providers/terraform-provider-google#3812]
I'm trying to upgrade to 2.5+ with terraform 0.12. I was able to adapt the minor syntactic sugar changes, but then I'm left with pretty but reconciliation issues where K8S cluster , VPC network, etc. resources don't work well anymore. I get a bunch of changes which it says can only be done by destroy / re-create, which of course I cannot afford with production setup.

I walkthrough with clear path to solving those issues would be helpful.

**Comment by Chupaka** [comment]
1) Please use issue templates.
2) Please add more details to your issue.
