### ISSUE TITLE
Allow to use GOOGLE_OAUTH_ACCESS_TOKEN in backend configuration the same way that is used in the provider configuration

### ISSUE THREAD

**Issue by primeroz** [terraform-providers/terraform-provider-google#3821]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
I am using vault to generate dynamic Google Tokens to then use in terraform run.

I am able to use a GOOGLE_OAUTH_ACCESS_TOKEN environment variable for the google provider as documented [here](https://www.terraform.io/docs/providers/google/provider_reference.html#access_token-1) but it does not seem to work/propagate in the backend definition for remote-states 

regardless of what i try i get

```
Initializing the backend...                                                     
                          
Error configuring the backend "gcs": storage.NewClient() failed: dialing: google: could not find default credentials. See https://developers.google.com/accounts
/docs/application-default-credentials for more information.
                                                                                
Please update the configuration in your Terraform files to fix this error
then run this command again.   
```

### New or Affected Resource(s)

* google backend for remote state

**Comment by emilymye** [comment]
The GCS backend is actually part of the Terraform core and doesn't implicitly share credentials with the provider - I'm guessing it just uses the same environment variable. Adding @paddycarver to see if he'd be able to add this to the GCS backend

**Comment by primeroz** [comment]
That make lot of sense.

I will raise a case on upstream

**Comment by emilymye** [comment]
@primeroz no worries, thanks for submitting the issue! It's nice to see people using the GCP secrets backend with Terraform :)
