### ISSUE TITLE
Search console domains

### ISSUE THREAD

**Issue by jleclanche** [terraform-providers/terraform-provider-google#3827]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There doesn't appear to be resources for the Google Search Console sites:
https://developers.google.com/webmaster-tools/search-console-api-original/v3/sites/add

**Would these go in the google terraform provider or would it belong in a separate provider?**

### New or Affected Resource(s)

* google_search_console_domain
* google_search_console_site

### Potential Terraform Configuration

```tf
resource "google_search_console_site" "https_example_com" {
    site_url = "https://example.com"
}

resource "google_search_console_domain" "example_com" {
    domain = "example.com"  # Maps to sc-domain:example.com
}

# Verification examples

resource "cloudflare_record" "example_com_google_verification" {
    domain = "example.com"
    name = "example.com"
    type = google_search_console_domain.example_com.dns_txt_verification.type
    value = google_search_console_domain.example_com.dns_txt_verification.value
}

# Outputs:
# google_search_console_domain.example_com.verification_tag = "google-site-verification"
# google_search_console_domain.example_com.verification_value = "<code>"
```

**Comment by jleclanche** [comment]
I'm guessing these go in a separate provider as they're not really part of the same API as the rest?

**Comment by emilymye** [comment]
My response is the same as aboves - the Google in terraform-google-provider actually means "Google Cloud", so we'd probably not fold it into this provider.

**Comment by jleclanche** [comment]
@emilymye Thanks for the clarification. Is there an existing provider this better fits into or would this be a new one?
