### ISSUE TITLE
Error on deleting networks if routes are added not by terraform

### ISSUE THREAD

**Issue by kigawas** [terraform-providers/terraform-provider-google#3831]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.1

### Affected Resource(s)

* google_compute_network.vpc_network

### Terraform Configuration Files

```tf
provider "google" {
  version = "~> 2.7"

  project = "YOUR_PROJECT"
  region  = "asia-northeast1"
  zone    = "asia-northeast1-a"
}
resource "google_compute_network" "vpc_network" {
  name                    = "test-network"
  auto_create_subnetworks = true
}

```

### Expected Behavior

Delete vpc networks normally

### Actual Behavior
Cannot delete the network and it complains:

```
Error: Error waiting for Deleting Network: The network resource 'projects/YOUR_PROJECT/global/networks/test-network' is already being used by 'projects/YOUR_PROJECT/global/routes/test-route'
```

### Steps to Reproduce

1. `terraform apply`
2. Add a route on gcp manually
3. `terraform destroy`

### Important Factoids

No. Just 3 steps to simply reproduce.

### References

Maybe #89

**Comment by kigawas** [comment]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.



### Terraform Version
Terraform v0.12.1



### Affected Resource(s)



* google_compute_network.vpc_network

### Terraform Configuration Files



```tf
provider "google" {
  version = "~> 2.7"

  project = "YOUR_PROJECT"
  region  = "asia-northeast1"
  zone    = "asia-northeast1-a"
}
resource "google_compute_network" "vpc_network" {
  name                    = "test-network"
  auto_create_subnetworks = true
}

```

### Debug Output

### Panic Output

### Expected Behavior

Delete vpc networks normally

### Actual Behavior
Cannot delete the network and it complains:

```
Error: Error waiting for Deleting Network: The network resource 'projects/YOUR_PROJECT/global/networks/test-network' is already being used by 'projects/YOUR_PROJECT/global/routes/test-route'
```

### Steps to Reproduce



1. `terraform apply`
2. Add a route on gcp manually
3. `terraform destroy`

### Important Factoids

No. Just 3 steps to simply reproduce.

### References

Maybe #89

**Comment by emilymye** [comment]
This is to be expected. Terraform generally will not destroy things it doesn't directly manage.

**Comment by kigawas** [comment]
@emilymye Thanks for reply. Actually if you use kubeadm init to create a kubernetes cluster on GCP, k8s'll create routes for networks and when it'll come to this error when destroy the cluster. In this case, an option like "delete anyway" may help.
