### ISSUE TITLE
Changing instance size doesnt update DNS

### ISSUE THREAD

**Issue by jwcmd** [terraform-providers/terraform-provider-google#3835]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.1
+ provider.aws v2.14.0
+ provider.google v2.8.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```
resource "google_compute_instance" "testhost" {
  name          = "jsw-test"
  machine_type  = "n1-standard-1"
  zone          = "us-west1-a"
  project       = var.projectname
  tags          = ["mytest"]

  boot_disk {
    initialize_params {
      image = "ubuntu-1604-xenial-v20190605"
      size = 100
    }
  }

  network_interface {
    subnetwork          = "us-west1"
    subnetwork_project  = var.projectname
    access_config {
      #Ephemeral IP
    }
  }
  allow_stopping_for_update = true

  service_account {
    scopes = ["userinfo-email", "compute-ro", "storage-rw", "cloud-platform"]
  }
}
resource "aws_route53_record" "myname" {
  zone_id = data.aws_route53_zone.myzone.zone_id
  name    = "myname.example.com"
  type    = "A"
  ttl     = "1800"
  records = google_compute_instance.testhost.*.network_interface.0.network_ip
}
```

### Expected Behavior

When changing the machine type of a GCP instance that has a DNS record associated with it, because this results in a stop/start of the instance which leads to an IP change, the DNS record should be updated with the IP address of the instance after it has come up.

### Actual Behavior

Changing the machine type results in stop/starting the instance, resulting in a new IP address, but does not update the DNS record.
Resolving this requires running terraform apply a second time.

### Steps to Reproduce

Create a GCP instance with terraform
Create a DNS entry associated with the IP of that instance
Change the machine type of the GCP instance with terraform, and run apply.
You will observe that terraform wants to change the instance machine type only, although the IP address will change as well, requiring a DNS update.

### Important Factoids

I believe this appears with any DNS service provider record, but have only tested it with aws_route53_record resources.

I apologize if this is a duplicate, I checked both Terraform's Issues and the Issues for this provider but couldn't find anything that looked similar. 

We understand this may be a workflow issue, but we feel this is a bug because resolving this requires running terraform a second time which, to us, violated the principle of least astonishment. We're open to alternative solutions.

### References

**Comment by emilymye** [comment]
I believe this is actually due to ephemeral IP addresses, as I just changed my machine type and my IP address didn't change. It just so happened that the internal address of your instance changed, and because this is a change made outside of Terraform, it then makes sense that you'd need to apply again to reach the state that Terraform is aware of. If you want to avoid this, I'd use a static internal IP (since you are using internal IP network_ip, using the external address would be access_config.nat_ip).
