### ISSUE TITLE
Documentation for legacy/old provider versions

### ISSUE THREAD

**Issue by glakshmeepathi** [terraform-providers/terraform-provider-google#3849]
I am working on a particular provider version 1.10.0 but the docs seem to always point to the latest. Though the breaking changes are documented , there is no way to distinguish if an attribute is available or not in the older version. It has to be trial and error always.

For example, "kms_key_self_link" introduced in "boot_disk" under "google_compute_instance". I believe it is introduced in 2.6.0. Now I can't say if this attribute is available in 2.5.0 or 1.10.0 and so on.

**Comment by emilymye** [comment]
We have brought up having docs at different versions with HashiCorp and this is potentially happening  soon, please remain patient! 

 In the meantime, generally there are a few ways outside of documentation to view the features added per version. The easiest would be to look at the [CHANGELOG.md](https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md), but sometimes a few things get left out of the CHANGELOG or aren't exactly describing the fields added. If you want to be even more specific/exact, you can always view the code at the specific release tag in the repo - for example [2.5.0](https://github.com/terraform-providers/terraform-provider-google/tree/v2.5.0)
