### ISSUE TITLE
Importing SOA google_dns_record_set causes: Error: project: required field is not set

### ISSUE THREAD

**Issue by charlex** [terraform-providers/terraform-provider-google#3853]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.1
provider.google v2.8.0
provider.google-beta v2.8.0

### Affected Resource(s)

* google_dns_record_set

### Terraform Configuration Files

```tf

resource "google_dns_managed_zone" "foobar" {
  labels      = {}
  name        = "foobar"
  dns_name    = "foobar.com."
  project     = "foobar-1"
  description = "Managed by Terraform"

  lifecycle {
    prevent_destroy = true
  }

  visibility = "public"

  dnssec_config {
    kind          = "dns#managedZoneDnsSecConfig"
    non_existence = "nsec3"
    state         = "off"
    default_key_specs {
      algorithm  = "rsasha256"
      key_length = 2048
      key_type   = "keySigning"
      kind       = "dns#dnsKeySpec"
    }
    default_key_specs {
      algorithm  = "rsasha256"
      key_length = 1024
      key_type   = "zoneSigning"
      kind       = "dns#dnsKeySpec"
    }
  }

  timeouts {}
}


resource "google_dns_record_set" "foobar_soa" {
  name = "foobar.com."
  type = "SOA"
  ttl  = 30

  project      = "${google_dns_managed_zone.foobar.project}"
  managed_zone = "${google_dns_managed_zone.foobar.name}"

  rrdatas = ["xx.xx.xx.xx.xx"]
}
```

### Debug Output

```sh
terraform import -provider=google google_dns_record_set.foobar_soa foobar/foobar.com./SOA.
google_dns_record_set.foobar_soa: Importing from ID "foobar/foobar.com./SOA."...
google_dns_record_set.foobar_soa: Import complete!
  Imported google_dns_record_set
google_dns_record_set.foobar_soa: Refreshing state... [id=foobar/foobar.com./SOA.]

Error: project: required field is not set
```

### Expected Behavior

Should not see:

```
Error: project: required field is not set
```

### Actual Behavior

DNS Record did not actually import

### Steps to Reproduce

1. `terraform import....` (See above import comment)
2. Running `terraform state list` does not show dns record

**Comment by danawillow** [comment]
My hypothesis is that you don't have a project set in your provider block or as an environment variable, is that correct @charlex? If so, then what's happening is that the resource doesn't yet know how to import record set resources that aren't in the provider-configured project (see related issue https://github.com/terraform-providers/terraform-provider-google/issues/3280), so it's failing. This is easy to fix though- I can get started on that right away.
