### ISSUE TITLE
`google_compute_url_map` continues to update even when fingerprint mismatch is encountered

### ISSUE THREAD

**Issue by garbetjie** [terraform-providers/terraform-provider-google#3867]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.2
+ provider.google v2.8.0
```

### Affected Resource(s)

* `google_compute_url_map`

### Terraform Configuration Files

* https://gist.github.com/garbetjie/d5c9b470cc27a90e450b0e70f4eabaf4#file-main-tf
* https://gist.github.com/garbetjie/d5c9b470cc27a90e450b0e70f4eabaf4#file-patch-diff
* https://gist.github.com/garbetjie/d5c9b470cc27a90e450b0e70f4eabaf4#file-remove-backend-sh

(README is provided in the gist)

### Debug Output

https://gist.github.com/garbetjie/d5c9b470cc27a90e450b0e70f4eabaf4#file-output-log

### Panic Output

None

### Expected Behavior

I expected 1 of 2 behaviours to happen:

* For the provider to refresh the url map, and update the fingerprint before updating, or
* For the provider to fail when a fingerprint mismatch occurs.

### Actual Behavior

When updating a url map externally (via some kind of create/destroy provisioner), the url map's fingerprint is changed. 

When the provider attempts to continue updating the url map, it will fail with an `Invalid fingerprint.` error. However, the provider sees this as retryable, and will continue to retry updating the url map until the resource's timeout is hit.

As far as I can tell, the fingerprint doesn't have a chance of changing to what the provider is using.

### Steps to Reproduce

All steps provided in gist: https://gist.github.com/garbetjie/d5c9b470cc27a90e450b0e70f4eabaf4#file-readme-md

### Important Factoids

None

### References

None

**Comment by danawillow** [comment]
Hi @garbetjie, thank you so much for the detailed logs and repro steps! That information is super helpful for us :)

I'm thinking about the best solution for this, but in the meantime, I'm not sure the config you've provided is the best way to handle what you're trying to do. The issue I'm seeing is that, even if this did work, the next run of TF will fail because the path matchers that were deleted are still defined in the config. I'd recommend looking into a TF-native way of accomplishing what you need to (without using gcloud as well), and I think that if you can do that, the fingerprint issue will go away. Let me know if you need help working out a config or if you'd like to try it on your own!

**Comment by garbetjie** [comment]
Hey @danawillow.

The main use case that I had for this was actually to work around something similar to https://github.com/hashicorp/terraform/issues/21766, where a backend service/bucket was being recreated before the url map was being updated. This would cause the update to fail, as the backend was still in use by the url map when being recreated. 

This was why I was trying to remove the path matcher from the url map in a destroy-time provisioner, considering it was going to be removed from the url map anyway.

But as to your last point, I agree. A TF-native way of doing it is _always_ preferred. I'll keep bashing away at it.

Is this still considered a bug? I'm happy to close it if it's not considered a bug by the TF team.

**Comment by danawillow** [comment]
Sure, let's go ahead and close this, but do post back once you've figured it out! I'm definitely curious to see what you come up with.
