### ISSUE TITLE
Attaching google_compute_resource_policy to a disk

### ISSUE THREAD

**Issue by jahantech** [terraform-providers/terraform-provider-google#3891]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
A resource "google_compute_resource_policy" was recently added to the beta provider and it does seem to create the resource correctly.

However, I don't see any traces of how I can attach it to an existing/new disk. Maybe I am missing something or it hasn't been implemented yet?

If it hasn't been implemented, this should be considered as an enhancement because even with the creation of resource policy, its not possible to automate the scheduled snapshotting of disks.

### New or Affected Resource(s)

google_compute_resource_policy

### References

https://github.com/terraform-providers/terraform-provider-google/issues/3062

**Comment by megan07** [comment]
Thanks @jahantech for opening this issue. It's been closed with #960 and will be released shortly.

**Comment by jeremyvisser** [comment]
Hi Megan,

Issue #960 doesn’t seem related at all to this issue. However, around the same time you made commit https://github.com/terraform-providers/terraform-provider-google-beta/commit/97fefe29061112bea0985acf8d353259cf34c37d which I’m guessing you intended to link to instead?

**Comment by chrissng** [comment]
@jeremyvisser yes, it seems that we will have to wait for PR https://github.com/terraform-providers/terraform-provider-google-beta/pull/960/files to land as a new release.

In the interim, consider local-exec `gcloud beta compute disks add-resource-policies [DISK_NAME] \
    --resource-policies [SCHEDULE_NAME] \
    --zone [ZONE]`

**Comment by jeremyvisser** [comment]
Ahhh, now I see what went wrong in the description:

https://github.com/terraform-providers/terraform-provider-google-beta/pull/960
versus
#960

All good, cheers!

**Comment by Lirt** [comment]
Hey guys,

I'm testing this feature with beta-provider, but so far it forces replacement of resource policies, which forces replacement of the whole disk.

When I attach snapshot schedule to disk manually, it works without the need to stop or recreate anything.

Is this intended, or maybe some kind of bug/unfinished work?
