### ISSUE TITLE
Remove deprecated internalCheckers from google_monitoring_uptime_check_config

### ISSUE THREAD

**Issue by jahantech** [terraform-providers/terraform-provider-google#3899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

Spent couple of hours trying to get my head around this one, the is_internal shouldn't be in the docs or the code and API doesn't support internalCheckers anymore. 

### Terraform Version
Terraform v0.11.14

### Affected Resource(s)
google_monitoring_uptime_check_config

### Terraform config
```
resource "google_monitoring_uptime_check_config" "example_check" {
  display_name = "${var.cluster_name}-http-check"
  timeout = "60s"

  http_check{
    use_ssl = true
  }
  is_internal = true

  internal_checkers {
    network = "${data.google_compute_network.current.self_link}"
  }

  monitored_resource {
    type = "uptime_url"
    labels = {
      project_id = "${var.project}"
      host = "${var.cluster_name}"
    }
  }
}
```
### Output

```
 Invalid JSON payload received. Unknown name "is_internal" at 'uptime_check_config': Cannot find field.
```

### Expected Behavior

Should have created the check.

### Actual Behavior

Doesn't create the check with is_internal = true and internalCheckers is now deprecated according to API Docs.

### References

Documentation where it says its deprecated:
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.uptimeCheckConfigs

![Screenshot 2019-06-21 at 17 34 20](https://user-images.githubusercontent.com/13733348/59937623-d8f5f800-944a-11e9-8724-8736978c742c.png)

**Comment by rileykarson** [comment]
Hmm, a deprecated field should continue to work. Have you used this field in the past? & would it be possible to attach debug logs here?

**Comment by jahantech** [comment]
Thank you for your response. The problem is that, internalCheckers, require a field to be field that is "is_internal". But if you try to pass that in, the terraform returns:
```
Invalid JSON payload received. Unknown name "is_internal" at 'uptime_check_config': Cannot find field.```

Reference:
https://www.terraform.io/docs/providers/google/r/monitoring_uptime_check_config.html#is_internal

Also in the API definition I don't see the isInternal/is_internal flag. 

https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.uptimeCheckConfigs/create
![Screenshot 2019-06-24 at 17 59 34](https://user-images.githubusercontent.com/13733348/60037596-dfce7600-96a9-11e9-977e-0c76e0c394b1.png)

**Comment by rileykarson** [comment]
The field appeared in a past revision of the documentation, around when we wrote the Terraform support for the resource. We'd used our code generator, and unfortunately it doesn't appear the field was tested. Based on the hard removal of the field, I suspect it didn't actually work, and was previously inadvertently surfaced in the REST docs.

I'll follow through with the product team to see what's happening here, and remove this from our docs if appropriate.

**Comment by rileykarson** [comment]
Confirmed upstream, this field was erroneously surfaced to the cloud.google.com docs and then from there to Terraform. Leaving this open to track removal from the provider config + docs.

**Comment by rileykarson** [comment]
Closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/1974
