### ISSUE TITLE
[Feature] Set object versioning for google storage buckets

### ISSUE THREAD

**Issue by l-wang** [terraform-providers/terraform-provider-google#390]
### Terraform Version
`v0.10.3`

### Affected Resource(s)
- google_storage_bucket

### Terraform Configuration Files
```hcl
resource "google_storage_bucket" "foo" {
  name     = "foo"
  location = "${var.gcp_region}"
  storage_class = "REGIONAL"
  versioning = "true"
}
```

### Expected Behavior
I would like to be able to enable object versioning on a [bucket](https://cloud.google.com/storage/docs/using-object-versioning).

### Actual Behavior

```
$ terraform plan
1 error(s) occurred:

* google_storage_bucket.gpdb-release-builds: : invalid or unknown key: versioning
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

This is a feature request, and so the suggested field doesn't exist which is expect.

### Important Factoids
N/A

### References
To the best of our knowledge we were unable to find a relevant issue.

**Comment by Stelminator** [comment]
Slight modification, since versioning is an object:

```terraform
resource "google_storage_bucket" "foo" {
  name     = "foo"
  location = "${var.gcp_region}"
  storage_class = "REGIONAL"
  versioning = {
    enabled = "true"
  }
}
```
