### ISSUE TITLE
Unable to create bucket in tf0.12.2

### ISSUE THREAD

**Issue by sce81** [terraform-providers/terraform-provider-google#3905]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

tf0.12.2
google 2.8.0

### Affected Resource(s)

* google_storage_bucket

### Terraform Configuration Files

```tf

resource "google_storage_bucket" "main" {
  name      = var.bucket_name
  location  = var.bucket_location
  project   = var.project

  versioning {
    enabled = var.versioning_enabled
  }
  storage_class = var.storage_class

  labels = {
    name        = var.bucket_name
    environment = var.env
    application = var.app_name
    team        = var.team
    cost_type   = var.cost_type
  }
}
```

### Expected Behavior

module should be re-usable and a new bucket created

### Actual Behavior
  + create

Terraform will perform the following actions:

  # module.database_backups.google_storage_bucket.main will be created
  + resource "google_storage_bucket" "main" {
      + force_destroy = false
      + id            = (known after apply)
      + labels        = {
          + "application" = "backups"
          + "cost_type"   = "static"
          + "environment" = "production"
          + "name"        = "database_backups"
          + "team"        = "infra"
        }
      + location      = "EUROPE-WEST1"
      + name          = "database_backups"
      + project       = "COMPANY_NAME"
      + self_link     = (known after apply)
      + storage_class = "STANDARD"
      + url           = (known after apply)

      + versioning {
          + enabled = true
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Error: googleapi: Error 409: Sorry, that name is not available. Please try a different one., conflict

  on .terraform/modules/database_backups/main.tf line 1, in resource "google_storage_bucket" "main":
   1: resource "google_storage_bucket" "main" {

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sce81** [comment]
hmm. changing the name tag seemed to resolve the issue. 
i have no buckets with this name. perhaps its a reserved name?

**Comment by rileykarson** [comment]
There are some rules listed at https://cloud.google.com/storage/docs/naming#considerations, probably most notably bucket names are required to be globally unique across all GCS users. I'd imagine you ran into that, so as you found changing the bucket name resolves the issue.
