### ISSUE TITLE
pubSubConfigs not exposed for GCP cloud source resources

### ISSUE THREAD

**Issue by sitepodmatt** [terraform-providers/terraform-provider-google#3917]
pubSubConfigs not exposed for Cloud Source repo resources or GCP projects. They exist in the vendored dependencies
https://github.com/terraform-providers/terraform-provider-google/blob/master/vendor/google.golang.org/api/sourcerepo/v1/sourcerepo-gen.go#L849

These are required to do stuff like add a pubsub topic for cloud source repo pushes either at a project or individual repo level. 

Thanks to Cameron from Pulumi for helping me troubleshoot this

**Comment by AniX** [comment]
This is a very useful feature that is missing. Is there a problem with the vendored dependencies?
