### ISSUE TITLE
Avoid nested objects with a single optional field

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#3928]
For example, GKE `addons_config` has a bunch of nested objects with a single boolean field inside them:
```
			"addons_config": {
				Type:     schema.TypeList,
				Optional: true,
				Computed: true,
				MaxItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"http_load_balancing": {
							Type:     schema.TypeList,
							Optional: true,
							Computed: true,
							MaxItems: 1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"disabled": {
										Type:     schema.TypeBool,
										Optional: true,
									},
								},
							},
						},
						"horizontal_pod_autoscaling": {
							Type:     schema.TypeList,
							Optional: true,
							Computed: true,
							MaxItems: 1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"disabled": {
										Type:     schema.TypeBool,
										Optional: true,
									},
								},
							},
						},
...etc
```
This means that hypothetically, a user could put the following in their schema:
```
addons_config {
  http_load_balancing {
  }
}
```
From the user's point of view, this behavior would probably just take the API-level default. However, what it actually does is set disabled = false, since we ForceSend the field. If we decide to keep these fields nested in this way, we should make the booleans Required in order to make their behavior more clear.

Marking as 3.0 since this would be a breaking change.

**Comment by kibbles-n-bytes** [comment]
Is the GKE API's default behavior different than assuming `"disabled": false` when the object is empty? I just tried creating clusters through the API explorer with `"httpLoadBalancing": {}` and `"kubernetesDashboard": {}`, and got behavior consistent with that interpretation: When not specified, HTTP load balancing is on by default and Kubernetes dashboard is off by default, but passing the empty object to either of them forces enablement. Are there any APIs that break that pattern?

**Comment by danawillow** [comment]
I believe this is now done, so closing.
PRs:
- https://github.com/GoogleCloudPlatform/magic-modules/pull/2608
- https://github.com/GoogleCloudPlatform/magic-modules/pull/2639
- https://github.com/GoogleCloudPlatform/magic-modules/pull/2645

**Comment by danawillow** [comment]
Just kidding, apparently there's a few more.

**Comment by megan07** [comment]
This can be closed by the PRs referenced above.
