### ISSUE TITLE
Help me figure out how to add google_filestore_instance documentation

### ISSUE THREAD

**Issue by jmcgeheeiv** [terraform-providers/terraform-provider-google#3933]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I would like to enhance the documentation for `google_filestore_instance`, but I cannot figure
out how. Searching the files, the non-generated file I found is
`vendor/google.golang.org/api/file/v1beta1/file-api.json`. Really? Is this the right file?

I love to write technical documentation. Help me with this and I'll contribute. I might even
write something to help other people who want to contribute documentation figure it out.

I was going to document the following. I would be interested to hear if you think these are useful:
* `capacity_gb` must be at least 1024 GB for the standard tier,  2560 GB for the premium tier
* You must install using a (service) account with the _Cloud Filestore Editor_ role

### New or Affected Resource(s)

`google_filestore_instance` documentation.

### Potential Terraform Configuration

No change in usage.

### References

None

* #0000

**Comment by Chupaka** [comment]
Here are the files you're looking for, I believe: https://github.com/GoogleCloudPlatform/magic-modules/tree/master/products/filestore

**Comment by rileykarson** [comment]
Yep! Generated files come from Magic Modules, under their corresponding directory under `products/`. `api.yaml` is the best place to modify. https://github.com/GoogleCloudPlatform/magic-modules#getting-started-with-magic-modules can help with MM.

**Comment by jmcgeheeiv** [comment]
I entered a pull request over there. Thank you for your time and your already awesome documentation.
