### ISSUE TITLE
google.pubsub.v1.Publisher.CreateTopic fails, latency might be more than 30 seconds

### ISSUE THREAD

**Issue by higef** [terraform-providers/terraform-provider-google#3935]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.13

### Affected Resource(s)

google_pubsub_topic

### Terraform Configuration Files
```
resource "google_pubsub_topic" "topic" {
  count = "${length(var.topic)}"
  name  = "${var.topic[count.index]}"
  timeouts {
    create = "5m"
  }
}
```
### Actual Behavior

**terraform apply** fails after 30 seconds when creating Google PubSub Topic with message:
`google_pubsub_topic.topic.5: Error creating Topic: Put https://pubsub.googleapis.com/v1/projects/***/topics/***?alt=json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

### Important Factoids

Latency of the google.pubsub.v1.Publisher.CreateTopic Method is  ~50 seconds
Number of PubSub Topics/Subscriptions ~1000-2000

### Expected Behavior

Option to configure API response timeout

**Comment by rileykarson** [comment]
Can you confirm your provider version, and provide debug logs? The default timeout on that request is 4 minutes, and it _should_ be 5 based on your config.

**Comment by rileykarson** [comment]
Closing as stale. Please file again if you continue encountering this issue.
