### ISSUE TITLE
Add support for Cloud Functions IAM, document private-by-default by 2019/11/01

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#3944]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

On Nov 1, 2019 Cloud Functions will go private by default. We should add IAM support and get users ready for the switch far in advance.

### New or Affected Resource(s)

* google_cloudfunctions_function
* google_cloudfunctions_function_iam_*

**Comment by rileykarson** [comment]
This isn't technically a breaking change for Terraform, but it is from the API.

**Comment by jamiekt** [comment]
Hello @rileykarson , I see this issue is currently unassigned. Has there been any discussions pertaining to working on this issue?
Also interested to know if 15 thumbsups (which the issue currently has) is considered a significant enough number to warrant discussion or whether 1 is just a drop in the ocean?

**Comment by rileykarson** [comment]
We have nobody actively assigned yet, but we're aware of the severity of the issue and will ensure that we provide IAM support for a reasonable window before the API-side change.

**Comment by jamiekt** [comment]
Hi @rileykarson / @emilymye , 
We're 17 days away from cloud functions going private by default, just wondering if you know of any progress on this particular issue?

**Comment by rileykarson** [comment]
Ah- looks like we didn't close this issue out or link the appropriate PRs. Sorry about that! We've supported the appropriate IAM resources since `2.15.0`, and put up the private-by-default documentation in `2.16.0`.

https://github.com/GoogleCloudPlatform/magic-modules/pull/2297 added support for IAM resources while https://github.com/GoogleCloudPlatform/magic-modules/pull/2321 added the docs.

The correctly formatted example on this page shows how to create a public fn post-change: https://www.terraform.io/docs/providers/google/r/cloudfunctions_function.html

I'll put out a change fixing the formatting on the page.

**Comment by jamiekt** [comment]
fantastic, thanks @rileykarson
