### ISSUE TITLE
Add retries for more network related errors

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#3957]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

Errors like these pop up every so often in tests and bug reports:
* read: connection reset by peer
* net/http: request canceled (Client.Timeout exceeded while awaiting headers)

We should probably consider these retryable, or hard-code in a certain number of tries, since  there's not much a user can do about them besides just try again.

**Comment by danawillow** [comment]
Jan 9 2020 TPG run has a few examples of "read: connection reset by peer" in case anyone needs debug logs for a failure

**Comment by emilymye** [comment]
Some tests were fixed, but I think various libraries are still returning weird error formats, keeping open to track removing debug logs from a fix

**Comment by emilymye** [comment]
Moving to near-term goals, since it will most likely get fixed by https://github.com/terraform-providers/terraform-provider-google/issues/5460

**Comment by danawillow** [comment]
@emilymye what work (if any) is remaining for this?

**Comment by emilymye** [comment]
This was just open to see if we ran into more network errors - since we pretty much don't get them now unless there's a big outage, I'm going to close
