### ISSUE TITLE
POSTGRES_11_1 not supported

### ISSUE THREAD

**Issue by hprotzek** [terraform-providers/terraform-provider-google#3964]
Using the new POSTGRES_11_1 version
```
resource "google_sql_database_instance" "concourse" {
  database_version = "POSTGRES_11_1"
...
```
end up with an error:

```
googleapi: Error 400: Invalid value at 'body.database_version' (TYPE_ENUM), "POSTGRES_11_1", badRequest
```

**Comment by Chupaka** [comment]
Just a guess: it's in beta, do you use beta provider?

**Comment by hprotzek** [comment]
yes I am using the beta provider

**Comment by chrisst** [comment]
Apparently the correct syntax is `POSTGRES_11` I'll update our docs and see if I can convince the sql team to do the same.
