### ISSUE TITLE
unsupported attribute "cloudrun_config"

### ISSUE THREAD

**Issue by drzero42** [terraform-providers/terraform-provider-google#3965]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.3
+ provider.google v2.10.0
+ provider.google-beta v2.10.0
+ provider.kubernetes v1.8.0

### Affected Resource(s)

* google_container_cluster

### Debug Output

https://gist.github.com/drzero42/b7032b1c161460608651da4224b7569b

### Expected Behavior

Terraform should show state.

### Actual Behavior

Got this error: `unsupported attribute "cloudrun_config"`

### Steps to Reproduce

1. Create a cluster with google-beta provider with `istio_config.disabled` set to either true or false.
2. `terraform state show google_container_cluster.cluster`

### Important Factoids

In my tests, this seems to be linked to having istio_config block set. If I create a cluster with that block (does not matter if disabled is set to true or false) the `state show` command will complain about cloudrun_config.

**Comment by chrisst** [comment]
[cloudrun_config](https://www.terraform.io/docs/providers/google/r/container_cluster.html#istio_config) is only in beta right now. You need to add provider = "google-beta" to your resource in order to use beta features. See terraform.io/docs/providers/google/provider_versions.html for more info.

Please provide an example config if there is a different issue.

**Comment by drzero42** [comment]
@chrisst I know it is in the google-beta provider. That is why I wrote 

> Create a cluster with google-beta provider

;) 

The issue is when a cluster has been created with the beta provider, and I try to do a `terraform state show` on the resource, it gives an error saying `unsupported attribute "cloudrun_config"`.

**Comment by chrisst** [comment]
Sorry I missed that as your bug came in with a few other very similar bugs :P I am pretty sure this is actually something that will need to be fixed in Terraform core, but I'll poke around a bit.

**Comment by drzero42** [comment]
I guessed as much :)

I've tried doing a `terraform state pull` and I see the `cloudrun_config` inside `addons_config`, but it is just an empty list. Note that I have not specified `cloudrun_config` in my Terraform manifest.

```
            "addons_config": [
              {
                "cloudrun_config": [],
```

**Comment by chrisst** [comment]
Closing this out as it will be tracked by the upstream bug. Please direct comments and 👍's there.
