### ISSUE TITLE
Blocks of type "istio_config" are not expected here.

### ISSUE THREAD

**Issue by ivanovaleksandar** [terraform-providers/terraform-provider-google#3966]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.3
+ provider.google v2.10.0
+ provider.random v2.1.2
### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "control_plane" {
  name     = "${var.gke_cluster_name}-control"
  location = "${var.gke_cluster_location}"

  remove_default_node_pool = true
  initial_node_count       = 1
  resource_labels = {
    env = "${var.environment}"
  }

  addons_config {
    istio_config {
      disabled = "${var.istio_disabled}"
      auth     = "${var.istio_auth}"
    }
  }

  master_auth {
    username = "xxx"
    password = "xxx"

    client_certificate_config {
      issue_client_certificate = false
    }
  }

}
```
### Expected Behavior

Terraform should create the resource.

### Actual Behavior

```
terraform plan

Error: Unsupported block type

  on ./main.tf line 18, in resource "google_container_cluster" "control_plane":
  18:     istio_config {

Blocks of type "istio_config" are not expected here.
```

### Steps to Reproduce

1. Create a google cluster with provider `google` or `google-beta` with defining the `istio_config` in the `addons` block.
2. `terraform init`
3. `terraform plan`

**Comment by chrisst** [comment]
[istio_config](https://www.terraform.io/docs/providers/google/r/container_cluster.html#istio_config) is only in beta right now. You need to add provider = "google-beta" to your resource in order to use beta features. See terraform.io/docs/providers/google/provider_versions.html for more info.
