### ISSUE TITLE
google_container_cluster doesn't support database_encryption block despite docs (and changelogs) saying it does

### ISSUE THREAD

**Issue by cyclingwithelephants** [terraform-providers/terraform-provider-google#3968]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.3
+ provider.external v1.2.0
+ provider.google v2.9.0
+ provider.google-beta v2.7.0

This also doesn't work for terraform 0.11.14, which is the version I need this to work for.
### Affected Resource(s)

google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "gke_cluster" {
  name       = var.cluster_name
  location   = var.location
  project    = var.project_id
  network    = google_compute_network.VPC.self_link
  subnetwork = google_compute_subnetwork.subnet.self_link

  remove_default_node_pool = "true"
  initial_node_count       = "1"

  ip_allocation_policy {
    use_ip_aliases = "true"
  }

  private_cluster_config {
    master_ipv4_cidr_block = "10.148.0.0/28"

    # enable_private_endpoint = "true"
    enable_private_nodes = "true"
  }

  # This sets etcd to encrypt all secrets at rest, using the specified key
  database_encryption {
    state    = "ENCRYPTED"
    key_name = google_kms_crypto_key.etcd_key.name
  }

  master_authorized_networks_config {
    cidr_blocks {
      cidr_block   = "0.0.0.0/0"
      display_name = "for-testing"
    }
  }
}
```

### Debug Output

https://gist.githubusercontent.com/cyclingwithelephants/e9013a22e6266f42ae64f582dfb3b4cf/raw/d9e37ddec229d0a1a2931d77101565363ec8f74f/gistfile1.txt

### Expected Behavior

the cluster should have been configured to encrypt etcd secrets at rest

### Actual Behavior

terraform doesn't even recognise the block:

Error: Unsupported block type

  on GKE.tf line 23, in resource "google_container_cluster" "gke_cluster":
  23:   database_encryption {

Blocks of type "database_encryption" are not expected here.

### Steps to Reproduce

create a google_container_cluster with a "database_encryption" block

terraform init

terraform plan

1. `terraform apply`

### Important Factoids
not AFIAK

### References

* #0000

**Comment by chrisst** [comment]
[database_encryption](https://www.terraform.io/docs/providers/google/r/container_cluster.html#database_encryption) is only in beta right now. You need to add `provider = "google-beta"` to your resource to use beta features. See https://www.terraform.io/docs/providers/google/provider_versions.html for more.
