### ISSUE TITLE
terraform 0.12.x Inappropriate value for attribute "nat_ips" in google_compute_router_nat

### ISSUE THREAD

**Issue by scippio** [terraform-providers/terraform-provider-google#3980]
terraform -v
Terraform v0.12.3
+ provider.google v2.10.0

```
Error: Incorrect attribute value type

  on gke-cluster.tf line 107, in resource "google_compute_router_nat" "egress_nat_production":
 107:   nat_ips                            = ["${google_compute_address.egress_production.*.self_link}"]

Inappropriate value for attribute "nat_ips": element 0: string required.
```

**Comment by tysen** [comment]
Hi @scippio - can you try `nat_ips = "$google_compute_address.egress_production[*].self_link"`?

**Comment by TheMagoo73** [comment]
Thanks @tysen - that's resolved the same issue I'd just run into, perfect timing! Hopefully it will resolve @scippio too.

**Comment by FakeBuddy** [comment]
This parameter should be fixed in documentation https://www.terraform.io/docs/providers/google/r/compute_router_nat.html

**Comment by tysen** [comment]
Docs fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/2056

**Comment by dpkirchner** [comment]
The error occurs, for me, when using the lines in the updated documentation. The easiest way to reproduce this is by copying the production-like configuration as-is ([at the above-referenced documentation URL](https://www.terraform.io/docs/providers/google/r/compute_router_nat.html)). This is with terraform v0.12.6 and provider.google v2.12.0:

```
Error: Incorrect attribute value type

  on network-us-west2.tf line 32, in resource "google_compute_router_nat" "advanced-nat":
  32:   nat_ips                            = ["${google_compute_address.address[*].self_link}"]

Inappropriate value for attribute "nat_ips": element 0: string required.
```

Replacing line 32 with the string:

```
nat_ips = google_compute_address.address[*].self_link
```

works fine.

**Comment by tysen** [comment]
Thanks @dpkirchner - fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/2125
