### ISSUE TITLE
Composer environment with service/pods IP range specified

### ISSUE THREAD

**Issue by sonots** [terraform-providers/terraform-provider-google#3983]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

version

```
terraform {
  required_version = "= 0.12.3"

  required_providers {
    google      = "= 2.9.1"
    google-beta = "= 2.9.1"
  }
}
```

### Affected Resource(s)

* google_composer_environment

### Potential Terraform Configuration

```
provider "google-beta" {
  version = "~> 1.19"
  region  = "${var.region}"
  project = "${var.project_id}"
}

resource "google_composer_environment" "airflow" {
  provider = "google-beta"
  name     = "${var.project_id}-airflow"
  project  = "${var.project_id}"
  region   = "${var.region}"

  config {
    node_count = "${var.primary_nodes}"

    node_config {
      zone            = "${var.zone}"
      machine_type    = "n1-standard-1"
      network         = "${var.network}"
      subnetwork      = "${var.subnetwork}"
      service_account = "${var.composer_service_account}"
    }
  }
}
```

Since it seems the `gcloud beta` command  supports `--cluster-secondary-range-name` options to specify pod IP range, I like `google_composer_environment` supporting `cluster_secondary_range_name` configuration as `google_container_cluster` does:

```
resource "google_compute_subnetwork" "vpc-subnetwork" {
  name = "vpc-subnetwork"

  secondary_ip_range {
    range_name    = "pods"
    ip_cidr_range = "172.20.0.0/14" # must be at least /14 and cannnot overlap with other cidr
  }

  ip_cidr_range = "172.19.0.0/22" # must be at least /22

  secondary_ip_range {
    range_name    = "services"
    ip_cidr_range = "172.19.4.0/22" # must be at least /22 and cannnot overlap with other cidr
  }

  region                   = var.region
  network                  = google_compute_network.vpc-network.self_link
  private_ip_google_access = true

  depends_on = [google_compute_network.vpc-network]
}

resource "google_container_cluster" "primary" {
  name                     = var.gke_name
  location                 = var.region
  node_locations           = [var.zone, var.secondary_zone]
  network                  = google_compute_network.vpc-network.self_link
  subnetwork               = google_compute_subnetwork.vpc-subnetwork.self_link
  remove_default_node_pool = true
  min_master_version       = var.gke_min_master_version
  initial_node_count       = 1
  logging_service          = "logging.googleapis.com/kubernetes"
  monitoring_service       = "monitoring.googleapis.com/kubernetes"

  ip_allocation_policy {
    cluster_secondary_range_name  = google_compute_subnetwork.vpc-subnetwork.secondary_ip_range[0].range_name // <- LIKE THIS
    services_secondary_range_name = google_compute_subnetwork.vpc-subnetwork.secondary_ip_range[1].range_name
  }
}
```

### References

* gcloud beta supports `--cluster-secondary-range-name` https://cloud.google.com/sdk/gcloud/reference/beta/composer/environments/create?hl=ja#--cluster-secondary-range-name

**Comment by sonots** [comment]
A comment from https://github.com/terraform-providers/terraform-provider-google/issues/2875 says to have 2 GCP projects, but it seems https://cloud.google.com/sdk/gcloud/reference/beta/composer/environments/create?hl=ja#--cluster-secondary-range-name does not require 2 GCP projects.

**Comment by paddycarver** [comment]
I believe this is already implemented. Please see https://www.terraform.io/docs/providers/google/r/composer_environment.html#ip_allocation_policy
