### ISSUE TITLE
Terraform 0.12 and "Provider produced inconsistent final plan" error

### ISSUE THREAD

**Issue by tdsacilowski** [terraform-providers/terraform-provider-google#3987]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.3
+ provider.google v2.10.0

### Affected Resource(s)

* google_compute_firewall

### Terraform Configuration Files

```tf
terraform {
  required_version = ">= 0.12"
}

provider "google" {
  # credentials = "${file("CREDENTIALS_FILE.json")}"
  project = var.gcp_project
  region  = var.gcp_region
}

# ---------------------------------------------------------------------------------------------------------------------
# Deploy TFE Instance
# ---------------------------------------------------------------------------------------------------------------------

resource "google_compute_instance" "tfe" {
  name = var.tfe_instance_name

  machine_type = var.tfe_machine_type
  zone         = var.tfe_instance_zone

  metadata = {
    sshKeys = "${var.tfe_instance_ssh_username}:${var.tfe_instance_ssh_pub_key}"
  }

  metadata_startup_script = "echo 'TFE install script will go here' > test.txt"

  boot_disk {
    initialize_params {
      image = var.tfe_instance_image
      size  = var.tfe_instance_boot_disk_size
    }
  }

  network_interface {
    network = var.tfe_instance_network

    access_config {
      # Ephemeral IP
    }
  }

  tags = var.tfe_instance_tags
}

# ---------------------------------------------------------------------------------------------------------------------
# Configure GCP Firewall Rules
# ---------------------------------------------------------------------------------------------------------------------

resource "google_compute_firewall" "tfe_ingress" {
  name = "${google_compute_instance.tfe.name}-ingress"

  network = google_compute_instance.tfe.network_interface[0].network

  direction   = "INGRESS"
  target_tags = google_compute_instance.tfe.tags

  allow {
    protocol = "tcp"
    ports    = var.tfe_firewall_ingress_ports
  }
}
```

See full module repo here: https://github.com/tdsacilowski/tfe-demo-modules/tree/master/terraform-gcp/examples/root-example

### Debug Output

https://gist.github.com/tdsacilowski/f7270e95a737279f0d6c8fb5c6d02438

### Panic Output

N/A

### Expected Behavior

Provisioned an GCP compute instance and create firewall rules in the same network as the GCP instance network interface

### Actual Behavior

TF `apply` fails after creating GCP instance when trying to create firewall rules.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Rerunning `apply` right after the first failure succeeds and creates the firewall rules as expected.

This worked fine with Terraform 0.11.x

### References

Seems similar to:
* #3727

**Comment by tdsacilowski** [comment]
Seems this happens because the API returns a full canonical URI for the resource in place of the shorthand that's passed in. E.g. `var.network == "default"` but the API returns `https://www.googleapis.com/compute/v1/projects/testing/global/networks/default` which results in an inconsistent plan. For now, I've worked around this by doing the following:

```terraform
locals {
  default_network = "https://www.googleapis.com/compute/v1/projects/${var.gcp_project}/global/networks/default"
}

resource "google_compute_firewall" "tfe_ingress" {
  name = "${google_compute_instance.tfe.name}-ingress"

  network = var.tfe_instance_network == "default" ? local.default_network : google_compute_instance.tfe.network_interface.0.network

  direction   = "INGRESS"
  target_tags = google_compute_instance.tfe.tags

  allow {
    protocol = "tcp"
    ports    = var.tfe_firewall_ingress_ports
  }
}
```

**Comment by tysen** [comment]
@tdsacilowski Terraform 0.12 introduced some new validation that fails when the config changes between plan and apply. In this case the `network` field in the instance starts as the short form and is replaced with the fully qualified URI, as you mentioned. Another way to satisfy this validation is to reference the same var from your firewall, instead of referencing the `network` field in the instance. The var will be the short form the whole time so the config won't change.
