### ISSUE TITLE
add descriptions to resource schemas

### ISSUE THREAD

**Issue by kibbles-n-bytes** [terraform-providers/terraform-provider-google#3988]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, none of the resource schemas have descriptions for fields, though the [Terraform schema.Schema type supports them](https://github.com/hashicorp/terraform/blob/e4ec9310c4e165e277d2ee0cd5f42150a5e985fb/helper/schema/schema.go#L144). It seems the only descriptions available are part of the website reference documentation, which is not ideal to use programatically.

### New or Affected Resource(s)

All resources

**Comment by rileykarson** [comment]
This gets done widely for generated resources with #2643. Handwritten ones are infeasible- they'll drift near-immediately, and I don't want to add more work to editing them.
