### ISSUE TITLE
database_encryption block has key_name field as required. The computed value from GKE is actually empty. 

### ISSUE THREAD

**Issue by xiaobaitusi** [terraform-providers/terraform-provider-google#3998]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.1
provider.google-beta v2.10.0

### Affected Resource(s)
google_container_cluster

### Expected Behavior
IMO, key_name field in database_encryption block should be optional. Google doc doesn't mention it's required per https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#databaseencryption
### Actual Behavior
key_name field in database_encryption block is marked as required. However if database_encryption is not specified, the computed value from server side is empty:
databaseEncryption:
  state: DECRYPTED

**Comment by tysen** [comment]
The intended use is to not specify the block at all in Terraform config if the `state` is `"DECRYPTED"`. There's not a good way in a Terraform provider to require one field depending on the value of another field, which is why both are required in the optional `database_encryption` block. Is there a reason you need to explicitly specify `"DECRYPTED"`?

**Comment by xiaobaitusi** [comment]
> The intended use is to not specify the block at all in Terraform config if the `state` is `"DECRYPTED"`. There's not a good way in a Terraform provider to require one field depending on the value of another field, which is why both are required in the optional `database_encryption` block. Is there a reason you need to explicitly specify `"DECRYPTED"`?

Sorry for the late reply. The way that we use terraform-provider-google is to generate k8s CRDs based on tf schemas. The fact that `key_name` being required makes the generated CRD also mark the field as required and we cannot write back the status even if users simply choose not specify `database_encryption` because the computed default value for `databaseEncryption` is {state: DECRYPTED} with `key_name` being empty. The CRD schema would complain about it.
Currently we hack it around by intentionally removing `key_name` from requires. However it would be great if it gets marked correctly as optional.

**Comment by tysen** [comment]
@xiaobaitusi Fixed.
