### ISSUE TITLE
Support for service account keys

### ISSUE THREAD

**Issue by drzero42** [terraform-providers/terraform-provider-google#400]
Currently we can create service accounts with Terraform, but we cannot create keys for service accounts. Creating a service account key returns the generated private key and some other information, that should be kept.

My use case for service keys are that I create a service account for the services that I run in container engine to enable usage of various APIs (Cloud Storage, Pub/Sub and Cloud SQL Proxy amongst others). I basically upload the generated JSON file (written by gcloud when using that, or downloaded from Cloud Console when using the browser) as a Kubernetes secret, which can then be consumed by my pods. Being able to create a service account key in Terraform and having the same data as is in such a JSON file available as an attribute would enable me to use the Kubernetes provider to create a secret with this content. This would bring me one step closer to being able to deploy my entire GCP stack with Terraform.

**Comment by sebglon** [comment]
PR#204

**Comment by danawillow** [comment]
Thanks @sebglon, closing this one as a duplicate.

**Comment by jasonjho** [comment]
@danawillow @sebglon I see that you're now able to generate service account keys, but is there a way to generate the furnished JSON key file? As @drzero42 mentioned, these files are typically consumed by other resources, whether referenced on disk or uploaded as a Kubernetes secrets.

Any pointers here would be greatly appreciated. Thanks!

**Comment by danawillow** [comment]
Isn't that the [`private_key`](https://www.terraform.io/docs/providers/google/r/google_service_account_key.html#private_key) field? Or are you looking for something else?

**Comment by drzero42** [comment]
@jasonjho It is easily possible, it is just unintuitively named, and badly documented (IMHO). The attribute named `private_key` on the `google_service_account_key` resource, contains a base64 encoded version of the json-file normally downloaded when you create a service account key through the console or gcloud cli. Here is a simply example of how to use it:

```
resource "google_service_account" "myaccount" {
  account_id   = "myaccount"
  display_name = "My Service Account"
}
resource "google_service_account_key" "mykey" {
  service_account_id = "${google_service_account.myaccount.id}"
}
resource "local_file" "myaccountjson" {
    content     = "${base64decode(google_service_account_key.mykey.private_key)}"
    filename = "${path.module}/myaccount.json"
}
```
Same deal for setting a kubernetes secret with the json-content :)

**Comment by danawillow** [comment]
@drzero42 was that an offer to improve the documentation? ;)

**Comment by jasonjho** [comment]
@danawillow @drzero42 Thank you for the assist here! I had a hunch this might be the case, but glad that this is confirmed. I'd imagine adding this to the docs would be immensely helpful for others.

**Comment by drzero42** [comment]
@jasonjho You're welcome :)
@danawillow Me and my big mouth eh? I'll take a stab at making a PR for the documentation to make it more obvious that the private_key attribute has the same content as the JSON-file normally downloaded :)

**Comment by milesmatthias** [comment]
Are there any security concerns with adding the private key in this way? I notice that the entire key is logged when you run terraform when you include it as in [@drzero42's example](https://github.com/terraform-providers/terraform-provider-google/issues/400#issuecomment-360565229), which depending on logging configurations could be leaked.
