### ISSUE TITLE
data.google_project requires project_id field

### ISSUE THREAD

**Issue by Aedalus** [terraform-providers/terraform-provider-google#4020]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.4
+ provider.google v2.10.0

### Affected Resource(s)

data google_project

### Terraform Configuration Files

```tf
provider "google" {
  credentials = "${file("~/.gcp/credentials.json")}"
  region      = "us-central1"
}

data "google_project" "project" {}

output "project_number" {
  value = "${data.google_project.project.number}"
} 
```

### Expected Behavior

The data source should have pulled the project ID from the provider credentials, as indicated in this documentation: https://www.terraform.io/docs/providers/google/d/google_project.html

### Actual Behavior

Received an error specifying that a required field was not set:

Error: project: required field is not set

  on gcp-iam-separation-of-duties-kms-related-roles-to-users.tf line 6, in data "google_project" "project":
   6: data "google_project" "project" {}

Seems to require a project_id field to run

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References

* #0000

**Comment by Chupaka** [comment]
Provider credentials have nothing to do with provider project. You may set project in provider object (like `provider "google" { project = "blah-blah"}`) — then this value will be used as default value in data source.

**Comment by aymond** [comment]
``` HCL
data "google_project" "host-project" {
  project_id = "${var.hostvpc_project_id}" 
}
```
and I receive the error
``` bash
Error: project: required field is not set

  on ..\modules\project\main.tf line 28, in data "google_project" "host-project":
  28: data "google_project" "host-project" {
```

**Comment by slevenick** [comment]
Hey @Aedalus as @Chupaka has pointed out if you set a project in the provider object it will be set as default for the `google_project` data source.

The google terraform provider does not detect the project from a credentials file, it must be specified either in the `provider` object or on the resource/datasource itself.

I recommend changing the provider block to look like the following
```
provider "google" {
  credentials = "${file("~/.gcp/credentials.json")}"
  region      = "us-central1"
  project = "your-project"
}
```
