### ISSUE TITLE
google_compute_region_instance_group_manager never built with auto_healing_policies

### ISSUE THREAD

**Issue by eakarsu** [terraform-providers/terraform-provider-google#4022]
I have google_compute_region_instance_group_manager manager that has been working always so far. I have added auto_healing_policies and update_policy to it. When I run this terraform, the cluster is never built and timed out always. I know this zk cluster and port number is 2181 and making tcp heatth checks. I am not sure why this is happening. All google documents  says this should work as expected.
Here I will give my terraform module definition. The error is the last. I am using google-beta provider for this. My terraform version is 0.12.2

resource "google_compute_region_instance_group_manager" "region-node-manager" {
  provider = "google-beta"
  name               = "${var.env}-manager"
  target_size        = var.node_instance_count
  base_instance_name = var.env
  version {
    instance_template  = google_compute_instance_template.node-template.self_link
    name = "newVersion"
  }
  region             = var.region
  wait_for_instances = true
  project            = var.my_gcp_project

  named_port {
    name = var.port_name
    port = var.port_number
  }
  
  update_policy{
    type = "PROACTIVE"
    minimal_action = "RESTART"
    max_surge_fixed = max(var.node_instance_count,3)
    max_unavailable_fixed = 3
    min_ready_sec = 50
  }
  
  auto_healing_policies {
    health_check      = google_compute_health_check.tcp_autohealing.self_link
    initial_delay_sec = 60 #seconds
  }
  
}

locals {
  env_array=split("-", var.env)
  comp = element(local.env_array, length(local.env_array) - 1 )
  path="${(local.comp == "solr")?"/solr":"/"}"
}

resource "google_compute_health_check" "tcp_autohealing" {
  project        = var.my_gcp_project
  name                = "${var.env}-tcp-autohealing-health-check"
  check_interval_sec  = 5
  timeout_sec         = 5
  healthy_threshold   = 2
  unhealthy_threshold = 10 # 50 seconds

  tcp_health_check {
    port         = var.port_number
  }
}

Error in Jenkins job of running terraform:
[0m[1mmodule.instance-template.google_compute_region_instance_group_manager.region-node-manager: Still creating... [5m10s elapsed][0m[0m
[0m[1mmodule.instance-template.google_compute_region_instance_group_manager.region-node-manager: Still creating... [5m20s elapsed][0m[0m
[31m
[1m[31mError: [0m[0m[1mtimeout while waiting for state to become 'created' (last state: 'creating', timeout: 5m0s)[0m

[0m  on ../../modules/region-instance-template/main.tf line 73, in resource

**Comment by slevenick** [comment]
Hey @eakarsu 

Looks like the terraform apply is timing out. This could be because of a bug, but I would guess that it is just taking longer than usual to deploy this `google_compute_region_instance_group_manager`. 

Could you try specifying a longer timeout for creating and run the terraform apply again?

Information on timeouts can be found here: https://www.terraform.io/docs/configuration/resources.html#timeouts

Adding 
```timeouts {
    create = "15m"
  }```
to the `google_compute_region_instance_group_manager` block may fix the issue

**Comment by eakarsu** [comment]
Exactly it did! thanks
