### ISSUE TITLE
Cloud functions source repository with moveable alias with branch refers to commit not HEAD of branch

### ISSUE THREAD

**Issue by frankfarrell** [terraform-providers/terraform-provider-google#4025]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
terraform -v
Terraform v0.11.14
+ provider.google v2.7.0
+ provider.google-beta v2.7.0

```
### Affected Resource(s)

* google_cloudfunctions_function 

### Terraform Configuration Files

```tf
resource "google_cloudfunctions_function" "my_function" {
  provider = "google-beta"

  name                  = "myfunction"
  description           = "etc"
  runtime               = "python37"

  available_memory_mb   = 1024 
  trigger_http          = true
  timeout               = 540
  entry_point           = "main"
  service_account_email = "${var.service_account_email}"

  source_repository {
    url = "https://source.developers.google.com/projects/myorganisation/repos/bitbucket_myrepo/moveable-aliases/${var.branch}/paths/myfunction"
  }
}
```

### Expected Behavior

The cloud function shoudl refer to the head of the branch

### Actual Behavior

The cloud function resolves the head at the time of apply and refers to a specific commit

### Steps to Reproduce

1. `terraform apply`
2. Check the console to see what the source is

### References

* #0000

**Comment by slevenick** [comment]
Hey @frankfarrell I'd like to get a little more information.

What are you trying to accomplish with the combination of this cloud function + terraform? 

The way I understand cloud functions is that deploying via terraform and specifying a moveable alias will evaluate to that alias at time of deploy, and any future terraform applies will not see a diff between the current state and your terraform config. You could try destroying and then recreating this cloud function via terraform, which should make resolve the alias again

If you are trying to have a cloud function keep in sync with the most current version of a branch I would recommend looking into having something else redeploy the cloud function whenever there is a change to the branch (Cloud Build triggers could do this)

**Comment by frankfarrell** [comment]
Hi @slevenick, 
I would like this cloud function to always have the code that is on the HEAD of the specified branch. That is how I understand it from the docs, which are a little ambiguous. There are 3 options, 1) specific commit, 2) branch, 3) tag. I think its natural to infer from those options that if you use 2 it won't resolve to the specific commit at the time of provisioning. The console is a bit ambiguous too, 
Deployed from branch
mybranch (resolved to 8d75e68d4185abcdefdf5ec564da4d353a21)

Do you have any examples of such a cloud build trigger?

**Comment by slevenick** [comment]
Here is an example of someone doing a similar thing: https://medium.com/google-cloud/triggering-cloud-functions-deployments-97691f9b5416

I haven't gone through that tutorial, but it looks reasonable to me.

The idea is to have a cloud build trigger that is triggered by a change to a specific branch, and that trigger then builds & deploys that branch to cloud functions.

You can likely set up the trigger via terraform, but the cloud function would not be controlled by terraform. 

Other resources: https://cloud.google.com/cloud-build/docs/running-builds/automate-builds
https://www.terraform.io/docs/providers/google/r/cloud_build_trigger.html

**Comment by jpbecotte** [comment]
Hi @slevenick ! 

I think @frankfarrell question was «How can I specify the repo URL so I can describe my function in Terraform language».

A cloud function has many meta values that refers to the infrastructure, such as: memory limit, region, trigger, etc.

I understand that deploying a function should be different than providing it.

Unfortunately, it is impossible at the moment to create an «empty» function. For the Terraform Google provider, we must specify the source either by providing a zip file (thru a bucket) or using a Google Source Repositories URL. I agree that the doc is very poor and gives nothing about what should be replaced.
