### ISSUE TITLE
Panic when creating a DNS record set.

### ISSUE THREAD

**Issue by bweston92** [terraform-providers/terraform-provider-google#4027]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
$ terraform version
Terraform v0.12.3
+ provider.google v2.10.0
```

### Affected Resource(s)

* google_dns_record_set

### Terraform Configuration Files

```tf
terraform {
  backend "gcs" {
    bucket  = "cfgroup-terraform-state"
    prefix  = "terraform/state"
  }
}

provider "google" {
  project = "commercialfinancegroup"
  region  = "europe-west2"
  zone    = "europe-west2-b"
}

resource "google_dns_managed_zone" "prod" {
  name     = "cfgroup-zone"
  dns_name = "commercialfinancegroup.co.uk."
}


data "google_compute_address" "prod_addr" {
  name = "production"
}

resource "google_dns_record_set" "frontend" {
  name = "commercialfinancegroup.co.uk"
  type = "A"
  ttl  = 60

  managed_zone = "${google_dns_managed_zone.prod.name}"

  rrdatas = ["${data.google_compute_address.prod_addr.address}"]
}

```

### Panic Output

https://gist.github.com/bweston92/5edd8cf89665fea260ce970e98a2da42

### Expected Behavior

A DNS record set to be created.

### Actual Behavior

Panic.

### Steps to Reproduce

1. `terraform apply`

### References

* https://www.terraform.io/docs/providers/google/r/dns_record_set.html

**Comment by bweston92** [comment]
Seems like `rrdatas = ["${google_compute_address.prod_addr.address}"]` is the line causing this `panic`. Am I doing something wrong?

**Comment by slevenick** [comment]
Hey @bweston92 

I agree that it looks like the `rrdatas` line is causing the issue. I see that a `google_compute_address` is a data source, have you verified that the underlying resource has an address that can be used? The `address` field is marked as Optional on the address resource, so it is possible that it is not being returned by the API.

Can you verify that a valid IP address is coming back for that data source, either by looking at the terraform plan for the result of `rrdatas`, or using outputs as specified here: https://www.terraform.io/docs/configuration/outputs.html

**Comment by bweston92** [comment]
I deleted the IP address in GCP and changed it to a `resource` rather then `data` and it worked. (created a new IP address but that's fine)
