### ISSUE TITLE
Any resource available for listing instances created in a project/organization

### ISSUE THREAD

**Issue by srujan70** [terraform-providers/terraform-provider-google#4035]
If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by slevenick** [comment]
Are you looking to list all the instances in your project from terraform? That's not currently functionality that exists in this provider.

**Comment by srujan70** [comment]
Ok thanks for the clarification.
