### ISSUE TITLE
backend: invalid character '/' looking for beginning of value

### ISSUE THREAD

**Issue by nodesocket** [terraform-providers/terraform-provider-google#4039]
Attempting to pass an absolute path in envar `GOOGLE_CREDENTIALS` into `backend` results in invalid character '/' looking for beginning of value.

```
GOOGLE_CREDENTIALS="/tmp/terraform-backend-credentials.json" terraform init
```

Terraform configuration block:

```
terraform {
  required_version = "0.11.13"

  backend "gcs" {
    bucket  = "myapp-terraform-state"
    project = "myproject"
  }
}
```

According to the doc (https://www.terraform.io/docs/backends/types/gcs.html) the envar `GOOGLE_CREDENTIALS` should be able to accept a local path to a json file.

```
Initializing the backend...

Error configuring the backend "gcs": Error parsing credentials '/tmp/terraform-backend-credentials.json': invalid character '/' looking for beginning of value

Please update the configuration in your Terraform files to fix this error
then run this command again.
```

**Comment by Chupaka** [comment]
https://github.com/hashicorp/terraform/issues/16803

**Comment by slevenick** [comment]
This looks like a similar issue: https://github.com/hashicorp/terraform/issues/17975

Does following the steps in there resolve the issue?
