### ISSUE TITLE
Datasource google_active_folder doesn't work anymore

### ISSUE THREAD

**Issue by gabrielgbim** [terraform-providers/terraform-provider-google#4057]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.4
+ provider.google v2.5.0

### Affected Resource(s)

data.google_active_folder

### Terraform Configuration Files

```tf
data "google_active_folder" "my_folder" {
  display_name = local.my_folder_name
  parent = format("organizations/%s", local.organization_id)
}
```

### Expected Behavior

It should have retrieve folder's information, so that it can be used to create a ressource within it for example

### Actual Behavior

Error: Error refreshing state: 1 error(s) occurred:

data.google_active_folder.group: 1 error(s) occurred:

data.google_active_folder.group: data.google_active_folder.group: Folder not found

### Steps to Reproduce

1. `terraform apply`

### References

* #3220

**Comment by gabrielgbim** [comment]
It seems that the default service account is not being used.
I only can use google_active_folder when passing `credentials` to the google provider declaration.

`provider "google" {
  version = "~> 2.5.0"
  credentials = "path/to/credentials.json"
}`

**Comment by slevenick** [comment]
Is it possible that your default service account does not have permission to view the folder in question? There isn't anything different about how the resource itself works for different authentication methods

**Comment by slevenick** [comment]
I believe this is caused by permissions on different service accounts. If this is not the case, feel free to reopen
