### ISSUE TITLE
google_monitoring_notification_channel no longer obfuscating auth_token for Slack

### ISSUE THREAD

**Issue by StephenWithPH** [terraform-providers/terraform-provider-google#4058]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.12.4
+ provider.google v2.11.0
```

### Affected Resource(s)

* google_monitoring_notification_channel

### Terraform Configuration Files

```tf
resource "google_monitoring_notification_channel" "this" {
  provider     = google
  display_name = var.display_name
  enabled      = "true"
  project      = data.google_project.this.project_id
  type         = "slack"

  labels = {
    auth_token   = data.vault_generic_secret.slack_token.data["value"]
    channel_name = var.channel_name
  }
}

```

### Expected Behavior

Per https://github.com/terraform-providers/terraform-provider-google/blob/v2.11.0/website/docs/r/monitoring_notification_channel.html.markdown...

>Note: Some NotificationChannelDescriptor labels are sensitive and the API will return an partially-obfuscated value. For example, for "type": "slack" channels, an auth_token label with value "SECRET" will be obfuscated as "**CRET".

### Actual Behavior

- `terraform apply`:
```
Terraform will perform the following actions:

  # module.slack.google_monitoring_notification_channel.this will be created
  + resource "google_monitoring_notification_channel" "this" {
      + display_name        = "my-display-name"
      + enabled             = true
      + id                  = (known after apply)
      + labels              = {
          + "auth_token"   = "UN-OBFUSCATED TOKEN"          <---------- this is the problem
          + "channel_name" = "my-channel-name"
        }
      + name                = (known after apply)
      + project             = "my-project"
      + type                = "slack"
      + verification_status = (known after apply)
    }

```

- `terraform show`:
```
# module.slack.google_monitoring_notification_channel.this:
resource "google_monitoring_notification_channel" "this" {
    display_name = "my-display-name"
    enabled      = true
    id           = "<redacted>"
    labels       = {
        "auth_token"   = "UN-OBFUSCATED TOKEN"       <------ also a problem here
        "channel_name" = "my-channel-name"
    }
    name         = "<redacted>"
    project      = "my-project"
    type         = "slack"
}
```

- `terraform destroy`:
```
Terraform will perform the following actions:

  # module.slack.google_monitoring_notification_channel.this will be destroyed
  - resource "google_monitoring_notification_channel" "this" {
      - display_name = "my-display-name" -> null
      - enabled      = true -> null
      - id           = "<redacted>" -> null
      - labels       = {
          - "auth_token"   = "UN-OBFUSCATED TOKEN"      <------- also a problem here
          - "channel_name" = "my-channel-name"
        } -> null
      - name         = "<redacted>" -> null
      - project      = "my-project" -> null
      - type         = "slack" -> null
      - user_labels  = {} -> null
    }
```

### Steps to Reproduce

1. `terraform apply` or `terraform show` (having created the resource) or `terraform destroy` (having created the resource)
2. see the unredacted token in the output

**Comment by slevenick** [comment]
I believe this is working as intended.

The documentation mentions that the API will return an obfuscated value, which it does (see snippet below).

Terraform state, and the results of plan do not obfuscate the token, as they need the entire value to be able to send it to the API. See https://www.terraform.io/docs/state/sensitive-data.html

Result from API:
```2019-07-19T14:22:38.131-0700 [DEBUG] plugin.terraform-provider-google_v2.10.0_x4: {
2019-07-19T14:22:38.131-0700 [DEBUG] plugin.terraform-provider-google_v2.10.0_x4:   "type": "slack",
2019-07-19T14:22:38.131-0700 [DEBUG] plugin.terraform-provider-google_v2.10.0_x4:   "displayName": "displaythis",
2019-07-19T14:22:38.131-0700 [DEBUG] plugin.terraform-provider-google_v2.10.0_x4:   "labels": {
2019-07-19T14:22:38.131-0700 [DEBUG] plugin.terraform-provider-google_v2.10.0_x4:     "auth_token": "**************ALUE",
2019-07-19T14:22:38.131-0700 [DEBUG] plugin.terraform-provider-google_v2.10.0_x4:     "channel_name": "channel"
2019-07-19T14:22:38.131-0700 [DEBUG] plugin.terraform-provider-google_v2.10.0_x4:   },
2019-07-19T14:22:38.131-0700 [DEBUG] plugin.terraform-provider-google_v2.10.0_x4:   "name": "projects/project-name/notificationChannels/123123",
2019-07-19T14:22:38.131-0700 [DEBUG] plugin.terraform-provider-google_v2.10.0_x4:   "enabled": true
2019-07-19T14:22:38.131-0700 [DEBUG] plugin.terraform-provider-google_v2.10.0_x4: }```
