### ISSUE TITLE
Retrieve current master version for google_container_engine_versions

### ISSUE THREAD

**Issue by natalysheinin** [terraform-providers/terraform-provider-google#4060]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Given a new feature like `workload_identity` which can only be provisioned for clusters on 1.12, it would be nice to be able to leverage the conditional syntax of terraform 0.12 to evaluate whether the cluster should have workload identity or not based on the current cluster master version.

### New or Affected Resource(s)

* google_container_engine_versions

### Potential Terraform Configuration

```tf
google_container_engine_versions.current_master_version >= "1.12"
```

### References

* https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

**Comment by paddycarver** [comment]
Hey!

Unfortunately, we can't actually do this. We would need to rely on the current resource's master version, which we don't actually know until after apply. But we want to rely on it before apply. So it's kind of a circular dependency; before we can decide whether to set workload_identity, we need to know the master version, meaning we need to apply, but we can't apply until we know workload identity.

This is a limitation in Terraform itself, but my understanding is it's not one they can fix, so I'm going to close this out. In theory, you should be able to use https://www.terraform.io/docs/providers/google/r/container_cluster.html#min_master_version to ensure that workload_identity is available.
