### ISSUE TITLE
cannot configure AutoprovisioningNodePoolDefaults for GKE node auto-provisioning

### ISSUE THREAD

**Issue by mattnworb** [terraform-providers/terraform-provider-google#4061]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The google-beta provider allows for activating [node auto-provisioning](https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning), but there is no way to configure some of the settings for the auto-provisioner that you can set with `gcloud` for things like `--autoprovisioning-service-account`, `--autoprovisioning-scopes`, etc.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_container_cluster" "foobar" {
  cluster_autoscaling {
    enabled = true
    resource_limits = {
      ...
    }
    # new field - to make it clear that these values are auto-provisioning defaults?
    auto_provisioning_defaults {
      service_account = ...
      scopes = [
        "https://www.googleapis.com/auth/logging.write",
        ...
      ]
    }
}
```

### References

* https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning

**Comment by mattnworb** [comment]
to be a bit more specific, I'd like to be able to set values for fields in `AutoprovisioningNodePoolDefaults ` of the `ClusterAutoscaling ` struct: 

https://github.com/googleapis/google-api-go-client/blob/aa15faf3c8a1cffc77fc3dabe95703bb12c5f6a9/container/v1beta1/container-gen.go#L1102-L1111

but it seems like `expandClusterAutoscaling` only sets `EnableNodeAutoprovisioning ` and `ResourceLimits `:

https://github.com/terraform-providers/terraform-provider-google-beta/blob/10a665739c0ce34bcfdace7b065e61c6be5bf635/google-beta/resource_container_cluster.go#L2112

**Comment by rmanyari** [comment]
Happy to add support for this if anyone has time to take a look. We also need this feature to be able to use the provider

**Comment by MMBRitter** [comment]
+1 for this.  I am unable to use cluster autoscaler because my default oauth scopes exclude the devstorage.read_only which is required to pull images from GCR.  Would love to see this feature added.

**Comment by megan07** [comment]
Hi @mattnworb, thank you for opening this issue!  I can take a look into this unless anyone else has started working on it.
