### ISSUE TITLE
Suppoort Dataproc Advanced Security kerberos

### ISSUE THREAD

**Issue by thadeusb** [terraform-providers/terraform-provider-google#4062]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Need to add support for Dataproc Advanced Security with Kerberos and Hadoop Secure mode. This is required for HIPAA compliance on the google cloud platform and prevents managing HIPAA compliant Dataproc clusters through terraform. The gcloud command line supports creating a cluster with advanced security enabled. It would be even more amazing if terraform could automatically create a one time password using the encryption key for the cluster and dispose of it when the cluster is created as recommended in the google cloud documentation for advance security.

### New or Affected Resource(s)

* google_dataproc_cluster

### Potential Terraform Configuration

```tf
    kerberos-root-principal-password-uri="Cloud Storage URI of KMS-encrypted password for Kerberos root principal"
    kerberos-kms-key="The URI of the KMS key used to decrypt the root password" \
```

### References

Documentation on enabling advanced security mode for dataproc.

https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/security

**Comment by emilymye** [comment]
To elaborate, this involves adding fields securityConfig.kerberosConfig.* to cluster

**Comment by tysen** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/2806
