### ISSUE TITLE
Possible regression (or just a corner case) of #863

### ISSUE THREAD

**Issue by rsalmond** [terraform-providers/terraform-provider-google#4064]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
terraform version
Terraform v0.12.5
+ provider.google v2.11.0
+ provider.google-beta v2.11.0
```
### Affected Resource(s)

* google_dns_record_set

### Terraform Configuration Files

```tf
resource "google_dns_record_set" "txt" {
  name = "mandrill._domainkey.descarteslabs.com."
  type = "TXT"
  ttl  = 300

  managed_zone = "www"

  rrdatas = [
    "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrLHiExVd55zd/IQ/J/mRwSRMAocV/hMB3jXwaHH36d9NaVynQFYV8NaWi69c1veUtRzGt7yAioXqLj7Z4TeEUoOLgrKsn8YnckGs9i3B3tVFB+Ch/4mPhXWiNfNdynHWBcPcbJ8kjEQ2U8y78dHZj1YeRXXVvWob2OaKynO8/lQIDAQAB;",
  ]
}
```

Terraform should not have tried to change the TXT record.

### Actual Behavior
```
google_dns_record_set.TXT-mandrill-domainkey-descarteslabs-com will be updated in-place
  ~ resource "google_dns_record_set" "TXT-mandrill-domainkey-descarteslabs-com" {
        id           = "www/mandrill._domainkey.descarteslabs.com./TXT"
        managed_zone = "www"
        name         = "mandrill._domainkey.descarteslabs.com."
        project      = "dalhart-project-421"
      ~ rrdatas      = [
          - "\"v=DKIM1;\" \"k=rsa;\" \"p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrLHiExVd55zd/IQ/J/mRwSRMAocV/hMB3jXwaHH36d9NaVynQFYV8NaWi69c1veUtRzGt7yAioXqLj7Z4TeEUoOLgrKsn8YnckGs9i3B3tVFB+Ch/4mPhXWiNfNdynHWBcPcbJ8kjEQ2U8y78dHZj1YeRXXVvWob2OaKynO8/lQIDAQAB;\"",
          + "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrLHiExVd55zd/IQ/J/mRwSRMAocV/hMB3jXwaHH36d9NaVynQFYV8NaWi69c1veUtRzGt7yAioXqLj7Z4TeEUoOLgrKsn8YnckGs9i3B3tVFB+Ch/4mPhXWiNfNdynHWBcPcbJ8kjEQ2U8y78dHZj1YeRXXVvWob2OaKynO8/lQIDAQAB;",
        ]
        ttl          = 300
        type         = "TXT"
    }
```
### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The GCP API escapes quotes on the back end. Other approaches to this sort of behavior I am aware of is the way the AWS provider formats JSON blobs for IAM roles / policies which the AWS API munges and caused spurious modify operations on the next apply. Might work here?

### References

* #863

**Comment by emilymye** [comment]
From [rrdatas field docs](https://www.terraform.io/docs/providers/google/r/dns_record_set.html#rrdatas): 

> The string data for the records in this record set whose meaning depends on the DNS type. For TXT record, if the string data contains spaces, add surrounding '" if you don't want your string to get split on spaces. 

If you'd intended for the spaces to split, we could add a diffsuppress, but I think in the past we haven't included it so it's more obvious if a user runs into the situation where GCP is splitting their rrdatas on spaces.

**Comment by rsalmond** [comment]
> if you don't want your string to get split on spaces.

So to clarify, if I _do_ want my string to be split on spaces then the expected behavior is that Terraform will show a change every time when no change exists?
