### ISSUE TITLE
Using a self_link in google_compute_forwarding_rule ip_address

### ISSUE THREAD

**Issue by MaT1g3R** [terraform-providers/terraform-provider-google#4072]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

According to the GCP docs, I can supply the link to an IP address when I'm creating a forwarding rule. Terraform lets me do this. However, after the first `terraform apply`, terraform tries to re-create the forwarding rule every time I run `terraform apply` again.

### Terraform Version
0.12.5

### Affected Resource(s)

* google_compute_forwarding_rule

### Terraform Configuration Files

```hcl
resource "google_compute_address" "tcp_ipv4" {
  name = "tcp-ipv4"
}

resource "google_compute_forwarding_rule" "jumphost_ssh" {
  project               = var.project_id
  name                  = "jumphost-ssh"
  target                = google_compute_target_pool.jumphost.self_link
  load_balancing_scheme = "EXTERNAL"
  port_range            = "22"
  ip_address            = google_compute_address.tcp_ipv4.self_link
}
```

### Expected Behavior

Terraform not re-creating the forwarding rule resource

### Actual Behavior

Terraform re-creating the forwarding rule resource
### Steps to Reproduce

1. `terraform apply`

### References

* #1543

**Comment by emilymye** [comment]
This is an interesting case where I'm not sure a diff suppress will fix this. It looks like the API replaces the value, and to determine whether the diff is valid or not, we'd actually have to get the address in question. I think a workaround while we get a fix out is to, instead of using self-link, use `google_compute_address.tcp_ipv4.address`, which will instead use the ip address and thus not cause a diff.

**Comment by MaT1g3R** [comment]
We are using `google_compute_address.tcp_ipv4.address` right now, but since the `self_link` version is still valid terraform config it would be nice that it gets fixed or made invalid, otherwise many users might run into the same problem that we had.
