### ISSUE TITLE
google_binary_authorization_policy: Improve declaration of admission_whitelist_patterns

### ISSUE THREAD

**Issue by mrtyler** [terraform-providers/terraform-provider-google#4090]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Each `admission_whitelist_patterns` block supports only one `name_pattern`. To specify multiple patterns, we must specify multilple `admission_whitelist_patterns` blocks.

This is uncomfortable for module authors, or anyone who might want to define `admission_whitelist_patterns` based on variable input. We worked around the limitation like this:

```tf
variable "binary_authorization_admission_whitelist_patterns" {
  default = ["my.repo/image1", "your.repo/image2"]
}


resource "google_binary_authorization_policy" "policy" {
...
  admission_whitelist_patterns {
    name_pattern = "${length(var.binary_authorization_admission_whitelist_patterns) > 0 ? element(var.binary_authorization_admission_whitelist_patterns, 0) : "PLACE.HOLDER/PATTERN"}"
  }
  admission_whitelist_patterns {
    name_pattern = "${length(var.binary_authorization_admission_whitelist_patterns) > 1 ? element(var.binary_authorization_admission_whitelist_patterns, 1) : "PLACE.HOLDER/PATTERN"}"
  }
  admission_whitelist_patterns {
    name_pattern = "${length(var.binary_authorization_admission_whitelist_patterns) > 2 ? element(var.binary_authorization_admission_whitelist_patterns, 2) : "PLACE.HOLDER/PATTERN"}"
  }
...
}
```

(Full code in context: https://github.com/gpii-ops/exekube/pull/62/files#diff-401a945a30f8418108760fde1baf4d09R30 )

### New or Affected Resource(s)

* google_binary_authorization_policy

### Potential Terraform Configuration

I wish I could pass a list directly:

```tf
variable "binary_authorization_admission_whitelist_patterns" {
  default = ["my.repo/image1", "your.repo/image2"]
}

resource "google_binary_authorization_policy" "policy" {
  ...

  admission_whitelist_patterns {
    name_patterns = "${var.binary_authorization_admission_whitelist_patterns}"
  }
}
```

Another Terraform-ish way it might work using a separate resource and `count`:

```tf
variable "binary_authorization_admission_whitelist_patterns" {
  default = ["my.repo/image1", "your.repo/image2"]
}

resource "google_binary_authorization_policy" "policy" {
  ...
}

resource "google_binary_authorization_policy_admission_whitelist_pattern" "pattern" {
  count = "${length(var.binary_authorization_admission_whitelist_patterns)"
  policy = "${google_binary_authorization_policy.policy.id}"
  pattern = "${element(var.binary_authorization_admission_whitelist_patterns, count.index)}"
}
```

I guess this problem becomes simpler with Terraform 0.12 and https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks, so perhaps the best solution to this issue is to wait for 0.12's more powerful syntax to become more widely used.

**Comment by emilymye** [comment]
This is made much easier by 0.12/foreach, and we would rather you upgrade if possible, since it is the recommended syntax rather than a "beta feature". A 0.11-only fix would require the resource structure to change (e.g. deprecations/multiple fields for the same things), which we like to avoid (especially since this matches the API structure and they may add more fields to the `admissionWhitelistPatterns` object). You could use the 0.11 syntax and maybe provide a list of blocks, but it's not recommended.
