### ISSUE TITLE
missing google_compute_network_endpoint_group data source

### ISSUE THREAD

**Issue by one1zero1one** [terraform-providers/terraform-provider-google#4096]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Data source for `google_compute_network_endpoint_group` would be useful to safer/better automate gke resources with traffic manager. Currently using 

```
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"XXXX":{}}}'
```

GKE creates a convenient NEG that can be used outside the cluster, e.g with traffic manager etc. Terraform can express pretty much all the bits needed to setup lb's, but can't easily include objects created by GKE.

### New or Affected Resource(s)

* google_compute_network_endpoint_group

### Potential Terraform Configuration

The way I work around it now, is by data external.
```tf
data "external" "negs" {
  program = ["bash", "${var.path}/data-external-scripts/get-negs.sh"]
  query = {
    service = var.service
  }
}
```

where the `get-negs.sh` is a flatten map with NEGs links.
I use the service name as a filter, not completely happy with it, but did not find another way.

```bash
#!/bin/bash

# Exit if any of the intermediate steps fail
set -e

# Extract "foo" and "baz" arguments from the input into
# FOO and BAZ shell variables.
# jq will ensure that the values are properly quoted
# and escaped for consumption by the shell.
eval "$(jq -r '@sh "SERVICE=\(.service)"')"

# Placeholder for whatever data-fetching logic your script implements
SERVICE="$SERVICE"

gcloud beta compute network-endpoint-groups list --format json |  jq --arg target "$SERVICE" '[.[] | select( .name | contains($target))] | [.[] | { (.selfLink): .selfLink }] | add'
```

Then,  in a `google_compute_backend_service` resource, I create as many backends my service has `for_each`

```tf
  dynamic "backend" {
    for_each = keys(data.external.negs.result)
    content {
      group                 = backend.value
      balancing_mode        = "RATE"
      max_rate_per_endpoint = var.max_rate_per_endpoint
    }
  }
```

**Comment by emilymye** [comment]
Whoops, forgot to close this - done by community contributor @bpineau very soon after the issue was opened in https://github.com/GoogleCloudPlatform/magic-modules/pull/2112
