### ISSUE TITLE
Add docs for beta custom routes in google_compute_network_peering

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#4097]
Looks like this got missed as part of https://github.com/GoogleCloudPlatform/magic-modules/pull/1695/

**Comment by ocervell** [comment]
@rileykarson can we please add the docs ? Lots of customers are wondering why this is not documented so far.

**Comment by rileykarson** [comment]
I can get to it next week, probably landing for `3.1.0` on ~12/3

**Comment by mllu** [comment]
@rileykarson Do you by any chance know if this'll work for gke-managed peerings as mentioned in https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#master-on-prem-routing?

**Comment by rileykarson** [comment]
Yes, they'd work. You'd need to read the values of the peering resource manually and write it out right now, then run `terraform import` so Terraform knows to manage it.

We could improve that by exporting the `peeringName` from `google_container_cluster` and adding a datasource for peerings; then, the only manual step would be import.

**Comment by mllu** [comment]
I see, thanks for the info, but I just tried to import `google_compute_network_peering`, it showed me the following error message, wondering if it's expected?
```
Error: resource google_compute_network_peering doesn't support import
```

**Comment by rileykarson** [comment]
1. You should have permission to read the network, I think? GKE should put the nodes in an existing network you control. 

2. Ah, import used to be somewhat uncommon in this provider but nearly all newer resources now support it. I'd assumed `google_compute_network_peering` did, but I guess not. It's an older one. Mind filing an issue asking for import support on it, so that we can track that separately?

**Comment by mllu** [comment]
will do, realized someone already created such issue https://github.com/terraform-providers/terraform-provider-google/issues/4793

**Comment by rileykarson** [comment]
Ah, great. Looks like the PR got dropped- I'll get the reviewer looking at it again.
