### ISSUE TITLE
Error messages from regular execution differ from error messages in debug mode

### ISSUE THREAD

**Issue by HebertCL** [terraform-providers/terraform-provider-google#4108]
I've been working on Terraform modules that involve DB instance, Database and DB user creation using version `0.12`. While running `terraform apply` during SQL database creation I received a strange error:

```google_sql_database.gcp_sql_database: Creating...

Error: Error creating Database: googleapi: got HTTP response code 404 with body: Not Found

  on main.tf line 43, in resource "google_sql_database" "gcp_sql_database":
  43: resource "google_sql_database" "gcp_sql_database" {
```

After a quick search I found similar issues related to [gcp database instance](https://github.com/terraform-providers/terraform-provider-google/issues/167) and [gcp disk](https://github.com/terraform-providers/terraform-provider-google/issues/436). In both issues the described workaround of using project ID in provider block instead of using it in the config itself is the setup I was using since the beginning.
You can find [my configuration here](https://gist.github.com/HebertCL/082d744756cccdf195eb20d2244ffa42). For simplicity I included all configs in the same file, but the issue remains the same both using modules or single config file. After some additional research I decided to run `terraform apply` in debug mode. Execution failed as expected, but the error output was different, instead of getting a longer 404 error description, I got a 403 error:

``` {
   "error": {
     "code": 403,
     "message": "Cloud SQL Admin API has not been used in project XXXXXXXXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=XXXXXXXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
     "errors": [
       {
         "message": "Cloud SQL Admin API has not been used in project XXXXXXXXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=XXXXXXXXXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
         "domain": "usageLimits",
         "reason": "accessNotConfigured",
         "extendedHelp": "https://console.developers.google.com"
       }
     ],
     "status": "PERMISSION_DENIED"
   }
 }
```

The complete debug output can be found [here](https://gist.github.com/HebertCL/8868d103fb762e6519c1e648bdf210ef). After I ran the apply with debug mode enabled I figured out what my issue was and how I was suppose to solve it. 
While I've found error messages in 0.12 version far more clear and descriptive, this 404 error message was useless (I know, this comes from Google API and not from Terraform) and rather deceiving from the real issue.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

0.12.5

### Affected Resource(s)

google_sql_database_instance
google_sql_database

### Terraform Configuration Files

https://gist.github.com/HebertCL/082d744756cccdf195eb20d2244ffa42

### Debug Output

https://gist.github.com/HebertCL/8868d103fb762e6519c1e648bdf210ef

### Expected Behavior

Terraform should have failed with a `403` error due SQL Admin api disabled. 

### Actual Behavior

Terraform returns a `404` error message that does not reflect the actual issue.

### Steps to Reproduce

`terraform init`
`terraform plan`
`terraform apply`
`TF_LOG=DEBUG terraform apply`

**Comment by HebertCL** [comment]
## Quick update

I continued working on this issues. I had difficulties testing this due Google platform API issues, but after a while ended up getting a consistent 404 error. At this point, with the same config file I keep getting 404s. So this may actually be a bug again for Terraform 0.12. Unfortunately I haven't found a way around this. Any help would be greatly appreciated.

**Comment by HebertCL** [comment]
# Workaround

I did some additional research and got some input from office colleagues I will document below in case someone comes across this issue. 

## Using depends_on

An initial thought was that maybe instance wasn't completely ready when I was trying to provision the SQL database, so I decided to add a dependency to it

```resource "google_sql_database" "gcp_sql_database" {
  depends_on  = [
    "google_sql_database_instance.gcp_sql_db_instance",
  ]

  name      = var.gcp_sql_database_name
  instance  = google_sql_database_instance.gcp_sql_db_instance.self_link
}
```
This didn't work and I still got the same 404 error.

## Using local-exec

One of my colleagues at office suggested if some form of `sleep` could be included in the execution just to give an extra time for the instance to be ready before database creation and I tried with `local-exec`. While it now sounds dumb to me (local-exec as its name suggests, executes a command in the machine where Terraform is executed), gave me a hint to accomplish what I was looking for.
So instead of just using a simple sleep I decided to create my DB using `local-exec` with gcloud. The block that handles the DB creation looks like this:

```provisioner "local-exec" {
    command =  "sleep 30; gcloud sql databases create $DATABASE --instance=$INSTANCE --project=$PROJECT --async"

    environment = {
      DATABASE = var.gcp_sql_database_name
      INSTANCE = google_sql_database_instance.gcp_sql_db_instance.name
      PROJECT  = var.gcp_project
    }
  }
```
It is worth noting a few things here: 
- I am using a `sleep 30` inside my local-exec provisioner. This might not be necessary, but I decided to wait 30 more seconds to be extra safe.
- Gcloud documentation to [create database](https://cloud.google.com/sdk/gcloud/reference/sql/databases/create) states that `--instance` flag is the only one required. My first attempt to create my DB using gcloud still failed with the same 404 error:
```
google_sql_database_instance.gcp_sql_db_instance: Provisioning with 'local-exec'...
google_sql_database_instance.gcp_sql_db_instance (local-exec): Executing: ["/bin/sh" "-c" "sleep 30; gcloud sql databases create $DATABASE --instance=$INSTANCE --async"]
google_sql_database_instance.gcp_sql_db_instance: Still creating... [3m0s elapsed]
google_sql_database_instance.gcp_sql_db_instance: Still creating... [3m10s elapsed]
google_sql_database_instance.gcp_sql_db_instance: Still creating... [3m20s elapsed]
google_sql_database_instance.gcp_sql_db_instance (local-exec): ERROR: (gcloud.sql.databases.create) HTTPError 404: Not Found


Error: Error running command 'sleep 30; gcloud sql databases create $DATABASE --instance=$INSTANCE --async': exit status 1. Output: ERROR: (gcloud.sql.databases.create) HTTPError 404: Not Found
```
Since the beginning of this issue I found several posts referring to this 404 errors with google api and it seems that it is expected if you don't explicitly include the `--project` flag. After I included this flag provisioning completed successfully.

I must say this is not the ideal workaround from a modular approach. It also seems that API call from Terraform to GCP resource (not sure if this only happens to database resources) is failing to pass that `--project` flag and causing this error.

Hope this long update helps to solve this issue or guide someone with the same situation.

**Comment by paddycarver** [comment]
This is incredibly bizarre and I'm going to have to see if I can replicate it, because it sounds like a [heisenbug](https://en.wikipedia.org/wiki/Heisenbug), a bug that changes its behavior when you try to study it. Turning on debug logging shouldn't alter the behavior of the program, and the fact that we're reportedly reliably getting different errors depending on whether debug mode is on or not is baffling to me.

**Comment by HebertCL** [comment]
I just gave another shot to this issue. This time around I decided to test with debug mode on and off testing database and db instance creation in an isolated project with SQL Admin API disabled on purpose.
As expected, a 403 error like this showed up despite the debug mode on or off:
```"error": {
     "code": 403,
     "message": "Cloud SQL Admin API has not been used in project XXXXXXXXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=XXXXXXXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
     "errors": [
       {
         "message": "Cloud SQL Admin API has not been used in project XXXXXXXXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=XXXXXXXXXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
         "domain": "usageLimits",
         "reason": "accessNotConfigured",
         "extendedHelp": "https://console.developers.google.com"
       }
     ],
     "status": "PERMISSION_DENIED"
   }
```
I went on and enabled the required API, and after a few mins tried again. The result this time was a successful run. 
Next, I commented my `local-exec` block and used a module for database creation to make sure no more 404 errors came across. Again, execution completed successfully and both instance and database got created.

My conclusion here is that the deceiving error messages I faced the first time were the result of GCP issues in the region I was working with (In fact I found out later in https://status.cloud.google.com/ a number of services were facing issues) during those days.
That being said, I think this issue can be closed. Thanks @paddycarver for checking this out.
