### ISSUE TITLE
Assign/Reassign a google project to a folder.

### ISSUE THREAD

**Issue by rosbo** [terraform-providers/terraform-provider-google#411]
This affects the existing `google_project` resource.

The following use cases should be supported:
* Create a new project inside an existing folder
(Implementation note: I'd suggest to add a "folder_id" attribute to "google_project". This should only require a minor change to the call to v1/projects/create. If "folder_id" is set, then parent ResourceId.type="folder".)
* Move a TF-managed GCP project between folders and between org node and folder.
(Implementation note: This should be just a matter of updating the project with the appropriate parent ResourceId.)

#132 is the parent task tracking all the work necessary to fully support `Folders` in Terraform.

**Comment by rosbo** [comment]
@ubschmidt2 & @srivasta are working on it

**Comment by srivasta** [comment]
I now have a working solution which passes acceptnce tests.

**Comment by rosbo** [comment]
Great. Add me as a reviewer to your PR whenever it is ready. Thank you Manoj!

**Comment by srivasta** [comment]
Hi,


   I don't have permissions to add reviewers, but
https://github.com/terraform-providers/terraform-provider-google/pull/438
is out there to be reviewed.


   Manoj

On Fri, Sep 15, 2017 at 9:49 AM, Vincent Roseberry <notifications@github.com
