### ISSUE TITLE
Dataproc enable "Component gateway"?

### ISSUE THREAD

**Issue by kdzhao** [terraform-providers/terraform-provider-google#4128]
Hello,
The gcp console UI allows to create a Dataproc with Component gateway, like: 
```
Component gateway  
Enable access to the web interfaces of default and selected optional components on the cluster. Learn more. 
```
However, it seems the google Terraform provider does not support it: 
https://www.terraform.io/docs/providers/google/r/dataproc_cluster.html

Is that right? If yes, can we add that function? 

Thanks!

**Comment by emilymye** [comment]
For reference, this is enabled through [endpointconfig.enableHttpPortAccess](https://cloud.google.com/dataproc/docs/reference/rest/v1beta2/ClusterConfig#endpointconfig) based on https://cloud.google.com/dataproc/docs/concepts/accessing/dataproc-gateways

**Comment by kdzhao** [comment]
Is it doable using Terraform yet? Thanks.

**Comment by emailbob** [comment]
I don't think it is. I don't see enableHttpPortAccess supported in the latest version yet https://github.com/terraform-providers/terraform-provider-google/blob/release-2.14.0/google/resource_dataproc_cluster.go

**Comment by c2thorn** [comment]
We've reached out to the Dataproc team and at this time it is not clear whether or not future stages will be backwards compatible. We would want to wait until the Component Gateway is at least in Beta to add support in the beta provider.

That being said, I have the alpha version working in this open PR here:
https://github.com/terraform-providers/terraform-provider-google-beta/pull/1298

**Comment by newtorob** [comment]
Once component gateway moves to Beta stages, would it be useable with Terraform? Or is it something we have to wait until post-beta? 

Thanks.

**Comment by c2thorn** [comment]
@newtorob Once it hits beta, the feature would go straight to the [google-beta](https://github.com/terraform-providers/terraform-provider-google-beta) provider. When made generally available, it would be moved over to this provider.

**Comment by samhumphreys-2sixty** [comment]
The component gateway is now in Beta. Is there an update on availability for the google-beta provider? 

Thanks
