### ISSUE TITLE
Configure constraints on a GCP folder

### ISSUE THREAD

**Issue by rosbo** [terraform-providers/terraform-provider-google#414]
Blocked by #412 

Implementation note: Constraints can be set on the org node, folder(s), and the project, thus need a solution that works (or could be extended to work) for all levels.

#132 is the parent task tracking all the work necessary to fully support Folders in Terraform.

**Comment by srivasta** [comment]
If noone else is working on it, I can have a crack at this one

**Comment by rosbo** [comment]
That would be awesome!

**Comment by srivasta** [comment]
Unfortunately, I am off on vacation, so I withdraw my claim on this. Please feel free to pick this up.

**Comment by rosbo** [comment]
Note to the implementer:
Should reuse a lot of what has been done for org policies at the org level: #523
