### ISSUE TITLE
google bigtable on terraform cannot take more than two clusters

### ISSUE THREAD

**Issue by avaldes19** [terraform-providers/terraform-provider-google#4150]
I am using terraform and the resource is google_bigtable_instance. When using more than 2 clusters I get the error:

**Error: Too many cluster blocks on line 0: (source code not available) No more than 2 "cluster" blocks are allowed**

The google web console allows to have up to 4 clusters.

**Could you help me raise the limit to 4?**

**Comment by megan07** [comment]
Thanks @avaldes19 for opening this issue. It's been closed with #4156 and will be released shortly.
