### ISSUE TITLE
Support for http/2 in google_compute_health_check

### ISSUE THREAD

**Issue by jschiff** [terraform-providers/terraform-provider-google#4151]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Looking for exactly what is described in https://github.com/terraform-providers/terraform-provider-google/issues/3641, which I feel was closed in error. We can now create http2 backend services, but we cannot create http/2 health checks, which are sorely needed especially for gRPC services.

### New or Affected Resource(s)

google_compute_health_check

### Potential Terraform Configuration

Copying this from the above-referenced locked issue.

```tf
resource "google_compute_health_check" "http2-health-check" {
 name = "http2-health-check"

 timeout_sec        = 1
 check_interval_sec = 1

 http2_health_check {
   port = "443"
   host = ""
   request_path = "/"
   response = ""
   proxy_header = "NONE"
 }
}
```

### References

This issue was (I believe) erroneously closed when adding http2 backend service support:

* #3641

**Comment by danawillow** [comment]
Added in https://github.com/GoogleCloudPlatform/magic-modules/pull/2195.
