### ISSUE TITLE
Creating a GKE cluster with istio add-on creates some cluster brokenness.

### ISSUE THREAD

**Issue by majelbstoat** [terraform-providers/terraform-provider-google#4152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.14
provider google 2.6.0
provider google-beta 2.6.0

### Affected Resource(s)

google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "primary" {
  provider = "google-beta"
  name     = "pinian-${terraform.workspace}"
  location = "${var.zone}"

  # Use a separately managed node pool
  remove_default_node_pool = true
  initial_node_count       = 1

  # Workaround for perpetual diff, see https://github.com/terraform-providers/terraform-provider-google/issues/988
  network    = "projects/pinian-app/global/networks/${google_compute_network.primary.name}"
  subnetwork = "projects/pinian-app/regions/${var.region}/subnetworks/${google_compute_subnetwork.primary_cluster.name}"

  min_master_version          = "${var.min_kubernetes_version}"
  enable_binary_authorization = true
  enable_tpu                  = true

  ip_allocation_policy {}

  resource_labels = {
    env       = "${terraform.workspace}"
    terraform = "true"
  }

  # Creating a cluster without master authorized networks is not possible, so we just mimic
  # openness by allowing access from anywhere, see https://issuetracker.google.com/issues/123071694
  master_authorized_networks_config {
    cidr_blocks {
      cidr_block   = "0.0.0.0/0"
      display_name = "anywhere"
    }
  }

  addons_config {
    http_load_balancing {
      disabled = false
    }

    istio_config {
      disabled = false
    }

    cloudrun_config {
      disabled = false
    }
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

### Expected Behavior

Terraform creates a stable GKE cluster with Istio add-on enabled, and Cloud Run add-on enabled.

### Actual Behavior

Two issues appear in the default workloads created:

A job, `istio-security-post-install-1.1.7`, fails to complete.
The `cluster-local-gateway` deployment is continually killed and restarted.

These were originally reported on GKE's issue tracker:

* https://issuetracker.google.com/issues/138481985
* https://issuetracker.google.com/issues/138474645

During attempts to reproduce, I cloned the cluster from the GKE Dashboard, and neither issue happened in the new cluster.

### Steps to Reproduce

Firstly, because I didn't know the precise terraform config I needed, I created a cluster from the GKE dashboard. I then `terraform import`d it and ran `terraform plan` repeatedly, adjusting the config until it no longer had any updates to make. This is how I built the config above. The original cluster did not exhibit either problem.

I then deleted the original cluster and ran `terraform apply` to rebuild it from scratch.

The issue has happened on all clusters created with this definition. It has not happened on clusters created through the dashboard that I import, and for which terraform plan does not suggest any more work.

### Important Factoids

N/A

### References

* https://issuetracker.google.com/issues/138481985
* https://issuetracker.google.com/issues/138474645

**Comment by paddycarver** [comment]
Can you give me a more complete config? For example, what config are you using for your "separately managed node pool"?

**Comment by majelbstoat** [comment]
Sure thing :)

```
resource "google_container_node_pool" "primary" {
  name               = "primary-node-pool"
  location           = "${var.zone}"
  initial_node_count = "${var.initial_node_count}"
  cluster            = "${google_container_cluster.primary.name}"

  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]

    labels = {
      env       = "${terraform.workspace}"
      terraform = "true"
    }

    metadata = {
      disable-legacy-endpoints = "true"
    }

    machine_type = "${var.machine_type}"
  }

  management {
    auto_repair  = true
    auto_upgrade = true
  }

  autoscaling {
    min_node_count = "${var.min_node_count}"
    max_node_count = "${var.max_node_count}"
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

There is also a subnet and compute network. Let me know if you think that's important. The GKE min master network is 1.13.7-gke.8.

**Comment by edwardmedia** [comment]
@majelbstoat it seems to be fine that both services are successfully enabled using below code. How many nodes did you specified? 
```
resource "google_container_cluster" "primary" {
  provider = "google-beta"
  name               = "issue-4162"
  location           = "us-central1-a"
  initial_node_count = 5

  master_auth {
    username = ""
    password = ""

    client_certificate_config {
      issue_client_certificate = false
    }
  }

  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]

    metadata = {
      disable-legacy-endpoints = "true"
    }

    labels = {
      foo = "bar"
    }

    tags = ["foo", "bar"]
  }

  timeouts {
    create = "30m"
    update = "40m"
  }

  addons_config {
    http_load_balancing {
      disabled = false
    }

    istio_config {
      disabled = false
    }

    cloudrun_config {
      disabled = false
    }
  }
}
```

**Comment by majelbstoat** [comment]
I can't recall, I think it was 3.

**Comment by edwardmedia** [comment]
@majelbstoat  can you retry with 5 nodes? Let me know what you see.

**Comment by edwardmedia** [comment]
@majelbstoat I am closing this issue. Please feel free to reopen it if you still see an issue with it
