### ISSUE TITLE
Can't import google_compute_router_nat, "Import id doesn't match any of the accepted formats"

### ISSUE THREAD

**Issue by dpkirchner** [terraform-providers/terraform-provider-google#4162]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.6
+ provider.google v2.12.0
```

### Affected Resource(s)

* `google_compute_router_nat`

### Terraform Configuration Files

```tf
provider "google" {
  project     = "${var.project_id}"
  region      = "${var.default_region}"
  zone        = "${var.default_zone}"
}

resource "google_project_services" "project" {
  project  = "${var.project_id}"
  services = ["compute.googleapis.com", "container.googleapis.com", "oslogin.googleapis.com"]
  disable_on_destroy = false
}

resource "google_compute_network" "default" {
  name = "primary"
  auto_create_subnetworks = false
  delete_default_routes_on_create = false
}

resource "google_compute_router" "router" {
  name    = "router-us-west2"
  region  = "us-west2"
  network = "${google_compute_network.default.self_link}"
  bgp {
    asn = 64512
  }
}

resource "google_compute_subnetwork" "default" {
  name                     = "subnet-1"
  network                  = "${google_compute_network.default.self_link}"
  ip_cidr_range            = "10.1.0.0/23"
  region                   = "us-west2"
  private_ip_google_access = true
}

resource "google_compute_address" "address" {
  count  = 1
  name   = "nat-external-address-${count.index}"
  region = "us-west2"
}

resource "google_compute_router_nat" "nat-1" {
  name                               = "nat-1"
  router                             = "${google_compute_router.router.name}"
  region                             = "us-west2"
  nat_ip_allocate_option             = "MANUAL_ONLY"
  nat_ips                            = google_compute_address.address[*].self_link
  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"
  log_config {
    filter = "ERRORS_ONLY"
    enable = true
  }
}
```

### Debug Output

https://gist.github.com/dpkirchner/1e6ffc9a58c0b02d04c10eaf54beba90

### Expected Behavior

I expected terraform to try to import a Cloud NAT config.

### Actual Behavior

```
terraform import google_compute_router_nat.nat-1 nat-1
google_compute_router_nat.nat-1: Importing from ID "nat-1"...

Error: Import id "nat-1" doesn't match any of the accepted formats: [(?P<project>[^/]+)/(?P<region>[^/]+)/(?P<router>[^/]+)/(?P<name>[^/]+) (?P<region>[^/]+)/(?P<router>[^/]+)/(?P<name>[^/]+) (?P<router>[^/]+)/(?P<name>[^/]+)]
```

I tried other values (nat_1, nat1).

### Steps to Reproduce

1. Create the configs
2. `terraform import google_compute_router_nat.nat-1 nat-1`

That's it. I'm not sure if you need to have an existing Google project.

### Important Factoids

Not AFAIK.

### References

https://github.com/terraform-providers/terraform-provider-google/issues/3538

* #0000

**Comment by Chupaka** [comment]
According to the docs https://www.terraform.io/docs/providers/google/r/compute_router_nat.html, there are three accepted formats:

$ terraform import google_compute_router_nat.default {{project}}/{{region}}/{{router}}/{{name}}
$ terraform import google_compute_router_nat.default {{region}}/{{router}}/{{name}}
$ terraform import google_compute_router_nat.default {{router}}/{{name}}

Which one do you use?

**Comment by dpkirchner** [comment]
Ah, I wasn't using any of those. I was just using the name. I totally misunderstood the syntax. Thanks!
