### ISSUE TITLE
google_monitoring_alert_policy filter invalid value must specify a restriction on "resource.type"

### ISSUE THREAD

**Issue by ScubaDrew** [terraform-providers/terraform-provider-google#4165]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

terraform -v
Terraform v0.11.14
+ provider.aws v2.21.1
+ provider.google v2.11.0
+ provider.google-beta v2.11.0
+ provider.helm v0.10.0
+ provider.kubernetes v1.8.1
+ provider.local v1.3.0
+ provider.template v2.1.2

### Affected Resource(s)

google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_monitoring_alert_policy" "logging_bytes_alert_policy" {
  project = "${var.project}"
  display_name = "Logging Bytes"
  enabled = true
  combiner = "OR"
  notification_channels = [
    "${var.notificationChannels}"
  ]
  conditions {
    display_name = "Logging Bytes Condition"
    condition_threshold {
      threshold_value = "${var.threshold_value_bytes}"
      filter = "metric.type=\"logging.googleapis.com/byte_count\""
      duration = "600s"
      comparison = "COMPARISON_GT"
      trigger {
        count = 1
      }
      aggregations {
        alignment_period = "60s"
        per_series_aligner = "ALIGN_RATE"
        cross_series_reducer = "REDUCE_SUM"
        group_by_fields = [
          "metric.label.log"
        ]
      }
    }
  }
}
```

### Expected Behavior

In GCP Monitoring I can create this alert without the resource.type. I exported the JSON from the console:

```
{
  "combiner": "OR",
  "conditions": [
    {
      "conditionThreshold": {
        "aggregations": [
          {
            "alignmentPeriod": "60s",
            "groupByFields": [
              "metric.label.log"
            ],
            "perSeriesAligner": "ALIGN_RATE"
          }
        ],
        "comparison": "COMPARISON_GT",
        "duration": "600s",
        "filter": "metric.type=\"logging.googleapis.com/log_entry_count\"",
        "thresholdValue": 400,
        "trigger": {
          "count": 1
        }
      },
      "displayName": "Logging Entries Condition"
    }
  ],
  "displayName": "Logging Entries",
  "enabled": true,
  "incidentStrategy": {},
  "notificationChannels": [
xxx
  ]
}
```

### Actual Behavior

```
2019/08/05 14:45:56 [ERROR] root.logging_alerts: eval: *terraform.EvalApplyPost, err: 1 error occurred:
	* google_monitoring_alert_policy.logging_bytes_alert_policy: Error updating AlertPolicy "projects/nuorder-staging/alertPolicies/2612755766349xxxxxx": googleapi: Error 400: Field alert_policy.conditions[0].condition_threshold.filter had an invalid value of "metric.type="logging.googleapis.com/byte_count"": must specify a restriction on "resource.type" in the filter; see "https://cloud.google.com/monitoring/api/resources" for a list of available resource types.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by abhijitchaudhari1** [comment]
Try adding 
```
AND resource.type=\"metric\"
```
to your filter.

Something like this

```
filter = "metric.type=\"logging.googleapis.com/byte_count\" AND resource.type=\"metric\"",
```

**Comment by rileykarson** [comment]
It appears you're using different `filter` values? The first example is `      filter = "metric.type=\"logging.googleapis.com/byte_count\""` vs `        "filter": "metric.type=\"logging.googleapis.com/log_entry_count\""` in the second. Can you try an identical `filter` value in each?

**Comment by ScubaDrew** [comment]
> It appears you're using different `filter` values? The first example is ` filter = "metric.type=\"logging.googleapis.com/byte_count\""` vs ` "filter": "metric.type=\"logging.googleapis.com/log_entry_count\""` in the second. Can you try an identical `filter` value in each?

@rileykarson I can confirm that log_entry_count works without resource but byte_count fails. Adding `resource.type=\"gke_container\"` to the filter fixes it. The resource is NOT required in Stack driver metric explorer in either case. 

I'm fine closing this as I can track down the resource type - but it remains strange behavior.

**Comment by rileykarson** [comment]
That's surprising, that it works there but not here. We're hitting the API directly, so I wonder if they provide a default value like `metric` as in https://github.com/terraform-providers/terraform-provider-google/issues/4165#issuecomment-519098176.

I'm going to close this out because I think we're sending the right request and hitting an API limitation. If you're able to find the exact `filter` value the console returns (such as through the [Api Explorer](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies/get)) and it's different than you expect, getting closer to that is something we could look into Terraform doing.

**Comment by lawliet89** [comment]
I encountered the exact same issue. I tried comparing the updates of the resource in both Terraform and in the UI.

Terraform uses PATCH `https://monitoring.googleapis.com/v3/projects/<PROJECT>/alertPolicies/<ID>` endpoint to do the update.

The UI uses POST `https://monitoring.clients6.google.com/v3/projects/<PROJECT>:parseTimeSeriesFilter?key=<REDACTED>` instead.

<details><summary>POST info</summary>
POST Body:

```json
{"filter":"metric.type=\"logging.googleapis.com/user/<redacted>\" project=\"<PROJECT>\""}
```
</details>

The UI uses a different set of undocumented APIs that treats the input differently. I will raise a support case with GCP and see what they say.

**Comment by lawliet89** [comment]
After a frustrating back and forth with GCP support, they pointed me to this issue: https://issuetracker.google.com/issues/143436657
