### ISSUE TITLE
Can't specify empty set of taints on GKE node pools

### ISSUE THREAD

**Issue by shields-fn** [terraform-providers/terraform-provider-google#4168]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.6
+ provider.google v2.12.0
+ provider.google-beta v2.12.0

### Affected Resource(s)

* google_container_cluster
* google_container_node_pool

### Terraform Configuration Files

Before:
```tf
resource "google_container_cluster" "test" {
  provider = "google-beta"

  name               = "test"
  location           = "us-central1-b"
  initial_node_count = 1

  node_config {
    taint {
      key    = "K"
      value  = "V"
      effect = "NO_SCHEDULE"
    }
  }
}
```

After:

```tf
resource "google_container_cluster" "test" {
  provider = "google-beta"

  name               = "test"
  location           = "us-central1-b"
  initial_node_count = 1

  node_config {
  }
}
```

### Debug Output

https://gist.github.com/shields-fn/641926b7b3a68adc70e42dad82094563

### Panic Output

None

### Expected Behavior

The node pool should have been destroyed and recreated without Kubernetes taints.

### Actual Behavior

Nothing; `terraform plan` reports that no changes are needed.

### Steps to Reproduce

1. `terraform apply`
2. Remove `taint` section of config
3. `terraform apply`

**Comment by rileykarson** [comment]
Due to how this is implemented (as an `Optional` + `Computed` field), it'll end up being a breaking change to allow users to define empty taints.

GKE tends to add taints at will based on using certain features, so I'm not sure that requiring users to always define their node pool taints in their TF config is a great idea, although sticking unnecessary taints on users' node pools isn't great either.

**Comment by nicktrav** [comment]
Not sure I agree with the assessment that this isn't a bug, irrespective of whether a fix would be a breaking change or not.

Concretely, we had a node pool defined with a taint. I then removed the taint in terraform but this did nothing to the node pool. The taint remains. At this point, my state doesn't match my intent.

Are there any known workarounds in the interim?

**Comment by nicktrav** [comment]
@rileykarson - noticed this was closed. Will this be in a 2.x release of the provider?

**Comment by rileykarson** [comment]
This will appear in a `3.X` release.

https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/version_3_upgrade.html.markdown#taint-field-is-now-authoritative-when-set contains some justification for why it's there and couldn't have landed in a `2.X` release. While minor, there were technically 2 breaking changes made on the field.
