### ISSUE TITLE
Fix 2.10.0 / 2.11.0 changelogs

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#4172]
We named the `2.10.0` changelog entry as the `2.11.0` changelog, and missed the real `2.11.0` changelog at `master`. We should fix the naming + add the missing entry.

@paddycarver, assigning you to this. If you won't have cycles to do this anytime soon please raise with me / in Slack!

**Comment by paddycarver** [comment]
I'll take care of this today, sorry about that. I think I had a human error with updating the CHANGELOGs for the last release.
