### ISSUE TITLE
400 error badRequest - cloud function deploy

### ISSUE THREAD

**Issue by tmprender** [terraform-providers/terraform-provider-google#4178]
### Community Note

 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

* If you are interested in working on this issue or have submitted a pull request, please leave a comment

* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

 

 

### Terraform Version

 

 

v0.11.13

 

### Affected Resource(s)

 

 

* google_cloud_functions

 

### Terraform Configuration Files

 

 

```tf

`provider "google" {

  region      = "us-central1"

  credentials = "${file("../../../terraform-service-account.json")}"

}

 

resource "google_cloudfunctions_function" "autorem-org-policy"{

  name = "${var.name}"

  description = "${var.description}"

  project = "${var.project_id}"

  region = "us-central1"

  available_memory_mb = 256

  source_archive_bucket = "${var.source_bucket}"

  source_archive_object = "${var.source_object}"

  timeout = 60

  entry_point = "set_org_policy"

  event_trigger {

    event_type = "providers/cloud.pubsub/eventTypes/topic.publish"

    resource = "projects/terraform-p1/topics/autorem-org-policies"

    }

  runtime = "python37"

}
# Copy-paste your Terraform configurations here - for large Terraform configs,

# please use a service like Dropbox and share a link to the ZIP file. For

# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security

# If reproducing the bug involves modifying the config file (e.g., apply a config,

# change a value, apply the config again, see the bug) then please include both the

# version of the config before the change, and the version of the config after the change.

```

 

### Debug Output

 

 https://gist.github.com/tmprender/d4245192035d94c0a260eaf2c400d42e
 

### Expected Behavior

 

Function deploys

 

### Actual Behavior

 

400 Error, badRequest

 

### Steps to Reproduce

 

 

1. `terraform apply`

 

### Important Factoids

 

 

function has event_trigger

 

### References

 

https://github.com/terraform-providers/terraform-provider-google/issues/1173
-the above post was resolved by adjusting the region field to 'us-central1'
 

* #0000

**Comment by rileykarson** [comment]
Currently, we only support shortnames (eg: `"autorem-org-policies"`) for the `event_trigger.resource` field. I'll add support for partial URI form as well, though, where we don't try to construct the partial URI based on the `event_type` value.
