### ISSUE TITLE
Enabling or changing VPC Flow Logs parameters should not force the VPC subnet resource recreation

### ISSUE THREAD

**Issue by lainra** [terraform-providers/terraform-provider-google#4179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

terraform-providers/null 2.1.2

terraform-providers/google 2.12.0

terraform-providers/google-beta 2.12.0

### Affected Resource(s)

* google_compute_subnetwork

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug) then please include both the
# version of the config before the change, and the version of the config after the change.
resource "google_compute_subnetwork" "shared_vpc_subnetwork" {
  provider                 = "google-beta"
  project                  = "redacted"
  name                     = "shared-vpc-subnetwork"
  region                   = "redacted"
  network                  = "shared-vpc-network"
  ip_cidr_range            = "redacted"
  private_ip_google_access = "true"

  dynamic "secondary_ip_range" {
    for_each = var.secondary_ip_ranges

    content {
      range_name    = secondary_ip_range.value.name
      ip_cidr_range = secondary_ip_range.value.ip_cidr_range
    }
  }

  enable_flow_logs = var.enable_flow_logs

  log_config {
    aggregation_interval = var.flow_logs_aggregation_interval
    flow_sampling        = var.flow_logs_flow_sampling
    metadata             = var.flow_logs_metadata
  }
}
```

### Debug Output

https://gist.github.com/lainra/05dbdab45cc93892ce35c4a1ca3ecdda

### Panic Output

None

### Expected Behavior

Creating or editing VPC Flow Logs `logs_config` in the subnet should not force its re-creation.
VPC Flow Logs can be enabled, disabled, have it's log_config modified without implying the resource deletion.

### Actual Behavior

When enabling VPC Flow Logs with a `log_config` block, the subnet becomes subject to recreation.

### Steps to Reproduce

1. Prepare a similar manifest as above, specifying the `log_config` block.
1. `terraform plan`

### References

https://github.com/terraform-providers/terraform-provider-google-beta/blob/v2.12.0/google-beta/resource_compute_subnetwork.go#L108
https://github.com/terraform-providers/terraform-provider-google-beta/pull/619

**Comment by rileykarson** [comment]
Duplicates https://github.com/terraform-providers/terraform-provider-google/issues/3628
