### ISSUE TITLE
Enhancement | Enable target for internal regional forwarding rule 

### ISSUE THREAD

**Issue by JasperWoo** [terraform-providers/terraform-provider-google#4182]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We are trying to configure internal load balancer in GCP. From the GCP [documentation](https://cloud.google.com/load-balancing/docs/l7-internal/set-up-gce-vms), it creates a regional forwarding rule, with http proxy target. However, here in terraform I only see that option in a global forwarding rule as [here](https://github.com/terraform-providers/terraform-provider-google/blob/d28bfc7aafd59f9b089a9029707cac39a416134e/google/resource_compute_global_forwarding_rule_test.go), or documented as only used for external regional load balancer [here](https://www.terraform.io/docs/providers/google/r/compute_forwarding_rule.html).

### New or Affected Resource(s)

* google_compute_forwarding_rule

### Potential Terraform Configuration

I would need the `target` field to be enabled for `INTERNAL`, and can point to `target_http_proxy` resource, as follows:
```tf
resource "google_compute_forwarding_rule" "default" {
  name       = "forwarding-rule"
  target     = "${google_compute_target_http_proxy.default.self_link}"
  subnetwork = "${google_compute_subnetwork.default.self_link}"
  load_balancing_scheme = "INTERNAL"
  ip_address = "10.128.0.0"
}
```

### References

* #0000

**Comment by JasperWoo** [comment]
From what I understand now, the GCP documentation I provided is for google-beta provider. 

But before we close this ticket. I want to clarify, how can I view terraform documentation for google-beta provider specifically? There are options like `region` that is available in beta but not available in main. And when I try `terraform plan`, it complains about unrecognized field `region`

**Comment by rileykarson** [comment]
The `google_compute_forwarding_rule` resource should allow `region` regardless of the version through Terraform; is it possible you tried `google_compute_global_forwarding_rule`?

`target` is supported on the regional resource: https://www.terraform.io/docs/providers/google/r/compute_forwarding_rule.html#target

Our docs indicate that support is for ELB/XLB though, not ILB. We don't have full support for L7 ILB. Tracking for that is in https://github.com/terraform-providers/terraform-provider-google/issues/4190.

Since this field is supported, I'm going to close out this issue. Issues about L7 ILB should be deduped to the issue linked above.
