### ISSUE TITLE
In google_container_cluster, when network_policy is disabled, we get a 400 from Google

### ISSUE THREAD

**Issue by jtslear** [terraform-providers/terraform-provider-google#4187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.14
+ provider.google v2.7.0
```

### Affected Resource(s)

* google_container_cluster
* network_policy

### Terraform Configuration Files

```tf
<snip>
  addons_config {
    network_policy_config = {
      disabled = "${var.disable_network_policy}"
    }
  }

  network_policy {
    enabled  = "${var.disable_network_policy == "true" ? "false" : "true" }"
    provider = "${var.network_policy_provider}"
  }

<snip>
```

### Debug Output

https://gist.github.com/jtslear/ce6b8c8fc1de0d959dedf7c71e8e07a8

### Expected Behavior

When `disable_network_policy` is set to `true`, I do _not_ expect the network policy add-on to be enabled, and I do _not_ expect the `network_policy` to set the provider.

### Actual Behavior

The network policy addon remains disabled as desired, however the `network_policy` still attempts to apply the provider which fails with an API 400:

```
Terraform will perform the following actions:

  ~ module.gke-skarbek.google_container_cluster.cluster
      network_policy.0.provider: "" => "CALICO"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.gke-skarbek.google_container_cluster.cluster: Modifying... (ID: skarbek-test)
  network_policy.0.provider: "" => "CALICO"

Error: Error applying plan:

1 error occurred:
        * module.gke-skarbek.google_container_cluster.cluster: 1 error occurred:
        * google_container_cluster.cluster: googleapi: Error 400: The network policy addon must be enabled before updating the nodes., badRequest
```

### Steps to Reproduce

Using module here: https://gitlab.com/gitlab-com/gl-infra/terraform-modules/google/gke/tree/v5.0.0 with the example main.tf here: https://gist.github.com/jtslear/8d72d66a7ecd49d76193b86815d4e7b3

1. `terraform apply`

### References

* https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/7476

**Comment by rileykarson** [comment]
Terraform has a limited ability to handle complex diffs, and it's seeing a diff because the `provider` value is unset in state (since it can't be set) and your config is trying to set it. You'll need to supply the empty string for `var.network_policy_provider`. Using Terraform `0.12` it would be possible to omit the block when `disable_network_policy` is `true` altogether.

We have a limited ability to remediate this error in the provider itself. We're already sending an empty request to indicate disablement, it just seems the API isn't sure how to handle it.

Closing out since I believe this can be fixed with config, please update this if you find that isn't the case.

**Comment by jtslear** [comment]
@rileykarson Thank you for that information.

In fixing this, I later discovered I had issues with disabling both the network policy addon as well as the network policy for nodes at the same time.  It would appear the Google API doesn't allow such to happen and instead requires that they be done in sequential order.  I landed on this

```tf
  addons_config {
    network_policy_config = {
      disabled = "${var.disable_network_policy}"
    }
  }

  network_policy {
    enabled  = "${var.node_network_policy}"
    provider = "${var.node_network_policy == "true" ? var.network_policy_provider : "PROVIDER_UNSPECIFIED" }"
  }
```
