### ISSUE TITLE
Add support for L7 ILB

### ISSUE THREAD

**Issue by JasperWoo** [terraform-providers/terraform-provider-google#4190]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
`terraform -v`
Terraform v0.12.6
+ provider.google v2.12.0
+ provider.google-beta v2.12.0

### Affected Resource(s)

* google_compute_health_check, google_compute_forwarding_rule, etc

### Terraform Configuration Files

```tf
resource "google_compute_health_check" "default" {
  provider = "google-beta"
  name         = "packer-service-health-check"
  region                   = "us-central1"

  http_health_check {
      port_specification = "USE_SERVING_PORT"
  }
}
```

### Debug Output

https://gist.github.com/JasperWoo/c945a6856e0148e0744c4bd826fa3ca9

### Panic Output

None

### Expected Behavior
Import successfully

### Actual Behavior
Import fails with id not found; however gcloud beta compute describe gives correct data, proving the resource exists. (See gist).

### Steps to Reproduce

1. Create google_compute_health_check using `gcloud beta compute `
2. `terraform import -provider=google-beta <name of the health_check resource>`

### Important Factoids
None

### References
1. https://www.terraform.io/docs/providers/google/r/compute_health_check.html
2. https://cloud.google.com/load-balancing/docs/l7-internal/set-up-gce-vms

* #0000

**Comment by rileykarson** [comment]
This is a regional variant of the GCP health check used in L7 ILB, and support hasn't been added to the Google provider yet. I'm marking this as an enhancement request and re-titling it.

**Comment by rileykarson** [comment]
@tysen: Assigning since I think you're working on these. If there's another issue  can you dedupe to there?/ I'm wrong, feel free to correct the assignment.

**Comment by tysen** [comment]
I am indeed working on this :+1:

**Comment by morgante** [comment]
@tysen Any updates here?

**Comment by tysen** [comment]
Just merged https://github.com/GoogleCloudPlatform/magic-modules/pull/2363 but still need to update RegionUrlMap with the many new fields added for L7 ILB.
