### ISSUE TITLE
google_cloudbuild_trigger should support Invert Regex option in trigger_template

### ISSUE THREAD

**Issue by MichaelDao** [terraform-providers/terraform-provider-google#4195]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I am trying to setup my cloud build CI/CD in a way that one trigger will only run for the master branch and the second trigger will run on any branch except the master.

Usually I will be able to solve this with a regex with negative lookahead, e.g. `^(?!.*master).*$`

The problem here is that google cloud build triggers do not support any lookahead in their regex.

Luckily google provides us with an Invert Regex option!

![invertregex](https://user-images.githubusercontent.com/16555859/62760929-9a82ce00-bac8-11e9-80ec-f125eb61d849.png)

Anyways there seems to be nothing for the invert regex option as seen here:
https://www.terraform.io/docs/providers/google/r/cloud_build_trigger.html#trigger_template

This would be a nice feature to have, as a temporary workaround, I am ignoring anything that starts with master 
`^(?:[^m]|m[^a]|ma[^s]|mas[^t]|mast[^e]|maste[^r]|master.)`

I would like to help out as a contributor if possible, will need help though.

### New or Affected Resource(s)

* google_cloudbuild_trigger

### Potential Terraform Configuration

```tf
provider "google" {
    project = "my-project"
}

resource "google_cloudbuild_trigger" "trigger" {
    trigger_template {
        branch_name = "master"
        repo_name = "my-repo"
        invert_regex = true
    }
}
```

### References

* https://stackoverflow.com/questions/44008616/google-cloud-builder-how-to-build-all-branches-except-for-master
* https://stackoverflow.com/questions/53194830/build-trigger-doesnt-recognize-negative-lookahead-in-regexp-on-cloud-build

**Comment by MichaelDao** [comment]
I am interested in contributing, will take a deep dive into this.

**Comment by joeyorlando** [comment]
I could help out contributing this! 😃

**Comment by stephanlindauer** [comment]
i think, after this `invert` flag is currently not exposed through the [google cloud api](https://cloud.google.com/cloud-build/docs/api/reference/rest/Shared.Types/Build#RepoSource), there is not much we can do on the terraform provider side.
is there an ETA on when this flag will be exposed through the google api? @danawillow @paddycarver

**Comment by danawillow** [comment]
You're welcome to file an issue against the GCP API if it's something you'd like to see! https://cloud.google.com/support/docs/issue-trackers

**Comment by stephanlindauer** [comment]
please star this ticket to indicate that you are also effected by this missing api feature: https://issuetracker.google.com/issues/148122483

**Comment by harryparkdotio** [comment]
I believe it's now exposed via the api

---

https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.triggers#GitHubEventsConfig

https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.triggers#PushFilter

**Comment by stephanlindauer** [comment]
@danawillow how long until we can expect that to be in the provider?

**Comment by megan07** [comment]
Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/3628
