### ISSUE TITLE
Time For a New Release?

### ISSUE THREAD

**Issue by seanmalloy** [terraform-providers/terraform-provider-google#420]
We have a need for several of the features that have been merged into the master branch after the v0.1.3 release. It's been 27 days since the v0.1.3 release. It would be helpful to have a new official release, so we don't need to compile from source.

Would it be possible to get a new release cut soon?

CC: @zbikmarc @rameshvenk

**Comment by rameshvenk** [comment]
+1 for new release. This would help Kohls immensely. Thank you

**Comment by paddycarver** [comment]
We're currently working towards one, and hope to release it very soon. We're in the final phases of cleaning up some stuff and making sure that we have a smooth release. :) Sorry for the delay, and thanks for your patience!

**Comment by seanmalloy** [comment]
Sorry to be pushy ... but .... any updates on the new release?
