### ISSUE TITLE
no schema available for google_compute_managed_ssl_certificate

### ISSUE THREAD

**Issue by underflow00** [terraform-providers/terraform-provider-google#4208]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

v0.12.2

### Affected Resource(s)

* google_compute_managed_ssl_certificate

### Terraform Configuration Files

```tf
provider "google" {
  credentials = file("REDACTED")
  project = "REDACTED"
  region = "us-west1"
}
provider "google-beta" {
  credentials = file("REDACTED")
  project = "REDACTED"
  region = "us-west1"
}
resource "google_compute_managed_ssl_certificate" "cert1" {
  provider = "google-beta"
  name = "cert1"
  managed {
    domains = ["example.com"]
  }
}
```

### Debug Output

https://gist.github.com/underflow00/d25c72af10eebca1126b859c0db8188b

### Expected Behavior

Running `terraform destroy` when the `google_compute_managed_ssl_certificate` resource block is not specified does not error.

### Actual Behavior

Running `terraform destroy` when the `google_compute_managed_ssl_certificate` resource block is not specified produces:
`Error: no schema available for google_compute_managed_ssl_certificate.main while reading state; this is a bug in Terraform and should be reported`

### Steps to Reproduce

1. Run `terraform apply` with the above config.
1. Remove the resource block in the config.
1. Run `terraform destroy`.

**Comment by underflow00** [comment]
It appears to be because it uses `google-beta` instead of `google`. Not sure if it's a bug. Anyway, is there a workaround other than having to include it in the config?

**Comment by tysen** [comment]
This resource is only available in the beta provider. You have to include it in the config.
