### ISSUE TITLE
Environment variable precedence issue with backend and provider

### ISSUE THREAD

**Issue by nodesocket** [terraform-providers/terraform-provider-google#4209]
### Description

When setting the only supported environment variable `GOOGLE_CREDENTIALS` for `terraform.backend.gcs` for reading/writing to the Terraform state file in a Google Storage bucket, it is not possible to set the provider credentials using an environment variable `GOOGLE_CLOUD_KEYFILE_JSON` to different credentials because `GOOGLE_CREDENTIALS` always takes the highest precedence.

`GOOGLE_CREDENTIALS` points to credentials for one project _(call it project-a)_ which only has read/write access to the backend storage bucket.

`GOOGLE_CLOUD_KEYFILE_JSON` points to credentials for another project _(call it project-b)_ which should be used for all Terraform provider operations.

### New or Affected Resource(s)

`terraform.backend.gcs`
`provider.google`

### Suggestion

I'm not sure the best solution, perhaps add support for a lower priority environment variable to define `terraform.backend.gcs` like `GOOGLE_CLOUD_KEYFILE_JSON` then I can use the higher priority environment variable `GOOGLE_CREDENTIALS` for Terraform provider operations. Though, this probably has the reverse issue that the backend state file would use `GOOGLE_CREDENTIALS` instead of desired `GOOGLE_CLOUD_KEYFILE_JSON`.

**Comment by paddycarver** [comment]
I opened a PR to make the backend respect a `GOOGLE_BACKEND_CREDENTIALS` environment variable. This will allow credentials to be specified for the backend, and users won't need to worry about precedence at all.
