### ISSUE TITLE
Dataproc - Support Components

### ISSUE THREAD

**Issue by paul-opsguru** [terraform-providers/terraform-provider-google#4230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Will be great to have a support for DataProc 'Components features as per: https://cloud.google.com/dataproc/docs/concepts/components/overview as part of the existing `cluster_config` block, and not rely on init scripts for 3rd party components installations such as JupyterHub, Zeppelin, Presto and so on.

### New or Affected Resource(s)
* google_dataproc_cluster

Proposed configuration:

```tf
cluster_config {
components = ['PRESTO','ZEPPELIN']
}
```
### References
https://cloud.google.com/dataproc/docs/concepts/components/overview

* #0000

**Comment by megan07** [comment]
Thanks @paul-opsguru for opening this issue. It's been closed with #4073 and will be released shortly.
