### ISSUE TITLE
compute instance ssh-key not honouring dependencies

### ISSUE THREAD

**Issue by phil-bevan** [terraform-providers/terraform-provider-google#4251]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.0
+ provider.google v2.12.0
+ provider.null v2.1.2
### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
Module1:
locals {
  gcp_publickeyfile = "${var.sshpubkeyfile}gcp"
}

resource "null_resource" "write_public_key_file" {
  provisioner "local-exec" {
    command = "Get-Content -Path ${var.sshpubkeyfile} | ForEach-Object {$_.Replace(\"ddadmin\",\"${var.adminname}\")} |Set-Content -Path ${local.gcp_publickeyfile} -NoNewLine"
    interpreter = ["PowerShell", "-Command"]
  }
}

output "gcp_publickeyfile" {
  value = "${local.gcp_publickeyfile}"
  depends_on = ["null_resource.write_public_key_file"]
}

Which is passed into:

Module2:
resource "google_compute_instance" "dockerelk" {
  name         = "${var.customerprefix}-elk"
  machine_type = "${var.vmsize}"
  tags = ["elk","internal"]

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
      size = "${var.elk_disksize_gb}"
    }
  }

  network_interface {
    subnetwork = "${var.subnet}"
    access_config {
      nat_ip = ""
      network_tier = "PREMIUM"
    }
	network_ip = "${local.static_server_internal_ip}"
  }
  metadata = {
    ssh-keys = "${var.adminname}:${file("${var.sshpubkeyfile_gcp}")}"
  }
}
```

### Expected Behavior

Dependencies should ensure that compute instance ssh-key should be populated with the content of the keyfile AFTER it is modified by Module1

### Actual Behavior

```tf
Error: Provider produced inconsistent final plan

When expanding the plan for module.DockerELK.google_compute_instance.dockerelk
to include new values learned so far during apply, provider "google" produced
an invalid new value for .metadata["ssh-keys"]: was
cty.StringVal("xxxadmin:ssh-rsa <blob> ddadmin"), 
but now cty.StringVal("xxxadmin:ssh-rsa <blob> xxxadmin").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

1. `terraform apply`

terraform plan does not generate any errors

### Important Factoids

Also tried passing the file contents in the output variable rather than the file name, but behaviour is the same.

### References

* #0000

**Comment by tysen** [comment]
0.12 has some new checks that prevent application of values that change between plan and apply. The dependency is being honored but the value of `sshpubkeyfile_gcp` changes so Terraform rejects it. Similar issue here: https://github.com/terraform-providers/terraform-provider-google/issues/3987
