### ISSUE TITLE
(v1) project_iam_policy: see restore_policy and complete_policy on plan

### ISSUE THREAD

**Issue by tmshn** [terraform-providers/terraform-provider-google#4263]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

#### Background

Starting from v2.0.0, `google_project_iam_policy` removes `authoritative` field. To mitigate the risk of migration, it's better to set `authoritative=true` on v1.x before directly jumping into the v2.

#### What is the problem

Just setting `authoritative=true` and run `terraform plan`, you'll see a diff only on the `authoritative` field.

```
~ google_project_iam_policy.project
      authoritative: "false" => "true"
```

 However, Terraform will **_remove policy bindings_** which aren't specified on `policy_data` (=the one stored on the `restore_policy`)!!
This is huge risk (note that `restore_policy` usually contains the policy configured at the early stage of the project, which likely to be vital ones).

#### Purpose of this issue

- share codes that shows you complete policy applied to the project and restore_policy at the plan phase: see **References** section for the link
- propose to release v1.21.0 with above change, if possible

This repository does not have a branch for v1, which I understand the `terraform-provider-google` team are not willing to maintain v1.
Well, yeah, I know it's a high burden for dev team to keep multiple version of codebase. So it's okay to close this issue immediately as I already fulfilled my minimum purpose: share this info.

### New or Affected Resource(s)

* google_project_iam_policy on v1

### Potential Terraform Configuration

```tf
resource "google_project_iam_policy" "project" {
  project       = "${data.google_project.current.project_id}"
  authoritative = false
  policy_data   = "${data.google_iam_policy.partial.policy_data}"
}
```

↓

```tf
resource "google_project_iam_policy" "project" {
  project       = "${data.google_project.current.project_id}"
  authoritative = true
  policy_data   = "${data.google_iam_policy.partial.policy_data}"
}
```

### References

You can see the proposed changes here (the pr is opened on my own fork, since this repository has no v1 branch):

* https://github.com/tmshn/terraform-provider-google/pull/1

**Comment by paddycarver** [comment]
Hey @tmshn,

Thanks for the issue, and my apologies for the delayed response. I agree, that's a sub-optimal upgrade experience. Unfortunately, because of the way the Terraform's protocol works, we have limited control right now over the diffs. I know you have a bit of code that could help, but it's also a subtle area of code that has a lot of edge cases, and so making sure all the edge cases are handled is a lot of work and not an exact science.

Given 2.0.0 came out almost a year ago, and the majority of our users seem to have moved off it, I'm going to close this issue out. I appreciate the issue, though, and apologise for the rough upgrade experience. We'll try to make future upgrades easier and less painful.
