### ISSUE TITLE
GCS lifecycle_rule not created

### ISSUE THREAD

**Issue by Rukeith** [terraform-providers/terraform-provider-google#4273]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.6
+ provider.google v2.13.0
+ provider.google-beta v2.12.0
+ provider.random v2.1.2

### Affected Resource(s)

* google_storage_bucket
* random_id

### Terraform Configuration Files

```tf
resource "random_id" "db_name_suffix" {
  byte_length = 4
}

resource "google_storage_bucket" "prod" {
  provider = "google-beta"

  name          = "demo-${random_id.db_name_suffix.hex}"
  location      = "${var.region}"
  storage_class = "REGIONAL"

  labels = {
    project = "demo"
    service = "gcs"
    role    = "production"
  }

  retention_policy {
    is_locked        = false
    retention_period = 604800 # 7 days
  }

  lifecycle_rule {
    action {
      type          = "SetStorageClass"
      storage_class = "NEARLINE"

    }
    condition {
      age        = 14
      with_state = "LIVE"
    }
  }

  logging {
    log_bucket        = "demo-${random_id.db_name_suffix.hex}"
    log_object_prefix = "gcs_log_"
  }
}

```

### Expected Behavior

Create a bucket with lifecycle rule

### Actual Behavior

A bucket is created but lifecycle rule is not created.

### Steps to Reproduce

1. `terraform apply -auto-approve`
2. Get to GCP console to check the bucket lifecycle rule

**Comment by tysen** [comment]
Worked for me:
![lifecycle](https://user-images.githubusercontent.com/1501322/63460495-806fb680-c40b-11e9-9f71-a1a935976893.png)

**Comment by slevenick** [comment]
If this is still an issue can you capture the debug logs that are produced when attempting to apply this terraform config? It may contain information about why the bucket is not created in your case

**Comment by Rukeith** [comment]
Thank you @tysen and @slevenick to testing this issue.
I retry yesterday, this issue didn't happen anymore. I don't how to fix that, but it seems to be solved.
So I close this.
