### ISSUE TITLE
Remove old import formats

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#4277]
In some cases, such as SQL Database with `{{instance}}:{{name}}` form, we support import formats with non-standard delimiters. We should remove them as part of `3.0.0` to ensure consistency across resources and to simplify MM generation.

If it's impossible to remove in some cases - say, if `/` is an ambiguous character - we should instead add support for different delimiters to MM.

**Comment by rileykarson** [comment]
@slevenick: Do you think you got all these in the process of the id changes?

**Comment by slevenick** [comment]
I don't think so! I definitely changed a couple of them that used `:` or `.`, but I didn't change ones where a self link wouldn't be helpful or applicable, like organization policies

**Comment by paddycarver** [comment]
This should be done as part of 3.0.0.
