### ISSUE TITLE
The snippet from GCP provider docs produces an error

### ISSUE THREAD

**Issue by courteouselk** [terraform-providers/terraform-provider-google#4285]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```text
Terraform v0.12.6
+ provider.google v2.13.0
```

### Affected Resource(s)

* google_compute_address
* google_dns_record_set

### Terraform Configuration Files

```tf
data "google_compute_address" "my_address" {
  name = "foobar"
}

resource "google_dns_record_set" "frontend" {
  name = "frontend.${google_dns_managed_zone.prod.dns_name}"
  type = "A"
  ttl  = 300

  managed_zone = "${google_dns_managed_zone.prod.name}"

  rrdatas = ["${data.google_compute_address.my_address.address}"]
}

resource "google_dns_managed_zone" "prod" {
  name     = "prod-zone"
  dns_name = "prod.mydomain.com."
}
```

### Debug Output

https://gist.github.com/courteouselk/dfe25992000a0fe81ca99c44288ce9f4

### Expected Behavior

No error.

### Actual Behavior

Error is thrown:

```
Error: Null value found in list

  on main.tf line 20, in resource "google_dns_record_set" "frontend":
  20:   rrdatas = ["${data.google_compute_address.my_address.address}"]

Null values are not allowed for this attribute value.
```

### Steps to Reproduce

1. Use the snippet from gcp terraform provider docs:  https://www.terraform.io/docs/providers/google/d/datasource_compute_address.html
2. `terraform plan`

**Comment by slevenick** [comment]
Thanks for the issue report.

I don't believe there is an issue here, as the example is showing the use of an address data source. The data source is used to retrieve attributes of a resource that is managed outside of terraform. In this case the resource in question is the compute address named `foobar`. If this address does not exist, I believe it will produce the error in your bug report.

If you create a compute address named `foobar` and this behavior still occurs then this would be a bug. 

You may want the compute address resource instead, which will create a new address resource when terraform is run: https://www.terraform.io/docs/providers/google/r/compute_address.html

For more information on data sources see https://www.terraform.io/docs/configuration/data-sources.html

I'm going to close this issue, if you believe it is still a bug you can re open it
