### ISSUE TITLE
google_compute_subnetwork documentation does not include aggregation_intervals

### ISSUE THREAD

**Issue by TV4Fun** [terraform-providers/terraform-provider-google#4297]
The format of intervals expected in the `log_config.aggregation_interval` field of `compute_subnetwork` is not documented anywhere, except for a cursory look in one example in [the docs](https://www.terraform.io/docs/providers/google/r/compute_subnetwork.html). format is different from [what is expected by the API](https://cloud.google.com/vpc/docs/using-flow-logs#enabling_vpc_flow_logging), so this should really be documented.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_subnetwork

### Expected Behavior

This should be documented

### Actual Behavior

It's not documented

### Steps to Reproduce

Read the documentation at https://www.terraform.io/docs/providers/google/r/compute_subnetwork.html#aggregation_interval

**Comment by slevenick** [comment]
Thanks for the report, I'll have a PR fixing this shortly.

**Comment by slevenick** [comment]
Fixed in https://github.com/terraform-providers/terraform-provider-google-beta/pull/1080
