### ISSUE TITLE
Can't destroy sql_user or sql_database

### ISSUE THREAD

**Issue by rubensayshi** [terraform-providers/terraform-provider-google#4299]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.12.6
+ provider.google v2.12.0
+ provider.google-beta v2.12.0
+ provider.kubernetes v1.8.1
+ provider.local v1.3.0
```

### Affected Resource(s)

* google_sql_database
* google_sql_user

### Terraform Configuration Files

```tf
resource "google_sql_database" "encrypter-db" {
  name     = "encrypterdb"
  depends_on = [ google_sql_database_instance.encrypter-db ]

  instance = "${google_sql_database_instance.encrypter-db.name}"

}

resource "google_sql_user" "encrypter-db-prvbl" {
  name     = "prvbl"
  depends_on = [ google_sql_database_instance.encrypter-db ]

  instance = "${google_sql_database_instance.encrypter-db.name}"
  password = "${var.db-prvbl-password}"
}
```

### Panic Output

```
Error: Error reading Database: googleapi: Error 400: Invalid request: Failed to delete database "encrypterdb". Detail: pq: must be owner of database encrypterdb. (Please use psql client to delete database that is not owned by "cloudsqlsuperuser")
```

```
Error: Error, failed to deleteuser prvbl in instance encrypter-db: googleapi: Error 400: Invalid request: Failed to delete user prvbl. Detail: pq: role "prvbl" cannot be dropped because some objects depend on it
., invalid
```

### Expected Behavior

Should be able to destroy the gcloud sql resources properly.

### Actual Behavior

I can't destroy either my sql user or sql database, I tried both seperately as well with `terraform destroy -target=google_sql_user.encrypter-db-prvbl` and `terraform destroy -target=google_sql_database.encrypter-db` but that makes no difference.

### Steps to Reproduce

1. `terraform destroy`

**Comment by rubensayshi** [comment]
hmm, I couldn't resist and tried deleting the user and database through the google cloud console (web UI) and both give the same error as terraform does!

I haven't done anything other than letting terraform create the database and user and then used the user to fill the database schema...  
but it seems somehow that has caused an undeletable scenario ... ?

**Comment by slevenick** [comment]
I believe this is a sql related question rather than terraform, so I'm a little out of my element.

It looks like you have a database that you created manually within this instance that cannot be deleted by either terraform or the web UI. This is probably because the database has a dependency on the user as shown by `role "prvbl" cannot be dropped because some objects depend on it`?

I would suggest attempting to delete the schema the same way you created it and then trying to delete the database after that.

**Comment by rubensayshi** [comment]
ye, I'm gonna spend another few hours trying to figure it out today, it's not a terraform issue at least so can close the issue.  

if I find the solution I'll update the issue here just for future readers
