### ISSUE TITLE
Firestore create index does not work

### ISSUE THREAD

**Issue by ncjones** [terraform-providers/terraform-provider-google#4306]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.13
+ provider.google v2.13.0
+ provider.google-beta v2.13.0

### Affected Resource(s)

* google_firestore_index

### Terraform Configuration Files

```tf
resource "google_firestore_index" "quotes-account-id-created-date" {
  provider = "google-beta"
  project = "${google_project.myproject.project_id}"
  collection = "quotes"
  fields { field_path = "accountId" order = "ASCENDING" }
  fields { field_path = "created" order = "DESCENDING" }
  # following field is required for stable plan but it's presence breaks the index:
  fields { field_path = "__name__" order = "ASCENDING" }
}
```

### Expected Behavior
Queries should work after index is created and rerunning terraform plan should not recreate resources.

### Actual Behavior
If index is created with terraform with "\_\_name\_\_" field then the index is created but the Firestore query still fails. If the index is created with terraform without the "\_\_name\_\_" field then the index is created and works but rerunning terraform plan shows that the index needs to be recreated.

**Comment by slevenick** [comment]
Hey @ncjones,

Can you include the debug logs from attempting to create the index with both a `__name__` field and without one? You can enable debug logs by setting the environment variable `TF_LOG=DEBUG`

It may include some helpful information
