### ISSUE TITLE
Support adding/removing Bigtable clusters

### ISSUE THREAD

**Issue by garye** [terraform-providers/terraform-provider-google#4318]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In addition to resizing existing clusters, some customers would like the ability to add or remove clusters in an instance.

**Comment by garye** [comment]
@rileykarson I have a version of this in the Bigtable client coded up, but what do you think about pushing it to the terraform layer instead?

**Comment by rileykarson** [comment]
Yeah, we could implement it Terraform-side. Holistically I'm slightly in preference of having it live in the client lib, since then other clients can use the same functionality, but if you're hesitant to expose it there it can live here.

**Comment by garye** [comment]
I don't really have a problem exposing it in the library, I'll add you to the CL and see what the Go client reviewers have to say.

**Comment by garye** [comment]
There's some mild pushback against putting this new method in the library, so I'd like to try and find a home for it in this project if possible. 

Is the right approach to put a utility method for syncing clusters in https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_bigtable_instance.go?

**Comment by rileykarson** [comment]
@stankiewicz, let me know if you made any more progress on this that didn't end up on GH. I'll pick this up in a couple weeks if not, and get it in for whatever release happens next after that, somewhere between `3.3.0` and `3.5.0`.

**Comment by rileykarson** [comment]
This will be supported in `3.5.0`+.
