### ISSUE TITLE
google_container_cluster should allow disabling of KubernetesDashboard addon

### ISSUE THREAD

**Issue by calind** [terraform-providers/terraform-provider-google#433]
Currently the `google_container_cluster` allows enabling/disabling of `HorizontalPodAutoscaling` and `HttpLoadBalancing` addons. Since https://cloud.google.com/container-engine/release-notes#july_25_2017 it's allowed to enable/disable the KubernetesDashboard addon as well.

**Comment by sebglon** [comment]
I have created a PR for this #505

**Comment by selmanj** [comment]
@sebglon Thanks for your PR!  Unfortunately I beat you to it with #464. Please keep them coming though!
