### ISSUE TITLE
Cloud Run: await service ready status before finishing refresh

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#4335]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Today, this fails with the following error:

```
Error: Invalid index

  on main.tf line 21, in locals:
  21:     for cond in google_cloud_run_service.default.status[0].conditions :
    |----------------
    | google_cloud_run_service.default.status is empty list of object

The given key does not identify an element in this collection value.
```

Ideally, we'd wait on the status being ready (or another terminal state) in the `Read` function of the resource.  That would allow interpolation off of the status fields to work.

### New or Affected Resource(s)

* google_cloud_run_service

### Potential Terraform Configuration

```tf
resource "google_cloud_run_service" "default" {
  name     = "my-service"
  location = "us-central1"
  provider = "google-beta"

  metadata {
    namespace = "my-project"
  }

  spec {
    containers {
      image = "gcr.io/cloudrun/hello"
    }
  }
}

# The Service is ready to be used when the "Ready" condition is True
# Due to Terraform and API limitations this is best accessed through a local variable
locals {
  cloud_run_status = {
    for cond in google_cloud_run_service.default.status[0].conditions :
    cond.type => cond.status
  }
}

output "isReady" {
  value = local.cloud_run_status["Ready"] == "True"

```

### References

* #0000

**Comment by chrisst** [comment]
Should be fixed by https://github.com/terraform-providers/terraform-provider-google/issues/4091

**Comment by rileykarson** [comment]
Ah cool, managed to miss that. closing as dupe.
