### ISSUE TITLE
Support Advanced routing in google_compute_router_peer

### ISSUE THREAD

**Issue by nathkn** [terraform-providers/terraform-provider-google#4357]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This request is to update the `google_compute_router_peer` to include the full routing options, similar to what exists in `google_compute_router`, specifically so that the terraform resource can match the REST API resource specified in the [docs](https://cloud.google.com/compute/docs/reference/rest/v1/routers):

```
"bgpPeers": [
    {
      "name": string,
      "interfaceName": string,
      "ipAddress": string,
      "peerIpAddress": string,
      "peerAsn": number,
      "advertisedRoutePriority": number,
      "advertiseMode": enum,
      "advertisedGroups": [
        enum
      ],
      "advertisedIpRanges": [
        {
          "range": string,
          "description": string
        }
      ],
      "managementType": enum
    }
  ],
```

Currently the `advertiseMode`, `advertisedGroups`, and `advertisedIpRanges` are not available. They are useful settings for setting up multiple peers with different route priorities.

### New or Affected Resource(s)

* google_compute_router_peer

### Potential Terraform Configuration

This should be similar to the same options that exist for the `google_compute_router` resource, except for the individual peers. 

```
...
    advertise_mode    = "CUSTOM"
    advertised_groups = ["ALL_SUBNETS"]
    advertised_ip_ranges {
      range = "1.2.3.4"
    }
...
```

### References

* similar to #1278
* REST API docs: https://cloud.google.com/compute/docs/reference/rest/v1/routers

**Comment by allandrick** [comment]
@megan07 no doc update for this?   I've suddenly got existing resources wanting to rebuild because the unset value now wants to be set to "DEFAULT"
