### ISSUE TITLE
cidr_blocks not accepted in master_authorized_networks_config in the resource google_container_cluster

### ISSUE THREAD

**Issue by cotigao** [terraform-providers/terraform-provider-google#4384]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.7
+ provider.google v2.14.0

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "primary" {
 .......
 .......

 master_authorized_networks_config {
    cidr_blocks = [
        {
          cidr_block   = data.google_compute_subnetwork.subnetwork.ip_cidr_range
          display_name = "VPC"
        },
        {
          cidr_block   = var.external_network
          display_name = "ext network"
        },
    ]
 }

.......
.......
}
```

### Actual Behavior
```tf
  Error: Unsupported argument

  on main.tf line 104, in resource "google_container_cluster" "primary":
 104:     cidr_blocks = [

  An argument named "cidr_blocks" is not expected here. Did you mean to define a
  block of type "cidr_blocks"?
```

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by rileykarson** [comment]
This syntax was disallowed starting with Terraform `0.12`, other than for a certain subset of fields (~3-4 in this provider). Try this syntax instead:

```hcl
 master_authorized_networks_config {
    cidr_blocks {
          cidr_block   = data.google_compute_subnetwork.subnetwork.ip_cidr_range
          display_name = "VPC"
   }

   cidr_blocks {
          cidr_block   = var.external_network
          display_name = "ext network"
   }
 }
```
