### ISSUE TITLE
IAM policy not working

### ISSUE THREAD

**Issue by sarab321** [terraform-providers/terraform-provider-google#4385]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

0.12.1

### Affected Resource(s)

iam_policy

* google_XXXXX

### Terraform Configuration Files

resource "google_project_iam_policy" "project" {
  project     = "xxx"
  policy_data = "${data.google_iam_policy.admin.policy_data}"
}

data "google_iam_policy" "admin" {
  binding {
    role = "roles/storage.objectViewer"

    members = [
      "xxx@gmail.com"
    ]
  }
}

### Debug Output

Error: Error applying IAM policy for project "terraform-251319". Policy is &cloudresourcemanager.Policy{AuditConfigs:[]*cloudresourcemanager.AuditConfig(nil), Bindings:[]*cloudresourcemanager.Binding{(*cloudresourcemanager.Binding)(0xc0001f87e0)}, Etag:"", Version:0, ServerResponse:googleapi.ServerResponse{HTTPStatusCode:0, Header:http.Header(nil)}, ForceSendFields:[]string(nil), NullFields:[]string(nil)}, error is googleapi: Error 400: Policy members must be of the form "<type>:<value>"., badRequest

**Comment by rileykarson** [comment]
`members` entries must be specially formatted, as per https://www.terraform.io/docs/providers/google/d/google_iam_policy.html#members.

Try `user:xxx@gmail.com` instead of `xxx@gmail.com`. If that doesn't work, please comment again here!
