### ISSUE TITLE
Changing label of boot disk forces replacement of instance

### ISSUE THREAD

**Issue by kartvep** [terraform-providers/terraform-provider-google#4387]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

terraform 0.12.6
provider google 2.13.0

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "instance" {
  depends_on   = [google_compute_disk.disk]
  count        = var.number
  name         = "${var.name}-${var.start_num + count.index}"
  machine_type = var.instance_type
  zone         = var.availability_zone
  labels       = {
    iow_name = local.label
  }

  boot_disk {
    initialize_params {
      image  = var.base_image
      size   = local.boot_size
      type   = local.boot_type
      labels = {
        iow_name = "${local.label}-sda"
      }
    }

    auto_delete = var.disks_autodelete
  }
...
```

### Debug Output

```
      ~ boot_disk {
            auto_delete                = false
          ~ device_name                = "persistent-disk-0" -> (known after apply)
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
          ~ source                     = "https://www.googleapis.com/compute/v1/projects/iponweb-udsp2/zones/europe-west1-d/disks/instance-1" -> (known after apply)

          ~ initialize_params {
              ~ image  = "https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20180911" -> "ubuntu-os-cloud/ubuntu-1804-lts"
              ~ labels = { # forces replacement
                  ~ "my_label" = "old-label" -> "new-label-sda"
                }
                size   = 100
                type   = "pd-standard"
            }
        }
```

### Expected Behavior

Label will be changed in place, like it can be changed via web console

### Actual Behavior

Plan shows replacement of changed instance

### Steps to Reproduce

1. `terraform apply`

**Comment by Chupaka** [comment]
This is expected behaviour, you cannot change initialize_params without recreating the disk. If you change them on-the-fly, they're not initialize but kind of current_params :)
To update boot disk via Terraform you should use separate google_compute_disk resource, something like:

```
resource "google_compute_disk" "boot" {
  count = var.number
  name  = "${var.name}-${var.start_num + count.index}-boot"
  image  = var.base_image
  size   = local.boot_size
  type   = local.boot_type
  labels = {
    iow_name = "${local.label}-sda"
  }
}

...
boot_disk {
  source = google_compute_disk.boot.*.self_link[count.index]
}

```

**Comment by rileykarson** [comment]
@Chupaka's answer is correct, if you'd like to modify the disk in place you can create instances using a `google_compute_disk` instead of by using `initialize_params`. `initialize_params` are exclusively used to manage 1-off creation of a disk for use with the instance that won't be modified in the future. Closing this out.
