### ISSUE TITLE
Make google_cloud_build_trigger.trigger_template Required

### ISSUE THREAD

**Issue by ryu1kn** [terraform-providers/terraform-provider-google#4389]
Hello all. Thank you for your great work!

This is more like a doc inconsistency report rather than a bug report.

While I was creating a cloud build trigger by referring to [google_cloudbuild_trigger](https://www.terraform.io/docs/providers/google/r/cloudbuild_trigger.html), I found a potential inconsistency. The doc says `trigger_template` field is optional, but it seems it's not the case.

> trigger_template - (Optional) Template describing the types of source changes to trigger a build. Branch and tag names in trigger templates are interpreted as regular expressions. Any branch or tag change that matches that regular expression will trigger a build. Structure is documented below.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.7
+ provider.google v2.14.0
```

### Affected Resource(s)

* google_cloudbuild_trigger

### Terraform Configuration Files

main.tf

```tf
variable "project_id" {}
variable "access_token" {}

provider "google" {
  version = "~> 2.14.0"
  project = var.project_id
  access_token = var.access_token
}

resource "google_project_service" "project" {
  service = "cloudbuild.googleapis.com"
  disable_dependent_services = true
}

resource "google_cloudbuild_trigger" "test" {
  # trigger_template {
  #   repo_name = "foobar"
  #   branch_name = "master"
  # }
  filename = "cloudbuild.yaml"
}
```

cloudbuild.yaml

```yaml
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args: ['-c', 'echo hi']
```

### Expected Behavior

A Cloud Build trigger is created if `trigger_template` field is actually optional.

### Actual Behavior

Failed to create a trigger with this error, but it did create one when `trigger_template` was provided.

```
google_cloudbuild_trigger.test: Creating...

Error: Error creating Trigger: googleapi: Error 400: trigger config not set

  on main.tf line 15, in resource "google_cloudbuild_trigger" "test":
  15: resource "google_cloudbuild_trigger" "test" {
```

### Steps to Reproduce

```sh
export TF_VAR_project_id="your-project-id"
export TF_VAR_access_token="$(gcloud auth print-access-token)"
terraform init
terraform apply
```

**Comment by rileykarson** [comment]
This should be `Required`. Marking as a breaking change + technical debt to be done in `3.0.0`, prior Terraform Core versions had issues with interpolated `Required` values https://github.com/hashicorp/terraform/issues/16306 so I'd prefer to play it safe in terms of backwards compatibility.

**Comment by ryu1kn** [comment]
Hi @rileykarson , should we still fix the doc now (i.e. replace `(Optional)` with `(Required)`) so that people will know that they need to provide the value unless `3.0.0` is coming real soon?

**Comment by rileykarson** [comment]
Sure! Since the resource is generated, changing just the docs like that is a little harder than expected, so I'm appending a note onto the end of the description body instead.

**Comment by ryu1kn** [comment]
Thanks @rileykarson !  👍

**Comment by ndmckinley** [comment]
Going to close this because it will be done in `3.0.0` as of https://github.com/GoogleCloudPlatform/magic-modules/pull/2352.
