### ISSUE TITLE
Publish GitHub releases during provider releases

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#4392]
We publish releases by updating our changelog, pushing a binary, and making a GitHub "tag" release. Users can't subscribe to these releases automatically, though: https://github.community/t5/How-to-use-Git-and-GitHub/Not-getting-release-notification-despite-quot-Watching-releases/td-p/19665.

We could publish rich releases on GitHub, allowing users to subscribe. Both the Azure and AWS providers do this already. It's also probably possible to automate the process somewhat from the HC releasing side, especially if it would have x-provider impact.

**Comment by pdecat** [comment]
Current work-around: subscribe to https://github.com/terraform-providers/terraform-provider-google/tags.atom with an feed reader

**Comment by danawillow** [comment]
Pretty sure this is fixed now: https://github.com/terraform-providers/terraform-provider-google/releases.

**Comment by pdecat** [comment]
Indeed, thanks!
