### ISSUE TITLE
Make google_compute_backend_service.backends.group Required

### ISSUE THREAD

**Issue by samcgardner** [terraform-providers/terraform-provider-google#4396]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.6
+ provider.google v2.11.0
+ provider.google-beta v2.11.0
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.random v2.1.2

Your version of Terraform is out of date! The latest version
is 0.12.7. You can update by downloading from www.terraform.io/downloads.html
```

### Affected Resource(s)

`google_compute_backend_service`

### Terraform Configuration Files

```tf
resource "google_compute_backend_service" "react-backend" {
  provider = "google-beta"

  name        = "react-be"
  port_name   = "http"
  protocol    = "HTTP"
  timeout_sec = 10

  health_checks = ["${google_compute_http_health_check.react-hc.self_link}"]
  backend {
    balancing_mode = "RATE"
    max_rate = 999999999
  }
}

resource "google_compute_http_health_check" "react-hc" {
  provider = "google-beta"

  name               = "react-hc"
  request_path       = "/Testpage"
  port               = 8080
  check_interval_sec = 5
  timeout_sec        = 5
}
```
(this is an excerpt from a larger module)

### Debug Output

https://gist.github.com/samcgardner/15e6b220d22f3977d3ca003a2fdeb4b4

### Expected Behavior

GCP's API should respond with a 4xx code for a bad request or handle resource creation successfully

### Actual Behavior

GCP's API responds with a 503 Service Unavailable

### Steps to Reproduce

1. `terraform apply`

**Comment by rileykarson** [comment]
Weird! Mine returns a `4XX` error:

```
Error creating BackendService: googleapi: Error 400: Invalid value for field 'resource.backends[0]': '{  "balancingMode": "RATE",  "maxUtilization": 0.8,  "maxRate": 999999999,  "capacityScaler": 1.0}'. Resource group must be set for a backend., invalid
```

As stated in that message, `group` is required. We have it set as optional in Terraform for historical reasons (https://github.com/terraform-providers/terraform-provider-google/pull/576) and I'd imagine I can change it back to `Required`. I'll try to repro the underlying error, though.

**Comment by rileykarson** [comment]
I can't repro the original issue that made this optional, I'm going to mark this as a breaking change to roll into `3.0.0`. It would probably be safe to make before, but I'd rather play it safe.

**Comment by ndmckinley** [comment]
Done in https://github.com/GoogleCloudPlatform/magic-modules/pull/2373.
