### ISSUE TITLE
Snapshot schedules policy enable VSS automatically for linux instances

### ISSUE THREAD

**Issue by femrtnz** [terraform-providers/terraform-provider-google#4397]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.14
+ provider.google v2.14.0
+ provider.google-beta v2.14.0
+ provider.random v2.2.0
+ provider.template v2.1.2

### Affected Resource(s)

* google_compute_resource_policy

### Terraform Configuration Files

```tf
provider "google-beta" {
  region = "us-central1"
  zone   = "us-central1-a"
}

resource "google_compute_resource_policy" "foo" {
  provider = "google-beta"
  name = "policy"
  region = "us-central1"
  snapshot_schedule_policy {
    schedule {
      daily_schedule {
        days_in_cycle = 1
        start_time = "04:00"
      }
    }
  }
}
```

### Debug Output

```
code:  "GUEST_FLUSH_NOT_SUPPORTED"       
      message:  "You can only use Volume Shadow Copy Service (VSS) on disks attached to Windows instances. Make sure you have the latest Windows image version with the VSS agent installed." 
```

### Expected Behavior

we should have an option to disable Volume Copy Shadow Service (VSS), so we can create a snapshot scheduler through terraform

### Actual Behavior

snapshot scheduler does not work because VSS was enabled automatically

### References
https://cloud.google.com/compute/docs/instances/windows/creating-windows-persistent-disk-snapshot#create-snapshot

**Comment by rileykarson** [comment]
Hey @femrtnz! What conditions does this occur under? When GCP is attempting to create your scheduled snapshot of a disk? If so, can you include a config for the disk as well? 

https://www.terraform.io/docs/providers/google/r/compute_resource_policy.html#guest_flush is a configurable field.Based on your config, it shouldn't be enabled. Can you share debug logs during a refresh (`terraform refresh` or `terraform plan`) of your resource policy resource?

**Comment by femrtnz** [comment]
Hi @rileykarson you are right. The `guest_flush` flag do the job here. It wasn't clear as I was looking for something directly related to VSS.

thank you.

Hence, closing.
