### ISSUE TITLE
Documentation for `google_netblock_ip_ranges` datasource should be clearer on what is included with `restricted-googleapis`

### ISSUE THREAD

**Issue by TV4Fun** [terraform-providers/terraform-provider-google#4404]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The documentation for `google_netblock_ip_ranges` says that setting `range_type` to `restricted-googleapis` "Corresponds to the IP addresses used for Private Google Access and/or VPC Service Controls API access." These are actually two different subnetworks, but only one of them is actually included with this resource. According to [the GCP documentation](https://cloud.google.com/vpc/docs/private-access-options#domain-vips), you should only ever have occasion to use one or the other of these anyway, so this should really be two different `range_type`s.

### New or Affected Resource(s)

* google_netblock_ip_ranges

### Potential Terraform Configuration

```tf
data "google_netblock_ip_ranges" "restricted-apis" {
  range_type = "restricted-googleapis"
}

output "restricted-api-ranges" {
  # Should be ["199.36.153.4/30"]
  value = data.google_netblock_ip_ranges.restricted-apis.cidr_blocks
}

data "google_netblock_ip_ranges" "private-apis" {
  range_type = "private-googleapis"
}

output "private-api-ranges" {
  # Should be ["199.36.153.8/30"]
  value = data.google_netblock_ip_ranges.private-apis.cidr_blocks
}
```

**Comment by danawillow** [comment]
Fixed (a while back) in https://github.com/GoogleCloudPlatform/magic-modules/pull/2266.
