### ISSUE TITLE
`google_storage_bucket_acl` takes authoritative control after first apply

### ISSUE THREAD

**Issue by lawliet89** [terraform-providers/terraform-provider-google#4405]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.8
+ provider.google v2.14.0
```

### Affected Resource(s)

* google_storage_bucket_acl

### Terraform Configuration Files

```tf
resource "google_storage_bucket_acl" "log_delivery" {
  bucket = var.log_bucket

  role_entity = [
    "WRITER:group-cloud-storage-analytics@google.com",
  ]
}
```

### Expected Behavior

After applying, there should be no diff

### Actual Behavior

The plan after apply shows:

```
  # google_storage_bucket_acl.log_delivery will be updated in-place
  ~ resource "google_storage_bucket_acl" "log_delivery" {
        bucket      = "<bucket>"
        id          = "<bucket>"
      ~ role_entity = [
          - "OWNER:project-owners-<project_id>",
            "WRITER:group-cloud-storage-analytics@google.com",
          - "OWNER:project-editors-<project_id>",
          - "READER:project-viewers-<project_id>",
        ]
    }

```

### Steps to Reproduce

1. `terraform apply`
1. `terraform plan`

### References

This seems to be a regression of https://github.com/terraform-providers/terraform-provider-google/issues/892

**Comment by venkykuberan** [comment]
@lawliet89 sorry for the delay in response. Using this [resource](https://www.terraform.io/docs/providers/google/r/storage_default_object_acl.html) will give more control over the default behavior.  Plan wouldn't find the difference

```
resource "google_storage_default_object_acl" "image-store-default-acl" {
    bucket = google_storage_bucket.image-store.name

  role_entity = [
    "OWNER:group-cloud-storage-analytics@google.com",
  ]
}
```
Let us know if it worked for you.

**Comment by lawliet89** [comment]
`google_storage_default_object_acl` does not have a permanent diff but this does not solve the issue:

- It's a completely different resource with different semantics
- OR the docs should make it clear that `google_storage_bucket_acl` is authoritative.

**Comment by chrisst** [comment]
@lawliet89 You are correct that `google_storage_bucket_acl` tries to be authoritative for a given bucket's acl list. If you are looking for a non-authoritative way to manage ACL's try taking a look at [storage_bucket_access_control](https://www.terraform.io/docs/providers/google/r/storage_bucket_access_control.html). I'll add some clarification to the docs to point future users in this direction.

Additionally we don't allow the project owner to be removed from the role of `OWNER`. I'll stop Terraform presenting a permadiff for this role.
