### ISSUE TITLE
Unable to create instance_group_manager referring to template with local ssd

### ISSUE THREAD

**Issue by flokli** [terraform-providers/terraform-provider-google#4417]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

terraform v0.11.14
terraform-provider-google 2.12.0

### Affected Resource(s)

* google_compute_instance_template
* google_compute_instance_group_manager

### Terraform Configuration Files

```tf
resource "google_compute_instance_template" "node" {
  name         = "node-template"
  machine_type = "n1-standard-8"

  tags = ["ssh"]

  disk {
    source_image = "${module.node_image.self_link}"
    auto_delete  = true
    boot         = true
    disk_type    = "pd-ssd"
    disk_size_gb = "50"
  }

  disk {
    auto_delete  = true
    device_name = "scratch"
    disk_type    = "local-ssd"
    disk_size_gb = "300"
    type = "SCRATCH"
  }

  network_interface {
    network       = "default"
    access_config = {}
  }
}

resource "google_compute_instance_group_manager" "node" {
  name               = "node"
  instance_template  = "${google_compute_instance_template.node.self_link}"
  base_instance_name = "node"
  zone               = "us-west2-a"
  target_size        = "25"
}

```

### Expected Behavior

Terraform creates the instance template and the instance group manager

### Actual Behavior

Terraform creates the instance template, but fails to create the instance group manager:

```
google_compute_instance_group_manager.node: Creating...
  base_instance_name:      "" => "node"
  fingerprint:             "" => "<computed>"
  instance_group:          "" => "<computed>"
  instance_template:       "" => "https://www.googleapis.com/compute/beta/projects/myproject/global/instanceTemplates/node-template"
  name:                    "" => "node"
  project:                 "" => "<computed>"
  rolling_update_policy.#: "" => "<computed>"
  self_link:               "" => "<computed>"
  target_size:             "" => "25"
  update_strategy:         "" => "REPLACE"
  version.#:               "" => "<computed>"
  wait_for_instances:      "" => "false"
  zone:                    "" => "us-west2-a"

Error: Error applying plan:

1 error occurred:
	* google_compute_instance_group_manager.node: 1 error occurred:
	* google_compute_instance_group_manager.node: Error waiting for Creating InstanceGroupManager: Invalid value for field 'resource.properties.disks[1].initializeParams.diskSizeGb': '300'. Invalid local SSD size in GB: 300

```

If I remove the scratch disk definition, it works, so it fails due to the scratch disk definition.

### Steps to Reproduce

1. `terraform apply`

**Comment by Chupaka** [comment]
Each local SSD is 375 GB in size. What if you change 300 to 375?

**Comment by flokli** [comment]
Changing to 375 works - thanks! - I totally missed that part about local ssds being restricted in size - it's only written in the GCE documentation, not in the provider documentation.

What do you think about doing some of that validation locally, or updating the docs?

**Comment by rileykarson** [comment]
Closed in linked PR
