### ISSUE TITLE
attached_disk set delete instance behavior

### ISSUE THREAD

**Issue by nodesocket** [terraform-providers/terraform-provider-google#442]
When attaching additional disks to an instance, I don't see a way to set `When deleting instance: delete disk`. Currently defaulting to `When deleting instance: keep disk`.

````
attached_disk {
    source = "${google_compute_disk.minio_data.self_link}"
}
````

**Comment by danawillow** [comment]
What's your use case? Here's why I didn't add it:

```
resource "google_compute_disk" "foo" {
[properties]
}

resource "google_compute_instance" "bar" {
  attached_disk {
    source = "${google_compute_disk.foo.self_link}"
  }
}
```

Now let's say you remove the instance. Your configuration would still have the disk being there. If you had it set to auto-delete, then there would be a mismatch between what's in your config and what's true, and a new `terraform plan` would try to recreate the disk.

**Comment by nodesocket** [comment]
Ah, tht makes sense. I was thinking it would be nice if you delete the instance from the Google web interface it would delete the disk for you, but this edge case with Terraform makes sense.

**Comment by danawillow** [comment]
Cool, I'm going to go ahead and close this out but do let me know if it comes up again :)
