### ISSUE TITLE
Error importing google_compute_subnetwork when region not set in provider

### ISSUE THREAD

**Issue by arvindgorur** [terraform-providers/terraform-provider-google#4424]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
```Terraform v0.11.10```
### Affected Resource(s)
```google_compute_subnetwork```

### Terraform Configuration Files (if applicable)

```main.tf
provider "google" {
  version = "~> 1.17"
}

resource "google_compute_network" "vpc_network" {
  name                    = "main-network"
  auto_create_subnetworks = "false"
  project                 = "my-project"
  routing_mode            = "REGIONAL"
}

resource "google_compute_subnetwork" "default" {
  name          = "custom-subnet"
  ip_cidr_range = "10.255.57.0/24"
  region        = "us-east1"
  network       = "${google_compute_network.vpc_network.self_link}"
  project       = "my-project"
}
```

### Issue Description
Not sure if this is a bug or something I'm not doing right. Let's say I have a GCP project that has a VPC network with a single custom subnet called 'custom-subnet'. I am trying to import the VPC network and the subnet into Terraform. I can import the VPC network without any issues. I do have an issue when importing the single subnet. Below is the command and it's output:
```
terraform import google_compute_subnetwork.default custom-subnet
Error: google_compute_subnetwork.default (import id: custom-subnet): import google_compute_subnetwork.default (id: custom-subnet): Error constructing id: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
```
While I haven't set the region/zone at the provider level, I have set the region in the resource. So not sure what it's complaining about. Any clarification would be appreciated. I was able to import the resource by adding in the region at the provider level.

**Comment by danawillow** [comment]
Hi @arvindgorur, it looks like you accidentally deleted the note at the top of the issue template that  helps our automation label the issues. If you could leave that in next time, that helps our team out quite a bit :)

For your actual question, take a look at the subnetwork import docs:  https://www.terraform.io/docs/providers/google/r/compute_subnetwork.html#import. There are a few import formats that are allowed, and if you choose one that has the region, it should work.

I'm going to go ahead and close this issue since I think it's been resolved, but if I'm wrong please let me know and we can reopen it and investigate further!
