### ISSUE TITLE
Shielded GKE Nodes

### ISSUE THREAD

**Issue by somethingnew2-0** [terraform-providers/terraform-provider-google#4434]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Shielded GKE Nodes protects against a variety of attacks by hardening the underlying GKE node against rootkits and bootkits. More specifically, Shielded GKE Nodes provides:
* Node OS provenance check: A cryptographically verifiable check to make sure the node OS is running on a virtual machine in a Google data center
* Enhanced rootkit and bootkit protection: Protection against advanced rootkits and bootkits in the node by leveraging advanced platform security capabilities such as secure and measured boot, virtual trusted platform module (vTPM), UEFI firmware, and integrity monitoring
* Standards-based security: Built on the Trusted Computing Group’s (TCG) Trusted Platform Module (TPM), Shielded GKE Nodes uses a standardized specification for trusted computing, such as verifying the boot integrity of the node and enhancing the node bootstrapping process

### New or Affected Resource(s)

* google_container_cluster
* google_container_node_pool (maybe?)

### Potential Terraform Configuration

Perhaps similar to [shielded_instance_config](https://www.terraform.io/docs/providers/google/r/compute_instance.html#shielded_instance_config) 
```tf
shielded_cluster_config {
  enable_secure_boot = true;
  enable_vtpm = true;
  enable_integrity_monitoring = true;
}
```

### References

* [Google Cloud Feature Announcement: Exploring container security: Bringing Shielded VMs to GKE with Shielded GKE Nodes](https://cloud.google.com/blog/products/identity-security/exploring-container-security-bringing-shielded-vms-to-gke-with-shielded-gke-nodes) 
* [Documentation: Using Shielded GKE Nodes](https://cloud.google.com/kubernetes-engine/docs/how-to/shielded-gke-nodes) 
* Add support for Shielded VMs #3209

**Comment by awly** [comment]
Note that there are 2 relevant API fields:
- `shielded_instance_config` in `node_config`: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig#shieldedinstanceconfig
- `shielded_nodes` in `cluster`: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#shieldednodes

Please add both.

**Comment by rileykarson** [comment]
@awly: Do you anticipate any fields other than `enabled` being added to the `ShieldedNodes` object? We can significantly improve the UX of the field in Terraform if you don't.

**Comment by awly** [comment]
We don't plan on adding anything else to `ShieldedNodes` at this time.

**Comment by rileykarson** [comment]
FYI @megan07, We can probably surface this as

```hcl
enable_shielded_nodes = true
```

instead of

```hcl
shielded_nodes {
  enabled = true
}
```

For alignment with https://github.com/terraform-providers/terraform-provider-google/issues/3928.
