### ISSUE TITLE
google_kms_secret_ciphertext producing new ciphertext even though plaintext hasn't changed

### ISSUE THREAD

**Issue by spacetj** [terraform-providers/terraform-provider-google#4436]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Using Terraform 0.11.8

### Affected Resource(s)

* google_kms_secret_ciphertext

### Terraform Configuration Files

```tf

data "google_kms_secret_ciphertext" "encrypt" {
  crypto_key = "${var.key}"
  plaintext = "${some_info_from_data_source}"
}

resource "local_file" "save_encrypted" {
  content  = "${data.google_kms_secret_ciphertext.encrypt.ciphertext}"
  filename = "save-me.txt"
}

```

### Expected Behavior

If the original plaintext hasn't changes, then it should not produce a new cipher text.

### Actual Behavior

Even through the plain text hasnt changed, a new ciphertext is created, which forces a new file to be created each time terraform is run.

### Steps to Reproduce

1. `terraform apply`

**Comment by spacetj** [comment]
@danawillow Any update on this?

**Comment by danawillow** [comment]
No updates, sorry! It's still on my radar but other things have come up in the meantime.
