### ISSUE TITLE
cloudbuild: build timeout

### ISSUE THREAD

**Issue by GeneralAardvark** [terraform-providers/terraform-provider-google#4437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

A timeout variable for the whole build is missing from the google_cloudbuild_trigger resource.

A timeout variable is available per step, but we are currently unable to alter the default build timeout of 10 mins.

### New or Affected Resource(s)

* google_cloudbuild_trigger

### Potential Terraform Configuration

```
resource "google_cloudbuild_trigger" "container_build" {
  description = "Build container."

  trigger_template {
    branch_name = "my-branch"
    repo_name   = "my-repo"
  }

  build {
    step {
      name = "gcr.io/cloud-builders/docker"
      args = ["build", "-t", "eu.gcr.io/MY_PROJECT//MY_CONTAINER", "."]
    }   
    timeout = 1200s
    images = [ 
      "eu.gcr.io/MY_PROJECT/MY_CONTAINER",
    ]   
  }
}

```

### References

https://cloud.google.com/cloud-build/docs/build-config#timeout_2

* #0000

**Comment by alekna** [comment]
Setting `google_cloudbuild_trigger` step timeout above build-level timeout breaks the trigger as build-level timeout remains at 600s (default). This is a bug as sum of step timeouts (if set) should never be allowed to exceed build-level timeout.
```tf
resource "google_cloudbuild_trigger" "build_trigger" {
  description = "Push to any branch"
  build {
    step {
      args = [
        "build",
        "-t",
        "${var.gcr_endpoint}/${var.project_id}/${var.repo_name}:$BRANCH_NAME",
        "."]
      env = []
      name = "gcr.io/cloud-builders/docker"
      timeout = "900s"
    }
    images = [
      "${var.gcr_endpoint}/${var.project_id}/${var.repo_name}:$BRANCH_NAME"
    ]
    tags = []
  }

  trigger_template {
    branch_name = ".*"
    project_id = var.project_id
    repo_name = var.repo_name
  }
}
```

```bash
$ gcloud builds describe $ID

<...>

status: FAILURE
statusDetail: 'invalid build: invalid timeout in build step #0: build step timeout
  "15m0s" must be <= build timeout "10m0s"'
steps:
- args:
  - build
  - -t
  - us.gcr.io/<...>/<...>:$BRANCH_NAME
  - .
  name: gcr.io/cloud-builders/docker
  timeout: 900s
tags:
- trigger-<...>
timeout: 600s
```

As a workaround until it's fixed, build-level timeout can be edited manually via https://console.cloud.google.com/cloud-build/triggers however it is reverted back to 600s on subsequent `terraform apply` run.
