### ISSUE TITLE
Feature Request: Support for Cloud Identity Aware Proxy in Compute Engine

### ISSUE THREAD

**Issue by migibert** [terraform-providers/terraform-provider-google#444]
Hi there,

We would love to see support for Cloud Identity Aware Proxy (https://cloud.google.com/iap/) as it is now available in GA.

Relevant links:
* https://cloud.google.com/iap/docs/reference/compute-engine-apis

**Comment by Cidan** [comment]
I'll go ahead and take a look at this in the next week or two.

**Comment by homelessnessbo** [comment]
Hey guys, as I can see - PR is already merged, right? Is it going to be included in the nearest release, or should I build it from master?

**Comment by rosbo** [comment]
Hi @homelessnessbo,

Yes, this will be included in the next release. I also realized that we had forgot to update our docs so I updated them.

Thank you

**Comment by Cidan** [comment]
@rosbo It's actually already released iirc, no?

**Comment by rosbo** [comment]
@Cidan you are right. This was release in version 1.2.0. However, the documentation was not updated. You can look at #839 for the documentation on how to use it.

**Comment by homelessnessbo** [comment]
Thanks guys!

**Comment by b4b4r07** [comment]
Thank you for your development. This feature is what I want! BTW, can we manage ACL about IAP via terraform? As far as I see docs, it seems that it cannot be manage. https://www.terraform.io/docs/providers/google/r/compute_backend_service.html

**Comment by Cidan** [comment]
@b4b4r07 Can you open a new issue to add ACL support? Thanks!

**Comment by b4b4r07** [comment]
OK, I'll do later. Thanks

**Comment by nightmare-moon** [comment]
this this feature acl and iap support in the product or not... 
I'm seeing conflicting information. 

I need this feature...
