### ISSUE TITLE
Cycle dependency when importing resources with access_token in default provider

### ISSUE THREAD

**Issue by xynova** [terraform-providers/terraform-provider-google#4443]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform version: 0.12.8
+ provider.google v2.14.0
+ provider.google-beta v2.14.0

### Affected Resource(s)

* provider.google
* data.google_service_account_access_token

### Terraform Configuration Files

```tf
terraform {
  required_version = ">=v0.12.8"
  required_providers {
    google = "v2.14.0"
    google-beta = "v2.14.0"
  }
}

provider "google" {
  alias = "myself"
}

data "google_service_account_access_token" "impersonated" {
  provider = "google.myself"
  target_service_account = "${var.run_plan_as_svcacc}"
  lifetime = "300s"
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform"
    ]
}

provider "google" {
  access_token = "${data.google_service_account_access_token.impersonated.access_token}"
  project = "${var.project}"
  region = "${local.location}"
}
```

### Debug Output

https://gist.github.com/xynova/4117bfe303fb04260ad6c64d87c55374

### Expected Behavior

I would have expected the provider hierarchy to be resolved

### Actual Behavior

Error: Cycle: data.google_service_account_access_token.impersonated, provider.google

### Steps to Reproduce

terraform import google_kms_crypto_key.etcd_enc_key projects/myproject/locations/australia-southeast1/keyRings/gke-clusters-keyring/cryptoKeys/experiments-cluster-v2-cluster-etcd-key

**Comment by danawillow** [comment]
Hi @xynova, thanks for the bug report! I took a look and I'm pretty confident this is actually a bug in Terraform Core, not in the Google provider. From what I can tell, something that's running while it's constructing the dependency graph is losing the provider set on the access token data source.

Would you mind filing an issue at https://github.com/hashicorp/terraform/issues and link back to this one?

**Comment by xynova** [comment]
Update: The[ terraform import documentation](https://www.terraform.io/docs/commands/import.html#provider-configuration) specifies that a provider used in import cannot depend on a data source (or other resource). :(
