### ISSUE TITLE
google_logging_project_sink resource does not export the filter attribute

### ISSUE THREAD

**Issue by jchoksijudopay** [terraform-providers/terraform-provider-google#4450]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.11

### Affected Resource(s)

google_logging_project_sink

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

The documentation for [google_logging_project_sink](https://www.terraform.io/docs/providers/google/r/logging_project_sink.html#attributes-reference) informs that the filter attribute should have been exported when the resource is created.

### Actual Behavior

I see a 

> ... does not have attribute 'filter' ...

error when trying to setup an output.

### Steps to Reproduce

n/a

### Important Factoids

n/a

### References

n/a

**Comment by danawillow** [comment]
Hi @jchoksijudopay, can you please attach your Terraform config file and the version of the google provider that you're using? If you have debug logs as well those might end up being useful.

**Comment by jchoksijudopay** [comment]
Hi

Here is some example code to demonstrate the issue:
Note: You will need to change the project / region to something else for it to work for you:


```tf
terraform {
  required_version = "=0.11.14"

  backend "local" {
    path = "./terraform.tfstate"
  }
}

provider "google" {
  version = "=2.15.0"

  project = "opnf-staging"
  region  = "europe-west1"
}

resource "google_logging_project_sink" "project_level_log_sink" {
  name    = "example-prj-lvl-log-sink"
  project = "opnf-staging"

  #filter                 = "resource.type:k8s_container"
  filter                 = ""
  destination            = "pubsub.googleapis.com/projects/opnf-staging/topics/some_topic_name"
  unique_writer_identity = "false"
}

output "log_sink_filter" {
  description = "The filter to apply when exporting logs. Only log entries that match the filter are exported. See Advanced Log Filters for information on how to write a filter."
  value       = "${element(concat(google_logging_project_sink.project_level_log_sink.*.filter, list("")), 0)}"
}
```

I reported this issue with Terraform 0.11.11, and the above example reproduces it with 0.11.14 as well. We were using v1.20.0 of the Google Terraform Provider but the above example reproduces it with the latest v2.15.0 version.

The outcome of running the above is:

```
C:\Temp\Terraform>terraform init

Initializing the backend...

Successfully configured the backend "local"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "google" (2.15.0)...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

C:\Temp\Terraform>terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Error running plan: 1 error occurred:
        * output.log_sink_filter: Resource 'google_logging_project_sink.project_level_log_sink' does not have attribute 'filter' for variable 'google_logging_project_sink.project_level_log_sink.*.filter'

C:\Temp\Terraform>
```

We specified the filter to be "" since according to: https://github.com/terraform-google-modules/terraform-google-log-export, setting it to "" exports all logs.

Setting the filter to "" may be the problem.

regards,
Jinesh

**Comment by danawillow** [comment]
I ran a similar config against terraform 0.12, and it plans just fine, so my guess is that the syntax you're using is valid in 0.12 but not in 0.11.

I did notice that you're using the * operator on a resource that doesn't specify a count, which could be the problem. Any reason why you decided to do that?

**Comment by jchoksijudopay** [comment]
Hi

I can confirm that with terraform 0.12.9, the example config above does work fine when the filter is set to "".

So this looks like a terraform core issue in versions <0.12.x and not a provider issue. I'll close the issue. Thank you for your time.

Regarding your comment / query about the syntax for the ouput:

I got the idea of using that syntax from reading the code here: https://github.com/terraform-google-modules/terraform-google-log-export/blob/v2.2.0/modules/pubsub/main.tf#L22

but I don't think the issue is the syntax used since if I use the following output instead of the one described above, I get the same issue in terraform <0.12.x:

```tf
output "log_sink_filter" {
  description = "The filter to apply when exporting logs. Only log entries that match the filter are exported. See Advanced Log Filters for information on how to write a filter."

  #value       = "${element(concat(google_logging_project_sink.project_level_log_sink.*.filter, list("")), 0)}"
  value = "${google_logging_project_sink.project_level_log_sink.filter}"
}
```

When filter is set to "", I get a "does not have attribute 'filter' for variable" error in terraform <0.12.x. When filter is set to some value, it works fine.
