### ISSUE TITLE
google_compute_firewall: allow protocol should be case insensitive

### ISSUE THREAD

**Issue by JordanP** [terraform-providers/terraform-provider-google#4458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.12.7
+ provider.acme v1.4.0
+ provider.cloudflare v1.18.1
+ provider.external v1.2.0
+ provider.google v2.14.0
+ provider.kubernetes v1.9.0
+ provider.null v2.1.2
+ provider.random v2.2.0
+ provider.tls v2.1.0
```

### Affected Resource(s)
* google_compute_firewall

### Terraform Configuration Files

```tf
resource "google_compute_firewall" "allow_ssh" {
  name    = "allow-ssh"
  network = "default"
  allow {
    protocol = "TCP"
    ports    = ["22"]
  }
  source_ranges = ["0.0.0.0/0"]
}
```

### Debug Output
```
  ~ resource "google_compute_firewall" "allow_ssh" {
        creation_timestamp      = "2019-09-16T04:39:48.012-07:00"
        destination_ranges      = []
        direction               = "INGRESS"
        disabled                = false
   ....

      + allow {
          + ports    = [
              + "22",
            ]
          + protocol = "TCP"
        }
      - allow {
          - ports    = [
              - "22",
            ] -> null
          - protocol = "tcp" -> null
        }
    }
```

### Expected Behavior

No diff

### Actual Behavior

Looks like TF wants to replace TCP by tcp (case difference)

### Steps to Reproduce

1. `terraform apply`

**Comment by slevenick** [comment]
Thanks for the report! I have a fix for this, should be merged within a day or two
