### ISSUE TITLE
default_max_pods_per_node is out of beta

### ISSUE THREAD

**Issue by ewolak-sq** [terraform-providers/terraform-provider-google#4466]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `default_max_pods_per_node` option on the `google_container_cluster` resource is no longer a Beta feature. I know this because [the documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/flexible-pod-cidr) says to run `gcloud container clusters...`, not `gcloud beta container clusters`...

### New or Affected Resource(s)

* `google_container_cluster`

### References

* https://cloud.google.com/kubernetes-engine/docs/how-to/flexible-pod-cidr

**Comment by ewolak-sq** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/2377

**Comment by ewolak-sq** [comment]
This should be fixed by GoogleCloudPlatform/magic-modules#2429.

**Comment by rileykarson** [comment]
Looks like we missed updating some docs, I'll update those and close this out.
