### ISSUE TITLE
google_compute_firewall don't accept list variable in source_ranges

### ISSUE THREAD

**Issue by Cib0rg** [terraform-providers/terraform-provider-google#4482]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.9
+ provider.google v2.15.0

### Affected Resource(s)

* google_compute_firewall

### Terraform Configuration Files

```tf
variable "GCP-NETWORK-LB-HEALTHCHECK-SUBNETS" {
  default = [
    "209.85.152.0/22",
    "209.85.204.0/22",
    "35.191.0.0/16",
  ]
}

resource "google_compute_firewall" "fw-allow-all-server-tcp8040" {
  name    = "fw-allow-all-server-tcp8040"
  network = data.google_compute_network.us1101.self_link

  allow {
    protocol = "tcp"
    ports    = ["8040"]
  }

  source_ranges = [
    concat(var.GCP-LOADBALANCER-SUBNETS,
    var.VPN-CORPIT-SUBNET,
)
  ]

  target_tags = [
    "fw-allow-all-server-tcp8040",
  ]
}
```

### Expected Behavior
Correct object creation

### Actual Behavior

Error: Incorrect attribute value type

  on firewall.tf line 10, in resource "google_compute_firewall" "fw-allow-all-server-tcp8040":
  10:   source_ranges = [

Inappropriate value for attribute "source_ranges": element 0: string required.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by slevenick** [comment]
Hey there,

I think the issue here is the syntax around `concat`. `concat` takes multiple lists and turns them into a single list, but when you put that inside the `[]` brackets in your config you are declaring a list of lists, like so:
`source_ranges = [ ["item1", "item2"] ]`

What you want is:
```source_ranges = concat(var.GCP-LOADBALANCER-SUBNETS, var.VPN-CORPIT-SUBNET)```
