### ISSUE TITLE
Infinite apply loop when sql database instance region is us-central instead of us-central1

### ISSUE THREAD

**Issue by danielcompton** [terraform-providers/terraform-provider-google#449]
### Terraform Version
Terraform v0.10.6
GCP provider v0.1.3

### Affected Resource(s)

- google_compute_instance_template
- google_sql_database_instance

### Terraform Configuration Files
```hcl
resource "google_sql_database_instance" "master" {
  region           = "us-central"
  database_version = "POSTGRES_9_6"

  settings {
    tier = "${terraform.env == "default" ? "db-custom-1-4096" : "db-f1-micro"}"

    backup_configuration {
      enabled = true
    }
  }
}

resource "google_sql_database" "app" {
  name     = "deps_prod"
  instance = "${google_sql_database_instance.master.name}"
}
```

### Expected Behavior
After running an apply, terraform should reach a stable configuration

### Actual Behavior
Every time I run plan after an apply, the database instance wants to be recreated.

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

### Important Factoids
When writing up this issue, I found that the region was changing from us-central1 back to us-central. The [docs](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#region) say that you need to use us-central, but it seems like now us-central1 is ok?

This might be good to put in some upgrade notes for people upgrading to 0.10 Terraform. I assumed something was broken with the provider when I first saw this, and almost didn't bother upgrading and trying to debug it.

**Comment by danawillow** [comment]
I'm going to go ahead and close this based on #521, but if we see it come up more I can look into a more robust solution.
