### ISSUE TITLE
Return better error message when custom IAM role_id contains `-` characters

### ISSUE THREAD

**Issue by mdeggies** [terraform-providers/terraform-provider-google#4492]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When we create custom IAM roles through terraform, many times people will mistakenly add `-` characters to the role_id, which is not valid. The error message is not helpful in uncovering the actual problem that needs to be fixed (see below): 

```
Error: Error applying plan:

1 error(s) occurred:

* google_project_iam_policy.project_policy: 1 error(s) occurred:

* google_project_iam_policy.project_policy: Error applying IAM policy to project: Error applying IAM policy for project "ads-data-pipeline-test". Policy is &cloudresourcemanager.Policy{AuditConfigs:[]*cloudresourcemanager.AuditConfig(nil), Bindings:[]*cloudresourcemanager.Binding{(*cloudresourcemanager.Binding)(0xc000839560), (*cloudresourcemanager.Binding)(0xc0008395c0), (*cloudresourcemanager.Binding)(0xc000839620), (*cloudresourcemanager.Binding)(0xc000839680), (*cloudresourcemanager.Binding)(0xc0008396e0), (*cloudresourcemanager.Binding)(0xc000839740), (*cloudresourcemanager.Binding)(0xc0008397a0), (*cloudresourcemanager.Binding)(0xc000839800), (*cloudresourcemanager.Binding)(0xc000839860), (*cloudresourcemanager.Binding)(0xc0008398c0), (*cloudresourcemanager.Binding)(0xc000839920), (*cloudresourcemanager.Binding)(0xc000839980), (*cloudresourcemanager.Binding)(0xc0008399e0), (*cloudresourcemanager.Binding)(0xc000839a40), (*cloudresourcemanager.Binding)(0xc000839aa0), (*cloudresourcemanager.Binding)(0xc000839b00), (*cloudresourcemanager.Binding)(0xc000839b60), (*cloudresourcemanager.Binding)(0xc000839bc0), (*cloudresourcemanager.Binding)(0xc000839c20), (*cloudresourcemanager.Binding)(0xc000839c80), (*cloudresourcemanager.Binding)(0xc000839ce0), (*cloudresourcemanager.Binding)(0xc000839d40), (*cloudresourcemanager.Binding)(0xc000839da0), (*cloudresourcemanager.Binding)(0xc000839e00), (*cloudresourcemanager.Binding)(0xc000839e60), (*cloudresourcemanager.Binding)(0xc000839ec0), (*cloudresourcemanager.Binding)(0xc000839f20), (*cloudresourcemanager.Binding)(0xc000839f80), (*cloudresourcemanager.Binding)(0xc000736000), (*cloudresourcemanager.Binding)(0xc000736060), (*cloudresourcemanager.Binding)(0xc000736120), (*cloudresourcemanager.Binding)(0xc000736180), (*cloudresourcemanager.Binding)(0xc0007361e0), (*cloudresourcemanager.Binding)(0xc000736240), (*cloudresourcemanager.Binding)(0xc0007362a0), (*cloudresourcemanager.Binding)(0xc000736300), (*cloudresourcemanager.Binding)(0xc0007363c0)}, Etag:"BwWS2IZTb8I=", Version:1, ServerResponse:googleapi.ServerResponse{HTTPStatusCode:200, Header:http.Header{"Content-Type":[]string{"application/json; charset=UTF-8"}, "Server":[]string{"ESF"}, "Cache-Control":[]string{"private"}, "X-Frame-Options":[]string{"SAMEORIGIN"}, "X-Content-Type-Options":[]string{"nosniff"}, "Server-Timing":[]string{"gfet4t7; dur=126"}, "Vary":[]string{"Origin", "X-Origin", "Referer"}, "Date":[]string{"Wed, 18 Sep 2019 19:09:38 GMT"}, "X-Xss-Protection":[]string{"0"}}}, ForceSendFields:[]string(nil), NullFields:[]string(nil)}, error is googleapi: Error 400: The role name must be in the form "roles/{role}", "organizations/{organization_id}/roles/{role}", or "projects/{project_id}/roles/{role}"., badRequest
```

### New or Affected Resource(s)

* google_project_iam_custom_role

Link: https://www.terraform.io/docs/providers/google/r/google_project_iam_custom_role.html

### Potential Terraform Configuration

N/A

### References

None that I have found

**Comment by norbjd** [comment]
I may be mistaken, but I don't believe this error is related to the `-` character present in the `role_id`. I've tried to reproduce the error with the latest provider (`3.11.0`) and also the last provider at the time when the issue was written (`2.15.0`, released September 17, 2019) with the following resource (notice the `-` character in the `role_id`) :

```
resource "google_project_iam_custom_role" "my-custom-role" {
  role_id     = "my-CustomRole"
  title       = "My Custom Role"
  description = "A description"
  permissions = ["iam.roles.list", "iam.roles.create", "iam.roles.delete"]
}
```

And in both cases, I got the following error when running `terraform plan` :

```
Error: "role_id" ("my-CustomRole") doesn't match regexp "^[a-zA-Z0-9_\\.]{3,64}$"
```

This error fits to find the real problem that needs to be fixed. This leads to the same explanation that the Console provides when messing with the `role_id` :

> ID must be at least 3 characters long.
ID can only include letters, numbers, periods and underscores.

**Comment by danawillow** [comment]
That validation was added in https://github.com/terraform-providers/terraform-provider-google/pull/3109, which makes me think the report was from an older provider version. Regardless, the field is checked for valid values at plan-time, so closing.
