### ISSUE TITLE
Unable to create multi-zonal cluster with separate node-pool

### ISSUE THREAD

**Issue by elsbrock** [terraform-providers/terraform-provider-google#4499]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

`Terraform v0.12.9`, `terraform-provider-google_v2.15.0`

### Affected Resource(s)

* `google_container_cluster`
* `google_container_node_pool`

### Terraform Configuration Files

```tf
resource "google_container_cluster" "primary" {
  name     = "${var.name}"
  
  location = "europe-west3-a"
  node_locations = ["europe-west3-b"]

  network = "projects/${var.project}/global/networks/default"

  # enable VPC native
  ip_allocation_policy {}

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true
  initial_node_count = 1

  monitoring_service = "monitoring.googleapis.com/kubernetes"
  logging_service    = "logging.googleapis.com/kubernetes"

  master_auth {
    username = ""
    password = ""

    client_certificate_config {
      issue_client_certificate = false
    }
  }

  addons_config {
    http_load_balancing {
      disabled = false
    }

    horizontal_pod_autoscaling {
      disabled = false
    }

    network_policy_config {
      disabled = false
    }

    kubernetes_dashboard {
      disabled = true
    }
  }

  network_policy {
    enabled  = true
    provider = "CALICO"
  }

  maintenance_policy {
    daily_maintenance_window {
      start_time = "01:00"
    }
  }

  lifecycle {
    prevent_destroy = true
  }

  timeouts {
    update = "1h"
  }
}

resource "google_container_node_pool" "primary_pool" {
  cluster    = "${google_container_cluster.primary.name}"

  location = "${google_container_cluster.primary.location}"

  initial_node_count = "${var.primary_pool_node_count}"

  node_config {
    machine_type = "${var.primary_pool_node_config_machine_type}"
    disk_size_gb = "${var.primary_pool_node_config_disk_size_zb}"

    oauth_scopes = [
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
      "https://www.googleapis.com/auth/servicecontrol",
      "https://www.googleapis.com/auth/service.management.readonly",
      "https://www.googleapis.com/auth/trace.append"
    ]
  }

  management {
    auto_repair  = true
    auto_upgrade = true
  }

  lifecycle {
    create_before_destroy = true
  }

  timeouts {
    create = "30m"
  }
}
```

### Expected Behavior

Expected the cluster to be created with node pool and 2*n nodes in total for the two configured zones of the pool.

### Actual Behavior

It creates two compute instance groups with n nodes each. However, only the nodes of the instance group of the same zone like the master register correctly with the K8S master (in this case `europe-west3-a`). The ones in `europe-west3-b` never show up. I can see in `k get events` that nodes do register initially, but are then subsequently removed because they do not appear to be healthy/discoverable: https://gist.github.com/elsbrock/a9c43374af10315c8743590364873887

After 15 minutes, the following error is received from terraform:

```
Error: Error waiting for creating GKE NodePool: All cluster resources were brought up, but the cluster API is reporting that: only 2 nodes out of 4 have registered; cluster may be unhealthy.
```

Creating a cluster with the very same configuration via the UI works fine. I have retrieved `gcloud container node-pools describe` and `gcloud container clusters describe` and do not see any apparent difference. I'm not sure what's wrong.

### Steps to Reproduce

see above

1. `terraform apply`

**Comment by memory** [comment]
Fascinating.  This exact scenario happened to me as well recently.  Even odder, we were rebuilding a cluster that we had previously successfully built with the same manifest ~150 days ago.  Unclear whether the regression is on the provider side or google's.

**Comment by memory** [comment]
Hopefully useful: I'm appending the container.googleapis.com log (with some PII elided :) for the lifecycle of a test cluster I created to reproduce the issue. 
[gke_log.json.txt](https://github.com/terraform-providers/terraform-provider-google/files/3636999/gke_log.json.txt)

(Note that for some reason the stackdriver json exporter put this in reverse chronological order: you need to read from the bottom up.)

**Comment by slevenick** [comment]
Strange, I'm able to reproduce the issue with a similar config, but there is no apparent reason why it would fail like this. Changing to a regional cluster by specifying
```
  location = "europe-west3"
  node_locations = ["europe-west3-b", "europe-west3-b"]
```
works just fine. Will continue to investigate

**Comment by slevenick** [comment]
Update on this, it seems like specifying the `  ip_allocation_policy {}` causes this issue. Removing this line causes the create to succeed (at least in my case).

I don't have an exact cause, but it looks like specifying this causes the nodes that are created in different zones from the master to not be able to connect. I'll try to see if a default has changed recently that would have caused this

**Comment by slevenick** [comment]
Another update: It looks like this is caused by a change that happened around June 17th to the `use_ip_aliases` block within `ip_allocation_policy`.

The updated documentation from the website for this resource says 
```use_ip_aliases - (Optional) Whether alias IPs will be used for pod IPs in the cluster. Defaults to true if the ip_allocation_policy block is defined, and to the API default otherwise. Prior to June 17th 2019, the default on the API is false; afterwards, it's true.
```

It looks like there was a change to the default value at that time that is setting `use_ip_aliases` to true, which is causing the node to be unable to connect. Changing the `ip_allocation_policy` block to 
```
  ip_allocation_policy {
    use_ip_aliases = false
  }
```
should fix this issue

**Comment by memory** [comment]
Er, but we very much want to use IP aliases with our clusters, and in fact using them is google's recommended approach: https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips

You are correct that google changed the API default from route-based to IP-alias in June, but I do not see why this should make it impossible to create a zonal master with multi-zone node pools, and while I can't speak for @elsbrock we were absolutely manually setting `use_ip_aliases` to true before this behavior started occurring.

Respectfully, this bug does not seem to me to be resolved.

**Comment by memory** [comment]
@slevenick ping? :)
