### ISSUE TITLE
Provider produced inconsistent final plan google_service_networking_connection

### ISSUE THREAD

**Issue by MartinLavelle** [terraform-providers/terraform-provider-google#4501]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.9
+ provider.google v2.15.0
+ provider.google-beta v2.15.0
+ provider.null v2.1.2

### Affected Resource(s)

google_service_networking_connection

### Terraform Configuration Files

data "google_compute_network" "default" {
  project                    = "insert-your-project-here"
  name                       = "default"
  provider                   = "google-beta"
}
resource "google_compute_global_address" "google-managed-services-range" {
  provider      = google-beta
  project       = "insert-your-project-here"
  name          = "google-managed-services-test"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  network       = data.google_compute_network.default.self_link
}
resource "google_service_networking_connection" "private_service_access" {
  provider                = google-beta
  network                 = google_compute_global_address.google-managed-services-range.network
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.google-managed-services-range.name]
}
resource "null_resource" "dependency_setter" {
  depends_on = [google_service_networking_connection.private_service_access]
}

### Debug Output
The following text is returned form the apply:

Error: Provider produced inconsistent final plan

When expanding the plan for
module.private-service-access.google_service_networking_connection.private_service_access
to include new values learned so far during apply, provider "google-beta"
produced an invalid new value for .network: was cty.StringVal("default"), but
now
cty.StringVal("https://www.googleapis.com/compute/v1/projects/insert-your-project-here/global/networks/default").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Panic Output

No Panic

### Expected Behavior

Private Service Access should have been enabled for the google network

### Actual Behavior

The apply produced the error shown in the "Debug Output", However the apply may succeed it the plan and apply are repeated directly.

### Steps to Reproduce

1. `terraform apply example.plan`

### Important Factoids

When the google_compute_network is provided as a resource rather than a data type the apply succeeds.

**Comment by slevenick** [comment]
I'm unable to reproduce this error. The config included in the report does not seem to work, the API rejects the `google_compute_global_address` due to a lack of a `prefix_length`.

I attempted to reproduce using a similar config with a datasource as the network, but it succeeds. 

My config:
```
data "google_compute_network" "default" {
	name = "default"
}

resource "google_compute_global_address" "private_ip_alloc" {
  name          = "private-ip-alloc"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  network       = "${data.google_compute_network.default.self_link}"
}

resource "google_service_networking_connection" "foobar" {
  network                 = "${data.google_compute_network.default.self_link}"
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = ["${google_compute_global_address.private_ip_alloc.name}"]
}

resource "null_resource" "dependency_setter" {
	depends_on = [google_service_networking_connection.foobar]
}
```
With terraform 0.12.9, google/google-beta 2.15.0

Are you able to reproduce this with only the config that you posted?
