### ISSUE TITLE
Remove long form name behavior for pubsub subscriptions

### ISSUE THREAD

**Issue by paddycarver** [terraform-providers/terraform-provider-google#4508]
I'm not sure on the background of this one, but it came up in our discussion of 3.0.0 goals. I believe you can currently specify two versions of the pubsub subscription name, and the long one is undesirable for some reason, and so we want to stop supporting it. @danawillow, assigning this to you so you can assign it to Cameron when they get commit access.

**Comment by rileykarson** [comment]
I forget the exact context, but we have custom code to allow specifying something- I think the `name`- as either the shortname or long name. We kept it for BC reasons when MM-ifying the resource, but we can remove some of that behaviour (and the underlying custom code) in 3.0.0.

**Comment by danawillow** [comment]
`topic` is currently doing `compareSelfLinkOrResourceName` which seems perfectly reasonable for it to do. `name` is `comparePubsubSubscriptionBasename` which seems like the actual one to get rid of (and instead treat it like the other newer-style APIs where the `name` field is always short). Does that sound like what you were thinking, @rileykarson?

**Comment by danawillow** [comment]
Cool. Since @c2thorn has plenty of other things on his plate right now, I'm going to go ahead and take this since it's pretty quick.

**Comment by rileykarson** [comment]
Closed in linked issue ("Fixes: " doesn't work in non-primary branches)
