### ISSUE TITLE
[Beta] Compute Resource Policy recreates disk when attaching a policy 

### ISSUE THREAD

**Issue by dkothari-clgx** [terraform-providers/terraform-provider-google#4511]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.4
GCP Provider 2.14.0

### Affected Resource(s)

* google_compute_disk
* google_compute_resource_policy 

### Terraform Configuration Files
Previous Terraform code 
```tf
resource "google_compute_disk" "data" {
  name  = "myDisk0"

  labels = "myDisk0"

  zone = "us-west1-a"

  type = "${var.data_volume_type}"
  size = "${var.data_volume_size}"
}
```
```tf 
resource "google_compute_disk" "data" {
  name  = "myDisk0"
  provider = "beta" 
  labels = "myDisk0"

  zone = "us-west1-a"

  type = "${var.data_volume_type}"
  size = "${var.data_volume_size}"
resource_policies = ["${google_compute_resource_policy.snapshot_policy.name}"]
}

resource "google_compute_resource_policy" "snapshot" {
  provider = "google-beta"
  name = "myDisk0-snapshot-policy"
  region = "us-west1"
  snapshot_schedule_policy {
    schedule {
      daily_schedule {
        days_in_cycle = 1
        start_time = "07:00"
      }
    }
    retention_policy {
      max_retention_days = "${var.disks_snapshot_rention_days}"
      on_source_disk_delete = "KEEP_AUTO_SNAPSHOTS"
    }
    snapshot_properties {
      labels = "myDisk0"
      storage_locations = ["us"]
      guest_flush = true
    }
  }
}

```

### Expected Behavior
The policy should be created and be attached. 

### Actual Behavior
Disk gets recreated and then policy gets created and attached according to the plan.
 
### Important Factoids

Understand this is in beta.

**Comment by rileykarson** [comment]
Related: https://github.com/GoogleCloudPlatform/magic-modules/pull/2228 will add a fine-grained resource to allow attaching resource policies (+ bumps the feature to GA) in our next release.

**Comment by slevenick** [comment]
I'd suggest waiting for the next release to use the fine-grained resource mentioned by @rileykarson  to manage policies. Currently changing any field on a compute disk will force a recreate, but the fine-grained resource will help fix this
