### ISSUE TITLE
Terraform computes change to google_compute_router_nat based on subnetwork name vs. full self-link

### ISSUE THREAD

**Issue by Markbnj** [terraform-providers/terraform-provider-google#4513]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform 0.12.8
Provider 2.15.0

### Affected Resource(s)
* google_compute_router_nat

### Terraform Configuration Files
```tf
resource "google_compute_router_nat" "nat_gateway" {
  name = "nat-gateway"
  router = google_compute_router.router-nat-gateway.name
  region = google_compute_router.router-nat-gateway.region

  nat_ip_allocate_option = "MANUAL_ONLY"
  nat_ips = google_compute_address.address-nat-egress[*].self_link

  source_subnetwork_ip_ranges_to_nat = "LIST_OF_SUBNETWORKS"
  subnetwork {
    name = "prod-us-central1"
    source_ip_ranges_to_nat = ["ALL_IP_RANGES"]
  }
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
On running the plan step for an unrelated change, with no changes made to the google_compute_router_nat resource, we would expect to see no changes to the deployed component.

### Actual Behavior
```
Terraform will perform the following actions:

  # module.nat-gateway-prod.google_compute_router_nat.nat_gateway will be updated in-place
  ~ resource "google_compute_router_nat" "nat_gateway" {
        icmp_idle_timeout_sec              = 30
        id                                 = "xxxxxxxx/us-central1/nat-gateway/nat-gateway"
        min_ports_per_vm                   = 0
        name                               = "nat-gateway"
        nat_ip_allocate_option             = "MANUAL_ONLY"
        nat_ips                            = [
            "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/regions/us-central1/addresses/nat-egress-ip-0",
            "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/regions/us-central1/addresses/nat-egress-ip-1",
        ]
        project                            = "xxxxxxxx"
        region                             = "us-central1"
        router                             = "nat-gateway"
        source_subnetwork_ip_ranges_to_nat = "LIST_OF_SUBNETWORKS"
        tcp_established_idle_timeout_sec   = 1200
        tcp_transitory_idle_timeout_sec    = 30
        udp_idle_timeout_sec               = 30

      - subnetwork {
          - name                     = "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/regions/us-central1/subnetworks/prod-us-central1" -> null
          - secondary_ip_range_names = [] -> null
          - source_ip_ranges_to_nat  = [
              - "ALL_IP_RANGES",
            ] -> null
        }
      + subnetwork {
          + name                     = "prod-us-central1"
          + secondary_ip_range_names = []
          + source_ip_ranges_to_nat  = [
              + "ALL_IP_RANGES",
            ]
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.```

### Steps to Reproduce

Create the resource as described above, then run plan against the project after it has been created.

**Comment by slevenick** [comment]
Looking at either updating the hash function on `subnetwork` to prevent the diff, or preventing the overwrite of the `subnetwork.name` field during API read to resolve this.

**Comment by slevenick** [comment]
This will be available in the next release of the terraform provider.
