### ISSUE TITLE
Add iam_binding for Binary Authorization Attestor

### ISSUE THREAD

**Issue by megan07** [terraform-providers/terraform-provider-google#4516]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

add an IAM role binding to an attestor in Terraform

### New or Affected Resource(s)

* google_binary_authorization_policy

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_binary_authorization_attestor_iam_policy" "foo" {
	project = 
	attestor = 
	policy_data = 
}
```

### References

* https://cloud.google.com/binary-authorization/docs/multi-project-setup-cli#add_an_iam_role_binding_for_the_deployer_project

**Comment by erkolson** [comment]
Is this to handle the iam binding for the container analysis note for the system binauthz service account?  For both the deployer and attestor projects?
