### ISSUE TITLE
google_cloudiot_registry - event_notification_config(s)

### ISSUE THREAD

**Issue by olegkorol** [terraform-providers/terraform-provider-google#4522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.9
provider.google v2.15.0
provider.google-beta v2.15.0

### Affected Resource(s)

* google_cloudiot_registry

### Terraform Configuration Files

```tf
[...]
resource "google_cloudiot_registry" "device-registry" {
  name = "device-registry"
  project = "${var.gcp_project}"
  region = "${var.region}"

  event_notification_config = {
        pubsub_topic_name = "${google_pubsub_topic.device-events.id}" 
    }

  state_notification_config = {
    pubsub_topic_name = "${google_pubsub_topic.device-states.id}"
  }

  http_config = {
    http_enabled_state = "HTTP_ENABLED"
  }

  mqtt_config = {
    mqtt_enabled_state = "MQTT_ENABLED"
  }
}
[...]
```

### Debug Output

When running `terraform plan` I get the following:
```
Warning: "event_notification_config": [DEPRECATED] eventNotificationConfig has been deprecated in favor of eventNotificationConfigs (plural). Please switch to using the plural field.
```

Fair enough. So then I rewrite eventNotificationConfig to:
```tf
[...]
  event_notification_configs = [
    {
        pubsub_topic_name = "${google_pubsub_topic.device-events.id}"
        subfolder_matches = "some-subfolder"
    },
    {
        pubsub_topic_name = "${google_pubsub_topic.device-events.id}"
        subfolder_matches = "some-subfolder-2"
    },
    {
        pubsub_topic_name = "${google_pubsub_topic.device-events.id}"
        subfolder_matches = ""
        
    }
  ]
[...]
```

... and I get the following output:
```
Error: Unsupported argument

  on main.tf line 16, in resource "google_cloudiot_registry" "device-registry":
  16:   event_notification_configs = [

An argument named "event_notification_configs" is not expected here. Did you
mean "event_notification_config"?
```

It sounds kind of contradicting to me... :/

### Expected Behavior

Either `event_notification_config` or `event_notification_configs` should work.
I would not expect the output to tell that both are incorrect.

### Actual Behavior

Both arguments are "unsupported".

### Steps to Reproduce

1.  Create a main.tf definition as the one pasted above.
2.  Run `terraform plan`

Thanks a lot in advance!

**Comment by olegkorol** [comment]
PS:

I see that the `event_notification_configs` argument exists though. Why would it say otherwise?

https://github.com/terraform-providers/terraform-provider-google/blob/41a3cd05433e7bd899096897144f9e7a8091ab9f/google/resource_cloudiot_registry.go#L74-L94

**Comment by emilymye** [comment]
This list format in HCL was actually removed  in 0.12. If you do

resource "google_cloudiot_registry" "device-registry" {

event_notification_configs {
        pubsub_topic_name = "${google_pubsub_topic.device-events.id}"
        subfolder_matches = "some-subfolder"
}
event_notification_configs {
        pubsub_topic_name = "${google_pubsub_topic.device-events.id}"
        subfolder_matches = "some-subfolder-2"
}
}

it *should* work...but also I found a different bug with subfolder matches for multiple event notification configs. So, if you only want to do singular, you can just do by adding a s to your block declaration and removing the equal sign, but I'll have to get a fix in for the multiple event notification configs.

Sorry for the trouble!

**Comment by olegkorol** [comment]
Thanks for the quick feedback @emilymye.

This seems to do the trick - at least when running `terraform plan`. Thank you.
I have to say this wasn't the syntax I expected though. It is a little bit confusing, IMO.

What would this _bug with subfolder matches_ be?
I actually do need to define `subfolder_matches` for multiple `event_notification_configs`. What kind of trouble should I be expecting?

**Comment by emilymye** [comment]
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/2362
