### ISSUE TITLE
google_security_scanner_scan_config always requires recreation 

### ISSUE THREAD

**Issue by kpurdon** [terraform-providers/terraform-provider-google#4542]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

v0.12.8

### Affected Resource(s)

* google_security_scanner_scan_config

### Terraform Configuration Files

```tf
resource "google_security_scanner_scan_config" "ce" {
  project                           = var.gcp_project
  provider                          = "google-beta"
  display_name                      = "CE Web Application"
  starting_urls                     = ["https://${var.ce_domain_name}"]
  target_platforms                  = ["COMPUTE"]
  export_to_security_command_center = "ENABLED"

  authentication {
    custom_account {
      username  = var.web_security_scan_account_username
      password  = var.web_security_scan_account_password
      login_url = "https://${var.ce_domain_name}"
    }
  }

  schedule {
    schedule_time          = "2019-09-25T15:07:00Z" # 7am UTC, 3am EST
    interval_duration_days = 7
  }
}
```

### Expected Behavior

After being created, this resource should not require recreation w/o changes.

### Actual Behavior

The resource requires a recreate with no changes.

```
  # module.syndio_monitoring_ce.google_security_scanner_scan_config.ce must be replaced
-/+ resource "google_security_scanner_scan_config" "ce" {
      - blacklist_patterns                = [] -> null
        display_name                      = "CE Web Application"
        export_to_security_command_center = "ENABLED"
      ~ id                                = "projects/staging-e67bcca1/scanConfigs/5210846834327552" -> (known after apply)
        max_qps                           = 15
      ~ name                              = "projects/staging-e67bcca1/scanConfigs/5210846834327552" -> (known after apply)
        project                           = "staging-e67bcca1"
        starting_urls                     = [
            "https://gcp-ce-staging.synd.io",
        ]
        target_platforms                  = [
            "COMPUTE",
        ]
        user_agent                        = "CHROME_LINUX"

      ~ authentication {
          ~ custom_account {
                login_url = "https://gcp-ce-staging.synd.io"
              + password  = (sensitive value)
                username  = "devops+gcpwebsecscan@synd.io"
            }
        }

        schedule {
            interval_duration_days = 7
            schedule_time          = "2019-09-25T15:07:00Z"
        }
    }
```

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

### References

N/A

**Comment by tysen** [comment]
I'm looking into resolving this but the above PR requires some modifications to our code generation in order to work. The problem is that the API does not return the password in the response object so it looks like a diff to Terraform.
