### ISSUE TITLE
google_kms_secret_ciphertext ciphertext is not being base64 decoded

### ISSUE THREAD

**Issue by siropsalot** [terraform-providers/terraform-provider-google#4545]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Using Terraform 0.11.8

### Affected Resource(s)

* google_kms_secret_ciphertext

### Terraform Configuration Files

```tf
data "google_kms_secret_ciphertext" "encrypt" {
  crypto_key = "${var.key}"
  plaintext = "${some_info_from_data_source}"
}

resource "local_file" "save_encrypted" {
  content  = "${data.google_kms_secret_ciphertext.encrypt.ciphertext}"
  filename = "save-me.txt"
}
```

### Expected Behavior

the file should contain a bare ciphertext string equivalent to other methods of encrypting, e.g. via the gcloud cli

### Actual Behavior

the string produced by this data source is base64 encoded

### Steps to Reproduce

1. `terraform apply`

* #0000

**Comment by tysen** [comment]
If you replace `content` with `content_base64` in your `local_file` resource declaration, the output file will contain bare ciphertext.

As a note, [the encrypt method](https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings.cryptoKeys/encrypt) in the API requires and outputs base64 encoded strings.
