### ISSUE TITLE
Update (R)IGM update functionality in GA provider

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#4555]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://github.com/terraform-providers/terraform-provider-google-beta/pull/1 updated (R)IGM  resources to use the newer updater functionality, but it hasn't made it into the GA provider yet. We need to do this enough before 3.0.0 that we can deprecate the old `update_strategy` field and remove it in 3.0.0.

### New or Affected Resource(s)

* google_compute_instance_group_manager
* google_compute_region_instance_group_manager

**Comment by rileykarson** [comment]
@chrisst: Mind attaching the followup PR to this?
