### ISSUE TITLE
Unable to create zonal GKE cluster with multi-zone node pool

### ISSUE THREAD

**Issue by memory** [terraform-providers/terraform-provider-google#4562]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Seen in:
```
Terraform v0.12.9
terraform-provider-google_v2.15.0
```

...and also in:

```
Terraform v0.11.14
provider.google v2.16.0
```

### Affected Resource(s)

* `google_container_cluster`
* `google_container_node_pool`

### Terraform Configuration Files

```tf
variable project {
  description = "GKE project name"
  default     = "myproject"
}

variable region {
  description = "Region for the cluster and its node pools"
  default     = "us-central1"
}

provider "google" {
  project     = "${var.project}"
  region      = "${var.region}"
  credentials = ""
}

variable name {
  description = "Name for the service and prefix for supporting resources."
  default     = "testcluster-1"
}

variable zone {
  description = "Zone for the cluster and its node pools; leave blank for a regional cluster"
  default     = "a"
}

variable version {
  description = "GKE release for the master and nodes"
  default     = "1.13.7-gke.24"
}

variable machine_type {
  description = "Google Cloud Compute machine type."
  default     = "n1-standard-1"
}

resource "google_container_cluster" "default" {
  name               = "${var.name}"
  location           = "${join("-",compact(list(var.region, var.zone)))}"
  node_version       = "${var.version}"
  min_master_version = "${var.version}"
  project            = "${var.project}"
  network            = "default"

  // add the "A" zone if deploying a regional cluster
  node_locations = [
    "${var.region}-b",
    "${var.region}-c",
  ]

  # Stackdriver Kubernetes Monitoring support (Beta).
  monitoring_service = "monitoring.googleapis.com/kubernetes"
  logging_service    = "logging.googleapis.com/kubernetes"

  ip_allocation_policy {
    use_ip_aliases = true
  }

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true

  initial_node_count = 1

  # Setting an empty username and password explicitly disables basic auth
  master_auth {
    username = ""
    password = ""

    client_certificate_config {
      issue_client_certificate = false
    }
  }
}

resource "google_container_node_pool" "primary" {
  name               = "primary"
  location           = "${join("-",compact(list(var.region, var.zone)))}"
  cluster            = "${google_container_cluster.default.name}"
  project            = "${var.project}"
  initial_node_count = 1

  management {
    auto_repair  = true
    auto_upgrade = false
  }

  autoscaling {
    min_node_count = 1
    max_node_count = 2
  }

  node_config {
    preemptible  = false
    machine_type = "${var.machine_type}"

    metadata {
      disable-legacy-endpoints = "true"
    }

    oauth_scopes = [
      "https://www.googleapis.com/auth/bigquery",
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly",
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring.write",
      "https://www.googleapis.com/auth/monitoring",
      "https://www.googleapis.com/auth/pubsub",
      "https://www.googleapis.com/auth/service.management.readonly",
      "https://www.googleapis.com/auth/servicecontrol",
      "https://www.googleapis.com/auth/sqlservice.admin",
      "https://www.googleapis.com/auth/trace.append",
    ]
  }
}
```

### Expected Behavior

Terraform should create a zonal GKE cluster (single-zone master), delete the default node pool, and create a node pool named "primary" with nodes in three zones.

### Actual Behavior

Three InstanceGroups are created by the node pool, but only the nodes in the instanceGroup in the same zone as the master (us-central1-a in the example config) succeed in registering with the cluster.  The nodes in the other two instanceGroups are not seen as healthy by the cluster.  Eventually `terraform apply` times out with an error:

```
Error: Error waiting for creating GKE NodePool: All cluster resources were brought up, but the cluster API is reporting that: only 2 nodes out of 4 have registered; cluster may be unhealthy.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* As far as we know, this configuration, as-is, worked correctly the last time we rebuilt the cluster, ~150 days ago.
* Per #4499 setting `use_ip_aliases` to `false` will allow the cluster to set up successfully, but see previous point: this worked before. :) (Also, IP Alias clusters are google's recommended configuration!)
* Building a cluster in the same configuration via either the GKE web console or the gcloud api appears to work
* I've pulled the container.googleapis.com logs and did not see anything obviously amiss: 
[gke_log.json.txt](https://github.com/terraform-providers/terraform-provider-google/files/3663287/gke_log.json.txt)

### References

* https://github.com/terraform-providers/terraform-provider-google/issues/4499

**Comment by slevenick** [comment]
Hello again @memory!

I'm going to bring up this issue with the GKE team. Seems like some network issue is cropping up due to `use_ip_aliases` and deleting the default node pool. 

I'll update this issue as I get more information

**Comment by slevenick** [comment]
One other thing I found, on the machine that comes up but fails to connect to the master (the machine in the different zone from the master) it seems to have a network issue with kube-proxy. 

A snippet from the `kube-proxy.log`:
```
W0927 16:44:42.655672       1 server_others.go:296] Flag proxy-mode="" unknown, assuming iptables proxy
W0927 16:44:42.681979       1 node.go:103] Failed to retrieve node info: nodes "gke-sam-test-cluster-terraform-201909-b8bc249d-zlv3" not found
I0927 16:44:42.682006       1 server_others.go:148] Using iptables Proxier.
W0927 16:44:42.682118       1 proxier.go:314] invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP
I0927 16:44:42.682196       1 server_others.go:178] Tearing down inactive rules.
I0927 16:44:42.810320       1 iptables.go:200] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
```

**Comment by memory** [comment]
You might want to point the GKE folks to enterprise support case `20702476` where I tried to pursue it on their end.  (Without much luck so far.)

**Comment by slevenick** [comment]
Thanks, I believe they are aware of the enterprise support case as well. This is an issue with multi-zone clusters, but I don't have an ETA on when it will be resolved.

I would suggest changing to a regional cluster if possible, as they don't have this issue and should work similarly

**Comment by memory** [comment]
Yeah, that was our workaround for the moment, but boy was it aggravating that this magically stopped working w/o notice. :(  Not your fault obviously -- another day in the cloud I guess.
