### ISSUE TITLE
Which provider version supports v1 endpoint 

### ISSUE THREAD

**Issue by ameyaptk** [terraform-providers/terraform-provider-google#4564]
We got an email from Google notifying that they are shutting down v0.1 and v1beta1 endpoints of the Compute Engine Metadata Server. Recommendation is to update our requests to v1 endpoint. 
For example, if you’re currently making this request:
`curl "http://metadata.google.internal/computeMetadata/v1beta1/instance/id" `
Upgrade to v1 as follows:
`curl "http://metadata.google.internal/computeMetadata/v1/instance/id" -H "Metadata-Flavor: Google" `

We're using the `google` provider and not `google-beta` provider. A quick search shows that our terraform provider `terraform-provider-google_v2.7.0` is using this API call. But being a binary, I'm unable to see what call is being made or what URL is being used.

Given the above-
1) Is there a way to see what the call is being made in the 2.7.0 version?
2) If not, which provider version supports this updated 'v1' call?

**Comment by ndmckinley** [comment]
That's interesting!  How did you find out that terraform was making that call?  The `.internal` tld there tells me that this call can only be made from an instance on GCP.  I'm not sure what your architecture is like, but it would be surprising to me if Terraform was doing that.

**Comment by ndmckinley** [comment]
Thanks!
