### ISSUE TITLE
Setting quic_override in google_compute_target_https_proxy once stops being optional

### ISSUE THREAD

**Issue by gilberthdez** [terraform-providers/terraform-provider-google#4574]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.9
+ provider.google v2.15.0
+ provider.google-beta v2.15.0

### Affected Resource(s)

* google_compute_target_https_proxy

### Terraform Configuration Files

```tf
resource "google_compute_target_https_proxy" "test" {
  name             = "tf-test-proxy"
  url_map          = "${google_compute_url_map.test.self_link}"
  ssl_certificates = "${concat([var.test_certificate_link])}"
  #quic_override    = "ENABLE"
}
```

### Panic Output

```
Error: Error updating TargetHttpsProxy "tf-test-proxy": googleapi: Error 400: Required field 'quicOverride' not specified, required
```

### Expected Behavior

Based on the [documentation](https://www.terraform.io/docs/providers/google/r/compute_target_https_proxy.html#quic_override), the argument is 'optional'. Meaning that setting it once and removing it later shouldn't yield an Error and should set it as default "NONE" as expressed in the documentation.

### Steps to Reproduce

1. Create a `google_compute_target_https_proxy` resource setting the `quic_override`.
2. Update the resource description and comment out `quic_override`.

1. `terraform apply`

### References

* #0000

**Comment by ndmckinley** [comment]
Well, that's certainly what it says in the public REST documentation...

![image](https://user-images.githubusercontent.com/605324/65923815-24e7ff80-e39f-11e9-81c9-8eb213a7fb8c.png)

This is a bug in GCP, then.  We'll work around it by explicitly setting the field default to `NONE`.

**Comment by ndmckinley** [comment]
That'll be https://github.com/GoogleCloudPlatform/magic-modules/pull/2404.
