### ISSUE TITLE
Support for Release Channels in GKE

### ISSUE THREAD

**Issue by zioproto** [terraform-providers/terraform-provider-google#4575]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This is a feature request to support the recent "Release channels" concept of GKE.

https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels

Instead of using the variable `min_master_version` it would be great to create a cluster and just specify the wanted release channel.

The CLI gcloud already implements this with `--release-channel` .

On the dashboard is possible to use Release channels instead of specific versions using this new UI button:
<img width="463" alt="Screen Shot 2019-09-30 at 10 55 51 AM" src="https://user-images.githubusercontent.com/789701/65866017-6d3df800-e374-11e9-8d38-1e489faffda8.png">

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "primary" {
  release_channel = rapid
  [..CUT..]
}
```

### References

* https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels
* I found that someone already proposed a PR for this: https://github.com/terraform-providers/terraform-provider-google/pull/4534
* Once this change is implemented, it will be possible to update the terraform-google-kubernetes-engine module: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/271

**Comment by ndmckinley** [comment]
It looks like that PR was abandoned - we'll put this on our backlog and prioritize according to :+1: reactions as usual.  :)

**Comment by tpoindessous** [comment]
Hi !

New PR on MagicModules : https://github.com/GoogleCloudPlatform/magic-modules/pull/2414

Not merged yet.

**Comment by chrissng** [comment]
PR https://github.com/GoogleCloudPlatform/magic-modules/pull/2414 has been merged. Until the GKE v1 API has Release channels, it will be available as a beta feature.

**Comment by rileykarson** [comment]
Closing since this is done- once it's available in the GA client, feel free to open an issue for us to add it to the `google` provider as well.
