### ISSUE TITLE
rename remote state file in gsp

### ISSUE THREAD

**Issue by maro007** [terraform-providers/terraform-provider-google#4576]
Hello. 

when creating a backend with gsp. it does not seem to be able to change the remote state file. it defaults to whatever workspace I am in. 

```
terraform {
  backend "gcs" {
    bucket = "my-bucket"
    prefix = "fcglab/dns/terraform.tfstate"
  }
}
```

when checking the bucket it  has the following. 
```gsutil ls gs://(my-bucket)/fcglab/dns/terraform.tfstate/
gs://(my-bucket)/fcglab/dns/terraform.tfstate/default.tfstate
```

to my understand the actual file structure should be.
`gs://(my-bucket)/fcglab/dns/terraform.tfstate`

**Comment by ndmckinley** [comment]
Hi,

Sorry, but this repository is for the GCP terraform provider, and your issue is with the GCS terraform backend.  I would say you should reopen this issue in github.com/hashicorp/terraform -  we can't do anything about it here since the code for that backend isn't in this repository.

**Comment by maro007** [comment]
thanks.
