### ISSUE TITLE
Sql database is marked for deletion after growing past `disk_size` 

### ISSUE THREAD

**Issue by mdeggies** [terraform-providers/terraform-provider-google#4579]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

0.11.11

### Overview

When a google sql database instance grows past `disk_size`, and a terraform plan is run, terraform attempts to delete the instance and recreate it at `disk_size`. 

### Affected Resource(s)

* [sql_database_instance](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html)

### Expected Behavior

Terraform should recognize the instance's disk_size is greater than what we provisioned (a feature provided by google, to auto-scale databases). No action should be taken. The plan should return a no-op. 

### Actual Behavior

The terraform plan marks the instance for deletion, and tries to recreate it with the original `disk_size`. 

### Steps to Reproduce

1. Create a sql_database_instance via TF and set an explicit `disk_size`. 
2. Use a load tool to add data to the DB, and make sure the size of the DB exceeds that of the original `disk_size`. 
3. Run a terraform plan and see that it tries to delete the instance and recreate it. 
=

**Comment by mdeggies** [comment]
Similar issue: https://github.com/terraform-providers/terraform-provider-google/issues/2498

**Comment by ndmckinley** [comment]
This issue is not easily resolvable in Terraform - terraform cannot tell the difference between an instance that has grown on the server-side and an instance that the user is explicitly attempting to resize down.  I highly recommend you set `lifecycle { prevent_destroy = true }` on your resources which represent irrecoverable data, and examine diffs closely.  Consider turning off `settings.disk_auto_resize`, as well.  I'll add a warning on the docs page.

**Comment by ndmckinley** [comment]
Added a warning in https://github.com/GoogleCloudPlatform/magic-modules/pull/2405.

**Comment by mdeggies** [comment]
Hmm OK, that makes sense. I added `lifecycle {  ignore_changes = ["settings[0].disk_size] }` for now (which unfortunately doesn't work with our old 0.11.11 tf version, so I'm upgrading that and the provider version as well). 

I'm curious though, if we don't set `disk_size`, will this behavior still occur? I assumed that by not setting `disk_size`, it would be set to the default, which is 10, and we'd run into this same issue once the DB exceeds 10gb. It seems like your MR is stating otherwise, so hoping you can confirm.

Thanks!

**Comment by ndmckinley** [comment]
If you don't set `disk_size`, Terraform won't see a diff between the value in state on refresh (since TF does a refresh before every plan) and the value in config (since there is no value in config).  I believe you should be able to remove `disk_size` from an existing resource without impact - please correct me if you see different behavior, but that is what I expect to happen.

**Comment by ndmckinley** [comment]
I'm going to go ahead and close this issue since I've added the warning to the docs - please reopen or comment if you have any further trouble.

**Comment by Chupaka** [comment]
> which unfortunately doesn't work with our old 0.11.11 tf version

`ignore_changes = ["settings.0.disk_size]` should work with TF 0.11, I believe...

**Comment by mdeggies** [comment]
Seems to have worked after removing `disk_size`, but did not work while `disk_size` was a parameter. Thanks all, we're unblocked now!
