### ISSUE TITLE
Using the "remote" backend leads to "could not find default credentials."

### ISSUE THREAD

**Issue by jlcheng** [terraform-providers/terraform-provider-google#4601]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform version: 0.12.9 

### Affected Resource(s)

* provider "google"

### Terraform Configuration Files

Version that does not work

```tf
provider "google" {
  project = "jcheng-learn-gcp"
  region = "us-west2"
}

resource "google_compute_instance" "default" {
  name         = "test"
  machine_type = "f1-micro"
  zone         = "us-west2-a"

  tags = ["experiment", "transient"]

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }

  network_interface {
    network = "default"

    access_config {
      // Ephemeral IP
    }
  }

  allow_stopping_for_update = "true"
  
  service_account {
    scopes = ["userinfo-email", "compute-ro", "storage-ro", "https://www.googleapis.com/auth/cloud-vision", "https://www.googleapis.com/auth/cloud-platform"]
  }  
}

terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "XXXXXX"

    workspaces {
      name = "yyy_zzzzz"
    }
  }
}

```

Version that does work
```tf
provider "google" {
  project = "jcheng-learn-gcp"
  region = "us-west2"
}

resource "google_compute_instance" "default" {
  name         = "test"
  machine_type = "f1-micro"
  zone         = "us-west2-a"

  tags = ["experiment", "transient"]

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }

  network_interface {
    network = "default"

    access_config {
      // Ephemeral IP
    }
  }

  allow_stopping_for_update = "true"
  
  service_account {
    scopes = ["userinfo-email", "compute-ro", "storage-ro", "https://www.googleapis.com/auth/cloud-vision", "https://www.googleapis.com/auth/cloud-platform"]
  }  
}
```

### Debug Output

https://gist.github.com/jlcheng/6e1023312ca321728d7cc8504a1d0c57

### Expected Behavior

When the remote backend is enabled, I'd still expect the GCP provider to find the necessary credentials via the `GOOGLE_CLOUD_KEYFILE_JSON` environment variable.

### Actual Behavior

When the remote backend is enabled, I can no longer specify the credential file using the three environment variables listed in the document:  GOOGLE_CLOUD_KEYFILE_JSON, GOOGLE_CREDENTIALS, and GCLOUD_KEYFILE_JSON.

As a work around, I can store the contents of the credentials file in the Terraform.io backend and reference it as Terraform variable.  

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

None

### References

None

**Comment by ndmckinley** [comment]
The issue here is that the remote backend does not have access to your local credentials.

```
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...
```

The error comes from your remote host.  You'll need to set that environment variable on that host.  This is a restriction of Terraform, not of our provider, unfortunately, so I'm going to go ahead and close this issue.  Please comment again if you need any further help - and consider opening or voting on a similar issue in Terraform core if this is inconvenient for you.

**Comment by jlcheng** [comment]
Thanks for the clarification. I'll discuss in the core group instead.
