### ISSUE TITLE
Support for Traffic Director Traffic Control in Beta Provider (UrlMap routeRules and routeActions)

### ISSUE THREAD

**Issue by bmenasha** [terraform-providers/terraform-provider-google#4604]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The ability to use automated provisioning tools with GCP APIs, even Beta APIs is important for users, it's why terraform exists. I'm working with terraform heavy company that is evaluating this traffic director feature  https://cloud.google.com/traffic-director/docs/traffic-control to support canary deployments. They wish to use either Terraform or the kubernetes config connector, both of which rely on magic modules supporting our beta apis.

### New or Affected Resource(s)

Support the new  routeRule/routeAction properties added to google_compute_url_map
https://cloud.google.com/compute/docs/reference/rest/beta/urlMaps/insert#body.request_body.FIELDS.inlinedField_117
 
Thanks!

**Comment by ndmckinley** [comment]
Work is underway!  :)

**Comment by vmarchaud** [comment]
@ndmckinley Do you have any news on that ?

**Comment by tysen** [comment]
The last PR for TD support is here: https://github.com/GoogleCloudPlatform/magic-modules/pull/2603
