### ISSUE TITLE
google_compute_resource_policy easy to misuse

### ISSUE THREAD

**Issue by cornmander** [terraform-providers/terraform-provider-google#4611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

The google_compute_resource_policy resource allows you to set an hourly schedule, in the format HH:MM. The MM is normalized to 00 on the server side, which leads to continuous diffs.

Example bad code:

```
resource "google_compute_resource_policy" "backups" {
  project  = var.project_id
  provider = "google-beta"
  name     = "backup-policy"
  region   = "us-west1"
  snapshot_schedule_policy {
    schedule {
      daily_schedule {
        days_in_cycle = 1
        start_time    = "04:17"
      }
    }
    retention_policy {
      max_retention_days    = 60
      on_source_disk_delete = "KEEP_AUTO_SNAPSHOTS"
    }
  }
}
```

Diff:
```
  # module.nethack-dev.google_compute_resource_policy.backups must be replaced
-/+ resource "google_compute_resource_policy" "backups" {
      ~ id        = "backup-policy" -> (known after apply)
        name      = "backup-policy"
        project   = "nethack-dev"
      ~ region    = "https://www.googleapis.com/compute/v1/projects/nethack-dev/regions/us-west1" -> "us-west1"
      ~ self_link = "https://www.googleapis.com/compute/v1/projects/nethack-dev/regions/us-west1/resourcePolicies/backup-policy" -> (known after apply)

      ~ snapshot_schedule_policy {
            retention_policy {
                max_retention_days    = 60
                on_source_disk_delete = "KEEP_AUTO_SNAPSHOTS"
            }

          ~ schedule {
              ~ daily_schedule {
                    days_in_cycle = 1
                  ~ start_time    = "04:00" -> "04:17" # forces replacement
                }
            }
        }
    }
```

**Comment by venkykuberan** [comment]
@cornmander sorry for the delay in response. Its a bug I will add it to our issue list and will get prioritized.
