### ISSUE TITLE
google_compute_region_backend_service failover parameter change isn't detected

### ISSUE THREAD

**Issue by kustodian** [terraform-providers/terraform-provider-google#4612]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.9
Google Provider 2.16.0

### Affected Resource(s)

* google_compute_region_backend_service

### Terraform Configuration Files

There is a problem with the `failover` parameter of `backend`. When the resource is created `failover` is set correctly on the backend, but if we want to change `failover` later on TF doesn't make any changes, it doesn't even report that there is anything to do.

Here is an example code below of the resource, where the second `failover` is set as a variable so that we can change it via command line:
```tf
resource "google_compute_region_backend_service" "backend" {
  provider = "google-beta"
  name     = "haproxy"

  backend {
    group = google_compute_instance_group.umig[0].self_link
    failover = false
  }

  backend {
    group = google_compute_instance_group.umig[1].self_link
    failover = var.failover
  }

  health_checks = [
    google_compute_health_check.haproxy_front_http.self_link,
  ]
}
```

### Expected Behavior

When we run TF the first time:
```
terraform apply -var=failover=false
```
This is reported:
```
  # google_compute_region_backend_service.backend will be created
  + resource "google_compute_region_backend_service" "backend" {
      + connection_draining_timeout_sec = 0
      + fingerprint                     = (known after apply)
      + health_checks                   = (known after apply)
      + id                              = (known after apply)
      + load_balancing_scheme           = "INTERNAL"
      + name                            = "haproxy"
      + project                         = (known after apply)
      + protocol                        = (known after apply)
      + region                          = (known after apply)
      + self_link                       = (known after apply)
      + session_affinity                = (known after apply)
      + timeout_sec                     = (known after apply)

      + backend {
          + failover = false
          + group    = (known after apply)
        }
      + backend {
          + failover = false
          + group    = (known after apply)
        }
    }
```
and in the GCP web console it's configured correctly.

### Actual Behavior

When we run TF the second time with `failover=true`:
```
terraform apply -var=failover=true
```
TF doesn't report any changes:
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
and it also doesn't make any changes in the GCP when we check the web console.

### Steps to Reproduce

Create a resource `google_compute_region_backend_service` with any backend's `failover` value set to something. Apply the changes, then change the `failover` to a different value and apply again. Nothing will change.

### Important Factoids

I tried it the other way around, setting `failover=true`, then setting it to `false`, but it's the same thing. The initial value was set on the creation of the resource stays.

**Comment by ndmckinley** [comment]
Do you have debug logs available?  This does seem like a bug - I'd like to see what's getting sent to the API, though, and constructing a terraform config that reproduces this issue will take a little while.  I'll get started on that, but if you have debug logs, that will make this a bit faster.

**Comment by ndmckinley** [comment]
Ah, okay, it's a problem with the hashing function.  Let me figure that out...

**Comment by ndmckinley** [comment]
This will be fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/2430.

**Comment by kustodian** [comment]
Thx for the fix. Can I help with merge somehow? To e.g. test it?

**Comment by ndmckinley** [comment]
I'm merging it right now!  There was a fire alarm test over here on Friday afternoon, and I had to drop everything real suddenly, sorry about that.
