### ISSUE TITLE
node_config.taint for google_container_cluster and google_container_node_pool should also be in GA provider

### ISSUE THREAD

**Issue by danpeachey** [terraform-providers/terraform-provider-google#4633]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

node_config.taint  is GA in GCP for both clusters and node_pools and should be supported in the GA provider.

https://cloud.google.com/kubernetes-engine/docs/how-to/node-taints

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by rileykarson** [comment]
Done in `2.19.0` with https://github.com/GoogleCloudPlatform/magic-modules/pull/2523
