### ISSUE TITLE
Add support to selecting N1 or N2 machine type when using custom machine types.

### ISSUE THREAD

**Issue by eddy-curv** [terraform-providers/terraform-provider-google#4650]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google introduced new machine types - N2 for predefined and custom machine types.
When creating a a compute instance or node pool for a K8S cluster which is using a custom machine type I want to be able to specify which machine type I would like.      

### New or Affected Resource(s)

* google_container_node_pool
* google_compute_instance

### Potential Terraform Configuration

```tf
node_config {
    machine_type = "n2-custom-8-10240"
    .....
```

### References

https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type#n2_custom_machine_types

**Comment by Chupaka** [comment]
So just specify it, what's the problem?

**Comment by Stono** [comment]
Hi, 
I believe his problem is simply that it doesn't work.

When specifying `n2-custom`, you end up with something like this:

```
Error: Error waiting for creating GKE NodePool: Google Compute Engine: The resource 'projects/at-delivery-platform-testing/zones/europe-west4-a/machineTypes/n2-custom-8-10240' was not found.
```

It appears as if terraform is looking for the machine type as it hasn't recognised that it is indeed, custom.

**Comment by Stono** [comment]
I would hold off making any changes to terraform to support this just yet, we have an open case with google about the partial support for n2 on gke and have fed back these api differences 

They’ve just replied saying the implementation is still under development and the eta for it to be “working” is the 11th November

**Comment by Stono** [comment]
Not really getting anywhere with google support to be honest, I think moving forward they're going to be sticking with:

n1 (as it is currently) you would do:
machine-type: custom-10-10240
min generation: Intel SkyLake

n2 you need to prefix the machine type:
machine-type: n2-custom-10-10240
min generation: Intel Cascade Lake

which breaks terraform:

```
Error: Error waiting for creating GKE NodePool: Google Compute Engine: The resource 'projects/at-delivery-platform-testing/zones/europe-west4-a/machineTypes/n2-custom-8-10240' was not found.
```

**Comment by Stono** [comment]
Hey @danawillow sorry to be tagging you directly but you've helped me out a lot historically :-)

**Comment by danawillow** [comment]
Hey @Stono, I'm not sure this is something we need to explicitly add (it should just work out of the box), but we can probably document how to do it. Does it work with gcloud, and if so, can you run the command with `--log-http` to see what the POST request getting sent to GKE looks like?

**Comment by Qvazar** [comment]
> Hey @Stono, I'm not sure this is something we need to explicitly add (it should just work out of the box), but we can probably document how to do it. Does it work with gcloud, and if so, can you run the command with `--log-http` to see what the POST request getting sent to GKE looks like?

Hi, I'm experiencing this exact same error.
I've attached a http log of the gcloud command: `gcloud compute instances create sj-n2-test --custom-vm-type=n2 --custom-cpu=4 --custom-memory=7168MB --zone=europe-west1-b --log-http`
[n2-instance-http-log.txt](https://github.com/terraform-providers/terraform-provider-google/files/4053533/n2-instance-http-log.txt)

The generated custom machine type is "n2-custom-4-7168". When this string is used in Terraform as a machine_type, it instead tries to find a standard machine type with that name.

**Comment by venkykuberan** [comment]
I am closing this issue as now i am able to create instances with custom type `n2-custom-8-10240`. Please reopen if you still face the issue.

**Comment by danawillow** [comment]
Given that @Qvazar's comment is from earlier today, I think that means they're still facing the issue :)

@Qvazar, do you have debug logs (https://www.terraform.io/docs/internals/debugging.html) from a run of Terraform that failed with that machine type?

**Comment by Qvazar** [comment]
> Given that @Qvazar's comment is from earlier today, I think that means they're still facing the issue :)
> 
> @Qvazar, do you have debug logs (https://www.terraform.io/docs/internals/debugging.html) from a run of Terraform that failed with that machine type?

Hi @danawillow,
Since @venkykuberan is able to create custom instances with type n2, I assume this is fixed in the newest TF release?
I'm still stuck on 0.11 for now, but upgrading is planned for the near future.

**Comment by eddy-curv** [comment]
When trying to create a node pool with N2 custom mcahine type (n2-custom-2-4096) using the following configuration:

Terraform v0.12.18
+ provider.google-beta v3.3.0

I get the following error:
` Error waiting for creating GKE NodePool: (1) Google Compute Engine: Not all instances running in IGM after 27.74815672s. Expect 1. Current errors: [UNSUPPORTED_OPERATION]: Instance 'gke-c4759v3-cluster-c4759v3-node-pool-94a01e28-f9bk' creation failed: Setting minimum CPU platform is not supported for the selected machine type e2-highcpu-2
`
