### ISSUE TITLE
google_cloud_run_domain_mapping is broken

### ISSUE THREAD

**Issue by chreble** [terraform-providers/terraform-provider-google#4651]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.8
+ provider.google.beta v2.17.0
```

### Affected Resource(s)

* google_cloud_run_domain_mapping

### Terraform Configuration Files

```
resource "google_cloud_run_domain_mapping" "domain_mapping" {
  location = "europe-west1"
  provider = "google-beta"
  name     = "mapping.foo.com"

  metadata {
    namespace = "google_project_id"
  }

  spec {
    route_name        = "mapping.foo.com"
    certificate_mode = "AUTOMATIC"
  }
}
```

### Debug Output

https://gist.github.com/chreble/5c0698fc0d03532a4e8bc16e45f78ef4

### Expected Behavior

Resource should be created or updated successfully.

### Actual Behavior

An error is returned

```
Error creating DomainMapping: googleapi: Error 400: The request has errors
```

### Steps to Reproduce

1. Define a `google_cloud_run_domain_mapping` resource
2. Run `terraform apply`

**Comment by rileykarson** [comment]
The `google_cloud_run_domain_mapping` resource and the `google_cloud_run_service` resource were written using the `v1alpha` API of Cloud Run, and domain mapping appears to have been pulled a few days ago, requests failing with `"Unsupported API version 'serving.knative.dev/v1alpha1'"` since.

I've followed up with the team to ensure that this was intended- it's unusual that one resource works while the other got listed as unsupported out of the blue.

A future provider release (hopefully the next) will bump to using the recently released `v1` API. However, as I understand, there may have been structural changes between versions and none of the maintainers have scoped them yet.

**Comment by rileykarson** [comment]
This is an issue with the inline `apiVersion` field on the API request, where we send `serving.knative.dev/v1alpha1`. That value worked previously, but validation has since been added and we need to send the correct value, `domains.cloudrun.com/v1alpha1`. PR out (above).

**Comment by kevlened** [comment]
I'm still seeing `Error creating DomainMapping: googleapi: Error 400: The request has errors` in  `v2.18.1`. Is autogeneration run for each release?

```terraform
resource "google_cloud_run_domain_mapping" "default" {
  location = "us-central1"
  provider = "google-beta"
  project = "some-google-project-id"
  name = "some-desired-domain-ending-in-dot"

  metadata {
    namespace = "some-google-project-id"
  }

  spec {
    route_name = "some-cloud-run-service-name"
  }
}
```

**Comment by rileykarson** [comment]
Yes. Can you file a new issue, including debug logs?

**Comment by kevlened** [comment]
From the logs, it appears `"some-desired-domain-ending-in-dot"` should just be `"some-desired-domain"`. The resource works as expected.
