### ISSUE TITLE
master_authorized_networks_config.cidr_blocks does not work

### ISSUE THREAD

**Issue by chriscowley** [terraform-providers/terraform-provider-google#4654]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

0.12.10 with GCP provider 2.17

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```
resource "google_container_cluster" "tools" {
  
  name                     = "tools"
  location                 = "${var.region}"
  remove_default_node_pool = true
  initial_node_count       = 1
  network                  = "${google_compute_network.services.name}"

  #subnetwork               = "${google_compute_subnetwork.services-europe-west1.name}"
  min_master_version = "${var.kube-version}"

  master_authorized_networks_config {
    cidr_blocks = [
      {
        display_name = "a network"
        cidr_block   = "8.8.8.8/32"
      },
      {
        display_name = "another"
        cidr_block   = "1.1.1.1/32"
      },
    ]
  }


  ip_allocation_policy {
    use_ip_aliases    = true
    create_subnetwork = true
  }
}
```

### Debug Output

https://gist.github.com/chriscowley/752e8b0d9a58f1876f67a6989b2401ee

### Expected Behavior

Create a GKE cluster with access to the masters limited to the specified networks

### Actual Behavior

Terraform fails with the output:

```
Error: Unsupported argument

  on gke.tf line 13, in resource "google_container_cluster" "tools":
  13:     cidr_blocks = [

An argument named "cidr_blocks" is not expected here. Did you mean to define a
block of type "cidr_blocks"?

make: *** [Makefile:8: plan] Error 1
```

### Steps to Reproduce

1. Use the above code
1. `terraform plan`

### Important Factoids

I was inadvertently using Terraform 0.11.<something> until this morning and it worked as expected, so it seems to be a regression.

### References

* #0000

**Comment by rileykarson** [comment]
Hey @chriscowley!

Terraform `0.11` enforced less restrictions on config than `0.12`, and this is one of those restrictions. By default, `field = [ {item}, ]` syntax for blocks is no longer supported and blocks all need to be expressed in `field { }` format.

```
  cidr_blocks = [
      {
        display_name = "a network"
        cidr_block   = "8.8.8.8/32"
      },
      {
        display_name = "another"
        cidr_block   = "1.1.1.1/32"
      },
    ]
```


should be expressed as

```
cidr_blocks {
  display_name = "a network"
  cidr_block   = "8.8.8.8/32"
}

cidr_blocks {
  display_name = "another"
  cidr_block   = "1.1.1.1/32"
}

```
