### ISSUE TITLE
Creating a GKE cluster without an ephemeral external IP

### ISSUE THREAD

**Issue by marcb1** [terraform-providers/terraform-provider-google#4675]
We use google cloud NAT + firewall rules for external traffic in google cloud. Hence, our instances are not set-up with an external IP, so traffic is routed via cloud NAT.

I don't see any option to create `google_container_node_pool` with only internal IP addresses.
When created via terraform, the instance template for the node pool uses ephemeral external IPs.
Is there a way around this?

**Comment by slevenick** [comment]
The `google_container_cluster` resource has a block `private_cluster_config` this field: https://www.terraform.io/docs/providers/google/r/container_cluster.html#enable_private_nodes

Does setting that remove the external IP on the node pool instances?

**Comment by marcb1** [comment]
yep that worked 👍
