### ISSUE TITLE
Unable to use provider within official Terraform Docker image

### ISSUE THREAD

**Issue by remmeier** [terraform-providers/terraform-provider-google#4677]
for some reason

### Terraform Version

Terraform v0.12.10
+ provider.google v2.17.0
+ provider.kubernetes v1.9.0
+ provider.random v2.2.1

### Affected Resource(s)

e.g. 

```
resource "kubernetes_secret" "..." 
```

### Terraform Configuration Files

```


resource "google_container_cluster" "primary" {
  name                     = var.cluster_name
  location                 = var.location
  remove_default_node_pool = true
  min_master_version       = "1.13.7-gke.24"
  logging_service          = "none"

  initial_node_count = "1"
}

resource "google_container_node_pool" "primary_pool" {
    name          = "primary-pool"
    project       = var.project
    location      = var.location
    cluster       = "${google_container_cluster.primary.name}"
    version       = "1.13.7-gke.24"

    initial_node_count = "1"

    autoscaling {
        min_node_count = 1
        max_node_count = 5
    }

    management {
        auto_repair  = true
        auto_upgrade = false
    }

    node_config {
        image_type   = "COS"
        machine_type = var.gke_node_size

        labels = {
            private-pools-example = "true"
        }

        disk_size_gb = "30"
        disk_type    = "pd-standard"
        preemptible  = false

        # TODO service_account = module.gke_service_account.email
    }
}


resource "kubernetes_secret" "adminSecret" {
  metadata {
    namespace = "kube-system"
    name = "database-admin-secrets"
  }

  data = {
    DATASOURCE_ADMIN_USERNAME: "test"
  }

  type = "Opaque"
}
```

### Debug Output

```
Error: Get https://.../api/v1/namespaces/kube-system/secrets/database-admin-secrets: error executing access token command "/usr/lib/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /usr/lib/google-cloud-sdk/bin/gcloud: no such file or drectory output= stderr=
```

### Expected Behavior

When creating Kubernetes resources after the cluster has been setup, I would expect this to work smoothly. 

### Actual Behavior

Unfortunately when making use of the Terraform Docker image it attempts to execute:

```/usr/lib/google-cloud-sdk/bin/gcloud```

which is not installed. There is no more detailed feedback or what kind of configuration may should change. Since we make use of the official  Terraform Docker image, there is no gcloud command installed and I assume the gcloud provider does not bring one along on its own. We would expect this to work. We make use of the Docker image for exactly this reason, have a stable self-contained setup for terraform (and other tools) so that they do not interfere with each other.

### Steps to Reproduce

make use of the Docker image with any kind of GKE-based image, e.g. with run it with:

`docker run -i --rm -e HOME=/workdir/build/home -v C:/demo/demo-deployment:/workdir -v C:/demo/demo-deployment/build/.terraformCache:/.terraform -e IF_LOG=DEBUG --workdir /workdir/src/main/terraform hashicorp/terraform:0.12.10 terraform apply /workdir/src/main/terraform`

**Comment by slevenick** [comment]
This looks like an issue with the Kubernetes plugin for terraform. I don't believe we use gcloud within the google provider at all.

This repo is specifically for the google provider, I would file an issue over on the Kubernetes provider repo: https://github.com/terraform-providers/terraform-provider-kubernetes
