### ISSUE TITLE
Published documentation for google_compute_subnetwork doesn't reflect this repo

### ISSUE THREAD

**Issue by jamiekt** [terraform-providers/terraform-provider-google#4682]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_subnetwork

### Expected Behavior

Documentation at https://www.terraform.io/docs/providers/google/d/datasource_compute_subnetwork.html should reflect this repo

### Actual Behavior

The doc at https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/r/compute_subnetwork.html.markdown is not the same as what is at https://www.terraform.io/docs/providers/google/d/datasource_compute_subnetwork.html. For example, check the published site and you will see that `private_ip_google_access` is listed as an attribute where the repo states that it is an argument (which is true). The published documentation is incorrect even though the documentation source is correct.

**Comment by slevenick** [comment]
The doc at https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/r/compute_subnetwork.html.markdown represents the `google_compute_subnetwork` resource, while the linked doc on the terraform site is for the datasource. For more information on resources vs datasources see https://www.terraform.io/docs/configuration/data-sources.html

I don't see an issue in this case, and I believe `private_ip_google_address` should be an attribute for the datasource. If I have missed something feel free to reopen this

**Comment by jamiekt** [comment]
OK, I'm suitably embarrassed about that. Apologies for having wasted your time @slevenick
