### ISSUE TITLE
Swapping from "google_project_services" to "google_project_service" causes API rate limiting error

### ISSUE THREAD

**Issue by yinzara** [terraform-providers/terraform-provider-google#4689]
When a project has numerous services enabled, using the "google_project_service" resource causes multiple API requests during a refresh which can often go over the API limits.   By using the "google_project_services" resource, this is limited to a single API call.  I was only able to fix issues with my project by swapping to using the now deprecated "google_project_services". I believe this deprecation needs to be revisited.

**Comment by rileykarson** [comment]
Are you using a recent version of the provider? `2.13.0` and onwards support [Batching](https://www.terraform.io/docs/providers/google/provider_reference.html#batching)]  which should cause multiple `google_project_service` resources to send a single request.

Debug logs would be a big help, if batching isn't working for some reason.

**Comment by yinzara** [comment]
That does seem to have fixed my issue. I appreciate it. Didn't realize that was added.

**Comment by rileykarson** [comment]
Great! I'm going to use this issue to track updating some of the deprecation warnings to note that users should upgrade to `2.13.0+`.
