### ISSUE TITLE
Problem about field `peer_ip_address` in resource `google_compute_router_peer`

### ISSUE THREAD

**Issue by maqiuyujoyce** [terraform-providers/terraform-provider-google#4692]
Field `peer_ip_address` in resource `google_compute_router_peer` is marked as "Required" in the [doc](https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/r/compute_router_peer.html.markdown#argument-reference), however, it is "Optional" in the [schema](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_router_peer.go#L41). This happens in both GA and [Beta](https://github.com/terraform-providers/terraform-provider-google-beta/blob/master/google-beta/resource_compute_router_peer.go#L41). It is pretty confusing and I'm not sure which one I should follow. Could you fix it?

**Comment by slevenick** [comment]
I *believe* it should be required, but I don't know enough about bgp peers to answer definitively.

Is there a reason you would want to create one without a `peer_ip_address`?

**Comment by maqiuyujoyce** [comment]
I agree that it should be required and I don't want to create one without a `peer_ip_address`. But the schema said it is optional so this required field cannot be enforced in the config. That's why I wondered if it is a bug and if it can be fixed.

**Comment by slevenick** [comment]
Yes, it should be required. We are reworking this resource at the moment, and the new version will have the field correctly marked as required.

**Comment by selslack** [comment]
@slevenick can you please clarify why `ip_address` field of `google_compute_router_peer` is read-only?

It's editable in the API (I guess, it's `bgpPeers[].ipAddress`) and in the Cloud Console.

If it's a mistake, can you please fix it as well?

**Comment by slevenick** [comment]
I don't believe it is editable because it is assigned when the peer is created. The gcloud command doesn't allow you to specify the ip_address field either: https://cloud.google.com/sdk/gcloud/reference/compute/routers/add-bgp-peer

Why do you want to be able to set this field?

**Comment by selslack** [comment]
@slevenick it's definitely editable here: 
<img width="459" alt="Screen Shot 2019-12-02 at 9 42 26 PM" src="https://user-images.githubusercontent.com/4094244/69997757-c11fb580-154c-11ea-8f72-e3349b79606d.png">.

I'm setting up Site-to-Site VPN with AWS, the default value provided by GCP is not correct in that case (it's the first address in the subnet).

**Comment by slevenick** [comment]
I'm not very familiar with that field, and I think it is a separate issue from this one. Feel free to file a request for enhancement to make the `ip_address` field editable, it should be much easier now that we are generating the BgpPeer resource
