### ISSUE TITLE
Support new GKE maintenance window fields ("enhanced maintenance windows")

### ISSUE THREAD

**Issue by KatrinaHoffert** [terraform-providers/terraform-provider-google#4697]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GKE maintenance windows have been extended with new fields for specifying much more versatile maintenance windows (or exclusions to when maintenance should occur). These fields should be supported by Terraform. Some of this integration is presumably on MagicModules (filed https://github.com/GoogleCloudPlatform/magic-modules/issues/2486 for that), but recording this issue here as Terraform integration is the focus and presumably will need changes in this provider as well.

### New or Affected Resource(s)

**All new fields are currently beta only.**

[`MaintenancePolicy`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.MaintenancePolicy) message now has the following new fields:

* `resourceVersion`: An etag for ensuring consistency of updates. Always set (this field being set was the cause of #4010).
* `window.recurringWindow`: A [`RecurringTimeWindow`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.RecurringTimeWindow) that represents a window of time and an associated RRULE defining how it recurs. Mutually exclusive with the existing `window.dailyMaintenanceWindow` (note that the `recurringWindow` can represent all possible `dailyMaintenanceWindow`s -- we may deprecate those at a future time).
* `window.maintenanceExclusions`: A dictionary mapping string names to [`TimeWindow`s](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.TimeWindow) when maintenance should not occur.

Either the [`update`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters/update) or [`setMaintenancePolicy`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters/setMaintenancePolicy) method may be used for setting the above features.

The `resourceVersion` is **required** if `window.recurringWindow` or `window.maintenanceExclusions` are set and is also enforced if provided anyway. Note the impact of this in that if a cluster sets a maintenance policy with the new features outside of Terraform, attempts to update within Terraform will currently fail as it does not set the `resourceVersion` (which can be obtained by getting the current cluster). This also means that the GA API cannot currently be used to change the maintenance policy when those fields are set (workaround: remove the fields first via `gcloud beta container clusters [CLUSTER_NAME]` with `--clear-maintenance-window`/`--remove-maintenance-exclusion`).

### References

* magic-modules issue: https://github.com/GoogleCloudPlatform/magic-modules/issues/2486
* API definitions: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.MaintenancePolicy
* Overview on maintenance windows: https://cloud.google.com/kubernetes-engine/docs/concepts/maintenance-windows-and-exclusions
* How to configure maintenance windows and exclusions in gcloud and cloud console: https://cloud.google.com/kubernetes-engine/docs/how-to/maintenance-windows-and-exclusions
* Important caveats for UX: https://cloud.google.com/kubernetes-engine/docs/concepts/maintenance-windows-and-exclusions#caveats_for_maintenance_windows

**Comment by jphilaine** [comment]
Yesterday, I had an error with this feature.

I changed maintenance windows into GKE console. After that I was blocked by Terraform to make any changes into `maintenance_policy` block. I have this following error:
```
Error: googleapi: Error 400: Patch request's maintenancePolicy.resourceVersion  is not equal to the current maintenancePolicy.resourceVersion cff707a4. The patch request's maintenance policy may not contain the most recent values., badRequest
```

To bypass this error, I need to comment `maintenance_policy` block. In this case Terraform doesn't see any change despite the fact that a maintenance is configured.

**Comment by chrisst** [comment]
linking related issue: https://github.com/terraform-providers/terraform-provider-google/issues/4710

**Comment by ndmckinley** [comment]
Hi there!

https://github.com/googleapis/google-api-go-client/blob/master/container/v1/container-gen.go#L1273 doesn't yet include those fields.  I'll see if I can find who's responsible for updating that library and get that done.

**Comment by ndmckinley** [comment]
Okay, it's more complicated than I thought at first glance.  We need to

a) support the existing behavior in the ga provider (for now).
b) support the new behavior in the beta provider.
c) support migrating freely between the new and old behavior in the beta provider.
d) support the downgrade case in the ga provider, for instance if the user has hit the button in the cloud console to upgrade to the new provider (as @jphilaine has).
e) publish a mitigation for users in @jphilaine's situation.  That mitigation is as @KatrinaHoffert listed, `gcloud beta container clusters $CLUSTER --clear-maintenance-window --remove-maintenance-exclusion`.

I'll get on that.

**Comment by inductor** [comment]
I'd like this feature too!
Especially GKE can be upgraded very unexpectedly like this https://twitter.com/mareksuscak/status/1192053133989629952

It will be great if we can control this in a better way

**Comment by ndmckinley** [comment]
It's in `2.20.0`, released yesterday.  :)

**Comment by inductor** [comment]
@ndmckinley Thanks. Can it be in the release note? It seems not at the point.

**Comment by ndmckinley** [comment]
Ah, I was mistaken, it's in `2.19.0`.  https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#2190-november-05-2019
