### ISSUE TITLE
Org Level Functionality of "google_project_iam_audit_config" resource

### ISSUE THREAD

**Issue by angelchang** [terraform-providers/terraform-provider-google#4698]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be useful to have org level functionality of the google_project_iam_policy resource. 

It would give the IAM policy to a user at the org level. A dangerous tool but provides more automation for projects fully managed by Terraform.
### New or Affected Resource(s)

```
resource "google_organization_iam_audit_config" "organization" {
  organization= "your-organization-id"
  service = "allServices"
  audit_log_config {
    log_type = "DATA_READ"
    exempted_members = [
      "user:joebloggs@hashicorp.com",
    ]
  }
}
```

**Comment by umairidris** [comment]
I can take a stab at implementing this.

**Comment by xingao267** [comment]
Triaged with Umair, I'm currently working on this.

**Comment by xingao267** [comment]
This is fixed by https://github.com/terraform-providers/terraform-provider-google/pull/4977
