### ISSUE TITLE
google_bigtable_instance schema change causes refresh to fail

### ISSUE THREAD

**Issue by nickmoorman** [terraform-providers/terraform-provider-google#4701]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.14 (also v0.12.9)
+ provider.google-beta v2.14.0 (and up)
```

### Affected Resource(s)

* `google_bigtable_instance`

### Terraform Configuration Files

Relevant resource:
```tf
resource "google_bigtable_instance" "test_instance" {
  name = "test-instance"

  cluster {
    cluster_id   = "cluster1"
    zone         = "us-central1-a"
    num_nodes    = 3
    storage_type = "SSD"
  }
}
```

### Debug Output

Debug log from above: https://gist.github.com/nickmoorman/de60a218fcdb200baff333163d4c37e3#file-01-terraform-plan-debug-log

### Panic Output

Interestingly, the explicit crash (with the `...!!! TERRAFORM CRASH !!!...` output) only happens when the `--target` argument is passed to only refresh the `google_bigtable_instance` resource, in which case similar output to above is shown with the more informative error `panic: interface conversion: interface {} is nil, not map[string]interface {}` and the trace to go with it.  Full `crash.log` can be found [here](https://gist.github.com/nickmoorman/de60a218fcdb200baff333163d4c37e3#file-02-terraform-plan-target-crash-log).

### Expected Behavior

`terraform plan` should show that there are no changes when nothing has changed.

### Actual Behavior

Terraform errors (or outright crashes if the `--target` argument is passed to `terraform plan`) on arbitrary resources due to a crash in a plugin goroutine.

### Steps to Reproduce

1. Create a `google_bigtable_instance` resource with version 2.13.0 or earlier of the `google` provider (note: must be done with Terraform 0.11!)
2. Upgrade the provider to 2.14.0 or higher
3. Run `terraform plan`
4. Observe errors

### References

* #4026

**Comment by nickmoorman** [comment]
Some additional info I wanted to share that didn't quite fit into the issue template...  This came about when I tried to upgrade to version 2.14.0 or later of this plugin to make use of the change from #4026.  Unfortunately, changing `cluster` from `TypeSet` to `TypeList` _did_ result in backwards-incompatible changes, but not for the reason expected (as raised [here](https://github.com/terraform-providers/terraform-provider-google/pull/4026#issuecomment-511461114)).  In short, due to the way Terraform serializes `TypeSet` vs. `TypeList` in the state file's flat attribute map, the plugin is not able to identify clusters in the state in version 2.14.0 and up, resulting in a panic: `interface conversion: interface {} is nil, not map[string]interface {}`.  See sample states below for a concrete illustration of the issue:

```
# When resource was created with v2.13.0, when `cluster` was a `TypeSet`
$ terraform state pull | jq '.modules[0].resources."google_bigtable_instance.test_instance"'
{
  "type": "google_bigtable_instance",
  "depends_on": [],
  "primary": {
    "id": "test-instance",
    "attributes": {
      "cluster.#": "1",
      "cluster.3909609229.cluster_id": "cluster1",
      "cluster.3909609229.num_nodes": "3",
      "cluster.3909609229.storage_type": "SSD",
      "cluster.3909609229.zone": "us-central1-a",
      "display_name": "test-instance",
      "id": "test-instance",
      "instance_type": "PRODUCTION",
      "name": "test-instance",
      "project": "<REDACTED>"
    },
    "meta": {},
    "tainted": false
  },
  "deposed": [],
  "provider": "provider.google"
}

# When resource was created with v2.14.0, when `cluster` was a `TypeList`
$ terraform state pull | jq '.modules[0].resources."google_bigtable_instance.test_instance"'
{
  "type": "google_bigtable_instance",
  "depends_on": [],
  "primary": {
    "id": "test-instance",
    "attributes": {
      "cluster.#": "1",
      "cluster.0.cluster_id": "cluster1",
      "cluster.0.num_nodes": "3",
      "cluster.0.storage_type": "SSD",
      "cluster.0.zone": "us-central1-a",
      "display_name": "test-instance",
      "id": "test-instance",
      "instance_type": "PRODUCTION",
      "name": "test-instance",
      "project": "<REDACTED>"
    },
    "meta": {},
    "tainted": false
  },
  "deposed": [],
  "provider": "provider.google"
}
```

I have a fix for this (PR incoming), but wanted to document this in an issue first.

cc @rileykarson @mackenziestarr

**Comment by rileykarson** [comment]
Can you check whether `2.17.0` resolves the issue for you? I believe I know why this happened, and why I thought it was a compatible change.

Normally, changing from a List <-> a Set is a safe change in terms of state (but not behaviour! List -> Set breaks interpolations, and Set -> List means ordering matters) because the provider doesn't rely on state to perform a refresh. In Bigtable, it did, because `StorageType` wasn't exposed by the client library we use.

Terraform 0.11 and Terraform 0.12 are _supposed_ to behave identically (barring config language changes and a couple other minor things), but that isn't always the case. It turns out that 0.12 (which our test gauntlet uses / I'd tested with locally) allows us to read a Set's values in state as a List safely. 0.11 doesn't.

As a requirement for https://github.com/GoogleCloudPlatform/magic-modules/pull/2409, I patched in `StorageType` on read to the client library. That allowed me to remove read of the prior state from Read. That change was released in `2.17.0`, and I believe that `2.13.0` (or prior) -> `2.17.0` will be a safe upgrade. It works locally for me, using Terraform 0.11.14 and TPG `2.13.0` -> `2.17.0`.

**Comment by nickmoorman** [comment]
Hi Riley.  Sorry for the delayed response.  Looks like `2.17.0` does indeed resolve this issue (yay!).

**Comment by rileykarson** [comment]
Great! I'll add a note on `2.13.0` in the changelogs to try `2.17.0` if this issue is encountered.
