### ISSUE TITLE
TCP health check with named port doesn't work as expected

### ISSUE THREAD

**Issue by ilicmilan** [terraform-providers/terraform-provider-google#4706]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

### Terraform Version
Terraform v0.12.10

### Affected Resource(s)
* google_compute_health_check

### Terraform Configuration Files

```tf
resource "google_compute_backend_service" "app_tcp" {
  name      = "test-lb-tcp"
  port_name = "tcp"
  protocol  = "TCP"

  backend {
    group = google_compute_instance_group.app.self_link
  }
  
  health_checks = [
    google_compute_health_check.app_tcp.self_link
  ]
}

resource "google_compute_instance_group" "app" {
  name        = "test-lb-umig-01"
  zone        = "europe-west1-b"

  instances = [
    module.app.instances[0].self_link
  ]

  named_port {
    name = "tcp"
    port = "5222"
  }
}

# Healthcheck ####################################################

resource "google_compute_health_check" "app_tcp" {
  name = "test-lb-tcp"

  tcp_health_check {
    port_name = "tcp"
    # port_specification = "USE_NAMED_PORT"
  }
}

module "app" {
  source       = "../../instance"
  name         = "app"
  machine_type = "f1-micro"
}
```
### Expected Behavior

As stated in TF doc and Google API doc:
```
port_name - (Optional) Port name as defined in InstanceGroup#NamedPort#name. If both port and port_name are defined, port takes precedence.
```
I expected that port `5222` defined in `google_compute_instance_group.app` will be used for health checking.

### Actual Behavior

In the example above `port` is not explicitly set but since the default value is 80, this health check ignores defined `port_name` in InstanceGroup and uses port `80` anyway.
I've found a workaround by setting `port_specification = "USE_NAMED_PORT"`.
But again, looking at the `port_specification` section
```
port_specification:
USE_FIXED_PORT: The port number in port is used for health checking.
...
USE_SERVING_PORT: For NetworkEndpointGroup, the port specified for each network endpoint is used for health checking. For other backends, the port or named port specified in the Backend Service is used for health checking. If not specified, HTTP health check follows behavior specified in port and portName fields.
```
having these two options (`USE_FIXED_PORT` and `USE_SERVING_PORT`) doesn't make sense since `port` will always be defined (as it is 80 by default) and it will always take precedence.

In my opinion, setting `port_name` should implicitly apply `port_specification = "USE_NAMED_PORT"` or you should enrich `port_name` section with some note that it's necessary to set `port_specification` when using `port_name`.

**Comment by slevenick** [comment]
It looks like when checking out the code in this case that we imply that not specifying a `port_specification` is the same as specifying `USE_FIXED_PORT`, in that we default the port in both of those cases. [As seen here](https://github.com/terraform-providers/terraform-provider-google/blob/7ba8fef5fc0e41b9442a263d2c7716a51ef1dc20/google/resource_compute_health_check.go#L1574)

I'll add a note on this to the documentation

**Comment by ilicmilan** [comment]
What do you think about the idea that we imply `port_specification: USE_NAMED_PORT` when using `port_name`, of course, if `port_specification` is not specified?

**Comment by slevenick** [comment]
Ended up not setting the default port if `port_name` is specified.
