### ISSUE TITLE
Add maintenance-window-end to GKE cluster

### ISSUE THREAD

**Issue by Philmod** [terraform-providers/terraform-provider-google#4710]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In GKE, one can [define](https://cloud.google.com/kubernetes-engine/docs/how-to/maintenance-windows-and-exclusions#maintenance-window) the maintenance window, with its start, end and recurrence. It seems like the `end_time` is not supported in Terraform.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
maintenance_policy {
  daily_maintenance_window {
    start_time = "18:00"
    end_time = "20:00"
  }
}
```

**Comment by ndmckinley** [comment]
This requires a revendor of the container library, since this doesn't exist in that library at the point where we are, but I'll get on that.

**Comment by ndmckinley** [comment]
Reposting here from linked issue: https://github.com/terraform-providers/terraform-provider-google/issues/4697#issuecomment-545171155

**Comment by ndmckinley** [comment]
Going to close this one in favor of that issue - it's more complicated than I thought at first glance.
