### ISSUE TITLE
Cloud function returns 403 error on 'locations/us-west2'

### ISSUE THREAD

**Issue by HebertCL** [terraform-providers/terraform-provider-google#4714]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

## Description

While troubleshooting issue described in #4712 I found that when I try to provision an isolated cloud function I am getting the following 403 error:

```
google_cloudfunctions_function.function: Creating...

Error: googleapi: Error 403: Permission denied on 'locations/us-west2' (or it may not exist), forbidden

  on main.tf line 18, in resource "google_cloudfunctions_function" "function":
  18: resource "google_cloudfunctions_function" "function" {
```

Initially I realized that `trigger_topic` config was deprecated and needed to use `event_trigger` block. I use PubSub as function trigger, and came up with the following configuration:

```hcl
resource "google_cloudfunctions_function" "gcp_function" {
  name                  = "tf-grumman"
  runtime               = "nodejs8"
  available_memory_mb   = 512
  source_archive_bucket = var.gcp_function_source_bucket
  source_archive_object = var.gcp_function_source_archive
  
  event_trigger {
    event_type = "google.pubsub.topic.publish"
    resource = var.gcp_function_resource
  }
}
```
However, I got the 403 error described above. This error remains constant even using the configuration provided in the documentation [example](https://www.terraform.io/docs/providers/google/r/cloudfunctions_function.html). After several attempts I decided to change location from `us-west2` to `us-central1` and error went away. I've seen similar issues with us-west2 I will link below.

### Terraform Version

`Terraform v0.12.11`
`Terraform v0.12.9`

### Affected Resource(s)

`google_cloudfunctions_function.function`

### Terraform Configuration Files

```tf
terraform {
  required_version  = ">=0.12.9"
}

provider "google" {
  credentials = file("var.gcp_keys")
  project     = var.gcp_project
  region      = "us-west2"
}

provider "google-beta" {
  credentials = file("var.gcp_keys")
  project     = var.gcp_project
  region      = "us-west2"
}

resource "google_cloudfunctions_function" "gcp_function" {
  name                  = "tf-grumman"
  runtime               = "nodejs8"
  available_memory_mb   = 512
  source_archive_bucket = var.gcp_function_source_bucket
  source_archive_object = var.gcp_function_source_archive
  
  event_trigger {
    event_type = "google.pubsub.topic.publish"
    resource = var.gcp_function_resource
  }
}
```

### Expected Behavior

Terraform is able to create cloud function in `us-west2`

### Actual Behavior

Terraform throws 403 error using this region.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

* #1869

**Comment by slevenick** [comment]
Unfortunately cloud functions are not available in certain regions, including `us-west2`. A list of available regions can be found here: https://cloud.google.com/functions/docs/locations

**Comment by HebertCL** [comment]
Should have stopped and read the docs. Thanks for the reference!
