### ISSUE TITLE
cloudbuild_trigger: Request contains an invalid argument. (400)

### ISSUE THREAD

**Issue by petomalina** [terraform-providers/terraform-provider-google#4718]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.10
+ provider.google v2.17.0
+ provider.google-beta v2.17.0
+ provider.null v2.1.2
```

### Affected Resource(s)

* google_cloudbuild_trigger

### Terraform Configuration Files

```tf
resource "google_cloudbuild_trigger" "build-prod" {

  description = "Build prod"
  project     = "flowup-stage-dev2"

  trigger_template {
    repo_name = "test-repo"
  }

  build {
    step {
      name       = "ubuntu"
      entrypoint = "/bin/sh"
      args       = ["echo", "hello world"]
    }
  }
}
```

### Debug Output

Request generated by Terraform:

```
2019/10/20 14:58:19 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
POST /v1/projects/<my-project>/triggers?alt=json HTTP/1.1
Host: cloudbuild.googleapis.com
User-Agent: HashiCorp Terraform/0.12.10 (+https://www.terraform.io) Terraform Plugin SDK/1.0.0 terraform-provider-google/2.17.0
Content-Length: 163
Content-Type: application/json
Accept-Encoding: gzip

{
 "build": {
  "steps": [
   {
    "args": [
     "echo",
     "hello world"
    ],
    "entrypoint": "/bin/sh",
    "name": "ubuntu"
   }
  ]
 },
 "description": "Build prod",
 "triggerTemplate": {
  "repoName": "test-repo"
 }
}
```

GAPI response:
```
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
```

### Expected Behavior

A trigger should have been created.

### Actual Behavior

An error occurs.

### Steps to Reproduce

1. copy the resource
2. apply it, the plan will run fine
3. applying the plan produces the above error

* #0000

**Comment by ndmckinley** [comment]
Yep, that's a correct error to receive.  This is an incorrect config - one of `trigger_template.branch_name` and `trigger_template.tag_name` is required.  It says in the docs for those fields:
>Name of the branch to build. Exactly one a of branch name, tag, or commit SHA must be provided.

**Comment by ndmckinley** [comment]
FWIW: it's an easy mistake to make!  If this sort of thing happens to you a lot, I'd file an issue in Terraform Core to ask them to make it possible to express "exactly one of these fields is required" - right now that can't really be done outside of custom code.

**Comment by ndmckinley** [comment]
Super, super reasonable assumption - do you think we should set a default there?

**Comment by petomalina** [comment]
@ndmckinley setting a default value to `.*` would be a very UX friendly move from my point of view. I tend first to try things in the UI (where this value is pre-populated by `.*`).

A note that both `branch_name` and `tag_name` are regexes would also be beneficial in the docs.

**Comment by ndmckinley** [comment]
Hm, I can't see any Terraform support for default values (set to `.*` unless a _different_ field is set).  That'd have to be implemented in a fairly complex way - I suppose we'll have to leave it this way for now.  The docs, though, that I can do.
