### ISSUE TITLE
Add description to google_service_account resource

### ISSUE THREAD

**Issue by mykter** [terraform-providers/terraform-provider-google#4719]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Service accounts have a [description ](https://cloud.google.com/iam/docs/creating-managing-service-accounts#iam-service-accounts-create-rest) field, but terraform currently only supports the name and display name.

### New or Affected Resource(s)

* google_service_account

### Potential Terraform Configuration

```tf
resource "google_service_account" "terraform-read" {
  account_id   = "terraform-read"
  display_name = "Terraform read only service account"
  description = "Allows terraform plan to run in CICD unprotected branches"
}
```

**Comment by paddycarver** [comment]
This looks like it was resolved in https://github.com/terraform-providers/terraform-provider-google/pull/4734.
