### ISSUE TITLE
google_pubsub_subscription.expiration_policy cannot set 'never'

### ISSUE THREAD

**Issue by jimmy-ho** [terraform-providers/terraform-provider-google#4737]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.14

### Affected Resource(s)

* google_pubsub_subscription

### Terraform Configuration Files

```
data "terraform_remote_state" "amlg-transcript-topic" {
  backend = "gcs"

  config {
    bucket      = "cbsi-${var.project}-tfstate"
    prefix      = "gcp/${var.project}/pubsub/amlg-transcript/topic"
    credentials = "~/.gcloud/${var.project}-default_service_account.json"
  }
}

resource "google_pubsub_subscription" "amlg-transcript" {
  project = "${var.project}"
  name    = "${var.name}"
  topic   = "${data.terraform_remote_state.amlg-transcript-topic.name}"

  # Cannot be more than 7 days (604800) or less than 10 minutes (600)
  message_retention_duration = "${var.message_retention_duration}s"
  retain_acked_messages      = "${var.retain_acked_messages}"

  ack_deadline_seconds = "${var.ack_deadline_seconds}"

  expiration_policy {
  }

  timeouts {
    create = "${var.create_timeout}"
    update = "${var.update_timeout}"
    delete = "${var.delete_timeout}"
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Expected the subscription to be set to `never` for expiring, it appears one can do this with gcloud at the moment.

```
gcloud pubsub subscriptions update [SUBSCRIPTION_NAME] --expiration-period=never
```

### Actual Behavior

A default of 31 days is applied, which from the documentation seems like it is expected behaviour... however, it would be nice to be able to set **never** by not supplying a ttl - or allowing **never** to be an acceptable value.

It does look like the documentation (https://www.terraform.io/docs/providers/google/r/pubsub_subscription.html) is quite conflicting, unless I am doing something odd.

Under **expiration_policy**:
```
If expirationPolicy is not set, a default policy with ttl of 31 days will be used
```

However for the **ttl** below:
```
If ttl is not set, the associated resource never expires
```

So the documentation probably needs updating, or the behaviour needs to change.

### Steps to Reproduce

1. `terraform apply`

### References

N/A

**Comment by ndmckinley** [comment]
The docs are incorrect, setting expiration policy to `{}` produces a never-expire result in TPG 2.17.

```
resource "google_pubsub_subscription" "sub" {
  name    = "test-ps"
  topic   = "${google_pubsub_topic.topic.name}"

  message_retention_duration = "600s"

  expiration_policy {
  }
}
```

produces, in the cloud console:
![image](https://user-images.githubusercontent.com/605324/67530408-da8f3100-f673-11e9-8a82-3702b3e56534.png)

I'm modifying the docs.
