### ISSUE TITLE
google_container_cluster fields recreate the cluster unnecesarily

### ISSUE THREAD

**Issue by paddycarver** [terraform-providers/terraform-provider-google#474]
It should be possible to update, e.g., the `node_pool` field on `google_container_cluster` without tearing down the cluster and recreating it. However, at the moment, Terraform requires the cluster to be destroyed and recreated in order to make changes to many of the fields.

**Comment by paddycarver** [comment]
When `google_container_cluster` was created, the API didn't support updating most (or all, I forget) of its fields. Now the API has progressed, but the resource hasn't been updated to support the new functionality. I think for a lot of this, it's just a matter of updating the resource to do the update API call and marking the fields as `ForceNew: false`.

**Comment by davidquarles** [comment]
Realistically, this behavior (specifically: when mutating `google_container_cluster.node_pool`) is the main deal-breaker for us (with IP Aliases as a close second), and I'd really like to use terraform to keep our tooling consistent with cluster provisioning on the AWS side.  If you'd like help, I have bandwidth to do so this week.

**Comment by danawillow** [comment]
@davidquarles happy to have help! Just let me know which ones you're planning on doing so I don't accidentally do the same ones.

**Comment by danawillow** [comment]
Closing this in favor of more granular issues per field that needs to be updatable (I think most are now anyway)
