### ISSUE TITLE
Creating new projects with auto_create_network = false fails due to default firewall rules

### ISSUE THREAD

**Issue by timwsuqld** [terraform-providers/terraform-provider-google#4746]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.12.12
+ provider.google v2.18.0

```

### Affected Resource(s)

* google_project

### Terraform Configuration Files

```tf
resource "google_project" "su-cloud" {
  name                = "${var.gcloud-project}"
  project_id          = var.gcloud-project
  folder_id           = var.suqld-org-cloud-hosting-folder # Cloud Hosting fodler ID
  billing_account     = var.billing_account
  auto_create_network = false
}
```

### Debug Output

```
Error: Error deleting default network in project su-cloud-test2: Error waiting for Deleting Network: The network resource 'projects/su-cloud-test2/global/networks/default' is already being used by 'projects/su-cloud-test2/global/firewalls/default-allow-internal'


  on project-metadata.tf line 1, in resource "google_project" "su-cloud":
   1: resource "google_project" "su-cloud" {

```

### Expected Behavior

Create a project, after the initial network creation completed, it would remove the auto created networks so we could create our custom VPCs

### Actual Behavior

Project is created, but removal of auto created networks fail due to a default firewall being present.

> Error waiting for Deleting Network: The network resource 'projects/su-cloud-test2/global/networks/default' is already being used by 'projects/su-cloud-test2/global/firewalls/default-allow-internal'

### Steps to Reproduce

1. `terraform apply`

**Comment by cr-amnonbenzion** [comment]
@timwsuqld timwsuqld
In the meantime, you can choose the provider to work with as a workaround

**Comment by pkaramol** [comment]
I just run into this issue today.

**Comment by rileykarson** [comment]
Ran into this while glancing through tests, I think I've got a fix.

**Comment by rileykarson** [comment]
This should get released in a patch tomorrow.

**Comment by timwsuqld** [comment]
@rileykarson Thanks. So would that be a provider version bump to 2.18.1 then?

**Comment by rileykarson** [comment]
Yep!
