### ISSUE TITLE
message_storage_policy causing permadiff for pubsub resources

### ISSUE THREAD

**Issue by morgante** [terraform-providers/terraform-provider-google#4766]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.10
+ provider.google v2.17.0
+ provider.google-beta v2.17.0
+ provider.null v2.1.2
```

### Affected Resource(s)

- google_pubsub_topic

### Behavior
As reported in https://github.com/terraform-google-modules/terraform-google-scheduled-function/issues/16, omitting the `message_storage_policy` block from a pubsub topic is now causing a permadiff on the `allowed_persistence_regions` field. I'm *guessing* this is because omitting the block causes Terraform to attempt to apply a `null` value while the API returns a complete list of all regions by default.

**Comment by tysen** [comment]
I can't repro this. Setting `message_storage_policy` and then removing it from config doesn't produce a diff. Can you provide repro steps?

**Comment by morgante** [comment]
@tysen To be clear, the behavior I was seeing is a diff when you *never* set the `message_storage_policy`.

With a config like this:
```tf
resource "google_pubsub_topic" "example" {
  name = "example-topic"

  labels = {
    foo = "bar"
  }
}
```

First run `terraform apply` (this will succeed) then run `terraform apply` again and see if you have a permadiff.

@ocervell Are you still seeing this too?

**Comment by slevenick** [comment]
I have seen this before, but it is usually caused by project or organization wide message storage policies that get applied to pubsub topics. If you have an organization wide policy it will be applied to a topic created via terraform, showing a diff.

See: https://cloud.google.com/pubsub/docs/resource-location-restriction
