### ISSUE TITLE
add support for google_compute_forwarding_rule in shared vpc

### ISSUE THREAD

**Issue by pulidon** [terraform-providers/terraform-provider-google#4771]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_compute_forwarding_rule

### Potential Terraform Configuration

Add subnetwork_project field to resource so it can be deployed on a shared vpc host project, but kept as a resource on the service project.

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by danawillow** [comment]
Hi  @pulidon, this should work if you pass in a reference to the subnetwork as a URL or relative  path that includes the project, rather than as a name.

Since I'm pretty sure this works already, closing, but feel free to open a bug report if it doesn't.
