### ISSUE TITLE
How can I create a Composer and upload the DAG file into the bucket in the same TF script?

### ISSUE THREAD

**Issue by paulankho** [terraform-providers/terraform-provider-google#4779]
Kind of newbie in Terraform, maybe this question doesn't have any sense and hopefully is just a lack of skills in my team! 

Our use case:
Deploy a Composer instance and upload the DAG file into the created bucket in one single Terraform execution so the DAG starts once TF ends the configuration and deployment.

Our Current State:
We have coded a TF script that deploys a Composer with success but we are stuck uploading the DAG file into the new bucket because we don't know how to get the bucket name of the new composer. 
We were expecting to have access to the bucket name via this attribute `config.0.dag_gcs_prefix` but we are always getting an error from Terraform saying that the attribute does not exist. 

We have a workaround that is working but it is using two different TF scripts:
1. _Script A_: creates the composer and the bucket, exposing the `composer_bucket` variable as  output in the state file 
2. _Script B_: reads the state from the Script A and gets the bucket name using the code below:
```
[...]
data "terraform_remote_state" "servicesDB" {
  backend = "local"
  config = {
    path = "path_to_the_step1_tf_state_file}"
  }
}

resource "google_storage_bucket_object" "DAG" {
  name   = "name_of_the_dag"
  source = "location_of_the_dag"
  bucket = "${replace(replace(data.terraform_remote_state.servicesDB.composer_bucket,"gs://",""),"/dags","")}"
}
[...]
```

The code is working but it is overcomplicating the sync of our deployment process. 

Wondering if there is a place with a good example about how to use the Composer template and how to access to bucket name from the same TF script so we can upload the DAG file into the new bucket directly.

Thank you!

**Comment by ndmckinley** [comment]
Hey there!

Thanks for the question.  Unfortunately, the information that you would need to do this is just not present in the API object.  It seems like your workaround is genuinely the best way to do this right now.

I do wish there was a way to do this in a single step, but unfortunately there is not at the moment.
