### ISSUE TITLE
Provider ignores credentials file in provider.tf

### ISSUE THREAD

**Issue by rtim75** [terraform-providers/terraform-provider-google#4785]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.12
+ provider.google v2.18.1
+ provider.google-beta v2.18.1

### Terraform Configuration Files

provider.tf
```
provider "google-beta" {
  credentials = "${file("account.json")}"
  project     = "sandbox-248416"
  region      = "us-central1"
  zone        = "us-central1-c"
}
```
check.tf
```
variable "gcloud_project" {
  default = "sandbox-248416"
}
resource "google_compute_network" "jerseydev-gke-vpc" {
  auto_create_subnetworks = false
  name                    = "gke-test"
  project                 = "${var.gcloud_project}"
  routing_mode            = "REGIONAL"
}
```

### Debug Output
https://gist.github.com/rtim75/6cc66b8299b3cdde808f7229378ed1c6

### Expected Behavior

Terraform should have used account.json file that is stored in the same directory provider.tf is stored.
### Actual Behavior
Terraform ignores credentials parameter of provider and tries to use application default credentials which leads to 'Required 'permision name' permission for 'project name', forbidden.

If you I run `gcloud auth application-default revoke` than I get

```
Error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

  on <empty> line 0:
  (source code not available)
```

### Steps to Reproduce

1. `terraform plan`

or 

1. `yes | gcloud auth application-default revoke`
2. `terraform plan`

### References

* #0000

**Comment by Chupaka** [comment]
Your resource still uses "google" provider implicitly. To use "google-beta", you need to set it explicitly in the resource:

```
resource "google_compute_network" "jerseydev-gke-vpc" {
  provider = "google-beta"
  XXXXX
}
```

**Comment by rtim75** [comment]
@Chupaka thanks. Setting provider explicitly in the resource solved the issue
