### ISSUE TITLE
resource google_compute_network_peering doesn't support import

### ISSUE THREAD

**Issue by jarondl** [terraform-providers/terraform-provider-google#4793]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I want to import an existing network_peering object, and it is not supported. The message I get is:
`resource google_compute_network_peering doesn't support import`. The schema doesn't have an Importer, and the [docs](https://www.terraform.io/docs/providers/google/r/compute_network_peering.html) don't mention importing either.

It seems like existing peering should be importable by the network name and peering name. This is what the resource uses for an ID anyway, but a passthrough is not adequate because the resource does not parse the id, instead it reads the name from the object.

### New or Affected Resource(s)

* google_compute_network_peering

**Comment by danawillow** [comment]
Added in https://github.com/GoogleCloudPlatform/magic-modules/pull/2751, should be available in  3.1.0
