### ISSUE TITLE
Resource google_logging_project_exclusion fails to create more than a single resource - reports success

### ISSUE THREAD

**Issue by Zamyatin** [terraform-providers/terraform-provider-google#4796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

`v0.12.x`

### Affected Resource(s)

* google_logging_project_exclusion

### Terraform Configuration Files

```tf
locals {
  my_project = "my-project-with-hash"
}

resource "google_logging_project_exclusion" "microservice_1_service_logs_exclusion" {
  name        = "microservice-1-service-logs-exclusion"
  description = "Exclude logs with severity less than DEBUG"
  project     = local.my_project
  filter      = "resource.type=k8s_container AND severity<DEBUG AND resource.labels.container_name=my-microservice-1-service-deployment"
}

resource "google_logging_project_exclusion" "microservice_2_service_logs_exclusion" {
  name        = "microservice-2-service-logs-exclusion"
  description = "Exclude logs with severity less than DEBUG"
  project     = local.my_project
  filter      = "resource.type=k8s_container AND severity<DEBUG AND resource.labels.container_name=my-microservice-2-service-deployment"
}

resource "google_logging_project_exclusion" "microservice_3_service_logs_exclusion" {
  name        = "microservice-3-service-logs-exclusion"
  description = "Exclude logs with severity less than DEBUG"
  project     = local.my_project
  filter      = "resource.type=k8s_container AND severity<DEBUG AND resource.labels.container_name=my-microservice-3-service-deployment"
}

resource "google_logging_project_exclusion" "microservice_4_service_logs_exclusion" {
  name        = "microservice-4-service-logs-exclusion"
  description = "Exclude logs with severity less than DEBUG"
  project     = local.my_project
  filter      = "resource.type=k8s_container AND severity<DEBUG AND resource.labels.container_name=my-microservice-4-service-deployment"
}

resource "google_logging_project_exclusion" "microservice_5_service_logs_exclusion" {
  name        = "microservice-5-service-logs-exclusion"
  description = "Exclude logs with severity less than DEBUG"
  project     = local.my_project
  filter      = "resource.type=k8s_container AND severity<DEBUG AND resource.labels.container_name=my-microservice-5-service-deployment"
}
```

Alternately, I've tried an iterating approach with the same issue:
```tf
locals {
  test_log_levels = {
    my-microservice-1-service-deployment = "INFO"
    my-microservice-2-service-deployment = "INFO"
    my-microservice-3-service-deployment = "INFO"
    my-microservice-4-service-deployment = "INFO"
    my-microservice-5-service-deployment = "INFO"
  }
  my_project = "my-project-with-hash"
}

resource "google_logging_project_exclusion" "test_logs_exclusion_info" {
  count       = length(keys(local.test_log_levels))
  name        = "${element(keys(local.test_log_levels), count.index)}-logs-exclusion"
  description = "Exclude logs with severity less than ${element(values(local.test_log_levels), count.index)}"
  project     = local.my_project
  filter      = "resource.type=k8s_container AND severity<${element(values(local.test_log_levels), count.index)} AND resource.labels.container_name=${element(keys(local.test_log_levels), count.index)}"
}
```

### Debug Output

https://gist.github.com/Zamyatin/daa0b616cc0532fca84092e82c2d63c9

### Panic Output

```
Error: Provider produced inconsistent result after apply

When applying changes to
google_logging_project_exclusion.microservice_4_service_logs_exclusion, provider
"google" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent result after apply

When applying changes to
google_logging_project_exclusion.microservice_3_service_logs_exclusion, provider
"google" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Expected Behavior
All 5 resources should have been created and/or updated.

### Actual Behavior
Only a single resource was created/updated (the first).  Upon another `terraform plan` shows that 4 remain to be created/updated. Another `terraform apply` may take with no error, but will only create/update the next resource, not all.

Subsequent `terraform apply` runs generally return the Panic Output (above), but continue to create/update a single resource at a time.

### Steps to Reproduce

1. `terraform apply` - this will return successful green output
```
Plan: 5 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "tst"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

...
Apply complete! Resources: 5 added, 0 changed, 0 destroyed.
...

```

2. `terraform plan` - see that not all resources have been created
```
Plan: 4 to add, 0 to change, 0 to destroy.
```

3. `terraform apply` again - another green output (suggesting success)
```
Plan: 4 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "tst"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

...
Apply complete! Resources: 4 added, 0 changed, 0 destroyed.
...
```

4. `terraform plan` - one more resource possibly created

```
Plan: 3 to add, 0 to change, 0 to destroy.
```

5. `terraform apply` - probably will get Panic Output (above). However, a single new resource has either been created/updated/destroyed.

### Important Factoids

I am authenticating as a User (not a service account) . This did work under Terraform 0.11.x, and we did recently update our Terraform to v0.12.10.  However, I have deleted/destroyed these resources from both GCP and Terraform state, then tried to execute again with no success.

Also interesting: I see the correct logs/API calls to the Google Logging API in the Activity tab of my GCP Project under my user name.  All resource CRUD calls are there as though they all hit the API:

`my.email@domain.com has executed google.logging.v2.ConfigServiceV2.CreateExclusion on microservice-1-service-logs-exclusion`

`my.email@domain.com has executed google.logging.v2.ConfigServiceV2.UpdateExclusion on microservice-2-service-logs-exclusion`  -- (in cases where I'm making an update)

It is as though Terraform is making the calls to Google's APIs, but not waiting for confirmation, and the APIs, while getting the POST from Terraform, are not processing calls correctly.  I am not sure.  This started happening only recently, as I've made changes to our numerous exclusion rules as a large batch.

### References

* #0000

**Comment by Zamyatin** [comment]
Additional Behavior I've found: 
* Any time Terraform tries to perform any CRUD actions on a number of `google_logging_project_exclusions`, only one item will be deleted.  When deleting these resources, for example, they seem to be deleted from state, but they are not actually deleted in Google Cloud. Manual deletion via the Google Cloud Console manually is required.

**Comment by danawillow** [comment]
Hi @Zamyatin, when you get a chance can you please post the debug output (https://www.terraform.io/docs/internals/debugging.html) as per the issue template?

**Comment by Zamyatin** [comment]
Sure @danawillow.  Will get that up asap.

Hey FWIW this seems to be an issue with parallelism.  I'm able to execute these resources without parallelism: `terraform apply -parallelism=1`, which then creates/updates all resources correctly.  Not sure if this is a problem with the API or the google-terraform-provider.

**Comment by Zamyatin** [comment]
Debug output gist added.

**Comment by danawillow** [comment]
Thanks, I've verified that it indeed doesn't work. It looks like an API issue so I've filed it with that team, but we should be able to work around it pretty easily on our side. I'll prepare a fix.
