### ISSUE TITLE
Invalid value for field 'resource.disks[1].initializeParams.diskType': 'pd-standard'

### ISSUE THREAD

**Issue by adayanlan** [terraform-providers/terraform-provider-google#4801]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.13
+ provider.google v2.7.0

### Affected Resource(s)
google_compute_instance_from_template

* google_XXXXX

### Terraform Configuration Files
variables.tf

variable "additional_disks" {
  description = "List of maps of additional disks. See https://www.terraform.io/docs/providers/google/r/compute_instance_template.html#disk_name"
  type = list(object({
    auto_delete  = bool
    boot         = bool
    disk_size_gb = number
    disk_type = string
    source_image    = string
  }))
  default = [{
                              auto_delete  = false
                              boot = false
                              device_name = "data"
                              disk_size_gb = 100
                              mode = "READ_WRITE"
                              disk_type = "pd-standard"
                              source_image = "projects/wmt-case-cbb-plt-stg/global/images/nifi-data-blank"
                            }]
}
main.tf
#########
# Locals
#########

locals {
  boot_disk = [
    {
      disk_size_gb = 100
      disk_type    = "pd-standard"
      auto_delete  = "true"
      boot         = "true"
    },
  ]
  all_disks = concat(local.boot_disk, var.additional_disks)
}

####################
# Instance Template
####################
resource "google_compute_instance_template" "tpl" {
  name                    = "${var.name}"
  machine_type            = var.machine_type
  labels                  = var.labels
  metadata                = var.metadata
  tags                    = var.tags
  can_ip_forward          = var.can_ip_forward
  metadata_startup_script = var.startup_script
  dynamic "disk" {
    for_each = local.all_disks
    content {
      auto_delete  = lookup(disk.value, "auto_delete", null)
      boot         = lookup(disk.value, "boot", null)
      device_name  = lookup(disk.value, "device_name", null)
      disk_name    = lookup(disk.value, "disk_name", null)
      disk_size_gb = lookup(disk.value, "disk_size_gb", null)
      disk_type    = lookup(disk.value, "disk_type", null)
      interface    = lookup(disk.value, "interface", null)
      mode         = lookup(disk.value, "mode", null)
      source       = lookup(disk.value, "source", null)
      source_image = var.source_image
      type         = lookup(disk.value, "type", null)

      dynamic "disk_encryption_key" {
        for_each = lookup(disk.value, "disk_encryption_key", [])
        content {
          kms_key_self_link = lookup(disk_encryption_key.value, "kms_key_self_link", null)
        }
      }
    }
  }
  dynamic "service_account" {
    for_each = [var.service_account]
    content {
      email  = lookup(service_account.value, "email", null)
      scopes = lookup(service_account.value, "scopes", null)
    }
  }

  network_interface {
    network            = var.network
    subnetwork         = var.subnetwork
    subnetwork_project = var.subnetwork_project
  }

  // scheduling must have automatic_restart be false when preemptible is true.
  scheduling {
    preemptible       = var.preemptible
    automatic_restart = ! var.preemptible
  }

}

```tf
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug) then please include both the
# version of the config before the change, and the version of the config after the change.
```

### Actual Behavior
create 1 boot disk and 2 persisted disk which will not be deleted after vm removed

Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.disks[1].initializeParams.diskType': 'pd-standard'. The URL is malformed.
It is the same error in this issue https://github.com/terraform-providers/terraform-provider-google/issues/3713, which is supposed to be fixed in that ticket. but I am using latest version and get the same error.

### Steps to Reproduce

1. `terraform apply`

### References
It is the same error in this issue https://github.com/terraform-providers/terraform-provider-google/issues/3713, which is supposed to be fixed in that ticket. but I am using latest version and get the same error.

* #0000

**Comment by Chupaka** [comment]
You're using v2.7.0, the latest one at the moment is 2.18.1. Please upgrade (`terraform init -upgrade`) and recheck. Just my 2¢.

**Comment by danawillow** [comment]
I'm going to close this out since I'm pretty sure @Chupaka's comment applies.

If this is still an issue after upgrading, please comment and I'll take a look!
