### ISSUE TITLE
Expose generated DNSKEY/DS records on DNSSEC-signed managed zones

### ISSUE THREAD

**Issue by jhujhiti** [terraform-providers/terraform-provider-google#4802]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When creating a DNSSEC-signed zone, Google generates DNSKEY records (both a ZSK and a KSK). These records should be exposed as attributes, ideally in both the DNSKEY format and the DS format. Exposing the KSK is especially important as it's necessary to delegate the zone securely from the parent. With this data exposed, the delegation from the registrar could happen entirely within Terraform (assuming a supported registrar provider...).

I see this accomplished with at least two attributes:
- A list of all KSKs in DNSKEY format (`["257 3 13 mdsswUyr3DPW132mOi8V9xESWE8jTo0dxCjjnopKl+GqJxpVXckHAeF+ KkxLbxILfDLUT0rAK9iUzy1L53eKGQ=="]`)
- A list of all KSKs in DS format (`["2371 13 2 32996839A6D808AFE3EB4A795A0E6A7A39A76FC52FF228B22B76F6D63826F2B9"]`)
- (Maybe, although somewhat less useful) A list of all ZSKs in DNSKEY format (`["256 3 13 oJMRESz5E4gYzS/q6XDrvU1qMPYIjCWzJaOau8XNEZeqCYKD5ar0IRd8 KqXXFJkqmVfRvMGPmM1x8fGAa2XhSA=="]`). This isn't necessary to delegate the zone, but Google's API response does provide it.

A secure delegation at the registrar requires either the KSK DS records or the KSK DNSKEY records (depending on the registry, they will either require the DS or accept a DNSKEY and convert it to DS automatically).

It may also be useful to expose a map of each type of key with the raw values Google's API provides in addition to exposing the strings above. If this is done, I'd want to see at least the following contained in the map:

- algorithm name
- algorithm id
- protocol
- flags
- encoded public key
- key digest algorithm
- key digest algorithm id
- key digest

The key of each map item would be the key tag in the API response.

Happy to help elucidate any details on the records themselves if necessary.

### New or Affected Resource(s)

* google_dns_managed_zone

### Potential Terraform Configuration

```tf
# standard zone creation with dnssec enabled
resource "google_dns_managed_zone" "myzone" {
  name        = "myzone"
  dns_name    = "terraform.io."
  visibility  = "public"

  dnssec_config {
    state         = "on"
    non_existence = "nsec3"

    default_key_specs {
      algorithm  = "ecdsap256sha256"
      key_length = "256"
      key_type   = "keySigning"
    }

    default_key_specs {
      algorithm  = "ecdsap256sha256"
      key_length = "256"
      key_type   = "zoneSigning"
    }
  }
}

# module output to allow consumers to programmatically send the key to the registrar
output "ksks" {
  # i would expect this to be a list since multiple keys are valid
  value = google_dns_managed_zone.myzone.dnskey_ksks
}
```

### References

API documentation is at https://cloud.google.com/dns/docs/reference/v1beta2/dnsKeys/list

Presentation format for the DNSKEY and DS records is described in https://tools.ietf.org/html/rfc4034

DNSKEY algorithm numbers are defined by IANA at https://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml#dns-sec-alg-numbers-1

Digest algorithm numbers are also defined by IANA separately at https://www.iana.org/assignments/ds-rr-types/ds-rr-types.xhtml

**Comment by chrissng** [comment]
The way magic-module resources are defined seems to suggest that this cannot be a computed property of `google_dns_managed_zone`. It could be defined as a data source instead.
