### ISSUE TITLE
Blocks of type "labels" are not expected here.

### ISSUE THREAD

**Issue by chrisLeeTW** [terraform-providers/terraform-provider-google#4804]
### Terraform Version

Terraform v0.12.13

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

```tf
resource "google_container_node_pool" "main" {
  provider = "google-beta"
  name     = var.display_name

  cluster    = var.cluster_name
  location   = var.cluster_region
  node_count = var.count_in_each_zones

  management {
    auto_repair  = true
    auto_upgrade = true
  }

  node_config {
    machine_type = var.instance_type
    disk_size_gb = var.disk_size
    oauth_scopes = local.oauth_scopes

    dynamic "labels" {
      for_each = var.enable_dedicated_taint ? list("1") : list("")
      content {
        dedicated = var.taint_dedicated_for
      }
    }

    dynamic "taint" {
      for_each = var.enable_dedicated_taint ? list("1") : list("")
      content {
        key    = "dedicated"
        value  = var.taint_dedicated_for
        effect = "NO_SCHEDULE"
      }
    }
  }

  dynamic "autoscaling" {
    for_each = var.enable_auto_scaling ? list("1") : list("")
    content {
      min_node_count = var.auto_scale_min_nodes_in_each_zones
      max_node_count = var.auto_scale_max_nodes_in_each_zones
    }
  }
}
```

### Debug Output

```
Error: Unsupported block type

  on ../../../shared/gcp_gke_node_pool/main.tf line 19, in resource "google_container_node_pool" "main":
  19:     dynamic "labels" {

Blocks of type "labels" are not expected here.
```

full gist output with TF_DEBUG : https://gist.github.com/chrisLeeTW/95cef20536529d9d834951dc5e90d877

### Expected Behavior

should execute terraform plan successfully.

### Actual Behavior

Got error.

### Steps to Reproduce

1. `terraform apply`

**Comment by danawillow** [comment]
Hi @chrisLeeTW, thanks the report! Next time can you please leave the comments in the issue template alone so that our bot can label the issue appropriately? Thanks!

For this specific question, `dynamic` is only used for blocks: https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks. `labels` is a map, not a block. I haven't tried it out, but you might be able to use a for expression instead: https://www.terraform.io/docs/configuration/expressions.html#for-expressions

**Comment by chrisLeeTW** [comment]
> Hi @chrisLeeTW, thanks the report! Next time can you please leave the comments in the issue template alone so that our bot can label the issue appropriately? Thanks!

Ok, no problem. Thank you for the notification.

> For this specific question, `dynamic` is only used for blocks: https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks. `labels` is a map, not a block. I haven't tried it out, but you might be able to use a for expression instead: https://www.terraform.io/docs/configuration/expressions.html#for-expressions

Sorry about it. I am on the way that transform my terrafrom configuration from 0.11 to 0.12, and I do not notice that the type of labels was changed. thank you for the notification again, and sorry for the bothering.
