### ISSUE TITLE
testable_permissions data source

### ISSUE THREAD

**Issue by morgante** [terraform-providers/terraform-provider-google#4812]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We would like to see a `testable_permissions` data source which returns the available permissions for a particular resource. This would wrap [this API](https://cloud.google.com/iam/docs/reference/rest/v1/permissions/queryTestablePermissions) call and, critically, provide information on the permissions usable with custom roles.

### New or Affected Resource(s)

- google_testable_permissions

### Potential Terraform Configuration

```tf
data "google_testable_permissions" "project_perms" {
  resource = "//cloudresourcemanager.googleapis.com/projects/my-project"
  custom_role_support_level = "SUPPORTED" # only return supported permissions
}
```

**Comment by soleimanigoogle** [comment]
+1
