### ISSUE TITLE
nil pointer dereference when reading state of an "old" cluster

### ISSUE THREAD

**Issue by mleclercq** [terraform-providers/terraform-provider-google#4822]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Using pulumi 1.4.1 which depends on v2.18.1 of https://github.com/terraform-providers/terraform-provider-google-beta

### Affected Resource(s)

* google_container_cluster during read

### Stack-trace

Crash happens at: https://github.com/terraform-providers/terraform-provider-google-beta/blob/v2.18.1/google-beta/resource_container_cluster.go#L1198

```
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x27a017d]
    goroutine 13 [running]:
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.resourceContainerClusterRead(0xc000420620, 0x2f768c0, 0xc00018f600, 0x0, 0xc0006d0088)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:1198 +0x106d
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.resourceContainerClusterUpdate(0xc000420620, 0x2f768c0, 0xc00018f600, 0x24, 0x4ee6580)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:1951 +0x16c2
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0001bef00, 0xc00047f680, 0xc000702fa0, 0x2f768c0, 0xc00018f600, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:311 +0x264
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000575780, 0xc000539878, 0xc00047f680, 0xc000702fa0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x18f
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.(*Provider).Update(0xc00010a280, 0x3858740, 0xc000728a80, 0xc0007be000, 0xc00010a280, 0x2f63201, 0xc0006e8e80)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge/provider.go:814 +0xa14
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler.func1(0x3858740, 0xc000728a80, 0x32ddca0, 0xc0007be000, 0x32dc9e0, 0x4ee4d98, 0x3858740, 0xc000728a80)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1592 +0x86
    github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x3858740, 0xc000796030, 0x32ddca0, 0xc0007be000, 0xc0007921a0, 0xc0007921c0, 0x0, 0x0, 0x3803de0, 0xc0001b7600)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x360
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler(0x3334660, 0xc00010a280, 0x3858740, 0xc000796030, 0xc0000a80c0, 0xc0000aa600, 0x3858740, 0xc000796030, 0xc00027d000, 0x3564)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1594 +0x158
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c0160, 0x386cbe0, 0xc000462d80, 0xc000432000, 0xc00051a2d0, 0x4eb70c0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:995 +0x466
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000c0160, 0x386cbe0, 0xc000462d80, 0xc000432000, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:1275 +0xda6
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003b20c0, 0xc0000c0160, 0x386cbe0, 0xc000462d80, 0xc000432000)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:710 +0x9f
    created by github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:708 +0xa1
```

### Expected Behavior

Read of the cluster's state should not crash

### Actual Behavior

`pulumi refresh` crashes when reading the state of the cluster.
Also `pulumi up` crashes with the same error after when updating the cluster configuration.

### Steps to Reproduce

I'm having that error only in one of our GKE clusters. I have the feeling that it is caused by the fact that this cluster is "old" (createTime: 2018-01-25T20:54:08+00:00).

So you would probably need an old cluster and try to import it in pulumi/terraform to reproduce the problem.

### Important Factoids

at https://github.com/terraform-providers/terraform-provider-google-beta/blob/v2.18.1/google-beta/resource_container_cluster.go#L1198

```go
d.Set("enable_shielded_nodes", cluster.ShieldedNodes.Enabled)
```

It looks like `cluster.ShieldedNodes` is `nil` on that old cluster while it is not on more recent clusters.

I've noticed that `enable_shielded_nodes` has been added in v2.18.0 of the provider. 

Using an older version of the pulumi gcloud provider (v1.3.0) which uses an older version of this terraform provider fixes the issue.

**Comment by danawillow** [comment]
Hey @mleclercq! We actually just released v2.19.0 today, which contains a fix for that (https://github.com/terraform-providers/terraform-provider-google-beta/pull/1314). Once pulumi updates to this version, you should be good to go.

I'm going to close this issue but please let me know if it continues after changing the version and I can take another look.
