### ISSUE TITLE
Newly created google_compute_autoscaler has always default min_replicas

### ISSUE THREAD

**Issue by tomplus** [terraform-providers/terraform-provider-google#4832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.5
+ provider.archive v1.3.0
+ provider.google v2.19.0
+ provider.google-beta v2.19.0
+ provider.random v2.2.1

### Affected Resource(s)

* google_compute_autoscaler

### Terraform Configuration Files

```tf

resource "google_compute_autoscaler" "test" {
  provider = "google-beta"
  name     = "test"
  target   = "${google_compute_instance_group_manager.test.self_link}"
  zone     = var.zone
  project  = var.project

  autoscaling_policy {
    max_replicas    = 6
    min_replicas    = 0
    cooldown_period = 60

    metric {
      name                       = "pubsub.googleapis.com/subscription/num_undelivered_messages"
      filter                     = "resource.label.subscription_id = \"${var.queue_name}\" AND resource.type = \"pubsub_subscription\""
      single_instance_assignment = 1
    }
  }
}

```

### Expected Behavior

The created resource should have min_replicas = 0.

### Actual Behavior

The resource has min_replicas = 2 after creation. I have to run `terraform apply` again to fix this parameter.

```
      ~ autoscaling_policy {
            cooldown_period = 60
            max_replicas    = 6
          ~ min_replicas    = 2 -> 0
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tomplus** [comment]
Thank you.

**Comment by hixus** [comment]
Have the same issue. Running with TF_LOG=true it seems that terraform drops minNumReplicas from POST request if it's set to zero. Therefore autoscaler selects some minimum other than zero. Below post request body terraform made.

```
[DEBUG] plugin.terraform-provider-google-beta_v2.19.0_x4:
{
  "autoscalingPolicy": {
   "coolDownPeriodSec": 60,
   "customMetricUtilizations": [
    {
     "filter": "resource.type = pubsub_subscription AND resource.label.subscription_id = foobar",
     "metric": "pubsub.googleapis.com/subscription/num_undelivered_messages",
     "singleInstanceAssignment": 100
    }
   ],
   "maxNumReplicas": 1
  },
  "name": "foobar",
  "target": "https://www.googleapis.com/compute/beta/projects/foobar/zones/europe-north1-a/instanceGroupManagers/foobar-igm",
  "zone": "projects/foobar-258114/global/zones/europe-north1-a"
}```

**Comment by hixus** [comment]
Ok, this seems to be fixed but when does the fix come out?

**Comment by danawillow** [comment]
v2.20 (probably tomorrow)
