### ISSUE TITLE
google_project_iam_member: Inconsistent result after apply

### ISSUE THREAD

**Issue by rosmo** [terraform-providers/terraform-provider-google#4833]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

$ terraform version
Terraform v0.12.13
+ provider.google v2.19.0
+ provider.google-beta v2.19.0
+ provider.null v2.1.2

### Affected Resource(s)

* google_iam_project_member

### Terraform Configuration Files

main.tf:
```tf
module "project-factory" {
  source = "github.com/terraform-google-modules/terraform-google-project-factory"

  name                = "${upper(terraform.workspace)} - ${var.project-id}"
  project_id          = "${module.example-config.organization_prefix}-${var.project-id}-${terraform.workspace}"
  random_project_id   = "false"
  org_id              = "${module.example-config.organization_id}"
  folder_id           = "${module.example-config.example_folder}"
  billing_account     = "${module.example-config.billing_account}"
  auto_create_network = "true"

  labels = { environment = "${terraform.workspace}", project = "${var.project-id}" }
  activate_apis = [
    "compute.googleapis.com",
    "iam.googleapis.com",
  ]

  shared_vpc = "${module.example-config.sharedvpc_project}"
```

### Debug Output

https://gist.github.com/rosmo/5de3a27c6752541bf5bd06c59f67f352

### Expected Behavior

No inconsistent results. 

### Actual Behavior

```
Error: Provider produced inconsistent result after apply

When applying changes to
module.project-factory.module.project-factory.google_project_iam_member.controlling_group_vpc_membership[0],
provider "google" produced an unexpected new value for was present, but now
absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent result after apply

When applying changes to
module.project-factory.module.project-factory.google_project_iam_member.controlling_group_vpc_membership[1],
provider "google" produced an unexpected new value for was present, but now
absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent result after apply

When applying changes to
module.project-factory.module.project-factory.google_project_iam_member.controlling_group_vpc_membership[2],
provider "google" produced an unexpected new value for was present, but now
absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

Create a project using project factory module:

1. `terraform apply`

### Important Factoids

This uses the latest version of: https://github.com/terraform-google-modules/terraform-google-project-factory

**Comment by danawillow** [comment]
Hey @rosmo, thanks for the report! Would you mind sending over full DEBUG logs (https://www.terraform.io/docs/internals/debugging.html)? I'd like to see the full API requests/responses sent to/from GCP.

**Comment by rosmo** [comment]
@danawillow, it's really interesting, I enable the DEBUG logs, the project gets successfully provisioned. Maybe a race condition?

**Comment by rosmo** [comment]
@danawillow Here are the debug logs: https://gist.github.com/rosmo/a67d769671d21829689e98e3dcb8c80e
