### ISSUE TITLE
enabled-logging feature in google_compute_firewall needs to be added in GA

### ISSUE THREAD

**Issue by sanmmishra** [terraform-providers/terraform-provider-google#4836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

As per this announcement, the enable logging (which enables firewall level logs) is in [GA,](https://cloud.google.com/blog/products/identity-security/google-cloud-firewall-rules-logging-how-and-why-you-should-use-it) but the google provider (GA) doesnt support it yet (see line 113/ 128) . It is only supported by beta

https://github.com/terraform-google-modules/terraform-google-network/blob/master/modules/fabric-net-firewall/main.tf

Can we add this feature to the GA provider?

### New or Affected Resource(s)

* google_compute_firewall"

### Potential Terraform Configuration
```
resource "google_compute_firewall" "custom" {
  name                    = foofw
  description             = foodescription
  direction               = INGRESS
  network                 = default
  project                 = foo-project
  enable_logging          = true
}
```
* #0000

**Comment by venkykuberan** [comment]
@sanmmishra enable-logging feature is added to GA [here](https://github.com/terraform-providers/terraform-provider-google/pull/4999). Hence i am closing this ticket
