### ISSUE TITLE
Add support for configuring IAM policies at the organization-level

### ISSUE THREAD

**Issue by ubschmidt2** [terraform-providers/terraform-provider-google#485]
This is related to https://github.com/terraform-providers/terraform-provider-google/issues/132, https://github.com/terraform-providers/terraform-provider-google/issues/413, which are about folders and the configuration of the IAM at the folder-level.

IAM policy can also be set at the organization-level. We want to configure these policies given an existing org.

**Comment by rosbo** [comment]
Are you planning on tackling this @ubschmidt2?

**Comment by ubschmidt2** [comment]
@rosbo - it would be great if you could take it ;-). Otherwise, I'll look into it (nothing concrete planned yet).

**Comment by rosbo** [comment]
I created a separate issue for org policies at the organization level (#507) and I renamed this issue.
