### ISSUE TITLE
Resource to setup budget alerts

### ISSUE THREAD

**Issue by umairidris** [terraform-providers/terraform-provider-google#4850]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Adding a resource to automate creation of https://cloud.google.com/billing/docs/how-to/budgets through Terraform. Send budget alerts to pubsub or email.

### New or Affected Resource(s)

* google_billing_export

### Potential Terraform Configuration

```tf
resource google_billing_budget_alert "alert" {
  name = "foo-alert"
  billing_account_id = "123"
  projects = [
    "p1"
  ] # omitting this sets alerts for all projects?
  products = [
    "foo-product"
  ] # omitting this sets alerts for all products?
  type: MONTHLY_SPEND
  amount: 10000
  include_credits = true
  notifications = [{
    threshold = 8000
    pubsub_topic = ${google_pubsub_topic.foo_topic.name}
    email = "foo@example.com"
  }]
}
```
NOTE: Currently there doesn't  seem to be an API for this.

**Comment by umairidris** [comment]
There is now an API for this resource, so I am looking to add it into the terraform google provider.

**Comment by danawillow** [comment]
This is now done: https://github.com/GoogleCloudPlatform/magic-modules/pull/2734
