### ISSUE TITLE
Review version-3-upgrade documentation

### ISSUE THREAD

**Issue by megan07** [terraform-providers/terraform-provider-google#4855]
This is a reminder issue to review the version 3 upgrade documentation to make sure everything is in there.

## Confirmation that all parts are added

- [x] @chrisst (reviewed by @rileykarson)
- [x] @danawillow 
- [x] @emilymye 
- [x] @megan07 
- [x] @ndmckinley 
- [x] @paddycarver 
- [x] @rileykarson 
- [x] @slevenick

**Comment by rileykarson** [comment]
We've all reviewed the docs- closing out.
