### ISSUE TITLE
Error: project: required field is not set on google_compute_network

### ISSUE THREAD

**Issue by brunocrt** [terraform-providers/terraform-provider-google#4856]
I'm facing an issue when trying to create GCP network resource! 
by the documentation it seems all required parameters are provided!

`Error: project: required field is not set`

  `on main.tf line 1, in resource "google_compute_network" "vpc_network":`
   `1: resource "google_compute_network" "vpc_network" {`

I was using the example provided by the link bellow

[https://www.terraform.io/docs/providers/google/r/compute_network.html](https://www.terraform.io/docs/providers/google/r/compute_network.html)

Follows the terraform and plugin versions:

student_00_98fff344d534@cloudshell:~/docs-examples/network_basic$ terraform -v
**Terraform v0.12.6
+ provider.google v2.19.0
+ provider.random v2.2.1**

Your version of Terraform is out of date! The latest version
is 0.12.13. You can update by downloading from www.terraform.io/downloads.html
student_00_98fff344d534@cloudshell:~/docs-examples/network_basic$

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_network

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug) then please include both the
# version of the config before the change, and the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by brunocrt** [comment]
It seems that this bug was already reported for other google cloud resources as well like this one
https://github.com/hashicorp/terraform/issues/17131

**Comment by brunocrt** [comment]
It was my fault! I forgot to set the default google project name using the command
`gcloud config set project qwiklabs-gcp-00-860efe63b710`
It solved the issue!

**Comment by eversC** [comment]
I had the same thing, but unfortunately `gcloud config set project` didn't work for me..

I got it working by setting the env var: `GOOGLE_PROJECT`
