### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by AndreaGiardini** [terraform-providers/terraform-provider-google#486]
Hi there,

Last release is over one month old and during this time the provider has evolved a lot. Especially PR like this ( https://github.com/terraform-providers/terraform-provider-google/issues/25 ) have been merged and could overcome limitations of the current version.

Is there any reason not to publish a new release?

**Comment by paddycarver** [comment]
The 1.0.0 & 1.0.1 releases just landed. I realise they had a lot of features people were waiting on, and apologise for the delay. To give some insight as to why the release wasn't just published, a lot of things went into the actual release process:

* Making sure that the breaking changes we knew were on the horizon were actually merged, so we didn't release a 1.0.0 just to follow it with 2.0.0 a week later.
* Removing the deprecated fields on resources that have been deprecated for a while, making our codebase smaller and more maintainable. Unfortunately, some of these fields (in this case, `disk` and `network` on `google_compute_instance` especially) are heavily used in other resources' tests, documentation, etc. Getting all the tests and documentation updated takes time.
* Some of our breaking changes (the disk migration) are very complex and hard to test. We wanted to take ample time with these to try and make sure that upgrading was a smooth, error-free experience. Unfortunately, even with all our testing of these, we still experienced a migration error, necessitating 1.0.1 getting sent out just a few hours later. So even with all the time we took on this, we probably should have taken a little bit more.

Again, I regret the delay in getting this release out the door. We'll do our best to return to regularly-scheduled releases and smooth upgrade processes now. Thanks everyone, for your patience.

**Comment by AndreaGiardini** [comment]
Thank you for the great work! :)
