### ISSUE TITLE
google_service_account description not properly updating

### ISSUE THREAD

**Issue by tdgeery** [terraform-providers/terraform-provider-google#4868]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.13
+ provider.google v2.19.0
+ provider.google-beta v2.19.0
+ provider.kubernetes v1.10.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.vault v2.6.0
```

### Affected Resource(s)

* `google_service_account`

### Terraform Configuration Files

```tf
resource "google_service_account" "testing123" {
  project      = data.terraform_remote_state.service_project.outputs.project_id
  account_id   = "testing123"
  display_name = "testing123"
  description  = "Test Description... 123"
}
```

### Expected Behavior

```tf
# google_service_account.testing123 will be updated in-place
~ resource "google_service_account" "testing123" {
    account_id   = "testing123"
  ~ description  = "Test Description" -> "Test Description... 123"
    display_name = "testing123"
    email        = "testing123@<project-id>.iam.gserviceaccount.com"
    id           = "projects/<project-id>/serviceAccounts/testing123@<project-id>.iam.gserviceaccount.com"
    name         = "projects/<project-id>/serviceAccounts/testing123@<project-id>.iam.gserviceaccount.com"
    project      = "<project-id>"
}
```

### Actual Behavior

When trying to add or modify the description of a Service Account, the apply completes successfully but resource is not properly updated. Second run of plan/apply shows it still needs to be modified.

### Steps to Reproduce

1. Add/Modify description argument to already created Service Account
2. `terraform apply`
3. Describe your service account via gcloud or look at the console for updated description
4. Rerun `terraform apply`

### Important Factoids

Only occurs when the service account has already been created, and you're modifying/adding a description

**Comment by ndmckinley** [comment]
It may be that descriptions aren't modifiable - I'll take a look.
