### ISSUE TITLE
Healthcare stores failing on creation

### ISSUE THREAD

**Issue by umairidris** [terraform-providers/terraform-provider-google#4869]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.12
+ provider.google v2.19.0
+ provider.google-beta v2.19.0

### Affected Resource(s)

* google_healthcare_dicom_store
* google_healthcare_fhir_store
* google_healthcare_hl7_v2_store

### Terraform Configuration Files

```tf
resource "google_healthcare_dataset" "dataset" {
    provider = google-beta
    name = "demo"
    location = "us-central1"
    project = "umairidris-data-191001"
}

resource "google_healthcare_fhir_store" "store" {
    provider = google-beta
    dataset = google_healthcare_dataset.dataset.name
    name = "test"
}
```

### Debug Output

[debug.txt](https://github.com/terraform-providers/terraform-provider-google/files/3833927/debug.txt)

### Expected Behavior

Stores are created.

### Actual Behavior

google_healthcare_fhir_store.store: Creating...

Error: Error creating FhirStore: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1beta1/demo/fhirStores?alt=json&amp;fhirStoreId=test</code> was not found on this server.  <ins>That’s all we know.</ins>

### Steps to Reproduce

1. `terraform apply`

**Comment by rileykarson** [comment]
You've used the `name` value for `dataset`, but it expects a certain format for the value. Can you use `id` instead, as shown in the example? https://www.terraform.io/docs/providers/google/r/healthcare_fhir_store.html#example-usage-healthcare-fhir-store-basic

**Comment by umairidris** [comment]
D'oh. That was it. Sorry about that!
