### ISSUE TITLE
Terraform plan or apply doesn't work when just cloud source code changed for cloud functions deployment

### ISSUE THREAD

**Issue by dfang** [terraform-providers/terraform-provider-google#4871]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* google_cloud_functions

### Terraform Configuration Files

```tf
resource "google_cloudfunctions_function" "f1" {
  name        = "${terraform.workspace}_f1"
  runtime     = "go111"
  available_memory_mb = 256
  source_repository {
    url = "<GOOGLE CLOUD SOURCE REPO>"
  }
  trigger_http = true
  timeout      = 60
  entry_point  = "Handler"
  environment_variables = {
    GOOGLE_CLOUD_PROJECT = "${var.projectID}"
    CLOUD_SQL_HOST     = "${var.cloud_sql_host}"
    CLOUD_SQL_PORT     = "${var.cloud_sql_port}"
    CLOUD_SQL_USERNAME = "${var.cloud_sql_username}"
    CLOUD_SQL_PWD      = "${var.cloud_sql_password}"
    CLOUD_SQL_DB       = "${var.cloud_sql_database}"
  }
}
```

this deploys a function and the function source code is hosted on google code source repository.
when i just push function changes to google code source, but change nothing on this file.
then i run `terraform plan`, i got this
```
.....
No changes. Infrastructure is up-to-date.
```
and `terraform apply`, got this:

```
....
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Expected Behavior

redeploy the function

### Actual Behavior

nothing happened

### References

* #0000

**Comment by rileykarson** [comment]
This is a variant of https://github.com/terraform-providers/terraform-provider-google/issues/1938.

Terraform knows that the correct source repo was used, and isn't able to tell that the underlying contents have changed. From its point of view, the config correctly matches the upstream state.

To a non-computer, your use-case is clear. Unfortunately, it isn't really possible to accomplish as-is with Terraform. I'd suggest tagging a specific commit with the syntax shown at https://www.terraform.io/docs/providers/google/r/cloudfunctions_function.html#url and updating that commit when you want to redeploy.

This could be accomplished automatically if we were able to read the commit, such as with a[sourcerepo datasource](https://github.com/terraform-providers/terraform-provider-google/issues/2794). Unfortunately, that issue hasn't picked up much steam- :+1:ing it will help.

**Comment by dfang** [comment]
currently a hack like this works for me

```
labels = {
    last_deployed_at = "${timestamp()}"
}
``
