### ISSUE TITLE
google_compute_subnetwork  - removing 'log_config' block doesn't disable the Flow Logs

### ISSUE THREAD

**Issue by ocantov** [terraform-providers/terraform-provider-google#4881]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.14
+ provider.google v2.19.0

### Affected Resource(s)
google_compute_subnetwork

### Terraform Configuration Files

Initial Terraform code with Flow Logs enabled
```tf
resource "google_compute_subnetwork" "subnet-with-logging" {
  name          = "log-test-subnetwork"
  ip_cidr_range = "10.2.0.0/16"
  region        = "us-central1"
  network       = "${google_compute_network.custom-test.self_link}"
  #enable_flow_logs = false
   
  log_config {
    aggregation_interval = "INTERVAL_10_MIN"
    flow_sampling        = 0.5
    metadata             = "INCLUDE_ALL_METADATA"
  }
}

resource "google_compute_network" "custom-test" {
  name                    = "log-test-network"
  auto_create_subnetworks = false
}
```
New Terraform code without the 'log_config' argument

```tf
resource "google_compute_subnetwork" "subnet-with-logging" {
  name          = "log-test-subnetwork"
  ip_cidr_range = "10.2.0.0/16"
  region        = "us-central1"
  network       = "${google_compute_network.custom-test.self_link}"
  #enable_flow_logs = false

}

resource "google_compute_network" "custom-test" {
  name                    = "log-test-network"
  auto_create_subnetworks = false
}
```

### Debug Output

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

### Expected Behavior

The presence of 'log_config' block enables the Flow Logs option. If the 'log_config' block is removed, Terraform should detect the changes, update the resource in place and disable the Flow Logs option

### Actual Behavior
Terraform doesn't detect any changes when the 'log_config' block is removed 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rileykarson** [comment]
Right, so this case is a little unfortunate. Due to the specific attributes we used in the resource schema to represent the resource, Terraform loses track of `log_config` when it's unset (specifically, it considers it a computed value).

We'd tested disablement, but did it by using the old field. In `2.19.0`/`2.20.0`, you can disable flow logging by setting `enable_flow_logs = false` as an intermediary, shown below. This will work correctly in `3.0.0`, where we're able to change around the schema so that drift is detected again.

## Original Config

```hcl
resource "google_compute_subnetwork" "subnet-with-logging" {
  name          = "log-test-subnetwork"
  ip_cidr_range = "10.2.0.0/16"
  region        = "us-central1"
  network       = "${google_compute_network.custom-test.self_link}"
   
  log_config {
    aggregation_interval = "INTERVAL_10_MIN"
    flow_sampling        = 0.5
    metadata             = "INCLUDE_ALL_METADATA"
  }
}
```

## Intermediary Config

```hcl
resource "google_compute_subnetwork" "subnet-with-logging" {
  name          = "log-test-subnetwork"
  ip_cidr_range = "10.2.0.0/16"
  region        = "us-central1"
  network       = "${google_compute_network.custom-test.self_link}"

  enable_flow_logs = false
}
```

## New Config

```hcl
resource "google_compute_subnetwork" "subnet-with-logging" {
  name          = "log-test-subnetwork"
  ip_cidr_range = "10.2.0.0/16"
  region        = "us-central1"
  network       = "${google_compute_network.custom-test.self_link}"
}
```
