### ISSUE TITLE
Declare Cloud SQL instance for google_cloud_run_service

### ISSUE THREAD

**Issue by maxcct** [terraform-providers/terraform-provider-google#4885]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, I am imperatively deploying a Ghost blog instance via Google Cloud Run. The blog uses a Cloud SQL instance for storage. This is specified by passing the flag `--set-cloudsql-instances $CLOUD_SQL_INSTANCE_NAME` to the  `gcloud beta run deploy` command.

I'm now looking to deploy via Terraform instead, but I can't see any equivalent to `--set-cloudsql-instances` within [the docs](https://www.terraform.io/docs/providers/google/r/cloud_run_service.html) for `google_cloud_run_service`.

Am I missing something, or does support need to be added for this?

### New or Affected Resource(s)

* google_cloud_run_service

**Comment by chrisst** [comment]
Cloud Run is using a special annotation (`run.googleapis.com/cloudsql-instances`) on a given RevisionTemplate to attach the SQL instance. When v1 is launched I'll be adding support for the `annotations` block required for this.

here's a quick preview syntax:
```
template {
    metadata {
      annotations = {
        "autoscaling.knative.dev/maxScale"      = "1000"
        "run.googleapis.com/cloudsql-instances" = "namespace-id:us-east1:${google_sql_database_instance.instance.name}"
        "run.googleapis.com/client-name"        = "cloud-console"
      }
    }
```

will be fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/2740

**Comment by danawillow** [comment]
@chrisst is this done? can it be closed?
