### ISSUE TITLE
GKE cluster always updates even if there is no change

### ISSUE THREAD

**Issue by bharathiraja29** [terraform-providers/terraform-provider-google#4894]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.13
provider.google v2.5.1

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```
resource "google_container_cluster" "cluster" {

  name        = var.name
  description = var.description
  network    = var.network
  subnetwork = var.subnetwork

  logging_service    = var.logging_service
  monitoring_service = var.monitoring_service

  # with no   node pools.
  remove_default_node_pool = true

  initial_node_count = 1

  # ip_allocation_policy.use_ip_aliases defaults to true, since we define the block `ip_allocation_policy`
  ip_allocation_policy {
    // Choose the range, but let GCP pick the IPs within the range
    cluster_secondary_range_name  = var.cluster_secondary_range_pods
    services_secondary_range_name = var.cluster_secondary_range_services
  }

  # We can optionally control access to the cluster
  # See https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters
  private_cluster_config {
    enable_private_endpoint = var.disable_public_endpoint
    enable_private_nodes    = var.enable_private_nodes
    master_ipv4_cidr_block  = var.master_ipv4_cidr_block
  }
  master_auth {
    client_certificate_config {
      issue_client_certificate = false
    }
  }

  addons_config {
    http_load_balancing {
      disabled = ! var.http_load_balancing
    }

    horizontal_pod_autoscaling {
      disabled = ! var.horizontal_pod_autoscaling
    }

    kubernetes_dashboard {
      disabled = ! var.enable_kubernetes_dashboard
    }

    network_policy_config {
      disabled = ! var.enable_network_policy
    }
  }

  maintenance_policy {
    daily_maintenance_window {
      start_time = var.maintenance_start_time
    }
  }
}
```

### Expected Behavior

Terraform should not update when there is no change made in the resource. 

### Actual Behavior

Terraform always updates even when there is no change.
Since `master_authorized_networks_config` is a optional value, I did not add it in my resource.
But terraform marks this resource as deleting and tries to update the resource. 

### Steps to Reproduce

1. Create a `google_container_cluster` resource without `master_authorized_networks_config` config. 
2. Run `terraform apply`
3. After successful creation, without making any change to the resource run `terraform plan`.
4. The plan output will be `0 to Add, 1 to Change, 0 to Delete`. This is not expected since we do not make any change. 
5. If you still continue to run `terraform apply`, it will fail with `Error: googleapi: Error 400: Network "dedicated-interconnect-sharedvpc" does not exist., badRequest`

### Important Factoids
I fixed this by adding 
```
master_authorized_networks_config{

  }
```
to my code. 
But this is not the actual expected behavior. 

### References

* #0000

**Comment by rileykarson** [comment]
Can you reproduce this with a recent version like `2.20.0`? There've been extensive changes since `2.5.1`, and I wouldn't doubt it if this was fixed by coincidence since then.

If you're unable to upgrade, attaching debug logs would be a big help

**Comment by rileykarson** [comment]
Closing as stale.
