### ISSUE TITLE
Feature request - support for Network Intelligence

### ISSUE THREAD

**Issue by bluemalkin** [terraform-providers/terraform-provider-google#4895]
https://console.cloud.google.com/net-intelligence/ is now in Beta, it would be great to add support to Terraform.

**Comment by danawillow** [comment]
Closing due to lack of issue template

**Comment by bluemalkin** [comment]
@danawillow not sure why a feature request needs a "template" when it's a brand new F.R.

**Comment by danawillow** [comment]
This is what I'm talking about: https://github.com/terraform-providers/terraform-provider-google/issues/new?template=enhancement.md

When you go to https://github.com/terraform-providers/terraform-provider-google/issues/new/choose, you can choose the "enhancement" option to get there. By filling out the template, HashiBot will automatically label it, so when we're searching the issue tracker for FRs, we'll find it.
