### ISSUE TITLE
Add support for enabling/disabling google_service_account

### ISSUE THREAD

**Issue by ondrejklucka** [terraform-providers/terraform-provider-google#4903]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Service accounts have a [disabled](https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts#ServiceAccount) field, which is not yet supported by google_service_account resource.

### New or Affected Resource(s)

* google_service_account

### Potential Terraform Configuration

```tf
resource "google_service_account" "service-account" {
  account_id   = "abcd"
  disabled     = false
}
```

**Comment by marrau** [comment]
> disabled | boolean     A bool indicate if the service account is disabled. The field is currently in alpha phase.Note: This field is used in responses only. Any value specified here in a request is ignored.

I don´t think that it will work to set this field as it is ignored in a request. But in a response it makes sense if "alpha"-state is ok.

**Comment by ondrejklucka** [comment]
Hi @marrau, thanks for the update. Let's add the field once it's fully supported in REST API. I'll close the ticket for now.
