### ISSUE TITLE
Add region variable support for compute_target_https_proxy

### ISSUE THREAD

**Issue by richard-whitney-clover** [terraform-providers/terraform-provider-google#4914]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I am requesting that the google-beta provider allow clients to be able to pass the region input variable using the compute_target_https_proxy resource to create a region specific https_proxy. With v2.20.0 beta being released, our team was working on automating the creation of internal HTTPs load balancers with Terraform. We were able to duplicate all instructions from https://cloud.google.com/load-balancing/docs/l7-internal/set-up-gce-vms for setting up an i7 internal LB, but the one step that we cannot duplicate with terraform is setting the region for the compute_target_https_proxy.  Without being able to set the region, our https proxy is getting created in the Global space and regional load balancers cannot use them due to the below error:

Error creating ForwardingRule: googleapi: Error 400: Invalid value for field ‘resource.target’: ’https://www.googleapis.com/compute/v1/projects/<<project>>/global/targetHttpsProxies/service-vip-proxy'. Scope mismatch between forwarding rule and target proxy, forwarding rule scope: us-west1, target proxy scope: global., invalid

API allows region to be set per i7-internal documentation and the API documentation below:
https://cloud.google.com/compute/docs/reference/rest/beta/targetHttpsProxies

The terraform resources does not:
https://www.terraform.io/docs/providers/google/r/compute_target_https_proxy.html

### New or Affected Resource(s)

v.2.20.0 Terraform Google Beta Provider

* google-beta_v2.20

### Potential Terraform Configuration

Please add region variable to compute_target_https_proxy mimicking the current work being down for URL Maps with: https://github.com/terraform-providers/terraform-provider-google-beta/pull/1338

Terraform region input should be usable like the below example:
```
resource "google_compute_target_https_proxy" "service_vip" {
  provider = "google-beta"
  name = "service-vip-proxy"
  project = var.project
  region = var.region
  url_map = google_compute_url_map.service_vip.self_link
  ssl_certificates = [google_compute_ssl_certificate.service_vip.self_link]
}
```

**Comment by danawillow** [comment]
This was added in https://github.com/GoogleCloudPlatform/magic-modules/pull/2363 as `google_compute_region_target_https_proxy`, but the link to its documentation on the website was accidentally omitted. That will be fixed in the next few days, but in the meantime you can access it directly at: https://www.terraform.io/docs/providers/google/r/compute_region_target_https_proxy.html
