### ISSUE TITLE
Cloud SQL - Error, failure waiting for deletion of postgres

### ISSUE THREAD

**Issue by nikhilbalekundargi** [terraform-providers/terraform-provider-google#4915]
If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

When I destroy Postgres DB created on cloud sql getting the error - failure waiting for deletion of postgres

**Comment by slevenick** [comment]
Can you elaborate on the issue you are seeing, and provide the terraform config that you are running that causes the issue?

You could try increasing the waiting period that terraform waits for a successful operation:
https://www.terraform.io/docs/configuration/resources.html#operation-timeouts

**Comment by lpfeup** [comment]
I am having the same issue:

> Error: Error, failure waiting for deletion of postgres in dummy-db

when destroying with:
```
terraform destroy --target=google_sql_database_instance.default
```

with the following configuration:

```
terraform {
  required_version = "~> 0.12.16"

  backend "gcs" {
    bucket = "terraform-dummy-test"
    prefix = "infrastructure/terraform"
  }
}

provider "google" {
  region  = "europe-west2"
  version = "~> 2.20.1"
}

resource "google_compute_network" "default" {
  name                    = "dummy-network"
  auto_create_subnetworks = "true"
}

resource "google_compute_global_address" "database" {
  name          = "dummy-database-private-ip-address"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  network       = google_compute_network.default.self_link
}

resource "google_service_networking_connection" "database" {
  network                 = google_compute_network.default.self_link
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.database.name]
}

resource "google_sql_database_instance" "default" {
  name             = "dummy-db"
  database_version = "POSTGRES_11"

  settings {
    tier            = "db-f1-micro"
    disk_autoresize = true
    disk_type       = "PD_SSD"

    location_preference {
      zone = "europe-west2-a"
    }

    backup_configuration {
      enabled    = true
      start_time = "01:00"
    }

    maintenance_window {
      day  = 4
      hour = 5
    }

    ip_configuration {
      ipv4_enabled = true

      private_network = google_compute_network.default.self_link
    }
  }
}

resource "google_sql_user" "users" {
  name     = var.postgres_username
  instance = google_sql_database_instance.default.name
  password = var.postgres_password
}

```

**Comment by viktorbenei** [comment]
Seeing the same issue, once a Google Cloud SQL Postgres is created successfully with `terraform` and you try to `terraform destroy` it it'll hang at destroying `google_sql_user`.

**Comment by danawillow** [comment]
Hi @lpfeup, could you please file a new issue with the bug template fully filled out? It's hard for us to really know what's going on without the information we request there, especially the full error message and debug logs. Thanks!
