### ISSUE TITLE
google_cloudfunctions_function - Error code 7, message: Failed to retrieve function source code

### ISSUE THREAD

**Issue by Sciguymjm** [terraform-providers/terraform-provider-google#4932]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.15
+ provider.google v3.0.0-beta.1
```
### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files

```tf

resource "google_cloudfunctions_function" "function" {
  name        = "parse"
  description = "Parse replay"
  runtime     = "python37"

  available_memory_mb   = 1024
  timeout = 120
  source_repository {
    url = "https://source.developers.google.com/projects/1095751815127/repos/parse_replay/moveable-aliases/master/paths/"
  }
  trigger_http          = true
  entry_point           = "parse_replay"
}
```

### Debug Output

https://gist.github.com/Sciguymjm/ffb35e97f3a87ade1c29eddc1eec945f

### Expected Behavior

Cloud Function gets created and deployed.

### Actual Behavior

`
Error: Error waiting for Creating CloudFunctions Function: Error code 7, message: Failed to retrieve function source code`
Cloud Function is created, but fails to deploy.

### Steps to Reproduce

1. Create a Cloud Function config with a source repository as its source code.
1. `terraform apply`

### Important Factoids

1. Clicking "download zip" in the failed cloud function's edit area leads to a 404 Key not found on a Cloud Storage bucket.
1. It seems like the cloud function is set up correctly, because I can manually go in and click deploy with the settings that terraform set up. It just fails to retrieve the source through `terraform apply`.

**Comment by slevenick** [comment]
I believe this is an issue with the Cloud Function interacting with the code in your source repository. This error code comes up when it cannot find a valid entry point, probably because it can't find the index.js file

Can you make sure that you have a file named `index.js` in that repository, and that it has the `parse_replay` function defined?

**Comment by Sciguymjm** [comment]
It's a Python runtime so I'm not sure how it looks for an entrypoint in cloud functions.

**Comment by slevenick** [comment]
Right, so not `index.js` but it looks like the file should be named `main.py` and the function name has to match your `entry_point`, so `parse_replay`.

**Comment by Sciguymjm** [comment]
Yes, that exists, and I have another cloud function using the exact same repo/code and it works fine. Like I mentioned, when I deploy manually using the settings that terraform gives (by clicking edit on the broken terraform cloud function in the console, then clicking deploy), it then deploys and works perfectly.

**Comment by slevenick** [comment]
I was able to deploy a simple function using python via a source repository and terraform, so I'm not sure what to do here. The repository that you are using seems to be private, so I cannot access it.

I get the error code 7 when attempting to deploy based off of the repo that I do not have permission to access, could this be happening when you deploy via terraform?

Does the service account that you are using to run terraform have access to the source repository that contains the source code? If it works via the console but not terraform this could be the cause

**Comment by Sciguymjm** [comment]
You may be right - I'll test this, thanks. I feel like that's something that should be documented if it's not already.

**Comment by slevenick** [comment]
If you have a suggestion on where that should go I'm happy to consider it. I'm not entirely sure where that would go though, and error code 7 is an API-side error.
