### ISSUE TITLE
Unable to create External regional TCP Load balancer

### ISSUE THREAD

**Issue by ArnauFauquer** [terraform-providers/terraform-provider-google#4936]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I'm unable to create an external regional TCP Load balancer 

### New or Affected Resource(s)

google/compute_region_backend_service

### Potential Terraform Configuration

```tf
resource "google_compute_region_backend_service" "lb-backend" {
  health_checks = [google_compute_health_check.autohealing.self_link]
  name = var.project
  region = var.region
  load_balancing_scheme = "EXTERNAL"

resource "google_compute_health_check" "autohealing" {
  name = "autohealing-health-check"
  http_health_check {
    port = "80"
    host = "/"
  }
}
}
```

### References
https://www.terraform.io/docs/providers/google/r/compute_region_backend_service.html

**Comment by migibert** [comment]
I think this is not a good resource to create external load balancers;
As stated in the documentation:

> load_balancing_scheme - (Optional) Indicates what kind of load balancing this regional backend service will be used for. A backend service created for one type of load balancing cannot be used with the other(s). Must be INTERNAL or INTERNAL_MANAGED. Defaults to INTERNAL.

I used to use the following resources to manage external TCP load balancers:
* google_compute_instance_group_manager
* google_compute_global_forwarding_rule
* google_compute_target_http_proxy
* google_compute_url_map

Complete example:
```
resource "google_compute_global_address" "global-address" {
  provider = "google-beta"
  name     = "${var.name}"
  labels   = "${var.labels}"

  lifecycle {
    prevent_destroy = true
  }
}

resource "google_compute_global_forwarding_rule" "https-forwarding-rule" {
  provider    = "google-beta"
  name        = "${var.name}-https"
  target      = "${google_compute_target_https_proxy.https-proxy.self_link}"
  ip_address  = "${google_compute_global_address.global-address.address}"
  ip_protocol = "TCP"
  port_range  = "443"
  labels      = "${var.labels}"
}

resource "google_compute_global_forwarding_rule" "http-forwarding-rule" {
  provider    = "google-beta"
  name        = "${var.name}-http"
  target      = "${google_compute_target_http_proxy.http-proxy.self_link}"
  ip_address  = "${google_compute_global_address.global-address.address}"
  ip_protocol = "TCP"
  port_range  = "80"
  labels      = "${var.labels}"
}

resource "google_compute_target_http_proxy" "http-proxy" {
  name        = "${var.name}-http"
  description = "${var.name} HTTP proxy"
  url_map     = "${google_compute_url_map.url-map.self_link}"
}

resource "google_compute_target_https_proxy" "https-proxy" {
  name             = "${var.name}-https"
  description      = "${var.name} HTTPS proxy"
  url_map          = "${google_compute_url_map.url-map.self_link}"
  ssl_certificates = ["${var.certificate-self-link}"]
  ssl_policy       = "${google_compute_ssl_policy.ssl-policy.self_link}"
}

resource "google_compute_ssl_policy" "ssl-policy" {
  name        = "${var.name}"
  description = "${var.name} policy"
  profile     = "MODERN"
}

resource "google_compute_url_map" "url-map" {
  name            = "${var.name}"
  description     = "${var.name} url map"
  default_service = "${var.backend-service-self-link}"
}
```

It may have change a little bit but I think the general idea is still good.

**Comment by ArnauFauquer** [comment]
Thank you @migibert, I am sure that what you say can work for me. But the functionality of the resource should be the same as the console, right?.

**Comment by migibert** [comment]
Oh right, I just checked and I think the UI is misleading as it shows a simple way to configure the load balancer, but you can go in the "advanced menu" on which you will see the resources I mentioned.

![lb_advanced_menu](https://user-images.githubusercontent.com/488493/69072475-04960200-0a2c-11ea-8179-bf31f334fe3f.jpg)

**Comment by ArnauFauquer** [comment]
Researching more I found the most accurate solution and issue, thanks you @migibert https://github.com/terraform-providers/terraform-provider-google/issues/2373#issuecomment-434802918
