### ISSUE TITLE
Support compute.reservations.resize 

### ISSUE THREAD

**Issue by bmenasha** [terraform-providers/terraform-provider-google#4937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently when changing google_compute_reservation.specific_reservation.count Terraform will delete the existing reservation and attempt  to provision a new one. 

This can cause the loss of the existing whole reservation which can cause lots of problems for a zone under capacity pressure which is the whole point of this reservations feature!   

Can we please support the resize method  compute.reservations.resize  so a user can safely grow an existing reservation without losing the reservation when the new capacity fails to provision?

Thanks

### New or Affected Resource(s)
google_compute_reservation

**Comment by danawillow** [comment]
google-internal request: b/145758596
