### ISSUE TITLE
data.google_project.project.id output change from <project_id> to projects/<project_id>

### ISSUE THREAD

**Issue by abgm** [terraform-providers/terraform-provider-google#4947]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.13
Downloading plugin for provider "google" (hashicorp/google) 3.0.0-beta.1...

### Affected Resource(s)

* data.google_project.project.id (3.0.0-beta.1)

### Terraform Configuration Files

```tf
// project_id - (Optional) The project ID. If it is not provided, the provider project is used.
// we will use this to get the project form provider
// the provider will get the project from export GOOGLE_PROJECT=myprojectNPE or  export GOOGLE_PROJECT=myprojectPROD 
data "google_project" "project" {}
```

### Expected Behavior
Terraform plan with ``` No changes. Infrastructure is up-to-date.```

### Actual Behavior
All my Infrastructure need to be updated 
```    ~ project = "myProjectNPE" -> "projects/myProjectNPE" # forces replacement ```

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by slevenick** [comment]
Hey @abgm this is an intentional change in the format of the id for this datasource, and similar changes have been made to many resources for the 3.0.0 release.

I would recommend not depending on the `id` field prior to 3.0.0.

The fix in this case will be to change uses of `google_project.id` to `google_project.project_id` which is the value you expect, and will not cause infrastructure updates

**Comment by abgm** [comment]
Thanks @slevenick
