### ISSUE TITLE
google_composer_environment fails with terraform-provider-google_v3.0.0-beta

### ISSUE THREAD

**Issue by GeKasap** [terraform-providers/terraform-provider-google#4959]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.0
+ provider.google v3.0.0-beta.1
+ provider.google-beta v3.0.0-beta.1

### Affected Resource(s)

* google_composer_environment

### Terraform Configuration Files

https://github.com/GeKasap/terraform-google-composer

### Debug Output

https://gist.github.com/GeKasap/743b78ca90a16884b0d4544546f9e19c

### Expected Behavior

It should deploy a composer environment. That was working last week,.
### Actual Behavior
When I tried to deploy it on a different environment, it failed with no obvious reason. Finally I realized that the google plugin was in newer version. I have explicitly set google plugin to version 2.20 and I was able to deploy the environment.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by slevenick** [comment]
Hey @GeKasap this definitely looks like a problem. Could you include more complete debug logs? Specifically I would like to see the calls for that environment, as it seems like we are not handling the API's response correctly. It would be much easier to diagnose the issue with the response that is causing this failure, it should be directly above the panic

**Comment by slevenick** [comment]
One thing that jumps out at me is that the `use_ip_aliases` field in `ip_allocation_policy` is now required, but it is not specified in your config. If you specify that field is there any change?

**Comment by slevenick** [comment]
It looks like your config is invalid. According to the documentation: https://www.terraform.io/docs/providers/google/r/composer_environment.html

If you specify `ip_allocation_policy` you *must* specify `use_ip_aliases`, and you must specify either `cluster_secondary_range_name` or `cluster_ipv4_cidr_block` but not both. You must also specify either `cluster_ipv4_cider_block` or `cluster_secondary_range_name` but not both.
And these fields are only applicable if `use_ip_aliases` is set to `true`.

When I run this config I get validation errors: 
```
Error: "config.0.node_config.0.ip_allocation_policy.0.use_ip_aliases": required field is not set

  on t.tf line 8, in resource "google_composer_environment" "composer_env":
   8: resource "google_composer_environment" "composer_env" {

Error: "config.0.node_config.0.ip_allocation_policy.0.cluster_secondary_range_name": conflicts with config.0.node_config.0.ip_allocation_policy.0.cluster_ipv4_cidr_block

  on t.tf line 8, in resource "google_composer_environment" "composer_env":
   8: resource "google_composer_environment" "composer_env" {

Error: "config.0.node_config.0.ip_allocation_policy.0.services_secondary_range_name": conflicts with config.0.node_config.0.ip_allocation_policy.0.services_ipv4_cidr_block

  on t.tf line 8, in resource "google_composer_environment" "composer_env":
   8: resource "google_composer_environment" "composer_env" {

Error: "config.0.node_config.0.ip_allocation_policy.0.cluster_ipv4_cidr_block": conflicts with config.0.node_config.0.ip_allocation_policy.0.cluster_secondary_range_name

  on t.tf line 8, in resource "google_composer_environment" "composer_env":
   8: resource "google_composer_environment" "composer_env" {

Error: "config.0.node_config.0.ip_allocation_policy.0.services_ipv4_cidr_block": conflicts with config.0.node_config.0.ip_allocation_policy.0.services_secondary_range_name

  on t.tf line 8, in resource "google_composer_environment" "composer_env":
   8: resource "google_composer_environment" "composer_env" {
```

These errors were introduced with 3.0.0-beta, so I'm not sure why you are not seeing them. I would try updating your terraform core version

**Comment by GeKasap** [comment]
Thanks for the reply. Actually I had to update the code. I have the `use_ip_aliases` set to true by default. This error is with that parameter set.

**Comment by slevenick** [comment]
So, it looks like the config is still invalid and *should* fail at plan time. I'm not sure why you are able to run attempt to apply this config.

The fields `cluster_secondary_range_name` and `cluster_ipv4_cidr_block` are not allowed to be specified at the same time, as they conflict. Same with `services_secondary_range_name` and `services_ipv4_cidr_block`.

I'm unsure why you are able to attempt to apply this config, as new validation was added in 3.0.0 to error at plan time on this (as well as require `use_ip_aliases` to be specified)

Can you attempt to upgrade your version of terraform core?

**Comment by GeKasap** [comment]
Upgrading terraform to latest, caused me another issue that I have reported to  https://github.com/hashicorp/terraform/issues/23445 and was migrated to https://github.com/terraform-providers/terraform-provider-google/issues/4984
According to terraform when a variable has null value (which works for this version of TF) it is ommited. If you check `vars.tf`, default values for these parameters are `null`, so if not defined by the user, should be omitted and not fail.

**Comment by slevenick** [comment]
If you manually remove the fields that will be evaluated to `null` within `ip_allocation_policy` and set the others manually does it deploy?

What I'm trying to do is figure out if this is a provider issue or a terraform core issue caused by the variable evaluation. I believe it is a terraform core issue because the diff on the composer environment file between 2.20.0 and 3.0.0-beta does not include anything that I would expect to cause a panic in this method. 

This is the commit that contains the changes between 2.20.0 and 3.0.0: https://github.com/terraform-providers/terraform-provider-google/commit/1b413bcb4e704933b16f61207b4f70c0cb6a4dbb#diff-7477e5914f695a25c677ec26001c39b5

According to your debug logs the error is coming from: `google.expandComposerEnvironmentIPAllocationPolicy(0x292f880, 0xc0005d7e80, 0xc0003e9500, 0xc000180000, 0xc0008112d8, 0x0, 0x0)` but there were no changes to this method or anything significant surrounding it. The main difference is that there were restrictions introduced around `use_ip_aliases`

Due to the other issues you have run into around variable evaluation I would guess that is part of the issue

**Comment by GeKasap** [comment]
Hi @slevenick , first of all I want to thank you for the time you spend to reply to me.
I have sorted other issues that TF0.12.16 was causing to me and run the above code with the latest version (as you suggested initially). It worked perfectly without any issue.
So from my point, I think this should be closed.
