### ISSUE TITLE
`google_compute_network_peering` project field is required but cannot be set

### ISSUE THREAD

**Issue by rochdev** [terraform-providers/terraform-provider-google#496]
When creating a `google_compute_network_peering` resource with a provider with no default project, the following error is received:

```
* google_compute_network_peering.my_peering: "project": required field is not set
```

This is the expected behaviour. However, when adding the `project` field as requested on the resource, the following error is received:

```
* google_compute_network_peering.my_peering: : invalid or unknown key: project
```

The resource should support the `project` field for Terraform configurations without a default project on the provider.

**Comment by rochdev** [comment]
Closing in favor of https://github.com/terraform-providers/terraform-provider-google/pull/498

**Comment by rosbo** [comment]
Reopening, #498 is a PR fixing your issue :)

**Comment by rochdev** [comment]
Yes I meant to do that on my own PR sorry :)
