### ISSUE TITLE
google_folder_iam_policy import misbehaves if given a bare folder id

### ISSUE THREAD

**Issue by rvandegrift** [terraform-providers/terraform-provider-google#4971]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```$ terraform -v
Terraform v0.12.16
+ provider.google v2.20.0
```

### Affected Resource(s)

* google_folder_iam_policy

### Terraform Configuration Files

```tf
resource "google_folder_iam_policy" "policy" {
    folder = google_folder.stuff.name
    policy_data = data.google_iam_policy.stuff.policy_data
}
```    

### Expected Behavior

I can import by running the following:
`terraform import google_folder_iam_policy.stuff 234421525268`

At this point, I'd expect the resource to be correctly imported, but running plan will show that it is not:
```
-/+ resource "google_folder_iam_policy" "stuff" {
      ~ etag        = "T2pKSHdydGFIR0Q9Cg==" -> (known after apply)
      ~ folder      = "234421525268" -> "folders/234421525268" # forces replacement
      ~ id          = "234421525268" -> (known after apply)
    }
```

terraform should've stored the relative resource name of the folder instead of the bare folder id.  That would ensure that the folder wouldn't be replaced.

The correct behavior is achieved by importing this way:
`terraform import google_folder_iam_policy.stuff folders/234421525268`

terraform should either always store the relative resource name of the folder (ie `folders/<folder_id>`) in the state, or require the user to supply `folders/` on the import command line.

### Actual Behavior

terraform stores the folder id on import, which causes it to try and replace it on the next plan/apply cycle.

**Comment by slevenick** [comment]
I have a fix for this in the pipeline, but until that gets released I would recommend using the format `terraform import google_folder_iam_policy.stuff folders/234421525268` as you found

**Comment by rvandegrift** [comment]
great, thanks!

**Comment by slevenick** [comment]
This will be in the 3.1.0 release of the provider
