### ISSUE TITLE
Cloud Armor, google_compute_security_policy, how can I add the target LB backend?

### ISSUE THREAD

**Issue by meirhazon2** [terraform-providers/terraform-provider-google#4973]
Hello,
I am using terraform to create cloud armor rules, I miss the target part (LB backends).
How can it be done?
Thanks so much,
Meir

**Comment by c3st7n** [comment]
You need to add the security policy to the backend service instead. Take a look at the docs for google_compute_backend_service, the security-policy argument.

**Comment by meirhazon2** [comment]
Thanks so much

**Comment by meirhazon2** [comment]
What should the security_policy be then, in the case of cloud armor?
Thanks

**Comment by c3st7n** [comment]
I wasn't sure but I just tried using the self_link of the security policy and it worked.

**Comment by meirhazon2** [comment]
I have looked into this and we are using kubernetes_ingress to create the backend. I dont see a security_policy attribute in this module. any suggestion? thanks so much

**Comment by slevenick** [comment]
I believe you will need to specify the https://www.terraform.io/docs/providers/google/r/compute_backend_service.html#security_policy field on the backend service. If you are using a module to create the backend service you may be able to pass this field as a variable to the module, but it depends on how the module is set up.

Normally you would do something like this in your `google_compute_backend_service`:
```hcl
security_policy = google_compute_security_policy.my-policy.self_link
```

**Comment by meirhazon2** [comment]
Thanks so much @slevenick , we are using kubernetes_ingress to create the backend services today and not google_compute_backend_service, do you suggest changing this and use google_compute_backend_service instead? it would be quite a big change.

**Comment by slevenick** [comment]
I don't know what makes sense for your particular use case.

Just providing information around how to use the provider

**Comment by meirhazon2** [comment]
Looks like there is no possible way to use cloud armor with kubernetes_ingres. please correct me if I am wrong, Thanks

**Comment by slevenick** [comment]
I'm not familiar with kubernetes_ingress, so I do not know

**Comment by meirhazon2** [comment]
thanks
