### ISSUE TITLE
Docs Isse Dataflow job IP Configuration

### ISSUE THREAD

**Issue by jaketf** [terraform-providers/terraform-provider-google#4987]
The Terraform Google Provider [docs for google_dataflow_job ip_configuration](https://www.terraform.io/docs/providers/google/r/dataflow_job.html#ip_configuration)
incorrectly lists options duplicating `"WORKER_IP_PUBLIC"` rather than enumerating `"WORKER_IP_PUBLIC"` and `"WORKER_IP_PRIVATE"`. However the [source code for this block](https://github.com/terraform-providers/terraform-provider-google/blob/b278a0ac3b14c5125d418d8b9f91c958ee9dc288/google/resource_dataflow_job.go#L126-L131) does seem to support WORKER_PRIVATE_IP. 
I believe this is a typo.

**Comment by megan07** [comment]
Thanks @jaketf for opening this issue!  It's been closed with #4806 and will be released shortly.
