### ISSUE TITLE
cloud nat - add network to vm instance

### ISSUE THREAD

**Issue by pc-dok** [terraform-providers/terraform-provider-google#5015]
hi all

i am on the way to create a new lab in gcp. i am before in Azure so here are some differncies. what i am trying is, to create a bunch of vm´s where i do not want always have a public IP for this vm´s, but i want Internet connection for all of this vm´s. so i read that you need here the cloud nat solution. what i have now create is a VPC, with default Subnets, and than i try to create with terraform also the router and the nat gateway. but i do not know, how i can now associate this nat gw with the vm´s. so have someone a complete example for me, how i create from the scratch a VM with Internet with a NAT Cloud and that all in terraform, maybe with a special Subnet not only the default. would be great to get help here:

my code meanwhile:

provider "google" {
  credentials = file("account.json")
  project     = var.gcp_project
  region      = var.region
  zone        = var.zone
}
resource "google_compute_network" "vpc1" {
  name                    = var.vpc-name-1
  auto_create_subnetworks = true
}

resource "google_compute_subnetwork" "subnet" {
  name          = "${var.gcp_project}-subnet-01"
  network       = google_compute_network.vpc.self_link
  ip_cidr_range = "172.21.2.0/24"
  region        = var.region
}

resource "google_compute_router" "router" {
  name    = "${var.gcp_project}-router-01"
  region  = google_compute_subnetwork.subnet.region
  network = google_compute_network.vpc.self_link

  bgp {
    asn = 64514
  }
}

resource "google_compute_router_nat" "nat" {
  name                               = "${var.gcp_project}-router-nat-01"
  router                             = google_compute_router.router.name
  region                             = google_compute_router.router.region
  nat_ip_allocate_option             = "AUTO_ONLY"
  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"

  log_config {
    enable = true
    filter = "ERRORS_ONLY"
  }
}

resource "google_compute_instance" "vm_mdt" {
  name                    = var.vm-mdt
  machine_type            = "n1-standard-2"
  metadata = {
    Install = file("cloud.ps1")
  }

  boot_disk {
    initialize_params {
      image       = "windows-cloud/windows-2019"
      size        = "100"
      type        = "pd-ssd"
    }
  }

  network_interface {
    network = "default"
    access_config {
    }
  }
}

thanks and best regards franco

**Comment by pradeepbhadani** [comment]
@pc-dok  - you can leverage the google cloud NAT terraform module to create one in your project.
Here is the CLoud NAT module https://github.com/terraform-google-modules/terraform-google-cloud-nat and it has some examples as well https://github.com/terraform-google-modules/terraform-google-cloud-nat/tree/master/examples

**Comment by pc-dok** [comment]
i know that example, but it is not helpful for me. i  must know how i add now a network interface to the vm with the right subnet. that is what i am searching for. what is the part than on creating a compute instance to take than the cloud-nat for internet breakout. so i need a example from google_compute_instance. thx and best regards franco

**Comment by pradeepbhadani** [comment]
@pc-dok  you configure a `subnetwork` to use `Cloud NAT` and under your VM config, you can mention it to use the `subnetwork` like below :

```
  network_interface {
    network = "<your-network-selflink>"
    subnetwork = "<your-subnetwork-selflink>"
  }
```

**Comment by pc-dok** [comment]
hi prad
thx for helping and pointing me in the right direction. is it possible to wrote me, where in my code you define cloud-nat in the subnetwork ressource? or i mean, did you know if there is an example from the beginning, to create a bunch of vm's with cloud-nat as solution to have internet connection? so with all rg's what we need for that this will work. or is my code ok? only some lines of code what are not correct?
regards franco

**Comment by pradeepbhadani** [comment]
I am not able to run your code and identify the exact issue at the moment.
but having a quick look, you are trying to create a new `VPC` with name `var.voc-name-1` but in VM config you are setting it to `default`. So your VM will live in `default` VPC not in the one you are creating.

To create VM in the newly created VPC, update the `network_interface` as below:
```
network_interface {
network = google_compute_network.vpc1.self_link
subnetwork = google_compute_subnetwork.subnet.self_link
}
```

Also, you `subnet` block is referring to `google_compute_network.vpc.self_link`, it should be `google_compute_network.vpc1.self_link`

**Comment by pc-dok** [comment]
hi prad
i think i have now the right configuration. so cloud-nat is working, my vm has internet connection and i can connect over IAP (gcloud compute start-iap-tunnel) a RDP Session to the host. so that is working fine. only one thing i dont understand here. if i have also create a VPN Tunnel from Google to my Home Office, why i can than not connect directly over RDP to the VM. Without Cloud-NAT that works as a charme. Is there any Forwarding Rule or Firewall Rule where i must add? so to be clear, i want have Internet on all VM´s, that i can get running with Cloud-NAT Service. I also want have a VPN Tunnel to my Home Office, where i want connect directly over RDP to the vm´s. What i must make for that example?

best regards and big thanks that you point me right

franco

**Comment by pradeepbhadani** [comment]
@pc-dok Cloud-NAT is for outbound Internet access and you are creating a VPN tunnel for the inbound connection.. right?
Not sure why VPN tunnel is not behaving properly with Cloud NAT. Can you check you have a Firewall Rule which allows inbound RDP access to your VM from your VPN Server and you can connect your VPN server from your home network on that port as well?

**Comment by pc-dok** [comment]
hi prad.
yes i have forgotten to make also a Firwall Rule also for VPN Subnet, now IAP and also direct rdp sessions are working. wow, cool. it works. best thanks for supporting me here.
