### ISSUE TITLE
google_monitoring_alert_policy - Understanding flapping 

### ISSUE THREAD

**Issue by freakssy** [terraform-providers/terraform-provider-google#5016]
### **Terraform Version**
Terraform v0.12.16

### **Affected Resource(s)**
google_logging_metric and google_monitoring_alert_policy

### **Terraform Configuration Files**
```
variable "kube_events" {
  type = set(string)

  default = [
    "FailedScheduling",
    "BackOff",
    "Killing",
    "Unhealthy",
    "FailedCreatePodSandBox",
  ]
}

resource "google_logging_metric" "kube_events" {
  for_each = var.kube_events

  name   = each.value
  filter = <<EOT
resource.labels.cluster_name="${terraform.workspace}" AND
jsonPayload.reason="${each.value}"
EOT
  metric_descriptor {
    metric_kind = "DELTA"
    value_type  = "INT64"
  }
}

resource "google_monitoring_alert_policy" "kube_events" {
  for_each = var.kube_events

  display_name = "${terraform.workspace} - Container - ${each.value}"
  combiner     = "OR"
  notification_channels = [
    google_monitoring_notification_channel.slack.name
  ]

  conditions {
    display_name = google_logging_metric.kube_events[each.value].name
    condition_threshold {
      filter          = <<EOT
metric.type="logging.googleapis.com/user/${google_logging_metric.kube_events[each.value].name}" AND
resource.type="k8s_pod"
EOT
      duration        = "60s"
      threshold_value = 0
      comparison      = "COMPARISON_GT"
      aggregations {
        group_by_fields = [
          "metadata.user_labels.app"
        ]
       }
    }
  }
}
```
### **Result**
![image](https://user-images.githubusercontent.com/22796433/69809954-1d03da80-11eb-11ea-9631-623e64a5c672.png)

A new incident is created approximately every 5 minutes and resolved. 

### **expected Behavior**
Only one incident must be created and stay in this state until resolution

**Comment by ndmckinley** [comment]
@freakssy From the information here, it feels likely that the event was truly flapping - that this is unrelated to Terraform configuration.  My recollection of k8s is that this is fairly common.  You can see that each of the events has a duration of 1 minute, meaning that the condition was checked 60 seconds later and found to be fixed.

You could try increasing the `google_monitoring_alert_policy.conditions.duration` from 60s to 600s, which would have caused all these incidents to be grouped into one incident - but that will increase detection time to ten minutes, which may be unacceptable, and if a flap lasted longer than 10 minutes, it would close the incident and create a new one.

Do you have any reason to believe that the `FailedScheduling` event was not truly flapping?

**Comment by ndmckinley** [comment]
Going to close - please comment if you need this reopened.
