### ISSUE TITLE
Override network_interface.access_config using variable

### ISSUE THREAD

**Issue by nodesocket** [terraform-providers/terraform-provider-google#502]
I am attempting to override the `access_config` in `google_compute_instance` with a dynamic map variable:

```
variable "network_access_config" {
    type = "map"
    default = {
        nat_ip = "${google_compute_address.web.address}"
    }
    description = "Optional network configuration"
}
```

```
...
network_interface {
    network = "default"
    access_config = "${var.network_access_config}"
}
...
```

But getting:

    * network_interface.0.access_config: should be a list

Any ideas?

**Comment by sl1pm4t** [comment]
Does this work:
```
access_config = ["${var.network_access_config}"]
```

**Comment by nodesocket** [comment]
@sl1pm4t still didn't work. See below. Everything I see in docs says `access_config` should be a `map` not a `list`.

```
network_interface {
        network = "default"
        access_config = ["${var.network_access_config}"]
    }
```

**Comment by danawillow** [comment]
@nodesocket, where are you seeing `access_config` documented as a map? It's definitely a list in Terraform. I'm also pretty sure that Terraform as a whole doesn't support variables being full blocks of a resource like this. @paddycarver, is that correct?

**Comment by nodesocket** [comment]
Forgive me if I am wrong, but don't braces `{}` indicate a map vs `[]` a list?

```
network_interface {
    network = "default"

    access_config {
      // Ephemeral IP
    }
  }
```

**Comment by danawillow** [comment]
The short answer is that if it's a list or map of primitives then yes (such as tags or labels), but if it contains sub-fields then no. I can explain further if you're interested, but it'll take me a bit of time to write it out. If you're familiar with go, it might be easiest to just see what's going on in the code: https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_instance.go#L288

**Comment by paddycarver** [comment]
> I'm also pretty sure that Terraform as a whole doesn't support variables being full blocks of a resource like this. @paddycarver, is that correct?

That really heavily depends on the implementation of the resource blocks, because resource blocks can be:

* maps
* lists
* sets
* lists of maps
* maps of lists
* sets of lists of maps of ....
* etc.

Because there are so many ways of implementing these that are represented with the same HCL syntax, it's super hard to know what the underlying type is. Further, complex types (sets, lists, maps, etc.) are a bit complicated when it comes to variables, modules, etc. right now.

My recommendation on this: you _may_ be able to get something working, but it's going to be a lot of trial and error, and it may only work accidentally and may break in future versions of Terraform. I'd not rely on this behaviour, personally. This isn't a recommendation I feel great about giving, and it's something the core team is paying a lot of attention to, but at the moment using complex types with variables is a bit tricky.

**Comment by nodesocket** [comment]
@paddycarver and @danawillow ok I modified the module to do the following instead:

```
variable "nat_ip" {
    default = ""
    description = "NAT ip configuration for each instance"
}

resource "google_compute_instance" "caddy" {
    ...
    network_interface {
        network = "default"
        access_config = {
            nat_ip = "${var.nat_ip}"
        }
    }
    ...
}
```

Then instantiating the module:

```
resource "google_compute_address" "web" {
    name = "web"
}

resource "google_dns_record_set" "api" {
    name = "api.mydomain.io."
    type = "A"
    ttl = 60

    managed_zone = "mydomain"
    rrdatas = [
        "${google_compute_address.web.address}"
    ]
}

module "web" {
    source = "modules/caddy"
    name = "web"
    nat_ip = "${google_compute_address.web.address}"
    ssh_private_key = "~/.ssh/google_compute_engine"
}
```

Any improvement there?

**Comment by paddycarver** [comment]
The only thing to note is that if no value is given to the `nat_ip` variable, an ephemeral IP will be allocated and associated with the resource. Looking at the code, there doesn't appear to be a way to let module consumers choose between a specified IP address or no address, at the moment. If that's an important use case for you, it's probably best to open a feature request issue for that.

**Comment by nodesocket** [comment]
@paddycarver not sure I follow what you are saying. Just tested the module without specifying `nat_ip` and it worked, GCP allocated an `ephemeral` to the instance.

```
module "web" {
    source = "modules/caddy"
    name = "web"
    ssh_private_key = "~/.ssh/google_compute_engine"
}
```

**Comment by paddycarver** [comment]
Hi @nodesocket, I think we solved the problem here, so I'm going to close this issue out. If I'm mistaken, and there's still a problem to be solved, please feel free to reply and we can reopen this. Thanks!
