### ISSUE TITLE
Unable to set availability_type

### ISSUE THREAD

**Issue by m477r1x** [terraform-providers/terraform-provider-google#5022]
### Terraform Version

Terraform v0.11.14
+ provider.google v2.20.0
+ provider.random v2.2.1

### Affected Resource(s)

* google_sql_database_instance

### Debug Output

https://gist.github.com/m477r1x/4a1ea827ca6fcf37c9bf8713a96b582d

### Expected Behavior

I was expecting the following output which is successful if you run the command on the CLI.

```gcloud sql instances patch REDACTED --availability-type REGIONAL --enable-bin-log
The following message will be used for the patch API method.
{"project": "REDACTED", "name": "REDACTED", "settings": {"availabilityType": "REGIONAL", "backupConfiguration": {"kind": "sql#backupConfiguration", "enabled": true, "startTime": "02:00", "binaryLogEnabled": true}}}
Patching Cloud SQL instance...
```

### Actual Behavior

The terraform did not apply. The binary logging is set to enabled in this terraform job, as it is required in order to enable the HA on the instance.

**Comment by venkykuberan** [comment]
@m477r1x  sorry for the delay in response. If you still have that issue, in order to set HA for  MYSQL_5_x instances you need to enable Binary Logging flag. This setting is not required for PostgreSQL.
 
```
resource "google_sql_database_instance" "test" {
  name              = "test-sql4"
  region            = "us-central1"
  database_version  = "MYSQL_5_7"
  
  
  settings {
    # Second-generation instance tiers are based on the machine
    # type. See argument reference below.
    tier = "db-f1-micro"
    availability_type = "REGIONAL"
    backup_configuration {
      binary_log_enabled = true
      enabled=true
    }
    }
}
```

**Comment by venkykuberan** [comment]
[Doc](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#availability_type) need to be updated that  **binary_log_enabled** flag to be enabled for MYSQL instance type for the DB instance to be regional and High Available.

**Comment by m477r1x** [comment]
Hi,

Thank you for your response. I can confirm that binary logging is set to enabled as I did state in my original issue. However the problem is present regardless.

Thank you
Matt

**Comment by danawillow** [comment]
Can you please post the config that isn't working and debug logs as requested in the original issue template? https://www.terraform.io/docs/internals/debugging.html explains how to do so. Without the config, we can't accurately reproduce the issue.
