### ISSUE TITLE
Version v3.0.0-beta.1 breaks when using alternative dynamic blocks

### ISSUE THREAD

**Issue by flelli** [terraform-providers/terraform-provider-google#5024]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.12.9
+ provider.aws v2.40.0
+ provider.google v3.0.0-beta.1
```

### Affected Resource(s)

* google_compute_firewall
* google_compute_health_check

### Terraform Configuration Files

```tf
resource "google_compute_firewall" "compute_firewall_rule" {

  for_each                  = var.rules

  name                      = each.key
  description               = each.value.description

  project                   = var.project
  network                   = var.network

  disabled                  = var.disabled
  priority                  = each.value.priority
  direction                 = each.value.direction

  source_ranges             = each.value.direction == "INGRESS" ? each.value.ip_ranges : null
  destination_ranges        = each.value.direction == "EGRESS" ?  each.value.ip_ranges : null
  source_tags               = each.value.direction == "INGRESS" ? each.value.source_tags : null
  target_tags               = each.value.target_tags

  dynamic "allow" {
    for_each = each.value.allow
    content {
      protocol                = allow.value.protocol
      ports                   = allow.value.ports
    }
  }

  dynamic "deny" {
    for_each = each.value.deny
    content {
      protocol                = deny.value.protocol
      ports                   = deny.value.port
    }
  }
}
```

### Expected Behavior
Provided that only allow OR deny variables are passed, the resource should have been applied without errors, just like when using the plugin version 2.20.0.

### Actual Behavior
```
Error: "allow": only one of `allow,deny` can be specified, but `allow,deny` were specified.

  on modules/gcp/network/firewall/main.tf line 1, in resource "google_compute_firewall" "compute_firewall_rule":
   1: resource "google_compute_firewall" "compute_firewall_rule" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It works correctly in version 2.20.0.

### References

* #0000

**Comment by tysen** [comment]
3.0.0 adds some restrictions to configs like marking some fields as members of `ExactlyOneOf` sets, which applies here. Unfortunately, you have discovered an instance of the SDK not nicely handling the combination of `ExactlyOneOf` and dynamic blocks.

**Comment by morgante** [comment]
@tysen Is there any workaround? I don't think we should add constraints which will prevent using dynamic blocks.

As it is now, we will be unable to upgrade major Terraform modules to 3.0. FYI @danawillow

**Comment by danawillow** [comment]
I would recommend filing an issue against Terraform to see if this can be fixed on their end. It's not that we're adding constraints that prevent using dynamic blocks, it's that a dynamic block with no content is being seen as set instead of unset.

**Comment by flelli** [comment]
I don't know the internals but I wonder I it could work before v3.0.0-beta.1

**Comment by danawillow** [comment]
The reason why it probably worked before 3.0 is that we didn't add the `ExactlyOneOf` validations until then- so the TF bug was still there, it just got triggered when we added the validations.

**Comment by morgante** [comment]
Ok I opened an [upstream issue](https://github.com/hashicorp/terraform/issues/23668) but keep in mind that this will prevent modules from upgrading to the 3.0 provider - it might be worth relaxing the constraint until the upstream bug is fixed.

**Comment by danawillow** [comment]
If we relax the constraint and then add it back, adding it back would be a breaking change, which would require another major release.

**Comment by morgante** [comment]
@danawillow The resources I've noticed this being an issue for, in priority order:
- google_compute_firewall
- google_folder_organization_policy
- google_organization_policy
- google_project_organization_policy
- google_compute_health_check
- google_compute_region_health_check
- google_compute_route (still need to confirm workarounds)
