### ISSUE TITLE
Adding support for app engine flexible app version

### ISSUE THREAD

**Issue by jackap** [terraform-providers/terraform-provider-google#5025]
### Community Note
I am asking this here because I did not find any resource online
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
It would be good to have the possiblity of introducing flexible applications in app engine. At the moment this is not possible. The only supported resource is: `google_app_engine_standard_app_version`. One solution could be adding a new resource or refactoring the existing one so that one could specify the type of application.

### New or Affected Resource(s)
The new resource name might be:

* google_app_engine_flex_app_version

### Potential Terraform Configuration

```tf
resource "google_app_engine_flex_app_version" "myapp_v1" {
  version_id = "v1"
  service    = "myapp"
  runtime    = "nodejs10"

  entrypoint {
    shell = "node ./app.js"
  }

  deployment {
    zip {
      source_url = "https://storage.googleapis.com/${google_storage_bucket.bucket.name}/${google_storage_bucket_object.object.name}"
    }
  }

  env_variables = {
    port = "8080"
  }

  delete_service_on_destroy = true
}
```

### References
https://www.terraform.io/docs/providers/google/r/app_engine_standard_app_version.html

* #0000

**Comment by dlee** [comment]
Please support custom runtimes to allow running custom Dockerfiles on App Engine: https://cloud.google.com/appengine/docs/flexible/custom-runtimes/about-custom-runtimes?hl=en

Also, please support `beta_settings.cloud_sql_instances` (https://cloud.google.com/sql/docs/postgres/connect-app-engine) to allow connecting to Cloud SQL for PostgreSQL without VPC.

<img width="872" alt="Screen Shot 2020-02-11 at 10 04 58 AM" src="https://user-images.githubusercontent.com/7035/74264776-1ba86100-4cb6-11ea-810a-111d23aa7134.png">
