### ISSUE TITLE
`node_version` cannot be updated on `google_container_cluster` if no common version exists on master and node

### ISSUE THREAD

**Issue by rochdev** [terraform-providers/terraform-provider-google#503]
If there are no common versions on the master and node, updating `node_version` always results in an error. One way to solve this would be having a separate `master_version`. It would also make updating safer as the master and nodes could be updated separately.

For example, given the following available versions:

```
$ gcloud container get-server-config 
Fetching server config for us-east1-b
defaultClusterVersion: 1.7.5-gke.1
defaultImageType: COS
validImageTypes:
- COS
- UBUNTU
validMasterVersions:
- 1.7.6-gke.1
- 1.7.5-gke.1
- 1.6.10-gke.1
validNodeVersions:
- 1.7.6
- 1.7.5
- 1.7.4
- 1.7.3
- 1.7.2
- 1.6.10
- 1.6.9
- 1.6.8
- 1.6.7
- 1.6.4
- 1.5.7
```

The following error is received when trying to update to `1.7.6-gke.1`:

```
* google_container_cluster.primary: googleapi: Error 400: bad desired node version (1.7.6-gke.1)., badRequest
```

The master did, however, get updated properly since `1.7.6-gke.1` is a valid master version.

The same also fails if updating to an available node version, which will simply fail since the master cannot be updated to the provided version.

**Comment by rochdev** [comment]
If the `node_version` is not changed, Terraform still attempts to update it on subsequent `apply` since it detects that the actual node version in GCP is different than the one specified in Terraform. 

The only way to avoid this at the moment is to create `google_container_cluster` with the master version in `node_version`, and once created change it to the node version from GCP so Terraform detects no change.

**Comment by choliver** [comment]
This feels pretty related to #503 FWIW.

**Comment by rochdev** [comment]
Duplicate of #492
