### ISSUE TITLE
Use different example in dataflow tests

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#5046]
Our tests run against the deprecated [WordCount example pipeline](https://cloud.google.com/dataflow/examples/wordcount-example), which uses an old SDK version. The new WordCount templates are at `gs://dataflow-templates/latest/Word_Count`. Old ones will start failing eventually. The new ones also add some labels to the job so that'll have to be fixed too.

**Comment by emilymye** [comment]
Closing and tracking in https://github.com/terraform-providers/terraform-provider-google/issues/5038
