### ISSUE TITLE
b/144576075

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#5049]

**Comment by danawillow** [comment]
@chrisst we weren't totally sure whether this is essentially done, or should continue into sprint 6. can you update it?

**Comment by chrisst** [comment]
I have a handful of follow up bugs to finish on this, so unfortunately sprint 6 it is.

**Comment by chrisst** [comment]
closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/3160
