### ISSUE TITLE
The example format for gooogle_container_cluster in doc for recurring_window returns invalid error.

### ISSUE THREAD

**Issue by inductor** [terraform-providers/terraform-provider-google#5052]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

0.12.18

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "foo-cluster" {
  provider = google-beta

  maintenance_policy {
    recurring_window {
      start_time = "2019-01-01T03:00:00Z09:00"
      end_time   = "2019-01-01T06:00:00Z09:00"
      recurrence = "FREQ=DAILY"
    }
  }
}
```

I tried all of these combinations and they all got error.

```
      start_time = "2019-01-01T03:00"
      end_time   = "2019-01-01T06:00"
```

```
      start_time = "2019-01-01T03:00:00+0900"
      end_time   = "2019-01-01T06:00:00+0900"
```

### Panic Output

```
Error: parsing time "2019-01-01T06:00:00+0900" as "2006-01-02T15:04:05Z07:00": cannot parse "+0900" as "Z07:00"

  on foo-cluster.tf line 150, in resource "google_container_cluster" "foo-cluster":
 150: resource "google_container_cluster" "foo-cluster" {

Error: parsing time "2019-01-01T03:00:00+0900" as "2006-01-02T15:04:05Z07:00": cannot parse "+0900" as "Z07:00"

  on foo-cluster.tf line 150, in resource "google_container_cluster" "foo-cluster":
 150: resource "google_container_cluster" "foo-cluster" {
```

```
Error: parsing time "2019-01-01T03:00:00Z09:00": extra text: 09:00

  on foo-cluster.tf line 150, in resource "google_container_cluster" "foo-cluster":
 150: resource "google_container_cluster" "foo-cluster" {

Error: parsing time "2019-01-01T06:00:00Z09:00": extra text: 09:00

  on foo-cluster.tf line 150, in resource "google_container_cluster" "foo-cluster":
 150: resource "google_container_cluster" "foo-cluster" {
```

### Expected Behavior

Allow the time format as documented

### Actual Behavior

It returns an invalid error

### Steps to Reproduce

1. `terraform plan` with the above preference

### References

Based on the [test](https://github.com/terraform-providers/terraform-provider-google-beta/blob/121f77b0cfe77ad5fe87182f24b511c3c08f4324/google-beta/resource_container_cluster_test.go#L1083), it only validates `2019-01-01T00:00:00Z` format and I would like to add my timezone for this. Is it possible?

**Comment by venkykuberan** [comment]
@inductor 
 Using the following format i am able to create the cluster successfully.
resource "google_container_cluster" "foo-cluster" {
  provider = google-beta
  name = "test-cluster"
  initial_node_count=1

  maintenance_policy {
    recurring_window {
      **start_time = "2019-01-01T03:00:00+09:00"
      end_time   = "2019-01-01T08:00:00+09:00"**
      recurrence = "FREQ=DAILY"
    }
  }
}

**Comment by inductor** [comment]
@venkykuberan

The point was that the document example did not work.

**Comment by venkykuberan** [comment]
@inductor 
 The [doucment](https://www.terraform.io/docs/providers/google/r/container_cluster.html#maintenance_policy) says:
``` daily_maintenance_window - (Required in GA, Optional in Beta) Time window specified for daily maintenance operations. Specify start_time in RFC3339 format "HH:MM”, where HH : [00-23] and MM : ```
I tested different time zones with RFC3339 formats. It worked fine, i didn't get any parsing error. Please check you are using the RFC3339, i see in your example missing the colon for last part

Time zones tested:
UTC-11 - 2019-12-19T11:33:39-08:00
AST - 2019-12-19T22:39:11+03:00
UTC - 2019-12-19T19:42:19+00:00

**Comment by inductor** [comment]
@venkykuberan The following part of the doc is what I tried as I wrote in the original issue 🤒 
It got error with

```
      start_time = "2019-01-01T03:00"
      end_time   = "2019-01-01T06:00"
```

<img width="866" alt="スクリーンショット 2019-12-20 9 50 55 1" src="https://user-images.githubusercontent.com/20236173/71221039-3e4d7780-230e-11ea-8768-f043b50aea09.png">

**Comment by venkykuberan** [comment]
@inductor Sorry for misinterpretation. We will fix the documentation.
