### ISSUE TITLE
Stackdriver Service Monitoring

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#5058]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services.serviceLevelObjectives

### New or Affected Resource(s)

* google_monitoring_service
* google_monitoring_slo (or service_level_objective)

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

b/142965924

**Comment by danawillow** [comment]
`google_monitoring_custom_service` and `google_monitoring_app_engine_service` added in https://github.com/GoogleCloudPlatform/magic-modules/pull/3341
`google_monitoring_slo` added in https://github.com/GoogleCloudPlatform/magic-modules/pull/3363

All 3 will be in v3.18.0, releasing later today.

Keeping this issue open for now as per comment in https://github.com/GoogleCloudPlatform/magic-modules/pull/3341:
> Add other datasources google_monitoring_cloud_endpoints_service, google_monitoring_mesh_istio_service, etc: This needs extra resources outside of GCP/monitoring to test, so I'm excluding them until I figure out how to get testing resources for them.

**Comment by matthias-froomle** [comment]
Is there any timeline on the support of *requestBased* and *windowsBased* SLO's for custom services in the `google_monitoring_slo` resource?

**Comment by danawillow** [comment]
It's being actively worked on now, so I'd expect within the next few weeks (this issue is part of our upcoming sprint- you can see that in the Milestone field)

**Comment by tmarszal** [comment]
@emilymye, thanks a lot for implementing it. I am going to clone master and try to use it on my dev environment right away

**Comment by emilymye** [comment]
Request and Window based SLOs are now supported in #3491 and #3510

**Comment by emilymye** [comment]
@danawillow I'm going to add additional datasources for cloud endpoints and cluster/mesh istio but track in a different issue
