### ISSUE TITLE
packet mirroring

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#5060]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/compute/docs/reference/rest/beta/packetMirrorings

### New or Affected Resource(s)

* google_compute_packet_mirroring

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

b/142593719

**Comment by ndmckinley** [comment]
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/3157.
