### ISSUE TITLE
Dataflow job max_workers not being applied 

### ISSUE THREAD

**Issue by bigbitbus** [terraform-providers/terraform-provider-google#5067]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.9
terraform-google-provider version v2.2.0

### Affected Resource(s)

* google_dataflow_job

### Terraform Configuration Files

This resource will be created without errors, however the max_workers (called NumMaxWorkers) will be fixed at 3 as confirmed in the dataflow google cloud console for the job, no matter what number I specify in the "max_workers" key below.

Interestingly the machine_type is correctly applied.

```tf
### DATAFLOW JOB
resource "google_dataflow_job" "big_data_job" {
  name              = "dataflow-job"
  template_gcs_path = "gs://my-bucket/templates/template_file"
  temp_gcs_location = "gs://my-bucket/tmp_dir"
  parameters = {
    foo = "bar"
    baz = "qux"
  }
  zone = var.location
  machine_type = "n1-standard-1"
  max_workers = "12"
  labels = {
    pipeline = "trackit"
  }
}
```

### Debug Output
With terraform debug I see these lines in the request being sent to the API endpoint: - so we are sending "maxWorkers" key.

```
2019-12-03T21:10:40.871-0500 [DEBUG] plugin.terraform-provider-google_v2.20.0_x4:   "machineType": "n1-standard-1",
2019-12-03T21:10:40.871-0500 [DEBUG] plugin.terraform-provider-google_v2.20.0_x4:   "maxWorkers": 12,
```
### Expected Behavior

numMaxWorkers should have been set to 12.

### Actual Behavior

The dataflow job (when seen in the Google cloud console) only had 3 as the numMaxWorkers, not 12.

### Steps to Reproduce

1. `terraform apply` on the above snippet.

### Important Factoids

When I see the documentation at https://cloud.google.com/dataflow/docs/guides/specifying-exec-params, there is `numMaxWorkers` key  but no `maxWorkers` key; 

but in the go code for the provider  see "maxWorkers" @https://github.com/terraform-providers/terraform-provider-google/blob/b100586a6366c6a716b8e52158811a231a8d6c17/google/resource_dataflow_job.go#L158

### References

* #0000

**Comment by venkykuberan** [comment]
@bigbitbus my understanding is max_workers config value is being used during Auto scaling. If your job requires more resources then GCP increase the workers/instances up to 12 (for your config). However it starts the job with minimal workers and bump up when it needed.  The examples i tried started with 1 worker though.
Regarding the params [here](https://cloud.google.com/dataflow/docs/guides/specifying-exec-params) numMaxWorkers are used by Java SDK. The maxWorkers are used by terraform providers.

**Comment by venkykuberan** [comment]
@bigbitbus are you still needing help on this issue, if not can you close this one ?
