### ISSUE TITLE
Can not import existing google_app_engine_domain_mapping

### ISSUE THREAD

**Issue by courteouselk** [terraform-providers/terraform-provider-google#5068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.17
+ provider.google v2.20.0
+ provider.google-beta v2.20.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Affected Resource(s)

* google_app_engine_domain_mapping

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug) then please include both the
# version of the config before the change, and the version of the config after the change.
```

### Expected Behavior

`terraform import [address] apps/[app]/domainMappings/[domain]` should import the existing App Engine domain mapping into terraform state.

### Actual Behavior

The above command fails wit:

> Error: project: required field is not set

### Steps to Reproduce

1. Create the terraform resource for domain mapping
2. Create the actual resource manually
3. Try to import it via `terraform import`

**Comment by tysen** [comment]
The import format is regrettably labeled - when you use `[app]` in your usage example, is that the name of the project?

**Comment by courteouselk** [comment]
> The import format is regrettably labeled - when you use `[app]` in your usage example, is that the name of the project?

Yes.  Actually I tried all three variants documented at https://www.terraform.io/docs/providers/google/r/app_engine_domain_mapping.html:

```bash
$ terraform import google_app_engine_domain_mapping.default apps/{{project}}/domainMappings/{{domain_name}}
$ terraform import google_app_engine_domain_mapping.default {{project}}/{{domain_name}}
$ terraform import google_app_engine_domain_mapping.default {{domain_name}}
```

... and all of them produce the same error.

**Comment by Chupaka** [comment]
Do you have "project" field set in your configuration (either in provider or in the resource)?

**Comment by courteouselk** [comment]
> Do you have "project" field set in your configuration (either in provider or in the resource)?

Yes, of course.  In fact, if I just delete the existing resource and do `terraform apply` then the new one is created without problem.  Only importing the existing one does not work.

**Comment by edwardmedia** [comment]
@courteouselk I have tried `import` using all three commands and all are successful. No issues can be repro. I noticed that your provider versions are pretty old. Do you want to try with the latest versions? I am closing the issue. You can reopen this for further assistance if you still encounter the issue. Thanks
