### ISSUE TITLE
How to use computer_instance_migrate?

### ISSUE THREAD

**Issue by TraGicCode** [terraform-providers/terraform-provider-google#509]
We are trying to convert to the new way of specifying compute instance disks.  I noticed that @danawillow merged in a feature to perform a migration.  How do we run this migration to ensure our instances do not get destroyed and recreated and the state gets migrated from v3 to v4 correctly?

**Comment by danawillow** [comment]
Once you download the next release (it'll be out today), you should get migrated automatically. I think this happens when you first run `terraform plan`.

**Comment by TraGicCode** [comment]
We actually cloned master and built the provider using go.  We then pointed our tf code at our custom built provider and did a plan and nothing got migrated.  Is this a bug?

**Comment by TraGicCode** [comment]
All it informed us was that the resource was going to blow away our instance and recreate it.

**Comment by paddycarver** [comment]
It looks like we have a bug in this. The good news is it's really easy to mitigate. We'll be releasing a v1.0.1 ASAP to resolve the problem. Sorry for the issues!

**Comment by TraGicCode** [comment]
Thanks!  Just for reference here is the screenshot of terraform trying to recreate the node when doing a plan with v1.0.0
<img width="1108" alt="screen shot 2017-10-02 at 2 19 05 pm" src="https://user-images.githubusercontent.com/6224270/31095048-f8f837e2-a77c-11e7-89f4-7c114536946f.png">

**Comment by TraGicCode** [comment]
@paddycarver I'm back.  Now it's constantly showing a modification in place needs to happen but never actually performs it on the apply.  It looks like it's not actually updating the attached_disk.0.source attribute

**Comment by danawillow** [comment]
Can you post the output of `terraform show` and `terraform plan`?

**Comment by TraGicCode** [comment]
@danawillow Are you all on some sort of public chat where i can send this via Private message?

**Comment by paddycarver** [comment]
While I want to be clear this is not an official HashiCorp resource, HashiCorp has no influence there, and there's no guarantee that HashiCorp employees will be logged in there, Dana and I happen to both be in [the GCP community Slack](https://gcp-slack.appspot.com/) in the Terraform channel.

**Comment by danawillow** [comment]
Yup, Paddy and I are in the GCP slack which you can get an invite for at https://gcp-slack.appspot.com/. I'm danahoffman there and he's paddy.

**Comment by TraGicCode** [comment]
It's almost like my invite got lost into oblivion.
