### ISSUE TITLE
Permission 'cloudkms.cryptoKeyVersions.useToEncrypt' denied on resource

### ISSUE THREAD

**Issue by jdziat** [terraform-providers/terraform-provider-google#5103]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
0.11.14	

### Affected Resource(s)

* google_compute_disk
* google_kms_key_ring
* google_kms_crypto_key

### Terraform Configuration Files

```tf
data "google_kms_key_ring" "custom_defined_key_ring" {
  name     = "test-ring"
  location = "global"
}

data "google_kms_crypto_key" "custom_defined_crypto_key" {
  name     = "test-key"
  key_ring = "${data.google_kms_key_ring.custom_defined_key_ring.self_link}"
}


resource "google_compute_disk" "nfs_disk" {
   
  name = "manager-nfs"
  type = "${var.nfs_disk_type}"
  zone = "${var.zone}"
  size = "${var.nfs_disk_size_gb}"
  disk_encryption_key {
      kms_key_self_link="${data.google_kms_crypto_key.custom_defined_crypto_key.self_link}"
  }

}
```

### Expected Behavior

Use the defined key to encrypt the created disks

### Actual Behavior

Errors out because of missing permissions. Even though the service account being used has been granted project-owner privileges within the project that the key is stored in.

```tf
4 errors occurred:
	* google_compute_disk.nfs_disk: 1 error occurred:
	* google_compute_disk.nfs_disk: Error creating Disk: googleapi: Error 400: Cloud KMS error when using key projects/*******/locations/global/keyRings/global-test/cryptoKeys/customer-key: Permission 'cloudkms.cryptoKeyVersions.useToEncrypt' denied on resource 'projects/*******/locations/global/keyRings/global-test/cryptoKeys/customer-key' (or it may not exist)., kmsPermissionDenied

```

### Steps to Reproduce

1. `terraform apply`

**Comment by megan07** [comment]
Hi @jdziat!  Thank you for reporting this issue.  This is caused because the Compute Engine System service account does not have the correct permissions.  In order to update those permissions, you can add this to your configuration file:

```
resource "google_kms_crypto_key_iam_binding" "crypto_key" {
  crypto_key_id = data.google_kms_crypto_key.custom_defined_crypto_key.self_link
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"

  members = [
    "serviceAccount:service-<PROJECT NUMBER>@compute-system.iam.gserviceaccount.com",
  ]
}
```

I will update the documentation to hopefully avoid this issue in the future.
Thanks!

**Comment by jdziat** [comment]
Thanks i actually just figured that out. i was using:

```
data "google_compute_default_service_account" "default" {}
"serviceAccount:${data.google_compute_default_service_account.default.email}",
``
for my binding thinking that was the one i needed. The you mentioned did work.

**Comment by megan07** [comment]
Great!  I've updated the doc now too.  Thanks!
