### ISSUE TITLE
Panic: google_cloud_run_service interface{} is nil

### ISSUE THREAD

**Issue by sethvargo** [terraform-providers/terraform-provider-google#5113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.17

### Affected Resource(s)

* google_cloud_run_service

### Terraform Configuration Files

```tf
terraform {
  required_version = ">= 0.12"

  required_providers {
    google = "~> 3.0"
  }
}

resource "google_cloud_run_service" "my-service" {
  name     = "my-service"
  location = "us-central1"

  metadata {}

  template {
    spec {
      containers {
        image = "gcr.io/cloudrun/hello"
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
}
```

### Debug Output

https://gist.github.com/sethvargo/40885e2f8677f9b7b7e4cf794dee71a5

### Panic Output

https://gist.github.com/sethvargo/40885e2f8677f9b7b7e4cf794dee71a5

### Expected Behavior

Not a panic

### Actual Behavior

Panic

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nope

**Comment by chrisst** [comment]
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/2793/files
This will be resolved in 3.2.0
