### ISSUE TITLE
google_compute_router_interface doesn't work correctly with google_compute_interconnect_attachment resource

### ISSUE THREAD

**Issue by jpawlowski-sapient** [terraform-providers/terraform-provider-google#5133]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
v0.12.7
```

### Google provider version
I got the same error with both 2.20.0 and 3.1.0

### Affected Resource(s)

* google_compute_router_interface

### Terraform Configuration Files

```hcl
resource "google_compute_network" "mynetwork" {
  name                    = "mynetwork"
  auto_create_subnetworks = false
  routing_mode            = "GLOBAL"
  project                 = var.project_id
}

resource "google_compute_router" "router" {
  name     = var.interconnect
  network  = google_compute_network.mynetwork.name
  project  = var.project_id
  region   = var.region
  bgp {
    asn = var.asn
  }
}

resource "google_compute_interconnect_attachment" "attachment" {
  name          = var.interconnect
  interconnect  = "projects/${var.target_project_id}/global/interconnects/${var.interconnect}"
  router        = google_compute_router.router.self_link
  project       = var.project_id
  region        = var.region
  admin_enabled = true
}
resource "google_compute_router_interface" "router_interface" {
  name = var.interconnect
  router                  = google_compute_router.router.name
  region                  = var.region
  ip_range                = google_compute_interconnect_attachment.attachment.cloud_router_ip_address
  interconnect_attachment = google_compute_interconnect_attachment.attachment.self_link
  project                 = var.project_id
}
```

### Expected Behavior

GCP should assign ip range to the attachment and router interface should pick it up.
### Actual Behavior

```
$ terraform apply

Error: Each interface requires one linked resource or an ip range, or both.

  on ..\..\..\main.tf line 22, in resource "google_compute_router_interface" "router_interface":
  22: resource "google_compute_router_interface" "router_interface" {

```
It works however if I split it in stages, i.e. create google_compute_interconnect_attachment first and router interface on another pass of terraform apply.

One workaround is to use
```hcl
resource "google_compute_interconnect_attachment" "attachment" {
...
candidate_subnets = ["169.254.0.0/29"]
}
resource "google_compute_router_interface" "router_interface" {
...
ip_range                = "169.254.0.1/29"
}
```
however it complicates configuration and adds little value as terraform will always try to recreate 
```
google_compute_interconnect_attachment resource anyway, e.g.

  # google_compute_interconnect_attachment.attachment must be replaced
-/+ resource "google_compute_interconnect_attachment" "attachment" {
...
      ~ candidate_subnets          = [ # forces replacement
          + "169.254.0.0/29",
        ]
      ~ cloud_router_ip_address    = "169.254.0.1/29" -> (known after apply)
    }
```
### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@jpawlowski-sapient can you post the debug log? Thanks

**Comment by jpawlowski-sapient** [comment]
@edwardmedia here's the link to debug output: https://gist.github.com/jpawlowski-sapient/814f9f87ac32f307eb6377d6a525c29d

Here's the code which is responsible for that error: https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_router_interface.go#L300
```
func routerInterfaceDiffOneOfCheck(d *schema.ResourceDiff, meta interface{}) error {
	_, ipOk := d.GetOk("ip_range")
	_, vpnOk := d.GetOk("vpn_tunnel")
	_, icOk := d.GetOk("interconnect_attachment")
	if !(ipOk || vpnOk || icOk) {
		return fmt.Errorf("Each interface requires one linked resource or an ip range, or both.")
	}
	return nil
}
```

It seems like it would be fixed if we change implementation of that GetOK function 
```
return r.Value, exists
```
to the following:
```
return r.Value, (exists || r.Computed)
```
https://github.com/terraform-providers/terraform-provider-google/blob/6c8ef61974fa2011f8105e233915697929904c46/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource_data.go#L108
However I'm too new to that code to correctly assess consequences.

**Comment by edwardmedia** [comment]
It appears the resources creation requires in certain order. Can you add `depends_on` mega-argument in two resources? Here is the reference for how to add the mega-argument https://www.terraform.io/docs/configuration/resources.html#depends_on-explicit-resource-dependencies

**Comment by jpawlowski-sapient** [comment]
I already had implicit "depends on" because of this line:
```
ip_range                = google_compute_interconnect_attachment.attachment.cloud_router_ip_address
```
I've tried adding the explicit one but, as expected, it doesn't change anything and I'm getting the same error.

**Comment by rileykarson** [comment]
The issue here is that the value of the fields in `google_compute_router_interface` are unknown as a result of the interpolation. At apply time, all values are known and GetOk works as expected. Unknown fields are considered to be unset in `CustomizeDiff`, and the function author needs to remember that when using it. Terraform handles them correctly in most other cases- it's an annoying gotcha. This should be fixed w/ the linked PR.
