### ISSUE TITLE
Add example for google_compute_disk_resource_policy_attachment

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#5137]
https://www.terraform.io/docs/providers/google/r/compute_disk_resource_policy_attachment.html

**Comment by pradeepbhadani** [comment]
I can pick this up

**Comment by pradeepbhadani** [comment]
Added example in https://github.com/terraform-providers/terraform-provider-google/pull/5097

**Comment by danawillow** [comment]
Fixed in https://github.com/terraform-providers/terraform-provider-google/pull/5257.
