### ISSUE TITLE
attached_disks only work if source is a self_link

### ISSUE THREAD

**Issue by paddycarver** [terraform-providers/terraform-provider-google#514]
When using `attached_disk` on a resource, if a `name` is used instead of a full `self_link`, the API response can't match it to the `attached_disk` field it belongs to, and tries to make it a `disk`. But disks don't exist anymore, so it just ignores it in the state. This manifests as a constant diff showing the need to update the attached disk.

A quick solution to this would be to update the matching that happens in `compute_instance`'s Read function to accept either a `self_link` _or_ a `name` and treat them as equivalent. A _better_ solution to this would probably involve ripping out the code that distinguished between `attached_disk` and `disk` entirely, and reworking the logic of that section, as we no longer need to match against `disk`.

In the meantime, users can workaround the problem by using the `self_link` instead of the `name` in their configs.

**Comment by danawillow** [comment]
FYI #460

**Comment by paddycarver** [comment]
\*facepalm\*
