### ISSUE TITLE
Support "source_image" and "source_snapshot" in Compute Image resource?

### ISSUE THREAD

**Issue by maqiuyujoyce** [terraform-providers/terraform-provider-google#5148]
Could you support `source_image` and `source_snapshot` in [Compute Image resource](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_image.go)? According to the [public doc](https://cloud.google.com/compute/docs/images/create-delete-deprecate-private-images#create_image), there are different sources for image creation and it would be great to have all of them covered.

**Comment by danawillow** [comment]
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/2092 and https://github.com/terraform-providers/terraform-provider-google/issues/4696
