### ISSUE TITLE
Add support for min_cpu_platform in google_compute_instance_template.

### ISSUE THREAD

**Issue by tik-son** [terraform-providers/terraform-provider-google#516]
Hi there,

### Terraform Version
This is a feature proposal

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance_template

### Expected Behavior
Add support for min_cpu_platform in google_compute_instance_template

### Actual Behavior
https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform

**Comment by rosbo** [comment]
This feature is now in GA

**Comment by tik-son** [comment]
@rosbo 
Thanks.
When will you release a version including this feature?
It seems that this feature is not released on [CHANGELOG](
https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#131-unreleased).

**Comment by rosbo** [comment]
It will be part of the next release. We tend to do a new release every 2-3 weeks.
