### ISSUE TITLE
google_project_service fails with 404 when attempting to call enable api

### ISSUE THREAD

**Issue by gazmania** [terraform-providers/terraform-provider-google#5161]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.16
+ provider.google v3.2.0

### Affected Resource(s)

* google_project_service
* google_service_account

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug) then please include both the
# version of the config before the change, and the version of the config after the change.

resource "google_project" "project" {
  name = "${var.environment}-project"
  project_id = "${var.environment}-${var.seed}"
  folder_id = var.folder_id
  billing_account = var.billing_account

  labels = {
    environment = var.environment
  }

  auto_create_network = false
}

resource google_project_service "compute" {
  service = "compute.googleapis.com"
  project = google_project.project.id
}

resource "google_service_account" "shell" {
  account_id = "${var.environment}-shell-account"
  project = google_project.project.id
}

```

### Expected Behavior

After project creation the service should be successfully enabled and the service account should be cretaed

### Actual Behavior
```
Error: Error creating service account: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1/projects/projects/prod-191214/serviceAccounts?alt=json&amp;prettyPrint=false</code> was not found on this server.  <ins>That’s all we know.</ins>

  on ../modules/shell/main.tf line 36, in resource "google_service_account" "shell":
  36: resource "google_service_account" "shell" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The thing I'm noticing here is that the url being called is incorrect, it has a double 'projects' in it.  Given this is happening on multiple resource for the same reason, is there a problem with the google_project resource that is outputing a slightly different id than it used to?

### References

* #0000

**Comment by edwardmedia** [comment]
Can't repo for me in creating google_service_account. Noticed that your project is created in live `project_id = "${var.environment}-${var.seed}"`. How did you make sure this project id is used in creating  `google_service_account`?

**Comment by gazmania** [comment]
I'm not quite sure I get the question. The project id for the google_service_account is retrieved from the newly created project.

```tf
resource "google_service_account" "shell" {
  account_id = "${var.environment}-shell-account"
  project = google_project.project.id
}
```

**Comment by edwardmedia** [comment]
@gazmania can you post full debug log? Thanks

**Comment by gazmania** [comment]
debug here....

https://gist.github.com/gazmania/1bedfccad614dfb1ea71cda63591e4ce

**Comment by pradeepbhadani** [comment]
@gazmania  Can you try to update `project = google_project.project.id` to `project = google_project.project.project_id` and try?

**Comment by edwardmedia** [comment]
@gazmania using `project_id` instead of `id` 

```
resource "google_service_account" "shell" {
  account_id = "${var.environment}-shell-account"
  project = google_project.project.project_id
}
````

**Comment by Erouan50** [comment]
We had the same issue but using the `project_id` instead of `id` works, which makes sense since the v3.0.0 sets the ID of resources with the self-link: https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#id-format-changes.

**Comment by pradeepbhadani** [comment]
There is no `id` that is defined as an argument or attribute. So that's why it's giving issue.
Ref: https://www.terraform.io/docs/providers/google/r/google_project.html

**Comment by edwardmedia** [comment]
@gazmania I am closing this issue. Using project_id should solve your problem. You may reopen the issue if this does not help, or open another issue if you see a different problem. Thanks
