### ISSUE TITLE
gke node pool creation fails when using location output from gke master

### ISSUE THREAD

**Issue by joemiller** [terraform-providers/terraform-provider-google#5171]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.18
+ provider.google v3.2.0

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

Given a module `gke-master` that manages the master (`google_container_cluster`) and a module for managing node_pools (`google_container_node_pool`) and a root module like the following:

```tf
# "root" module:
locals {
  name              = "sandbox-joem1"
  master_version    = "1.13.11-gke.14"
  machine_type      = "n1-standard-4"
  project           = "foo"
  region            = "us-central1"
}

module "gke-master" {
  source = "../../../modules/gke-master"

  name                     = "${local.name}"
  project                  = "${local.project}"
  location                 = "${local.region}"
  network                  = "projects/${local.project}/global/networks/default"
  min_master_version       = "${local.master_version}"
}

module "pool-03" {
  source = "../../../modules/gke-node-pool"

  name            = "${local.name}-pool-03"
  k8s_version     = "1.13.11-gke.14"
  master          = "${module.gke-master.master}"
  project         = "${module.gke-master.project}"
  location        = "${module.gke-master.location}"
  service_account = "${module.gke-master.service_account}"
  machine_type    = "${local.machine_type}"
  node_count      = 1

  metadata = {
    "disable-legacy-endpoints" = "true"
  }
}
```

Terraform will fail to create the node pool with error:

```console
Error: Cannot determine zone: set in this resource, or set provider-level zone
```

The `location` for the node-pool is set based on the gke-master module's `region` output.

Changing the `location` for the node-pool to be an explicit string works fine, eg:

```tf
module "pool-03" {
  source = "../../../modules/gke-node-pool"

  name            = "${local.name}-pool-03"
  k8s_version     = "1.13.11-gke.14"
  master          = "${module.gke-master.master}"
  project         = "${module.gke-master.project}"
  region          = "us-central1"
...
```

We were not seeing this behavior with the 2.20.x provider, so it feels like new behavior with google 3.x or possibly with terraform 0.12.18.

### Expected Behavior

The node-pool creation would succeed when using the location output from the gke-master module.

**Comment by neale-bpm** [comment]
@joemiller Did you intend to close this without commeit?  We're getting the same error since updating to 3.3.0, so I'm wondering if you found some other cause.

**Comment by joemiller** [comment]
@neale-bpm Sorry, I  closed it because I did not  feel like I was able to communicate enough usable information in the ticket, and also because I had trouble verifying the issue.

In our case it was solved by using an existing local var we already had in place, eg:

```
# main.tf
locals {
  region = "us-central1"
}

module {
 source = "gke-master"
 location = local.region
...
}
module {
  source = "nodepool"
- location = module.gke-master.location
+ location = local.region
```

If you think the issue has sufficient information to re-open and reproduce, I'd be happy to re-open. Another option might be opening a new bug with a full reproducible set of TF code?

**Comment by neale-bpm** [comment]
Thanks for the reply @joemiller. Simple workaround did the job for us too.
