### ISSUE TITLE
Project creation failing with "invalid argument"

### ISSUE THREAD

**Issue by clebio** [terraform-providers/terraform-provider-google#5172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
$ terraform version
Terraform v0.12.18
+ provider.google v3.2.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* google_project_service
* google_project

### Terraform Configuration Files

```tf
variable "billing_account_id" {
  description = "Billing account to use"
}

variable "org_id" {
  description = "Organization ID"
}

provider "google" {
  region = "us-central1"
}

terraform {
  required_version = "~> 0.12"
  required_providers {
    google = ">= 3.2.0"
  }
}

resource "random_id" "id" {
  byte_length = 4
}

resource "google_project" "main" {
  name            = "repro-${random_id.id.hex}"
  project_id      = "repro-${random_id.id.hex}"
  org_id          = var.org_id
  billing_account = var.billing_account_id
}

resource "google_project_iam_member" "project" {
  project = google_project.main.id
  role    = "roles/owner"
  member  = "user:me@example.com"
}

resource "google_project_service" "project" {
  project  = google_project.main.id
  service = "oslogin.googleapis.com"
}
```

### Debug Output

https://gist.github.com/clebio/b44fbc995c4cd3a3db8b3b6b5a0fe82a

### Expected Behavior

`apply`  should succeed

### Actual Behavior

Error and failed apply

### Steps to Reproduce

1. create terraform file with the contents above
2. `terrform init`
3. `terraform apply`

### Important Factoids

I created a project in this manner about a week ago, without issue. 

### References

Seems related:

* #5161

**Comment by pradeepbhadani** [comment]
@clebio Can you update ` project = google_project.project.id` to ` project = google_project.project.project_id` ?

Also, could you please paste the output of `terraform graph` and `terraform plan` ?

It seems like `google_project_service` is not waiting for `google_project.project` to finish.

**Comment by clebio** [comment]
@pradeepbhadani , I think you're right. That seems to have fixed this for me. Thanks!
