### ISSUE TITLE
parameterize bigtable cloumn_family name in GCP terrafrom

### ISSUE THREAD

**Issue by BALABHASKARARAO** [terraform-providers/terraform-provider-google#5176]
resource "google_bigtable_table" "table" {
   name          = "tf-table"
   project       = "${var.project_id}"
   instance_name = google_bigtable_instance.production_instance.name
   column_family {
      family = "payment"
   }
   column_family {
     family = "test"
   }
  depends_on = [google_bigtable_instance.production_instance]
}

Question : any can help me to parameter "column family names" in main.tf, varibales.tf and terraform.tf vars 

Please send the code in the form of main.tf ,variables.tf and terraform.tfvars

**Comment by danawillow** [comment]
Hi @BALABHASKARARAO, as noted in https://github.com/terraform-providers/terraform-provider-google/issues/new?template=question.md, the issue tracker is intended to keep track of bugs and feature requests for the provider, and is not the correct place to ask for help writing your Terraform configs. Please check out one of our community resources listed there instead!
