### ISSUE TITLE
how to paramerixe bigtable name in the following code in GCP by terraform

### ISSUE THREAD

**Issue by BALABHASKARARAO** [terraform-providers/terraform-provider-google#5177]
terraform code to create bigtable in gcp with out parameter.  then main.tf file will look this. 
It is working. but error occurs at the time of paramertiize . Please read entire document.
resource "google_bigtable_instance" "production_instance" {
  name = "tf-instance2"
  project = "saturada

  cluster {
    cluster_id   = "terraform-cluster"
    zone         = "us-central1-b"
    num_nodes    = 3
    storage_type = "SSD"
  }
}
resource "google_bigtable_table" "table" {
  name          = "tf-table"
  project       = "saturaday"
  instance_name = google_bigtable_instance.production_instance.name
  column_family {
    family = "payment"
  }
  column_family {
    family = "test"
  }
  depends_on = [google_bigtable_instance.production_instance]
}

# The below code is main.tf after parametize
resource "google_bigtable_instance" "production_instance" {
  name = var.instance_name
  project = var.project_id

  cluster {
    cluster_id   = "terraform-cluster"
    zone         = "us-central1-b"
    num_nodes    = 3
    storage_type = "SSD"
  }
}
resource "google_bigtable_table" "table" {
  name          = "tf-table"
  project       = var.project_id
  instance_name = var.google_bigtable_instance.production_instance.name
  column_family {
    family = "payment"
  }
  column_family {
    family = "test"
  }
  depends_on = [google_bigtable_instance.production_instance]
}

# Request suggestion on resource "google_bigtable_table" "table" 4th line instance_name " that was define at earlier block " please give suggestion on that line

**Comment by danawillow** [comment]
Hi @BALABHASKARARAO, as noted in https://github.com/terraform-providers/terraform-provider-google/issues/new?template=question.md, the issue tracker is intended to keep track of bugs and feature requests for the provider, and is not the correct place to ask for help writing your Terraform configs. Please check out one of our community resources listed there instead!
