### ISSUE TITLE
google provider returning 0 exit code on error

### ISSUE THREAD

**Issue by marcb1** [terraform-providers/terraform-provider-google#5181]
Terraform version info:
```
$ terraform version
Terraform v0.12.16
+ provider.google v2.20.1
+ provider.google-beta v3.2.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1
```

We are creating the following resource via the google provider:
```
resource "google_kms_key_ring" "slack-reporter-keyring" {
  project  = "project_id"
  name     = "slack-reporter-keyring"
  location = "us-central1"
}

resource "google_kms_crypto_key" "slack-reporter-cryptokey" {
  name     = "slack-reporter-cryptokey"
  key_ring = google_kms_key_ring.slack-reporter-keyring.self_link
}
```

When running terraform apply, we get the following error:
```
Error: Error creating KeyRing: googleapi: Error 400: Google Cloud KMS API has not been used in this project before, or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudkms.googleapis.com/overview?project=[project_id] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

  on slack_reporter.tf line 27, in resource "google_kms_key_ring" "slack-reporter-keyring":
  27: resource "google_kms_key_ring" "slack-reporter-keyring" {
```

```
$ echo $?
0
```

However the exit code returned by terraform is `0`. Our automation relies on an error exit code (non-zero) being returned. 
Is this a terraform bug, or a google provider bug? Let me know I can close and re-open this on terraform's main github repo.

**Comment by venkykuberan** [comment]
@marcb1 Its not a bug working as expected. If you haven't used that service before in your project, GCP expects you to enable it before you use it. It can be done in 2 ways

1) On the Cloud Console, Search for the API **Google Cloud KMS API** under Api & Services side bar
2) run the command on terminal **gcloud services enable cloudkms.googleapis.com**

**Comment by marcb1** [comment]
@venkykuberan thanks for the info. I think this was a bug in the main terraform core and the google provider. We've upgraded from 0.12.16 to 0.12.18 and the issue went away.
(terraform now returns a 1 exit code on errors, before this was inconsistent as sometimes an error will be printed by terraform but the shell exit code would be 0- we rely on exit codes for our terraform automation)
