### ISSUE TITLE
google_sql_database_instance incorrectly has SQLSERVER_ENTERPRISE_2016 documented as an option

### ISSUE THREAD

**Issue by orikashi** [terraform-providers/terraform-provider-google#5190]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

google_sql_database_instance

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug) then please include both the
# version of the config before the change, and the version of the config after the change.
```

### Expected Behavior

SQL Server 2016 should not be an option

### Actual Behavior

2016 is listed as an option

### Steps to Reproduce

1. Documentation incorrect - documentation for google_sql_database_instance incorrectly has SQLSERVER_ENTERPRISE_2016 as an option.  This is not supported by the service.

### References

* #0000

**Comment by venkykuberan** [comment]
@orikashi 
  Thank you for pointing out. API is not supporting SQLServer_Enterprise_2016 as per https://cloud.google.com/sql/docs/sqlserver/db-versions. We will correct the provider documentation

**Comment by pradeepbhadani** [comment]
@orikashi @rileykarson  - I have added a fix for this in https://github.com/terraform-providers/terraform-provider-google/pull/5207

**Comment by rileykarson** [comment]
Thanks @pradeepbhadani! However, I'd like to keep those changes separate instead of rolling several together into a single PR. I've sent https://github.com/GoogleCloudPlatform/magic-modules/pull/2850 which includes a deprioritisation of first-gen instances for https://cloud.google.com/sql/docs/mysql/deprecation-notice

**Comment by pradeepbhadani** [comment]
@rileykarson  - git puts commit into the open PR. I couldn't find a way to open multiple PRs from a fork repo to upstream repo.

**Comment by rileykarson** [comment]
@pradeepbhadani: You can have a single PR per branch, by using multiple branches you can open multiple PRs per fork.
