### ISSUE TITLE
Change affected AtLeastOneOfs back to ExactlyOneOf

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#5193]
See https://github.com/terraform-providers/terraform-provider-google/issues/5024

This affects:
- google_compute_firewall
- google_folder_organization_policy
- google_organization_policy
- google_project_organization_policy
- google_compute_health_check
- google_compute_region_health_check

Because of https://github.com/hashicorp/terraform-plugin-sdk/issues/280, several fields that were ExactlyOneOf were changed to AtLeastOneOf. In the next major release after the blocking issue is fixed, change them back.

**Comment by mholleville** [comment]
Hello !

Do you have a date for the availability of these new features? It is quite structuring on the firewall part etc..

**Comment by danawillow** [comment]
The behavior of this should be correct as of https://github.com/GoogleCloudPlatform/magic-modules/pull/2856. This specific issue is to simplify the code by having it be ExactlyOneOf instead of AtLeastOneOf+ConflictsWith. Are you seeing otherwise? I'm not totally sure from your comment what you mean by "it is quite structuring on the firewall part"

**Comment by j-don** [comment]
Not sure if this is the right place to report this, but 3.20.0 seems to have reintroduced the issue described in https://github.com/hashicorp/terraform-plugin-sdk/issues/280 that links to this issue. We ran into that same error signature today when applying `terraform-google-modules/network/google//modules/fabric-net-firewall` modules, and rolling back to 3.19.0 fixed it.

**Comment by danawillow** [comment]
Oh gosh, we never revendored the SDK after they fixed it on their end 🤦‍♀️ 

I'll go ahead and do that now for our next release.
