### ISSUE TITLE
Error uploading object redis_test.sh: googleapi: Error 403: The project to be billed is associated with an absent billing account., accountDisabled

### ISSUE THREAD

**Issue by judika03** [terraform-providers/terraform-provider-google#5209]
### Community Note

*Error uploading object redis_test.sh: googleapi: Error 403: The project to be billed is associated with an absent billing account., accountDisabled

### Terraform Version

terraform version
Terraform v0.12.0
+ provider.google v3.2.0
+ provider.google-beta v3.2.0
+ provider.template v2.1.2

Your version of Terraform is out of date! The latest version

### Affected Resource(s)

Error: Error uploading object redis_test.sh: googleapi: Error 403: The project to be billed is associated with an absent billing account., accountDisabled

  on main.tf line 70, in resource "google_storage_bucket_object" "config":
  70: resource "google_storage_bucket_object" "config" {

* google_XXXXX

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@judika03 it's not clear how to repro this issue from your context. You post your tf configurations files, along with the plan result, and the full debug log? Thanks

**Comment by edwardmedia** [comment]
@judika03 is this still an issue with you?

**Comment by edwardmedia** [comment]
@judika03 I am closing this issue as there are no enough materials for us to investigate. Please feel free to reopen it once you have the full debug log available for share. Thanks
