### ISSUE TITLE
Allow configuring Datastore / Firestore mode (native - Firestore or legacy Datastore)

### ISSUE THREAD

**Issue by jaceq** [terraform-providers/terraform-provider-google#5210]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It seems that now it is not possible to define Firestore vs Datastore via TF, it is necessary to click manually in project and enabling a API alone isn't enough.
Would be cool to be able to define this via TF

### Potential Terraform Configuration

```tf
google_firestore_database "default" {
  name = "some-name"
  mode = "native" // or legacy
}
```

* #0000

**Comment by rileykarson** [comment]
Duplicates https://github.com/terraform-providers/terraform-provider-google/issues/3657
