### ISSUE TITLE
Cluster creation and node pool creation not working 

### ISSUE THREAD

**Issue by gowrisankar22** [terraform-providers/terraform-provider-google#5229]
Hello Folks,

I am unable to create cluster and node pool creation via terraform. Looks like something wrong?
can someone help ?
```
Error: Error applying plan:

2 error(s) occurred:

* google_container_node_pool.gke-node-pool: 1 error(s) occurred:

* google_container_node_pool.gke-node-pool: error creating NodePool: googleapi: Error 404: Not found: projects/xxxx/locations/europe-west1/clusters/gke-cluster., notFound
* google_container_cluster.gke-cluster: 1 error(s) occurred:

* google_container_cluster.gke-cluster: Error waiting for creating GKE cluster: timeout while waiting for state to become 'DONE' (last state: 'RUNNING', timeout: 30m0s)
```

**Comment by edwardmedia** [comment]
@gowrisankar22  can you post your terraform code and full debug log? And how did you repro the issue?

**Comment by gowrisankar22** [comment]
I am closing this as it was a problem from my side.

**Comment by coolblknerd** [comment]
@gowrisankar22 what was your solution to this issue? I'm running into the same error.

**Comment by coolblknerd** [comment]
Nevermind, I figured it out. I made my cluster a zonal cluster and I was trying to make a node pool in a different zone. Once I re-created my cluster to be regional and made sure my node pool matched my region everything worked as expected.
