### ISSUE TITLE
Failure to create VPC Access Connector

### ISSUE THREAD

**Issue by nryoung** [terraform-providers/terraform-provider-google#5233]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.11.13
+ provider.google v2.20.1
+ provider.google-beta v2.20.0
+ provider.null v2.1.2
```

### Affected Resource(s)

* `google_vpc_access_connector`
* https://cloud.google.com/vpc/docs/reference/vpcaccess/rest/v1beta1/projects.locations.connectors

### Terraform Configuration Files

```tf
resource "google_vpc_access_connector" "vpcConnector" {
  name          = "some-connector"
  provider      = "google-beta"
  region        = "us-central1"
  ip_cidr_range = "10.8.0.0/20"
}

```

### Debug Output

https://gist.github.com/nryoung/84d8a7db4ec6d62ed2f53bc3afcede10

### Panic Output

None

### Expected Behavior

Terraform should create the VPC Connector in GCP.

### Actual Behavior

Receive a `400` response from googleapis saying `INVALID_ARGUMENT`

### Steps to Reproduce

Use the version of Terraform and google-beta above and use my config to attempt to create a VCP Connector in GCP.

### Important Factoids

None

### References

* #3401
* https://github.com/terraform-providers/terraform-provider-google-beta/pull/1004

**Comment by harsh-dialpad** [comment]
According to GCP docs, `ip_cidr_range` has to belong to an unused block with a network mask of `/28`: https://cloud.google.com/vpc/docs/configure-serverless-vpc-access#creating_a_connector (look at `[IP_RANGE]`)

**Comment by nryoung** [comment]
@harsh-dialpad good catch, however, even with changing it to the `/28` network mask suffix, I still get the same error from googleapis.

**Comment by venkykuberan** [comment]
@nryoung  please use network property for that resource. If you are using default network just use this way
```
resource "google_vpc_access_connector" "vpcConnector" {
  name          = "some-connector"
  provider      = google-beta
  region        = var.region
  ip_cidr_range = "10.8.0.0/28"
  network = "default"
}
```

**Comment by nryoung** [comment]
@venkykuberan that worked! Looks like the docs for the `google_vpc_access_connector` resource needs to be updated: 

https://www.terraform.io/docs/providers/google/r/vpc_access_connector.html#argument-reference

As it lists the `network` argument as optional.

**Comment by venkykuberan** [comment]
@nryoung  Agreed, docs need to be updated. We will work on it.
