### ISSUE TITLE
GKE node pools are not remade after cluster is recreated

### ISSUE THREAD

**Issue by JaymoKang** [terraform-providers/terraform-provider-google#5235]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.6
+ provider.google v2.20.0
```

### Affected Resource(s)

* `google_container_node_pool`

### Terraform Configuration Files

```tf
resource "google_container_cluster" "gke-cluster" {
  name     = var.cluster_name
  project  = var.project_id
  location = var.location

  min_master_version       = var.min_master_version
  initial_node_count       = 1
  remove_default_node_pool = true

  ip_allocation_policy {
    # Always enable to access everything on private network
    use_ip_aliases                = "true"
    cluster_secondary_range_name  = var.enable_private_network ? var.secondary_ip_1 : null
    services_secondary_range_name = var.enable_private_network ? var.secondary_ip_2 : null
  }

  # connect to shared subnet
  network    = var.enable_private_network ? var.network_self_link : null
  subnetwork = var.enable_private_network ? var.subnet_self_link : null

  logging_service    = "logging.googleapis.com/kubernetes"
  monitoring_service = "monitoring.googleapis.com/kubernetes"

  private_cluster_config {
    enable_private_nodes    = var.enable_private_cluster
    enable_private_endpoint = false
    master_ipv4_cidr_block  = var.master_ipv4_cidr_block
  }
}

resource "google_container_node_pool" "system-nodes" {
  name     = "system-node-pool"
  location = google_container_cluster.gke-cluster.location
  cluster  = google_container_cluster.gke-cluster.name

  initial_node_count = var.system_node_count
  node_config {
    disk_size_gb    = var.system_node_pool_disk_size_gb
    disk_type       = "pd-ssd"
    oauth_scopes    = ["cloud-platform"]
    machine_type    = "n1-standard-1"
    tags            = local.node_pool_tags
    service_account = var.service_account_email
  }

  management {
    auto_repair  = true
    auto_upgrade = true
  }
}
```

the `var.enable_private_cluster` was turned from `true` to `false`. 

### Expected Behavior

* cluster should've recreated, and node pools should've recreated under the cluster

### Actual Behavior

* the cluster was recreated
* the node pools were not recreated

### Steps to Reproduce

0. create a cluster with node pool
  * `enable_private_nodes = true`
0. turn `enable_private_nodes = false`
1. `terraform apply`

**Comment by venkykuberan** [comment]
@JaymoKang  Just referring the cluster name in the following way makes terraform to understand that it has to recreate the node pool as it refers a computed value of another resource. 
```
resource "google_container_node_pool" "system-nodes" {
  name     = "system-node-pool"
  location = google_container_cluster.gke-cluster.location
  cluster  = split("/", google_container_cluster.gke-cluster.id)[5]

  initial_node_count = 2
  node_config {
    disk_size_gb    = var.system_node_pool_disk_size_gb
    disk_type       = "pd-ssd"
    oauth_scopes    = ["cloud-platform"]
    machine_type    = "n1-standard-1"
    tags            = local.node_pool_tags
    service_account = var.service_account_email
  }

  management {
    auto_repair  = true
    auto_upgrade = true
  }
}```

**Comment by JaymoKang** [comment]
it seems like you're saying as long as the value is only known after apply, then the node pools will also be recreated. However, it should be the case that the node pool depending on the cluster will force the node pools to recreate regardless of whether i use a value that is known before or after the apply, especially since the dependency is explicit

**Comment by venkykuberan** [comment]
In your config file the cluster property was actually coming from variable.  When you change the cluster to non-private and run the plan terraform recognizes that the cluster needs to be recreated. However for the node-pool resource it sees that only property its depending on is the cluster name which is not changing so its doesn't care to delete it. Therefore terraform perceives that its deleting the cluster resource and recreating it.  
  On the GCP side when the cluster is deleted it deletes the associated node-pool as well. Terraform have no idea about this relation. When you run the plan command again it learns that node-pool resource is missing on the GCP and expects the apply command to create the node-pool resource.

The solution i was suggesting is making terraform aware that its using the computed value for the property in node-pool resource, so if the depending resource is going to be deleted, it will consider the dependent resource to be deleted as well.

**Comment by JaymoKang** [comment]
hmm ok, ill think about this more and then re-open if I'm still concerned. Happy new years :)
