### ISSUE TITLE
Support range partitioning for BigQuery tables

### ISSUE THREAD

**Issue by tristan957** [terraform-providers/terraform-provider-google#5239]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Right now the google_bigquery_table resource only supports time partitioning. Google's BigQuery documentation supports a notion of range partitioning (https://cloud.google.com/bigquery/docs/creating-integer-range-partitions). Right now it is impossible to model range partitioned tables in Terraform.

### New or Affected Resource(s)

* google_bigquery_table

### Potential Terraform Configuration

```tf
resource "google_bigquery_table" "weather-locations" {
  dataset_id    = google_bigquery_dataset.twc
  table_id      = "weather_locations"
  friendly_name = "Weather Loactions"
  schema        = file("${path.module}/schemas/twc/weather_locations.json")
  range_partitioning {
    type                     = "INTEGER"
    field                    = "num_hash"
    start = 0
    end = 100
    interval = 10
  }
}
```

**Comment by tristan957** [comment]
Is there anything more required, other than editing this file (https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/resources/resource_bigquery_table.go.erb) and adding documentation somewhere?

**Comment by emilymye** [comment]
Test: [third_party/terraform/tests/resource_bigquery_table_test.go](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/tests/resource_bigquery_table_test.go)

Website Doc: [third_party/terraform/website/docs/r/bigquery_table.html.markdown](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/website/docs/r/bigquery_table.html.markdown)

**Comment by sid0911** [comment]
Team, range_partitioning is not working for me. Could you please help to resolve this issue ?

Error: Unsupported block type

on bigqtable.tf line 51, in resource "google_bigquery_table" "bq_tables_rgpt":
51: range_partitioning {

Blocks of type "range_partitioning" are not expected here.

**Comment by tristan957** [comment]
I already answered you yesterday. Are you using the beta provider?

**Comment by sid0911** [comment]
Thanks for your response tristan957. 
Yes, I am using beta provider

**Comment by tristan957** [comment]
Post your whole resource definition

**Comment by sid0911** [comment]
Here is my resource definition:

resource "google_bigquery_table" "bq_tables_rgpt" {
  project       = var.project_id
  dataset_id    = google_bigquery_dataset.tera_gcp_dtset1.dataset_id
  table_id      = "btd_ebim_fal_product_agg_mnth"
  friendly_name = "Weather Loactions"
  schema     = file("${path.module}/files/createTableSqls/rangept/btd_ebim_fal_product_agg_mnth.json")
  range_partitioning {
   type     = "INTEGER"
    field    = "year_month"
    range {
    start    = 200001
    end      = 209912
    interval = 1
  }
}
  depends_on = [google_bigquery_dataset.tera_gcp_dtset1]
}

**Comment by tristan957** [comment]
post where you instantiate your provider

**Comment by sid0911** [comment]
provider "google" {
  version = "~> 3.11"
  credentials = file("creds/round-pilot-267411-bd02bbe634d8.json")
  project     = "round-pilot-267411"
  region      = "us-central1"
}

provider "google-beta" {
  version = "~> 3.11"
  credentials = file("creds/round-pilot-267411-bd02bbe634d8.json")
}

terraform {
  backend "gcs" {}
}

**Comment by tristan957** [comment]
you have to specify your beta provider in your resource otherwise you will use the non-beta provider. Reminder that GitHub is not a support forum.

**Comment by sid0911** [comment]
Thank you so much, Tristan. Appreciate your help!

**Comment by tristan957** [comment]
no problem. Good luck with your work.
