### ISSUE TITLE
Pub/sub topic not found while creating topic+subscription

### ISSUE THREAD

**Issue by michael-databerries** [terraform-providers/terraform-provider-google#524]
Hi there,

### Terraform Version
Terraform v0.10.2

### Affected Resource(s)
Please list the resources as a list, for example:
- google_pubsub_topic
- google_pubsub_subscription

### Terraform file

> resource "google_pubsub_topic" "bidder-response-request" {
>   name = "bidder-response-request"
> }
> 
> resource "google_pubsub_subscription" "bidder-response-request-to-bq" {
>   name  = "bidder-response-request-to-bq"
>   topic = "bidder-response-request"
> 
>   ack_deadline_seconds = 20
> }

### Debug Output

> ➜ terraform apply  
> google_pubsub_subscription.bidder-refused-request-to-bq: Creating...
>   ack_deadline_seconds: "" => "20"
>   name:                 "" => "bidder-refused-request-to-bq"
>   path:                 "" => "<computed>"
>   topic:                "" => "bidder-refused-request"
> google_pubsub_topic.bidder-response-request: Creating...
>   name: "" => "bidder-response-request"
> google_pubsub_subscription.bidder-accepted-request-to-bq: Creating...
>   ack_deadline_seconds: "" => "20"
>   name:                 "" => "bidder-accepted-request-to-bq"
>   path:                 "" => "<computed>"
>   topic:                "" => "bidder-accepted-request"
> google_pubsub_topic.bidder-accepted-request: Creating...
>   name: "" => "bidder-accepted-request"
> google_pubsub_subscription.bidder-response-request-to-bq: Creating...
>   ack_deadline_seconds: "" => "20"
>   name:                 "" => "bidder-response-request-to-bq"
>   path:                 "" => "<computed>"
>   topic:                "" => "bidder-response-request"
> google_pubsub_topic.bidder-refused-request: Creating...
>   name: "" => "bidder-refused-request"
> google_pubsub_topic.bidder-response-request: Creation complete (ID: projects/databerries-staging/topics/bidder-response-request)
> google_pubsub_topic.bidder-refused-request: Creation complete (ID: projects/databerries-staging/topics/bidder-refused-request)
> google_pubsub_topic.bidder-accepted-request: Creation complete (ID: projects/databerries-staging/topics/bidder-accepted-request)
> Error applying plan:
> 
> 3 error(s) occurred:
> 
> * google_pubsub_subscription.bidder-accepted-request-to-bq: 1 error(s) occurred:
> 
> * google_pubsub_subscription.bidder-accepted-request-to-bq: googleapi: Error 404: Resource not found (resource=bidder-accepted-request)., notFound
> * google_pubsub_subscription.bidder-response-request-to-bq: 1 error(s) occurred:
> 
> * google_pubsub_subscription.bidder-response-request-to-bq: googleapi: Error 404: Resource not found (resource=bidder-response-request)., notFound
> * google_pubsub_subscription.bidder-refused-request-to-bq: 1 error(s) occurred:
> 
> * google_pubsub_subscription.bidder-refused-request-to-bq: googleapi: Error 404: Resource not found (resource=bidder-refused-request)., notFound
> 
> Terraform does not automatically rollback in the face of errors.
> Instead, your Terraform state file has been partially updated with
> any resources that successfully completed. Please address the error
> above and apply again to incrementally change your infrastructure.
> ➜   terraform apply
> google_pubsub_topic.bidder-accepted-request: Refreshing state... (ID: projects/databerries-staging/topics/bidder-accepted-request)
> google_pubsub_topic.bidder-response-request: Refreshing state... (ID: projects/databerries-staging/topics/bidder-response-request)
> google_pubsub_topic.bidder-refused-request: Refreshing state... (ID: projects/databerries-staging/topics/bidder-refused-request)
> google_pubsub_subscription.bidder-refused-request-to-bq: Creating...
>   ack_deadline_seconds: "" => "20"
>   name:                 "" => "bidder-refused-request-to-bq"
>   path:                 "" => "<computed>"
>   topic:                "" => "bidder-refused-request"
> google_pubsub_subscription.bidder-accepted-request-to-bq: Creating...
>   ack_deadline_seconds: "" => "20"
>   name:                 "" => "bidder-accepted-request-to-bq"
>   path:                 "" => "<computed>"
>   topic:                "" => "bidder-accepted-request"
> google_pubsub_subscription.bidder-response-request-to-bq: Creating...
>   ack_deadline_seconds: "" => "20"
>   name:                 "" => "bidder-response-request-to-bq"
>   path:                 "" => "<computed>"
>   topic:                "" => "bidder-response-request"
> google_pubsub_subscription.bidder-response-request-to-bq: Creation complete (ID: projects/databerries-staging/subscriptions/bidder-response-request-to-bq)
> google_pubsub_subscription.bidder-accepted-request-to-bq: Creation complete (ID: projects/databerries-staging/subscriptions/bidder-accepted-request-to-bq)
> google_pubsub_subscription.bidder-refused-request-to-bq: Creation complete (ID: projects/databerries-staging/subscriptions/bidder-refused-request-to-bq)
> 
> Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

### Expected Behavior

It should have created the topic then create the subscription

### Actual Behavior
only create the topic

### Steps to Reproduce
terraform apply

Thanks in advance,
Michael

**Comment by rosbo** [comment]
I can't repro your issue. What version of the google providers are you using?

It should print the version when running `terraform init`. You can also run `terraform init --upgrade` to fetch the latest version of the `terraform-provider-google`.

**Comment by rosbo** [comment]
I will close the issue for now. Let me know if you still experience this issue with the latest version of our provider.

**Comment by rickenharp** [comment]
I just ran into the same problem with the latest version of the provider (1.2.0). I always have to run `make apply` twice on a fresh install to create the subscriptions.

**Comment by rosbo** [comment]
You should use interpolation in your config to make sure the topic gets created before the subscription.

The config should be:

```hcl
resource "google_pubsub_topic" "bidder-response-request" {
name = "bidder-response-request"
}

resource "google_pubsub_subscription" "bidder-response-request-to-bq" {
name = "bidder-response-request-to-bq"
topic = "${google_pubsub_topic.bidder-response-request.name}"

ack_deadline_seconds = 20
}
```
