### ISSUE TITLE
Fix google_bigquery_table encryption_configuration modifications

### ISSUE THREAD

**Issue by slevenick** [terraform-providers/terraform-provider-google#5241]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

See: https://github.com/GoogleCloudPlatform/magic-modules/pull/2763

This field is currently updatable.

This field should ForceNew on removing the `encryption_configuration`, and updatable on adding `encryption_configuration`. Removing this field causes an error from the API with the following message: `Changing from Default to Cloud KMS encryption key and back must be done via table.copy job.`

Adding this field correctly updates the table and adds encryption, so we should not simply add `ForceNew` on the field.

### New or Affected Resource(s)

* google_bigquery_table

### References

https://github.com/GoogleCloudPlatform/magic-modules/pull/2763

**Comment by MartinNowak** [comment]
> This field should ForceNew on removing the `encryption_configuration`, and updatable on adding `encryption_configuration`. Removing this field causes an error from the API with the following message: `Changing from Default to Cloud KMS encryption key and back must be done via table.copy job.`

@slevenick while there is no API error when adding an encryption key to a previously unencrypted (default encrypted) table, it doesn't actually have any effect in BigQuery. This is the same behavior as with the BigQuery CLI, it silently passes, but doesn't actually switch to CMEK.
```bash
bq update \
--destination_kms_key projects/project_id/locations/location/keyRings/key_ring/cryptoKeys/key \
-t dataset_id.table_id
```

So the docs are correct in that you need a full copy atm. to switch to/from CMEK.
https://cloud.google.com/bigquery/docs/customer-managed-encryption#change_to_kms
Updates only work when changing the key.
https://cloud.google.com/bigquery/docs/customer-managed-encryption#change_key

**Comment by emilymye** [comment]
@MartinNowak Sorry to butt in since I'm not fully up-to-speed on the unique behavior of bigquery, but this *sounds* like it might be a good use-case for [CustomDiff](https://www.terraform.io/docs/extend/resources/customizing-differences.html)? Particularly [`ForceNewIfChange`](https://github.com/hashicorp/terraform/blob/master/helper/customdiff/force_new.go#L32), which can force new on "not-set" --> "set" and "set" --> "not-set", but update on "set to key 1" --> "set to key 2". 

I also don't typically know if users really, really need the ability to update the table and would be ok with force-recreating no matter what, since the API behavior is undocumented and could choose to silently succeed but actually not update at any point.

**Comment by ndmckinley** [comment]
After some discussion, it seems like the correct move here is to just mark this field `ForceNew` - the API call to add encryption succeeds, but doesn't do anything.  Approved @MartinNowak's PR and will merge once the magician finished running.
