### ISSUE TITLE
google_compute_router_peer requires replace due to `advertise_mode` when upgrading to 2.3

### ISSUE THREAD

**Issue by bitglue** [terraform-providers/terraform-provider-google#5243]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
terraform -v
Terraform v0.12.17
+ provider.aws v2.43.0
+ provider.cloudflare v2.3.0
+ provider.google v3.3.0
+ provider.google-beta v3.3.0
+ provider.random v2.2.1
+ provider.template v2.1.2
```

but the state was written by:

```
terraform version
Terraform v0.12.17
+ provider.aws v2.41.0
+ provider.cloudflare v2.2.0
+ provider.google v2.20.0
+ provider.google-beta v3.2.0
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Affected Resource(s)

* google_compute_router_peer

### Terraform Configuration Files

```tf
resource "google_compute_router_peer" "transit" {
  project = var.project
  count   = length(var.transit_router_ips)
  name    = "peer-${count.index}"
  router  = google_compute_router.transit.name
  region  = var.region
  peer_ip_address = cidrhost(
    google_compute_router_interface.transit[count.index].ip_range,
    2,       
  )
  peer_asn  = var.transit_asn
  interface = google_compute_router_interface.transit[count.index].name
}
```

### Debug Output

```
terraform plan

  # module.shared-gcp-stage-west-1.google_compute_router_peer.transit[1] must be replaced
-/+ resource "google_compute_router_peer" "transit" {
      + advertise_mode            = "DEFAULT" # forces replacement
      - advertised_groups         = [] -> null
      - advertised_route_priority = 0 -> null
      ~ id                        = "us-west1/gcp-uswest1-stage/peer-1" -> (known after apply)
        interface                 = "interface-1"
      ~ ip_address                = "169.254.228.77" -> (known after apply)
      + management_type           = (known after apply)
        name                      = "peer-1"
        peer_asn                  = 65001
        peer_ip_address           = "169.254.228.78"
        project                   = "postmates-network-stage-20292"
        region                    = "us-west1"
        router                    = "gcp-uswest1-stage"
    }
```

### Expected Behavior

No resource replacement should be required: the proposed new state is equivalent to what's currently live.

### Actual Behavior

Terraform destroys and recreates the resource.

### Steps to Reproduce

1. Apply with terraform-google v2.20.0
2. Upgrade to v3.3
3. Apply (or just plan)

### Important Factoids

A workaround is to add an explicit `advertise_mode = ""` to the resource.

### References

Only maybe relevant thing I find in the changelog is https://github.com/terraform-providers/terraform-provider-google/pull/4503

**Comment by emilymye** [comment]
Would it be possible to get the full config/state before and after, and debug logs (i.e. run with `TF_LOG="DEBUG"`) ? I just tried with TF 0.12.17 (and 18) where I created using v2.20, changed my provider version to 3.20 and re-applied and I couldn't recreate. My config:

```
resource "google_compute_router_peer" "foobar" {
  name                     = "my-peer"
  router                    = google_compute_router.foobar.name
  region                    = google_compute_router.foobar.region
  peer_ip_address   = ...
  peer_asn               = ...
  advertised_route_priority = 100
  interface                 = google_compute_router_interface.foobar.name
}

(plus other resources)
```

I'm noticing that my state for v2.20 also has `advertise_mode = "DEFAULT"` set when I have no advertise_mode set in my config, and I don't see a diff when I reapply after changing my provider version.. Did you create the resource with an even older version maybe? 

Another workaround might be to remove the resource from state and import it into state after upgrade, to prevent needing the explicity empty.

**Comment by venkykuberan** [comment]
@bitglue if you still need help on this issue, please provide the details asked above.

**Comment by bitglue** [comment]
It's quite possible the resource was created with an older version, but sharing the entire state is not something I can do. I understand if you'd prefer to simply close the issue.

**Comment by venkykuberan** [comment]
Thank you @bitglue, I will close this issue. Please open a new one in case if you happened to hit the issue again.
