### ISSUE TITLE
google_project_iam_binding for custom role must be replaced after import

### ISSUE THREAD

**Issue by charleskorn** [terraform-providers/terraform-provider-google#5250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.18
+ provider.google v3.2.0
+ provider.null v2.1.2
```

### Affected Resource(s)

* `google_project_iam_binding`

### Terraform Configuration Files

```tf
resource "google_project_iam_custom_role" "deployer" {
  role_id     = "deployer"
  title       = "Deployer"
  description = "Permissions required to deploy the application"
  project     = google_project.project.project_id

  permissions = [
    // ...
  ]

  depends_on = [google_project_service.iam]
}

resource "google_project_iam_binding" "deployer" {
  role    = google_project_iam_custom_role.deployer.id
  project = google_project.project.project_id
  members = ["group:my-group@googlegroups.com"]
}
```

### Expected Behavior

If the binding already exists and matches the requirements, no changes need to be applied.

### Actual Behavior

`terraform plan` shows changes need to be made, even though the binding is in the desired state:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_project_iam_binding.deployer must be replaced
-/+ resource "google_project_iam_binding" "deployer" {
      + etag    = (known after apply)
      ~ id      = "my-project/roles/deployer" -> (known after apply)
      ~ members = [
          + "group:my-group@googlegroups.com",
        ]
        project = "my-project"
      ~ role    = "roles/deployer" -> "projects/my-project/roles/deployer" # forces replacement
    }
```

The `roles/deployer` syntax is only permitted for built-in roles, custom roles must be specified with the full `projects/my-project/roles/deployer` syntax.

### Steps to Reproduce

1. Create `.tf` file with content similar to above
2. Apply
3. Delete state file
4. Import existing state (eg. `terraform import google_project_iam_custom_role.deployer "projects/my-project/roles/deployer" && terraform import google_project_iam_binding.deployer "my-project roles/deployer"`
5. Run `terraform plan`

Manually editing the `.tfstate` file with the correct value for `role` for the `google_project_iam_binding` resource produces the expected behaviour.

### References

* May be related to #1296

**Comment by emilymye** [comment]
In general, we suggest that you don't use `.id` for a resource, as this is a Terraform-specific ID and we have historically changed it. We typically don't document it for that reason. 

Probably the best workaround for this right now would be interpolating the `role_id` and `project`, i.e. 

```
resource "google_project_iam_binding" "deployer" {
  role = join("/", [
    "projects",
    google_project_iam_custom_role.deployer.project,
    "roles",
    google_project_iam_custom_role.deployer.role_id,
  ])

  project = google_project.project.project_id
  members = ["group:my-group@googlegroups.com"]
}
```

In the meantime, I think it might be good to 
a) creating a Terraform-specific `role_name` field that is output for you so you don't have to use .id/`join()`
b) create an example where we actually interpolate custom roles into a binding

so I'll use this issue to track that work.

**Comment by charleskorn** [comment]
Thanks for your quick response @emilymye. 

It looks like the issue is not with what `role` is set to in the resource, but the value that is stored in state when the binding is imported - it's always imported in the short form (`roles/deployer`) when the correct value is the longer form for custom roles.

**Comment by emilymye** [comment]
After some more careful reading on my part, I realized you're using the short-hand role to import the binding. Have you tried importing with the full role name? i.e. 

```
terraform import google_project_iam_binding.deployer "my-project projects/my-project/roles/deployer"
```

I just did that and it worked. 

I'll add some checks to be stricter about how we read the bindings - it seems that we are allowing importing with "roles/custom-role" if we see "projects/my-proj/roles/custom-role" in the IAM policy) but importing using the full role name should fix your issue.

**Comment by charleskorn** [comment]
Yep that works - thanks for your help @emilymye.

**Comment by emilymye** [comment]
Ah, this is a more complicated problem! So, currently, the way in which we import bindings allows for empty bindings, i.e. if a binding for a role isn't found, it's still imported but with no members. That's why your diff also shows adding the member back in. When you re-apply, your members will get added with the appropriate bindings. 

However, because import uses the values you give in the import command, i.e. `terraform import project roles/my-custom-role` instead of `resource ... { role = projects/.../roles/... }` , we are weirdly doing the expected right behavior. We didn't find a binding for roles/customRoles, so we assume the user is going to add the real binding in reapply, and there's no way for us to tell that the role is meant to be a custom role unless it's specified by the user during import 🤷‍♀ 

I'm not entirely sure why we allow the empty members import, but I'll need to ask around before I stomp on this behavior - I'm certain there was historically a good reason for adding it. For now, it might just be that on import you'll just have to be careful about using the full role name. I also believe reapply will just re-read the policy and then no-op if the binding added already exists, and the read comparison actually compares the full role name.

**Comment by emilymye** [comment]
Closing this issue - currently we don't see a way to resolve this other than being careful when importing or being ok with the extra apply. We have to allow both import and reading bindings with empty roles so users can revoke access easily, and we can't determine on our end the difference between roles/my-custom-role and roles/built-in-role.
