### ISSUE TITLE
Error creating InstanceGroupManager: googleapi: Error 400: Invalid value for field 'resource.versions[0].instanceTemplate

### ISSUE THREAD

**Issue by judika03** [terraform-providers/terraform-provider-google#5252]
### Community Note
Error creating InstanceGroupManager: googleapi: Error 400: Invalid value for field 'resource.versions[0].instanceTemplate':
Unexpected resource collection 'instances'., invalid

### Terraform Version
Terraform v0.12.0

provider.google v3.2.0
provider.google-beta v3.2.0
provider.template v2.1.2
### Affected Resource(s)

* google_compute_instance_template
* google_compute_instance_from_template
* google_compute_instance_group_manager

### Terraform Configuration Files

```tf
resource "google_compute_instance_template" "redis-1" {
  project              = "${var.project}"
  name                 = "redis-7000-7002-${var.cluster_name}-${local.runid}-0"
  description          = "redis instance template"
  
  instance_description = "Redis Server"
  machine_type         = "${var.instance_type}"
  can_ip_forward       = false
  tags                 = ["redis"]
  labels = {
    template = "tf-redis"
    cluster_name = "${var.cluster_name}"
    node_type = "static"
  }
  metadata = {
    startup-script = "${data.template_file.startup1.rendered}"
  }
  disk {
    source_image = "debian-cloud/debian-9"
    disk_size_gb = "${var.disk_size_gb}"
    type         = "pd-standard"
  }
  
    network_interface {
    network = "default"
   
  }
  service_account {
    email  = "${var.service_account}@${var.project}.iam.gserviceaccount.com"
    scopes = ["cloud-platform"]

  }
  scheduling {
    automatic_restart   = true
    on_host_maintenance = "MIGRATE"
  }
  lifecycle {
    create_before_destroy = true
  }
}

resource "google_compute_instance_from_template" "tpl" {
  name = "instance-from-template"
    project              = "${var.project}"
   zone = "asia-southeast1-a"

  source_instance_template = google_compute_instance_template.redis-1.self_link

  // Override fields from instance template
  can_ip_forward = false
  labels = {
    my_key = "my_value"
  }
}
resource "google_compute_instance_group_manager" "redis1" {
  provider           = "google-beta"
  project            = "${var.project}"
  name               = "redis1-${var.cluster_name}"
  base_instance_name = "redis1-${var.cluster_name}"
  zone               = "${var.zone_a}"
  target_size        = 1
  version {
    name              = "v1"
    instance_template = "${google_compute_instance_from_template.tpl.self_link}"
  }
 

}
```

### Debug Output

Error creating InstanceGroupManager: googleapi: Error 400: Invalid value for field 'resource.versions[0].instanceTemplate':
Unexpected resource collection 'instances'., invalid
--->

### Steps to Reproduce

1. `terraform apply`

**Comment by emilymye** [comment]
It looks like your config sets `instance_template` to the instance-from-template self-link, not the actual `redis-1` template resource self_link. I'm guessing this is just a typo since you named your instance (from-template) `tpl`.

i.e.

> `instance_template = "${google_compute_instance_from_template.tpl.self_link}" `

should be 
`instance_template = "${google_compute_instance_template.redis-1.self_link}"`

Both instance-from-template and IGMs depend on an instance template, not template <-- instance from template <-- IGM. 

Please feel free to re-open if you have more questions!

**Comment by judika03** [comment]
I'm already to testing google_compute_instance_from_template to adding rrdatas google_dns_record_set already done, but I want use google_compute_instance_from_template to create instance group. I have purpose to create template instance is google_compute_instance_group_manager, I want to create many instance to one group from template instance, Is it possible to google_compute_instance_from_template to google_compute_instance_group_manager.
