### ISSUE TITLE
google_cloud_run_service destroys and recreates service when adding an environment variable

### ISSUE THREAD

**Issue by charleskorn** [terraform-providers/terraform-provider-google#5263]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.18
+ provider.google v3.2.0
```

### Affected Resource(s)

* `google_cloud_run_service`

### Terraform Configuration Files

First step:

```tf
resource "google_cloud_run_service" "service" {
  name     = "my-service"
  location = "us-central1"

  template {
    spec {
      containers {
        image = var.image_reference

        env {
          name  = "CONFIG_VAR_1"
          value = "foo"
        }
      }
    }
  }
}
```

Second step:

```tf
resource "google_cloud_run_service" "service" {
  name     = "my-service"
  location = "us-central1"

  template {
    spec {
      containers {
        image = var.image_reference

        env {
          name  = "CONFIG_VAR_1"
          value = "foo"
        }

        env {
          name  = "CONFIG_VAR_2"
          value = "bar"
        }
      }
    }
  }
}
```

### Expected Behavior

A new revision is added to the existing service with the new environment variable

### Actual Behavior

The existing service is destroyed and a new one is created with the new environment variable.

This causes a service interruption and destroys all revision history.

### Steps to Reproduce

1. `terraform apply` the 'first step' configuration above
2. `terraform apply` the 'second step' configuration above

### References

* https://cloud.google.com/run/docs/reference/rest/v1/namespaces.services/replaceService may be relevant

**Comment by venkykuberan** [comment]
@charleskorn Thank you for pointing out. We are forcenewing it whenever there is a change in env variables which we shouldn't be. I will add this item for code change on the provider.
