### ISSUE TITLE
conflicts with are called out both ways

### ISSUE THREAD

**Issue by jsoref** [terraform-providers/terraform-provider-google#5284]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_instance_template

### Terraform Configuration Files

```tf
provider google {
  version = "~> 3.0"
}

resource "google_compute_instance_template" "node" {
  name         = "node"
  name_prefix  = ""
  machine_type = "n1-standard-1"
}

```

### Expected Behavior

Only report things once.
In this example, that means one call out for the lack of a disk, and one call out for the pair `name`, `name_prefix`. Here, there are two callouts for the pair.

### Actual Behavior

```
Error: "disk": required field is not set

  on terraform.tf line 9, in resource "google_compute_instance_template" "node":
   9: resource "google_compute_instance_template" "node" {



Error: "name_prefix": conflicts with name

  on terraform.tf line 9, in resource "google_compute_instance_template" "node":
   9: resource "google_compute_instance_template" "node" {



Error: "name": conflicts with name_prefix

  on terraform.tf line 9, in resource "google_compute_instance_template" "node":
   9: resource "google_compute_instance_template" "node" {
```

### Steps to Reproduce

1. `terraform plan`

### References

**Comment by edwardmedia** [comment]
The error message could be more accurate

**Comment by jsoref** [comment]
Yes. blaming line 9 twice instead of blaming/listing line 10 at least once is unfortunate.

**Comment by danawillow** [comment]
I'm happy to make the change for this resource specifically- however, as a whole, I think this should be fixed in the provider SDK itself. For 2 fields that conflict with each other, it's easy enough to just set one of them, but if there were 3, the only way to accurately have the plan fail is to set ConflictsWith on at least two of them. Filed https://github.com/hashicorp/terraform-plugin-sdk/issues/286 for the general solution, and I'll make a PR for this specific case now.
