### ISSUE TITLE
bigquery_data_transfer_config - 'partition_field' missing from resource

### ISSUE THREAD

**Issue by kurtmaile** [terraform-providers/terraform-provider-google#5317]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Hopefully a simple one - the 'partition field' is missing from the bq data transfer config.

This can be set via the UI (older one at least)

<img width="443" alt="Screenshot 2020-01-06 11 38 50" src="https://user-images.githubusercontent.com/20066181/71816037-48df6f00-3079-11ea-8c11-934ee4af32ad.png">

### New or Affected Resource(s)

* bigquery_data_transfer_config

### Potential Terraform Configuration

part of 

```params.partition_field```

### References

* #0000

**Comment by danawillow** [comment]
Hey @kurtmaile, `params` is a map so you can put any value you'd like in the key. If the API accepts `partition_field` as a param, then you can do it without any changes to the provider.

Looking at the docs a bit, I'm not totally sure how you would do it, but I did find https://cloud.google.com/bigquery-transfer/docs/gcs-transfer-parameters#partitioning_options which hopefully helps (it's GCS-specific but you can look in the sidebar for similar docs for other sources).

Hope this helps!

**Comment by kurtmaile** [comment]
Hi,

Thanks - this worked for ```partitioning_field```, which could be one of these.

However, ```email_preferences``` needs to be an explicit top level config item as its not related to the data sourced, rather, the transfer config itself as below .  thanks heaps!

```
resource "google_bigquery_data_transfer_config" "cfg"  {

  display_name = "name"
  location = "EU"
  data_source_id = "scheduled_query"
  schedule = "every sun 23:00"
  destination_dataset_id = "sdv_dims"
  //email_preferences = "support@domain.com"
  params = {
    destination_table_name_template = "stock_level_history_dim"
    write_disposition = "WRITE_TRUNCATE"
    query = "SELECT * FROM `aProject.aDataset.aTable`"
    partitioning_field = "pt"
  }
  disabled =  false
}
```

**Comment by danawillow** [comment]
Is there a programatic way to set that? If so, would you mind filing a new FR that links to the cloud.google.com page that says how to set that field? All I'm seeing is https://cloud.google.com/bigquery-transfer/docs/transfer-run-notifications#email_notifications which says "These messages are sent to the user who set up the transfer", so my impression is that would be whatever account you're authenticating to TF with.
