### ISSUE TITLE
Update documentation on how to use google_compute_region_instance_group_manager

### ISSUE THREAD

**Issue by timurshevekhman** [terraform-providers/terraform-provider-google#532]
Apologies in advance if this is not a proper place to report documentation feedback.

Now that google_compute_region_instance_group_manager (thank you!) is available to us, I believe we can use it with google_compute_region_backend_service. [Documentation](https://www.terraform.io/docs/providers/google/r/compute_region_backend_service.html) is still referring to google_compute_instance_group_manager. 

Per Google [documentation](https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups#adding_a_regional_managed_instance_group_to_a_load_balancer)
> You can assign a regional managed instance group as a target of a backend service for external load balancing and [internal load balancing(/compute/docs/load-balancing/) or as part of a target pool for Network load balancing.

It would be good to see Terraform documentation be updated with examples for both cases.

**Comment by rosbo** [comment]
Thanks @ timurshevekhman!

Yes, this is the right place for this issue. I opened a PR (#533) to fix it. Let me know if you have further suggestions for improving this documentation page.

**Comment by timurshevekhman** [comment]
Documentation says 

> protocol - (Optional) The protocol for incoming requests. Defaults to HTTP.

It looks like it's actually TCP. When I tried setting protocol value to HTTP, I got the following error:

>Error creating backend service: googleapi: Error 400: Invalid value for field 'resource.protocol': 'HTTPS'. Protocol for an INTERNAL backend service must be one of TCP/UDP.

Per [Google](https://cloud.google.com/compute/docs/load-balancing/internal/#backend-service)

> --protocol (default: http) — The protocol, either tcp or udp, that the load balancer will process. This parameter must match the --protocol parameter specified for the forwarding rule. The protocol is required for backend services as the default value is http and **only tcp and udp are supported for Internal load balancing**. 

The confusing part is that in GCP it is possible to create a regional backend service that can be used to serve either external or internal traffic. It appears  (please correct me if I am wrong), `google_compute_region_backend_service` will always create an internal load balancer. Perhaps, if you want to have Internet facing LB, `google_compute_region_backend_service` is not the right resource.

**Comment by danielcompton** [comment]
I think the title and tags on this issue are no longer accurate, it's not that better documentation is needed (AFAICT), it's that it isn't actually possible to create a `google_compute_region_backend_service` that uses the HTTP protocol.

**Comment by danielcompton** [comment]
After digging into this a bit more, I think this is just a docs issue. If you want a regional managed instance group, you need to create a `google_compute_region_instance_group_manager` and you connect that up to a `google_compute_backend_service`.

I _think_ that https://www.terraform.io/docs/providers/google/r/compute_region_backend_service.html should have a warning saying that this is only used for internal load balancing, and that it should remove this line saying that it defaults to HTTP, possibly mentioning that HTTP protocols are done via a compute backend service.

> * protocol - (Optional) The protocol for incoming requests. Defaults to HTTP.

The [API docs](https://cloud.google.com/compute/docs/reference/rest/v1/regionBackendServices) say that the HTTP protocol is supported, but I can't see how, and suspect that may be from an autogenerated protobuf docs. The [main docs](https://cloud.google.com/compute/docs/load-balancing/internal/) say

> protocol (either TCP or UDP).

**Comment by paddycarver** [comment]
So largely thanks to your excellent notes here, I think I've deciphered this. The only mention of "regional backend services" I can seem to find is in the UI to manage load balancers, under "Advanced". From what I can see, it can only be used for internal load balancing. And according to the docs for ILB, it routes at a TCP or UDP level, meaning it couldn't create an HTTP protocol load balancer.

I'll open a PR right now with some clarifying language.
