### ISSUE TITLE
Provider 3.3.0 introduces a change in filter attribute for google_logging_project_sink resource

### ISSUE THREAD

**Issue by yannlambret** [terraform-providers/terraform-provider-google#5327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Core version: v0.12.8
Google provider version: v3.3.0

### Affected Resource(s)

google_logging_project_sink

### Terraform Configuration Files

The code below is an excerpt of a module that automates the creation of mutliple resources, as part of the overall network configuration:

```tf
locals {
  // set a default value for the filter, if no value is provided to the module
  filter = var.flow_logs_sink_filter != null ? var.flow_logs_sink_filter : "resource.type=\"gce_subnetwork\" logName=\"projects/${local.project_id}/logs/compute.googleapis.com%2Fvpc_flows\""
}

resource "google_logging_project_sink" "flow_logs_sink" {
  name                   = "${google_compute_network.network.name}-flow-logs-sink"
  destination            = "storage.googleapis.com/${google_storage_bucket.flow_logs_bucket.name}"
  filter                 = local.filter
  unique_writer_identity = true
}
```

### Expected Behavior

Nothing, as we did not change anything (module code or values provided to the module).

### Actual Behavior

Terraform wants to apply a change, by appending an extra heading ```projects/``` to the ```logName``` field of the filter:

```text
  # module.network.google_logging_project_sink.flow_logs_sink will be updated in-place
  ~ resource "google_logging_project_sink" "flow_logs_sink" {
        destination            = "storage.googleapis.com/<bucket-name>"
      ~ filter                 = "resource.type=\"gce_subnetwork\" logName=\"projects/<fake-project-id>/logs/compute.googleapis.com%2Fvpc_flows\"" -> "resource.type=\"gce_subnetwork\" logName=\"projects/projects/<fake-project-id>/logs/compute.googleapis.com%2Fvpc_flows\""
        id                     = "projects/<fake-project-id>/sinks/<network-name>-flow-logs-sink"
        name                   = "<network-name>flow-logs-sink"
        project                = "<fake-project-id>"
        unique_writer_identity = true
        writer_identity        = "serviceAccount:<fake-sa-id>@gcp-sa-logging.iam.gserviceaccount.com"
    }
```
Sorry for the quite unusual output, I've performed some sanitization on data.

### Important Factoids

I've also ran a ```terraform plan``` with the v2.20.1 provider, and everything is fine (no changes detected). I believe the change of behavior is related to this commit: https://github.com/terraform-providers/terraform-provider-google/commit/dcd9a286cdfca8f6c5e16c92cf17d1c93910a85d, but I didn't take the time to look further into it.

**Comment by edwardmedia** [comment]
@yannlambret config changes are expected between versions as the new ones are needed to cover more use cases. Can you tell us why you think this `appending` should not happen in general?

**Comment by yannlambret** [comment]
Hi @edwardmedia, I didn't understand that this change was made on purpose. I have nothing against configuration changes as a general rule, but I don't really see the added value of this one, given the fact that we have to provide a lot of additional information in the ```logName``` field. But if this is the intended behavior, I will change our configuration and close this issue.

**Comment by edwardmedia** [comment]
@yannlambret Sorry about the change which causes you headache. Please modify your configuration accordingly as you plan to use new versions of providers. I am closing the issue. You may reopen it if you think you need further discussions or assistance. Thanks
