### ISSUE TITLE
Issues that are waiting-response should get marked stale

### ISSUE THREAD

**Issue by chrisst** [terraform-providers/terraform-provider-google#5334]
Similarly to how hashibot auto closes stale issues, hashibot should also mark an issue as `stale` if it has had a `waiting-response` label for a configurable amount of time.

**Comment by paddycarver** [comment]
Because this is a feature request for hashibot, I'm going to move it to the hashibot repo, instead of tracking it here. I opened issue 104 for it. Unfortunately, that's a private repo, but the issue should be visible to at least some of the maintainers here.
