### ISSUE TITLE
'google_monitoring_alert_policy' can't successfully apply 'labels' after update from 3.3.0 to 3.4.0

### ISSUE THREAD

**Issue by radkomateusz** [terraform-providers/terraform-provider-google#5339]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.16
+ provider.google v3.4.0

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_monitoring_alert_policy" "http_500_per_hour_policy" {
  project = "project-id"
  display_name = "Sum of http 500 responses in last hour < 100"
  enabled = true
  combiner = "OR"
  conditions {
    display_name = "GAE Application - Response count for 500 [SUM] is above 100 per last hour"
    condition_threshold {
      filter = "metric.type=\"appengine.googleapis.com/http/server/response_count\" resource.type=\"gae_app\" metric.label.\"response_code\"=\"500\""
      comparison = "COMPARISON_GT"
      duration = "60s"
      threshold_value = 100
      trigger {
        count = 1
      }
      aggregations {
        alignment_period = "3600s"
        per_series_aligner = "ALIGN_SUM"
        cross_series_reducer = "REDUCE_SUM"
      }
    }
  }
}
```

### Expected Behavior

After successfully applying changes, resource is up to date. 

### Actual Behavior
1. `terraform apply`  - succesfully applied 
then: 
1. `terraform plan` 

```
  ~ resource "google_monitoring_alert_policy" "http_500_per_hour_policy" {
        combiner              = "OR"
        creation_record       = [
            {
                mutate_time = "2019-05-15T15:04:24.039203962Z"
                mutated_by  = "xx@xx.com"
            },
        ]
        display_name          = "Sum of http 500 responses in last hour < 100"
        enabled               = true
        id                    = "projects/project-id/alertPolicies/2014937487431631776"
      + labels                = (known after apply)
        name                  = "projects/project-id/alertPolicies/2014937487431631776"
        notification_channels = []
        project               = "project-id"
        user_labels           = {}

        conditions {
            display_name = "GAE Application - Response count for 500 [SUM] is above 100 per last hour"
            name         = "projects/project-id/alertPolicies/2014937487431631776/conditions/2014937487431634789"

            condition_threshold {
                comparison      = "COMPARISON_GT"
                duration        = "60s"
                filter          = "metric.type=\"appengine.googleapis.com/http/server/response_count\" resource.type=\"gae_app\" metric.label.\"response_code\"=\"500\""
                threshold_value = 100

                aggregations {
                    alignment_period     = "3600s"
                    cross_series_reducer = "REDUCE_SUM"
                    group_by_fields      = []
                    per_series_aligner   = "ALIGN_SUM"
                }

                trigger {
                    count   = 1
                    percent = 0
                }
            }
        }

        timeouts {}
    }
```
 it shows that `+ labels = (known after apply)`

Terraform still wants to update resource, even after successfully apply. Problem doesn't occurs in 3.3.0 provider version. It happens after 3.4.0

**Comment by gilberthdez** [comment]
Also happens in Terraform v0.12.18

**Comment by edwardmedia** [comment]
@gilberthdez it looks to me to me by design. @chrisst could you please answer?

**Comment by chrisst** [comment]
AlertPolicy labels was removed but as of https://github.com/GoogleCloudPlatform/magic-modules/pull/2910 is was changed to computed. This was done in an attempt to make sure any fields that previously had something set but are now removed would not have a diff when they were upgraded. It unfortunately had the opposite effect for this field. 
Resources should not have a diff that doesn't resolve in a single apply, and in almost all cases shouldn't have a diff when upgrading versions of the provider if nothing changed on the resource.

**Comment by chrisst** [comment]
This looks like it's an issue with Terraform core not calculating the diff correctly for attributes that are lists. I've filed an upstream bug, but if there isn't a quick resolution to it I can revert the change for our next version of the provider.

**Comment by chrisst** [comment]
Filed: https://github.com/hashicorp/terraform/issues/23814

**Comment by rileykarson** [comment]
We can also work around this by calling `d.Set("field", nil)` in `Read`. We've done that in a handful of places in the past where `Removed` complex values are (correctly) marked `Computed`.
