### ISSUE TITLE
Instance template creation uses a random, non-existent image

### ISSUE THREAD

**Issue by HebertCL** [terraform-providers/terraform-provider-google#5344]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

## Description

The workflow I am following is cooking an image using Packer, then use that image to create an instance template, then launch igm using the template. I have a module taking care for instance template and another for igm + autoscaler. I noticed the infra I was provisioning was in fact using a wrong image, so I made sure my image was properly cooked (correct builder an provisioners) and that, at the moment of launching an instance with it the image had the stuff I wanted. I also got rid of any older images and left only the correct one:

```
gcloud compute images list --filter=crabi-openvpn                         
NAME                             PROJECT      FAMILY  DEPRECATED  STATUS
crabi-openvpn-server-1578439795  crabi-admin                      READY
```
I then started creating my resources one by one instead of chaining my modules together to make sure resources provisioned correctly. After creating my template I made sure I got that right:

```
gcloud compute instance-templates list --filter=ovpn                                       
NAME              MACHINE_TYPE   PREEMPTIBLE  CREATION_TIMESTAMP
tf-ovpn-template  n1-standard-1               2020-01-08T11:06:21.384-08:00
```
Here's where things get bad. When I describe my template from gcloud the response seems right:

```
gcloud compute instance-templates describe tf-ovpn-template                                
creationTimestamp: '2020-01-08T11:06:21.384-08:00'
description: ''
id: '8121076812869244610'
kind: compute#instanceTemplate
name: tf-ovpn-template
properties:
  disks:
  - boot: true
    deviceName: persistent-disk-0
    index: 0
    initializeParams:
      diskName: tf-ovpn-template
      diskSizeGb: '100'
      diskType: pd-standard
      sourceImage: global/images/crabi-openvpn-server-1578439795
    interface: SCSI
    kind: compute#attachedDisk
    mode: READ_WRITE
    type: PERSISTENT
  machineType: n1-standard-1
  metadata:
...
```
On the Google Cloud console, however, the template boot disk appears empty:

![image](https://user-images.githubusercontent.com/24655209/72009820-4701e100-321c-11ea-9d7f-7e758e6de5e6.png)

If I keep forward and use the template that looks alright on gcloud CLI and weird on console, I end up with an instance managed group that on CLI side is what I expect, but in reality is somehow using an old image I created and deleted. Using `terraform show`:

```
# module.vpn_autoscaler.google_compute_instance_group_manager.gcp_managed_group:
resource "google_compute_instance_group_manager" "gcp_managed_group" {
    ...
    a lot of config info
    ...
    version {
        instance_template = "https://www.googleapis.com/compute/v1/projects/crabi-admin/global/instanceTemplates/tf-ovpn-template"
        name              = "tf-openvpn-v1"
    }
}
```
And then, checking in Google Cloud console:

![image](https://user-images.githubusercontent.com/24655209/72011092-b8429380-321e-11ea-9498-a8f982723ce6.png)

Notice the image ID in the screenshot is not even listed by gcloud command I posted previously. It is one of the images I cooked before, and ended up deleting to avoid noise while troubleshooting this.
I have successfully created an instance template with gcloud CLI, so I am unsure what goes wrong with Terraform provisioned infra, the results I see from CLI and console from those resources don't match, they look right on CLI, wrong on console and the truth is in fact what console shows me.

### Terraform Version

```
Terraform v0.12.12
+ provider.google v3.4.0
+ provider.google-beta v3.4.0
+ provider.null v2.1.2
```

### Affected Resource(s)

`google_compute_instance_template`

### Terraform Configuration Files

This is my instance template module code:
```tf
resource "google_compute_instance_template" "gcp_instance_template" {
  depends_on  = [
    "null_resource.provision_ready",
  ]
  
  name          = var.gcp_template_name
  project       = var.gcp_template_project
  machine_type  = var.gcp_template_machine
  tags          = flatten([var.gcp_template_target_tags])

  disk {
    auto_delete   = false
    source_image  = var.gcp_template_disk_image
    disk_name     = var.gcp_template_name
    disk_type     = var.gcp_template_disk_type
    disk_size_gb  = var.gcp_template_disk_size
    type          = var.gcp_template_gce_disk
  }

  network_interface {
    subnetwork          = var.gcp_template_subnetwork
    subnetwork_project  = var.gcp_template_subnetwork_project
    access_config {
      nat_ip            = var.gcp_template_nat_ip
    }
  }

  service_account {
    scopes  = var.gcp_template_sa_scopes
  }

  scheduling {
    preemptible       = var.gcp_template_preemptible
    automatic_restart = var.gcp_template_restart
  }
  
  lifecycle {
    create_before_destroy = true
  }
}

resource "null_resource" "provision_ready" {
  triggers  = {
    provision_ready = var.provision_ready
  }
}

resource "null_resource" "template_complete" {
  depends_on  = [
    "null_resource.provision_ready",
    "google_compute_instance_template.gcp_instance_template",
  ]
}
```
And this is the combination of modules I use it with

```tf
module "vpn_firewall" {
  source  = "/modules/google_network/firewall_allow"

  provision_ready             = var.provision_ready
  gcp_firewall_name           = var.vpn_firewall_name
  gcp_firewall_network        = data.terraform_remote_state.network.outputs.vpc_self_link
  gcp_firewall_allowed        = var.vpn_firewall_allowed
  gcp_firewall_source_ranges  = var.vpn_firewall_source_ranges
  gcp_firewall_target_tags    = var.vpn_firewall_target_tags
}

module "vpn_ip" {
  source = "/modules/google_network/compute_address"

  provision_ready   = var.provision_ready
  gcp_address_name  = var.gcp_address_name
}

module "vpn_template" {
  source = "/modules/google_compute/instance-template"

  provision_ready                 = module.vpn_firewall.firewall_allow_complete
  gcp_template_name               = var.gcp_template_name
  gcp_template_project            = var.gcp_project
  gcp_template_disk_image         = var.gcp_template_disk_image
  gcp_template_target_tags        = module.vpn_firewall.firewall_allow_tags
  gcp_template_subnetwork         = data.terraform_remote_state.network.outputs.vpn_self_link
  gcp_template_nat_ip             = module.vpn_ip.address_ip
  gcp_template_subnetwork_project = var.gcp_project
}
```
Both external IP and firewall tags can be substituted with variables using default or tfvars values. Only missing part is subnetwork data I source and can be substituted too with variable.

### Expected Behavior

Terraform should create a template using the specified image.

### Actual Behavior

Terraform creates a template with empty image, and ends up assigning a random, non-existing image to instance managed group.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by venkykuberan** [comment]
@HebertCL I am not able to repro your issue, however i am able to successfully create igm with the disk image given in the config and Cloud console shows the right image on instance template as well on the compute instance property page.

1. Created 2 disk images from gcloud (it does't matter how images are baked i believe)
  ```
 gcloud compute images list --filter=test
NAME                PROJECT             FAMILY  DEPRECATED  STATUS
centos6-test-image  xxx-external-org                      READY
debian9-test-image  xxx-external-org                      READY
``` 
2. 
```
variable "gcp_template_disk_image" {
  default = "xxx-external-org/centos6-test-image" //debian-cloud/debian-9
}
resource "google_compute_instance_template" "gcp_instance_template" {
  depends_on = [
    "null_resource.provision_ready",
  ]
  name         = "test-instance-template"
  project      = var.project_id
  machine_type = "n1-standard-1"
  disk {
    auto_delete  = true
    source_image = var.gcp_template_disk_image
    # disk_name    = "test-disk"
    # disk_type     = var.gcp_template_disk_type
    # disk_size_gb  = var.gcp_template_disk_size
    # type          = var.gcp_template_gce_disk
    boot = true
  }

   network_interface {
    network = "default"
  }
  lifecycle {
    create_before_destroy = true
  }
}

resource "null_resource" "provision_ready" {
  triggers = {
    provision_ready = var.provision_ready
  }
}
resource "null_resource" "template_complete" {
  depends_on = [
    "null_resource.provision_ready",
    "google_compute_instance_template.gcp_instance_template",
  ]
}
resource "google_compute_instance_group_manager" "appserver" {
  name = "appserver-igm"

  base_instance_name = "app"
  zone               = "us-central1-a"

  version {
    instance_template  = google_compute_instance_template.gcp_instance_template.self_link
  }
  target_size  = 2

  named_port {
    name = "custom-http"
    port = 8888
  }C
  project = var.project_id
}
```
3. verified that on the cloud console that both instance template and VMs shows the image picked.
```
![Screenshot from 2020-01-09 12-39-31](https://user-images.githubusercontent.com/16162214/72103199-92c88f00-32dd-11ea-95be-8d98ea345e52.png)
![Screenshot from 2020-01-09 12-38-39](https://user-images.githubusercontent.com/16162214/72103200-92c88f00-32dd-11ea-996f-5fbf2b33b27b.png)

Terraform v0.12.12
+ provider.google v3.4.0
+ provider.null v2.1.2
```
1. Can you try referring your image by <project_id>/<image_name> and see if it makes any difference ?.  
2. Not sure UI had some issues during that time. Please try again visiting the page and see it fixed by itself.

**Comment by HebertCL** [comment]
@venkykuberan thanks for the reply. As you mentioned, using the format `project-name/image-name` did the trick, and assign the desired image to my template as expected. After sorting this out I moved on to IGM and, once again, I faced with the same odd behavior where image the IGM isn't the one from template. I made extra testing this time, using a plain CentOS image and metadata startups script. I found that create the IGM, do some installing and configuring on that image, destroying and create would somehow do some kind of caching where after `terraform destroy` then `terraform apply` would give me the CentOS image with the changes I made and configs I added. I will work through the day to document this in detail, cause I know it sounds crazy.

**Comment by venkykuberan** [comment]
sure @HebertCL will wait for your more details

**Comment by HebertCL** [comment]
Continuing with my previous comment, I've documented my findings so it makes a bit more sense. While trying to get passed my issue with cooking images (which by the way, as you suggested, how image is cooked makes no difference) I decided to make it simple for me and have a startup script to handle the configuration. I will make sure to include a gist with my startup script, IGM module and main.
First off, I create my infrastructure that includes firewall, external ip, template, health check, instance group manager and target pool:
```
module.pritunl_health_check.null_resource.provision_ready: Creating...
module.pritunl_ip.null_resource.provision_ready: Creating...
module.pritunl_firewall.null_resource.provision_ready: Creating...
module.pritunl_firewall.null_resource.provision_ready: Creation complete after 0s [id=8946484505103071588]
module.pritunl_health_check.null_resource.provision_ready: Creation complete after 0s [id=470084763125577762]
module.pritunl_ip.null_resource.provision_ready: Creation complete after 0s [id=5193272350032900875]
module.pritunl_ip.google_compute_address.gcp_address: Creating...
module.pritunl_firewall.google_compute_firewall.gcp_firewall_allow: Creating...
module.pritunl_health_check.google_compute_health_check.gcp_health_check: Creating...
module.pritunl_health_check.google_compute_health_check.gcp_health_check: Creation complete after 3s [id=projects/crabi-admin/global/healthChecks/tf-pritunl-hc]
module.pritunl_health_check.null_resource.health_check_complete: Creating...
module.pritunl_health_check.null_resource.health_check_complete: Creation complete after 0s [id=3958501314416428358]
module.pritunl_ip.google_compute_address.gcp_address: Creation complete after 3s [id=projects/crabi-admin/regions/us-west2/addresses/tf-pritunl-ip]
module.pritunl_ip.null_resource.compute_address_complete: Creating...
module.pritunl_ip.null_resource.compute_address_complete: Creation complete after 0s [id=5611791132355977412]
module.pritunl_firewall.google_compute_firewall.gcp_firewall_allow: Creation complete after 8s [id=projects/crabi-admin/global/firewalls/tf-pritunl-ingress]
module.pritunl_firewall.null_resource.firewall_allow_complete: Creating...
module.pritunl_firewall.null_resource.firewall_allow_complete: Creation complete after 0s [id=2527067770774517577]
module.pritunl_template.null_resource.provision_ready: Creating...
module.pritunl_template.null_resource.provision_ready: Creation complete after 0s [id=3345939031198491119]
module.pritunl_template.google_compute_instance_template.gcp_instance_template: Creating...
module.pritunl_template.google_compute_instance_template.gcp_instance_template: Creation complete after 4s [id=projects/crabi-admin/global/instanceTemplates/tf-pritunl-tpl]
module.pritunl_template.null_resource.template_complete: Creating...
module.pritunl_template.null_resource.template_complete: Creation complete after 0s [id=2698998569660441317]
module.pritunl_igm.null_resource.provision_ready: Creating...
module.pritunl_igm.null_resource.provision_ready: Creation complete after 0s [id=4484066548394435573]
module.pritunl_igm.google_compute_target_pool.gcp_target_pool: Creating...
module.pritunl_igm.google_compute_target_pool.gcp_target_pool: Creation complete after 3s [id=projects/crabi-admin/regions/us-west2/targetPools/tf-pritunl-pool]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Creating...
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Still creating... [10s elapsed]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Still creating... [20s elapsed]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Creation complete after 28s [id=projects/crabi-admin/zones/us-west2-a/instanceGroupManagers/tf-pritunl-igm]
module.pritunl_igm.null_resource.autoscaler_complete: Creating...
module.pritunl_igm.null_resource.autoscaler_complete: Creation complete after 0s [id=2657963904038306996]

Apply complete! Resources: 16 added, 0 changed, 0 destroyed.
```
After this, I go on with following setup steps (again, this is what I am trying to get setup, so that's why I reference it):
1. Open my web browser using https://IP_ADDRESS to get my Pritunl initial setup
2. SSH to my CentOS instance and run `pritunl setup-key` and use it in my web browser setup.
3. Run `pritunl default-password` to get the default password and login to my vpn server.

All of these is documented in [pritunl config docs](https://docs.pritunl.com/docs/configuration-5). At this point it would be enough to say you've done an initial manual config. I went further and created a user, organization, server, delete the user and organization. So my server looks like this:

![image](https://user-images.githubusercontent.com/24655209/72297549-c418c600-3621-11ea-973a-bf54e477f332.png)

At this point we can also say that if I run `terraform destroy` I would lose the setup done manually, and if I run again `terraform apply` I would get a fresh installation where steps 1, 2 and 3 have to be done all over again. So I go ahead and do it:
```
module.pritunl_igm.null_resource.autoscaler_complete: Destroying... [id=2657963904038306996]
module.pritunl_health_check.null_resource.health_check_complete: Destroying... [id=3958501314416428358]
module.pritunl_ip.null_resource.compute_address_complete: Destroying... [id=5611791132355977412]
module.pritunl_ip.null_resource.compute_address_complete: Destruction complete after 0s
module.pritunl_igm.null_resource.autoscaler_complete: Destruction complete after 0s
module.pritunl_health_check.null_resource.health_check_complete: Destruction complete after 0s
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Destroying... [id=projects/crabi-admin/zones/us-west2-a/instanceGroupManagers/tf-pritunl-igm]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Still destroying... [id=projects/crabi-admin/zones/us-west2-a/instanceGroupManagers/tf-pritunl-igm, 10s elapsed]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Still destroying... [id=projects/crabi-admin/zones/us-west2-a/instanceGroupManagers/tf-pritunl-igm, 20s elapsed]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Still destroying... [id=projects/crabi-admin/zones/us-west2-a/instanceGroupManagers/tf-pritunl-igm, 30s elapsed]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Still destroying... [id=projects/crabi-admin/zones/us-west2-a/instanceGroupManagers/tf-pritunl-igm, 40s elapsed]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Still destroying... [id=projects/crabi-admin/zones/us-west2-a/instanceGroupManagers/tf-pritunl-igm, 50s elapsed]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Still destroying... [id=projects/crabi-admin/zones/us-west2-a/instanceGroupManagers/tf-pritunl-igm, 1m0s elapsed]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Still destroying... [id=projects/crabi-admin/zones/us-west2-a/instanceGroupManagers/tf-pritunl-igm, 1m10s elapsed]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Destruction complete after 1m18s
module.pritunl_igm.google_compute_target_pool.gcp_target_pool: Destroying... [id=projects/crabi-admin/regions/us-west2/targetPools/tf-pritunl-pool]
module.pritunl_health_check.google_compute_health_check.gcp_health_check: Destroying... [id=projects/crabi-admin/global/healthChecks/tf-pritunl-hc]
module.pritunl_health_check.google_compute_health_check.gcp_health_check: Destruction complete after 3s
module.pritunl_health_check.null_resource.provision_ready: Destroying... [id=470084763125577762]
module.pritunl_health_check.null_resource.provision_ready: Destruction complete after 0s
module.pritunl_igm.google_compute_target_pool.gcp_target_pool: Destruction complete after 3s
module.pritunl_igm.null_resource.provision_ready: Destroying... [id=4484066548394435573]
module.pritunl_igm.null_resource.provision_ready: Destruction complete after 0s
module.pritunl_template.null_resource.template_complete: Destroying... [id=2698998569660441317]
module.pritunl_template.null_resource.template_complete: Destruction complete after 0s
module.pritunl_template.google_compute_instance_template.gcp_instance_template: Destroying... [id=projects/crabi-admin/global/instanceTemplates/tf-pritunl-tpl]
module.pritunl_template.google_compute_instance_template.gcp_instance_template: Destruction complete after 3s
module.pritunl_template.null_resource.provision_ready: Destroying... [id=3345939031198491119]
module.pritunl_ip.google_compute_address.gcp_address: Destroying... [id=projects/crabi-admin/regions/us-west2/addresses/tf-pritunl-ip]
module.pritunl_template.null_resource.provision_ready: Destruction complete after 0s
module.pritunl_firewall.null_resource.firewall_allow_complete: Destroying... [id=2527067770774517577]
module.pritunl_firewall.null_resource.firewall_allow_complete: Destruction complete after 0s
module.pritunl_firewall.google_compute_firewall.gcp_firewall_allow: Destroying... [id=projects/crabi-admin/global/firewalls/tf-pritunl-ingress]
module.pritunl_ip.google_compute_address.gcp_address: Destruction complete after 4s
module.pritunl_ip.null_resource.provision_ready: Destroying... [id=5193272350032900875]
module.pritunl_ip.null_resource.provision_ready: Destruction complete after 0s
module.pritunl_firewall.google_compute_firewall.gcp_firewall_allow: Still destroying... [id=projects/crabi-admin/global/firewalls/tf-pritunl-ingress, 10s elapsed]
module.pritunl_firewall.google_compute_firewall.gcp_firewall_allow: Destruction complete after 16s
module.pritunl_firewall.null_resource.provision_ready: Destroying... [id=8946484505103071588]
module.pritunl_firewall.null_resource.provision_ready: Destruction complete after 0s

Destroy complete! Resources: 16 destroyed.
```
Then I run terraform apply:
```
module.pritunl_health_check.null_resource.provision_ready: Creating...
module.pritunl_ip.null_resource.provision_ready: Creating...
module.pritunl_firewall.null_resource.provision_ready: Creating...
module.pritunl_firewall.null_resource.provision_ready: Creation complete after 0s [id=8092508750290649228]
module.pritunl_health_check.null_resource.provision_ready: Creation complete after 0s [id=6611665439195584909]
module.pritunl_ip.null_resource.provision_ready: Creation complete after 0s [id=8163108083975963101]
module.pritunl_ip.google_compute_address.gcp_address: Creating...
module.pritunl_firewall.google_compute_firewall.gcp_firewall_allow: Creating...
module.pritunl_health_check.google_compute_health_check.gcp_health_check: Creating...
module.pritunl_health_check.google_compute_health_check.gcp_health_check: Creation complete after 3s [id=projects/crabi-admin/global/healthChecks/tf-pritunl-hc]
module.pritunl_health_check.null_resource.health_check_complete: Creating...
module.pritunl_health_check.null_resource.health_check_complete: Creation complete after 0s [id=9036018439019706925]
module.pritunl_ip.google_compute_address.gcp_address: Creation complete after 4s [id=projects/crabi-admin/regions/us-west2/addresses/tf-pritunl-ip]
module.pritunl_ip.null_resource.compute_address_complete: Creating...
module.pritunl_ip.null_resource.compute_address_complete: Creation complete after 0s [id=1709646096333478678]
module.pritunl_firewall.google_compute_firewall.gcp_firewall_allow: Creation complete after 8s [id=projects/crabi-admin/global/firewalls/tf-pritunl-ingress]
module.pritunl_firewall.null_resource.firewall_allow_complete: Creating...
module.pritunl_firewall.null_resource.firewall_allow_complete: Creation complete after 0s [id=3890130881717484239]
module.pritunl_template.null_resource.provision_ready: Creating...
module.pritunl_template.null_resource.provision_ready: Creation complete after 0s [id=1006482875782121501]
module.pritunl_template.google_compute_instance_template.gcp_instance_template: Creating...
module.pritunl_template.google_compute_instance_template.gcp_instance_template: Creation complete after 4s [id=projects/crabi-admin/global/instanceTemplates/tf-pritunl-tpl]
module.pritunl_template.null_resource.template_complete: Creating...
module.pritunl_template.null_resource.template_complete: Creation complete after 0s [id=1121426175721711382]
module.pritunl_igm.null_resource.provision_ready: Creating...
module.pritunl_igm.null_resource.provision_ready: Creation complete after 0s [id=8223057036164179755]
module.pritunl_igm.google_compute_target_pool.gcp_target_pool: Creating...
module.pritunl_igm.google_compute_target_pool.gcp_target_pool: Creation complete after 4s [id=projects/crabi-admin/regions/us-west2/targetPools/tf-pritunl-pool]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Creating...
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Still creating... [10s elapsed]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Still creating... [20s elapsed]
module.pritunl_igm.google_compute_instance_group_manager.gcp_managed_group: Creation complete after 28s [id=projects/crabi-admin/zones/us-west2-a/instanceGroupManagers/tf-pritunl-igm]
module.pritunl_igm.null_resource.autoscaler_complete: Creating...
module.pritunl_igm.null_resource.autoscaler_complete: Creation complete after 0s [id=4180623897065897445]

Apply complete! Resources: 16 added, 0 changed, 0 destroyed.
```
Once the new set of resources is complete, and I open my web browser expecting the initial setup window. Instead, I get a login window:

![image](https://user-images.githubusercontent.com/24655209/72298629-38546900-3624-11ea-97cc-fee0d0500766.png)

If I try to use the default password it returns an error. So I use the password I set up last time, and once I'm in I can see it's exactly as it was before I ran destroy:

![image](https://user-images.githubusercontent.com/24655209/72298811-c892ae00-3624-11ea-92f8-4056d992b9dd.png)

That's where I am at. Worth to note, if I follow up the same steps of adding manual configuration while using a cooked image, destroy and create, the instance I get somehow has all those changes I added by hand. Summarizing it: Looks like template issue is that reference `image-name` can be confusing to a point where Terraform will not fail but also will not get the image properly assigned. This could be documented to resource docs as good practice or expected behavior. On the other hand, IGM behavior I get is beyond my comprehension, so hopefully this can help to continue investigating this. 
For now, using IGM seems unreliable so I am sticking with compute instances for now.
Finally, I created a gist that can help as reference.
https://gist.github.com/HebertCL/d63f66565151931c5878a9e5e2516da1
Thanks.

**Comment by venkykuberan** [comment]
@HebertCL It looks like your instance_template is picking up the right image now. 
Regarding IGM,  If i understand your issue you are saying that you destroyed the igm & instances (with the config you manually did) and ran the apply command again you see new instances coming up with old config or setup you manually did.  I am sensing its not a Terraform issue and not sure how could it happen.
  GCP brings up new blank instance, unless its part of your config you wouldn't see any of your manual changes you did it on another instances. 
1) When you destroy your terraform IGM resource please verify its successful and all instances associated with the IGM are no longer seen in Cloud Console UI.
2) Verify the manual setup you are doing are already baked in the image and you are just repeating the same

To repro your issue, i need simple instance_template,  metadata startup scripts and igm.

**Comment by HebertCL** [comment]
@venkykuberan long story short is pretty much as you mention and uses the following workflow:

1. Cooked image/metadata startup script > Instance template > IGM
2. Once IGM launches the instance(s), it can be one of these two scenarios:
  - Cooked image gets replaced by an older, deleted image
  - Metadata startup script sets instance up, and any additional configuration added manually appears back after `terraform destroy` and `terraform apply` as I documented above. 

Worth to mention, I am using the same main.tf file to create and destroy, so each destroy wipes out all resources. Every time resources get created/destroyed, I check my `.tfstate` files to ensure resources are properly created/deleted.

Regarding the points you mention:

1. Yes, I make sure resources are created/destroyed properly in google cloud console and there's nothing old in my tfstate files.
2. The setup in image cooked by Packer is different from what I am setting up using startup script. I did this to remove the additional cooking layer and leverage OpenVPN administration to a more manageable tool. So there is no way I am repeating the setup from cooked image in startup script. On top of all I mentioned before, I am using the CentOS image from gcloud and not a custom CentOS image.

You can find my igm and template module configurations in [gist](https://gist.github.com/HebertCL/d63f66565151931c5878a9e5e2516da1). I included the `packer.json` used for image cooking along with playbooks I used in case you want to give it a shot, as well as the startup script I use with plain CentOS image called `pritunl.sh`.

**Comment by venkykuberan** [comment]
@HebertCL As image/instance_template is working as expected.  Lets try to isolate terraform in igm issue you are facing. You can try creating the igm in following ways
 1) gcloud
 2) cloud-console
Verify any of the above behavior (deleted disk image or non-configured startup scripts) is occurring ?

**Comment by HebertCL** [comment]
@venkykuberan sorry for the late response. I've tried creating IGM from cloud console before, although I didn't follow up with manual configs and then delete/create the IGM once again to see if the issue persisted. I will try to get it done throughout the day and share the results.

**Comment by venkykuberan** [comment]
@HebertCL Can you please close this issue if you don't help on this issue any more

**Comment by venkykuberan** [comment]
I am closing this issue as i don't see any help needed from us. Please reopen if needed..
