### ISSUE TITLE
google_compute_autoscaler does not support google_compute_region_instance_group_manager

### ISSUE THREAD

**Issue by zbikmarc** [terraform-providers/terraform-provider-google#535]
It looks like that newly added `google_compute_region_instance_group_manager` can not be used with auto scaling because `google_compute_autoscaler` has `zone` [parameter as required](https://www.terraform.io/docs/providers/google/r/compute_autoscaler.html#zone).

### Terraform Version
`Terraform-0.10.6`
`terraform-provider-google-1.0.1`

### Affected Resource(s)
- google_compute_autoscaler
- google_compute_region_instance_group_manager

Those two resources are connected with eachother

### Expected Behavior
It should be able to create `google_compute_region_instance_group_manager` with auto scaling enabled.

### Important Factoids
This feature is supported from Google Cloud console. Snippet from Google documentation:

> Regional managed instance groups also support autoscaling, internal load balancing, and external load balancing.

Example API call is provided under [this location](https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups#enabling_autoscaling)

### References
- https://www.terraform.io/docs/providers/google/r/compute_autoscaler.html#zone
- https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups
- https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups#enabling_autoscaling

**Comment by rosbo** [comment]
We will need to create a new resource called `google_compute_region_autoscaler`. It will be very similar to `google_compute_autoscaler` but will take a region instead of a zone and call the region autoscaler API using `config.clientCompute.RegionAutoscalers.*`
