### ISSUE TITLE
Bigquery Dataset access shows an update

### ISSUE THREAD

**Issue by mralanlee** [terraform-providers/terraform-provider-google#5350]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform: v0.11.13
Provider: v2.20.1

### Affected Resource(s)

* google_bigquery_dataset

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "sample" {
  project       = "${var.project_id}"
  count         = "${var.create_data_stack}"
  dataset_id    = "sample"
  friendly_name = "Sample Data Warehouse"

  labels {
    env = "${var.env}"
  }

  access {
    role          = "roles/bigquery.dataOwner"
    user_by_email = "${google_service_account.sample.email}"
  }

  access {
    role   = "roles/bigquery.dataEditor"
    domain = "sample"
  }
}
```

### Expected Behavior
`Plan: 0 to add, 1 to change, 0 to destroy.`

### Actual Behavior
```
  ~ module.mod.google_bigquery_dataset.sample
      access.3036005142.domain:         "" => ""
      access.3036005142.group_by_email: "" => ""
      access.3036005142.role:           "" => "roles/bigquery.dataOwner"
      access.3036005142.special_group:  "" => ""
      access.3036005142.user_by_email:  "" => "sample@project-id.iam.gserviceaccount.com"
      access.3036005142.view.#:         "0" => "0"
      access.3246847876.domain:         "sample.com" => ""
      access.3246847876.group_by_email: "" => ""
      access.3246847876.role:           "WRITER" => ""
      access.3246847876.special_group:  "" => ""
      access.3246847876.user_by_email:  "" => ""
      access.3246847876.view.#:         "0" => "0"
      access.3500345347.domain:         "" => "sample.com"
      access.3500345347.group_by_email: "" => ""
      access.3500345347.role:           "" => "roles/bigquery.dataEditor"
      access.3500345347.special_group:  "" => ""
      access.3500345347.user_by_email:  "" => ""
      access.3500345347.view.#:         "0" => "0"
      access.514945909.domain:          "" => ""
      access.514945909.group_by_email:  "" => ""
      access.514945909.role:            "OWNER" => ""
      access.514945909.special_group:   "" => ""
      access.514945909.user_by_email:   "sample@project-id.iam.gserviceaccount.com" => ""
      access.514945909.view.#:          "0" => "0"
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
I also had upgrade the plugin from 1.20 to 2.20.1 before initially creating the resources the first time. So I'm unsure if this could be a state issue. I had followed the upgrade guide, and everything created without errors.

### Description
I had already created the resource successfully the first time. However, when I ran `apply` again without updating any of terraform configurations... it prompted me that a update is in place.

**Comment by edwardmedia** [comment]
@mralanlee Use your configuration without any change, if I use the plugin v1.20, I receive below error.   
```
Error: google_bigquery_dataset.sample: expected access.0.role to be one of [OWNER WRITER READER], got roles/bigquery.dataOwner

Error: google_bigquery_dataset.sample: expected access.1.role to be one of [OWNER WRITER READER], got roles/bigquery.dataEditor
```
After I updated your configuration by replacing below `role` like below. It passed the resource creation. Look at the error message you reported, it seems make sense someone may have already updated the configuration. 
```
resource "google_bigquery_dataset" "sample" {
  project       = "${var.project_id}"
  count         = "${var.create_data_stack}"
  dataset_id    = "sample"
  friendly_name = "Sample Data Warehouse"

  labels {
    env = "${var.env}"
  }

  access {
    role          = "OWNER"
    user_by_email = "${google_service_account.sample.email}"
  }

  access {
    role   = "WRITER"
    domain = "sample"
  }
}
```
Can you double check if this is the case?

**Comment by mralanlee** [comment]
Hi @edwardmedia,

Thanks for the response.

Regarding the access roles, I was able to get the resource created in plugin v2.20.1. 

With respect to the possibility someone else updating the configuration... I, initially, thought this could be a possibility so I accepted the update change to move forward and then I ran `terraform apply` again (after waiting 1 minute in case ACL changes had to be propagated in GCP), but I still got the same output about having 1 update. Tested the `terraform apply` a few more times and it still states that there is 1 update.

**Comment by edwardmedia** [comment]
@mralanlee I may have misunderstood your problem. Can you specify what you tried to do and failed? Thank you

**Comment by mralanlee** [comment]
Sure.

1. I created the dataset with the configuration listed above.
2. Ran `terraform apply`, and it was exactly as I had expected: 1 to add.
3. I made a slight modification elsewhere, unrelated to this resource.
4. Ran `terraform apply`, the output said I had an update on this resource specifically regarding the `access`:
```
  ~ module.mod.google_bigquery_dataset.sample
      access.3036005142.domain:         "" => ""
      access.3036005142.group_by_email: "" => ""
      access.3036005142.role:           "" => "roles/bigquery.dataOwner"
      access.3036005142.special_group:  "" => ""
      access.3036005142.user_by_email:  "" => "sample@project-id.iam.gserviceaccount.com"
      access.3036005142.view.#:         "0" => "0"
      access.3246847876.domain:         "sample.com" => ""
      access.3246847876.group_by_email: "" => ""
      access.3246847876.role:           "WRITER" => ""
      access.3246847876.special_group:  "" => ""
      access.3246847876.user_by_email:  "" => ""
      access.3246847876.view.#:         "0" => "0"
      access.3500345347.domain:         "" => "sample.com"
      access.3500345347.group_by_email: "" => ""
      access.3500345347.role:           "" => "roles/bigquery.dataEditor"
      access.3500345347.special_group:  "" => ""
      access.3500345347.user_by_email:  "" => ""
      access.3500345347.view.#:         "0" => "0"
      access.514945909.domain:          "" => ""
      access.514945909.group_by_email:  "" => ""
      access.514945909.role:            "OWNER" => ""
      access.514945909.special_group:   "" => ""
      access.514945909.user_by_email:   "sample@project-id.iam.gserviceaccount.com" => ""
      access.514945909.view.#:          "0" => "0"
```

I didn't make any changes to the configuration regarding the bigquery dataset or 
the access block attributes. 
5. I accept the update changes thinking that maybe I may made a chance or that a colleague made a change.
6. I run `terraform apply` again as a sanity check to see if the output will read 0 add, 0 change, 0 destroy... but it showed the above output again that I saw in step 4.

So I guess my problem is that I do not want to make have to approve this update every time I run `terraform apply` even when there isn't any change or mutation. I'm wondering if this could be a bug or if it's state issue. Please let me know if you have any questions.

**Comment by edwardmedia** [comment]
@mralanlee there are 2 things I am not clear: 1) what specific thing did you do for `made a slight modification elsewhere, unrelated to this resource.` 2) between your repro steps, did you change the versions?  If yes, please specify. If not, what version I can use to repro the issue. Thanks

**Comment by mralanlee** [comment]
Before doing anything, I upgraded the provider version from `1.20` to `2.20.1`. Here is the change that I had made...

1. The change I made was [this](https://www.terraform.io/docs/providers/google/guides/version_2_upgrade.html#resource-google_project). This should not create an update or change for the `bigquery_dataset` resources.

2. Not _between_ the steps. Upgrading was the first thing I had done.

**Comment by edwardmedia** [comment]
@mralanlee during the steps when I try to repro the issue, at least I have to modify below syntax between v1.20 and v2.20.1. Not sure how you did upgrade without modifying the configuration. Can you double check if this happens on your side?
```
  # v1.20.0
  labels {
    env = "${var.env}"
  }
```
```
  # v2.20.1
  labels = {
    env = "${var.env}"
  }
```
After I upgraded the plugin to v2.20.1, and successfully run `tf apply` initially, I always get below response each time I rerun `tf apply`
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
Not sure what I missed. Can you post the result of `tf show`?
Please specify how I can repro your issue. Thanks

**Comment by mralanlee** [comment]
I updated the `labels` and still seeing a `1 to change` on just the `access` portion of the resource.

Running `terraform show` exposes some certs and credentials that I cannot share.

**Comment by edwardmedia** [comment]
@mralanlee having `tf plan` and `tf show` could help us identify the issue. You may redact the credentials, etc. before put them in the public. Also after the upgrade the provider plugin, have you ever successfully run `tf apply`? It is expected that the state files could be different between different versions. If this is the first time you run `tf apply`, you may have to accept the different.

**Comment by preston-hf** [comment]
I am having a similar issue. I try to define access blocks but Terraform seems to really care about the order yet it doesn't seem the BigQuery API stores/returns them in the order they were created, so this makes it seem like it's constantly changing. I believe access {} blocks may be totally broken with BigQuery. Is there some way you could just treat the access blocks as a set or something?

**Comment by edwardmedia** [comment]
@danawillow we can repro it with below config
```
resource "google_bigquery_dataset" "sample" {
  project       = "myproject"
  count         = "1"
  dataset_id    = "sample"
  friendly_name = "Sample Data Warehouse"
  access {
    role          = "roles/bigquery.dataOwner"
    user_by_email = google_service_account.bqowner.email
  }
  access {
    role   = "roles/bigquery.dataEditor"
    domain = "google.com"
  }
}
resource "google_service_account" "bqowner" {
  account_id = "bqowner"
}
```
It keeps giving below `plan`
```
      - access {
          - role          = "OWNER" -> null
          - user_by_email = "bqowner@myproject.iam.gserviceaccount.com" -> null
        }
      + access {
          + role          = "roles/bigquery.dataOwner"
          + user_by_email = "bqowner@myproject.iam.gserviceaccount.com"
        }
      - access {
          - domain = "google.com" -> null
          - role   = "WRITER" -> null
        }
      + access {
          + domain = "google.com"
          + role   = "roles/bigquery.dataEditor"
        }
```

**Comment by danawillow** [comment]
This looks to be WAI from what I can tell. Our docs specifically point this out: https://www.terraform.io/docs/providers/google/r/bigquery_dataset.html#role
> role - (Optional) Describes the rights granted to the user specified by the other member of the access object. Primitive, Predefined and custom roles are supported. Predefined roles that have equivalent primitive roles are swapped by the API to their Primitive counterparts, and will show a diff post-create. See official docs.

So to stop the permadiff, you should change `roles/bigquery.dataEditor` to `WRITER` and `roles/bigquery.dataOwner` to `OWNER`.

Closing this out because the behavior is already documented. @preston-hf, not sure if your issue is the same one as the original. If you aren't using predefined roles that have primitive counterparts and are just seeing an ordering issue, let's have you open a new bug with the full template filled out so that someone on our side can take a look at what you're experiencing.

**Comment by preston-hf** [comment]
It turns out I was having exactly the same issue. Thanks!
