### ISSUE TITLE
Terraform tries to destroy the certificate before remove it from google_compute_target_https_proxy

### ISSUE THREAD

**Issue by i2dcarrasco** [terraform-providers/terraform-provider-google#5356]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.18
+ provider.dns v2.2.0
+ provider.google v3.3.0
+ provider.google-beta v3.3.0
+ provider.kubernetes v1.9.0
+ provider.local v1.4.0
+ provider.template v2.1.2

### Affected Resource(s)
* google_compute_managed_ssl_certificate
* google_compute_target_https_proxy

### Terraform Configuration Files

```tf
resource "google_compute_managed_ssl_certificate" "lb_certs" {
  provider = google-beta

  name = replace(each.value, ".", "-")
  lifecycle { create_before_destroy = true } 
  for_each = local.workspace["certificates"]

  managed {
    domains = ["${each.value}."]
  }
}

resource "google_compute_target_https_proxy" "base_https_proxy" {
  name               = "base-https"
  url_map           = google_compute_url_map.base.self_link
  ssl_certificates = values(google_compute_managed_ssl_certificate.lb_certs).*.self_link
  ssl_policy         = google_compute_ssl_policy.ssl-policy-restricted.self_link
  depends_on     = [google_compute_managed_ssl_certificate.lb_certs]
}
```

On workspace I've just a list like for example: `certificates = ["www.google.es", "www.google.com"]`. When I remove a certificate from that list then is removed from google_compute_target_https_proxy and google_compute_managed_ssl_certificate at same time and then fails. I've to remove the certificate manually from the proxy and then apply.

### Debug Output
The log is too big and contains too much private data that I don't want to share publicly, so I've cutted the latest lines where the error ocurs:
https://gist.github.com/i2dcarrasco/2654e9d6313b2e0f60e015b9153dfb5f

### Panic Output
N/A

### Expected Behavior
First it will delete the resource from the google_compute_target_https_proxy and then delete the certificate

### Actual Behavior
Terraform just tries to delete the google_compute_managed_ssl_certificate without remove it from the proxy, so the api gives an error saying that is in use.

### Steps to Reproduce
1. Create the above resources with a few certificates
2. Apply the changes: `terraform apply`
3. Remove one of the certificates from both resources at same time
4. Try to apply again and then it will fail. You have to remove the certificate from the proxy manually and then apply.

### Important Factoids
Nothing to take into consideration

### References
None

**Comment by edwardmedia** [comment]
@i2dcarrasco how did you do `Remove one of the certificates from both resources at same time`? It it fine with me if I remove one from the workspace.

**Comment by chrisst** [comment]
The solution will require managing the ssl certificate's name in a way that will generate a new name so that `create_before_destroy` will not conflict with the existing certificate. This isn't something that we are able to handle in the provider because we can't make a decision on how the proxy should be updated. However using the random provider and keepers can provide a good way to manage this without needing manual intervention. I'll add an example to the docs for managed_ssl_cert to encourage this.

Here is an example config:
```
resource "google_compute_target_https_proxy" "default" {
  name             = "test-proxy"
  url_map          = google_compute_url_map.default.self_link
  ssl_certificates = [google_compute_managed_ssl_certificate.cert.self_link]
}

locals {
  managed_domains = list("test.example.com")
}

resource "random_id" "certificate" {
  byte_length = 4
  prefix      = "issue6147-cert-"

  keepers = {
    domains = join(",", local.managed_domains)
  }
}

resource "google_compute_managed_ssl_certificate" "cert" {
  provider = google-beta
  name     = random_id.certificate.hex

  lifecycle {
    create_before_destroy = true
  }

  managed {
    domains = local.managed_domains
  }
}
```
