### ISSUE TITLE
Auto create sub network for a google container cluster

### ISSUE THREAD

**Issue by srisurya777** [terraform-providers/terraform-provider-google#5361]
We are in the process of migrating from google deployment-manager to terraform. Initially, I have been using 2.x version google provider to have the create subnetwork functionality inside google_container_cluster resource. However, as per the recommendations, I am trying to update the provider to 2.x. Well aware that the create subnetwork feature in ip_allocation_policy is deprecated. Hence, we need to create the subnetwork manually using terraform resource.

The problem here would be the ip_cidr range field which has to be updated manually every time. Is there a way that I can make this automated and not enter a unique range everytime I deploy a new cluster

**Comment by rileykarson** [comment]
Deduplicating this to https://github.com/terraform-providers/terraform-provider-google/issues/5119
