### ISSUE TITLE
google_monitoring_notification_channel labels field not marked Sensitive

### ISSUE THREAD

**Issue by rsalmond** [terraform-providers/terraform-provider-google#5369]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.12
+ provider.google v2.20.0

### Affected Resource(s)

* google_monitoring_notification_channel

### Terraform Configuration Files

```tf
data "google_kms_secret" "slack_token" {
  crypto_key = "<project>/global/automation-prod/k8s-secrets"
  ciphertext = filebase64("SLACK_STACKDRIVER_TOKEN.enc")
}

resource "google_monitoring_notification_channel" "slack" {
  display_name = "foobar"
  type         = "slack"

  labels = {
    "auth_token"   = data.google_kms_secret.slack_token.plaintext
    "channel_name" = "#foobar"
  }
}
```

### Expected Behavior

Sensitive values should not appear in the plan.

### Actual Behavior

Plaintext Slack token did appear in the plan.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

It has been established in #4058 that storing the plaintext token in the state file is expected behavior, however it is [considered best practice](https://www.terraform.io/docs/extend/best-practices/sensitive-state.html#using-the-sensitive-flag) for a field which is [intended to accept secret data](https://www.terraform.io/docs/providers/google/r/monitoring_notification_channel.html#labels) to be hidden from the plan by marking it as `Sensitive`.

### References

* #4058

**Comment by venkykuberan** [comment]
@radeksimko plaintext field is already marked as sensitive in data source `google_kms_secret`. Hence it shouldn't be shown in the plan. However i see you are using ciphertext in your kms_secret config and using plaintext in `google_monitoring_notification_channel` resource.

Could you please try using the plaintext field and verify if its working as expected ?

**Comment by rsalmond** [comment]
Hey @radeksimko to clarify this is not an issue with the `google_kms_secret` attribute.`google_monitoring_notification_channel` reveals the sensitive contents of the `labels` attribute when used in isolation as well. Eg.

```
resource "google_monitoring_notification_channel" "slack" {
  display_name = "foobar"
  type         = "slack"

  labels = {
    "auth_token"   = "NOT_A_REAL_SECRET_BUT_YOU_GET_THE_POINT"
    "channel_name" = "#foobar"
  }
}
```

```
Terraform will perform the following actions:

  # google_monitoring_notification_channel.slack will be created
  + resource "google_monitoring_notification_channel" "slack" {
      + display_name        = "foobar"
      + enabled             = true
      + id                  = (known after apply)
      + labels              = {
          + "auth_token"   = "NOT_A_REAL_SECRET_BUT_YOU_GET_THE_POINT"
          + "channel_name" = "#foobar"
        }
      + name                = (known after apply)
      + project             = (known after apply)
      + type                = "slack"
      + verification_status = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

**Comment by venkykuberan** [comment]
Hi @rsalmond i intend to refer you in my previous message but picked a different person from the list. I apologize to both.

Regarding the issue, thanks for posting the plan output, I see it now. We don't have Sensitive property available for `google_monitoring_notification_channel` resource and i will add this issue to feature/bug list to be prioritized.  Thank you

**Comment by rsalmond** [comment]
Perfect, thanks @venkykuberan!

**Comment by chrisst** [comment]
@rsalmond I agree this should be sensitive but we can't mark the entire labels attribute as sensitive because it wouldn't be good for every other use case of labels. We also are unable to mark a single key value pair as sensitive at run time because the sensitive attribute is effectively a compute time type.

Instead I think we can make a new attribute that contains only the slack token (eg: `slack_auth_token`) which can be marked sensitive and merge it with the labels at apply/refresh time. This will allow the token to be obfuscated in the plan/apply output. Does this still satisfy your use case?

**Comment by rsalmond** [comment]
Hey @chrisst yeah that'd help us out, it's kludgy but it works. Not your fault, weird to use labels as control data.

Based on the output of `gcloud alpha monitoring channel-descriptors list` it looks like you may want to include `service_key` for the pagerduty descriptor and `password` for the  `webhook_basicauth` channel. And maybe the `url` label for the `webhook_tokenauth` channel? I think that one includes the shared secret as a query param in the url. Might be others.
