### ISSUE TITLE
compute_instance.network_interface doesn't get set on read

### ISSUE THREAD

**Issue by paddycarver** [terraform-providers/terraform-provider-google#537]
As [pointed out](https://github.com/terraform-providers/terraform-provider-google/commit/f2f276ea0b8a98fa782a9321a9d4b55122e27fe5#commitcomment-24781495) by @PeterMilley, #491 accidentally removed the `d.Set` line for the `network_interfaces` field in `google_compute_instance`, probably misreading it as a `network` field. That should be reintroduced to make computed fields work again, as well as to make importing accurate.

**Comment by PeterMilley** [comment]
#519 is likely the same issue (I was going to file an issue myself before I found that).

**Comment by paddycarver** [comment]
Ah, thanks, poor reading on my part. Closing out in favor of #519.
