### ISSUE TITLE
google_dns_managed_zone doesn't yet support peering_config blocks

### ISSUE THREAD

**Issue by flelli** [terraform-providers/terraform-provider-google#5371]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.12.19
+ provider.google v3.4.0
```

### Affected Resource(s)

* google_dns_managed_zone

### Terraform Configuration Files

```tf
resource "google_dns_managed_zone" "managed_zone" {
  name                      = var.name
  description               = var.description
  project                   = var.project
  dns_name                  = var.dns_name
  visibility                = var.type

peering_config {
    target_network {
      network_url   = var.peer_network
    }
  }
}
```

### Expected Behavior

According to [the docs](https://www.terraform.io/docs/providers/google/r/dns_managed_zone.html), resource should apply.

### Actual Behavior

When running `terraform plan` the following error occurs:

```
Error: Unsupported block type

  on modules/gcp/dns/zone/main.tf line 34, in resource "google_dns_managed_zone" "managed_zone":
  34:   peering_config {

Blocks of type "peering_config" are not expected here.
```

### Steps to Reproduce

1. `terraform plan`

### References

[reference docs](https://www.terraform.io/docs/providers/google/r/dns_managed_zone.html)

* #0000

**Comment by venkykuberan** [comment]
@flelli peering_config is available only in beta provider. Please use the same, i tested your config with beta provider and it worked fine. 
Closing this issue, please reopen if still get the same error
