### ISSUE TITLE
google_pubsub_subscription doesn't allow empty ttl

### ISSUE THREAD

**Issue by maroux** [terraform-providers/terraform-provider-google#5374]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.19
+ provider.google v3.4.0

### Affected Resource(s)

* google_pubsub_subscription

### Terraform Configuration Files

```tf
resource "google_pubsub_subscription" "subscription" {
  name  = "my-subscription"
  topic = "my-topic"

  ack_deadline_seconds = 20

  expiration_policy {}
}
```

### Expected Behavior

Terraform creates the subscription

### Actual Behavior

```
Error: Missing required argument

  on main.tf line 7, in resource "google_pubsub_subscription" "subscription":
  10:   expiration_policy {}

The argument "ttl" is required, but no definition was found.
```

### Steps to Reproduce

1. `terraform apply`

### Notes

In addition, the documentation states
```
 If it is set but ttl is "", the resource never expires
```
However, if you set ttl to `""`, expiry is set to the default 31 days.

**Comment by Chupaka** [comment]
What provider version do you use?

**Comment by maroux** [comment]
@Chupaka ah sorry it's 3.4.0

**Comment by edwardmedia** [comment]
@maroux if you have `expiration_policy` block in the config, the plugin looks for the `ttl`. If you want to leave it to default value, you should not have `expiration_policy` block. Below is the response I got when I don't have  `expiration_policy` block in the config. I think the doc needs to update to reflect the behavior. 
```
 
 {
   "name": "projects/myproject/subscriptions/my-subscription",
   "topic": "projects/myproject/topics/example-topic",
   "pushConfig": {},
   "ackDeadlineSeconds": 20,
   "messageRetentionDuration": "604800s",
   "expirationPolicy": {
     "ttl": "2678400s"
   }
 }
```

**Comment by Chupaka** [comment]
@edwardmedia "ttl": "2678400s" (31 days) is the default value if you don't set expiration_policy at all. To set it to "unlimited" in version 2.x you set "expiration_policy {}". That works. Looks like in v3 something was broken.

**Comment by slevenick** [comment]
You can set `ttl` to `""` for the same effect.

The change happened here: https://github.com/GoogleCloudPlatform/magic-modules/commit/5b665adf05cb75efaa1c6da9aeff0d5da87a1516#diff-293147022553799829844cb248360ba3L235

Creating a pubsub subscription with
```
  expiration_policy {
    ttl = ""
  }
```
Works as expected

**Comment by slevenick** [comment]
For a little context, this change happened during 3.0.0 to try to prevent the setting of empty blocks in most cases. Generally we try to not allow empty blocks to be set, and in this case we fixed it by requiring users to set `""` for ttl

**Comment by maroux** [comment]
@slevenick Ah indeed that works as expected. My test case was flawed. thanks!
