### ISSUE TITLE
google_bigtable_app_profile doesn't interpolate explicit dependencies

### ISSUE THREAD

**Issue by EmilyMazo** [terraform-providers/terraform-provider-google#5377]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
0.12.9

### Affected Resource(s)

google_bigtable_app_profile
google_bigtable_instance

### Terraform Configuration Files

```tf
resource "google_bigtable_app_profile" "write-throttling" {
  instance       = google_bigtable_instance.arizona-sandbox.name
  app_profile_id = "write-throttling"
  description    = "Application profile for the write throttling aspect of the shipping pipeline"

  single_cluster_routing {
    cluster_id                 = google_bigtable_instance.arizona-sandbox.cluster[0].cluster_id
    allow_transactional_writes = true
  }

  ignore_warnings = false
}

```

Original Bigtable Instance config:
```resource "google_bigtable_instance" "arizona-sandbox" {
  name          = "arizona-sandbox"
  instance_type = "PRODUCTION"

  cluster {
    cluster_id   = "arizona-sandbox-c1"
    zone         = "us-central1-c"
    storage_type = "SSD"
    num_nodes    = 3
  }

  cluster {
    cluster_id   = "arizona-sandbox-a1"
    zone         = "us-central1-a"
    storage_type = "SSD"
    num_nodes    = 3
  }
}

```

Changed Bigtable instance config (which prompted destruction/creation of the instance:
```
resource "google_bigtable_instance" "arizona-sandbox" {
  name          = "arizona-sandbox"
  instance_type = "DEVELOPMENT"

  cluster {
    cluster_id   = "arizona-sandbox-c1"
    zone         = "us-central1-c"
    storage_type = "SSD"
  }

}

```

### Expected Behavior

We expect the names of the Bigtable Instance in this application profile to be interpolated (https://www.terraform.io/docs/configuration-0-11/resources.html#explicit-dependencies) and destroyed and recreated when the Bigtable Instance named is destroyed and recreated. 

### Actual Behavior

When I change a Bigtable Instance from a PRODUCTION to a DEVELOPMENT instance and change the number of clusters and nodes (from 2 clusters, 3 nodes each to 1 cluster with no nodes specified, because development instances all have 1 node), terraform correctly destroys and recreates that instance, but all of the app-profiles for that instance have been destroyed. Running `terraform apply` again correctly recreates them, on the new instance. 

### Steps to Reproduce

1. Create a DEVELOPMENT Bigtable Instance in terraform
2. Create one or more app-profiles for that instance in terraform
2. `terraform apply`
3. Change the instance to a PRODUCTION instance
4. `terraform apply`

Note that your app-profiles are gone.

This also works in reverse order, if you go from a PRODUCTION instance to a DEVELOPMENT instance.

### References

* #0000

**Comment by venkykuberan** [comment]
@EmilyMazo When you change the config for the resource `google_bigtable_instance`, terraform decides not to destroy the `google_bigtable_app_profile` since its dependent on the  `name` property which is not going to change even after big_table instance is recreated. However GCP deletes both the resources since it knows the underlying dependency.  Next time during the refresh process (apply) terraform comes to aware that app_profile resource has been removed hence it recreating it.
    I suggest we can make terraform understand the dependency explicitly by using random_string in the app_profile resource. (i.e) every time `bigtable_instance` is created `bigtable_app_profile` name have to computed which forces terraform to recreate this resource. 

```resource "random_string" "random" {
  keepers = {
      name = google_bigtable_instance.bigtable-ah.id
  }
  length  = 5
  special = false
  upper   = false
}

resource google_bigtable_app_profile "bigtable-ah" {
  app_profile_id                = "bigtable-ah-app-profile-${random_string.random.result}"
  description                   = "Profile to enable the BigTable app profile"
  instance                      = google_bigtable_instance.bigtable-ah.name
  project                       = var.project_id
  multi_cluster_routing_use_any = true
  ignore_warnings               = true
}
``` 
Please let me know how it works you after trying above approach ?

**Comment by EmilyMazo** [comment]
Hi @venkykuberan! Thank you for your response! This solution would not allow our services to continue specifying the app profile they wish to use by app_profile_id. In addition, I believe the Bigtable Instance itself is what needs to have a randomly-generated name, so that when the Instance is deleted by tf and a new one is created, the name changes and the app profiles have parameters that need to be recomputed. I've tested this, and get this `plan` output: 

```

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_bigtable_app_profile.dataflow must be replaced
-/+ resource "google_bigtable_app_profile" "dataflow" {
        app_profile_id                = "dataflow"
        description                   = "Application profile for Dataflow jobs"
      ~ id                            = "etsy-aznext-sandbox/arizona-sandbox/dataflow" -> (known after apply)
        ignore_warnings               = false
      ~ instance                      = "arizona-sandbox" -> (known after apply) # forces replacement
      - multi_cluster_routing_use_any = false -> null
      ~ name                          = "projects/etsy-aznext-sandbox/instances/arizona-sandbox/appProfiles/dataflow" -> (known after apply)
      ~ project                       = "etsy-aznext-sandbox" -> (known after apply)

        single_cluster_routing {
            allow_transactional_writes = false
            cluster_id                 = "arizona-sandbox-c1"
        }
    }

  # google_bigtable_app_profile.mmx-slv2 must be replaced
-/+ resource "google_bigtable_app_profile" "mmx-slv2" {
        app_profile_id                = "mmx-slv2"
        description                   = "Application profile for the MMX SLV2 service"
      ~ id                            = "etsy-aznext-sandbox/arizona-sandbox/mmx-slv2" -> (known after apply)
        ignore_warnings               = false
      ~ instance                      = "arizona-sandbox" -> (known after apply) # forces replacement
      - multi_cluster_routing_use_any = false -> null
      ~ name                          = "projects/etsy-aznext-sandbox/instances/arizona-sandbox/appProfiles/mmx-slv2" -> (known after apply)
      ~ project                       = "etsy-aznext-sandbox" -> (known after apply)

        single_cluster_routing {
            allow_transactional_writes = false
            cluster_id                 = "arizona-sandbox-c1"
        }
    }

  # google_bigtable_app_profile.mmx-suggest must be replaced
-/+ resource "google_bigtable_app_profile" "mmx-suggest" {
        app_profile_id                = "mmx-suggest"
        description                   = "Application profile for the MMX Suggest service"
      ~ id                            = "etsy-aznext-sandbox/arizona-sandbox/mmx-suggest" -> (known after apply)
        ignore_warnings               = false
      ~ instance                      = "arizona-sandbox" -> (known after apply) # forces replacement
      - multi_cluster_routing_use_any = false -> null
      ~ name                          = "projects/etsy-aznext-sandbox/instances/arizona-sandbox/appProfiles/mmx-suggest" -> (known after apply)
      ~ project                       = "etsy-aznext-sandbox" -> (known after apply)

        single_cluster_routing {
            allow_transactional_writes = false
            cluster_id                 = "arizona-sandbox-c1"
        }
    }

  # google_bigtable_app_profile.write-throttling must be replaced
-/+ resource "google_bigtable_app_profile" "write-throttling" {
        app_profile_id                = "write-throttling"
        description                   = "Application profile for the write throttling aspect of the shipping pipeline"
      ~ id                            = "etsy-aznext-sandbox/arizona-sandbox/write-throttling" -> (known after apply)
        ignore_warnings               = false
      ~ instance                      = "arizona-sandbox" -> (known after apply) # forces replacement
      - multi_cluster_routing_use_any = false -> null
      ~ name                          = "projects/etsy-aznext-sandbox/instances/arizona-sandbox/appProfiles/write-throttling" -> (known after apply)
      ~ project                       = "etsy-aznext-sandbox" -> (known after apply)

        single_cluster_routing {
            allow_transactional_writes = true
            cluster_id                 = "arizona-sandbox-c1"
        }
    }

  # google_bigtable_instance.arizona-sandbox must be replaced
-/+ resource "google_bigtable_instance" "arizona-sandbox" {
      + cluster_id    = (known after apply)
      ~ display_name  = "arizona-sandbox" -> (known after apply)
      ~ id            = "arizona-sandbox" -> (known after apply)
      ~ instance_type = "PRODUCTION" -> "DEVELOPMENT" # forces replacement
      ~ name          = "arizona-sandbox" -> (known after apply) # forces replacement
      + num_nodes     = (known after apply)
      ~ project       = "etsy-aznext-sandbox" -> (known after apply)
      + storage_type  = (known after apply)
      + zone          = (known after apply)

      ~ cluster {
            cluster_id   = "arizona-sandbox-c1"
          - num_nodes    = 3 -> null
            storage_type = "SSD"
            zone         = "us-central1-c"
        }
      - cluster {
          - cluster_id   = "arizona-sandbox-a1" -> null # forces replacement
          - num_nodes    = 3 -> null
          - storage_type = "SSD" -> null
          - zone         = "us-central1-a" -> null # forces replacement
        }
    }

  # random_string.suffix will be created
  + resource "random_string" "suffix" {
      + id          = (known after apply)
      + length      = 3
      + lower       = true
      + min_lower   = 0
      + min_numeric = 0
      + min_special = 0
      + min_upper   = 0
      + number      = true
      + result      = (known after apply)
      + special     = false
      + upper       = false
    }

Plan: 6 to add, 0 to change, 5 to destroy.
```

Which seems to bear this out! `terraform apply` however resulted in this error: `Error: Error reading AppProfile: googleapi: Error 400: Deleting an app profile will cause all requests using it to fail.`
(The app profiles were correctly attempted to be deleted before the instance, but the instance was taking zero requests of any type at the time of `apply`.)

Unfortunately, this solution isn't amazing for systems that don't have service discovery implementations. All of the services that use our Bigtable Instance have a bigtable_instance_id (and app_profile_id) set in a config somewhere, which would need to be updated every time we make this type of terraform change. This doesn't work well for services taking live production traffic (of course, we imagine needing to recreate instances while taking live traffic only in disaster-recovery situations). Our best-case scenario would involve only needing to deploy changes once, in one place, in order to recreate our instance and its app profiles. 

Is there a way in terraform itself to link these resources more closely? In my `terraform plan` output I see `display_name`, `id`,  and `name` all as parameters to the google_bigtable_instance resource. Is it possible to set one of those (if one of them isn't the bigtable_instance_id used by the google bigtable APIs to identify instances) to have a randomly generated value, and link an app profile to it?

**Comment by venkykuberan** [comment]
@EmilyMazo  can you please share you big_table_instance and app_profile config. Your `random_string` resource doesn't have any `keeper` and i wonder you get random value on the next plan after you change "PRODUCTION" to "DEVELOPMENT". 

Also I am not able to repro the error message you are getting. It would be helpful if you can share the config.

**Comment by EmilyMazo** [comment]
Sure! Here is the config after I made the changes that created the plan output I shared above:

```
# Generate a random_string to use in other resources
resource "random_string" "suffix" {
  length  = 3
  upper   = false
  special = false
}

resource "google_bigtable_instance" "arizona-sandbox" {
  name          = "arizona-sandbox-${random_string.suffix.result}"
  instance_type = "DEVELOPMENT"

  cluster {
    cluster_id   = "arizona-sandbox-c1"
    zone         = "us-central1-c"
    storage_type = "SSD"
  }

}
```

**Comment by venkykuberan** [comment]
@Ebolon I believe your config would generate random string only once after that some value change is needed to trigger the random_generator for new string (which is not there). Given in your config you have big_table_instance and app_profile resources the best bet i can think of setting the randomness on app_profile ("static name - <random value>"). This way i am able to force create every time i change the big_table instance_type DEVELOPMENT <==> PRODUCTION.

Please let me if it works for you.

```
# Generate a random_string to use in other resources
resource "random_string" "suffix" {
  keepers = {
    name = google_bigtable_instance.bigtable-ah.instance_type
  }
  length  = 3
  upper   = false
  special = false
  
}

resource google_bigtable_instance "bigtable-ah" {
  name          = "bigtable-ah"
  project       = var.project_id
  instance_type = "DEVELOPMENT" // PRODUCTION DEVELOPMENT

  cluster {
    cluster_id   = "bigtable-main-cluster-2"
    # num_nodes    = 3
    storage_type = "HDD"
    zone         = var.zone //"europe-west4-b"
  }

#   cluster {
#     cluster_id   = "bigtable-cluster-replica-2"
#     num_nodes    = 3
#     storage_type = "HDD"
#     zone         = var.zone //"europe-west4-c"
#   }

  }

resource google_bigtable_app_profile "write-throttle" {
  app_profile_id = "write_throttle-app-profile-${random_string.suffix.result}"
  description = "Profile to enable the BigTable app profile"
  instance    = google_bigtable_instance.bigtable-ah.name
  project     = var.project_id
  ignore_warnings = true

  single_cluster_routing {
    allow_transactional_writes = true
    cluster_id                 = "bigtable-main-cluster-2"
  }
}

resource google_bigtable_app_profile "read-throttle" {
  app_profile_id = "read-throttle-app-profile-${random_string.suffix.result}"
  description = "Profile to enable the BigTable app profile"
  instance    = google_bigtable_instance.bigtable-ah.name
  project     = var.project_id
  ignore_warnings = true
  single_cluster_routing {
    allow_transactional_writes = false
    cluster_id                 = "bigtable-main-cluster-2"
  }
}
output "bigtable_id" {
  value = google_bigtable_instance.bigtable-ah.id
}

output "read_throttle_app_profile" {
  value = google_bigtable_app_profile.read-throttle.name
}
output "write_throttle_app_profile" {
  value = google_bigtable_app_profile.write-throttle.name
}

```

**Comment by EmilyMazo** [comment]
Hi @venkykuberan! Thanks for your response, and sorry about my delay in getting back to you. While this would allow us to recreate the app profile IDs when the bigtable instances are recreated, it would necessitate renaming all app profiles everywhere they are used, whenever bigtable instances are altered. We are definitely looking for an infrastructure-as-code solution that doesn't require large-scale configuration changes elsewhere. It does not appear that the Bigtable APIs allow specification of app profile IDs by prefix, otherwise this would work great! 

In one of my previous comments I float the idea of using a non-"public-facing" parameter of the bigtable instances to link them to app profiles to them in terraform: ```In my terraform plan output I see display_name, id, and name all as parameters to the google_bigtable_instance resource. Is it possible to set one of those (if one of them isn't the bigtable_instance_id used by the google bigtable APIs to identify instances) to have a randomly generated value, and link an app profile to it?```

(By "public facing" I mean used for identification of the object in the Bigtable API.) 

Similarly, would it be possible to add an optional parameter to app profiles in terraform (that would force recreation of the object if changed), that is not public-facing like the app profile ID? To summarize- I'm looking for a solution that would tie app profiles to bigtable instances directly in terraform but would not affect the way other services interact with either object via the Bigtable API or other interfaces.

**Comment by venkykuberan** [comment]
@EmilyMazo I will move this issue to enhancement bucket. We will work on it once it get prioritized.

**Comment by venkykuberan** [comment]
Just to summarize for the feature request : 

Issue :- When a google_bigtable_instance config is changed (Instance type PRODUCTION to Development), terraform/provider not able to determine the internal dependency between instance and the app profile, hence its only replacing the instance. However GCP deletes both the resources since it knows the underlying dependency.  Terraform comes to aware of the missing app_profile resource only on the next refresh process. This behavior breaks the process flow.

Ask: Terraform/Provider should be able to determine the dependency between the big table instance and app profile, so when ever an instance is recreated the associated app profile should also be recreated.

**Comment by ndmckinley** [comment]
Hi there - you should be able to solve this problem by using the bigtable instance's `id` field instead of its `name` field as your interpolation into the `app_profile`, as long as the instance name does not include the `/` character - which is disallowed in almost all cases.

```
resource "google_bigtable_app_profile" "write-throttling" {
  instance       = google_bigtable_instance.arizona-sandbox.id
  ...
}
```

should do it!

Please comment if this doesn't solve your issue.
