### ISSUE TITLE
Check for valid google_compute_router.bgp.asn number

### ISSUE THREAD

**Issue by umairidris** [terraform-providers/terraform-provider-google#5381]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
The asn field is a number that must be within a specific range. Being outside of this range results in an error from the GCP api:

```
Error: Error updating Router "projects/example-project/regions/us-central1/routers/example-router": googleapi: Error 400: Invalid value for field 'resource.bgp.asn': '1'. Local ASN must be either in the RFC6996 private ASN ranges: [64512..65534], [4200000000..4294967294]; or be the value of [16550].
```

We should check for this in the provider.

### New or Affected Resource(s)

* google_compute_router

Please assign to me, I can implement this.

**Comment by umairidris** [comment]
Thanks for the fix @ankitvg

**Comment by ankitvg** [comment]
@umairidris I didn't see that you wanted this issue to be assigned to yourself. Sorry if I interfered.

**Comment by umairidris** [comment]
No need, you saved me the trouble as this was a bit low on my list anyway :)
