### ISSUE TITLE
auto_delete parameter missing from attached_disk argument

### ISSUE THREAD

**Issue by mioi** [terraform-providers/terraform-provider-google#539]
### Terraform Version
Terraform v0.10.6

### Affected Resource(s)
- google_compute_instance

### Terraform Configuration Files
```hcl
resource "google_compute_instance" "instance" {
  boot_disk {
    initialize_params {
      image = "${var.image}"
    }
  }

  attached_disk {
    source = "${google_compute_disk.disk.name}"
    device_name = "mnt"
    auto_delete = "false"
  }

  machine_type = "${var.machine_type}"

  name = "${var.name}"
  zone = "${var.zone}"

  network_interface {
    subnetwork = "${var.subnetwork}"
    access_config = {
      nat_ip = "${var.address}"
    }
  }

  tags = "${var.tags}"

}
```

### Debug Output
I will just provide the error here since I think it is pretty obvious why this is happening:
```
1 error(s) occurred:

*google_compute_instance.instance: attached_disk.0: invalid or unknown key: auto_delete
```

### Expected Behavior
I expect the `auto_delete` parameter to be available for `attached_disk`. This worked before the split-out from disk to the 3 different disk types.

### Actual Behavior
I get an error (see above).

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
Running the latest available release (v1.0.1 of the terraform-provider-google).

**Comment by mioi** [comment]
@danawillow this makes total sense! Thanks for the explanation. The reason I brought it up was only because as I was modifying my TF configs to reflect the `disk` deprecation change, I noticed that some parameters I was expecting went missing.

I appreciate your explanation. This can be closed as far as I am concerned.

**Comment by danawillow** [comment]
Great! Glad I didn't break you :)
