### ISSUE TITLE
when maintenance_policy recurring_window & release_channel feature move to stable release

### ISSUE THREAD

**Issue by gowrisankar22** [terraform-providers/terraform-provider-google#5391]
Hi colleagues, 

when will the maintenance_policy recurring_window feature and release_channel feature move to the stable release? currently, it is beta.

BRs, Gowrisankar

**Comment by slevenick** [comment]
Recurring window will be available in the next release of the Terraform provider. I don't have information on when the `release_channel` feature will move to GA on the API, but when it does you can file a request for us to make it available in the GA provider.
