### ISSUE TITLE
Add support for custom project and organization roles

### ISSUE THREAD

**Issue by pdecat** [terraform-providers/terraform-provider-google#540]
Hi there,

Google Cloud IAM introduced custom roles last week:

- https://cloudplatform.googleblog.com/2017/10/Introducing-custom-roles-a-powerful-way-to-make-Cloud-IAM-policies-more-precise.html
- https://cloud.google.com/iam/docs/understanding-custom-roles

These custom roles are supported at the project and organization levels:

- https://cloud.google.com/iam/reference/rest/v1/projects.roles
- https://cloud.google.com/iam/reference/rest/v1/organizations.roles#Role

Go API: https://github.com/google/google-api-go-client/blob/c37f2bf2819e28a3885f240b350978f3f833be30/iam/v1/iam-gen.go#L989

### New Resources

It would great to have terraform support those new resources:

- google_project_iam_role
- google_organization_iam_role

**Comment by patrykmikula** [comment]
Any chance those features will be implemented soon (mainly custom roles) ?

**Comment by rosbo** [comment]
Hi @patrykmikula, I just opened a PR to add this feature. Stay tuned :)
