### ISSUE TITLE
Updating a field that requires stopping failed when the compute_instance resource has an encrypted disk

### ISSUE THREAD

**Issue by maqiuyujoyce** [terraform-providers/terraform-provider-google#5408]
I created a compute_instance resource that has an encrypted disk, and wanted to update the `machine_type` field. However, the update failed at [this line](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_instance.go#L1402) because [Instances.Start() doesn't work when the instance has any encrypted disks](https://cloud.google.com/compute/docs/instances/stop-start-instance#starting_a_stopped_instance_that_has_encrypted_disks). Could you fix it?

**Comment by edwardmedia** [comment]
@maqiuyujoyce Can you post your configuration and full debug log here? Thanks
