### ISSUE TITLE
Creating instance from template failed because the boot disk name is not expanded to the full selfLink

### ISSUE THREAD

**Issue by maqiuyujoyce** [terraform-providers/terraform-provider-google#5413]
I'm trying to use the instance_from_template resource to create an instance. The boot disk is defined in the instance_template and [it is referenced by name in the `source` field](https://www.terraform.io/docs/providers/google/r/compute_instance_template.html#source). However, the creation failed because the disk name is not expanded to the full selfLink (code [here](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_instance_from_template.go#L183-L192)). Could you fix it?

TF Config looks like below:
```
resource "google_compute_instance_from_template" "tpl" {
  name = "instance-from-template"
  zone = "us-central1-a"

  source_instance_template = google_compute_instance_template.default.self_link
}

resource "google_compute_instance_template" "default" {
  name        = "test-template"
  machine_type         = "n1-standard-1"

  // Use an existing disk resource as the boot disk
  disk {
    // Instance Templates reference disks by name, not self link
    source      = google_compute_disk.foobar.name
    auto_delete = false
    boot        = true
  }

  network_interface {
    network = "default"
  }
}

data "google_compute_image" "my_image" {
  family  = "debian-9"
  project = "debian-cloud"
}

resource "google_compute_disk" "foobar" {
  name  = "existing-disk"
  image = data.google_compute_image.my_image.self_link
  size  = 10
  type  = "pd-ssd"
  zone  = "us-central1-a"
}
```

**Comment by edwardmedia** [comment]
1. Using above config, `'existing-disk'. The URL is malformed.` is received
2. Changing the config to use self-link: `Disk must be in a regional scope.` is received.
3. Changing it to use regional disks, `Regional disks cannot be used as a boot device.` is received
