### ISSUE TITLE
Can not create google_service_account with  doesn't match regexp error

### ISSUE THREAD

**Issue by TetsutaroWatanabe** [terraform-providers/terraform-provider-google#5421]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.19

### Affected Resource(s)

* google_service_account

### Terraform Configuration Files

```tf
provider "google" {
  project = "xxxx"
  region  = "us-central1"
  credentials = file("terraform-key.json")
}

resource "google_service_account" "hoge" {
  account_id   = "hoge"
}

```

### Panic Output

```
Error: "account_id" ("hoge") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"

  on hoge.tf line 7, in resource "google_service_account" "hoge":
   7: resource "google_service_account" "hoge" {
```

### Steps to Reproduce

1. `terraform apply`

**Comment by Chupaka** [comment]
Correct. Minimum SA name length is 6 chars in GCP. "hoge" is only 4.

**Comment by TetsutaroWatanabe** [comment]
Thank you.
I am sorry to make the issue without investigating regexp in error message well.
