### ISSUE TITLE
Boot to set true for non-boot disks 

### ISSUE THREAD

**Issue by edwardmedia** [terraform-providers/terraform-provider-google#5428]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.16
provider.google v3.4.0

### Affected Resource(s)

google_compute_instance_template

### Terraform Configuration Files

```tf
resource "google_compute_instance_from_template" "tpl" {
  name = "instance-from-template"
  zone = "us-central1-a"

  source_instance_template = google_compute_instance_template.default.self_link
}

resource "google_compute_instance_template" "default" {
  name        = "test-template"
  machine_type         = "n1-standard-1"


  disk {
    source      = google_compute_region_disk.regiondisk.self_link
    auto_delete = false
    boot        = false
  }

    // Create a new boot disk from an image
  disk {
    source_image = "debian-cloud/debian-9"
    auto_delete  = true
    boot         = true
  }

  network_interface {
    network = "default"
  }
}

data "google_compute_image" "my_image" {
  family  = "debian-9"
  project = "debian-cloud"
}

resource "google_compute_region_disk" "regiondisk" {
  name  = "existing-disk"
  snapshot                  = google_compute_snapshot.snapdisk.self_link
  type                      = "pd-ssd"
  region                    = "us-central1"
  physical_block_size_bytes = 4096

  replica_zones = ["us-central1-a", "us-central1-f"]
}

resource "google_compute_disk" "disk" {
  name  = "my-disk"
  image = "debian-cloud/debian-9"
  size  = 50
  type  = "pd-ssd"
  zone  = "us-central1-a"
}

resource "google_compute_snapshot" "snapdisk" {
  name        = "my-snapshot"
  source_disk = google_compute_disk.disk.name
  zone        = "us-central1-a"
}
```

### Expected Behavior

Resources are created without issues 

### Actual Behavior

Error: Error creating instance template: googleapi: Error 400: Invalid value for field 'resource.properties.disks[1].boot': 'true'. At most one persistent disk can be marked as a boot device., invalid

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

In below post body, both disks' boot are set to `true`
```
X-Goog-Api-Client: gl-go/1.13.0 gdcl/20191026
Accept-Encoding: gzip

{
 "name": "test-template",
 "properties": {
  "disks": [
   {
    "boot": true,
    "interface": "SCSI",
    "mode": "READ_WRITE",
    "source": "https://www.googleapis.com/compute/v1/projects/myproject/regions/us-central1/disks/existing-disk",
    "type": "PERSISTENT"
   },
   {
    "autoDelete": true,
    "boot": true,
    "initializeParams": {
     "diskType": "pd-standard",
     "sourceImage": "projects/debian-cloud/global/images/family/debian-9"
    },
    "interface": "SCSI",
    "mode": "READ_WRITE",
    "type": "PERSISTENT"
   }
  ],
  "machineType": "n1-standard-1",
  "metadata": {},
  "networkInterfaces": [
   {
    "network": "projects/sunedward-1/global/networks/default"
   }
  ],
  "scheduling": {
   "onHostMaintenance": "MIGRATE"
  },
  "tags": {}
 }
}
```

### References
I
* #0000

**Comment by slevenick** [comment]
This is a tricky one. The ordering of disks in the Terraform instance_template resource expects the boot disk to be the first specified disk. There is actually an API-level restriction that enforces this. We could potentially re-order the disks from the Terraform config to pass the boot disk first, and then re-order from the response to prevent diffs, but this is tricky.

I'll add an error for if a user attempts to specify a boot disk that is not the first disk in the instance template.
