### ISSUE TITLE
docs: sandbox_config vs sandbox_type

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#5431]
https://www.terraform.io/docs/providers/google/r/container_cluster.html
says

```
sandbox_config - (Optional, Beta) GKE Sandbox configuration. When enabling this feature you must specify image_type = "COS_CONTAINERD" and node_version = "1.12.7-gke.17" or later to use it. Structure is documented below.
```

but in "below" it's "sandbox_type"

**Comment by matti** [comment]
so the actual bug is

"The sandbox_type block supports:" but it should say "The sandbox_config block supports:"

**Comment by venkykuberan** [comment]
yes, the block name should be `sandbox_config`. I will add this to doc update bug list which will be fixed soon. Thank you @matti
