### ISSUE TITLE
google_container_cluster auto_provisioning_defaults state never converges

### ISSUE THREAD

**Issue by MaT1g3R** [terraform-providers/terraform-provider-google#5442]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v0.12.18

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "default-cluster" {
  provider = google-beta

  name = local.cluster_name

  cluster_autoscaling {
    enabled = true
    resource_limits {
      resource_type = "cpu"
      minimum       = 6
      maximum       = 72
    }
    resource_limits {
      resource_type = "memory"
      minimum       = 24
      maximum       = 128
    }
    auto_provisioning_defaults {
      service_account = google_service_account.k8s_service_account.email
    }
  }
}
```

### Expected Behavior

Terraform state does not track oauth_scopes under auto_provisioning_defaults

### Actual Behavior
Terraform state tracks oauth_scopes under auto_provisioning_defaults, which leads to a diff for every apply like so:

```
~ cluster_autoscaling {
    enabled = true
    ~ auto_provisioning_defaults {
        ~ oauth_scopes    = [
            - "https://www.googleapis.com/auth/logging.write",
            - "https://www.googleapis.com/auth/monitoring",
        ]
        service_account = "xxxx@xxxx.iam.gserviceaccount.com"
    }
    resource_limits {
        maximum       = 72
        minimum       = 6
        resource_type = "cpu"
    }
    resource_limits {
        maximum       = 128
        minimum       = 24
        resource_type = "memory"
    }
}

```

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@MaT1g3R yes, I can repro this issue. It does show below plan 
```
Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by mtricolici** [comment]
This issue is still present in latest terraform version 0.12.20 !

**Comment by danawillow** [comment]
Hi @mtricolici, we close issues once the code is checked in, but that doesn't mean it's been released yet. You can see whether or not a given PR has made it into a release by checking the [CHANGELOG](https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md).

Note also that 0.12.20 is a Terraform CLI version but not a Google Provider version. You can read about provider versions at https://www.terraform.io/docs/configuration/providers.html#provider-versions.
