### ISSUE TITLE
Add `google_project_iam_policy` as a data source

### ISSUE THREAD

**Issue by j-martin** [terraform-providers/terraform-provider-google#5444]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We would like to be able to able to use `google_project_iam_binding` and/or `google_project_iam_policy` as a data source. Our use case is that to apply plans in production we require admins to grant temporarily themselves the project owner role. We call it `sudo`. 

We want to use `google_project_iam_policy` resource on this project, but terraform will remove the ownership assignment if it's not defined explicitly in the tf config. We also do not want it to be permanent either.

By reading the current members assigned to the role on that project, we can inject the current role assignment during the planning phase.

### New or Affected Resource(s)

* data.google_project_iam_policy
* data.google_project_iam_binding

### Potential Terraform Configuration

```tf
data "google_project_iam_policy" "something" {
  project = "my-project-id"
}

data "google_project_iam_binding" "owners" {
  project = "my-project-id"
  role = "roles/owner"
}
```

### References

* #0000

**Comment by rileykarson** [comment]
Hey @j-martin!

I'm a little confused how these datasources will help your use case. If you were to use `google_project_iam_policy` with the policy data fed in from `data.google_project_iam_policy`, wouldn't the effect just be that Terraform never sees a diff?

I think one avenue to explore would be to create a service account on your project, and grant it the project owner role. Then, "`sudo`" users can be assigned roles directly on the service account like with [`google_service_account_iam_member`](https://www.terraform.io/docs/providers/google/r/google_service_account_iam.html#google_service_account_iam_member). Particularly, `roles/iam.serviceAccountTokenCreator` will allow them to create short-lived credentials like access tokens as described in the guide [Creating short-lived service account credentials](https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials).

**Comment by j-martin** [comment]
As counter interruptive as it may seem we do want to have zero change for
this role. For example, if doing a plan I might have not granted myself the
extra role so I don't want to add it in terraform. If I do an apply and
granted myself the role temporarily then I want terraform to keep the role.

In the end I got it working by using the external provider and invoking
`gcloud Ian roles ...` directly.

On this note you are right that the service account approach is much more
elegant.

On this note, feel free to close this issue.
