### ISSUE TITLE
Retries for everything

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#5460]
Request from KCC. Generated resources have retries for everything, but handwritten ones only do sometimes.

Ideally this would be done as a custom transport or something like that so that we don't have to copy/paste retry blocks into all the handwritten resources. If we do that strategy, we'll at least want to remove the ones we already have so that we aren't retrying our retries.

**Comment by emilymye** [comment]
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/3196
