### ISSUE TITLE
google_monitoring_alert_policy: "labels" doesn't go away

### ISSUE THREAD

**Issue by jba** [terraform-providers/terraform-provider-google#5462]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.12.19
+ provider.google v3.4.0
+ provider.google-beta v3.4.0
```

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_monitoring_alert_policy" "uptime" {
  display_name = "Uptime Checks"

  conditions {
    display_name = "Uptime Checks Failed"

    condition_threshold {
      filter          = <<-EOT
        metric.type="monitoring.googleapis.com/uptime_check/check_passed"
        resource.type="uptime_url"
        resource.label."host"=monitoring.regex.full_match("(REDACTED.appspot.com|REDACTED.appspot.com)")
      EOT
      comparison      = "COMPARISON_GT"
      threshold_value = 0.1

      aggregations {
        alignment_period     = "120s"
        cross_series_reducer = "REDUCE_COUNT_FALSE"
        group_by_fields      = ["resource.*"]
        per_series_aligner   = "ALIGN_NEXT_OLDER"
      }
      duration = "300s"
      trigger { count = 1 }
    }
  }
  combiner = "OR"

  notification_channels = local.page

  documentation {
    content = format(local.playbook_fmt, "uptime_checks")
  }
}

```

### Expected Behavior

I just upgraded to 3.4 from 2.18. 

`tf apply` followed by `tf plan` should say that no changes are needed.
### Actual Behavior

Now `tf plan` always says

```
# google_monitoring_alert_policy.uptime will be updated in-place                                                           
  ~ resource "google_monitoring_alert_policy" "uptime" {      
      ...
      + labels                = (known after apply)
       ...
```
Running `tf apply` does not change that.

As you can see from my config above, I do not explicitly mention `labels` in the config.
### Steps to Reproduce

Given above

### Important Factoids

Upgraded from 2.18 to to 3.4.

### References

#3493 does not apply; I have no `labels` in my config.

**Comment by edwardmedia** [comment]
duplicate https://github.com/terraform-providers/terraform-provider-google/issues/5339
