### ISSUE TITLE
Ability to reference a GKE google_compute_backend_service by kubernetes.io/service-name label

### ISSUE THREAD

**Issue by dijitali** [terraform-providers/terraform-provider-google#5468]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I have several GCE Ingresses with Identity-Aware Proxy enabled and I'm attempting to use Terraform specify which G Suite user groups are allowed to access (via the `iap.httpsResourceAccessor` role).

The GCE Ingresses and therefore also the corresponding Backend Services are managed by GKE, not Terraform.  Therefore I am attempting to use the `google_compute_backend_service` data source reference in my `google_iap_web_backend_service_iam_policy` but am struggling to work out how to inform Terraform of the correct `name` attribute since it's an auto-generated name, e.g. `k8s-be-12345--1234a12345xy78za`.

The Kubernetes service name is available within the description of the [backendServices API](https://cloud.google.com/compute/docs/reference/rest/v1/backendServices/list):
```text
GET https://compute.googleapis.com/compute/v1/projects/{project}/global/backendServices

      "name": "k8s-be-12345--1234a12345xy78z",
      "description": "{\"kubernetes.io/service-name\":\"my-namespace/my-ingress\",\"kubernetes.io/service-port\":\"3000\"}",
      "selfLink": "https://www.googleapis.com/compute/v1/projects/<project>/global/backendServices/k8s-be-12345--1234a12345xy78z",
```

Could this be used to allow me to select which GCE Ingress I want to refer to in the `google_compute_backend_service` data source?

### New or Affected Resource(s)

* `google_compute_backend_service`
* `google_iap_web_backend_service_iam_policy`

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

data "google_iam_policy" "iap-team-access" {
  binding {
    role = "roles/iap.httpsResourceAccessor"

    members = [
      "group:my-first-team@example.com",
      "group:my-second-team@example.com",
    ]
  }

  audit_config {
    service = "iap.googleapis.com"
    audit_log_configs {
      log_type = "DATA_READ"
    }

    audit_log_configs {
      log_type = "DATA_WRITE"
    }

    audit_log_configs {
      log_type = "ADMIN_READ"
    }
  }
}

data google_compute_backend_service "my-ingress" {
  kubernetes-service-name = "my-namespace/my-ingress"
}

resource "google_project_iam_audit_config" "iap-audit-logging" {
  project = local.remote_proj_id
  service = "iap.googleapis.com"

  audit_log_config {
    log_type = "ADMIN_READ"
  }
  audit_log_config {
    log_type = "DATA_READ"
  }
  audit_log_config {
    log_type = "DATA_WRITE"
  }
}

resource "google_iap_web_backend_service_iam_policy" "my-ingress-team-access" {
  provider = google-beta
  project  = local.remote_proj_id

  web_backend_service = data.google_compute_backend_service.my-ingress.name
  policy_data         = data.google_iam_policy.iap-team-access.policy_data
}

```

### References

* This seems like a similar area to the discussion in https://github.com/terraform-providers/terraform-provider-google/issues/3838#issuecomment-501484794.  So perhaps there's a better approach altogether here?

**Comment by rileykarson** [comment]
I would recommend trying to raise an issue against the GCE Ingress implementation, I'd hope that resource-level permissions for GKE-managed resources can be handled in GKE itself instead of awkwardly crossing control planes as proposed. Alternatively, if the name of the backend service is available within K8S, [Config Connector](https://cloud.google.com/config-connector/docs/overview) may support a cleaner solution if that resource is available in it.

In terms of a Terraform-side solution, your approach seems feasible. This isn't work that the provider team is likely to pick up unless there's _significant_ community interest, so we've added it to the backlog milestone. If the proposed datasource is something you (or another reader) are interested in, we'd probably accept a PR adding it.

**Comment by dijitali** [comment]
Thanks @rileykarson - that makes good sense.  

Turns out there's already something open on the GCE Ingress side for this: https://github.com/kubernetes/ingress-gce/issues/511 (and also [#133192467: add/change "IAP-Secured Web App Users" in BackendConfig](https://issuetracker.google.com/issues/133192467)) which looks like a more elegant way of doing this.

Happy to close this issue and wait on progress there.  Even if Terraform is creating the Ingress within K8s, GKE is creating the LBs and IAP config so it seems correct for IAM settings to be done in the same manner.
