### ISSUE TITLE
Import of google_sql_database_instance crashs provider

### ISSUE THREAD

**Issue by moos3** [terraform-providers/terraform-provider-google#5482]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.20
+ provider.google v3.5.0
+ provider.google-beta v3.5.0

### Affected Resource(s)

* google_sql_database_instance
* google_sql_database

### Terraform Configuration Files

```tf init.tf
provider "google" {}
provider "google-beta" {}
```

### Debug Output
https://gist.github.com/moos3/4e5a633c0668bec19fb6c48b7ca9f00e

### Panic Output
https://gist.github.com/moos3/4e5a633c0668bec19fb6c48b7ca9f00e

### Expected Behavior
to be able to refresh and import the resources. 

### Actual Behavior
doesn't actually import the resources in the tfstate.

### Steps to Reproduce

1. `terraformer import google --connect=true --regions=us-east1 --projects=<project> -p "{service}/" --resources=cloudsql -v`

### Important Factoids
Authenticating as project owner

**Comment by venkykuberan** [comment]
@moos3 I assume you have created the `google_sql_database` and `google_sql_database_instance` successfully outside the terraform and want to import the resource state to terraform.

the import commands are
```
terraform import google_sql_database_instance.master projects/{{xxx-xxx}}/instances/{{test-import-mysql}}
terraform import google_sql_database.default projects/{{xxx-xxx}}/instances/{{test-import-mysql}}/databases/{{testdb}}
```
I am able to import the state with the version
```
Terraform v0.12.20
+ provider.google v3.5.0
```  

---------------- sample config ----------------
```
resource "google_sql_database_instance" "master" {
  # (resource arguments)
}

resource "google_sql_database" "default"{
    
}
```

**Comment by venkykuberan** [comment]
@moos3 the above command would help to import the sql_database_instance resource. I am closing this issue, if you need any other help please open an new issue
