### ISSUE TITLE
Not able to create dataproc cluster in another project

### ISSUE THREAD

**Issue by eakarsu** [terraform-providers/terraform-provider-google#5483]
I am creating dataproc cluster with terraform with latest version and lates version of gcloud provider 3.5

Even though we are giving all roles to sa account to use, still we are getting error.

Roles:
Compute Instance Admin (v1)
Dataproc Administrator
Dataproc Service Agent
Dataproc Worker
Dataproc Editor
Storage Admin

It does not matter whether we c rate dataproc cluster with glcoud direct command line or terraform. Both is giving same error

gcloud I am using is this:

gcloud dataproc clusters create --region=us-east4 --service-account=sa-dataproc@sampleproject.iam.gserviceaccount.com --subnet=https://www.googleapis.com/compute/v1/projects/sampleproject/regions/us-east4/subnetworks/samplesubnet --verbosity=debug test-cluster

HttpBadRequestError: HttpError accessing <https://dataproc.googleapis.com/v1/projects/sampleproject/regions/us-east4/clusters?alt=json&requestId=234c2ee9409648768641aee397fcf5fa>: response: <{'status': '400', 'content-length': '471', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 'cache-control': 'private', 'date': 'Thu, 23 Jan 2020 16:36:04 GMT', 'x-frame-options': 'SAMEORIGIN', 'alt-svc': 'quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000', 'content-type': 'application/json; charset=UTF-8'}>, content <{
  "error": {
    "code": 400,
    "message": "Required 'compute.subnetworks.get' permission for 'projects/samplenetwork/regions/us-east4/subnetworks/samplesubnet'. This usually happens when Dataproc Control Plane Identity service account does not have permission to validate resources in another project. For additional details see https://cloud.google.com/dataproc/docs/concepts/iam/dataproc-principals",
    "status": "INVALID_ARGUMENT"
  }
}
>
ERROR: (gcloud.dataproc.clusters.create) INVALID_ARGUMENT: Required 'compute.subnetworks.get' permission for 'projects/samplenetwork/regions/us-east4/subnetworks/samplesubnet'. This usually happens when Dataproc Control Plane Identity service account does not have permission to validate resources in another project. For additional details see https://cloud.google.com/dataproc/docs/concepts/iam/dataproc-principals

**Comment by edwardmedia** [comment]
@eakarsu  can you share your configurations? Also please post the full debug log so I can take a look. Thanks

**Comment by upodroid** [comment]
@eakarsu Hi that error is to do with the dataproc service account not having Compute Network User role in the Shared VPC Host project.

Please review this document. https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/network#creating_a_cluster_that_uses_a_vpc_network_in_another_project

**Comment by edwardmedia** [comment]
@eakarsu you said you see the same error by running `gcloud` and `terraform`. You file this issue at `terraform-provider-google`, before I say for sure this is not a terraform issue, do you mind if you post your terraform code and your full debug log so I can take a closer look? Thank you

**Comment by edwardmedia** [comment]
@eakarsu the error you received seems to tell you what you could do next. Likely it is not a provider issue. At this point, I am going to close the issue. Please feel free to reopen it if you need further assistance. Thanks

> Required 'compute.subnetworks.get' permission for 'projects/samplenetwork/regions/us-east4/subnetworks/samplesubnet'. This usually happens when Dataproc Control Plane Identity service account does not have permission to validate resources in another project. For additional details see https://cloud.google.com/dataproc/docs/concepts/iam/dataproc-principals
