### ISSUE TITLE
Add support for providing zones in google_compute_region_instance_group_manager

### ISSUE THREAD

**Issue by zbikmarc** [terraform-providers/terraform-provider-google#549]
Google released (currently in beta) capability to select to which zones regional instance group manager should deploy to. It would be awesome to has similar feature in `google_compute_region_instance_group_manager`.

### Terraform Version
- `terraform-0.10.6`
- `terraform-provider-google-1.0.1`

### Affected Resource(s)
- `google_compute_region_instance_group_manager`

### Expected Behavior
It should be possible to provide zones (optional) where regional manager can deploy to. I think it should be list of zones.

### Actual Behavior
It does not support it.

### References
- https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups#selectingzones

**Comment by danawillow** [comment]
Fixed in #1092
