### ISSUE TITLE
google_dns_record_set always wants to update

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#5497]
like in #863

```
resource "google_dns_record_set" "google_dot__domainkey-lol-com-txt" {
  name = "google._domainkey.lol.com."

  managed_zone = google_dns_managed_zone.tld-1.name
  type         = "TXT"
  ttl          = 60

  rrdatas = [
    "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCj8O8aDzmnPwJ8mzo6y8rLXq8r1i45fr3nTGElX9h6Nr3s8w5Ozu27ep5T08YC6Vo00WLPl5N+K91Fb1y/RHHQVfPMHvHD+IDcUiaBOe6RNVMv3AcR0S+pSwaE8KFsYbizdRjH8+qMUwyH9o3c18tNcpS6otCiwBMg1PqJ1i+EyQIDAQAB"
  ]
}
```

```
  # module.dns-1.google_dns_record_set.google_dot__domainkey-lol-com-txt will be updated in-place
  ~ resource "google_dns_record_set" "google_dot__domainkey-lol-com-txt" {
        id           = "lol-com-1-1/google._domainkey.lol.com./TXT"
        managed_zone = "lol-com-1-1"
        name         = "google._domainkey.lol.com."
        project      = "katti-makkara"
      ~ rrdatas      = [
          - "\"v=DKIM1;\" \"k=rsa;\" \"p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCj8O8aDzmnPwJ8mzo6y8rLXq8r1i45fr3nTGElX9h6Nr3s8w5Ozu27ep5T08YC6Vo00WLPl5N+K91Fb1y/RHHQVfPMHvHD+IDcUiaBOe6RNVMv3AcR0S+pSwaE8KFsYbizdRjH8+qMUwyH9o3c18tNcpS6otCiwBMg1PqJ1i+EyQIDAQAB\"",
          + "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCj8O8aDzmnPwJ8mzo6y8rLXq8r1i45fr3nTGElX9h6Nr3s8w5Ozu27ep5T08YC6Vo00WLPl5N+K91Fb1y/RHHQVfPMHvHD+IDcUiaBOe6RNVMv3AcR0S+pSwaE8KFsYbizdRjH8+qMUwyH9o3c18tNcpS6otCiwBMg1PqJ1i+EyQIDAQAB",
        ]
        ttl          = 60
        type         = "TXT"
    }
```

**Comment by edwardmedia** [comment]
It shows 
```
Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by danawillow** [comment]
@edwardmedia, when you reproed were you able to get DEBUG logs that you could share? It looks like it has to do with escaping the quotes but it would be good to know for sure whether it's the API doing it or something in our code.

@matti, thanks for the report! Next time, please fill out the [bug template](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=bug.md)- it asks for information that make it easier to figure out what's going on on our side.

**Comment by matti** [comment]
@danawillow Which particular piece of information did I leave out by not following the template? Honest question.

**Comment by danawillow** [comment]
Debug logs and provider version

**Comment by danawillow** [comment]
Oh and there's also some metadata in the template that helps our automation label issues so that our teammates don't have to hunt down issues without a label.

**Comment by matti** [comment]
Okay, the template is missing information on how to get DEBUG logs - I have used terraform and google provider for 3 years and I have no idea what is DEBUG log

**Comment by danawillow** [comment]
The template has the following block in the debug logs section:
> To obtain the debug output, see the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html).

If that documentation is confusing or could be improved, I'd recommend filing an issue against https://github.com/hashicorp/terraform so they can try to improve clarity there. Or if you'd just prefer that our bug template be phrased in a different way, you're welcome to propose a PR to change it (the source is at https://github.com/terraform-providers/terraform-provider-google/blob/master/.github/ISSUE_TEMPLATE/bug.md) or file an issue against us to do so (no issue template needed in that case)

**Comment by matti** [comment]
It is still not 100% clear

I am assuming TF_LOG=DEBUG ?

the template could just say:

Debug logs (TF_LOG=DEBUG terraform apply ...):

?

**Comment by danawillow** [comment]
Hey @matti, aside from the perpetual diff, do the record sets actually get created correctly? Our [documentation](https://www.terraform.io/docs/providers/google/r/dns_record_set.html#rrdatas) says:
> For TXT record, if the string data contains spaces, add surrounding \" if you don't want your string to get split on spaces. 

which was added after https://github.com/terraform-providers/terraform-provider-google/issues/232, which implies the record might be invalid with the extra quotes. I don't know if that's the case with a record like your example or just SPF, do you know?

**Comment by andrew-s** [comment]
I came here for the same issue on TXT records (DKIM/SPF, etc..) - the quotes worked but it seems like a really odd syntax, e.g.

```
value = ["\"v=spf1 include:_spf.google.com ~all\""]
```

I'm really unclear on the defaults here, this provider splits strings within a list into a further list (so a list of lists?)? Why would it do that by default? It makes no sense to me, I'd maybe suggest this default behaviour is changed as it's completely counterintuitive.

**Comment by danawillow** [comment]
@andrew-s that requirement comes straight from the GCP documentation on record sets (https://cloud.google.com/dns/records/json-record). The provider is just passing along the strings exactly as they're sent.

I'm going to go ahead and close this issue for now since it's been open for a few months without a response, but feel free to comment or file a new issue if you encounter any other issues or questions.
