### ISSUE TITLE
Fix  TestAccDataSourceDnsManagedZone_basic

### ISSUE THREAD

**Issue by emilymye** [terraform-providers/terraform-provider-google#5507]
=== RUN   TestAccDataSourceDnsManagedZone_basic
=== PAUSE TestAccDataSourceDnsManagedZone_basic
=== CONT  TestAccDataSourceDnsManagedZone_basic
--- FAIL: TestAccDataSourceDnsManagedZone_basic (5.53s)
    testing.go:635: Step 0 error: Check failed: reverse_lookup is ; want false

**Comment by emilymye** [comment]
@slevenick might be related to https://github.com/GoogleCloudPlatform/magic-modules/pull/3026

**Comment by slevenick** [comment]
Ah, dang forgot the datasource
