### ISSUE TITLE
google_service_networking_connection project ID issue

### ISSUE THREAD

**Issue by mbrowne** [terraform-providers/terraform-provider-google#5516]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v0.11.14
(I'm pretty sure the same issue would occur with Terraform 0.12 but haven't tested it.)

### Affected Resource(s)

* google_service_networking_connection

### Terraform Configuration Files

```tf
provider "google-beta" {
  project     = "terraform-admin-project"
}

resource "google_compute_network" "peering_network" {
  project = "my-private-network-project"
  name    = "peering-network"
}

resource "google_compute_global_address" "private_ip_alloc" {
  project       = "my-private-network-project"
  name          = "private-ip-alloc"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  network       = google_compute_network.peering_network.self_link
}

resource "google_service_networking_connection" "foobar" {
  provider = "google-beta"
  network                 = "${google_compute_network.peering_network.self_link}"
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = ["${google_compute_global_address.private_ip_alloc.name}"]
}
```

### Debug Output

> 1 error occurred:
> 	* google_service_networking_connection.foobar: 1 error occurred:
> 	* google_service_networking_connection.foobar: Error waiting for Create Service Networking Connection: error while retrieving operation: googleapi: Error 403: Service Networking API has not been used in project [xxx-redacted] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/servicenetworking.googleapis.com/overview?project= [xxx-redacted] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured

### Expected Behavior

Applied successfully

### Actual Behavior

The above error is referring to the fact that that when I originally tried to apply this config, the service networking API was enabled in `terraform-admin-project` but not in `my-private-network-project`.

It occurs because `peering_network` is in a different project than the provider (the provider project is `terraform-admin-project`, whereas the google_service_networking_connection should be created in the `my-private-network-project` project (where the `peering_network` is being created).

It worked after I asked an administrator to enable the service networking API in `terraform-admin-project`, but I don't think that should be a requirement because I wasn't trying to create any resources in that project. In other words, I think enabling the service networking API in `my-private-network-project` should have been sufficient.

### Steps to Reproduce

1. `terraform apply`

### References

This previous feature request is relevant, although I don't think it's necessarily the best way to solve this:
https://github.com/terraform-providers/terraform-provider-google/issues/2799

It's fine if `google_service_networking_connection` doesn't support a `project` field (one less thing to configure, or potentially forget to configure). But if you're referencing a `google_compute_network` in a project that already has the service networking API enabled, I think it should work, even if the provider is using a different project (which is a common setup for larger Terraform configs that include multiple GCP projects).

**Comment by edwardmedia** [comment]
@mbrowne  this is an expected behavior. It is nothing to do in the terraform layer.

**Comment by mbrowne** [comment]
So it's expected that the service networking API needs to be enabled for both projects (given the above example) and not only in the project where you're actually making the change? I was thinking that maybe the provider is checking if the API is enabled in `terraform-admin-project` based on an assumption that that's where I want to create the `google_service_networking_connection`. But if Google requires the API to be enabled in both projects, then obviously there's nothing the TF provider can do about this...

**Comment by edwardmedia** [comment]
@mbrowne  yes. This is the case. Thank you. I am closing the issue now.
