### ISSUE TITLE
provider block using google-beta

### ISSUE THREAD

**Issue by anubbhavm** [terraform-providers/terraform-provider-google#5519]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Expected Behavior
As per documentation,
https://www.terraform.io/docs/providers/google/guides/provider_versions.html#using-both-provider-versions-together
To use the google-beta provider, explicitly define a google-beta provider block, and state on the resource which provider you wish to use.
```hcl
provider "google-beta" {
  credentials = "${file("account.json")}"
  project     = "my-project-id"
  region      = "us-central1"
}

resource "google_compute_instance" "beta-instance" {
  provider = "google-beta"

  # ...
}
```

### Actual Behavior

Not explicitly defining the google-beta provider block and only defining the provider on the resource also seems to work.
```hcl
resource "google_compute_instance" "beta-instance" {
  provider = "google-beta"
  # ...
}
```

**Comment by edwardmedia** [comment]
@anubbhavm Not sure what exact cases you are referring, but if you are taking about below two configs, they are different. Let me know if I addressed your issue.
```
resource "google_compute_instance" "beta-instance" {
  provider = "google-beta"
  # ...
}
```
```
resource "google_compute_instance" "beta-instance" {
  # provider = "google-beta"
  # ...
}
```

**Comment by anubbhavm** [comment]
Okay let me clarify:
In order to use the google-beta provider, is it required to explicitly define a google-beta provider block?
```hcl
provider "google-beta" {
  credentials = "${file("account.json")}"
  project     = "my-project-id"
  region      = "us-central1"
}
```
Or, just stating the provider on the resource suffice?
```hcl
resource "google_compute_instance" "beta-instance" {
  provider = "google-beta"
  # ...
}```

The TF documentation says both are necessary (a provider block and provider on the resource), but I was able to use the beta feature without explicitly defining a provider block.

**Comment by edwardmedia** [comment]
@anubbhavm  the block is not required. You need to provide the attribute `provider` inside the resource if it is `google-beta`.

**Comment by anubbhavm** [comment]
Thanks. Could we then have the TF documentation updated please?
https://www.terraform.io/docs/providers/google/guides/provider_versions.html#using-both-provider-versions-together

**Comment by danawillow** [comment]
Thanks @anubbhavm, that's a good suggestion and I didn't even know that not providing the provider block for google-beta even worked, so I learned something new today :)

Changing the labels since this is a docs improvement rather than a bug in the provider. We'll triage this alongside FRs.

**Comment by rileykarson** [comment]
This changed in Terraform 0.12. We were aware at the time of `2.5.1`'s release, but kept the docs indicating it was required because the majority of users would have been using `0.11` still. It could be worth including a note about `0.11` still needing it, since our docs are unversioned and we expect some users to be using `2.X` + `0.11` still.
