### ISSUE TITLE
google_compute_managed_ssl_certificate attribute supports 1 item maximum, config has 3 declared

### ISSUE THREAD

**Issue by hpio** [terraform-providers/terraform-provider-google#5523]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

`Terraform v0.12.20`

### Affected Resource(s)

* google_compute_managed_ssl_certificate

### Terraform Configuration Files

```
resource "google_compute_managed_ssl_certificate" "example" {
  provider = google-beta
  name = "${var.envname}-example-certificate"

  managed {
    domains = ["example.com", "test.example.com"]
  }

}
```

### Expected Behavior

A new san certificate is created for all domains listed in `domains` list

### Actual Behavior

`Error: managed.0.domains: attribute supports 1 item maximum, config has 2 declared`

### Steps to Reproduce

try to plan the above code

1. `terraform apply`

### References

as per resource docs https://www.terraform.io/docs/providers/google/r/compute_managed_ssl_certificate.html 

```
domains - (Required) Domains for which a managed SSL certificate will be valid. Currently, there can be up to 100 domains in this list. 
```
* #0000

**Comment by edwardmedia** [comment]
@hpio  This is controlled by GCP API and maximum = 1 is expected. Below is the reference from GCP API. I am closing this issue. Please reopen it if you have more questions. 
```
managed.domains[] | stringThe domains for which a managed SSL certificate will be generated. Currently only single-domain certs are supported.
```
https://cloud.google.com/compute/docs/reference/rest/beta/sslCertificates/insert

**Comment by missinglink** [comment]
Hi @edwardmedia, I also found this confusing as the docs say:

> Currently, there can be up to 100 domains in this list
