### ISSUE TITLE
PubSub topic trigger event context.resource has different structure/content when created using terraform instead of CLI/console

### ISSUE THREAD

**Issue by nstonesplunk** [terraform-providers/terraform-provider-google#5535]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `google_cloudfunctions_function` resource should include trigger_topic as an optional attribute. Although you can work around this by using the legacy `event_trigger` attribute, it seems that using `event_trigger` is not equivalent to a `trigger_topic` in terms of the context object that is passed into the Cloud Function when the topic is actually published to and the function is triggered.

As an example, I have a manually configured (through the console) Cloud Function using a pubsub topic trigger and a function deployed with an `event_trigger` to the same pubsub topic.

The context object when the function is created manually (with a PubSub topic trigger):
```
{
  "event_id": "1234567890"
  "timestamp": "2020-01-29T19:00:31.345Z",
  "event_type": "google.pubsub.topic.publish",
  "resource": {
    "service": "pubsub.googleapis.com",
    "name": "projects/{project}/topics/stackdriver-logs",
    "type": "type.googleapis.com/google.pubsub.v1.PubsubMessage"
  }
}
```
**Note that resource is an object**

This is the context object when the function is created through terraform using `event_trigger` (with the same PubSub topic trigger):
```
{
  "event_id": "1234567890",
  "timestamp": "2020-01-29T18:58:10.258Z",
  "event_type": "providers/cloud.pubsub/eventTypes/topic.publish",
  "resource": "projects/{project}/topics/stackdriver-logs"
}
```
**Note that resource is a string (the triggering topic name)**

Terraform resource code snippet for context:
```
resource "google_cloudfunctions_function" "pubsub-triggered-function" {
  ...
  event_trigger {
    event_type = "providers/cloud.pubsub/eventTypes/topic.publish"
    resource = google_pubsub_topic.stackdriver-logs-topic.name
  }
  ...
}
```

### New or Affected Resource(s)

* google_cloudfunctions_function

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```
```
resource "google_cloudfunctions_function" "pubsub-triggered-function" {
  ...
  trigger_topic = google_pubsub_topic.stackdriver-logs-topic.name
  ...
}
```
### References

* https://cloud.google.com/functions/docs/calling/pubsub#legacy_cloud_pubsub_triggers (describing current `event_trigger` attribute as the legacy approach)

**Comment by danawillow** [comment]
Hey @nstonesplunk, I'm having some trouble mapping what you're looking for back to the REST API, since there's no `triggerTopic` field there (https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions). Can you run the gcloud command that works with `--log-http` and the current Terraform one with `TF_LOG=DEBUG` so we can see the difference in the API requests being made?

**Comment by nstonesplunk** [comment]
Hi @danawillow. Did a bit more digging since posting this. Looks like this was an error on my part. I took a closer look at the difference between the console/gcloud and the Terraform deployed Cloud Function and the difference is in the eventTrigger's eventType. I was using the legacy `providers/cloud.pubsub/eventTypes/topic.publish` eventType while the console (and gcloud using `--trigger-topic`) will set the eventType as `google.pubsub.topic.publish`.

Below is the GET response to both to highlight the difference.

**Terraform deployed function:**
```
{
  ...
  "eventTrigger": {
    "eventType": "google.pubsub.topic.publish",
    "resource": "projects/{PROJECT}/topics/stackdriver-logs",
    "service": "pubsub.googleapis.com",
    "failurePolicy": {}
  },
  ...
}
```
 
**Manually (console) deployed function:**
```
{
  ...
  "eventTrigger": {
    "eventType": "providers/cloud.pubsub/eventTypes/topic.publish",
    "resource": "projects/{PROJECT}/topics/stackdriver-logs",
    "service": "pubsub.googleapis.com",
    "failurePolicy": {}
  },
  ...
}
```

Thanks, you can close this out.

**Comment by danawillow** [comment]
Glad you were able to figure it out!
