### ISSUE TITLE
google_organization_iam_policy misbehaves if given a bare organization id

### ISSUE THREAD

**Issue by rvandegrift** [terraform-providers/terraform-provider-google#5537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```$ terraform -v
Terraform v0.12.18
+ provider.google v3.6.0
```

### Affected Resource(s)

* `google_organization`
* `google_organization_iam_policy`

### Terraform Configuration Files

```tf
data "google_organization" "example" {
  domain = "example.com"
}

resource "google_organization_iam_policy" "example" {
  org_id      = data.google_organization.example.id
  policy_data = data.google_iam_policy.org_iam_policy.policy_data
}
```

### Expected Behavior

`google_organization_iam_policy` should know that canonical and non-canonical org ids can be the same.  ie. org id `1234567890` is the same organization as `organizations/1234567890`.

(Maybe that could be generalized to other resources?)

### Actual Behavior

I'm upgrading a config from provider 2.x to 3.x.  In 3.x, the `google_organization` data source stored the non-canonical format of the org ID.  Now, a 3.x upgrade forces recreation of the IAM policy because 3.x uses the canonical form.

### Steps to Reproduce

1. Deploy an org IAM policy using the non-canonical format.
2. Update the config to change to the canonical format.
3. `terraform plan`

### References

I reported a similar bug for folder ids in terraform import here: #4971

**Comment by rvandegrift** [comment]
I just tried to work around this by deleting the org IAM policy from the state & re-importing, but that fails.  terraform import only accepts the non-canonical form of the id:
```
$ terraform state rm google_organization_iam_policy.example
Removed google_organization_iam_policy.example
Successfully removed 1 resource instance(s).
$ terraform import google_organization_iam_policy.example organizations/1234567890
google_organization_iam_policy.example: Importing from ID "organizations/1234567890"...
google_organization_iam_policy.example: Import prepared!
  Prepared google_organization_iam_policy for import
google_organization_iam_policy.example: Refreshing state... [id=organizations/1234567890]

Error: Cannot import non-existent remote object

While attempting to import an existing object to
google_organization_iam_policy.example, the provider detected that no object
exists with the given id. Only pre-existing objects can be imported; check
that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new remote
object for this resource.
$ terraform import google_organization_iam_policy.example 123456780
google_organization_iam_policy.example: Importing from ID "1234567890"...
google_organization_iam_policy.example: Import prepared!
  Prepared google_organization_iam_policy for import
google_organization_iam_policy.example: Refreshing state... [id=1234567890]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

And unfortunately, after this import, the IAM policy still has the non-canonical form that terraform wants to replace:
```
$ terraform state show google_organization_iam_policy.example | grep org_id
    org_id      = "1234567890"
```

**Comment by venkykuberan** [comment]
@rvandegrift it should treat 1234567890 & organizations/1234567890 as same. The provider needs to be updated, i will add this issue to features list for code change.

Thanks for filing it.

**Comment by c2thorn** [comment]
The change to `id` in the organization datasource was intentional, and part of a larger set of id changes in 3.0.0.

This specific datasource was also brought up in https://github.com/terraform-providers/terraform-provider-google/issues/5110, so a new field `org_id` was added in 3.0.0 to maintain access to the raw org id. **Using `org_id` instead of `id` from the datasource should get you what you want.**

This is represented in the documentation for the [datasource](https://www.terraform.io/docs/providers/google/d/google_organization.html) but not pointed out specifically in the [upgrade guide](https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#id-format-changes), which is something I can update.

**Comment by c2thorn** [comment]
Whoops, `org_id` wasn't added until 3.2, so it couldn't have been in the upgrade guide to 3.0. It is present in the [3.2 changelog](https://github.com/terraform-providers/terraform-provider-google-beta/blob/master/CHANGELOG.md#320-december-11-2019).

**Comment by c2thorn** [comment]
Closing as this is intentional. If there is still a desire to be able to import using either format, a feature request can be added.
