### ISSUE TITLE
Allow specifying 'container_port' and 'request_timeout' for google_cloud_run_service

### ISSUE THREAD

**Issue by viprerk** [terraform-providers/terraform-provider-google#5539]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When deploying a Managed Cloud Run service in the GCP Web UI, the 'Container Port' and 'Request Timeout' options can be changed.

When deploying a Managed Cloud Run service with Terraform, there is no configuration available to change the 'Container Port' and 'Request Timeout' options away from default values.

I would like to be able to set these options when deploying Managed Cloud Run services with Terraform, instead of using the default values.

### New or Affected Resource(s)

google_cloud_run_service

### Potential Terraform Configuration

```tf
resource "google_cloud_run_service" "example-service" {
  name     = "example-service"
  location = var.cloud_run_region
  template {
    spec {
      containers {
        image = "us.gcr.io/${var.gcp_project}/${var.cloud_run_container}"  
        resources {
	  limits = {
            cpu = "2000m"
	    memory = "2048Mi"
	  }
        }
      }   
      container_concurrency = 0
      request_timeout = 900
      container_port = 9999      
    }
  }
  traffic {
    percent         = 100
    latest_revision = true
  }
}
```

### References
https://www.terraform.io/docs/providers/google/r/cloud_run_service.html
https://console.cloud.google.com/run

**Comment by FallenHoot** [comment]
I just stumbled on this issue as well. To provide more context to the issue:

In Cloud Run container instances, the PORT environment variable is always set to 8080, but for portability reasons, your code should **not hardcode** this value. 
https://cloud.google.com/run/docs/reference/container-contract#port

The current way to deploy Cloud Run makes us hardcode this and is not best practice.

**Comment by remorses** [comment]
I would like to have this feature too, this change was made in the [January 7 release](https://cloud.google.com/run/docs/release-notes#January_07_2020) together with the option to deploy from a knative yaml file

**Comment by kristianmandrup** [comment]
@remorses Do you know how to customise the container port? The release notes say it is now possible, but not how. Any idea where I can find the docs for this? Thanks.

**Comment by remorses** [comment]
Someone should update the terraform provider to do so, unfortunately the provider is not updated by the google devs themselves so you just need to wait

**Comment by smootherbug** [comment]
Is there any update on this issue?

**Comment by sjortiz** [comment]
Waiting on this

**Comment by sjortiz** [comment]
any updates?

**Comment by sherifkozman** [comment]
Has there been any updates on this issue, its breaking pretty much all of our deployments on the first run or we have to accomodate to the default port 8080!

**Comment by joshuarli** [comment]
Isn't `request_timeout` possible with [`timeout_seconds`](https://www.terraform.io/docs/providers/google/r/cloud_run_service.html#timeout_seconds)?

**Comment by joshuarli** [comment]
Also reproduced the fact that adding a PORT env results in:

```
Error: Error creating Service: googleapi: Error 400: The request has errors
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "The following reserved env names were provided: PORT. These values are automatically set by the system.",
        "field": "spec.template.spec.containers[0].env"
      }
    ]
  }
]
```
