### ISSUE TITLE
Document `id` field for resources

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#5542]
In `3.0.0`, we changed Terraform's internal `id` field from formats like `{{project}}/{{region}}/{{name}}` to `projects/{{project}}/regions/{{region}}/resources/{{name}}`, a valid reference value.

Historically we've encouraged users to use `name` or `self_link` as the reference value, however these values should be preferred going forward. We've since documented the field on generated resources, but no examples or tests have been updated and neither have handwritten resources.

For this issue:

- [ ] Update every resource's documentation to include an `id` output-only attribute including the expected format (see https://github.com/GoogleCloudPlatform/magic-modules/pull/3040 downstreams for samples)
- [ ] Update every example at https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples to use `id` as the reference value if it makes sense / works
- [ ] Update every handwritten docs page following the same criteria

This should happen in small groups (~3-7 resources) so the PRs are easy to test and not overwhelming.

**Comment by danawillow** [comment]
We should also probably update our examples/tests to use it

cc @slevenick since we were talking about this for a bit earlier

**Comment by danawillow** [comment]
Riley to add more details before this goes to bug triage folks

**Comment by rileykarson** [comment]
@edwardmedia did https://github.com/GoogleCloudPlatform/magic-modules/pull/3205 fix every id, or are some remaining?

**Comment by edwardmedia** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/3478

**Comment by edwardmedia** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/3482

**Comment by edwardmedia** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/3467

**Comment by edwardmedia** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/3489

**Comment by edwardmedia** [comment]
The work are done. Some examples remain unchanged as their tests are failing.

**Comment by danawillow** [comment]
@edwardmedia do you have a list of examples that this doesn't work for? It would be worth having that so we can fix the resources in question.
