### ISSUE TITLE
Error in disk migration

### ISSUE THREAD

**Issue by aSegatto** [terraform-providers/terraform-provider-google#555]
Hi, we found an issue while migrating from terraform 9.6 to 10.7 with 1.0.1 google provider. What happens is that when we run `terraform refresh` or `terraform plan`  after` terraform init` the state isn't migrated. 

Instead this error occurs for every compute instance:

```
2017/10/09 12:35:04 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: ["disk": [REMOVED] Use boot_disk, scratch_disk, and attached_disk instead]
2017/10/09 12:35:04 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: ["disk": [REMOVED] Use boot_disk, scratch_disk, and attached_disk instead]
```

### Affected Resource(s)
- google_compute_instance

### Terraform Configuration Files
```
resource "google_compute_instance" "appserver" {
  name = "appserver"
  machine_type = "n1-standard-1"
  zone = "${var.region_zone}"
  disk {
    image = "${var.appserver_image}"
  }
  network_interface {
    network = "${var.network_name}"
    access_config = {
    }
  }
  tags = [
    "https",
    "http"]
}
```
We also tried to change disk property to 
``` 
boot_disk {
    initialize_params {
      image = "${var.appserver_image}"
    }
  }
```

but this forces new resource to be built. 
For us the most important thing is not to have to rebuild our VM's , how can we migrate to the new sintax without running into this problem ? 

Thanks !

**Comment by danawillow** [comment]
When you upgraded the state should definitely have been migrated. If you open up the state file what does it say for the schema_version for that resource?

**Comment by aSegatto** [comment]
After upgrading terraform we run `terraform init`, it correctly downloaded the google provider plugin. Then, leaving the terraform configuration file unchanged, we run both `terraform refresh` and `terraform plan`.

In both cases an error was returned

```
* google_compute_instance.appserver: "disk": [REMOVED] Use boot_disk, scratch_disk, and attached_disk instead
```

and nothing happened to the state file, it was NOT modified at all. Below is the state file

```
"google_compute_instance.appserver": {
                    "type": "google_compute_instance",
                    "depends_on": [
                        "google_compute_address.appserver_ip"
                    ],
                    "primary": {
                        "id": "appserver",
                        "attributes": {
                            "attached_disk.#": "0",
                            "can_ip_forward": "false",
                            "create_timeout": "4",
                            "disk.#": "1",
                            "disk.0.auto_delete": "true",
                            "disk.0.device_name": "",
                            "disk.0.disk": "",
                            "disk.0.disk_encryption_key_raw": "",
                            "disk.0.disk_encryption_key_sha256": "",
                            "disk.0.image": "appserver-image-1507121463",
                            "disk.0.scratch": "false",
                            "disk.0.size": "0",
                            "disk.0.type": "",
                            "id": "appserver",
                            "machine_type": "n1-standard-1",
                            "metadata.%": "0",
                            "metadata_fingerprint": "CCEZc6hvDK0=",
                            "name": "appserver",
                            "network.#": "0",
                            "network_interface.#": "1",
                            "network_interface.0.access_config.#": "1",
                            "network_interface.0.access_config.0.assigned_nat_ip": "######",
                            "network_interface.0.access_config.0.nat_ip": "######",
                            "network_interface.0.address": "######",
                            "network_interface.0.name": "nic0",
                            "network_interface.0.network": "beepmn",
                            "network_interface.0.subnetwork": "",
                            "network_interface.0.subnetwork_project": "",
                            "self_link": "https://www.googleapis.com/compute/v1/projects/######/zones/europe-west1-d/instances/appserver",
                            "service_account.#": "0",
                            "tags.#": "3",
                            "tags.1056335270": "https",
                            "tags.2541227442": "http",
                            "tags_fingerprint": "Qj2j_fZ0vTk=",
                            "zone": "europe-west1-d"
                        },
                        "meta": {
                            "schema_version": "2"
                        },
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": ""
                }
```

Are we supposed to manually change the terraform configuration file before running `refresh` or `plan`?

thanks

**Comment by danawillow** [comment]
@paddycarver can you look into this? Shouldn't `refresh` have updated the state file? The gist of this issue from my opinion is that since we removed `disk`, users can't see what `plan` would have done with the new state because they get the removed error instead. I think we just need to deal with this now since we can't really un-remove disk, but I'm definitely curious why the state file didn't get updated.

**Comment by paddycarver** [comment]
Things I'm noticing here:

* You said: 
  > We also tried to change disk property to....
  
  Which suggests to me that the config you're experiencing the error with still has a disk field, is that right?
* Your state still shows a schema version of 2, which means no migrations are getting run at all.

If I had to guess, I'd say you need to update the config before the migration will run, though I haven't confirmed that. If you can, let's try this:

1. Make a backup of your terraform.tfstate file somewhere safe.
2. Update your config to use boot_disk instead of disk.
3. Run `terraform plan`
4. Check your terraform.tfstate file. What does the `schema_version` tag say? Do you still have any `disk.` attributes?

If the answer to that last question is "no", then you're all set, and our next task is to work your config so you don't have to destroy/recreate the instance, which should be achievable. I just want to take this one problem at a time, if we can.

If the answer to that last question is "yes", please post the output of `tree .terraform` (or `ls .terraform/plugins/{OS_ARCH}` if you don't have `tree`) and we'll work through making sure the migration gets run.

**Comment by paddycarver** [comment]
Oh, also, if you're using any remote backends, definitely let us know about that, too.

**Comment by beatcracker** [comment]
I've had the same issue. Fixed it by hacking `tfstate` file manually:

1. Make backup of `tfstate` just in case. I'm using local file, don't know how it works for remote state.
2. Edit `*.tf` files and replace

```
disk = {
  image = "some/image"
}
```

with

```
boot_disk {
  initialize_params {
    image = "some/image"
  }
}
```

3. Run `terraform refresh`
4. Run `terraform plan`. Notice those two lines per each VM in the output:
```
boot_disk.0.initialize_params.#:                     "0" => "1" (forces new resource)
boot_disk.0.initialize_params.0.image:               "" => "some/image" (forces new resource)
```

5. Open `tfstate` and find for each VM:

```
"boot_disk.0.initialize_params.#": "0",
"boot_disk.0.source": "your-vm-name",
```

Replace with:

```
"boot_disk.0.initialize_params.#": "1",
"boot_disk.0.initialize_params.0.image": "some/image",
```

6. Save `tfstate` and run `terraform plan`. It should say `No changes. Infrastructure is up-to-date.`  and not try to force new resource(s).

**Comment by paddycarver** [comment]
Hey @beatcracker, thanks for sharing! I think at the moment we're just trying to establish whether the migration is running for @aSegatto, not how to fix the delete/recreate. Though that's definitely one way to do it! We're recommending people update their config file to use the suggested "source" instead of modifying the source, but (on my end, at least) that's just because modifying configuration files is safer than modifying state.

However, for the moment, let's set that problem and aside and cross that bridge when we come to it. For the moment, let's make sure the `disk` -> `boot_disk` part is happening.

**Comment by beatcracker** [comment]
> We're recommending people update their config file to use the suggested "source" instead of modifying the source

I've missed that part, where I can read about it?

> I think at the moment we're just trying to establish whether the migration is running for @aSegatto, not how to fix the delete/recreate.

Just FYI, I've got 

```
"meta": {
  "schema_version": "2"
}
```

updated to `5` after `terrafrom refresh`.

**Comment by aSegatto** [comment]
Hi , we tried to apply what you suggested. First of all we don't have a remote backend but only a local state saved in our VCS.
We run `terraform init` and downloaded version 1.1.0 of google provider. Then we changed all disk entries in our json file

```
disk {
    image = "${var.appserver_image}"
}
```

to 

```
boot_disk {
    initialize_params {
        image = "${var.appserver_image}"
    }
}
```

After running `terraform refresh` our state file was correctly migrated to

```
"meta": {
    "schema_version": "5"
}
```

We still want to avoid the problem of recreating resources, here is the output of `terraform plan`

```
-/+ google_compute_instance.appserver (new resource required)
      id:                                                  "appserver" => <computed> (forces new resource)
      boot_disk.#:                                         "1" => "1"
      boot_disk.0.auto_delete:                             "true" => "true"
      boot_disk.0.device_name:                             "persistent-disk-0" => <computed>
      boot_disk.0.disk_encryption_key_sha256:              "" => <computed>
      boot_disk.0.initialize_params.#:                     "0" => "1" (forces new resource)
      boot_disk.0.initialize_params.0.image:               "" => "appserver-image" (forces new resource)
      boot_disk.0.source:                                  "appserver" => <computed>
      can_ip_forward:                                      "false" => "false"
      cpu_platform:                                        "Intel Haswell" => <computed>
      create_timeout:                                      "4" => "4"
      instance_id:                                         "#####" => <computed>
      label_fingerprint:                                   "####=" => <computed>
      machine_type:                                        "n1-standard-1" => "n1-standard-1"
      metadata_fingerprint:                                "CCEZc6hvDK0=" => <computed>
      name:                                                "appserver" => "appserver"
      network_interface.#:                                 "1" => "1"
      network_interface.0.access_config.#:                 "1" => "1"
      network_interface.0.access_config.0.assigned_nat_ip: "####" => <computed>
      network_interface.0.access_config.0.nat_ip:          "#####" => "#####"
      network_interface.0.address:                         "#####" => <computed>
      network_interface.0.name:                            "nic0" => <computed>
      network_interface.0.network:                         "https://www.googleapis.com/compute/v1/projects/#####/global/networks/beepmn" => "beepmn"
      network_interface.0.subnetwork_project:              "vivid-union-95616" => <computed>
      scheduling.#:                                        "1" => <computed>
      self_link:                                           "https://www.googleapis.com/compute/v1/projects/####/zones/europe-west1-d/instances/appserver" => <computed>
      tags.#:                                              "3" => "3"
      tags.1056335270:                                     "https" => "https"
      tags.2541227442:                                     "http" => "http"
      tags_fingerprint:                                    "Qj2j_fZ0vTk=" => <computed>
      zone:                                                "europe-west1-d" => "europe-west1-d"
```

What next step do you suggest?

Thank you for your help  ! :smiley:

**Comment by danawillow** [comment]
If you remove the `initialize_params` block then the resource won't be recreated (don't worry, it won't remove the image or anything weird like that). Give that a try and let me know how it goes!

**Comment by aSegatto** [comment]
Ok , we did as you suggested and it worked . It would be nice not to have to remove the image name from the config file, so we will keep an eye on #592 ! 
Thanks !!! 
Alessandro
