### ISSUE TITLE
Add Placement Policy support

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#5565]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/compute/docs/reference/rest/beta/resourcePolicies/insert (`groupPlacementPolicy`)
Plus the ability to attach it to an [instance](https://cloud.google.com/compute/docs/reference/rest/beta/instances) and [instanceTemplate](https://cloud.google.com/compute/docs/reference/rest/beta/instanceTemplates)

### New or Affected Resource(s)

* google_compute_resource_policy
* google_compute_instance
* google_compute_instance_template

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* b/144708037

**Comment by slevenick** [comment]
Postponing work until update functionality becomes available on compute instance, and resource policies are preserved on instance templates (currently you can POST resource policies but they are never returned)

**Comment by slevenick** [comment]
Implementing via https://github.com/GoogleCloudPlatform/magic-modules/pull/3217 that adds support for `google_compute_instance` and adds `placement_policy` on `google_compute_resource_policy`. Will add support for templates and updating instance when it becomes available

**Comment by raddaoui** [comment]
Thanks @slevenick for this patch.
can we reopen this until we add support for google_compute_instance_template as per the description or maybe track it in another issue.

**Comment by slevenick** [comment]
Opened https://github.com/terraform-providers/terraform-provider-google/issues/5863 to track this for instance templates
