### ISSUE TITLE
`secondary_ip_range` block cannot be deleted from `google_compute_subnetwork`

### ISSUE THREAD

**Issue by dancmeyers** [terraform-providers/terraform-provider-google#5568]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.20
+ provider.google v3.6.0
+ provider.random v2.2.1

### Affected Resource(s)

* google_compute_subnetwork

### Terraform Configuration Files

Initial `main.tf`:

```tf
provider "google" {
  version = "~> 3.6.0"
}

provider "random" {
  version = "~> 2.1"
}

resource "random_id" "project" {
  byte_length = 2
}

resource "google_project" "project" {
  name = "Google Bug Test"
  project_id = "bug-test-${random_id.project.hex}"
  auto_create_network = false
}

resource "google_project_service" "services" {
  for_each = toset(["compute.googleapis.com"])
  project  = google_project.project.project_id
  service  = each.value
}

resource "google_compute_network" "vpc" {
  project = google_project.project.project_id
  name = "test-vpc"
  routing_mode = "GLOBAL"
  auto_create_subnetworks = false

  depends_on = [
    google_project_service.services
  ]
}

resource "google_compute_subnetwork" "subnet" {
  project = google_project.project.project_id
  network = google_compute_network.vpc.self_link
  name = "test-subnet"
  region = "europe-west1"
  ip_cidr_range = "10.10.0.0/16"

  secondary_ip_range {
    range_name = "test-secondary-one"
    ip_cidr_range = "10.20.0.0/16"
  }
}
```

Modified `main.tf`:

```tf
provider "google" {
  version = "~> 3.6.0"
}

provider "random" {
  version = "~> 2.1"
}

resource "random_id" "project" {
  byte_length = 2
}

resource "google_project" "project" {
  name = "Google Bug Test"
  project_id = "bug-test-${random_id.project.hex}"
  auto_create_network = false
}

resource "google_project_service" "services" {
  for_each = toset(["compute.googleapis.com"])
  project  = google_project.project.project_id
  service  = each.value
}

resource "google_compute_network" "vpc" {
  project = google_project.project.project_id
  name = "test-vpc"
  routing_mode = "GLOBAL"
  auto_create_subnetworks = false

  depends_on = [
    google_project_service.services
  ]
}

resource "google_compute_subnetwork" "subnet" {
  project = google_project.project.project_id
  network = google_compute_network.vpc.self_link
  name = "test-subnet"
  region = "europe-west1"
  ip_cidr_range = "10.10.0.0/16"
}
```

### Debug Output

https://gist.github.com/dancmeyers/6e2cf6332e2bfd8a64a29c39693df65a

### Panic Output

N/A

### Expected Behavior

The `secondary_ip_range` should be deleted from the `google_compute_subnetwork` resource.

### Actual Behavior

Terraform does not detect any changes as being necessary to the resources.

### Steps to Reproduce

1. `terraform apply` on the initial `main.tf`.
2. Delete the `secondary_ip_range` from `google_compute_subnetwork.subnet` (as per the modified `main.tf`.
3. `terraform apply` again.

### Important Factoids

In the debug output I was authenticating as a user. However I have verified this same behaviour exists when authenticating as a service account too.

### References

* Possibly related to https://github.com/terraform-providers/terraform-provider-google/issues/2570, but I know even the UI/`gcloud` doesn't support updating secondary IP ranges, only destroy/create, so I don't think it's the same issue as I am specifically trying to destroy.

**Comment by edwardmedia** [comment]
[debug.log](https://github.com/terraform-providers/terraform-provider-google/files/4156596/debug.log)

**Comment by c2thorn** [comment]
Hi! `secondary_ip_range` is a computed field meaning if it is not present in the field, terraform will default to what is returned by the API.
If you want to explicitly delete any existing `secondary_ip_ranges` you can do so by setting 
`secondary_ip_range = []`
into your config. Hope this helps.

**Comment by dancmeyers** [comment]
Hi @c2thorn, thanks for the update. I tried to simplify the problem I was actually having to the simplest version in the issue, but unfortunately I think that means the nuance has been lost. I'm not actually defining `secondary_ip_range` statically. I'm building the subnets based on configuration in a module, so the actual block looks like this:

    resource "google_compute_subnetwork" "subnet" {
      for_each = var.subnets
      project = google_project.project.project_id
      network = google_compute_network.vpc.self_link
      name = each.value.name
      region = each.value.region
      ip_cidr_range = each.value.cidr

      dynamic "secondary_ip_range" {
        iterator = range
        for_each = each.value.secondary_ips

        content {
          range_name = range.key
          ip_cidr_range = range.value
        }
      }
    }

Unfortunately this means that when the secondary IP block is an empty map I don't get any secondary IPs defined in the Terraform. I realise this is more of thing for Terraform itself rather than the Google provider, but are you aware of how I could resolve this? I tried creating a separate dynamic block that only gets triggered when there are no secondary IPs, but it won't allow me to create an empty content block/array like that...

**Comment by chrisst** [comment]
There are many fields in the GCP API's which will allow a user to specify the value in their config or the API will provide a default value if it is not specified by the user. This is a pattern that Terraform didn't anticipate would be so prevalent and as such there isn't great built in functionality for handling this well. 

We ended up marking these fields as Computed _and_ Optional, but in terraform 0.12 we lost the ability explicitly send empty results to the API. The compromise they made was to allow us to manually mark individual fields as [attributes as block](https://www.terraform.io/docs/configuration/attr-as-blocks.html). It's effectively a legacy shim that allowed us to preserve the behavior of sending explicitly empty lists on optional/computed fields. Since 0.12 doesn't natively support this behavior it's probably worth filing a Terraform request with your use case so they are aware of the ways people are using these defaulting blocks.

Unfortunately I don't have a great work around off the top of my head, but you could try asking in the terraform community forums to see if anybody has some HCL tricks that could help.
