### ISSUE TITLE
Bogus use_ip_aliases state reported on upgrade to v3.7.0

### ISSUE THREAD

**Issue by akilman** [terraform-providers/terraform-provider-google#5586]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
$ terraform -v
Terraform v0.12.20
+ provider.google v3.7.0
+ provider.kubernetes v1.10.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* `google_container_cluster`

### Terraform Configuration Files

```tf
resource "google_container_cluster" "clever-cluster-name" {
    name = "${var.application_instance_name}-cluster"
    depends_on = [google_project_service.kubernetes]

    remove_default_node_pool = true
    initial_node_count = 1

    ip_allocation_policy {
    }

    network = google_compute_network.clever-vpc.self_link
}
```

### Debug Output

https://gist.github.com/akilman/f06c0d2a00f86ae2aeac0f3e37f34023

### Expected Behavior

GCP reports `useIpAliases == true` in the UI after upgrade to v3.7.0 of the Google provider and `terraform apply`. Terraform should reflect the same correct state.

### Actual Behavior

`terraform show | grep ip_allocation_policy -A 8` details `use_ip_aliases == false`

### Steps to Reproduce

1. `terraform apply` w/ v2.5.0 Google Provider with 
```tf   
    ip_allocation_policy {
        use_ip_aliases = true
    }
``` 
2. Upgrade to 3.7.0 provider, following the [upgrade guide](https://registry.terraform.io/providers/hashicorp/google/3.5.0/docs/guides/version_3_upgrade#resource-google_container_cluster) which instructs to remove `use_ip_aliases = true` as `true` is the default with the presence of the `ip_allocation_policy`
3. `terraform apply` with newly upgraded Provider + updated config
4. Observe `use_ip_aliases` has changed to `false` in Terraform. However, in GCP `useIpAliases` is still set to `true`. Can be confirmed via:
```bash
$ gcloud container clusters describe clever-cluster | grep useIpAliases
``` 

### References

* #5154

**Comment by akilman** [comment]
For good measure, attempted to spin up a fresh cluster to see if it was just a state reporting issue on upgrade. But, was able to reproduce the same behavior on a newly provisioned environment. 

`terraform show` reports `use_ip_aliases = false`, and GCP's UI reports VPC native (Alias IP) attribute of the cluster is set to `true` 🤷‍♂

**Comment by edwardmedia** [comment]
@c2thorn after tf init, I see this in the plan
```
      + ip_allocation_policy {
          + cluster_ipv4_cidr_block       = (known after apply)
          + cluster_secondary_range_name  = (known after apply)
          + create_subnetwork             = (known after apply)
          + node_ipv4_cidr_block          = (known after apply)
          + services_ipv4_cidr_block      = (known after apply)
          + services_secondary_range_name = (known after apply)
          + subnetwork_name               = (known after apply)
          + use_ip_aliases                = (known after apply)
        }
```
after `tf apply` I see this in the `show` (it is **false**)
```
    ip_allocation_policy {
        cluster_ipv4_cidr_block       = "10.4.0.0/14"
        cluster_secondary_range_name  = "gke-name-cluster-pods-432f38af"
        create_subnetwork             = false
        services_ipv4_cidr_block      = "10.0.0.0/20"
        services_secondary_range_name = "gke-name-cluster-services-432f38af"
        use_ip_aliases                = false
    }
```
In the meantime, GCP UI show 
```
VPC-native (alias IP)	Enabled
```

**Comment by c2thorn** [comment]
`use_ip_aliases` is a removed field since v3.0.0, so ideally it would not appear in state at all. Filed an [issue](https://github.com/hashicorp/terraform-plugin-sdk/issues/320) with the Terraform SDK, but in the meantime I'll add a workaround for this field.
