### ISSUE TITLE
import google_firestore_index skips important attributes

### ISSUE THREAD

**Issue by filipzyzniewski-fexco** [terraform-providers/terraform-provider-google#5588]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
terraform-firestore-index-import $ terraform -v
Terraform v0.12.20
+ provider.google v3.7.0
terraform-firestore-index-import $ 
```

### Affected Resource(s)

* google_firestore_index

### Terraform Configuration Files

```tf
provider "google" {
  version = ">= 3.7.0"
}

terraform {
  required_version = ">= 0.12.20"
}

resource "google_firestore_index" "someindex" {
  project    = "someproject"
  collection = "somecollection"

  fields {
      field_path   = "permissions"
      array_config = "CONTAINS"
  }

  fields {
      field_path = "canonicalTime"
      order      = "DESCENDING"
  }

  fields {
      field_path = "__name__"
      order      = "DESCENDING"
  }
}
```

### Debug Output

terraform import: https://gist.github.com/filipzyzniewski-fexco/1ef4b69786823491ed9df484f7530a37
subsequent terraform plan: https://gist.github.com/filipzyzniewski-fexco/b9e215ab40187cc5fc764799a18f5ccf

### Expected Behavior

importing a google_firestore_index should set its collection and database attributes based on the components of its attribute name:

 
 projects/someproject/databases/(default)/collectionGroups/somecollection/indexes/CICAgPi_lZUK => database = "(default)", collection = "somecollection"

terraform plan should report no changes after importing the example index.

### Actual Behavior

As shown in https://gist.github.com/filipzyzniewski-fexco/b9e215ab40187cc5fc764799a18f5ccf

### Steps to Reproduce

1. `terraform import 'google_firestore_index.someindex' 'projects/someproject/databases/(default)/collectionGroups/somecollection/indexes/CICAgPi_lZUK'`
2. `terraform plan`

### Important Factoids

A Python script that I use to fix the state after importing: https://gist.github.com/filipzyzniewski-fexco/eca5e3ad86793a9de33ab73ab6e22f14

After using the script: https://gist.github.com/filipzyzniewski-fexco/06d46ab91b766a0f5d10c7ae77c95627

* #0000

**Comment by edwardmedia** [comment]
@c2thorn After import, I see null for both fields `collection` and `database`
```
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "collection": null,
            "database": null,
            "fields": [
              {
                "array_config": "CONTAINS",
                "field_path": "permissions",
                "order": ""
              },
              {
                "array_config": "",
                "field_path": "canonicalTime",
                "order": "DESCENDING"
              },
              {
                "array_config": "",
                "field_path": "__name__",
                "order": "DESCENDING"
              }
            ],
            "id": "projects/myproject-1/databases/(default)/collectionGroups/somecollection/indexes/CICAgOjXh4EK",
            "name": "projects/myproject-1/databases/(default)/collectionGroups/somecollection/indexes/CICAgOjXh4EK",
            "project": "myproject-1",
            "query_scope": "COLLECTION",
            "timeouts": {
              "create": null,
              "delete": null
            }
          },
          "private": "eyJlMmJmYjczMC1lY2FhLTExZTYtOGY4OC0zNDM2M2JjN2M0YzAiOnsiY3JlYXRlIjo2MDAwMDAwMDAwMDAsImRlbGV0ZSI6NjAwMDAwMDAwMDAwfSwic2NoZW1hX3ZlcnNpb24iOiIwIn0="
        }
      ]
```
But I do see something in both fields in `tf show` on original state
```
resource "google_firestore_index" "someindex" {
  collection  = "somecollection"
  database    = "(default)"
  id          = "projects/myproject-1/databases/(default)/collectionGroups/somecollection/indexes/CICAgOjXh4EK"
  name        = "projects/myproject-1/databases/(default)/collectionGroups/somecollection/indexes/CICAgOjXh4EK"
  project     = "myproject-1"
  query_scope = "COLLECTION"

  fields {
      array_config = "CONTAINS"
      field_path   = "permissions"
  }
  fields {
      field_path = "canonicalTime"
      order      = "DESCENDING"
  }
  fields {
      field_path = "__name__"
      order      = "DESCENDING"
  }
}
```
