### ISSUE TITLE
Support a "job_id" field for google_dataflow_job

### ISSUE THREAD

**Issue by jcanseco** [terraform-providers/terraform-provider-google#5596]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Dataflow Jobs are uniquely identified by their job ID instead of their name. My request is to expose the job ID as a computed field, `job_id`.

It seems that the Terraform provider is already retrieving the job ID and setting it as the Terraform resource ID as seen [here](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_dataflow_job.go#L194-L198), so exposing it as a computed field should hopefully be reasonably doable.

Furthermore, there is precedence in using a computed identifier as the Terraform resource ID _and_ exposed as a computed field, as seen with the `name` field of `google_firestore_index` [here](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_firestore_index.go#L188-L196).

### New or Affected Resource(s)

* google_dataflow_job

**Comment by jeet-parekh** [comment]
Can I try to work on this?

**Comment by danawillow** [comment]
Sure! Putting @jeet-parekh as the assignee. Since this is the same value that we already set in the id field, this should be pretty straightforward, but let me know if you have questions.

**Comment by jcanseco** [comment]
Thank you for taking the initiative @jeet-parekh!
