### ISSUE TITLE
expr block does not work in google_compute_security_policy

### ISSUE THREAD

**Issue by sanmmishra** [terraform-providers/terraform-provider-google#5597]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform -v
Terraform v0.12.16

### Affected Resource(s)

google_compute_security_policy

### Terraform Configuration Files

```tf
resource "google_compute_security_policy" "policy" {
  name = lower(join("-", list(var.org, var.tnt_code, var.purpose)))
  project = var.project_id
  description = var.description
  dynamic "rule" {
    for_each = [ for s in var.rules : {
        action = s.action
        priority = s.priority
        description = s.description
        match = s.match
    }]
      content {
        action = rule.value.action
        priority             = rule.value.priority
        description          = rule.value.description
        dynamic "match" {
             for_each = contains(keys(rule.value), "match") ? [rule.value.match] : []
             content {
                 dynamic "expr" {
                    for_each = contains(keys(match.value), "expr") ? [match.value.expr] : [] 
                    content {
                        expression = expr.value.expression
                        }
                     }                 
                 versioned_expr = lookup(match.value, "versioned_expr", null)
                 dynamic "config" {
                    for_each = contains(keys(match.value), "config") ? [match.value.config] : [] 
                    content {
                        src_ip_ranges = config.value.src_ip_ranges
                        }
                     }
                          
                }
        }
    }
  }
```

### Actual Behavior

When I run terraform apply, it causes problems on the expr block. Can you confirm if[ this issue](https://github.com/terraform-providers/terraform-provider-google/issues/4994) was resolved?
  on ../modules/armor/main.tf line 35, in resource "google_compute_security_policy" "policy":
  35:                  dynamic "expr" {

Blocks of type "expr" are not expected here.
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sanmmishra** [comment]
@danawillow Please let me know what you think.

**Comment by sanmmishra** [comment]
actually i noted that it is only in google beta. i think that was the problem. we can either close this bug or just move to GA?  any timelines?

**Comment by edwardmedia** [comment]
@sanmmishra can you post what var.rules did you provide? Thanks

**Comment by sanmmishra** [comment]
rules = [
    {
    name = "rule1"
    action   = "deny(403)"
    priority = "1000"
    match = {
            versioned_expr = "SRC_IPS_V1"
            config = {
                src_ip_ranges = ["9.9.9.0/24"]
            }
        }
    description = "Deny access to IPs in 9.9.9.0/24"
    },
    {
    name = "rule2"
    action   = "deny(403)"
    priority = "100"
    match = {
            expr = {
                expression: "evaluatePreconfiguredExpr('xss-canary')"
            }
        }
    description = "Custom expression"
    }
    ]

**Comment by edwardmedia** [comment]
@sanmmishra I have seen the same as what you got. It is in beta only and we don't have the date to release to GA yet. I am closing this issue. Please reopen it if you want a further discussion. Thanks

**Comment by danawillow** [comment]
Looks like it was added to the GA provider in https://github.com/GoogleCloudPlatform/magic-modules/pull/3028, so it'll be available there in our next release (Mondayish)
