### ISSUE TITLE
Add resourcePolicies support

### ISSUE THREAD

**Issue by mgaidia** [terraform-providers/terraform-provider-google#5625]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This is the only way to automatically configure a snapshot schedule on disks created by google_compute_instance_template:

https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates/insert
(resourcePolicies)
"Resource policies applied to this disk for automatic snapshot creations. Specified using the full or partial URL. For instance template, specify only the resource policy name."

### New or Affected Resource(s)

- google_compute_instance_template

**Comment by raddaoui** [comment]
I will be working on this because it's a priority for us right now.

**Comment by slevenick** [comment]
Looks like this is similar enough to https://github.com/terraform-providers/terraform-provider-google/issues/5565 for me to call it a duplicate.

Fixing #5565 will require adding the resourcePolicies field to instance and instance_template.

@raddaoui I have already started on this, so I would recommend holding off on any work on this feature
