### ISSUE TITLE
Handle id's in test sweeper template

### ISSUE THREAD

**Issue by c2thorn** [terraform-providers/terraform-provider-google#5629]
Breaking up remainder of https://github.com/terraform-providers/terraform-provider-google/issues/3288

**Comment by rileykarson** [comment]
The `identity` field and how we create import ids are a good place to start with this.

**Comment by danawillow** [comment]
@c2thorn can you add more details about what this entails?

**Comment by c2thorn** [comment]
The sweeper template naively uses `name` to construct the delete URL. A minority of the generated resources use `id` in the delete URL, so the template needs to be updated to capture those cases correctly.
