### ISSUE TITLE
Stateful Managed Instance Groups

### ISSUE THREAD

**Issue by marko7460** [terraform-providers/terraform-provider-google#5635]
Is there are plan to add a resource for stateful managed instance groups as described in https://cloud.google.com/compute/docs/instance-groups/stateful-migs?

**Comment by edwardmedia** [comment]
@marko7460 like other issue you filed, we don't have timeline to implement this yet. Can you tell us your use cases why you need this?

**Comment by edwardmedia** [comment]
@marko7460 do you mind file an enhancement (using template) with business needs so the team can prioritize it. In the meantime, I am closing this issue. Thank you
