### ISSUE TITLE
Creating instances in managed instance group with predefined names

### ISSUE THREAD

**Issue by marko7460** [terraform-providers/terraform-provider-google#5636]
Is there a way to create instances in the managed instance group as described in this API?
```
POST https://compute.googleapis.com/compute/v1/projects/project-id/zones/zone/instanceGroupManagers/instance-group-name/createInstances
{
  "instances": [
    {
      "name": "instance-name-1"
    },
    {
      "name": "instance-name-2"
    }
  ]
}
```

**Comment by edwardmedia** [comment]
@marko7460 have you had a chance to check out
https://www.terraform.io/docs/providers/google/r/compute_instance_group_manager.html? Does it help you?

**Comment by marko7460** [comment]
@edwardmedia allows me to set `base_instance_name` to which a random 4 character string is appended. I would like to control the names myself like in this example: 
```bash
gcloud compute instance-groups managed create-instance instance-group-name \
    --instance managed-instance-name \
    [--region region | --zone zone]
```
Source: https://cloud.google.com/compute/docs/instance-groups/working-with-managed-instances#adding_instances_with_specific_names

**Comment by edwardmedia** [comment]
@marko7460 does this module for you? https://github.com/terraform-google-modules/terraform-google-vm/blob/master/examples/mig/simple/main.tf

**Comment by marko7460** [comment]
@edwardmedia It doesn't . It will still create an instance with random string  (https://github.com/terraform-google-modules/terraform-google-vm/blob/master/modules/mig/main.tf#L38) which is different behavior from the above mentioned command. 

I don't think that the following flow can be done with the current resources:
```bash
$ gcloud compute instance-groups managed create my-test-group --template stateful-instances-template --size 3 --region us-central1 --instance-redistribution-type NONE
$ gcloud compute instance-groups managed create-instance my-test-group --instance my-instance-name --region us-central1
$ gcloud compute instance-groups managed list-instances my-test-group --region us-central1
NAME                ZONE           STATUS   HEALTH_STATE  ACTION  INSTANCE_TEMPLATE            VERSION_NAME  LAST_ERROR
my-test-group-1zfj  us-central1-b  RUNNING                NONE    stateful-instances-template
my-instance-name    us-central1-c  RUNNING                NONE    stateful-instances-template <----instance created with my chosen name
my-test-group-djtf  us-central1-c  RUNNING                NONE    stateful-instances-template
my-test-group-dsmv  us-central1-f  RUNNING                NONE    stateful-instances-template

**Comment by edwardmedia** [comment]
@marko7460 yeah we don't have existing implementation that supports that. Can you explain in what use cases you need to specify the full names by yourself?

**Comment by marko7460** [comment]
One use case would be creating a cluster of mongo instances where we want to name instances mongo1, mongo2, mongo3. In that case my mongo config can deduce the DNS names right from the hostname and i can also set mongo1 to be a Primary for example.

I think that having an ability to specify my own hostname fits use case of stateful managed instance groups. Stateful MIGs can keep the name and the disk in case the instance goes down.

See https://cloud.google.com/compute/docs/instance-groups/stateful-migs for more details.

**Comment by edwardmedia** [comment]
@marko7460 do you mind file an enhancement (using template) so the team can prioritize it. In the meantime, I am closing this issue. Thank you
