### ISSUE TITLE
google_bigquery_table : optional field range is required

### ISSUE THREAD

**Issue by ndechandon** [terraform-providers/terraform-provider-google#5645]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform:0.12.7
```
provider "google" {
  region  = "europe-west1"
  version = "3.7.0"
}
```
### Affected Resource(s)
* google_bigquery_table

### Terraform Configuration Files

```tf
resource "google_bigquery_table" "table" {
  dataset_id = google_bigquery_dataset.xxx.dataset_id
  table_id = "sheet"
  project = var.project
  schema = file("${path.module}/schemas/sheet.json")

  external_data_configuration {
    autodetect = true
    source_format = "GOOGLE_SHEETS"
    ignore_unknown_values = true

    google_sheets_options {
      skip_leading_rows = 1
    }

    source_uris = [
      "https://drive.google.com/open?id=xxxx",
    ]
  }
}
```

### Panic Output
```
Error: "external_data_configuration.0.google_sheets_options.0.range": one of 
`external_data_configuration.0.google_sheets_options.0.range` must be specified

on folder/file.tf line 1, in resource "google_bigquery_table" "sheet":
   1: resource "google_bigquery_table" "sheet" {
```
### Expected Behavior
Range field should not be required in the config. 

### Actual Behavior
Range is required 

### Important Factoids
I think this PR https://github.com/GoogleCloudPlatform/magic-modules/pull/2608 brought an incorrect input control. 

Because the AtLeastOneOf condition is expecting only one field for Range and skip_leading_rows:

https://github.com/hashicorp/magic-modules/blob/master/third_party/terraform/resources/resource_bigquery_table.go.erb#L166-L177

**Comment by edwardmedia** [comment]
@chrisst below error occurs on the resource example as well  https://www.terraform.io/docs/providers/google/r/bigquery_table.html
```
Error: "external_data_configuration.0.google_sheets_options.0.range": one of `external_data_configuration.0.google_sheets_options.0.range` must be specified

  on main.tf line 44, in resource "google_bigquery_table" "sheet":
  44: resource "google_bigquery_table" "sheet" {
```
