### ISSUE TITLE
Cannot create an instance with replica

### ISSUE THREAD

**Issue by gabsn** [terraform-providers/terraform-provider-google#5656]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.20

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "app" {
  project          = var.project_id
  name             = var.app_db_name
  database_version = "POSTGRES_9_6"
  region           = "europe-west1"

  master_instance_name = "app-master"
  replica_configuration {
    username = "readonly"
    password = "toto"
  }

  settings {
    tier = "db-custom-2-7680"
  }
}
```

### Debug Output

[Link](https://gist.github.com/gabsn/50efcfbc4dc86f024af1923771329d0f) to the debug output.

### Expected Behavior

It should have created the resource properly. Indeed I'm using a service account with the roles `Owner` and `Cloud SQL Admin` to apply those changes.

### Actual Behavior

It crashes:
```sh
Error: Error, failed to create instance app-db: googleapi: Error 403: The client is not authorized to make this request., notAuthorized
```

### Steps to Reproduce

1. `terraform apply`

**Comment by gabsn** [comment]
Here is the payload that is posted to the cloud sql API:
```json
{
 "databaseVersion": "POSTGRES_9_6",
 "masterInstanceName": "app-master",
 "name": "app-db",
 "region": "europe-west1",
 "replicaConfiguration": {
  "mysqlReplicaConfiguration": {
   "password": "toto",
   "username": "readonly"
  }
 },
 "settings": {
  "pricingPlan": "PER_USE",
  "replicationType": "SYNCHRONOUS",
  "storageAutoResize": true,
  "tier": "db-custom-2-7680"
 }
}
```

I'm not sure if it's the problem or not but the replication field is prefixed with `mysql` whereas I want to create a postgres instance.

**Comment by edwardmedia** [comment]
@gabsn have you had the `app-master` instance in place? To make replica work, you have to have the master instance. Can you try something like below config? Let me know if this help address your issue. Thanks
```
resource "google_sql_database_instance" "master" {
  name             = "app-master1"
  database_version = "POSTGRES_9_6"
  region           = "us-central1"
  settings {
    tier = "db-f1-micro"
    backup_configuration {
        #binary_log_enabled = true
        enabled = true
    }
  }

}

resource "google_sql_database_instance" "replica" {
  name             = "replica1"
  database_version = "POSTGRES_9_6"
  region           = "us-central1"

  settings {
    tier = "db-f1-micro"
  }

  master_instance_name = "app-master1"
  replica_configuration {
    username = "readonly"
    password = "toto"
  }
}
```

**Comment by gabsn** [comment]
Thanks, I finally got it to work. See this minimal config:

```tf

resource "google_sql_database_instance" "main" {
  name             = "main"
  database_version = "POSTGRES_9_6"

  settings {
    tier = "db-f1-micro"

    backup_configuration {
      enabled = true
    }
  }
}

resource "google_sql_database_instance" "replica" {
  name             = "replica"
  database_version = "POSTGRES_9_6"

  master_instance_name = google_sql_database_instance.main.name

  replica_configuration {
    connect_retry_interval = "30"
    failover_target        = "false"
  }

  settings {
    tier = "db-f1-micro"
  }
}
```

The problem is that [terraform doc](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html) says to have `binary_log_enabled`
![image](https://user-images.githubusercontent.com/18901085/74424555-74acfc00-4e52-11ea-85a9-bdac96ad2e5e.png).

But this is only true for `mysql`. As you can see in [Cloud SQL postgres doc](https://cloud.google.com/sql/docs/postgres/replication/tips), it is not a requirement whereas it is for mysql.

Anyway, I think that the error is too cryptic and confusing. So I hope my working example will help people looking to add a working read replica to their postgres Cloud SQL!
