### ISSUE TITLE
BigQuery external tables should be able to be defined using HivePartitioningOptions

### ISSUE THREAD

**Issue by preston-hf** [terraform-providers/terraform-provider-google#5664]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

[Hive partitioning on external tables](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#hivepartitioningoptions) is now supported (in beta) and it would be awesome if Terraform supported creating tables that use it.

### New or Affected Resource(s)

* google_bigquery_table

### Potential Terraform Configuration

```tf
resource "google_bigquery_table" "hive" {
  dataset_id = google_bigquery_dataset.default.dataset_id
  table_id   = "hive"

  external_data_configuration {
    autodetect    = true
    
    hive_partition_options {
      mode = "AUTO"
      source_uri_prefix = "gs://mybucket/foo"

      requirePartitionFilter = false
    }
  }
}
```

### References

**Comment by preston-hf** [comment]
Is this something that Google is working on internally, or would you accept a pull request for it?

**Comment by preston-hf** [comment]
This is now GA. Is this something you'd accept a contribution for? Need this ASAP :)

**Comment by danawillow** [comment]
Always happy to look at PRs! Take a look at our contributing guide at https://github.com/terraform-providers/terraform-provider-google/blob/master/.github/CONTRIBUTING.md

**Comment by matteosdocsity** [comment]
are there any updates? is there a way to start using it?
