### ISSUE TITLE
Creating a google_service_account results in an incorrect Google Cloud creation REST URI

### ISSUE THREAD

**Issue by ringods** [terraform-providers/terraform-provider-google#5682]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.20
+ provider.google v3.8.0

### Affected Resource(s)

* google_service_account

### Terraform Configuration Files

```tf
resource "google_project" "my_project" {
  name       = "Test Project"
  project_id = "tftest-my-project-id"
}

resource "google_service_account" "service_account" {
  account_id   = "tftestserviceaccountid"
  display_name = "Terraform Test Service Account"
  project = google_project.my_project.id
}
```

### Debug Output

https://gist.github.com/ringods/a9cd1659389ce32689c5c541e0b550bd

### Expected Behavior

The service account should be correctly created.

### Actual Behavior

I get a 404 error because the generated URL is incorrect.

```
2020/02/14 11:39:00 [DEBUG] google_service_account.service_account: applying the planned Create change
2020-02-14T11:39:00.061+0100 [DEBUG] plugin.terraform-provider-google_v3.8.0_x5: 2020/02/14 11:39:00 [DEBUG] Google API Request Details:
2020-02-14T11:39:00.061+0100 [DEBUG] plugin.terraform-provider-google_v3.8.0_x5: ---[ REQUEST ]---------------------------------------
2020-02-14T11:39:00.061+0100 [DEBUG] plugin.terraform-provider-google_v3.8.0_x5: POST /v1/projects/projects/tftest-my-project-id/serviceAccounts?alt=json&prettyPrint=false HTTP/1.1
```

The URL contains the word `projects` twice.

The references below point both to the provider code calling into the Google Cloud SDK with a parameter name of `projects/{projectId}` which seems to comply with the requirements described in the JSON description. However, somewhere along the execution path, the word `projects` is added a second time in the creation of the resulting URI.

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/googleapis/google-api-go-client/issues/212
* TF provider calling the SDK: https://github.com/terraform-providers/terraform-provider-google/blob/e7b9c03f9e8e072624aa1d3960da572b9a125f35/google/resource_google_service_account.go#L80
* JSON description for serviceAccounts creation name parameter: https://github.com/googleapis/google-api-go-client/blob/7f2cf9d6ec65884391850645915bc3752fc61db2/iam/v1/iam-api.json#L586-L592

**Comment by Fryuni** [comment]
Just tried and its working with this configs:

Terraform v0.12.19
- provider.google v3.7.0

**Comment by ringods** [comment]
In my example above, I am passing `myproject.id` as the project ID to the service account. The value of `id` is `projects/tftest-my-project-id`. If I change my example to pass `myproject.project_id`, then it works!

`myproject.id` = `projects/tftest-my-project-id`
`myproject.project_id` = `tftest-my-project-id`
