### ISSUE TITLE
CAA record support

### ISSUE THREAD

**Issue by mrusme** [terraform-providers/terraform-provider-google#5692]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I'm trying to create a CAA record using `google_dns_record_set`, however it doesn't seem to support it. The records I'm trying to add are:

```
your_domain. CAA 0 issue "letsencrypt.org"
your_domain. CAA 0 issue "pki.goog"
```

### New or Affected Resource(s)

* google 3.4.0
* google-beta 3.4.0

### Potential Terraform Configuration

```tf
resource "google_dns_record_set" "example_caa_issue" {
        provider = google-beta

        name         = "example.domain."
        type         = "CAA"
        ttl          = 300
        managed_zone = google_dns_managed_zone.example_zone.name
        rrdatas      = ["0 issue \"letsencrypt.org\""]
}
```

### References

* #0000

**Comment by venkykuberan** [comment]
@mrusme following sample config creates DNS zone and recordset of type `CAA`. 
```
resource "google_dns_managed_zone" "managed_zone" {
#   provider    = google-beta
  name        = "test-dns-managedzone"
  description = "Example DNS managed zone"
  project     = var.project_id
  dns_name    = "example.domain."
}

resource "google_dns_record_set" "caa_issue" {
#   name = google_dns_managed_zone.managed_zone.dns_name
  name         = "example.domain."
  type = "CAA"
  ttl  = 300
  managed_zone = google_dns_managed_zone.managed_zone.name
  rrdatas = ["0 issue \"letsencrypt.org\"", "0 issue \"pki.goog\""]
}
```
Please let me know how it works for you.

**Comment by mrusme** [comment]
@venkykuberan thank you, this seems to have done the trick!
