### ISSUE TITLE
Feature Request: gcloud services identity create 

### ISSUE THREAD

**Issue by dhrapson** [terraform-providers/terraform-provider-google#5694]
### Description

Please add support for the `gcloud services indentity create` command. This is a pre-requisite for using CMEK with CloudSQL as described in the 'Creating a service account' section of https://cloud.google.com/sql/docs/mysql/configure-cmek 

The Terraform provider recently [added support for configuring CMEK with CloudSQL](https://github.com/terraform-providers/terraform-provider-google-beta/commit/826b1c376cb948d91f12f055295a32bff89ff1a2), however the creation of this service identity via gcloud prior to running Terraform would still be necessary.

NB. That link still describes the feature usage as 'alpha', however it is currently in beta.

### New or Affected Resource(s)

Something like:

* google_service_identity

### Potential Terraform Configuration

```tf

resource "google_service_identity" "my_sa_id" {
  project = "my_project_id"
  service = "sqladmin.googleapis.com"
}

```

### References

None

**Comment by edwardmedia** [comment]
@dhrapson could you please file an enhancement for this request so we can prioritize it into the backlog? I am closing this issue. You can reopen it if you want to have a further discussion.

**Comment by danawillow** [comment]
This looks like an enhancement request to me, just that the "please do not remove this line" message got removed so it didn't get auto-labeled. However, it looks like an additional issue was filed at https://github.com/terraform-providers/terraform-provider-google/issues/5697, so I'll go ahead and re-close this and we can use the other as the canonical version.
