### ISSUE TITLE
Add support for 'gcloud services identity create'

### ISSUE THREAD

**Issue by dhrapson** [terraform-providers/terraform-provider-google#5697]
### Community Note

Please vote on this issue by adding a +1 reaction to the original issue to help the community and maintainers prioritize this request.
Please do not leave +1 or me too comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.
If an issue is assigned to the modular-magician user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to hashibot, a community member has claimed the issue already.

### Description

Please add support for the `gcloud services indentity create` command. This is a pre-requisite for using CMEK with CloudSQL as described in the 'Creating a service account' section of https://cloud.google.com/sql/docs/mysql/configure-cmek 

The Terraform provider recently [added support for configuring CMEK with CloudSQL](https://github.com/terraform-providers/terraform-provider-google-beta/commit/826b1c376cb948d91f12f055295a32bff89ff1a2), however the creation of this service identity via gcloud prior to running Terraform would still be necessary.

NB. That link still describes the feature usage as 'alpha', however it is currently in beta.

### New or Affected Resource(s)

Something like:

* google_service_identity

### Potential Terraform Configuration

```tf

resource "google_service_identity" "my_sa_id" {
  project = "my_project_id"
  service = "sqladmin.googleapis.com"
}

```

### References

GCP docs: https://cloud.google.com/sql/docs/mysql/configure-cmek 
Related commit: https://github.com/terraform-providers/terraform-provider-google-beta/commit/826b1c376cb948d91f12f055295a32bff89ff1a2

**Comment by ndmckinley** [comment]
Hi there,

I implemented that support for Cloud SQL CMEK, and I'm disappointed that it does require that once-per-project setup.  Unfortunately, at the moment, the docs are accurate - 
> Currently, you can only use gcloud command-line tool commands to create the type of service account you need for customer-managed encryption keys.

We would love to implement this in Terraform, but gcloud setup is quite complicated and shelling out to it in a provider is a nonstarter.  As a workaround, you might consider ensuring that gcloud is set up correctly on the machine from which you are running terraform, and using

```hcl
resource "null_resource" "cluster" {
  provisioner "local-exec" {
    inline = [
      "gcloud services identity create",
    ]
  }
}
```

along with the service account datasource to get a script that works for you.

I'm sorry that this is necessary - we would like it to be made possible for REST clients like Terraform to do this, and we will prioritize it when it becomes possible.

**Comment by rileykarson** [comment]
I believe this is https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_service_identity?
