### ISSUE TITLE
AppEngine Configuring Handlers not working / needs example

### ISSUE THREAD

**Issue by TheWolfNL** [terraform-providers/terraform-provider-google#5716]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.20
+ provider.archive v1.3.0
+ provider.google v3.9.0
+ provider.google-beta v2.20.2
+ provider.null v2.1.2
+ provider.random v2.2.1

### Affected Resource(s)

* google_app_engine_standard_app_version

### Terraform Configuration Files

```tf
resource "google_app_engine_standard_app_version" "map" {
  for_each = (local.enable_boilerplate ? { boilerplate = "boilerplate" } : {})

  project    = local.gcp_project_id
  service    = "default"
  runtime    = "php73"
  version_id = "boilerplate"
  threadsafe = true

  env_variables = local.env_variables

  entrypoint {
    shell = "serve index.php"
  }

  deployment {
    zip {
      source_url = var.source_url
    }
  }

  handlers {
    url_regex = "/static"
    static_files {
      path = "static"
      upload_path_regex = ".*"
    }
  }

  handlers {
    url_regex = "/.*"
  }
}
```
`local.enable_boilerplate` is a simple boolean to toggle this version to be created
`local.gcp_project_id` is assigned with the ID of a project resource,
`local.env_variables` can just be an empty map
`var.source_url` is a url to a GCS hosted zip archive.

### Expected Behavior

I was expecting the apply to succeed and configuring the handlers for both the static files and the default route.

### Actual Behavior

Apply failed throwing:
> googleapi: Error 400: Unrecognized handler type 'HANDLERTYPE_NOT_SET'.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000 https://www.terraform.io/docs/providers/google/r/app_engine_standard_app_version.html#handlers

**Comment by edwardmedia** [comment]
@TheWolfNL your 2nd handlers does not have one of the `**type**` the handler expected. Here is the explanation from API document. Please let me know if this addresses your issue.
```
{
  "urlRegex": string,
  "securityLevel": enum (SecurityLevel),
  "login": enum (LoginRequirement),
  "authFailAction": enum (AuthFailAction),
  "redirectHttpResponseCode": enum (RedirectHttpResponseCode),

  // Union field handler_type can be only one of the following:
  "staticFiles": {
    object (StaticFilesHandler)
  },
  "script": {
    object (ScriptHandler)
  },
  "apiEndpoint": {
    object (ApiEndpointHandler)
  }
  // End of list of possible types for union field handler_type.
}
```
https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services.versions#scripthandler

**Comment by TheWolfNL** [comment]
Thnx @edwardmedia , This seems to work.

```
  handlers {
    url_regex                   = "/static/(.*)"
    redirect_http_response_code = "REDIRECT_HTTP_RESPONSE_CODE_301"
    security_level              = "SECURE_ALWAYS"
    static_files {
      path              = "static/\\1"
      upload_path_regex = "static/.*"
    }
  }

  handlers {
    url_regex                   = ".*"
    redirect_http_response_code = "REDIRECT_HTTP_RESPONSE_CODE_301"
    security_level              = "SECURE_ALWAYS"
    script {
      script_path = "auto"
    }
  }
```
