### ISSUE TITLE
BigQuery dataset attribute delete_contents_on_destroy cannot be added after dataset has been created

### ISSUE THREAD

**Issue by rsalmond** [terraform-providers/terraform-provider-google#5726]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
terraform version
Terraform v0.12.21
+ provider.google v3.9.0
```
### Affected Resource(s)

* google_bigquery_dataset

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "foo" {
  dataset_id  = "foo"
  location    = "US"

  #delete_contents_on_destroy = true
}
```

### Expected Behavior

BQ Dataset would be deleted.

### Actual Behavior

```
Error: Error reading Dataset: googleapi: Error 400: Dataset <project_name>:foo is still in use, resourceInUse
```

### Steps to Reproduce

Terraform apply to create a BQ dataset using the example configuration above omitting the `delete_contents_on_destroy` attribute. Re-add the attribute after the dataset has been created and attempt a terraform destroy.

### Important Factoids

I don't know enough about how terraform merges what it finds in HCL with what it finds in the state file to suggest a fix, but after adding some debug print statements to the BQ dataset resource it seems like when `resourceBigQueryDatasetDelete` is called, despite having `delete_dataset_contents_on_destroy` set to true in HCL the value of `d.delete_contents_on_destroy` is false, which matches what's in the state file.

If that is expected behavior, which would make sense, then I suspect [setting the attribute to false during creation if it has been omitted](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_big_query_dataset.go#L411) is how we get into a state where it cannot be deleted.

**Comment by edwardmedia** [comment]
@rsalmond I am not able to hit that error. Below is the result I just tested. You may noticed the attribute getting updated. If you can repro the issue. Can you post the full debug log? Thank you
```
Terraform will perform the following actions:

  # google_bigquery_dataset.foo will be updated in-place
  ~ resource "google_bigquery_dataset" "foo" {
        creation_time                   = 1582320532736
        dataset_id                      = "foo"
        default_partition_expiration_ms = 0
        default_table_expiration_ms     = 0
      ~ delete_contents_on_destroy      = false -> true
....
....
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by rsalmond** [comment]
Hey @edwardmedia thanks for the quick response. I went back to the repo where I first encountered the problem and realized there is a key detail I failed to include in my initial report.

While I tested deleting the dataset with the latest provider release, it was actually created with the v2.20.0 release. In that version, when `delete_contents_on_destroy` is omitted from the HCL the field is stored as `false` in the state. In the v3.9.0 release when that field is omitted from the HCL it is stored as `null` in the state.

**Comment by edwardmedia** [comment]
@rsalmond I have tried using two versions of the provider. In both cases, the field `delete_contents_on_destroy` were set to `false` when this field in the HCL was commented. 
I also tried by applying with v2.20.0 first and then un-commenting the line and re-applying with new version, v3.10. No error was caught. Can you post your full debug log and the state files before and after the change if you are still able to repro this issue? Thank you
 
```
2020-02-27T11:50:09.473-0800 [DEBUG] plugin.terraform-provider-google_v2.20.2_x4: 2020/02/27 11:50:09 [INFO] Instantiating Google Cloud Storage Transfer client for path https://storagetransfer.googleapis.com/
  + create

Terraform will perform the following actions:

  # google_bigquery_dataset.foo will be created
  + resource "google_bigquery_dataset" "foo" {
      + creation_time              = (known after apply)
      + dataset_id                 = "foo"
      + delete_contents_on_destroy = false
      + etag                       = (known after apply)
      + id                         = (known after apply)
```
```
2020-02-27T11:59:03.489-0800 [DEBUG] plugin.terraform-provider-google_v3.10.0_x4: plugin 

Terraform will perform the following actions:

  # google_bigquery_dataset.foo will be created
  + resource "google_bigquery_dataset" "foo" {
      + creation_time              = (known after apply)
      + dataset_id                 = "foo"
      + delete_contents_on_destroy = false
      + etag                       = (known after apply)
      + id                         = (known after apply)
      + last_modified_time         = (known after apply)
      + location                   = "US"
```

**Comment by rsalmond** [comment]
@edwardmedia after reporting I just edited my statefiles so I could get on with my tasks. Spent some time fiddling with old and new version combinations I am unable to reliably reproduce this. 

Thanks for sanity checking, I guess it is safe to close this!

**Comment by edwardmedia** [comment]
@rsalmond you are welcome. I am closing the issue now.
