### ISSUE TITLE
 Error creating SecretVersion (beta)

### ISSUE THREAD

**Issue by glasnt** [terraform-providers/terraform-provider-google#5730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.21
provider.google-beta v3.9.0

### Affected Resource(s)

google_secret_manager_secret_version

### Terraform Configuration Files

```
resource google_secret_manager_secret dummy {
  provider = google-beta
  project  = "XXXXX"

  secret_id   = "dummy"
  replication {
    automatic = true
  }
}

resource google_secret_manager_secret_version dummy {
  provider = google-beta

  secret = google_secret_manager_secret.dummy.secret_id
  secret_data = "value"
}
```
(This is nearly verbatim from the docs https://www.terraform.io/docs/providers/google/r/secret_manager_secret_version.html)

### Debug Output

https://gist.github.com/glasnt/6df786bcc1ccf90080aa7e8afce9410b

### Expected Behavior

The secret value would be created.

### Actual Behavior

`Error: Error creating SecretVersion: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>`

### Steps to Reproduce

```
terraform init
terraform apply
```

### Important Factoids

I know this is a resource of the beta provider, but that repo doesn't have an open issue tracker.

**Comment by edwardmedia** [comment]
@glasnt can you try to use `id` instead of `secret_id` in below line? Let me know if this address your issue. Thanks
```
secret = google_secret_manager_secret.dummy.id
```

**Comment by glasnt** [comment]
@edwardmedia Oh, that worked. 

I think I see where I got confused: 

In google_secret_manager_secret_version it takes a `secret` based on the `id` of the google_secret_manager_secret

But you define a google_secret_manager_secret with a [secret_id](https://www.terraform.io/docs/providers/google/r/secret_manager_secret.html#secret_id)

I'm *guessing* what I've done is use the user-provided identifier rather than the generated id (which I guess would be the full resource identifier) (both are valid properties of the resource) and the value being passed as is to the API fails. 

My bad. If my assumptions are right and this user error, feel free to close.

**Comment by edwardmedia** [comment]
@glasnt I am glad this works for you. I am closing the issue right now. Thanks again for using the tools
