### ISSUE TITLE
Support ingressSettings for google_cloudfunctions_function

### ISSUE THREAD

**Issue by filip-sc** [terraform-providers/terraform-provider-google#5740]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please provide a field to set [ingressSettings](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#IngressSettings) of a cloud function. Currently there is no way as far as I can see, to allow only internal traffic to the cloud function via terraform. Default is to allow all traffic. Which isn't to much of a problem as one might set google_cloudfunctions_function_iam_member anyway. However, the cloud function will be exposed which I would like to prevent.   

### New or Affected Resource(s)

* google_cloudfunctions_function

### Potential Terraform Configuration

```tf
data "google_cloudfunctions_function" "my-function" {
  name = "function"
  ingress_settings="ALLOW_INTERNAL_ONLY"
}
```

### References

* https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#IngressSettings
* https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#CloudFunction

**Comment by filip-sc** [comment]
I can give it a shot? Only question is if this should be handled in magic modules or if its fine if I create a PR here.

**Comment by danawillow** [comment]
Go for it! I'll assign the issue to you.

Since this is a handwritten resource + data source, you're welcome to do it in either location, but it's easier for your reviewer if you do it against magic modules. https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/resources/resource_cloudfunctions_function.go is the location of the resource code, tests/docs/data source code are all also in the third_party/terraform directory.
