### ISSUE TITLE
Add `tfgen` prefix to Spanner sweeper

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#5746]
Spanner automatically generates a shortname like `tfgen-spanid-20200212140837281` when `name` isn't provided for an instance. We use this a few times in our tests, and we've leaked a handful of instances. We should add this prefix to our sweepers.

**Comment by emilymye** [comment]
We could also use this prefix for names that don't support dashes (not a lot of them, but some)
