### ISSUE TITLE
google_bigtable_app_profile resource should support long form 'id' for big_table instance reference

### ISSUE THREAD

**Issue by venkykuberan** [terraform-providers/terraform-provider-google#5751]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)
- google_bigtable_instance
- google_bigtable_app_profile

### Terraform Configuration Files

google_bigtable_app_profile resource takes only short form of instance name, it should accept both the formats. Using long format throws 404 error.
 
 - {{instance-name}}
 -  projects/{{project}}/instances/{{instance-name}}

Potential Terraform Config
```tf
resource "google_bigtable_instance" "bgtable-instance" {
#   provider      = google-beta
  name          = "tf-instance"
  instance_type = "PRODUCTION"
  cluster {
    cluster_id   = "tf-instance-cluster"
    zone         = "us-central1-b"
    storage_type = "HDD"
    num_nodes = 3
  }
}

resource "google_bigtable_app_profile" "ap" {
  instance       = google_bigtable_instance.bgtable-instance.id
  app_profile_id = "bt-profile"
  multi_cluster_routing_use_any = true
  ignore_warnings               = true
  depends_on = [google_bigtable_instance.bgtable-instance]
} 

```

### Actual Behavior

 <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v2/projects/xxxx/instances/projects/xxxx/instances/tf-instance/appProfiles?alt=json&amp;appProfileId=bt-profile</code> was not found on this server.  <ins>That’s all we know.</ins>

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by emilymye** [comment]
A workaround would be to use `google_bigtable_instance.bgtable-instance.name` instead of `.id` - is there a specific reason you want to use the ID? Right now this is only a field we use to construct the URL, hence the 404
