### ISSUE TITLE
Adding a Bigtable column family to an existing table forces replacement

### ISSUE THREAD

**Issue by chetaldrich** [terraform-providers/terraform-provider-google#5759]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.20
+ provider.aws v2.49.0
+ provider.google v3.8.0
+ provider.google-beta v3.8.0
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Affected Resource(s)

* google_bigtable_table

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change

resource "google_bigtable_table" "some_table" {
  name          = "stuff"
  instance_name = google_bigtable_instance.some_bigtable.name
  project       = google_project.project.project_id
  column_family {
    family = "family1"
  }
  column_family {
    family = "family2"
  }
}

# * the version of the config after the change.

resource "google_bigtable_table" "some_table" {
  name          = "stuff"
  instance_name = google_bigtable_instance.some_bigtable.name
  project       = google_project.project.project_id
  column_family {
    family = "family1"
  }
  column_family {
    family = "family2"
  }
  column_family {
    family = "family3"
  }
}

```

### Plan Output

```
  # module.some_project.google_bigtable_table.stuff must be replaced
-/+ resource "google_bigtable_table" "some_table" {
      ~ id            = "projects/some-google-project/instances/some-bigtable/tables/stuff" -> (known after apply)
        instance_name = "some-bigtable"
        name          = "stuff"
        project       = "some-google-project"

        column_family {
            family = "family1"
        }
        column_family {
            family = "family2"
        }
      + column_family { # forces replacement
          + family = "family3"
        }
    }
```

### Expected Behavior

The plan would indicate that we're creating a new column family and not replacing the table.

### Actual Behavior

The plan indicates that we're forcing replacement of the whole table when adding a column family. `cbt` is capable of doing this, so Google likely has an API that doesn't force replacement when adding a new column family. 

### Steps to Reproduce

1.  Change the configuration to include a new column family on an existing Bigtable table. 
2. `terraform plan`

**Comment by venkykuberan** [comment]
@chetaldrich I am able to repro the behavior (and cbt adds the column family without deleting the table). Looking at the code we are forcenewing for `cloumn_family` attribute in our provider, we shouldn't be doing that . I will move this item for code change, it will be added to our sprint work once prioritized.

**Comment by emilymye** [comment]
This requires a custom update using the https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances.tables/modifyColumnFamilies API endpoint
