### ISSUE TITLE
google_compute_network resource does not honor delete_default_routes_on_create flag

### ISSUE THREAD

**Issue by Reifier** [terraform-providers/terraform-provider-google#5777]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.21
+ provider.google v3.10.0
+ provider.google-beta v3.9.0
+ provider.kubernetes v1.10.0
+ provider.random v2.2.1
+ provider.tls v2.1.1
```

### Affected Resource(s)
google_compute_network

* google_XXXXX

### Terraform Configuration Files

https://drive.google.com/open?id=1ZaUIvcktY0d388iFPpDYvzUeD_zeUReI

### Debug Output
https://gist.github.com/Reifier/9c9428bfc640c81ff089a69a193c2669

### Expected Behavior
Default subnet routes get deleted on final stages of vpc creation.

### Actual Behavior
The subnets still exist even with the `delete_default_routes_on_create ` set to true.

### Steps to Reproduce
Run provided terraform scripts with apply. When the scripts finishes vpc setup go to the project page, select VPC, observe default networks present.

1. `terraform apply`

### Important Factoids
Nothing original. Mostly taken from here: https://github.com/sethvargo/vault-on-gke

### References

* #0000

**Comment by edwardmedia** [comment]
@Reifier  from the log you provided, I noted that provider did send the `delete` request to api and received `DONE` response from API. Can you double check if the default route still exist? 
```
---[ REQUEST ]---------------------------------------
DELETE /compute/v1/projects/vault-8c1cdccc66b6e942/global/routes/default-route-eaa9a29daa6685c5?alt=json&prettyPrint=false HTTP/1.1
Host: www.googleapis.com
User-Agent: google-api-go-client/0.5 HashiCorp Terraform/0.12.21 (+https://www.terraform.io) Terraform Plugin SDK/1.4.0 terraform-provider-google/3.10.0
X-Goog-Api-Client: gl-go/1.13.7 gdcl/20200203
Accept-Encoding: gzip



---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Wed, 26 Feb 2020 22:37:31 GMT
Etag: 7cT_sBmSwQD3rRGD5PN40o9-3Ns=/ihpevny8nHqsKLNkvFCOPjwDufs=
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
 "id": "8337532680576650699",
 "name": "operation-1582756644245-59f823f8bce8c-42f58dd5-4cfc06a1",
 "operationType": "delete",
 "targetLink": "https://www.googleapis.com/compute/v1/projects/vault-8c1cdccc66b6e942/global/routes/default-route-eaa9a29daa6685c5",
 "targetId": "4876853032248888816",
 "status": "DONE",
 "user": "alex.pinchuk@peek.com",
 "progress": 100,
 "insertTime": "2020-02-26T14:37:24.630-08:00",
 "startTime": "2020-02-26T14:37:24.646-08:00",
 "endTime": "2020-02-26T14:37:28.145-08:00",
 "selfLink": "https://www.googleapis.com/compute/v1/projects/vault-8c1cdccc66b6e942/global/operations/operation-1582756644245-59f823f8bce8c-42f58dd5-4cfc06a1",
 "kind": "compute#operation"
}
```

**Comment by Reifier** [comment]
Yes. I can still see the routes being in place after full terraform run cycle.

**Comment by edwardmedia** [comment]
@Reifier  the doc says 
```
delete_default_routes_on_create - (Optional) If set to true, default routes (0.0.0.0/0) will be deleted immediately after network creation. Defaults to false.
```
Do you see below 
![default-route](https://user-images.githubusercontent.com/42220489/75402570-0c323600-58ba-11ea-86d8-0921777160f2.png)

**Comment by Reifier** [comment]
My apologies, I am dumb.
