### ISSUE TITLE
`google_compute_attached_disk` doesn't recognize `google_compute_instance` replacement

### ISSUE THREAD

**Issue by jnearing-kabam** [terraform-providers/terraform-provider-google#5788]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.21

### Affected Resource(s)

* `google_compute_attached_disk`
* `google_compute_instance`

### Expected Behavior
Consider the following state: 
`google_compute_instance.instance`
`google_compute_disk.disk`
`google_compute_attached_disk.attach-disk`
`google_compute_resource_policy.snapshot-policy`
`google_compute_disk_resource_policy_attachment.attach-snapshot-policy`

_NOTE:  I expect that only instance and disk/attach-disk are necessary to repro, but I am presenting the full state for this resource just in case_

In the event of: 
`google_compute_instance.instance must be replaced`

It should trigger the event:
`google_compute_attached_disk.attach-disk must be replaced`

### Actual Behavior

The resource `google_compute_attached_disk.attach-disk` does not recognize a replaced compute instance. The instance will be recreated, but the disk will not be attached, as the `attach-disk` resource does not trigger.

When you `terraform  apply` a second time, it will trigger a `.google_compute_attached_disk.attach-disk will be created` event. 

### Steps to Reproduce

Create 
`google_compute_instance.instance`
`google_compute_disk.disk`
`google_compute_attached_disk.attach-disk`

1. `terraform apply`
1. Make a change to `google_compute_instance.instance` that forces replacement
1. `terraform plan||apply`
1. Notice `google_compute_attached_disk` does not trigger
1. Notice created instance has no disk attach
1. `terraform apply`
1. Notice once instance state is updated, `google_compute_attached_disk.attach-disk will be created`

### References

* #0000

**Comment by venkykuberan** [comment]
@jnearing-kabam It does triggered replacement for both instance and attached_disk when i forced a replacement for an instance. Can you please share your config or plan output to have an understanding what's going on ?
Alternate way to attach disk is to have `attached_block` in instance config (commented in the following config).

Also i am sharing my working config, please verify with yours
```
resource "google_compute_instance" "some_server" {
  project = var.project_id
  name    = "test-instance-${var.environment}"
  machine_type = "n1-standard-1"
  zone         = var.zone
  tags         = ["xxx-${var.environment}"]
  boot_disk {
    initialize_params {
      size  = 100
      type  = "pd-ssd"
      image = "gce-uefi-images/ubuntu-1804-lts"
    }
  }
    scratch_disk {
      interface = "SCSI"
    }
    # attached_disk {
    #   source = google_compute_disk.some_data.id
     # }
  network_interface {
    network = "default"
    access_config {
      // Ephemeral IP
    }
  }
  lifecycle {
      ignore_changes = [attached_disk]
  }
}

resource "google_compute_disk" "some_data" {
  project = var.project_id
  name    = "test-disk"
  type    = "pd-ssd"
  zone    = var.zone
  size    = 1000
  labels = {
    environment = var.environment
  }
  physical_block_size_bytes = 4096
}

resource "google_compute_attached_disk" "default" {
  disk     = google_compute_disk.some_data.id
  instance = google_compute_instance.some_server.id
}
```
Please let me know if it helps

**Comment by jnearing-kabam** [comment]
Looking at this, I have a disk module responsible for attaching disks. So my config looks something like:

```terraform
resource "google_compute_instance" "instance" {

  name         = var.instance_name
  zone         = var.zone
  machine_type = var.machine_type

  tags = local.network_tags


  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-1604-lts"
    }
  }

  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet.self_link

    access_config {
      // Ephemeral IP
    }
  }

  lifecycle {
    ignore_changes = [attached_disk]
  }

  metadata = {
 // foo
  }

  metadata_startup_script = data.template_file.metadata_startup_script.rendered

  service_account {
    scopes = [
      // foo
    ]
    email = var.service_account_email
  }

  allow_stopping_for_update = true
}

# Create a persistent disk to attach to the instance
module "instance-disk" {
  source = "../disk"
  gcp_project = var.gcp_project
  region = var.region
  zone = var.zone
  instance_name = google_compute_instance.instance.name
  disk_labels = var.disk_labels
  disk_size_gb = var.disk_size_gb
  max_retention_days = var.max_retention_days
  disk_storage_locations = var.disk_storage_locations
}
```

Im guessing that the module doesn't recognize the change since the only dependency is on `google_compute_instance.instance.name`. I suspect that if I put a dependency on a unique identifier it would pick up the change as expected. 

Reasonable to assume this is on my end. I'll close this.
