### ISSUE TITLE
Move the provider from vendoring dependencies to gomodules

### ISSUE THREAD

**Issue by chrisst** [terraform-providers/terraform-provider-google#5789]
We are currently checking in the whole vendor folder into github and also the go.mod. The only thing keeping these in sync is a manual process. 

- [x] Ensure that magic modules can generate the correct imports once the vendor directory is removed
- [x] Change the makefiles in TPG and TPGB to remove mod=vendor references
- [x] Update the kokoro build files to remove any references to vendoring
- [x] Update the HashiCorp build process to work with go modules
- [x] Remove the vendor folder
- [x] Update the documentation that refers to the vendor process

**Comment by ndmckinley** [comment]
@megan07, have you seen #6306 and are you planning on addressing it here?  If not we can discuss next week.
