### ISSUE TITLE
Adding support for "Private service access" for Cloud MemoryStore Redis (for Shared VPC setups)

### ISSUE THREAD

**Issue by iiro** [terraform-providers/terraform-provider-google#5792]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

At the moment, the `google_redis_instance` resource does not support creating the Redis

But, as this feature was just announced, this should now be possible:

https://cloud.google.com/memorystore/docs/redis/release-notes#February_27_2020
https://cloud.google.com/memorystore/docs/redis/networking
https://cloud.google.com/memorystore/docs/redis/creating-managing-instances#creating_a_redis_instance_with_a_shared_vpc_network_in_a_service_project

### New or Affected Resource(s)

* google_redis_instance

### Potential Terraform Configuration

```tf
# No actual idea, but maybe aligning on how things happen with Cloud SQL (if applicable?): https://www.terraform.io/docs/providers/google/r/sql_database_instance.html
```

**Comment by Gatsby-Lee** [comment]
@danawillow Thank you for working on this :)

**Comment by danawillow** [comment]
This is in our Goals milestone, which means it's something we'd like to do but don't have a timeline on. You can see our full list of sprints and milestones at https://github.com/terraform-providers/terraform-provider-google/milestones, and we move things around depending on demand. We always happily accept PRs, which is the easiest way for you to control the timeline around features. Otherwise, we use a combination of thumbs ups and customer interest (reported internally to us via TAMs, CEs, and similar roles at Google/HashiCorp) to determine which things get moved from Goals -> Near Term, and from there into a sprint.

**Comment by iiro** [comment]
@danawillow since I've created the issue, I've received some mixed messages from my peers at Google. They said things should already work without any additions, which sounded like the issue actually would not be valid. @danawillow were they right, or is there pending work to be done to the provider on this?

**Comment by iiro** [comment]
And @danawillow thank you for the update on this :) I need to ping both peers at Google and Hashicorp if we can affect this to get more action ;) Unfortunately we're very blocked by this, cannot go live with a project at all... :/ I'd like to try to help with a PR here, but unfortunately there are legal obstacles on the way.

**Comment by Gatsby-Lee** [comment]
@iiro BTW, this is not only related to Shared VPC. connection-mode ( direct peering / private services access ) argument is not supported.

**Comment by danawillow** [comment]
Well, not sure whether it was you or a coincidence but this just popped up on our internal tracker  :)

@Gatsby-Lee yup, the only thing missing from our end right now from what I can tell is the connect-mode argument.

**Comment by Gatsby-Lee** [comment]
@danawillow Nice!!. it's PR2 now. 👍

**Comment by syl20bnr** [comment]
Thank you for working on this, this is great to have this limitation being addressed.

Will this be in the provider v2 or in v3 ?

**Comment by danawillow** [comment]
We try to make our release numbers monotonically increasing as best as possible, so it'll be in 3.X. 2.X releases are only being done in emergencies (such as an API changing out from underneath us that makes the provider unusable)

**Comment by Gatsby-Lee** [comment]
Thank you.
