### ISSUE TITLE
`Blocks of type "release_channel" are not expected here` though Terraform docs suggest otherwise

### ISSUE THREAD

**Issue by webyneter** [terraform-providers/terraform-provider-google#5794]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
Terraform v0.12.21
+ provider.google v3.10.0
+ provider.google-beta v3.10.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* `google_container_node_pool`

### Terraform Configuration Files

```tf
# ...
resource "google_container_node_pool" "cluster_nodes" {
  # https://www.terraform.io/docs/providers/google/r/container_node_pool.html
  provider   = google-beta
  name       = "${google_container_cluster.cluster.name}-nodes"
  location   = google_container_cluster.cluster.location
  cluster    = google_container_cluster.cluster.name
  node_count = 1
  node_config {
    disk_size_gb = 100
    disk_type    = "pd-standard"
    # region https://cloud.google.com/kubernetes-engine/docs/how-to/node-images
    image_type = "cos"
    # endregion
    # region https://cloud.google.com/compute/docs/machine-types
    machine_type = "n1-standard-2"
    # endregion
    service_account = var.service_account
    release_channel {
      channel = local.release_channel
    }
    oauth_scopes = [
      # TODO not sure if we need these given the current service_account
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]
  }
}
# ...
```

### Debug Output

It fails before I could run `terraform apply`, on `terraform validate` instead: https://gist.github.com/webyneter/15485e0cbf2fc05f87db9d7df25d1375

### Expected Behavior

`terraform validate` is supposed to exit normally.

### Actual Behavior

`terraform validate` yields the aforementioned error.

### Steps to Reproduce

1. `terraform init`
1. `terraform validate`

### Important Factoids

Authenticating with a manually pre-created service account with unrestricted access to all resources.

### References

* https://www.terraform.io/docs/providers/google/r/container_node_pool.html#node_config
* https://www.terraform.io/docs/providers/google/r/container_cluster.html#channel

**Comment by venkykuberan** [comment]
@webyneter `release_channel` is `google_container_cluster` resource property. Looks like you are using it for node pool, it won't here.  I am closing this issue as the fix suggested will work, please reopen if you still get that error

**Comment by webyneter** [comment]
Indeed, thank you.
