### ISSUE TITLE
`An argument named "end_time" is not expected here`/`An argument named "end_time" is not expected here` though Terraform docs suggest the opposite

### ISSUE THREAD

**Issue by webyneter** [terraform-providers/terraform-provider-google#5795]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
Terraform v0.12.21
+ provider.google v3.10.0
+ provider.google-beta v3.10.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* `google_container_cluster`

### Terraform Configuration Files

```tf
# ...
locals {
  release_channel = "STABLE"
}
resource "google_container_cluster" "cluster" {
  # https://www.terraform.io/docs/providers/google/r/container_cluster.html
  provider   = google-beta
  name       = "${var.environment}-${locals.cluster_region}-cluster"
  location   = locals.cluster_region
  network    = google_compute_network.vpc.self_link
  subnetwork = google_compute_subnetwork.vpc_subnet.self_link
  ip_allocation_policy {
    cluster_secondary_range_name  = local.vpc_subnet_pods_secondary_ip_range
    services_secondary_range_name = local.vpc_subnet_services_secondary_ip_range
  }
  release_channel {
    channel = local.release_channel
  }
  maintenance_policy {
    daily_maintenance_window {
      start_time = "02:00"
      end_time   = "03:00"  # Has failed with `An argument named "end_time" is not expected here.`
      recurrence = "FREQ=WEEKLY;BYDAY=SA,SU"  # Has failed with `An argument named "recurrence" is not expected here.`
    }
  }
  # region Prerequisites for the use of google_container_node_pool
  # https://www.terraform.io/docs/providers/google/r/container_cluster.html#initial_node_count
  # https://www.terraform.io/docs/providers/google/r/container_cluster.html#remove_default_node_pool
  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  initial_node_count       = 1
  remove_default_node_pool = true
  # endregion
  master_auth {
    username = ""
    password = ""
    client_certificate_config {
      issue_client_certificate = false
    }
  }
}
# ...
```

### Debug Output

`terraform validate`: https://gist.github.com/webyneter/03b3b67a31b6bee45d2ed12e24ba033a

### Expected Behavior

`terraform validate` was supposed to exit normally.

### Actual Behavior

`terraform validate` has failed with the errors above.

### Steps to Reproduce

1. `terraform init`
1. `terraform validate`

### Important Factoids

Authenticating with a manually pre-created service account with unrestricted access to all resources.

### References

* `maintenance_policy.daily_maintenance_window`: https://www.terraform.io/docs/providers/google/r/container_cluster.html#daily_maintenance_window

> Specify start_time and end_time in RFC3339 date format. The start time's date is the initial date that the window starts, and the end time is used for calculating duration. Specify recurrence in RFC5545 RRULE format, to specify when this recurs.
> Examples: maintenance_policy { recurring_window { start_time = "2019-08-01T02:00:00Z" end_time = "2019-08-01T06:00:00Z" recurrence = "FREQ=DAILY" } }
```tf
maintenance_policy {
  recurring_window {
    start_time = "2019-01-01T09:00:00-04:00"
    end_time = "2019-01-01T17:00:00-04:00"
    recurrence = "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR"
  }
}
```

**Comment by venkykuberan** [comment]
@webyneter `end_time` is supported only inside the `recurring_window` block.  Moving the config to right block should fix the issue. Let me know if it works.

**Comment by webyneter** [comment]
@venkykuberan thanks for the lead but not that I have

```tf
maintenance_policy {
    recurring_window {
      start_time = "02:00"
      end_time   = "03:00"
      recurrence = "FREQ=WEEKLY;BYDAY=SA,SU"
    }
  }
```

it says:

```shell
Error: parsing time "02:00" as "2006-01-02T15:04:05Z07:00": cannot parse "0" as "2006"

  on main.tf line 34, in resource "google_container_cluster" "cluster":
  34: resource "google_container_cluster" "cluster" {


Error: parsing time "03:00" as "2006-01-02T15:04:05Z07:00": cannot parse "0" as "2006"

  on main.tf line 34, in resource "google_container_cluster" "cluster":
  34: resource "google_container_cluster" "cluster" {
```

Do I have to specify the timestamps with regard to a particular moment in time?

**Comment by webyneter** [comment]
Ah, my bad, that's all in the docs actually. Though I'm a little bit confused as to why I have to specify the exact timestamp even though it's gonna be a recurring thing as soon as the stack is up and running, starting whatever the moment in future after it's deployed...

**Comment by webyneter** [comment]
My understanding is that we need to specify a pivot point in future to jumpstart recurrences given the frequency, onwards.

**Comment by venkykuberan** [comment]
I don't think its expecting the exact minute/sec in the time stamp. As long as its in RFC339 date format its acceptable. Please refer the examples section in this page - https://www.ietf.org/rfc/rfc3339.txt

sample config for 2 different time zones
```
 recurring_window {
      start_time = "2019-01-01T03:00:00+00:00"
      end_time = "2019-01-01T08:00:00+00:00"

      # start_time = "2019-01-01T03:00:00+09:00" (UTC + 9 hrs)
      # end_time = "2019-01-01T08:00:00+09:00" (UTC + 9 hrs)

      recurrence = "FREQ=DAILY"
    } ```

if it works, shall i go head and close this issue ?

**Comment by webyneter** [comment]
Yes, it worked, thank you.
