### ISSUE TITLE
Add the ability to Create a Composer Environment on a Shared VPC

### ISSUE THREAD

**Issue by DanielWozniak** [terraform-providers/terraform-provider-google#5815]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I currently have a composer environment running that was spun up with terraform. At the time of creation there was no need for it to be a private IP one and therefore it was created with public IPs. Now we are trying to remove public IPs wherever they are not required and while trying to create a private IP composer environment on a shared vpc I got an error saying `Private IP Composer Environment does not support Shared VPC`. However, from what I could tell it looks like this is [available](https://cloud.google.com/composer/docs/how-to/managing/creating#beta_features).

 I noticed [this](https://github.com/terraform-providers/terraform-provider-google/issues/5422) issue where the above mentioned error was asked about but kinda of got looked over due to a different question. In this issue it says to create a new issue if the option to create a private IP composer environment with a shared vpc with the API is available and it looks like it is. Just under `network` -> `nodeConfig.subnetwork`. [API](https://cloud.google.com/composer/docs/reference/rest/v1beta1/projects.locations.environments#nodeconfig) 

### New or Affected Resource(s)

google_composer_environment

### Potential Terraform Configuration

No changes would need to be done from the resource config side, just allow network and subnetwork to be a part of a shared vpc.
```tf
resource "google_composer_environment" "default" {
node_config {
      network    = google_compute_network.sharedvpc_network.self_link
      subnetwork = google_compute_subnetwork.sharedvpc_subnetwork.self_link
    }
}
```

### References
* #5422

**Comment by emilymye** [comment]
Private IP Composer environments and Shared VPC are two different modes for a Composer environment. While they both use VPC-native clusters, the first specifically applies to setting up the Composer environment as private, whereas the second involves setting up the GKE cluster in a shared VPC (I believe Composer service directly sends that node config to GKE). The combination is what is not supported currently - a public issue tracker exists for supporting them together https://b.corp.google.com/issues/134608300

**Comment by DanielWozniak** [comment]
Thanks for the response. Unfortunately it won't be possible for us to create the Composer environment in the vpc host project but appreciate the suggestion. I heard from google that the feature is supposed to be available some time in March. So I will have to wait for that and hopefully it doesn't get pushed back. However, I would want to possibly keep this open so that when the feature does get put in it could also get added to the google provider. Or if you prefer we could close this and just open a new issue when the feature does get put in.

**Comment by DanielWozniak** [comment]
@emilymye, looks like the feature has finally been put into starting composer-1.9.2.
[Release Notes](https://cloud.google.com/composer/docs/release-notes)

**Comment by kosxe** [comment]
will ability to use shared VPC be coming to this terraform module anytime soon?

**Comment by danawillow** [comment]
Looks like the dependent bug was marked fixed, and according to https://cloud.google.com/composer/docs/how-to/managing/configuring-shared-vpc there aren't any API changes that were made as part of this. Is this still not working for anyone? If so, could you please provide debug logs (env variable TF_LOG=DEBUG) that show an API request/response that did not successfully work?

**Comment by ConstantineAbayeu** [comment]
we are still having some issues with this:
Error: googleapi: Error 400: Found 1 problem:
	1) Network and subnetwork must belong to the same project., badRequest

**Comment by danawillow** [comment]
@ConstantineAbayeu mind sharing the config that you used as well as debug logs that show it not working (running terraform with the env var TF_LOG=DEBUG)?

**Comment by ConstantineAbayeu** [comment]
`Terraform v0.12.20
Initializing plugins and modules...
2020/04/08 17:15:44 [DEBUG] Using modified User-Agent: Terraform/0.12.20 TFE/v202001-4

google_composer_environment.TEAM-composer-prod: Creating...

Error: googleapi: Error 400: Found 1 problem:
	1) Network and subnetwork must belong to the same project., badRequest

  on ipt-composer.tf line 1, in resource    "google_composer_environment" "TEAM-composer-prod":
   1: resource "google_composer_environment" "TEAM-composer-prod"
`

thinking about this, do I need to switch to a newer Terraform version?

**Comment by danawillow** [comment]
The information I'm looking for in the debug logs are specifically the full requests/responses that get sent to GCP. That looks like the regular output from running Terraform.

That output also doesn't say which provider version you're using, so I can't say whether an upgrade would help or not.

**Comment by ConstantineAbayeu** [comment]
[run-x7dodfAkqtas6sE5-apply-log.txt](https://github.com/terraform-providers/terraform-provider-google/files/4452467/run-x7dodfAkqtas6sE5-apply-log.txt)

Attached is the full debug log from terraform for that run ( i have reducted our company name from it)

as a side note, deploying it via gcloud command works just fine with that same shared VPC works fine. it is just trying to use the terraform module when it fails like that.

**Comment by danawillow** [comment]
Cool, so looking at those logs it's showing that Terraform is trying to use a network from the same project as the composer environment, but a subnetwork from a different project. I assume you're looking to have it use a network in a different project- how are you setting the two fields in your config? My guess is that network is just getting set to a network name, rather than the full path of the network that includes the project as well.

**Comment by ConstantineAbayeu** [comment]
`resource "google_composer_environment" "REDUCTED-composer-prod" {

    name = "REDUCTED-composer-prod"
    region = var.region
    config {
        node_count = 3
        node_config {
            zone = "us-central1-a"
            machine_type = "n1-standard-1"
            network = "projects/ccnetwork-prd-dc3570/regions/us-central1/networks/REDUCTED-composer"
            subnetwork = "projects/ccnetwork-prd-dc3570/regions/us-central1/subnetworks/gcp-REDUCTED-composer-prod-us-central1-net01"
            service_account = google_service_account.cloud-composer-sa.name
            ip_allocation_policy {
                use_ip_aliases = "true"
                cluster_secondary_range_name = "gcp-REDUCTED-composer-prod-us-central1-net01-ipt-pods"
                services_secondary_range_name = "gcp-REDUCTED-composer-prod-us-central1-net01-ipt-svcs"
            }
        }
        private_environment_config {
            enable_private_endpoint = "true"
        }
    }    
    depends_on = [google_project_iam_member.composer-worker]
}
`


this is how I am specifying that in my terraform file

**Comment by danawillow** [comment]
Ah, I see the issue: networks are global, so that link is incorrect. You want `projects/OTHER_PROJECT-prd-dc3570/global/networks/REDUCTED-composer`

You could also use something like the `data.google_compute_network` data source (https://www.terraform.io/docs/providers/google/d/datasource_compute_network.html) to avoid hard-coding the link of the network.

**Comment by ConstantineAbayeu** [comment]
awesome! this seems to have worked. at least it is attempting to spin up the composer! thank you for all your help!

**Comment by danawillow** [comment]
Great! Going to go ahead and close this out then, but feel free to comment back if it doesn't work.
