### ISSUE TITLE
Terraform apply showing one GCP project (correct one) in actions and using a different project (the default project) while creating..

### ISSUE THREAD

**Issue by vivalaks** [terraform-providers/terraform-provider-google#5816]
### Community Note

Block of related configuration
resource "google_storage_bucket" "text-store" {
  name     = "${module.new_project.project_id_out}-10xcc-gcf-ocr-texts"
  location = "EU"
  project = module.new_project.project_id_out
  force_destroy = true
}

**resource "google_pubsub_topic" "topic_gcf_ocr_results" {
  name     = "${module.new_project.project_id_out}-topic_gcf_ocr_results"
  project = module.new_project.project_id_out
}**

**Terraform apply output**

Lakshmanas-MacBook-Air:dev laks$ terraform apply
module.new_project.random_id.id: Refreshing state... [id=YU1CGw]
module.new_project.google_project.project: Refreshing state... [id=projects/ai-apis-pocs-dev614d421b]
module.new_project.google_project_service.service["vision.googleapis.com"]: Refreshing state... [id=ai-apis-pocs-dev614d421b/vision.googleapis.com]
module.new_project.google_project_service.service["compute.googleapis.com"]: Refreshing state... [id=ai-apis-pocs-dev614d421b/compute.googleapis.com]
module.new_project.google_project_service.service["pubsub.googleapis.com"]: Refreshing state... [id=ai-apis-pocs-dev614d421b/pubsub.googleapis.com]
module.new_project.google_project_service.service["cloudfunctions.googleapis.com"]: Refreshing state... [id=ai-apis-pocs-dev614d421b/cloudfunctions.googleapis.com]
module.new_project.google_project_service.service["translate.googleapis.com"]: Refreshing state... [id=ai-apis-pocs-dev614d421b/translate.googleapis.com]
module.new_project.google_project_service.service["storage-component.googleapis.com"]: Refreshing state... [id=ai-apis-pocs-dev614d421b/storage-component.googleapis.com]
google_storage_bucket.image-store: Refreshing state... [id=ai-apis-pocs-dev614d421b-10xcc-gcf-ocr-images]
google_storage_bucket.text-store: Refreshing state... [id=ai-apis-pocs-dev614d421b-10xcc-gcf-ocr-texts]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_pubsub_topic.topic_gcf_ocr_results will be created
  + resource "google_pubsub_topic" "topic_gcf_ocr_results" {
      + id      = (known after apply)
      + name    = "ai-apis-pocs-dev614d421b-topic_gcf_ocr_results"
      **+ project = "ai-apis-pocs-dev614d421b"**

      + message_storage_policy {
          + allowed_persistence_regions = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_pubsub_topic.topic_gcf_ocr_results: Creating...

Error: Error creating Topic: googleapi: Error 40

3: Cloud Pub/Sub API has not been used in project 481178746626 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/pubsub.googleapis.com/overview?**project=481178746626** then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

  on main.tf line 36, in resource "google_pubsub_topic" "topic_gcf_ocr_results":
  36: resource "google_pubsub_topic" "topic_gcf_ocr_results" {

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@vivalaks  from the error, it appears you have not enabled `pubsub` service yet. You need to do that before you can proceed. Follow the link you can enable it first. Also your config is not clear. In order for me to help investigate the issue, probably you might want to post the entire config along with the full debug log. Please let me know if I can help further.

**Comment by vivalaks** [comment]
Thanks Edward. 

The _pubsub_ service is enabled in the project (id = ai-apis-pocs-dev614d421b) where I am trying to create a new topic. But the pubsub service is not enabled in the Provider Google default project (id = tenxcc-terraform-admin-host, number = 481178746626). Does Terraform use the default project configuration for API services (enabled or not enabled) to create a resource in another project. Does it not use this project's configuration where the pubsub topic needs to be created?

Full TF Config file
------------------
variable "billing_account" {}
variable "org_id" {}
variable "project_name" {}
variable "parent_folder_id" {}
variable "region" {}

provider "google" {
  region = "us-central1"
}

module "new_project" {
  source  = "/Users/laks/python-git-basics/terraform_basics/modules/project"

  billing_account = var.billing_account
  org_id = var.org_id

  project_name = var.project_name
  parent_folder_id = var.parent_folder_id
  region = var.region
}

resource "google_storage_bucket" "image-store" {
  name     = "${module.new_project.project_id_out}-10xcc-gcf-ocr-images"
  location = "EU"
  project = module.new_project.project_id_out
  force_destroy = true
}

resource "google_storage_bucket" "text-store" {
  name     = "${module.new_project.project_id_out}-10xcc-gcf-ocr-texts"
  location = "EU"
  project = module.new_project.project_id_out
  force_destroy = true
}

resource "google_pubsub_topic" "topic_gcf_ocr_results" {
  name     = "${module.new_project.project_id_out}-topic_gcf_ocr_results"
  project = module.new_project.project_id_out
}

output "project_id" {
    value = "${module.new_project.project_id_out}"
}

**Comment by edwardmedia** [comment]
@vivalaks I don't know what you have in the module ` "/Users/laks/python-git-basics/terraform_basics/modules/project"`. If you can post the entire code, we can try to investigate. To answer your question, you may want to try hard-coded the project first and see how it behave.

**Comment by edwardmedia** [comment]
@vivalaks for your project 481178746626, if you don't need any pubsub related resources, you don't need to enable pubsub service in that project. Please go back to check if that is the right project and if there are no pubsub related resources. Because you have provided project for each resource, terraform will create the resource in the specified project, no matter where you run the terraform. But you have to give the terraform runner account the right permission to the right services on individual project.  At this point, I don't see an issue in the provider so I am closing this issue. Please feel free to reopen it if you still need assistance
