### ISSUE TITLE
google_compute_instance keeps computing network_interface attributes.

### ISSUE THREAD

**Issue by anas-aso** [terraform-providers/terraform-provider-google#582]
### Terraform Version
v0.10.6

### Affected Resource(s)
- google_compute_instance

### Terraform Configuration Files
```hcl
resource "google_compute_instance" "instance" {
  name         = "server"
  machine_type = "sometype"
  zone         = "somezone"

  boot_disk {
    auto_delete = true
    initialize_params {
      image = "some_image"
      size  = "100"
    }
  }

  network_interface {
    network = "default"
    access_config {
         nat_ip = "A.B.C.D"
    }
  }
}
```

### Expected Behavior
After upgrading the plugin to 1.1.0, `terraform plan` showed this changes:
```
  ~ google_compute_instance.instance
      network_interface.#:                                 "1" => "1"
      network_interface.0.access_config.#:                 "1" => "1"
      network_interface.0.access_config.0.assigned_nat_ip: "A.B.C.D" => <computed>
      network_interface.0.access_config.0.nat_ip:          "A.B.C.D" => "A.B.C.D"
      network_interface.0.address:                         "a.b.c.d" => <computed>
      network_interface.0.name:                            "nic0" => <computed>
      network_interface.0.network:                         "https://www.googleapis.com/compute/v1/projects/MY_GCP_PROJECT/global/networks/default" => "default"
      network_interface.0.subnetwork_project:              "MY_GCP_PROJECT" => <computed>
```
Run `terraform apply` to apply "pending" changes (due to provider plugin upgrade).

### Actual Behavior
But even after `terraform apply`, `terraform plan` keeps showing the same changes over and over.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan` => will shows the output posted in `Expected Behavior`
2. `terraform apply`
3. `terraform plan` => will shows the same output as on step 1.

### References
- https://github.com/terraform-providers/terraform-provider-google/pull/536

**Comment by rosbo** [comment]
Hi Anas,

I am trying to reproduce this with the following Terraform config but I don't get a perpetual diff like you are describing:

```hcl
resource "google_compute_address" "default" {
  name = "test-address"
}

resource "google_compute_instance" "instance" {
  name         = "server"
  machine_type = "g1-small"
  zone         = "us-central1-b"

  boot_disk {
    auto_delete = true
    initialize_params {
      image = "debian-cloud/debian-8"
    }
  }

  network_interface {
    network = "default"
    access_config {
        nat_ip = "${google_compute_address.default.address}"
    }
  }
}
```

Can you post the full diff for `google_compute_instance.instance`, in the diff you posted there is no fields with changes. 

Thank you

**Comment by anas-aso** [comment]
@rosbo thanks for checking. The diff I posted is the whole diff.
Next to the computed attributes, I can only see line which will be changed 
```
      network_interface.0.network:                         "https://www.googleapis.com/compute/v1/projects/MY_GCP_PROJECT/global/networks/default" => "default"
```
I would like to mention that this issue happens with instance created before. Not sure if it affects newly created ones as well.

**Comment by anas-aso** [comment]
@rosbo I changed my terraform code to use the full URI of the network instead of just its name, and I don't see any pending changes. I am not sure on which version of terraform this was changed as the same code was working fine.

**Comment by rosbo** [comment]
Hum...

The `network_interface.0.network` field has a DiffSuppressFunc that suppress the diff if when the self_link refers to the same network by name...

**Comment by rosbo** [comment]
Also, the network field is ForceNew which means it forces the creation of a new resources if it is changed. That also means that the diff output includes a special mention for this like below if there is a diff for that field:

```sh
network_interface.0.network:                         "https://www.googleapis.com/compute/v1/projects/MY_GCP_PROJECT/global/networks/default" => "default2" (forces new resource)
```

**Comment by anas-aso** [comment]
@rosbo weird! well I wouldn't waste my time on it, I will keep the changes I did for terraform files. Thanks for checking. I will close this issue.
