### ISSUE TITLE
Issue with google_compute_instance->scheduling->node_affinities->operator

### ISSUE THREAD

**Issue by jsfrerot** [terraform-providers/terraform-provider-google#5823]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.21

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "master" {
...
  scheduling {
    node_affinities {
      key = var.cluster_name
      operator = "NOT"
      values = [var.cluster_name]
    }
  }
...
}
```

### Expected Behavior

Accept gcp api values (IN and NOT)

### Actual Behavior
When using "NOT"
```Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.scheduling.nodeAffinities[0].operator': 'OPERATOR_UNSPECIFIED'. Unknown operator value., invalid

  on .terraform/modules/gce_mariadb_lunashared_dsm_sand/main.tf line 1, in resource "google_compute_instance" "master":
   1: resource "google_compute_instance" "master" {
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Module should comply with https://cloud.google.com/compute/docs/nodes/create-nodes

* #0000

**Comment by edwardmedia** [comment]
@jsfrerot you don't have other code which makes a little hard to investigate. Could you please post complete code along with the full debug log? Thanks

**Comment by jsfrerot** [comment]
Here is the debug output: https://gist.github.com/jsfrerot/08611cac298c5128151ceb05efa8e793
And here is the code: https://gist.github.com/jsfrerot/5df3c070ec120ad5f34e6f23cfd5bfc8

**Comment by edwardmedia** [comment]
@jsfrerot can you replace `ǸOT` by `NOT_IN`. Here is the reference from API
https://cloud.google.com/compute/docs/reference/rest/v1/instances/setScheduling.
Let me know if this helps address your issue. In the meantime, I change the issue form `bug` to `document`

**Comment by jsfrerot** [comment]
I'm getting the following error with "NOT_IN"
Error: expected scheduling.0.node_affinities.0.operator to be one of [IN NOT], got NOT_IN

  on .terraform/modules/gce_mariadb_lunashared_dsm_sand/main.tf line 6, in resource "google_compute_instance" "master":
   6: resource "google_compute_instance" "master" {

**Comment by edwardmedia** [comment]
@jsfrerot yeah this is a bug in the validation. I am going to reset it to `bug`. Thank you for reporting it. We will get it fixed as soon as we can. 
```
			"operator": {
				Type:         schema.TypeString,
				Required:     true,
				ForceNew:     true,
				ValidateFunc: validation.StringInSlice([]string{"IN", "NOT"}, false),
			},
```
https://github.com/terraform-providers/terraform-provider-google/blob/master/google/compute_instance_helpers.go#L13:6
