### ISSUE TITLE
`google_sql_database_instance`, `google_container_cluster` through `google_compute_network` why are not able to see each other?

### ISSUE THREAD

**Issue by DarioBernardo** [terraform-providers/terraform-provider-google#5824]
Hi, please help. Lot's of frustration going on.
I am trying to create an infrastructure where a kubernetes cluster and a sql database are able to communicate in a VPC. My code is [here](https://github.com/DarioBernardo/cloud-infrastructure).
A pod in my k8s cluster is trying to ping the database (see yaml) but nothing happens. (I also try to ping by manually exec into the pod). I have runned out of things to try. 
What am I missing?

**Comment by edwardmedia** [comment]
@DarioBernardo it looks like you need to add more pieces. Here are some docs that might help to set it up. 
https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine
https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/master/cloudsql

**Comment by DarioBernardo** [comment]
@edwardmedia Thank you for the answer. The second link you provided, the wordpress example, uses a proxysql sidecar. I thought that the point of having a VPC and a private IP address was to bypass the sidecar and connect directly through the private IP. I think the documentation in your first link mention this too. Is this the piece you think I am missing or something else? furthermore, why in my configuration I am not able to even ping my sql instance? Thank you

**Comment by edwardmedia** [comment]
@DarioBernardo you probably can find multiple different ways to connect Cloud sql from k8s clusters. Sidecar is one way. This repo is specific for `terraform-provider-google` and probably is not the best resources for you to seek advice for the solutions. In term of the `ping`, you might want to check your firewalls settings. I am going to close this issue. Please feel free to reopen it if you have more the `provider` issues and questions, etc.
