### ISSUE TITLE
allow_stopping_for_updates should not restrict changes when the instance is stopped.

### ISSUE THREAD

**Issue by davegalos** [terraform-providers/terraform-provider-google#5828]
provider.google v2.17.0
Terraform v0.12.13

Right now the code simply aborts if allow_stopping_for_updates=false and if certain fields are being modified. If the instance is stopped; however these there is no need to abort, these fields can be updated with no special confirmation. A flag to bring up the stopped instance in this situation would be useful as well.

**Comment by edwardmedia** [comment]
@davegalos do you mind if you can open an enhancement instead? Please use the template and state your suggestions and business needs. I am closing this issue right now. In that way we can prioritize each item in the backlog. Thank you

**Comment by rileykarson** [comment]
Hey @davegalos! This is actually supported as-of https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#3110-march-02-2020. It isn't stated explicitly, but https://github.com/terraform-providers/terraform-provider-google/pull/4797 added the behaviour.

Prior to that change, Terraform assumed that instances were always in the RUNNING state, so stopped instances weren't handled as well as they could be.
