### ISSUE TITLE
Equivalent of gcloud compute instances create-with-container

### ISSUE THREAD

**Issue by JSANL** [terraform-providers/terraform-provider-google#5832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I am trying to create an VM in Google Compute Engine which automatically runs a container that I uploaded to the Google Container Registry (as described here https://cloud.google.com/compute/docs/containers/deploying-containers#how_deploying_containers_on_works)

The
```
gcloud compute instances create-with-container [INSTANCE_NAME] \
     --container-image [DOCKER_IMAGE]
```
command works so far, but I dont see any equivalent in Terraform.
From what I've seen google_compute_image is not what helps me.

### New or Affected Resource(s)

* google_compute_instance

**Comment by ndmckinley** [comment]
No problem, that's very doable in Terraform, but like you've said, there is no direct equivalent.  The reason for that is that GCP does not support it through the API:

> You can only use this feature through the Google Cloud Console or the gcloud command-line tool, not the API.

One way to do it would be to use `metadata_startup_script` in `google_compute_instance` - simply select the Container Optimized OS image of your choice from [this section](https://cloud.google.com/container-optimized-os/docs/how-to/create-configure-instance#creating_an_instance) and configure that in the `image` parameter.  Then, write a startup script following [these instructions](https://cloud.google.com/container-optimized-os/docs/how-to/create-configure-instance#running_startup_scripts) (or, if you are an advanced user of COS, [these instructions](https://cloud.google.com/container-optimized-os/docs/how-to/create-configure-instance#using_cloud-init).  It's possible that `docker run $IMAGE` is a sufficient startup script for you, depending on how your docker image is configured.

If that doesn't work for you, please comment again and I'll see what I can do!
