### ISSUE TITLE
Allowing host_ruleS and path_matcherS in google_compute_url_map

### ISSUE THREAD

**Issue by diodfr** [terraform-providers/terraform-provider-google#5844]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

According to the [API documentation](https://cloud.google.com/compute/docs/reference/rest/v1/urlMaps) it now possible to provide multiple host_rule and path_matcher.

As shown in the exemple below, I could redirect foo.bar.com to foobar backend and zoo.bar.com to zoobar backend.

Thanks for your work.

### New or Affected Resource(s)

* google_compute_url_map

### Potential Terraform Configuration

```tf
resource "google_compute_url_map" "url_map" {
    name = "mymap"
    project = local.gcp_project

host_rules = 
  [
    {
      hosts        = ["foo.bar.com"]
      path_matcher = "foobarpaths"
    },
    {
      hosts        = ["zoo.bar.com"]
      path_matcher = "commonpaths"
    }
  ]
  
  
path_matcher = 
  [ 
    {
      name            = "foobarpaths"
      default_service = "projects/${var.project_id}/global/backendServices/${var.foobar_backend}"
    },
    {
      name = "commonpaths"
      default_service = "projects/${var.project_id}/global/backendServices/${var.zoobar_backend}"
    }
  ]
}
```

### References

* This issue is close to this one : https://github.com/terraform-providers/terraform-provider-google/issues/3537

* API doc : https://cloud.google.com/compute/docs/reference/rest/v1/urlMaps

* #0000

**Comment by megan07** [comment]
Hi @diodfr!  Thank you for reaching out.  Our naming convention for this is `host_rule`, so you can pass that list to `host_rule`.
I think the configuration that you're looking for looks like this
```
resource "google_compute_url_map" "url_map" {
  name    = "mymap"
  project = local.gcp_project

  host_rule {
    hosts        = ["foo.bar.com"]
    path_matcher = "foobarpaths"
  }
  host_rule {
    hosts        = ["zoo.bar.com"]
    path_matcher = "commonpaths"
  }

  path_matcher {
    name            = "foobarpaths"
    default_service = "projects/${var.project_id}/global/backendServices/${var.foobar_backend}"
  }
  path_matcher {
    name            = "commonpaths"
    default_service = "projects/${var.project_id}/global/backendServices/${var.zoobar_backend}"
  }
}
```
Let me know if this helps and I can close the issue.  Thanks!

**Comment by diodfr** [comment]
It works. Sorry for the noise. Maybe an example in the documentation could help.
Thanks you.
