### ISSUE TITLE
Errors for domain mapping to cloud run are swallowed.

### ISSUE THREAD

**Issue by dogmatic69** [terraform-providers/terraform-provider-google#5851]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_cloud_run_domain_mapping

### Terraform Configuration Files

```tf
resource "google_cloud_run_domain_mapping" "default" {
  count    = var.domain != "" ? 1 : 0
  project  = var.project
  location = var.location
  name     = var.domain

  metadata {
    namespace = var.project
    labels = {
      terraformed                     = true
      component                       = var.component
      "cloud.googleapis.com/location" = var.location 
    }
  }

  spec {
    force_override = false
    route_name     = google_cloud_run_service.run-api.name
  }
}
```

### Debug Output
This is actually TRACE as DEBUG still does not actually give the right error messages

https://gist.github.com/dogmatic69/2a2aa1f9382047dcc2fbfef246bd9949

### Panic Output

na

### Expected Behavior
Get a decent error message (I realise even GCP does not provide a good message, but it is better than nothing)
```
Error: Error creating DomainMapping: domain is too long

  on .terraform/modules/admin-ui/modules/cloud-run/domain.tf line 1, in resource "google_cloud_run_domain_mapping" "default":
   1: resource "google_cloud_run_domain_mapping" "default" {
```

Google actually has this error in the logs: 

> Resource name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.

### Actual Behavior

Completely unhelpful errorr unless TRACE is enabled.
```
Error: Error creating DomainMapping: googleapi: Error 400: The request has errors

  on .terraform/modules/admin-ui/modules/cloud-run/domain.tf line 1, in resource "google_cloud_run_domain_mapping" "default":
   1: resource "google_cloud_run_domain_mapping" "default" {
```

### Steps to Reproduce

Create a domain mapping to cloud run with a long domain (ca 70 characters long)

### Important Factoids

n/a

### References

n/a

**Comment by venkykuberan** [comment]
Yes i see it. API is not sending enough info on the `message` attribute. Even we customize the error handler to include the `fieldViolations` description, it wouldn't be descriptive enough to explain the domain name string length issue.  Its best to raise an issue against the cloud_run API as provider can't do much here. Please let me know your thoughts ..

```
 {
   "error": {
     "code": 400,
     "message": "The request has errors",
     "status": "INVALID_ARGUMENT",
     "details": [
       {
         "@type": "type.googleapis.com/google.rpc.BadRequest",
         "fieldViolations": [
           {
             "field": "metadata.name",
             "description": "Resource name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character."
           }
         ]
       },
       {
         "@type": "type.googleapis.com/google.rpc.DebugInfo",
         "detail": "[ORIGINAL ERROR] generic::invalid_argument: userFacingMessage: The request has errors; userFacingDetails: field_violations {\n  field: \"metadata.name\"\n  description: \"Resource name must consist of lower case alphanumeric characters, \\'-\\' or \\'.\\', and must start and end with an alphanumeric character.\"\n}\n; \ncom.google.cloud.eventprocessing.manager.api.error.MalformedRequestException: userFacingMessage: The request has errors; userFacingDetails: field_violations {\n  field: \"metadata.name\"\n  description: \"Resource name must consist of lower case alphanumeric characters, \\'-\\' or \\'.\\', and must start and end with an alphanumeric character.\"\n}\n;  Code: INVALID_ARGUMENT [google.rpc.error_details_ext] { message: \"The request has errors\" details { type_url: \"type.googleapis.com/google.rpc.BadRequest\" value: \"\\n\\226\\001\\n\\rmetadata.name\\022\\204\\001Resource name must consist of lower case alphanumeric characters, \\'-\\' or \\'.\\', and must start and end with an alphanumeric character.\" } }"
       }
     ]
   }
 }
```

**Comment by venkykuberan** [comment]
As we agreed in this case the upstream API have to send the appropriate error message and provider have limited role i am closing this issue. Please reopen if you feel otherwise.
