### ISSUE TITLE
minor typos in google_billing_account_iam_binding

### ISSUE THREAD

**Issue by JohnMcSpedon** [terraform-providers/terraform-provider-google#5853]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.16
+ provider.google v3.8.0

### Affected Resource(s)

* google_billing_account_iam_binding

### Expected Behavior

title should be `google_billing_account_iam_binding`

example import should use `roles/billing.viewer`

### Actual Behavior

title is `google_billing_account__iam_binding`

example import uses `roles/viewer`

### Steps to Reproduce

visit https://www.terraform.io/docs/providers/google/r/google_billing_account_iam_binding.html

**Comment by edwardmedia** [comment]
fixing in https://github.com/GoogleCloudPlatform/magic-modules/pull/3244

**Comment by JohnMcSpedon** [comment]
thanks for the quick fix!
