### ISSUE TITLE
Add compute status field on data.google_compute_instance

### ISSUE THREAD

**Issue by sebglon** [terraform-providers/terraform-provider-google#5865]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_compute_instance

### Potential Terraform Configuration

As make [here](https://github.com/terraform-providers/terraform-provider-google/pull/4797), can we have access to the compute status?

**Comment by danawillow** [comment]
Since I see you have a PR out for review already, assigning the issue to you as well!

**Comment by danawillow** [comment]
@sebglon I see that the PR you had out for review was on the compute instance resource, though this issue is about the data source. Are you also intending to create a PR for the data source change, or should I unassign this from you?

**Comment by sebglon** [comment]
@danawillow Sorry the PR is here: https://github.com/GoogleCloudPlatform/magic-modules/pull/3269

**Comment by danawillow** [comment]
Great, thanks! Sounds like this is done now, so closing.
