### ISSUE TITLE
`google_container_cluster` should support a subnetwork self_link

### ISSUE THREAD

**Issue by rochdev** [terraform-providers/terraform-provider-google#587]
Right now it only supports a subnetwork name. The only way to set up a dependency on the subnetwork if defined in a different module is to use its `self_link` property which is not currently supported. This means that whenever the cluster needs to be recreated it results in a conflict since the subnetwork is deleted at the same time even though the cluster is still using it.

**Comment by danawillow** [comment]
Can you explain what you mean by "The only way to set up a dependency on the subnetwork if defined in a different module is to use its self_link property"? I'm fine with making the change, but I want to get a good idea of what's broken right now. A sample config would be helpful.

**Comment by rochdev** [comment]
For example, in the following scenario:

```yaml
# network/network.tf

resource "google_compute_subnetwork" "subnet" {
  name          = "${var.name}"
  network       = "${var.network}"
  ip_cidr_range = "10.128.0.0/16"
}

output "subnet_name" {
  value = "${google_compute_subnetwork.subnet.name}"
}

# cluster/cluster.tf

resource "google_container_cluster" "cluster" {
  name               = "primary"
  network            = "${var.network}"
  subnetwork         = "${var.subnet}"
  zone               = "us-east1-b"
  initial_node_count = 1
}

# test.tf

module "subnet" {
  source = "./subnet"

  name    = "test"
  network = "test"
}

module "cluster" {
  source = "./cluster"

  network    = "test"
  subnetwork = "${module.subnet.subnet_name}"
}
```

This will work, but will not set up a dependency between the cluster and the subnet even though it uses an output from the subnet. This is because Terraform is able to infer the subnet name before it actually creates the resource since it is also given to the subnet as an input. This would not be possible with a `self_link` and Terraform would therefore properly set up the dependency.

A workaround that I have found is to use `${basename(var.subnet_link)}` which finds the name from the `self_link`, but since this is usually supported out of the box in most resources, I think `google_container_cluster` should support it as well for consistency.

P.S.: I would argue that having module dependencies in Terraform would solve this issue, but this is unfortunately not supported at the moment.

**Comment by danawillow** [comment]
Can you show me the output of `terraform plan` and also the error message you're seeing?

The issue with accepting a self_link out of the box is it gives the implication that you could use a subnetwork from a different project, which isn't currently the case- the GCP API only accepts the subnetwork name, so we would just be cutting off the rest of the information. Again, not totally opposed, but just want to make sure we're solving the right problem.

**Comment by danawillow** [comment]
Also debug logs would be great!

**Comment by rochdev** [comment]
The error we had was when deleting the subnet, the cluster would not be deleted first since the dependency was never set up so the error was about the subnet being in use by the cluster.

I will try to add more details tomorrow, but in general I agree that accepting a `self_link` could cause inconsistencies with the project specified. Especially since the workaround was not all that difficult once I figured it out.

**Comment by paddycarver** [comment]
Hi! This issue has gone some time without a response, and we need some more details before we can really do anything about this. To help maintainers find actionable issues to work on, I'm going to close this out. However, if this is still a bug people are experiencing, and someone can provide an error message and/or debug log, we can get this reopened and hopefully get it fixed.
