### ISSUE TITLE
Resource google_sql_database_instance root_password (MS SQL) for GA

### ISSUE THREAD

**Issue by goobysnack** [terraform-providers/terraform-provider-google#5870]
Based on https://github.com/terraform-providers/terraform-provider-google/issues/4776

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.18
Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "random" (hashicorp/random) 2.2.1...
- Downloading plugin for provider "vault" (hashicorp/vault) 2.8.0...
- Downloading plugin for provider "google" (hashicorp/google) 3.11.0...
- Downloading plugin for provider "null" (hashicorp/null) 2.1.2...

### Affected Resource(s)

google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "master" {
  depends_on       = [random_password.root_password]
  project          = var.project_id
  name             = var.master_name
  database_version = var.db_version
  region           = var.region
  root_password    = random_password.root_password.result
  settings {
    tier             = var.tier
    disk_size        = var.disk_size
    replication_type = "SYNCHRONOUS"

    backup_configuration {
      binary_log_enabled = false
      enabled            = true
    }
    maintenance_window {
      day          = var.maint_day
      hour         = var.maint_hour
    }

    ip_configuration {
<removed>
        }
      }
    }
  }
}
```

### Expected Behavior
The module should accept the root_password argument per https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#root_password
--it says beta, but the issue above indicates it was merged into the GA provider.

### Actual Behavior

```
on .terraform/modules/gcp_csql_instances/main.tf line xx, in resource "google_sql_database_instance" "master":
  22:   root_password    = random_password.root_password.result

An argument named "root_password" is not expected here.
```

### Steps to Reproduce

1. `terraform apply` with a root_password configured.

### References

* #0000

**Comment by edwardmedia** [comment]
@goobysnack You have got the answer in below PR. I have verified it works for `google-beta`.  I am closing this issue here. Thanks
https://github.com/GoogleCloudPlatform/magic-modules/pull/2592

**Comment by edwardmedia** [comment]
Change this `issue` to `enhancement`
Refer to: https://github.com/GoogleCloudPlatform/magic-modules/pull/2592

**Comment by goobysnack** [comment]
It does work in google-beta.  I was told to open an issue to get it moved to google provider.  Is that not accurate?

**Comment by asbchakri** [comment]
I have the same issue. It works in Provider=google-Beta but nit in Provider = Google

**Comment by asbchakri** [comment]
Any update on when this enhancement will be released

**Comment by asbchakri** [comment]
I'm still having issues creating a SQL Server Instance using the Google provider. Can you let me know when this enhancement will be released.

**Comment by goobysnack** [comment]
> I'm still having issues creating a SQL Server Instance using the Google provider. Can you let me know when this enhancement will be released.

It's working.  I just created one.  You will need a variable input configuration file, but here's the module.  I believe you still have to use the beta provider.

```
provider "google-beta" {
  credentials = ""
  version     = "~> 3.0"
}

resource "random_password" "root_password" {
  length = 48
  special = true
  override_special = "_^*($@?-+)"
}

// Create SQL Instance

resource "google_sql_database_instance" "master" {
  provider  = google-beta
  depends_on       = [random_password.root_password]
  project          = var.project_id
  name             = var.master_name
  database_version = var.db_version
  region           = var.region
  root_password    = random_password.root_password.result
  settings {
    tier             = var.tier
    disk_size        = var.disk_size

    backup_configuration {
      binary_log_enabled = true
      enabled            = true
    }
    maintenance_window {
      day          = var.maint_day
      hour         = var.maint_hour
    }

    availability_type = "REGIONAL"

    ip_configuration {
      ipv4_enabled = true
      require_ssl = true
      dynamic "authorized_networks" {
        for_each = var.authorized_nets
        iterator = authorized_nets
        content {
         name = "authorized_nets-${authorized_nets.key}"
         value = authorized_nets.value
        }
      }
    }
  }
}
```

**Comment by asbchakri** [comment]
Yes it works with the beta provider, i've been creating instances with that, but what i'm saying is it does not work with Provider=Google and i guess this is what this Enhancement is for.

**Comment by goobysnack** [comment]
> Yes it works with the beta provider, i've been creating instances with that, but what i'm saying is it does not work with Provider=Google and i guess this is what this Enhancement is for.
 
Fair point :D

**Comment by talonx** [comment]
Even provider=google-beta does not work for me.
