### ISSUE TITLE
Sporadic error which lasted for an hour during release of v2.20.3

### ISSUE THREAD

**Issue by bharathkkb** [terraform-providers/terraform-provider-google#5876]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v0.12.20
Also observed in v0.12.23

### Affected Resource(s)

* provider "google"

### Terraform Configuration Files

```tf
provider "google" {
  version = "~> 2.7"
}
```
### Debug Output

https://gist.github.com/bharathkkb/fa7fb467c37e8382c1e4231730045218

### Expected Behavior

Terraform should have been successfully initialized

### Actual Behavior

Error: Provider "google" v2.20.3 is not compatible with Terraform 0.12.20.

### Steps to Reproduce

1. `terraform init`

### Important Factoids

This happened for about an hour after the release of provider v2.20.3 and then it magically resolved. I was wondering if this is common during the release of a new provider version or if something happened during this release as alot of us are using some kind of automated pipelines and these errors can be confusing. 

### References

* #0000

**Comment by danawillow** [comment]
Assigning over to @megan07 to provide some context and to close (since it's working now).

**Comment by megan07** [comment]
Hi @bharathkkb!  Sorry for the interruption and inconvenience.  Our release on Tuesday ran into a problem due to a new deploy tool, and it was briefly unavailable for Terraform 0.12 users. We've fixed the release and updated our internal processes to ensure we don't run into this specific problem again. Thanks for your patience.

**Comment by bharathkkb** [comment]
@megan07 thanks for the explanation :)
