### ISSUE TITLE
AI Platform Notebook support

### ISSUE THREAD

**Issue by preston-hf** [terraform-providers/terraform-provider-google#5879]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be nice to be able to define AI Notebook resources using Terraform.

### New or Affected Resource(s)

* google_ai_notebook

### Potential Terraform Configuration

```tf
resource "google_ai_notebook" "my_notebook" {
  # Actually doesn't overlap much with GCE, so we'll need to snake_case here: https://cloud.google.com/ai-platform/notebooks/docs/reference/rest/v1beta1/projects.locations.instances#Instance
}
```

### References

Instance definition https://cloud.google.com/ai-platform/notebooks/docs/reference/rest/v1beta1/projects.locations.instances#Instance

#4359 may be related.

* #0000

**Comment by agosto-raypitmon** [comment]
[This medium article](https://medium.com/google-cloud/using-google-cloud-ai-platform-notebooks-as-a-web-based-python-ide-e729e0dc6eed) describes how to create an AI platform notebook using `gcloud` commands to create a GCE VM. Using that, I was able to create a notebook using `google_compute_instance` resource and setting some metadata, boot disk image, etc.

**Comment by getmarkus** [comment]
You may want to contact the GCP Notebook's API team. There is a new Notebook's API in beta that will deprecate the method's in the referenced Medium article.

https://cloud.google.com/ai-platform/notebooks/docs/reference/rest

**Comment by gogasca** [comment]
Hi @preston-hf , I'm part of the Notebooks API team (Here you will find a workaround to create notebooks using GCE https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/notebooks/tools/terraform) is in our plan to add Terraform support in next quarter. 
As I will be working on it, I would appreciate any pointers as how to get started/documentation for developers so I can add direct support.

**Comment by preston-hf** [comment]
Thanks for reaching out. Could you provide more info about what kind of information you're looking for? Thanks for the link, I will definitely check it out.

**Comment by gogasca** [comment]
I'm looking for a contribution guide to start Development. (Code structure for the Terraform component)
We have the REST API and SDK, already and I will generate the GoLang library

I found a sample PR for Dataproc.
https://github.com/terraform-providers/terraform-provider-google/pull/252/files#diff-022d1bbf3b0cde7c913a68aac08359eb

Not sure if this is the best starting point

**Comment by ndmckinley** [comment]
I'm helping @gogasca accomplish this - I've sent you the initial steps you'll need to take, thanks so much for your contribution, and please reach out whenever or if you ever need help.  :)

**Comment by gogasca** [comment]
Created PR https://github.com/GoogleCloudPlatform/magic-modules/pull/3620

**Comment by gogasca** [comment]
PR [#3620 ](GoogleCloudPlatform/magic-modules#3620)was merged today!
