### ISSUE TITLE
Projects created with Terraform are not listed in the UI

### ISSUE THREAD

**Issue by rochdev** [terraform-providers/terraform-provider-google#588]
We have the following project resource:

```yaml
resource "google_project" "project" {
  org_id          = "${var.org_id}"
  project_id      = "${var.project_id}"
  name            = "${var.project_name}"
  billing_account = "${var.billing_account}"
}
```

The `org_id` option is not being used and the project is created with no organization.

**Comment by rochdev** [comment]
Actually it seems from the settings page they are in the correct organization yet they do not show up in the list of projects. Projects that were created outside of Terraform appear properly.

**Comment by rochdev** [comment]
They to show up in `No organization` even though I can see the correct information in the project settings.

**Comment by danawillow** [comment]
Just to confirm, you're looking at the "all" tab of the projects list and not the "recent" tab, correct? I know that distinction has thrown me off a whole bunch of times.

**Comment by rochdev** [comment]
Yes. Basically:

* I can see the project in Recent
* I can see the project in "All" only when selecting "No organization"
* I can see the project in "Manage Resources" only when selecting "No organization"

However, in the project settings page, I can see the correct organization

**Comment by rochdev** [comment]
The projects were moved to the correct place automatically and new projects are also created in the right place now so it seems it was a bug in the GCP UI.
