### ISSUE TITLE
global backend service?

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#589]
with gcloud you can do:
```
gcloud compute backend-services create be-i \
          *******--global******* --protocol=HTTP \
          --load-balancing-scheme=EXTERNAL \
          --enable-cdn \
          --health-checks=http \
          --timeout=30s
```
with terraform not: https://www.terraform.io/docs/providers/google/r/compute_backend_service.html

?

**Comment by danawillow** [comment]
Hi @matti, the `google_compute_backend_service` resource is global. The regional version is at `google_compute_region_backend_service`. Hope that helps!

**Comment by matti** [comment]
This naming is so confusing - some of the things are named with _global_ in them and some are not.

**Comment by danawillow** [comment]
I'm sorry you're disappointed with our naming. In Terraform we try to keep things more-or-less equivalent to their GCP APIs: https://cloud.google.com/compute/docs/reference/latest/backendServices
