### ISSUE TITLE
Data Catalog tagTemplates + tags

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#5892]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/data-catalog

### New or Affected Resource(s)

Request is specifically for:
* https://cloud.google.com/data-catalog/docs/reference/rest/v1beta1/projects.locations.tagTemplates
* https://cloud.google.com/data-catalog/docs/reference/rest/v1beta1/projects.locations.tagTemplates.fields
* https://cloud.google.com/data-catalog/docs/reference/rest/v1beta1/projects.locations.entryGroups.entries.tags

but it may make sense to also add the other entryGroup related resources for completeness (especially since that'll make it easier to test).

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* b/151143549

**Comment by danawillow** [comment]
Quick update- I'm working on the tag template resource, but the API is a bit unusual:
- `tagTemplates` require a non-empty list of fields
- `fields` cannot be updated by calling an update/patch method on the `tagTemplate`, but instead are done with add/remove/patch on the `field`
- typically we would handle ^ by breaking out `field` into its own resource, but we can't do that here because of the requirement of `tagTemplates.fields` being non-empty.

It's still doable in Terraform- Bigtable Clusters have similar restrictions, and so we put them on the Bigtable Instance resource (which requires at least one cluster). However, it's not the easiest code to write+maintain (I don't know how it is from a usability perspective though, but my guess is the separate resource is better than or equivalent to the list of objects). Checking with the Data Catalog team to see what they think (b/155304495 for Googlers).

**Comment by yin** [comment]
Data Catalog is now GA and the most recent API version is `v1`. The API v1 is identical to `v1beta1`. The docs are thus located at:

**Comment by danawillow** [comment]
Filed https://github.com/terraform-providers/terraform-provider-google/issues/6574 for update support on tag template fields. Please +1 that issue if it's important to you so we know whether or not its worth putting effort into.

Closing this one out since we now have all resources supported.

**Comment by yin** [comment]
I see this PR includes EntryGroups. Tagging is most relevant with entries as well. Do we need to file a new feature request for maintaining entries as well?

**Comment by danawillow** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/3532 is the PR for Entry
