### ISSUE TITLE
`google_kms_crypto_key_version` `public_key` returns 400

### ISSUE THREAD

**Issue by c2thorn** [terraform-providers/terraform-provider-google#5895]
`public_key` is returning an error during the initial GET request:
```

  "error": {
     "code": 400,
    "message": "projects/graphite-test-camtest2/locations/global/keyRings/test-attestor-key-ring/cryptoKeys/test-attestor-key/cryptoKeyVersions/1 is not enabled, current state is: PENDING_GENERATION.",
    "status": "FAILED_PRECONDITION",
   "details": [
      {
     "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
         "violations": [
          {
             "type": "KEY_PENDING_GENERATION",
            "subject": "projects/graphite-test-camtest2/locations/global/keyRings/test-attestor-key-ring/cryptoKeys/test-attestor-key/cryptoKeyVersions/1"
          }
         ]
      }
     ]
   }
```

Thus `public_key` returns with an empty list during apply, causing the error seen in https://github.com/terraform-providers/terraform-provider-google/issues/5552#issuecomment-599131035

**Comment by ooq** [comment]
Thanks for creating this bug @c2thorn !
I'm new to terraform. But It seems that even when the key is indeed generated (by checking GCP console), refreshing terraform state for `version` would still not retrieve the `public_key`. Is this expected?

**Comment by c2thorn** [comment]
@ooq that is not expected, mind sharing your Terraform configuration file?

**Comment by ooq** [comment]
@c2thorn Exactly this one: https://www.terraform.io/docs/providers/google/r/binary_authorization_attestor.html#example-usage-binary-authorization-attestor-kms

**Comment by c2thorn** [comment]
Thanks for your cooperation @ooq! I cannot seem to reproduce what you are seeing (refreshing is showing `public_key`). Do you mind sharing your [DEBUG](https://www.terraform.io/docs/internals/debugging.html) logs when you apply/refresh?
