### ISSUE TITLE
GCP Credentials per file work in "google" but not "google-beta"

### ISSUE THREAD

**Issue by JSANL** [terraform-providers/terraform-provider-google#5899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.12.23
+ provider.google v3.12.0
+ provider.google-beta v3.12.0
```

### Affected Resource(s)

* google-beta

### Terraform Configuration Files

Works:  
```tf
provider "google" {
  credentials = file("account.json")
  project = "my-project"
  region = "europe-west3"
  zone   = "europe-west3-c"
}

resource "google_compute_network" "default" {
  name = "default"
}
```

Does not work:   
```tf
provider "google-beta" {
  credentials = file("account.json")
  project = "my-project"
  region = "europe-west3"
  zone   = "europe-west3-c"
}

resource "google_compute_network" "default" {
  name = "default"
}
```

### Output
```
Error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

  on <empty> line 0:
  (source code not available)
```

### Debug Output
https://gist.github.com/JSANL/f55e4c54464f15e30e7ce46de8ef3934

### Expected Behavior
The credentials should've been found with the "google-beta"-provider.

### Actual Behavior

The credentials haven't been found with the "google-beta"-provider.

### Steps to Reproduce
1. `terraform apply`

**Comment by venkykuberan** [comment]
@JSANL per your debug log i see your resource is trying to use google provider as its the default. Try using the provider attribute `provider = "google-beta" ` in your network resource, it will work as expected. Let me know if it isn't working.

**Comment by JSANL** [comment]
Yes, It works :)  
Is this the expected behavior though? Because for many resources it will be quite painstaking.

**Comment by venkykuberan** [comment]
Yes, its is expected to work that way. Please refer this doc for using `google-beta provider` - https://www.terraform.io/docs/providers/google/guides/provider_versions.html#using-the-google-beta-provider

I am closing this issue as its solved
