### ISSUE TITLE
google_compute_disk_resource_policy_attachment cant be created for google_compute_region_disk

### ISSUE THREAD

**Issue by eddy-curv** [terraform-providers/terraform-provider-google#5901]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.18
+ provider.google v3.4.0
+ provider.kubernetes v1.9.0

### Affected Resource(s)

* `google_compute_disk_resource_policy_attachment`
* `google_compute_resource_policy`
* `google_compute_region_disk`

### Terraform Configuration Files

```tf
resource "google_compute_region_disk" "my_disk" {
  name = "my-disk"
  region = "us-east1"
  replica_zones = ["us-east1-a", "us-east1-b"]
  type = var.storage_type
  size = var.storage_size
}

resource "google_compute_resource_policy" "my_disk_snapshot_schedule" {
  name = "${google_compute_region_disk.my_disk.name}-schedule"
  region = "us-east1"

  snapshot_schedule_policy {
    schedule {
      daily_schedule {
        start_time = "16:00"
        days_in_cycle = 1
      }
    }
    retention_policy {
      max_retention_days = 7
    }
    snapshot_properties {
      storage_locations = ["us-east1]
    }
  }
}

resource "google_compute_disk_resource_policy_attachment" "my_policy_attachment" {
  disk = google_compute_region_disk.my_disk.name
  name = google_compute_resource_policy.my_disk_snapshot_schedule.name
}
```

### Debug Output

Can't add debug output due to confidentiality 

### Expected Behavior

The following resources should have been successfully created: 
resource `"google_compute_region_disk" "my_disk"`
resource `"google_compute_resource_policy" "my_disk_snapshot_schedule"`
resource `"google_compute_disk_resource_policy_attachment" "my_policy_attachment"`

final result: `my_disk` should use `my_disk_snapshot_schedule`.

### Actual Behavior

terraform failed with the following error message:
Error: Error creating DiskResourcePolicyAttachment: googleapi: Error 404: The resource 'projects/my-project/zones/us-east1-b/disks/my-disk' was not found, notFound

### Steps to Reproduce

1. create a `google_compute_region_disk`, `google_compute_resource_policy`
1. try to attach the policy using `google_compute_disk_resource_policy_attachment`
1. `terraform apply`

### Important Factoids

When using a non regional disk - `google_compute_disk` (specifying a zone of course), `google_compute_disk_resource_policy_attachment` is successfully created for the disk and the policy. 

So currently in order to overcome this, we are attaching the resource policy using `gcloud compute disks add-resource-policies` which is ran using `null-resource` `provisioner "local-exec"`.
### References

* #0000

**Comment by rileykarson** [comment]
We actually just released [`3.13.0`](https://github.com/terraform-providers/terraform-provider-google/releases/tag/v3.13.0), which includes a `google_compute_region_disk_resource_policy_attachment` resource. Closing since this is now supported.

Original issue: https://github.com/terraform-providers/terraform-provider-google/issues/5357
