### ISSUE TITLE
Unable to switch from port to port_name in tcp health check

### ISSUE THREAD

**Issue by Unichron** [terraform-providers/terraform-provider-google#5905]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

- terraform: 0.12.23
- google provider: 3.13.0

### Affected Resource(s)
* google_compute_health_check

### Terraform Configuration Files

Version before
```tf
resource "google_compute_health_check" "default" {
  name                = "test"
  timeout_sec         = 1
  check_interval_sec  = 1
  healthy_threshold   = 2
  unhealthy_threshold = 2
  tcp_health_check {
    port         = 80
    proxy_header = "PROXY_V1"
  }
}
```

Version after
```tf
resource "google_compute_health_check" "default" {
  name                = "test"
  timeout_sec         = 1
  check_interval_sec  = 1
  healthy_threshold   = 2
  unhealthy_threshold = 2
  tcp_health_check {
    port_name          = "health"
    port_specification = "USE_NAMED_PORT"
    proxy_header       = "PROXY_V1"
  }
}
```

### Debug Output

https://gist.github.com/Unichron/cdae0b05a291ed9adf51ab457c37e1fc

### Expected Behavior

Port is unset, port_name is set.

### Actual Behavior

Port is not unset, validation fails because of port_specification="USE_NAMED_PORT". According to the google api docs, if both are specified port takes precedence, hence the need to use port_specification.

If the initial port is not the default (for example 88), then this change works.

My guess is that the portDiffSuppress function causes the bug.
### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@c2thorn in the plan, I see this after making changes 
```
      ~ tcp_health_check {
            port               = 80
          + port_name          = "health"
          + port_specification = "USE_NAMED_PORT"
            proxy_header       = "PROXY_V1"
        }
``` 
```
Error: Error updating HealthCheck "projects/myproject/global/healthChecks/test": googleapi: Error 400: Invalid
 value for field 'resource.tcpHealthCheck.portSpecification': 'USE_NAMED_PORT'. Port cannot be set if USE_NAMED_
PORT is specified., invalid
```
