### ISSUE TITLE
Unable to use google-beta provider

### ISSUE THREAD

**Issue by Crizstian** [terraform-providers/terraform-provider-google#5920]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

➜ terraform version
Terraform v0.12.23
+ provider.google v3.13.0
+ provider.google-beta v3.13.0
+ provider.random v2.2.1

### Affected Resource(s)

google_compute_health_check
google_compute_forwarding_rule
google_compute_region_backend_service

### Terraform Configuration Files

```tf
resource "google_compute_health_check" "default" {
  provider = google-beta
  count = var.instance_count > 0 ? 1 : 0
  
  name               = "${var.cloud_provider}${var.ssr_id}${var.environment}${var.server_type}-hc${ var.is_dr ? "-dr" : "" }-${var.project_tag}"
  check_interval_sec = 5
  timeout_sec        = 5
  https_health_check {
    request_path = "/_health_check"
    port         = 443
  }
  lifecycle {
      create_before_destroy = true
  }
}

resource "google_compute_forwarding_rule" "gcp_fr" {
  provider = google-beta
  
  count = var.instance_count > 0 ? 1 : 0
  project               = var.project
  name                  = "${var.cloud_provider}${var.ssr_id}${var.environment}${var.server_type}-lbfr${ var.is_dr ? "-dr" : "" }-${var.project_tag}"
  backend_service       = google_compute_region_backend_service.backend.0.self_link
  load_balancing_scheme = "INTERNAL"
  all_ports             = true
  region                = var.region
  network               = var.gcp_network
  ip_address            = google_compute_address.default.0.address
  subnetwork            = replace(var.subnet, "gcp-region", var.region)
}

resource "google_compute_region_backend_service" "backend" {
  provider = google-beta
  
  count = var.instance_count > 0 ? 1 : 0
  name                = "${var.cloud_provider}${var.ssr_id}${var.environment}${var.server_type}-backend${ var.is_dr ? "-dr" : "" }-${var.project_tag}"
  region              = var.region
  health_checks       = [google_compute_health_check.default.0.self_link]

  dynamic "backend" {
    for_each = local.backend
    content {
      failover = backend.value.failover
      group    = backend.value.group
    }
  }
}
```

### Debug Output
Error: Post https://www.googleapis.com/storage/v1/b?alt=json&prettyPrint=false&project=slb-tfe: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: net/http: TLS handshake timeout

  on storage-bucket.tf line 1, in resource "google_storage_bucket" "tfe-store":
   1: resource "google_storage_bucket" "tfe-store" {

Error: Error creating Address: Post https://www.googleapis.com/compute/v1/projects/slb-tfe/regions/europe-west4/addresses?alt=json: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: net/http: TLS handshake timeout

  on ../loadbalancer.tf line 1, in resource "google_compute_address" "default":
   1: resource "google_compute_address" "default" {

Error: Error creating HealthCheck: Post https://www.googleapis.com/compute/beta/projects/slb-tfe/global/healthChecks?alt=json: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: net/http: TLS handshake timeout

  on ../loadbalancer.tf line 42, in resource "google_compute_health_check" "default":
  42: resource "google_compute_health_check" "default" {

### Expected Behavior

Resources should be created

### Actual Behavior

TLS issue

### Steps to Reproduce

1. `terraform apply`

### References
i am not running behind any proxy, I am connected to a strong wifi signal with enough bandwidth to test terraform code

* #0000

**Comment by venkykuberan** [comment]
@Crizstian it looks to me its more of connectivity issues rather than google-beta provider issue. 

 Were you able to create the same resources with google provider ? or try to create 1 or 2 resources using gcloud just to narrow down network component ?

**Comment by venkykuberan** [comment]
@Crizstian are you still needing help on this issue ?
