### ISSUE TITLE
Cloud Run service template spec field timeoutSeconds missing

### ISSUE THREAD

**Issue by mcaballeropinto** [terraform-providers/terraform-provider-google#5924]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When trying to set the field `timeoutSeconds` in a Cloud Run service template spec,  I get an error that the argument is not expected.

<img width="646" alt="Screen Shot 2020-03-18 at 2 39 37 PM" src="https://user-images.githubusercontent.com/2819038/77010070-51c8a880-6926-11ea-93b3-04718896878f.png">

This argument allows to change the timeout for the request send to the Cloud Run service. Very handy when using Cloud Run services for queue jobs.

### New or Affected Resource(s)

* google_cloud_run_service

### Potential Terraform Configuration

```tf
resource "google_cloud_run_service" "cloud_run_services" {
  for_each = local.cloud_run_services_map

  name = each.key
  location = var.default_region

  template {
    spec {
      timeout_seconds = 900
    }
  }
}
```

### References

* Here there is the documentation for `RevisionSpec` that contains the field: https://cloud.google.com/run/docs/reference/rest/v1/RevisionSpec

* Option in Google Cloud Console when creating a Cloud Run Service
![image](https://user-images.githubusercontent.com/2819038/77015749-edf8ac80-6932-11ea-983b-13f8f915fd56.png)

**Comment by chrisst** [comment]
related issue #5539

**Comment by sergeylanzman** [comment]
fixed  https://github.com/GoogleCloudPlatform/magic-modules/pull/3622

**Comment by mcaballeropinto** [comment]
Thanks @sergeylanzman ! Feel free to close this issue. 👍
