### ISSUE TITLE
Support Google Cloud Artifact Registry

### ISSUE THREAD

**Issue by dinvlad** [terraform-providers/terraform-provider-google#5928]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* (**New**) `google_artifact_repository`
* (**New**) `google_artifact_repository_iam_member`

### Potential Terraform Configuration

With the beta availability of [Google Cloud Artifact Registry](https://cloud.google.com/artifacts), would it be possible to add `beta` support for a `google_artifact_repository` resource, for all formats:
- Docker
- Maven/Gradle
- NPM

Additionally, would it be possible to support repository-level access controls?

Example:
```tf
resource "google_artifact_repository" "repo" {
  location    = "us"
  format      = "DOCKER"
  description = "Example Docker repository"
}

resource "google_artifact_repository_iam_member" "repo_member" {
  repository = google_artifact_repository.repo.id
  role   = "roles/artifactregistry.reader"
  member = "user:read@gmail.com"
}
```

**Comment by ardagnir** [comment]
I'd like to add AR support. Can someone assign this to me?
