### ISSUE TITLE
Terraform changes the project name in a resource reference when running terraform apply.

### ISSUE THREAD

**Issue by spil-dbhagat** [terraform-providers/terraform-provider-google#5930]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.11.14
+ provider.google v2.3.0
+ provider.google-beta v2.20.0
```
### Affected Resource(s)
google_compute_target_https_proxy

### terraform plan output
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:
```
  + module.static_spela_se_lb.google_compute_global_forwarding_rule.forwarding_rule_v4
      id:                 <computed>
      ip_address:         "34.107.209.94"
      ip_protocol:        <computed>
      label_fingerprint:  <computed>
      name:               "spil-static-stg-spela-se-fwr-v4"
      port_range:         "443"
      project:            <computed>
      self_link:          <computed>
      target:             "${google_compute_target_https_proxy.https_proxy.self_link}"

  + module.static_spela_se_lb.google_compute_global_forwarding_rule.forwarding_rule_v6
      id:                 <computed>
      ip_address:         "2600:1901:0:448f::"
      ip_protocol:        <computed>
      label_fingerprint:  <computed>
      name:               "spil-static-stg-spela-se-fwr-v6"
      port_range:         "443"
      project:            <computed>
      self_link:          <computed>
      target:             "${google_compute_target_https_proxy.https_proxy.self_link}"

  + module.static_spela_se_lb.google_compute_target_https_proxy.https_proxy
      id:                 <computed>
      creation_timestamp: <computed>
      name:               "spil-static-stg-spela-se-https-proxy"
      project:            <computed>
      proxy_id:           <computed>
      self_link:          <computed>
      ssl_certificates.#: "1"
      ssl_certificates.0: "https://www.googleapis.com/compute/v1/projects/spil-infra-prd/regions/europe-west1/sslCertificates/terraform-20200317085037056700000001"
      url_map:            "https://www.googleapis.com/compute/v1/projects/spil-portal-widgetplatform-stg/global/urlMaps/spil-static-stg-spela-se-url-map"
```

Plan: 3 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

### Debug Output

https://gist.github.com/spil-dbhagat/65ba16b201d827e43586ffffba75ad70

The relevant lines from the gist are:
  ssl_certificates.0: "" => "https://www.googleapis.com/compute/v1/projects/spil-infra-prd/regions/europe-west1/sslCertificates/terraform-20200317085037056700000001"
  url_map:            "" => "https://www.googleapis.com/compute/v1/projects/spil-portal-widgetplatform-stg/global/urlMaps/spil-static-stg-spela-se-url-map"
2020-03-19T11:46:31.697+0100 [DEBUG] plugin.terraform-provider-google_v2.3.0_x4: 2020/03/19 11:46:31 [DEBUG] Creating new TargetHttpsProxy: map[string]interface {}{"sslCertificates":[]interface {}{"projects/spil-portal-widgetplatform-stg/global/sslCertificates/terraform-20200317085037056700000001"}, "urlMap":"projects/spil-portal-widgetplatform-stg/global/urlMaps/spil-static-stg-spela-se-url-map", "name":"spil-static-stg-spela-se-https-proxy"}

Note the change in project name from spil-infra-prd to spil-portal-widgetplatform-stg

### Expected Behavior
A https_proxy resource should have been created using the certificate referenced in the plan.

### Actual Behavior
Terraform tries to reference the certificate in the project I am creating the https proxy in as opposed to the one where it is actually created.

**Comment by spil-dbhagat** [comment]
Tracking my way through the source code, the call from expandComputeTargetHttpsProxySslCertificates at https://github.com/terraform-providers/terraform-provider-google/blob/15ebe233dc45ce34e5250ee1c15f3a1245d331d4/google/resource_compute_target_https_proxy.go#L148 ends up at https://github.com/GoogleCloudPlatform/terraform-validator/blob/4ffa90923d2d8ab808e4b4f2487f22bfd8fe0d15/vendor/github.com/GoogleCloudPlatform/terraform-google-conversion/google/compute_target_https_proxy.go#L97 containing "req = append(req, f.RelativeLink())" on line 108.

The parseGlobalFieldValue function extracts the project here https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/747660880f159c567a4e00a6eb6ab81dc9742d38/google/field_helpers.go#L114

I suspect a bug somewhere here.

**Comment by edwardmedia** [comment]
@spil-dbhagat could you post the config so I can try to repro the issue?

**Comment by spil-dbhagat** [comment]
https://gist.github.com/spil-dbhagat/099f11411ea68398f7fd44eda5d5d735 is the relevant config. Mostly unredacted.

To summarise:
spil-infra-prd is the central resource management project. Letsencrypt certificates are generated here.
spil-portal-dns-prd is the DNS resource zone
spil-portal-widgetplatform-stg is the project with webservers and loadbalancers. The desired LB should be created here, with a certificate generated in spil-infra-prd.

**Comment by spil-dbhagat** [comment]
This is also true in the latest 2.X version of the provider.
```
 ../../terraform -v
Terraform v0.11.14
+ provider.google v2.20.3
+ provider.google-beta v2.20.3
```

Plan:
```
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + module.static_spela_se_lb.google_compute_global_forwarding_rule.forwarding_rule_v4
      id:                    <computed>
      ip_address:            "34.107.209.94"
      load_balancing_scheme: "EXTERNAL"
      name:                  "spil-static-stg-spela-se-fwr-v4"
      port_range:            "443"
      project:               <computed>
      self_link:             <computed>
      target:                "${google_compute_target_https_proxy.https_proxy.self_link}"

  + module.static_spela_se_lb.google_compute_global_forwarding_rule.forwarding_rule_v6
      id:                    <computed>
      ip_address:            "2600:1901:0:448f::"
      load_balancing_scheme: "EXTERNAL"
      name:                  "spil-static-stg-spela-se-fwr-v6"
      port_range:            "443"
      project:               <computed>
      self_link:             <computed>
      target:                "${google_compute_target_https_proxy.https_proxy.self_link}"

  + module.static_spela_se_lb.google_compute_target_https_proxy.https_proxy
      id:                    <computed>
      creation_timestamp:    <computed>
      name:                  "spil-static-stg-spela-se-https-proxy"
      project:               <computed>
      proxy_id:              <computed>
      quic_override:         "NONE"
      self_link:             <computed>
      ssl_certificates.#:    "1"
      ssl_certificates.0:    "https://www.googleapis.com/compute/v1/projects/spil-infra-prd/regions/europe-west1/sslCertificates/terraform-20200317085037056700000001"
      url_map:               "https://www.googleapis.com/compute/v1/projects/spil-portal-widgetplatform-stg/global/urlMaps/spil-static-stg-spela-se-url-map"


Plan: 3 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: tfplan
```

Apply
``` ../../terraform apply "tfplan"
module.static_spela_se_lb.google_compute_target_https_proxy.https_proxy: Creating...
  creation_timestamp: "" => "<computed>"
  name:               "" => "spil-static-stg-spela-se-https-proxy"
  project:            "" => "<computed>"
  proxy_id:           "" => "<computed>"
  quic_override:      "" => "NONE"
  self_link:          "" => "<computed>"
  ssl_certificates.#: "" => "1"
  ssl_certificates.0: "" => "https://www.googleapis.com/compute/v1/projects/spil-infra-prd/regions/europe-west1/sslCertificates/terraform-20200317085037056700000001"
  url_map:            "" => "https://www.googleapis.com/compute/v1/projects/spil-portal-widgetplatform-stg/global/urlMaps/spil-static-stg-spela-se-url-map"

Error: Error applying plan:

1 error occurred:
        * module.static_spela_se_lb.google_compute_target_https_proxy.https_proxy: 1 error occurred:
        * google_compute_target_https_proxy.https_proxy: Error creating TargetHttpsProxy: googleapi: Error 404: The resource 'projects/spil-portal-widgetplatform-stg/global/sslCertificates/terraform-20200317085037056700000001' was not found, notFound





Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by edwardmedia** [comment]
@spil-dbhagat  have you tried to add `project` in the related resource?

**Comment by spil-dbhagat** [comment]
Which resource(s) should I be adding a project to? The certificate is created in the correct project. The https_proxy is in the correct project, which is not the same as the project where the certificates are managed.

If I add project = spil-infra-prd to the https_proxy resource,
```
resource "google_compute_target_https_proxy" "https_proxy" {
    name             = "spil-${var.name}-https-proxy"
    url_map          = "${google_compute_url_map.url_map.self_link}"
    ssl_certificates = [ "${var.ssl_certificates}" ]
    project = "spil-infra-prd"
}
```
I get
```

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + module.static_spela_se_lb.google_compute_global_forwarding_rule.forwarding_rule_v4
      id:                    <computed>
      ip_address:            "34.107.209.94"
      load_balancing_scheme: "EXTERNAL"
      name:                  "spil-static-stg-spela-se-fwr-v4"
      port_range:            "443"
      project:               <computed>
      self_link:             <computed>
      target:                "${google_compute_target_https_proxy.https_proxy.self_link}"

  + module.static_spela_se_lb.google_compute_global_forwarding_rule.forwarding_rule_v6
      id:                    <computed>
      ip_address:            "2600:1901:0:448f::"
      load_balancing_scheme: "EXTERNAL"
      name:                  "spil-static-stg-spela-se-fwr-v6"
      port_range:            "443"
      project:               <computed>
      self_link:             <computed>
      target:                "${google_compute_target_https_proxy.https_proxy.self_link}"

  + module.static_spela_se_lb.google_compute_target_https_proxy.https_proxy
      id:                    <computed>
      creation_timestamp:    <computed>
      name:                  "spil-static-stg-spela-se-https-proxy"
      project:               "spil-infra-prd"
      proxy_id:              <computed>
      quic_override:         "NONE"
      self_link:             <computed>
      ssl_certificates.#:    "1"
      ssl_certificates.0:    "https://www.googleapis.com/compute/v1/projects/spil-infra-prd/regions/europe-west1/sslCertificates/terraform-20200317085037056700000001"
      url_map:               "https://www.googleapis.com/compute/v1/projects/spil-portal-widgetplatform-stg/global/urlMaps/spil-static-stg-spela-se-url-map"


Plan: 3 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan"

../../terraform apply tfplan
module.static_spela_se_lb.google_compute_target_https_proxy.https_proxy: Creating...
  creation_timestamp: "" => "<computed>"
  name:               "" => "spil-static-stg-spela-se-https-proxy"
  project:            "" => "spil-infra-prd"
  proxy_id:           "" => "<computed>"
  quic_override:      "" => "NONE"
  self_link:          "" => "<computed>"
  ssl_certificates.#: "" => "1"
  ssl_certificates.0: "" => "https://www.googleapis.com/compute/v1/projects/spil-infra-prd/regions/europe-west1/sslCertificates/terraform-20200317085037056700000001"
  url_map:            "" => "https://www.googleapis.com/compute/v1/projects/spil-portal-widgetplatform-stg/global/urlMaps/spil-static-stg-spela-se-url-map"

Error: Error applying plan:

1 error occurred:
        * module.static_spela_se_lb.google_compute_target_https_proxy.https_proxy: 1 error occurred:
        * google_compute_target_https_proxy.https_proxy: Error creating TargetHttpsProxy: googleapi: Error 400: Invalid value for field 'resource.urlMap': 'projects/spil-portal-widgetplatform-stg/global/urlMaps/spil-static-stg-spela-se-url-map'. Cross project referencing is not allowed for this resource., invalid
```

I could work around this by creating the certificate in spil-portal-widgetplatform-stg, but I have to use the same certificate in a different project as well. 

I would expect that the resource shown in terraform plan *is* the one used in terraform apply, but that isn't working. If this isn't going to work as other resources do, then it should be documented as an exceptional case.

**Comment by spil-dbhagat** [comment]
Creating the certificate for individual domains by setting project in the certificate creation does not work either.
```
gcloud compute ssl-certificates list --project spil-portal-widgetplatform-stg
NAME                                  CREATION_TIMESTAMP
stg-a10-com-1581588124                2020-02-13T02:03:54.136-08:00
stg-agame-com-1583143204              2020-03-02T02:49:50.093-08:00
stg-gameplayer-io-1581588274          2020-02-13T02:06:19.381-08:00
terraform-20200320223450878800000002  2020-03-20T15:34:52.743-07:00
```

```
gcloud compute ssl-certificates describe terraform-20200320223450878800000002 --project spil-portal-widgetplatform-stg
ERROR: (gcloud.compute.ssl-certificates.describe) Could not fetch resource:
 - The resource 'projects/spil-portal-widgetplatform-stg/global/sslCertificates/terraform-20200320223450878800000002' was not found
```

The relevant config changes:

resources/ssl-certificates/main.tf
```
resource "google_compute_region_ssl_certificate" "certificate" {
    provider = "google-beta"
    region = "europe-west1"
    project = "${var.project}"
    private_key = "${acme_certificate.certificate.private_key_pem}"
    certificate = "${acme_certificate.certificate.certificate_pem}${acme_certificate.certificate.issuer_pem}"

    lifecycle {
        create_before_destroy = true
    }
}
```
projects/spil-infra-prd/certificates.tf
module "static_stg_spela_certificate" {
    source = "../../resources/ssl-certificates"
    common_name = "static.stg.spela.se"
    project = "spil-portal-widgetplatform-stg"
    account_key_pem = "${acme_registration.registration.account_key_pem}"
}

projects/spil-portal-widgetplatform-stg/loadbalancers.tf
```
module "static_spela_se_lb" {
    source = "../../resources/external-https-lb"
    name = "static-stg-spela-se"
    network    = "${data.terraform_remote_state.infra_prd.portal_staging_vpc_network}"
    backend    = "${module.wp_proxy_localmarkets_vpc.instance_group}"
    target_tag  = "wp-proxy-localmark-vpc"
    health_host = "example.com"
    ssl_certificates = [ "${data.terraform_remote_state.infra_prd.static_stg_spela_se_certificate}" ]
}
```

**Comment by edwardmedia** [comment]
@spil-dbhagat it says `The resource 'projects/spil-portal-widgetplatform-stg/global/sslCertificates/terraform-20200317085037056700000001' was not found` in your log. It seems the cert was created in that project in earlier steps. Your provided log only contains one call. Do you have the full debug log? Can you see where/when the cert was created? Looking at the `gistfile1.txt` you provided, I noticed you did not specify `project` for most of resources. I don't see the project `spil-portal-widgetplatform-stg` was used anywhere. If you create resources cross different projects, I would suggest you specify projects explicitly. Please provide full code and entire debug log  if you like me to repro the issue.

**Comment by spil-dbhagat** [comment]
There are a grand total of three projects involved. All resources get applied/created in the scope of that individual project. We don't add the project in the config in most resources because it comes from the current project

If you look at line 9 of gistfile1.txt, you will see the project where the certificate is created (correctly).

Line 9: projects/spil-infra-prd/regions/europe-west1/sslCertificates/terraform-20200317085037056700000001
Line 25: 
projects/spil-portal-widgetplatform-stg/global/sslCertificates/terraform-20200317085037056700000001


I have made a new run, full debug logs and configs attached.



[terraform-sample.tar.gz](https://github.com/terraform-providers/terraform-provider-google/files/4370946/terraform-sample.tar.gz)

**Comment by edwardmedia** [comment]
@spil-dbhagat how did you use the scope of individual project? how did you make sure `it comes from the current project`?

**Comment by spil-dbhagat** [comment]
My understanding is that Terraform will always use the scope of the current project when run, unless explicitly specified otherwise. This has so far been verified by experience.

Each project in my setup is independent of the others. All shared resources are created and managed in spil-infra-prd, exported to a shared bucket (using the outputs functionality of Terraform), and then imported as data (using terraform_remote_state).

This export has worked fine for other items (like networks/subnets), and I see no reason why it shouldn't work for any other resource.

The certificate generated in this case is present in the europe-west1 region of GCP.
```gcloud compute ssl-certificates describe terraform-20200323164550737200000001 --project spil-infra-prd --region europe-west1
certificate: |
 <CERTIFICATE REDACTED>
creationTimestamp: '2020-03-23T09:45:52.315-07:00'
id: '5419387876533426479'
kind: compute#sslCertificate
name: terraform-20200323164550737200000001
region: https://www.googleapis.com/compute/v1/projects/spil-infra-prd/regions/europe-west1
selfLink: https://www.googleapis.com/compute/v1/projects/spil-infra-prd/regions/europe-west1/sslCertificates/terraform-20200323164550737200000001
```

It should be possible to use this certificate in a loadbalancer in a different project.

**Comment by edwardmedia** [comment]
@spil-dbhagat  do you notice `ssl_certificates` in below plan (./terraform.log-portal-widgetplatform-stg:66)? It tried to create one in project `spil-infra-prd`. Is that where you want to have it?
```
CREATE: google_compute_target_https_proxy.https_proxy
  creation_timestamp: "" => "<computed>"
  name:               "" => "spil-static-stg-spela-se-https-proxy" (forces new resource)
  project:            "" => "<computed>" (forces new resource)
  proxy_id:           "" => "<computed>"
  quic_override:      "" => "NONE"
  self_link:          "" => "<computed>"
  ssl_certificates.#: "" => "1"
  ssl_certificates.0: "" => "https://www.googleapis.com/compute/v1/projects/spil-infra-prd/regions/europe-west1/sslCertificates/terraform-20200323164550737200000001"
  url_map:            "" => "https://www.googleapis.com/compute/v1/projects/spil-portal-widgetplatform-stg/global/urlMaps/spil-static-stg-spela-se-url-map"
```

**Comment by spil-dbhagat** [comment]
Yes. The certificate is created in the right place. The output is correct.

When the change is applied, the certificate reference changes from regional to global, and the project changes.

**Comment by edwardmedia** [comment]
@spil-dbhagat  Exactly in `creation of the google_compute_target_https_proxy, which should be created in spil-portal-widgetplatform-prd, using the certificate created in spil-infra-prd`. how did you know `It should be possible to use this certificate in a loadbalancer in a different project.`?

**Comment by spil-dbhagat** [comment]
We use other resources that way (all networks and most subnets are defined in spil-infra-prd, for example).

For example:
In spil-portal-widgetplatform-stg:
```
module "consul_vpc" {
    source         = "../../resources/generic-instance-group"
    image          = "spil-infra-prd/centos7-spil"
    name           = "consul-wp-vpc"
    role           = "consul"
    tags           = "consul"
    subnet_name    = "${data.terraform_remote_state.infra_prd.portal_staging_widgetplatform_subnet}"
    project_name   = "spil-portal-widgetplatform-stg"
    project_number = "${data.google_project.spil_portal_widgetplatform_stg.number}"
    scopes         = [
            "https://www.googleapis.com/auth/cloud-platform"
    ]
    machine_type   = "n1-standard-1"
    instance_count = 3
}
```

In spil-infra-prd
```
output "portal_staging_widgetplatform_subnet" {
    value = "${module.portal_staging_vpc.portal_stg_widgetplatform_subnet}"
}
```

**Comment by edwardmedia** [comment]
@spil-dbhagat  Network & its subnets are limited within a project in GCP. You can build networks and subnets in different projects based on shared HCL code, but I don't think you can `use` networks cross projects. GCP provides many ways to allow networks to talk to each other between different projects. I don't have a full picture of what you are doing. You may want to double check whether you want to `create` or `use`.

**Comment by spil-dbhagat** [comment]
To summarise my expectations:
Create a regional SSL certificate in project A
Use that certificate in project B

Certificate creation works fine. 
Using the certificate does not, because terraform replaces the URL of this certificate with a different one (global scope in project B).

You can certainly use networks cross project in GCP (their acronym is XPN for cross project networking).

**Comment by edwardmedia** [comment]
@spil-dbhagat `XPN` is the one way I mentioned earlier in GCP which allows different networks to talk to each other. 
Have you seen any documents which say GCP supports `Create a regional SSL certificate in project A, Use that certificate in project B`?

**Comment by spil-dbhagat** [comment]
Ah, this is not supported. Maybe an enhancement to the error reporting in terraform plan that cross project use of SSL certificates is not allowed?

I would have been happier with this error (which I got from gcloud):
ERROR: (gcloud.compute.target-https-proxies.create) Could not fetch resource:
 - Invalid value for field 'resource.sslCertificates[0]': 'https://www.googleapis.com/compute/v1/projects/spil-infra-prd/regions/europe-west1/sslCertificates/terraform-20200323164550737200000001'. Cross project referencing is not allowed for this resource.

The "resource not found" is still a provider bug.

For the record, searching for "cross project ssl certificates gcp" lead me to https://stackoverflow.com/questions/53856192/one-certificate-for-multiple-projects-gcp for the next person who runs into this issue.

**Comment by edwardmedia** [comment]
@spil-dbhagat I am closing this issue as we know the cross project sslCertifcation reference is not supported. I would suggest you file another issue or enhancement if you feel a need for your expectation. Thank you very much
