### ISSUE TITLE
Terraform code to fetch kms encrypted cer and key file from bucket and use it for a application

### ISSUE THREAD

**Issue by shree1988** [terraform-providers/terraform-provider-google#5936]
Hi Folks,

I need terraform code which will decrypt the file which is stored on CGS and use it for application.

Thanks

**Comment by shree1988** [comment]
Hi @edwardmedia,

Thanks for your reply..

I have deployed vault on GCS kubernetes cluster "https://github.com/sethvargo/vault-on-gke"
the code is using self sign certificate and i want to replace the self signed with actual cer and key files.

For this i have created a GCS bucket and uploaded key and cer files encrypted with kms

I will need to download the encrypted cert from GCS and decrypt using kms and us it in the vault app, I believe i will need to create a shell script and download then decrypt the file using kms terraform module "https://www.terraform.io/docs/providers/google/d/google_kms_secret.html"

these are the self signed cert "https://github.com/sethvargo/vault-on-gke/blob/master/terraform/tls.tf"

Could you please tell me how can achive this

Thanks in advance.

**Comment by edwardmedia** [comment]
@shree1988 did you use terraform to create those resources? If yes, you may just replace the key files in the terraform code, and reapply. If not and you want to use terraform to do your work, you might still need to create terraform by importing the state for existing resources. Once you have the terraform config code, do the same as I mentioned above.

**Comment by shree1988** [comment]
Hi @edwardmedia ,

I can not directly add, i will need to download or decrypt from GCS and will have to take the content of cer file, how can i do in below resource 

# Create the request to sign the cert with our CA
resource "tls_cert_request" "vault" {
  key_algorithm   = tls_private_key.vault.algorithm
  private_key_pem = tls_private_key.vault.private_key_pem

  dns_names = [
    "vault",
    "vault.local",
    "vault.default.svc.cluster.local",
    "localhost",
  ]

  ip_addresses = [
    "127.0.0.1",
    google_compute_address.vault_address.address,
  ]

  subject {
    common_name  = "vault.local"
    organization = "HashiCorp Vault"
  }
}

# Now sign the cert
resource "tls_locally_signed_cert" "vault" {
  cert_request_pem = tls_cert_request.vault.cert_request_pem

  ca_key_algorithm   = tls_private_key.vault-ca.algorithm
  ca_private_key_pem = tls_private_key.vault-ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.vault-ca.cert_pem

  validity_period_hours = 8760

  allowed_uses = [
    "cert_signing",
    "client_auth",
    "digital_signature",
    "key_encipherment",
    "server_auth",
  ]

  provisioner "local-exec" {
    command = "echo '${self.cert_pem}' > ./tls/vault.pem && echo '${tls_self_signed_cert.vault-ca.cert_pem}' >> ./tls/vault.pem && chmod 0600 ./tls/vault.pem"
  }
}

**Comment by shree1988** [comment]
Hi @edwardmedia,

I am able to download the file using locla-exec from GCS but its failing to read that file

**Comment by shree1988** [comment]
Hi,

I have added code to read the encrypted content form GCS using KMS key.

But getting content-type error while reading content from GCS with http resource,

**Error: Content-Type is not a text type. Got: application/octet-stream
 268: data "http" "remote_contents_client_key"**

**data "http" "remote_contents_cacerts" {
 url = "${data.google_storage_object_signed_url.file_url_cacerts.signed_url}"
}**

I tried to add content type but still getting same issue.

Could you please help to solve If anyone faced the same issue

**Comment by edwardmedia** [comment]
@shree1988 is this still an issue?

**Comment by edwardmedia** [comment]
@shree1988 I am closing this issue. Please feel free to reopen it if this is still an issue. Thanks
