### ISSUE TITLE
google_storage_bucket_iam_member shows diff for bucket self links

### ISSUE THREAD

**Issue by MajorBreakfast** [terraform-providers/terraform-provider-google#5938]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.23

### Affected Resource(s)

* google_storage_bucket_iam_member

### Terraform Configuration Files

```tf
resource "google_storage_bucket_iam_member" "read_only_access" {
  bucket = google_container_registry.foo.id // this works
  role   = "roles/storage.objectViewer"
  member = "..."
}
```

```tf
resource "google_storage_bucket_iam_member" "read_only_access" {
  bucket = google_container_registry.foo.bucket_self_link // this also works but shows diff every time
  role   = "roles/storage.objectViewer"
  member = "..."
}
```

### Expected Behavior

An empty Terraform plan after it has been applied once

### Actual Behavior

Plan includes this every time:
```
bucket = "b/eu.artifacts.my-bucket.appspot.com" -> "https://www.googleapis.com/storage/v1/b/eu.artifacts.my-bucket.appspot.com" # forces replacement
```

**Comment by edwardmedia** [comment]
I can repro this issue with plugin.terraform-provider-google_v3.13.0_x5
```
  # google_storage_bucket_iam_member.viewer must be replaced
-/+ resource "google_storage_bucket_iam_member" "viewer" {
      ~ bucket = "b/eu.artifacts.sunedward-1-autotest.appspot.com" -> "https://www.googleapis.com/storage/v1/b/eu.artifact
s.myproject.appspot.com" # forces replacement
      ~ etag   = "CAQ=" -> (known after apply)
      ~ id     = "b/eu.artifacts.myproject.appspot.com/roles/storage.objectViewer/serviceaccount:fake-svcaccoun
t@myproject-autotest.iam.gserviceaccount.com" -> (known after apply)
        member = "serviceAccount:fake-svcaccount@myproject-autotest.iam.gserviceaccount.com"
        role   = "roles/storage.objectViewer"
    }
Plan: 1 to add, 0 to change, 1 to destroy.
```
reference: https://github.com/terraform-providers/terraform-provider-google/issues/1722
