### ISSUE TITLE
Network tag for GKE Nodes 

### ISSUE THREAD

**Issue by mikekuzak** [terraform-providers/terraform-provider-google#5939]
Hi All,

I have setup a K8s cluster via terraform on GCP. Now I need to add some firewall rules but in order to do this I need somehow to get the network tag from the Kubernetes nodes to use as Source in the Firewall rule. How do I obtain that ?

**Comment by edwardmedia** [comment]
@mikekuzak Can you post your terraform code that created your existing resources? Have you checked the state for these resources if it contains what you are looking for?

**Comment by athak** [comment]
I have been needing this too and apparently not available. It can't even be extrapolated from other attributes either.

It would be very useful since currently the only way around is to add network tags in the node config of a pool, but it has to be done on creation.

**Comment by mikekuzak** [comment]
I was able to get it the hard way, as the rancher2 provides doesn't return the auto generated google resources.

```
data "google_container_cluster" "master" {
    depends_on = [rancher2_cluster.mars-cluster]
    name       = rancher2_cluster.mars-cluster.id
}

data "google_compute_instance_group" "k8s-node-grp" {
    depends_on = [rancher2_cluster.mars-cluster]
    self_link = "${element(data.google_container_cluster.master.instance_group_urls, 0)}"    
}

data "google_compute_instance" "k8s-node-inst" {
    depends_on = [data.google_compute_instance_group.k8s-node-grp]
    self_link = sort(data.google_compute_instance_group.k8s-node-grp.instances)[0]    
}

output "k8s_node_network_tag" { 
     value = sort(data.google_compute_instance.k8s-node-inst.tags)[0]
}
```

If someone has a better idea I'm keen to hear.

**Comment by edwardmedia** [comment]
@mikekuzak not sure exactly what you want to do. If you just want to retrieve the node tags, you may just below block in your HCL. (based on https://www.terraform.io/docs/providers/google/r/container_cluster.html#example-usage-with-the-default-node-pool)
```
output "node_tag" {
  value = google_container_cluster.primary.node_config
}
```

**Comment by edwardmedia** [comment]
@mikekuzak  **network_tag** can be retrieved via output on either data source or resource. I think you have presented a good way above. I am closing this issue. Please feel free to reopen it if you want to continue discussion. Thanks
