### ISSUE TITLE
google_compute_route forced replacement on second run of 'terraform apply' with no changes since first run

### ISSUE THREAD

**Issue by thehunmonkgroup** [terraform-providers/terraform-provider-google#5945]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.24
terraform-provider-google_v3.13.0_x5

### Affected Resource(s)

* google_compute_route

### Terraform Configuration Files

```tf
resource "google_compute_network" "private-east" {
  name = "private-east"
  auto_create_subnetworks = false
  routing_mode = "REGIONAL"
  lifecycle {
    prevent_destroy = true
  }
}

resource "google_compute_subnetwork" "private-east" {
  name = "private-east"
  ip_cidr_range  = "${local.network["region"]["east"]["subnet"]}/24"
  region = var.provider_env.gcp.region.east
  network = google_compute_network.private-east.self_link
  lifecycle {
    prevent_destroy = true
  }
}

resource "google_compute_network" "private-west" {
  name = "private-west"
  auto_create_subnetworks = false
  routing_mode = "REGIONAL"
  lifecycle {
    prevent_destroy = true
  }
}

resource "google_compute_subnetwork" "private-west" {
  name = "private-west"
  ip_cidr_range  = "${local.network["region"]["west"]["subnet"]}/24"
  region = var.provider_env.gcp.region.west
  network = google_compute_network.private-west.self_link
  lifecycle {
    prevent_destroy = true
  }
}

resource "google_compute_route" "private-east-private-west" {
  name = "private-east-private-west"
  dest_range = "${local.network["region"]["west"]["subnet"]}/24"
  network = google_compute_subnetwork.private-east.self_link
  next_hop_ip = local.network["ips"]["private"]["gw-east"]
}
```

### Debug Output
https://gist.github.com/thehunmonkgroup/eeceb21a94459ce3fae2bf06001f6449

### Expected Behavior

Running ```terraform apply``` to create the resources should create them, and re-running ```terraform apply``` should show no changes.

### Actual Behavior

Running ```terraform apply``` the first time successfully creates the resources, however running ```terraform apply``` a second time results in a forced replacement for the ```google_compute_route``` resource, saying the ```network``` parameter has changed, even when no change to the configuration has been made between the first and second runs of ```terraform apply```:

```
  # module.provider-pre.google_compute_route.private-east-private-west must be replaced
-/+ resource "google_compute_route" "private-east-private-west" {
        dest_range       = "10.1.4.0/24"
      ~ id               = "projects/apartmentlines-staging/global/routes/private-east-private-west" -> (known after apply)
        name             = "private-east-private-west"
      ~ network          = "https://www.googleapis.com/compute/v1/projects/apartmentlines-staging/global/networks/private-east" -> "https://www.googleapis.com/compute/v1/projects/apartmentlines-staging/regions/us-east1/subnetworks/private-east" # forces replacement
        next_hop_ip      = "10.1.2.5"
      + next_hop_network = (known after apply)
        priority         = 1000
      ~ project          = "apartmentlines-staging" -> (known after apply)
      ~ self_link        = "https://www.googleapis.com/compute/v1/projects/apartmentlines-staging/global/routes/private-east-private-west" -> (known after apply)
      - tags             = [] -> null
    }
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### Important Factoids

Pretty standard setup. I store state in S3.

**Comment by thehunmonkgroup** [comment]
I will note that running ```terraform apply``` more than twice results in the same bug again -- it looks to me like the incorrect value for ```network``` is being stored in the state file.

**Comment by venkykuberan** [comment]
@thehunmonkgroup you are referring subnet in your route instead of network resource.  The following config should work. Please let me know if it helps

```
resource "google_compute_route" "private-east-private-west" {
  name = "private-east-private-west"
  dest_range = "${local.network["region"]["west"]["subnet"]}/24"
  network = google_compute_network.private-east.self_link
  next_hop_ip = local.network["ips"]["private"]["gw-east"]
}
```

**Comment by thehunmonkgroup** [comment]
@venkykuberan yes, thank you, that was the main issue. 

For completeness, I did run into one other issue:

```
Error: Error creating Route: googleapi: Error 400: Invalid value for field 'resource.nextHopIp': '10.1.2.5'. 10.1.2.5 must lie within the address spaces of (). private-east does not own any address space. Please create a subnetwork first., invalid

  on ../../../../modules/providers/gcp/provider-pre/main.tf line 144, in resource "google_compute_route" "private-east-private-west":
 144: resource "google_compute_route" "private-east-private-west" {
```

This is because Terraform creates resources in parallel if it detects no dependencies. With your updated configuration, the subnetworks were sometimes being created after the routes, and throwing the above error message. Declaring an explicit dependency on the related subnetwork fixed the issue.

```tf
resource "google_compute_route" "private-east-private-west" {
  name = "private-east-private-west"
  dest_range = "${local.network["region"]["west"]["subnet"]}/24"
  network = google_compute_network.private-east.self_link
  next_hop_ip = local.network["ips"]["private"]["gw-east"]
  depends_on = [
    google_compute_subnetwork.private-east,
  ]
}
```
