### ISSUE TITLE
Support for NodeLocal DNS cache in cluster addons

### ISSUE THREAD

**Issue by rmanyari** [terraform-providers/terraform-provider-google#5946]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please add support for [NodeLocal DNS Cache](https://cloud.google.com/kubernetes-engine/docs/how-to/nodelocal-dns-cache). This is already supported in the [container](https://godoc.org/google.golang.org/api/container/v1beta1#DnsCacheConfig) golang package.

### New or Affected Resource(s)

* google_beta

**Comment by danawillow** [comment]
This has already been added in the code (see https://github.com/terraform-providers/terraform-provider-google/issues/5150, https://github.com/GoogleCloudPlatform/magic-modules/pull/3126). I'd expect it in the next release today-ish.
