### ISSUE TITLE
Not able to create N2 machines in GCP managed instance group.

### ISSUE THREAD

**Issue by risheak081** [terraform-providers/terraform-provider-google#5951]
I am not able to create the n2 machine type for managed instance group instance template in GCP.
It simply says - "not found" while I am able to create the same from the GUI.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.6

### Affected Resource(s)

GCP MIG N2_CPUS

### Terraform Configuration Files
resource "google_compute_instance_template" "m4m_api" {
  name        = "m4m-api-${formatdate("DD-MM-YYYY-hh-mm", timestamp())}"
  min_cpu_platform = "Intel Cascade Lake"
  machine_type     = "n2-highmem-2"
  region            = "us-central1"

  disk {
    source_image = google_compute_image.m4m_api.self_link
    auto_delete  = true
    boot         = true
  }

  network_interface {
    network = "default"
    subnetwork = "default"
    access_config{
      network_tier = "PREMIUM"
    }
  }

  lifecycle {
    create_before_destroy = true
  }

  tags = ["http-server", "https-server"]
}
### Debug Output

Error: Error creating RegionInstanceGroupManager: googleapi: Error 400: Invalid value for field 'resource.versions[0].instanceTemplate': 'https://www.googleapis.com/compute/beta/projects/maropost-marketing-cloud/global/instanceTemplates/m4m-api-23-03-2020-16-25'. InstanceTemplate should be usable in all selected zones.
More details:
Reason: invalid, Message: Invalid value for field 'resource.versions[0].instanceTemplate': 'https://www.googleapis.com/compute/beta/projects/maropost-marketing-cloud/global/instanceTemplates/m4m-api-23-03-2020-16-25'. InstanceTemplate should be usable in all selected zones.
Reason: notFound, Message: The resource 'projects/maropost-marketing-cloud/zones/us-central1-b/machineTypes/n2-highmem-2' was not found

### Expected Behavior

It should be able to create the instance template with specific machine type

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by venkykuberan** [comment]
@risheak081 with the following sample config, i am able to create N2 instances through instance group. Please let me know if this helps, if not please share your instance group config. I will take a look.

```
data "google_compute_image" "my_image" {
  family  = "debian-10"
  project = "debian-cloud"
}
resource "google_compute_instance_template" "m4m_api" {
name = "m4m-api-${formatdate("DD-MM-YYYY-hh-mm", timestamp())}"
min_cpu_platform = "Intel Cascade Lake"
machine_type = "n2-highmem-2"
region = "us-central1"

disk {
source_image = data.google_compute_image.my_image.self_link
auto_delete = true
boot = true
}

network_interface {
network = "default"
subnetwork = "default"
access_config{
network_tier = "PREMIUM"
}
}

lifecycle {
create_before_destroy = true
}

tags = ["http-server", "https-server"]
}

resource "google_compute_instance_group_manager" "appserver" {
  name = "appserver-igm"

  base_instance_name = "app"
  zone               = "us-central1-a"

  version {
    instance_template  = google_compute_instance_template.m4m_api.self_link
  }

  target_size  = 2

}
```

**Comment by risheak081** [comment]
@venkykuberan I am still seeing the same error while creating the instanceTemplate itself. It halts at the template creation process. Doesn't even go to instance group creation step.
I tried with the sample config you gave above, but no luck.

Error: Error creating RegionInstanceGroupManager: googleapi: Error 400: Invalid value for field 'resource.versions[0].instanceTemplate': 'https://www.googleapis.com/compute/beta/projects/maropost-marketing-cloud/global/instanceTemplates/m4m-api-24-03-2020-04-31'. InstanceTemplate should be usable in all selected zones.
More details:
Reason: invalid, Message: Invalid value for field 'resource.versions[0].instanceTemplate': 'https://www.googleapis.com/compute/beta/projects/maropost-marketing-cloud/global/instanceTemplates/m4m-api-24-03-2020-04-31'. InstanceTemplate should be usable in all selected zones.
Reason: notFound, Message: The resource 'projects/maropost-marketing-cloud/zones/us-central1-b/machineTypes/n2-standard-2' was not found


  on api/instance_group.tf line 1, in resource "google_compute_region_instance_group_manager" "m4m_api":
   1: resource "google_compute_region_instance_group_manager" "m4m_api" {


2020-03-24T10:01:17.211+0530 [DEBUG] plugin: plugin process exited: path=/Users/maropost/Projects/auto-ssl/.terraform/plugins/darwin_amd64/terraform-provider-google_v3.13.0_x5 pid=12235
2020-03-24T10:01:17.211+0530 [DEBUG] plugin: plugin exited

**Comment by risheak081** [comment]
@venkykuberan - Found the issue. GCP doesn't allow creating n2 instances in us-central1-b zone.
I had this zone in the distribution_policy_zones property for google_compute_region_instance_group_manager.

After removing this zone from the array of zones, I was able to create MIG with N2 instances.

Thanks.
