### ISSUE TITLE
google_compute_interconnect_attachment - admin_enabled

### ISSUE THREAD

**Issue by smssoleimani** [terraform-providers/terraform-provider-google#5965]
In the google_compute_interconnect_attachment resource, admin_enabled is listed as an optional field, however, if you don’t set it, terraform tries to recreate the resource every time you run an apply, effectively destroying and recreating your interconnect attachments (which will break networking functionality).

**Comment by venkykuberan** [comment]
@smssoleimani Can you please share your plan output or config to get a better understanding. It is optional if you aren't using the `type` attribute

reference
 admin_enabled - (Optional) Whether the VLAN attachment is enabled or disabled. When using PARTNER type this will Pre-Activate the interconnect attachment

**Comment by smerchek** [comment]
I believe I'm having the same issue for an interconnect attachment that was initially created in terraform with version 2.x of google provider. Below is the initial plan diff. 

As it turns out, I can't get around this without replacing the resource (which I don't want to do since it is a PARTNER connection). If I set admin_enabled to `true` or to `false`, it wants to change to the opposite.

```
  # google_compute_interconnect_attachment.default must be replaced
-/+ resource "google_compute_interconnect_attachment" "default" {
      - admin_enabled              = true -> null # forces replacement
      ~ bandwidth                  = "BPS_50M" -> (known after apply)
        candidate_subnets          = []
      ~ cloud_router_ip_address    = "XXXX" -> (known after apply)
      ~ creation_timestamp         = "2019-08-09T14:18:01.024-07:00" -> (known after apply)
      ~ customer_router_ip_address = "XXXX" -> (known after apply)
        edge_availability_domain   = "AVAILABILITY_DOMAIN_1"
      + google_reference_id        = (known after apply)
      ~ id                         = "attachment" -> (known after apply)
        name                       = "attachment"
      ~ pairing_key                = "<guid>/us-central1/1" -> (known after apply)
      ~ partner_asn                = "XXXX" -> (known after apply)
      ~ private_interconnect_info  = [] -> (known after apply)
      ~ project                    = "XXXXX" -> (known after apply)
      ~ region                     = "https://www.googleapis.com/compute/v1/projects/XXXX/regions/us-central1" -> "us-central1"
        router                     = "https://www.googleapis.com/compute/v1/projects/XXXX/regions/us-central1/routers/router"
      ~ self_link                  = "https://www.googleapis.com/compute/v1/projects/XXXX/regions/us-central1/interconnectAttachments/attachment" -> (known after apply)
      ~ state                      = "ACTIVE" -> (known after apply)
        type                       = "PARTNER"
      ~ vlan_tag8021q              = 15 -> (known after apply)
    }
```

Setting `admin_enabled = true`

```
-/+ resource "google_compute_interconnect_attachment" "default" {
      ~ admin_enabled              = false -> true # forces replacement
```

Setting `admin_enabled = false`

```
-/+ resource "google_compute_interconnect_attachment" "default" {
      ~ admin_enabled              = true -> false # forces replacement
```

Here how the terraform resource is implemented:

```hcl
resource "google_compute_interconnect_attachment" "default" {
  provider                 = google
  name                     = var.name
  router                   = var.router
  region                   = var.region
  edge_availability_domain = "AVAILABILITY_DOMAIN_1"
  type                     = "PARTNER"

  # admin_enabled            = false
  candidate_subnets        = []
}
```

**Comment by ogreface** [comment]
Seeing the same issue.

**Comment by slevenick** [comment]
> I believe I'm having the same issue for an interconnect attachment that was initially created in terraform with version 2.x of google provider. Below is the initial plan diff.
> 
> As it turns out, I can't get around this without replacing the resource (which I don't want to do since it is a PARTNER connection). If I set admin_enabled to `true` or to `false`, it wants to change to the opposite.
> 
> ```
>   # google_compute_interconnect_attachment.default must be replaced
> -/+ resource "google_compute_interconnect_attachment" "default" {
>       - admin_enabled              = true -> null # forces replacement
>       ~ bandwidth                  = "BPS_50M" -> (known after apply)
>         candidate_subnets          = []
>       ~ cloud_router_ip_address    = "XXXX" -> (known after apply)
>       ~ creation_timestamp         = "2019-08-09T14:18:01.024-07:00" -> (known after apply)
>       ~ customer_router_ip_address = "XXXX" -> (known after apply)
>         edge_availability_domain   = "AVAILABILITY_DOMAIN_1"
>       + google_reference_id        = (known after apply)
>       ~ id                         = "attachment" -> (known after apply)
>         name                       = "attachment"
>       ~ pairing_key                = "<guid>/us-central1/1" -> (known after apply)
>       ~ partner_asn                = "XXXX" -> (known after apply)
>       ~ private_interconnect_info  = [] -> (known after apply)
>       ~ project                    = "XXXXX" -> (known after apply)
>       ~ region                     = "https://www.googleapis.com/compute/v1/projects/XXXX/regions/us-central1" -> "us-central1"
>         router                     = "https://www.googleapis.com/compute/v1/projects/XXXX/regions/us-central1/routers/router"
>       ~ self_link                  = "https://www.googleapis.com/compute/v1/projects/XXXX/regions/us-central1/interconnectAttachments/attachment" -> (known after apply)
>       ~ state                      = "ACTIVE" -> (known after apply)
>         type                       = "PARTNER"
>       ~ vlan_tag8021q              = 15 -> (known after apply)
>     }
> ```
> 
> Setting `admin_enabled = true`
> 
> ```
> -/+ resource "google_compute_interconnect_attachment" "default" {
>       ~ admin_enabled              = false -> true # forces replacement
> ```
> 
> Setting `admin_enabled = false`
> 
> ```
> -/+ resource "google_compute_interconnect_attachment" "default" {
>       ~ admin_enabled              = true -> false # forces replacement
> ```
> 
> Here how the terraform resource is implemented:
> 
> ```terraform
> resource "google_compute_interconnect_attachment" "default" {
>   provider                 = google
>   name                     = var.name
>   router                   = var.router
>   region                   = var.region
>   edge_availability_domain = "AVAILABILITY_DOMAIN_1"
>   type                     = "PARTNER"
> 
>   # admin_enabled            = false
>   candidate_subnets        = []
> }
> ```

If you want a short term workaround you can add a lifecycle `ignore_changes` to that field to prevent it from attempting to recreate.
https://www.terraform.io/docs/configuration/resources.html#ignore_changes

I'm unclear on why setting both `true` and `false` are causing issues, I would assume that setting it to the value in the API would make the diff go away. Could you include debug logs for both plans with `true` and `false` set?

I'm working on a longer term fix to ignore the default on `admin_enabled` and potentially make interconnect attachments updatable.
