### ISSUE TITLE
Add attribute for Autoscaling Profiles in Terraform Google Kubernetes Engine Provider

### ISSUE THREAD

**Issue by rioam2** [terraform-providers/terraform-provider-google#5980]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Using the Google API Documentation as a reference, I am trying to use Terraform to orchestrate an autoscaling Kubernetes Engine Node-Pool for running batch jobs on GCP. For my use-case, I would like to be able to aggressively downscale nodes in my pool when jobs are not running on my cluster. 

In the GKE documentation, this functionality is offered via the "Autoscaling Profiles" option (currently in beta): https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler#autoscaling_profiles. Looking at the GCP API Docs, it does not look like there is a way to enable this feature using the public API yet: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters.nodePools#NodePool.NodePoolAutoscaling. I'm (admittedly) not very familiar with the GCP API documentation, so someone please correct me if I'm missing something.

Since this attribute is not currently available in Terraform, what are the most practical next-steps to implement this attribute in the beta provider? I would love to continue using Terraform to automate deployment infrastructure via code 🙂

### New or Affected Resource(s)

* google_container_node_pool

### Potential Terraform Configuration

```tf
resource "google_container_node_pool" "my_autoscaling_node_pool" {
  provider          = google-beta

  # ...

  autoscaling {
    max_node_count  = 4
    min_node_count  = 0
    autoprovisioned = true
    profile         = "optimize-utilization"   # or "balanced" (the default)
  }

  # ...

}
```

**Comment by danawillow** [comment]
It's in the beta cluster API: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#clusterautoscaling

**Comment by rioam2** [comment]
Thanks @danawillow! I discovered this a few days ago after digging through the provider source code. Works perfectly.

To future readers of this thread, I highly recommend reading through the appropriate files in https://github.com/terraform-providers/terraform-provider-google-beta/tree/master/google-beta if you're ever in doubt of attributes that may/may not exist.

**Comment by danawillow** [comment]
Ah good find, I didn't even notice. It's also in the docs, and our hope is that people can find what they need without reading through the code (though it definitely helps too)!
