### ISSUE TITLE
Add label creation to storage bucket resource type

### ISSUE THREAD

**Issue by jpmckenna** [terraform-providers/terraform-provider-google#599]
Hi,

Was hoping that we could get label creation on storage buckets added to that resource type. Not sure if this is planned or not, but I didn't see it in the last release of the provider.

Was hoping this could follow the pattern of labeling compute vms like:

```
resource "google_storage_bucket" "bucket" {
  name     = "my-bucket"
  labels   = {
      test  = "label"
  }
}
```

**Comment by danawillow** [comment]
@selmanj are you planning to do this or should one of the rest of us take it on?
