### ISSUE TITLE
Support for Dataflow job "update-by-replacement"

### ISSUE THREAD

**Issue by jcanseco** [terraform-providers/terraform-provider-google#5991]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Dataflow jobs support a sort of "update" mechanism that allows you to update an ongoing streaming job (and streaming jobs only).

How it works: you create a new job that is configured to "replace" an existing one. Dataflow would check if the new job's template is "compatible" with the existing job's template to see if the replacement request is valid, then Dataflow would **transfer state** from the old job to the new job, and then stop the old job ([documentation](https://cloud.google.com/dataflow/docs/guides/updating-a-pipeline)). Note: the name of the replacement job has to match the name of the job being replaced ([source](https://cloud.google.com/dataflow/docs/guides/updating-a-pipeline#specifying_your_replacement_job_name)).

Terraform today does not support the "state transfer" that an "update-by-replacement" allows.

Ideally, we would like to be able to perform an update-by-replacement if any of the fields in `google_dataflow_job` changed or if the underlying template file changed.

Supporting this functionality is theoretically possible. The Dataflow job REST API exposes an optional `replaceJobId` field which takes the ID of the existing job that you want to replace (see the `replaceJobId` field of the [`projects.jobs`](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.jobs#Job) resource).

That said, I'm not sure the Dataflow Go client actually gives you the option to perform an update-by-replacement by setting the `replaceJobId` yourself. Instead, it looks like the only way to do an update-by-replacement is by using the `projects.templates` resource's [`launch`](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.templates/launch) method (see the `Update` field of [`LaunchTemplateParameters`](https://godoc.org/google.golang.org/api/dataflow/v1b3#LaunchTemplateParameters)).

### New or Affected Resource(s)

* google_dataflow_job

**Comment by c2thorn** [comment]
>  if the underlying template file changed
After some internal discussion, this requirement has been removed.
