### ISSUE TITLE
BigQuery encryption service account data source

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#5996]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/bigquery/docs/reference/rest/v2/projects/getServiceAccount
Similar to https://www.terraform.io/docs/providers/google/d/google_storage_project_service_account.html

### New or Affected Resource(s)

* data.google_bigquery_service_account (bigquery_encryption_service_account?)

### References

* b/152521184
* https://github.com/terraform-providers/terraform-provider-google/issues/5359#issuecomment-573814743 (less relevant because this one _has_ an API to access it rather than needing to be constructed client-side, but still worth noting)

cc @drebes

**Comment by drebes** [comment]
Thanks!
