### ISSUE TITLE
OAuth error when creating BigQuery view depending on a table with external configuration

### ISSUE THREAD

**Issue by adesormi** [terraform-providers/terraform-provider-google#6005]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Quick Description

To create a BigQuery table with external configuration, the "drive.readonly" scope needs to be added as per the documentation (see https://www.terraform.io/docs/providers/google/r/bigquery_table.html#source_format)
This works for tables but it is not possible to create a view that reads such table.

In other words, creating a view that reads a table with external configuration is returning an OAuth error.

### Terraform Version

Google provider 2.20

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

```tf
provider "google" {
  project = var.project_id
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/drive.readonly",
  ]
}

resource "google_bigquery_table" "mytable" {
  dataset_id = "mydataset"
  table_id = "mytable"
  project = var.project_id

  external_data_configuration {
    autodetect = true
    source_format = "GOOGLE_SHEETS"
    source_uris = [
      "https://docs.google.com/spreadsheets/blabla",
    ]
  }
}

resource "google_bigquery_table" "myview" {
  dataset_id = "myviewdataset"
  table_id = "myview"
  project = var.project_id

  view {
    query = <<EOF
SELECT * FROM `${var.project_id}.mydataset.mytable`
EOF

    use_legacy_sql = false
  }
}
```

### Debug Output

Error is the following:
```
Error: googleapi: Error 400: Error while reading table: myproject.mydataset.mytable, error message: Failed to read the spreadsheet. Errors: No OAuth token with Google Drive scope was found., invalid
```

### Expected Behavior

Google Drive scope is already defined in the provider.
The view should be created successfully

### Actual Behavior

The view is not created

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@adesormi Using your code, I am not able to hit the error you received. Could you post your full debug log and let me take a closer look?
In my case, because the `view` is not available for `query` right after the `table` is created, I had to add below `resource` in order to make all resources creation smoothly. 
```
resource "null_resource" "delay" {
  provisioner "local-exec" {
    command = "sleep 10"
  }
  triggers = {
    "before" = "${google_bigquery_table.mytable.id}"
  }
}
```

**Comment by adesormi** [comment]
The error comes from the fact that I didn't specify the provider in my resource.
I was using "google-beta" provider and had set up the "drive.readonly" scope for that provider only.
By default, terraform use the "google" provider (based on the resource type prefix 'google_*').
Specifically specifying the provider in the resource fixed the issue.

```terraform
resource "google_bigquery_table" "myview" {
  provider = google-beta // <= this line was missing

  dataset_id = "myviewdataset"
  table_id = "myview"
  project = var.project_id

  view {
    query = <<EOF
SELECT * FROM `${var.project_id}.mydataset.mytable`
EOF

    use_legacy_sql = false
  }
}
```

So it was a misconfiguration. Not a bug. I mark this as fixed.
Thank you for your help
