### ISSUE TITLE
Unable to upload to gcs via google_storage_bucket_object

### ISSUE THREAD

**Issue by kwri-avongluck** [terraform-providers/terraform-provider-google#6008]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

$ terraform -v
Terraform v0.12.24
+ provider.google v3.14.0

### Affected Resource(s)

* google_storage_bucket_object

### Terraform Configuration Files

```tf
resource "google_storage_bucket" "artifact-bucket" {
  name          = "coolbucket-${var.env}"
  location      = "US"
  force_destroy = true

  bucket_policy_only = true

  cors {
    origin          = ["*"]
    method          = ["GET", "HEAD", "PUT", "POST", "DELETE"]
    response_header = ["*"]
    max_age_seconds = 3600
  }
}


resource "google_storage_bucket_object" "thing" {
  name   = "installer"
  source = "assets/cool.rpm"
  bucket = "image-store"

  depends_on = [google_storage_bucket.artifact-bucket]
}

```

### Debug Output
```
Error: Error uploading object thing: Post https://www.googleapis.com/upload/storage/v1/b/image-store/o?alt=json&name=thing&prettyPrint=false&uploadType=resumable: unable to copy invalid http.Request for retry: invalid HTTP request for transport, expected request.GetBody for non-empty Body

  on gcs.tf line 16, in resource "google_storage_bucket_object" "thing":
  16: resource "google_storage_bucket_object" "thing" {
```

### Expected Behavior

file uploaded

### Actual Behavior

Errored out.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

service account, all api's enabled

**Comment by edwardmedia** [comment]
@kwri-avongluck can you try if you replace `bucket` to something like below? Make sure `assets/cool.rpm` is in place
```
bucket = google_storage_bucket.artifact-bucket.name
```

**Comment by kwri-avongluck** [comment]
nice catch, but same error.
```
Error: Error uploading object coolthing: Post https://www.googleapis.com/upload/storage/v1/b/cool-bucket/o?alt=json&name=coolthing&prettyPrint=false&uploadType=resumable&upload_id=BLAH: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

  on gcs-thing.tf line 24, in resource "google_storage_bucket_object" "coolthing":
  24: resource "google_storage_bucket_object" "coolthing" {
```

**Comment by edwardmedia** [comment]
@kwri-avongluck did you use the posted code to run? Look at below URL, what is **upload_id=BLAH**? Again, you might need to double check all the settings.  
```
https://www.googleapis.com/upload/storage/v1/b/cool-bucket/o?alt=json&name=coolthing&prettyPrint=false&uploadType=resumable&upload_id=BLAH
```

**Comment by tswast** [comment]
Shouldn't this module be using the (somewhat new) `https://storage.googleapis.com` endpoint? https://cloud.google.com/storage/docs/json_api/v1

**Comment by tswast** [comment]
How large is the file you are trying to upload? I'm having a similar error when trying to upload a 83.6 MB deb package file.

**Comment by kwri-avongluck** [comment]
~80 MiB.  It seems to be working inconsistently.  

"@kwri-avongluck did you use the posted code to run? Look at below URL, what is upload_id=BLAH? Again, you might need to double check all the settings."

Yes.  BLAH is me hiding potentially sensitive information.

**Comment by edwardmedia** [comment]
@tswast regarding the size, we have a fix in https://github.com/terraform-providers/terraform-provider-google/issues/5970

**Comment by edwardmedia** [comment]
@kwri-avongluck do you have `assets/cool.rpm` in place? 
Without full debug log, It is a little bit difficult to help you debug. I can run your code with a problem

**Comment by edwardmedia** [comment]
@kwri-avongluck as I am not able to repro this issue, I am closing it. Please feel free to reopen it if this is still an issue with you
