### ISSUE TITLE
N2D instance types are not idempotent

### ISSUE THREAD

**Issue by jsirianni** [terraform-providers/terraform-provider-google#6016]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
❯ terraform version
Terraform v0.12.19
+ provider.google v2.12.0
```

### Affected Resource(s)

`google_compute_instance`

### Terraform Configuration Files

```tf
resource "google_compute_instance" "instance" {
  name         = var.name
  project      = var.project
  zone         = var.zone

  // 2 cores, 10gb ram
  machine_type = "n2d-custom-2-10240-ext"

  boot_disk {
    initialize_params {
      image = var.vrops_image
      size  = var.disk_size
      type  = var.disk_type
    }
  }

  network_interface {
    network = var.network
  }

  service_account {
    scopes = [
      "https://www.googleapis.com/auth/compute.readonly",
      "https://www.googleapis.com/auth/devstorage.read_only",
    ]
  }

}

```

### Expected Behavior

1) terraform apply creates instance 
2) terraform apply (2nd time) should offer to do nothing

### Actual Behavior

Terraform apply works fine, the instance is of type n2d (AMD Epic Rome). During a second apply, terraform wants to replace the instance because it wants to set `min_cpu_platform` to null when the state has it set to "AMD Rome".

```
min_cpu_platform        = "AMD Rome" -> null
```

I should not have to specify `min_cpu_platform  = "AMD Rome"` in my configuration, as this has never been the behavior for instance types that have multiple generations (N1 instance types for example).

### Steps to Reproduce

1. create an instance with n2d type, do not specify a min cpu platform
2. apply a second time, terraform will offer to replace the instance 

### Important Factoids

If I add `min_cpu_platform` to my instance configuration, re-running terraform apply results in 0 changes, as expected. This is a good workaround for now, however, I would expect terraform to set this to a sane default. This was never an issue with N1 instance types. 

### References

* #0000

**Comment by edwardmedia** [comment]
@jsirianni I can repro your issue with provider v2.12.0. But I tested it with v3.15.0, the issue appears to be fixed. Can you try the latest version?

**Comment by jsirianni** [comment]
@edwardmedia I just tried 3.15 and it resolves my issue. Thank you.
