### ISSUE TITLE
bigtable: support setting garbage collection policy

### ISSUE THREAD

**Issue by dasch** [terraform-providers/terraform-provider-google#602]
Per [the Bigtable docs](https://cloud.google.com/bigtable/docs/managing-tables#setting_an_expiration_time_for_values), it should be possible to set a `maxage` for values in a column family. It would be great if the Terraform provider supported defining this. It's also possible to define `maxversions`, although I don't personally have a need for that.

### Affected Resource(s)
- `google_bigtable_table`

**Comment by danawillow** [comment]
@emilymye

**Comment by rileykarson** [comment]
I looked at implementing `google_bigtable_family` as a resource, but ultimately didn't; there is a bit of context on garbage collection policies' default values here; https://github.com/GoogleCloudPlatform/google-cloud-go/issues/651.

One of the ongoing questions I had was how to handle [IntersectionPolicy](https://godoc.org/cloud.google.com/go/bigtable#IntersectionPolicy) and [UnionPolicy](https://godoc.org/cloud.google.com/go/bigtable#UnionPolicy) in Terraform - if they can be nested, specifically, I'm not sure how they should be represented in a way that is easy to specify simple cases & also allows any policy to be represented in Terraform.

**Comment by chetaldrich** [comment]
@rileykarson This can be closed given the following, right? 

https://www.terraform.io/docs/providers/google/r/bigtable_gc_policy.html

**Comment by rileykarson** [comment]
Yep!
