### ISSUE TITLE
Changing provider on google compute address does not recreate resource

### ISSUE THREAD

**Issue by zopanix** [terraform-providers/terraform-provider-google#603]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.10.7

### Google Provider Version
1.0.0

### Affected Resource(s)
- google_compute_address

### Terraform Configuration Files
```hcl
provider "google" {
  project     = "${var.project}"
  credentials = "${file("${var.credentials_path}")}"
  region      = "us-east1"
  version     = "1.0.0"
}

provider "google" {
  project     = "${var.project}"
  credentials = "${file("${var.credentials_path}")}"
  region      = "us-east2"
  alias       = "backup"
  version     = "1.0.0"
}

// Main IP Addresses
resource "google_compute_address" "eip-rdp-0" {
+  provider = "google.backup"
  name  = "eip-rdp-0"
}
```

### Expected Behavior
When IP Address exists using main provider and adding the backup provider, I would expect the IP's to be recreated using the backup provider instead of the main one.

### Actual Behavior
Nothing happened

### Steps to Reproduce
1. `terraform apply`
2. set provider on ip adress to backup
3. `terraform apply`

### Important Factoids
Workaround was to manually delete the ip's or taint the resources before re applying with proper config.

I don't know if this is the only resource affected.

**Comment by paddycarver** [comment]
Hey @zopanix, do you have a [debug log](https://www.terraform.io/docs/internals/debugging.html) for this, by any chance? Is it reproducible? It'd really help to figure out what's happening if we could get a log. Sorry for the issue!

**Comment by zopanix** [comment]
Sorry I don't have a debug log for this but I could generate one locally.

**Comment by paddycarver** [comment]
If it's straightforward enough and reproducible enough to generate a debug log, that would be super helpful. Honestly, a debug log from creating the IP and then another after switching the project would be 💯 .

**Comment by danawillow** [comment]
This issue is pretty old, so I'm going to go ahead and close it. If you run into it again and manage to get a debug log, let us know and we'd be happy to reopen!
