### ISSUE TITLE
ipip protocol missing from google_compute_firewall documentation

### ISSUE THREAD

**Issue by Jberlinsky** [terraform-providers/terraform-provider-google#6032]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The documentation for the `google_compute_firewall` resource lists a set of protocols that can be allowed/denied, but it is missing `ipip`, which is [supported](https://cloud.google.com/vpc/docs/firewalls#protocols_and_ports) in GCP APIs. Creating a firewall rule (see below) for `ipip` protocols succeeds, so this is a documentation-only update.

### New or Affected Resource(s)

* google_compute_firewall

### Potential Terraform Configuration

```tf
// Copyright 2020 Google LLC. This software is provided as is, without warranty or representation for any use or purpose. Your use of it is subject to your agreement with Google.

resource "google_compute_firewall" "default_deny-ipip" {
  name     = "default-deny-ipip"
  project  = ...
  network  = ...
  priority = 65535

  deny {
    protocol = "ipip"
  }
}
```

### References

N/A

**Comment by danawillow** [comment]
Added in https://github.com/terraform-providers/terraform-provider-google/pull/6033.
