### ISSUE TITLE
Missing Attributes for Google CloudFunctions

### ISSUE THREAD

**Issue by akamalov** [terraform-providers/terraform-provider-google#6049]
Greeetings,

I am looking at Terraform Provider for Google and specifically at cloudfunctions - https://www.terraform.io/docs/providers/google/d/datasource_cloudfunctions_function.html. 

However, I am not seeing an attribute support for

```
--egress-settings=[EGRESS_SETTINGS]
--ingress-settings=[INGRESS_SETTINGS]
```

...as displayed in Google's ```gcloud functions deploy``` command manual

https://www.terraform.io/docs/providers/google/d/datasource_cloudfunctions_function.html

Does it mean these attributes are not supported by Terraform Provider for Google at this present time?

Thanks a lot.

**Comment by danawillow** [comment]
Hey @akamalov. To clarify, that documentation page is actually for the data source. The resource page is at https://www.terraform.io/docs/providers/google/r/cloudfunctions_function.html.

Both fields were added recently, and appear in version 3.16.0 of the provider, which was just released a few minutes ago: https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#3160-april-06-2020. Give it a try!
