### ISSUE TITLE
google_compute_instance_from_template doesn't get scheduling parameters from template

### ISSUE THREAD

**Issue by digiology** [terraform-providers/terraform-provider-google#6050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.24
+ provider.google v3.15.0

### Affected Resource(s)

google_compute_instance_from_template

### Terraform Configuration Files

```tf

resource "google_compute_instance_from_template" "hashi-server-leader" {
  name = "hashi-server-leader"

  source_instance_template = google_compute_instance_template.hashi-server-template.self_link
}

resource "google_compute_instance_template" "hashi-server-template" {
  name_prefix  = "hashi-server-template-"
  machine_type = "n1-standard-2"
  region       = "europe-west3"

  disk {
    source_image = "ubuntu-1804-bionic-v20200317"
    auto_delete  = true
    boot         = true
    disk_type = "pd-standard"
  }

  network_interface {
    network = "default"
  }

  scheduling {
    automatic_restart = false 
    preemptible = true
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Debug Output

https://gist.github.com/digiology/f9693c843893e940bef590b684d17b93

### Expected Behavior

Instance "hashi-server-leader" should have been created as a preemptible instance, based on the template.

### Actual Behavior

The preemptible value seems to be picked up but not the automatic_restart value. It defaults to true and this causes an error.

Adding a 'scheduling' block to the google_compute_instance_from_template resolves the error, but this shouldn't be necessary?

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@digiology I can't repro your issue. To workaround, you may add below block in `google_compute_instance_from_template` to explicitly set `preemptible` for the instance
```
  scheduling {
    automatic_restart = false
    preemptible = true
  }
```
