### ISSUE TITLE
Request for datasource google_compute_network_peering when creating Private GKE Cluster with Private Endpoint

### ISSUE THREAD

**Issue by archyufa** [terraform-providers/terraform-provider-google#6057]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Request for datasource google_compute_network_peering

This is being requested because of a current use case where it is necessary to get details on the network peering that's automatically created with the google_container_cluster resource, when selected *enable_private_endpoint* (Optional) - When true, the cluster's private endpoint is used as the cluster endpoint and access through the public endpoint is disabled. 

This data source farther will be required to *--export-custom-routes* according to step 1 and step 2 of following document: https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#master-on-prem-routing. That we expect would be possible to accomplish with following resource: *google_compute_network_peering*.

### New or Affected Resource(s)

* google_compute_network_peering datasource

### Potential Terraform Configuration

```tf
data "google_compute_network_peering" "example" {
    name = "example"
}
```

### References

*  Instructions that can't be automated where it is required to export custom routes in order to make kubectl available for on prem-network when using private endpoint: https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#master-on-prem-routing.
* https://www.terraform.io/docs/providers/google/r/container_cluster.html
* https://www.terraform.io/docs/providers/google/r/compute_network_peering.html

**Comment by rileykarson** [comment]
Have you tried using the [`google_compute_network_peering_routes_config `](https://www.terraform.io/docs/providers/google/r/compute_network_peering_routes_config.html) resource? It was added to close this gap, since you like don't want Terraform to think that it fully manages the GKE-managed peering.

If that resource didn't work for you, please let us know!

**Comment by archyufa** [comment]
Hi @rileykarson .
It solves part of the puzzle indeed thank you! 

After GKE gets created we can take the peering naming value and manually copy in to the ` google_compute_network_peering_routes_config` and run terraform second time to --export-custom-routes.

It would of been great to make this process fully automated thought. Do you think we need to close this ticket or we can something as part of this ticket to farther automated process ?

**Comment by rileykarson** [comment]
The process should be fully automated already by using Terraform interpolations, as shown in this example: https://www.terraform.io/docs/providers/google/r/compute_network_peering_routes_config.html#example-usage-network-peering-routes-config-gke. You can actually try it for yourself! The "Open in Cloud Shell" button opens the example in a Cloud Shell environment to test the resource out.

However, if you're using a module that doesn't expose the name of the GKE-created peering (the `private_cluster_config[0].peering_name` field), that value will need to be exposed by the module authors or you'll need to use a datasource as a workaround.

For example, with Google's GKE cluster module and a module config like the following:

```hcl
module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google"
  project_id                 = "<PROJECT ID>"
  name                       = "gke-test-1"
  network                    = "vpc-01"
 ... other fields ...
}
```

You can define the following and the peering_name will be extracted:

```hcl
data "google_container_cluster" "gke_cluster" {
  name     = module.gke.name
  location = module.gke.location
  project  = "<PROJECT ID>"
}

resource "google_compute_network_peering_routes_config" "peering_gke_routes" {
  peering = data.google_container_cluster.gke_cluster.private_cluster_config[0].peering_name
  network = "vpc-01"

  import_custom_routes = true
  export_custom_routes = true
}
```

**Comment by rileykarson** [comment]
Closing based on communication out-of-band (on an internal issue) where changes to the `terraform-google-modules/kubernetes-engine/google` fixed this workflow.
