### ISSUE TITLE
Copying resources from one project to another

### ISSUE THREAD

**Issue by sagar-raythatha** [terraform-providers/terraform-provider-google#6063]
Hi,

I am very new to the Terraform so it might be the basic question.

I am working with the large projects where we have developed things in the Dev project and now we want to setup same things in the another project that we are using as the Prod project.

As a part of a task I want to copy the resources from one project to another. 
Resources need to be copied: BigQuery Tables, BigQuery views, Cloud Functions, Data flow jobs, Cloud Storage buckets.

I saw in all the tutorials we are creating resources from the base. Can we identify the configuration from one project and replicate same in another using the TerraForm script?

Thank you in advance.

**Comment by venkykuberan** [comment]
@sagar-raythatha refer this doc. if you want to maintain the states of each environment (dev, stage, prod) of the same config - https://www.terraform.io/docs/state/workspaces.html

Please let me know if this is what you are looking for ?

**Comment by venkykuberan** [comment]
I believe this one https://discuss.hashicorp.com/t/best-practice-for-reusing-with-many-environments/2704/2 will answer your question. As this is not related to GCP provider i would encourage you to raise it in Tearraform general forum for more related info.
