### ISSUE TITLE
GCP container-registry

### ISSUE THREAD

**Issue by mahmoudian1** [terraform-providers/terraform-provider-google#607]
Hi Team, 

It would be great if we can have provider for container-registry

https://cloud.google.com/container-registry/

Thanks.

**Comment by danawillow** [comment]
Hey @mahmoudian1, Container Registry is an interesting resource- it doesn't have a REST API from Google, and it spans two different gcloud commands: `gcloud container image` and `gcloud docker`. This one is probably going to take a fair amount more effort than the rest of the resources we have, so it's unlikely that someone from my team will be able to get to it soon.

In the meantime, it would be great to have an idea of what you think a sample schema might look like, so we can keep that in mind for the future.

**Comment by morgante** [comment]
@danawillow For my customer, something similar to the ECR schema would be sufficient. Ex.

```
resource "google_container_registry" "test" {
  name = "test-image"
}
```

**Comment by ndmckinley** [comment]
Okay!  It seems like this will be a data source instead of a resource, because there's no "creation" or "deletion" operation for GCR repos, and it will export "repository_url" which will be computed from data-source-level or provider-level project name, plus an optional "region" parameter.

**Comment by ndmckinley** [comment]
Could one of you folks take a look at #954 and make sure that what it does is helpful for you?  GCR is a strange one because (afaict) the repos are "available" / "created" as soon as the project is created, so there's no API requests to make here - it's all just convenient string concatenation.
