### ISSUE TITLE
The latest release note and online doc does not have the new google_os_login_ssh_public_key

### ISSUE THREAD

**Issue by sebglon** [terraform-providers/terraform-provider-google#6079]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

Terraform google provider 3.16.0

### Affected Resource(s)

* google_os_login_ssh_public_key

**Comment by rileykarson** [comment]
We have a slight delay between code landing in master and getting released, this will arrive in `3.17.0`: https://github.com/terraform-providers/terraform-provider-google/pull/6080/files
