### ISSUE TITLE
google_compute_instance: unexpected EOF panic crash

### ISSUE THREAD

**Issue by nerrage** [terraform-providers/terraform-provider-google#608]
### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
- google_compute_instance_template

### Terraform Configuration Files

-----BEGIN PGP MESSAGE-----

hQEMA9X0O2Qy6nfzAQf/aiysucAR1UytEfBtMQM2fGihYd3MJP3t/3Z1GrOCjaXW
TNwmFzG5xlRw/AQQT+h/+lYeUh1QFkX07XiyjrTT8CgXyntH3BGETz33YTy4wqVi
eWok3X9l9/1CrqKgi5OWa3FW5ntSbXGu+kdh+NgTL4zPw+QNcT01a+ap1u1xHsWC
jz3UzCZD2f4vMUiQcBaENMge102MdiD80bhMmodRSLmjg0rbO651i3FWbHQaL09c
N/S5UDbUZRZoukaLtV5jdz36K5H8Fg+cPDjYJcRhwdez9L9rcZzUtka+5/iqQn0j
Ynk4f/0/2x15zbifO5+Jiv85NsQyYKd1gkUmWqwDqdLBBwFG1B/GV5ZqdHmhTMWD
cxUa47dQ3SO0Hk1kKIfRFt1KH4O5E3phlnpNl9m55o2d//kLpREvX23ji7RU5Cnc
BlJMqTl6Fb1tLWoRvVJ9+xliG0IhjYl0rStXpbXorzmez6Ddb1AY8jXjyKlNfj5g
jPnGTSmCyuLz8H9PGW1VfG804FMqx3wsqOfJiONNcaeYOhc5du59F3KoT7Po7tvb
YC0S/3pxEOdE6idiaf58RcvI213dRzDWzqF1m/BfNpS5iR5o03vX3VcT7zpy61Oq
pTij+0h+eAW4YfYZ28atn3J1Em1MAmxAPc9rJeo59IMjLWVrASJBk3vCjH6XU6sT
6B8nVWYbea6/j3iBJCrMf+hamapFurDU2DvDb5sSvvX9eVx5K7aRwPSIDkpwESKt
w3FwMFsoNtiAwrRd50K+5Qk8XXdT96FRHXCVAbRwhsEmxYUHtEJSeF/DXyGv7slr
xbAG5hVIl6lSPDyLFKMb5ieDgdNlyVe1HtlNLsubMMe2r9jpyo98er2uFAfQGxdD
nRUyIXu8GpAenTc1LAJLHIrSL7iCL1oL2gRXMa6RtM7F+SPuA6QmaOEyb16ti6Nr
3tqE83JPkmhi
=QV0y
-----END PGP MESSAGE-----

### Panic Output
https://gist.github.com/nerrage/7cf2f2a07fecd76965f17dcb41c2e604

### Expected Behavior
Terraform to create a google compute instance template

### Actual Behavior
Crashes :(

### Steps to Reproduce
`terraform apply`

**Comment by zopanix** [comment]
@danawillow: seems pretty similar to what I'm facing, explained it here: #586

**Comment by nerrage** [comment]
I found a cause/workaround to the bug I was experiencing. While the error output was crashing on ```google_compute_instance_template```, it was actually the resource that I had defined *after* the ```google_compute_instance_template``` that had caused Terraform to crash. In particular it was this:

```
resource "google_compute_instance" "default" {
  name         = "first_instance"
  machine_type = "f1-micro"
  zone         = "us-east1-c"

  tags = ["fun", "testing"]

  boot_disk {
    initialize_params {
      image = "centos-cloud/centos-7"
    }
  }

  metadata {
    startup-script-url = "${var.bs_script}"
  }

  network_interface {
    subnetwork = "${google_compute_subnetwork.http_proxy_net.name}"

    access_config {}
  }
}
```
Changing the name of this from ```first_instance``` to ```test``` will run normally without crashing.

Full ```main.tf``` encrypted in gist if anything there would be helpful: https://gist.github.com/nerrage/49c70515e34cfc5666c4e042ddc5aa1a

**Comment by paddycarver** [comment]
Hi @nerrage! Do you happen to know which PGP public key that config was encrypted with? I'm not showing a match to the two I would expect.

**Comment by nerrage** [comment]
Hey @paddycarver, sorry if I grabbed the wrong key! I'm using https://keybase.io/hc_support with fingerprint `0B97 D8C1 9ADC 6EDE 96C0  9769 B785 CAA1 3A44 25C3`. I grabbed the support one over the main one since it belonged to "Hashicorp Security". I've gone ahead and edited and re-encrypted everything with key `91A6 E7F8 5D05 C656 30BE  F189 5185 2D87 348F FC4C` from https://keybase.io/hashicorp

**Comment by paddycarver** [comment]
No worries at all--we have a lot of keys floating around, to be honest :) I've successfully grabbed and decrypted the config. I'll take a look into this and see if I can't figure out what the issue is. Sorry for the inconvenience.

**Comment by DayFan** [comment]
Hello, I think my problem similar to this issue.  I don't know what a exact steps needed to reproduce this problema and it does not always appear . But thats starts after I start trying to recovery disk from a snapshot on a Google cloud.

Im using:
Terraform v0.11.2
+ provider.google v1.6.0
+ provider.null v1.0.0
---
## Logs
[Small](https://gist.github.com/DayFan/15db9f5c0060144cf9c47fbf536b3e12)
[Crash](https://gist.github.com/DayFan/d2f52b7692014fbcf04d761929907730)

**Comment by rileykarson** [comment]
I don't believe we've seen a similar issue since, and this was filed a long time ago; I'd imagine it's been fixed. If anyone is experiencing this still, please say so or file a new issue!
