### ISSUE TITLE
google_monitoring_notification_channel requires display_name

### ISSUE THREAD

**Issue by nesl247** [terraform-providers/terraform-provider-google#6084]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
N/A

### Affected Resource(s)

* google_monitoring_notification_channel

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

`display_name` should not be required or the description should not say it is optional

### Actual Behavior

`display_name` is required

### Steps to Reproduce

See https://www.terraform.io/docs/providers/google/r/monitoring_notification_channel.html#display_name

### Important Factoids

N/A

### References

* https://www.terraform.io/docs/providers/google/r/monitoring_notification_channel.html#display_name

**Comment by edwardmedia** [comment]
`display_name` is required. Please update doc for this field accordingly

**Comment by nesl247** [comment]
@edwardmedia Out of curiosity, why is it required? Because it isn't required on GCP's web console.
