### ISSUE TITLE
google_cloud_run_domain_mapping exports no attributes

### ISSUE THREAD

**Issue by weeco** [terraform-providers/terraform-provider-google#6096]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.24
+ provider.google v3.16.0
+ provider.google-beta v3.16.0

### Affected Resource(s)

* google_cloud_run_domain_mapping

### Terraform Configuration Files

```tf
# Domain Mapping
resource "google_cloud_run_domain_mapping" "this" {
  project  = var.project_id
  location = var.location
  name     = var.domain

  metadata {
    namespace = var.project_id
    labels    = {
      managed-by = "terraform"
    }
  }

  spec {
    route_name = google_cloud_run_service.this.name
  }
}

# Add DNS record
resource "google_dns_record_set" "this" {
  project      = var.project_id
  managed_zone = data.google_dns_managed_zone.this.name

  name = var.domain
  type = "CNAME"
  ttl  = 300

  # Status does not exist as attribute apparently
  rrdatas = google_cloud_run_domain_mapping.this.status.resource_records.rrdata
}
```

### Debug Output

terraform validate

Error: Unsupported attribute

  on ..\modules\userpanel\dns.tf line 14, in resource "google_dns_record_set" "this":
  14:   rrdatas = google_cloud_run_domain_mapping.this.status.resource_records.rrdata

This value does not have any attributes.

### Expected Behavior

I expected that the cloud_run_domain_mapping resource has all the attributes as documented here: https://www.terraform.io/docs/providers/google/r/cloud_run_domain_mapping.html

### Actual Behavior

The resource does not have any attributes at all.

### Steps to Reproduce

Create a domain mapping as shown above and try to access the status attribute from a different resource.

### References

* #0000

**Comment by venkykuberan** [comment]
@weeco `rrdata` is an array type. Use the following syntax and let me know if it helps

sample : 
rrdatas = `[google_cloud_run_domain_mapping.this.status[0].resource_records[0].rrdata] `

**Comment by weeco** [comment]
@venkykuberan Yes that fixed it, thanks for the help and sorry for submitting this issue.

The JetBrains IDEs wrongly highlight it as invalid but `terraform validate` and other commands work fine.

![image](https://user-images.githubusercontent.com/23424570/79070758-2001f200-7cd8-11ea-9402-3a4828e0b43a.png)
