### ISSUE TITLE
Add option to add taints to google_container_node_pool

### ISSUE THREAD

**Issue by eugene-chernyshenko** [terraform-providers/terraform-provider-google#6097]
There is an option to taint all nodes in the cluster

https://www.terraform.io/docs/providers/google/r/container_cluster.html#taint

But there is no clear way to set taints to the node pool

There are too many cases when you need to taint some set of separate nodes, then allow scheduling specific pods tolerated those taints 
(looks like a node pool is a good way to do it)

**Comment by edwardmedia** [comment]
@eugene-chernyshenko currently the provider does not support it. Would you please file an enhancement instead (using below link) so the team can priorize it into the backlog. Thank you
https://github.com/terraform-providers/terraform-provider-google/issues/new?template=enhancement.md
