### ISSUE TITLE
google_container_registry doesn't support import

### ISSUE THREAD

**Issue by charleskorn** [terraform-providers/terraform-provider-google#6098]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.18
+ provider.google v3.15.0
```

### Affected Resource(s)

* `google_container_registry`

### Terraform Configuration Files

```tf
resource "google_container_registry" "registry" {
  // Nothing to configure.
}
```

### Expected Behavior

`terraform import google_container_registry.registry my_project/containerregistry.googleapis.com` works

### Actual Behavior

`terraform import google_container_registry.registry my_project/containerregistry.googleapis.com` results in an error:

```
google_container_registry.registry: Importing from ID "my_project/containerregistry.googleapis.com"...

Error: resource google_container_registry doesn't support import
```

### References

* #4184
* #5593

**Comment by edwardmedia** [comment]
@charleskorn as the `Error` indicates, this resource doesn't support **import**.

**Comment by charleskorn** [comment]
@edwardmedia is there a reason why it doesn't support import? Happy to submit a PR to add it if necessary.
