### ISSUE TITLE
google_compute_instance boot_disk does not support disk self_url

### ISSUE THREAD

**Issue by migibert** [terraform-providers/terraform-provider-google#610]
Hi,

When I try to explicitly define a disk for an instance, and reference it using ${google_compute_disk.mydisk.self_link}

Terraform version : 0.10.6
Provider version : 1.1.0

Here is a sample file to reproduce the case.

```
resource "google_compute_disk" "test" {
  name  = "test"
  type  = "pd-standard"
  zone  = "europe-west1-d"
  image = "debian-cloud/debian-8"
}

resource "google_compute_instance" "test" {
  name         = "test"
  machine_type = "n1-standard-1"
  zone         = "europe-west1-d"

  boot_disk {
    source = "${google_compute_disk.test.self_link}"
  }

  network_interface {
    network = "default"
    access_config {
    }
  }
}
```

And the error message is 

> Error applying plan:
> 
> 1 error(s) occurred:
> 
> * google_compute_instance.test: 1 error(s) occurred:
> 
> * google_compute_instance.test: Error loading disk 'https://www.googleapis.com/compute/v1/projects/myproject/zones/myzone/disks/test': googleapi: Error 400: Invalid value 'https://www.googleapis.com/compute/v1/projects/myproject/zones/myzone/disks/test'. Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?', invalidParameter
> 
> Terraform does not automatically rollback in the face of errors.
> Instead, your Terraform state file has been partially updated with
> any resources that successfully completed. Please address the error
> above and apply again to incrementally change your infrastructure.

Replacing the disk self_link by the disk name works but the documentation at https://www.terraform.io/docs/providers/google/r/compute_instance.html#source-1 explicitly says 
> source - (Required) The self_link of the disk to attach to this instance.

**Comment by danawillow** [comment]
Hey @migibert, you're looking at the `source` documentation for `attached_disk`. The `boot_disk` one is https://www.terraform.io/docs/providers/google/r/compute_instance.html#source, which does say it's the name.

Conveniently, #605 is making both versions valid so I'm going to go ahead and close this issue. Thanks though!
