### ISSUE TITLE
Improve the exactly_one_of feature in magic modules

### ISSUE THREAD

**Issue by chrisst** [terraform-providers/terraform-provider-google#6103]
The `exactly_one_of` field is often added to fields where it doesn't make sense. This is usually top level fields instead of the terminal nested fields where it needs to be. This results in generated code that has `ExactlyOneOf: []string{},` instead of the correct restrictions. Magic Modules should be changed to throw a error during generation if the `exactly_one_of` field is going to generate invalid downstream code.

It would also be nice for it to support exactly_one_of on the top level resource instead of requiring the same string to be supplied on each of the nested resources.
eg:
top_level: NestedObject
 exactly_one_of ["foo", "bar", "baz"]
-- foo: String
-- bar: String
-- baz: String

**Comment by danawillow** [comment]
Closing since we're replacing MMv1 anyway and didn't get to it in the fixit
