### ISSUE TITLE
Some resource schemas lack field descriptions

### ISSUE THREAD

**Issue by xiaobaitusi** [terraform-providers/terraform-provider-google#6105]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Some resource schemas lack field descriptions, e.g ContainerCluster and ContainerNodePool.

### New or Affected Resource(s)
It's ideal to have field descriptions for every resource but the following resources are complicated enough to require inline field description in schema. 

* google_container_cluster (done by Edward)
* google_container_node_pool (done by Edward)
* google_sql_database_instance (claimed by Thomas)
* google_storage_bucket (claimed by Thomas)
* google_compute_instance (done by Edward)

**Comment by danawillow** [comment]
Adding google_bigtable_instance (and probably  _table just for consistency) as per email conversation.

**Comment by edwardmedia** [comment]
Closing the issue as **descriptions** have been added to the schema in above resources.
