### ISSUE TITLE
Can't specify machine type in `cloudbuild_trigger`

### ISSUE THREAD

**Issue by achew22** [terraform-providers/terraform-provider-google#6109]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Missing argument `machinetype`. In the [cloudbuild documentation](https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds#machinetype) they define a `machinetype` parameter that sets the size of the machine that runs your cloud build. In the proto definition of [`BuildTrigger`](https://github.com/googleapis/googleapis/blob/d8e226f702f8ddf92915128c9f4693b63fb8685d/google/devtools/cloudbuild/v1/cloudbuild.proto#L858), it defines a [`Build`](https://github.com/googleapis/googleapis/blob/d8e226f702f8ddf92915128c9f4693b63fb8685d/google/devtools/cloudbuild/v1/cloudbuild.proto#L503) message as part of a `oneof`. It would be nice to be able to set this property.

### New or Affected Resource(s)

* google_cloudbuild_trigger

### Potential Terraform Configuration

```tf
# https://www.terraform.io/docs/providers/google/r/cloudbuild_trigger.html
resource "google_cloudbuild_trigger" "build_trigger" {
  # Use the google-beta provider because the "github" block is currently in
  # beta. When Google Cloud Build promotes that to a non-beta feature we can drop
  # the -beta.
  provider = google-beta

  github {
    owner = "my-owner"
    name  = "my-thingy"

    push {
      branch = "master"
    }
  }

  build {
    machine_type = 'N1_HIGHCPU_8'
    step {
      name    = "my-docker-image"
      env = [
        "COMMIT_SHA=$COMMIT_SHA"
      ]
      args    = [
        step.value,
      ]
      timeout = "600s" # Timeout must be in seconds
    }
  }
}
```

### References

* None

Thanks so much for the great provider!

**Comment by edwardmedia** [comment]
@achew22 `machineType` is part of `build` while `cloudbuild_trigger` creates `trigger`. They represent different things. We don't have the resource for `build` yet. Can you explan why you need to specify `machineType`? If you see a business need, could you please file an `enhancement` instead using below template link?

**Comment by achew22** [comment]
@edwardmedia, please forgive my ignorance if I've messed something up here. It looks to me as if [`build`](https://www.terraform.io/docs/providers/google/r/cloudbuild_trigger.html#build) is a property of `cloudbuild_trigger`. I even have code in my terraform to the effect of:

```
# https://www.terraform.io/docs/providers/google/r/cloudbuild_trigger.html
resource "google_cloudbuild_trigger" "build_trigger" {
  # Use the google-beta provider because the "github" block is currently in
  # beta. When Google Cloud Build promotes that to a non-beta feature we can drop
  # the -beta.
  provider = google-beta

  github {
    owner = "my-owner"
    name  = "my-thingy"

    push {
      branch = "master"
    }
  }

  build {
    dynamic "step" {
      for_each = toset(var.run_targets)
    
      content {
        name    = "my-docker-image"
        env = [
          "COMMIT_SHA=$COMMIT_SHA"
        ]
        args    = [
          step.value,
        ]
        timeout = "600s" # Timeout must be in seconds
      }
    }
  }
}
```

WRT your comment:

> We don't have the resource for build yet

Maybe the breakdown is in my nomenclature. I guess it's not a resource, but maybe it's called a "block"? But inside that block or attribute or whatever it would be nice to add a machine definition. It looks like it is defined [here](https://github.com/terraform-providers/terraform-provider-google/blob/a2f617a58ddb77f3c4b685032a07e8f844ec8d6d/google/resource_cloud_build_trigger.go#L84). Maybe `machine` could be added as another key in that K/V map?

**Comment by edwardmedia** [comment]
@achew22  `A build resource in the Cloud Build API.` is from https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds. (vs. https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.triggers)  I think there is no implementation on the first resource yet.

**Comment by achew22** [comment]
In the link for [project.triggers](https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.triggers), in the JSON section it has the following inside of a section titled `Resource: BuildTrigger`:

```
  // Union field build_template can be only one of the following:
  "build": {
    object (Build)
  },
  "filename": string
  // End of list of possible types for union field build_template.
```

I believe the `build` object is a `projects.builds` embedded inside of a trigger. Can you provide me an alternative understanding of that part of the documentation?

In the Golang client for this, the first property of the [`BuildTrigger`](https://pkg.go.dev/google.golang.org/api/cloudbuild/v1?tab=doc#BuildTrigger) object is a [`Build`](https://pkg.go.dev/google.golang.org/api/cloudbuild/v1?tab=doc#Build). These appear to be generated by the proto definition of [`BuildTrigger`](https://github.com/googleapis/googleapis/blob/d8e226f702f8ddf92915128c9f4693b63fb8685d/google/devtools/cloudbuild/v1/cloudbuild.proto#L858) of the API, which also have [`Build`](https://github.com/googleapis/googleapis/blob/d8e226f702f8ddf92915128c9f4693b63fb8685d/google/devtools/cloudbuild/v1/cloudbuild.proto#L503) embedded as a message inside of them.

WRT

>  In your above HCL, why do you need to specify machineType?

I would like to specify `machineType` to run on a `N1_HIGHCPU_8` which is a "Highcpu machine with 8 CPUs" to cut down on the amount of time it takes my task to complete.

**Comment by achew22** [comment]
I've also adapted this issue to be based on the enhancement template and filled in the sections with an example usage.

Thanks again for taking the time to help me out with this!

**Comment by edwardmedia** [comment]
@achew22 Actually this is already in the backlog. Therefore I am closing this issue. Thank you for using `terraform-provider-google`
https://github.com/terraform-providers/terraform-provider-google/issues/6040
