### ISSUE TITLE
Terraform import of google_container_node_pool in state RUNNING_WITH_ERROR still doesn't work

### ISSUE THREAD

**Issue by epall** [terraform-providers/terraform-provider-google#6110]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
[ewolak/upgrade-google-provider¹]$ terraform -v
Terraform v0.12.24
+ provider.google v3.17.0
+ provider.google-beta v3.17.0
+ provider.kubernetes v1.11.1
+ provider.pagerduty v1.6.1
```

### Affected Resource(s)

* google_container_node_pool

### Debug Output

https://gist.github.com/epall/8aa705ed61be45961e2dfc0b94709971

### Expected Behavior

I expected it to import, albeit tainted, thanks to #5662.

### Actual Behavior

It still failed to import, just as with a version of of the provider before 3.10.

### References

* #3304
* #5662
* GCP Support Case #22996309 (private to me and Google, of course)

**Comment by rileykarson** [comment]
Ah, looks like a check survived those changes before that shouldn't have- I was certain I'd removed that one. I sent out a PR fixing it. It'll be available in next monday's release if it gets merged today, and the week after if it doesn't.

**Comment by rileykarson** [comment]
Ah, looks like a check survived those changes before that shouldn't have- I was certain I'd removed that one. I sent out a PR fixing it. It'll be available in next monday's release if it gets merged today, and the week after if it doesn't.
