### ISSUE TITLE
Regional Health Check

### ISSUE THREAD

**Issue by awolde** [terraform-providers/terraform-provider-google#6112]
Seems there is no way of creating regional health check here - https://www.terraform.io/docs/providers/google/r/compute_health_check.html

GCP support is already there and it looks like its GA - https://cloud.google.com/sdk/gcloud/reference/compute/health-checks/create/http

**Comment by danawillow** [comment]
I think you're looking for https://www.terraform.io/docs/providers/google/r/compute_region_health_check.html.

Also next time, please fill out the issue template- thanks!
