### ISSUE TITLE
Error 400: The request has errors, badRequest 

### ISSUE THREAD

**Issue by ilya-korotya** [terraform-providers/terraform-provider-google#6114]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.8
+ provider.google v3.17.0

### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files
```tf
provider "google" {
  project     = "${var.project}"
  region = "${var.region}"
}


resource "google_storage_bucket" "bucket" {
  name = "source-code-prometheus-fetch"
}

resource "google_storage_bucket_object" "archive" {
  name   = "function_aws.zip"
  bucket = google_storage_bucket.bucket.name
  source = "../../function_aws.zip"
}

resource "google_cloudfunctions_function" "function" {
  name        = "fetch-prometheus-data"
  description = "My function"
  runtime     = "g111"

  available_memory_mb   = 128
  source_archive_bucket = google_storage_bucket.bucket.name
  source_archive_object = google_storage_bucket_object.archive.name
  trigger_http          = true
  entry_point           = "HandleRequestGCP"

  environment_variables = {
    PROMETHEUS_LOGIN="${var.prometheus_url}"
    PROMETHEUS_URL="${var.prometheus_login}"
    PROMETHEUS_PASSWORD="${var.prometheus_password}"
  }
}

# IAM entry for all users to invoke the function
resource "google_cloudfunctions_function_iam_member" "invoker" {
  project        = google_cloudfunctions_function.function.project
  region         = google_cloudfunctions_function.function.region
  cloud_function = google_cloudfunctions_function.function.name

  role   = "roles/cloudfunctions.invoker"
  member = "allUsers"
}
```
### Expected Behavior

create google cloud function

### Actual Behavior

Error: googleapi: Error 400: The request has errors, badRequest

  on main.tf line 17, in resource "google_cloudfunctions_function" "function":
  17: resource "google_cloudfunctions_function" "function" {

**Comment by venkykuberan** [comment]
@ilya-korotya changing your runtime attribute value to `go111` should work. Please close the issue if it works.
