### ISSUE TITLE
Don't store SSL private_key in the tfstate file

### ISSUE THREAD

**Issue by hyww** [terraform-providers/terraform-provider-google#6119]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.12.24
+ provider.external v1.2.0
+ provider.google v3.17.0

```

### Affected Resource(s)

* google_compute_ssl_certificate
* google_compute_region_ssl_certificate (not tested)

### Terraform Configuration Files

```tf
resource "google_compute_ssl_certificate" "default" {
  project     = var.project
  name        = var.name
  certificate = file(var.certificate)
  private_key = file(var.private_key)
}
```

### Expected Behavior

`private_key` attribute of `google_compute_ssl_certificate` in state file should be SHA256 hash instead of actual key, as https://github.com/terraform-providers/terraform-provider-google/pull/2976 and https://github.com/GoogleCloudPlatform/magic-modules/pull/1336 claimed.

### Actual Behavior

we can see actual key in state file.

### Steps to Reproduce

1. `terraform apply`

### References

* #927

**Comment by hyww** [comment]
fix proposal: https://github.com/GoogleCloudPlatform/magic-modules/pull/3376

it will be a breaking change as https://github.com/terraform-providers/terraform-provider-google/pull/2976 should have been.

**Comment by danawillow** [comment]
Closing this for the reasons documented at https://github.com/GoogleCloudPlatform/magic-modules/pull/3376#issuecomment-620170988
