### ISSUE TITLE
google_compute_instance_group not updated when an instance is replaced

### ISSUE THREAD

**Issue by dawidpogorzelski** [terraform-providers/terraform-provider-google#6127]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.24
### Affected Resource(s)

* google_compute_instance_group
* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "kibana" {
  name                      = "kibana"
  machine_type              = var.size
  allow_stopping_for_update = true
  zone                      = data.google_compute_zones.available.names[0]

  tags = [
    "kibana"
  ]

  labels = {
    role    = "kibana"
    project = var.project
  }

  boot_disk {
    initialize_params {
      type  = "pd-standard"
      image = "debian-10"
    }
  }

  network_interface {
    network = var.vpc_name
    access_config {
      nat_ip = ""
    }
  }

  metadata_startup_script = file("${path.module}/config/startup_script.sh")

  metadata = {
    role = "kibana"
  }

  service_account {
    scopes = [
      "cloud-platform"
    ]
  }

  scheduling {
    automatic_restart = true
  }
}

resource "google_compute_instance_group" "kibana" {
  name = "kibana"
  zone = data.google_compute_zones.available.names[0]

  instances = [
    google_compute_instance.kibana.self_link
  ]

  named_port {
    name = "kibana"
    port = 3000
  }
}
```

### Expected Behavior

If you use the above configuration and make changes to `google_compute_instance` such that the instance must be replaced after the instances is replaced the `google_compute_instance_group` should be updated accordingly.

### Actual Behavior
After `google_compute_instance` is replaced, `instances` in `google_compute_instance_group` is empty and doesn't contain the self_link to the new `google_compute_instance`
Consider the following plan:

```
  # module.kibana.google_compute_instance.kibana must be replaced
-/+ resource "google_compute_instance" "kibana" {
    ....
    }

  # module.kibana.google_compute_instance_group.kibana will be updated in-place
  ~ resource "google_compute_instance_group" "kibana" {
        id        = "projects/myproject/zones/europe-west1-b/instanceGroups/kibana"
      ~ instances = [
          - "https://www.googleapis.com/compute/v1/projects/myproject/zones/europe-west1-b/instances/kibana",
        ] -> (known after apply)
        ....
    }
```
The above wants to replace `module.kibana.google_compute_instance.kibana` which triggers an update to `module.kibana.google_compute_instance_group.kibana` however, after the plan is applied, `instances` will be empty.
If I run `apply` again without any changes the plan will produce the following changes:
```
  # module.kibana.google_compute_instance_group.kibana will be updated in-place
  ~ resource "google_compute_instance_group" "kibana" {
        id        = "projects/myproject/zones/europe-west1-b/instanceGroups/kibana"
      ~ instances = [
          + "https://www.googleapis.com/compute/v1/projects/myproject/zones/europe-west1-b/instances/kibana",
        ]
        ....
    }
```
which should already have happened in the first step.

**Comment by venkykuberan** [comment]
I see that , Its a teraform core issue

**Comment by rileykarson** [comment]
This is an occurence of https://github.com/hashicorp/terraform-plugin-sdk/issues/122, Terraform Core believes that the instance group is unchanged in the (single-pass) plan and doesn't call into the provider to update it. It doesn't understand that removing the underlying instance would modify the instance group as well.

Unfortunately, this is a limitation of Terraform's single-pass plan/apply design and isn't something we can fix at the provider level. I'm closing this out based on that; filing against hashicorp/terraform or the Terraform Plugin SDK could be helpful.
