### ISSUE TITLE
Rename static IP description without recreation

### ISSUE THREAD

**Issue by sammyyu** [terraform-providers/terraform-provider-google#6130]
### Terraform Version
Terraform v0.12.13
+ provider.google v3.16.0
+ provider.google-beta v3.16.0

### Affected Resource(s)
* google_compute_global_address

### Terraform Configuration Files (if applicable)
resource "google_compute_global_address" "proj-prod-sip-cla2-lb-b0e8-com" {
  project         = "${google_project.proj-production1.project_id}"
  name            = "sip-cla2-lb-b0e8-com"
  address_type    = "EXTERNAL"
  address         = "34.95.105.148"
  description     = "a.b0e8.com"  << changing this cause recreation
}

### Issue Description
We use terraform to provision our GCP infrastructure.  There are a couple of times that I would like to change a resource rather than recreating it.  This is especially applicable for the resource google_compute_global_address where we would loose the address.

I would like to change the description without loosing the IP, it appears this is a GCP API limitation.

**Comment by edwardmedia** [comment]
Yes, I see below plan
```
  # google_compute_global_address.proj-prod-sip-cla2-lb-b0e8-com must be replaced
-/+ resource "google_compute_global_address" "proj-prod-sip-cla2-lb-b0e8-com" {
      ~ address            = "34.107.171.13" -> (known after apply)
      - address_type       = "EXTERNAL" -> null
      ~ creation_timestamp = "2020-04-16T15:06:47.251-07:00" -> (known after apply)
      ~ description        = "a.b0e8.com ---updated" -> "a.b0e8.com--updated2d" # forces replacement
      ~ id                 = "projects/myproject/global/addresses/sip-cla2-lb-b0e8-com" -> (known after apply)
        name               = "sip-cla2-lb-b0e8-com"
      - prefix_length      = 0 -> null
      ~ project            = "myproject" -> (known after apply)
      ~ self_link          = "https://www.googleapis.com/compute/v1/projects/myproject/global/addresses/sip-cla2-lb-b0e8-com" -> (known after apply)
    }
```

**Comment by rileykarson** [comment]
Unfortunately, this isn't possible. The underlying resource has no update API, so the only way to change this value is to recreate it.
