### ISSUE TITLE
Rename k8 cluster description without recreation

### ISSUE THREAD

**Issue by sammyyu** [terraform-providers/terraform-provider-google#6131]
### Terraform Version
Terraform v0.12.13
+ provider.google v3.16.0
+ provider.google-beta v3.16.0

### Affected Resource(s)
* google_container_cluster

### Terraform Configuration Files (if applicable)
resource "google_container_cluster" "prod_central-proxy-cluster-us-east1" {
  name = "central-proxy-cluster-us-east1"
  project = "${google_project.proj-production1.project_id}"
  description = "central proxy k8 cluster in us-east1 region" <<< changing this causes cluster to be recreated
  ....
}

### Issue Description
We use terraform to provision our GCP infrastructure.  There are a couple of times that I would like to fix up the description but it causes the cluster to be shutdown and recreated.  This is not suitable for uninterrupted operation.

**Comment by edwardmedia** [comment]
Yes I see it. Below is the plan 
```
Terraform will perform the following actions:
  # google_container_cluster.primary must be replaced
-/+ resource "google_container_cluster" "primary" {
      ~ additional_zones            = [] -> (known after apply)
      ~ cluster_ipv4_cidr           = "10.16.0.0/14" -> (known after apply)
      ~ default_max_pods_per_node   = 110 -> (known after apply)
      + description                 = "testing issue 6313" # forces replacement
        enable_binary_authorization = false
      + enable_intranode_visibility = (known after apply)
        enable_kubernetes_alpha     = false
```

**Comment by rileykarson** [comment]
This isn't possible in the underlying API. Clusters can only have a subset of their fields updated, shown [here](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/ClusterUpdate). You can file an issue against the API at https://issuetracker.google.com/issues/new?component=187077&template=0.
