### ISSUE TITLE
node_locations not supported in resource google_container_node_pool

### ISSUE THREAD

**Issue by BusiPlay** [terraform-providers/terraform-provider-google#6136]
The documentation states that node_locations should be a supported argument for the google_container_node_pool resource. 
https://www.terraform.io/docs/providers/google/r/container_node_pool.html#node_locations

It does note that this is in Beta, However even with the google-beta provider running terraform plan results in 👍 Error: Unsupported argument

on gke.tf line 48, in resource "google_container_node_pool" "node_pools":
  48:     node_locations      = var.cluster_node_locations

An argument named "node_locations" is not expected here.
Issue https://github.com/terraform-providers/terraform-provider-google/issues/3992 appears to add this functionality, and it looks to have been merged; am I doing something wrong?

**Comment by edwardmedia** [comment]
@BusiPlay can you post your node pool code?

**Comment by BusiPlay** [comment]
[mcld-sand-cp-central-gke.zip](https://github.com/terraform-providers/terraform-provider-google/files/4494596/mcld-sand-cp-central-gke.zip)

**Comment by edwardmedia** [comment]
@BusiPlay  what's value for `var.cluster_node_locations `?

**Comment by BusiPlay** [comment]
cluster_node_locations      = ["us-central1-a","us-central1-b",]

[tf.log](https://github.com/terraform-providers/terraform-provider-google/files/4496458/tf.log)

**Comment by BusiPlay** [comment]
I've reread the provider configuration instructions - if I explicitly specify provider="google-beta" in the resource then this works. I did not realize that was a requirement if a resource was supported in both providers.

**Comment by edwardmedia** [comment]
@BusiPlay I am glad it works for you. I am closing the issue now. Feel free to reopen if you see a need to a further discussion. Thanks
