### ISSUE TITLE
Disk autoresize defaults to false for Postgres

### ISSUE THREAD

**Issue by danielcompton** [terraform-providers/terraform-provider-google#614]
### Terraform Version
Terraform v0.10.7, Google Provider 1.1.0

### Affected Resource(s)
- google_sql_database_instance

### Terraform Configuration Files
```hcl
resource "google_sql_database_instance" "master" {
  region           = "us-central1"
  database_version = "POSTGRES_9_6"

  settings {
    tier = "db-custom-1-4096"

    backup_configuration {
      enabled = true
    }
  }
}
```

### Expected Behavior
The docs say that disk_autoresize should default to true if it isn't specified.

### Actual Behavior
The behaviour I see is that disk_autoresize defaults to false if it isn't specified. This is a computed value. The [API docs](https://cloud.google.com/sql/docs/mysql/admin-api/v1beta4/instances#settings.storageAutoResize) also say that it defaults to true, but that doesn't appear to be the case?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
This may end up being a bug in the Cloud SQL API, but I thought I'd open it here first.

**Comment by galdor** [comment]
I have the same behaviour here, I had to activate auto-resizing explicitely.
