### ISSUE TITLE
Deploying Google Cloud Function by Terraform got "Error 400: The request has errors, badRequest"

### ISSUE THREAD

**Issue by SergeSpinoza** [terraform-providers/terraform-provider-google#6140]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.24
+ provider.archive v1.3.0
+ provider.google v3.17.0
+ provider.google-beta v3.17.0

### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files

```tf
resource "google_pubsub_topic" "start_instance_event" {
  project = var.project
  name    = "start-instance-event"

  labels = {
    service = "pubsub"
    topic   = "start-instance-event"
  }
}

resource "google_storage_bucket" "cloudfunctions_fetcher_env" {
  name          = "cloudfunction-${var.project}"
  location      = var.region
  project       = var.project
  storage_class = "REGIONAL"
}

data "archive_file" "startInstancePubSub" {
  type        = "zip"
  output_path = "${path.module}/files/startInstancePubSub.zip"

  source {
    content  = "${file("${path.module}/files/startInstancePubSub/index.js")}"
    filename = "index.js"
  }

  source {
    content  = "${file("${path.module}/files/startInstancePubSub/package.json")}"
    filename = "package.json"
  }
}

resource "google_cloudfunctions_function" "startInstancePubSub" {
  name                  = "startInstancePubSub"
  runtime               = "nodejs8"
  entry_point           = "startInstancePubSub"
  available_memory_mb   = 256
  timeout               = 60
  project               = var.project
  region                = var.region
  ingress_settings      = "ALLOW_INTERNAL_ONLY"
  source_archive_bucket = google_storage_bucket.cloudfunctions_fetcher_env.name
  source_archive_object = google_storage_bucket_object.startInstancePubSub.name

  event_trigger {
    event_type = "google.pubsub.topic.publish"
    resource   = google_pubsub_topic.start_instance_event.name
  }

  labels = {
    deployment_name = "startInstancePubSub"
  }
}
```

### Debug Output

```
{
  "error": {
      "code": 400,
      "message": "The request has errors",
      "errors": [
        G] plugin.terraform-provider-google_v3.17.0_x5:       {
        "message": "The request has errors",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

### Actual Behavior

I try to deploy cloud function by terraform with use trigger PubSub, but it fails. 

### Steps to Reproduce

1. `export TF_LOG=DEBUG`
2. `terraform init`
3. `terraform plan` - this OK
4. `terraform apply` - this fail

### References

* #0000

**Comment by venkykuberan** [comment]
@SergeSpinoza i don't see which resource was failing from your debug log. Can you provide the full debug log to get a better idea?

**Comment by SergeSpinoza** [comment]
Hi! @venkykuberan https://pastebin.com/raw/R3RmY6Aj

**Comment by venkykuberan** [comment]
@SergeSpinoza our internal log shows format errors for labels block, API accepts only lower case values for `labels { key : value}`. I will create an issue for our doc update.
