### ISSUE TITLE
Cloud Composer environment fails sometimes with "project: required field is not set"

### ISSUE THREAD

**Issue by ngodec** [terraform-providers/terraform-provider-google#6145]
I've seen this bug reported multiple times for different resources in different versions of the google provider, but it's still present in  2.20.3.

We are trying to deploy Cloud Composer environments in a set of different projects. The setup is identical, and it works most of the time - but sometimes we run into this error:

```
Error: Error refreshing state: 1 error occurred:
	* module.cloud_composer_nonprod.google_composer_environment.composer_env: 1 error occurred:
	* module.cloud_composer_nonprod.google_composer_environment.composer_env: google_composer_environment.composer_env: project: required field is not set
```

Provider versions (not fixed in provider.tf, but this config is on Terraform 0.11.4 so the provider versions are the latest compatible anyway):
```
* provider.google: version = "~> 2.20"
* provider.google-beta: version = "~> 2.20"
```
Composer configuration:
```
resource "google_composer_environment" "composer_env" {
  provider = "google-beta"

  name     = "${local.name}"
  region   = "${var.gcp_region}"
  project  = "${var.project}"

  config {...}
}
```
I saw one suggestion was to export `GOOGLE_PROJECT` env var, and it resolved this issue but the next error appeared:
```
google_composer_environment.composer_env: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.11.4

### Affected Resource(s)

* google_composer_environment

### Terraform Configuration Files

```tf
terraform {
  required_version = "= 0.11.14"
  backend          "gcs"            {}
}
provider "google" {}
provider "google-beta" {}

```

### Expected Behavior

Successful plan and apply of the resource.

### Actual Behavior

The above error.
Note that the same configuration successfully deployed into a different GCP project.
For the project in question, Composer has been deployed using the same configuration, but it failed to install Python packages. Upon a rerun of Terraform, the above mentioned error appeared.

### Steps to Reproduce

1. `terraform plan`

### References

* #1618
* https://github.com/hashicorp/terraform/issues/17131

**Comment by ngodec** [comment]
Update: issue disappears when `project` and `region` are explicitly set in provider config:
```
provider "google" {
  project = "${var.project}"
  region  = "${var.gcp_region}"
}

provider "google-beta" {
  project = "${var.project}"
  region  = "${var.gcp_region}"
}
```

However, since the same deployment, with the same configuration, was working first and then failing, there must be a bug in the provider that's causing it.
All the rest of GCP modules that we have don't specify `project` and `region` in the provider config, and work well.

**Comment by edwardmedia** [comment]
@ngodec do you have GOOGLE environment variables created on your machine? You may run command `env | grep GOOGLE` in terminal to see. Here is the doc you may want to review. Let me know if this helps address your issue. https://www.terraform.io/docs/providers/google/guides/provider_reference.html

**Comment by ngodec** [comment]
Hi @edwardmedia , we have GOOGLE_APPLICATION_CREDENTIALS env var, but that's it.

**Comment by edwardmedia** [comment]
@ngodec Regarding your comments `since the same deployment, with the same configuration, was working first and then failing`, were they running on same terraform runner? Please provide detail steps so I can repro the issue. Thanks

**Comment by ngodec** [comment]
Yes, they were running on the same machine (Jenkins node) using the same user, with the following commands:
```
export GOOGLE_APPLICATION_CREDENTIALS=/home/jenkins/credentials && ./vault-auth.sh && terraform init -backend-config="${ENVIRONMENT_DIR}/backend.tfvars" && terraform plan -var-file="${ENVIRONMENT_DIR}/environment.tfvars" -out=plan_outputs/output.plan
# And then, after a pipeline approval step
terraform init -backend-config="${ENVIRONMENT_DIR}/backend.tfvars" && terraform apply -auto-approve plan_outputs/output.plan
```

`ENVIRONMENT_DIR` is composed from a set of parameters that determine our architecture, but it's safe to assume it being `environment/$GCP_PROJCT_ID/`.

I have also run these steps locally on my laptop, and saw both successful runs and errors such as described in the issue.

Hope this makes sense!

**Comment by edwardmedia** [comment]
@ngodec can you share the both success and fail terraform debug logs?

**Comment by ngodec** [comment]
Hi @edwardmedia that would prove difficult, since the error comes and goes arbitrarily

**Comment by edwardmedia** [comment]
@ngodec ` since the same deployment, with the same configuration, was working first and then failing,` does it still happen after you updated below providers? The error `project: required field is not set` appears to be clear. I would encourage you to review the doc from above link I gave you and double check your implementation. Without having your full code, it is difficult for me to pinpoint what goes wrong. Please share your code if you want me to take a closer look. Thanks
```
provider "google" {
  project = "${var.project}"
  region  = "${var.gcp_region}"
}

provider "google-beta" {
  project = "${var.project}"
  region  = "${var.gcp_region}"
}
```

**Comment by edwardmedia** [comment]
@ngodec is this still an issue with you?

**Comment by ngodec** [comment]
Hi @edwardmedia , apologies for not responding.
We haven't seen new errors wince we updated the providers.

**Comment by edwardmedia** [comment]
@ngodec I am closing this issue. Please feel free to reopen it if the issue emerges again.
