### ISSUE TITLE
Updating a google_compute_managed_ssl_certificate fails if it is used by a google_compute_target_https_proxy

### ISSUE THREAD

**Issue by rgolab** [terraform-providers/terraform-provider-google#6147]
[issue-type:bug-report]

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.20
+ provider.google-beta v3.9.0

### Affected Resource(s)

* google_compute_managed_ssl_certificate
* google_compute_target_https_proxy

### Terraform Configuration Files

```tf
resource "google_compute_managed_ssl_certificate" "cert" {
  provider = google-beta

  name    = "cert_name"
  project = var.current_project_id

  managed {
    domains = [
      "test.example.com"
    ]
  }
}

resource "google_compute_target_https_proxy" "https_proxy" {
  provider = google-beta

  name    = "proxy_name"
  url_map = google_compute_url_map.my_url_map_name.self_link
  ssl_certificates = [
    google_compute_managed_ssl_certificate.cert.self_link
  ]

  project = var.current_project_id
}
```

### Expected Behavior

When I add domains to the certificate and when I run `terraform apply` I'd like to have updated version of my certificate and the new certificate should be used by loadbalancer (`google_compute_target_https_proxy` resource).

### Actual Behavior

When I add domains to the certificate and when I run `terraform apply` I can see:
```
Error: Error reading ManagedSslCertificate: googleapi: Error 400: The ssl_certificate resource 'projects/my_project/global/sslCertificates/cert_name' is already being used by 'projects/my_project/global/targetHttpsProxies/proxy_name', resourceInUseByAnotherResource
```

I also tried to use `create_before_destroy = true` lifecycle but with this option I can see this error:
```
Error: Error creating ManagedSslCertificate: googleapi: Error 409: The resource 'projects/my_project/global/sslCertificates/cert_name' already exists, alreadyExists
```

### Steps to Reproduce

1. Add domain to the `google_comput_managed_ssl_certificate` resource
2. Run `terraform apply`

### Workaround (ugly)

As a workround I add new `google_compute_managed_ssl_certificate` resource each time when I'd like to add other domain to the loadbalancer.

### References

I think this bug is very similar to the: 
https://github.com/terraform-providers/terraform-provider-google/issues/5356
https://github.com/hashicorp/terraform/issues/10546

**Comment by edwardmedia** [comment]
I can repro this. Below is the plan in my test. 
```
      ~ managed {
          ~ domains = [ # forces replacement
                "test.example.com",
              + "test2.example.com",
            ]
        }
```

**Comment by chrisst** [comment]
@rgolab you are correct, it is the same issue as #5356. Thanks for linking. I'll close this as a duplicate and respond on that thread.
