### ISSUE TITLE
Add support for redesigned Hl7V2NotificationConfig

### ISSUE THREAD

**Issue by anubbhavm** [terraform-providers/terraform-provider-google#6152]
### Description
Previously, an HL7v2 store could only publish notifications of changes on a single Cloud Pub/Sub topic. With the new release, you can now configure HL7v2 stores to publish notifications on multiple Pub/Sub topics, and restrict notifications sent to each topic with a filter. 

### New or Affected Resource(s)

* google_healthcare_hl7_v2_store

### References

* https://cloud.google.com/healthcare/docs/reference/rest/v1beta1/projects.locations.datasets.hl7V2Stores#Hl7V2NotificationConfig

**Comment by chrisst** [comment]
This was added in https://github.com/GoogleCloudPlatform/magic-modules/pull/3417 and should be released in 3.20.0.
