### ISSUE TITLE
google_compute_route requires attribute not required by API

### ISSUE THREAD

**Issue by tedwardd** [terraform-providers/terraform-provider-google#6168]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.24
+ provider.google v3.17.0

### Affected Resource(s)

* google_compute_route

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
resource "google_compute_route" "default-route-xxxxxxx" {
  description      = "Default route to the Internet."
  dest_range       = "0.0.0.0/0"
  name             = "default-route-xxxxxxx"
  network          = google_compute_network.default.self_link
  next_hop_gateway = "https://www.googleapis.com/compute/v1/projects/xxxxxxxxxxxxxxx/global/gateways/default-internet-gateway"
  priority         = "1000"
  project          = "xxxxxxxxxxxxxxx"
}

resource "google_compute_route" "default-route-xxxxxxxxxx" {
  description = "Default route to the virtual network."
  dest_range  = "xx.xxx.x.x/16"
  name        = "default-route-xxxxxxxxxx"
  network     = google_compute_network.default.self_link
  priority    = "1000"
  project     = "xxxxxxxxxxxxxxx"
}

resource "google_compute_route" "default-route-xxxxxxxxxxxxxxxx" {
  description = "Default route to the virtual network."
  dest_range  = "xx.xxx.x.x/16"
  name        = "default-route-xxxxxxxxxxxxxxxx"
  network     = google_compute_network.relay-prod.self_link
  priority    = "1000"
  project     = "xxxxxxxxxxxxxxx"
}

resource "google_compute_route" "default-route-xxxxxxxxxxxxxxxx" {
  description      = "Default route to the Internet."
  dest_range       = "0.0.0.0/0"
  name             = "default-route-xxxxxxxxxxxxxxxx"
  network          = google_compute_network.relay-prod.self_link
  next_hop_gateway = "https://www.googleapis.com/compute/v1/projects/xxxxxxxxxxxxxxx/global/gateways/default-internet-gateway"
  priority         = "1000"
  project          = "xxxxxxxxxxxxxxx"
}

```

### Debug Output

Terraform Plan shows the issue. Debug output: https://gist.github.com/tedwardd/d492e3ba2691e493e30940cd6b5ad2f1

### Expected Behavior

An existing `google_compute_route` resource imported to TF without one of the `next_hop_gateway,next_hop_ilb,next_hop_instance,next_hop_ip,next_hop_vpn_tunnel` specified should not require one to be added.

### Actual Behavior

When attempting to plan a `google_compute_route` lacking one of `next_hop_gateway,next_hop_ilb,next_hop_instance,next_hop_ip,next_hop_vpn_tunnel`, the provider complains that it is required.

### Steps to Reproduce

1. Create a compute route without one of `next_hop_gateway,next_hop_ilb,next_hop_instance,next_hop_ip,next_hop_vpn_tunnel` through means other than Terraform.
2. Create a `google_compute_route` resource file in terraform and import it.
3. Run plan for the route

### References

See this thread discussion in the terraform channel of the GCP community slack: https://googlecloud-community.slack.com/archives/C1VNJ4EG7/p1587477594102700

> [...] my gut says that this is a bug in the provider. I suspect these fields are specified as exactly_one_of when they should have just been marked as conflicting with each other.
Can you file a bug and if possible include the REST API response for your resource? Or a terraform config that you would expect to work but is currently failing validation?

A route displaying this issue, as seen from the google cloud sdk can be found below:
```
$ gcloud compute routes describe default-route-xxxxxxxxxx

creationTimestamp: '2014-01-15T12:57:17.255-08:00'
description: Default route to the virtual network.
destRange: xx.xxx.0.0/16
id: 'xxxxxxxxxxxxx'
kind: compute#route
name: default-route-xxxxxxxxxxxxxx
network: https://www.googleapis.com/compute/v1/projects/xxxxxx-xxxxxxxx/global/networks/default
nextHopNetwork: https://www.googleapis.com/compute/v1/projects/xxxxxx-xxxxxxxx/global/networks/default
priority: 1000
selfLink: https://www.googleapis.com/compute/v1/projects/xxxxxx-xxxxxxxx/global/routes/default-route-xxxxxxxxxxxxxxxx
```

**Comment by edwardmedia** [comment]
@tedwardd **import** works fine without one of the mentioned attributes. Can you post the exact HCL and the command you used for import?

**Comment by tedwardd** [comment]
@edwardmedia minus the redactions, that is the exact HCL, unfortunately I can't share the unredacted form because it contains confidential information. The import used was:
```
terraform import google_compute_network.relay-prod projects/xxxxxx-xxxxxxxx/global/networks/relay-prod
```

Can you please show me the route you created and imported with `gcloud compute routes describe` to make sure it looks the same as the one I'm referencing? I will attempt to create a new dummy route and reproduce on that as well.

**Comment by tedwardd** [comment]
Sorry, that was the wrong import:
```terraform import google_compute_route.default-route-xxxxxxxxx projects/xxxxxx-xxxxxxx/global/routes/default-route-xxxxxxxx```

**Comment by edwardmedia** [comment]
@tedwardd Here is what I used. I created `issue6167` via gcp console. Let me know if this helps. Thanks
```tf
resource "google_compute_route" "default" {
}
```
`terraform import google_compute_route.default issue6167`

**Comment by chrisst** [comment]
@tedwardd Taking a closer look at this now. When I look in the gcp console (UI) nexthop is a required dropdown but it adds a default for you. When I tried to create a route through the API directly without a nexthop specified the API rejected the request with:
"message": "Invalid resource usage: 'A Route must specify at least one type of next hop.'."

When I described the resource from gcloud I also see the `nextHopGateway` populated. 

Before we talk about import much further, can you help me understand what the route resource looks like and how I can create a route with a similar configuration? If you can post the raw API response that would be very helpful. [This link](https://cloud.google.com/compute/docs/reference/rest/v1/routes/get?apix=true&apix_params=%7B%22project%22%3A%22project-name%22%2C%22route%22%3A%22route-name%22%7D) will allow you to call the API directly with your own credentials.

**Comment by tedwardd** [comment]
@edwardmedia Here are some more specific reproduction steps with a dummy project and network so I can provide exact steps and information:

1. Create a route through GCP console. Below is the REST response:
```
{
  "creationTimestamp": "2020-04-23T10:06:55.580-07:00",
  "description": "",
  "destRange": "10.20.0.0/16",
  "id": "3924407127691261376",
  "kind": "compute#route",
  "name": "issue6168",
  "network": "projects/ted-sandbox-254117/global/networks/default",
  "nextHopGateway": "projects/ted-sandbox-254117/global/gateways/default-internet-gateway",
  "priority": 1000.0,
  "selfLink": "projects/ted-sandbox-254117/global/routes/issue6168"
}
```

2. Create TF file:
```TF
provider "google" {
  version = "~>v3.17.0"
}

resource "google_compute_route" "default" {
  name = "issue6168"
  dest_range = "10.20.0.0/16"
  network = "projects/ted-sandbox-254117/global/networks/default"
}
```

3. Initialize the project:
```
terraform init
```

4. Import the resource: 
```
terraform import google_compute_route.default projects/ted-sandbox-254117/global/routes/issue6168
```

5. Plan project:
```
$ terraform plan

Error: "next_hop_ilb": one of `next_hop_gateway,next_hop_ilb,next_hop_instance,next_hop_ip,next_hop_vpn_tunnel` must be specified

  on route.tf line 1, in resource "google_compute_route" "default":
   1: resource "google_compute_route" "default" {



Error: "next_hop_gateway": one of `next_hop_gateway,next_hop_ilb,next_hop_instance,next_hop_ip,next_hop_vpn_tunnel` must be specified

  on route.tf line 1, in resource "google_compute_route" "default":
   1: resource "google_compute_route" "default" {



Error: "next_hop_instance": one of `next_hop_gateway,next_hop_ilb,next_hop_instance,next_hop_ip,next_hop_vpn_tunnel` must be specified

  on route.tf line 1, in resource "google_compute_route" "default":
   1: resource "google_compute_route" "default" {



Error: "next_hop_vpn_tunnel": one of `next_hop_gateway,next_hop_ilb,next_hop_instance,next_hop_ip,next_hop_vpn_tunnel` must be specified

  on route.tf line 1, in resource "google_compute_route" "default":
   1: resource "google_compute_route" "default" {



Error: "next_hop_ip": one of `next_hop_gateway,next_hop_ilb,next_hop_instance,next_hop_ip,next_hop_vpn_tunnel` must be specified

  on route.tf line 1, in resource "google_compute_route" "default":
   1: resource "google_compute_route" "default" {
```

**Comment by tedwardd** [comment]
Oh, I also went back through the comments and noticed you had asked for the output of `terraform show` after the import. Here is the result from that command against the import in the previous comment:
```
# google_compute_route.default:
resource "google_compute_route" "default" {
    dest_range       = "10.20.0.0/16"
    id               = "projects/ted-sandbox-254117/global/routes/issue6168"
    name             = "issue6168"
    network          = "https://www.googleapis.com/compute/v1/projects/ted-sandbox-254117/global/networks/default"
    next_hop_gateway = "https://www.googleapis.com/compute/v1/projects/ted-sandbox-254117/global/gateways/default-internet-gateway"
    priority         = 1000
    project          = "ted-sandbox-254117"
    self_link        = "https://www.googleapis.com/compute/v1/projects/ted-sandbox-254117/global/routes/issue6168"
    tags             = []

    timeouts {}
}
```
So, somehow the nexthop is in there without me having set anything?

**Comment by tedwardd** [comment]
OK, well, now this is odd (sorry for the back to back comments. The output from `terraform show` on the networks I'm trying to import in the production project look like this:
```
# google_compute_route.default-route-xxxxxxx:
resource "google_compute_route" "default-route-xxxxxxx" {
    description      = "Default route to the virtual network."
    dest_range       = "xx.xxx.0.0/16"
    id               = "projects/xxxxxx-xxxxxxxx/global/routes/default-route-xxxxxxx"
    name             = "default-route-xxxxxxx"
    network          = "https://www.googleapis.com/compute/v1/projects/xxxxxx-xxxxxxx/global/networks/relay-prod"
    next_hop_network = "https://www.googleapis.com/compute/v1/projects/xxxxxx-xxxxxxx/global/networks/relay-prod"
    priority         = 1000
    project          = "xxxxxx-xxxxxxx"
    self_link        = "https://www.googleapis.com/compute/v1/projects/xxxxxx-xxxxxxx/global/routes/default-route-xxxxxxx"
    tags             = []

    timeouts {}
}
```

The REST response is:
```
{
  "creationTimestamp": "2015-05-11T09:37:41.250-07:00",
  "description": "Default route to the virtual network.",
  "destRange": "xx.xxx.0.0/16",
  "id": "xxxxxxxxxx",
  "kind": "compute#route",
  "name": "default-route-xxxxxxx",
  "network": "projects/xxxxxx-xxxxxxx/global/networks/relay-prod",
  "nextHopNetwork": "projects/xxxxxx-xxxxxxx/global/networks/relay-prod",
  "priority": 1000.0,
  "selfLink": "projects/xxxxxx-xxxxxxx/global/routes/default-route-xxxxxxx"
}
```

**Comment by tedwardd** [comment]
OK! (again, sorry for the comment spam) I have more information that may be useful! Further testing indicates that these routes are the "local routes" which are created between VPC networks automatically. I created a VPC network called `dummynet` through the console:

```
{
  "autoCreateSubnetworks": false,
  "creationTimestamp": "2020-04-23T10:42:35.756-07:00",
  "description": "DummyNet",
  "id": "6689930118544780644",
  "kind": "compute#network",
  "name": "dummynet",
  "routingConfig": {
    "routingMode": "REGIONAL"
  },
  "selfLink": "projects/ted-sandbox-254117/global/networks/dummynet",
  "subnetworks": [
    "projects/ted-sandbox-254117/regions/us-east1/subnetworks/dummynet"
  ]
}
```
and noticed this route appear automatically in the routes screen. Notice the lack of `nextHopGateway`:
```
{
  "creationTimestamp": "2020-04-23T10:42:52.634-07:00",
  "description": "Default local route to the subnetwork 10.120.0.0/16.",
  "destRange": "10.120.0.0/16",
  "id": "7902573229301853555",
  "kind": "compute#route",
  "name": "default-route-64337d49beeed564",
  "network": "projects/ted-sandbox-254117/global/networks/dummynet",
  "nextHopNetwork": "projects/ted-sandbox-254117/global/networks/dummynet",
  "priority": 1000.0,
  "selfLink": "projects/ted-sandbox-254117/global/routes/default-route-64337d49beeed564"
}
```

It would appear that routes created by the user (as they would do with Terraform) will have this attribute but these automatically created "local routes" do not.

The documentation for `google_compute_routes` indicates that the following attributes are the only ones required:

* network
* name
* dest_range

However, the module behavior would suggest that it's expecting that you would include one of:

* next_hop_gateway
* next_hop_ilb
* next_hop_instance
* next_hop_ip
* next_hop_vpn_tunnel

I believe this is a case of incorrect or misleading documentation and not a code error. The documentation for the `google_compute_routes` resource should indicate something akin to:

* Requires one of: `next_hop_network,next_hop_gateway,next_hop_ilb,next_hop_instance,next_hop_ip,next_hop_vpn_tunnel`

**Comment by chrisst** [comment]
@tedwardd Thanks for the extra information, that makes it a lot more clear. It sounds like there are two things at play; The `at_least_one_of` validation is happening a bit early and thus causing an error which is legitimate but misleading. Also the `next_hop_network` is a valid field which isn't part of the `at_least_one_of` block.
I'm not sure how possible the former is as the provider doesn't have much access to when the validation logic gets executed.
The latter should hopefully be a quick fix, assuming that the validation syntax will work correctly with output only fields.

**Comment by chrisst** [comment]
The validation logic for the `exactly_one_of` isn't aware of the state of the resource as its been imported and can only currently be used to validate the config version of the resource. However since the resource can't be created with `next_hop_network` through the API it's a valid assertion that this field is output only and shouldn't be in a user's config.

Taking a step back though - compute_route cannot be modified so importing an auto-created route doesn't provide you the ability to manage that route with Terraform. It would only allow you to remove that route via Terraform which would fail as it's used by the parent resource which created it. It sounds like the "right" solution here is that you should be using a data source for this instead of a resource. Unfortunately there isn't currently a data source for `compute_route` but if this solution works for you can you file a new feature request for it?

**Comment by tedwardd** [comment]
Yes, thank you for hashing this out with me. I now understand what's going on here and I agree. These resource blocks were generated by [Terraformer](https://github.com/GoogleCloudPlatform/terraformer) and I was naively attempting to import them as discovered. Based on the information here, I agree that importing them as resources makes no sense and that a data source would be beneficially for the purposes of referencing them in other resources.

Issue closed.
