### ISSUE TITLE
The provider provider.google does not support resource type "google_bigquery_job".

### ISSUE THREAD

**Issue by dboshardy** [terraform-providers/terraform-provider-google#6171]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.24
+ provider.google v3.18.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* google_bigquery_job

### Panic Output

```

Error: Invalid resource type

  on main.tf line 13, in resource "google_bigquery_job" "job":
  13: resource "google_bigquery_job" "job" {

The provider provider.google does not support resource type
"google_bigquery_job".

```

### Expected Behavior

It should be able to recognize and deploy the resource.

### Actual Behavior

It outputs the above error message.

### Steps to Reproduce

1. Go to the official documentation: https://www.terraform.io/docs/providers/google/r/bigquery_job.html
2. Navigate to the "Example Usage - Bigquery Job Load" example
3. Click on "Open in Google Cloud Shell" 
4. `terraform init`
5. `terraform validate`

* #0000

**Comment by edwardmedia** [comment]
The code was committed 5 days ago https://github.com/terraform-providers/terraform-provider-google/commits/master/google/resource_big_query_job.go

**Comment by dboshardy** [comment]
So presumably, this will go out in 3.19.0? Looking at the changelog for 3.19, it's not included there either. And this is already "released" in so far as it shows up in the documentation.  What is the expected release procedure in this case?

**Comment by edwardmedia** [comment]
@dboshardy likely go out in next release. Thank you for reporting this issue.
