### ISSUE TITLE
[DOC] Link google_compute_region_disk_resource_policy_attachment and google_compute_disk_resource_policy_attachment docs

### ISSUE THREAD

**Issue by tpoindessous** [terraform-providers/terraform-provider-google#6178]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Hi !

In https://www.terraform.io/docs/providers/google/r/compute_region_disk_resource_policy_attachment.html

there is a line 
```
Note: This resource does not support zonal disks (google_compute_disk).
```

and in https://www.terraform.io/docs/providers/google/r/compute_disk_resource_policy_attachment.html

there is a line : 
```
Note: This resource does not support regional disks (google_compute_region_disk).
```

Could you, please, add a link to each other ? 
For example : 
```
Note: This resource does not support regional disks (google_compute_region_disk). See https://www.terraform.io/docs/providers/google/r/compute_region_disk_resource_policy_attachment.html for support of regional disks.
```

### New or Affected Resource(s)

* google_compute_disk_resource_policy_attachment
* google_compute_region_disk_resource_policy_attachment

Question : How can I submit a PR for this changes ? it seems handled by MagicModules and I read in CONTRIBUTING, that we can't contribute to MagicModules ? It's that true or I misread ?

Thanks !

**Comment by danawillow** [comment]
Hey @tpoindessous, you're welcome to propose a PR against magic modules if you'd like! The CONTRIBUTING  page is meant to express that we won't accept PRs in _this_  repo  for autogenerated resources, since the changes would just get clobbered. The docs are generated there, so typically you'd just have to do a bit of grepping to figure out where to make your edits (until you develop an understanding of how it all works).

https://github.com/GoogleCloudPlatform/magic-modules/blob/master/products/compute/terraform.yaml#L348 is where you'll want to make the change.

**Comment by tpoindessous** [comment]
Hi

Done in https://github.com/GoogleCloudPlatform/magic-modules/pull/3430

We can close this issue.

Thanks !
