### ISSUE TITLE
Add support for Node Taints in `google_container_node_pool`

### ISSUE THREAD

**Issue by davidquarles** [terraform-providers/terraform-provider-google#621]
This is in the [v1beta1 API](https://godoc.org/google.golang.org/api/container/v1beta1#NodeTaint), which I understand makes this a bit of an ask, but @rileykarson suggested filing an issue all the same.  This is definitely a flag we'd use if it existed.  I haven't worked on terraform much, so I don't know how helpful I can really be with a task this complex, but I'm working at some of the lower hanging fruit in v1 and will happily contribute support for this and other v1beta1 flags if/when support exists for both API versions.

**Comment by paddycarver** [comment]
Even though this came first, it looks like most the conversation is happening in #680. In the spirit of consolidating the conversation, I'm going to close this in favor of #680. If you think it should remain open or that it's an error to close it, feel free to reply and we can discuss it. Thanks!
