### ISSUE TITLE
google_cloudfunctions_function - egress settings Enum is invalid

### ISSUE THREAD

**Issue by gal432** [terraform-providers/terraform-provider-google#6210]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
V0.12.18

### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files

```tf
resource "google_cloudfunctions_function" "notification_cloud_function" {
  name = "my-function"
  timeout = 120
  runtime = "python37"
  source_archive_bucket = "bucket-source-code"
  source_archive_object = "my-zip.zip"
  service_account_email = "service account email"

  entry_point = "handle_pubsub_message"
  event_trigger {
    event_type = "google.pubsub.topic.publish"
    resource = "topic-name"
  }

  vpc_connector = vpc-network
  vpc_connector_egress_settings = "ALL_TRAFFIC"
}
```

### Expected Behavior

Cloud function should be created with vpc_connector_egress_settings ALL_TRAFFIC

### Actual Behavior

Error 400 from google

### References
When I took a look in the code I see that we used ALL_TRAFFIC in 
https://github.com/terraform-providers/terraform-provider-google/pull/5984

but in the docs it should be all
https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--egress-settings

**Comment by venkykuberan** [comment]
@gal432 I am not sure what value is passed to vpc_connector, make sure its in the format `projects/xxx/locations/us-central1/connectors/vpcconn`.  If you still get the error, please share your debug log. The following config worked fine for me

sample config
```
resource "google_cloudfunctions_function" "py-function" {
  name                  = "python_function"
  description           = "Pull code from GCS"
  available_memory_mb   = 256
  region                = "us-central1"
  runtime               = "python37"
  trigger_http          = true
  entry_point           = "test_function"
  timeout               = 60
  source_archive_bucket = google_storage_bucket.functions_bucket.name
  source_archive_object = google_storage_bucket_object.functions_code_archive.name
  project               = var.project_id 
 
  vpc_connector                 = google_vpc_access_connector.connector.id
  vpc_connector_egress_settings = "ALL_TRAFFIC"
}

resource "google_vpc_access_connector" "connector" {
  name          = "vpcconn"
  region        = "us-central1"
  ip_cidr_range = "10.8.0.0/28"
  network       = "default"
}
```

**Comment by gal432** [comment]
OK. the problem was when I set the connector.name instead of connector id. the cloud function did attached to the vpc_connector, but I couldn't use the vpc_connector_egress_settings.
