### ISSUE TITLE
GCS terraform_remote_state Backend | Error: Unsupported attribute 

### ISSUE THREAD

**Issue by sagarr8130** [terraform-providers/terraform-provider-google#6211]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

[root@localhost instance]# terraform  version
Terraform v0.12.24
provider.google v3.18.0

### Affected Resource(s)

- terraform_remote_state
- google_compute_instance

### Terraform Configuration Files
https://github.com/sagarr8130/Terraform_Issue/tree/master/Network
https://github.com/sagarr8130/Terraform_Issue/tree/master/Instance

### Panic Output

https://github.com/sagarr8130/Terraform_Issue/blob/master/Instance/Instance_terraform_output.txt

### Expected Behavior

Instance Should be launch with the help of terraform_remote_state

### Actual Behavior

Error: Unsupported attribute

### Steps to Reproduce

Attached complete git repo url above which will be helpful for replicate

### Important Factoids

I am using GCP service account (account.json) in both locations (Network folder and Instance Folder)

**Comment by venkykuberan** [comment]
Looks like the way you are referencing the resources isn't right.  You can refer this doc - https://www.terraform.io/docs/providers/terraform/d/remote_state.html.  

I am closing this issue as this isn't GCP specific, you can check it in Terraform general channel about remote state objects to find more related information.
