### ISSUE TITLE
Warning: planned value does not match config value

### ISSUE THREAD

**Issue by y0ssar1an** [terraform-providers/terraform-provider-google#6230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.24
+ provider.google v3.19.0
+ provider.google-beta v3.19.0
+ provider.random v2.2.1
+ provider.tfe v0.16.0
```

### Affected Resource(s)

* `google_service_account`
* `google_cloud_run_service`
* `google_compute_global_address`
* `google_compute_firewall`
* `google_vpc_access_connector`
* `google_sql_database_instance`
* `google_compute_instance`
* `google_sql_user`
* `google_compute_network`

### Terraform Configuration Files

```tf
resource "google_service_account" "account" {
  account_id  = var.name
  description = "The service account used by Cloud SQL Proxy to connect to the db"
}
```

### Debug Output

```
2020/04/27 12:10:58 [WARN] Provider "registry.terraform.io/-/google" produced an unexpected new value for module.dbproxy.module.serviceaccount.google_service_account.account, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .display_name: was null, but now cty.StringVal("")
```

```
2020/04/27 12:10:58 [WARN] Provider "registry.terraform.io/-/google" produced an invalid plan for module.api.google_cloud_run_service.api, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .metadata: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .template[0].spec[0].containers[0].resources: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
```

```
2020/04/27 12:11:49 [WARN] Provider "registry.terraform.io/-/google-beta" produced an invalid plan for module.vpc.google_compute_firewall.allow_ssh, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .priority: planned value cty.NumberIntVal(1000) does not match config value cty.NullVal(cty.Number)
```

### Expected Behavior

The plan should've run without warnings.

### Actual Behavior

My logs are full of warnings like the above. I think some of these warnings would be resolved by updating `terraform-plugin-sdk`, but I don't really know. The latest version is v1.10.0. The version in `terraform-provider-google` is v1.4.0 from Nov 2019.

### Steps to Reproduce

1. `TF_LOG=TRACE
2. `terraform apply`

* #0000

**Comment by venkykuberan** [comment]
This is not a provider issue, its SDK compatibility issue. Please refer this https://discuss.hashicorp.com/t/context-around-the-log-entry-tolerating-it-because-it-is-using-the-legacy-plugin-sdk/1630 to learn more. 
 Closing this as its not provider related.

**Comment by y0ssar1an** [comment]
@venkykuberan, would updating `terraform-plugin-sdk` silence these warnings?

I don't understand this:
> This is a quirk of the compatibility bridge that allows the existing (0.11-oriented) SDK to be compatible with Terraform 0.12 until a 0.12-native SDK is available.

I thought `terraform-plugin-sdk` _was_ the 0.12-native SDK. The warnings reference an exemption for the "legacy plugin SDK", but AFAICT `terraform-provider-google` isn't using the legacy SDK (`github.com/hashicorp/terraform`).
