### ISSUE TITLE
google_bigquery_job resource ignores use_legacy_sql flag

### ISSUE THREAD

**Issue by kemer15** [terraform-providers/terraform-provider-google#6231]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.18
+ provider.google v3.19.0
+ provider.google-beta v3.19.0
### Affected Resource(s)
google_bigquery_job 
### Terraform Configuration Files

```tf
resource "google_bigquery_job" "job" {
  project = data.google_project.current-project.project_id
  job_id  = "n"
  query {
    query          = "SELECT Id FROM n.Some_view"
    use_legacy_sql = false
  }
}
```

### Expected Behavior
Big Query job uses Standard SQL dialect. Use Legacy SQL should be false.
### Actual Behavior
Big Query job uses Legacy SQL dialect. Use legacy SQL is true.
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by venkykuberan** [comment]
Unless you set to `false`, provider submit the request with default value `true` to API. Provider can't validate the type of SQL being sent and also i see API sending back the response with `useLegacySql=true` for the standard SQL request.  As provider is working as expected i am closing this issue. Please reopen if you feel otherwise.

Terraform config
```
resource "google_bigquery_job" "job" {
  project = var.project_id
  provider = google-beta
  job_id  = "n23"
  query {
    query          = "SELECT * FROM test_dataset.summary LIMIT 1000"
    # use_legacy_sql = false
  }
}
```

sample partial API response just for reference

```
"configuration": {
     "query": {
       "query": "SELECT * FROM test_dataset.summary LIMIT 1000",
       "destinationTable": {
         "projectId": "xx-xxx-xx",
         "datasetId": "_de49512d56391c1a7038eb1234343d4df786266f",
         "tableId": "anonff88a2d1b0eb23db4e95c8f1b2032432cb5befee"
       },
       "createDisposition": "CREATE_IF_NEEDED",
       "writeDisposition": "WRITE_TRUNCATE",
       "priority": "INTERACTIVE",
       "useQueryCache": true,
       "useLegacySql": true
     },
     "jobType": "QUERY"
   }
```

**Comment by kemer15** [comment]
> Unless you set to `false`, provider submit the request with default value `true` to API. Provider can't validate the type of SQL being sent and also i see API sending back the response with `useLegacySql=true` for the standard SQL request. As provider is working as expected i am closing this issue. Please reopen if you feel otherwise.
> 
> Terraform config
> 
> ```
> resource "google_bigquery_job" "job" {
>   project = var.project_id
>   provider = google-beta
>   job_id  = "n23"
>   query {
>     query          = "SELECT * FROM test_dataset.summary LIMIT 1000"
>     # use_legacy_sql = false
>   }
> }
> ```
> 
> sample partial API response just for reference
> 
> ```
> "configuration": {
>      "query": {
>        "query": "SELECT * FROM test_dataset.summary LIMIT 1000",
>        "destinationTable": {
>          "projectId": "xx-xxx-xx",
>          "datasetId": "_de49512d56391c1a7038eb1234343d4df786266f",
>          "tableId": "anonff88a2d1b0eb23db4e95c8f1b2032432cb5befee"
>        },
>        "createDisposition": "CREATE_IF_NEEDED",
>        "writeDisposition": "WRITE_TRUNCATE",
>        "priority": "INTERACTIVE",
>        "useQueryCache": true,
>        "useLegacySql": true
>      },
>      "jobType": "QUERY"
>    }
> ```
Everything works correctly when we use Legacy SQL dialect. But when I set use_legacy_sql = false to create a job with Standard SQL dialect it doesn't change dialect of result job. Created BQ job always has "Use legacy SQL" = false.

**Comment by kemer15** [comment]
@venkykuberan I think the issue should be reopened because setting use_legacy_sql=false doesn't affect the BQ job.
