### ISSUE TITLE
Race condition with google_compute_route and VPC peering operations

### ISSUE THREAD

**Issue by ct-dh** [terraform-providers/terraform-provider-google#6233]
I don't have time to find a small reproducable snippet for this issue at the moment, but hoping someone has some advice in the interim.

I am trying to create a google_compute_route resource but it regularly errors in our pipeline with the below error: 

```
2766 Error: Error creating Route: googleapi: Error 400: There is a peering operation in progress on the local or peer network. Try again later., badRequest
2767   on .terraform/modules/test_runtime/modules/test-runtime/network.tf line 27, in resource "google_compute_route" "default":
2768   27: resource "google_compute_route" "default" {
```

I can see there was previous issue (https://github.com/terraform-providers/terraform-provider-google/issues/3034) requiring a mutex to be added to the peering create operations to allow for multiple peerings to be in the same terraform configuration, but it would appear that this needs to be extended to other resources such as `google_compute_route` too as they will be rejected by the GCP API if peering operations are in progress?

**Comment by edwardmedia** [comment]
@ct-dh could you share larger debug log that contains multiple requests & responses? If could, please also share your HCL so we could try to repro?

**Comment by ct-dh** [comment]
This is from a pretty large code base that I can't share the HCL for unfortunately. If it helps, I think the peering operation might be from bringing up a GKE private cluster as I believe that uses service networking and peers the network to a network outside of our org at the same time another module is trying to create a route (timing dependent). I will try and get a debug log that I can send.

**Comment by ct-dh** [comment]
I have tried to knock up a minimal repro configuration but the timing with a few resources never seems to line up, so the route tends to get created before the GKE cluster even starts being created. Are there any tips for recreating this type of "timing" issue? Is there any way to add some determinism to trigger 2 resources to be created in parallel?

**Comment by ct-dh** [comment]
Is there a mechanism to provide a debug log that isn't public?

**Comment by ct-dh** [comment]
@emilymye / @edwardmedia Thanks for sorting this so quickly. I was trying to look at the code but couldn't tell, will this mutex also protect the peering created by the `google_container_cluster`?
