### ISSUE TITLE
produced an invalid new value for .metadata["ssh-keys"]

### ISSUE THREAD

**Issue by DurisetiR** [terraform-providers/terraform-provider-google#6244]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Versions
* Terraform: ~>0.12.0
* google: ~>3.19.0
* tls: ~>2.1.1
* null: ~>2.1.2
* google: ~>3.19.0

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
main.tf
module "keypair" {
  source = "./modules/keypair"
}
module "vm" {
# outputs from the keypair module
}

vm.tf
resource "google_compute_instance" "sandbox" {
depends_on = [elastic_ip, public_key_file]
  metadata = {
    ssh-keys = "dummyuser:${fileexists(public_key_file) ? file(public_key_file) : "null"}"
  }
}
```

### Panic Output
terraform plan
machine_type         = "n1-standard-4"
      metadata             = {
          "ssh-keys" = **_"dummyuser:null_**"
        }

terraform apply

Provider produced inconsistent final plan
When expanding the plan for module.sandbox.google_compute_instance.sandbox to
include new values learned so far during apply, provider
"registry.terraform.io/-/google" produced an invalid new value for
.metadata["ssh-keys"]: was cty.StringVal("dummyuser:null"), but now
cty.StringVal("dummyuser:ssh-rsa
AAAAsdfsafasfasfsafsadfsadfsdfsadfsdafsadfsdaf\n").
This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### Important Factoids
If I run terraform apply after this error terraform apply will work. 

### References

* #0000

**Comment by edwardmedia** [comment]
@DurisetiR I am not super what was the problem. Could you clarify how I can repro the issue? For example: what is the expected behavior and what is the actual behavior?  It would be better if you can provide the more lines of your related code. Thanks

**Comment by DurisetiR** [comment]
@edwardmedia so I am trying to create an SSH key using the tls and null providers, then I want to use that ssh-key as a metadata for a gcp_compute_instance. 
During terraform plan since the ssh-key files does not exist yet the meta-data picks up null based on the logic i put in > ${fileexists(public_key_file) ? file(public_key_file) : "null"}
immediately when I do apply then the first the ssh-key gets created, then the ssh-key gets added to the gcp_compute_instance, at this point the provider complains of inconsistent plan for apply.

**Comment by emilymye** [comment]
This is somewhat expected behavior, and something we at the provider level actually don't manage (despite the error message). The way in which you've interpolated this value means that, at plan-time, the expression can be resolved and thus resolved at plan-time. Terraform doesn't expect a difference between plan and apply time output for these values, and throws an error. 

This likely can be resolved by using a variable to set this ssh-key when you expect to have the file present. Terraform then treats the variable value as only known at apply time.
