### ISSUE TITLE
Snapshot schedule change causes deatchDisk operation on VM instance

### ISSUE THREAD

**Issue by pleegor** [terraform-providers/terraform-provider-google#6248]
When I create and update snapshot schedule, a backup disk (there are total 3 disks attached) is being attached to the instance prior all changes is being detached (I can see detachDisk operation in logs) and after couple of hours it is being re-attached. Does anyone else experience similar behavior? I am not sure if I am hitting a bug and this is why I am submitting it as a question.

**Comment by emilymye** [comment]
By snapshot schedule, do you mean you are using `google_compute_disk_resource_policy_attachment`? 

We don't do anything with attachDisk or detachDisk in Terraform while editing the resource, so it seems like it's just the API detaching/reattach the disk after the schedule has been added. If you could show us your config and tell us which disk is getting detached/reattached, we might be able to help more, but it's also likely that it's just the intended behavior for adding resource policies (see [the API endpoint](https://cloud.google.com/compute/docs/reference/rest/v1/disks/addResourcePolicies).

**Comment by pleegor** [comment]
Yes ` google_compute_disk_resource_policy_attachment` is the resource I am using. I can see that detachDisk operation is being performed by terraform api. I do not think detaching 1 out 3 disks can be considered as intended behavior (the same backup disk is being detached in various projects managed by the same terraform repo). Disk is being detached by "google-api-go-client/0.5 HashiCorp Terraform/0.12.24 *" user_agent according to logs. This is my policy attachment resource:

`
resource "google_compute_disk_resource_policy_attachment" "backups_volume_snapshot" {
name    = google_compute_resource_policy.tableau_snapshots.name
disk    = google_compute_disk.tableau_backup_volume.name
project = var.project_id
zone    = var.zone
  }
`
Again I can confirm that attachment and detachment of this specific disk is being performed through terraform according to logs I can see in GCP.

**Comment by emilymye** [comment]
Hi @pleegor - Sorry, to be more specific, I'm curious about the output of the Terraform debug logs (output when running Terraform with `TF_LOG=DEBUG`) and whether attach/detachDisk is being called directly by Terraform, which I don't believe it is.

While the user agent might be passed along to track the original caller, we aren't actually calling attach/detachDisk methods based on the [code](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_disk_resource_policy_attachment.go) - it would very strange if we _were_ directly calling it and it only applied to specific disks. The only way we actually detach/attach disks in the Google provider overall appears to be when `google_compute_instance.attached_disk` values has changed and we update the disks on an instance. 

I suspect that the API method we do call ([addResourcePolicies](https://cloud.google.com/compute/docs/reference/rest/v1/disks/addResourcePolicies)) indirectly calls this. If so, the API itself is making the decision to detach/reattach the disk when we attach a resource policy, and we (the provider) don't have direct control over that. 

In that case, what we can do is escalate by filing an issue againt the Compute API to ask why detachment is happening only for the given disk, and whether or not we can prevent it by configuring it some other way. I'm not sure why this disk specifically, and it's not mentioned in the [guide](https://cloud.google.com/compute/docs/disks/scheduled-snapshots#attach_snapshot_schedule)

**Comment by pleegor** [comment]
I use `google_compute_attached_disk` resource since that specific volume is used for backup purposes and it needs to be attached to only one instance out of 3 instances I create with `google_compute_instance` resource.  Two [OS and data] volumes present on all instances are being attached via `google_compute_instance.attached_disk` values are not being detached and re-attached according to terraform plan; this problem only occurs with the disk attached separately via `google_compute_attached_disk` resource. Hopefully this helps.

**Comment by emilymye** [comment]
Something to note, from our [docs](https://www.terraform.io/docs/providers/google/r/compute_attached_disk.html) for google_compute_attached_disk:

> Note: When using google_compute_attached_disk you must use lifecycle.ignore_changes = ["attached_disk"] on the google_compute_instance resource that has the disks attached. Otherwise the two resources will fight for control of the attached disk block.

If the plan output you're seeing is only the instance being updated with the `attached_disk` block on the instance being removed, you might need to ignore lifecycle changes on the instance.

**Comment by pleegor** [comment]
@emilymye your last comment was spot on! After adding lifecycle policy things are back to normal. Thank you!
