### ISSUE TITLE
Enable multiple project services

### ISSUE THREAD

**Issue by jeremad** [terraform-providers/terraform-provider-google#6249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `google_project_service` ressource allows to enable a service API on a project. When manipulating multiple projects, it would be nice to provide a way to enable multiple service APIs.

It is easy to loop around APIs when manipulating one or two projects, however for N projects this does not scale easily.

### New or Affected Resource(s)

* google_project_services

A new resource that will enable multiple service APIs, using the [batchEnable](https://cloud.google.com/service-usage/docs/reference/rest/v1/services/batchEnable) endpoint

### Potential Terraform Configuration

```tf
resource "google_project_services" "services" {
  project  = "my-project"
  services = ["cloudbilling.googleapis.com", "clouderrorreporting.googleapis.com"] 
}
```

### References

https://cloud.google.com/service-usage/docs/reference/rest/v1/services/batchEnable

**Comment by jeremad** [comment]
Well, looking at make a PR to do this, I realized that this API used to exist. I didn't find why it was removed, though

**Comment by jeremad** [comment]
https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#resource-google_project_services
https://registry.terraform.io/modules/terraform-google-modules/project-factory/google/3.3.0/submodules/project_services

OK I found out what I needed to know, I can close this.

**Comment by jeremad** [comment]
So, I actually this module cannot be used with multiple projects programatically because of https://github.com/hashicorp/terraform/issues/17519.

So it would still be nice to have a non-authoritative version of `google_project_services`

**Comment by ndmckinley** [comment]
Hi there!  It seems like a [resource-level `for_each`](
https://www.terraform.io/docs/configuration/resources.html#for_each-multiple-resource-instances-defined-by-a-map-or-set-of-strings) on `google_project_service` would do what you need - is that right?

**Comment by ndmckinley** [comment]
Let me provide a little more:

```
variable "services" {
  type = list(string)
}

resource "google_project_service" "services" {
  for_each = toset(var.services)
  project = "my-project"
  service = each.value
}
```

And then you can set the variable in a tf.vars file or however you prefer to set variables.

Is that helpful?

**Comment by jeremad** [comment]
The problem is when you need to iterate over services and projects!

**Comment by ndmckinley** [comment]
Ah yeah, `setproduct` is a good solution for that.  :)

Behind the scenes we do support the GCP API service enablement batch mode.  I'm going to close this issue since the `setproduct` solution is the best one right now and should get you the relatively-low request volume you're looking for.

**Comment by jeremad** [comment]
OK, I understand. Thank you for you support anyways ! :+1:
