### ISSUE TITLE
Terraform Crash: Unexpected EOF

### ISSUE THREAD

**Issue by zopanix** [terraform-providers/terraform-provider-google#625]
### Terraform Version
`0.10.7`

### Terraform Provider Google
`1.0.0`
`1.0.1`

### Affected Resource(s)
All resources

### Terraform Configuration Files
The configuration files are a bit to long to just give out, but the same files were used last Thursday and worked on another Google Cloud Project

### Panic Output
https://gist.github.com/zopanix/e7ffd16f730552170aa28de0c716669b

### Expected Behavior
Apply successfull

### Actual Behavior
Terraform Crash

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I know I didn't clean up the project after last failure, so some resources already exist, But I had the same thing even when the resources did not exist.

### References
- #608 
- #586 
- #553

**Comment by zopanix** [comment]
@danawillow: I can still reproduce this one. I'll test on another google project when I have a chance to

**Comment by zopanix** [comment]
@danawillow: I wasn't succesfull in reproducing the bug. So I tried something since on the existing infrastructure and it worked.
The steps were:
* terraform destroy (succesfull)
* delete exisiting statefile ( This statefile had evolved from older version of terraform (0.8.X+) )
* recreate everything from scratch
* works

I cannot offer you anything else then what I already gave you. This might even be a terraform core bug using older TF statefiles so you can close the issue if you want to. Just noting this for future people which have the same problem and are in the same situation as I am.

Thx for the follow up on the issues

**Comment by danawillow** [comment]
Hey @zopanix, no need to tag me in issues- all of them get looked at by someone on our team within a week of filing (usually sooner). I'll go ahead and close this as per your last comment though.
