### ISSUE TITLE
400 Error with autoscaling.knative.dev/minScale on google_cloud_run_service

### ISSUE THREAD

**Issue by bharathkkb** [terraform-providers/terraform-provider-google#6255]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.20
+ provider.archive v1.3.0
+ provider.google v3.18.0
+ provider.google-beta v3.18.0

### Affected Resource(s)

* google_cloud_run_service

### Terraform Configuration Files

```tf
resource "google_cloud_run_service" "default" {
  name     = "cloudrun-srv"
  location = "us-central1"
  project  = "foo"

  template {
    spec {
      containers {
        image = "gcr.io/cloudrun/hello"
      }
    }
    metadata {
      annotations = {
        "autoscaling.knative.dev/minScale" = "1"
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
}
```
and
```tf
resource "google_cloud_run_service" "default" {
  name     = "cloudrun-srv"
  location = "us-central1"
  project  = "bar"
  metadata {
      annotations = {
        "autoscaling.knative.dev/minScale" = "1"
      }
    }

  template {
    spec {
      containers {
        image = "gcr.io/cloudrun/hello"
      }
    }
    
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
}
```
### Debug Output
https://gist.github.com/bharathkkb/7a724c443111e93df6c9a2948bdb0f5e
### Expected Behavior

1) No error thrown
2) A better and more descriptive error surfaced like `autoscaling.knative.dev/minScale' is not a supported annotation.`

### Actual Behavior

As per the docs, autoscaling.knative.dev/minScale is a supported annotation. This happens both at template level and service level. https://www.terraform.io/docs/providers/google/r/cloud_run_service.html#metadata

Throws error
`Error: Error updating Service [..] : googleapi: Error 400: The request has errors`

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rileykarson** [comment]
I've got a bug filed against the Cloud Run team upstream whose solution would also fix this, based on https://github.com/terraform-providers/terraform-provider-google/issues/6099. b/153896811 for Google-internal reference.

**Comment by rileykarson** [comment]
Deduping this to https://github.com/terraform-providers/terraform-provider-google/issues/6263, which would solve it generally.
