### ISSUE TITLE
google_cloud_run_service return HTTP response 404 with body during creation

### ISSUE THREAD

**Issue by Ameen-Alam** [terraform-providers/terraform-provider-google#6258]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
terraform version: v0.12.24
Google provider: v3.19.0

### Affected Resource(s)
google_cloud_run_service

### Terraform Configuration Files

provider "google" {
  credentials = file("skills-online.json")
  project     = "skills-online"
  region      = "asia-south1"
}

resource "google_project_service" "run" {
  service = "run.googleapis.com"
}

resource "google_cloud_run_service" "skills-online" {
  name     = "skills-online"
  location = "asia-south1"

  template {
    spec {
      containers {
        image = "gcr.io/skills-online/imagename"
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
}

### Debug Output

https://gist.github.com/Ameen-Alam/7765d293028a9fd7b29630edfb8e45a3

### Expected Behavior

Cloud run service created

### Actual Behavior

google_cloud_run_service.skills-online: Creating...

Error: Error creating Service: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/apis/serving.knative.dev/v1/namespaces/skills-online/services</code> was not found on this server.  <ins>That’s all we know.</ins>

  on main.tf line 11, in resource "google_cloud_run_service" "skills-online":
  11: resource "google_cloud_run_service" "skills-online" {

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

        image = "gcr.io/skills-online/imagename"
        image = "gcr.io/skills-online/---------------"
due to security reason, I wrote the name of the image as a dummy

### References

https://github.com/terraform-providers/terraform-provider-google/issues/5420

*#5420

**Comment by edwardmedia** [comment]
@Ameen-Alam I noticed you choose `location = "asia-south1"`. This location is not listed in 
https://cloud.google.com/run/docs/locations

Cloud Run is available in the following regions:
- asia-east1 (Taiwan)
- asia-northeast1 (Tokyo)
- europe-north1 (Finland)
- europe-west1 (Belgium)
- europe-west4 (Netherlands)
- us-central1 (Iowa)
- us-east1 (South Carolina)
- us-east4 (Northern Virginia)
- us-west1 (Oregon)

**Comment by Ameen-Alam** [comment]
**The google cloud run service is not available in asia-south1 region**

which is why 
"Error creating Service: googleapi: got HTTP response code 404 with body:" 
is occurring, during creation google_cloud_run_service

I changed the region in my code, according to this list 
https://cloud.google.com/run/docs/locations.

**Cloud Run is available in the following regions:**

- asia-east1 (Taiwan)
- asia-northeast1 (Tokyo)
- europe-north1 (Finland)
- europe-west1 (Belgium)
- europe-west4 (Netherlands)
- us-central1 (Iowa)
- us-east1 (South Carolina)
- us-east4 (Northern Virginia)
- us-west1 (Oregon)

I have selected asia-east1 (Taiwan) region.
The error has been resolved.

Thanks, @edwardmedia for quickly respond.
