### ISSUE TITLE
google_compute_router_peer  import not populate the advertise_mode

### ISSUE THREAD

**Issue by sebglon** [terraform-providers/terraform-provider-google#6259]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

$ terraform versionTerraform v0.12.23
+ provider.google v3.19.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

* google_compute_router_peer

### Terraform Configuration Files

```tf
resource "google_compute_router_peer" "gcp-router2-peer" {
  count   = length(var.vpns)
  project = google_project.main_project.project_id
  region  = var.vpns[count.index]["region"]

  name            = "gcp-to-aws-bgp2-x"
  router          = "gcp-router2-x"
  peer_ip_address = "1.1.1.1"
  peer_asn        = "7224"
  interface       = "gcp-to-aws-interface2-x"
  advertise_mode  = "DEFAULT"
}
```

### Expected Behavior

The import populate the `advertise_mode`

### Actual Behavior

The import not populate the `advertise_mode` field as `DEFAULT` and the next plan want to re-create the resource to set the 
### Steps to Reproduce

1. `terraform import module.project.google_compute_router_peer.gcp-router2-peer[0] my-project/europe-west3/gcp-router2-europe-west3/gcp-to-aws-bgp2-
europe-west3`
```
module.project.google_compute_router_peer.gcp-router2-peer[0]: Importing from ID "my-project/europe-west3/gcp-router2-europe-west3/gcp-to-aws-bgp2-europe-we
st3"...
module.project.google_compute_router_peer.gcp-router2-peer[0]: Import prepared!
  Prepared google_compute_router_peer for import
module.project.google_compute_router_peer.gcp-router2-peer[0]: Refreshing state... [id=projects/my-project/regions/europe-west3/routers/gcp-router2-europe-w
est3/gcp-to-aws-bgp2-europe-west3]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

2. `terraform plan -target=module.project.google_compute_router_peer.gcp-router2-peer[0]` 
```
 # module.project.google_compute_router_peer.gcp-router2-peer[0] must be replaced
-/+ resource "google_compute_router_peer" "gcp-router2-peer" {
      + advertise_mode            = "DEFAULT" # forces replacement
      - advertised_groups         = [] -> null
      - advertised_route_priority = 0 -> null
      ~ id                        = "projects/my-projectv/regions/europe-west3/routers/gcp-router2-europe-west3/gcp-to-aws-bgp2-europe-west3" -> (known after apply)
        interface                 = "gcp-to-aws-interface2-europe-west3"
      ~ ip_address                = "1.1.1.1" -> (known after apply)
      + management_type           = (known after apply)
        name                      = "gcp-to-aws-bgp2-europe-west3"
        peer_asn                  = 7224
        peer_ip_address           = "169.252.254.254"
        project                   = "my-project"
        region                    = "europe-west3"
        router                    = "gcp-router2-europe-west3"

      - timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by sebglon** [comment]
It seem fixed on the 2.17 but not reported on 3.x
https://github.com/terraform-providers/terraform-provider-google/pull/4503

**Comment by sebglon** [comment]
Fix is available here : https://github.com/GoogleCloudPlatform/magic-modules/pull/3454

**Comment by venkykuberan** [comment]
Thanks for the PR, this issue will be closed after the PR approved/merged
