### ISSUE TITLE
Add ability to choose between IP Aliases and Routes

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#6268]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

(API-side changes in https://container.googleapis.com/$discovery/rest?version=v1beta1, not yet seeing on https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters)

In addition to `useIpAliases`, `IPAllocationPolicy` now supports `useRoutes`. We got rid of `use_ip_aliases` [in 3.0.0](https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#ip_allocation_policy-will-catch-out-of-band-changes-use_ip_aliases-removed) because it was the only possibility when a user specified an `ip_allocation_policy` block. Whoever implements this should think about the UX of the change and whether it makes sense to add the two booleans vs an enum, and whether these should be inside or outside the `ip_allocation_policy` block.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* b/150889533 (there's some design ideas in here that are worth thinking about)
* https://github.com/terraform-providers/terraform-provider-google/issues/5842

**Comment by rileykarson** [comment]
fwiw, copy-paste of my thoughts from inside that bug:

>  I've been trying to think of ways to flip the default to VPC-native in Terraform for a little while, since newer GKE features tend to rely on it. I filed https://github.com/terraform-providers/terraform-provider-google/issues/5842 to capture my thoughts, but I think it'd be better to conform to the API's flip instead.

> The API will return an ip_allocation_policy block on every response after this change, including one of use_ip_aliases or use_routes set to true, right? So if I send both set to false, one of them will come back true.

> Right now, Terraform assumes that ip_allocation_policy being set means a cluster is VPC-native, and unset means it's routes-based. However, I see that allowRouteOverlap in beta can also apply to both types of clusters. It's probably most clear for our users if we transform the schema clientside a bit to collapse the pair of use_ booleans to an enum ("networking_mode" with "VPC NATIVE" and "ROUTES" as options, probably) at the top level, and to make allow_routes_overlap a top-level field as well.
