### ISSUE TITLE
Add support for yaml file to organization policy

### ISSUE THREAD

**Issue by c8w** [terraform-providers/terraform-provider-google#627]
The gcloud CLI command does allow this ability:
https://cloud.google.com/resource-manager/docs/organization-policy/quickstart-list-constraints
gcloud alpha resource-manager org-policies set-policy \
  --project [PROJECT_ID] /tmp/policy.yaml

### References
GH-523 Add support for org policies at the organization level
This was added recently but does not support applying an org policy with a yaml file.

### Affected Resource(s)
- google_organization_policy

**Comment by danawillow** [comment]
@srivasta

**Comment by srivasta** [comment]
Update: Started looking at this

**Comment by paddycarver** [comment]
At the moment, our policy is to specify things like this as HCL. If someone has a good reason for why this needs to be specified as YAML or why specifying this as YAML opens up new use cases for them, I'd love to hear it in a new issue.
