### ISSUE TITLE
VMware: Terraform crashed with OVF deployment

### ISSUE THREAD

**Issue by harashee** [terraform-providers/terraform-provider-google#6291]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

auto@auto:~/terraform-lab/vmware-lab$ terraform -v
Terraform v0.12.24
+ provider.vsphere v1.18.0

+ VMware vCenter - 6.0

### Affected Resource(s)

* VMware_vSphere

### Terraform Configuration Files

provider "vsphere" {
  user           = "root"
  password       = "vmware"
  vsphere_server = "x.x.x.x"
  allow_unverified_ssl = true
  version = "1.18.0"
}
data "vsphere_datacenter" "dc" { 
	name = "DC"	
	 }
data "vsphere_datastore" "datastore" { 
	name = "datastore" 
	datacenter_id = data.vsphere_datacenter.dc.id 
}
data "vsphere_host" "host" { 
	name = "x.x.x.x" 
	datacenter_id = "${data.vsphere_datacenter.dc.id}" 	
	}
data "vsphere_compute_cluster" "cluster" {
  name          = "Automation"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
resource "vsphere_virtual_machine" "vmFromRemoteOvf" { 
	name = "vm1" 
	resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
	datastore_id = data.vsphere_datastore.datastore.id 
	host_system_id = data.vsphere_host.host.id
	wait_for_guest_net_timeout = 0
	wait_for_guest_ip_timeout = 0
	datacenter_id = data.vsphere_datacenter.dc.id
	ovf_deploy { 
				remote_ovf_url = "xxx.ova" 
			   } 
}

### Debug Output

2020/05/05 09:29:12 [WARN] Provider "registry.terraform.io/-/vsphere" produced an invalid plan for vsphere_virtual_machine.vmFromLocalOvf, but we are t
olerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .shutdown_wait_timeout: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
      - .migrate_wait_timeout: planned value cty.NumberIntVal(30) does not match config value cty.NullVal(cty.Number)
      - .scsi_controller_count: planned value cty.NumberIntVal(1) does not match config value cty.NullVal(cty.Number)
      - .ept_rvi_mode: planned value cty.StringVal("automatic") does not match config value cty.NullVal(cty.String)
      - .swap_placement_policy: planned value cty.StringVal("inherit") does not match config value cty.NullVal(cty.String)
      - .poweron_timeout: planned value cty.NumberIntVal(300) does not match config value cty.NullVal(cty.Number)
      - .boot_retry_delay: planned value cty.NumberIntVal(10000) does not match config value cty.NullVal(cty.Number)
      - .cpu_limit: planned value cty.NumberIntVal(-1) does not match config value cty.NullVal(cty.Number)
      - .run_tools_scripts_after_resume: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .wait_for_guest_net_routable: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .firmware: planned value cty.StringVal("bios") does not match config value cty.NullVal(cty.String)
      - .force_power_off: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .hv_mode: planned value cty.StringVal("hvAuto") does not match config value cty.NullVal(cty.String)
      - .latency_sensitivity: planned value cty.StringVal("normal") does not match config value cty.NullVal(cty.String)
      - .memory_share_level: planned value cty.StringVal("normal") does not match config value cty.NullVal(cty.String)
.NumberIntVal(1) does not match config value cty.NullVal(cty.Number)
      - .scsi_bus_sharing: planned value cty.StringVal("noSharing") does not match config value cty.NullVal(cty.String)
      - .num_cores_per_socket: planned value cty.NumberIntVal(1) does not match config value cty.NullVal(cty.Number)
      - .run_tools_scripts_before_guest_shutdown: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .cpu_share_level: planned value cty.StringVal("normal") does not match config value cty.NullVal(cty.String)
      - .run_tools_scripts_before_guest_standby: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .run_tools_scripts_after_power_on: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .memory_limit: planned value cty.NumberIntVal(-1) does not match config value cty.NullVal(cty.Number)
2020/05/05 09:29:12 [DEBUG] vsphere_virtual_machine.vmFromLocalOvf: applying the planned Create change
vsphere_virtual_machine.vmFromLocalOvf: Creating...
2020-05-05T09:29:12.872Z [DEBUG] plugin.terraform-provider-vsphere_v1.18.0_x4: 2020/05/05 09:29:12 [DEBUG] setting computed for "vapp_transport" from C
omputedKeys
2020-05-05T09:29:12.873Z [DEBUG] plugin.terraform-provider-vsphere_v1.18.0_x4: 2020/05/05 09:29:12 [DEBUG] setting computed for "guest_ip_addresses" fr
om ComputedKeys
2020-05-05T09:29:12.877Z [DEBUG] plugin.terraform-provider-vsphere_v1.18.0_x4: 2020/05/05 09:29:12 [DEBUG] vsphere_virtual_machine (ID = <new resource>
): Beginning create
2020-05-05T09:29:12.877Z [DEBUG] plugin.terraform-provider-vsphere_v1.18.0_x4: 2020/05/05 09:29:12 [DEBUG] tagsClientIfDefined: No tags configured, ski
pping loading of tagging client
2020-05-05T09:29:12.877Z [DEBUG] plugin.terraform-provider-vsphere_v1.18.0_x4: 2020/05/05 09:29:12 [DEBUG] :http://gigatftpserver.gigamon.com/tftpboot/
FM/POST/release/FM_5900/172687/esxi/gigamon-gigavue-fm-5.9.00-172687-trial.ova VM is being deployed from OVF template 
2020-05-05T09:29:12.877Z [DEBUG] plugin.terraform-provider-vsphere_v1.18.0_x4: 2020/05/05 09:29:12 [DEBUG] Locating resource pool with ID resgroup-116
2020-05-05T09:29:12.921Z [DEBUG] plugin.terraform-provider-vsphere_v1.18.0_x4: 2020/05/05 09:29:12 [DEBUG] Resource pool found: resgroup-116
2020-05-05T09:29:12.921Z [DEBUG] plugin.terraform-provider-vsphere_v1.18.0_x4: 2020/05/05 09:29:12 [DEBUG] Locating folder at path "" relative to virtu
al machine root
2020-05-05T09:29:12.931Z [DEBUG] plugin.terraform-provider-vsphere_v1.18.0_x4: 2020/05/05 09:29:12 [DEBUG] Folder located: "/DC-Nexus-1000V/vm"
2020-05-05T09:29:12.931Z [DEBUG] plugin.terraform-provider-vsphere_v1.18.0_x4: 2020/05/05 09:29:12 [DEBUG] Locating host system ID host-764
2020-05-05T09:29:12.945Z [DEBUG] plugin.terraform-provider-vsphere_v1.18.0_x4: 2020/05/05 09:29:12 [DEBUG] Host system found: host-764
2020-05-05T09:29:12.945Z [DEBUG] plugin.terraform-provider-vsphere_v1.18.0_x4: 2020/05/05 09:29:12 [DEBUG] Locating datastore with ID "datastore-765"
2020-05-05T09:29:12.947Z [DEBUG] plugin.terraform-provider-vsphere_v1.18.0_x4: 2020/05/05 09:29:12 [DEBUG] Datastore with ID "datastore-765" found
vsphere_virtual_machine.vmFromLocalOvf: Still creating... [10s elapsed]
vsphere_virtual_machine.vmFromLocalOvf: Still creating... [6m4s elapsed]
2020/05/05 09:35:24 [DEBUG] vsphere_virtual_machine.vmFromLocalOvf: apply errored, but we're indicating that via the Error pointer rather than returning it: unexpected EOF
2020/05/05 09:35:24 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: unexpected EOF
2020/05/05 09:35:24 [ERROR] <root>: eval: *terraform.EvalSequence, err: unexpected EOF

Error: unexpected EOF

  on vmware-vm.tf line 25, in resource "vsphere_virtual_machine" "vmFromLocalOvf":
  25: resource "vsphere_virtual_machine" "vmFromLocalOvf" { 

2020-05-05T09:35:24.779Z [DEBUG] plugin: plugin process exited: path=/home/auto/terraform-lab/vmware-lab/.terraform/plugins/linux_amd64/terraform-provider-vsphere_v1.18.0_x4 pid=15782
2020-05-05T09:35:24.779Z [DEBUG] plugin: plugin exited
auto@auto:~/terraform-lab/vmware-lab$ 

### Panic Output

2020/05/05 09:35:24 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: unexpected EOF
2020/05/05 09:35:24 [ERROR] <root>: eval: *terraform.EvalSequence, err: unexpected EOF

Error: unexpected EOF

  on vmware-vm.tf line 25, in resource "vsphere_virtual_machine" "vmFromLocalOvf":
  25: resource "vsphere_virtual_machine" "vmFromLocalOvf" { 

### Expected Behavior

Should be able to deploy VM using OVA given in the remote URL

### Actual Behavior

Deployment failed during VM creation using OVA deployment

### Steps to Reproduce

1.   `terraform init`
2.  `terraform apply`

**Comment by venkykuberan** [comment]
It looks to me this issue doesn't belong to GCP provider. Can you please open it in the respective provider. Closing here .
