### ISSUE TITLE
Add taint on container_node_pool want to re-create it

### ISSUE THREAD

**Issue by sebglon** [terraform-providers/terraform-provider-google#6292]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
terraform version
Terraform v0.12.23
+ provider.google v3.19.0
+ provider.local v1.4.0
+ provider.null v2.1.2
```

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

```tf
resource "google_container_node_pool" "np" {
  name       = "my-node-pool"
  location   = "us-central1-a"
  cluster    = google_container_cluster.primary.name
  node_count = 3
  node_config {
    taint {
      key = "key"
      value = "value"
      effect = "NO_SCHEDULE"
   }
  }

}
```

### Debug Output

```
          ~ taint             = [ # forces replacement
              + {
                  + effect = "NO_SCHEDULE"
                  + key    = "key"
                  + value  = "value"
                },
            ]
```

### Expected Behavior

Not recreate the node pool.
When we use the Google [API](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/NodeConfig#nodetaint), It does not drop and re-create the node pool nor rolling update nodes

### Actual Behavior

Terraform need to drop and re-create the node pool.

### Steps to Reproduce

1. `terraform apply` without taint config => node pool is well created
2. Add taint block
3. `terraform plan` => it needs to drop and re-create the node pool

### References

* #0000

**Comment by sebglon** [comment]
Not supported by Google API only avaible With the Kubernetes API

**Comment by venkykuberan** [comment]
Yes, taint values can be updated safely in Kubernetes (eg. through kubectl), and it's recommended that you do not use this field to manage taints. If you do, lifecycle.ignore_changes is recommended.

refer this doc : -  https://www.terraform.io/docs/providers/google/r/container_cluster.html

Closing this issue as provider is working as expected. Please reopen if you feel otherwise .
