### ISSUE TITLE
server_ca_cert output in plain text during terraform plan of google_sql_database_instance

### ISSUE THREAD

**Issue by red8888** [terraform-providers/terraform-provider-google#6297]
Is there some way to prevent terraform from outputting the full private cert as plan text during a plan? i think thats insecure right? Or is server_ca_cert the public cert?

**Comment by ndmckinley** [comment]
I believe that is the public certificate based on https://cloud.google.com/sql/docs/mysql/configure-ssl-instance - you see how the private key is marked as secret / cryptomaterial, and the server cert isn't?  I can't find an up-or-down answer in the docs, but if you find one let me know and I'll mark this as sensitive.

**Comment by red8888** [comment]
If its the public key then np thats actually really nice to have kept in the state

maybe i can open a gcp support case to confirm
