### ISSUE TITLE
google_container_cluster fail to create if resource_labels fiels is not defined or empty

### ISSUE THREAD

**Issue by sebglon** [terraform-providers/terraform-provider-google#6298]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.23
+ provider.google v3.19.0
+ provider.local v1.4.0
+ provider.null v2.1.2
### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster"
  location = "us-central1"

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true
  initial_node_count       = 1
}
```

### Debug Output
First creation is bad with an error 
```
Error: 2 problems:

- Invalid template interpolation value: The expression result is null. Cannot include a null value in a string template.
- Invalid template interpolation value: The expression result is null. Cannot include a null value in a string template.

``` 
And 2nd plan with this log
```
-/+ resource "google_container_cluster" "primary" {
      - resource_labels             = {} -> null
```

### Expected Behavior

No new change after first creation

### Actual Behavior

It want to drop an re-create the cluster

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

* #0000

**Comment by venkykuberan** [comment]
Is the issue is adding cluster label causing the cluster to recreate it ?
