### ISSUE TITLE
delete_default_routes_on_create is not really working as part of google compute network resource

### ISSUE THREAD

**Issue by VenkyGitDeloitte** [terraform-providers/terraform-provider-google#6302]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

https://www.terraform.io/docs/providers/google/r/compute_network.html#delete_default_routes_on_create

* google_compute-network

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Expected Behavior

It should not create default internet routes

### Actual Behavior

It is still created default internet routes

### Steps to Reproduce

You can assign this flag to true and test
https://www.terraform.io/docs/providers/google/r/compute_network.html#delete_default_routes_on_create

1. `terraform apply`

### References

* #0000

**Comment by VenkyGitDeloitte** [comment]
resource "google_compute_network" "network" {
  name                    = var.network_name
  delete_default_routes_on_create = var.default_route
  auto_create_subnetworks = var.auto_create_subnetworks
  routing_mode            = var.routing_mode
  project                 = var.project_id
  description             = var.description
}

I have enabled var.default_route="false"  but still it is creating default internet routes. Even for new project or existing project

**Comment by edwardmedia** [comment]
I can repro this issue. I see below payload when I set the `delete_default_routes_on_create` a value

```
 ---[ REQUEST ]---------------------------------------
POST /compute/v1/projects/myproject/global/networks?alt=json HTTP/1.1
 {
 "autoCreateSubnetworks": true,
  "name": "issue6302"
 }

**Comment by ndmckinley** [comment]
```
resource "google_compute_network" "network" {
name = var.network_name
delete_default_routes_on_create = var.default_route
auto_create_subnetworks = var.auto_create_subnetworks
routing_mode = var.routing_mode
project = var.project_id
description = var.description
}
```

If `var.default_route` is `false` as you said, then the routes will not be deleted.  Is that right?

**Comment by ndmckinley** [comment]
Yes, I believe the issue is in your config.  If you set the variable to true it should work.  It seems to work for me, at least.  Please post full debug logs and we'll reopen the issue if that doesn't work for you!

**Comment by VenkyGitDeloitte** [comment]
@ndmckinley 

if i se tthis var.default_route is true, then the routes will not be getting created.  Le tme know if you need screen sharign session to show my configs.

Isssue is still persists. Does this flag has to be enabled with any other variables in the resource?

**Comment by ndmckinley** [comment]
No, it seems to be working.

```
resource "google_compute_network" "network" {
  name = "demo"
  delete_default_routes_on_create = true
}
```

Produces a resource with no default routes.  See the docs here.  https://www.terraform.io/docs/providers/google/r/compute_network.html#delete_default_routes_on_create

**Comment by VenkyGitDeloitte** [comment]
@ndmckinley 

But for me routes are still getting created..

**Comment by ndmckinley** [comment]
If you post debug logs I may be able to help with that, but I believe the resource is working as documented.  Do you know how to get debug logs?

**Comment by VenkyGitDeloitte** [comment]
No Idea .. can u help.. i can send the logs

**Comment by ndmckinley** [comment]
Does this help?  https://www.terraform.io/docs/internals/debugging.html
