### ISSUE TITLE
google_project_service behavior

### ISSUE THREAD

**Issue by srlightbody** [terraform-providers/terraform-provider-google#6309]
Currently the google_project_service resource automatically does an import when an apply is run. If the resource is then removed, the default is to disable the defined service. This combination means that it's fairly easy to disable something that you didn't create, which seems to go against the fundamental design pattern of Terraform. Is this intentional behavior? Shouldn't the default be to not disable the service unless explicitly set to?

**Comment by venkykuberan** [comment]
Its the expected behavior, if you don't want to disable the service on destroy please use `disable_on_destroy = false`.
