### ISSUE TITLE
Possible regression with GKE and GCR IAM access issues?

### ISSUE THREAD

**Issue by svachmic** [terraform-providers/terraform-provider-google#6311]
It seems like [this issue](https://github.com/terraform-providers/terraform-provider-google/issues/1273) had a simple solution:

```
oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
```

Apply this in `node_config` of the GKE node pool and you're good to go. I've been trying to make this work in the past few days, being 100% sure it's my misconfiguration, but I noticed there is [somebody else](https://stackoverflow.com/questions/61551898/terraform-gke-problem-pulling-from-private-gcr) with the same issue.

I have followed all various examples (by the way, the official documentation probably [has outdated example](https://www.terraform.io/docs/providers/google/r/container_node_pool.html)) with no luck - still getting `403 Access denied` when trying to pull image from GCR in the same project, while all SA IAM roles are set properly.

Could this be a regression that it stopped working again? Some changes in GCP, new configuration to be applied? Thanks a lot in advance!

---
TF version: 0.12.24
google version 3.18.0
google-beta version 3.18.0

**Comment by venkykuberan** [comment]
I am able to pull the image and run it on pods successfully. My SA was set to storageAdmin role.  Following is the config i used.  

```
resource "google_container_cluster" "gke_cluster" {
   name               = "test-cluster"
  location           = "us-central1"
  initial_node_count = 1
   remove_default_node_pool = true
}
resource "google_container_node_pool" "gke_node_pool" {
    cluster    = google_container_cluster.gke_cluster.name
  location   = google_container_cluster.gke_cluster.location
  node_count = 2
  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
    service_account = "xxx-service-account-limited@xxx.iam.gserviceaccount.com"
  }
}
```

**Comment by svachmic** [comment]
Hi @venkykuberan thanks for your input on this. Your snippet indeed works for me as well - **but only when using a default service account** (the one GCP generates automatically, beginning with a number that is not importable to TF). When creating a special separate account, with same granted role, the code works no more and the cluster keeps throwing 403.

**Comment by venkykuberan** [comment]
oauth_scopes - (Optional) The set of Google API scopes to be made available on all of the node VMs under the "default" service account. These can be either FQDNs, or scope aliases. The following scopes are necessary to ensure the correct functioning of the cluster:

storage-ro (https://www.googleapis.com/auth/devstorage.read_only), if the cluster must read private images from GCR. Note this will grant read access to ALL GCS content unless you also specify a custom role. See https://cloud.google.com/kubernetes-engine/docs/how-to/access-scopes
