### ISSUE TITLE
data.google_compute_network.private_network.self_link fails to fetch attribute

### ISSUE THREAD

**Issue by Hashfyre** [terraform-providers/terraform-provider-google#6312]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.24
+ provider.google v3.20.0
+ provider.google-beta v3.20.0

### Affected Resource(s)

* `data.google_compute_network`

### Terraform Configuration Files

```tf
data "google_compute_network" "private_network" {
  name = "<my-vpc-name>"
}
```

### Debug Output

https://gist.github.com/Hashfyre/bf1598f6ade0fdd1a4bb3f547d7c9d4b

### Expected Behavior

The datablock should return the `self_link` attribute of  pre-existing`google_compute_network`

### Actual Behavior

Errors out with:
```
Acquiring state lock. This may take a few moments...

Error: Result depends on values that cannot be determined until after "terraform apply".


Releasing state lock. This may take a few moments...
```
This is a previously created google_compute_network that exists.

### Steps to Reproduce

1. `echo data.google_compute_network.private_network.self_link | terraform console`

### References

This is the code block I'm working with, with the `resource.google_compute_network` replaced with `data.google_compute_network`
https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#private-ip-instance

So, far no luck with provider version 3.20. I'll try out older versions in a while.

**Comment by venkykuberan** [comment]
first run `terraform apply` to get the data source to the state before echoing it in terraform console

**Comment by Hashfyre** [comment]
terraform apply has been run. This case happens afterwords.
