### ISSUE TITLE
create branches in cloud source repository using terraform

### ISSUE THREAD

**Issue by anjil** [terraform-providers/terraform-provider-google#6313]
please help in creating multiple branches when a repo is provisioned using google_sourcerepo_repository.

Thanks in advance.

**Comment by edwardmedia** [comment]
@anjil creating branches is usually done via git command. Are you running a pipeline for terraform? Can you add git commands in the pipeline?

**Comment by anjil** [comment]
@edwardmedia - No there is no pipeline for terraform as of now. I am gone try the `remote-exec`
 and see.

Thanks for you time 👍

**Comment by edwardmedia** [comment]
@anjil  Hopefully that method works for you. I am closing this question
