### ISSUE TITLE
google_compute_firewall breaks in google provider version 3.20.0

### ISSUE THREAD

**Issue by anubbhavm** [terraform-providers/terraform-provider-google#6315]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
* Terraform v0.12.23
* provider.google v3.20.0

### Affected Resource(s)

* google_compute_firewall

#### Wrapper
```tf

module "firewall_rule_allow_egress_onprem" {
  action               = "allow"
  description          = "gcp-tcp-icmp-onprem"
  direction            = "EGRESS"
  ranges               = ["x.y.z.a/b"]
  use_service_accounts = false
  rules = [
    {
      protocol = "tcp"
      ports    = [22] 
    },
    {
      protocol = "icmp"
      ports    = []
    }
  ]
  extra_attributes = {
    enable_logging = true
    priority       = 2000
  }
}

```

#### Resource

```tf
resource "google_compute_firewall" "custom" {

  name                    = local.firewall_name
  description             = var.description
  direction               = var.direction
  network                 = var.network
  project                 = var.project_id
  source_ranges           = var.direction == "INGRESS" ? var.ranges : null
  destination_ranges      = var.direction == "EGRESS" ? var.ranges : null
  source_tags             = var.use_service_accounts || var.direction == "EGRESS" ? null : var.sources
  source_service_accounts = var.use_service_accounts && var.direction == "INGRESS" ? var.sources : null
  target_tags             = var.use_service_accounts ? null : var.targets
  target_service_accounts = var.use_service_accounts ? var.targets : null
  disabled                = lookup(var.extra_attributes, "disabled", false)
  priority                = lookup(var.extra_attributes, "priority", 1000)
  enable_logging          = lookup(var.extra_attributes, "enable_logging", true)

  dynamic "allow" {
    for_each = [for rule in var.rules : rule if var.action == "allow"]
    iterator = rule
    content {
      protocol = rule.value.protocol
      ports    = rule.value.ports
    }
  }

  dynamic "deny" {
    for_each = [for rule in var.rules : rule if var.action == "deny"]
    iterator = rule
    content {
      protocol = rule.value.protocol
      ports    = rule.value.ports
    }
  }
}
```
### Actual Behavior

Error: "allow": only one of `allow,deny` can be specified, but `allow,deny` were specified.

  on .terraform/modules/firewall_rule_allow_egress_onprem/main.tf line 21, in resource "google_compute_firewall" "custom":
  21: resource "google_compute_firewall" "custom" {

Error: "deny": only one of `allow,deny` can be specified, but `allow,deny` were specified.

  on .terraform/modules/firewall_rule_allow_egress_onprem/main.tf line 21, in resource "google_compute_firewall" "custom":
  21: resource "google_compute_firewall" "custom" {

### Expected Behavior

The terraform plan should be successful as it does with google provider versions 3.19.0 and 3.18.0

### Steps to Reproduce

1. `terraform plan`

**Comment by edwardmedia** [comment]
@anubbhavm this is dup issue https://github.com/terraform-providers/terraform-provider-google/issues/6296. I am closing this as we use #6296 to track the progress. Thank you
