### ISSUE TITLE
Terraform tries to update google_compute_instance_template instead of recreating

### ISSUE THREAD

**Issue by danpospisil** [terraform-providers/terraform-provider-google#6317]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

When trying to update network_interface - access_config - network_tier option, terraform tries to update the resource instead of destroying and recreating the resource
### Terraform Version

Terraform v0.12.24
+ provider.google v3.20.0

### Affected Resource(s)

* google_compute_instance_template 

### Terraform Configuration Files

Original:
```tf
resource "google_compute_instance_template" "instance_template" {
  machine_type = "e2-micro"
  disk {
    source_image = "debian-cloud/debian-9"
  }
  network_interface {
    network = "default"
    access_config {
        network_tier = "STANDARD"
    }
  }
  lifecycle {
    create_before_destroy = true
  }
}
```

Update after original was applied:
```tf
resource "google_compute_instance_template" "instance_template" {
  machine_type = "e2-micro"
  disk {
    source_image = "debian-cloud/debian-9"
  }
  network_interface {
    network = "default"
    access_config {
        network_tier = "PREMIUM"
    }
  }
  lifecycle {
    create_before_destroy = true
  }
}
```

### Expected Behavior
Instance template should be recreated - not updated

### Actual Behavior
Terraform tries to update the resource:
```
google_compute_instance_template.instance_template: Modifying... [id=projects/terraform-test-274919/global/instanceTemplates/terraform-20200507210144048800000001]

Error: doesn't support update

  on main.tf line 14, in resource "google_compute_instance_template" "instance_template":
  14: resource "google_compute_instance_template" "instance_template" {
```

### Steps to Reproduce
Create google_compute_instance_template with network_tier set to STANDARD
run apply
change the network_tier option to PREMIUM
apply will fail

### Important Factoids
This was supposed to fixed in PR#11548 but it doesnt seem to work

### References

https://github.com/hashicorp/terraform/pull/11548

**Comment by edwardmedia** [comment]
@ndmckinley  I can repro above issue with `Error: doesn't support update`
Additional Info: 
1) if I change other attributes (like adding metadata) along with the upgrade on **network_tier**, the `apply` succeeds.  **PREMIUM** is showing up on **network_tier**
2) changes on **create_before_destroy** appear not working.
