### ISSUE TITLE
Terraform apply to ask if a system reboot required for changing the infrastructure

### ISSUE THREAD

**Issue by suvsap** [terraform-providers/terraform-provider-google#6322]
Hi,

We recently did some resizing our GCP instances to save cost. This would ideally go for reboot. We have observed that some of our engineers who are new to terraform not aware that the particular change that will be applied will go for reboot. This affected our live client.

Is their any way by which when we do terraform apply and if it requires to reboot the instance for sucessful completion then it should ask before doing reboot?

This change will require reboot. Do you want to proceed? Yes/no

Thanks,
Suvankar

**Comment by ndmckinley** [comment]
You can use `allow_stopping_for_update` in this way.
 https://www.terraform.io/docs/providers/google/r/compute_instance.html#allow_stopping_for_update
