### ISSUE TITLE
[google-beta] google_sql_database_instance for SQL Server fails on creation if root_password handed over to the module

### ISSUE THREAD

**Issue by gleichda** [terraform-providers/terraform-provider-google#6323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
$ terraform -v
Terraform v0.12.24
+ provider.google v3.20.0
+ provider.google-beta v3.20.0

```

### Affected Resource(s)

`google_sql_database_instance`

### Terraform Configuration Files

(this can also be found at https://github.com/gleichda/terraform-sql-demo)
`main.tf`
```tf
provider "google-beta" {
  project = "<MY PROJECT ID>"
}

module "sql-instance" {
  source = "./modules/sql-instance"
  root_password = var.root_password
  providers = {
    google = google-beta
  }
}

variable "root_password" {
  type = string
  default = "MyS3cureP4ssword"
}
```

`/modules/sql-instance/main.tf`
```tf
variable "root_password" {
  type = string
}

resource "google_sql_database_instance" "instance" {
  name = "instance"
  database_version = "SQLSERVER_2017_STANDARD"

  root_password = var.root_password

  settings {
    tier = "db-custom-1-4096"
  }
}
```

### Debug Output

https://github.com/gleichda/terraform-sql-demo/blob/master/terraform.log

### Expected Behavior

Terraform should provision the SQL instance

### Actual Behavior

Terraform is producing the following error:

```bash
Error: Provider produced inconsistent final plan

When expanding the plan for
module.sql-instance.google_sql_database_instance.instance to include new
values learned so far during apply, provider
"registry.terraform.io/-/google-beta" produced an invalid new value for
.root_password: inconsistent values for sensitive attribute.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

Terraform resource docs: https://www.terraform.io/docs/providers/google/r/sql_database_instance.html
Issue for making the root_password GA: #5870 

* #0000

**Comment by edwardmedia** [comment]
@c2thorn I can repro it. This issue happens with other providers as well

**Comment by c2thorn** [comment]
Hi @gleichda, I was able to successfully create an instance by adding a 
`provider = google-beta`
to your "google_sql_database_instance.instance". Can you try the same?

**Comment by gleichda** [comment]
Hi @c2thorn thanks for  that hint. Works for me also 🎉

**Comment by c2thorn** [comment]
@gleichda that is great to hear!
