### ISSUE TITLE
 Cloud Run Domain Mapping Route Name Not Working

### ISSUE THREAD

**Issue by natalysheinin** [terraform-providers/terraform-provider-google#6325]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.24

### Affected Resource(s)

* `google_cloud_run_domain_mapping`

### Terraform Configuration Files

```tf
resource "google_cloud_run_service" "default" {
...
}

resource "google_cloud_run_domain_mapping" "default" {
  depends_on = [google_cloud_run_service.default]

  location = local.location
  name     = "mydomain.mydomain.com"

  metadata {
    namespace = local.project
  }

  spec {
    route_name = google_cloud_run_service.default.name
  }
}
```

OR you can make this configuration (same result):
```tf
resource "google_cloud_run_domain_mapping" "default" {
...
spec {
    route_name = "default"
  }
}
```
### Expected Behavior

* The domain mapping should have been successfully created via terraform apply
* The `Mapped To` column in the UI should have said `default`

### Actual Behavior

* The domain mapping was successfully created via terraform apply
* The `Mapped To` column in the UI says: `projects/my-project-here/global/services/default (us-central1)`

When you visit the Cloud Run Domain Mappings UI in the cloud console, the `Mapped To` column shows:
```
projects/my-project-here/global/services/default (us-central1)
```
and there is a warning message beside it: `Service does not exist`.
### Steps to Reproduce

Follow the instructions here: https://www.terraform.io/docs/providers/google/r/cloud_run_domain_mapping.html#example-usage-cloud-run-domain-mapping-basic
Or here:
https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_cloud_run_domain_mapping_generated_test.go#L81

### References

* https://www.terraform.io/docs/providers/google/r/cloud_run_domain_mapping.html#example-usage-cloud-run-domain-mapping-basic
* https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_cloud_run_domain_mapping_generated_test.go#L81

**Comment by edwardmedia** [comment]
@natalysheinin in my test, I see the value in `Mapped To` column is `cloudrun-srv (us-central1)`. Can you post your debug log?

**Comment by edwardmedia** [comment]
@natalysheinin is this still an issue with you? If yes, could provide debug log?

**Comment by natalysheinin** [comment]
> Can you post your debug log so we can take a close look? 

I'm struggling to post my debug log because I would have to redact a lot. :'( 
Is there a particular part of the debug log you are looking for so I can paste it in faster?

**Comment by edwardmedia** [comment]
@natalysheinin mainly the requests & responses around creating these two resources. Still possible we need to review the log outside these payloads.

**Comment by edwardmedia** [comment]
@natalysheinin I am closing this issue at this moment. Once you have the log available, please reopen it and we can restart the investigation from there. Thank you
