### ISSUE TITLE
Big Query Role Binding removes other project IAM users

### ISSUE THREAD

**Issue by mralanlee** [terraform-providers/terraform-provider-google#6326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_project_iam_member

### Terraform Configuration Files

```tf
# This was already existing in the main.tf file
resource "google_project_iam_member" "old_account" {
  project = "${var.project_id}"
  role    = "roles/bigquery.dataEditor"
  member  = "serviceAccount:${google_service_account.old_account.email}"
}

# ...

# all of these below are new
resource "google_service_account" "example" {
  project      = "${var.project_id}"
  account_id   = "example"
  display_name = "Example BigQuery service account"
}

resource "google_service_account_key" "example" {
  service_account_id = "${google_service_account.example.name}"
}

resource "google_project_iam_binding" "example" {
  project = "${var.project_id}"
  role    = "roles/bigquery.dataEditor"

  members = [
    "serviceAccount:${google_service_account.example.email}",
  ]
}
```

### Expected Behavior
Create the service account, service account key, and iam binding for service account.

### Actual Behavior
It did the expected, and the plan showed that it would. However `google_project_iam_member` in the same `main.tf` were removed (these iam members are also tied to BigQuery access and are primarily used as service accounts). 

The terraform plan output did NOT list a change/deletion of these project iam members, only for the configurations I had shared above (service account, service account key, and iam binding).  However the project iam member (`old_account`) got deleted without any notification and warning.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
I can repro this issue.

**Comment by edwardmedia** [comment]
@mralanlee  this is expected for `google_project_iam_binding`. Below is what it says in the doc. If you want to preserve a member in a role, you need to explicitly add it in the list for a role, along with the new ones. If you just want to add a new member into an existing role, you may use `google_project_iam_member` instead. 

> google_project_iam_binding: Authoritative for a given role. Updates the IAM policy to grant a role to a list of members. Other roles within the IAM policy for the project are preserved.

I am closing this issue. Feel free to reopen it if you see the behavior differently. Thanks

**Comment by mralanlee** [comment]
Hi @edwardmedia 

I'm still a bit confused because the service account, it's key, and role binding is separate from the project iam member.

I guess the only relation that those IAM members have is that they also have access big query. Would it actually make more sense to create them as service accounts and add them as into the iam binding as members?
