### ISSUE TITLE
Finish "Mark GKE Workload Identity config as GA" PR.

### ISSUE THREAD

**Issue by ndmckinley** [terraform-providers/terraform-provider-google#6329]
Finish https://github.com/GoogleCloudPlatform/magic-modules/pull/3453 - "Mark GKE Workload Identity config as GA"

**Comment by danawillow** [comment]
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/5916?

**Comment by ndmckinley** [comment]
Fixing this will also close that one, but I think it's worth having an issue to say "this PR is abandoned but useful, finish it up" - your call.
