### ISSUE TITLE
why remove google_project_services

### ISSUE THREAD

**Issue by mig4** [terraform-providers/terraform-provider-google#6333]
Hi, I was looking for a way to manage a list of APIs I want enabled in a project and only found the `google_project_service` resource, but I also found that there used to be a `google_project_services` which was authoritative but has been removed in latest version of the provider.

From the description in upgrading guide:

> `google_project_services` was an assertion that "only these services are set on this project"

this is exactly what I want. My understanding is that there's currently no way to remove APIs I no longer need. May I ask why was it removed? Is there some limitation of GCP or in how this TF module interacts with it?

**Comment by venkykuberan** [comment]
It's not really a limitation - we learned that many users were accidentally doing something dangerous, so we removed the dangerous tool. We will update the resource doc alike in upgrading guide

**Comment by danawillow** [comment]
Hey @mig4, the upgrade guide that you quoted from actually has a paragraph on why we removed it:
> However, this was dangerous to use in practice. Services have dependencies that are automatically enabled alongside them and GCP will add dependencies to services out of band, enabling them. If a user ran Terraform after this, Terraform would disable the service- and implicitly disable any service that relied on it.

Does that help at all? I'm happy to try to make our docs explain our thinking better, but I'm not sure what else we could add aside from that. There's also some information at https://github.com/terraform-providers/terraform-provider-google/issues/4570 if that helps.

**Comment by mig4** [comment]
> There's also some information at #4570 if that helps.

Thanks! It helps a lot. I understand, with the dependencies changing silently behind the scenes there's no way for Terraform to track that. Also I must've misunderstood the documentation regarding the non-authoritative `google_project_service` in that it will actually disable a service if its resource is removed from Terraform config.

Thanks for your help!

I'm going to close this as I don't think any action is necessary here.
