### ISSUE TITLE
Google Resource:google_storage_bucket does not honour map labels for buckets

### ISSUE THREAD

**Issue by mike-19** [terraform-providers/terraform-provider-google#6336]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

`terraform2 -v`                                                             
> + Terraform v0.12.24
> + provider.google v3.20.0
> + provider.random v2.2.1

### Affected Resource(s)

`google_storage_bucket`

### Terraform Configuration Files

`variable.tf`
```tf
variable "labels" {
  description = "Labels to be attached to all buckets."
  type        = map(string)
  default     = {}
}
```

`terraform.tfvars`
```tf
resource "google_storage_bucket" "buckets" {
  project  = "${var.project_name}"
  name =  "testing"
  location           = "US"
  force_destroy      = false
  bucket_policy_only = true
  labels = map("location", "US")
  }
```
### Panic Output
```tf
Error: googleapi: Error 400: Invalid argument, invalid
  on bucket.tf line 7, in resource "google_storage_bucket" "buckets":
   7: resource "google_storage_bucket" "buckets" {
```

### Expected Behavior

It should be able to add labels to the bucket 

### Actual Behavior

It fails with `invalid argument`

```tf
Error: googleapi: Error 400: Invalid argument, invalid
  on bucket.tf line 7, in resource "google_storage_bucket" "buckets":
   7: resource "google_storage_bucket" "buckets" {
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by venkykuberan** [comment]
Using lower case labels should do it. Please refer this doc - https://cloud.google.com/storage/docs/key-terms#bucket-labels

**Comment by mike-19** [comment]
@venkykuberan  doesnt really help with lower case 
tried changing it to and run , bucket creation failed 
`labels = map("location:", "us")`

**Comment by venkykuberan** [comment]
Bucket label rules as in the above referred doc , `:` not allowed there
```
  You can apply multiple labels to each bucket, with a maximum of 64 labels per bucket.

Keys and values cannot be longer than 63 characters each.
Keys and values can only contain lowercase letters, numeric characters, underscores, and dashes. International characters are allowed.
Label keys must start with a lowercase letter and international characters are allowed.
Label keys cannot be empty.
```
