### ISSUE TITLE
Can't delete a taint from a GKE node pool using Terraform

### ISSUE THREAD

**Issue by rtoma** [terraform-providers/terraform-provider-google#6337]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

* terraform 0.12.23
* terraform google provider beta 3.9.0

### Affected Resource(s)

* google_container_cluster
* google_container_node_pool

### Terraform Configuration Files

Like https://github.com/terraform-providers/terraform-provider-google/issues/4168 - before the .tf file had a node pool with taint. After creating the node pool with taint, the taint was removed from the .tf file. In my case my "after" .tf file includes this:
```
resource "google_container_node_pool" "[REDACTED]" {
  provider           = google-beta.kubernetes-engine-beta
  ...
  node_config {
     # without any taints
     ...
  }
}
```
After running Terraform on this template the removal is ignored and the statefile still contains:
```
"taint": [
  {
    "effect": "NO_SCHEDULE",
    "key": "nidhogg.uswitch.com/kube-system.calico-node",
    "value": "default"
  }
],
```

### Expected Behavior

Terraform detects a taint has been removed from the template and plans a change. Since a taint can not be changed without node pool replacement Terraform will destroy the node pool and create a new one.

### Actual Behavior

Nothing. The change is ignored by Terraform.

### Steps to Reproduce

See https://github.com/terraform-providers/terraform-provider-google/issues/4168

### Important Factoids

https://github.com/terraform-providers/terraform-provider-google/issues/4168 was for the 2.x google provider. A fix was supposed to be part of 3.0, but it is not. Or am I mistaken it's related?

**Comment by venkykuberan** [comment]
An empty taint [] would unset the taint property. Please refer this upgrade [guide](https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#taint-field-is-now-authoritative-when-set).
