### ISSUE TITLE
Dynamic blocks within network resources fail on Terraform Validate with 3.20.0

### ISSUE THREAD

**Issue by NotAnotherMetaTag** [terraform-providers/terraform-provider-google#6345]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
0.12.23

### Affected Resource(s)
google_compute_health_check
google_compute_firewall

### Terraform Configuration Files
```tf
resource "google_compute_health_check" "vault_lb_hc" {
  # used for internal backend
  project             =  var.project_id
  name                = var.name
  check_interval_sec  = 10
  timeout_sec         = 5
  healthy_threshold   = 2
  unhealthy_threshold = 10
  dynamic "https_health_check" {
    for_each = var.tls_enable ? ["enabled"] : []
    content {
      request_path = var.health_check_active
      port         = 8200
    }
  }
  dynamic "http_health_check" {
    for_each = var.tls_enable ? [] : ["enabled"]
    content {
      request_path = var.health_check_active
      port         = 8200
    }
  }
}
```
```tf
terraform {
  required_providers {
    google = "~3.14" # resolves to 3.20 currently
  }
}
```
### Expected Behavior
Expect Terraform to successfully validate with the "Success!..." output, which it will do if the google provider is pinned to 3.19 (or earlier).

### Actual Behavior
Health check fails with the output:
```
"https_health_check": only one of `http2_health_check,http_health_check,https_health_check,ssl_health_check,tcp_health_check` can be specified, but `http_health_check,https_health_check` were specified.
```
### Steps to Reproduce
1. Use a dynamic block in google_compute_health_check
2. `terraform validate`

### Other
Based on a conversation with my coworker, this appears to happen as well with google_compute_firewall with dynamic allow/deny. I do not have his logs. There isn't anything in the Changelog for 3.20.0 that would leave me to expect any changes to these resources.

**Comment by edwardmedia** [comment]
dups 
https://github.com/terraform-providers/terraform-provider-google/issues/6295 
https://github.com/terraform-providers/terraform-provider-google/issues/6315
Closing as the fix will be in the next release. Please feel free to reopen it if this is still an issue after the release.
