### ISSUE TITLE
Add Network argument reference to google_compute_backend_service

### ISSUE THREAD

**Issue by liraymond19** [terraform-providers/terraform-provider-google#6348]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Requesting ability to specify the network for a backend service. This is available through gcloud, but not through Terraform. 

I currently have a use case for a managed instance group with multiple nics. Because only nic0 can be a shared VPC, we assigned the required Shared VPC to nic0, and the local VPC where the traffic must be sent to nic1. All components of this solution have been automated through Terraform Google provider resources, except for the backend service. 

### New or Affected Resource(s)

google_compute_backend_service

### Potential Terraform Configuration

Add an optional "network" argument reference which would map to "--network" here https://cloud.google.com/sdk/gcloud/reference/compute/backend-services/create#--network

### References

* #0000

**Comment by danawillow** [comment]
Hi @liraymond19, the documentation at https://cloud.google.com/sdk/gcloud/reference/compute/backend-services/create#--network says "Network that this backend service applies to. It can only be set if the load-balancing-scheme is INTERNAL."

According to https://cloud.google.com/load-balancing/docs/backend-service, the only type of load balancer that supports the INTERNAL load balancing scheme is Internal TCP/UDP Load Balancing, which uses Regional backend services.

The [google_compute_region_backend_service](https://www.terraform.io/docs/providers/google/r/compute_region_backend_service.html) resource already does support the `network` argument. Can you confirm for me that you're specifically looking it for the google_compute_backend_service resource, and if so, what type of load balancing you're using?

**Comment by liraymond19** [comment]
Hi @danawillow  thank you for looking into this! I just checked and agree the network flag is there. I'm a bit confused, because when me and my colleague were researching this last week, we did not see this. Not sure what happened there - I will test this evening and validate it's working.

**Comment by liraymond19** [comment]
Hi @danawillow confirming that the google_compute_region_backend_service fits our requirements. There is no request to add network to google_compute_backend_service. Thank you again for your help.
