### ISSUE TITLE
changing initial_node_count on google_container_node_pool destroys the pool

### ISSUE THREAD

**Issue by bad** [terraform-providers/terraform-provider-google#6354]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.24
+ provider.google v3.21.0

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

```tf
from:
resource "google_container_node_pool" "foo" {
  initial_node_count = 1
  ...
}

to:
resource "google_container_node_pool" "foo" {
  initial_node_count = 2
  ...
}
```

### Expected Behavior

The node pool should be changed to update the new initial_node_count value and the additional node(s) should be created.
I would expect reasonable behaviour  when the initial_node_count is decreased, too.  I.e. just update the resource and let node deallocation be handled by auto scaling.

### Actual Behavior

The node pool is destroyed and then a new one is created:

```
      ~ initial_node_count  = 1 -> 2 # forces replacement
...
Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2. change initial_node_count in the google_container_node_pool
3. `terraform apply`

**Comment by edwardmedia** [comment]
@bad This is expected. 

> initial_node_count - (Optional) The initial number of nodes for the pool. In regional or multi-zonal clusters, this is the number of nodes per zone. Changing this will force recreation of the resource.

https://www.terraform.io/docs/providers/google/r/container_node_pool.html

**Comment by bad** [comment]
Ed,
thank you for your input.

However, isn't that a pretty weak argument? After all, any documented bug and deficiency is expected behaviour.

I don't see a technical reason for this restriction.  Changing the number of nodes in a pool on the fly works just fine with gcloud.

Also, what is the work around for this limitation? This very unfortunate behaviour has severe operational ramifications.
