### ISSUE TITLE
Race condition with google_compute_route and VPC peering operations still exists

### ISSUE THREAD

**Issue by ct-dh** [terraform-providers/terraform-provider-google#6361]
Opening this issue as Issue:6233 was closed as fixed because the `google_compute_route` resource was added to the mutex for VPC peering operations. This doesn't seem to have fixed my issue as far as I can tell as per my comment just after the fix was submitted.

I __think__  the issue might be, but not 100% sure, that this mutex doesn't also protect the peering created by the google_container_cluster when using private clusters? I will try and look at the code a bit more to see if I can help steer in the right direction.

For reference, this issue appears to be that creating a static route whilst a peering operation is in progress will cause the Google API to throw this error:

```
Error creating Route: googleapi: Error 400: There is a peering operation in progress on the local or peer network. Try again later., badRequest
```

I have tried to create a minimal repro but have struggled due to the timing issues, and the best way to have it fail reliably is in our pipeline, the code of which isn't something I can just share publicly.

**Comment by ct-dh** [comment]
@edwardmedia I finally managed to come up with a local repro without using the actual codebase:

```
variable "name" {
  type        = string
  description = "name"
}

variable "project" {
  type        = string
  description = "Project ID"
}

variable "region" {
  type        = string
}

variable "zone" {
  type        = string
}

terraform {
  required_version = ">= 0.12.9"

}

provider "google" {
  version = "3.11.0"
  project = var.project
  region  = "europe-west1"
}


provider "google-beta" {
  version = "3.11.0"
  project = var.project
  region  = "europe-west1"
}


resource "google_compute_network" "base" {
  name                    = "${var.name}-test-base-network"
  auto_create_subnetworks = false
  description             = "Repro for TF provider bug"
}

resource "google_compute_subnetwork" "unrelated-subnet" {
  name                     = "${var.name}-unrelated-subnet"
  ip_cidr_range            = "10.250.250.0/24"
  network                  = google_compute_network.base.self_link
  region                   = var.region
}

resource "google_compute_route" "default" {
  name        = "network-route-testing-bug"
  dest_range  = "15.0.0.0/24"
  network     = google_compute_network.base.self_link
next_hop_gateway = "default-internet-gateway"
  priority    = 100
}

resource "google_compute_route" "default1" {
  name        = "network-route-testing-bug1"
  dest_range  = "15.0.1.0/24"
  network     = google_compute_network.base.self_link
next_hop_gateway = "default-internet-gateway"
  priority    = 100
  depends_on  = [
    google_compute_route.default,
  ]
}
resource "google_compute_route" "default2" {
  name        = "network-route-testing-bug2"
  dest_range  = "15.0.2.0/24"
  network     = google_compute_network.base.self_link
next_hop_gateway = "default-internet-gateway"
  priority    = 100
  depends_on  = [
    google_compute_route.default1,
  ]
}
resource "google_compute_route" "default3" {
  name        = "network-route-testing-bug3"
  dest_range  = "15.0.3.0/24"
  network     = google_compute_network.base.self_link
next_hop_gateway = "default-internet-gateway"
  priority    = 100
  depends_on  = [
    google_compute_route.default2,
  ]
}
resource "google_compute_route" "default4" {
  name        = "network-route-testing-bug4"
  dest_range  = "15.0.4.0/24"
  network     = google_compute_network.base.self_link
next_hop_gateway = "default-internet-gateway"
  priority    = 100
  depends_on  = [
    google_compute_route.default3,
  ]
}
resource "google_compute_route" "default5" {
  name        = "network-route-testing-bug5"
  dest_range  = "15.0.5.0/24"
  network     = google_compute_network.base.self_link
next_hop_gateway = "default-internet-gateway"
  priority    = 100
  depends_on  = [
    google_compute_route.default4,
  ]
}
resource "google_compute_route" "default6" {
  name        = "network-route-testing-bug6"
  dest_range  = "15.0.6.0/24"
  network     = google_compute_network.base.self_link
next_hop_gateway = "default-internet-gateway"
  priority    = 100
  depends_on  = [
    google_compute_route.default5,
  ]
}
resource "google_compute_route" "default7" {
  name        = "network-route-testing-bug7"
  dest_range  = "15.0.7.0/24"
  network     = google_compute_network.base.self_link
next_hop_gateway = "default-internet-gateway"
  priority    = 100
  depends_on  = [
    google_compute_route.default6,
  ]
}
resource "google_compute_route" "default8" {
  name        = "network-route-testing-bug8"
  dest_range  = "15.0.8.0/24"
  network     = google_compute_network.base.self_link
next_hop_gateway = "default-internet-gateway"
  priority    = 100
  depends_on  = [
    google_compute_route.default7,
  ]
}
resource "google_compute_route" "default9" {
  name        = "network-route-testing-bug9"
  dest_range  = "15.0.9.0/24"
  network     = google_compute_network.base.self_link
next_hop_gateway = "default-internet-gateway"
  priority    = 100
  depends_on  = [
    google_compute_route.default8,
  ]
}

resource "google_compute_subnetwork" "gke-subnetwork" {
  name                     = "${var.name}-cluster-subnet"
  ip_cidr_range            = local.primary_subnet_range
  network                  = google_compute_network.base.self_link
  region                   = var.region
  private_ip_google_access = true

  secondary_ip_range {
    range_name    = "${var.name}-services"
    ip_cidr_range = local.services_subnet_range
  }

  secondary_ip_range {
    range_name    = "${var.name}-pods"
    ip_cidr_range = local.pods_subnet_range
  }
}


locals {
  primary_subnet_range      = cidrsubnet(local.kube_parent_range, 6, 0)
  services_subnet_range     = cidrsubnet(local.kube_parent_range, 6, 1)
  pods_subnet_range = cidrsubnet(
    "10.0.0.0/13",
    1,
    0,
  )
  master_ipv4_cidr_block   = cidrsubnet(local.master_ipv4_parent_range, 8, 0)
  master_ipv4_parent_range = cidrsubnet(local.kube_parent_range, 6, 2)
  kube_parent_range = cidrsubnet(
    "10.0.0.0/13",
    1,
    1,
  )
}

data "google_container_engine_versions" "k8s-version" {
  location       = var.region
  version_prefix = "1.15."
}

resource "google_container_cluster" "primary" {
  provider           = google
  project            = var.project
  name               = "${var.name}-marcelus-wallace-test"
  location           = var.region
  node_locations     = [var.zone]
  network            = replace(google_compute_network.base.self_link, "https://www.googleapis.com/compute/v1/", "")
  subnetwork         = replace(google_compute_subnetwork.gke-subnetwork.self_link, "https://www.googleapis.com/compute/v1/", "")
  min_master_version = data.google_container_engine_versions.k8s-version.latest_master_version
  enable_legacy_abac = false

  initial_node_count       = 1

  master_auth {
    client_certificate_config {
      issue_client_certificate = false
    }
  }

  ip_allocation_policy {
    cluster_secondary_range_name  = "${var.name}-pods"
    services_secondary_range_name = "${var.name}-services"
  }

  private_cluster_config {
    enable_private_endpoint = false
    enable_private_nodes    = true

    # https://github.com/gruntwork-io/terraform-google-gke/blob/1763bb37b7cdfa455c7a2d8e188dca3f2841b9c1/examples/gke-private-cluster/main.tf#L49
    master_ipv4_cidr_block = local.master_ipv4_cidr_block
  }

}
```

If this doesn't reproduce for you, adding more routes in a linear fashion should help.

**Comment by c2thorn** [comment]
Hi @ct-dh,
Just a quick question, have you been able to reproduce this with `v3.21.0` of the providers? Looks like the initial fix went to that version, and I see you are reproducing with an older version.

**Comment by edwardmedia** [comment]
@c2thorn I am able to hit the mentioned error after I increased the number of routes to 16

**Comment by ct-dh** [comment]
@c2thorn sorry, the issue occurred in my real world scenario after bumping to 3.21.0 of the provider. I forgot to bump the version for the minimal repro.

I just ran it now but changed the provider version to 3.21.0 and the behaviour was the same as expected.

**Comment by c2thorn** [comment]
@ct-dh Thanks, for checking on that! It certainly seems like the peering created by the container cluster is blocking the route creation. As a quick work around, you should be able to add 
`  
depends_on  = [
	google_compute_route. default9,
]
`
to your `google_container_cluster` to force Terraform to create the cluster after the last route is created. I tried it just now, and got a successful attempt with 16 routes attempted.

The full fix will be to add another lock to `google_compute_route` for private container creation, but you may not have to wait for that by adding the above code.

**Comment by c3st7n** [comment]
@c2thorn thanks for the suggestion. It was my first thought when I hit the issue but I don't think I can in my situation (happy to be corrected if I'm wrong). The 2 conflicting resources are being created in 2 unrelated modules, both being optional in our setup. Sometimes both modules are enabled, but our deployment of code may delete the file including either one based on some configuration. To my knowledge you can't depend on a module itself and I can't figure out how to rely on a module output if you can't guarantee the module will be defined. If it helps we are using terraform 0.12.23 I think.

I tried my own build of magic modules last night, adding the network mutex to guard create and delete for `google_container_cluster`, whilst it did stop the routes from creating at the same time as the cluster it still failed just after the cluster finished creating. My guess was that even though the cluster resource completed the peering was still in progress for a short while? I get that you proposed the opposite, to reuse the cluster mutex on the route resource, but I assume the behaviour would be the same? Would it make sense to make the route resource retry on hitting that specific error perhaps? One other possibility is that I want actually using the test provider build our out didn't actually include my patch but as I say it did seem to serialise the order in which the resources tried to create.

(This is the personal account for @ct-dh by the way)

**Comment by c2thorn** [comment]
@c3st7n, thanks for actually testing out an implementation, that saves some time. Based on your results, it sounds like peering may just be continuing outside of Terraform's visibility (ie after cluster creation). Some retry polling sounds like our best bet in this case. Container cluster mutex is probably _helping_, but if we need to rely on retries afterwards anyway, might as well just implement that.

The implementation shouldn't take long, but it'll be a bit before it is released. Your setup seems to be the most encompassing repro, so it'll be great if you were able to pull the change early and try it out.

**Comment by ct-dh** [comment]
I will try and build this and test it today in our CI pipeline where we were consistently failing.

**Comment by ct-dh** [comment]
@c2thorn I built the version with your retry added and it passed multiple times in my CI pipeline where it was previously failing. The minimal local repro worked too (although I am guessing you already tested that). 👍

**Comment by c2thorn** [comment]
@ct-dh Thanks for the proactive tests! Glad we were able to solve this.
