### ISSUE TITLE
Is there a way to add user specific metadata that will show up in gcp audit logs?

### ISSUE THREAD

**Issue by red8888** [terraform-providers/terraform-provider-google#6378]
GCP audit logs are extensive, they include the caller ip and a bunch of stuff for helping identify who did the thing. But is there a way to add my own metadata/identifier and do that with the gcp terraform provider?

AWS makes this possible with AWS_ROLE_SESSION_NAME environment variable and it works seamlessly with terraform. 

I call terraform apply from a remote system which uses a service account. BUT I still want to know who executed the apply from that remote system. For aws I can just set AWS_ROLE_SESSION_NAME  to the current user and in cloudtrail logs that identifier will show up. Even though Im using a service account I can still add my own metadata that appears in audit logs.

Is this possible with GCP somehow? Is there a GCP environment variable or API argument the provider supports for doing this?

Also, Im sure there is a terraform enterprise feature for this but Im still on the free version for now

**Comment by venkykuberan** [comment]
Having the following in your config will show the user info who executed the apply

data "google_client_openid_userinfo" "me" {
}

output "user_id" {
  value = data.google_client_openid_userinfo.me.email
}

**Comment by red8888** [comment]
that would always show the same user. I call terraform apply from a remote system which uses a service account. 

AWS_ROLE_SESSION_NAME allows me to add arbitrary info
