### ISSUE TITLE
Terraform 0.12.25 thinks appengine.googleapis.com is enabled when it's not

### ISSUE THREAD

**Issue by gaahrdner** [terraform-providers/terraform-provider-google#6385]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v0.12.25

### Affected Resource(s)

`google_project_service`

### Terraform Configuration Files

```tf
resource "google_project_service" "appengine_api" {
  project                    = var.dab_project
  service                    = "appengine.googleapis.com"
  disable_dependent_services = false
  disable_on_destroy         = false
}
```

### Debug Output

https://gist.github.com/gaahrdner/a3ef6ddba76f7b33bf96e9ef703dfa00

### Expected Behavior

Terraform enables the AppEngine API.

### Actual Behavior

Terraform thinks the AppEngine API is enabled when it is not.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

```
± |phil/add-users-for-build-project ✓| → gcloud app describe --project OUR_PROJECT
ERROR: (gcloud.app.describe) The current Google Cloud project [OUR_PROJECT] does not contain an App Engine application. Use `gcloud app create` to initialize an App Engine application within the project.
```

This is actually contained in a module that we use but it shouldn't matter; the `setup` module still gets run first. Not sure why this API is not being enabled. Line 25 of the linked issue clearly shows Terraform thinks it's on.

### References

* #0000

**Comment by edwardmedia** [comment]
@gaahrdner your above code works fine with me in term of enabling the `appengine.googleapis.com`. I have verified the service enabled from the GCP console. Without having your other code, I am not sure what exactly what happened. But from the error you received, it says **does not contain an App Engine application.**. It might not refer to the api service. How did you verify whether your above code works?

**Comment by edwardmedia** [comment]
@gaahrdner  is this still an issue with you?

**Comment by gaahrdner** [comment]
Hi @edwardmedia, sorry about the delay I totally forgot about this issue; your assessment was correct and this is not an issue with enabling the API. I still haven't figured out the root cause yet but will dig in some more.
