### ISSUE TITLE
How to add targets as code (terraform) to cloudarmor

### ISSUE THREAD

**Issue by gowrisankar22** [terraform-providers/terraform-provider-google#6389]
Currently, we create cloud armor rules via terraform and applications(targets) separately. I don't find any terraform code to add targets to cloud armor rules via terraforming. Currently, I am doing manually. Can you help me here ?

**Comment by edwardmedia** [comment]
@gowrisankar22 I am not familiar with that. Can you provide detailed steps how you manually **add targets to cloud armor**? Thanks

**Comment by edwardmedia** [comment]
@gowrisankar22 Here are some conversations related to your question. Is it helpful?

**Comment by gowrisankar22** [comment]
@edwardmedia Nope it was not. Backend we are not creating via terraform rather via ingress annotation. In this case, how can we add a backend to the cloud armor rule. Currently, it is a very pain point for anyone whoever is using helm charts based deployments. Is there any possibility to do this via annotation?
```
annotations:
---
   kubernetes.io/ingress.class: gce

```
Example my application:
https://github.com/concourse/concourse-chart/blob/master/values.yaml#L1715-L1733

**Comment by edwardmedia** [comment]
@gowrisankar22 I don't think currently terraform directly supports you mentioned `annotations` If the Backend is already in place, you may import the Backend, and then you can start from there. But that still require certain manual work. I am closing this issue. If you think of some new features the provider could provide, you may file an enhancement instead https://github.com/terraform-providers/terraform-provider-google/issues/new?template=enhancement.md. Thank you
