### ISSUE TITLE
Make google_container_cluster release_channel GA

### ISSUE THREAD

**Issue by gleichda** [terraform-providers/terraform-provider-google#6390]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As from the [documentation](https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels) Release Channels are now GA but in [Terraform](https://www.terraform.io/docs/providers/google/r/container_cluster.html#release_channel) they are still beta. Would be awesome if you could bring them to GA in Terraform also.

### New or Affected Resource(s)

* google_container_cluster

### References

Documentation: https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels Terraform Docs: https://www.terraform.io/docs/providers/google/r/container_cluster.html#release_channel

* #0000

**Comment by gowrisankar22** [comment]
#5391

**Comment by gleichda** [comment]
@gowrisankar22 Not really as release channels are now GA

**Comment by danawillow** [comment]
This is actually still in beta: https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels#enrolling_an_existing_cluster_in_a_release_channel

**Comment by gleichda** [comment]
Only enrolling an existing cluster with Release Channels but not creating a new cluster with release channels? Or did I miss something?

**Comment by danawillow** [comment]
Regardless, the API doesn't have support for it in GA yet: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters (vs https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters, search for ReleaseChannel)

**Comment by steinbrueckri** [comment]
As you could check in the documentation about GKE v1 API projects.locations.clusters, nowadays the feature ReleaseChannel is in GA since yesterday. 🙌
