### ISSUE TITLE
google_os_login_ssh_public_key : Update of key value should recreate resource

### ISSUE THREAD

**Issue by dinwath** [terraform-providers/terraform-provider-google#6399]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.24
+ provider.google v3.21.0
+ provider.tls v2.1.1

### Affected Resource(s)

* google/resource_os_login_ssh_public_key.go

### Terraform Configuration Files

```tf
locals {
  settings = yamldecode(file("./local_settings.yml"))
}

provider "google" {
  credentials = file(local.settings.creds)
  project     = local.settings.project
  region      = local.settings.region
  zone        = local.settings.zone
}

data "google_client_openid_userinfo" "terraform_service_account" {}

resource "tls_private_key" "ephemeral" {
  rsa_bits  = 2048
  algorithm = "RSA"
}

resource "google_os_login_ssh_public_key" "service_account_key" {
  user = data.google_client_openid_userinfo.terraform_service_account.email
  key  = tls_private_key.ephemeral.public_key_openssh
}
```

### Expected Behavior

Changing the public key fingerprint should have marked the `google_os_login_ssh_public_key` resource for complete substitution

### Actual Behavior

 `google_os_login_ssh_public_key`  is simply marked for in-place update, and upon second apply an error message is raised:
```
Error: Provider produced inconsistent result after apply

When applying changes to google_os_login_ssh_public_key.service_account_key,
provider "registry.terraform.io/-/google" produced an unexpected new value for
was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
### Steps to Reproduce

1. `terraform apply`
2. `terraform taint tls_private_key.ephemeral`
3. `terraform apply`

### References

* #0000

**Comment by venkykuberan** [comment]
Yes, it should recreate the resource. Thanks for filing the issue, I will move this to code change bucket.
