### ISSUE TITLE
google_compute_interconnect_attachment edge_availability_domain recomputing when no edge_availability_domain set

### ISSUE THREAD

**Issue by HammoTime** [terraform-providers/terraform-provider-google#6400]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.24
+ provider.google v3.21.0

### Affected Resource(s)

compute_interconnect_attachment

### Terraform Configuration Files

```tf
resource "google_compute_interconnect_attachment" "tf_test" {
  name         = "terraform-test-interconnect"
  type         = "PARTNER"
  router       = google_compute_router.tf_test.self_link
}
```

### Expected Behavior

The way the variable for `AVAILABILITY_DOMAIN_ANY` is handled is incorrect. The variable should be separate from the state of the interconnect's availability domain. If it is set to ANY, then it will then have an actual availability domain set after creation.

### Actual Behavior

```
# google_compute_interconnect_attachment.tf_test must be replaced
-/+ resource "google_compute_interconnect_attachment" "tf_test" {
        admin_enabled              = true
      ~ bandwidth                  = "BPS_1G" -> (known after apply)
      ~ cloud_router_ip_address    = "169.254.196.241/29" -> (known after apply)
      ~ creation_timestamp         = "2020-05-17T19:19:17.257-07:00" -> (known after apply)
      ~ customer_router_ip_address = "169.254.196.242/29" -> (known after apply)
      - edge_availability_domain   = "AVAILABILITY_DOMAIN_1" -> null # forces replacement
      .... snip ....
}
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I work for Megaport and we are a GCP Partner. I am willing to fix and troubleshoot this issue, as long as the agreed pattern for the fix (where to store the actual state) is agreed to.

I recommend adding a new attribute named `edge_availability_domain_actual` which is computed where the actual state is set. `edge_availability_domain` should stay the same except it doesn't hold the actual state set from the API, and is just used in the initial creation call. Changes to `edge_availability_domain` will still continue to trigger a REPLACE.

Please let me know if this is acceptable and I will start working on the fix.

**Comment by slevenick** [comment]
Hey @HammoTime 

So the issue is that if you don't specify a value for `edge_availability_domain` it may eventually be populated by the API which causes terraform to try to recreate the interconnect to make sure the value doesn't exist?

I think it might be possible to just mark the `edge_availability_domain` field as `Computed` which would let it default a non-existent value in the config to whatever the API returns. Does that sound like it would solve the problem?

**Comment by HammoTime** [comment]
If it’s still user-configurable, I can’t see any problem with that. Sounds awesome.

**Comment by slevenick** [comment]
Ok, I'll get that in. In the meantime you can set a lifecycle ignore on the `edge_availability_domain` field to prevent diffs:

https://www.terraform.io/docs/configuration/resources.html#ignore_changes
