### ISSUE TITLE
Fix TestAccDNSPolicy_dnsPolicyBasicExample

### ISSUE THREAD

**Issue by c2thorn** [terraform-providers/terraform-provider-google#6406]
`Error: Error creating Policy: googleapi: Error 400: Invalid value for 'entity.policyResource.networks[0]': 'projects/ci-test-project-188019/global/networks/tf-test-network-1k2skzzny64', invalid`

**Comment by emilymye** [comment]
Fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/3530
