### ISSUE TITLE
.*. doesn't work on google_compute_subnetwork

### ISSUE THREAD

**Issue by jaksky** [terraform-providers/terraform-provider-google#6416]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.20
+ provider.google v3.7.0
+ provider.google-beta v3.7.0
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0

### Affected Resource(s)

* google_compute_subnetwork

### Terraform Configuration Files

```tf
data "google_compute_network" "default"{
  name = "default"
  project = var.project
}

data google_compute_subnetwork "peered" {
  for_each = toset(data.google_compute_network.default.subnetworks_self_links)
  self_link = each.value
}
```

### Expected Behavior

Get the list with cidr blocks

### Actual Behavior

value = data.google_compute_subnetwork.peered.*.ip_cidr_range

This object does not have an attribute named "ip_cidr_range".

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by venkykuberan** [comment]
@jaksky its not provider related question and i see you raised the same in Terraform general forum which is the best place for it. Hence closing it here ..
