### ISSUE TITLE
google_appengine_standard_version is missing properties on read

### ISSUE THREAD

**Issue by pmarschik** [terraform-providers/terraform-provider-google#6417]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.25

### Affected Resource(s)

* google_appengine_standard_version

### Terraform Configuration Files

```tf
resource "google_app_engine_standard_app_version" "default" {
  project = google_app_engine_application.app.project

  version_id          = var.gae_service_default.version
  service             = "default"
  runtime             = "java8"
  runtime_api_version = "user_defined"
  threadsafe          = true
  instance_class      = "F4_1G"

  deployment {
    zip {
      source_url  = "REDACTED"
      files_count = 1000
    }
  }

  handlers {
    url_regex = "(/.*)"
    static_files {
      path                  = "__static__/root\\1"
      upload_path_regex     = "__NOT_USED__"
      require_matching_file = true
      expiration            = "0s"
    }
    security_level   = "SECURE_OPTIONAL"
    login            = "LOGIN_OPTIONAL"
    auth_fail_action = "AUTH_FAIL_ACTION_REDIRECT"
  }

  handlers {
    url_regex = "/.*"
    script {
      script_path = "unused"
    }
    security_level   = "SECURE_OPTIONAL"
    login            = "LOGIN_OPTIONAL"
    auth_fail_action = "AUTH_FAIL_ACTION_REDIRECT"
  }
}
```

### Expected Behavior

Running `terraform apply` twice should show no changes on the second run.

### Actual Behavior

Since (at least) the `handlers` property is not fetched from the `apps.services.versions` resource terraform always wants to apply changes.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### Important Factoids

The `apps.services.versions` has a query paramter `view` (enum `BASIC` (default) or `FULL`). If using `FULL` for resource reads this would be fixed.

### References

* https://github.com/terraform-providers/terraform-provider-google/pull/6388 /cc @megan07

**Comment by edwardmedia** [comment]
I see below in the plan after `tf apply`
```
      + handlers {
          + auth_fail_action = "AUTH_FAIL_ACTION_REDIRECT"
          + login            = "LOGIN_OPTIONAL"
          + security_level   = "SECURE_OPTIONAL"
          + url_regex        = "(/.*)"
          + static_files {
              + expiration            = "0s"
              + path                  = "__static__/root\\1"
              + require_matching_file = true
              + upload_path_regex     = "__NOT_USED__"
            }
        }
      + handlers {
          + auth_fail_action = "AUTH_FAIL_ACTION_REDIRECT"
          + login            = "LOGIN_OPTIONAL"
          + security_level   = "SECURE_OPTIONAL"
          + url_regex        = "/.*"
          + script {
              + script_path = "auto"
            }
        }
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by pmarschik** [comment]
@edwardmedia after the first `tf apply` or the second `tf apply`?

**Comment by slevenick** [comment]
Thanks for the fix in https://github.com/GoogleCloudPlatform/magic-modules/pull/3536

I'll wait for that PR to get merged in
