### ISSUE TITLE
endpoint_config block in dataproc cluster config not recognized. 

### ISSUE THREAD

**Issue by nielsvaneck** [terraform-providers/terraform-provider-google#6422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
$  terraform --version
Terraform v0.12.25
+ provider.github v2.8.0
+ provider.google v3.22.0
+ provider.google-beta v3.22.0
+ provider.kubernetes v1.11.2
+ provider.netlify v0.4.0
+ provider.random v2.2.1
```

### Affected Resource(s)
* `google_dataproc_cluster`

### Terraform Configuration Files

`dataproc.tf`:
```tf
resource "google_dataproc_cluster" "reporting-cluster" {
  project = google_project.main.project_id
  name    = "reporting-cluster"
  region  = "us-central1"

  cluster_config {
    master_config {
      num_instances    = 1
      machine_type     = "n1-standard-1"
      min_cpu_platform = "Intel Skylake"

      disk_config {
        boot_disk_type    = "pd-ssd"
        boot_disk_size_gb = 15
        num_local_ssds    = 1
      }
    }
    worker_config {
      num_instances = 0
    }
    software_config {
      optional_components = ["PRESTO", "ZEPPELIN"]
      override_properties = {
        "dataproc:dataproc.allow.zero.workers" = "true"
      }
    }
    endpoint_config {
        enable_http_port_access = "true"
    }
  }
}
```

### Debug Output

https://gist.github.com/nielsvaneck/44034613c8106475ac58499b32374039

```
2020/05/19 14:57:13 [ERROR] <root>: eval: *terraform.EvalValidateResource, err: Unsupported block type: Blocks of type "endpoint_config" are not expected here.
2020/05/19 14:57:13 [ERROR] <root>: eval: *terraform.EvalSequence, err: Unsupported block type: Blocks of type "endpoint_config" are not expected here.
```

### Expected Behavior

I expected a single node dataproc cluster with PRESTO and Zeppelin to be created, and to have the public urls available, per the endpoint configuration. 

Note that this functionality should have been enables in the google-beta provider 3.21 release per: 
- https://github.com/terraform-providers/terraform-provider-google-beta/releases/tag/v3.21.0
- https://github.com/terraform-providers/terraform-provider-google-beta/pull/2035

Without the `endpoint_config` block, a cluster is created as expected, which proves the rest of my configuration is OK. 

### Actual Behavior

```bash
$ terraform validate     

Error: Unsupported block type

  on dataproc.tf line 27, in resource "google_dataproc_cluster" "reporting-cluster":
  27:     endpoint_config {

Blocks of type "endpoint_config" are not expected here.
```

### Steps to Reproduce

1. `terraform validate` or `terraform apply`

### Important Factoids

I've tested this with both the 3.21 and 3.22 release of the google-beta provider.  The issue occurs in both.

### References

- https://github.com/terraform-providers/terraform-provider-google-beta/releases/tag/v3.21.0
- https://github.com/terraform-providers/terraform-provider-google-beta/pull/2035

**Comment by edwardmedia** [comment]
@nielsvaneck can you share your full debug log?

**Comment by nielsvaneck** [comment]
Done

**Comment by edwardmedia** [comment]
@nielsvaneck  I just successfully created a dataproc cluster  with endpoint_config in place. Can you add `provider = google-bera`  explicitly inside the `resource` and then try?
```
resource "google_dataproc_cluster" "dev" {
provider = google-beta
```

**Comment by nielsvaneck** [comment]
That worked.. thanks for that work-around!   But am I wrong in assuming there's still something wrong here?

**Comment by edwardmedia** [comment]
@nielsvaneck Maybe, it depends on how you want to set the provider configuration overall. Here is the doc you might want to review for your case. I am glad the suggestion works for you. I am closing the issue then. Thanks

https://www.terraform.io/docs/providers/google/guides/provider_reference.html

**Comment by nielsvaneck** [comment]
looks like I just missed that configuration detail in the doc. it clearly says using beta features requires specifying the beta provider.  hope not too many people run into this. 

thank you for your help!
