### ISSUE TITLE
Error: key "ssh-keys" already present in metadata for project  in GCP 

### ISSUE THREAD

**Issue by vikas4cloud** [terraform-providers/terraform-provider-google#6440]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version 
Terraform v0.12.24
+ provider.google v3.11.0

### Affected Resource(s)

* google_XXXXX
Terraform v0.12.24
+ provider.google v3.11.0

### Terraform Configuration Files

```tf
main.tf
resource "google_compute_project_metadata_item" "username" {
  key   = "ssh-keys"
  value = var.users
}

variables.tf
variable "users" {}
```

### Panic Output

Error: key "ssh-keys" already present in metadata for project

google_compute_project_metadata_item.username: Creating...
Error: key "ssh-keys" already present in metadata for project "solid-ridge-266407". Use `terraform import` to manage it with Terraform
  on main.tf line 1, in resource "google_compute_project_metadata_item" "username":
   1: resource "google_compute_project_metadata_item" "username" {
 
### Expected Behavior

Expecting to add the provided key to the metadata/sshKeys
https://console.cloud.google.com/compute/metadata/sshKeys

### Actual Behavior

its replacing the previous sshKeys  its not appending 

it should append as well as should not delete the previous terraform apply  

### Steps to Reproduce

1.  `add users key in terraform.tfvars file` 
2. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@vikas4cloud This is expected behavior, If you have already created the metadata using other methods, terraform does not have knowledge about it, and then will not overwrite it. That is why you have to create the state by calling `terraform import` before you can let terraform to manage it. Also the metadata is a pair of key/value. It does not support multiple values for a key as you mentioned `append`. Does this make sense to you?

**Comment by vikas4cloud** [comment]
@edwardmedia Thanks for your message let assume its a expected behavior of terraform then how to add more keys

as well as i have added the 2 keys (first time) with terraform only 

scenario 1   if i want to add another 2 keys how can i add keys ??
my use case is i want to add 2 more new keys to metadata (2 already added via same terraform script)so after execution of terraform it should have to be 2 new and 2 old keys in metadata total 4 

scenario 2 - if i am adding 2 new keys via terraform script its replacing old keys and adding only new 2 keys

working scenario 3 if i will keep all previous keys and appending the 2 more new keys then its adding but keeping all keys for adding new key is not a good practice for me.

can u let is know if this is a expected behiver than how can we achieve (adding more keys)

we would not like to use import as our jenkins jobs have same mechanism(init-plan-apply) for Iac

**Comment by edwardmedia** [comment]
@vikas4cloud you may use below way or Terraform dynamic blocks feature to create multiple keys.  Keep in mind, if you have already had keys that were created through non-Terraform methods, you have to run `terraform import` first before you can use Terraform to manage all keys. 

```tf
resource "google_compute_project_metadata_item" "item1" {
  key   = "key1"
  value = "value1"
}
resource "google_compute_project_metadata_item" "item2" {
  key   = "key2"
  value = "value2"
}
```

**Comment by edwardmedia** [comment]
@vikas4cloud I am closing this issue at this moment. Please feel free to reopen it if you still have related questions
