### ISSUE TITLE
Support root password for google_sql_database_instance MySQL

### ISSUE THREAD

**Issue by talonx** [terraform-providers/terraform-provider-google#6441]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The google_sql_database_instance resource should support supplying the root password. This field is optional in the GCP UI but we would like to set it.

### New or Affected Resource(s)

* google_sql_database_instance

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_sql_database_instance" "master" {
  name             = "master"
  database_version = "MYSQL_5_7"
  region           = var.region

  root_password = "xxx"

  replica_configuration {
    failover_target = true
  }

  settings {
    tier = "db-n1-standard-1"
    availability_type = "REGIONAL"
    backup_configuration {
      binary_log_enabled = true
      enabled = true
      start_time = "00:00"
    }
    maintenance_window {
      day = 7
      hour = 0
      update_track = "stable"
    }
  }
}

```

### References

* #4776 which is about MSSQL, not MySQL

**Comment by danawillow** [comment]
Hey @talonx, this seems pretty discouraged going by the deprecation in gcloud (https://cloud.google.com/sdk/gcloud/reference/sql/instances/set-root-password). Can you use the `google_sql_user` resource instead?

**Comment by talonx** [comment]
@danawillow Thanks, that works.
