### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by jiristepan** [terraform-providers/terraform-provider-google#6456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.25
+ provider.google v3.22.0

### Affected Resource(s)

* google_project_iam_member

### Terraform Configuration Files

```tf
provider "google" {
  project = var.project_id
  region  = var.region
  zone    = var.zone
}

locals {
  project_id = var.project_id
}

# ADD USERS
resource "google_project_iam_member" "member" {
  project = local.project_id
  role    = "roles/editor"
  count = length(var.users)
  member  = "user:${var.users[count.index]}@${var.users_domain}"
}

```

### Debug Output
https://gist.github.com/jiristepan/a70f4da248821c769a0747726caa49bc

### Expected Behavior

Should create 4 users.

### Actual Behavior

Created only 3 users, the last one in the var.users variable has not been created

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
no, standard useage

### References

* #0000

**Comment by edwardmedia** [comment]
@jiristepan  can you show me how you provide `var.users`?

**Comment by jiristepan** [comment]
terraform.tfvars
```tf
project_id="activate-test-project-2"
region="europe-west3"
zone="europe-west3-a"

users_domain="etnetera.cz"
users=["leona.ledinska","hana.kalivodova","filip.hanzl","jana.zuzanakova"]
```
variables.tf
```tf
variable "project_id" {
  description = "GCP project id"
  type = string
}

variable "region" {
  description = "GCP project region"
  type = string
  default = "europe-west3"
}
variable "zone" {
  description = "GCP project zone"
  type = string
  default = "europe-west3-a"
}

variable "users_domain" {
    description = "the domain of users"
    default = "etnetera.cz"
}

variable "users" {
  description = "list of editors of the project"
  type = list(string)
}

```

I tried to get debug.log now, but when I ran the code, averything finished ok and the fourth user has beed added. So no way ho to reproduce the bug ;-(

**Comment by edwardmedia** [comment]
@jiristepan thank you for reporting this issue. It seems that you were just in the middle of changing code from using individual `iam member` resource for each user to using one resource dynamically for all users. It created a race condition when you applied the plan as Terraform tried to write and delete the same record at the same time. To avoid this as a workaround, you may call apply twice: first remove the dynamic code and call `terraform apply` and then add the dynamic code back in and call `terraform apply` again.

**Comment by danawillow** [comment]
I don't think there are any provider changes we can make here, since this was caused by Terraform attempting to destroy and create different resources in parallel, which is exactly what it should be doing. I agree that @edwardmedia's suggestion is going to be the easiest way to apply these sorts of changes in the future.
