### ISSUE TITLE
default service account used instead of explicit credentials file

### ISSUE THREAD

**Issue by mboogerd** [terraform-providers/terraform-provider-google#6457]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.25
+ provider.google v3.22.0
```

### Affected Resource(s)

As this concerns authentication / authorisation, I'm expecting it to affect all resources / data sources. However, I have specifically observed this when deploying cloud **functions**. Haven't tested anything else just yet.

### Terraform Configuration Files

These are the project files with some values substituted with `anonymised1` ... `anonymised5`:

`main.tf`
```tf
provider "google" {
  credentials = file("gcp-key.json")
  project     = "anonymised3"
  region      = "europe-west1"
}

module "email" {
  source = "./email"
}
```

`email/email.tf`
```tf
resource "google_cloudfunctions_function" "function" {
  name                = "send-email"
  description         = "Sends emails from anonymised2.nl contact form to anonymised4"
  runtime             = "nodejs10"
  available_memory_mb = 128
  trigger_http        = true
  source_repository {
    url = "https://source.developers.google.com/projects/anonymised3/repos/github_anonymised2_backend/"
  }
}
```

`gcp-key.json`
```json
{
    "type": "service_account",
    "project_id": "anonymised3",
    "private_key_id": "anonymised6",
    "private_key": "anonymised5",
    "client_email": "mcboo-256@anonymised3.iam.gserviceaccount.com",
    "client_id": "109079154250184834508",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/mcboo-256%40anonymised3.iam.gserviceaccount.com"
  }
  ```

### Debug Output

These are the raw debug logs, with 4 values substituted with `anonymised1` ... `anonymised4`. :
https://gist.github.com/mboogerd/62749acca9fff20a071480f9aa06de1d

Replacements are done consistent with the replacements in project files.

### Expected Behavior

I would have expected my credentials file to be used, which contains a key for a specifically created service account to be used from my machine.

### Actual Behavior

Terraform attempts to authenticate/authorise using the default service account for the project instead. This fails as that account is not authorised, which can be observed in the logs.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Don't know whether these matter, but they might:

- On macOS Catalina 10.15.4
- gcloud installed

### References

* There is an open issue that closely matches this one in the main terraform repository: https://github.com/hashicorp/terraform/issues/21562

**Comment by edwardmedia** [comment]
@mboogerd  I have followed your code and it seems to be fine with me. Which one is your default account? How did you know the default account was used instead of the credential file? Can you disable the default account and then watch the log difference?

**Comment by mboogerd** [comment]
Hi @edwardmedia, thanks for looking into this!

> Which one is your default account?

That would be `anonymised3@appspot.gserviceaccount.com`

> How did you know the default account was used instead of the credential file?

`terraform apply` reports the error message on exit: `Missing necessary permission iam.serviceAccounts.actAs for $MEMBER on the service account anonymised3@appspot.gserviceaccount.com.`

That account doesn't match the one in my credentials file.

> Can you disable the default account and then watch the log difference?

Good suggestion! I have tried this, but it made no difference

Reading the error again though, I may have misunderstood what is going wrong.
1. The account it tries to _authenticate_ with might be `$MEMBER`, not `anonymized3`. I do wonder what it means that the actual account name is not returned instead of a placeholder.
2. GCP requires my credentials account to be _authorised to impersonate_ the default account. But I am clueless as to why that would matter when simply stating that a function needs to be deployed using a particular service-account.

Could this be GCP throwing me off rather than a terraform bug? For my GCP setup I have done the following:
- Create a new project
- Enable GCP functions
- Setup a synchronised cloud source repository
- Add a service account for terraform deployment with (1) developer privileges for functions and (2) read access to the cloud source repo

I can't quite tell what the cause is. If you want to have another look, perhaps this is sufficient to work with? Let me know otherwise, I'll be happy to provide more information!

**Comment by edwardmedia** [comment]
@mboogerd  I am not quite sure what you intended to do. Running Terraform scripts and running Cloud functions are totally different things.

> Add a service account for terraform deployment with (1) developer privileges for functions and (2) read access to the cloud source repo

There are two accounts you have: one is used to run Terraform which is specified in the file you provided, and the other is used to run your cloud functions.  When you enable cloud function, GCP creates the default account for you. Its format is like `xxxx@appspot.gserviceaccount.com` If you plan to use a different account to run your Cloud functions, you can provide it to `service_account_email ` in the resource like below 
 ```tf 
resource "google_cloudfunctions_function" "function" {
  name                = "send-email"
  description         = "Sends emails from anonymised2.nl contact form to anonymised4"
  service_account_email = "your-account@example.com"
}
```
Does this make sense to you?

**Comment by mboogerd** [comment]
> @mboogerd I am not quite sure what you intended to do in below step. Running Terraform scripts and running Cloud functions should be treated totally different things.

> > Add a service account for terraform deployment with (1) developer privileges for functions and (2) read access to the cloud source repo

I may have been unclear, so to make sure we're on one line about what has happened. What I intended to do is to create a service account that I could use from terraform and that would have the permission to _deploy_ a function. That's the account that

- I manually added to GCP
- I gave the developer role for functions (which gives it deploy function permission, which is what I was really after)
- I gave read access to my source repo (just to make sure, as I wasn't certain whether it was the deployer or the runner that would require read access)
- I added to my terraform credentials

In effect, I would expect that this is the account the terraform runner uses, and that it is permitted to deploy functions.

> If you plan to use a different account to run your Cloud functions

Sorry to have confused you there, but no, for now I am fine using the default account to _run_ the function. I am mainly interested in making sure that there is a dedicated account for _deploying_ the function.

Hope this clarifies things!

**Comment by edwardmedia** [comment]
@mboogerd under Actual Behavior you indicated below which may not be the right case. That is why I wanted you to double check which account is used to run Terraform (not the default account, I think)   

> Terraform attempts to authenticate/authorise using the default service account for the project instead.
To resolve your issue, below is what the log complains which indicates you may need to do with the default account for running Cloud functions. 

> Missing necessary permission iam.serviceAccounts.actAs for $MEMBER on the service account anonymised3@appspot.gserviceaccount.com.
Ensure that service account anonymised3@appspot.gserviceaccount.com is a member of the project anonymised3, and then grant $MEMBER the role 'roles/iam.serviceAccountUser'. 
You can do that by running 'gcloud iam service-accounts add-iam-policy-binding anonymised3@appspot.gserviceaccount.com --member=$MEMBER --role=roles/iam.serviceAccountUser' 
In case the member is a service account please use the prefix 'serviceAccount:' instead of 'user:'., forbidden

**Comment by mboogerd** [comment]
Well, I feel daft now. You're right, it was telling me what to do. I refused to do that because it didn't make sense to me, and it still doesn't, but it did fix it. I'm going to be doing some reading up on IAM. Thank you for your time and patience, it is much appreciated! :)
