### ISSUE TITLE
Cloud functions: Example with Permissions

### ISSUE THREAD

**Issue by kaihendry** [terraform-providers/terraform-provider-google#6459]
Hi, I come from AWS where it's relatively easy to express permissions inline with my serverless functions via `AssumeRolePolicyDocument` or `ManagedPolicyArns`, however I'm very confused how to add [compute.instances API access](https://stackoverflow.com/questions/61999907/terraforming-cloudfunctions-that-need-compute-instances-permissions).

IIUC I need to create a service account in advance, and then add it via [cloudfunctions_cloud_function_iam](https://www.terraform.io/docs/providers/google/r/cloudfunctions_cloud_function_iam.html), however I'm struggling to find any examples of this surely common use case.

Is there an example I could please refer to?

**Comment by venkykuberan** [comment]
Here is the example, you can refer other compute roles [here](https://cloud.google.com/compute/docs/access/iam#compute.admin) 

resource "google_cloudfunctions_function_iam_member" "member" {
  project = google_cloudfunctions_function.function.project
  region = google_cloudfunctions_function.function.region
  cloud_function = google_cloudfunctions_function.function.name
  role = "roles/compute.admin"
  member = "serviceAccount:<emailid>"
}

**Comment by kaihendry** [comment]
Does that `member = "serviceAccount:"` need to be there? I don't quite understand how permissions work. I thought the role or permission was assigned to a service account (which needs to be created?) and then you assume the service account in GCP.

**Comment by venkykuberan** [comment]
google_cloudfunctions_function_iam_member is Non-Authoritative function (i.e), it retains the other users for that role and include the following user to the list.

The following resource basically gives the read/write and invocation access of the cloud function to the given service account. 
  `member=` has 2 parts
  1) type of the user (regular, service account etc)
   2) actual email id.

Note: - This resource is just set the access control on the cloud function, you would see the users you added by this resource under Permissions tab on the cloud console.

```
resource "google_cloudfunctions_function_iam_member" "member" {
  project = google_cloudfunctions_function.function.project
  region = google_cloudfunctions_function.function.region
  cloud_function = google_cloudfunctions_function.function.name
  role = "roles/editor"
  member = "serviceAccount:svc-acct@project_id.iam.gserviceaccount.com"
}
```
To get a better understanding about Cloud Functions and Functions Identity, please refer here https://cloud.google.com/functions/docs/securing. Hope this helps, if so please close the issue.

**Comment by kaihendry** [comment]
So IIUC I need to know the service account email in advance before deploying this cloud function? It can't be inferred by the project?

RE roles upon https://cloud.google.com/compute/docs/access/iam#compute.admin ... it seems to imply I need both roles/compute.instanceAdmin in order to use roles/compute.instanceAdmin. I am not sure how to express that when one `role =` is used.

**Comment by venkykuberan** [comment]
By default cloud function deployed with App Engine default service account which has project wide editor access. If you want to deploy the cf with non-default sa, you need to use your sa email on this resource - https://www.terraform.io/docs/providers/google/r/cloudfunctions_function.html. In this case you need to get the sa email prior.

This doc helps to understand the function identity- https://cloud.google.com/functions/docs/securing/function-identity
