### ISSUE TITLE
non RFC-1918 GKE clusters

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#6465]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#networkconfig (defaultSnatStatus)

### New or Affected Resource(s)

* google_container_cluster

### References

* b/157146525

**Comment by tvvignesh** [comment]
@danawillow Hi there. I have been facing the same issue with GKE private clusters which I have reported here: https://github.com/terraform-providers/terraform-provider-google/issues/6537

May I know what the temporary resolution could be to solve this issue so that I can move forward without being stuck till this is out. Thanks.

**Comment by mkushakov** [comment]
@tvvignesh for me solution was to move `master_ipv4_cidr_block` to RFC-1918 range - https://cloud.google.com/vpc/docs/vpc#valid-ranges

**Comment by tvvignesh** [comment]
@mkushakov Ahh.. Thanks a lot. Let me try it out. Will reply back with the status :+1:

**Comment by tvvignesh** [comment]
@mkushakov Tried RFC 1918 range and few other things to make it work. Thanks.

@danawillow @venkykuberan There is one question that I wanted to ask. I use a shared vpc within which I have subnets where I am hosting my private K8 clusters across different zones.

After struggling a lot, I found out that when I created the cluster in this subnet, it worked:
```
{
      ip_cidr_range = "10.0.2.0/24"
      name          = "my-subnet-1"
      region        = "asia-south1"
      secondary_ip_range = {
        pods     = "172.18.0.0/20"
        services = "192.168.10.0/24"
      }
}
```

but if I try to create the same cluster without any changes in this subnet, I get the SNAT error:

```
{
      ip_cidr_range = "10.0.20.0/24"
      name          = "my-subnet-2"
      region        = "asia-south1"
      secondary_ip_range = {
        pods     = "172.40.0.0/20"
        services = "192.168.100.0/24"
      }
}
```

where both these subnets are part of the same shared vpc in the same region. I am not good at networking, but can you tell me why is this the case?

**Comment by 9474757** [comment]
Before run TF need to use "export TF_VAR_masquerade=false"
