### ISSUE TITLE
Alert policy is incorrectly created and breaks UI editor

### ISSUE THREAD

**Issue by rottenbytes** [terraform-providers/terraform-provider-google#6469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.24
+ provider.google v3.23.0
+ provider.google-beta v3.23.0

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_monitoring_alert_policy" "pci_controls_10_2_6_surge" {
  display_name = "New logging from GCE VM detected or log surge alert (PCI 10.2.6)"
  combiner = "OR"
  conditions {
    display_name = "New logging from GCE VM detected or log surge alert (PCI 10.2.6)"
    condition_threshold {
      filter = "metric.type=\"logging.googleapis.com/log_entry_count\" resource.type=\"gce_instance\""
      duration = "0s"
      comparison = "COMPARISON_GT"
      threshold_value = 500.0
      trigger {
        count = 1
      }

      aggregations {
        cross_series_reducer = "REDUCE_MEAN"
        alignment_period = "300s"
        per_series_aligner = "ALIGN_RATE"
        group_by_fields = [ "resource.label.instance_id" ]
      }

     # this is the block that causes the problem
      aggregations {
        alignment_period = "300s"
        per_series_aligner = "ALIGN_PERCENT_CHANGE"
      }
    }
  }
}
```

### Expected Behavior

The second aggregation block is supposed  make the "configuration" part (in the UI) be a 500% increase of the last 5 minutes

### Actual Behavior

It brings the whole condition editor in RO mode, displaying (incorrectly) the JSON

### Steps to Reproduce

1. `terraform apply` with this resource

### Informations :

Getting the JSON description using `gcloud alpha monitoring policies describe projects/.../.../.... --format=json` lets me think my TF code is valid. I can't tell if the bug is on GCP or TF side exactly

**Comment by edwardmedia** [comment]
@rottenbytes  I am not super familiar with the expected behavior. Below is what I see. What is what you expected?
```
   "aggregations": [
      {
        "alignmentPeriod": "300s",
        "crossSeriesReducer": "REDUCE_MEAN",
        "groupByFields": [
          "resource.label.instance_id"
        ],
        "perSeriesAligner": "ALIGN_RATE"
      },
      {
        "alignmentPeriod": "300s",
        "perSeriesAligner": "ALIGN_PERCENT_CHANGE"
      }
    ],
```

**Comment by edwardmedia** [comment]
@rottenbytes is this still an issue with you?

**Comment by rottenbytes** [comment]
Hello,

I changed the aligner and reducer (and the values of course) to get a "working alert condition". I still can't figure out the culprit of the behaviour but I'm fine with my setup now

**Comment by edwardmedia** [comment]
OK I am closing the issue right now. Please feel free to reopen it if you have further info. Thanks
