### ISSUE TITLE
google_compute_subnetwork, region change gives provider bug error

### ISSUE THREAD

**Issue by rbianchi29** [terraform-providers/terraform-provider-google#6470]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform 0.12.20 (Tested with 0.12.25)
Google Provider 3.19.0 (Tested with 3.23.0 as well)

### Affected Resource(s)

* google_compute_subnetwork

### Terraform Configuration Files

provider.tf
terraform {
  required_providers {
    google = "~> 3.19.0"
  }
}

provider "google" {
  credentials = file("account.json")
}

main.tf
terraform {
  required_version = "0.12.20"
}

resource "google_project" "my_project" {
  name                = "test-subnetwork-region-270520"
  project_id          = "test-subnetwork-region-270520"
  folder_id           = "111111111"
  billing_account     = "11111-11111-11111"
  auto_create_network = false
}

resource "google_project_service" "project" {
  project = google_project.my_project.project_id
  service = "compute.googleapis.com"

  disable_dependent_services = true
}

resource "google_compute_network" "vpc_network" {
  name                    = "test-vpc-network"
  project                 = google_project.my_project.project_id
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "subnet" {
  name          = "test-subnetwork"
  ip_cidr_range = "10.2.0.0/16"
  region        = "europe-west2"
  network       = google_compute_network.vpc_network.id
  project       = google_project.my_project.project_id
}

### Debug Output

https://gist.github.com/rbianchi29/fca2604337101f2d8b506f7885fff013

### Expected Behavior

The subnetwork should have been recreated with the updated region.

### Actual Behavior

Terraform fails with this error.
"When applying changes to google_compute_subnetwork.this[0], provider
"registry.terraform.io/-/google" produced an unexpected new value for was
present, but now absent."

### Steps to Reproduce

1. Run `terraform apply`
2. Once completed, change the region to another (i.e. europe-west1 > europe-west2)
3. Re run `terraform apply`

### Important Factoids

Service account is used for deployment.

**Comment by edwardmedia** [comment]
Looks like this is a legit use case.
