### ISSUE TITLE
google_bigquery_data_transfer_config - clustering fields

### ISSUE THREAD

**Issue by kurtmaile** [terraform-providers/terraform-provider-google#6477]
Hi,

Sorry I cant find in the examples how to set table cluster fields. I can set a partitioning_field fine of course,  but on a table, how do I define a clustering keys?

```
resource "google_bigquery_data_transfer_config" "xxxx"  {

  display_name = "x"
  location = "EU"
  data_source_id = "scheduled_query"
  schedule = "every day 23:55"
  destination_dataset_id = "x"
  params = {
    destination_table_name_template = "x"
    write_disposition = "WRITE_TRUNCATE"
    query = "SELECT * FROM `x`"
    partitioning_field = "TransactionDate"
    **clustering** = "y,z" **<- this what is the param to use?**
  }
...
```
Thanks!

**Comment by edwardmedia** [comment]
@kurtmaile  which specific field(s) are you referring to? Can you provide a link to that document? Can you set `table cluster` field using other tools, like `gcloud`?

**Comment by kurtmaile** [comment]
Hi,

In SQL, I can create a clustered table as below.  Current in the google_bigquery_data_transfer_config I can specify ```partitioning_field```, but im not sure on the equiv of the clustering field(s) in a google_bigquery_data_transfer_config

```
CREATE TABLE `project.dataset.table` 
PARTITION BY p
CLUSTER BY a,b,c
AS
  SELECT * FROM `x`
```

**Comment by edwardmedia** [comment]
@kurtmaile do you know if bigquery supports that feature?

**Comment by kurtmaile** [comment]
Hi,

Thanks - tt definitely does, we create tables with clustering fields with SQL.

Should just be another variable in 'params' for the TF object.

Cheers
K

**Comment by edwardmedia** [comment]
@kurtmaile can you point a doc that shows the use of the field(s)?

**Comment by kurtmaile** [comment]
Hey,

https://cloud.google.com/bigquery/docs/creating-clustered-tables#bq

bq cmd line, they use 'clustering_fields' as shown in the link above.  I tried that with below setup:

Terraform v0.12.23
+ provider.aws v2.45.0
+ provider.google v3.4.0
+ provider.template v2.1.2

and got:

Error: Error updating Config Error 400: Data source definition doesn't define this parameter Id: clustering_fields

thanks
K

**Comment by edwardmedia** [comment]
@kurtmaile Thank you for the info. We will put the request into backlog.

**Comment by edwardmedia** [comment]
@kurtmaile  are you looking for `clustering` in the **google_bigquery_table** instead of `google_bigquery_data_transfer_config`? 

https://www.terraform.io/docs/providers/google/r/bigquery_table.html#clustering

**Comment by kurtmaile** [comment]
Hi,

Thanks.  No just like how partitioning is enabled in scheduled queries (data transfer) when tables are created by the transfer itself, clustering is an option on the table also.

So while this is as you say is a property on an actual table object, the transfer config itself also creates tables, thus, we also want to specify clustering fields alongside partitioning (currently supported) when the transfer does this.

I just checked, and the new BQ console UI only offers partitioning as an option now, but the API may support it even if the UI doesnt, think the old UI did.

Cheers
Kurt

**Comment by edwardmedia** [comment]
@kurtmaile If the API supports it, could you provide the link?
Below is the one I am looking at. Can you specify which field you are referring to?
https://cloud.google.com/bigquery-transfer/docs/reference/datatransfer/rest/v1/projects.locations.transferConfigs

**Comment by edwardmedia** [comment]
@kurtmaile I am closing this issue at this moment. Please feel free to reopen it you need further assistance on your question.
