### ISSUE TITLE
google_compute_subnetwork (beta),  updating purpose forces replacement 

### ISSUE THREAD

**Issue by edwardmedia** [terraform-providers/terraform-provider-google#6481]
### Affected Resource(s)

* google_compute_subnetwork (beta)

### Expected Behavior

Updating  **purpose** should like **role** do partial replacement

### Actual Behavior

Changing **purpose** will force the subnetwork recreation.

### Important Factoids

It appears the PATCH is supported for field **purpose** 
( Note **role** was introduced at the same time and `if d.HasChange("role")` was added in the code )

https://cloud.google.com/compute/docs/reference/rest/beta/subnetworks/patch

**Comment by danawillow** [comment]
@edwardmedia I don't think the field can be updated. I tried it in API explorer and got the response:
```
{
  "error": {
    "code": 400,
    "message": "Invalid value for field 'resource': '{  \"fingerprint\": \"KN4X1G0qzB0=\",  \"purpose\": \"INTERNAL_HTTPS_LOAD_BALANCER\"}'. The following field(s) specified in the request cannot be modified: [purpose]",
    "errors": [
      {
        "message": "Invalid value for field 'resource': '{  \"fingerprint\": \"KN4X1G0qzB0=\",  \"purpose\": \"INTERNAL_HTTPS_LOAD_BALANCER\"}'. The following field(s) specified in the request cannot be modified: [purpose]",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

Closing this since I think there's nothing to do here.
