### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by Pritilender** [terraform-providers/terraform-provider-google#6486]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.26
+ provider.google v3.23.0
```

### Affected Resource(s)

* google_project_service

### Terraform Configuration Files

```tf
provider "google" {
  version = "~> 3.0"
  project = "m-tools-terraform-admin"
}

resource "google_project" "foo" {
  name = "foo-bar-baz"
  project_id = "foo-bar-baz-test"
  org_id = var.organization_id
  billing_account = var.billing_account_id
}

resource "google_project_service" "foo" {
  project = google_project.foo.id
  service = "firebase.googleapis.com"

  disable_dependent_services = true
}
```

### Debug Output

[Gist to the debug output](https://gist.github.com/Pritilender/3833a96ce28dc8bddee1fd234f40eb80)

### Expected Behavior

The API service should been enabled for the project.

### Actual Behavior

I get following error from TF: "Error: Provider produced inconsistent result after apply"
And the API service is not enabled, even after multiple apply runs.

### Steps to Reproduce

1. `terraform apply`

### References

I saw a few of issues with similar name, but from my investigation, there is no issue regarding `google_project_service` resource.

**Comment by edwardmedia** [comment]
@Pritilender can you take a look below solution and see if that helps address your issue? 

https://github.com/terraform-providers/terraform-provider-google/issues/6377

**Comment by Pritilender** [comment]
@edwardmedia I've tried the approach with `null_resource` and the other approach with depending on the project, but with no success. The issue persists.

**Comment by edwardmedia** [comment]
@Pritilender can you post the new code with `null_resource` added?

**Comment by Pritilender** [comment]
Yes, here's the code:

```terraform
provider "google" {
  version = "~> 3.0"
  project = "m-tools-terraform-admin"
}

resource "google_project" "foo" {
  name = "foo-bar-baz"
  project_id = "foo-bar-baz-test1"
  org_id = var.organization_id
  billing_account = var.billing_account_id
}

resource "null_resource" "delay" {
  provisioner "local-exec" {
    command = "sleep 60"
  }
  triggers = {
    "project" = "${google_project.foo.id}"
  }
}

resource "google_project_service" "foo" {
  project = google_project.foo.id
  service = "firebase.googleapis.com"

  disable_dependent_services = true
  depends_on = [null_resource.delay]
}
```

**Comment by edwardmedia** [comment]
@Pritilender there is an issue `google_project`. `google_project.foo.id` is not good used for `google_project_service`. To workaround, you may use below code instead. Please let me know how it works. Thanks
```tf 
resource "google_project_service" "foo" {
  project = "foo-bar-baz-test"
  service = "firebase.googleapis.com"

  disable_dependent_services = true
  depends_on = [null_resource.delay]
}
```

**Comment by edwardmedia** [comment]
@Pritilender Please try to use `project_id` instead of `id` in above code. I am closing this issue. Please feel free to reopen it if your problem remains. Thanks

**Comment by Pritilender** [comment]
@edwardmedia Sorry for taking me a few days to reply.

Changing `id` to `project_id` works! Thank you!
