### ISSUE TITLE
Add request type (POST/GET) setting for stackdriver monitoring uptime checks

### ISSUE THREAD

**Issue by thomasLeclaire** [terraform-providers/terraform-provider-google#6495]
### Description

sounds like the API allow now to define the request type for uptime checks (not available in the google UI however)

https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.uptimeCheckConfigs#requestmethod

so would be a good added value to also allow it here : https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_monitoring_uptime_check_config.go

### New or Affected Resource(s)

* google_monitoring_uptime_check_config

**Comment by tishen25** [comment]
Starting to work on this issue.
