### ISSUE TITLE
google_container_registry builds invalid request URL

### ISSUE THREAD

**Issue by kitschysynq** [terraform-providers/terraform-provider-google#6501]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.26
+ provider.google v3.23.0
+ provider.kubernetes v1.11.3

### Affected Resource(s)

* google_container_registry

### Terraform Configuration Files

```tf
resource "google_container_registry" "dev-registry" {
  project  = var.project_key
  location = "US"
}
```

### Debug Output

This is running in Terraform Cloud, so I don't have debug output but the output of the run is [here](https://gist.github.com/kitschysynq/9db12d9bc7e618e2826fc07ae7db7067).

### Panic Output

N/A

### Expected Behavior

A new Container Registry should be created

### Actual Behavior

The provider builds a URL that doesn't parse, and so the request fails.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by megan07** [comment]
Hi @kitschysynq !  Thanks for opening this issue, I'm sorry it's not working for you. Are you able to provide me more of your configuration file? I'm unable to reproduce it with just the `google_container_registry` resource. I'm specifically interested in how it's being used with the k8s provider, but the more you can provide me, hopefully the quicker I can solve the issue.
Thanks!

**Comment by kitschysynq** [comment]
:facepalm: 

The config was changed so that `var.project_key` did in fact contain that json key. Sorry for the false alarm.
