### ISSUE TITLE
How do I provision with APIs enabled?

### ISSUE THREAD

**Issue by kaihendry** [terraform-providers/terraform-provider-google#6508]
I want to avoid situations like this:

<img src="https://s.natalian.org/2020-06-02/1591067228_2560x1440.png">

When my terraform provisioned function is executed and fails due to a API not being enabled. How can I avoid this situation in my code https://github.com/kaihendry/gcp-label

**Comment by edwardmedia** [comment]
@kaihendry  you may use `google_project_service` to enable APIs. https://www.terraform.io/docs/providers/google/r/google_project_service.html

**Comment by kaihendry** [comment]
So if my [function](https://github.com/kaihendry/gcp-label/blob/master/src/main.go) uses {compute,iam} APIs, I need something like:

```
resource "google_project_service" "compute" {
  project = var.project_name
  service = "compute.googleapis.com"
}
 
resource "google_project_service" "iam" {
  project = var.project_name
  service = "iam.googleapis.com"
}
```
IIUC, in my https://github.com/kaihendry/gcp-label/blob/master/main.tf

**Comment by edwardmedia** [comment]
@kaihendry looks right to me. Keep in mind it may take a little long time to enable the services.

**Comment by edwardmedia** [comment]
@kaihendry I am closing this issue.at this moment. Please feel free to reopen it if you still have the question about how to enable the APIs via Terraform. Thanks
