### ISSUE TITLE
Add name collision warning/reminder in google_storage_bucket errors 

### ISSUE THREAD

**Issue by caieo** [terraform-providers/terraform-provider-google#6542]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

If a user is trying to reference a Storage Bucket that exists already, but they do not have the permission to access it, Terraform correctly returns a IAM error. However, it's awfully common for users to accidentally be creating a Storage Bucket with the same name as one that already exists and it would be helpful to indicate/remind users to make sure they're using a unique Storage Bucket name rather than go down a rabbit hole of investigating if your IAM permissions are set up properly.

### New or Affected Resource(s)

* google_storage_bucket

### Potential Terraform Configuration

n/a

### References

n/a

**Comment by danawillow** [comment]
Closing as per offline discussion.
