### ISSUE TITLE
google_sql_database_instance retry loop on reused name

### ISSUE THREAD

**Issue by carlpett** [terraform-providers/terraform-provider-google#6544]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.26
+ provider.google v3.22.0
```

### Affected Resource(s)

`google_sql_database_instance`

### Terraform Configuration Files

```tf
resource "random_id" "db_name_suffix" {
  byte_length = 4
}
resource "google_sql_database_instance" "instance" {
  name             = "some-name-${random_id.db_name_suffix.hex}"
  region           = "us-central1"
  database_version = "POSTGRES_11"
  settings {
    tier = "db-f1-micro"
  }
}
```

### Expected Behavior

We `terraform destroy`:ed the instance, but did not destroy the random id, leading to the new instance trying to use the same name as the old one (which we are aware is not possible).
Expected would be a hard error when GCP returns an error.

### Actual Behavior

Terraform got stuck until timeout. Looking at the Stackdriver Logs, we found a http 400/"`error 2`" code, which Terraform appears to treat as retryable, and keeps retrying forever.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy -target google_sql_database_instance.instance`
3. `terraform apply`

**Comment by venkykuberan** [comment]
@carlpett Its a known issue and we have an open issued with upstream - https://github.com/terraform-providers/terraform-provider-google/issues/6066

 I see a work around mentioned [here](https://github.com/terraform-providers/terraform-provider-google/issues/6066#issuecomment-620489346) for the same issue. Closing this one as we are already tracking it on other.
