### ISSUE TITLE
google_sql_database_instance does not recreate when changing to private network

### ISSUE THREAD

**Issue by carlpett** [terraform-providers/terraform-provider-google#6545]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.26
+ provider.google v3.22.0
```

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "instance" {
  name             = "some-name"
  region           = "us-central1"
  database_version = "POSTGRES_11"
  settings {
    tier = "db-f1-micro"
  }
}
```

Then change to

```tf
resource "google_sql_database_instance" "instance" {
  name             = "some-name"
  region           = "us-central1"
  database_version = "POSTGRES_11"
  settings {
    tier = "db-f1-micro"
    ip_configuration {
      ipv4_enabled    = false
      private_network = var.private_network
      require_ssl     = true
    }
  }
}
```

### Expected Behavior

Since the network type cannot be changed for an existing instance, it should trigger a recreate. 

### Actual Behavior

Instead it tries to edit in place, and this error is returned:
`Error: Error, failed to update instance settings for : googleapi: Error 400: This operation isn"t valid for this instance., invalidOperation`

### Steps to Reproduce

1. `terraform apply`
1. **edit**
1. `terraform apply`

**Comment by venkykuberan** [comment]
`ip_configuration` is not set to ForceNew, thus we are making the API call and fail from there. I think `ForceNew` is required here. @rileykarson  can `ForceNew` & `Computed` go into same attribute ?

**Comment by rileykarson** [comment]
The network can be changed for an existing instance. Running both of those configs in order is actually a success for me. However, once a private network is enabled, it can't be disabled- is that the operation you're trying to perform?

**Comment by carlpett** [comment]
Hi @rileykarson,
Interesting. I'm getting the error when enabling private networking, with the exact steps in the initial report :thinking: 
I'll do a few more tests.

**Comment by carlpett** [comment]
Got it. It happens when the private network I try to use is a shared vpc network. If I use a network in the same project, it works.

**Comment by rileykarson** [comment]
Ah, yep- Cloud SQL lets you _create_ a private cluster in a shared VPC but not upgrade an existing one. [See here for docs](https://cloud.google.com/sql/docs/mysql/private-ip#quick-reference). I think that's a deeper validation than we tend to track in the provider, so I'm going to close this out.
