### ISSUE TITLE
unable to provision google_sql_database_instance when availability_type = "REGIONAL"  is set

### ISSUE THREAD

**Issue by brett-wright** [terraform-providers/terraform-provider-google#6573]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.26

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

resource "google_sql_database_instance" "main" {
  name             = "${var.name}-${local.env}-${random_id.db_name_suffix.hex}"
  database_version = var.db_version
  region           = var.region
  project          = var.project

  settings {
    tier              = local.db_vm_size
    availability_type = "REGIONAL" 

    ip_configuration {
      ipv4_enabled    = false
      private_network = local.network

    }

    backup_configuration {
      enabled = true
    }

  }

}

### Expected Behavior

Created a cloud sql instance that has the availability_type = REGIONAL

### Actual Behavior

I'm unable to create cloud sql instance  that has the availability_type = REGIONAL

### Steps to Reproduce

1. `terraform apply`

google_sql_database_instance.main: Creating...

Error: Error, failed to create instance test-prod-0409198a: googleapi: Error 400: The incoming request contained invalid data., invalidRequest

  on main.tf line 24, in resource "google_sql_database_instance" "main":
  24: resource "google_sql_database_instance" "main" {

### References

* #0000

**Comment by edwardmedia** [comment]
Below command receives same error. After removing `--availability-type`, The error goes away
`gcloud sql instances create regionalinstance1 --availability-type=REGIONAL --database-version=MYSQL_5_7  --cpu=4 --memory=9GiB --region=us-central1
`

**Comment by rileykarson** [comment]
I believe in addition to backups being enabled, binary logging needs to be as well. This flag: https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#binary_log_enabled

Can you see if enabling that works @brett-wright?

Otherwise, something you can try is using the Console to create an instance similar to the one you want, and importing it to Terraform to find the differences between your config and the real one. That often helps find the issue in situations like this.

**Comment by brett-wright** [comment]
@rileykarson I set binary_log_enabled = true and I was able to provision the cloud sql instance

**Comment by rileykarson** [comment]
Cool! I'll update our documentation to reflect the requirement. Weirdly enough, I can't find it anywhere on the cloud.google.com docs, so I filed a bug upstream as well.

**Comment by edwardmedia** [comment]
Thank you @rileykarson I am closing this issue then.
