### ISSUE TITLE
DOCUMENTATION - google_filestore_instance

### ISSUE THREAD

**Issue by goobysnack** [terraform-providers/terraform-provider-google#6587]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
N/A
### Affected Resource(s)
resource "google_filestore_instance"

https://www.terraform.io/docs/providers/google/r/filestore_instance.html

```
The issue is just documentation.  The docs show that the project is declared in the Network block but that isn't the case.  It's declared in the main block.
```

### Terraform Configuration Files

THIS is the correct syntax.
```tf
resource "google_filestore_instance" "instance" {
  project = <project_id>
  name = "instance-name"
  zone = "us-west1-a"
  tier = "STANDARD"

  file_shares {
    capacity_gb = 1024
    name        = "share"
  }

  networks {
    network = "default"
    modes   = ["MODE_IPV4"]
  }
}
```

### Debug Output

When the project is declared in the Network block:

```
Error: Unsupported argument

  on filestore.tf line 13, in resource "google_filestore_instance" "instance":
  13:     project = <project-id>

An argument named "project" is not expected here.
```

### Panic Output

n/a

### Expected Behavior
When it is declared in the main block:

```
Terraform will perform the following actions:

  # google_filestore_instance.instance will be created
  + resource "google_filestore_instance" "instance" {
      + create_time = (known after apply)
      + etag        = (known after apply)
      + id          = (known after apply)
      + name        = "instance-name"
      + project     = "<project-id>"
      + tier        = "STANDARD"
      + zone        = "us-west1-a"

      + file_shares {
          + capacity_gb = 1024
          + name        = "share"
        }

      + networks {
          + ip_addresses      = (known after apply)
          + modes             = [
              + "MODE_IPV4",
            ]
          + network           = "default"
          + reserved_ip_range = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* #0000

**Comment by venkykuberan** [comment]
@goobysnack the doc has a divider between network block  and upper level attributes. Doc is shown as expected hence closing this one

**Comment by goobysnack** [comment]
Okee.
