### ISSUE TITLE
firewall logging controls

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#6596]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/vpc/docs/using-firewall-rules-logging
https://cloud.google.com/compute/docs/reference/rest/beta/firewalls
This should also probably deprecate enable_logging, and be built similarly to the subnet logging config (which sets to enabled if the block is present)

### New or Affected Resource(s)

* google_compute_firewall

### References

* b/148667052

**Comment by zmeggyesi** [comment]
Quite coincidentally, for about eight days now, I've been seeing a related error whenever I try to terraform a firewall configuration.

Consider the following configuration:

```
resource "google_compute_firewall" "https" {
  name           = "permit-https"
  project        = var.project_id
  network        = google_compute_network.services.name
  enable_logging = false

  allow {
    protocol = "tcp"
    ports = [
      "443",
    ]
  }

  priority = 1000

  source_ranges = concat(values(var.permitted_ips),
    list(google_compute_address.gke-swarm-router.address,
      google_compute_address.artifactory-address.address,
      google_compute_address.singularity-address.address,
  data.google_compute_subnetwork.services_us-central1.ip_cidr_range))
}
```
Applying this yields the error `Error updating Firewall "permit-https": googleapi: Error 400: Invalid value for field 'resource.logConfig': '{  "enable": false}'. Logging for this firewall rule must be enabled to toggle logging options., invalid`. Strangely, _removing_ the line `enaable_logging = false` changes nothing, the same error is still thrown.

This means I cannot use Terraform to control my firewall settings.

**Comment by rybus** [comment]
The only workaround I found was to enable manually through the UI for this to work... Not ideal at all unfortunately.

**Comment by zmeggyesi** [comment]
@rybus Well yes, the UI works.

However, we're both using Terraform to avoid having to use the UI. Currently, Terraform is not suitable for controlling the GCP Firewall settings.
