### ISSUE TITLE
Add support for advanced routing rules for External HTTP(s) Load Balancers

### ISSUE THREAD

**Issue by Hmerac** [terraform-providers/terraform-provider-google#6634]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We tried to use header-based routing for one of our External HTTP(s) Load Balancers by `header_matches`, but received `Advanced routing rules are not supported for scheme EXTERNAL, invalid` error.

As Terraform documentation for [compute_url_map](https://www.terraform.io/docs/providers/google/r/compute_url_map.html) states, advanced routing such as header-based routing is not possible for External HTTP(s) Load Balancers. Yet, on GCP documentation, it's possible with gcloud utility but not via Console. You can see it in below documentations:

- https://cloud.google.com/load-balancing/docs/https/setting-up-query-and-header-routing#http-header-based-routing
- https://cloud.google.com/load-balancing/docs/features#routing_and_traffic_management

### New or Affected Resource(s)

* compute_url_map

**Comment by edwardmedia** [comment]
@Hmerac Can you see if below code works for you?
```tf
resource "google_compute_url_map" "urlmap" {
name        = "urlmap"
  description = "header-based routing example"
  default_service = google_compute_backend_service.default.id
  host_rule {
    hosts = ["*"]
    path_matcher = "allpaths"
  }
  path_matcher {
    name = "allpaths"
    default_service = google_compute_backend_service.default.id
    route_rules {
      priority = 1
      service = google_compute_backend_service.service-a.id
      match_rules {
        prefix_match = "/"
        ignore_case = true
        header_matches {
          header_name = "abtest"
          exact_match = "a"
        }
      }
    }
    route_rules {
      priority = 2
      service = google_compute_backend_service.service-b.id
      match_rules {
        ignore_case = true
        prefix_match = "/"
        header_matches {
          header_name = "abtest"
          exact_match = "b"
        }
      }
    }
  }
}
```

**Comment by edwardmedia** [comment]
@Hmerac examples are added https://github.com/terraform-providers/terraform-provider-google/issues/6340

**Comment by Hmerac** [comment]
> @Hmerac Can you see if below code works for you?
> 
> ```terraform
> resource "google_compute_url_map" "urlmap" {
> name        = "urlmap"
>   description = "header-based routing example"
>   default_service = google_compute_backend_service.default.id
>   host_rule {
>     hosts = ["*"]
>     path_matcher = "allpaths"
>   }
>   path_matcher {
>     name = "allpaths"
>     default_service = google_compute_backend_service.default.id
>     route_rules {
>       priority = 1
>       service = google_compute_backend_service.service-a.id
>       match_rules {
>         prefix_match = "/"
>         ignore_case = true
>         header_matches {
>           header_name = "abtest"
>           exact_match = "a"
>         }
>       }
>     }
>     route_rules {
>       priority = 2
>       service = google_compute_backend_service.service-b.id
>       match_rules {
>         ignore_case = true
>         prefix_match = "/"
>         header_matches {
>           header_name = "abtest"
>           exact_match = "b"
>         }
>       }
>     }
>   }
> }
> ```

I actually tried to apply the same logic with GCP provider version of v3.25.0, that's how I got the error. 
I should've pointed that out in the description, sorry.

**Comment by edwardmedia** [comment]
@Hmerac do you want to share your debug log if above code does not work for you?

**Comment by Hmerac** [comment]
@edwardmedia I cannot reproduce the same case now because we've proceeded with Istio to do the header-based routing. But, as far as I remember the only error we received was:

`Advanced routing rules are not supported for scheme EXTERNAL, invalid`

Which I believe is quite understandable, looking at the terraform docs for `google_compute_url_map` for `route_rules`:
https://www.terraform.io/docs/providers/google/r/compute_url_map.html
<img width="818" alt="Screenshot 2020-06-26 at 14 36 53" src="https://user-images.githubusercontent.com/15844674/85857630-83b99880-b7ba-11ea-98a8-634a0c77b4cc.png">

**Comment by edwardmedia** [comment]
@Hmerac routeRules should work for External load balancers now. The doc is out of date, and we are going to update it. I am closing this issue. Please feel free to reopen it if you see the error `Advanced routing rules are not supported for scheme EXTERNAL, invalid` again. Thanks
