### ISSUE TITLE
google_container_registry_image should provide actual image data

### ISSUE THREAD

**Issue by salrashid123** [terraform-providers/terraform-provider-google#6635]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

[google_container_registry_image(https://www.terraform.io/docs/providers/google/d/google_container_registry_image.html) currently is really just a parser/formatter datatype.  It will parse the input values provided and provide formatting for a GCR url and what not.  It does not contact gcr to get live information about the image.

This enhancement request is for this data provider to actually contact gcr and retrieve image information (eg, the `digest`) value of  of an image thats actually in gcr

### New or Affected Resource(s)

`google_container_registry_image`

* google_XXXXX

### Potential Terraform Configuration

```tf
provider "google" { }

data "google_container_registry_image" "tokenserver" {
  name = "tokenserver"
}

output "gcr_location" {
  value = data.google_container_registry_image.tokenserver.digest
}
```
the output would show the actual live digest value for `:latest` (in this example)

### References

in `gcloud` the command to recall is

```
$ gcloud container images describe gcr.io/mineral-minutia-820/tokenserver
image_summary:
  digest: sha256:3d2f33787ad902d8922aef070b1b8f781767209ccffe3ef6c5f043d9d6e4040d
  fully_qualified_digest: gcr.io/mineral-minutia-820/tokenserver@sha256:3d2f33787ad902d8922aef070b1b8f781767209ccffe3ef6c5f043d9d6e4040d
  registry: gcr.io
  repository: mineral-minutia-820/tokenserver
```

* #0000

**Comment by danawillow** [comment]
GCR doesn't have an API for reading image information. Instead, it uses the Docker Registry API (https://cloud.google.com/container-registry/docs/reference/docker-api). I'd recommend, then, using the [Docker provider](https://www.terraform.io/docs/providers/docker/index.html) instead.

**Comment by salrashid123** [comment]
ok,  guess th'll need docker running werever terrform run but for ref

https://roidelapluie.be/blog/2019/04/22/docker-gcp-terraform/

```hcl
data "google_client_config" "default" {}

provider "docker" {
  registry_auth {
    address  = "gcr.io"
    username = "oauth2accesstoken"
    password = data.google_client_config.default.access_token
  }
}

data "google_container_registry_image" "myapp_tagged" {
  name = "tokenserver"
  tag  = "latest"
}

data "docker_registry_image" "myapp" {
  name = "${data.google_container_registry_image.myapp_tagged.image_url}"
}

data "google_container_registry_image" "myapp" {
  name   = "tokenserver"
  digest = "${data.docker_registry_image.myapp.sha256_digest}"
}

output "gcr_image_info" {
  value = data.google_container_registry_image.myapp
}

```
