### ISSUE TITLE
GCP Monitoring Dashboard Creation in Workspace

### ISSUE THREAD

**Issue by singh-ashutosh1** [terraform-providers/terraform-provider-google#6661]
I am planning to create a dashboard in monitoring workspace but not sure to which project i should provide access of Monitoring.editor.

Scenario: 
Resources in project x-y-z
Monitoring Workspace project a-b-c

https://www.terraform.io/docs/providers/google/r/monitoring_dashboard.html

For above module what would be the project id to which we need to provide access?

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by edwardmedia** [comment]
@singh-ashutosh1 I am not sure if I understand what your question. Below is the link to GCP Dashboard. If you want to know what project, you may want review GCP **Resource hierarchy**  to decide. I am closing this issue. Feel free to reopne the issue if you have Terraform Google Provider issues

https://cloud.google.com/monitoring/dashboards
https://cloud.google.com/resource-manager/docs/cloud-platform-resource-hierarchy
