### ISSUE TITLE
Services 'profiler.googleapis.com' and 'eu-automl.googleapis.com' are not supported by VPC-SC perimeter resource

### ISSUE THREAD

**Issue by anubbhavm** [terraform-providers/terraform-provider-google#6665]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.23
provider.google v3.23.0

### Affected Resource(s)
google_access_context_manager_service_perimeter

### Terraform Configuration Files

```tf
module "regular_service_perimeter" {
  source              = "../../modules/vpc_service_controls/modules/regular_service_perimeter"
  policy = "123456"
  perimeter_name      = "regular_perimeter_1"
  description         = "Perimeter shielding projects"
  resources           = ["987543"]
  restricted_services = ["bigquery.googleapis.com", "storage.googleapis.com", "eu-automl.googleapis.com", "profiler.googleapis.com"]
}
```
### Expected Behavior

'profiler.googleapis.com' and 'eu-automl.googleapis.com' would be added to the perimeter as restricted services since they are VPC-SC supported services.

### Actual Behavior

Error: Error creating ServicePerimeter: googleapi: Error 400: Service 'eu-automl.googleapis.com' is not supported by VPC Service Controls. The list of supported services is documented at https://cloud.google.com/vpc-service-controls/docs/supported-products

**Comment by edwardmedia** [comment]
@anubbhavm   can you try **cloudprofiler.googleapis.com**,  and **automl.googleapis.com** instead? **eu-automl.googleapis.com** is listed beta. I can't find it available besides the doc you linked.  This appears beyond the control of `Terraform Provider Google`, I am closing this issue. Please feel free to reopen it if you still have questions
