### ISSUE TITLE
WINDOWS image families do not support metadata concealment

### ISSUE THREAD

**Issue by grzebis1** [terraform-providers/terraform-provider-google#6678]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.21
Google-beta v3.24.0

### Affected Resource(s)

google_container_node_pool

### Terraform Configuration Files

Create a node pool 
```tf
resource "google_container_node_pool" "node_pool" {
  provider = google-beta

  name     = "test"
  cluster  = "gke-test"
  location = "australia-southeast1"
  project  = "test-1234"

  initial_node_count = 1

  autoscaling {
    min_node_count = 1
    max_node_count = 3
  }

  management {
    auto_repair = true
    auto_upgrade = true
  }

  node_config {
    image_type      = "WINDOWS_LTSC"
    machine_type    = "n1-standard-4"
    disk_size_gb    = 100
    local_ssd_count = 0

    service_account = google_service_account.node_pool.email

    metadata = {
      disable-legacy-endpoints = false
    }

    labels = {
      nodepool-name = "test"
    }

    workload_metadata_config {
      node_metadata = "UNSPECIFIED"
    }

    tags = [
      "test-1234-pool",
      "test-1234-node",
    ]

    oauth_scopes = [
      "logging-write",
      "monitoring",
      "storage-ro",
      "cloud-source-repos-ro",
      "cloud-platform",
      "trace-append",
    ]
  }

  upgrade_settings {
    max_surge = 1
    max_unavailable = 0
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Expected Behavior

create the windows node pool
 
### Actual Behavior

errors and the windows node is not created 

```tf
Error: error creating NodePool: googleapi: Error 400: WINDOWS_SAC and WINDOWS_LTSC image families do not support metadata concealment., badRequest

on .terraform/modules/gke_node_pool/gcp/gke-node-pool/main.tf line 6, in resource "google_container_node_pool" "node-pool":
6: resource "google_container_node_pool" "node-pool" {
```
Full debug log 
https://gist.github.com/grzebis1/27f7e3138cdcf353f69286f063715e71

### Steps to Reproduce

ensure that `image_type  = "WINDOWS_LTSC"` and `node_metadata = "UNSPECIFIED"` is set in the node config 

1. `terraform apply`

### Important Factoids

`node_metadata` is a required field

**Comment by edwardmedia** [comment]
@grzebis1 can you share your full debug log?

**Comment by grzebis1** [comment]
> @grzebis1 can you share your full debug log?

https://gist.github.com/grzebis1/27f7e3138cdcf353f69286f063715e71

**Comment by grzebis1** [comment]
@edwardmedia I think the error maybe a red herring, I just worked out that workload identity has been switched on for the cluster which is not supported but Windows Node Pools so this maybe why I'm getting that error.

**Comment by edwardmedia** [comment]
@grzebis1 I am glad you have figured it out. Closing the issue then.
