### ISSUE TITLE
Mark google_secret_manager_secret_version.secret_data field as sensitive

### ISSUE THREAD

**Issue by dpatrick** [terraform-providers/terraform-provider-google#6696]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I want to suggest marking this field as sensitive since it is the contents of a secret. That will provide a (small) layer of protection for the secret data.

### New or Affected Resource(s)

* google_secret_manager_secret_version.secret_data (data resource)

### References

* https://www.terraform.io/docs/extend/best-practices/sensitive-state.html

**Comment by megan07** [comment]
Hi @dpatrick! Sorry for the confusion. It looks like `secret_data` is sensitive on both the [resource](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_secret_manager_secret_version.go#L64) and the [datasource](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/data_source_secret_manager_secret_version.go#L51). It's not called out in the datasource documentation, and I can update that, but I wanted to double-check that you are seeing it function properly.
Thanks!

**Comment by dpatrick** [comment]
@megan07  - Oh! Okay no, I can confirm that this is working as it should. I just realized I was seeing the value from the datasource in the output of another terraform object that references it.  Sorry for the false alarm!
