### ISSUE TITLE
google_binary_authorization_attestor is not accepting EC_SIGN_P256_SHA256 as valid algorithm

### ISSUE THREAD

**Issue by imrannayer** [terraform-providers/terraform-provider-google#6705]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v0.12.21
v0.12.28

### Affected Resource(s)

google_binary_authorization_attestor

### Terraform Configuration Files

```tf
resource "google_kms_key_ring" "keyring" {
  name      = "mybinauth-attestor-kr"
  location  = "global"
  project   = "my-project-id-999999"

  lifecycle {
    prevent_destroy = false
  }
}


# KEYS


resource "google_kms_crypto_key" "crypto_key" {
  name     = "mybinauth-attestor-key"
  key_ring = google_kms_key_ring.keyring.id
  purpose  = "ASYMMETRIC_SIGN"

  version_template {
    algorithm = "EC_SIGN_P256_SHA256"
  }

  lifecycle {
    prevent_destroy = false
  }
}

data "google_kms_crypto_key_version" "version" {
  crypto_key = google_kms_crypto_key.crypto_key.id
}

resource "google_container_analysis_note" "build_note" {
  project   = "my-project-id-999999"
  name    = "mybinauth-attestor-note"
  attestation_authority {
    hint {
      human_readable_name = "mybinauth Attestor"
    }
  }
}

resource "google_binary_authorization_attestor" "attestor" {
  project   = "my-project-id-999999"
  name        = "mybinauth-attestor"
  description = "my bin auth desc"

  attestation_authority_note {
    note_reference = google_container_analysis_note.build_note.name
    public_keys {
      id = data.google_kms_crypto_key_version.version.id
      pkix_public_key {
        public_key_pem      = data.google_kms_crypto_key_version.version.public_key[0].pem
        signature_algorithm = data.google_kms_crypto_key_version.version.public_key[0].algorithm
      }
    }
  }
}


```

### Debug Output
2020/06/26 10:19:07 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error creating Attestor: googleapi: Error 400: Invalid value at 'attestor.user_owned_grafeas_note.public_keys[0].pkix_public_key.signature_algorithm' (TYPE_ENUM), "EC_SIGN_P256_SHA256"
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Invalid value at 'attestor.user_owned_grafeas_note.public_keys[0].pkix_public_key.signature_algorithm' (TYPE_ENUM), \"EC_SIGN_P256_SHA256\"",
        "field": "attestor.user_owned_grafeas_note.public_keys[0].pkix_public_key.signature_algorithm"
      }
    ]
  }
]

Error: Error creating Attestor: googleapi: Error 400: Invalid value at 'attestor.user_owned_grafeas_note.public_keys[0].pkix_public_key.signature_algorithm' (TYPE_ENUM), "EC_SIGN_P256_SHA256"
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Invalid value at 'attestor.user_owned_grafeas_note.public_keys[0].pkix_public_key.signature_algorithm' (TYPE_ENUM), \"EC_SIGN_P256_SHA256\"",
        "field": "attestor.user_owned_grafeas_note.public_keys[0].pkix_public_key.signature_algorithm"
      }
    ]
  }
]

### Expected Behavior
Should create attestor

### Actual Behavior
Error: Error creating Attestor: googleapi: Error 400: Invalid value at 'attestor.user_owned_grafeas_note.public_keys[0].pkix_public_key.signature_algorithm' (TYPE_ENUM), "EC_SIGN_P256_SHA256

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by venkykuberan** [comment]
It looks to me API isn't accepting that format although i see it on their docs https://cloud.google.com/kms/docs/reference/rest/v1/CryptoKeyVersionAlgorithm. Provider don't have any validation for that attribute, it just pass on to API. Also I am able to create the resource with RSA_** format.  Please report the issue against the API.
