### ISSUE TITLE
Error waiting for Setting usage export bucket.: Required 'read' permission for ' gcp-bucket '

### ISSUE THREAD

**Issue by TitanRob16** [terraform-providers/terraform-provider-google#6737]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version 
v0.12.28

### Affected Resource(s)

* google_project_usage_export_bucket

### Terraform Configuration Files

```json
{
  "provider": {
    "google": [
      {
        "credentials": "/service-account.json",
        "project": "deployment-project"
      }
    ]
  },
  "resource": {
    "google_project": {
      "test-software-prd": {
        "name": "test-software-prd",
        "project_id": "test-software-prd",
        "billing_account": "123456-ABCDEF-123456",
        "org_id": "12345678910",
        "auto_create_network": "false"
      }
    },
    "google_project_service": {
      "compute-googleapis-com": {
        "service": "compute.googleapis.com"
      }
    },
    "google_project_usage_export_bucket": {
      "usage_export": {
        "project": "${google_project.test-software-prd.project_id}",
        "bucket_name": "gcp-bucket",
        "prefix": "_usage_"
      }
    }
  }
}
```

### Debug Output
https://gist.github.com/TitanRob16/92d080c3e25fb0c50b417ddaeda42e82

### Expected Behavior

The project should deploy, after which the Compute Engine Usage Export should be enabled, pointing to the 'gcp-bucket' bucket with the report prefix of "_ usage _".

### Actual Behavior

I received the error:
"Error waiting for Setting usage export bucket.: Required 'read' permission for ' gcp-bucket '".

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The service account does have the 'Storage Object Viewer' role on 'gcp-bucket'.
'gcp-bucket' is a storage bucket in another project.
I'm using a .tf.json configuration instead of a simple .tf configuration for use with Python.

### References

* #0000

**Comment by edwardmedia** [comment]
@TitanRob16 can you specify how you verify the `service account` has the `Storage Object Viewer` role on `gcp-backet`?

**Comment by TitanRob16** [comment]
@edwardmedia I'm an organisation admin, so I simply browse to the project hosting the bucket and check the permission via the GUI (Show Info Panel - Permissions - 'Storage Object Viewer' shows the service account has been granted the permission at the bucket level).

**Comment by edwardmedia** [comment]
@TitanRob16 can you share the debug log when you execute above script?

**Comment by TitanRob16** [comment]
@edwardmedia Please see the edited OP: I've included the debug output from my test this morning.

**Comment by edwardmedia** [comment]
@TitanRob16 I am able to create the `google_project_usage_export_bucket` on another project's bucket without issue. Have you already had the bucket `usage-exports-summer-sun` in the place?

**Comment by edwardmedia** [comment]
@TitanRob16 is this still an issue?

**Comment by TitanRob16** [comment]
@edwardmedia Yep, the "usage-exports-summer-sun" bucket is located in another project.
I need the new project to setup the Compute Engine export to this bucket, but every time I do this I run into the 'read' permission error (even though the service account deploying the project and settings via Terraform has the Storage Object Viewer role).

**Comment by TitanRob16** [comment]
@edwardmedia I managed to resolve this by giving the service account the Storage Object Admin role. 
I would have thought the 'Viewer' role would be enough considering it only needs the 'read' permission, but clearly not. 
Thanks for the help :)

**Comment by edwardmedia** [comment]
@TitanRob16 Glad you have resolved this issue. Closing it then. Thanks
