### ISSUE TITLE
Destroy timeout of 4m is too low for google_compute_network

### ISSUE THREAD

**Issue by y0ssar1an** [terraform-providers/terraform-provider-google#675]
### Terraform Version
`v0.10.8`

### Affected Resource(s)
- `google_compute_network`

### Terraform Configuration Files
```hcl
provider "google" {
  credentials = ""
  project     = ""
  region      = "us-west1"
  version     = "~> 1.0"
}

resource "google_compute_network" "network" {
  name          = "my-network"
  project       = "my-project"
}
```

### Debug Output
https://gist.github.com/y0ssar1an/6fcb3a42b268496621ce95248e8d313d

### Expected Behavior
The `destroy` should succeed and return exit code 0.

### Actual Behavior
The deletion of a `google_compute_network` times out after 4m and returns exit code 1. In the Web UI, I can see that it takes about 5m for the destroy to complete.
```
Error waiting for Deleting Network: timeout while waiting for state to become 'DONE' (last state: 'RUNNING', timeout: 4m0s)

It takes a long time for the delete call to propagate around the globe. This timeout should be doubled.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform destroy` with a `google_compute_network` resource.

**Comment by danawillow** [comment]
Fix in https://github.com/terraform-providers/terraform-provider-google/pull/662
