### ISSUE TITLE
Does iam_custom_policy support wildcard?

### ISSUE THREAD

**Issue by hmm2001** [terraform-providers/terraform-provider-google#6762]
Dear Support,

I am trying to create custom iam policy and when I am using wildcard like. 

    permissions = [
        "automl.*",
    ]

It gave me the following error "Error: Error updating the custom project role Role: googleapi: Error 400: Permission automl.* is not valid., badRequest"

I am not sure if the gcp provider support wildcard for permissions or not. Please guide.

Thanks.

Mengmeng

**Comment by hmm2001** [comment]
@megan07  Any update on this?

**Comment by megan07** [comment]
Hi @hmm2001! I just tried it out in the API (outside of Terraform) and it looks like this is a limitation of the Google API, so, no, currently the GCP provider does not support wildcard for permissions. Sorry!
