### ISSUE TITLE
GCS: Broken (ish) URL on error message

### ISSUE THREAD

**Issue by poy** [terraform-providers/terraform-provider-google#6764]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.12.28
+ provider.google v3.29.0
```

### Affected Resource(s)

* google_storage_bucket

### Terraform Configuration Files

```tf
resource "google_storage_bucket" "poy-intro-1" {
  name          = "poy-test-bucket-1"
  bucket_policy_only = true
}

resource "google_storage_default_object_access_control" "poy-intro-policy-rule-1" {
  bucket = google_storage_bucket.poy-intro-1.name
  role   = "READER"
  entity = "allUsers"
}
```

### Debug Output

```
Error: Error creating DefaultObjectAccessControl: googleapi: Error 400: Cannot get legacy ACL for a bucket that has uniform bucket-level access. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access., invalid
```

So note that the URL (https://cloud.google.com/storage/docs/uniform-bucket-level-access.) ends with a period. In iTerm on MacOS, URLs in the terminal are clickable. However, when I clicked this link, it got the period as well. This might be small, however it did throw me for a loop at first.

### Expected Behavior

I can click listed link.

### Actual Behavior

Link included period at end.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by venkykuberan** [comment]
doc link update reqd.

**Comment by danawillow** [comment]
This looks to me like the error message that is coming back from the API. I don't think there's much we can really do about it on our end. May be worth filing a bug against GCS instead.

**Comment by ndmckinley** [comment]
I've updated this error message - the change will roll out according to the normal schedule.  :)
