### ISSUE TITLE
google_billing_budgets does not seem to function properly

### ISSUE THREAD

**Issue by UrsysC** [terraform-providers/terraform-provider-google#6775]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.28
+ provider.google v3.28.0
+ provider.google-beta v3.28.0

### Affected Resource(s)

google_billing_budget

* google_XXXXX

### Terraform Configuration Files

```tf
data "google_billing_account" "account" {
  provider = google-beta
  billing_account = "aaaaaa-bbbbbb-cccccc"
}

resource "google_billing_budget" "budget" {
  provider = google-beta
  billing_account = data.google_billing_account.account.id
  display_name = "Example Billing Budget"
  amount {
    specified_amount {
      currency_code = "USD"
      units = "100000"
    }
  }
  threshold_rules {
      threshold_percent =  0.5
  }
}

```

### Debug Output

https://gist.github.com/UrsysC/a663505a54c73e58f4876e729d700e90

### Expected Behavior

Terraform creates a new billing budget, per: https://www.terraform.io/docs/providers/google/r/billing_budget.html

In fact, the code used in testbudget.tf is literally copied and pasted from the example code in the above link, substituting only billing_account

### Actual Behavior

Terraform returns a 400 bad request error, specifying an invalid argument but not specifying which argument is invalid. 

### Steps to Reproduce

1. Create a GCP project, with our terraform service account user set as a billing account administrator and project owner at the organization level
2. `terraform apply`

### Important Factoids

I am creating my GCP project through terraform using https://github.com/UrsysC/terraform-gcp-createProjects
The context is that I am attempting to set up an automatic billing alert to the project that is being created. The google-beta provider uses an impersonated terraform service account with Project_Owner and Billing Account Administrator permissions. When initially testing, I had attempted to terraform apply with my user account and received as expected a 403 bad permissions error. Once running as the service account, the permissions error went away and I started getting errors regarding the bad POST request.

**Comment by edwardmedia** [comment]
@UrsysC your code seems fine with me. My guess is something wrong with the account you use to run the Terraform. Please review below doc and make sure the account has proper roles assigned. 
https://cloud.google.com/billing/docs/how-to/budgets

**Comment by UrsysC** [comment]
![image](https://user-images.githubusercontent.com/10835481/87163715-cc328500-c295-11ea-82c9-ceeca24d6437.png)
My service account is a billing account administrator. As mentioned, when I ran without that permission

![image](https://user-images.githubusercontent.com/10835481/87164087-50850800-c296-11ea-9319-3d99526f08a3.png)
![image](https://user-images.githubusercontent.com/10835481/87164315-a5288300-c296-11ea-9016-e84aef69ad9d.png)


Confirmed that billing account administrator has:

```
billing.budgets.create to create a new budget.
billing.budgets.get and billing.budgets.list to view all budgets for the Cloud Billing account.
```

I'm not sure what I could possibly be missing here.

**Comment by edwardmedia** [comment]
@UrsysC I have tested your request payload and it works fine. Do you have other resources that are in the same `apply`? Can you share the entire debug log?

**Comment by UrsysC** [comment]
first things first, thank you for taking the time on this! I really appreciate it. 

Here is the first gist

https://gist.github.com/UrsysC/dc36d8540545a0916c2c24320650d425

I noticed the following:

```2020/07/11 13:18:35 [WARN] Provider "registry.terraform.io/-/google-beta" produced an invalid plan for google_billing_budget.budget, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .threshold_rules[0].spend_basis: planned value cty.StringVal("CURRENT_SPEND") does not match config value cty.NullVal(cty.String)
```

I added spend_basis = "FORECASTED_SPEND" which removed this warning but still gave the same error as above.

https://gist.github.com/UrsysC/63be332f475c8b59cd26d097c5e48781

In case you didn't want to trawl through all the TRACE output, here's the same as above but with only DEBUG and higher.

https://gist.github.com/UrsysC/8e107e66272523f4bebd0a502c547b82


For context, the other resources in the same apply are:
an access token for the terraform service account, time limited to 300s (we error well before that)
Other than that, these are the resources in my terraform state:
data.google_billing_account.account
data.google_billing_account.billing_account
data.google_service_account_access_token.create-project-service-user
google_project.created_project

full source code is here: https://github.com/UrsysC/terraform-gcp-createProject

**Comment by danawillow** [comment]
@UrsysC, have you enabled the billing budget API in your project? You can do that in your terraform config with the `google_project_service` resource.

**Comment by UrsysC** [comment]
Thanks for the reply! Unfortunately, I still get the same `Error creating Budget: googleapi: Error 400: Request contains an invalid argument.` even when manually enabling the billing budget API in my created project. Relevant addition to the code (everything else is identical).

`resource "google_project_service" "billing" {
  provider = google
  project = var.project_name
  service = "billingbudgets.googleapis.com"
}`

gist of TRACE output: https://gist.github.com/UrsysC/6ca7b441ef92d452fa860e730138e134

**Comment by edwardmedia** [comment]
@UrsysC from your above trace, I noticed that below call occurred right before the resource is being created which was failed Can you share the rest of config?  
``
POST /v1/projects/ursys-test-project-3/services/billingbudgets.googleapis.com:disable
```

**Comment by UrsysC** [comment]
I added a depends on tag to the budget to depend on enabling the service, to force it to be created after. Gist: https://gist.github.com/SaraMurphyFreshbooks/ba0b033071b4b5b70b5830fb12b2a9ce

The rest of my config is available here: https://github.com/UrsysC/terraform-gcp-createProject

**Comment by danawillow** [comment]
Just to try something else- is the billing budget API enabled on the project that the service account you're running TF as comes from? So in https://github.com/UrsysC/terraform-gcp-createProject/pull/6/files, that would be "terra-276704". If not, can you try enabling it and seeing whether that works?

**Comment by UrsysC** [comment]
It is enabled, and more than that, I can actually see a metric of all my API responses. You can see below that project is receiving my API responses (and returning a 400 error). I actually have a bunch of pretty charts measuring my API response times... all of which are for the 400 error responses. 

![image](https://user-images.githubusercontent.com/10835481/88311763-4e339c80-ccdf-11ea-9c0a-78469e764cc1.png)

![image](https://user-images.githubusercontent.com/10835481/88311520-f85ef480-ccde-11ea-8ac7-e94bdf3bdf28.png)

I'm pretty baffled here honestly. I just have no idea what I could be missing at this point. It's pretty basic code + requirements, all of which we seem to meet.

**Comment by danawillow** [comment]
I forwarded this issue to the billing API folks and they believe the issue is that your billing account is in CAD, but the request sent was for USD. Could you try using `currency_code = "CAD"` and see if that works?

**Comment by UrsysC** [comment]
That did the trick! Which of course would make sense. Thank you very much for your help, and taking the time to walk me through all the troubleshooting. 

Have a great weekend!
