### ISSUE TITLE
TF import GCP backend_service

### ISSUE THREAD

**Issue by robertrockjr** [terraform-providers/terraform-provider-google#6786]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.28
+ provider.google v3.29.0

### Affected Resource(s)

google_compute_backend_service

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
provider "google" {
  credentials = "****"
  project       = "asc-ahnat-rstudio-team-prd"
  region        = "us-central1"
  zone          = "us-central1-a"
  }

terraform {
  backend "gcs" {
    bucket      = "asc-terraform-prod"
    prefix      = "terraform/prod/import_test_ilb"
    credentials = "****"
  }
}

resource "google_compute_backend_service" "default" {
}

# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Debug Output

$ tf import google_compute_backend_service.default 1848053231971369158
google_compute_backend_service.default: Importing from ID "rstudio-connect-tcp-ilb"...
google_compute_backend_service.default: Import prepared!
  Prepared google_compute_backend_service for import
google_compute_backend_service.default: Refreshing state... [id=projects/asc-ahnat-rstudio-team-prd/global/backendServices/rstudio-connect-tcp-ilb]

Error: Cannot import non-existent remote object

While attempting to import an existing object to
google_compute_backend_service.default, the provider detected that no object
exists with the given id. Only pre-existing objects can be imported; check
that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new remote
object for this resource.

### Expected Behavior

I would expect the resource would be imported into the state file.

### Actual Behavior

Error: Cannot import non-existent remote object

While attempting to import an existing object to
google_compute_backend_service.default, the provider detected that no object
exists with the given id. Only pre-existing objects can be imported; check
that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new remote
object for this resource.

### Steps to Reproduce

1. tf import google_compute_backend_service.default 1848053231971369158

### References
$ terraform import google_compute_backend_service.default projects/{{project}}/global/backendServices/{{name}}
$ terraform import google_compute_backend_service.default {{project}}/{{name}}
$ terraform import google_compute_backend_service.default {{name}}

* #0000

**Comment by edwardmedia** [comment]
@robertrockjr can you verify the name of the backend-services? What do you see `gcloud compute backend-services list`?

**Comment by robertrockjr** [comment]
Hey, Edward.

Thanks for the quick response.  Here is the result of gcloud compute
backend-services list
NAME                             BACKENDS
       PROTOCOL
rstudio-connect-tcp-ilb          us-central1-a/instanceGroups/connect-uig
       TCP

Here is the json from the same command:
[
  {
    "backends": [
      {
        "balancingMode": "CONNECTION",
        "description": "",
        "failover": false,
        "group": "
https://www.googleapis.com/compute/v1/projects/asc-ahnat-rstudio-team-prd/zones/us-central1-a/instanceGroups/connect-uig
"
      }
    ],
    "connectionDraining": {
      "drainingTimeoutSec": 300
    },
    "creationTimestamp": "2020-07-09T08:56:25.227-07:00",
    "description": "",
    "fingerprint": "S3OlGfIjYi0=",
    "healthChecks": [
      "
https://www.googleapis.com/compute/v1/projects/asc-ahnat-rstudio-team-prd/global/healthChecks/rstudio-connect-tcp-ilb-hc
"
    ],
    "id": "1848053231971369158",
    "kind": "compute#backendService",
    "loadBalancingScheme": "INTERNAL",
    "name": "rstudio-connect-tcp-ilb",
    "protocol": "TCP",
    "region": "
https://www.googleapis.com/compute/v1/projects/asc-ahnat-rstudio-team-prd/regions/us-central1
",
    "selfLink": "
https://www.googleapis.com/compute/v1/projects/asc-ahnat-rstudio-team-prd/regions/us-central1/backendServices/rstudio-connect-tcp-ilb
",
    "sessionAffinity": "CLIENT_IP_PORT_PROTO",
    "timeoutSec": 30
  }
]

On Mon, Jul 13, 2020 at 4:30 PM Edward Sun <notifications@github.com> wrote:

> @robertrockjr
> <https://clicktime.symantec.com/3G7f6jBJuFQqWpJZLQGSkA37Vc?u=https%3A%2F%2Fgithub.com%2Frobertrockjr>
> can you verify the name of the backend-services? What do you see gcloud
> compute backend-services list?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://clicktime.symantec.com/32j5jA9X3q3FMRR7ye17Qus7Vc?u=https%3A%2F%2Fgithub.com%2Fterraform-providers%2Fterraform-provider-google%2Fissues%2F6786%23issuecomment-657777353>,
> or unsubscribe
> <https://clicktime.symantec.com/32DtqcSA7omRfWXKXctEkKi7Vc?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQIV3EE5SLIP2L76U5DM4FDR3NVGLANCNFSM4OYYT5XQ>
> .
>


-- 
PTO: 7/16 - 7/27

Warm Regards,

Robert (Bob) Rock
Cloud Strategy & Services - Cloud Engineer
Ascension Technologies
(989) 513-0772


CONFIDENTIALITY NOTICE: This email message and any accompanying data or files is confidential and may contain privileged information intended only for the named recipient(s). If you are not the intended recipient(s), you are hereby notified that the dissemination, distribution, and or copying of this message is strictly prohibited. If you receive this message in error, or are not the named recipient(s), please notify the sender at the email address above, delete this email from your computer, and destroy any copies in any form immediately. Receipt by anyone other than the named recipient(s) is not a waiver of any attorney-client, work product, or other applicable privilege.

**Comment by edwardmedia** [comment]
@robertrockjr  Can you run
`$ terraform import google_compute_backend_service.default us-central1-a/instanceGroups/connect-uig`

**Comment by robertrockjr** [comment]
$ terraform import google_compute_backend_service.default
us-central1-a/instanceGroups/connect-uig
google_compute_backend_service.default: Importing from ID
"us-central1-a/instanceGroups/connect-uig"...
google_compute_backend_service.default: Import prepared!
  Prepared google_compute_backend_service for import
google_compute_backend_service.default: Refreshing state...
[id=projects/us-central1-a/global/backendServices/instanceGroups]

Error: Cannot import non-existent remote object

While attempting to import an existing object to
google_compute_backend_service.default, the provider detected that no object
exists with the given id. Only pre-existing objects can be imported; check
that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new
remote
object for this resource.

On Mon, Jul 13, 2020 at 4:40 PM Edward Sun <notifications@github.com> wrote:

> @robertrockjr
> <https://clicktime.symantec.com/35m6d8jajxo9mNjBmLRkpPm7Vc?u=https%3A%2F%2Fgithub.com%2Frobertrockjr>
> Can you run
> $ terraform import google_compute_backend_service.default
> us-central1-a/instanceGroups/connect-uig
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://clicktime.symantec.com/39mccG2ELcFVZzsQv1ysZvJ7Vc?u=https%3A%2F%2Fgithub.com%2Fterraform-providers%2Fterraform-provider-google%2Fissues%2F6786%23issuecomment-657782307>,
> or unsubscribe
> <https://clicktime.symantec.com/3Mw86sYhgnHeDJBFxigY96R7Vc?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQIV3EFAJZRRSS77ZIPAB2LR3NWL7ANCNFSM4OYYT5XQ>
> .
>


-- 
PTO: 7/16 - 7/27

Warm Regards,

Robert (Bob) Rock
Cloud Strategy & Services - Cloud Engineer
Ascension Technologies
(989) 513-0772


CONFIDENTIALITY NOTICE: This email message and any accompanying data or files is confidential and may contain privileged information intended only for the named recipient(s). If you are not the intended recipient(s), you are hereby notified that the dissemination, distribution, and or copying of this message is strictly prohibited. If you receive this message in error, or are not the named recipient(s), please notify the sender at the email address above, delete this email from your computer, and destroy any copies in any form immediately. Receipt by anyone other than the named recipient(s) is not a waiver of any attorney-client, work product, or other applicable privilege.

**Comment by edwardmedia** [comment]
Try this 
'$ terraform import google_compute_backend_service.default projects/asc-ahnat-rstudio-team-prd/regions/us-central1/backendServices/rstudio-connect-tcp-ilb'

**Comment by robertrockjr** [comment]
Same error.

On Mon, Jul 13, 2020 at 6:08 PM Edward Sun <notifications@github.com> wrote:

> Try this
> '$ terraform import google_compute_backend_service.default
> projects/asc-ahnat-rstudio-team-prd/regions/us-central1/backendServices/rstudio-connect-tcp-ilb'
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://clicktime.symantec.com/346gw4mvUZTAYXBY5S4f2bu7Vc?u=https%3A%2F%2Fgithub.com%2Fterraform-providers%2Fterraform-provider-google%2Fissues%2F6786%23issuecomment-657817723>,
> or unsubscribe
> <https://clicktime.symantec.com/3X4Bn8J3q2JFgbAYtRTqXR77Vc?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQIV3EFLIHVDSTTCH74E5ILR3OAVPANCNFSM4OYYT5XQ>
> .
>


-- 
PTO: 7/16 - 7/27

Warm Regards,

Robert (Bob) Rock
Cloud Strategy & Services - Cloud Engineer
Ascension Technologies
(989) 513-0772


CONFIDENTIALITY NOTICE: This email message and any accompanying data or files is confidential and may contain privileged information intended only for the named recipient(s). If you are not the intended recipient(s), you are hereby notified that the dissemination, distribution, and or copying of this message is strictly prohibited. If you receive this message in error, or are not the named recipient(s), please notify the sender at the email address above, delete this email from your computer, and destroy any copies in any form immediately. Receipt by anyone other than the named recipient(s) is not a waiver of any attorney-client, work product, or other applicable privilege.

**Comment by edwardmedia** [comment]
You may use `google_compute_region_backend_service` instead, and then 
`$ terraform import google_compute_region_backend_service.default projects/asc-ahnat-rstudio-team-prd/regions/us-central1/backendServices/rstudio-connect-tcp-ilb`

**Comment by robertrockjr** [comment]
Awesome! Works perfect. Thanks for the assist Ed! :)

On Tue, Jul 14, 2020 at 10:25 AM Edward Sun <notifications@github.com>
wrote:

> You may use google_compute_region_backend_service instead, and then
> $ terraform import google_compute_region_backend_service.default
> projects/asc-ahnat-rstudio-team-prd/regions/us-central1/backendServices/rstudio-connect-tcp-ilb
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://clicktime.symantec.com/a/1/Wb1y9y4SRqyVZo6SuA5WZ3asV8Nu4azUULBeDx3MeF0=?d=X8vwvJQBpSBdT3G-ilY3SvJqGaRpj9vKo0llwRpu4ODsvHIhKkbC5u2ysMwXL9T6XeDIJMVEdzvkBo1DCFswu3T8DPgPKO2Q-8tWMhpxSwELdjMQzlBA4Sygw1zZJGbMd-dKxHjLN7yj_G4U4g7MKe8ZhvGUR9epppoCANXcgtyf56I6bxCflR6HBpJTkwteo-TPVSvMKbT-lbeVaEa-6UKP-JApop50amdMGrVOPmfhMLZJxbsHHLO13ZTqL2xOeuVDzQ69H2YU3hS4J8vRmac7upiny32c-T7FjKzfKSrjm92NbZ35a8yVNlFlZ7DnkPJr7DTMbaJJVtoEbPEnr31gco4ojacVZd4P768b-XwurHEkuf2jQA8oCY158uZmCw4FrHaBfU44TMZ17hd5ARZ6X73VGmz0ZZbq5oRs5ajyr5_5Y6TE8vvlbcVJW10fLnY82bfKMnnuiAs-2BR1OwQSMoxVsZW3Bxp3KCeRFHDeNe-pZsos1_vHZw6MbpfUqX7HbLz0VqfiFNJ9MU1N3MpC1p9IQ7kslqMg0wtwhZZUzj9XQ6NC6b3HnWmSjK9Ud65IKPm5Vim7h7pdzlWuoyWb&u=https%3A%2F%2Fgithub.com%2Fterraform-providers%2Fterraform-provider-google%2Fissues%2F6786%23issuecomment-658211423>,
> or unsubscribe
> <https://clicktime.symantec.com/a/1/5pE0BCQOobH_FAd0brpgbR1VQzz00FDnSN90ju4-Y4I=?d=X8vwvJQBpSBdT3G-ilY3SvJqGaRpj9vKo0llwRpu4ODsvHIhKkbC5u2ysMwXL9T6XeDIJMVEdzvkBo1DCFswu3T8DPgPKO2Q-8tWMhpxSwELdjMQzlBA4Sygw1zZJGbMd-dKxHjLN7yj_G4U4g7MKe8ZhvGUR9epppoCANXcgtyf56I6bxCflR6HBpJTkwteo-TPVSvMKbT-lbeVaEa-6UKP-JApop50amdMGrVOPmfhMLZJxbsHHLO13ZTqL2xOeuVDzQ69H2YU3hS4J8vRmac7upiny32c-T7FjKzfKSrjm92NbZ35a8yVNlFlZ7DnkPJr7DTMbaJJVtoEbPEnr31gco4ojacVZd4P768b-XwurHEkuf2jQA8oCY158uZmCw4FrHaBfU44TMZ17hd5ARZ6X73VGmz0ZZbq5oRs5ajyr5_5Y6TE8vvlbcVJW10fLnY82bfKMnnuiAs-2BR1OwQSMoxVsZW3Bxp3KCeRFHDeNe-pZsos1_vHZw6MbpfUqX7HbLz0VqfiFNJ9MU1N3MpC1p9IQ7kslqMg0wtwhZZUzj9XQ6NC6b3HnWmSjK9Ud65IKPm5Vim7h7pdzlWuoyWb&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQIV3EEJNG4U6J7E3NX7RDTR3RTGHANCNFSM4OYYT5XQ>
> .
>


-- 
PTO: 7/16 - 7/27

Warm Regards,

Robert (Bob) Rock
Cloud Strategy & Services - Cloud Engineer
Ascension Technologies
(989) 513-0772


CONFIDENTIALITY NOTICE: This email message and any accompanying data or files is confidential and may contain privileged information intended only for the named recipient(s). If you are not the intended recipient(s), you are hereby notified that the dissemination, distribution, and or copying of this message is strictly prohibited. If you receive this message in error, or are not the named recipient(s), please notify the sender at the email address above, delete this email from your computer, and destroy any copies in any form immediately. Receipt by anyone other than the named recipient(s) is not a waiver of any attorney-client, work product, or other applicable privilege.

**Comment by edwardmedia** [comment]
Great. I am glad it works for you. Closing the issue then
