### ISSUE TITLE
google_container_cluster import fails with "doesn't support import"

### ISSUE THREAD

**Issue by czka** [terraform-providers/terraform-provider-google#679]
As per https://www.terraform.io/docs/providers/google/r/container_cluster.html#import, TF supports importing google_container_cluster. Terraform 0.10.8 claims the opposite though, and fails as follows:
```
$ terraform --version
Terraform v0.10.8
```
```
$ terraform import google_container_cluster.protect-stage protect-stage
google_container_cluster.protect-stage: Importing from ID "protect-stage"...
Error importing: 1 error(s) occurred:

* google_container_cluster.protect-stage (import id: protect-stage): import google_container_cluster.protect-stage (id: protect-stage): resource google_container_cluster doesn't support import
```
In my 07_clusters.tf I have:
```
resource "google_container_cluster" "protect-stage" {
  zone = "us-central1-f"
}
```
And the cluster is there, alive and kicking, eg:
```
$ gcloud container clusters describe --zone us-central1-f protect-stage | grep -i version:
currentMasterVersion: 1.7.8-gke.0
currentNodeVersion: 1.7.5
initialClusterVersion: 1.7.5
  version: 1.7.5
  version: 1.7.5
```
What gives?

**Comment by danawillow** [comment]
Which version of the google provider are you using? We added import support in 1.0.0.

**Comment by czka** [comment]
```
$ terraform providers
.
└── provider.google 0.1.3
```
Any issues to expect if we upgrade?

**Comment by danawillow** [comment]
That's not a call I can really make for you- check out the [CHANGELOG](https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md), especially the backwards incompatibilities and notes.
