### ISSUE TITLE
google_container_cluster Blocks of type "release_channel" are not expected here.

### ISSUE THREAD

**Issue by PDQDakota** [terraform-providers/terraform-provider-google#6794]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.28
provider.google v3.30.0     
provider.google-beta v3.30.0

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
provider "google-beta" {
  project     = "code-project"
  region      = "us-west3"
}

resource "google_container_cluster" "example" {
  name = "code-cluster"
  location = "us-west3-a"
  release_channel {
    channel = "REGULAR"
  }
}
```

### Debug Output

https://gist.github.com/PDQDakota/8b4567b4c1949a0248304c22443f209b

### Panic Output

No panic

### Expected Behavior

Validation passes.

### Actual Behavior

The release_channel block is marked as unsupported.

### Steps to Reproduce

1. `terraform validate`

### Important Factoids

I believe I am following the documentation correctly. https://www.terraform.io/docs/providers/google/r/container_cluster.html#release_channel

### References

None

**Comment by edwardmedia** [comment]
@PDQDakota How about adding `provider = google-beta` like below?
```tf 
resource "google_container_cluster" "example" {
  provider = google-beta
  name = "ssue6794-code-cluster"
  initial_node_count       = 1
  location = "us-west3-a"
  release_channel {
    channel = "REGULAR"
  }
}
```

**Comment by PDQDakota** [comment]
@edwardmedia That was it, thank you for your help and sorry for the bother!
