### ISSUE TITLE
Passing multiline filter values as strings is not working with escape and heredoc

### ISSUE THREAD

**Issue by crisalid** [terraform-providers/terraform-provider-google#6801]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.28
+ provider.google v3.29.0

### Affected Resource(s)

"google_logging_organization_sink" 

### Terraform Configuration Files

```tf
variable "events" {
  #type = "map"
  default = {
    "Admin permissions" = "(protoPayload.methodName=\"google.admin.AdminService.assignRole\" OR protoPayload.methodName=\"google.admin.AdminService.addPrivilege\")"
  }
}

resource "google_logging_organization_sink" "static_filters" {
  org_id           = var.org_id
  destination      = "pubsub.googleapis.com/projects/${var.project}/topics/${google_pubsub_topic.high_priority_events_topic.name}"
  include_children = true
  for_each = var.high_priority_events
  name   = each.key
  filter = each.value 
}
```

### Debug Output

https://gist.github.com/crisalid/79f766a34ea1f992966b31a18ea9ef2f

### Panic Output

Error: googleapi: Error 400: Resource id contains illegal character, badRequest

  on main.tf line 40, in resource "google_logging_organization_sink" "static_filters":
  40: resource "google_logging_organization_sink" "static_filters" {
### Expected Behavior

escaped double-quote symbols inside filter strings should not produce an error.

### Actual Behavior

the resource did not get created

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I have 20 filters to be created. To make a perfectly readable code it would be best to put those filter values as string variables. However, some of them contain multiple double quote character "

This caused me to try like 4 or 5 different ways to work around this issue, as you know - a double quote is used to describe s single string variable in TF. But when there are several " in a line - TF goes crazy :)
so I tried using \ and \\\ as escape characters
tried heredoc format
tried putting those strings to text files and a function to read from them
none of that worked 
TF argues on illegal characters :)

**Comment by edwardmedia** [comment]
@crisalid your log does not contain the ERROR section. But from your plan, I am able to mimic and create the `sink` with below filter. Do I miss your point? Please provide the filter values that could trigger the error along with your longer debug log. Thanks

`filter           = "(protoPayload.methodName=\"google.admin.AdminService.assignRole\" OR protoPayload.methodName=\"google.admin.AdminService.addPrivilege\")"`

**Comment by crisalid** [comment]
@edwardmedia thanks for your reply!
so the issue does not occur when the filter is assigned in a plain value inside resource, but when I put for_each and assign filter value through variable:

Error: googleapi: Error 400: Resource id contains illegal character, badRequest

  on main.tf line 40, in resource "google_logging_organization_sink" "static_filters":
  40: resource "google_logging_organization_sink" "static_filters" {

it's generated by the code above.

**Comment by edwardmedia** [comment]
@crisalid can you post your code showing how you assign the filter values through variables?

**Comment by crisalid** [comment]
```tf
variable "events" {
  #type = "map"
  default = {
    "Admin permissions" = "(protoPayload.methodName=\"google.admin.AdminService.assignRole\" OR protoPayload.methodName=\"google.admin.AdminService.addPrivilege\")"
  }
}

resource "google_logging_organization_sink" "static_filters" {
  org_id           = var.org_id
  destination      = "pubsub.googleapis.com/projects/${var.project}/topics/${google_pubsub_topic.high_priority_events_topic.name}"
  include_children = true
  for_each = var.high_priority_events
  name   = each.key
  filter = each.value 
}
```

**Comment by edwardmedia** [comment]
@crisalid by using for_each, do you expect you can create multiple sinks? I don't think it supports that

**Comment by crisalid** [comment]
ok, I removed for_each.
I put my filter just like you did.
the plan runs Ok
apply fails due to illegal character, \

**Comment by edwardmedia** [comment]
@crisalid can you post your updated code which yields `illegal character` error?

**Comment by crisalid** [comment]
@edwardmedia I think this might be related to the backslash symbol not being url encoded for being used with google rest api
https://gist.github.com/crisalid/2e761ae1708c920253827f5ad1f51032

**Comment by edwardmedia** [comment]
@crisalid I was using below **filter** in the code and apply was complete successfully. Could you be more specific about the **backslash symbol** which causes problem? Please share your code so I can repro the problem. Thanks
filter = "(protoPayload.methodName=\"google.admin.AdminService.assignRole\" OR protoPayload.methodName=\"google.admin.AdminService.addPrivilege\")"

**Comment by crisalid** [comment]
my fault.
dumb.
spaces in resource name :)
