### ISSUE TITLE
Big Query Table Level Access/Permission Setting on with Terraform?

### ISSUE THREAD

**Issue by hburak** [terraform-providers/terraform-provider-google#6805]
Can we grant table level access on bigquery tables with terraform? It's in beta in GCP at the moment. https://cloud.google.com/bigquery/docs/table-access-controls

**Comment by edwardmedia** [comment]
@hburak Not yet. It is in the backlog. Closing this issue as below is the issue tracking its implementation. 
https://github.com/terraform-providers/terraform-provider-google/issues/6561
