### ISSUE TITLE
Support labels for Bigtable Instance

### ISSUE THREAD

**Issue by caieo** [terraform-providers/terraform-provider-google#6813]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It looks like a newer version of Bigtable Instance supports labels (https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances#Instance), but the Terraform provider does not (https://www.terraform.io/docs/providers/google/r/bigtable_instance.html).

### New or Affected Resource(s)

* google_bigtable_instance

### Potential Terraform Configuration

N/A

### References

* [Bigtable client code that has `labels`](https://github.com/googleapis/google-cloud-go/blob/master/bigtable/admin.go#L733)

**Comment by rileykarson** [comment]
The magic words `fix #6813` in a vendoring change closed this. Sorry for the noise!

**Comment by ryanyuan** [comment]
cool. thank you @rileykarson
