### ISSUE TITLE
Add setting to allow Postgres high availability

### ISSUE THREAD

**Issue by samhamilton** [terraform-providers/terraform-provider-google#682]
Hi,

Google just released Postgres HA support and from my basic testing, it looks like it is not supported. 
https://cloud.google.com/sql/docs/postgres/configure-ha

### Terraform Version
```
$ terraform -v
Terraform v0.10.8
```

### Affected Resource(s)
- google_sql_database_instance

### Terraform Configuration Files
```hcl
resource "google_sql_database_instance" "postgres-01" {
  name    = "postgres-01"
  region  = "us-east1"
  database_version = "POSTGRES_9_6"

  settings {
    tier                = "db-custom-2-4096"
    availability_type   = "REGIONAL"
    disk_type           = "PD_SSD"
    disk_size           = "10"
    disk_autoresize     = true
  }
}
```
### Expected Behavior
Changed the Google settings to update to HA 

### Actual Behavior
`Error: google_sql_database_instance.postgres-01: settings.0: invalid or unknown key: availability_type`

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Nope

### References
None

**Comment by danawillow** [comment]
Fixed in #1001.
