### ISSUE TITLE
google_compute_router_nat.nat_ips changes forever due to API URL prefix

### ISSUE THREAD

**Issue by slimsag** [terraform-providers/terraform-provider-google#6824]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.12.28
+ provider.google v3.29.0
+ provider.google-beta v3.29.0
```

### Affected Resource(s)

* google_compute_router_nat
* google_compute_address

### Terraform Configuration Files

```tf
resource "google_compute_network" "prod" {
  name                    = "prod-network"
  auto_create_subnetworks = "false"
}
resource "google_compute_subnetwork" "prod" {
  name          = "prod-subnetwork"
  ip_cidr_range = "10.2.0.0/16"
  region        = "us-central1"
  network       = google_compute_network.prod.id
}
resource "google_compute_router" "prod" {
  name    = "prod-router"
  region  = "us-central1"
  network = google_compute_network.prod.id
}
resource "google_compute_router_nat" "prod" {
  name                               = "prod-nat"
  router                             = google_compute_router.prod.name
  region                             = "us-central1"
  nat_ip_allocate_option             = "MANUAL_ONLY"
  nat_ips = google_compute_address.prod.*.self_link
  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"
}
resource "google_compute_address" "prod" {
  count  = 1
  name   = "prod-nat-manual-ip-${count.index}"
  address_type = "EXTERNAL"
}
```

### Debug Output

Apologies I will have to follow-up with the debug output w/secrets redacted; it's a bit lengthy

### Panic Output

N/A

### Expected Behavior

Once `terraform apply`d once, no change should be reported on subsequent `terraform apply` invocations.

### Actual Behavior

The following plan gets created each time `terraform apply` is ran:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_compute_router_nat.prod will be updated in-place
2020/07/21 14:26:04 [DEBUG] command: asking for input: "Do you want to perform these actions?"
  ~ resource "google_compute_router_nat" "prod" {
        drain_nat_ips                      = []
        icmp_idle_timeout_sec              = 30
        id                                 = "REDACTED/us-central1/prod-router/prod-nat"
        min_ports_per_vm                   = 0
        name                               = "prod-nat"
        nat_ip_allocate_option             = "MANUAL_ONLY"
      ~ nat_ips                            = [
          - "https://www.googleapis.com/compute/v1/projects/REDACTED/regions/us-central1/addresses/prod-nat-manual-ip-0",
          + "projects/REDACTED/regions/us-central1/addresses/prod-nat-manual-ip-0",
        ]
        project                            = "REDACTED"
        region                             = "us-central1"
        router                             = "prod-router"
        source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"
        tcp_established_idle_timeout_sec   = 1200
        tcp_transitory_idle_timeout_sec    = 30
        udp_idle_timeout_sec               = 30
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

The only change here is the removal of the `https://www.googleapis.com/compute/v1/` prefix. Once applied, it simply goes back into the same state and `terraform apply` reports it wants to make the same change again.

### Steps to Reproduce

1. `terraform apply` once
2. `terraform apply` again and observe the change, accept it.
3. `terraform apply` again and observe the same reported change, accept it.
4. ...it repeats...

### Important Factoids

N/A

### References

N/A

**Comment by edwardmedia** [comment]
@slimsag  I can repro your issue ONLY when I replace your code with below assignment. Using `self_link` is fine. If you see the issue when `self_link` is used, could you share your debug log? 
```
nat_ips = google_compute_address.prod.*.id
```

**Comment by slimsag** [comment]
Thanks for the prompt response @edwardmedia -- you're 100% correct I by mistake was still using `.id` instead of `.self_link` - this is fixed by using `.self_link`

I got this code from this snippet in the docs: https://www.terraform.io/docs/providers/google/r/compute_router_nat.html#example-usage-router-nat-manual-ips

Is it possible to update that so others don't run into this as well?
