### ISSUE TITLE
Unset value for google_project org_id and folder_id

### ISSUE THREAD

**Issue by danisla** [terraform-providers/terraform-provider-google#683]
Specifying an empty string value for org_id or folder_id does not "unset" the argument for the google_project resource.

My scenario is to have a module that parameterizes the creation of a project:

```hcl
resource "google_project" "host" {
  name            = "${var.project_name}"
  org_id          = "${var.org_id}"
  folder_id       = "${var.folder_id}"
  project_id      = "${var.project_id == "" ? random_id.default-project-id.hex : var.project_id}"
  billing_account = "${var.billing_account}"
}
```

In this example I can't provide both `org_id` and `folder_id` even if one is empty `""` without getting this error:

```
Error: module.shared-vpc.google_project.host: "folder_id": conflicts with org_id ("1234567890")

Error: module.shared-vpc.google_project.host: "org_id": conflicts with folder_id ("")
```

If I could pass an empty value for either `org_id` or `folder_id`, that would be fantastic.

**Comment by rosbo** [comment]
This is an issue with terraform itself (not the google plugin).

When checking for violations of ConflictsWith, it only checks if the field is set, it doesn't check whether the value has the zero value. 

The culprit code:
```go
for _, conflicting_key := range schema.ConflictsWith {
	if value, ok := c.Get(conflicting_key); ok {
		return fmt.Errorf("%q: conflicts with %s (%#v)", k, conflicting_key, value)
	}
}
```
https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go?#L1235

ideally, `c.Get(conflicting_key)` would check whether the value is set to the default value the same way it is done in `ResourceData.GetOk`:
https://github.com/hashicorp/terraform/blob/master/helper/schema/resource_data.go#L89

I opened an issue with Terraform Core and cc'ed you, feel free to add more details to it:
https://github.com/hashicorp/terraform/issues/16575
