### ISSUE TITLE
Ability to add "min-instances" field for fully managed cloud run in terraform "google_cloud_run_service" 

### ISSUE THREAD

**Issue by mejuhi** [terraform-providers/terraform-provider-google#6841]
### Description

I have a use case which requires to have min instance of my cloud run to be set as 1 (to avoid the cold start). CICD solution used for creating and updating the resources is in terraform script(main.tf) . We can set min instance  using gcloud command 
 ``` gcloud alpha run deploy --image gcr.io/cloudrun/hello --min-instances=<# of min instances> helloservice ``` 

It would be nice to have  terraform to include a filed in ```google_cloud_run_service``` to set min instance to mimic the functionality achieved using the above command. 

### New or Affected Resource(s)

* google_cloud_run_service

**Comment by c2thorn** [comment]
Hi @mejuhi you should be able to set the min/max instances via the revision template under `metadata` annotations. See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#example-usage---cloud-run-service-sql for an example of setting the max instances.
