### ISSUE TITLE
Resource `google_bigquery_dataset_iam_binding` Documentation Incorrect

### ISSUE THREAD

**Issue by kevinbirch** [terraform-providers/terraform-provider-google#6843]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.12.28
+ provider.google v3.29.0
+ provider.google-beta v3.29.0
+ provider.helm v1.2.3
+ provider.kubernetes v1.11.3
+ provider.local v1.4.0
+ provider.mysql v1.9.0
+ provider.null v2.1.2
+ provider.postgresql v1.7.0
+ provider.random v2.3.0
+ provider.tls v2.1.1

Your version of Terraform is out of date! The latest version is 0.12.29. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* google_bigquery_dataset_iam_binding

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "test" {
  provider = google-beta

  dataset_id = "test"

  location = "US"
}

resource "google_bigquery_dataset_iam_binding" "test" {
  provider = google

  dataset_id = google_bigquery_dataset.test.id
  role       = "roles/bigquery.dataEditor"

  members = [
    "user:alice@example.com",
  ]
}
```

### Debug Output

I am unable to provide debug output as it contains information we cannot share publicly.  The issue should be easily reproducible given the above example resources.

### Expected Behavior

The IAM binding is created.

### Actual Behavior

The BigQuery API returns a 404 when trying to access an incorrectly formatted API endpoint URL.  Dataset ids are in the form `projects/{project}/datasets/{dataset_id}` and the [documentation for this resource](https://www.terraform.io/docs/providers/google/r/bigquery_dataset_iam.html#dataset_id) states that this is the expected format for the field `dataset_id`.  It seems the first step of this resource's behavior is to get information about the dataset to be used in the role binding.  However, when given that form, it constructs this following URL:

    GET /bigquery/v2/projects/my-project/datasets/projects/my-project/datasets/test?alt=json HTTP/1.1

instead of:

    GET /bigquery/v2/projects/my-project/datasets/test?alt=json HTTP/1.1

### Steps to Reproduce

1. `terraform apply`
2. Observe failure
3. Update `dataset_id` field from `google_bigquery_dataset.test.id` to `basename(google_bigquery_dataset.test.id)`
4. `terraform apply`
5. Observe success

**Comment by edwardmedia** [comment]
@kevinbirch I see what you mean. It only accepts `{{dataset}}`.

**Comment by kevinbirch** [comment]
> @kevinbirch I see what you mean. It only accepts `{{dataset}}`.

I see you've opened up a fix for the documentation which is fantastic.  May I also suggest that another output attribute is added to `google_bigquery_dataset` which is just the dataset's name (i.e. `test` in the above example).  Currently only `dataset_id` is available and using the `basename` function feels like a clunky workaround.

**Comment by edwardmedia** [comment]
@kevinbirch  Instead of `basename()`, can you use `dataset_id = google_bigquery_dataset.dataset.dataset_id`?

**Comment by kevinbirch** [comment]
> @kevinbirch Instead of `basename()`, can you use below statement?
> `dataset_id = google_bigquery_dataset.test.dataset_id`

Sure, that's fine.
