### ISSUE TITLE
Add support for redis 5.0 to google_redis_instance

### ISSUE THREAD

**Issue by AlistairB** [terraform-providers/terraform-provider-google#6850]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://www.terraform.io/docs/providers/google/r/redis_instance.html#redis_version supports a maximum version of `REDIS_4_0`. However, version 5.0 is now supported https://cloud.google.com/memorystore/docs/redis/supported-versions#current_versions . According to https://cloud.google.com/memorystore/docs/redis/release-notes it reached GA on June 3rd 2020.

### New or Affected Resource(s)

* google_redis_instance

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_redis_instance" "cache" {
  name           = "tf-test%{random_suffix}"
  tier           = "STANDARD_HA"
  memory_size_gb = 1

  location_id             = "us-central1-a"
  alternative_location_id = "us-central1-f"

  authorized_network = google_compute_network.network.id
  connect_mode       = "PRIVATE_SERVICE_ACCESS"

  redis_version     = "REDIS_5_0"
  display_name      = "Terraform Test Instance"

  depends_on = [ google_service_networking_connection.private_service_connection ]
}

```

**Comment by danawillow** [comment]
Hey @AlistairB, we don't actually do any client-side validation on that field so you should be able to set it to whatever value you want. Updated this issue to mark it as a docs fix only.
