### ISSUE TITLE
Increasing timeout for deleting default network

### ISSUE THREAD

**Issue by bharathkkb** [terraform-providers/terraform-provider-google#6852]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
0.12.29

### Affected Resource(s)

* google_project

### Terraform Configuration Files

```tf
resource "google_project" "my_project" {
  name                = "My Project"
  project_id          = "your-project-id"
  org_id              = "1234567"
  auto_create_network = false
}
```

### Error Output
https://gist.github.com/bharathkkb/535bf78a188407a0f1d9fd9943881c7f

### Expected Behavior

It should have deleted the default network successfully.

### Actual Behavior
It timed out due to delay in API activation.

### Steps to Reproduce
Sporadic and hard to repro. I can give additional logs for example builds if needed.
I believe this is originating from here:
https://github.com/terraform-providers/terraform-provider-google/blob/09bc2e2c9145ec8c07b689a28bfccdc22d49ad6d/google/resource_google_project.go#L176
and a possible workaround would be to bump the timeout (currently 4m).

From the Cloud Logs I see that enablement took a little over 4m
`request received at 14:34:42.913 PDT and enabled at 14:38:55.372 PDT`

1. `terraform apply`

### Important Factoids

Adding org policy for skipping default networks is a workaround.

### References

/cc @morgante @daniel-cit

**Comment by edwardmedia** [comment]
@bharathkkb  yes, please provide `additional logs for example builds`

**Comment by edwardmedia** [comment]
@rileykarson what do you think about this?

**Comment by bharathkkb** [comment]
Logs have been sent privately.

**Comment by rileykarson** [comment]
`google_project` actually implements [Timeouts](https://www.terraform.io/docs/configuration/resources.html#timeouts), although it's missing that fact in the documentation. As a workaround, you can add user-defined timeouts as well. A little less invasive than a new org policy 🙂 

I'll add that documentation, and bump the timeout for actions on project from 4 to 10 minutes. It's a substantial amount of headroom compared to the real time actions take, but projects are a particularly unfortunate resource to get into weird states due to timeouts.

**Comment by bharathkkb** [comment]
Thanks @rileykarson !!!
