### ISSUE TITLE
Update Google Service Account Key - Public Key Type

### ISSUE THREAD

**Issue by onlydole** [terraform-providers/terraform-provider-google#6861]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.29
+ provider.google v3.16.0
+ provider.google-beta v3.29.0

### Affected Resource(s)

* google_service_account_key

### Terraform Configuration Files

```tf
resource "google_service_account_key" "key" {
  service_account_id = google_service_account.integration.name
  key_algorithm      = "KEY_ALG_RSA_2048"
  public_key_type    = "X509_PEM"
  private_key_type   = "TYPE_GOOGLE_CREDENTIALS_FILE"
}
```

### Debug Output

```sh
Error: expected public_key_type to be one of [TYPE_NONE TYPE_X509_PEM_FILE TYPE_RAW_PUBLIC_KEY], got X509_PEM
```

### Expected Behavior

Docs should match what the resource inputs expect.

### Actual Behavior

```sh
Error: expected public_key_type to be one of [TYPE_NONE TYPE_X509_PEM_FILE TYPE_RAW_PUBLIC_KEY], got X509_PEM
```

### Steps to Reproduce

1. `terraform plan`

**Comment by edwardmedia** [comment]
@onlydole saw you have had above PR. You might want to update the file at `Magic Module` instead
https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/website/docs/r/google_service_account_key.html.markdown

**Comment by onlydole** [comment]
@edwardmedia - thank you for the heads up! I have submitted a PR here: https://github.com/GoogleCloudPlatform/magic-modules/pull/3787

**Comment by c2thorn** [comment]
Closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/3787
Thanks for helping us out with this @onlydole !
