### ISSUE TITLE
terraform support of serverless vpc access connector in a shared VPC 

### ISSUE THREAD

**Issue by aacloudlearn** [terraform-providers/terraform-provider-google#6869]
hello

the feature, serverless vpc access in a shared VPC, has been made available a few weeks ago. 
https://cloud.google.com/functions/docs/networking/connecting-vpc#shared-vpc
Is it supported by terraform yet?
For non shared VPC , it is already supported
https://www.terraform.io/docs/providers/google/r/html

thanks and best regards

**Comment by edwardmedia** [comment]
@aacloudlearn  you might want to take a look into the argument, `vpc_connector`, which has same format. 
`projects/HOST_PROJECT_ID/locations/CONNECTOR_REGION/connectors/CONNECTOR_NAME`
Let me know if that works for you.

**Comment by edwardmedia** [comment]
@aacloudlearn is this still an issue with you?

**Comment by cldlrn** [comment]
hello
thanks for your answer.
I did not  test it yet

**Comment by edwardmedia** [comment]
@cldlrn I am closing this issue. Feel free to reopen it if you need to continue the discussion. Thanks
