### ISSUE TITLE
Getting error "Error refreshing state" when using Circle CI with Terraform

### ISSUE THREAD

**Issue by RuchirCR7** [terraform-providers/terraform-provider-google#6879]
Getting the below mentioned error when trying to run Terraform generated code using Circle CI.
Error refreshing state: state snapshot was created by Terraform v0.12.29, which is newer than current v0.12.28; upgrade to Terraform v0.12.29 or greater to work with this state

When using Terraform.io to perform the same operation the error is not encountered in command line. 
It was working previously using the same configuration.

**Comment by rileykarson** [comment]
Hey @RuchirCR7!

This error isn't specific to the Google provider. The [`hashicorp/terraform` repo](https://github.com/hashicorp/terraform) is a more relevant place to file this issue.

Is it possible that the version of Terraform [Core] that you use in CI has regressed, or that someone edited the state file using a local copy of Terraform that's ahead in versions? The solution to this is almost certainly to update the Terraform version you're using in CI or to revert the state file if it's stored in versioned object storage.
