### ISSUE TITLE
Enhancement: Support for Network Intelligence

### ISSUE THREAD

**Issue by dansiviter** [terraform-providers/terraform-provider-google#6891]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

[Network Intelligence](https://console.cloud.google.com/net-intelligence/) is now in Beta, it would be great to add support to Terraform. (in lieu of #4895)

I would like to create Connectivity Tests to be able to monitor the network.

### New or Affected Resource(s)

* google_network_intelligence_connectivity_test

### Potential Terraform Configuration

```tf
resource "google_network_intelligence_connectivity_test" "my_test" {
  project     = "my-project"
  name        = "my-test"
  description = "My Test"
  source {
    ipAddress   = "0.0.0.1"
    port        = 443
    networkType = "GCP_NETWORK"
  }
  destination {
    ipAddress   = "0.0.0.2"
    port        = 443
    networkType = "NON_GCP_NETWORK"
  }
  protocol = "TCP"
}
```

### References

* https://cloud.google.com/network-intelligence-center/docs/connectivity-tests/reference/networkmanagement/rest/v1/projects.locations.global.connectivityTests

**Comment by danawillow** [comment]
I think you're looking for https://www.terraform.io/docs/providers/google/r/network_management_connectivity_test_resource.html. Closing since I think this is already done, but feel free to reopen if I'm wrong.

**Comment by dansiviter** [comment]
@danawillow Yea, that looks the one. Thanks

Bit strange that it doesn't mention 'network intelligence'.
