### ISSUE TITLE
Error: creating folder when creating project in a specified folder

### ISSUE THREAD

**Issue by Arconapalus** [terraform-providers/terraform-provider-google#6895]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.28
+ provider.google v3.30.0
+ provider.random v2.3.0

### Affected Resource(s)

google_project
google_folder

### Terraform Configuration Files

```tf


# # ------------------------------------------------------------------------------
# #  Configure GCP Projects
# # ------------------------------------------------------------------------------

resource "random_id" "id" {
  byte_length = 4
  prefix      = var.project_name
}

resource "google_project" "my_project-in-a-folder" {
  name       = var.project_name
  project_id =  random_id.id.hex
  folder_id  = google_folder.folder_name.name
}

resource "google_folder" "folder_name" {
  display_name = "folder_name"
  parent       = "folder_id"
}
```

### Debug Output

no output

### Panic Output

no output

### Expected Behavior

Creating a GCP project in a specified folder

### Actual Behavior

Error: Error creating folder 'folder name' in 'folder id': googleapi: Error 400: Request contains an invalid argument., badRequest

  on modules/services/GCProject/createproject.tf line 20, in resource "google_folder" "folder name":
  20: resource "google_folder" "folder name" {

### Steps to Reproduce

1. `terraform apply` from terraform cli 
input var.credentials_file
creds.json

### Important Factoids

I have the creds.json with least privilege however, this can be obtain to have owner role  
I also added the folder name and folder id to parent of resource "google_folder" "folder_name"
Folder name is a folder already created through the GCP console, I'm looking to add a project to the folder. 
### References

* [Terraform GCP project](https://www.terraform.io/docs/providers/google/r/google_project.html)

**Comment by edwardmedia** [comment]
@Arconapalus what roles does this account (var.credentails_file) have? Please note `folder` is above projects and creating a folder requires folder level permissions.

**Comment by Arconapalus** [comment]
@edwardmedia Ok so this resource is creating a new folder? Which is not what I want to do then, I'll have to use the data source right? If so, then this is where I was confused.

**Comment by edwardmedia** [comment]
@Arconapalus yes. Below is the link to its data source. I am closing this issue then. Feel free to reopen it if you need to continue the discussion. Thanks
https://www.terraform.io/docs/providers/google/d/folder.html
