### ISSUE TITLE
Cloud Spanner resources could document the lifecycle argument

### ISSUE THREAD

**Issue by rakyll** [terraform-providers/terraform-provider-google#6898]
Similar to https://www.terraform.io/docs/providers/google/r/bigtable_table.html, google_spanner_instance and google_spanner_database could document the availability of the lifecycle argument to prevent accidental destructions.

**Comment by edwardmedia** [comment]
@rakyll below is the API that is behind the resource. Which attribute do you refer to? 
https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances.databases

**Comment by rakyll** [comment]
@edwardmedia, sorry that I was not specific enough.

I was wondering if we can  suggest the following Terraform's [prevent_destroy](https://www.terraform.io/docs/configuration/resources.html#prevent_destroy) for Cloud Spanner resources as well?

```
lifecycle {
    prevent_destroy = true
}
```


An example from BigTable:

```
resource "google_bigtable_instance" "instance" {
  name = "tf-instance"

  cluster {
    cluster_id   = "tf-instance-cluster"
    zone         = "us-central1-b"
    num_nodes    = 3
    storage_type = "HDD"
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

**Comment by edwardmedia** [comment]
@rakyll `lifecycle` block is a Terraform feature. It should be available for all resources. Can you try it in Spanner to see if that works?

https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations

**Comment by rakyll** [comment]
It works as expected, we should document it as a good practice the way BigTable does.
