### ISSUE TITLE
OS Config - patch deployment for Windows only supports one classification

### ISSUE THREAD

**Issue by rjerrems** [terraform-providers/terraform-provider-google#6909]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.24
+ provider.google v3.32.0

### Affected Resource(s)

* google_os_config_patch_deployment

### Terraform Configuration Files

```tf
resource "google_os_config_patch_deployment" "patch_deployer" {
  patch_deployment_id = "patch-deployer"
  instance_filter {
    group_labels {
      labels = {
        env = "dev",
        app = "web"
      }
    }
  }
  patch_config {
    windows_update {
      classifications = ["CRITICAL", "SECURITY"]
    }
    reboot_config = "ALWAYS"
  }
  recurring_schedule {
    time_zone {
      id = "Pacific/Auckland"
    }

    time_of_day {
      hours   = 0
      minutes = 30
      seconds = 30
      nanos   = 20
    }

    monthly {
      week_day_of_month {
        week_ordinal = -1
        day_of_week  = "TUESDAY"
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/rjerrems/7d7c6bcfa4f0b8f2a047d453c11b07cf

### Expected Behavior

Multiple classifications should be supported as per the API:
https://cloud.google.com/compute/docs/osconfig/rest/v1/PatchConfig#WindowsUpdateSettings

### Actual Behavior

Only one classification is supported as a string.

### Steps to Reproduce

1. Copy sample block of code
1. `terraform init`
1. `terraform plan`

**Comment by morevillo** [comment]
When running an apply with only one classification (eg: SECURITY), getting the following error
`Error: Error reading PatchDeployment: patch_config.0.windows_update.0.classifications: '' expected type 'string', got unconvertible type '[]interface {}'
  on deployer_compute.tf line 44, in resource "google_os_config_patch_deployment" "patch_deployer":
  44: resource "google_os_config_patch_deployment" "patch_deployer" {`
