### ISSUE TITLE
How to find Google Container Cluster Backend Service Link

### ISSUE THREAD

**Issue by arekkas** [terraform-providers/terraform-provider-google#705]
I am looking for a way to find the backend created by a Google Container Cluster resource.

**Comment by danawillow** [comment]
Hey @arekkas, what's your use case for finding the URLs?

The API exposes instance group URLs, which hypothetically you could compare to each backend service to figure out which one is for that cluster, but that's all we can do right now.

**Comment by arekkas** [comment]
The idea was to have SSL termination using the Google SSL Proxy with a global ip address + global forwarding rule which ends up at a kubernetes created load balancer. I saw that that could be (partially) done using k8s ingress which is still beta though (and has been that way for some time now) and thus not supported by the k8s provider. For now, I just added SSL capabilities to my proxy to handle this, but it would be nice to have a native way of dealing with SSL termination and GKE.

**Comment by danisla** [comment]
@arekkas, you might find this tutorial helpful. It shows how to use a Terraform module to create an https load balancer to an existing GKE cluster. SSL is terminated at the forwarding rule. The tutorial shows how to extract the instance group URI and pass that to Terraform. 

https://github.com/GoogleCloudPlatform/terraform-google-examples/blob/master/example-lb-https-gke/README.md

**Comment by arekkas** [comment]
Nice, thank you! There's actually exactly the issue I was having with getting this to work using just terraform - the backend is fetched using the gcloud command and some grep magic :) I think the most native way is for the Kubernetes provider to support Ingress.

**Comment by danawillow** [comment]
Closing this since it appears to be working from the last comment, feel free to comment again to open it up if I'm misunderstanding.
