### ISSUE TITLE
Removing Google Container Cluster does not remove Google Backend Service

### ISSUE THREAD

**Issue by arekkas** [terraform-providers/terraform-provider-google#706]
While investigating #705 I recreated a GKE cluster. After some poking around, I found a stale backend service for the previously destroyed GKE cluster which linked to the (no longer existing) compute instances.

### Terraform Version
0.10.8

### Affected Resource(s)
- google_container_cluster

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
resource "google_container_cluster" "master" {
  project = "${google_project.project.project_id}"

  name = "master"

  zone = "${data.google_compute_zones.available.names[0]}"
  initial_node_count = 2

  master_auth {
    username = "${var.gke_master_username}"
    password = "${var.gke_master_password}"
  }

  node_config {
    disk_size_gb = "10"
    machine_type = "n1-standard-1"

    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring"
    ]

    service_account = "${google_service_account.gke_platform.email}"
  }
}
```

### Expected Behavior

All resources, including the backend service, should be removed when the cluster is deleted or recreated.

### Actual Behavior

The backend service was not removed.

**Comment by sl1pm4t** [comment]
@arekkas was the backend service created by Kubernetes when you add a service resource to the cluster? 
In which case Terraform has no knowledge of the backend service to be able to remove them.

To resolve this, on delete of a cluster Terraform would have to scan the cluster resources to find and delete all services / ingresses from Kubernetes and give time for the cloud controller to cleanup the GCP / AWS resources. But that sounds a bit messy to me.

**Comment by arekkas** [comment]
> @arekkas was the backend service created by Kubernetes when you add a service resource to the cluster?
In which case Terraform has no knowledge of the backend service to be able to remove them.

Yes I believe so. I'm still figuring out things with K8S/GKE and terraform automation so I was maybe doing some sketchy stuff, but I think that what you describe fits quite well. If I encounter it again, I'll try to create a repro case.

**Comment by danawillow** [comment]
My opinion is that this is something that should be fixed by GKE/K8s. https://github.com/kubernetes/kubernetes/issues/4630 is an issue you might be interested in following.

@sl1pm4t is right- hypothetically we could list all backend services, compare the instance group URLs to see if they match that of the cluster and if so delete it, but that's messy and error-prone.

I'm going to go ahead and close this issue since I don't think it's something we should be hacking around in Terraform, but if you disagree (or can think of a clean way to fix it) let me know and I'll reopen :)
