### ISSUE TITLE
Timeout when creating subnetworks

### ISSUE THREAD

**Issue by eilgin** [terraform-providers/terraform-provider-google#718]
### Terraform Version
```
terraform -v
Terraform v0.10.8
```

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_subnetwork

### Terraform Configuration Files
```hcl
resource "google_compute_subnetwork" "default_europe_west" {
  count   = 3
  name    = "${var.name}-subnet-${count.index + 1}"
  project = "${google_project.default.id}"

  ip_cidr_range = "10.132.${count.index + 1}.0/16"

  network                  = "${google_compute_network.default.self_link}"
  region                   = "europe-west${count.index + 1}"
  private_ip_google_access = true

  lifecycle {
    create_before_destroy = true
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
```
module.foo.module.project.google_compute_subnetwork.default_europe_west[0]: Creation complete after XXs (ID: foo)
```

### Actual Behavior
The subnetworks takes too much time to spawn and it reaches the timeout limit (i guess it's **4 minutes**):
```
* module.foo.module.project.google_compute_subnetwork.default_europe_west[0]: 1 error(s) occurred:

* google_compute_subnetwork.default_europe_west.0: Error waiting for Creating Subnetwork: timeout while waiting for state to become 'DONE' (last state: 'RUNNING', timeout: 4m0s)
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -out=tfplan`
1. `terraform apply tfplan`

**Comment by rosbo** [comment]
@eilgin Were you planning on working on this? If not, I am happy to take it.

**Comment by johnraz** [comment]
@rosbo @eilgin may I ask what the state of this is? Is someone working on this yet?

I'm not used to Go but if you think it's easy enough and maybe can provide me with some guidance on where to look at this I would gladly submit a PR because this is annoying me like crazy 😄

**Comment by eilgin** [comment]
@johnraz i'll let @rosbo take this since he said that he'd gladly take it 😄

**Comment by johnraz** [comment]
And I would love to start contributing too, just FTR ;-)

**Comment by rosbo** [comment]
Hi Jonathan,

I am glad you want to start contributing to this project :)

The best way to solve this issue is to add configurable timeout support for the `google_compute_subnetwork` resource. I implemented something similar for the `google_compute_instance`. You can look at that PR #856 for inspiration (in fact, it should be pretty similar).

Let me know if you need any help. 

Thank you

**Comment by johnraz** [comment]
@rosbo awesome, thanks for the warm welcome.

I'll try to do this in the best way possible and will submit a PR as soon as I get it done.

Cheers.

**Comment by johnraz** [comment]
@rosbo @eilgin ☝️ there is the PR 🎉
