### ISSUE TITLE
Maintenance windows with 1 digit hour start_time trigger google_container_cluster recreation because of formatting issue

### ISSUE THREAD

**Issue by pdecat** [terraform-providers/terraform-provider-google#719]
On a GKE cluster for which I manually set up a maintenance window with a starting time at 6h00 before it was available on the google terraform provider, `terraform plan` wants to recreate the cluster because of a formatting issue.

The command that was used to set up the maintenance:

```
# gcloud container clusters update mycluster --zone europe-west1-b --maintenance-window=6:00
```

### Terraform Version

Terraform v0.10.8
google provider v1.2.0

### Affected Resource(s)

- google_container_cluster

### Terraform Configuration Files

```hcl
//GKE cluster
resource "google_container_cluster" "gke_cluster1" {
  name               = "${var.general["project"]}-${var.general["region"]}-cluster1"
  zone               = "${var.general["region"]}-${var.gke["main_zone"]}"
  initial_node_count = "${var.gke["initial_node_count"]}"
  network            = "${var.infra["net0_name"]}"
  subnetwork         = "${var.infra["subnet1_name"]}"

  master_auth {
    username = "${var.gke["username"]}"
    password = "${var.gke["password"]}"
  }

  node_config {
    machine_type = "${var.gke["machine_type"]}"

    oauth_scopes = "${var.gke_oauth_scopes}"
  }

  maintenance_policy {
    daily_maintenance_window {
      start_time = "6:00"
    }
  }
}
```

### Output

```
      maintenance_policy.#:                                       "1" => "1"                 
      maintenance_policy.0.daily_maintenance_window.#:            "1" => "1"                                                                                                              
      maintenance_policy.0.daily_maintenance_window.0.duration:   "PT4H0M0S" => <computed>                                                                                                
      maintenance_policy.0.daily_maintenance_window.0.start_time: "6:00" => "06:00" (forces new resource)                                                                                 
```

### Expected Behavior

Plan should be empty

### Actual Behavior

Plan announces the destruction/recreation of the GKE cluster.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Trying to pass `6:00` instead of `06:00` is rejected by the google terraform provider:

```
# terraform plan                                                                                                    

Error: module.transport.google_container_cluster.gke_cluster1: "maintenance_policy.0.daily_maintenance_window.0.start_time" ("6:00") must be in the format HH:mm (RFC3399)
```

### References

- Support for this was recently added in #670

**Comment by pdecat** [comment]
# Workaround

Update the cluster specifying the start time with the RFC3399 format:

```
# gcloud container clusters update mycluster --zone europe-west1-b --maintenance-window=06:00
```

**Comment by pdecat** [comment]
Also, the documentation states:

> Note: Times are in UTC format.

cf. https://cloud.google.com/container-engine/docs/maintenance-window

**Comment by pdecat** [comment]
Perhaps removing the `ForcesNew` would be enough as this can be updated.

**Comment by michaelbannister** [comment]
Hi, sorry about this!
I found the reference to RFC3399 on the Go API: https://github.com/google/google-api-go-client/blob/9d4ba4bd1e8a1c936516ad27bcffb6b0adcec128/container/v1/container-gen.go#L785

Just to clarify, as I'm still getting my head around how terraform works: where is the single-digit hour coming from? is it in the response from the Google API? (i.e. does the Google resource preserve the format you originally provided?)

I'm also puzzled that you say it's updatable but I don't see it in the ClusterUpdate struct so how would we implement a clean update to this through terraform?
https://github.com/google/google-api-go-client/blob/9d4ba4bd1e8a1c936516ad27bcffb6b0adcec128/container/v1/container-gen.go#L617

**Comment by pdecat** [comment]
Hi @michaelbannister, don't feel sorry, the missing documentation on that part does not help. Thanks for your work here!

Yep, the single-digit hour was coming from the Google API as the gcloud CLI allows to pass such values and the API accepts them.

Also, there is a workaround by fixing the value with gcloud.

Not sure how gcloud implements the update...

**Comment by michaelbannister** [comment]
Ah - there is a separate API method container.projects.zones.clusters.setMaintenancePolicy, so we could make this safe to update through Terraform. I'm out today but will take a look at this tomorrow.

BTW, I'm only seeing the --maintenance-window option on `gcloud beta`, but it's useful to know it's there, lots of other useful options too!

**Comment by pdecat** [comment]
Hmm, it is indeed missing in the gcloud stable help but available through completion and operational:

```
# gcloud --version
Google Cloud SDK 179.0.0
alpha 2017.11.06
beta 2017.11.06
bq 2.0.27
core 2017.11.06
gsutil 4.28
# gcloud container clusters update --help | grep maintenance-window
# gcloud beta container clusters update --help | grep maintenance-window
          | --maintenance-window=MAINTENANCE_WINDOW
       --maintenance-window=MAINTENANCE_WINDOW
                  --maintenance-window=12:43
          use '--maintenance-window=None'
# gcloud container clusters update --ma<TAB><TAB>
--maintenance-window=          --master-authorized-networks=  --max-nodes=                   
```
