### ISSUE TITLE
Timeout when enabling the compute API

### ISSUE THREAD

**Issue by eilgin** [terraform-providers/terraform-provider-google#722]
### Terraform Version
```
terraform -v
Terraform v0.10.8
```

### Affected Resource(s)
Please list the resources as a list, for example:
- google_project_service

### Terraform Configuration Files
```hcl
resource "google_project_service" "compute" {
  project = "${google_project.default.id}"
  service = "compute.googleapis.com"
}
```

### Expected Behavior
```
google_project_service.services: Creation complete after XXs (ID: foo)
```

### Actual Behavior
Activating the "compute" API is sometimes taking a lot of time (more than the max allowed time which seems to be 1 minute):
```
* google_project_service.services: Error enabling service: Error enabling service "compute.googleapis.com" for project "XXX": timeout while waiting for state to become 'success' (timeout: 1m0s)
```

We should allow this resource to set the [`timeout` parameter](https://www.terraform.io/docs/configuration/resources.html#timeouts)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -out=tfplan`
1. `terraform apply tfplan`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- [GH-718](https://github.com/terraform-providers/terraform-provider-google/issues/718)

**Comment by rosbo** [comment]
A good example is #717

**Comment by arekkas** [comment]
I can confirm that this is happening regularly now.
