### ISSUE TITLE
Non-destructive update for machine-type change in google_compute_instance

### ISSUE THREAD

**Issue by gionn** [terraform-providers/terraform-provider-google#728]
Hi, it would be great if changing the machine-type will trigger a workflow where the instance is stopped, resized and started instead of recreating the VM.

This behaviour is what GCP do via console when a resize is requested.

**Comment by rosbo** [comment]
One idea to handle this:

We could add an extra boolean field called something like `allow_stopping_for_update`. Defaults would be `false`. If the `machine_type` field is updated, the instance is running and `allow_stopping_for_update` is false, it would fail with an error message saying that `allow_stopping_for_update` should be enabled or something like that.

There is other properties I believe that we can update only if the instance is stopped. We could support update in the same fashion.

**Comment by gionn** [comment]
@danawillow you are right and I lied, I've applied a resource resize tip on the console instead (via the yellow lightbulb that appear saying that you can save money changing machine-type), I supposed the standard resize behaviour was the same.

@rosbo it would be great.

FYI, manual resize didn't break anything in terraform, since at the next state refresh it will find the updated machine-types, so as workaround is fine.

**Comment by isabellf** [comment]
Does that duplicate https://github.com/terraform-providers/terraform-provider-google/issues/380 ?

**Comment by paddycarver** [comment]
I think we could take a similar approach to https://github.com/hashicorp/terraform/pull/11998 to make this work.

**Comment by ubschmidt2** [comment]
The same applies to changes to the assigned service account and the API scopes (e.g. https://github.com/terraform-providers/terraform-provider-google/blob/2a6974451838133bd89ac8e40d09285f91d6da61/google/resource_compute_instance.go#L483).

**Comment by ubschmidt2** [comment]
@danawillow
