### ISSUE TITLE
Regression/Bug in 1.2.0 - Sub DNS Delegation broken with NS Changes

### ISSUE THREAD

**Issue by Russell-IO** [terraform-providers/terraform-provider-google#729]
With Google Provider 1.2.0 I'm unable to create a dns delegation between two zones, details are in the hcl code below, N.B. I've changed the domain names from my code, but have validated that the issue still exists

### Terraform Version
Terraform v0.10.8
Google Cloud Provider 1.2.0 (N.b. issue doesn't exist in 1.1.1)

### Affected Resource(s)
- google_dns_record_set

### Terraform Configuration Files
```hcl
// Configure the Google Cloud provider
provider "google" {
  //version     = "~> 1.1.1"
  version = "1.2.0"
  region      = "europe-west2"
}

// Create Root zone
resource "google_dns_managed_zone" "gcp-root" {
  dns_name    = "gcp.domain.test."
  name        = "gcp-root"
}

// Create dev root zone
resource "google_dns_managed_zone" "gcp-dev" {
  dns_name    = "dev.gcp.domain.test."
  name        = "gcp-dev"
}

// Delegate dev root zone to dev nameservers
resource "google_dns_record_set" "gcp-dev-ns" {
  managed_zone  = "${google_dns_managed_zone.gcp-root.name}"
  name          = "dev.${google_dns_managed_zone.gcp-root.dns_name}"
  rrdatas       = [
    "${google_dns_managed_zone.gcp-dev.name_servers.0}",
    "${google_dns_managed_zone.gcp-dev.name_servers.1}",
    "${google_dns_managed_zone.gcp-dev.name_servers.2}",
    "${google_dns_managed_zone.gcp-dev.name_servers.3}"
  ]
  ttl           = 86400
  type          = "NS"
}
```

### Debug Output
https://gist.github.com/Russell-IO/86ccbeb5188d0eb3cf203117286031be

### Expected Behavior
Terraform should create the NS records on the named record without trying to delete the root records

### Actual Behavior
Terraform tries to delete the root nameservers and create the nonroot nameservers in the same call and google fails the api call

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### Important Factoids
I'm using different providers (i.e. google.infra & google.dev) - but the same issues occurs without them present, so I'm assuming... that this isn't related to the provider aliasing at all and an issue with the terraform provider google

### Related Information
https://github.com/terraform-providers/terraform-provider-google/pull/359
https://github.com/terraform-providers/terraform-provider-google/blob/4a342ca8eec32039ad2003d92bc3802834ac910d/google/resource_dns_record_set.go#L80-L105

This code, only checks if the NS is the record type, it doesn't validate that NAME is the apex, which is what is causing this defect
@paddycarver

**Comment by Russell-IO** [comment]
Hi @danawillow @paddycarver any update on this ?

**Comment by sqerison** [comment]
+1

**Comment by Rocklviv** [comment]
+1

**Comment by james-s-nduka** [comment]
+1

**Comment by fernandohonig** [comment]
+1

**Comment by mikrob** [comment]
+1
