### ISSUE TITLE
google_compute_instance_group: EOF panic on wrong `name`

### ISSUE THREAD

**Issue by Dominik-K** [terraform-providers/terraform-provider-google#731]
### Terraform Version
* Terraform v0.10.8
* Google provider v1.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance_group

### Terraform Configuration Files
```hcl
provider "google" {
  region = "europe-west1"
  project = "${var.gcloud_project}"
}

resource "google_container_cluster" "tf-test" {
  name = "load-test"
  zone = "europe-west1-c"
}

data "google_compute_instance_group" "tf-test" {
  name = "${google_container_cluster.tf-test.node_pool}"
  zone = ""
}
```

### Panic Output
https://gist.github.com/Dominik-K/20968a595340a7eac778b3dbabccbb0b

### Expected Behavior
Should output line `Error: 'name' in data.google_compute_instance_group.tf-test must be 'string' ...` 

### Actual Behavior
Panic output (see above). The bug is inside the `google_compute_instance_group`'s name. Changing it to a string, e.g. the correct setting `${google_container_cluster.tf-test.node_pool.0.name}`, solved it.

### Steps to Reproduce
1. Create the Cluster
2. Then add the data-source `google_compute_instance_group` with the wrong config.

### References
Maybe:
- https://github.com/terraform-providers/terraform-provider-google/issues/608

**Comment by rileykarson** [comment]
This looks like an issue with Terraform Core, and not like something we can solve in the provider; regardless, there have been a lot of changes since this was filed both in the provider and in Terraform itself. If you're experiencing this, please feel free to file a new issue!
