### ISSUE TITLE
GKE cluster data source

### ISSUE THREAD

**Issue by colin92** [terraform-providers/terraform-provider-google#732]
### Feature Description
It would be great to have a data source that can output the auth information for a GKE cluster so that it could be plugged into the Kubernetes provider.

This can currently be achieved with the external provider calling the gcloud sdk to retrieve the auth information, but it would be nice to cut out the extra setup steps.

**Comment by sl1pm4t** [comment]
I'm working on this datasource an will submit a PR soon.
