### ISSUE TITLE
Cannot mix node pools within google_container_cluster with seperate google_container_node_pool resources

### ISSUE THREAD

**Issue by drzero42** [terraform-providers/terraform-provider-google#751]
After submitting #742 I discovered that the new `node_pool` sub for `google_container_cluster` resources cannot be used with `google_container_node_pool`. If I have one or more node pools defined within a `google_container_cluster` and I add a `google_container_node_pool`, it will create everything correctly, but running terraform again after this will result in the node_pool attribute not having the correct amount and thus the cluster getting recreated.

I realize that the official line probably is that you should not use both, but instead just give `google_container_cluster` a node_config to let it create the default-pool and then add one or more `google_container_node_pool`s or instead define all node pools within `google_container_cluster`. However, I can only enable autoscaling on a node pool if I specify it. The current `google_container_cluster` resource does not allow setting autoscaling for the default-pool unless I define default-pool within the `node_pool` sub.

My use case for this is that I want to create a module which can be used for all of my kubernetes clusters, where some of them need an extra node pool of highmem machines, and some don't. I do this by having the module accept a create_highmem_np var that can be either true or false and use that for the `count` attribute of a `google_container_node_pool` resource. I don't see a way to do the same with the `node_pool` sub in `google_container_cluster`. I want all node pools to have autoscaling enabled, so that requires me to specify the default-pool, rather than let `google_container_cluster` auto create it. This leads to the resources fighting.

**Comment by danawillow** [comment]
Hmm, this is a tricky issue. What if you had two potential clusters defined in your module- one with the smaller number of node pools and the other with the larger, and you put something like:
```
resource "google_container_cluster" "highmem" {
  count = "${var.create_highmem_np ? 1 : 0}"

  [other attributes]
}
```
and then for the other one you just reversed the 0 and 1 in the ternary? Would that work for you?

**Comment by drzero42** [comment]
That is not a bad idea, to solve my immediate problem, thanks! :)
But perhaps a more general solution should also be considered? Again in my (perhaps narrow) use-case adding the autoscaling sub directly to `google_container_cluster` for the default-pool would also solve the issue, I guess. Maybe somebody else has a good idea for this? At the very least, maybe add some documentation that says to not use both `node_pool` sub in `google_container_cluster` and `google_container_node_pool` resources at the same time?

**Comment by drzero42** [comment]
Damn, that solution isn't actually entirely usable - I was too quick on the draw. My module outputs the endpoint, client_certificate, client_key and various others for the created cluster, so another module can use the Kubernetes provider to setup some configmaps and secrets. But when there are two different potential clusters, how can I connect the outputs to the right resources?

**Comment by danawillow** [comment]
> adding the autoscaling sub directly to google_container_cluster for the default-pool would also solve the issue

It would! I'm not opposed to it, but it's also not super high on my list of priorities.

> At the very least, maybe add some documentation that says to not use both node_pool sub in google_container_cluster and google_container_node_pool resources at the same time

Yeah, that's #475. Just haven't gotten around to it yet :-/

> But when there are two different potential clusters, how can I connect the outputs to the right resources?

Can you use the same var for another ternary? So something like:
```
output "cluster-info" {
  endpoint = "${var.create_highmem_np ? google_container_cluster.highmem.endpoint : google_container_cluster.lowmem.endpoint}"
}
```

**Comment by drzero42** [comment]
@danawillow Good suggestion, to use another ternary, but it does not seem that Terraform likes it. I have `google_container_cluster.cluster` and `google_container_cluster.worker_cluster` as my two potential cluster, and if I have `var.create_worker_pool = true`, it fails because `google_container_cluster.cluster` does not exist, and when it is false, it complains the other one does not exist.
```* module.container_cluster.output.endpoint: Resource 'google_container_cluster.cluster' not found for variable 'google_container_cluster.cluster.endpoint'```
When a resource has `count = 0` you are not allowed to reference it at all, even conditionally, it would seem. Any other suggestions would be awesome :)

**Comment by danawillow** [comment]
Hey @drzero42, I was just pointed to https://www.terraform.io/upgrade-guides/0-11.html#referencing-attributes-from-resources-with-count-0, which I think will work. Can you try this?
```
value = "${element(concat(google_container_cluster.cluster.*.id, google_container_cluster.worker_cluster.*.id), 0)}"
```

**Comment by drzero42** [comment]
@danawillow I had not read the upgrade guide well enough, because that part escaped me. It did not work entirely in that way - I ran into problems that I had to work around, but now, it works, so thank you so much - you rock! :smile:

For anybody else running into problems like this, I'll just summarize the issues and solutions I found. First I was using `google_container_cluster.clustername.master_auth.0.username` and the other attributes to do with access to the cluster (keys, certs etc), which the pattern did not like - seems that accessing list elements under a non-existing resource screws it up. I ended up using a local to extract the master_auth sub from the correct cluster resource and then using the lookup() function to access the attributes, since the syntax gods did not like any other way of doing it.

```
locals {
  master_auth = "${var.create_worker_pool ? element(concat(google_container_cluster.worker_cluster.*.master_auth, list("")), 0) : element(concat(google_container_cluster.cluster.*.master_auth, list("")), 0)}"
}

output "username" {
  value = "${lookup(local.master_auth[0], "username")}"
}

output "password" {
  value = "${lookup(local.master_auth[0], "password")}"
}
```

Next up, the pattern once again does not seem to work entirely as documented, so accessing attributes like the `.name` like this:
```
output "cluster_name" {
  value = "${var.create_worker_pool ? element(concat(google_container_cluster.worker_cluster.*.name, list("")), 0) : element(concat(google_container_cluster.cluster.*.name, list("")), 0)}"
}
```
gave this error:
```
module.container_cluster.output.cluster_name: strconv.ParseInt: parsing "${var.create_worker_pool ? 0 : 1 }": invalid syntax
```
Once again, I just moved it to a local, and then it worked as expected:
```
locals {
  cluster_name = "${var.create_worker_pool ? element(concat(google_container_cluster.worker_cluster.*.name, list("")), 0) : element(concat(google_container_cluster.cluster.*.name, list("")), 0)}"
}

output "cluster_name" {
  value = "${local.cluster_name}"
}
```

**Comment by danawillow** [comment]
Glad you got it working! I'll go ahead and close this.
