### ISSUE TITLE
Feature request: support for storage object change notifications via pubsub

### ISSUE THREAD

**Issue by stchris** [terraform-providers/terraform-provider-google#761]
Hi,

I would greatly appreciate if terraform was able to configure [pub/sub notifications](https://cloud.google.com/storage/docs/pubsub-notifications) for [Google Cloud storage object change notifications](https://cloud.google.com/storage/docs/reporting-changes). It does seem like the Go SDK supports the [necessary calls](https://godoc.org/cloud.google.com/go/storage#BucketHandle.AddNotification).

**Comment by amoiseiev** [comment]
@stchris I believe it was covered here: https://github.com/terraform-providers/terraform-provider-google/issues/971

Sorry for filing a duplicate, didn't notice it at first

**Comment by rosbo** [comment]
Fixed in #1033
