### ISSUE TITLE
Add provider-level `zone` attribute

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#772]
Right now our provider config supports Credentials, Project, and Region. Since someone may very well may want to have a default zone for creating resources in, I think it makes sense to add Zone to the list.

This also could potentially have good benefits for our tests- if one zone is low on resources generally, we would be able to change zones for the test suite without having to go into every single resource being tested and fix it there.

**Comment by ndmckinley** [comment]
I'll take this.
