### ISSUE TITLE
Use ResourceIamPolicy for google_project_iam_policy

### ISSUE THREAD

**Issue by rosbo** [terraform-providers/terraform-provider-google#777]
Once the deprecated `authoritative` boolean field is removed from the `google_project_iam_policy` resource. Reuse the common `ResourceIamPolicy`.

**Comment by rileykarson** [comment]
This is no longer breaking and no longer necessarily has to happen in `2.0.0`.

**Comment by paddycarver** [comment]
I think GoogleCloudPlatform/magic-modules#605 means this is done, right @rileykarson?

**Comment by rileykarson** [comment]
Nope - it wouldn't be a breaking change anymore, but we aren't using ResourceIamPolicy yet.

**Comment by paddycarver** [comment]
Can we still use ResourceIamPolicy if we're not using `getProject`?

**Comment by rileykarson** [comment]
Not yet - we would need to modify it to conditionally use `getProject`, which is worth doing eventually probably.
