### ISSUE TITLE
import google_bigquery_table crashes

### ISSUE THREAD

**Issue by mattes** [terraform-providers/terraform-provider-google#782]
### Terraform Version
```
terraform -v
Terraform v0.11.0
+ provider.aws v1.3.1
+ provider.google v1.2.0
+ provider.heroku v0.1.1
```

### Affected Resource(s)
- google_bigquery_table

### Terraform Configuration Files
```hcl
resource "google_bigquery_table" "csp_reports" {
  dataset_id = "${google_bigquery_dataset.csp.dataset_id}"
  table_id   = "reports"

  time_partitioning {
    type = "DAY"
  }

  schema = "${file("schema.json")}"

  lifecycle {
    ignore_changes = ["schema"]
  }
}
```

### Panic Output
https://gist.github.com/mattes/06d40238ea65070d565c0eb054c32836

### Expected Behavior
Import table.

### Actual Behavior
Panic and crash.

```
google_bigquery_table.csp_reports: Importing from ID "reports"...
google_bigquery_table.csp_reports: Import complete!
  Imported google_bigquery_table (ID: reports)
google_bigquery_table.csp_reports: Refreshing state... (ID: reports)
Error importing: 1 error(s) occurred:

* google_bigquery_table.csp_reports (import id: reports): 1 error(s) occurred:

* import google_bigquery_table.csp_reports result: reports: google_bigquery_table.csp_reports: unexpected EOF
```

### Steps to Reproduce
1. `terraform import google_bigquery_table.csp_reports reports`

**Comment by rosbo** [comment]
The you need to prefix the import id with the project name.

In your case the command to run would be:
```sh
terraform import google_bigquery_table.csp_reports NAME-OF-YOUR-PROJECT:reports
```

See documentation:
https://www.terraform.io/docs/providers/google/r/bigquery_table.html#import

I will make a fix to show a descriptive error message instead of crashing.
