### ISSUE TITLE
Getting instances details when creating an instance group

### ISSUE THREAD

**Issue by eilgin** [terraform-providers/terraform-provider-google#786]
### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance_group_manager
- google_compute_region_instance_group_manager

### Expected Behavior
Currently there's no way to retrieve the instance references (`self_link`) from this "mig" resources. However, the API allows us to get such values:

- [`instanceGroupManagers.listManagedInstances`](https://cloud.google.com/compute/docs/reference/latest/instanceGroupManagers/listManagedInstances)
- [`regionInstanceGroupManagers.listManagedInstances`](https://cloud.google.com/compute/docs/reference/latest/regionInstanceGroupManagers/listManagedInstances)

We could wait for the `currentAction` to be equal to `NONE` if we want to fetch more details (by querying the API using `instance.get`) or we could create dedicated data sources? Or both? I don't know what could be the best approach but fetching those values could be of great importance if we want to connect them to other resources such as Cloud DNS.

### Extra
This could be linked to https://github.com/terraform-providers/terraform-provider-google/issues/765

**Comment by danawillow** [comment]
A data source is probably the way to go for this

**Comment by paddycarver** [comment]
This is now possible:

* The [`instance_group`](https://www.terraform.io/docs/providers/google/r/compute_instance_group_manager.html#instance_group) property can be read for the self_link of the instance group being managed.
* The [`compute_instance_group`](https://www.terraform.io/docs/providers/google/d/google_compute_instance_group.html) data source can use that self_link to return a list of instance self_links.
* The `compute_instance` data source (#1906) can be used to get the information about each of those instances.

Going to close this out. If there's further work to be done, feel free to reply, and we can reopen this.
