### ISSUE TITLE
google_container_cluster.name causes syntaxerror when it contains a variable

### ISSUE THREAD

**Issue by AndreaGiardini** [terraform-providers/terraform-provider-google#792]
### Terraform Version
0.10.5
### Affected Resource(s)
- google_container_cluster

### Terraform Configuration Files
```hcl
variable "project" {
  type    = "string"
  default = "test-project"
}

resource "google_container_cluster" "main" {
  name             = "${var.project} a"
  zone             = "${var.zones[0]}"
  additional_zones = "${slice(var.zones, 1, length(var.zones) - 1)}"
 [...]
}
```

### Debug Output
`* google_container_cluster.main: "name" can only contain lowercase letters, numbers and hyphens
`

### Expected Behavior
It should work... the name contains only lowercase lettes, numbers and hyphens

### Actual Behavior
triggers syntaxerror

### Steps to Reproduce
 - Copy the previous example in a file
 - run `terraform plan`

**Comment by mrparkers** [comment]
I think it's failing because there's a space separating the variable and the letter 'a'.  Spaces aren't allowed in names for GKE clusters.

![image](https://user-images.githubusercontent.com/3793752/33323575-89a0c040-d412-11e7-8f40-1aacd5d882ef.png)

**Comment by AndreaGiardini** [comment]
Ow ... sorry for the noise
