### ISSUE TITLE
Rename all container resources to kubernetes

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#801]
https://cloudplatform.googleblog.com/2017/11/introducing-Certified-Kubernetes-and-Google-Kubernetes-Engine.html

Super-duper breaking change so holding off until v2.

**Comment by rosbo** [comment]
It sounds like a lot of pain for our users with very little gain. We could solve that by only changing the docs.

Side menu

* Kubernetes/Container engine
** google_container_cluster
** google_container_node_pool

Or something like that...

**Comment by danawillow** [comment]
Hold up, is it even possible to rename a resource @paddycarver? Migration fns only work per-resource, so they wouldn't let us put a new resource into the state. And if we just delete and rename it, then the diff would show users recreating all their resources.

**Comment by paddycarver** [comment]
Nothing in Terraform core allows a state migration, at the moment. I'd be game for just updating the docs. If it was important enough to Google (consistent branding, or whatever), we could _possibly_ find some way around this that could make it work, or we may be able to get the capability into a core Terraform release. But I'd say absent anyone _really, really_ wanting it, that's probably not worth it.
