### ISSUE TITLE
Removing username from master_auth in google_container_cluster recreates the cluster

### ISSUE THREAD

**Issue by rochdev** [terraform-providers/terraform-provider-google#803]
It is possible with the API to update the cluster to remove basic authentication.

See https://cloud.google.com/sdk/gcloud/reference/beta/container/clusters/update (--enable-basic-auth)

In Terraform the way to achieve this is to set an empty username/password combination. It should therefore be possible to go from using basic auth to not using auth by changing these values to blank without recreating the cluster.

**Comment by danawillow** [comment]
FYI to whoever implements this: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters/setMasterAuth.

**Comment by rileykarson** [comment]
Looks resolved. https://github.com/terraform-providers/terraform-provider-google/blob/17086fed4923f3995516178d12a255d74a614485/google/resource_container_cluster.go#L314
