### ISSUE TITLE
impossible condition: nil != nil in resourceKmsCryptoKeyRead

### ISSUE THREAD

**Issue by ubschmidt2** [terraform-providers/terraform-provider-google#813]
https://github.com/terraform-providers/terraform-provider-google/blob/41a952cdfacce5a08a550f059cb69ed662234fa8/google/resource_kms_crypto_key.go#L113

err is provably nil at this line, thus https://github.com/terraform-providers/terraform-provider-google/blob/41a952cdfacce5a08a550f059cb69ed662234fa8/google/resource_kms_crypto_key.go#L113-L115 has no effect.

I think that https://github.com/terraform-providers/terraform-provider-google/blob/41a952cdfacce5a08a550f059cb69ed662234fa8/google/resource_kms_crypto_key.go#L111-L115 could be removed, but not sure.

**Comment by paddycarver** [comment]
This looks to me like a different bug, to be honest. That error _seems_ to be trying to handle the case where there's an error reading info back from the API. I could be wrong, but that's what I'd assume it'd be trying to handle.

Of course, there _are_ no API calls in that method, which is mildly worrying, and looks like a bug to me. It feels like a GET request should be preceding that line. Of course, I'm unfamiliar with the API, so I could be wrong there.

**Comment by paddycarver** [comment]
It looks like @danawillow reviewed this resource, and probably has a bit more context. Dana, do you have bandwidth to add more context? If not, I'll dig into it myself and find out more.

**Comment by danawillow** [comment]
Weird, it had the GET call in an earlier version of it that I had reviewed and then I must have missed it when it got deleted. We should be reading it, and then setting rotation_period based on the response.

(I'm just going to take this moment to be smug and point out that an approach like #778 would have caught this)
