### ISSUE TITLE
`google_container_node_pool` has no `instance_group_urls` output

### ISSUE THREAD

**Issue by hawksight** [terraform-providers/terraform-provider-google#831]
When creating a multi zone cluster with an additional node pool (issue would multiple with further node pools), I attempt to put all the nodes into a backend service for a load balancer.
This is through the `google_container_cluster.cluster.instance_group_urls` output from the `google_container_cluster`. When you have a node pool as a separate resource in terraform, the output mentioned has only the URLs for the nodes in the default node pool. URLs for the node pool are not present. Also I cannot see a way to get the url as it is not present as an attribute of output for a [google_container_node_pool](https://www.terraform.io/docs/providers/google/r/container_node_pool.html).

### Terraform Version
```
Terraform v0.11.0
+ provider.google v1.2.0
```

Also updated to:
```
Terraform v0.11.1
+ provider.google v1.2.0
```
Issue not version specific, it is a lack of an output to use in other resources.

### Affected Resource(s)
- google_container_node_pool
- google_container_cluster
- google_compute_backend_service

### Terraform Configuration Files
```hcl
  backends       = {
    "0" = [
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[0]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[1]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[2]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[3]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[4]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[5]}" }
    ]
  }
```

Where:
```
output "K8S_INSTANCE_GROUP_URLS" {
  value       = "${google_container_cluster.cluster.instance_group_urls}"
  description = "URLs to the instance groups for all nodes"
}
```

### Expected Behavior
Either:
1) The `google_container_node_pool` should have a `instance_group_urls` attribute so it can be output.
Or
2) The `google_container_cluster.instance_group_urls` attribute inherits the urls for all node_pools associated with the cluster. 

### Actual Behavior
Just cannot seem to get the instance_group_url from anywhere.

Looking at getting the data from [here](https://www.terraform.io/docs/providers/google/d/google_compute_instance_group.html), the problem being that I don't know the name of the instance_groups because they are generated when the pool is created.

### Steps to Reproduce
1. Specify a container cluster with additional zones (two additional for 3 nodes).
2. Specify a nodepool via a separate `resource`, so 6 nodes.
3. Specify a backend service, I used [this](https://registry.terraform.io/modules/GoogleCloudPlatform/lb-http/google/1.0.4). And try to specify 6 backends as shown above.
4.`terraform apply` etc.

The var will only contain the 3 urls for the default node pool. Hence error on `K8S_INSTANCE_GROUP_URLS[3]` and above.

### Other
Wrote this up in a bit of a hurry. There may be some options to work around this:
- Specify the node pool within the container cluster resource.
- Find the name somehow of the instance groups and lookup the url.
- Expose the information as an attribute to ouput (preferred option)
- Inherit the urls for all nodes into the container cluster attribute.
- Build with only the default nodes and manually edit the load balancer to include others.

Or if anyone already has a workaround, I'd be all ears. Going to try a few ideas soon so will come back if I find anything.

**Comment by hawksight** [comment]
Just wanted to give a heads up that some kind person on slack pointed out the new release. I noticed the point `google_container_cluster` as a datasource and just wondered if this might fix the issue I was having here.

I checked if the instance group URLS were present on google end:
```bash
gcloud container clusters describe <cluster>
```

As they were, I decided, what the hell, lets see if that affects my load balancer.
I went from google provider version 1.1 to 1.5 (didn't realise I was behind so much).

Anyway, I ran:
```terraform
terraform refresh -var-file=europe.tfvars
terraform plan -var-file=europe.tfvars -out plan
```

And to my delight, it appears that no changes would be made, because I had already manually added the extra node pool to the load balancer.
Previously terraform would have modified the load balancer to remove them.

I was about to post back and say all was well, but I thought... best try this first to check. So now my code looks like the following (as desired):
```terraform-hcl
  backends       = {
    "0" = [
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[0]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[1]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[2]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[3]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[4]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[5]}" }
    ]
  }
```

But when applying my build which is VPC, subnet, Cluster + Node Pool , Load balancer I still get an error creating the backend:
```
module.cluster.google_container_node_pool.pools: Still creating... (3m0s elapsed)
module.cluster.google_container_node_pool.pools: Creation complete after 3m4s (ID: us-central1-a/k8s-dev/dev-np-1)

Error: Error applying plan:

1 error(s) occurred:

* module.lb-http.var.backends: index 3 out of range for list module.cluster.K8S_INSTANCE_GROUP_URLS (max 3) in:

${module.cluster.K8S_INSTANCE_GROUP_URLS[3]}
```

I think that the Instance group URLs for the node pool are not present immediately, because they have just finished creating.
By the time I have checked with gcloud that the instances urls are there, planned and applied the terraform code again, it does work.

On that basis, im either going to try and sleep or query to see the length of the returned data (from the container cluster data source perhaps) matched the expected number of nodes.

Unless anyone has a better idea of how I can refactor that module code so I don't have to specify all the backends manually?

**Comment by hawksight** [comment]
For anyone struggling with the same issue - managed to work around this now by using the following:
```hcl
data "google_container_cluster" "information" {
  name = "${google_container_cluster.cluster.name}"
  zone = "${google_container_cluster.cluster.zone}"

  depends_on = ["google_container_node_pool.pools"]
}
```

This waits for node pool(s) to be created and executes before the load balancer module. This is then  passed out of my k8s module as an output:
```hcl
output "K8S_INSTANCE_GROUP_URLS" {
  value       = "${data.google_container_cluster.information.instance_group_urls}"
  description = "URLs to the instance groups for all nodes"
}
```

Load balancer module reads this var now. I still have to manually specify the backends ie.
```hcl
  backends       = {
    "0" = [
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[0]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[1]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[2]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[3]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[4]}" },
      { group = "${module.cluster.K8S_INSTANCE_GROUP_URLS[5]}" }
    ]
  }
```

But at least I know that all instance_urls will be there and it won't bomb out mid way through build as it couldn't the 4th/ 5th / 6th instance group.

Although be wary of deletion - I am encountering [this](https://github.com/terraform-providers/terraform-provider-google/issues/1000) issue when trying to take down the infrastructure.

**Comment by danawillow** [comment]
Thanks for the detailed writeup, @hawksight! An alternative way to solve this would be to have the output depend on the node pools- that should get rid of the need for the data source.

Aside from that, anything else regarding this issue in particular that needs to be looked at?

**Comment by hawksight** [comment]
thanks @danawillow for the tip, I didn't realise an output could be dependant on a resource. That probably would have helped. That also explains why on the first run, there wold only ever be the default instance groups, but second run would show the node pool as well.

Ok so between the the new data resource in 1.5 and the `depends_on` solution, I think the should cover my initial request. Even though the `google_container_node_pool` resource doesn't have the output, the information is definitely available elsewhere. Please feel free to close.

**Comment by danawillow** [comment]
Great, happy to help!

**Comment by hawksight** [comment]
Note that node_pools now output instance_group_urls as of 1.8 plugin, see [here](https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#180-march-19-2018)

PR #1207 for reference.
