### ISSUE TITLE
Support For GKE federation 

### ISSUE THREAD

**Issue by Ronwebb55** [terraform-providers/terraform-provider-google#841]
Hi there,

### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
google_container_cluster

I would like  support for GKE federation.

**Comment by danisla** [comment]
Checkout k8s-multicluster-ingress (kubemci). This will let you federate ingress across clusters in multiple regions. A more usable approach to federation IMO. 

https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress

**Comment by Ronwebb55** [comment]
Thanks @danisla I'm looking for an approach with out the use of YAML files my team has created a kubernetes deployment resource which with create a deployment in kubernetes. But maybe I'm in the wrong provider I should be asking the kubernetes provider for this resource instead of terraform-provider-google.

**Comment by danisla** [comment]
@Ronwebb55, yes I would look to the [terraform-provider-kubernetes](https://github.com/terraform-providers/terraform-provider-kubernetes) for your use case. The Google provider is used to provision a new GKE cluster, but not necessarily the K8S resources that run inside it.
