### ISSUE TITLE
Add update support for routing mode in compute network.

### ISSUE THREAD

**Issue by rosbo** [terraform-providers/terraform-provider-google#847]
The `routing_mode` field in the `google_compute_network` can be updated using the Google Cloud API but Terraform doesn't support it.

**Comment by mrparkers** [comment]
`description` can also be updated.

**Comment by rosbo** [comment]
`description` actually can't be updated: 
```sh
Invalid value for field 'resource.description': 'Bar'. Updating this field is not supported.
```

**Comment by mrparkers** [comment]
Oops, you're right.  I thought I saw that it could be updated in the UI, but I just checked, and you can't.
