### ISSUE TITLE
delete timeout is too short

### ISSUE THREAD

**Issue by glehmann** [terraform-providers/terraform-provider-google#852]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.11.0

### Affected Resource(s)
at least, but may happen on other resources:
- google_compute_instance

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
```Error applying plan:

1 error(s) occurred:

* google_compute_instance.main: Error waiting for instance to delete: timeout while waiting for state to become 'DONE' (last state: 'RUNNING', timeout: 4m0s)

```

### Expected Behavior
terraform should wait long enough at destruction time

### Actual Behavior
it exited before the deletion completion, and leaved a terraform.tfstate file not consistent with the gce state

### Steps to Reproduce
Hard to do unfortunately — I guess it depends a lot on the gce load

### Proposed fix
I'm quite sure I'm missing a lot of side effects, but this could be a simple fix for this issue:

```
diff --git a/google/compute_operation.go b/google/compute_operation.go
index 52c64a7..24cefba 100644
--- a/google/compute_operation.go
+++ b/google/compute_operation.go
@@ -66,7 +66,7 @@ func (e ComputeOperationError) Error() string {
 }
 
 func computeOperationWait(client *compute.Service, op *compute.Operation, project, activity string) error {
-       return computeOperationWaitTime(client, op, project, activity, 4)
+       return computeOperationWaitTime(client, op, project, activity, 10)
 }
 
 func computeOperationWaitTime(client *compute.Service, op *compute.Operation, project, activity string, timeoutMin int) error {
```

**Comment by rosbo** [comment]
Note to implementer:
- Bump the default timeout 
- Support Terraform Configurable Timeouts like we did here: #717
