### ISSUE TITLE
Error when trying to update network_policy on google_container_cluster

### ISSUE THREAD

**Issue by rochdev** [terraform-providers/terraform-provider-google#860]
When trying to enable network policy support on existing clusters, the following error is returned:

```
* google_container_cluster.cluster: googleapi: Error 400: the network policy addon must be enabled before updating the nodes., badRequest
```

The change we have made to the cluster resource was to add the following block:

```yaml
network_policy {
  enabled  = true
  provider = "CALICO"
}
```

Adding the policy manually with the CLI and re-running `terraform apply` works. It seems the `network_policy` block attempts to enable network policy on the cluster without first adding the corresponding addon.

See https://cloud.google.com/sdk/gcloud/reference/beta/container/clusters/update#--enable-network-policy

terraform 0.11.1
terraform-provider-google 1.3.0

**Comment by Stono** [comment]
+1 to this problem, I just hit it too

**Comment by danawillow** [comment]
Pretty sure the answer for this is just to add support for the `networkPolicyConfig` addon: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters#AddonsConfig.

**Comment by f-f** [comment]
+1 for this, I also just hit it.
