### ISSUE TITLE
Feature request: google_dataproc_cluster resource support for internal ip address

### ISSUE THREAD

**Issue by rameshvenk** [terraform-providers/terraform-provider-google#864]
Hi
I noticed in a recent gcloud client update that Dataproc has support for private ip addresses. This is very critical since our security team prefers to provision VMs in our own private subnetwork at GCP. However the `google_dataproc_cluster`  resource does not have this per this [documentation](https://www.terraform.io/docs/providers/google/r/dataproc_cluster.html) link.

**Comment by danawillow** [comment]
Fixed in #837.

**Comment by rameshvenk** [comment]
Thank you so much for such a quick fix!
