### ISSUE TITLE
Feature Request: kms secret in data

### ISSUE THREAD

**Issue by wyardley** [terraform-providers/terraform-provider-google#867]
Would it be possible to add a kms_secret data type for gcp, similar to the one for AWS?

https://www.terraform.io/docs/providers/aws/d/kms_secret.html
This allows referencing KMS encrypted secrets (for example, for easy externalization of a password or other secret).

**Comment by rosbo** [comment]
There is a PR for it at #741

**Comment by wyardley** [comment]
@rosbo Thanks! Sorry for missing that.

**Comment by rosbo** [comment]
No worries @wyardley.

At this moment, we are reluctant to add this feature because we think it gives a false sense of security and encourages a unsafe pattern. Please chime in PR #741 and tell us about your use case and we might accept the PR if we see compelling arguments.
