### ISSUE TITLE
Add support for private visibility to DNS managed zones

### ISSUE THREAD

**Issue by dolvany** [terraform-providers/terraform-provider-google#870]
Please add support for cloud dns private zones.
https://cloud.google.com/blog/products/networking/introducing-private-dns-zones-resolve-to-keep-internal-networks-concealed

### Terraform Version
Terraform v0.11.1
+ provider.google v1.4.0

### Affected Resource(s)
- google_dns_managed_zone

**Comment by rosbo** [comment]
For reference: https://cloud.google.com/compute/docs/internal-dns

**Comment by rosbo** [comment]
Hi Dennis,

Which feature exactly are you referring to?

Thank you

**Comment by dolvany** [comment]
Cloud DNS zones can now be public or private.
<img width="79" alt="screen shot 2017-12-23 at 10 45 15 am" src="https://user-images.githubusercontent.com/10111600/34321535-77f6d300-e7ce-11e7-88a9-608780f6f32d.png">

**Comment by rosbo** [comment]
Hi,

This feature is currently in alpha. Our policy is to wait until it reaches the BETA stage before adding Terraform support.

**Comment by bgeesaman** [comment]
Is any work on this feature already underway despite being in alpha?  I'm asking because an alpha user may need to develop this before it goes beta and they don't want to duplicate work.

**Comment by alwaysastudent** [comment]
This is GA beta now. Would be useful if we get this in.

**Comment by shinmyung0** [comment]
+1 for this feature, we are waiting on this as well

**Comment by bluemalkin** [comment]
Is there any ETA on this please?

We really need it, thanks!

**Comment by bluemalkin** [comment]
Looks like we have a PR !

https://github.com/GoogleCloudPlatform/magic-modules/pull/981

**Comment by rileykarson** [comment]
This is merged and will be available in `2.1.0`, which we expect to release within the next 2 weeks.

We've added a caveat around update behaviour pre-`0.12`, but didn't feel that we should block the feature on the issue as it's not something we can solve in the provider.

Thanks all for you patience, and thanks especially to @drebes for contributing the feature!
