### ISSUE TITLE
min_cpu_platform for instance templates not documented

### ISSUE THREAD

**Issue by jayed** [terraform-providers/terraform-provider-google#876]
### Terraform Version
Terraform v0.11.1                                                                                                                 
+ provider.digitalocean v0.1.2                                                                                                    
+ provider.google v1.3.0                                                                                                          
+ provider.local v1.0.0                                                                                                           
+ provider.template v1.0.0                                                                                                        
+ provider.vault v1.0.0 

### Expected Behavior
The [docs](https://www.terraform.io/docs/providers/google/r/compute_instance_template.html) for google compute instance templates doesn't mention min_cpu_platform. It is, however, mentioned in the google compute instance docs.

### Actual Behavior
It seems to be provided by the [source code](https://github.com/terraform-providers/terraform-provider-google/blob/12baa8766b80f750177020934531b1d89bd047bf/google/resource_compute_instance_template.go#L387)

**Comment by rosbo** [comment]
It is a miss on my part. The feature is supported. I will open a PR to add the documentation. Thanks for flagging.
