### ISSUE TITLE
Support for creating a GKE container cluster with a service-account 

### ISSUE THREAD

**Issue by wmuizelaar** [terraform-providers/terraform-provider-google#894]
Hi there,

As can be read in https://cloud.google.com/solutions/prep-kubernetes-engine-for-prod - I would like the option to specify a specific service-account when creating a cluster. As the document quotes 
```Use a custom service account that has restricted permissions, however, because the default has editor access to the entire project.

To use a different service account for your clusters, provide the service account at cluster or node-pool creation by using the --service-account flag. For example, to use the gke-sa service account in the project my-project:

gcloud container clusters create west --service-account \
  gke-sa@my-project.google.com.iam.gserviceaccount.com
```

Would it be possible to add that as a feature in the google provider for GKE as well?

Thanks,
Wietse

**Comment by iniinikoski** [comment]
Hi,

you can do this in node_pool, see:

https://www.terraform.io/docs/providers/google/r/container_cluster.html#service_account

This should work for you...?


Yours,

Iiro

**Comment by wmuizelaar** [comment]
Yes, it does. Sorry, I overlooked it...
