### ISSUE TITLE
Providing GCP URL paths allows resources to be created but refresh needlessly

### ISSUE THREAD

**Issue by spacez320** [terraform-providers/terraform-provider-google#897]
It appears that you can successfully create resources using attribute values that just provide an API path (example: `projects/wf-gcp-gb-vpchost-prod/global/networks/wf-gcp-gb-vpchost-prod-network`) but these don't persist -- Terraform tries to constantly recreate them on every plan/apply unless you provide the full path (example: `https://www.googleapis.com/compute/v1/projects/wf-gcp-gb-vpchost-prod/global/networks/wf-gcp-gb-vpchost-prod-network`).

### Terraform Version

```
Terraform v0.11.1
```

### Affected Resource(s)

- google_compute_forwarding_rule
- google_compute_instance_group
- probably others

### Terraform Configuration Files

```hcl
# Causes a resource refresh even if the resource is already present and not changing:

resource "google_compute_forwarding_rule" "internal" {                          
  count = "${var.internal_only ? "1" : "0"}"                    
                                                                                
  backend_service = "${google_compute_region_backend_service.internal.self_link}"
  load_balancing_scheme = "${local.scheme}"                                     
  name = "${local.base_name}-forwarder"                        
  network = "projects/wf-gcp-gb-vpchost-prod/global/networks/wf-gcp-gb-vpchost-prod-network"
  ports = ["${var.service_port}"]                               
  project = "${var.project}"                                      
  region = "${var.region}"                                       
  subnetwork = "projects/wf-gcp-gb-vpchost-prod/regions/${var.region}/subnetworks/${var.network}"
}
```

```hcl
# Does not resource refresh after creation, as expected:

resource "google_compute_forwarding_rule" "internal" {                          
  count = "${var.internal_only ? "1" : "0"}"                    
                                                                                
  backend_service = "${google_compute_region_backend_service.internal.self_link}"
  load_balancing_scheme = "${local.scheme}"                                     
  name = "${local.base_name}-forwarder"                        
  network = "https://www.googleapis.com/compute/v1/projects/wf-gcp-gb-vpchost-prod/global/networks/wf-gcp-gb-vpchost-prod-network"
  ports = ["${var.service_port}"]                               
  project = "${var.project}"                                      
  region = "${var.region}"                                       
  subnetwork = "https://www.googleapis.com/compute/v1/projects/wf-gcp-gb-vpchost-prod/regions/${var.region}/subnetworks/${var.network}"
}
```

### Debug Output

https://gist.github.com/spacez320/b5cebc3c5f8adfb0c9c3f201f8d4c2a8

### Expected Behavior

Nothing was changing about the sources, so it shouldn't have appeared in the plan output.

### Actual Behavior

The resource refreshes, and appears to try to remove part of the full URL to match local configuration.

### Steps to Reproduce

1. Create a resource that has an attribute requiring an API resource URL.
2. Provide a URL API path, removing `https://www.googleapis.com/compute/v1`.
3. `terraform apply`, observe the resource is successfully created.
4. `terraform plan`, observe that Terraform wants to destory/recreate the resource.

Adding back the URL API path to the attribute causes this behavior to cease, although it seems like this is a bug since you can create the resource with the more succinct URL path.

**Comment by rosbo** [comment]
Hi,

This issue was fixed in #487. 

Make sure to update the Google Terraform provider to the latest version.

Thank you.

Feel free to reopen if you are still experiencing this issue after updating to the latest version.
