### ISSUE TITLE
preemptible instances in the google_container_node_pool

### ISSUE THREAD

**Issue by Stono** [terraform-providers/terraform-provider-google#919]
Hi there,
As you can see, [you can do preemptible](https://www.terraform.io/docs/providers/google/r/container_cluster.html#preemptible) as part of node configuration on the google_container_cluster resource, however if you use [node pool](https://www.terraform.io/docs/providers/google/r/container_cluster.html#node_pool) it says invalid or unknown key.

I presume that's because the items in the array of node_pool need to be [container_node_pool](https://www.terraform.io/docs/providers/google/r/container_node_pool.html) resources, but I don't understand why preemptible wouldn't be an option there?

This is kind of important for us as we have a variety of different pools, some preemptible, others not.

**Comment by davidquarles** [comment]
@Stono you should be able to specify preemptibility under `google_container_node_pool.node_config.preemptible`

**Comment by danawillow** [comment]
What @davidquarles said :)

Closing this, but let me know if it still doesn't work and I'll reopen.
