### ISSUE TITLE
Using alias for google provider at root module does not pass region attribute to child module

### ISSUE THREAD

**Issue by dhawal55** [terraform-providers/terraform-provider-google#920]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
v0.11

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance
- google_storage_bucket

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

```
provider "google" {
  region = "us-east1"
  alias  = "use1"
}

provider "google" {
  region = "us-west1"
  alias  = "usw1"
}

module "example-use1" {
  source = "./example"

  providers = {
    "google" = "google.use1"
  }
}

module "example-usw1" {
  source = "./example"

  providers = {
    "google" = "google.usw1"
  }
}
```

### Expected Behavior
Any google provider resources in the module ./example will use the us-east1 provider configuration for module.example-use1 and the us-west1 provider configuration for module.example-usw1.

### Actual Behavior
It prompts for region:
```
provider.google.region
  Enter a value:
```

### Steps to Reproduce
Use the above config and run `terraform plan`

**Comment by danawillow** [comment]
I think this is an issue with Terraform core, not the google provider. Can you file an issue at github.com/hashicorp/terraform instead? I'm going to go ahead and close this one since I don't think there's anything we can do in this repo to help.
