### ISSUE TITLE
Request: Add google_logging_organization_sink Stackdriver logging resource

### ISSUE THREAD

**Issue by qvallance** [terraform-providers/terraform-provider-google#922]
Please add a `google_logging_organization_sink` Stackdriver logging resource, to manage organization-level logging sinks.  There are already resources for project, folder, and billingAccount, with organization the only missing resource.

**Comment by qvallance** [comment]
I went ahead and created a new resource for this, based on the folders one.  I'll submit a PR for it shortly.

**Comment by paddycarver** [comment]
It looks like the PR for this was merged, so I'm going to close the issue. Thanks for contributing to the provider!
