### ISSUE TITLE
google_compute_instance: Subnetwork name expanded with wrong region

### ISSUE THREAD

**Issue by waldiTM** [terraform-providers/terraform-provider-google#926]
### Terraform Version
```
Terraform v0.11.1
+ provider.google v1.4.0
```

### Affected Resource(s)
- google_compute_instance
### Terraform Configuration Files
```hcl
resource "google_compute_instance" "default" {
  name = "test"
  zone = "asia-northeast1-b"
  machine_type = "g1-small"

  boot_disk {
    initialize_params {
      image = "${var.instance_image}"
      type = "pd-ssd"
    }
  }

  network_interface {
    subnetwork = "mirror"
  }

  lifecycle {
    ignore_changes = [ "machine_type" ]
  }
}

provider "google" {
  project = "${var.provider_project}"
  region = "us-central1"
}
```

### Debug Output
https://gist.github.com/waldiTM/3ef518510d7514b18f0e78405ee813ba

### Expected Behavior
Subnetwork is used in the correct region. It worked in the past, not sure when.

### Actual Behavior
According to the error, Terraform provides the full subnetwork URL in the wrong region, in the default region of the provider.

### Steps to Reproduce
1. `terraform apply`

**Comment by rosbo** [comment]
We changed the behavior to infers region from the zone in schema instead of the provider-level region.
