### ISSUE TITLE
Support AuditLogConfigs in Policy

### ISSUE THREAD

**Issue by uschen** [terraform-providers/terraform-provider-google#936]
Currently the `google_iam_policy` data source / object doesn't expose `AuditConfigs` which prevents 
enabling`DATA_READ` Audit Log mentioned in https://cloud.google.com/kms/docs/logging

**Comment by uschen** [comment]
wonder it is just expose AuditLog (https://godoc.org/google.golang.org/api/cloudresourcemanager/v1#AuditConfig) in  https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_iam_policy.go#L147

**Comment by saleh-sedighi-ck** [comment]
+1

**Comment by gkohen** [comment]
+1

**Comment by Farhie** [comment]
I would like to see support for this. I see this is labelled as an enhancement. @rosbo is this an enhancement? Enabling data access logs for all services is important for my current team and would argue it is likely a high priority for others.

https://cloud.google.com/logging/docs/audit/configure-data-access

**Comment by rosbo** [comment]
The `enhancement` tag simply means it will update existing resources. We use one of the three tags: `enhancement`, `new resource` or `new datasource`.

**Comment by Farhie** [comment]
Ah, my misunderstanding. Thanks for clearing that up. I should RTFM more 😎

**Comment by rileykarson** [comment]
This is present in `2.0.0`. https://www.terraform.io/docs/providers/google/d/google_iam_policy.html#audit_config
