### ISSUE TITLE
Documentation Incorrect for SQL Maintenance Day

### ISSUE THREAD

**Issue by breznik** [terraform-providers/terraform-provider-google#955]
### Affected Resource(s)
https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#day

Resource:
- google_sql_database_instance.settings.maintenance_window.day

### Expected Behavior
The documentation says Day of Week (1-7) starting on Monday with 1=Monday.

### Actual Behavior
1 is actually Sunday

### Steps to Reproduce
Pretty straightforward - just apply a maintenance_window setting. I tried with Day=6 for Saturday and in the Google Console it showed me the maintenance window was set to Fridays.

**Comment by rosbo** [comment]
Hi,

In Terraform, you need to set the maintenance window in UTC. The docs already mentions this "The maintenance window is specified in UTC time".

However, the Google Console shows the maintenance window in your timezone. The console prints out below the maintenance window field the timezone it is using. For me, I can see: "Hours shown in your local time zone ( UTC-8 )."
