### ISSUE TITLE
Request: add support for "accidental VM deletion" in "google_compute_instance"

### ISSUE THREAD

**Issue by iiro** [terraform-providers/terraform-provider-google#956]
Hi,

It could be great to get support for the "accidental VM deletion" for the "google_compute_instance" - now that the feature got into GA.

And thank you for an excellent provider! :)

**Comment by rosbo** [comment]
Additional link: https://cloud.google.com/compute/docs/instances/preventing-accidental-vm-deletion

**Comment by nickjacques** [comment]
I'm currently working on this; I have the create/update code for instance resources finished and am writing tests for it now. Expect to see a PR linked to this issue soon!

**Comment by nickjacques** [comment]
@danawillow not sure if it's allowable to set non-Googlers as assignees, but if that's not a problem, feel free to tag me!

**Comment by danawillow** [comment]
Looking forward to it! GitHub only allows setting maintainers as assignees so just claiming it in a comment like you did is about the best we can do now.

**Comment by nickjacques** [comment]
Right on! I'll try to knock out the tests today or tomorrow. I'll put up a WIP PR later this evening and xref this issue!
