### ISSUE TITLE
google_container_node_pool requires zone

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#980]
The zone required in `google_container_node_pool` when it's not required in a `node_pool` defined in `google_container_cluster`

This zone shouldn't matter, as the pool will follow clusters zones?

**Comment by ndmckinley** [comment]
This mirrors the structure of the request that needs to be made to create the `google_container_node_pool` - the path for that request is `POST https://container.googleapis.com/v1/projects/{projectId}/zones/{zone}/clusters/{clusterId}/nodePools`.  Basically, we need the zone to localize the cluster ID.  Does that make sense?  Reopen if you think I've got this wrong or this doesn't work for you.

https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters.nodePools/create

**Comment by matti** [comment]
@ndmckinley okay understood - I think this is a documentation issue then, the docs should mention this?

**Comment by ndmckinley** [comment]
Oh geez, they should!  I'm doing that.  :)
